### ISSUE TITLE
Whitelist Applications

### ISSUE THREAD

**Issue by CreamSlush** [InZidiuZ/op-framework-issue-tracker#1000]
**Name:**
Cream Slush#8990

**Summary:**
Whitelist Applications

**Reason:**
Alright, we obviously had whitelist applications before. It did not go in right direction. Our server is not a professional RP that needs a long drawn out application. It should of never been what it was. With the forums up now also, it should make a whitelist process easier to handle. All that should be needed before taking the application is linking your discord and steam to your forum account, then you can take your whitelist application. All the whitelist application should be is rule questions mainly. Maybe verify your birthday with what you put on the application and and what's linked to the forum account.
I really think this needs to be rethought and not just tossed to the side because we have a good player base. What's more important? Letting the server die off slowly due to all the hackers/rule breakers coming in? Or fix the issue now and keep the community we have and maybe continue to build it up. Myself and some others I have talked to are losing motivation to play due to the constant issues that arise daily from the server being public. Sure the server does seem fine player base currently, but I've started to see some people just apply to other servers and play on that server when they can't be bothered with Legacy. I feel like a whitelist application that isn't too hard to fill out will detour the shitlords coming to rule break/not reading rules and hackers when they can just go hack on a public server. While people who actually want to roleplay and start learning how to can fill out the simple application and be accepted into the server. Sure we still may get some, but the amount would be so so so much less than what it is currently. It will actually give staff room to breath and enjoy the server.

**Comment by iGreatWhite** [comment]
This isn’t really a framework related suggestion. I feel like this would be better put for on the forums or discord personally.

**Comment by z-Lunar** [comment]
> This isn’t really a framework related suggestion. I feel like this would be better put for on the forums or discord personally.

theres also no place on forums for this.

**Comment by CreamSlush** [comment]
> This isn’t really a framework related suggestion. I feel like this would be better put for on the forums or discord personally.

I mean sure, but it's labeled as a suggestion. It actually has been absolute hell on the server for the past 2 hours due to hackers. But it's been a constant issue ever since whitelist was removed.

**Comment by mavroses** [comment]
Whitelisting should 100% come back, there is barely any RP happening anymore.

Default Danny's ruining the server more and more each day and people are leaving to play and do other things because it's just not fun anymore.

**Comment by InZidiuZ** [comment]
Hey,

Please refrain from using the issue tracker to discuss community-related matters, as this framework is shared with multiple other communities as well. Redirect such discussions to the discord and forums if available.

**InZidiuZ**
*OP-FW Developer*
