### ISSUE TITLE
[game/inventory] Two handed guns not appearing on back

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/op-framework-issue-tracker#1001]
**Reporter:**
Livius#1235
https://steamcommunity.com/id/Nemmesys/
**Summary:**
Two Handed guns won't show up on the back sometimes , and if they show up and you do something as eating they disappear again 

**Steps to Reproduce:**
Get the gun and put it in the inventory

**Expected Results:**
I was expecting to see the gun on the back 

**Actual Results:**
the gun is not showing but you can use it and it is in your inventory

## Additional Information

**Screenshots:**
https://imgur.com/a/s7PQ8zk

**Game Resolution:**
1920x1080

**Player Data:**
Char ID : 239- Job Data:  Vehicle Dealership , Premium Deluxe Motorsport, Senior Salesman

**Server:**
Main

**Notes:**
I've noticed that the sometimes the gun appears back , for example after doing an emote but if you drink or eat something it disappears again.

**Comment by DaxterPancake** [comment]
#1008 Also posted a bug report on this issue, includes a photo.

**Comment by InZidiuZ** [comment]
When this happens, does it happen at a constant? Is it immediate? Do they appear first then disappear? Does it happen for *a lot* of people or just a few repeatedly? Was this on regular OneSync or the infinity mode? Is it still happening?

**Comment by InZidiuZ** [comment]
This is should now be resolved.
