### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by varunayyod** [InZidiuZ/op-framework-issue-tracker#1002]
**Reporter:**
MrSomething#8286
**Summary:**
Not able to access trunks of any vehicles in the city. Tried whole restart game also and still doesn't work. Need to fix this issue. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Hi,

Closing this.
Please re-make this issue with all areas filled in to the best of your ability.
If you're from the Indian Subdivison this issue has already been made, refer to here #990 

Cheers,
**Daxter.
Project Manager.**
