### ISSUE TITLE
[jobs/police] Fake ID's

### ISSUE THREAD

**Issue by Jamerson1793** [InZidiuZ/op-framework-issue-tracker#1003]
**Name:**
Who is suggesting this? Please include discord name. Jamerson#0001

**Summary:**
Write a short summary of what your suggestion is about. Make it so Police can go to Vinewood PD or MRPD to create a fake Id.

**Reason:**
Why would your suggestion be a good addition to Legacy? This would be a good suggestion to legacy because I don’t really know how the detectives go undercover but I’m assuming they don’t even use ID’s this would further enhance UC Work in Roleplay and could help someone sustain their identity.

**Comment by DaxterPancake** [comment]
Alternatively. 

Allow state to make ID's. 
Have police contact state to have an ID made.

**Comment by Jamerson1793** [comment]
@DaxterPancake Yah that would work it’s just if pd wanted to go on a UC operation and it just popped up but it was serious and they needed to do it again there and then they would have to wait for a state worker. But also Pd could just ask for like 20 ID’s to be made for undercover officers.

**Comment by Jamerson1793** [comment]
*Do it there and then
Stupid Phone
