### ISSUE TITLE
[subdivision/india] Unable to put someone in trunk

### ISSUE THREAD

**Issue by lucifer019** [InZidiuZ/op-framework-issue-tracker#1004]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Lucifer19#0105

**Summary:**
Write a short summary of what you're experiencing. 
We are not able to put anyone in trunk including dead bodies, we used to carry them and get inside car but now that feature is also not working so its impossible to get a dead body to hospital or transport a hostage.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
Trunk feature working fine.

**Actual Results:**
What are the actual results?
Its not working.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India normal server
**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
I'm assuming you're opening the trunk, then carrying someone to the back and then using F to put them inside?

**Comment by InZidiuZ** [comment]
Closing due to no response. Also please follow the template properly.
