### ISSUE TITLE
[subdivison/india] Sirens not working correctly

### ISSUE THREAD

**Issue by lucifer019** [InZidiuZ/op-framework-issue-tracker#1005]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Lucifer19#0105
**Summary:**
Write a short summary of what you're experiencing.
Sirens of police cars not working everytime, the chances of it working properly are 20% 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
Sirens working properly 
**Actual Results:**
What are the actual results?
Sirens Not working properly 
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India normal server
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This seems very odd & have no idea what to do with this very much lacking report. If it's still an issue, create another report properly filled out.

**InZidiuZ**
*OP-FW Developer*
