### ISSUE TITLE
[jobs/police] Panic button for police when downed

### ISSUE THREAD

**Issue by MezmerPlayz** [InZidiuZ/op-framework-issue-tracker#1007]
**Name:**
@MezmerPlayz#1001

**Summary:**
My suggestion is about adding panic button for officers of the server.

**Reason:**
Because whenever any officer goes down he have to say 10-14 in the dispatch but if other officers are busy in a situation then I dont think so that any officer notice that his officer is down, So adding panic button would be a great idea and very helpful for officers.

**Comment by mavroses** [comment]
I think this is a much-needed addition, there would need to be specified rules to when you can press it though, I don't think it should be automatic instantly when a cop dies since that's pretty unrealistic.

**Comment by twooot** [comment]
This is done
