### ISSUE TITLE
Gun back bug

### ISSUE THREAD

**Issue by MezmerPlayz** [InZidiuZ/op-framework-issue-tracker#1008]
**Reporter:**
@MezmerPlayz#1001

**Summary:**
While having any rifle or smg in our inventory we are not able to see our guns on our back hanging.

**Actual Results:**
It is not giving that feel to the RP as bcoz we dont know that our rifles come from where as its invisible on our back.

**Screenshots:**
![20200427140944_1](https://user-images.githubusercontent.com/63736358/80351985-d3e6ae00-8890-11ea-8346-ae8660e63919.jpg)
![20200427140949_1](https://user-images.githubusercontent.com/63736358/80351990-d5b07180-8890-11ea-963f-79e4be867a2c.jpg)

**Game Resolution:**
1920x1080

**Server:**
Legacy Roleplay India WL

**Comment by Livius99** [comment]
I already reported this 5 days ago , I hope it gets fixed asap

**Comment by DaxterPancake** [comment]
Closing due to already having this bug reported, referenced this issue in other bug report.

Cheers,
**Daxter.
Project Manager.**
