### ISSUE TITLE
AR INDUSTRY-PLEASE DON'T MIX PD AND S.W.A.T CHARACTER IN ONE. MAKE DIFFERENT CHARACTER OF PD AND S.W.A.T. Example GANESH GAITONDA 1 CHARACTER IS OF PD THEN MAKE HIM TRAIN S.W.A.T IN 2 CHARACTER, PLEASE MAKE DIFFERENT WEAPON INVENTORY ONLY FOR S.W.A.T PERSON. IF YOU APPOINTING S.W.A.T PERSON THEN TELL TIM TO MAKE A CHARACTER  FOR PD ALSO SO THAT HE/SHE CAN CHANGE THE CHARACTER IS NEEDED.

### ISSUE THREAD

**Issue by ARINDUSTRY** [InZidiuZ/op-framework-issue-tracker#1009]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by DaxterPancake** [comment]
Hi.

Closing this due to not following the template.
Please remake this correctly.

Thanks,
**Daxter
Project Manager.**
