### ISSUE TITLE
[BUG] Tracker of Police and EMS is not working properly

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/op-framework-issue-tracker#1010]
**Reporter:**
DC#4176

**Summary:**
Incorrect Movement of the Tracker of police and EMS.

**Steps to Reproduce:**
Tracker is very benificial for EMS and POLICE,Many thing depends on it so it should be fixed soon.

**Expected Results:**
I think it will be fixed soon.
## Additional Information
Incorrect Movement of the Tracker of police and EMS in Map.
**Screenshot:**
![Screenshot (369)](https://user-images.githubusercontent.com/64458489/80492255-61a1c680-8981-11ea-8439-79e3c8fa5b1c.png)
**Video:** Please Follow the EMS(pink)TRACKER in the MAP.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/64458489/80492761-1a680580-8982-11ea-87a3-cef4683013cf.gif)

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
 Bangladesh

**Notes:**
I'm a EMS in LEGACY sub division Bangladesh,i was facing such problems mentioned above,and i think it should be fixed soon.Thank You.

**Comment by Splash004** [comment]
Yep. I think the trackers needs to be fixed ASAP. Its a really important thing for the EMS/Police. These bugs should be fixed for better RP

**Comment by BmFarhan** [comment]
Its a very important thing for both EMS and POLICE , Can't track the tracker while in a situation , that's we are facing so much problem with this .

**Comment by DC0402** [comment]
No Responce

**Comment by DaxterPancake** [comment]
The server developer will respond when he has time. 

Be patient.

Cheers.

**Comment by InZidiuZ** [comment]
Closing in favor of #1028.
