### ISSUE TITLE
/repair on ems bike explorer not working

### ISSUE THREAD

**Issue by Guardian3-1** [InZidiuZ/op-framework-issue-tracker#1011]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GuArDiAn#0031
**Summary:**
Write a short summary of what you're experiencing.
We cant repair ford explorer or bmw 120 using /repair we get the only can repair ems/pd vehicles
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take out bmw bike with ems character do /repair repeat the same process with ford explorer.
**Expected Results:**
What are the expected results?
Both vehicles should be repaired like the ambulances repair
**Actual Results:**
What are the actual results?
we get the error only emergency vehicles can be repaired
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://imgur.com/a/rKWzyTg
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://imgur.com/a/dgYMnXI
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
IndiaWL
**Notes:**
For anything else noteworthy.

**Comment by z-Lunar** [comment]
Hello, this is to be posted in the assets issue tracker, but this is also known & being looked into. thank you for reporting this.

**Comment by DaxterPancake** [comment]
This issue should be fixed in the next update.

Thanks,
**Daxter.
Project Manager.**
