### ISSUE TITLE
[jobs/mechanic] Window & Wheel repairs not working

### ISSUE THREAD

**Issue by Girdeux2k** [InZidiuZ/op-framework-issue-tracker#1012]
**Reporter:**
Girdeux#9675

**Summary:**
When repairing customers vehicles at the Lost MC Mechanic shop Glass and Rubber repairs don't seem to be taking.  Also cosmetics when doing the body don't fix sometimes.

**Steps to Reproduce:**
Create a pane of glass or a tire.  Take it to the customers vehicle and install it.  Repair body work.

**Expected Results:**
The car shows that the new glass or the tire has been replaced and the customer can drive away happy.  The car is fixed and there are no cosmetic issues either.

**Actual Results:**
The glass is repaired but falls out 30 seconds later or doesn't repair at all.  The tires don't show up as repaired.  Sometimes they can place the car back into the garage and the fix will show as done but there is no way to know without the vehicle changing state at the shop.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1680x1050

**Player Data:**
Dane Wilson | 1146   (sorry not in the city currently)

**Server:**
Main 

**Notes:**
Sometimes the cars will be fixed and we can't see it.  Other times we've used 4 tires to repair a tire before it showed up.  Didn't start doing this until the 1sync started being used.

**Comment by Girdeux2k** [comment]
Seems that the city is trying to force the state of the car in everyone's eyes.  So if I can see it fully repaired but if someone sees it as broken, the city forces the windows to fall out and make it match up on all ends.

**Comment by InZidiuZ** [comment]
After looking into this I found at least 2 issues which could and probably would've caused this issue. Once resolved & tested locally I was unable to make it fail again, though I am not saying this is 100% resolved as it's already an iffy area and I think I've already claimed to have "fixed" it now a dozen times... :p

Closing for now. If there are other issues after 2.5, please create a new issue.
