### ISSUE TITLE
[dependency/easyadmin]

### ISSUE THREAD

**Issue by Guardian3-1** [InZidiuZ/op-framework-issue-tracker#1013]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GuArDiAn#0031
**Summary:**
Write a short summary of what you're experiencing.
SO some of the issues we are facing are : 1) when we spectate someone it happens randomly but we get teleported when we end spectating or press "E" to the location the player we started spectating or to a road but most of the time on the location or right infront of the player. 2) When we try to do teleport to player the admin panel gets bugged and we have to quit fivem. This issue is faced by a number of staff members/ ingame admins makes it hard to spectate and instantly remove a player breaking any of our rules.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
do /admin spectate a player 1-3 times and you get teleported to the location of the player or the location where you started spectating them.
**Expected Results:**
What are the expected results?
Expected results are that we we shouldn't get teleported to the player when ending spectate. Secondly that our teleport to player can be used by admins when needed in situation.
**Actual Results:**
What are the actual results?
We get teleported to the location of the player we spectate and when we press teleport to player the admin panel bugs out and is inaccessible and have to restart fivem. 
## Additional Information
Video Proof: https://youtu.be/OOsd68gzLoY
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://imgur.com/a/52t7BD1
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India Normal Servers
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has now been resolved.
