### ISSUE TITLE
[jobs/ems] Add a store to pillbox

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#1014]
**Name:**
AmokBSN#3856

**Summary:**
Including a shop for medics at Pillbox similarly to what PD has close to the evidence locker space. 

**Reason:**
It can be quite busy whilst on duty as a Paramedic and in order for us to restock on much-needed supplies e.g. food, water, bandages we would need to go off-duty and travel to a store to replenish these items. 

This would mean we can instantly restock where we carry out most of our duties. The store wouldn't require a lot of items to be functional and I would only suggest the following: 

Water, burgers, sandwiches, bandages and oxygen tanks. 

![20200426212312_1](https://user-images.githubusercontent.com/52701837/80589602-6498c780-8a12-11ea-9058-afc737c2cd60.jpg)

**Comment by InZidiuZ** [comment]
This was added with 2.7.
