### ISSUE TITLE
[jobs/ems] EMS MDT

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#1015]
**Name:**
AmokBSN#3856

**Summary:**
I know that in future the PD will have an MDT system which, they will be able to log crimes, calculate fines that will be fully functional within the city (as opposed to external use of software or website) I believe once the groundwork is fully operational it would be hugely beneficial to also have one for workers within Pillbox. 

**Reason:**
This would significantly increase roleplay not only for those working within Pillbox but also every civilian, the justice department and police force. 

For example, any complex surgeries can be logged by the surgeons of operations they've completed recording valuable information as to what happened and the resolution of their treatment. The therapy department can keep accurate records as to progression on therapy and if they've been attending regular meetings. 

If parole is implemented therapists can notify police or the justice system if they've been sticking to this agreement and if not, act accordingly. 

In situations of malpractice or in severe cases a patient is unable to be resuscitated, medics/coroners can record vital information that could be passed on to detectives for them to further investigate creating branching threads and long term roleplay development. 

Additionally, medical records can also be used to support defence or prosecution during trials.

**Comment by DaxterPancake** [comment]
I think this would be a great idea. 

I'd love to be able to look up someones name and flag them for allergiers or addictions to certain medication (such as Morphine).

**Comment by InZidiuZ** [comment]
This suggestion is being rejected for the time being.
