### ISSUE TITLE
[jobs/ems] Suspect in (increasing max count and animation change)

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#1016]
**Name:**
AmokBSN#3856

**Summary:**
Currently, the EMS Ambulance is able to transport (suspect in) one patient at a time and during scenes of heated conflict or where multiple patients are incapacitated being able to increase this to perhaps a maximum of three would be beneficial. 

I would also be happy with two, however, having three seems like an ideal medium as they would still receive treatment on scene and then transported to PB Medical for further analysis. 

I'm also not sure if it's possible to also request an animation change for when they're placed in the vehicle, at the moment their body sticks out from the side, I'm not sure if this animation change could be something that's a natural seating position when we place them inside. 

**Reason:**
During busy times this can mean that if PD is on a scene or other civilians, we are often having to resort to requesting assistance with transport this would be massively beneficial if low EMS numbers are currently on duty at one time and means for a quicker response and return rate and would not need to heavily rely on others. 

Animation changes would also make it look less silly with patients sticking out from the rear wheels.

**Comment by twooot** [comment]
You are able to put 3 people in an ambulance now
