### ISSUE TITLE
[jobs/ems] Addition of /heal command 

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#1017]
**Name:**
AmokBSN#3856

**Summary:**
During medical treatment, in order for us to fully treat patients, we often have to use /cpr for a full 'revive' The animation itself within that context is fine however when they are on a bed looks a little ridiculous. 

**Reason:**
Better interactions with patients from adding a new /heal command with a reasonable animation would increase ImMeRsIoN and less like we are palm blasting the floor while they're on a bed.

**Comment by InZidiuZ** [comment]
/revive shouldn't even be needed to revive treat patients, though

**Comment by TCruxer** [comment]
I believe they are referring to the /cpr which is currently needed in the hospital beds because it is the only way to fully view the list of injuries a patient has @InZidiuZ .

**Comment by twooot** [comment]
I think this is pretty much there with the /inspect command
