### ISSUE TITLE
[vehicle/seatbelt] Seat belt issue

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1019]
**Reporter**
RitikBakshi#4798
https://steamcommunity.com/id/sutta69/

**Summary:**
When we stop our vehicle then open the seatbelt then we get ejected from vehicle automatically into the air

**Steps to Reproduce:**
Drive a vehicle and make sure you are wearing seatbelt then stop your vehicle then put off seatbelt and it will launch you into air

**Expected Results:**
Seatbelt should be disengage without ejecting the player

**Actual Results:**
We get launched into air when we turn off seatbelt 

**Game Resolution:**
1080p

**Player Data:**
4082
**Server:**
Indian server

**Comment by InZidiuZ** [comment]
Does this happen every time? 🤔

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
