### ISSUE TITLE
Old key system

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1020]
**Name:**
RitikBakshi #4798
**Summary:**
bring back old vehicle key system 

**Reason:**
it was way more comfy than this new key system which we can’t see in our inventory.... that physical key in our inventory can be easily given to anyone without any problem

**Comment by AdeptCL** [comment]
Big -1.

**Comment by z-Lunar** [comment]
> **Name:**
> RitikBakshi #4798
> **Summary:**
> bring back old vehicle key system
> 
> **Reason:**
> it was way more comfy than this new key system which we can’t see in our inventory.... that physical key in our inventory can be easily given to anyone without any problem

rather we give a key to a person, they get the key we keep our key.

**Comment by DaxterPancake** [comment]
I'm not understanding your issue here. You prefer to see a physical key that you can hand someone? Even though doing /givekey does the exact same thing MINUS seeing it as an inventory item?

I'd like to be able to keep keys and also give a key, as Lunar suggested but, I am fairly certain we aren't going to be reverting the key system.

**Comment by Ashpritish** [comment]
> **Name:**
> RitikBakshi #4798
> **Summary:**
> bring back old vehicle key system
> 
> **Reason:**
> it was way more comfy than this new key system which we can’t see in our inventory.... that physical key in our inventory can be easily given to anyone without any problem

yup old key system will be better for game crashes.Cause after game crashes we lose our own car key so we have to hotwire our own car if its not locked its very dissapointing man do something for this isssue....
