### ISSUE TITLE
[?] Suggestion Add Rockstar Editor [ Indian Sub-Division ]

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1021]
**Name:**
Who is suggesting this? Please include discord name.
RaviCan'T#0001
**Summary:**
Write a short summary of what your suggestion is about.
The Rockstar Editor is a feature exclusive to GTA 5 for PC. The combination editor and Director's Mode tool allows players to record footage from both Grand Theft Auto 5 and GTA Online, set up scenes, edit that footage, and distribute it.
https://github.com/Kyominii/ClipSaverV
https://forum.cfx.re/t/release-clipsaverv-v1-2-0/29243
**Reason:**
Why would your suggestion be a good addition to Legacy?
If you add this it will gona be crazy will get more sexy footage like this :- https://www.youtube.com/watch?v=Mhsncz9MP4I

**Comment by inderpalofficial** [comment]
+1

**Comment by bhosalevishu** [comment]
+1

**Comment by Mechan1caL** [comment]
+1

**Comment by MrKanishkPatel** [comment]
+1

**Comment by KaiEagle** [comment]
+1 (Need some popcorn :( )

**Comment by officialpiyush** [comment]
+1 ( does anyone actually care though )

**Comment by ravicant** [comment]
> +1 ( does anyone actually care though )

you mf

**Comment by WildEngin33r** [comment]
+1

**Comment by Rithvikk05** [comment]
+1

**Comment by AdeptCL** [comment]
**Not the correct way to show your interest in it. Please react to the OP.**

**Comment by TomatoPatel** [comment]
+1

**Comment by 4RCHI007** [comment]
+1

**Comment by adityadevharkar** [comment]
+1

**Comment by lucifer019** [comment]
+1

**Comment by rahul-070** [comment]
+1👍

**Comment by Vexedgaming** [comment]
+1

**Comment by nazgul220** [comment]
+1

**Comment by InZidiuZ** [comment]
FiveM has now implemented this globally to everyone's client!

For more information, see https://forum.cfx.re/t/community-update-period-5/1208024
