### ISSUE TITLE
[jobs/reporter] Open Weazel News HQ ,adding new van and Helicopter

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/op-framework-issue-tracker#1022]
**Name:**
Who is suggesting this? Please include discord name.
ppthegamer#7381

**Summary:**
Open Weazel HQ with new vehicles and helicopter
https://forum.cfx.re/t/release-weazel-news-pack-news-vehicles-pack-2-2-discontinued/171540

**Reason:**
Why would your suggestion be a good addition to Legacy?
If you add this, it will increase reporter RP. As i am doing reporter RP in Indian Servers because of my news 1 PD officer was suspended. The only problem i am facing is we do not have Weazel Helicopter to cover chases. 

If this is added then not only in indian servers but in other servers it will increase RP and as the media is the important part of state to show what is going in city, to ask questions from authorities so it should be added.

You can see in video how i covered racing event from PD helicopter for weazel News(Now PD don't give their helicopter for covering new because i have exposed them many time )

https://www.youtube.com/watch?v=Osnhh6s1AkE

**Comment by InZidiuZ** [comment]
https://www.youtube.com/watch?v=4PfguJA9CxE :o

**Comment by ppthegamer** [comment]
> https://www.youtube.com/watch?v=4PfguJA9CxE :o

This interior is good have a look at this too 

https://www.youtube.com/watch?v=YyChQJ1s--M

Bro if these things are added literally it will increase RP in server. For ex. if something happens wrong in city Mayor or PD have to answer to reporter why did it happend

**Comment by ppthegamer** [comment]
Adding this vehicle with Weazel News livery. Like PD and EMS to choose their vehicle from multiple options

https://www.gta5-mods.com/vehicles/range-rover-evoque

**Comment by InZidiuZ** [comment]
This has since been done.
