### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1024]
**Reporter:**
RitikBakshi#4798 

https://steamcommunity.com/id/sutta69/

**Summary:**
after pressing ENTER to join im stuck on fetching character data this only happens in server 1 and server 1 is really unstable and gives alot of network issue

**Steps to Reproduce:**
Connect to city 1 then after loading screen press ENTER to join and boom you get stuck on fetching character data.

**Expected Results:**
It should join normally and show the different characters 

**Actual Results:**
It get stuck on fetching character data 
#
**Game Resolution:**
1920*1080

**Player Data:**
4085

**Server:**
Indian server

**Comment by InZidiuZ** [comment]
I believe this may have been caused by people maliciously abusing a FiveM bug. The bug has since been resolved and our server files have been updated to the latest version, so this should no longer be an issue.
