### ISSUE TITLE
[illegal/corner] New method to sell drugs

### ISSUE THREAD

**Issue by DarkD1d** [InZidiuZ/op-framework-issue-tracker#1026]
**Name:**
Alfie#4022 - Alfie Redd

**Summary:**
With the server now having access to over 64 slots its very hard to sell certain items that you can get a hold of, my suggestion is that you add a thing like oxy runs but you need the items you want to sell on you, and just like the oxy runs it sends you to certain people in which you can sell to. This would hopefully fix the current state of the server where people are sitting on loads of drugs they cant get rid of.

**Reason:**
It would allow people who are sitting on a large amount of drugs to be able to sell them, which hopefully will help the economy.

**Comment by InZidiuZ** [comment]
A suggestion was made to create a "/sell" command, which would create a nearby ped you would have to run to & sell as previously done when there were peds natively roaming the streets. Not sure if that's what you mean, but I think that definitely could work .😄 

I believe FiveM is also close to having peds (as well as parked vehicles) available on big mode 1s infinity.

**Comment by InZidiuZ** [comment]
I've added a /corner command now that allows you to spawn a ped nearby which you may offer drugs to. This resolves the primary reason OneSync Infinity isn't being used! 🎉
