### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by acharekarshubham** [InZidiuZ/op-framework-issue-tracker#1027]
**Name:**
Who is suggesting this? Please include discord name
shubhamacharekar#9137
**Summary:**
Write a short summary of what your suggestion is about.
We need old JDM car back in city like Supra MK4 and Nissan GTR r34 because they are iconic car and known in around the world
**Reason:**
Why would your suggestion be a good addition to Legacy?
We can do street racing and drifting event and all

**Comment by InZidiuZ** [comment]
If those are vehicles that have previously been in the exclusive dealership already, they will be readded at some point. If not, then take a look [at this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues) issue tracker and create suggestions there.
