### ISSUE TITLE
[game/trackers] Laggy tracker blips

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#1028]
**Reporter:**
Brundoggy#4820

**Summary:**
The PD blips are laggy on the maps. They update every second rather than being smooth and continuously following someone. Also I think the /tracker off isn't working either. 

**Steps to Reproduce:**
Go on duty and see the tracker's move smoothly.

**Expected Results:**
Tracker's move smoothly

**Actual Results:**
Choppy/laggy dots. And no command that tells you that /trackeroff is working

## Additional Information

**Screenshots:**

**Game Resolution:**
1920*1080
**Player Data:**

**Server:**
NA/EU

**Notes:**

**Comment by InZidiuZ** [comment]
Not sure if you intentionally closed this, but as only nearby players are loaded for you, most players' coordinates are not possible to be obtained from your client's side. Therefore, as a workaround, the server updates all the on-duty clients with the other people's coordinates that has their tracker enabled. Then from that, it recreates the blips. This is done in an interval running every second.

Lowering it will not be possible as one "tick" for a client is one frame, meanwhile for the server it's different, so it won't be possible to match them up properly allowing for that smooth experience previously had.  Besides, doing it in such a way wouldn't be very performant.

A "fix" would be to simply just manually create a smoothing effect by updating the blip's point every frame, based on two different updates from the server, having both a starting point as well as an ending point.

**Comment by Brundoggy** [comment]
The reason why I closed was because I  saw there was already another github opened. 

And it be what it be. ty ben

**Comment by InZidiuZ** [comment]
This has now been resolved. I added smoothing to both the rotation as well as the positioning of the blip. There's a 1-2 second delay on the blip compared to the actual player due to this being scripted by doing C->S->C without any event spam. [Here's](https://gyazo.com/ac8e76d151321a4cf280c5732ebff43b) what it looks like now. This will be properly infinity-compatible.
