### ISSUE TITLE
Quality of life improvement

### ISSUE THREAD

**Issue by mavroses** [InZidiuZ/op-framework-issue-tracker#1030]
**Name:**
MAVROSES#1110

**Summary:**
This is simply about improving the server and bringing back actual RP, since for a lot of people the server is currently not enjoyable.

Firstly, keep the server at 68 player cap without instancing, most people hate the fact that we can only sell Weed/Coke and run the Chopshop days a week. There are already very limited ways of making money and this 100+ slot instancing thing is ruining everything and making everything scuff out. Also, having such a big player cap is letting in unwanted people that are VDMing and RDMing everyone they see and also not talking or communicating in English or otherwise at all. The quality of RP and overall experience is 100000 times better with 68 slots.

Secondly, instead of 2 restarts per day (tsunamis), make the server restart 4 times a day (every 6 hours). This would drastically improve performance and also give people more opportunities to join the server when it's full and they don't feel like waiting through the train.

Thirdly, banks should not be as easy to do as they are now, people are just chain robbing every single hour and it's horrible. Either change the drop rates of thermite or add some sort of more complex system to robbing banks instead of just a lockpick and 4 thermite.

**Reason:**
The quality of RP + the amount of enjoyment in playing on the server is drastically decreasing.

**Comment by MrSnowSar** [comment]
100% Agree. Well said!

**Comment by InZidiuZ** [comment]
First off, this is meant for framework-related suggestions, not community ones. This issue tracker is shared with multiple other subdivisions/communities all using OP-FW, so creating issues specific for one of them, doesn't make sense & is therefore discouraged.

Increasing the amount of server restarts would also, most likely, have minimal impacts on performance. We could even test this by removing all restarts for a few days. My hypothesis is that it'll remain mostly the same as there's no reason this *wouldn't* be possible. Though, of course, there may be unseen bugs from both FiveM & the framework that might cause memory consumption build-up after time as well as CPU usage for both clients & the server.

You're also only meant to include one suggestion per opened issue to keep everything tidy.

Will close this issue. If you want to create an issue for the third point, feel free to. Though, make sure no one already has.

**Comment by Phunkadelia** [comment]
> Will close this issue. If you want to create an issue for the third point, feel free to. Though, make sure no one already has.

Someone already has.

https://github.com/InZidiuZ/op-framework-issue-tracker/issues/929

One hour global cooldown for banks. We had it before, why can't we have it now. The lack of one is producing far more negative experiences than good ones.
