### ISSUE TITLE
[subdivision/india] Increase server slots and update server

### ISSUE THREAD

**Issue by MezmerPlayz** [InZidiuZ/op-framework-issue-tracker#1031]
**Name:**
@MezmerPlayz#1001

**Summary:**
My suggestion is about Increasing server slots and changing server version to Beta from Alpha in Legacy India WL.

**Reason:**
Because a huge line of queue and growth of bugs day by day and a lot of Dsync. Bugs such as Gun back bug, Officer tracker's bug, Locale's cars spawn out of nowhere. If possible then please have a look into it for server version Beta.

**Comment by Doughnut2001** [comment]
-1 the point of having limited server slots is to help with Desync, which can change your face when you spawn and to also encourage people to Support the server for priority.

**Comment by InZidiuZ** [comment]
This is not related to the framework's development. Redirect other issues to the community you're a part of or referring to.
