### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ashpritish** [InZidiuZ/op-framework-issue-tracker#1032]
**Reporter:**
CriTicaLGuY#4459

**Summary:**
Im experiencing bug like below
when I get out of car and then get in at any time its windows and headlights are breaking down every time its happening with owned car to its very unsatisfiying to see ur car windows breaking without any accident or any crash plz fix this issue....

**Steps to Reproduce:**

**Expected Results:**
I expect u will fix this breaking issue soon..

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Closing this issue. 

If you want a bug to be fixed, you are required to provide as much information as you can and answer everything in the template. You have failed to do so. 
Please re-open when you've put more effort into it.

Also, get your car repaired. If you have high ping to the server you are going to run into things without seeing it in your eyes and your car is going to get damaged. It happens. It's why we have mechanics.

Cheers,
**Daxter.
Project Manager.**
