### ISSUE TITLE
[jobs/police] Increased capacity of MRPD evidence locker

### ISSUE THREAD

**Issue by AverageStatistic** [InZidiuZ/op-framework-issue-tracker#1035]
**Name:**
Who is suggesting this? Please include discord name.
Dex#0255
**Summary:**
Write a short summary of what your suggestion is about.
I've heard from other officers who have been around longer than me that the evidence locker size used to be 5000. It is currently set to 1000. However, most of the time long after a restart the locker tends to get full and evidence has to get manually destroyed.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a lot easier to be able to store evidence without the likely chance of it filling up

**Comment by InZidiuZ** [comment]
Or perhaps have it automatically wipe again every restart, as items that's needed to be kept as evidence can be stored in private lockers? :o

**Comment by AverageStatistic** [comment]
Why not just increase it so there’s not a chance it gets full? Will there be a drastic decrease in server stability or performance? Also why was it changed from 5000 to 1000?

**Comment by Masik52** [comment]
Even when the inventory wiped every tsunami there was a 5000 capacity in the evidence locker.  I get that we could use the personal lockers for evidence that must be kept but if that individual isn't in the city we can't access their locker to get said item.  Whichever option is decided to be used it would be great to see it happen as  soon as  possible.

**Comment by AverageStatistic** [comment]
@InZidiuZ Wait by your previous reply did you mean that if you upped to back to 5000 that it wouldnt wipe after every tsunami?

**Comment by InZidiuZ** [comment]
This has now been done.
