### ISSUE TITLE
Player Inventory wont open Anyone

### ISSUE THREAD

**Issue by McLovinzz** [InZidiuZ/op-framework-issue-tracker#1036]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Relano McLovinzz - R3ality#9329
https://steamcommunity.com/id/R3allity/

**Summary:**
Write a short summary of what you're experiencing.
Joined Server 2 After the Tsunami yesterday night. Alot of people had a problem with opening inventories but they all got it fixed with taking a soft nap (Character switch).
I tried everything, including reinstalling FiveM, then i created a test character and it worked again.
What i am guessing that happened is that my Character lost its bind to the "Player inventory".

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
This is not confirmed:

While the inventory was scuffed for everyone, someone tried to take my ID from me, nothing else out of the order happened.

**Expected Results:**
What are the expected results?

After doing you should not be able to enter your inventory anymore and everytime you try, a white arrow will appear but nothing "is there".

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://i.imgur.com/U8YNAR6.png
https://medal.tv/clips/23743844/d1337qrrRwW2

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 10076 - Job Data: Government, Waste Collector, Employee
Timestamp: 2020-05-06 13:18:04

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main#2 and Main#1

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
One of the inventories seemed to have overflowed looking at how a ground inventory was created. Once it was created, did you try pressing K?

Is this also still an issue?

If it is, please DM me so we can look further into it.

**Comment by InZidiuZ** [comment]
Closing due to no response
