### ISSUE TITLE
[dependency/easyadmin] EasyAdmin Bug

### ISSUE THREAD

**Issue by GamingZone01** [InZidiuZ/op-framework-issue-tracker#1037]
**Reporter:**
SpyGod#9193 https://steamcommunity.com/id/subha0109/

**Summary:**
While using easy admin, when we try to "teleport to player". It doesn't do anything, and /admin stops working. We need to restart the fivem, to make /admin to work again.

**Steps to Reproduce:**
1. Open easy admin 
2. while spectating, try "teleport to player", it won't do anything
3. easy admin will get off automatically. Try opening it again, it won't open

**Expected Results:**
While using easy admin, when we try to "teleport to player". It doesn't do anything, and /admin stops working. We need to restart the fivem, to make /admin to work again.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
https://imgur.com/a/km7ZEfI

**Game Resolution:**
1600x900

**Player Data:**
CID #: 199

**Server:**
Bangladesh

**Notes:**
For anything else noteworthy.

**Comment by riddlevongrump** [comment]
This I can confirm as well, has happened several times.  Both TP to player or them to me. Once one of those options are selected the moderator has to hard nap in order to regain access to admin panel.

**Comment by Masik52** [comment]
Teleport to player has been broken and causes easy admin to not work for me as well. Haven’t had issues with teleporting someone to me though

**Comment by Milan345** [comment]
+1, while spectating admins gets teleported randomly near the civilian.

**Comment by InZidiuZ** [comment]
This has now been resolved.
