### ISSUE TITLE
Camaro Bullet Proof

### ISSUE THREAD

**Issue by praveenprk25** [InZidiuZ/op-framework-issue-tracker#1038]
**Reporter:**
Discord ID: @praveenprk25#9757

**Summary:**
Camaro is bulletproof except tyre.

**Steps to Reproduce:**
Get a police camaro and fire shot on it through window with a person inside. Person inside wont get shot.

**Expected Results:**
Person inside should get damage.

**Actual Results:**
Person inside isnt getting any damage.

## Additional Information

**Video link:**
https://www.youtube.com/watch?v=EEtNK8P30Gg

**Game Resolution:**
2560x1440

**Player Data:**
character id : 5283

**Server:**
Indian server (WL)

**Notes:**
Its only for Police Camaro.

**Comment by InZidiuZ** [comment]
Report it [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
