### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by YashdeepSavlani** [InZidiuZ/op-framework-issue-tracker#1040]
**Reporter:**
My name is Yashdeep My discord name is YashDeep My stream id :- https://steamcommunity.com/id/YashDeep236/
**Summary:**
I am in garage  A  and i call my taxi suddenly  their spawn 2 taxi and blast . i retrieve my taxi 
when i open trunk i see all items gone

**Steps to Reproduce:**
i want all things or in game money
**Expected Results:**
i want all things or in game money

**Actual Results:**
i want all things or in game money

## Additional Information

**Screenshots:**
i have not screenshot that time 
**Game Resolution:**
1920*1080
**Player Data:**
Yashdeep BaBa

**Server:**
 Server 1: 139.99.125.59:30120, India

**Notes:**
You check also my logs

**Comment by AdeptCL** [comment]
The server doesn’t offer compensations. 

Bugs happen, but it’s a good thing you’ve reported the bug.

**Comment by YashdeepSavlani** [comment]
> The server doesn’t offer compensations.
> 
> Bugs happen, but it’s a good thing you’ve reported the bug.

ok but you give all items back ??
What happen now ?? what i do now??

**Comment by AdeptCL** [comment]
> ok but you give all items back ??
> What happen now ?? what i do now??

> The server doesn’t offer compensations.

Nothing. Just play. The bug report is made.

**Comment by YashdeepSavlani** [comment]
> > ok but you give all items back ??
> > What happen now ?? what i do now??
> 
> > The server doesn’t offer compensations.
> 
> Nothing. Just play. The bug report is made.

what are you saying i cant understand

**Comment by YashdeepSavlani** [comment]
> > > ok but you give all items back ??
> > > What happen now ?? what i do now??
> > 
> > 
> > > The server doesn’t offer compensations.
> > 
> > 
> > Nothing. Just play. The bug report is made.
> 
> what are you saying i cant understand

why are you cant giving me answer ???

**Comment by Masik52** [comment]
He did give you an answer. Nothing can be done to get your items back. You completed a bug report for the issue so it can hopefully be fixed and not happen in the future. Now all there is to do is go back to Roleplaying

**Comment by YashdeepSavlani** [comment]
> He did give you an answer. Nothing can be done to get your items back. You completed a bug report for the issue so it can hopefully be fixed and not happen in the future. Now all there is to do is go back to Roleplaying

i want money or items why i man can not understand this server make for us and they should help me

**Comment by AdeptCL** [comment]
There is **NO WAY** your getting your items back. There is nothing in place for you to get your items back.

But thank you for the bug report.

**Comment by YashdeepSavlani** [comment]
Give me 20k money in games
Do work very hard please do something I request you 😊

**Comment by Masik52** [comment]
No......

**Comment by YashdeepSavlani** [comment]
But the why you are admin

**Comment by Masik52** [comment]
We do not have a compensation system. That is why we cannot compensate you.

**Comment by AndersHSR** [comment]
Legacy Roleplay as a server does **_NOT_** provide money/items or any other way of **compensations** in any case that includes Game-Sided Bugs.

We are aware that this bug is frustrating, and that you have wasted your time getting those items, but please stop asking, this is unnecessary.

Thanks.

**Anders Asset Developer**

**Comment by YashdeepSavlani** [comment]
It's mean you don't care about your server player

**Comment by AdeptCL** [comment]
Yes we do. But it is not possible.

**Comment by DaxterPancake** [comment]
I'm closing this.

Bugs happen.
You submit a bug report to help better the server, not to try to get all your items back or money.

Thank you for your report, but without more information/evidence, we can't re-produce this and fix it.

Cheers,
**Daxter.
Project Manager.**
