### ISSUE TITLE
[?] Robbing without Cuffs Whitelisted Gangs

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#1041]
**Name:**
Lars.#0181

**Summary:**
Would it be possible to give Whitelisted Gangs a role so it would be possible to search someone without using cuffs?

**Reason:**
Because right now, if you are at war and you manage to down your enemy, you would need to pick everyone you downed up (1 person per trunk, so at least 5 cars are needed) and bring them to a place where you can search them. After that, you would need to bring them to Pillbox because you want them to remember, so we can progress with the storyline. If we would be able to search them within a few seconds, we could leave them at the crime scene to be picked up. It would also give the cops some more interaction because they will actually find something if they respond to shots fired.

**Comment by AdeptCL** [comment]
Definitely not.

**Comment by y0Razz** [comment]
Just remove their Whitelist if they can't use it properly sar.

**Comment by MrSnowSar** [comment]
+1

**Comment by McLovinzz** [comment]
Thats just going to be another advantage for gangs, definately not...

**Comment by y0Razz** [comment]
I mean, best scenario would be to make it possible for everyone. But that won't happen without Whitelist.

**Comment by Doughnut2001** [comment]
nope, if you're against it use the thumb down emoji don't flood the chat.

**Comment by twooot** [comment]
> Definitely not. There’s still be shitlords. KEKW

this
