### ISSUE TITLE
[vehicles/garages] MRPD PERSONAL VEHICLE GARAGE

### ISSUE THREAD

**Issue by lucifer019** [InZidiuZ/op-framework-issue-tracker#1042]
**Name:**
Who is suggesting this? Please include discord name.
Lucifer19#0105
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about to add that garage back in mrpd where you can store your personal vehicles, it got removed in the last update.(don’t know why)
**Reason:**
Why would your suggestion be a good addition to Legacy?
We literally have to travel to garage A to get our personal vehicles when we are going off duty, it was a good addition.

**Comment by InZidiuZ** [comment]
Already suggested in #921.
