### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PatelBhai03** [InZidiuZ/op-framework-issue-tracker#1043]
**Name:**
Patel Bhai   Discord- Patel Bhai#8055
**Summary:**
It is about the Toyota Chaser NSX
We understand it is a Drift car...But if you see properly in the interiors of the car 
there is a handle Bar/lever for Drifting at Particular turns, But What you have done
With this car is it keeps on Drifting and tire spin doesn't even stop! And the car can 
hardly take a reverse...It would be nice if the car goes back to normally it was
**Reason:**
Why would your suggestion be a good addition to Legacy?
All ready as such there are Less car for the Supporters and This car which was likely 
Good in compare to other 4 seater vehicle...People can opt more for This vehicle and 
Maybe Support the server even more! 
Think About it!
That car sucks right now!

**Comment by z-Lunar** [comment]
this cars being completely revised, at the time I did this when I had just started the development work for Legacy, I am going through a few of my changes and correcting immature/incorrect changes, I apologize for this on my behalf :).
