### ISSUE TITLE
Game is very laggy after maintenance (14th may)

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1044]
**Reporter:**
RitikBakshi#4798

https://steamcommunity.com/id/sutta69/

**Summary:**
after the short maintenance on 14th may the game became really unoptimized and laggy i have been also encountering texture loss and shuttering and i have a high end pc also other games are working fine.... i tried to reinstall fiveM and clear cache but didn't Work

**Steps to Reproduce:**
Just play on indian blacklist server many people are facing this issue 

**Expected Results:**
we just want it to run smooth and server should be optimised and should be very stable

**Actual Results:**
The game is very choppy and unplayable it was good before maintenance update

**Game Resolution:**
What is your game's resolution?
1920*1080

**Player Data:**
Name-RitikBakshi 
Id-4085

**Server:**
India.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Is this still an issue?

**Comment by InZidiuZ** [comment]
Closing due to no response.
