### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Vinu2KK** [InZidiuZ/op-framework-issue-tracker#1046]
**Reporter:**
Vinu2K#5353

**Summary:**
I Noticed that the PD Camaro has some bugs/issues with it. Even if the Windows or doors are broken the bullets doesnt hit the person which is inside the Car. The only way to hit the guy inside the car is to Fire at his Hand. This issue is only with the PD Camaro. The PD Camaro is not less then a Tank.

**Steps to Reproduce:**
Fix the bug that the bullet doesnt penetrate even if the doors/windows are broken.

**Expected Results:**
Make it same as a Normal EDM Camaro. Not the exact same but ya atleast the bug should be fixed.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
[I dont have it rn]

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 326

**Server:**
India Whitelisted

**Notes:**
 Clip:   ##https://drive.google.com/file/d/17k3vsCaj9c_YZbHDyT5811o7SUymHCki/view?usp=sharing

**Comment by z-Lunar** [comment]
Thank you for reporting this, going to be looking into the issue.

**Comment by InZidiuZ** [comment]
Use [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) issue tracker instead.
