### ISSUE TITLE
[properties/properties] Change garage location

### ISSUE THREAD

**Issue by NovaPurpl3** [InZidiuZ/op-framework-issue-tracker#1048]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
one of the houses on Amarillo Vista the garage is very annoying and very hard to use, the marker to pull cars out of this house is too far away from the street and you have to either get your car into the perfect position for it to work or somehow ramp your car onto the hill the marker is on.
**Reason:**
Why would your suggestion be a good addition to Legacy?
the marker is in a very awkward spot and makes things weird when you have to get into your car 2-3 times to position it enough to where it will accept your car into the garage. Many of us use this house and it is a pain not only for myself but also for everyone else that uses this house to store their cars in. 

![download (1)](https://user-images.githubusercontent.com/63160648/82099868-6206c500-96d6-11ea-9035-2297211129c5.png)

![sZ-aiYmnQpW77QxNGc9eXQ](https://user-images.githubusercontent.com/63160648/82099940-8662a180-96d6-11ea-9b7f-02e20327fad1.png)

**Comment by MrSnowSar** [comment]
+1

**Comment by InZidiuZ** [comment]
Something for the mighty pxyeb

**Comment by twooot** [comment]
This doesn't seem to be an issue anymore
