### ISSUE TITLE
[game/scoreboard] Scoreboard Page Up & Down

### ISSUE THREAD

**Issue by anuragkumarak95** [InZidiuZ/op-framework-issue-tracker#1049]
**Name:**
Who is suggesting this? Please include discord name.
anuragkumarak95#1597

**Summary:**
Write a short summary of what your suggestion is about.
The capability of scrolling full page in User List

**Reason:**
Why would your suggestion be a good addition to Legacy?
It can be helpful for players to note down a steamID of another player (commonly for reporting), to be able to traverse directly to the next page of the user list just by one click. you can use the standard PAGE-UP and PAGE-DOWN key-binds for this I suppose.

**Comment by InZidiuZ** [comment]
There's no "pages" in the scoreboard, but having page up & page down scroll 10 or so entries at a time could be useful for when there are a lot of players online.

**Comment by InZidiuZ** [comment]
This has now been done.
