### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sonu07-star** [InZidiuZ/op-framework-issue-tracker#1050]
**Name:**
My name is Harshith
discord id:  Harshith_07#5428

**Summary:**
i have an idea of open VPN hosting in AWS so we can give the openVPN source file of server and we can say that they can connect to it

**Reason:**
I have noted that many of them faces vpn issues and many TS issues if not using a vpn

**Comment by InZidiuZ** [comment]
Redirect this to Ravi.
