### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1051]
**Reporter:**
Jethiya#0001

**Summary:**
So as you know due to the increased player count the beds at the pillbox are usually occupied to their fullest so when a player automatically spawns in the hospital after paramedic waiting period get over. The player glitches into this forever black screen. And everytime you reconnect your items gets mugged and you glitch again. Thats what happened to me yesterday and I almost lost half of my inventory.

**Steps to Reproduce:**
Increase bed counts or decrease the auto treatment time period so that people take less time getting treated.

**Expected Results:**
Respawn and land up directly into pillbox wards 

**Actual Results:**
Glitched in a forever black screen.

**Game Resolution:**
1366 x 768

**Player Data**
Pardeshi Bhaiya 
Character id - 4148

**Server:**
India 

**Notes:**
No

**Comment by sonu07-star** [comment]
yes actually when u respawn u r self with out the help of EMS then some of your items will be goneso it is better to have only few items carried by you

**Comment by anuragkumarak95** [comment]
👍

**Comment by InZidiuZ** [comment]
This is a wontfix for now
