### ISSUE TITLE
[subdivison/india] Losing money glitch

### ISSUE THREAD

**Issue by Ruckledge** [InZidiuZ/op-framework-issue-tracker#1052]
**Reporter:**
Discord-FuRy_Ruckledge#1606
https://steamcommunity.com/profiles/76561198861551612/
**Summary:**
Different amounts of money is getting automatically deducted from my bank account . I lost around 20k from my bank account today . Each and every time i leave the city and restart FiveM nd enter into one of the servers of Legacy RP a certain amount is missiong from my bank account 
I have video evidence and the link to my video is-https://drive.google.com/open?id=1KpUvdBLQUoOsg6mq38mLiN7oxUDqCFiT
https://drive.google.com/open?id=1-hef66Iw84x8s2Pkt_wK3zXoAuYiwkkd
I provided two links incase one doesnt work 

**Steps to Reproduce:**
i dont know but pls fix this issue 

**Expected Results:**
I would expect that this bug would be fixed and this issue would not persist in the mere future and i hope that all my lost money amounting to almost 25k will be returned to me

**Actual Results:**
I am losing money from my bank continuously
## Additional Information

**Screenshots:**
Video Evidence- https://drive.google.com/open?id=1-hef66Iw84x8s2Pkt_wK3zXoAuYiwkkd

https://drive.google.com/open?id=1KpUvdBLQUoOsg6mq38mLiN7oxUDqCFiT

**Game Resolution:**
1920*1080p

**Player Data:**
Character ID:11419- Job Data: Government,Waste Collector,Employee
Timestamp:2020-05-18 18:05:03

**Server:**
I am from India
I play Legacy RP

**Notes:**
In the video evidence i first showed the bank balance i had then closed the game and restarted it and as soon as i entered the server i saw some amount of my money was missing

**Comment by Ruckledge** [comment]
Is it fixed????

**Comment by Cricketx818** [comment]
You will get a response once he has closed the file or reviewed it, Please be patient when he reviews the bug reports, 


Thank you

**Comment by InZidiuZ** [comment]
Not sure exactly what's happening. Could be that the money displayed to you when you're on #7 is desynced while in reality it should be $27,500. Did you purchase anything in that session that would've lowered your money amount with $2,500? Also, does this happen *every* time you change server?

**Comment by Ruckledge** [comment]
After I recorded the video I closed the game nd played it the next day. I saw that around 1500 was restored the nxt day. Also this started after i rented an apartment. And if the amount is gone then it is gone for me in all the servers. At first it deducted around 7k from my acc then 4k then once more around 5k and then I recorded this video.

**Comment by InZidiuZ** [comment]
Going to assume this is just some issues with the *ancient* money module that's set to be rewritten soon. Will therefore close this. If you have this issue in the future after it being rewritten, feel free to create another issue.
