### ISSUE TITLE
[companies/companies] Markers for property sectors

### ISSUE THREAD

**Issue by anuragkumarak95** [InZidiuZ/op-framework-issue-tracker#1053]
**Name:**
Who is suggesting this? Please include discord name.
anuragkumarak95#1597

**Summary:**
Write a short summary of what your suggestion is about.
Get markers in the in-game map about which company owners which property sectors 

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be really helpful for tenants and owners all together if the in-game map could show which blocks are owned by which companies. the approach time between the 2 parties will reduce drastically as the person will know definitely, who to approach for buying a property in their mind.

**Comment by InZidiuZ** [comment]
We can only have so many blips on the map, and don't think I'll be adding up to 170 additional blips for the blocks and their owners. In the future, once we get a new phone, you'll be able to search for addresses in an app which would help with people finding locations.
