### ISSUE TITLE
[jobs/vanillaunicorn] Locker in VU

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/op-framework-issue-tracker#1054]
**Name:**
Who is suggesting this? Please include discord name.
LilGrizz818#5108
**Summary:**
Write a short summary of what your suggestion is about.
What im suggesting is some sort of Safe/storage inside the vanilla unicorn. I have a perfect location where it would be at also. Similar to PD/EMS storages but for people with the VU role only ofc.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a really good addition to legacy cause i have plenty of plans for events etc and the storage would be really good cause future plans i have involved supplies and itll make it really good to have the storage in the VU.
![20200518143834_1](https://user-images.githubusercontent.com/53550279/82262556-fe6ada80-9915-11ea-82b0-7450bbeecd52.jpg)
![20200518143825_1](https://user-images.githubusercontent.com/53550279/82262565-01fe6180-9916-11ea-85a2-34f6075b36bd.jpg)

**Comment by twooot** [comment]
VU has a locker
