### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DarKSouL3147** [InZidiuZ/op-framework-issue-tracker#1055]
**Name:**
DarKSouL#1025

**Summary:**
I want to suggest about police in blacklisted servers. I have personally never seen police in normal servers.

**Reason:**
There are many people who are just roaming around hospital without any reason. and there are many new people who just shoot without any reason. We need police for that. And most importantly if police will be in city then people would think twice before doing anything wrong. You guys should maybe assign duties to officers. for eg: make a police team and tell them to work in server #1 and so on. I think atleast u can make 2-3 seperate teams. Have a good day!

**Comment by DaxterPancake** [comment]
This is not a suggesting relating to scripts in the server. 

I'd suggest talking to staff about this suggestion.

Closing this issue.
