### ISSUE TITLE
Bug report:i am ram prasad, Pratham#5181,  i was at hospital and entered my car and then got turned into a helicopter and my friend sitting in the car with me got also transformed into a helicopter.i have screen recording and screen shots of it as well . and then the host kicked me out and now i am unable to rejoin kindly fix this.

### ISSUE THREAD

**Issue by tigerzindahai26** [InZidiuZ/op-framework-issue-tracker#1056]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Fill out the template properly.

**InZidiuZ**
*OP-FW Developer*
