### ISSUE TITLE
[vehicles/keys] missing own car keys after game crash

### ISSUE THREAD

**Issue by Ashpritish** [InZidiuZ/op-framework-issue-tracker#1057]
**Name:**
CriTicaLGaY#4459

**Summary:**
Old key system will be good or any new system for owned cars after game crash..

**Reason:**
So many ppl got crashed from game and lose there own cars keys and they have to hotwire there own car if its not locked..and if its locked then no chance...we have to retrieve for spending 250 dollar each time.

**Comment by InZidiuZ** [comment]
One solution to this issue, would be to cache/store players' vehicle keys server-side throughout the duration of the server's uptime. Any additional feedback from other players would be great, though, as I didn't even think this was an issue. 🤔

**Comment by Ashpritish** [comment]
after every crash we have to retrieve our vehicle or hotwire or lockpick..
Sometimes it doesn't retrieve..

**Comment by InZidiuZ** [comment]
Yes, but are you crashing a lot? Crashing has become a very rare occurrence for most now & people can go days without a single crash. Besides, the chances are your vehicle will have automatically despawned by the time you're back in-game & at it's location, no?

**Comment by Ashpritish** [comment]
yeah my game crashes a lot 4 to 5 times throughout a days or sometimes in
10 to 15 mins 4 to 5 times... don't know why...

**Comment by InZidiuZ** [comment]
What about the vehicles themselves? Are they still at the spots they were when you crashed after coming back?

**Comment by DaxterPancake** [comment]
For me and a lot of my mates, we hang out in one place most of the time (for example: The Lost MC) and we'll crash or maybe even log off for a little bit. We load back in, head back to the shop and our car/bike is still there, we just no longer have keys for our vehicle and have to try to hotwire it.

**Comment by Ashpritish** [comment]
and if its lock then no chance...

**Comment by InZidiuZ** [comment]
Keys will now restore when you reconnect to the server. They're also separate for different characters now. They'll reset on restart.
