### ISSUE TITLE
[?] Hangar Property / Aircraft Garage for Los Santos Aviation

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#1058]
Ori#4385

**Summary:**
Setting some airport areas or hangars as purchasable private property for the new Los Santos Aviation company. And inserting aircrafts/allowing planes to be stored in that property garage, therefore making them accessible by employees of the company that are given access to the garage through the housing system. This concept successfully shifts the focus away from whitelisting and lays the responsibility on the company's management to allow access through the current tools we have in-game.

**Reason:**
Los Santos Aviation is a new aviation company that provides legal pilot licensing as well as training for the public. The company is approved by the state and has a good system in place. There is a lot of RP in it, as well as business opportunities as pilots. Everything is regulated and people are enjoying the companies services in healthy ways.

The company is currently roleplaying stealing the planes from LSIA as "renting" them under a contract with LSIA. The selection of aircrafts that are available is very small and consists of a helicopter that only spawns in a small time frame. And 2 types of planes, one of which only spawns in a small time frame.

Having some sort of garage the company could access would prevent vehicle theft calls, provide easier, more professional, and more immersive access to planes. And hopefully, also provide us a wider variety of aircrafts we could use.

Here is the list of the variety of aircrafts we wish to have available in the garage (different aircrafts would be approved for operation internally based on types of pilots licenses, all these aircrafts are confirmed to be non-weaponized)
**Planes:**
Alpha-Z1 (alphaz1)
Besra (besra)
Cuban800 (cuban800)
Dodo (dodo)
Duster (duster)
Howard NX-25 (howard)
Luxor (luxor)
Luxor Deluxe (luxor2)
Mammatus (mammatus)
Ultralight (microlight)
Nimbus (nimbus)
Rogue (rogue)
Seabreeze (seabreeze)
Shamal (shamal)
Mallard (stunt)
Velum (velum2)
Vestra (vestra)

**Helicopters:**
Cargobob(2) (cargobob2)
Frogger (frogger)
Havok (havok)
Maverick (maverick)
Sea Sparrow (seasparrow)
SuperVolito (supervolito)
SuperVolito Carbon (supervolito2)
Swift (swift)
Swift Deluxe (swift2)
Volatus (volatus)

Airport vehicles for ground transportation because our vehicles keep poofing when we go out flying and come back:
Caddy(3) (caddy3)
XLS (xls)

If you are interested in knowing more about LSA (Los Santos Aviation) feel free to join the companies discord, or go through our detailed documents:

https://discord.gg/K8sXkam

https://docs.google.com/document/d/16DJvGnqUciUZ2n_U0JyqE1F7jEXzn7SSJTk6UQpSSuo/edit?usp=sharing

https://drive.google.com/file/d/1fVopYn6UafoLfH6aOWTsH7faWtRTGFsx/view

And here is a great video example of what were essentially trying to avoid by having a garage menu lol:
https://clips.twitch.tv/MotionlessIntelligentChowderWTRuck

**Comment by MrSnowSar** [comment]
+1

**Comment by kucej** [comment]
Yes! We really need something like this.

**Comment by Livius99** [comment]
We really need this around , this would give us a lot of new RP opportunities !

**Comment by MrSnowSar** [comment]
It would be a great addition to the server and would make a difference in RP for a lot of people.

**Comment by NovaPurpl3** [comment]
What if licensed flyers/boat drivers had the ability to purchase their own planes or boats? I know boat garages were being worked on but idk if that will come out or not?

**Comment by cwisdasaur** [comment]
Bump with new LSA Discord: https://discord.gg/5GNJwV

**Comment by cwisdasaur** [comment]
Bump with new LSA Discord: https://discord.gg/QYCXVbE

**Comment by Spitfire2k6** [comment]
This is definitely needed for any sort of decent Aviation RP to occur. A system where LSA employees can spawn in aircraft like PDM works do with cars. If you spawn the aircraft in you get the keys to said aircraft. I think this should all be very possible using the current tools we have in game.

**Comment by Spitfire2k6** [comment]
Is bumping allowed? I'mma bump it, tell me off it's it's not allowed. I need this in my life lol

**Comment by riedling11** [comment]
this is sorely needed.

**Comment by Smach90** [comment]
This is needed so pilots can get access to the aircraft without having to hunt one down.

**Comment by twooot** [comment]
We now have a spawner for planes fi you have a license
