### ISSUE TITLE
[?] Gun Running/Whitelisted Gangs

### ISSUE THREAD

**Issue by Clorox54** [InZidiuZ/op-framework-issue-tracker#1059]
**Name:**
Clorox#8063 - Douglas

**Summary:**
I am suggesting that we revert back to distributing illegal guns like we did before OP FW. Give the ability to purchase illegal guns to a whitelisted group that can appropriately distribute them without over saturating the market.

The pre-OP FW system allowed the Cartel to purchase guns like the AK-47 for around $30k and then they would turn around and sell the gun for around $35k this would allow members of the group and the organization to directly profit from the gun sale, but not in a way that would be game breaking. This would also help control the flow of firearms, making it more difficult to buy weapons, thus giving them more value. This would also encourage the white listed gang in control of the guns, to be much more cautious with them, because they would be much more valuable.

**Reason:**
As it stands right now, obtaining illegal weapons in the this city has become incredibly easy at a relatively low cost. For example for about $4,000 and just a little time, a group can go find a gun worth $20,000, which is pretty ridiculous. The cartel has tried to make gun running something only their group can do, which has caused the efficiency of gun running to sky rocket, thus making illegal guns not very rare, but rather easy to access.

I think both the police and the cartel would benefit and be happy with moving the system back to purchasing guns, rather than using keys to find them.

**Comment by Lilgrizz818** [comment]
Really good idea but if he was to do this he would have to do the same with Drugs also. It wont really be fair for 1 gang to have the only privileges cause i been holding down the coke plane for a while now and would love the same thing and thats coming from the OG cartel member : )

**Comment by McLovinzz** [comment]
As an outsider i think this system would not fit the city as of right now. There will be 2 org. (Red & Cartel) which will be unable to be overthrown, as they will have even more power.

**Comment by DaxterPancake** [comment]
Inziduiz has talked about not wanting to whitelist illegal activities at the moment due to the fact that he wants to be able to push the updates to all subdivisions. If we had whitelisted illegal activities it would push the admins to have to constantly make sure that something is being run by someone, which would be a lot of work for the staff to have to keep up with.

I'll keep this open so that he can comment on this.

**Comment by itslilbuddy** [comment]
Think its a great idea, and would keep peoples hand off guns who have been in the city for less than a week, or even a couple hours, but grizz it right, it would have to be for everything in the city, which I also think is a great idea.

**Comment by FilipQeh** [comment]
Huge improvement for RP if you actually have to know the right people to get a hold of these things. The mafia for cocaine, if you wanna buy weed you have to go to southside gangs & if you want weapons you had to know someone who knew someone apart of the Cartel. Would definitely make the server a better place trough more interactions. 

I do however understand the dilemma when it comes to subdivisions, but maybe you could let the staff there choose if they want it controlled or open for everyone.

Just my opinion on this.
- Frankie.

**Comment by NovaPurpl3** [comment]
Even if we had a whitelisted job that was called " Hacker " and it would be CDLS Intel to know how to hack it so they would need us in order to hack it. Could create RP with people trying to kidnap someone to hack it but not everyone in the group would need the said job class. same could be for the coke plane where it would be " Plane intel/Flyer" and others can still rent the plane but it actually rents the plane to them but doesn't receive any coordinates.

**Comment by Xwezio** [comment]
+1

**Comment by Pyrotimegamer** [comment]
Alltho i dont play that mutch anymore i still want to give my 2 cents on this. Personally I still think the people running the big drugs/ guns should be unafiliated people. This way any group that wants acces to these things should have a connect for guns 

For example 1 Main Gundealer the one that brings in all the weapons and lets say 2/3 Main Connects these guys know of who runs guns and what he really does. then these guys sell arround to the "Dealers" lets say 6 ish people these people then sell to the street

same with drugs. 

Only issue for this would be that this person should be a Insane roleplayer not letting petty feuds ooc interupt or hurt the roleplay in any way and this person should be verry active to provide the roleplay (also his trust should also be pretty active to distribute the guns)

thats my 2Cents thanks :)

Skull / Thor

**Comment by twooot** [comment]
This issue is not relevant anymore
