### ISSUE TITLE
Suggestion | healthy buy/sell RP

### ISSUE THREAD

**Issue by anuragkumarak95** [InZidiuZ/op-framework-issue-tracker#1061]
**Name:**
Who is suggesting this? Please include discord name.
anuragkumarak95#1597

**Summary:**
Write a short summary of what your suggestion is about.
while a vehicle is locked, other players can view the contents stored in the vehicle but not transfer to self.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This feature can really make buy-sell RP very reliable between players. The `seller` can put the items he/she is about to sell in a vehicle that he/she can `lock` eventually. after which the `buyer` can browse the contents of the vehicle to be sure that this deal is not a scam and the material in the discussion is actually there as promised. As the exchange of money is done, the `seller` can then `unlock` the vehicle and the `buyer` can pick-up the material. this can lead to a healthy `buy-sell ecosystem` in the game. I am just stating one of the million possibilities this can lead to.

**Comment by LostAI** [comment]
tf did i just read

-1 "healthy buy-sell ecosystem" sounds like an "always win" mentality which isn't good RP.

**Comment by DaxterPancake** [comment]
If a car is locked.. They wouldn't be able to go into it to see its contents..

**Comment by DaxterPancake** [comment]
I'm sorry but if you're worried you're about to get scammed then bring backup. Don't sell to someone you don't trust. Use a middle man.

I don't think this addition makes sense, personally.

**Comment by anuragkumarak95** [comment]
Oh ok, got it now. I believe I was thinking with the wrong mindset here. Let me close the issue
