### ISSUE TITLE
UnPredictable#5986 speaking here. Sir when I try to connect into a server which has 50-60 players already in my tokovoip status shows offline. please help me with this issue as I am facing it after reinstalling windows 10

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/op-framework-issue-tracker#1062]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

You a) did not fill out the template, b) TokoVoip is not a part of our framework and c) this should be redirected to the communities' help channels and not to a framework bug report.

**InZidiuZ**
*OP-FW Developer*
