### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by deartsylens** [InZidiuZ/op-framework-issue-tracker#1063]
**Reporter:**
INDIAN-NINJA#3113 , piyush00721
**Summary:**
when we steal or buy a car and lock it and unloack it , after that when we get inside vehicle the lights dont car dont work anymore. 

**Steps to Reproduce:**
just steal or buy a car , i mean u should have keys of the vehicle , just lock and unloack vehicle from outside and then start the car and check if lights are working or not.

**Expected Results:**
the lights normally should work

**Actual Results:**
bt in actual the lights are not working

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920*1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

india legacy

**Notes:**
if we dont have keys and we hotwire then lights work properly

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*

**Comment by deartsylens** [comment]
thanks sir

**Comment by deartsylens** [comment]
bt this bus is still there @InZidiuZ  , i tried it ,it is still present

**Comment by InZidiuZ** [comment]
The version this has been fixed has yet to be released anywhere, though...

**Comment by deartsylens** [comment]
THE HEADLIGHTS NEVER TURN ON AFTER LOCKING AND UNLOCKING VEHICLE FROM OUTSIDE , I ASKED SOME RANDOM  PEOPLE IN SERVER THEY ALSO AGREED AFTER TRYING IT  @InZidiuZ  , I HOPE YOU WILL FIX IT SOON , HAVE A GOOD DAY ;)

**Comment by deartsylens** [comment]
> The version this has been fixed has yet to be released anywhere, though...

Oh then its fine , thanks for the quick response :)
