### ISSUE TITLE
[illegal/chopshop] Bugged vehicles

### ISSUE THREAD

**Issue by Ayanangsh** [InZidiuZ/op-framework-issue-tracker#1064]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Butter_Naan https://steamcommunity.com/id/ayanangsh/

**Summary:**
Write a short summary of what you're experiencing.
When I go for the chop shop missions some cars spawn with zero fuel but when u start them they run and stop after a few seconds the car vanishes in thin air. If you kick the car or jump or do anything the fuel starts to show again but just after a few seconds it bugs again and vanishes
**Steps to Reproduce:**
Include what steps are needed in order to reproduce the issue.
Find the chop shop car 
2}  hotwire it
3} if the door automatically starts to open (driverside) the car is bugged. 

**Expected Results:**
What are the expected results?
The car will start and go a little forward and the engine will stop and after a few tries, it will vanish while moving.

**Actual Results:**
What are the actual results?
The Car Vanishes.

## Additional Information
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
you will not be able to Refuel that car.
**Game Resolution:**
What is your game's resolution?
1366x768
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID - 16067
Job- reporter
timestamp - 2020-05-23 02:17:08

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India (Blacklist 3)
**Notes:**
For anything else noteworthy

**Comment by InZidiuZ** [comment]
#1098
