### ISSUE TITLE
[game/inventory] Make jerry-cans usable.

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1065]
**Name:**
DooZolz#4014

**Summary:**
So basically if you have a jerrycan in your inventory, and you use it you can use that jerrycan to fill up the fuel level on your vehicle instead of having to go to a gas station. 

Example of when you would use this amazing item: Let's say I'm in an EPIC police chase and I'm very low on fuel but I luckily have a jerrycan with me. If I have enough time I can quickly get out of my vehicle and refill as much fuel up as possible and get back in rather than having to go to a gas station. 

**Reason:**
because what's the point of being able to buy a jerrycan when you can't even use it. That would clear up confusion.

**Comment by Ashpritish** [comment]
This will be great if u made jerry cans usable again..

**Comment by InZidiuZ** [comment]
This has now been added for 2.5.
