### ISSUE TITLE
[external/clothing] Change between peds & freemode models at clothing stores.

### ISSUE THREAD

**Issue by ScotsMan-07** [InZidiuZ/op-framework-issue-tracker#1066]
Name: 
ScotsMan#9078

Summary:
so to be able to change from a ped to a freemode model at the clothes shop to allow peds to make outfits that have mask so if they do illegal things its not just instantly warrant out for them  

Reason:
Because if you pick a ped you like and want to do illegal stuff you either have to get a admin to let you change to a freemode model ( that could take a little bit ) or be caught every time even if you get away from the law ( i dont just mean i want to escape every time i don't mind taking the L but its annoying to not wear a mask and the cops roll up and instantly know who you are)

**Comment by InZidiuZ** [comment]
A better alternative, I suppose, would be to create "mask" items and simply attach an object to your ped when it's used.

**Comment by twooot** [comment]
#2092 pretty much this
