### ISSUE TITLE
[illegal/guns] Keys being consumed, not hacking

### ISSUE THREAD

**Issue by RajKhanna12** [InZidiuZ/op-framework-issue-tracker#1067]
**Reporter:**
Discord Name-Tusharmittal09
Steam-http://steamcommunity.com/id/rajonrolls

**Summary:**
Once We fail The hacking To be done for gun heist,The next attempt Keys Get used As usual But No hacking Pops Up And RGB Keys Get wasted. 

**Steps to Reproduce:**
Try doing Gun heist And Fail The hacking Once Then Retry There Will No hack Popping Up. 

**Expected Results:**
Hacking Should pop up On Successfully Submitting the right set of keys in right order

**Actual Results:**
No hacking Pops up Even On Doing everythiNg right

## Additional Information NIL

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920*1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India Public
**Notes:**
For anything else noteworthy.
Nil

**Comment by InZidiuZ** [comment]
This is a wontfix util this system is rewritten.
