### ISSUE TITLE
[illegal/guns] Gunrunning sometimes not working

### ISSUE THREAD

**Issue by Deathvalleygaming** [InZidiuZ/op-framework-issue-tracker#1068]
**Reporter:**
DeathvalleygamingYt
https://steamcommunity.com/id/DeathValleyGamingYt/

**Summary:**
my problem is when we try to do gun heist in hacking place after that we do all that step clear but after using key the hacking not start some time before server restart and after server restart

**Steps to Reproduce:**
Please try to check coding and if there any problem so do re coding of that op hacking

**Expected Results:**
I am just expected that some people who not get gun during this issues they get gun after the issues solve
**Actual Results:**
there have some more bug in the so i ll some soon and i hope so you have to clear that all problems

## Additional Information

**Screenshots:**
I don't have screen shot i have video proof of that issues

**Game Resolution:**
1980x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
[https://drive.google.com/file/d/15EFlEn4jBWIZRHESBIYtRN5KJ5HQnJM4/view?usp=sharing](url)
**Server:**
Bangladesh

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is a wontfix util this system is rewritten.
