### ISSUE TITLE
[?] More jobs?

### ISSUE THREAD

**Issue by Deathvalleygaming** [InZidiuZ/op-framework-issue-tracker#1069]
**Name:**
DeathvalleygamingYT
https://steamcommunity.com/id/DeathValleyGamingYt/

**Summary:**
you have to give more job in server and you have to add a system of import and export in car order by giving player and you have to give framework for wizeal news building inside  interior
and also have add coffee store for hangout with friends vine wood coffee store inside interior
**Reason:**
because i see now a day's old player's getting bore doing same thing so like more creative things come then they get  some fun if you any one buy a plane or boat ya ship for private so please add if you want i ll just suggest you

**Comment by KillWisshh** [comment]
just for your information posting. Mayor (RaviCan't) told that Delivery job pay us 1000 bucks for one truck but its not like that. we are only getting max 550 dollars and salary after 5 minutes is only 16 dollars which is 4 dollars less than other jobs. And this is taking equal time to garbage in job completion but we are not getting extra things in this job thermite or other things. 
Just a suggestion, please increase the job salary for this job at least 1000 to 1200 dollars and 20 dollars after every 5 minutes like other jobs. This will really increase the legal job RP.

**Comment by APeXHe** [comment]
I m not able to enter phone number with keyboard , I have to select a digit and press enter , so ultimately I m not able to enter 
" - " symbol between and same problem with mouse control please do something!

**Comment by DaxterPancake** [comment]
> **Name:**
> DeathvalleygamingYT
> https://steamcommunity.com/id/DeathValleyGamingYt/
> 
> **Summary:**
> you have to give more job in server and you have to add a system of import and export in car order by giving player and you have to give framework for wizeal news building inside interior
> and also have add coffee store for hangout with friends vine wood coffee store inside interior
> **Reason:**
> because i see now a day's old player's getting bore doing same thing so like more creative things come then they get some fun if you any one buy a plane or boat ya ship for private so please add if you want i ll just suggest you

A lot of the jobs are being looked at for a revamp and more activities could be added in the future.

**Comment by DaxterPancake** [comment]
> just for your information posting. Mayor (RaviCan't) told that Delivery job pay us 1000 bucks for one truck but its not like that. we are only getting max 550 dollars and salary after 5 minutes is only 16 dollars which is 4 dollars less than other jobs. And this is taking equal time to garbage in job completion but we are not getting extra things in this job thermite or other things.
> Just a suggestion, please increase the job salary for this job at least 1000 to 1200 dollars and 20 dollars after every 5 minutes like other jobs. This will really increase the legal job RP.

Not all jobs pay $20.
You're being paid due to what you're having to do, for example garbage pays $16 every 5min because you can get items.
You're not having to do much to get your money so your pay is $16.
Mechanics have to wait for someone to call them or visit them at a mechanic shop, hence why they make $20.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
