### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Chetan9891** [InZidiuZ/op-framework-issue-tracker#1071]
**Reporter:**
steam profile - Chetan
steam code- 0:0:543322636
discord- chetan #6164
**Summary:**
i have total 16 weed when i starting packing them the procees has completed but the weed isnt packed and when i try to do so again its showing error that you dont have weed

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1366*768

**Player Data:**
character id : 22145
job data: Taxi, Downtown Cab Co., Amateur
Timestamp: 2020-05-27 13:40:09

**Server:**
Indian legacy server

**Notes:**
For anything else noteworthy.

**Comment by ravicant** [comment]
Hey Chetan i think without any proof how we can help u you should at least give use Video/Pic.

**Comment by InZidiuZ** [comment]
If still relevant, please recreate this issue when the template has been properly filled out.
