### ISSUE TITLE
[weapons/recoil] Suggestion | Drive-by Mechanic Nerf

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1072]
**Name:**
Doughnut#1718

**Summary:**
Making the weapon Aim relative to the moving vehicle in third person, like first person and adding more recoil to drive-by shooting

**Reason:**
seeing a single player shoot down about 10 guys while driving a vehicle with a Draco in their hand has become an almost normal occurrence, that and the fact that the Draco is an SMG that has no recoil inside of a vehicle, much like all other weapons, has made it a very boring thing to be in the recieving end of the fight. in my opinion this should be nerfed in some way if it's possible.
what i'm suggesting is that the aim of the gun moves relative to the car, meaning that if you want to shoot accurately from a vehicle you would have to be stopped, meaning that your oponent has better chances to strike you, the way a vehicle is used in firefight is moving cover, which isn't realistic at all might i add, a 9mm easily goes trough the side of a door, even a .22 could if the door's thin enough. 
aside from that the fact that crims can shoot at cops with automatic weapons from vehicles while cops can't unless they have a helicopter far away in the sky makes firefights with criminals way too one sided, almost all troopers have been in a firefight where officers outnumber criminals in odds 3:1 and still end in the ground and/or dumped in the water. i've left PD 3 times just because it's not fun when it comes to firefights, and every single firefight that i'd been involved in the weeks prior to banks' Permadeath had been the same, officers catch one guy, that guy somehow has backup, there's a shootout in the back of pd with 6 officers and 3 crims, every crim is inside of a vehicle with MK2 automatic weapons and always moving and even when police backup arrives everyone still ends up in the ground. 
this is probably not going to change because most people in the city are crims, and that's the majority, but at least changing the drive-by mechanics would be a step in the right direction for balance.

**Comment by InZidiuZ** [comment]
The entire recoil system is being redone for 2.5. This will nerf in-vehicle firing as well as make "custom crosshairs" obsolete in order to create a more fair experience for everyone. More information will come on this system once it's being pushed to live servers.
