### ISSUE TITLE
[game/login] Death on spawn

### ISSUE THREAD

**Issue by fawad1k** [InZidiuZ/op-framework-issue-tracker#1074]
BigDaddyF#5462-  Steam SJ

So every time I log in aka come into the city and I want to spawn at my house that's at paleto bay, I die at the entrance of the house

when you are in the menu where you choose where you spawn, then you pick the paleto bay house. Then you die at the main entrance

To spawn and be used as a safehouse

die in the main entrance

## Additional Information

https://medal.tv/clips/25199192/d1337TW5X2n3 clip of how it happens

1920x1080

**Player Data:**
id- 4164-Job, Mechanic, Los Santos Custom, Tow Driver
**Server:**
North America(Canada)

No

**Comment by InZidiuZ** [comment]
This might be resolved with the rewritten core. If this is still an issue after 2.5, please create another issue.
