### ISSUE TITLE
Fps drops

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1075]
**Reporter:**.
RitikBakshi#4798

https://steamcommunity.com/id/sutta69/

**Summary:**
Legacy india server is very unoptimised i have a high end pc but still getting frame drops and several shutters

**Steps to Reproduce:**
just play in legacy india.

**Expected Results:**
the game should be running smooth cuz i have a high end pc 

**Actual Results:**
game is lagging , frame drops and shutters

## Additional Information
i have played on other servers and the game was running awesome and also i have played different games on high graphics setting it was running smooth... its problem with legacy india

**Game Resolution:** 1920*1080

**Player Data:**
RitikBakshi 
Id-4082.

**Server:**
India.

**Notes:**
Keep in mind that i have a high end pc and every game in running smooth so it’s not my pc

**Comment by InZidiuZ** [comment]
If still relevant, please create a new & more detailed issue. This has no information I can use to resolve the issue you're facing. Include a repro, PC specs, screenshots, etc.
