### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Gianniii12** [InZidiuZ/op-framework-issue-tracker#1076]
**Name:**
Who is suggesting this? Please include discord name.
Gianni👻#5422

**Summary:**
Hi to all the Legacy Roleplay community, I and all the staff of Legacy Italia have thought of proposing something innovative and never seen anywhere else in the world, since our name is a chain of Roleplay servers scattered around for the world we had the idea of ​​bringing these Italian, Indian, American, etc. servers together, in a single server or ours, for example the Italians are in the city, the Indians at nord etc. etc. then it will also be created in multilingual , there will be customs to move from one place to another and create an absurd and never seen RP, what do you think?

**Reason:**
Why would your suggestion be a good addition to Legacy?
Because in my opinion it would create an RP different from the others

**Comment by InZidiuZ** [comment]
This issue tracker is strictly used for the framework's development. Please take other matters to discord, though I myself think this idea is interesting & unique.
