### ISSUE TITLE
Bug report- Vehicles Headlights Issue

### ISSUE THREAD

**Issue by GaM3rShadow** [InZidiuZ/op-framework-issue-tracker#1077]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GaM3rShadow#3921. https://steamcommunity.com/id/GaM3rShadow

**Summary:**
Write a short summary of what you're experiencing.
Vehicle Headlight Issue.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take personal vehicle or citizen's vehicle lock it and unlock it

**Expected Results:**
What are the expected results?
After sitting on vehicle turning on headlights it should light up.

**Actual Results:**
What are the actual results?
After sitting on vehicle and turning on headlights it doesn't turn on.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1280x720

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character Id:7 - Job Data: Transportation, GoPostal, Delivery Job 
Timestamp: 2020-05-29 21:30:41
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Legacy Roleplay Bangladesh
**Notes:**
For anything else noteworthy.
This issue is with every vehicle and everyone

**Comment by z-Lunar** [comment]
Which vehicles in particular?...

**Comment by GaM3rShadow** [comment]
every vehicle

**Comment by InZidiuZ** [comment]
This issue has already been fixed.
