### ISSUE TITLE
[game/items]  Cocaine usage animation

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1078]
**Reporter:**
DooZolz#4014
https://steamcommunity.com/profiles/76561198185121513/
**Summary:**
When I use cocaine bags it puts me into an animation where I'm taking a pill. 

**Steps to Reproduce:**
Change the animation to some sort of "snorting" animation 

**Expected Results:**
When you use cocaine baggies you do a correct animation

**Actual Results:**
when using cocaine baggies you get put into a animation where ur taking a pill

## Additional Information

**Screenshots:**
No screenshots needed

**Game Resolution:**
1920x1080

**Player Data:**
https://gyazo.com/769407e9f68fdf661b68e74e250fb812

**Server:**
Main

**Notes:**
No

**Comment by InZidiuZ** [comment]
The reason for that animation is because I don't know of a "snort coke animation". If you have the name of one, feel free to post it here, otherwise I'll close this.

**Comment by ShelbsShelbs** [comment]
If the "animation" was used in a cutscene then would it be an animation of some sort still? I found this https://youtu.be/t3g9Ux6oCZA?t=39 but it's not the name of the animation.

**Comment by ShelbsShelbs** [comment]
Maybe this: snort_coke_a_male2

**Comment by DaxterPancake** [comment]
We have an animation sorted! Cheers guys!

**Comment by InZidiuZ** [comment]
A new animation has now been added.
