### ISSUE TITLE
Progressbar Error and Mhacking Error

### ISSUE THREAD

**Issue by RajKhanna12** [InZidiuZ/op-framework-issue-tracker#1079]
# Legacy UI Bug Report
Discord - tusharmittal09
http://steamcommunity.com/id/rajonrolls

**Summary:**
No progress bar shows up While Robbing houseS(you Feel Safe progressbar) Also No retrieving card Progressbar While using atm And Also Various other cases
When Trying to hack Only starting hAck box appears And after that Hacking disappears thereby failing the hack

**Steps to Reproduce:**
dont know 

**Expected Results:**
Progress bar Should appear in all above mentioned cases as Well as Hacking ShoulD Also appear

**Actual Results:**
What are the actual results?
Progress bar as well as Hacking doesnt Show up
## Additional Information
Nil
**Screenshots:**
Nil
**Game Resolution:**
1920*1080

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
You need to provide screenshots and more information. Please re-make this bug report and fill ALL required areas, including screenshots or a video of what you're experiencing.

**Comment by RajKhanna12** [comment]
Reinstalling fivem Helped Thanks for replying BTW

**Comment by DaxterPancake** [comment]
Glad to hear it!
