### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by ashish368** [InZidiuZ/op-framework-issue-tracker#1080]
I'm Facing fps drop issue. My laptop is specifications is also good Ryzen 5 Prosessor, AMD Graphics card, 8GB ram. I cam smoothly play the heigher games but i'm facing this problem in only FiveM Legacy Server's Please Resolve thi issue.. need help... Its to much irritating During RP. Big Request 🙌🏼
![IMG-20200530-WA0002](https://user-images.githubusercontent.com/66172967/83331370-9328ed00-a2b3-11ea-9817-bca02d44f72e.jpg)

**Comment by SamratAsho** [comment]
I am also facing the same problem

**Comment by harshu0914** [comment]
same here bro till yesterday morning it was running smoothly but after that it starts lagging

**Comment by SamratAsho** [comment]
Yep

**Comment by DaxterPancake** [comment]
Follow the bug report template to report things like this.

Go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose) to make one.

Closing due to not using a template.
