### ISSUE TITLE
Car spawns

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1081]
**Reporter:**
RitikBakshi#4798 
https://steamcommunity.com/id/sutta69/

**Summary:**
 while roaming in the city there’s a glitch in which locals cars spawn or sometime it disappears from the road that makes the game broke

**Steps to Reproduce:**
just explore the city.

**Expected Results:**
the locals car should be on point and not spawn or disappear or float in the air

**Actual Results:**
locals vehicle are floating in the air, disappearing and spawning like magic

**Game Resolution:**
1920*1080

**Player Data:**.
RitikBakshi 
Character id-4082

**Server:**
India
.

**Comment by DaxterPancake** [comment]
This is an issue that comes with OneSync. This is not a server issue as it'd be up to FiveM tp fix these types of issues, not us.
