### ISSUE TITLE
[?] Bug report- lagging very much

### ISSUE THREAD

**Issue by harshu0914** [InZidiuZ/op-framework-issue-tracker#1082]
**Reporter:**
discord name-harshu914#1654 and steam profile-http://steamcommunity.com/id/harshu0914/

i am facing very much lagging from yesterday evening in legacy roleplay server and some error is coming in bottom right corner but most importantly lagging is very much but my pc has enough specs. to run fivem gta rp smoothly

it should not lag but it is lagging from yesterday even though my internet speed is also very good and my pc has enough specs to run fivem gta rp smoothly

And this resource timeout error is also coming mentioning to contact the server owner to resolve the issue you can see in below screenshot highlighted with arrows

**Screenshots:**
![prblm](https://user-images.githubusercontent.com/65644348/83443327-2bb39e80-a467-11ea-92c4-9d1f295f444d.jpg)

**Game Resolution:**
1920 x 1080

**Server:**
legacy roleplay india 1,2,3,4, etc.  (legacy roleplay india all servers)

in all legacy roleplay india servers this problem is coming please solve it....

**Comment by InZidiuZ** [comment]
Does this happen at a constant?

**Comment by RitikBakshi** [comment]
> Does this happen at a constant?

Yes it happens constantly with me too i have high end pc

**Comment by InZidiuZ** [comment]
Constant as in from the time you join, every time? I've joined too, but can't reproduce anything...

**Comment by TRIANGLEEYE** [comment]
#1082 same problem
![20200611195640_1](https://user-images.githubusercontent.com/66789919/84404263-3cf96980-ac24-11ea-90ca-43a4f4ceb28c.jpg)

**Comment by InZidiuZ** [comment]
This was investigated and found to not be an issue with the framework itself. I'd explain why it happens but it'd take me way too long. Changes preventing the resource warning from appearing is planned to be added in the future, though.
