### ISSUE TITLE
[?] Bikes near spawn

### ISSUE THREAD

**Issue by Gianniii12** [InZidiuZ/op-framework-issue-tracker#1083]
**Name:**
G.x2#5422

**Summary:**
Write a short summary of what your suggestion is about.

Add a blip to the spawn to buy bikes

**Reason:**
Why would your suggestion be a good addition to Legacy?

Because new users don't know how to move

**Comment by z-Lunar** [comment]
tbh, with the newly added Tram system its not really needed.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
