### ISSUE TITLE
[game/items] Repair kits don't work

### ISSUE THREAD

**Issue by Gianniii12** [InZidiuZ/op-framework-issue-tracker#1084]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
G.x2#5422 Gianni
**Summary:**
Write a short summary of what you're experiencing.
Repair kits don't work

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Buy repair kit you use it and it does not work and if you use it continuously the engine is destroyed

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

That when I use it the engine repairs itself

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1680x1050

**Player Data:**
Write /info whilst ingame and provide the information you're given.

id 1466 job data Madrazo Cartel

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Italy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved for 2.5.
