### ISSUE TITLE
[animations/emotes] Command to take hostage

### ISSUE THREAD

**Issue by LoseBaida** [InZidiuZ/op-framework-issue-tracker#1085]
**Name:**
Discord: Lose

**Summary:**
add the command to take hostage

**Reason:**
Because for me is a good thing for do better rp
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66392208/83695947-7b2ad380-a5fb-11ea-98f9-ed8a6af099e4.gif)

**Comment by MukeshKC607** [comment]
Add It Will Be More Realistic

**Comment by iLikeAss3** [comment]
It will but you also have to consider power gaming angle.

**Comment by DaxterPancake** [comment]
Closing in favour of #1661.

Thank you,
Daxter.
**Project Manager.**
