### ISSUE TITLE
[jobs/dealership] DIGITAL PDM

### ISSUE THREAD

**Issue by yadav-rohit** [InZidiuZ/op-framework-issue-tracker#1086]
# Legacy Phone Suggestion
Reb0n(>_<)#6120

I think there should be a digital PDM procedure where you can get appointment and register for cars and after that get a appointment from pdm manager and go there and get our vehicle without wastage of time.
And prevent people rushing at place

I think this should be done because many time when we go to pdm there is no pdm manager and we have to go multiple times which waste many of our time , it would save time

**Comment by iLikeAss3** [comment]
Totally disagree! This would ruin PDM experience. Buying digitally will destroy rp during buying cars. and totally destroy PDM jobs. What do you expect PDM employees to do then?

**Comment by yadav-rohit** [comment]
Bro my idea was of only getting an appointment digitally because when ever
u go pdm is not always available and when he is available then there are
lots of people shouting there so as if they will get appointment it would
make it better

**Comment by InZidiuZ** [comment]
This will not be done at this time.

**Comment by yadav-rohit** [comment]
Ok brother 👍maybe in future
