### ISSUE TITLE
[illegal/weed] Weed 1oz > 4x 1oz. Weed  packing

### ISSUE THREAD

**Issue by GaM3rShadow** [InZidiuZ/op-framework-issue-tracker#1087]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GaM3rShadow#3921
https://steamcommunity.com/id/GaM3rShadow/

**Summary:**
Write a short summary of what you're experiencing.
Trying to pack less than 4 1oz. The system shows error of " Error: No weed (1oz) in your inventory" and The 1oz get used and vanished from inventory

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take less than 4 weed 1oz. Go to weed packing and pack the weed

**Expected Results:**
What are the expected results?
The system will show the error " Error: No weed (1oz) in your inventory". The inventory will be same.

**Actual Results:**
What are the actual results?
The system will show the error " Error: No weed (1oz) in your inventory". The 1oz will be used/ vanished.

## Additional Information
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1280x720

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 7- Job Data: Transportation, GoPostal, Delivery Job
Timestamp: 2020-06-04 13:44:16

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Legacy Roleplay Bangladesh

**Video**
https://drive.google.com/file/d/1dPmgDsJr4z_naADalU76u421vQA4SX4M/view?usp=sharing

**Notes:**
For anything else noteworthy.
This issue is being faced by everyone.

**Comment by InZidiuZ** [comment]
This has now been resolved for 2.5.
