### ISSUE TITLE
GAME PERFORMANCE FIX

### ISSUE THREAD

**Issue by Basant4008** [InZidiuZ/op-framework-issue-tracker#1088]
**Name:**
Basu#3617

**Summary:**
Stable servers would help with the performance.Glitch fixes and bugs fixes.Addition of more police staff and ems in other servers as well.Usually other servers are have less or no police no ems.

**Reason:**
It would make gameplay better for everyone and even low specs pc people can play rp without lags is servers are stable.Addition of ems and police in other servers would help everyone.S1 and S2 are always filled as all the police and ems are there.

**Comment by InZidiuZ** [comment]
> Stable servers would help with the performance
...what? Aren't they already mostly stable?

> Glitch fixes and bugs fixes
Report bugs individually. Without information on what bugs you're referring to & no repro, how am I meant to solve your issues?!

> Addition of ems and police in other servers would help everyone
In absolutely *no way* is this related to the framework's development.

> It would make gameplay better for everyone and even low specs pc people can play rp without lags is servers are stable
I'm struggling to even make sense of this sentence... though if you're saying that more stable servers will improve people's FPS, then no, that won't help.

Closing...
