### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by harshsachd3v** [InZidiuZ/op-framework-issue-tracker#1090]
Harsh
Hashjacker#1089

Regarding fueling vehicles
In every fuel station, we are able to find a Jerry can, but cannot fuel vehicles . This is a big issue! I suggest there should be an option to refuel vehicle using jerry can. 

**Reason:**
This would save a lot of time ! Mostly new members does not remember to refuel and wonder why vehicle is not running. If the fuel is really low, we cant even see the fuel percentage cause vehicle doesnt even start. And they call mechanic and mechanic scams and charges in bulk. Not even any new user, sometimes even old users forget to refuel and towing the car takes huge amount of time. I.e calling mechanic, he coming, towing, taking to fuel station, etc. sometimes even the mechanic wonders why isnt vehical starting. Fueling through jerry can will save really huge amount of time !

**Comment by InZidiuZ** [comment]
See #1065.
