### ISSUE TITLE
[properties/properties] Level1 access to a house gets storage access for first enter/spawn

### ISSUE THREAD

**Issue by anuragkumarak95** [InZidiuZ/op-framework-issue-tracker#1091]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
anuragkumarak95#1597

**Summary:**
Write a short summary of what you're experiencing.
After giving level1 access of my house to someone, the guy should not have been granted access of my storage, but the other person could access all storage the first time he/she spawns inside the house. (only first time though)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
give level1 access to another player outside the house and ask them (to enter/spawn to) the house for the first time. he/she will be able to access the storage.

**Expected Results:**
What are the expected results?
the player that was granted level1 access should not be able to access storage.

**Actual Results:**
What are the actual results?
he/she gets access to the storage for the first enter/spawn in the house

## Additional Information
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India

**Notes:**
For anything else noteworthy.
Sorry, I couldn't provide any SS proof as the other person in my case was able to access my storage after I left the session and he/she spawned in my house for the first time.

**Comment by GaM3rShadow** [comment]
In legacy roleplay Bangladesh if someone gives level 1 access to anyone. He will be able to use parking and storage not /furniture . untill the access has been revoked or house owner pays the rent.

**Comment by InZidiuZ** [comment]
Level one permissions has always had access to the house's storages... Level two allows you to furnish the house, though level one don't. I think it had some other extras as well but I can't remember. Only visitors are unable to access storages.
