### ISSUE TITLE
[jobs/dealership] 

### ISSUE THREAD

**Issue by OmegaGAaming** [InZidiuZ/op-framework-issue-tracker#1095]
Reporter:
Name-Maya Bhai
Steam id-https://steamcommunity.com/profiles/76561199038367941
Steam 3 hex id-1100001404288c5
Discord id-OmegaGaming#6167

Summary:
I purchased a pdm grooti vision on finance.after purchasing the vehicle i retrieved the car in garage A .to check my car.then i saw that my Grooti Vission car replaced with Reaper.please help me.

Steps to Reproduce:
1-purchased Grooti Vision
2-stored in garage A
3-To check my car
4-GrootiVision replaced with Reaper

Expected Results:
Car should be Grooti Vision

Actual Results:
Grooti Vision replaced with Reaper

Additional Information
i have video proof of this situation
https://drive.google.com/file/d/1tGM5U6Dl_Kke95yNqC_cGYF4yXC36kBn/view?usp=sharing
Screenshots:
i already gave video proof.

Game Resolution:
1920 1080

Player Data:
In game name Maya Bhai
Character id-17392

Server:
India Legacy Server
   City 2

Notes:
Plz Help Me out Of this Situation i need SOLUTION I dont need THis Car I WAnt My vISION bACK.

**Comment by InZidiuZ** [comment]
Closing in favor of #1103
