### ISSUE TITLE
[?] Stab City house enter[E] option is not working

### ISSUE THREAD

**Issue by ShanuDey** [InZidiuZ/op-framework-issue-tracker#1096]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Shanu Dey; Discord ID = Shanu#5516; Steam=https://steamcommunity.com/id/shanudey
**Summary:**
Write a short summary of what you're experiencing.
When I enter in my stab city house the black loading screen never progress. But my other house enter and exit working perfectly like My Occupation Avenue house. "Error Log after pressing F8--> `scrpit-op-frameword:globalFunction: OnStatusChange` in red color"
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
After one time enter if I try to enter my house then this problem occure every time. I have 1gb free at ram that time of enter. tried restarting network and using VPN also. Only statcity house error. Ihave to quit FiveM and restart FiveM to spawn at different house to fix that infinite loop.

**Expected Results:**
What are the expected results?
After enter"e press". I should Enter to the house mean the interior of the house will load like does in my other houses.

**Actual Results:**
What are the actual results?
I am stauck at black screen of loading, My friend radio is working I can hear them but I can't speak and Black Loading never progressed (infinite loop)
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![SS1](https://user-images.githubusercontent.com/30226346/84055254-32479600-a9d2-11ea-9731-55fd319287cd.png)
![SS2](https://user-images.githubusercontent.com/30226346/84055260-3378c300-a9d2-11ea-9def-bb9a2cedbb2d.png)

**Game Resolution:**
What is your game's resolution?
1280x720

**Player Data:**
Write /info whilst ingame and provide the information you're given.
name= Shanu Dey, CitizenID=21729,  PhoneNumber=249-5728 
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India server
**Notes:**
For anything else noteworthy.
May be the OnStatusChange event at enter function of stabcity house causes bug at loading further interior. Bcoz other house are working perfectly and house robbery houses also get rendered in other place of MAP.

**Comment by InZidiuZ** [comment]
What is "stab citty house"...?

**Comment by AdeptCL** [comment]
I think he is referring to the trailers at Stab City, West of Sandy Shores. Also known as the Lost MC trailer park.

**Comment by OP-Blade** [comment]
> What is "stab city house"...?

I also dont really know but i guess he is talking about the infinite loading screen

**Comment by ShanuDey** [comment]
> What is "stab city house"...?

Stab
