### ISSUE TITLE
Addition of more police and ems

### ISSUE THREAD

**Issue by Basant4008** [InZidiuZ/op-framework-issue-tracker#1097]
**Name:**
Basant Singh/Basu#3617

**Summary:**
Please kindly add ems and police personnel to all servers as it would make game better for everyone.There is no ems in other servers and on death we have to respawn and our stuff is gone and have to buy again.

**Reason:**
It would make all servers balanced and quality rp would be done in all servers.Right now people go in other servers to grind only no to very less rp is done.Only S1 And S2 have police or ems others don't.Other servers are being used just to farm no one does rp no one talks just doing jobs and other stuff.

**Comment by DaxterPancake** [comment]
This is not a framework related issue, this is a community issue.

Therefore, I will be closing this.

Cheers,
Daxter.
Project Manager.
