### ISSUE TITLE
[Illegal/chopshop] hot vehicles are bugged

### ISSUE THREAD

**Issue by manikgoyal04** [InZidiuZ/op-framework-issue-tracker#1098]
BlueMoon#0135
https://steamcommunity.com/id/manikgoyal
Summary:
After the recent update Chop shop vehicles are bugged They either got disappeared or they spawn with a local driving that car around the city, this bugs makes chop Shop a lot difficult, at around 10 times I found a chop shop vehicle with a local driving it and I found it 1 mile away from its expected location and 2-3 times that vehicle got disappeared when I was hotwiring, if I wanna do chop Shop I'll not able to find that vehicle 50% of the times and I know how to do chop Shop, I know all the secret location where the cars generally spawns but still I can't do chop Shop because of this bug!
And sometimes radio chatter says For example - Vehicle name - oracle At street - baytree canyon road last seen near - paleto bay but bay tree canyon road is nowhere near than paleto bay its like 5 miles away from that road.
Steps to Reproduce:
Just connect to legacy indian server and try to do chop Shop and u can see it yourself!
Expected Results:
Chop shop vehicles are supposed to be Sitting at one place and we have to Hotwire that vehicle and deliver it.
Actual Results:
What are the actual results?
i am not able to find that vehicle 50 percent of the times Because of this bug.
Screenshots:
https://cdn.discordapp.com/attachments/699096380714647612/720330300114206852/Screenshot_410.png
Server:
Legacy Indian servers
Hope you will fix this issue, Thanks :D

**Comment by OP-Blade** [comment]
Yeah this bug is really a headache to other player and me too. The development team will look into this. Thank you for reporting this bug

**Comment by InZidiuZ** [comment]
This is a wontfix until the chop shop is redone. Would advise just staying away from the chop shop until then

**Comment by manikgoyal04** [comment]
Okay, then will you do some changes in chop Shop in next update or not?

**Comment by InZidiuZ** [comment]
Not next update
