### ISSUE TITLE
Jerry Can bug

### ISSUE THREAD

**Issue by SubhamMishra** [InZidiuZ/op-framework-issue-tracker#1099]
Why's not the jerry can bug fixed till date, brought more than 4 jerry can for 100$ each but none works on vehicle or general

**Comment by DaxterPancake** [comment]
Closing this due to not using the template.

The reason it is not yet fixed is because there hasn't been an update yet. 
Thanks for your feedback though.

Cheers,
Daxter.
Project Manager.

**Comment by InZidiuZ** [comment]
#1065
