### ISSUE TITLE
[game/inventory] Wear for items

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/op-framework-issue-tracker#1100]
**Name:**
Who is suggesting this? Please include discord name.
J.C. 
**Summary:**
Write a short summary of what your suggestion is about.
Weapon wear / Item wear

**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding some kind of weapon wear or general item wear so people can’t sit on items for months and months. Whether it’s guns, drugs or lockpicks and other general materials. It’s hard to put into words how I actually want to say this but I think it will discourage large periods of grinding and make there more of a demand on things. Especially guns bc as of now (myself included we are just sitting on loads of guns)

**Comment by DaxterPancake** [comment]
I'd love to see a system where items 'degrade' over time, forcing you to have to either 1: Maintain them with Steel, Aluminium, Scrap, Copper, Plastic or they become unusable.

**Comment by JC-5** [comment]
Yesssss even better!!

**Comment by InZidiuZ** [comment]
#872

**Comment by InZidiuZ** [comment]
Closing as there's already an issue created for this. Please go more in-depth as to how the suggested system would work, though. What's included in this post just seems like an introduction ._. Please use #872 for further discussion on this matter
