### ISSUE TITLE
Dying while spawning in my house

### ISSUE THREAD

**Issue by OP-Blade** [InZidiuZ/op-framework-issue-tracker#1101]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Priyanshu#2576 and my steam profile=https://steamcommunity.com/id/PriyanshuXD/

**Summary:**
Write a short summary of what you're experiencing.
The problem I am facing is when ever I am spawning in the server at my house, I straightaway randomly die without any reason and I have face it multiple times.
 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
In order to reproduce this scene, You need to have a house in Jamestown Street. Spawn in the Legacy India servers or any server. Then After the loading screen, you will be dead lying infront of the house
**Expected Results:**
What are the expected results?
The expected result should be that you will select your house and spawn there. And then your character will spawn inside your house.
**Actual Results:**
What are the actual results?
Actual result is that you choose your house and die when you spwan inside your house
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
 Currently no screenshots.
**Game Resolution:**
What is your game's resolution?
1366x768
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Name= Priyanshu OP, CitizenID=23693, PhoneNumber=781-5178
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Legacy India
**Notes:**
For anything else noteworthy.
The major thing is that only some people of the city are facing this issue curently.

**Comment by InZidiuZ** [comment]
Create a new issue if this is an issue on 2.5.
