### ISSUE TITLE
[?] Military additions

### ISSUE THREAD

**Issue by Gianniii12** [InZidiuZ/op-framework-issue-tracker#1102]
**Name:**
G.x2#5422
**Summary:**
Write a short summary of what your suggestion is about.
Hi everyone, on legacy italia a group of guys wanted to create the army, you can add Blip of the machine to Fort Zancudo
Blip helicopter and changing room always in Fort Zancudo? https://it.gta5-mods.com/vehicles/mh-60l-black-hawk https://it.gta5-mods.com/vehicles/m1116-humvee-unarmed-add-on

obviously they will make an adequate RP they will not go to town etc. their RP will be staying in fortzancudo and intervening in case of terrorism level 4

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would create a nice rp

**Comment by MaximaVoid** [comment]
This is a really great idea and now If there are more than 6 players involved in crime scene, they would be tackled by Army rather than kick/ban.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
