### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by farazarbi786** [InZidiuZ/op-framework-issue-tracker#1104]
**Reporter:**
Who is reporting this? Covid-19#3357

**Summary:**
I was play in India legecy SV 1  ,At the time of server restarting i was playing then server resarted but after restar i didnt came in server but now i am in server may bank account is having only $11 actually i was having $3523.

**Steps to Reproduce:**
I want my money back in my Bank Account

**Expected Results:**
I will get my money back.

**Game Resolution:**
1920x1080 60 Hz

**Player Data:**
Character ID 30277

**Server:**
India Server 1

**Comment by InZidiuZ** [comment]
Closing due to incomplete report.
