### ISSUE TITLE
1 server 

### ISSUE THREAD

**Issue by jaskaranbasra** [InZidiuZ/op-framework-issue-tracker#1105]
**Name:**
Who is suggesting this? Please include discord name.
hello my name is shaktimaan #2920
**Summary:**
Write a short summary of what your suggestion is about.
Bro my idea for your server make 1 server of 400 people  instead of 6 different servers of 68 players    in India legacy BL it would  increase RP exp .  hope you understand what i am saying .

**Comment by OP-Blade** [comment]
Your idea is good but if we create a server that big, it will create more glitches and bugs and more unstable.

**Comment by InZidiuZ** [comment]
Closing as this is not related to the framework's development. Discuss this within your community.
