### ISSUE TITLE
[illegal/chopshop] Change to the Chop Shop

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1106]
**Name:**
AdeptCL#0402

**Summary:**
Change to the Chop Shop script to allow a "chop list" to be created which contains up to 5 vehicles.

**Reason:**
I have seen this system being used in other servers and I think it would be a very good system to put in place.
Firstly, let me state how it would work. So every 1 hour period, a "chop list" gets added (maybe by /chop), and it shows all the different types of vehicles that are *hot*/*wanted* and only up to 5 vehicles per person. This would bring a system in place where there is a larger period of activity at the chop shop, and gives a reason to be there. 
Secondly, the way it would work would be that the "chop list" given to each person doesn't get smaller if someone else delivers a type of vehicle that is on your list. If you have a *comet* on your list and someone else has the same, if the other person grabs it and takes it to the chop shop, you would still have it on your list too until you have delivered a *comet*.
Thirdly, by having a system like this in place, I would say to slightly increase the amount of materials are obtained, while minimally decreasing the drop % of "expensive items".

Currently, due to bugs with vehicles sometimes not being around in the locations of the radio call, there is only a small % of the community that are following a roleplay path of something including the chop shop. Not only would it bring more roleplay experiences to those that currently control the location of chop shop, and it would also give more reasons for other groups to try take it over.

**Comment by manikgoyal04** [comment]
Nice suggestion +1

**Comment by manikgoyal04** [comment]
BTW any idea when will this suggestion will be pushed to the servers? chop shops needs to be reworked its bugged from almost 3 months and this effects economy of the server. i hope you will make changes in chop shop in the next update :(

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
