### ISSUE TITLE
[?] Ped issues

### ISSUE THREAD

**Issue by cr7soni** [InZidiuZ/op-framework-issue-tracker#1108]
**Reporter:**
Discord name: krishsoni123#6714 and steam profile link: https://steamcommunity.com/id/Cr_7soni/

**Summary:**
My game is too glitchy and whenever i make new character  and play with it then after changing my saveoutfit or restart the game it becomes green effect or any bug everywhere on every character and my character too. It changes my normal character to any other character. Everytime it is same issue whenever i start the game. And i dont know it is graphic issue or any bugs. Please help me.

**Expected Results:**
There is no expected result because i thought that there would be no lag and glitches or any bugs will be there.

**Actual Results:**
There is only one actual result that the bug issue or green effect on every character's body.

## Additional Information

**Screenshots:**
[https://prnt.sc/t1dp2u]() 
[https://prnt.sc/t1dn39]()

**Game Resolution:**
1920x1080

**Server:**
I am from indian legacy server 3.

**Comment by InZidiuZ** [comment]
This is unlikely to be an issue related to the framework. Try reinstalling GTA 5 & FiveM.
