### ISSUE TITLE
[jobs/ems] EMS Store

### ISSUE THREAD

**Issue by ArshvirSingh** [InZidiuZ/op-framework-issue-tracker#1109]
Skullbuster#9111

**Summary:**
Suggestion regarding the Ems inventory. 
I think there should be a ems inventory like pd inventory where ems can buy some essential stuff for cheaper price then the actual market like bandages which they always need and some food items and it will also be very nice if the vending machines at pillbox can actually be used to get some items from it. 

**Reason:**
It will really help ems to get over the financial crisis XD

**Comment by Imaghost1337** [comment]
+1

**Comment by T4NZIM** [comment]
+1 Pls do it

**Comment by MukeshKC607** [comment]
+1

**Comment by EvilGhost5** [comment]
+1 please do it!

**Comment by InZidiuZ** [comment]
An EMS store has now been added. Vending machines were also added earlier today.
