### ISSUE TITLE
[jobs/ems] See injuries on scene

### ISSUE THREAD

**Issue by abhishek-dixit7** [InZidiuZ/op-framework-issue-tracker#1110]
**Name:**
I'm Abhishek, game name thunder and discord id- THUNDER#7677

**Summary:**
Can we have the feature for ems where they can see the injuries of a downed person without specifically signing as a doctor, like when the go on a call they can see what kind of injury that person has so that they can do the roleplay according to it.

**Reason:**
My suggestion will most like enhance the ems roleplay and might make it more realistic.

**Comment by EvilGhost5** [comment]
This would be really great
