### ISSUE TITLE
features and suggestions

### ISSUE THREAD

**Issue by adivish** [InZidiuZ/op-framework-issue-tracker#1111]
Dear Admins,
It will be good if we move towards a digital city. We should focus more digitally . So you can add some new apps like whatsapp and Mobile banking
Why to add those apps?-
Whatsapp - To share pics to particular person or a group of persons ,Clicking pictures as evidence , clicking pictures of illegal activities going around the to report PD
Mobile Banking - To buy something a player need a to carry cash to the store , but if we introduce a Mbanking then it will be to pay directly at the stores , And also to prevent robbery you can make a rule that we can't ask a hostage to use mbanking to pay.
This was my suggestion you can also make changes to these things to make the RP experience to the next level.

Discord - RockstarAdii #9220

**Comment by InZidiuZ** [comment]
Only create one suggestion per issue. Please create new issue(s).
