### ISSUE TITLE
[game/phone] Whatsapp App / Group Messages

### ISSUE THREAD

**Issue by adivish** [InZidiuZ/op-framework-issue-tracker#1112]
# Legacy Phone Suggestion
**Aditya Vishal Shaw**
RockstarAdii#9220

**Summary:**
To add new feature in phone
It would be good if we get a new app in our phone which is whatsapp with some handy features which will enable the players to connect with other players more easily.

**Reason:**
Whatsapp - To share picture to particular person or a group of persons ,Clicking pictures as evidence , clicking pictures of illegal activities going around the to report PD. It will also help to capture some moments and building a strong community, which will further connect the citizens more digitally ,like - suppose a citizen finds a location and wants to share it with his friends then he need to talk to every single citizen one by one to tell about the location but with whatsapp he can send the picture to his friends directly and ask them to gather here at a particular time. 
And even more we can swift location sharing option to whatsapp to make it easy for all

This was my suggestion you can also make changes to these things to make the RP experience to the next level.

**Comment by Xwezio** [comment]
Don't believe this would happen without a new phone been created, which i believe is planned for the future.

**Comment by InZidiuZ** [comment]
This will be considered in the future. Though for now, 'phone' issues are being closed.
