### ISSUE TITLE
[game/phone] Banking App

### ISSUE THREAD

**Issue by adivish** [InZidiuZ/op-framework-issue-tracker#1113]
# Legacy Phone Suggestion
**Aditya:**
RockstarAdii#9220

**Summary:**
To add a new app in the mobile for Banking 

**Reason:**
Mobile Banking - To buy something a player need  to carry cash to the store , but if we introduce a Mobile banking then it will be easy to pay directly at the stores , And also to prevent robbery you can make a rule that we can't ask a hostage to use mobile banking to pay. Adding this app will enable the citizens to keep a check on their spendings where all the transaction will be recorded , this will highly help the citizens to manage their expenses and to pay rents and emi's and many mire things.

This was my suggestion you can also make changes to these things to make the RP experience to the next level.

**Comment by iLikeAss3** [comment]
It's really good idea, however this will reduce "Robbing RP" If players don't carry cash on them. It would be meaningless to rob someone.  You might still get some items. But still, it would reduce "Robbing RP" significantly

**Comment by InZidiuZ** [comment]
A "banking app" on the phone is planned, meaning you'd be able to check your bank balance (or cards' balances when that is implemented) as well as transfer money.

**Comment by InZidiuZ** [comment]
This is likely to be a thing with the new phone.
