### ISSUE TITLE
Add new cars in EDM

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1114]
**Name:**
RitikBakshi#4798

**Summary:**
You should add some new cars to EDM like Toyota fortuner, and some new bikes also like BMW R1250gs, Triumph Tiger etc .

**Reason:**
this vehicles will be great addition the EDM and many players will love it which is the main reason I provided the vehicle names. Also we are bored from the old vehicles in EDM so that’s why we need these vehicle

**Comment by DaxterPancake** [comment]
We appriciate your ideas.

New cars are coming with the new update.

Cheers, 
Daxter.
