### ISSUE TITLE
Add new cars to EDM

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#1115]
**Name:**
RitikBakshi#4798

**Summary:**
add some new cars to EDM and my suggestion will be :- Toyota fortuner, range rover sport, range rover evoque, Toyota Land Cruiser, BMW R1250gs and triumph tiger

**Reason:**
the vehicles I mentioned are very lovely and also many players will love it, especially indian players. These are very great additions and also we got bored from old edm cars

**Comment by Xwezio** [comment]
Daxter commented on your previous suggestion saying there will be new cars in the upcoming update. I don't believe any new cars will be added to current pack.

**Comment by DaxterPancake** [comment]
Again, thank you for your suggestion when it comes to cars. 
As it stands, we already have all cars ready to come out when the new update comes out.
You do not need to make this post again.

Thanks,
Daxter.
