### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Warrior2805** [InZidiuZ/op-framework-issue-tracker#1116]
Who is suggesting this? Please include discord name.

Warrior

Write a short summary of what your suggestion is about.

If possible please whitelist news and mechanic jobs and remove them from life invader and we could only give them the roles the same as ems and police. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
It will add to more proper rp as no one will directly take job and doesn't start repairing vehicle without any training of vehicle repairing. We have proper sections and department for news and mechanic jobs so it will promote rp and people will have fun.

**Comment by InZidiuZ** [comment]
Unless/until a full rewrite of how the jobs work is done, this won't happen.
