### ISSUE TITLE
Pd stuff

### ISSUE THREAD

**Issue by RajKhanna12** [InZidiuZ/op-framework-issue-tracker#1117]
**Name:**
!!xxdangerxx!!#2368
**Summary:**
Just A Small Suggestion,I understand That All Of Pd Stuff Cannot be Made Lootable But I Would LIke to suggest That Basic Items Likes Armour and Medkit Be made Lootable Since when We are In a Code red situation(Robber POV) its Generally 5 vs More amount of police officers. Therefore Making Pd Armours And Medkits Lootable Can situation Fair for Both PD And Robbers Side. 

**Reason:**
The reason I suggested This Is Because I Find It quite unfair That Pd Officers can Use Our Stuff Like guns And Armour for their use during a code red situation but same Is Not With Robbers. The concept Of keeping Prices lower for Pd Department Is Still a good idea .I would really be thankful If U Could Implement my suggested changes.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
