### ISSUE TITLE
Suggestion for a DJ Concert

### ISSUE THREAD

**Issue by shivaayyt** [InZidiuZ/op-framework-issue-tracker#1119]
**Name:**
Who is suggesting this? Please include the discord name.
𝕊ℍ𝕀𝕍𝔸𝔸𝕐#1428

**Summary:**
Write a short summary of what your suggestion is about.
Hii well I am a DJ and I love that part of me, I was wondering that can you put up a Concert as an event, surely I will DJ and I am very very sure that the crowd would love it. I also do live DJing on SHoutCast, if you would like to have a test run I can do that for you, I can do EDM, Trance, House Mix, Indian Mix, Mashups, and lots more, think about it.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Well I think if this happens first of all it would be the very first in RPing History and basically I am thinking about a big concert and yes its definitely gonna attract music lovers and a lot of players to the community. If you consider this just let me know I am right there in discord list and if u don't consider this just drop a "No" :)

**Comment by AdeptCL** [comment]
This isn't a framework related issue. This is something you can organise yourself in-character.

**Comment by InZidiuZ** [comment]
Not framework related. Feel free to create a new issue with suggestions as to what features could be implemented to easier allow this to happen. Though as @AdeptCL said, this is something you can organize yourself in-character and/or with your community.
