### ISSUE TITLE
House robbery freeze

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#1120]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Lars.#0181

**Summary:**
Write a short summary of what you're experiencing.
Game freezing on loading screen while trying to rob a house.
**Steps to Reproduce:**
Lockpick the door and try to enter the house.

**Expected Results:**
What are the expected results?
Being able to walk and rob the house.

**Actual Results:**
What are the actual results?
Game getting stuck on the loading screen, see screenshot below.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080.

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
EU/NA

**Notes:**
Screenshot: https://imgur.com/df2uHuE

**Comment by InZidiuZ** [comment]
Afaik this issue has since been resolved, can anyone confirm/deny?

**Comment by y0Razz** [comment]
Confirmed.
