### ISSUE TITLE
Seatbelt Change

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#1122]
**Name:**
Lars. #0181

**Summary:**
Lower the speed where the seatbelt stops working and you would fly out through the windscreen.

**Reason:**
With the speedadjustment of the cars (which is perfect) everyone is travelling at a lower speed which results that in 99% of the crashes the seatbelt still functions cause it's actually hard to reach 120mph nowadays.
Maybe lower the 120MPH mark a bit?

**Comment by InZidiuZ** [comment]
The belt system was remade when the HUD was, meaning they've never "stopped" working at a certain speed for quite some time. Feel free to create a suggestion to re-add such a feature.
