### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vishwajeet1132** [InZidiuZ/op-framework-issue-tracker#1125]
**Reporter:**
VEEJEE#1623

**Summary:**
Place and street dont match

## Additional Information

**Notes:**
While doing the chopshop mission many times i saw that the street mentioned is not in the area mentioned over radio. So vehicles are impossible to find. And secondly . Some vehicles are not there around the given locations

**Comment by InZidiuZ** [comment]
The vehicles original location wouldn't have a mismatch, it's most likely automatically despawned *or* taken by someone else. The chopshop is overall buggy and is set to be rewritten at some point in the future, so closing this.
