### ISSUE TITLE
Suggestion (For a New Role In RP)

### ISSUE THREAD

**Issue by Abzi00** [InZidiuZ/op-framework-issue-tracker#1126]
**Name:**
Abhimaan, Abzi#5333

**Summary:**
Due to many situations that I have seen in RP while doing it myself and of other players.
I believe there should be a Counselor in the city.

**Reason:**
In Legacy India, people are limited to very few type of situations, there are people trying to bring more situation and new type of RP so that everyone can enjoy and therefore similarly I believe that a Counselor would allow people to do new type of RP and maybe will also help to make a better experience for everyone.

**Comment by iLikeAss3** [comment]
What kind of counselor are you thinking? Like marriage counselor or what?

**Comment by DaxterPancake** [comment]
You mean a therapist? 
Which is a department in EMS?

This is a community issue, not an framework issue.
