### ISSUE TITLE
Beard problem

### ISSUE THREAD

**Issue by EvilGhost5** [InZidiuZ/op-framework-issue-tracker#1127]
Whenever i change saved outfits my beard gets removed, first i thought maybe its because i havent saved my beard in my outfit, so what i did was i delete all my outfit...went to the parlour and applied beard then returned and saved it but still whenever i change my beard just disappears.

**Comment by InZidiuZ** [comment]
Use the template(s).

**Comment by Devil-jk** [comment]
same issue with me how to fix it?
