### ISSUE TITLE
Housing - Buying Pre-Purchased Furniture in a Trailer (Maybe other houses) Causes an infinite Black Screen

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1128]
**Reporter:**
Bob Hess
https://steamcommunity.com/id/nohbob/
Nohbob#1028

**Summary:**
When purchasing attempting to use the pre-furnish feature on Calafia Road 5,  I entered an infinite black screen with a gray spinning wheel on the bottom right-hand side. 

**Steps to Reproduce:**
1.  Purchase Property
2.  /furniture
3.  Use the Pre-Furnish button
4.  Enter infinite load screen

**Expected Results:**
1.  To be removed from the house at the front door. 

**Actual Results:**
1. Black Screen that results in you having to f8 quit

## Additional Information

**Screenshots:**
https://imgur.com/a/krpw6Sh

**Game Resolution:**
2560 x 1440

**Player Data:**
Character ID: 86 - Job Data:  Mechanic, Los Santos Customs, Tow Driver

**Server:**
Main

**Notes:**

**Comment by b-hess** [comment]
Please note, when re-entering the server, you can spawn in the the space and it will be furnished.  However, re-entering the space causes issue  #1130.

**Comment by InZidiuZ** [comment]
Closing as this issue is the same as #1120.
