### ISSUE TITLE
Tuner Chip

### ISSUE THREAD

**Issue by Kristoffermyr** [InZidiuZ/op-framework-issue-tracker#113]
**Name:**
kristoffer#9080

**Summary**
Adding tunerchip to the game.

**Reason:**
Would get more high speed chases. And people could start using stolen cars at robberied etc. So they dont get stopped later on because they are driving the same car that was used in a robbery

**Comment by Revo1848** [comment]
could be a really good game changer for mechanics.Cars that are not good at X stuff could be changed

**Comment by SteezyRen** [comment]
> could be a really good game changer for mechanics.Cars that are not good at X stuff could be changed

My issue with this is some cars are supposed to be better than others regarding certain stuff. I don't want a stock supercar to have a hard time against a budgeted sports car with a tuner chip. Then there is no purpose of the supercar other than to flex if you can easily just budget with a sports car and throw a chip on it to have it perform in areas it was lacking purposely.

**Comment by Revo1848** [comment]
> > could be a really good game changer for mechanics.Cars that are not good at X stuff could be changed
> 
> My issue with this is some cars are supposed to be better than others regarding certain stuff. I don't want a stock supercar to have a hard time against a budgeted sports car with a tuner chip. Then there is no purpose of the supercar other than to flex if you can easily just budget with a sports car and throw a chip on it to have it perform in areas it was lacking purposely.

i see your point but this happens irl aswell some cars are built as sleepers and the supercar could just get a tunerchip to change up stats

**Comment by SirPiff** [comment]
Personally, I love this idea and it'd be awesome to have like underground racing knowledge, for example, if they only way you could get these would not by buying them off of someone or anything like that, but it had some sort of secret recipe once the item crafting system is introduced, making it really expensive + illegal. (Like some car modifications being illegal IRL)

**Comment by InZidiuZ** [comment]
Hey,

This has now been added, and will go live with the next patch.

**InZidiuZ**
*OP-FW Developer*
