### ISSUE TITLE
Housing:  On a Prefurnished Trailer, when attempting to re-enter into it, I get an infinite black loading screen

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1130]
**Reporter:**
Bob Hess
https://steamcommunity.com/id/nohbob/
Nohbob#1028

**Summary:**
On a Prefurnished Trailer, when attempting to re-enter into it, I get an infinite black loading screen

**Steps to Reproduce:**
1.  Leave a Pre-furnished Trailer after spawning at that location
2.  Attempt to re-enter into it.
3.  Infinite Black Loading Screen

**Expected Results:**
1.  Enter into the trailer and be able to use as normal.

**Actual Results:**
1. Enter into the trailer and get an infinite black screen. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

Screenshots:
https://imgur.com/a/krpw6Sh

Game Resolution:
2560 x 1440

Player Data:
Character ID: 86 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Comment by b-hess** [comment]
As a side note, when logging in, I was able to remove the pre-furnished option, and enter the trailer safely without loading into the infinite black loading screen.

**Comment by InZidiuZ** [comment]
Closing as this issue is the same as #1120.
