### ISSUE TITLE
[Phone Suggestion] GIVE ME A TITLE

### ISSUE THREAD

**Issue by SyedAbbuTurab** [InZidiuZ/op-framework-issue-tracker#1131]
# Legacy Phone Suggestion
**Name:**
Who is suggesting this? Please include discord name.
Abbu Turab
Dexter#2917
**Summary:**
Write a short summary of what your suggestion is about.
Spray paints is fun and it can be used in many ways. To troll someone/gangs rivalries or to take revenge by painting vehicles.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It's a unique and full of fun addition feature. I haven't seen this kind of feature in any other roleplay servers. If this added in legacy server then definitely other server user get's attracted to legacy.

**Comment by InZidiuZ** [comment]
...what? This is not a phone suggestion... Create a new issue. And maybe explain more what "spray paints" are in GTA, as I have no clue myself.
