### ISSUE TITLE
[external/clothing] /delete_all_outfits command

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1132]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
/deleteallclothing
**Reason:**
Why would your suggestion be a good addition to Legacy?
It’s a pain in the ass sometimes to go one by one to delete clothings. If you want to get rid of all of them for when new clothes get added you have to go one by one and delete every single one of them and it’s a pain in the ass. Same way if you get a reskin you have to delete them all. Think it’s a tiny thing but a lot of people would appreciate it.

**Comment by Xwezio** [comment]
+1

**Comment by CaptainVro** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing in favor of #1407
