### ISSUE TITLE
[illegal/stockade] Only one guy should be allowed to pick gold bars at a time

### ISSUE THREAD

**Issue by RusuSergiu** [InZidiuZ/op-framework-issue-tracker#1133]
**Name:**
Xellos#3869

**Summary:**
After doing 2 bank trucks I think only 1 guy should be able to pick up the gold bars because else cops won't make it in time for the bank truck. It is just like doing hit and run banks.
People can cut the RP every time they are doing one if they are 3 or 4 picking the gold bars.
If only 1 guy would pick the bars at a time would be fine i think.

**Reason:**
Bank trucks are free money and people are cutting the interaction with the cops.

**Comment by novapurple** [comment]
+1

**Comment by joevapes3** [comment]
I 1000% agree with this. +1

**Comment by twooot** [comment]
Bank trucks are very risky since you have to kill the guards and are usually considered code red. Also i feel like you would be able to have multiple people grab gold bars
