### ISSUE TITLE
PDM Outfits Suggestion

### ISSUE THREAD

**Issue by aggaming111** [InZidiuZ/op-framework-issue-tracker#1135]
**Name:**
Laspatya AG 
Discord ID : @AG 👑#8683
{ Senior Salesman of PDM [Legacy India BL] } 

**Summary:**
As a member of PDM, we have facing lot of problems for outfits selection we need some decals of Premium Deluxe Motorsport like this for back https://drive.google.com/file/d/1h8R9gPxFbLf9GY4DlXWzKWdkjPT350we/view?usp=sharing and for front > https://drive.google.com/file/d/1JuWz0vwjtqe3fpRq1k544kmx95g83a-S/view?usp=sharing please check this links for pictures, if these decals added we have lot of cloths in which we can design PDM outfits also we dont have PDM cloths for Female modules that's also a main reason, please look into this suggestion if will help us alot.

**Reason:**
As i already mentioned i am a PDM member also i designed cloths for PDM in Legacy Blacklisted server before but the problem is we cannot match that PDM tshirt with formal pants or we cant wear that track while working in PDM, if this decals added it would help us alot to design Male and Female modules as well, Thanks

**Comment by aanya143** [comment]
+1

**Comment by SwagstarGaming** [comment]
+1

**Comment by InZidiuZ** [comment]
This is not a suggestion nor a framework script/UI issue. Use the asset-related issue tracker.
