### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BlazeHarsha** [InZidiuZ/op-framework-issue-tracker#1136]
**Reporter:**
BlazeHarsha/YT.INC#8612

**Summary:**
there is a bug cant put garbage in the truck and cant even return back the truck.And one more bug to i cant get in my vehicle its says vehicle is busy due to that i died while i pressed F button

**Steps to Reproduce:**
please fix this issue

**Expected Results:**
i hope this will fix and wont happen to anyone

**Actual Results:**
still not fixed

## Additional Information

**Screenshots:**
yes
![Screenshot (130)](https://user-images.githubusercontent.com/67585473/86001286-507e4000-ba2c-11ea-9917-b8a84efd4480.png)
![Screenshot (131)](https://user-images.githubusercontent.com/67585473/86001290-51af6d00-ba2c-11ea-9e4c-181f3511b173.png)
![Screenshot (132)](https://user-images.githubusercontent.com/67585473/86001292-52480380-ba2c-11ea-81cf-5fea5979fab1.png)

**Game Resolution:**
1080p

**Player Data:**
character id - 114

**Server:**
legacy india whitelist

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Include proper "steps to reproduce" and not a "pls fix"...
