### ISSUE TITLE
official events should be organised by higher admins in One server jisme whitelist aur blacklist dono k players event m aa ske and uss server ki limit b like 150-200 players something honi chahiye with strict rulesSuggestion

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/op-framework-issue-tracker#1137]

**Comment by Bhavesh02** [comment]
Bhavesh Sachdeva......UnPredictable#5986
official events should be organised by higher admins in One server jisme whitelist aur blacklist dono k players event m aa ske and uss server ki limit b like 150-200 players something honi chahiye with strict rules. In this event log ek taraf apni performance de skte h aur dusri taraf catering ya or koi legal business kr skte h....property dealers can make customers. Winning prize m ek car ya ek bike b de skte h. One week type phle register krwa skte h log jinhe event m perform krna ho and ek decent si registration entry b ho skti h like 500-1000$.
This suggestion for events will give a boost to other player rp experince and also sabko ek new thing milegi server m sab logo ko. This will also provide high quality rp to each and every players. I think you should take a look after my suggestion as I really want a event to be happen like this is legacy roleplay INDIA server

**Comment by InZidiuZ** [comment]
Not a framework issue.
