### ISSUE TITLE
Morgue system

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#114]
**Name:**
SteezyRen#2828

**Summary:**
A morgue system that is implemented in the event that someone who was involved in activity against a cop that escalated it to code black and resulted in the cop having to kill the suspect. This suspect can now RP as being dead and the only option the cop has is.. well not sure yet. They either RP getting them treated, carrying them to the hospital by placing them in a trunk, and having a "doctor" RP that they have miraculously been brought back to life.

**Reason:**
Adding a morgue system will now cause people to spend time in the grave that would have been spent otherwise in a jail cell for their actions. This will also allow cops to RP with suspects in the event that EMS is not available. This also creates an RP scenario for EMS to evaluate suspects and determine if someone driving 165mph having a head on collision with another vehicle is ground to morgue them instead of just carrying them to a hospital. That being said, the check-in feature at pillbox is a loophole around the morgue system as someone can easily retrieve their "dead" friend and bring them to pillbox.

This is definitely hard to tackle and I wish you best of luck on integrating it :P
I wish I could be of more use but hopefully the community can throw some insight on this suggestion.

**Comment by InZidiuZ** [comment]
Hey,

I was initially going to add a morgue system, but started thinking, and don't believe we need such a system yet. Possibly in the future, but closing for now.

**InZidiuZ**
*OP-FW Developer*

**Comment by SteezyRen** [comment]
Yeah, as I was thinking about it I think it made more sense to have ICU instead of morgue since people don't and shouldn't need to RP "killing off" their character
