### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mezmer69** [InZidiuZ/op-framework-issue-tracker#1140]
**Reporter:**
@MezmeR#3274

**Summary:**
There is still some De-sync and sudden vehicle teleport issues happening in Indian subdivision Whitelisted server.

**Actual Results:**
These glitches giving an huge effect in chase RP and A lot problem in driving

**Game Resolution:**
1920x1080

**Server:**
Indian subdivision

**Notes:**
Plz try to fix this problem asap

**Comment by InZidiuZ** [comment]
This is a OneSync/FiveM issue.
