### ISSUE TITLE
Tattoos doesn't save

### ISSUE THREAD

**Issue by Giv3nPL** [InZidiuZ/op-framework-issue-tracker#1141]
**Reporter:**
Giv3n#0753 - https://steamcommunity.com/id/Giv3n/

**Summary:**
Tattoos doesn't save after reconnecting 

**Steps to Reproduce:**
Go to the tattoo shop - buy any tattos - reconnect - you don't have any

**Expected Results:**
Tattoos saves

**Actual Results:**
Tattoos disappear

**Player Data:**
https://i.imgur.com/wOJ3cZ6.png

**Server:**
Poland

**Comment by AdeptCL** [comment]
This is also happening on the main servers too, since the database wipe happened.

**Comment by MukeshKC607** [comment]
Yess This Is Happening!

**Comment by InZidiuZ** [comment]
This has now been resolved.
