### ISSUE TITLE
Bug report - /GSR 

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#1142]
**Reporter:**
Masik52#5834
https://steamcommunity.com/profiles/76561198397274352/home

**Summary:**
when attempting to GSR test an individual who's been firing a weapon  the result comes back at zero %

**Steps to Reproduce:**
have someone fire a weapon a lot perform /gsr result is zero %

**Expected Results:**
should return a positive gsr result

**Actual Results:**
returns a gsr result of zero %

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
main
**Notes:**
For anything else noteworthy.

**Comment by ishwarnigam** [comment]
Reporter:
LeMeSMASH#2984
https://steamcommunity.com/id/lemesmash101/

Summary:
Being alive after being dead, shows time to spawn but can move and do other things

Steps To Produce:
Have to die by any cause.

Expected result:
To be actually dead i.e. could not move from the position only by external force.

Actual Result:
Could move, throw punches, cannot be killed by any means, i.e. Gunshots, Melee Attacks, Jumping form great height, No vehicle damage. Until you press Enter.
![lol](https://user-images.githubusercontent.com/39857931/86081702-9500ee80-bab3-11ea-86e8-82b6971d1179.PNG)

**Comment by InZidiuZ** [comment]
This has now been resolved.
