### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ishwarnigam** [InZidiuZ/op-framework-issue-tracker#1143]
**Reporter:**
LeMeSMASH#2984
https://steamcommunity.com/id/lemesmash101/

**Summary:**
Being alive after being dead, shows time to spawn but can move and do other things

**Steps To Produce:**
Have to die by any cause.

**Expected result:**
To be actually dead i.e. could not move from the position only by external force.

**Actual Result:**
Could move, throw punches, cannot be killed by any means, i.e. Gunshots, Melee Attacks, Jumping form great height, No vehicle damage. Until you press Enter.
![lol](https://user-images.githubusercontent.com/39857931/86082985-b1eaf100-bab6-11ea-8fd5-2debaccbd26c.PNG)

**Comment by InZidiuZ** [comment]
Create a new issue with steps to reproduce. I was not able to reproduce this by "dying by any cause".
