### ISSUE TITLE
Bug report/ house robbery

### ISSUE THREAD

**Issue by mittalraghav49** [InZidiuZ/op-framework-issue-tracker#1144]
@Robin Rude#0308**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:** when we try to house robbery it ends with unlimited loading screen amd never enter the house
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Closing as this issue is the same as #1120.
