### ISSUE TITLE
Bug report/house robbery

### ISSUE THREAD

**Issue by tkajari** [InZidiuZ/op-framework-issue-tracker#1145]
**Reporter:**
Tejas kajari#5333
Steam username:- tejas_kajari

Sir im doing house robbery bt I can not enter in house 
Im stuck in black screen all the time i try to rob house

**Steps to Reproduce:**
Please solve the issue

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by SIMRANJEETBSS** [comment]
Yes

**Comment by InZidiuZ** [comment]
Closing as this issue is the same as #1120.
