### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by suyashkhare28** [InZidiuZ/op-framework-issue-tracker#1146]
**Name:**
 suyash khare discord name sarth khare#7925

**Summary:**
i request you for make 2 or 3 more server because there is more than 10 people in que every server so i request you we all are facing this problem now all are use help for this solution and i am sorry because i am weak in english
**Reason:**
we all are facing this problem

**Comment by AdeptCL** [comment]
If you can, support the server and you will get queue priority.
https://www.patreon.com/legacyroleplay

**Comment by manikgoyal04** [comment]
Everyone can't afford priority and in Indian servers there are like 80 players waiting in queue just to play

**Comment by ultrahacx** [comment]
But opening more servers cost much more than a single priority for a month + it's maintainance... I don't know though... Everything depends on Inzi

**Comment by InZidiuZ** [comment]
This is a community specific matter. Ask your manager(s).
