### ISSUE TITLE
garbage collection bug

### ISSUE THREAD

**Issue by amulaggarwal** [InZidiuZ/op-framework-issue-tracker#1147]
apparently, if we are going to collect garbage and done collecting all the garbage we can leave the truck anywhere and come back in any vehicle to the garbage headquarters and the mission is passed and we receive the money
so I think this needs to be fixed 
Well I have not tried to return back on foot maybe you should once look into it also but I confirm for other vehicles.

**Comment by InZidiuZ** [comment]
Use the available template(s).
