### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ChuK23** [InZidiuZ/op-framework-issue-tracker#1149]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Chu K#9451
**Summary:**
Write a short summary of what you're experiencing.
I was riding a bike then I crashed on a  location name board and died but after few minutes I woke up suddenly and I was able to do everything
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![20200630231833_1](https://user-images.githubusercontent.com/67654344/86162199-2745d880-bb2e-11ea-9c22-a207100cd0fa.jpg)
![20200630231227_1](https://user-images.githubusercontent.com/67654344/86162207-29a83280-bb2e-11ea-8fc3-556dbacf872e.jpg)
![20200630231610_1](https://user-images.githubusercontent.com/67654344/86162210-2a40c900-bb2e-11ea-8f39-272749423a88.jpg)

**Game Resolution:**
What is your game's resolution?
1920-1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Nepal

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Fill out the template properly.
