### ISSUE TITLE
Bug report cant purchase edm car

### ISSUE THREAD

**Issue by RRRFIGHTER** [InZidiuZ/op-framework-issue-tracker#1151]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
myself RRRfighter and my steam profile name Khaman

**Summary:**
Write a short summary of what you're experiencing.
i have Legendary priority pass and i cant purchase edm car i am facing problem

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
![20200701171947_1](https://user-images.githubusercontent.com/67693472/86245979-ed291500-bbc7-11ea-8554-20e4405a3482.jpg)

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This should now be resolved. If not, DM me on discord.
