### ISSUE TITLE
[vehicles/vehicles] Seatbelt change

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#1153]
**Name:**
Who is suggesting this? Please include discord name.
Lars.#0181

**Summary:**
Write a short summary of what your suggestion is about.
Disable the effect of wearing a seatbelt above a certain speed, making you fly out the vehicle.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would add something new to how the driving is on the server. Chases would be more interesting as people would have to focus on not to crash instead of just going full throttle 24/7.
It might even decrease the amount of people driving 100MPH+ through the city, who knows.
Made this suggestion regarding this screenshot: https://imgur.com/5gAo7kb

**Comment by novapurple** [comment]
+1

**Comment by novapurple** [comment]
I think anything above 70 should give you a chance. Even with the seatbelt on. And the faster you go the higher chance for this to happen? 70mph 5-10%, 85mph 25%, 95mph 45% , 100+mph 65% of a chance.

**Comment by iLikeAss3** [comment]
Yes I totally agree, But how about instead of flying out we kill them?  Like in road accidents. @novapurple  has suggested great idea. But I think we should just kill them at  speeds higher than 95 mph

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
