### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by shubhboy** [InZidiuZ/op-framework-issue-tracker#1154]
**Reporter:**
∂αякѕσυℓ ︻デ═一 💀#1950
https://steamcommunity.com/profiles/76561199031078142

**Summary:**
In garbage collector job when we go to location many of times message pop up "go to HQ" without collecting any garbage this issue facing many players please fix it asap

**Steps to Reproduce:**
get a waste collector job pick a truck go to location

**Expected Results:**
collecting garbage every time without any without failure

**Actual Results:**
particular location where we cannot collecting garbage
![bug 3](https://user-images.githubusercontent.com/65948827/86373979-a871ac80-bca1-11ea-9006-d8f8a5bf12fc.jpg)
![bug 2](https://user-images.githubusercontent.com/65948827/86374005-b1627e00-bca1-11ea-98b8-f81afb7ce1c6.jpg)

## Additional Information

**Screenshots:**
Check screenshot this locations bug everytime 
https://imgur.com/MkVzf5F
https://imgur.com/hta2Ckt

**Game Resolution:**
1366*768

**Player Data:**
Character ID: 669 - Job Data : Government, Waste Collector, Employee
Timestamp: 2020-07-01 12:24:39

**Server:**
Legacy Roleplay India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is a wontfix. For for in-depth reason, use the search function & look for reports on the same matter.
