### ISSUE TITLE
Ghost RP

### ISSUE THREAD

**Issue by Epicboy-Manas** [InZidiuZ/op-framework-issue-tracker#1157]
> 

> **Name:**
Epicboy#2157

**Summary:**
I am suggesting to add a ghost in the city. Only few people can access that by applying form. The ghost can be find in some particular areas(not in public place). He will have the powers like that of moderators. This will allows him the power to be invisible, teleport himself and also some magic powers like :-
1:- He will have the power to create a invisible circle in a small area from which the victim cannot be escape
2:- he could magically teleport a player to a place Very far from city (like an island, mountchiliad, under any bridge, cave and several haunted place) 
3:- He can give virus to the victim so that victim will feel dizzy and his health will continuously decrease. Only special doctors can fix him with special instruments. 
4:- He can also use a voice filter which will sounds more Realistic. He can talk in English for every player whether it is an American or an Indian (in some cases only) 
**Reason:**
I think addition to Ghost RP will create a terror in mind of people who travels alone around the city. I know in real life ghost doesn't exist but some people believe and assured that they have seen paranormal activity and something like ghost.Ghost will not take anything from the victim. He will only target few players so that the victims will share their experience to rest of the people and the that people will also start fearing from ghost. There will be strict actions against people who will not follow the rules and regulation. Rules will be Simple that he will not behave as normal citizen and he can do whatever he wants to the victim if the victim don't follow his instructions. Police will also be fear from ghost. The creator can add special things for ghost like the size and height of the ghost will be little greater than normal citizen.

**Comment by Epicboy-Manas** [comment]
Plz don't ignore this suggestion, I have put lot of effort and think before written this how this will affect in the RP 😚

**Comment by DaxterPancake** [comment]
This is a community event suggestion, not a framework suggestion. 

I suggest talking to your server leader/s about creating an event like this.

I will be closing this as it doesn't pertain to scripting for the framework.

Cheers,
Daxter.
Project Manager.

**Comment by Epicboy-Manas** [comment]
Can you plz where I can post this idea?

**Comment by DaxterPancake** [comment]
Speak to your community managers for the subdivison you play on.
