### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sumitmazu** [InZidiuZ/op-framework-issue-tracker#1158]
**Reporter:**
hi my name is sumit mazumder my discord id is hgh#6762  and my steam name is AM H1GH aF.

**Summary:**
whenever i try to spawn anywhere in the server i go below the map and i get spawned inside a motel from which i can not exit i cleared cache but still same bug

**Steps to Reproduce:**
i just try to spawn anywhere in the map and this happens

**Expected Results:**
i should spawn in the location i choose

**Actual Results:**
but instead i go under the map and spawn in a motel room

## Additional Information

**Screenshots:**

![Desktop Screenshot 2020 07 03 - 13 49 35 69](https://user-images.githubusercontent.com/67780465/86448213-136bc380-bd34-11ea-8007-07b4d16e6b55.png)

![Uploading Desktop Screenshot 2020.07.03 - 13.47.36.41.png…]()

**Game Resolution:**
1920 x 1080

**Player Data:**
my character id is 783
**Server:**
i am on legecy roleplay indian blacklist

**Notes:**
For anything else noteworthy.

**Comment by sumitmazu** [comment]
![Desktop Screenshot 2020 07 03 - 13 47 36 41](https://user-images.githubusercontent.com/67780465/86448637-a73d8f80-bd34-11ea-87e5-ee14bdcf81c7.png)

**Comment by sumitmazu** [comment]
and now i see a dead player with me

![Desktop Screenshot 2020 07 03 - 13 56 26 36](https://user-images.githubusercontent.com/67780465/86448898-0bf8ea00-bd35-11ea-939b-9c4c7c68bfc4.png)

**Comment by iLikeAss3** [comment]
Why not disconnect and spawn at train station?

**Comment by sumitmazu** [comment]
even if 

> Why not disconnect and spawn at train station?

even if i spawn in station it happens i spawn anywhere it happens

**Comment by InZidiuZ** [comment]
Are you not able to select the train station, or? Could you provide a video of this occurrence?

**Comment by sumitmazu** [comment]
yup

**Comment by sumitmazu** [comment]
BRO I CHECKED TODAY AFTER 2 DAYS IT IS FIXED BUT MY HAIR  GOT REMOVED
