### ISSUE TITLE
Able to walk even when dead.

### ISSUE THREAD

**Issue by ishaanmeena** [InZidiuZ/op-framework-issue-tracker#1159]
So, I was riding my card from front of pillbox and someone rammed into me, I went flying and died and could still walk while I was dead.

[http://www.mediafire.com/file/ayiagl720u0bmwx/FiveM_-_Legacy_Roleplay_India_%25235_Wiped_Recently_Custom_Framework_Active_Staff_Development_Join_us_%2540_discord.gg_ehNU9xP_2020-07-03_21-27-37.mp4/file](url)

**Comment by DaxterPancake** [comment]
I appriciate the report but please re-do your issue following the BUG template. Provide as much information as you can.

Cheers,
Daxter.
Project Manager.
