### ISSUE TITLE
Twitter verified tick

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-issue-tracker#116]
**Name:**Tankfurious

**Summary:**
possibilty of having a verified tick

**Reason:**
i feel it would be great addition to the patreons to have a verified tick on our in game twitter account to show that we are supporters. (if possible)

**Comment by SteezyRen** [comment]
I actually like this idea. Another incentive for people to support the server.

**Comment by Anderzenn** [comment]
Hey :)
This is a great idea and will be implemented on the new phone.

**Anderzenn**
*OP-FW UI Developer*
