### ISSUE TITLE
[jobs/*] New job system to ensure people don't farm paychecks and actually work

### ISSUE THREAD

**Issue by Niveet** [InZidiuZ/op-framework-issue-tracker#1160]
**Name:** iLikeAss3#7122

**Summary:** A new system to make sure people actually work. So I've noticed people taking jobs which provide high passive incomes, and not actually work. So my idea is to make it so that If anyone doesn't work at least once in in-game day or two. They would be fired from the job meaning they can't select the same job for at least 5 IRL days. 

**Reason:**
This new system will make sure people work. This would also solve people claiming passive incomes. Moreover, If you want to have a leave of absence from the job people will have to set their job as unemployed before going out with friends. much like real life. As in real life, we can't just bunk our jobs and work when we please,

**Note:** This is ofc a premature idea, But this does sound promising

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
