### ISSUE TITLE
[game/miscellaneous] Ability to see ped messages in chat

### ISSUE THREAD

**Issue by Giv3nPL** [InZidiuZ/op-framework-issue-tracker#1161]
**Name:**
Giv3n#0753 - https://steamcommunity.com/id/Giv3n/

**Summary:**
Making the ME/DO/ATTEMPT command showing in the chat, not only 3dtext

**Reason:**
it's mostly for ems and ppl that use this commands a lot
Sometimes they type a lot of things on me/do/attempt, and they need to remember it 

So when this commands will show in the chat too, they will need only to scroll up to see every me/do/attempt instead of asking to type again.

**Comment by Giv3nPL** [comment]
Another quick thing, sometimes ppl can't even see the me/do

**Comment by InZidiuZ** [comment]
The ability to toggle such a feature has now been added. Use /ped_messages to toggle it.
