### ISSUE TITLE
[game/rockstar_editor] Adding rockstar editor [the function to make video's]

### ISSUE THREAD

**Issue by Giv3nPL** [InZidiuZ/op-framework-issue-tracker#1162]
**Name:**
Giv3n#0753 - https://steamcommunity.com/id/Giv3n/

**Summary:**
Adding a option to film so you can make some quality video's/photo's for the server
FiveM added a function to use the rockstar editor in FiveM, but not the function to make video's

**Reason:**
Cool feature for making some quality photo/video's I would love to see some beautiful screenshot from players, it can be used in multiple ways, even making you're own movie for the server

**Link**
https://forum.cfx.re/t/release-clipsaverv-v1-2-0

**Comment by InZidiuZ** [comment]
This has been added with version 3150. Hold ALT to use.
