### ISSUE TITLE
[illegal/racing] Improved racing system

### ISSUE THREAD

**Issue by ItsTehLegend** [InZidiuZ/op-framework-issue-tracker#1163]
**Name:**
William Buttlicker (ItsLegend#0913)

**Summary:**
I want there to be a better system for creating and starting up races. I want to be able to hold a bunch of races with ease and people able to join easily as well. Maybe something where you can create races and save them for a later time. Maybe something like nopixel has but not saying exactly that. If anything just something where you can set up the checkpoints your self. Possibly even share them with others who want to hold races.

**Reason:**
This would bring a new option for people to hang out and show off their cars that they worked so hard for and if they win a nice way to make a little cash. I want to be able to start a big underground racing league that people will be excited about and wanting more.

**Comment by InZidiuZ** [comment]
Closing in favor of #840.
