### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by abhishek-dixit7** [InZidiuZ/op-framework-issue-tracker#1164]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
THUNDER#7677
https://steamcommunity.com/profiles/76561198986668541/

**Summary:**
Write a short summary of what you're experiencing.
When I do escort command on a character and he gets dc'ed than my character gets bugged out i.e. in the state of escorting a patient which prevents me from running and jumping.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Just escort someone and tell the escorted person to disconnect, and you'll get bugged.

**Expected Results:**
What are the expected results?
Well when something like this happens doing escort again should either make unbugged again.

**Actual Results:**
What are the actual results?
But nothing sort of this happens, now in order to get unbugged you have to escort someone else who is in the server and than escort him again.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920*1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is a wontfix as it's related to a deprecated system.
