### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by scortendazlar** [InZidiuZ/op-framework-issue-tracker#1165]
**Krishnendu kar
Discord-  scorten#3609 :**

**Spwan and break oxy RULE:**

Plz make a rule ... No one spawn in oxy place and told ki kab se huj main its so irritating.if u don't wanna do this then in future its convert into big issue.
Thank you

**Reason:**
After waiting for 10 min i m in 2nd 1st one get his percale and go on. And again i wated for around 10 min and suddenly my vehicle disappeared and near by i took a vehicle and came and see someone in fornt of that door and toldme ki " i am waiting for to long" that so irritating after waited for minimum 20 if someone spawn that area and told me then what should i do ?

**Comment by OrionSparkles** [comment]
![image](https://user-images.githubusercontent.com/54718744/86586922-5af98600-bfa6-11ea-99eb-dc2da2010af5.png)

**Comment by y0Razz** [comment]
Just shoot them 
![image](https://user-images.githubusercontent.com/52549154/86587682-60e16e00-bf8a-11ea-8010-415d257843cf.png)

**Comment by InZidiuZ** [comment]
Closing because:
a) Parts are not even in English,
b) "Rules" are community specific
