### ISSUE TITLE
Caught whilst robbing

### ISSUE THREAD

**Issue by cammybruh** [InZidiuZ/op-framework-issue-tracker#1166]
**Reporter:** Cammy#3351 https://steamcommunity.com/id/artificialking

**Summary:** When caught whilst robbing majority of the time, home owners/tenants (locals) don't spawn (the ones that are meant to come beat the shit out of you). If they do spawn, they aren't aggressive towards you, they just stand in the middle of the road. In my experience it's working about 5% of the time.

**Steps to Reproduce:** Rob a house and get caught.

**Expected Results:** Upon being caught, the home owners/tenants (locals) should spawn outside and beat you when you leave.

**Actual Results:** If you're caught you can leave in peace instead of being attacked by the home owners/tenants (locals).

## Additional Information

**Screenshots:**

**Game Resolution:**

**Player Data:** Chad Rhodes - ID 83

**Server:** EU

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Guessing it's a OneSync issue, as no changes relating to this feature has been made in ages. It's also a deprecated system, so it'll remain a wontfix for now.
