### ISSUE TITLE
[game/objects] ATM at Repair Shop 4

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1167]
**Name:**
Nuziatella#5931

**Summary:**
Put an ATM in the active and organized repair shop 4. (Or any organized repair shops ran by a business) 

**Reason:**
Generally money is always exchanged for car repairs and the current setup requires a disruption in RP if the person needs to "run to the atm" to cover their expenses for the repairs causing a minimum 3-5 minute pause in RP. While the mechanic is "paused" waiting for the customer to return other situations can arise where the mechanic needs to leave or there is a queue formed. So upon returning with the money for the repairs the mechanic is gone or is otherwise occupied. This can cause further pauses in RP or completely break the RP chain that was happening. After deep thought I couldn't think of a way it can be abused or cause harm to the city. Any questions please reach out and I could discuss further. Thank you

Edit: Spelling is hard sometimes

**Comment by S3WAGST4R** [comment]
+1

**Comment by z-Lunar** [comment]
This has been resolved. 😄 ty for the suggestion, for the future post in https://github.com/InZidiuZ/legacy-assets/issues -Lunar Assets Team
