### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by naujawan** [InZidiuZ/op-framework-issue-tracker#1169]
**Reporter:**
naujawan#8383 steam name is sicklepin

**Summary:**
I walked back into my motel room an lost a bunch of stuff. Oddly enough, only expensive things went missing. bricks, guns, keys chips. 
**Steps to Reproduce:**
I possibly couldn't.

**Game Resolution:**
What is your game's resolution? 720

**Player Data:**
Player ID 161

**Server:**
India

**Notes:**
Someone told me that, you can enter someone else's motel if you have the same name, i did not believe him but this is so strange.

**Comment by DaxterPancake** [comment]
You need to provide a lot more information than this. There is no possible way we can determine what happened just from you saying it did. Please re-make this bug report and follow the template, filling in all fields with as much information as you possibly can.

Cheers,
Daxter.
Project Manager.
