### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Rawsome7** [InZidiuZ/op-framework-issue-tracker#1170]
**Reporter:**
Rawsome  (discord tag- Rawsome#2657)(steam-https://steamcommunity.com/id/rawsome07/ )
**Summary:**
i guess tuner chips are not working for now 

**Steps to Reproduce:**
using tuner chip

**Expected Results:**
speed of bike/car should increase by increasing boost

**Actual Results:**
but the speed remains the same

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920*1080

**Player Data:**
CID -181

**Server:**
India whitelisted

**Notes:**
https://drive.google.com/file/d/16KhIEFE-PlGZgWaJ1s-fIBKumXKzkenW/view?usp=sharing 
here is the video for the prove

**Comment by InZidiuZ** [comment]
Use GitHub's search function before you create an issue in order to prevent duplicates. Closing in favor of #873.
