### ISSUE TITLE
[Bug] emotebinding without numpads

### ISSUE THREAD

**Issue by Ajax-thebug** [InZidiuZ/op-framework-issue-tracker#1171]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

MrGandia#3015 | https://steamcommunity.com/profiles/76561199058097866/

**Summary:**
Write a short summary of what you're experiencing.

Emote Binding is not working on laptop which don't have Numpad. Can You Enable to bind with another keys like (6-0) [number keys] or with any other key. 

**Steps to Reproduce:**

Just Run the Emotebind command and try to bind with another key except numpad keys. 

## Additional Information

**Game Resolution:**
What is your game's resolution?
1920*1080

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
The fact that your laptop doesn't have a numpad isn't really a bug though, is it? 🤔 The emote system is also an external one & thus it's barely maintained by us. I do however believe you'd be able to rebind the numpad keys to something else in the GTA settings.
