### ISSUE TITLE
[UI Bug] Translation error in Phone Contacts (English)

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1172]
# Legacy UI Bug Report

**Reporter:** Matt;)#7784 | https://steamcommunity.com/id/mattxiv

**Summary:**
Translation error for English in the Phone Contacts.

**Steps to Reproduce:**
In the phone go to Contact and then with Keyboard control -> right arrow key on a contact OR with Mouse control -> right click on a contact to get up something which says "Edit Contact" and "Annuler" which is in French. I believe it should say "Cancel".

**Expected Results:**
It should say "Cancel".

**Actual Results:**
It says "Annuler".

## Additional Information

**Screenshots:**
https://prnt.sc/teelw5

**Game Resolution:**
1920x1080 Full Screen.

**Comment by InZidiuZ** [comment]
This has now been resolved.
