### ISSUE TITLE
[jobs/ems] Salary change

### ISSUE THREAD

**Issue by Rudra6969** [InZidiuZ/op-framework-issue-tracker#1173]
**Name:**
Rudra Dang, Discord :- E-668 || Dean Brooks#1731

**Summary:**
Salary of starting posts of ems should be increased. Mainly of EMT , EMT Advance and Paramedic. 

**Reason:**
If we see around in legacy server, the people working as garbage cleaners are earning more than the ems people in the same period of time which in real life does not make sense as any medical job cannot be achieved without quite a large amount of study and hardwork. As before the salary was 96$ for EMT but now it is just 50$, which is very low according to my point of view. Else you decide, thanks for your time! Have a great day!

**Comment by MukeshKC607** [comment]
+1
