### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by AnujBeriwal** [InZidiuZ/op-framework-issue-tracker#1174]
**Reporter:**
GamingBuddy#5401 Discord | DeadKurse [Steam]

**Summary:**
I am not getting proper interface to control tuner chip.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
Can't able to tune a car.

## Additional Information

**Screenshots:**
(https://cdn.discordapp.com/attachments/731880006644662284/731880044317900820/unknown.png) SS

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Indian server [Legacy Roleplay India]

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is a wontfix until it's remade.
