### ISSUE TITLE
NEW GTR Livery Bug report ( India WL )

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1175]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
so Some time when we buy GTR it come with permanent livery and and we cant change any color or anything.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Its Random 
**Expected Results:**
What are the expected results?
We cant able to change color
**Actual Results:**
What are the actual results?
you cant able to change ur car color and cant do illegal jobs xD
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://i.ravicant.in/1idlXKtSA
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Charcter ID - 231
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India WL
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Post this in the asset-related issue tracker.
