### ISSUE TITLE
Bring in a rule about cars and hearing

### ISSUE THREAD

**Issue by BreeZaH7** [InZidiuZ/op-framework-issue-tracker#1177]
**Name:**
Lynchy#0301

**Summary:**
When driving in a car unless you roll a window down you shouldn't be able to hear into another car driving passed you at high speeds.

**Reason:*
Why would your suggestion be a good addition to Legacy?
Today I got away from a scenario, was in a car with windows closed up going around 40mph, then 2 cop cars come flying passed at around 120-150mph and heard me speaking in the car and instantly turned around and started chasing me. 
it makes more sense if we want to bring realistic roleplay that people cant do this.

**Comment by InZidiuZ** [comment]
This issue tracker is strictly for framework development. Rule suggestions should be directed to your community.
