### ISSUE TITLE
[game/hud] Custom metrics display

### ISSUE THREAD

**Issue by abhishek-dixit7** [InZidiuZ/op-framework-issue-tracker#1178]
**Name:**

THUNDER#7677

**Summary:**
Can we have a toggleable command which can show continuous ping to the servers.

**Reason:**
As for the fivem in-built cli command "cl_drawperf" which show information in a very detailed manner is not eye friendly, (it would not effect RP at all, but would be a good thing to have).

**Comment by InZidiuZ** [comment]
This has now been added. Do /metrics_toggle while in-game to enable.
