### ISSUE TITLE
Useless items 

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-issue-tracker#118]
Tankfurious

**Summary:**
would it be possible to implement some where to sell useless items plastic/recyclebles ect
at the garbage depot

**Reason:**
give items a temperory use
be able to offload useless items after each run 

or add extra items to sell at the warehouse

**Comment by SteezyRen** [comment]
I currently couldn’t figure out the purpose of some items which has me believing that they are items that are to be used at a later date. I could be wrong though. 

But if that is the case then I definitely agree that being able to get even a few dollars for these items at a designated location (junk collector, pawn shop, etc).

**Comment by Revo1848** [comment]
from what i have realised is InZ has added items that have no use for now only because once he has dealt with all the bugs he is going to make a update that will let u use these items.

**Comment by essjaybee** [comment]
I think the items can be as is until they have their usage.

Pretty sure we will have some kind of pawn shop in the future, or recycle station for the recyclable materials. But IMO, adding something for it already is added work for something we'll sell and probably regret later ;) as long as they are not taking up trunk space I don't mind them.

**Comment by SteezyRen** [comment]
The issue with changing storage to 0.0 is that now we will have a hoard of items that when they do have a purpose for it there will be an abundant amount for the server and might not help from an economic perspective.

**Comment by InZidiuZ** [comment]
Hey,

A use for these items will be added later.

**InZidiuZ**
*OP-FW Developer*
