### ISSUE TITLE
[base/queue] Queue Adjustment

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1180]
**Name:**
@Doughnut#1718

**Summary:**
Making the waiting time spent in queue shorter by shortening the amount of time it's frozen waiting for more people or shortening the time it takes to push people in from half a second to inmediate in restarts.

**Reason:**
When restarts happen, the server takes a minute to go down, about 30 seconds to restart and a minute where the queue stays frozen, waiting for people to get in and fill the queue, the issue is that for people that cannot afford priority (18yo teens without credit cards outside the US) it's impossible to get in at restarts, even if you are number one when the queue has stopped pushing people in more people will get in front of you and push you to the 16th place; another issue is the fact that even if you are 41/56 during the waiting time you can be pushed back while the server is allowing people in.

I have been playing in this server for about a year and a half now, i've had multiple chars, friendly, weird and evil, but the thing is ever since i rejoined pd with Brooks, i have got to be able to join the sv for long enough to not get fired, this little time i have has become an issue lately ever since my main char got evicted due to not being able to join and get paid working. There is supposed to be a prio for active cops but you can't really be active if you can't join in the first place.

The solution would be making that minute shorter, and letting people join inmediatly, not making them wait 0.5 seconds after the one before them joined.
This would make people with prio wait to join if they didn't join inmediatly after restart, making it better for people that want to join and have been waiting for restart to do so.
Don't get me wrong, people with prio have still got it but it can be more useful after everyone else joins
I appriciate you reading this and i hope you acknowledge this issue, kind regards.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
