### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JustPoro** [InZidiuZ/op-framework-issue-tracker#1181]
**Name: Póro#9521**
Who is suggesting this? Please include discord name.

**Summary: So I was thinking to suggest if it hasn't already be suggested. A new racing system because current one is literally just waypoint and going to that waypoint that was pin pointed, i was thinking if it could be possible to add or make one where we could maybe make our own races and even save them with the mod review or something and then added to the list of available races. So people could actually make the races in circles with laps and that would also be good for both racing scene on the city which is currently almost nonexistent and for cops to add diversity in their job and make it fun for them as well.**
Write a short summary of what your suggestion is about.

**Reason: Current racing system is not good at all, i mean it is good for what it is, but i making pre existent waypoints and using them as a race would be wonderful.**
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Use the search function 😩 

#840 & #1163
