### ISSUE TITLE
[?] I lost my stuf work lakhs. from my 3 vehicles infront of me there a situation arrived where the car was locked and the boot was open.

### ISSUE THREAD

**Issue by bajrangibhai** [InZidiuZ/op-framework-issue-tracker#1183]
**Reporter:**
Bajrangi Bhaijaan DUTT_SAHAB_GAMING#9068

**Summary:**
Hello I lost my stuf work lakhs. from my 3 vehicles infront of me there a situation arrived where the car was locked and the boot was open. i will attach the video where u can see what acctualy happened with my stuff and in the end lost everything.

**Steps to Reproduce:**
I believe if I get the stuff back i'll be happy...

**Expected Results:**
I believe all the stuff should be returned to my vehicle of the amount for which i was gonna sell all the stuff

**Actual Results:**
stuff back or money instead of stuff.
that money gonna use to register our company.
that would be an extra money help.

## Additional Information

**Screenshots:**
for [sure] 
![BOOT OPEN WHEN VEHICLE LOCKED](https://user-images.githubusercontent.com/68252626/87818675-9dfe0800-c888-11ea-972d-e7f8626d0623.PNG)
![Capture2](https://user-images.githubusercontent.com/68252626/87818683-9fc7cb80-c888-11ea-9c4f-b7699a801388.PNG)
![Capture3](https://user-images.githubusercontent.com/68252626/87818684-a0606200-c888-11ea-9118-5056d7cf37a7.PNG)
![Capture4](https://user-images.githubusercontent.com/68252626/87818686-a0f8f880-c888-11ea-97bc-786636dfe1cf.PNG)
![Capture5](https://user-images.githubusercontent.com/68252626/87818688-a0f8f880-c888-11ea-802e-a981091aa238.PNG)
![Capture6](https://user-images.githubusercontent.com/68252626/87818691-a22a2580-c888-11ea-90b3-9848fa0b0dd8.PNG)
![Capture7](https://user-images.githubusercontent.com/68252626/87818692-a22a2580-c888-11ea-834f-ef7f244530e9.PNG)
![Capture8](https://user-images.githubusercontent.com/68252626/87818693-a2c2bc00-c888-11ea-91f1-b74edeb037a5.PNG)
![STUF GONE](https://user-images.githubusercontent.com/68252626/87818694-a35b5280-c888-11ea-8e94-1624093cd08d.PNG)
![STUFF AT DIFRENT GARAGE](https://user-images.githubusercontent.com/68252626/87818698-a3f3e900-c888-11ea-808c-0789e3c7aaf8.PNG)
![STUFF GONE 2](https://user-images.githubusercontent.com/68252626/87818700-a48c7f80-c888-11ea-9d62-4716add7211f.PNG)
![STUFF PURCHASED](https://user-images.githubusercontent.com/68252626/87818703-a5251600-c888-11ea-8e98-bb611850f371.PNG)
![VEHLICE LOCKED](https://user-images.githubusercontent.com/68252626/87818705-a5bdac80-c888-11ea-9c9f-c78a6df0148b.PNG)

**Game Resolution:**
its maximum

**Player Data:**
my self bajrangi bhaijaan I usually live in city 4 at motel 2 and i love to explore other cities for marketing and selling my the weapons.

**Server:**
What server/community are you from? India

**Notes:**
Please look in to the matter i have a body cam of that incident.
and i can show u on discord on screen share what and where and how the stuff got cleared.
![BOOT OPEN WHEN VEHICLE LOCKED](https://user-images.githubusercontent.com/68252626/87818906-064ce980-c889-11ea-8885-10c8da0e8a26.PNG)
![Capture2](https://user-images.githubusercontent.com/68252626/87818919-0cdb6100-c889-11ea-8a1a-2e35f945c738.PNG)
![Capture3](https://user-images.githubusercontent.com/68252626/87818924-0e0c8e00-c889-11ea-8dfd-2866f88ac06c.PNG)
![Capture4](https://user-images.githubusercontent.com/68252626/87818931-0f3dbb00-c889-11ea-8f2f-a5aafbf1e656.PNG)
![Capture5](https://user-images.githubusercontent.com/68252626/87818934-106ee800-c889-11ea-85a5-bdae34fd29b3.PNG)
![Capture6](https://user-images.githubusercontent.com/68252626/87818941-1238ab80-c889-11ea-901e-d73104382bb0.PNG)
![Capture7](https://user-images.githubusercontent.com/68252626/87818944-1369d880-c889-11ea-9538-f67e5082b337.PNG)
![Capture8](https://user-images.githubusercontent.com/68252626/87818947-149b0580-c889-11ea-8770-95ed20c7cc80.PNG)
![STUF GONE](https://user-images.githubusercontent.com/68252626/87818948-15cc3280-c889-11ea-9fc0-4351f813b488.PNG)
![STUFF AT DIFRENT GARAGE](https://user-images.githubusercontent.com/68252626/87818949-16fd5f80-c889-11ea-9cfc-dbbc7ef20445.PNG)
![STUFF GONE 2](https://user-images.githubusercontent.com/68252626/87818952-182e8c80-c889-11ea-87e2-c10bf3107328.PNG)
![STUFF PURCHASED](https://user-images.githubusercontent.com/68252626/87818956-195fb980-c889-11ea-83f6-815294c948f2.PNG)
![VEHLICE LOCKED](https://user-images.githubusercontent.com/68252626/87818957-1a90e680-c889-11ea-80a5-d289ae7deecb.PNG)

**Comment by InZidiuZ** [comment]
Could you post the video instead of instead of 20+ pictures from it?

**Comment by bajrangibhai** [comment]
Video size is big.. ci can show u on screen share discord

**Comment by InZidiuZ** [comment]
No. Upload it to YT or google disk & that should be fine.

**Comment by bajrangibhai** [comment]
Ok

**Comment by InZidiuZ** [comment]
5 days & still no video, so gonna close this until later. Feel free to reopen it or create a new issue once you've uploaded the video.

**Comment by bajrangibhai** [comment]
I'll send the video today..
