### ISSUE TITLE
Replace Lost Santos Customs #7 with a Mechanic Shop.

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#1184]
**Name:**
Who is suggesting this? Please include discord name.
Zurxey#2607
**Summary:**
Write a short summary of what your suggestion is about.
Basically, there is a new garage added to the city under the "Midnight Club Los Santos"
This exact place would be perfect for a "Tuner Shop" and for a reputable group of businessmen to run, and own.
**Reason:**
Why would your suggestion be a good addition to Legacy?
The community has been asking for a player ran mechanic, and tuner shop for months now, adding this simple feature would allow that to happen. Sure, we have the Lost MC, but this place would provide actual RP into Mechanic, and Tuning roleplay. There's space for car meets, car upgrading, and viewing. 

This is exactly the kind of thing that could provide a load of RP for hired Mechanics within the city.
Remove the Docks Repair Shop, and add it here, it has the space, and availability, and will no longer interfere with CDLS as well.

**Comment by DaxterPancake** [comment]
Personally I feel like there can be more buisnesses than Mechanic & Tuner shop RP. But what would I know, I come from a group that apparently doesn't do actual Mechanic RP. :^)

**Comment by DaxterPancake** [comment]
Wait, hold on. You're wanting to replace a garage that a whitelisted group owns and runs?

**Comment by DaxterPancake** [comment]
After speaking to InZiduiz more about this issue, we have decided that something like this may be available in the FAR future through the use of the company system, but as it stands right now, it won't be added.

For the time being, if you wish to own a Mechanic shop, you will have to go through the proper RP channels such as state and purchase somewhere that isn't owned. If in the future you have done so and wish to expand, this can be revisited. 

Cheers,
Daxter.
Project Manager.
