### ISSUE TITLE
[external/chat] Have "/" automatically added when pressing "T"

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#1185]
**Name:**
Who is suggesting this? Please include discord name.
Zurxey#2607
**Summary:**
Write a short summary of what your suggestion is about.
Basically in the server when you press "T" to open text chat, I believe it should automatically include the "/" for commands, as without a command line, there is no use for the chat. 
**Reason:**
Why would your suggestion be a good addition to Legacy?
It's a small quality of life improvement, but I believe it just makes sense, and could help a lot of the people in the community who use 60% keyboards.

**Comment by InZidiuZ** [comment]
You can now use commands without prepending the "/". That would mean `ooc hello` would work as well.
