### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pappurana** [InZidiuZ/op-framework-issue-tracker#1186]
**Reporter:**
is:open is:issue author:pappurana archived:false my character face grt Change after cloths change i have try reconnect the server bt not works and after that i delete character bt its also not working

**Summary:**
i want to play bt i cant i want a diffrent character face plz help me 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Bruh... spend some time on reports... This is literally not even coherent. ._.
