### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by vigilante3** [InZidiuZ/op-framework-issue-tracker#1192]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Vigilante steamname:Vigilante
**Summary:**
Write a short summary of what you're experiencing.
i was in city 3 when my taxi was out and it was scuffed i couldnt store it and couldnt open the trunk so i retrieved it and stored it in another garage and when i went back and pulled it out everything in it was gone 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
idk
**Expected Results:**
What are the expected results?
i would like my stuff back atleast main things
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1018
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
india
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Closing due to a minimal amount of information.
