### ISSUE TITLE
Adding a repair shop inside same premise as the new Midnight Club Customs.

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-issue-tracker#1193]
**Name:**
Skipping Baboon? Skipping Baboon#7690.

**Summary:**
The new Midnight Club Customs shop is great, absolutely huge, but this premise is so large you could easily fit a repair station inside the same premise, as well as keeping the existing Los Santos Customs menu at the same location

**Reason:**
This Custom shop is pretty nice, but due to vehicle customisation involving very little RP (as the vehicle owner has to modify their vehicle themselves via the Los Santos Custom menu), there is little to do there right now other than modify your vehicle and leave. With the addition of a repair station at the same premise, mechanics could RP as Import Vehicle mechanics inside the same premise, fixing vehicles to make a profit and RP, and if someone comes by to modify their car using the menu, there is more likely to be a mechanic there, who can then choose to pretend to be the one adding the vehicle mods to the car, and generating more layers of RP than just a simple mechanic that repairs your engine or body.

With multiple reasons to use this one, very large premise, it will create new RP opportunities for Mechanics that want to specialise in Import vehicles, and will increase the usage of the premises as a whole.

![Shop 1](https://user-images.githubusercontent.com/52204924/87925042-9f415780-ca77-11ea-9cf2-c291bc76d90e.png)

![shop 2](https://user-images.githubusercontent.com/52204924/87925109-baac6280-ca77-11ea-80de-087d836bf197.png)

![shop3](https://user-images.githubusercontent.com/52204924/87925124-c009ad00-ca77-11ea-9d60-ba6bdabbf616.png)

**Comment by DaxterPancake** [comment]
After our chat, we are filing this away as a 'Maybe Later'.

Thanks for clearing up the idea.

Cheers,
Daxter.
Project Manager.

**Comment by Imaghost1337** [comment]
Massive love hearts from the Midnight Club <3
