### ISSUE TITLE
Face change automatically

### ISSUE THREAD

**Issue by sohambadjate** [InZidiuZ/op-framework-issue-tracker#1196]
when we create a character my character face is according to my selected choice and my hairs are green even if i select different textures. BUT, then if i exit the game or load my saved outfits then boom....my face changes automatically into a different face and my hairs are of different color rather than green.
![Screenshot (274)](https://user-images.githubusercontent.com/62098216/88042667-ee67b500-cb69-11ea-8319-6bdd6a11eb27.png)

**Comment by InZidiuZ** [comment]
Use the template. This is also a FiveM issue, so no point in reporting this.
