### ISSUE TITLE
Police Crim Alerts

### ISSUE THREAD

**Issue by AzarReflex** [InZidiuZ/op-framework-issue-tracker#1197]
**Name:**
AzarReflex#9763

**Summary:**
Basically the ability to scroll through the previous police alerts.

**Reason:**
Ive had it many times where ive responded to a car robbery, then the chat just gets more ooc messages or more alerts and now i cant see the vehicle plate number nor model, i think being able to scroll up will prevent this.

**Comment by Nuziatella** [comment]
When you press T and the chat box is active. Page up or down key will scroll the chat

**Comment by AzarReflex** [comment]
oh my bad, appreciated!
