### ISSUE TITLE
Bug report car upgrade and lost parts + money.

### ISSUE THREAD

**Issue by hirugain** [InZidiuZ/op-framework-issue-tracker#1198]
**Reporter:**
I am Himansu Gain, Discord name - HIRU GAIN and Steam profile link - https://steamcommunity.com/id/hiru_gain/

**Summary:**
I buy neon light colors & wheels smoke for my car then store the car at garage after withdrawal the car and both are not there, then I check and both are lost. I check 2 time and 2 time are same. 

**Steps to Reproduce:**
I don't know, you know better then me.

**Expected Results:**
stay the upgrade, don't lost the upgrade.

**Actual Results:**
I lost my upgrade and money.

## Additional Information

**Screenshots:**
I have video proof.

**Game Resolution:**
1366x768 full screen.

**Server:**
India server 3.

**Notes:**
please fix this issue.

**Comment by InZidiuZ** [comment]
This is a wontfix, unless you find a solid repro.
