### ISSUE TITLE
[game/notepads] Ability to drop notes

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1199]
**Name:**
Daxter#7158

**Summary:**
I'd like the ability to be able to DROP notes that I write on a notepad.

**Reason:**
It could open up a lot more RP. Some examples would be that, when you kill someone you can leave a note to whichever group you need to get a message to or even the cops. You could find cars that are parked like crap and drop a note telling them to stop parking like a dickhead, etc. I feel it's something simple but would be quite useful to have in the server.

**Comment by InZidiuZ** [comment]
This has now been added and you are now able to DROP notepades.
