### ISSUE TITLE
[game/items] Camera Item -  Used for Evidence Gathering with Zoom

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1200]
**Name:**
Nohbob#1028

**Summary:**
It would be great to have an ability to have a usable Camera item, that functions like the Cell Phone Camera, but also displays evidence from the evidence system.  

**Reason:**
Currently, when collecting evidence, you have to use a flashlight to have the items revealed as part of the evidence system.  

It would be great to have a usable item, that functions like the cell phone camera, but also displays evidence from the evidence system.  This would be useful for documenting crime scenes for PD and enhancing Evidence Gathering RP.

**Comment by Masik52** [comment]
This would be beneficial for FIB and PD to build case file evidence with pictures of the crime scene that show the evidence that’s being collected.

**Comment by twooot** [comment]
This was done
