### ISSUE TITLE
[Suggestion] New Server

### ISSUE THREAD

**Issue by Ishaan0511** [InZidiuZ/op-framework-issue-tracker#1202]
**Name:**
ishaan#3371

**Summary:**
I have an idea of making a new server which Legacy Community will like. The idea is that there is a one robber and around police and a round of 10 minutes and in 10 minutes we have to catch robber otherwise robber will escape and we have to destroy robber vehicle. Police consist of one helicopter and bikers and cars. We can also add more things like insted of one robber we can have 5 to 7 robbers which can do code Red in place and police have to kill them in 20 minutes. There are levels and by gaining xp we levelup and at each level there are cars and there are donator cars also you can visit one server like this name **Busted by mythicalbro**

**Reason:**
Legacy Community will like this type of server

**Comment by Doughnut2001** [comment]
i wouldn't personally enjoy that, sounds a bit too fast paced and i believe that legacy has already got too many servers to it's name, we've done events like that before but the idea would not stand on a single server imo.

**Comment by InZidiuZ** [comment]
This issue tracker is for the 'op framework' & this has nothing to do with that...
