### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Berlin4632** [InZidiuZ/op-framework-issue-tracker#1203]
**Reporter:**
Berlin#4362

**Summary:**
HUD coming on top left instead of bottom left 

[[](https://cdn.discordapp.com/attachments/700985352953004103/735794289128243230/20200723011021_1.jpg)
**Game Resolution:**
1600 x 900

**Comment by DaxterPancake** [comment]
Use the bug template. Provide as much information as you can.
