### ISSUE TITLE
Issue regarding Edm Vehicle

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/op-framework-issue-tracker#1204]
Unpredictable#5986 https://steamcommunity.com/profiles/76561198404346164/

Today I saw a EDM vehicle Harley Davidson changing into Police Department type bike and its headlights were to blinking with blue and red lights. Then automatically it started changing its colour into blue ,red, grey, green.

https://gyazo.com/6003f4895acf50550d4f7bb17850ce3c
https://gyazo.com/1f1c64408ffa34e6092f1764fd6e19e7

**Comment by InZidiuZ** [comment]
Use the assets-related issue tracker for such issues.
