### ISSUE TITLE
Reporter:

### ISSUE THREAD

**Issue by GhoulMonk** [InZidiuZ/op-framework-issue-tracker#1205]
**Reporter:**
GhoulMonkey#9177 
steam profile: http://steamcommunity.com/id/sanket_official

**Summary:**
After loading everything last session and all i am experiencing a black screen with 2000+ fps when there should be Enter key to press i will provide a screenshot with this.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
ingame name vijay rastogi 
**Server:**
India whitelist
![Screenshot (380)](https://user-images.githubusercontent.com/68705611/88317867-836bd900-cd37-11ea-9560-af6ec049ae8a.png)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
I haven o idea how I should solve this considering I've been provided almost no information... Looks like an issue with your client and/or FiveM.
