### ISSUE TITLE
PDM Bug report

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1206]
**Reporter:**
Jethiya#0941 

**Summary:**
Players are going through this weird issue in the pdm where you buy something and some other vehicle else gets stored in your garage. Plus the amount which gets deducted is equal to the new vehicle that replaces the vehicle you wished to buy. For example yesterday I bought a cycle for 15k , went to the garage and found that it was replaced by bati (which costs 15k).

**Steps to Reproduce:**
Buy any pdm vehicle

**Expected Results:**
having the correct vehicle for the right amount

**Actual Results:**
vehicles getting replaced 

## Additional Information

**Screenshots:**

**Game Resolution:**
1366x768

**Player Data:**
Name - Sanjay Gupta 
Charc id - 947

**Server:**
India

**Notes:**
I have talked to the pdm employees they say its an issue caused when two players are buying two different vehicles in two different cities (eg india 1 and 2 ) from the same car slot at the same time.

**Comment by InZidiuZ** [comment]
Closing, see #1103.
