### ISSUE TITLE
[jobs/dealership] Buyable Limo (Stretch) from PDM or Premium Car Shop

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1208]
**Name:**
Brennan#0279

**Summary:**
Have the ability to buy a Limo, or Stretch as it is called in game, to PDM or the Supporter Car Store. 

**Reason:**
Running a Casino business, we would be able to pick up important individuals with the limo and bring them to the business. Additionally, I have seen people steal the limos when they want to dress up and do things, it would be easier and legal to just buy one from one of the stores.

**Comment by z-Lunar** [comment]
This runs the problem of fitting inside of PDM, currently theres no spot the Limo would fit inside the building.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
