### ISSUE TITLE
[game/progressbar] "SkillBar"

### ISSUE THREAD

**Issue by AzarReflex** [InZidiuZ/op-framework-issue-tracker#1209]
**Name:**
AzarReflex#9763

**Summary:**
a "Skillbar" is commonly known for semi repairing cars

**Reason:**
I think it could be used for a few things such as being used for the "repair" command for cops, but with a chance of failing... i think having that chance of fail will be good, could also be used for lock picking thy vehicular device!
![skillbar](https://user-images.githubusercontent.com/61126330/88437754-13288a80-cdff-11ea-9887-ffeea800e92f.PNG)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
