### ISSUE TITLE
[game/freemod] Suggestion / Kid Character Build up in Role Play

### ISSUE THREAD

**Issue by imjst19** [InZidiuZ/op-framework-issue-tracker#1210]
SBkhan101 
m s khan101#5800

**Summary:**
I want a to play Kid character role play in Legacy RP

**Reason:**
It is new concept in RP. It is very interesting and we try to bring some funny and Discipline among your families.

**Comment by DaxterPancake** [comment]
I don't see why you'd need to be a child. This is a server that has drugs and alcohol and death.. Why would we need children running around?

**Comment by InZidiuZ** [comment]
...yea no, unless you mean small peds, that would be up to the assets team

**Comment by sbkhan101** [comment]
> I don't see why you'd need to be a child. This is a server that has drugs and alcohol and death.. Why would we need children running around?

sie first of all this is character and i know This is a server that has drugs and alcohol and death.. but i m first person on rp to try this. check this link sir  plz this person already play a 3 years old kid character / https://youtu.be/GCDrAakevKc / plz chek this link. we try new creativity in gta rp. #1215
