### ISSUE TITLE
Going Inside Roads Multiple Times Everyday After Driving

### ISSUE THREAD

**Issue by XanderX-Official** [InZidiuZ/op-framework-issue-tracker#1211]
Going Inside Roads Multiple Times Everyday After Driving

Have done the Following Everytime:
- Clear Cache
- Reinstalled FiveM

![Screenshot (1385)](https://user-images.githubusercontent.com/67511268/88449377-16099680-ce64-11ea-96a8-d340974ec39c.png)
![Screenshot (1384)](https://user-images.githubusercontent.com/67511268/88449380-199d1d80-ce64-11ea-937f-5bdc0a1b6900.png)

**Comment by InZidiuZ** [comment]
a) you did not fill out the template, and b) this is most likely a FiveM issue *or* an issue with your system/PC
