### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Xpertsavage900** [InZidiuZ/op-framework-issue-tracker#1212]
Xpertsavage900 Xpertsavage900#5924(Discord name)

**Summary:**
Make a  new discord channel for  the  lspd as  we have  one  for mechanics.

**Reason:**
I am  suggesting this because it is  very difficult  to see how many  lspd ppl are  online  and  playing in the server. It is also  difficult to see in  game  as the PD stays  empty most of  the time.   It wont affect RP in any ways and  is just  to ease the  life of the people

**Comment by DaxterPancake** [comment]
This isn't a server issue, this is a community discord issue. Speak to your community manager of your subdivision.
