### ISSUE TITLE
Legacyroleplay india, Chopshop issue

### ISSUE THREAD

**Issue by Ashu9565** [InZidiuZ/op-framework-issue-tracker#1213]
this is issue is happening with all the people who play in legacyroleplay but admin don't give importance to this glitch so When we do chopshop in all the cities which are 1to5 but when we do chopshop we can't find chopshop car in the perfect location not all the cars but maximum car is not able to see and some of the location that radio give us is not available in the whole map and it make soo much lose so we need you to fix the chopshop so we can get more cars,Thank you.

**Comment by B1ueMoon** [comment]
Yeah actually this issue got reported multiple times, but i dont know why inzidiuz didn't fixed this issue! Like 3/10 chop Shop vehicles are bugged normally and some people waste 5-10 minutes trying to find that vehicle but after they know that this vehicle is bugged and they searched the whole street!

**Comment by InZidiuZ** [comment]
...if you don't know why I didn't fix it, perhaps read my response that I left when I closed the previous ticket(s)? #1098
