### ISSUE TITLE
[vehicles/vehicles] Custom License Plates

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#1214]
**Name:**
Who is suggesting this? Please include discord name.
Zero Hernandez - Arteria#1380
**Summary:**
Write a short summary of what your suggestion is about.
Basically what I want is obviously custom plates. There are people in real life who have these, and it's not uncommon. For what it does, it's actually quite simple obviously. We can use custom plates of any letter combination more than 3 letters. The actual process to do this would be going through the state. Since the state has specific plates that refer to your car, changing it should be somewhat of a process. So perhaps you would have to find a state worker to "approve" your plate. The reason they would need to approve it is in case someone else has the same plate. They would than have someone "print" you a plate (would possibly appear as the same item as a fake plate in your inventory) and would need a mechanic to change it for you. 
**Reason:**
Why would your suggestion be a good addition to Legacy?
I think this would bring a little more aesthetic to cars which would make people happy.  I know personally this would be used by probably all gangs and used throughout. I feel like it would also be pretty scary seeing Douglass pull up with "DOUG" on his plate. The reason the suggestion would be good purely is for any car designs and even so, I know racing will be more of a common thing and it would push the RP experience in a positive direction.

**Comment by Livius99** [comment]
Aaand add a feature for pdm so you can request the custom plate when u buy the car and pay some cash to get it like that before you buy it.
In the end we'll need to put it on the paperwork anyway so...

**Comment by InZidiuZ** [comment]
This will not be added at this time.
