### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1215]
**Name:**
Jethiya#0941

**Summary:**
I have 2 suggestions at the moment : 

1. Notifications should toggle on/off with respect to the player going on/off duty **(for both pd/ems)**  
2. Pillbox should have a store same as the pd has. 

**Reason:**
1. notifications are annoying when off duty.
2. a store in the pillbox would save time which could be further used to treat patients.

**Comment by InZidiuZ** [comment]
1) sure...
2) Already done, see #1213.
3) ONE SUGGESTION PER TICKET

**Comment by InZidiuZ** [comment]
> Notifications should toggle on/off with respect to the player going on/off duty (for both pd/ems)

Just checked & this is already a thing, so...
