### ISSUE TITLE
[game/items] IFak's (Individual First Aid Kit) for PD

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#1216]
**Name:**
northbayjoe#5571

**Summary:**
With the new buff of oxy coming into the server soon according to the github commits, I wanted to suggest that PD may get IFaks's as well. An IFak is an Individual First Aid Kit, that is a mini trama kit that is much more advanced than a bandage. An item like this will balance the use of these quick heal/emergency tools for both PD & Crims during active shootouts. With that being said, they should take twice as long to apply, and instead of doing 20hp increase, only do 10hp increase of health while similarly stopping bleeding. Since in RP an oxy should legitimately do a bit more for you. Neither oxy or IFak's should be spammable either, and both should have a cool down between each use. Street price for oxy is around $50 per pill so IFak's should cost around $200-300 each to make them something that would be sorta expensive in an effort to balance them even further. Creating the IFak for the city shouldn't be too difficult either since you could copy the oxy item, rename it to IFak, and just reduce the values for it.

**Reason:**
Weather we like to admit it or not, we have alot of gunplay RP in the server, and with that comes shootouts. The ability for one side to have a tool that gives bleeding stoppage alone will make gunfights unbalanced, and that is not including the rapid health boost. Adding an item that is similar for the PD, but with less of an the HP boost effect such as an IFak will at least keep some of the balance in place. One of my goals as member of the community/command member of the PD is to prevent other members of PD from getting discouraged ahead of time, and keep the on duty channel full for the better of the server. Having too much of an imbalance makes it so PD members get frustrated and go off duty, and that effects the server negatively when there is no police presence around. So I am preemptively suggesting this to avoid any issues ahead of time.

Sample icon:
![ifak](https://user-images.githubusercontent.com/44896032/88468486-62bb9480-ce99-11ea-8d60-e37a67293be1.png)

**Comment by AverageStatistic** [comment]
+1

**Comment by devesh180** [comment]
+1

**Comment by ZeAviator** [comment]
+1

**Comment by Vedder742** [comment]
This is a well thought out suggestion for development to improve fair engagement on both sides while improving RP for "gunplay", and maintaining realism. Would absolutely love to see this added.

**Comment by InZidiuZ** [comment]
This has been added with version 2975
