### ISSUE TITLE
JDM Cars at EDM to be at lower-most tier

### ISSUE THREAD

**Issue by armadamYT** [InZidiuZ/op-framework-issue-tracker#1218]
**Name:**
Armadam#2431

**Summary:**
So basically my suggestion is just about a little more realism in EDM cars. If all the previous EDM cars are readded I would suggest that the lower most tier should have all the JDM cars like the Honda S2000,Supra, R32 & R34 GTR, RX7, Honda civic etc. 

**Reason:**
These cars were actually intended to be sports cars for the masses and I believe these cars should be available for the players who are not willing/ cannot afford the priority. Obviously with proper nerfing done to these cars these would not be misused (for robberies etc.)

**Comment by InZidiuZ** [comment]
There's no direct plan to make them return at this point. We'll see what categories they go in if they do, though.
