### ISSUE TITLE
[game/injuries] New EMS Features

### ISSUE THREAD

**Issue by GameXport** [InZidiuZ/op-framework-issue-tracker#1220]
**Name:**
GameXport#3997

**Summary:**
I think there are not many changes or any new feature that has been added to EMS apart from the new Pillbox. So I found out this feature where an EMS can examine the patient and can treat and heal them on the spot. They can even find out what injuries they have. I think this will boost EMS RP and will give some joy in EMS RP too. I am attaching 1 video and 3 screenshots so that you guys could get a better look. Thanks.
Video Link: https://www.youtube.com/watch?v=z92hrsuLc0U&feature=youtu.be
Screenshot 1: https://imgur.com/VXIvTxx
Screenshot 2: https://imgur.com/JYD92Pc
Screenshot 3: https://imgur.com/LCe1dYj

**Reason:**
I think this will boost the EMS RP and Will give EMS more options to treat the patient and do more RP with them. To be honest, EMS will look more advance by adding those features. Thanks.

**Comment by EvilGhost5** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
