### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Foolhardy-Orc** [InZidiuZ/op-framework-issue-tracker#1221]
**Reporter:**
Discord- Foolhardy_orc#5848 
Steam id - STEAM_0:1:431779837
**Summary:**
I bought a freecrawler and I customized its full engine, turbo, tuning, paint, liveries and light under the car. After that when I stored in garage and get my car out from the garage no customization is showing except the car paint not engine not light under the car not even turbo. 

## Additional Information

**Screenshots:**
![FiveM -  7  Legacy Roleplay India #2 _ Wiped Recently _ Custom Framework _ Active Staff_Development _ Join us @ discord gg_ehNU9xP 26-07-2020 17_58_27](https://user-images.githubusercontent.com/68809330/88479052-391e6e00-cf6a-11ea-9c5a-6d222170a499.png)

https://drive.google.com/file/d/1398VBmaVpn1rs2co6A_K3gLNAih9_8pD/view?usp=sharing

**Game Resolution:**
1920*1080

**Server:**
Legacy India Server 2

**Comment by InZidiuZ** [comment]
Already known issue, no repro, no additional info. This will remain a wontfix until the vehicle modification system is remade.

**Comment by Foolhardy-Orc** [comment]
I don't understand will you plz elaborate it
