### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by atha10** [InZidiuZ/op-framework-issue-tracker#1222]
**Reporter:**
Myself Atharva discord tag:- ! Atharva !#4494 and steam profile:- https://steamcommunity.com/id/rage1050/

**Summary:**
While playing the inventory access get denied or cant open inventory on foot and also on vehicle plus cant access any trunk.

**Steps to Reproduce:**
When a character inventory is open and click right+left mouse button the inventory get disappear.

**Expected Results:**
Inventory should get access.

**Actual Results:**
Inventory get stuck.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920*1080p

**Player Data:**
Character ID:547
timestamp:2020-07-26 18:06:01

**Server:**
Indai

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Thank you for the report! I managed to fix 3 separate issues with the inventory all relating to 'spam clicking'. If you encounter any other similar issues in the future, please create another report or just DM on discord.
