### ISSUE TITLE
[illegal/*] Robberies cannot be done X time before the server restart

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1225]
**Name:**
Igna#6192

**Summary:**
That the current robberies and future robberies cannot be done it X time (30min-1h) before the server restart. 

**Reason:**
In some cases players wait for the server restart to rob the bank or bank trunks and take advantage of this. For the police it's frustrating not being able to do our job and not even having a chance to catch and process them.

**Comment by twooot** [comment]
This should be handled in a server rule not a thing in the framework itself
