### ISSUE TITLE
While you /carry and /escort, allow to jump and climb obstacles

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1226]
**Name:**
Igna#6192

**Summary:**
While you /carry and /escort, allow to jump and climb obstacles

**Reason:**
In some cases shootings occur in very closed places with little access and many obstacles, jumps, roofs etc. So jumping and climbing would facilitate movement while we are /carry or /escort someone. I think this was done to avoid some PG, but sometimes it's a bit annoying.

**Comment by InZidiuZ** [comment]
This won't be done at this time.
