### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tuinhalder** [InZidiuZ/op-framework-issue-tracker#1227]
**Reporter:**
Shadow Gaming#9032
https://steamcommunity.com/id/TUHINHALDER2020/

**Summary:**
sir car tuning chip in not working something happening.. the tab not show properly..

**Steps to Reproduce:**
to tune any car

**Expected Results:**
my car is super fast

**Actual Results:**
What are the actual results?

## Additional Information

**Game Resolution:**
1920*1080

**Server:**
India 

**Notes:**
i have a car tuning chip but i cant tune my car

**Comment by InZidiuZ** [comment]
As mentioned previously, this is a wontfix until the tuner chips are rewritten.
