### ISSUE TITLE
[game/inventory] /give command for items in the inventory

### ISSUE THREAD

**Issue by armadamYT** [InZidiuZ/op-framework-issue-tracker#1228]
**Name:**
Armadam#2431
**Summary:**
I wanted to suggest to make a /give command with the syntax: [/give _item-name_*_quantity_ server ID] for all the items in the inventory. The give animation in shared emotes can be used for it.
**Reason:**
When we drop item for multiple people at once people often take all the items (by mistake or otherwise). This command will directly transfer the item from the giver's inventory to the receiver's. This would simplify transfer of items between people and will also make sure other people can't spy on what is being given or take it for themselves.

**Comment by InZidiuZ** [comment]
Closing in favor of #2250.
