### ISSUE TITLE
Losing Health While Entering House For Robbery

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#1229]
**Reporter:**
ayushpandit99#1842,https://steamcommunity.com/profiles/76561198439789164/

**Summary:**
I,And Some Of My Friends are Facing Issue While We Enter The House...  For The House Robbery.. While Loading It Randomly Reduces Health And Sometimes Even U Die..
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
Please Fix It

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Legacy India
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Great job filling out the template...
