### ISSUE TITLE
Bug report there is a bug in server 3 when I get the tattoos it gets undone whenever I reenter the server please fix it  discord name GhostFox06 steam profile GhostFox06

### ISSUE THREAD

**Issue by Ghostfox06** [InZidiuZ/op-framework-issue-tracker#1230]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by its-Frost** [comment]
Next time you are making a report on github you should follow the form and answer the questions.
The tattoo bug is already being looked at if you havent heard already.

**Comment by InZidiuZ** [comment]
...seriously, how do so many people fail to do something so simple?!
