### ISSUE TITLE
[game/teleporters] Pillbox Medical Morgue -> Los Santos County Coroner Office

### ISSUE THREAD

**Issue by z-Lunar** [InZidiuZ/op-framework-issue-tracker#1231]
**Name:**
Lunar#3391

**Summary:**
Coroners Morgue to be moved from Pillbox to the Actual coroner office. https://gta.fandom.com/wiki/Los_Santos_County_Coroner_Office

**Reason:**
I am suggesting the morgue to be moved from pillbox to the coroner office, because it is more fitting, gives us a reason to properly use the medical rooms we have been provided inside the new pillbox, we have a changing room for EMS behind the front desk, & this is also prevents people from running from police custody & teleporting into the morgue. currently it's still natural for us to use the coroners morgue for surgery, which in reality it makes no sense cause they are x-ray rooms & such, no real surgery rooms like the new pillbox has.

**Comment by InZidiuZ** [comment]
This has now been done.
