### ISSUE TITLE
[game/doors] Bahamas Door lock/Unlock | Bar Shop

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1232]
**Name:**
Rithvik05⚽#0774

**Summary:**
 The Bahamas Club Located Near Marathon Avenue | As In The Update Coming Up Doors Were Added And If There Will Be The Option For Lock/Unlock Of Doors To Build RP Also A Purchase Option Of Buying Alcohol In The Club As It Is One Of The Biggest And Also A Great Interior Club.
_Below Are The Some Screenshots:_
Screenshot 1[Door Lock]:-  https://drive.google.com/file/d/1XbK1vAcjrlcesANTo27Xe2_dsGtLNzKB/view?usp=sharing
Screenshot 2:-  https://drive.google.com/file/d/1UqhzvZBiaVKSousyAUaPYQEnvbvDbSCC/view?usp=sharing

**Reason:**
Why would your suggestion be a good addition to Legacy?
As Per The Changes Coming Up The Doors Were Added At Bahamas Club Which Has Been Increasing RP For Companies. There is RP To Be Build Like A Company Owning It For Lease By The State Department. So, People Will Come And Try To Contact You Regarding A Event To Host In Your Club.Which As The Benefits In Multiple And As IRL Concept No One Goes Directly To Someone Club To Have A Party.

**Comment by InZidiuZ** [comment]
This is being added in the next update.
