### ISSUE TITLE
Adding An ATM in PDM will be much better then any other suggestions !!!

### ISSUE THREAD

**Issue by S3WAGST4R** [InZidiuZ/op-framework-issue-tracker#1233]
**Name:**
INDRvlxHSTAR#5203

**Summary:**
Add a ATM in PDM

**Reason:**
Bcauz many a times when the commission of any car is $300,000 and when we are have this much cash and the police pulls of the car for some reason and if they search so they found this much cash they consificate the cash bcauz we have more money so that's why I am suggesting to add a atm in PDM ! May you like my suggestion ! Thanks

**Comment by DaxterPancake** [comment]
Already added! Cheers tho!
