### ISSUE TITLE
Car Purchasing Issue

### ISSUE THREAD

**Issue by Vatsu1670** [InZidiuZ/op-framework-issue-tracker#1234]
**Vatsal Joshi:**
Vatsal Joshi Is reporting This. Discord-Vatsal#2793  Steam Profile-https://steamcommunity.com/profiles/76561198863510953/

**Summary:**
I Purchased A Car From PDM Named Vulcar Of 20k And Gave The Comission Too,And When I Purchased The PDM Took The Vehicle Number And Then I Went For Washing My Car And When I Washed My Car I Stored The Vehicle In Garage A And When I Read The Cars Name It Was Named BLISTA But I Purchased Car Named VULCAR The When I Removed My Car From Garage It Came BLISTA Named Car Of 6k Its A Bug And 6k Got Cut From My Car.This Is A Bug.

**Steps to Reproduce:**
I Need My Money Back And I Want To Purchase That Car named VULCAR As Its A Bug.

**Expected Results:**
What are the expected results?

**Actual Results:**
The Actual Result Is That When I Stored my car it was VULCAR named and when I removed from my garage A it became a car named BLISTA of 6k.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
Low

**Player Data:**
Character ID-808 Job Data-Transportation,GoPostal,Delievery Job.

**Server:**
I AM FROM LEGACY ROLEPLAY INDIA

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Nice repro & also #1103.

**Comment by Vatsu1670** [comment]
> Nice repro & also #1103.

But now what should i do?
