### ISSUE TITLE
Missing Property - Smoke Tree Road Block - Smoke Tree Road 11

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1235]
**Reporter:**
https://steamcommunity.com/id/nohbob/
Nohbob#1028

**Summary:**
I am unable to locate a property that I purchased, have searched the entire area, and haven't been able to find it. 

**Steps to Reproduce:**
Own the Smoke Tree Road Block
/locate Smoke Tree Road 11
- No Results

**Expected Results:**
Highlights on Map

**Actual Results:**
- No Results

## Additional Information

**Screenshots:**
https://i.imgur.com/bKW6hlk.jpg
https://i.imgur.com/G325j5y.png

**Game Resolution:**
2560 x 1440

Game Resolution:
2560 x 1440

Player Data:
Character ID: 86 - Job Data: Mechanic, Los Santos Customs, Tow Driver

Server:
Main

Notes:
I tried a ton of spell combinations with spaces and such to located it.

**Comment by InZidiuZ** [comment]
This has now been resolved.
