### ISSUE TITLE
[game/slot_machines] Gambling Machines

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1236]
**Name:**
DooZolz#4014

**Summary:**
I think that we should be able to use the gambling machines. When we go near them it says "Press [E] to use the machine" and then you get a mini UI that pops up. You would be able to play multiple mini games (having a chance to win or loose money). You put the amount of money you want to gamble into a little box on the left of the screen maybe and then you play one of the mini games.

**Reason:**
It's a good addition to Legacy because it's something different for everyone. It gives some people a chance to spend money in a different way. As far as I know I haven't seen any suggestions about these gambling machines. All I really see is crim and cop stuff. Me and Dano#5666 (The manager of the LATAM discord) Both agree that this is a great addition to Legacy.

**Comment by its-Frost** [comment]
+1 on this one.. This can also be changed into a scratch card which almost works the same. Would love to see different type of scratch cards for $2, $5, $10 and up.

**Comment by DooZolz** [comment]
> +1 on this one.. This can also be changed into a scratch card which almost works the same. Would love to see different type of scratch cards for $2, $5, $10 and up.

thank u mr frost

**Comment by DaxterPancake** [comment]
Love this idea.
In the future I also think that adding poker or blackjack minigames at certain interiors that have poker tables, etc would be another cool addition to the server.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
