### ISSUE TITLE
[Phone Suggestion] GIVE ME A TITLE

### ISSUE THREAD

**Issue by z-Lunar** [InZidiuZ/op-framework-issue-tracker#1237]
# Legacy Phone Suggestion
**Name:**
Lunar#3391

**Summary:**
Assuming there will be a Twitter APP would be nice to see this restricted to the Character Name & Not Users Choice.

**Reason:**
To better explain what I mean, when I make a character I'd purchase a phone and twitter would already have an account made with the name of the character "Bob Test" On Twitter: "@Bob_Test" this would restrict the Illegal activity and really promote a more realistic twitter and stop people from posting dead bodies willy nilly on a throw away account on twitter 😄 this is just an example..would also lead them putting more thought into their tweets knowing it comes directly back to their names 👍

**Comment by InZidiuZ** [comment]
This is already the plan for the Twitter app.
