### ISSUE TITLE
[game/rockstar_editor] Clip Saver for Rockstar Editor

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1238]
**Name:**
Who is suggesting this? Please include discord name.
@Vishal#1523
**Summary:**
Write a short summary of what your suggestion is about.
https://github.com/Kyominii/ClipSaverV
This link will help you to add script in server. This will help people to save their roleplay situations and they can awesome videos out of it... which will further promote legacy server.  Please have a look to site once... and let us know if it is possible to add this...
**Reason:**
Why would your suggestion be a good addition to Legacy?
by adding this in server, people can edit their RP clips and make it cinematic to make awesome content and Legacy will also get promoted.

**Comment by InZidiuZ** [comment]
Closing in favor of #1162
