### ISSUE TITLE
[jobs/?] Addition of static jobs to the core

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1240]
**Name:**
Nuzi Tello - Legacy Government Employee / Discord: Nuziatella#5931

**Summary:**
Need jobs added to the city to support the new companies.

**Reason:**
The jobs will add cohesion for the companies and immersion to the city. Adding valuable opportunity for great roleplay.  Pay scales and job descriptions have been discussed with members consisting of the admin staff, developer, and a moderator.

Bar/Club

Bar Owner - 80
Bar Manager - 64
Bar Security - 55
Bartender - 35

Casino

Casino Owner - 80
Casino Manager - 64
Casino Security - 55
Casino Dealer - 50

```
Jobs = {
    ['Bar and Club'] = {
        ['Bar Jobs'] = {
            ['Bartender'] = {salary = 35},  - *The Bartender will greet customers, learn about their preferences, answer questions, recommend menu items, and prepare and serve beverages and food. They can receive tips and must have excellent communication skills.

            ['Bar Security'] = {salary = 55}, - *Maintain order and peace on the property. Confiscate weapons upon entry and return them on departure. Notify authorities when the need arises.

            ['Bar Manager'] = {salary = 64}, - *Handle day to day operations and assist the owner with operations.
            ['Bar Owner'] = {salary = 80}, - *Manage and maintain the company.
            
        },
```

```
Jobs = {
    ['Casino'] = {
        ['Casino Jobs'] = {
            ['Casino Dealer'] = {salary = 50},  - *Operates and maintains tables used for gambling.

            ['Casino Security'] = {salary = 55}, - *Maintain order and peace on the property. Confiscate weapons upon entry and return them on departure. Notify authorities when the need arises.

            ['Casino Manager'] = {salary = 64}, - *Handle day to day operations and assist the owner with operations.
            ['Casino Owner'] = {salary = 80}, - *Manage and maintain the company.
            
        },
```

**Comment by InZidiuZ** [comment]
Any specific reason you're requesting these roles into the job system considering they would include no features besides a salary? Can't this be done with the company system?

The only actual use of these roles I would imagine would be to get an increased paycheck while not *really* constantly be going at it with these roles... I'd imagine if it's money you're looking for, you could try to arrange something with your community manager(s) in exchange for hosting events or such.

**Comment by Nuziatella** [comment]
To elaborate further on my reasoning stated above. Currently for the example of the 2 bar companies we currently have there isn't a way for them to gather capital as beverages purchased from the establishment do not go to company funds. While the government can hand out money to assist in this matter; the solution isn't an elegant one. So to utilize the company system the owner would need perform other jobs and perhaps a considerable amount of time on them which can feel very foreign being as they had already gone through the process of investing into their time, planning, submission, money, and interview just to get their company.  

The solution I gave above would, as I stated, add cohesion and immersion. While the jobs themselves may be featureless the goal would be to add value to these positions and offer a rewarding route of RP.

**Comment by InZidiuZ** [comment]
> Currently for the example of the 2 bar companies we currently have
The framework is used by 10+ communities, so this is not very relevant nor is the fact that 'admin staff' has helped you reach the salary amounts.

It still sounds like just a way of getting a paycheck greater than the default ones to me. Chances are this would quickly level down & become inactive, leaving players with these salaries even though they're not really doing anything to deserve them.

I'd rather have something more dynamic for the bars, casinos, etc. implemented.

I can add this for the community managers to give to players as they please, though the current job system is deprecated so when it's rewritten, it's unlikely this would carry over, at least in the proposed state.
