### ISSUE TITLE
[game/banking] Remove deposit ability from ATM's

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#1241]
**Name:**
northbayjoe#5571

**Summary:**
Changing ATM's to withdrawal money only, and no deposits. Only deposits would work at the large fleeca banks or the pacific standard vault. 

**Reason:**
This would create a more realistic money handling system as in real life you wouldn't be able to shove large amounts of money into an ATM, and people stuffing 20k into a ATM after robbery to secure the win instantly is pretty weird. I also think it would intensify the roleplay with people holding the money on them for a while longer until they can go to a bank after a robbery has cooled down for a while. This would make people have to be more strategic with their getaways instead of running into a convenient store, and stuffing the money in an ATM, which has been happening quite a bit in the city lately. Since at that point it's no longer about the roleplay of the robbery, and more about securing the win.

**Comment by Imaghost1337** [comment]
Alternatively, you can remove the deposit ability to most of the ATMs, but keep it when the ATM is next to a bank, for example Legion Bank

**Comment by EvilGhost5** [comment]
+1

**Comment by S3WAGST4R** [comment]
+1

**Comment by twooot** [comment]
I think this issue is solved with the addition of the limit to atms
