### ISSUE TITLE
[game/voice] Raise on TokoVOIP ver.1.5.0+ 

### ISSUE THREAD

**Issue by fakkit** [InZidiuZ/op-framework-issue-tracker#1242]
**Name:**
𝘧𝘢𝘬𝘬𝘪𝘵#6400

**Summary:**
I think a lot of users want to use others plugins w/ toko like soundboard, clownfish etc etc, however that plugins doesnt works on tokovoip ver.1.5.0-. 

**Reason:**
A few, or several dozen players on all sets legacy would play on good workin' plugins. That partly increase our roleplay level, and given more willingness and satisfaction :D

**Comment by Masik52** [comment]
I don’t believe Legacy will be updating to Toko 1.5. On the test server a custom voip is being used so once that update hits the live servers we will likely be moving away from TS and Toko.

**Comment by InZidiuZ** [comment]
Version 2.6 and later versions uses FiveM's Mumble voice integration instead of TokoVoip.
