### ISSUE TITLE
Bug report - Gas tank in Paleto repair shop explodes

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1245]
**Reporter:**
AdeptCL#0402 - https://steamcommunity.com/id/AdeptCL/

**Summary:**
Gas tank in Paleto repair shop explodes. People can come and shoot it for it to explode.

**Steps to Reproduce:**
Go into the new repair shop in Paleto Bay.
Shoot the red gas tank on the left wall.

**Expected Results:**
Not to blow up with it being an inside area.

**Actual Results:**
It explodes.

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/697961330149163068/740310533709758474/20200804214504_1.jpg

**Server:**
Thew new EU/NA 2.7.

**Comment by InZidiuZ** [comment]
This is not a bug.
