### ISSUE TITLE
Chop Shop Not Working

### ISSUE THREAD

**Issue by SwaysterUS** [InZidiuZ/op-framework-issue-tracker#1247]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Sway#2610 https://steamcommunity.com/id/TheSwayster
**Summary:**
With the new radio update we are no longer receiving radio call outs for chop cars

**Steps to Reproduce:**
Maybe having a separate radio just for the chop call outs

**Expected Results:**
Having the chop shop work correctly again.

**Comment by InZidiuZ** [comment]
> Maybe having a separate radio just for the chop call outs
This is already a thing. Check out the chop shop location.
