### ISSUE TITLE
You can run while you are carrying someone with DPEmotes menu

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1248]
**Reporter:**
Igna#6192
steam:1100001156ca896

**Summary:**
You can run while you are carrying someone when you open DPEmotes F3 Menu

**Steps to Reproduce:**
Carry someone and then press F3, and keep the menu open.

**Expected Results:**
While you carry someone you can't run by any means

**Actual Results:**
While you carry someone and have F3 Menu open, you can run.

## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
CID: 719

**Server:**
Latin America

**Comment by InZidiuZ** [comment]
Running has been disabled while in the menu for now.
