### ISSUE TITLE
[game/Vehicles] New Tow Truck

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1250]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**

So, there are some tow trucks available in GTA 5, which can improve the RP of mechanics.

Option 1: **Clean Vanilla Tow Truck [Replace] [ALL LODS] (Lore Friendly)**
https://www.gta5-mods.com/vehicles/clean-vanilla-tow-truck-replace-all-lods-lore-friendly

Option 2: **Benny's Custom Tow Truck 1.5**
https://www.gta5-mods.com/vehicles/bennys-custom-tow-truck

**Tow Truck for LSPD: https://www.gta5-mods.com/paintjobs/lspd-tow-truck**

You can replace MTL Flatbed with Option 1
and You can add Option 2 in PDM.

**Reason:**

This tow trucks don't need /tow command to tow trucks but there should be option to impound vehicle when this vehicles reach to impound lot.  plus sometime it's difficult to tow some vehicles, so this vehicles can solve this problem. 

and about LSPD tow truck: there are RP situation when LSPD need tow truck to tow vehicles used in crimes like robbery to seize them. this tow truck will help them a lot even if there are no mechanic available in city.

**Comment by InZidiuZ** [comment]
Add-on vehicles will not be used as job vehicles as that would make them at a constant 'required', so no.

**Comment by z-Lunar** [comment]
to add to this even though its closed, Tow trucks with "Hooks" don't work in a stable manor as is.
