### ISSUE TITLE
Bug report - Clothing Store with NO clothing menu

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#1251]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Never (jk - yes)

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/FearingMANiac/

**Summary:**
Write a short summary of what you are experiencing.
Clothing store near michael's mansion does not have a clothing menu or any clothing indicator on the map.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Go to the location marked in the screenshot section of this report.

**Expected Results:**
What are the expected results?
Enter clothing store and see a clothing menu.

**Actual Results:**
What are the actual results?
Enter to find a clothing store interior with no clothing menu.

**Screenshots:**
https://imgur.com/zL19Kxd

**Game Resolution:**
What is your game's resolution?
1920x1080

**Server:**
What server/community did this issue occur in?
Legacy EU/NA main servers

**Comment by InZidiuZ** [comment]
This has now been added.
