### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by hetpatel3** [InZidiuZ/op-framework-issue-tracker#1252]
My vehicle inventory is stucked. i stored thermites, guns, handcuffs, and many more things but after server restart, there are lots of burgers, coke and medi kits which are not stored by me.
and also server are not stable from today. At some place vehicles are constantly spawning in air and getting down and then gayab and then repeat.

when i get my items back?
i stored all items there [my all items], please do something.

**Comment by InZidiuZ** [comment]
Read through the rules in the `README.md` file in the root folder of this GitHub repository.
