### ISSUE TITLE
[properties/properties] Add a personal garage to Eclipse Boulevard

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1253]
**Summary:**
A suggestion was made almost a year ago asking for a garage at Eclipse, but instead a new local garage was set up a few blocks away. With the current standard of needing to get a car quickly, and the fact that there is an actual garage next to the block, it makes sense that there should be an ability to be able to get out a car here. Currently there is NO garage at Eclipse because it was removed due to cars clipping with the garage door. My suggestion is to place back the spawn for cars but to move it onto the drive way so it is safe for cars to come out.

**Reason:**
Eclipse Boulevard is the location and home of a whitelisted gang on Legacy EU/NA. We need the ability to take out a car on our turf and ride it out of the turf which can protect us and keep us a mystery ever so slightly. We purchased the property under the impression that there would be a nice garage to take out vehicles at. Other tenants should also in the future have access to a personal garage as it is a great block.

**Additional Information:**
Eclipse Boulevard has Block ID: 77

Tenants at the following houses should have access to the garage:
Eclipse Boulevard 1
Eclipse Boulevard 2
Eclipse Boulevard 3 / Apt1
Eclipse Boulevard 3 / Apt2
Eclipse Boulevard 3 / Apt3
Eclipse Boulevard 3 / Apt4
Eclipse Boulevard 4
Eclipse Boulevard 5

Some screenshots of where the spawn location for vehicles could be:
https://prnt.sc/tulekk
https://prnt.sc/tulfkf
https://prnt.sc/tulfxl
https://prnt.sc/tulg8z

**Comment by Bhavesh02** [comment]
I agree with him

**Comment by S3WAGST4R** [comment]
+1

**Comment by Foolhardy-Orc** [comment]
I agree with him

**Comment by Masik52** [comment]
Any chance on this being added in?

**Comment by Masik52** [comment]
Bumping this up as I have people living on this block and they’d like to have a garage to store their cars

**Comment by Masik52** [comment]
Any chance of this being added?

**Comment by Masik52** [comment]
Tossing a little bump to this I’m hopes that it’s seen. I have tenants that have been requesting a garage be added for these properties

**Comment by twooot** [comment]
There is a garage therre now
