### ISSUE TITLE
[alpha/bank_robberies] After Closing Bank Vault PD Officers get stuck in Bank with Locked Doors

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1255]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/id/nohbob/

**Summary:**
After using the /closebank command on the Vault door after a robbery of the bank, you cannot leave the front doors.  You need someone to /carry out of the front. 

**Steps to Reproduce:**
1.  Have someone open the Vault
2.  With PD Role /closebank
3.  Walk up to the front doors, you are unable to walk out the front door. 

**Expected Results:**
PD members can walk out of the front door. 

**Actual Results:**
You get stuck inside the bank with a message reading that the bank is closed. 

## Additional Information

**Screenshots:**
Sadly No. 

Game Resolution:
2560 x 1440

Player Data:
- Sadly did not take it down. 

Server:
Main

**Comment by Masik52** [comment]
Here is a link of us attempting a bank robbery in the test server showing after popping the vault door open the cage door can't be lockpicked or opened via thermite.  I'm not sure if the new door lock script is possibly causing the issues with the cage door.  Also once you close the bank if you're inside you cannot walk through the doors as PD like you used to be able to.  Also the banks stay in that state until restart as it doesn't seem that the cooldown is working on it at the moment on unlocking the front door. https://youtu.be/GBRcY4DOL2M

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
