### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by S3WAGST4R** [InZidiuZ/op-framework-issue-tracker#1257]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Remove voice chat and add tokovoip back

**Reason:**
Why would your suggestion be a good change to the framework?
Bcauz the voice is lagging of others and some of other voice is cmg like guitar

**Comment by InZidiuZ** [comment]
I'll take a second to consider it...

No.
