### ISSUE TITLE
Bug report press e interface not showing

### ISSUE THREAD

**Issue by swetax** [InZidiuZ/op-framework-issue-tracker#1258]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Follow the template.
