### ISSUE TITLE
Less servers at slow periods of the day

### ISSUE THREAD

**Issue by ZKNukeZ** [InZidiuZ/op-framework-issue-tracker#126]
**Name:**
ZK NukeZ#2275

**Summary:**
Have only 2 servers online at all times, then open a 3rd when they get full, and so on.

**Reason:**
Stop people being scattered over all the servers, more people on 1 server = more chances of rp

**Comment by InZidiuZ** [comment]
Hey,

At this time, this won't happen. Maybe later on.

**InZidiuZ**
*OP-FW Developer*
