### ISSUE TITLE
Chop hot cars not being at the locations

### ISSUE THREAD

**Issue by stormin88** [InZidiuZ/op-framework-issue-tracker#1260]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Player Identification:**
https://steamcommunity.com/profiles/76561198272382233/

**Summary:**
On average if you go to 10 hot car locations using the chop radio. 2 out of 10 will actually be there.

**Steps to Reproduce:**
Show up to the chop hot car location.

**Expected Results:**
To find a chop hot car

**Actual Results:**
Finding no chop hot car

## Additional Information
Chop was working half decent leading up until the most recent update. Now you get super lucky if actually find the car. Also chop car radio will say the car is in the area of Mt Chiliad on Strawberry ave or another impossible combination and cannot find. Chop has never fully worked since its integration and would really like to a see a good working version of chop.

**Server:**
Server #1

**Comment by InZidiuZ** [comment]
This has already been addressed multiple times. See #1098.
