### ISSUE TITLE
Police - Plate Reader and Radar default key binding no longer works

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1261]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
https://steamcommunity.com/id/nohbob/

**Summary:**
The default key binding for Plate Reader and Radar no longer works (F5), it only works after you rebind the default key

**Steps to Reproduce:**
1. Have PD Job
2. Pull out a police cruiser
3. Press F5 to bring up Radar
4  Go into menu and rebind Radar (FiveM Menu)
5.  Press rebound key, it works. 

**Expected Results:**
When you press F5, it brings up Radar/Plate Reader

**Actual Results:**
It does not work until you rebind the key.

## Additional Information

**Screenshots:**
- None

**Game Resolution:**
2560 x 1440

**Player Data:**

**Server:**
EU/NA

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
You need to "reset" your keybind:

Settings > Key Bindings > FiveM > Open Remote Control 

Rebind the F5

**Comment by Nuziatella** [comment]
I need to learn to read. But you are correct rebinding solves the issue

**Comment by InZidiuZ** [comment]
Not an issue directly related to the framework, so this will not be investigated at this time.
