### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KidDano** [InZidiuZ/op-framework-issue-tracker#1263]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
Dano_i_

**Summary:**
The second door in the vault doesn't open when you use the lock pick and when an officer closes the bank, the officer cant exit the bank 
**Steps to Reproduce:**
rob a bank
**Expected Results:**
I expected this to work as it is the only fkn shit we can rob and it doesn't even work 
**Actual Results:**
doesn't open the fkn door 
## Additional Information
Ben is shit coder
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
LATAM SERVER
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Sorry but you forgot you game's resolution. Please create another issue.
