### ISSUE TITLE
[vehicles/keys] Addition of a /key feature

### ISSUE THREAD

**Issue by armadamYT** [InZidiuZ/op-framework-issue-tracker#1266]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Name:**
Armadam#2431

**Summary:**
A /key feature maybe added to enable the key to a vehicle to remain in the ignition of the vehicle and will be transferred to the inventory of the next person who drives it.

**Reason:**
The /key feature will trigger the same event as the F key(to exit the vehicle, moving or otherwise) but will keep the key to the vehicle,in the vehicle itself and keep the engine running so that another player can drive it immediately without needing the player originally driving it to do a /givekey.
Often in a situation if the driver of a vehicle needs to be changed, people need to pause the RP, do /givekey and start the vehicle by /engine and then continue.
Also, usage of /givekey is quite uncertain if entered without the server ID number and used in the presence of multiple players as keys are often transferred to the wrong player which results in unrealism in RP and creates confusion.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
