### ISSUE TITLE
A solution for trams and train glitching/randomly despawning.

### ISSUE THREAD

**Issue by armadamYT** [InZidiuZ/op-framework-issue-tracker#1267]
**Assurance:**
Yes.
**Name:**
Armadam#2431
**Summary:**
 Server end sync of position of trams and freight train in server.
**Reason:**
A very common glitch right now in trams is that one tram goes into another when arriving at a station and causes a glitch which sometimes results in player dying.
A solution for this is a server end sync of the position of trams and freight train in server(kind of like the train in apex legends which keeps looping around). The train tracks and the subway tracks are made in a loop in the map of Los Santos. The train can be made as a server end entity which syncs its position directly to the server and hence is common for all the players.

Similarly instead of trams remaining static at subway stations, 5-6 trams can be made as server end entities which loop around the tracks. They can remain behind each other at a comfortable gap and the players can expect trams at some equal intervals(4-5 mins or so). This will also enable "waiting for my train" kind of civilian-RP. To get into a tram, tickets need to be purchased from the ticket booth(which are already usable). These tickets can also be an entity like a vehicle key without which you cannot enter a tram.

**Comment by InZidiuZ** [comment]
...yea, this won't work with FiveM/OneSync in its current state.
