### ISSUE TITLE
[jobs/taxi] Something to do on taxi job downtime.

### ISSUE THREAD

**Issue by omgpointless** [InZidiuZ/op-framework-issue-tracker#127]
**Name:**
OMGPointless#1823

**Summary:**
So, I've been clocked in for hours now. I try to tweet etc, but since it's in the phones not many people pay attention (or care) and the reasons why people want taxis right now aren't maybe that many, so the fares have been few to say the least. I can't remember how many hours I've spent in the taxi, and the hours spent have been for the hopes to get an interaction. That's why I love the job, and the connections you establish to people.

_HOWEVER_, as an actual job it's pretty bad. At least for the wallet. There's nothing to do the vast majority of the time. And while I appreciate the salary fix, I don't want to be paycheck farming either. So I do believe that my suggested feature will have both short and long term positive consequences for the profession, the community and the city.

My suggestion is to add downtime activity as a source of income, that would per hour be at least comparable to the garbage job. And, I know from my hours from another server, that stimulating the taxi economy and making the job fun and interesting is a real struggle. No matter how much you want personal interaction, there has to be a landscape where they want or need to order a taxi. And with clients being sparse, I believe other game mechanics should be put in place to allow and enable it to be viable as a full time job, and to make the job more fun, interactive and dynamic.

### Source of activity would be; **Driving stupid NPCs**

No surprises really. Nothing fancy. Here's my bullet list for how I see it work:
* Have designated areas, "hot spots" where taxi people can idle. 
Why: I think target zones are easier to code, and from an UX perspective having specific locations where the "Press E to "-tooltip shows, makes it less intrusive and reduces complexity. From an RP perspective it would make sense as some people will prefer some spots more, and after running into each other enough - start talking and "eyyy loui you stole my guy you son of a gun".

* At said "hot spots", it would work similarly to a certain illegal substance transaction. A tap on E, NPC gets interested with RNG chance to succeed, NPC gets into backseat and you get a marker where he wants.

* When you arrive to the location, you get paid in cash, like the transporter or garbage job. The NPC exits the vehicle and, if possible, speaks a voice line like the guys downtown after you have a transaction with them and walks away.

* You are free to do whatever, advertise your buisness, "Hey I'm in Paleto right now, if anybody needs a taxi. Hit me up!". And if it's still quiet maybe you go to another hot spot and go for another client.

If concerns arise in terms of "but if he can taxi NPCs there is no reason to drive players", which I agree would be negative to the profession. If that should happen, one could imagine a cooldown being in place, with a "There are no pedestrians interested at this time". And if the $ payout is balanced accordingly, there should be no reason to pick taxi solely for the money, as other jobs would or could pay better. Again, this is not to buff taxi to a great money maker, just to make it viable as a full-time profession.  

**Reason:**
Why would your suggestion be a good addition to Legacy?
For the big picture meta I think there needs to be a big selection in terms of viable occupations, legal and illegal, which ideally should have organic ways to generate interactions. I feel there's a risk that players will be forced into some professions due to huge gaps in the payout. Which may turn the city into Phantom Lettuce heaven. And while I don't want to take anything away from those jobs or activities, I want to add taxi to the mix, so when you start as a new player you can actually get on your feet regardless of what you choose. (with journalist being the exception, that's for another issue). I think it would stimulate the profession, that would have the side-effect of more taxis being in town. With more taxis in town, it can make it both easier and more convenient to get around in a legal fashion, and with more taxis you don't have to wait for a guy to drive all the way from Paleto to get to you (nobody likes waiting). And perhaps most importantly, when you order a taxi. Somebody actually answers.

Looking at the prices at Beny's for my taxi upgrades, it's gonna be a long time if I keep having 0 calls. And if I have 0 calls, I have to switch over to Transporter and do some trucking to upgrade my taxi. Consequence being that if I'm not clocked in as taxi - I can't answer a taxi request if one should come. Effectively making people not want to try next time if they don't get answers or nobody is there.

Code wise, I reckon you have most of the scaffolding for it. I know you have parts of the whole "detecting pedestrians". But I reckon the vehicle interaction might be less than straight forward and piecing that all together. But I bet you'll do it in a weekend ;)

![20190630013717_1](https://user-images.githubusercontent.com/2750716/60391272-bd45be00-9aea-11e9-923b-295dd9540431.jpg)
_fastest taxi in los santos, cus I know inzid likes screenshots as much as I do (only probably not irrelevant ones)_

**Comment by SteezyRen** [comment]
>Which may turn the city into Phantom Lettuce heaven.

Read this and laughed and agree with at the same time.
News reporters currently make no money and really only know of one person who is willing to do the job for the RP. Reporters could probably use higher fixed salaries due to not being able to earn revenue outside of their salary.

**Comment by essjaybee** [comment]
Yeah I agree with you @SteezyRen, I think Journalist is the exception though, that probably just needs to be communicated better to newcomers as to what the role and purpose is. We've seen a bunch of great clips already being posted and so I think their status of being able to be "on" and "off" doesn't have as much of a negative consequence to the services available. But, I think that job in particular probably needs to be discussed in a seperate issue thread. Because there are issues with putting the salary too high, people choosing it for the wrong reasons etc etc. 

I might be mistaken, but I think the staff members are reviewing the material made by the journalists and those that do quality stuff I'd assume would get more beneficial roles within that department. But I'm wildly guessing based on assumptions there.

**Comment by jaymssmith** [comment]
this is a very good idea
It makes taxis very viable

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
