### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by IamCyanide** [InZidiuZ/op-framework-issue-tracker#1272]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561198993120801/

**Summary:**
I created my 3rd character but didn't get ant money. Is it a glitch? Bank and Cash both are 0-0

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
Fix this please so that i can start a new life.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
1920x1080

**Player Data:**
![20200807155520_1](https://user-images.githubusercontent.com/69347550/89636651-94375580-d8c6-11ea-90d6-9d170ad2c96d.jpg)

**Server:**
Server 1

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
You probably have created more than 4 characters, preventing you from getting starter money. These characters may be deleted as well, they'll still count.
