### ISSUE TITLE
[game/injuries] Hold Enter to Respawn Option

### ISSUE THREAD

**Issue by gameshots1** [InZidiuZ/op-framework-issue-tracker#1273]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Summary:**
Whenever someone is down we have the option to "Press Enter to Respawn" but at times where multiple people involved in a situation where the downed person have an advantage over other people to Respawn and impacting the RP of other as well, later when they get banned for the same reason they give excuses of wrongly muscle flex etc. But "Hold Enter to Respawn" option will avoid all those scenario of FailRP and giving all equal opportunity for the Quality RP.

**Reason:**
Adding this functionality will majorly influence people do quality RP since those who try to ran out of several situation will not have an excuse like they did alt+tab, Wrongly muscle flex etc.

**Comment by BmFarhan** [comment]
+1

**Comment by Imaghost1337** [comment]
+1

**Comment by MukeshKC607** [comment]
+1

**Comment by EvilGhost5** [comment]
+1

**Comment by S3WAGST4R** [comment]
+1

**Comment by KidDano** [comment]
+1 It does happen a lot that ppl just click it on accident, would be great that they have to hold it for at least 10-15 seconds and increase the time for it to be available, this would help with the ppl that say they did it on "accident"

**Comment by KaiEagle** [comment]
btw how about adding this sooner :?

**Comment by InZidiuZ** [comment]
This has since been done.
