### ISSUE TITLE
[game/shield] Limit which weapons can be used alongside the shield

### ISSUE THREAD

**Issue by armadamYT** [InZidiuZ/op-framework-issue-tracker#1274]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
1.The ballistic shield should be used only with handguns and not SMGs, ARs and shotguns.
2. The ballistic shield should be shown on the back of the player like other items like guns. 

**Reason:**
The ballistic shield should be displayed on the back of the players like guns for more realism.
Secondly ,the current animation of usage of ballistic shield is very unrealistic with ARs with basically no reload animation. Also it might be too overpowered in some situations, A way to combat this is to enable only some weapons to be used with it. The weapons can include all pistols, micro SMG, mini SMG, Machine pistol, sawed off shotguns and revolvers (Mk2 variants of all mentioned also). Marksman pistol should be intentionally left out.
This will at least give criminals a fighting chance against the SWAT/PD.

**Comment by InZidiuZ** [comment]
> The ballistic shield should be displayed on the back of the players like guns

This is unlikely to be done anytime soon.

> Secondly ,the current animation of usage of ballistic shield is very unrealistic

We're *modding* a game here, so animations won't always be optimal for our usage, so we'll have to make to of what we can find.

>This will at least give criminals a fighting chance against the SWAT/PD.

There is still plenty of areas for the player using it to be shot at, so I wouldn't imagine this would be very OP.

Though we could possible do something about which weapons can be used alongside it. I'll be adding the 'feedback' label on this post, hopefully encouraging people to come with input or votes.

**Comment by armadamYT** [comment]
Understood all your points. The animation point was just to emphasize that a person cannot hold a shield and an AR like that IRL too. Obviously animations cannot be creates by us. 
I would suggest to open up a vote on the main server dc or in the OP-FW dc if they want guns to be limited. Putting an announcement that is shown in all the servers to come vote can be done.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
