### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tuinhalder** [InZidiuZ/op-framework-issue-tracker#1276]
**Assurance:**
yes

**Player Identification:**
https://steamcommunity.com/id/TUHINHALDER2020/

**Summary:**
when i parches jarry can  and filing my bike the game is stack and error msg   
**Steps to Reproduce:**
parches jarry can  and filing my bike the game is stack and error msg   

**Expected Results:**
carry jarry cen and when my car fuel down i fill the fuel

**Actual Results:**
naver go petrol pump randomly 

## Additional Information

**Game Resolution:**
1920*1080

**Server:**
server 1

**Notes:**
no

**Comment by InZidiuZ** [comment]
Please create coherent reports...
