### ISSUE TITLE
[game/companies] Employee's have access to Company Funds

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1278]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Employee's of registered companies (under the /companies tab) should be able to be promoted to have access to the company funds account. For instance, if the owner of the company promotes a valuable worker, they can have access to the company funds and may deposit or withdrawal. There could even be a withdrawal/deposit log on the companies tab that can show deposit and withdrawal history. 

**Reason:**
This would give more leniency for businesses. If the owner is not around at all times of the day, then a trusted employee could run the company and have access to the account while they are aware. More specifically, for my character's business, large amounts of money are withdrawn and deposited all the time. The company account funds need to have a large safety net in case someone wins big at the casino. Employees would be able to draw from this account to fund aspects of the business, like paying people out. The log system would also just keep track of who is entering the account and withdrawing from the account.

**Comment by InZidiuZ** [comment]
More flexibility within the company system is planned, but the current system is deprecated and set to be rewritten at some point, and there are a lot of other tasks that are higher priority, so it's unlikely anything will be done about this in the near future.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
