### ISSUE TITLE
Bug report [ping/connection,peds issue after reconnecting in server version alpha 2.7]

### ISSUE THREAD

**Issue by BmFarhan** [InZidiuZ/op-framework-issue-tracker#1279]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/V4P1D/
**Summary:**
Write a short summary of what you are experiencing.
Usually, I play on Legacy Roleplay Bangladesh, in this case, I'm facing this issue also in Legacy roleplay India. Like when I enter the server, on the character selection tab/home tab I usually get 80-100ms ping. But after that when I select a character and it spawns on the ground, then I get 300-500ms ping, after that my ping goes very high like 1000ms. But the main point here is when my ping goes very high, after that, it shows a red mark saying that, CONNECT INTERUPTTED! and also saying that RECONNECTING TO THE SERVER..although I again got reconnected but, the thing is, after that thing getting bugged. like I can't see any of players, their steam id's over their head, also the peds. In this case, they[players] can see my ped, hear my voice like everything normally. And in my case, it doesn't.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
IDK why this things are happening. so I don't know how to Reproduce these things.
**Expected Results:**
What are the expected results?
After spawning my ped, my ping should be normal. or After getting the Connect Interuptted sign, when I got reconnected, I should be able to see the peds.
**Actual Results:**
What are the actual results?
After spawning my ped, my ping isn't normal. or After getting the Connect Interuptted sign, when I got reconnected, I am not able to see the peds and also the steam id of the player[over head].
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay Bangladesh
Legacy Roleplay India
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Not at all related to the framework's development.
