### ISSUE TITLE
Bad locations for hot vehicles

### ISSUE THREAD

**Issue by Daraion** [InZidiuZ/op-framework-issue-tracker#128]
**Reporter:**
Who is reporting this? Please include discord name. Daraion#7251

**Summary:**
Write a short summary of what you're experiencing.
The spawns for vehicles on hot cars to chop spawn unaccesable areas where you can get into but you can see through a fence or in a garage that will not open.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Natural occurring

**Expected Results:**
What are the expected results?
Being able to locate and access all vehicles

**Actual Results:**
What are the actual results?
Either miss information on the radio or cars in areas which are not accessible in any way possible.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
I have a recording if necessary

**Game Resolution:**
What is your game's resolution?
1900x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 1721

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

The hot vehicle is randomly decided from game memory, meaning I don't create the spawn locations. What I could do, however, is blacklist certain locations to prevent these vehicles from being picked as a "hot" vehicle.

Are you able to provide the locations this has been happening at?

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
Closing due to no response. Feel free to comment here later if you find any spots.
