### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BLUD-REAPER** [InZidiuZ/op-framework-issue-tracker#1281]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198955919349/

**Summary:**
I am facing the Problem Of inventory Not Opening since the update.

**Steps to Reproduce:**
FleX the K Muscle

**Expected Results:**
Inventory Open

**Actual Results:**
Inventory is not opening

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=EXqdXbQH4hE

**Game Resolution:**
1980x1080P

**Player Data:**
CID:- 1223.

**Server:**
Legacy india Roleplay

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.

**Comment by BLUD-REAPER** [comment]
I am facing the same issues again and again
