### ISSUE TITLE
MOUSTACHE ERROR 

### ISSUE THREAD

**Issue by 7263-8** [InZidiuZ/op-framework-issue-tracker#1282]
Mustache getting removed even after saving the outfit with the mustache . 
I went to barber shop and apply mustache , then went to outfit shop and chose the outfit i want and saved the outfit by this command :  /saveoutfit 5 
and when i apply the outfit 5 by command : /outfit 5 
OUTFIT gets applied but mustache is removed  and also whenever my player spanws to last position or any location his moustache is removed , 
My friends are saying that this character of free model i have made is glitched so i request you to help me in editing character , or give me the desired solution .

**Comment by InZidiuZ** [comment]
Read the README file
