### ISSUE TITLE
Cannot save a contact or send message from phone

### ISSUE THREAD

**Issue by bhaveshpawar** [InZidiuZ/op-framework-issue-tracker#1283]
Whenever i open my phone to save any contact and do a mouse click to start typing,
![20200810_165824](https://user-images.githubusercontent.com/36239514/89779323-b205f400-db2c-11ea-8f1e-0b5ff2cde832.jpg)
 my screen is freezed and i get a pop up saying "Five m game subprocess not responding"

**Comment by InZidiuZ** [comment]
Read the README file
