### ISSUE TITLE
The Game is crashing while i am trying to mark a location on the map and when the moment i hit esc it immediately crashes out of nowhere.

### ISSUE THREAD

**Issue by SharkyDi3** [InZidiuZ/op-framework-issue-tracker#1284]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? No :(

**Player Identification:**
What is your steam profile? https://steamcommunity.com/profiles/76561198930821382/

**Summary:**
So I am entering into the server and loading up the character and the moment i open the map and mark a location the game is crashing it has been happening since this morning and i think i am the only one who is experiencing this issue. There is an error message and a crash report log.( which i will provide below )
Please try fixing this.

**Steps to Reproduce:**
I have no idea how this issue will be solved.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
[url: https://imgur.com/vuxDzvd]

**Game Resolution:**
1920*1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file
