### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by farhan878** [InZidiuZ/op-framework-issue-tracker#1285]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/fshahriar/
**Summary:**
Write a short summary of what you are experiencing.
In Legacy Roleplay BD, I cannot do yoga or there is no option of doing in the yoga spot. This issue is happening with me after ther Alpha 2.7 update. Even I cannot see the yoga mats there.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Please Fix that issue 
**Expected Results:**
What are the expected results?
I think I can do yoga in that place very soon
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1280*720
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
My name is Tom Cruse in the game. My steam id link:  https://steamcommunity.com/id/fshahriar/
**Server:**
What server/community did this issue occur in?
Legacy Roleplay Bangladesh
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is due to a setting causing a low amount of ambient objects. Try turning all your density-related options to the max. [These](https://gyazo.com/e82de9ada1e2067ee2913aaaebaa5273), perhaps.
