### ISSUE TITLE
Jerrycan fueling error

### ISSUE THREAD

**Issue by subhankardash9704** [InZidiuZ/op-framework-issue-tracker#1287]
**Assurance:**
read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
subhankard68@gmail.com
**Summary:**
Write a short summary of what you are experiencing.
While i'm trying to top up the fuel in my truck, I'm getting an error message and after closing that dialogue box my character freezes. Ultimately I had to disconnect from the server and rejoin.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Getting a jerrycan> try fueling my truck> error message
**Expected Results:**
What are the expected results?
Should fill up fuel in my truck
**Actual Results:**
What are the actual results?
An error message pop ups and after closing it, the character freezes in the fueling possition.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![Screenshot (84)](https://user-images.githubusercontent.com/69472722/89801912-5e0c0700-db4e-11ea-86d7-46a0f0b41f05.png)

**Game Resolution:**
What is your game's resolution?
1920*1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Screenshot (109)](https://user-images.githubusercontent.com/69472722/89802552-45e8b780-db4f-11ea-84dc-b437fb4f5baa.png)

**Server:**
What server/community did this issue occur in?
Server #3- Indian Public
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
