### ISSUE TITLE
pillbox issue 

### ISSUE THREAD

**Issue by amanmishra7** [InZidiuZ/op-framework-issue-tracker#1288]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
What is your steam profile?
aman0as7@gmail.com

**Summary:**
Write a short summary of what you are experiencing.
as i enter pillbox from the front gate i go underground and end up dead in a tunnel . and when i respawn the same happens again 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
entering pillbox>going underground>leing dead in an underground tunnel>respawn after 5 minutes>same 

**Expected Results:**
What are the expected results?
proper enterance and treatment in pillbox 
**Actual Results:**
What are the actual results?
proper entering pillbox
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1280 X 720
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![0_20200810233704_1](https://user-images.githubusercontent.com/69478474/89815544-9ae1f900-db62-11ea-8fec-de3773fbe0b0.png)

**Server:**
What server/community did this issue occur in?
139.99.125.59:30120
139.99.125.59:30121
139.99.125.59:30122

**Notes:**
For anything else noteworthy.
please fix this soon i have lost a lot of stuff by now

**Comment by cammybruh** [comment]
I also had this issue. When loading into the city don't tab out. Also make sure your computer can handle the graphics settings that you currently have set up. This is normally fixed by hard napping.

**Comment by InZidiuZ** [comment]
This belongs to the assets-related issue tracker.

**Comment by amanmishra7** [comment]
inZdiuZ what does that mean
i am still facing this issue

**Comment by DaxterPancake** [comment]
This means that you need to direct this to [THIS](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) github.
