### ISSUE TITLE
Bank/Vault - Locked Cage Door behind main Vault door does not function

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1289]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
https://steamcommunity.com/id/nohbob/

**Summary:**
After successfully opening the main vault door, you are unable to Thermite or Pick the  Locked Cage door to gain access to the bank boxes. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
1. Open Vault Door
2. Attempt to lockpick or thermite second door.
3. Neither functionally opens the door. 

**Expected Results:**
The door opens

**Actual Results:**
The door does not open

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=GBRcY4DOL2M&feature=youtu.be

Game Resolution:
2560 x 1440

**Player Data:**
Not listed but see the Video Above

**Server:**
Both NA/EU and Test.  Please note this was done on Test.  

**Notes:**
This is currently preventing folks from doing banks at all on the main server.

**Comment by cammybruh** [comment]
Please hot fix this!

**Comment by xRunnin** [comment]
having the same issue at Latin America.

**Comment by Mugdha57** [comment]
fix this asap

**Comment by Mugdha57** [comment]
same problem we are facing in our sub division legacy BD server as well as @InZidiuZ

**Comment by InZidiuZ** [comment]
Closing for #1265
