### ISSUE TITLE
Suggestion | Police vehicles speed and handling changes.

### ISSUE THREAD

**Issue by lucifer019** [InZidiuZ/op-framework-issue-tracker#1292]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
The police vehicles are going really slow and their handling are really bad comparing to local vehicles and other personal vehicles, I don’t know if it was intentional or not but the police bike is going 135 max and charger is going 160 max while simple local vehicles are going 200+ easily.

**Reason:**
Why would your suggestion be a good change to the framework?
The police vehicles should me better than civilian vehicles, its not possible to give them proper chase with these speed and handlings, if you did this intentionally than I don’t think its a good addition because police is always and should be op than civilians.

**Comment by InZidiuZ** [comment]
> Have you read through the rules from the README.md file in the root folder of this GitHub repository?

Do this
