### ISSUE TITLE
Towing: Occasional Bug

### ISSUE THREAD

**Issue by KookieNCoffee1** [InZidiuZ/op-framework-issue-tracker#1293]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Player Identification:**
What is your steam profile?
nefxl1m1tl3ssx

**Summary:**
Write a short summary of what you are experiencing.
While towing, occasionally there is a problem where a car is completely unable to be towed unless I get in and out of it then do the /tow command. This is especially a problem when the car is locked, as then that car is completely un-towable unless it is lockpicked into.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I believe it happens when a car is left alone for a set amount of time, with no one entering or leaving the vehicle. I am unsure exactly how it can be replicated, but I have run into this problem more than I can count on my fingers.

**Expected Results:**
What are the expected results?
You should be expected to /tow a car, and have it go onto the flatbed without the need to enter and exit the car being towed.

**Actual Results:**
What are the actual results?
Unable to actually tow a car. Doesn't budge. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Character ID: 6767 - Job Data: Mechanic. Los Santos Customs, Tow Driver Timestamp: 2020-08-13 04:24:56

**Server:**
What server/community did this issue occur in?
US Legacy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
There *are* ways of resolving this, but the towing system is deprecated and set to be removed and replaced by a more thorough one at some point in the future, so I will leave this as a wontfix for now.
