### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by gautamkhanduja** [InZidiuZ/op-framework-issue-tracker#1294]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.
Many a times after new update all people get stuck and u can only their voices(sometimes not even voices)and it is happening very frequently which leads us to leave server and join back

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
When ping goes high and it shows connection interrupted and again ping gets stabled it happens

**Expected Results:**
What are the expected results?
All activities happening at the current time with people moving

**Actual Results:**
What are the actual results?
People get stuck and if u try to talk to stuck people who are stuck only in my screen cannot hear us and we are not able to see many people around sometimes
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Most likely a FiveM issue. There already is an issue on potential VOIP issues, #1264.
