### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nazar005** [InZidiuZ/op-framework-issue-tracker#1295]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/nazarahmad5/

**Summary:**
Write a short summary of what you are experiencing.
whenever i am trying to change clothes in any clothing store and reach to a blue camouflag type shirt or hoodie then my game crashes and it happens always when i try to change my clothes

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
try to resolve it

**Expected Results:**
What are the expected results?
to solve the issue of crashing the game 

**Actual Results:**
What are the actual results?
as soon as i try to change clothes game crashes and am unable to do anything

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![Screenshot (326)](https://user-images.githubusercontent.com/69644679/90165670-a4fc3580-ddb6-11ea-9a34-77442ae8caa7.png)

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
india legacy 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file, this belongs to the assets-related issue tracker.
