### ISSUE TITLE
Zion handling bug

### ISSUE THREAD

**Issue by bangladeshas** [InZidiuZ/op-framework-issue-tracker#1296]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/d1sco_jesus/
**Summary:**
Write a short summary of what you are experiencing.
Zion's handling is broken, reaching over 300mph on a first gear, seems like someone forgot to put a decimal on fInitialDriveMaxFlatVel
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Taking a car and driving
**Expected Results:**
What are the expected results?
driving normally
**Actual Results:**
What are the actual results?
read above
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Lithuanian server
**Notes:**
For anything else noteworthy.

**Comment by bangladeshas** [comment]
Applies to Zion Cabrio, since they both use the same handling data originally.

**Comment by InZidiuZ** [comment]
Wrong issue tracker
