### ISSUE TITLE
Bug report about bikes and car

### ISSUE THREAD

**Issue by toxicgamer6x6** [InZidiuZ/op-framework-issue-tracker#1300]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198857923541/
Write a short summary of what you are experiencing.
i am playing in the server about i am having a good experince but  i have bought the bike tommorow and i found the bug that i cant take out my bike
**Steps to Reproduce:**
can u fix that as soon as possible

**Screenshots:**
If suitable, include some screenshots.
https://media.discordapp.net/attachments/674837268174995489/743688041196945508/20200814_100038.jpg?width=902&height=677

**Server:**
What server/community did this issue occur in?
legacy india in five m

**Comment by InZidiuZ** [comment]
Read the README file
