### ISSUE TITLE
Bug report about bike and car in garage 

### ISSUE THREAD

**Issue by toxicgamer6x6** [InZidiuZ/op-framework-issue-tracker#1301]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198857923541/
**Summary:**
Write a short summary of what you are experiencing.
as i bought the dike tommrow and today morning i tried to take out the dike from the garage it is telling to report
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
not sure 
**Expected Results:**
What are the expected results?
i cant ritrive the bike
**Actual Results:**
What are the actual results?
i cant take out my new dike from garage
## Additional Information
n/a
**Screenshots:**
If suitable, include some screenshots.
https://media.discordapp.net/attachments/674837268174995489/743688041196945508/20200814_100038.jpg?width=902&height=677
**Game Resolution:**
What is your game's resolution?
1920*1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://media.discordapp.net/attachments/674837268174995489/743688041196945508/20200814_100038.jpg?width=902&height=677 

hear is the pick
**Server:**
What server/community did this issue occur in?
legacy india
**Notes:**
For anything else noteworthy.
N/A

**Comment by InZidiuZ** [comment]
> Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

...can you do this?

**Comment by toxicgamer6x6** [comment]
Ok I am giving me me 10 min

**Comment by toxicgamer6x6** [comment]
![15974155294045126165197230774606](https://user-images.githubusercontent.com/69682667/90260424-17c5e900-de69-11ea-89c6-d81a26c675fc.jpg)

**Comment by toxicgamer6x6** [comment]
Sir I have posted

**Comment by InZidiuZ** [comment]
Can you post a picture of which vehicle it is in your garage as well? Preferably with the plate, if you can get that.

**Comment by toxicgamer6x6** [comment]
Yes

**Comment by toxicgamer6x6** [comment]
![15974158755731192953050988012272](https://user-images.githubusercontent.com/69682667/90260923-dc77ea00-de69-11ea-9374-5600b8527e5c.jpg)

**Comment by toxicgamer6x6** [comment]
https://cdn.discordapp.com/attachments/674837268174995489/743841439133204560/20200814_201012.jpg

**Comment by InZidiuZ** [comment]
The error has been resolved, though you can still spawn it if you first try to retrieve it from the "Retrieve Vehicle" menu.

**Comment by toxicgamer6x6** [comment]
Nothing is happening

**Comment by toxicgamer6x6** [comment]
Solve thanks

**Comment by toxicgamer6x6** [comment]
Sir reall thanks

**Comment by toxicgamer6x6** [comment]
Sir I need one more help

**Comment by toxicgamer6x6** [comment]
Weed tree is growing 120percent but still I can't harvert
