### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by BLUD-REAPER** [InZidiuZ/op-framework-issue-tracker#1303]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198955919349/

**Summary:**
the Previous Issue Has Not been Solved  (Bugreport#1281)
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1281

**Steps to Reproduce:**
FleX the K Muscle.

**Expected Results:**
Inventory Open

**Actual Results:**
Inventory is not opening

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=EXqdXbQH4hE

**Game Resolution:**
1920x1080P

**Player Data:**
Chracter ID: 1223

**Server:**
Legacy india Roleplay

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has now been resolved
