### ISSUE TITLE
plz fix this bug

### ISSUE THREAD

**Issue by drchamp01** [InZidiuZ/op-framework-issue-tracker#1304]
![Screenshot (157)](https://user-images.githubusercontent.com/58654957/90333648-3ea92a00-dfe5-11ea-8719-6804c0fde383.png)
Sir i respawn in pillbox and again n again i drop somewhere underground metro site and i lost my phone radio and all plz fix asap!!! hope you fix soon and asap!!

**Comment by Nuziatella** [comment]
This issues is a you issue. Clear your FiveM Cache and disable visual mods.

**Comment by InZidiuZ** [comment]
Read the README
