### ISSUE TITLE
[vehicles/keys] Dupe key parameter for /givekey

### ISSUE THREAD

**Issue by ZeAviator** [InZidiuZ/op-framework-issue-tracker#1305]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Basically when you give keys to someone you lose keys. if it would be possible to implement a system wherein if you give keys to someone you don't lose them, and that both the players keep keys.

**Reason:**
Why would your suggestion be a good change to the framework?
It would make it more convenient for players driving a similar vehicle throughout the day, so when the passenger feels like driving we don't have to keep exchanging keys.

**Comment by twooot** [comment]
But you're giving them the keys? Where did the second pair of keys come from all the sudden?
