### ISSUE TITLE
[game/commands] Allow binding of commands

### ISSUE THREAD

**Issue by D1st0rt1On** [InZidiuZ/op-framework-issue-tracker#1306]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES
**Summary:**
It's simple really... We would be able to bind certain commands to a key, for example : /bind "key" "/engine"

**Reason:**
I think it'll just be a good quality of life update that will make it easier to roleplay more efficiently, and make it more easier and 'realistic' (cause less time will be wasted typing the commands)

**Comment by T4NZIM** [comment]
-1

**Comment by RyanShlap** [comment]
Just type faster?

**Comment by InZidiuZ** [comment]
This has now been added.

The commands to use this is as following:
- /command_bind [bind name] [command] [control]
- /command_bind_remove [bind name]
- /commands_binds

In-game there are more detailed descriptions of the different parameters.
