### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by meetyourdeath96** [InZidiuZ/op-framework-issue-tracker#1307]
![FiveM -  20  Legacy Roleplay India #1 _ Wiped Recently _ Custom Framework _ Active Staff_Development _ Join us @ discord gg_ehNU9xP 17-Aug-20 3_12_58 PM](https://user-images.githubusercontent.com/69793834/90383690-1c271780-e09e-11ea-943d-3e6a08279404.png)
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
MeetYourDeath#1660
**Summary:**
Write a short summary of what you are experiencing.
actualy after the new updates there are some bugs which we are facing like this one , i was doing mechanic job , suddenly my tow truck go in the air and started shaking , i leave the truck then my truck blased and their was a garbage bag in my hands , but i am mechanic how could this be posible , ithats why i report this bug here , i want that this server works smoothly as i am attached to this server from a long time , plz check this report
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
legacy India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Fill out the template properly
