### ISSUE TITLE
[game/hospitalization] Don't lose valuable items when 'mugged'

### ISSUE THREAD

**Issue by sableodoble** [InZidiuZ/op-framework-issue-tracker#1309]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I don’t think when you die you should lose phones guns or valuable items because it really annoying 
**Reason:**
Why would your suggestion be a good change to the framework?
People can keep more money and use that money for better rp because I always lose my phone when I die the I can’t contact my friends

**Comment by twooot** [comment]
Thats the whole point of airlifting. You may loose your valuables if you get unlucky
