### ISSUE TITLE
[jobs/police] Dispatch call when someone is going to prision

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1310]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yeah

**Summary:**
A "dispatch call" that pop-up with the name and the months of the people who are going to prison. The text could be something like this, "JAIL or DOC: XX was sent to prison for XX months". Of course this message would be only for Police officers.

**Reason:**
It would be good for self-control between police officers (commands ranks inclusive) and avoid processing errors. Also if there's a DOC on any server, they could know when they send inmates to prison.

**Comment by S3WAGST4R** [comment]
+1

**Comment by HydraLazy** [comment]
+1

**Comment by Nuziatella** [comment]
Incarceration are public knowledge. The method should include a system where everyone should be able to see who was incarcerated and for how long.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
