### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by NitinArora20** [InZidiuZ/op-framework-issue-tracker#1311]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
# https://steamcommunity.com/profiles/76561199046269806/
**Summary:**
Write a short summary of what you are experiencing.
# This thing came up and in a minute my fivem crashed. It's look like script error to me.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
 ![Screenshot (1)](https://user-images.githubusercontent.com/68475264/90455306-c36a7580-e0c3-11ea-89f6-04a4052ce87d.png)
**Game Resolution:**
What is your game's resolution?
# 1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
# legacy India  Server 1
# @InZidiuZ 
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file
