### ISSUE TITLE
[?] Trunks for more vehicles

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1319]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
Trunk for Neon And many super cars
**Reason:**
Why would your suggestion be a good change to the framework?
There is some really nice cars out there that are Supers and sports cars and maybe some other kinds, but the biggest factor when buying one of these cars is “ if it has a trunk” many good cars don’t have these. Out of all the supers about 4-5 have functional trunks and the Neon sport/electric car is one of the cars that does not have a trunk and for the large price tag it makes people not want to buy them just for that reason 😕

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
