### ISSUE TITLE
[game/items] Compass/Watch you can buy at Megamall/Toolshop

### ISSUE THREAD

**Issue by xRunnin** [InZidiuZ/op-framework-issue-tracker#1323]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

Adding a new item in this case a Watch/Compass that shows directions and time (Example: North West South East) when you are on foot.
The feature of this item is when you use it or have it in your inventory a compass pops up on your display.
This can be bought at Megamall/Toolshops  and at PD Shop for cops.
Screenshot of view in a vehicle:
![image](https://user-images.githubusercontent.com/67928475/90966772-a14a6c00-e4a4-11ea-8353-819ec32388a3.png)
This is the view of the compass and the map and everything else when you are in a vehicle.
What I'm suggesting or my idea for this item is that only the Compass pops up when the item is used or available in your inventory can work either way.
Screenshot of compass: 
![image](https://user-images.githubusercontent.com/67928475/90966797-fdad8b80-e4a4-11ea-9add-3ae8d8505be3.png)

**Reason:**
Why would your suggestion be a good change to the framework?
This will be important in a RP combat situation for making callouts for either Cops and Crims.
Examples: Cop Officer making a call out on the radio using compass directions: One shooter on the southwest pink and blue building. Cop Officer making a on foot pursuit: Suspect running Southeast.

**Comment by InZidiuZ** [comment]
This has now been added.
