### ISSUE TITLE
[game/speed_cameras] Speed cameras at random points

### ISSUE THREAD

**Issue by RyanShlap** [InZidiuZ/op-framework-issue-tracker#1325]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes I have. 

**Summary:**
Write a summary of what your suggestion is about. - my suggestion is pretty self explanatory to be honest. The rate people drive through the city kind of abuses the seat belt part of the vehicles because you do see people crash at approximately 100-150 mph and it doesn't effect them at all but takes a small bit of their health. Realistically speaking you would be stuck to the windshield regardless. They take no care for civilian life or their own when it comes to the situations involving the driving and Speeding through the city. So my suggestion is that when they go through a speed camera it fines them a set amount based on their speed they were doing. Emergency vehicles could be exempt as it shouldn't be to complex to do so. This will at least kind of make them reduce their speed drastically and you could maybe give them a 5-10 mph grace over the speed limit so its not to harsh. You could put some around the main populated areas of the city but scatter them and maybe have one or two on the free way leaving the city. 

**Reason:**
Why would your suggestion be a good change to the framework? - the reason for this suggestion is so that there will be less people heading to pillbox after getting hit by Speeding cars. It also makes people value civilian lives and actually take due care and attention when it comes to driving in the city.

**Comment by S3WAGST4R** [comment]
+1

**Comment by novapurple** [comment]
I could see these being used in highly populated areas, legion square , around PD and pillbox?

**Comment by RyanShlap** [comment]
It would be a good addition taking into consideration the amount of Speeding and recklessness and non valuing of lives as well.

**Comment by ScotsMan-07** [comment]
seems kinda lazy to me why not have police sat there if its such a big issue?. seems like it could take away rp from cops and crims but i understand why you would maybe want it to be in popular area's

**Comment by RyanShlap** [comment]
I disagree @ScotsMan-07... Police have a sheer amount of rp going on we actually really don't get enough time to speed trap unless it's early UK time. We have drug calls, house robberies at night time, banks and if there is enough of us on and not all of us responding to a bank 9 times out of 10 there is a chase or another situation that involves a few more officers, also with the current activity within the server and how people treat just a basic traffic stop it requires sometimes 2-3 officers on that as well. If your not a cop I understand your point but be a cop and trust me you'll know it can get hella busy in rp.

**Comment by novapurple** [comment]
Lots of people don’t give a shit and will go 200 thru the city. If they start gettin fined this wouldn’t be as big of an issue.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
