### ISSUE TITLE
Grandmas Isn’t working 

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1326]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
Nova
**Summary:**
Write a short summary of what you are experiencing.
Going to grandmas revives you, but when you leave the city and come back again, you wake up in pillbox and lose your items even though you didn't leave the city downed
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
1) Be downed
2) Get picked up by Grandma
3) leave the city
4) come back to the city
**Expected Results:**
What are the expected results?
To get back up from being down at grandma, keep your items when you leave the city
**Actual Results:**
What are the actual results?
get back from grandmas and it, leave the city and come back and keep your items
## Additional Information
I think going to grandmas and being picked up isn't registering you as being alive when leaving the city
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://cdn.discordapp.com/attachments/714462023735574549/747116590348238959/unknown.png
**Server:**
What server/community did this issue occur in?
NA/EU
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This should be resolved in version 2972
