### ISSUE TITLE
Nagasaki Chimera Modification

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1327]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
Nuziatella

**Summary:**
Write a short summary of what you are experiencing.
The Nagasaki Chimera vehicle can not be modified in any of the shops. When entering the garage doors the "Press Enter" prompt does not appear regardless of angle of entering or person driving the vehicle.

**Steps to Reproduce:**
Take Nagasaki Chimera and go to any of the 6 shops.

**Expected Results:**
When entering the shops the prompt to appear so the vehicle can be modified.

**Actual Results:**
The prompt does not appear for this vehicle specifically so it does not have the ability to be modified.

## Additional Information

**Screenshots:**
[Screenshot](https://imgur.com/2v0jVje)

**Game Resolution:**
2560x1440

**Player Data:**
![image](https://user-images.githubusercontent.com/67765305/90985570-efb24600-e54a-11ea-98fc-82a85265e3bf.png)

**Server:**
LegacyRP EU/NA

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
This should be resolved in version 2973

**Comment by z-Lunar** [comment]
Street Blazer Also has this problem.

**Comment by InZidiuZ** [comment]
All 'quad bikes' are allowed in LSC as of 2973, which includes the Street Blazer, @z-Lunar
