### ISSUE TITLE
Verification system in BL servers 

### ISSUE THREAD

**Issue by Captain1212** [InZidiuZ/op-framework-issue-tracker#1328]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yeah
Summary:
Write a summary of what your suggestion is about.
Hi it is really one of the main issue that you should look into ..Random players are entering into the server and they are doing RDM , VDM on regular basis and we have to report them Everytime to get them banned ..Today some Arabs entered the Indian server and they started Killing everyone ,Started abusing female players in thier own language and I met some players which gave me the IRL verbal threat. you should be having a verification system in which each player will be verified by the staff and then they should be allowed to play in the servers ..There are millions of players around the globe and in Fivem  and if servers will be open for all then anyone can enter the server and will make it toxic RP and it rarely happens in WL servers as they have to go through the interview and forms .. For BL servers you must have a basic verification system on your discord server or anything. In BL servers the admins can't be present 24/7 to ban them and there are 4 Bl servers which become difficult to manager from the Admin POV.  it will also reduce the work of staff if we will have a verification system or anything like that on discord or any other way !!  ** you can also imply a system in which a player needs to have  50-100 playable hours in server 1 and 2 **
Reason:**
Why would your suggestion be a good change to the framework?
It will be a good change to the framework because it will prevent the random players and toxic people to enter the server and it will also prevent the toxic RP which is common nowadays and it will prevent the players with the intention to Destroy the server .
Screenshots that how common is this issue - 
![Screenshot_20200824_111045](https://user-images.githubusercontent.com/70125849/91007912-c3ee9900-e5fa-11ea-87c0-8d1d2deef6dc.jpg)

![Screenshot_20200824_111037](https://user-images.githubusercontent.com/70125849/91007907-c0f3a880-e5fa-11ea-971e-f811c6adfcc2.jpg)
![20200824075650_1](https://user-images.githubusercontent.com/70125849/91007869-aa4d5180-e5fa-11ea-8e74-c4d42997b8a8.jpg)
![20200824085517_1](https://user-images.githubusercontent.com/70125849/91007876-acafab80-e5fa-11ea-9c43-9914491897a4.jpg)
![Screenshot_20200824_111111](https://user-images.githubusercontent.com/70125849/91007891-b89b6d80-e5fa-11ea-91e5-6fb140ed1fb4.jpg)
![Screenshot_20200824_111103](https://user-images.githubusercontent.com/70125849/91007900-bb965e00-e5fa-11ea-9653-6e9e5a31c25b.jpg)
![Screenshot_20200824_111057](https://user-images.githubusercontent.com/70125849/91007903-bd602180-e5fa-11ea-9e7b-8939586529a8.jpg)
![Screenshot_20200824_111052](https://user-images.githubusercontent.com/70125849/91007906-bf29e500-e5fa-11ea-806c-58dc197af7e9.jpg)

**Comment by InZidiuZ** [comment]
Isn't that what differentiates a WL and BL server? This won't be done now. In the future there would be a possibility of adding some setting to allow servers to enable a sort of 'soft whitelist' sort of thing, either through discord or through an in-game review process by staff.
