### ISSUE TITLE
Selling drugs not in locations

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-issue-tracker#133]
**Reporter:**
Who is reporting this? Please include discord name.
SATIN187(Jimmy McGuinness

**Summary:**
Write a short summary of what you're experiencing.
Was riding in my car with a buddy and we were selling drugs, then went back to my  apratment in paleto and he disconnected and it gave me the command to sell weed. and as long as you stand still and dont move the prompt will keep popping up to sell weed even if that zombie is long gone

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
had buddy log back in sold some weed and went back to my apartment and stood in one place as he logged out

**Expected Results:**
What are the expected results?
 for his zombie to just walk away and not be able to sell weed

**Actual Results:**
What are the actual results?
im able to sell weed outside designated area

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Are you able to recreate this, and take some screenshots of your F8 console?

And also, if I get this right, you're able to sell to your friend after he disconnects? Or are you able to sell outside of the "selling zone?

**Comment by SATIN187** [comment]
yes to both. so my friend was in my car at paleto and we got out of the car and then we said goodbye and he disconnected and i was able to sell his NPC character weed in paleto and once i have a friend log on i will try and recreate this and get the screen shots

**Comment by InZidiuZ** [comment]
Ah okay, probably not going to fix the "selling to disconnected players", but selling in different locations sounds strange.

**Comment by InZidiuZ** [comment]
I double-checked the code and have no idea why it would let you sell outside of the designated areas, so going to close this, as it's not that of a major issues anyways.
