### ISSUE TITLE
[animations/emotes] 10 second animation while searching someone 

### ISSUE THREAD

**Issue by devesh180** [InZidiuZ/op-framework-issue-tracker#1330]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES
**Summary:**
Write a summary of what your suggestion is about.
There should be 10 seconds animation while searching someone because you can't search someone within seconds and right now many people abusing direct search/steal for example while gang war if gang is having only 2 cars remaining at that time they just cuff other and steal them on the spot within seconds and left them and carry only 2 members with them if there should be 10 seconds cooldown while searching then atleast they will try to search someone in cover not in mid of road.
**Reason:**
People are abusing this command like while war if someone don't have armour and died opponent is on the road then they just cuff him on the spot and get armour and stuff from him within seconds they are not making any efforts. If someone got cuffed in bunch of peoples then nobody can say who search him.
Why would your suggestion be a good change to the framework?
It will promote quality role play like if someone search you in the bunch of people then with the help of animation you get to know who is searching you like in bank robbery if two robbers stand nearby hostage and search him then hostage can tell police that guy searched me.

**Comment by DaxterPancake** [comment]
I agree with this, as it stands right now the only notification you get is a notification that says 'You are being searched.'

I believe adding a 10sec progress bar with an animation would not only make it more realistic but also slow down that sort of RP. You'd know who/when a cop/criminal is searching you and act accordingly. I can see this being more useful for when cops search criminals but I can also see it being useful for when there is a rule break, you'd be able to see who took your things.

**Comment by S3WAGST4R** [comment]
+1

**Comment by twooot** [comment]
You are now forced into a searching animation for 4 to 6 seconds
