### ISSUE TITLE
Automation in buying of vehicles in cities where PDM staff is not available

### ISSUE THREAD

**Issue by mayhemongithub** [InZidiuZ/op-framework-issue-tracker#1331]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is about getting an automated menu which will open whenever a citizen wants to buy a car and PDM staff is not available there. I've been in the top cities but still I cannot find a single PDM staff to buy vehicles, and also posting on twitter about this minor problem of mine is not what I want to do. When PDM staff is available, he can turn off the menu which will come for other players and whenever he leaves he can turn that on again.

**Reason:**
Why would your suggestion be a good change to the framework?
It will be a good change as in real life, if there is no staff in any shop, we can get a confirmation from other shops nearby for when he will arrive or not, but here in the cities, we don't know for how long we will have to wait for the PDM staff to arrive. So for making this a good roleplay, we can order something on the menu available to us, where we can see the prices as well as the commission taken by the PDM staffs so that we can calculate before hand for how much we need to take cash with us. Otherwise, the PDM should have a message system that citizens can use for notifying the PDM staff that they are here when no one is available.

**Comment by T4NZIM** [comment]
-1 If anyone can buy vehicles without PDM staff, then there wont be any PDM RP and then why even this job is whitelisted?

**Comment by mayhemongithub** [comment]
Okay, I get your point, then what should be done is that there should be a catalog at least, so that we can find the prices of cars available in PDM, a local can stand there and we can go check there. And waiting there for so long and then you came to know that PDM staff is in city 1 and there are many citizens waiting to go to city 1, then how would someone buy a car? If that's the case, then there should be at least 1 PDM staff available in each city, not just in 1 city.

**Comment by Nuziatella** [comment]
There is a catalog with pricing available on the discord.

**Comment by Masik52** [comment]
They are likely from a subdivision server they may not have the pdm catalog in their discord.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
