### ISSUE TITLE
house bug

### ISSUE THREAD

**Issue by jaideep163** [InZidiuZ/op-framework-issue-tracker#1332]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
Jaideep163

**Summary:**
every time when i entered the server and try to enter in my house i am dead

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
What house? What server? How is the death happening? Are you free falling through the void? Screenshots? Server? 
The reason for the template as it provides vital information to the developers to test and correct issues.
Developers can't possibly diagnose an issue with such little information.

**Comment by DaxterPancake** [comment]
Please remake and fill in every section of the template provided.
