### ISSUE TITLE
weed plants issue

### ISSUE THREAD

**Issue by jaideep163** [InZidiuZ/op-framework-issue-tracker#1333]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
Jaideep163

**Summary:**
my weed plants is not growing all of them are 200% above

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file
