### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bhavesh02** [InZidiuZ/op-framework-issue-tracker#1334]
Personal garage at eclipse boulevard 

We genuinely recommend a personal garage at eclipse boulevard because the block has every facility except the garage. It is closed to vinewood cocaine selling area so no garage at that block doesn’t make any sense. I would really appreciate if you look into my suggestions and make the possible change as soon as possible

**Comment by InZidiuZ** [comment]
Read the README file
