### ISSUE TITLE
[game/inventory] Right-Click-To-Use

### ISSUE THREAD

**Issue by ZeAviator** [InZidiuZ/op-framework-issue-tracker#1335]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
The ability to use an item present in your inventory by simply right-clicking on the item, rather than dragging it into the use button
**Reason:**
Why would your suggestion be a good change to the framework?
Would reduce the time it takes to use items and also improve the quality of Gang-Fights / PD Code Reds since people will be able to quickly use items, which are not in their Hotbar.

**Comment by S3WAGST4R** [comment]
-1

**Comment by InZidiuZ** [comment]
Maybe a double right-click to prevent accidental use of items?

**Comment by ZeAviator** [comment]
> Maybe a double right-click to prevent accidental use of items?

Double Left-Click and or Right-Click Sounds Good 👍

**Comment by InZidiuZ** [comment]
Probably not left-click as it's used for dragging items

**Comment by KidDano** [comment]
Could also press E on the item you are hovering over with your mouse cursor

**Comment by twooot** [comment]
Middle click does this now
