### ISSUE TITLE
Suggestion Job/EMS

### ISSUE THREAD

**Issue by Splash004** [InZidiuZ/op-framework-issue-tracker#1336]
It would be better if EMS gets a Chevrolate Tahoe. Because its been a Long time no vehicles were added to ems. After every server update new vehicles comes for Police only. But for EMS same car but livery changes. Thats why People losses interests in EMS job most of the time. If EMS gets a Tahoe with some liveries it would be really better for us. Thank you

**Comment by MuhtasimSafa** [comment]
+1

**Comment by InZidiuZ** [comment]
Read the README file
