### ISSUE TITLE
My truck just blasted at fuel station.

### ISSUE THREAD

**Issue by MaximaVoid** [InZidiuZ/op-framework-issue-tracker#1337]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
MaximaVoid

**Summary:**
So I was doing transport job and stopped by a fuel station to refuel my truck and buy some food from the grocery store, but when I sat in my truck it just and moved it forward it blasted. WHY? and after the shipment is destroyed there is no way of cancelling the job except for leaving server and joining again.

**Steps to Reproduce:**
A transport truck with trailer and the fuel station with grocery store on senora fw ( when returning from paleto to city).
just park the truck in and take it out again after some time.

**Expected Results:**
What are the expected results?
The truck should have went out smoothly, there was quite enough space.

**Actual Results:**
What are the actual results?
The truck and trailer would blast with the fuel pumps.

## Additional Information
Nothing

**Screenshots:**
https://steamcommunity.com/sharedfiles/filedetails/?id=2211948814

**Game Resolution:**
What is your game's resolution?
680p (supposedly for better FPS)

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Not quite sure what to do with this... You can also cancel the job with /canceljob

**Comment by MaximaVoid** [comment]
K thanks
