### ISSUE TITLE
house glitch

### ISSUE THREAD

**Issue by innovativegroups** [InZidiuZ/op-framework-issue-tracker#1338]
I have bought a house in which if someone is in ground floor or else in neighbour house he can be visibel in my room and same for him i am visibel in his room even if u uses zeus on me i can got tez. and if i have drop something in my house it is shown in other room and he can pickup that things which i drop on floor. One more problem is if i enter house in some case after entering house i am dead . please help with this glitch ASAP

**Comment by InZidiuZ** [comment]
Read the README file

**Comment by innovativegroups** [comment]
> Read the README file
Where can i find this README files please tell me i will check it out then let u kwn

**Comment by InZidiuZ** [comment]
In the root folder of this repository, @innovativegroups
