### ISSUE TITLE
[game/map] Vagos Savehouse 

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1339]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
There is one place near Garbage Headquarters, where there is interior of Vagos Savehouse. I have added link in bottom. please add this if possible.

**Link:** https://www.gta5-mods.com/maps/vagos-savehouse-1-0-0-mlo
 
**Reason:**
This should be added because **Vagos** don't have any repair shop or club in city. but there are clubs for **LMC** and **SOL**. so it will be a good addition in **Legacy** server if we add this interior and make this one as a repair shop from inside.

**Comment by InZidiuZ** [comment]
Read the README file, this is the wrong issue tracker for assets
