### ISSUE TITLE
Glitchy House (Stelee Way 6)

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/op-framework-issue-tracker#1340]
That house is from inside like Michael's house. The room where Michael's son stays, there numerous numbers of sometimes lamps or sometimes bed something like that appears. Our items in other rooms vanishes.
Note: Not prefurnished. Items were removed by glitch not mistakenly by us.

**Comment by DaxterPancake** [comment]
Remake following the template provided [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).
