### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by bhaveshpawar** [InZidiuZ/op-framework-issue-tracker#1341]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561199078109481/

**Summary:**
Write a short summary of what you are experiencing.
I bought a new bike(Dinka Doube T), and on the same day i had an accident with garbage truck, then my bike was not moving at all. So, i called a mechanic and he repaired my bike, but still my bike was not moving(it was like freezed at one place), the mechanic took it to a garage and told me to store and remove it,but still same issue was there.Even retireving the vehicle didnt worked.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
You will need my bike to reproduce the issue

**Expected Results:**
What are the expected results?
The bike should move when i press the movement keys.

**Actual Results:**
What are the actual results?
Bike not moving and stuck at one location.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920*1080 

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/36239514/91632735-727e4980-ea00-11ea-813b-c40ec90fd879.png)

**Server:**
What server/community did this issue occur in?
Legacy India Server #2

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Get a jerrycan and refuel your bike & it'll start working again
