### ISSUE TITLE
Bug report - Lost my shit for no reason at all 

### ISSUE THREAD

**Issue by Breauxxx** [InZidiuZ/op-framework-issue-tracker#1342]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes, I have read through it

**Player Identification:**
What is your steam profile?

https://steamcommunity.com/profiles/76561198255979478/
**Summary:**
Write a short summary of what you are experiencing.

So I was on earlier at about 2pm EST and went afk in my apartment for awhile and then restart happened and the max players go raised I guess which caused some issues on the server as I've seen on discord. I got on and saw that shit was taken from my inventory and then I fell through my apartment, through the ground into the sewer or tunnels. I then restarted to fix me phasing through shit and then I logged on and lost even more of my shit. I am very frustrated with this issue because the server was working BEAUTIFULLY before the player cap go increased.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Not sure probably restarting the server and increasing the player cap by double.

**Expected Results:**
What are the expected results?

Losing your shit

**Actual Results:**
What are the actual results?

Losing your shit

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![image0 (12)](https://user-images.githubusercontent.com/70455728/91648256-2d273f80-ea33-11ea-938e-8a67eff3f076.jpg)

**Game Resolution:**
What is your game's resolution?
4k
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![0_screenshots_20200829201354_1](https://user-images.githubusercontent.com/70455728/91648347-614f3000-ea34-11ea-9352-f064e6d49c81.jpg)

**Server:**
What server/community did this issue occur in?
Legacy RP
**Notes:**
For anything else noteworthy.

I'm very poor on the server and would really appreciate a compensation for the shit I lost, feels useless to keep grinding for money to get it back when scuffs like this could happen and no ones gonna help me get my stuff back. I won't be playing on the server until I get a response to this because I don't want to keep playing and losing more shit, I just want to roleplay and be able to play the server. My discord is Breaux#0008

**Comment by InZidiuZ** [comment]
Probably a local issue. Try clearing your cache and/or verifying your game files if it continues to happen. Closing due to no real repro here, though.
