### ISSUE TITLE
Bug report (Glitchy House Steele Way 6)

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/op-framework-issue-tracker#1343]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198987373731/

**Summary:**
Write a short summary of what you are experiencing.
This house has the interior of Michaels House. Somethings appear like beds on beds, or sometimes there are light bulbs. It was like someone spammed beds. Something which we would never do. These appear in Michaels sons room and whenever these appear some of our items get deleted.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay Bangladesh.

**Notes:**
For anything else noteworthy.
Three players live in this house, excluding the company's access.
In the Map below the house marked with a black box is the glitchy one.
![SteeleWay-MapLocation-GTAV](https://user-images.githubusercontent.com/67185453/91651127-8e3e2a00-eaaa-11ea-8cf4-5e97cddf9766.png)

**Comment by InZidiuZ** [comment]
Not able to reproduce
