### ISSUE TITLE
 [jobs/police] Ability to escort and [suspect in] players when soft cuffed. As well as the ability to [suspect in] more than one suspect.

### ISSUE THREAD

**Issue by ZeAviator** [InZidiuZ/op-framework-issue-tracker#1344]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
PD Should be able to escort a suspect when he is in soft cuffs as well, along with the ability to put him in the vehicle soft cuffed, as well as currently you can only hard cuff, and then put one person in a car, allowing us the fill-up (putting more than one suspect in ] the car would make it more realistic and convenient for the PD.
**Reason:**
Why would your suggestion be a good change to the framework?
Allowing us the fill-up the car would make it more realistic and convenient for the PD. As well as we are forced to hard cuff to put in the vehicle so the RP end's there, this way crims will have more chances to escape.

**Comment by joevapes3** [comment]
I think this should be expanded to allowing anyone, cop or civilian to escort someone, and also have the ability to seat nearest into vehicles. This would help the PD, along with expand roleplay, and make the process much easier. Same forced walk mechanic should be applied when escorting them as well. This adds balance to the benefits of the ability.

**Comment by ZeAviator** [comment]
@InZidiuZ Also allowing us to suspect in while someone is already sitting in the car Currently if someone is sitting in the car, for eg in the driver's seat we cannot suspect in without having had that person step out first. Also, I agree to what @joevapes3 said, escort and put in and get out of vehicle should be available for civilians as well,

**Comment by T4NZIM** [comment]
+1 @joevapes3 @ZeAviator

**Comment by S3WAGST4R** [comment]
+1

**Comment by KidDano** [comment]
Yes, this would be great

**Comment by twooot** [comment]
You can suspect in more than 1 person, you can just /hardcuff while they are softcuffed to suspect them in
