### ISSUE TITLE
[illegal/*] Addition of a 'peaceful' setting/mode

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1345]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yeah

**Summary:**
My suggestion is make a command for STAFF members for toggle all robberies (bank, bank trunks for the moment). This toggle has to be logged into the admin panel.

**Reason:**
The reason behind this is sometimes police could do a training day on the server. We can do this right know, but make it "off-duty", but the "officers blips locations" doesn't show and these are esencial for strategy and coordination proposes and we don't need to worry about any robberies and focus on the training.

**Comment by superiorchicken007** [comment]
> **Assurance:** Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yeah
> 
> **Summary:** My suggestion is make a command for STAFF members for toggle all robberies (bank, bank trunks for the moment). This toggle has to be logged into the admin panel.
> 
> **Reason:** The reason behind this is sometimes police could do a training day on the server. We can do this right know, but make it "off-duty", but the "officers blips locations" doesn't show and these are esencial for strategy and coordination proposes and we don't need to worry about any robberies and focus on the training.

Since this has been created there is now a /training command which allows you to be "on-duty" and see other trackers but do not count towards numbers for robberies.

**Comment by twooot** [comment]
Closed in favor of the /training command
