### ISSUE TITLE
Pillbox becomes a gate to hell (sometimes)

### ISSUE THREAD

**Issue by Psychic05** [InZidiuZ/op-framework-issue-tracker#1346]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
= Yes
 
**Player Identification:**
What is your steam profile?
= https://steamcommunity.com/profiles/76561198375326433/

**Summary:**
= I have joined the Legacy Roleplay community not longer than a week ago.
It was all going perfectly in the first couple of days, but since yesterday, sometimes when i enter pillbox, i fall straight into it, like right below it, into the subway system beneath it. Yesterday, it happened in just server 3. So, i left server 3 and joined server 4.
It was all going good all day today when the bug happened in server 4 as well. Now i am afraid it will happen in server 1 and 2 as well if i join them.

It happens randomly so i wasn't able to record.

A sign of when this would happen is, my clothes are automatically changed from last time, when i spawn the first time(from FiveM)

Sometimes there is even a person lying there before me trying to contact there friends.

I have lost 3000 in game currency due to this bug because of this cycle:
1) I enter pillbox
2) I fall into the subway
3) I wait 5 minutes
4) I re-spawn
5) I get mugged
6) I get healed
7) As soon as i get of the bed and place my feet on pillbox ground i get sucked in

**Steps to Reproduce:**
= You spawn in from FiveM and enter pillbox till the bug happens.

**Expected Results:**
What are the expected results?
= Enter pillbox and check-in and get healed and move on with life.

**Actual Results:**
What are the actual results?
= 1) You fall in a subway right under a transparent hospital.
   2) You become stressed and everything starts to shake(in real life)
   3) Loose 3000 in-game currency, to buy the items that were taken from me when i was mugged, again and again.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
= Wasn't able to record because the bug is random. 

**Game Resolution:**
= 1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
= https://i.imgur.com/fZRWTUi.png

**Server:**
What server/community did this issue occur in?
= 3 and 4

**Notes:**
For anything else noteworthy.

**Comment by T4NZIM** [comment]
It's your PC problem, ask this in the help section :)

**Comment by InZidiuZ** [comment]
This is likely an issue out of our control. And if it would be an issue with something, it'd probably be with the map/interior itself and not the framework. My best suggestions to prevent this would be: clear your cache when it happens, always restart your game after logging out and make sure your hardware is up to date.

**Comment by Psychic05** [comment]
Ok,

Thanks for replying.
