### ISSUE TITLE
[jobs/police] 10-14 | Officer Down | Command for Police. == Panic Button Command | Police

### ISSUE THREAD

**Issue by ZeAviator** [InZidiuZ/op-framework-issue-tracker#1347]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
1. Add a command wherein a downed officer can do /10-14 to send a dispatch alert to all on-duty officer, consisting of the whereabouts of the downed officer.
2. Same concept as the above on sending out a dispatch alert controlled by the officer when kidnapped.
**Reason:**
Why would your suggestion be a good change to the framework?
It would make 10-14's and Kidnapping's more realistic as currently, we have to say 10-14 on the radio and many times that call is missed. Having an eye-catching alert would make it easier to identify officers in distress.

**Comment by its-Frost** [comment]
+1

**Comment by joevapes3** [comment]
A 10-99 panic button alert would be great, along with 10-14 alpha for emergency officer down distress command and a 10-14 bravo for non emergency officer down (car accident ect..). Adding those commands would be super beneficial to the PD roleplay. The idea that the alerts could be bound to a Keyboard bind would be amazing as well.

**Comment by T4NZIM** [comment]
+1

**Comment by S3WAGST4R** [comment]
+1

**Comment by novapurple** [comment]
Think this would need to be a 10-14 button Instead of a Panic button so people don’t hit it when they should have their hands up if they are being taken hostage.

**Comment by joevapes3** [comment]
> Think this would need to be a 10-14 button Instead of a Panic button so people don’t hit it when they should have their hands up if they are being taken hostage.

I think that if they hit the button with their hands up that'd be more of a fail RP issue. Easiest solution would be to make it so you can't hit the alert with you have /e handsup enabled. The panic alert could facilitate so much more RP interactions vs just a basic 10-14a or 10-14b alerts. If someone get's a gun on them before it can be activated, then they can't hit it at that point.  There is plenty of other times besides solely kidnappings where a panic button would be used for, and if they were to fail RP when using it for 1 scenario, it shouldn't negate it's other benefits, when that person could just be punished by staff if they abused it. Plenty of other servers have the same feature without any problems. Regardless, when kidnapping and robbing, people need to have a strong RP reason in the first place.

**Comment by twooot** [comment]
We have a panic button now
