### ISSUE TITLE
Police Boat Spawner

### ISSUE THREAD

**Issue by capsure** [InZidiuZ/op-framework-issue-tracker#135]
**Reporter:**
Who is reporting this? capsure#0737
**Summary:**
When testing out the boat spawner after picking boats, then backing up 1 instead of boats being in the option only helicopters are in the option. And when selecting the maverick it spawns it somewhere not sure where possibly at PD

**Steps to Reproduce:**
Goto boat spawner pick boats, back up 1, pick helicopters

**Expected Results:**
When backing up boats is still the option.

**Actual Results:**
When backing up helicopters is the option

## Additional Information

**Screenshots:**
Can supply but probably not needed

**Game Resolution:**
1080

**Player Data:**
Character ID:89 - Job Data: Law Enforcment, SASP, Trooper

**Notes:**

**Comment by capsure** [comment]
I can confirm they do in fact spawn at the PD helipad location. I'm guessing something in the script when hitting backspace on the boat list is using the same spawn menu as helipad and doesn't reinitialize properly and uses the helipad spawner instead...

**Comment by InZidiuZ** [comment]
Hey,

This issue will be resolved after next patch.

**InZidiuZ**
*OP-FW Developer*
