### ISSUE TITLE
[base/admin] /revive improvements

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1350]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

More staff /revive options 

/revive (picks up player from death)
/revive2 (picks player up and stops any bleeding and damages to them so they will not have to see Nancy)
/revive3 (same qualities as revive2 but also grants person with body armor)

**Reason:**
Why would your suggestion be a good change to the framework?
Currently when people are downed in any type of wrongful manner RDM, VDM, or scuff. They will lost any armor they had, and will occasionally bleeding and will need to be revived 2-4 more times till the bleeding naturally stops or go all the way to pillbox to have the bleeding fixed but they are still out of an Amour piece that they just forked 400$+ tax for. Would almost be like a compensation for the ones that were downed but shouldn’t of gone down.

**Comment by KidDano** [comment]
+1

**Comment by InZidiuZ** [comment]
As of version 3169, /revive will have a parameter to remove all injuries. A `/set_body_armor` command has also been added.
