### ISSUE TITLE
Change current functionality of Repair Kits/Advanced Repair Kits

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1351]
**Summary:**
Recently there have been some changes to the Repair Kits & Advance Repair Kits.  With the reduction in price of the kits and the increase of usefulness of the repair kits, it has made it so that far less people come to repair shops for repairs.  

Please do some of the following: 
Reduce the effectiveness of the Repair/Advance Repair Kit (make them fix only up to 30/60 respectively)
Increase the Price Somewhat
Require to be Purchased at a Mechanic Shop (possibly for Material Cost?)

**Reason:**
Why would your suggestion be a good change to the framework?
Currently if you car is badly damaged, it is much more economical to use a repair kit, because of the following: 
The repair kit not being consumed on use.
The repair parts costing more than the repair kit. 
It's easier to purchase an item then it is to Roleplay out the scenario.

This ends up reducing the need/use of the Mechanic Job as a whole, and the opportunity of roleplay that it brings. Additionally, it short changes the entire parts gathering portion of the econonmy (Chop/Diving/Garbage). 

While they may still want repairs to windows/doors, it leads the vast majority of repairs to be done without an RP interaction

**Comment by InZidiuZ** [comment]
I set it to 80% per #1349, though I've set it to 65% now.
