### ISSUE TITLE
[game/items] Painkillers item

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1352]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Pain killers- Oxy Alternative
**Reason:**
Why would your suggestion be a good change to the framework?
Similar to oxy it would stop your “injuries” but would stop it for a short period of time to give you time to go to the hospital. If not injuries will return and you will need to use another one or go the hospital. This can be a short amount of time 2-3 minutes so it’s useful but Also can be annoying if you don’t get it taken care of.
This items can be bought by EMS but given to patients creating medical RP (Prescriptions) where they will have to go to medical personal to get these items. And if this idea for the EMS didn’t work you could always throw these on the gas station for a bit of a price maybe 100$? So it pushes people to try to get the illegal form (Oxy)

**Comment by twooot** [comment]
I added painkillers
