### ISSUE TITLE
alcohol effects and breathalyzer

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1353]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Having too much liquor should effect health stats.

**Reason:**
This would bring realistic effects on consuming high levels of alcohol. Also cops can stop civilians for quick blood alcohol levels using https://www.gta5-mods.com/misc/australian-alcolizer-breathalyzer-v2

**Comment by InZidiuZ** [comment]
Be more specific & add more details when creating an issue.
