### ISSUE TITLE
[?] Purchasable fake IDs

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1356]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes:
**Summary:**
Write a summary of what your suggestion is about.
A location to buy Fake IDs at.
**Reason:**
Why would your suggestion be a good change to the framework?
Would be another thing people could be Able go interact with, with this you would go to said location and pay a large fee $1250-1500 for a fake citizen ID of similar names that are registered to local vehicles or more advanced names too keep the “immersion” up.
Would be another way to get ahold of these fake ID cards that you wouldn’t get from players.

**Comment by DaxterPancake** [comment]
I'd also like the ability for cops/FIB to create fake ID's to use while undercover.

**Comment by novapurple** [comment]
This would also be great! So they can get more involved with their story of doing FIB stuff!

**Comment by Imaghost1337** [comment]
Or maybe somehow utilise the 'dropping' system from houses and diving with things like plastic and have a process of producing fake IDs yourself. I think it also would be a nice addition for some groups (or an individual) to claim a place and supply groups or individuals with fake IDs

**Comment by RyanShlap** [comment]
I think if we were to do ID systems like that we need to change the current one. Because I feel that this would be abused for pdm vehicles on finance and also with pd unless brought in to custody then you would be finger printed for your real identification. I like the idea but I feel there would be more abusers than users in this instance.

**Comment by novapurple** [comment]
It would be no different then using someone else’s ID rn. Only difference is there is a different way of getting them and PD would get RP out of getting federally produced IDs for their FIB work

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
