### ISSUE TITLE
[properties/properties] Bug report weed plant

### ISSUE THREAD

**Issue by toxicgamer6x6** [InZidiuZ/op-framework-issue-tracker#1357]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198857923541/
**Summary:**
Write a short summary of what you are experiencing.

i am playing for a long time in this server i really like to play but from this season weed tress not growing fully like i put 10 trees in house on them i can harvest only 3 and another 7 trees goes more than 100 percent which we cannot hervest 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://cdn.discordapp.com/attachments/604726870830743563/751338237565599744/20200903195816_1.jpg

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
character id 503  name Nashehalie sing ph number  241-0891   
**Server:**
What server/community did this issue occur in?
in india legacy normal

**Comment by darklighter-creator** [comment]
there is a bug giving some massive problem when I try to refuel my vehicle by jerrycan and my character stuck's on that position no matter what I do. after restarting my fiveM the vehicle stays busy so I can't ride on that. hope you will fix the bug.
my discord id- DARK•LIGHTER#6461
thank you.

**Comment by InZidiuZ** [comment]
Do you have a live example of this at this moment? And if so, what is the address to the house where this live example can be found at?

**Comment by toxicgamer6x6** [comment]
yes i have in  my house 
near brouge avenue at house number 6

**Comment by InZidiuZ** [comment]
This issue has be resolved with version 3074. It should now also let you correctly harvest weed that has overgrown.
