### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by ktushar1716** [InZidiuZ/op-framework-issue-tracker#1358]
i cant hear anything ingame, till yesterday i was only able to hear other players voice
but since today i cant even hear a single thing 
i have tried turning sound on and off in settings 
if i reconnect the server for a while everything will be fine but after sometime again i wont hear any sound
i have reinstalled fivem but still iam facing the same issue
1 thing to add today when i went to grapeseeds grocery store to fill my cars fuel there was no fuel unit to fill my car and thats where my sound went off.
please if its a bug fix it soon as without sound i am unable to play

**Comment by DaxterPancake** [comment]
Follow the template and remake, please.
