### ISSUE TITLE
jerrycan bug

### ISSUE THREAD

**Issue by darklighter-creator** [InZidiuZ/op-framework-issue-tracker#1359]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561199055395165/
**Summary:**
Write a short summary of what you are experiencing.
-when i try to refuel my vehicle a bug appears and i can't move no matter what I do
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
fix the script written against this .
**Expected Results:**
What are the expected results?
-not stucking my character and refuel the vehicle bu jerrycan
**Actual Results:**
What are the actual results?
refuel a vehicle by jerrycan
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
legacy role play Bangladesh #1
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file
