### ISSUE TITLE
Repair issues with the contender

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#136]
**Reporter:**
Who is reporting this? Masik52

**Summary:**
Tried to repair the body of the Contender twice and both times as the repair completed the truck disappeared.

**Steps to Reproduce:**
purchased the materials 1 alum 3 scrap walked to truck body and attempted repair.

**Expected Results:**
expected the body to be repaired

**Actual Results:**
the truck disappears and the body isn't  repaired.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![image](https://user-images.githubusercontent.com/52395441/60411836-a495e080-9b9c-11e9-9c0e-85518b58001c.png)

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 516 - Job Data: Government, Waste Collector, Employee

**Notes:**
can provide video clip if needed

**Comment by InZidiuZ** [comment]
Was this your own car?

**Comment by Masik52** [comment]
Yes it is my car that I own. The issue is still going on as well

**Comment by InZidiuZ** [comment]
Hey,

Investigated it, and found out that it wasn't disappearing, but spawning on the roof of the repair shop. This issue has now been resolved, and will be live after next patch.

**InZidiuZ**
*OP-FW Developer*
