### ISSUE TITLE
Add additional Yoga mats.

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1360]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is about adding Yoga mats inside the Police Department (Mission Row) somewhere inside the locked rooms (so that civilians can't access it).

**Reason:**
Why would your suggestion be a good change to the framework?
This will stop the cops from smoking joints to lower their stress.

**Comment by InZidiuZ** [comment]
This will not be done through the framework at this time. You could make a suggestion in the assets tracker asking the assets developers to add mats to the MLOs we use.
