### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1361]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
[https://steamcommunity.com/id/KaiEagle](url)

**Summary:**
Write a short summary of what you are experiencing.
This bug is related to the admin powers, the **/resetjob [CID]** use to work before but now it doesn't. It just says that the user needs to soft relog to make it work but after doing so the job still stays on him/her.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Recode it or revert it back to the older version :|

**Server:**
What server/community did this issue occur in?
Legacy India WL

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has been resolved with version 3043.
