### ISSUE TITLE
House addition

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1362]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
It's about adding one more house spot in **Caesars Place** the images of the house & the location are attached below.
![FiveM_GTAProcess_JfuXUGu6KT](https://user-images.githubusercontent.com/29286961/92334282-1bd0d980-f0aa-11ea-96fe-b24e718b301d.jpg)
![FiveM_GTAProcess_N8vfAgu0Xa](https://user-images.githubusercontent.com/29286961/92334284-1d020680-f0aa-11ea-9a6e-1112b6e73d27.jpg)
![FiveM_GTAProcess_QrB4KjEXWR](https://user-images.githubusercontent.com/29286961/92334285-1d9a9d00-f0aa-11ea-96be-5ba7a413fba3.jpg)
![FiveM_GTAProcess_32S4GMgTRX](https://user-images.githubusercontent.com/29286961/92334286-1d9a9d00-f0aa-11ea-8c49-05ec733225c8.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?
It will add one more spot for people to live in 👍

**Comment by InZidiuZ** [comment]
This has been added with 3045.

**Comment by z-Lunar** [comment]
I hate to reply to a closed post, but is it doable for this trailer to be added as well? 
![image](https://user-images.githubusercontent.com/46366594/92626291-547dd800-f28f-11ea-9f1c-66b909dbb125.png)
![image](https://user-images.githubusercontent.com/46366594/92626302-58115f00-f28f-11ea-982c-57d174c99adb.png)

**Comment by InZidiuZ** [comment]
This has now been added as its own block, @z-Lunar
