### ISSUE TITLE
[vehicles/vehicles] Cruise Control

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1363]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Having a custom cruise control like we need to do **/cruisecontrol or /cc** & the maximum speed we need. 
Example: /cc 40 & the speed won't go beyond 40.
We can still have the current one + this one.

**Reason:**
Why would your suggestion be a good change to the framework?
Sometimes the speed doesn't lock where you want to & it's pretty troublesome when you having a convey.

**Comment by InZidiuZ** [comment]
This has been added with version 3073.
