### ISSUE TITLE
Vehicle despawning

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1364]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
After the recent big maintenance, the old bug or whatever it is came back, if we park our **vehicle** outside a house/repair shop or anywhere where we need to press E & load into an interior & when we come back from that interior our car disappears this was fixed in the previous version but after the maintenance, it started again. 

**Steps to Reproduce:**
Include what steps are needed in order to reproduce this issue.
Not sure :|

**Expected Results:**
What are the expected results?
The car should not disappear

**Actual Results:**
What are the actual results?
The car stays there 

**Server:**
What server/community did this issue occur in?
Indian Legacy WL

**Comment by InZidiuZ** [comment]
No framework files on any of the live servers has been changed since a few weeks, so it's most likely an issue related to FiveM. Could you try to change your FiveM client to Canary & see if it still happens then?

**Comment by KaiEagle** [comment]
> No framework files on any of the live servers has been changed since a few weeks, so it's most likely an issue related to FiveM. Could you try to change your FiveM client to Canary & see if it still happens then?

yea I can try btw it's not just me many other people have also experienced this.

**Comment by KaiEagle** [comment]
ok so I have tried what you asked me to & it's the same for both Release & Canary, the proof is attached below.
**Release:**
https://youtu.be/a46jeDxrlls

**Canary:**
https://youtu.be/Kf_m-uGbIZc

**Comment by InZidiuZ** [comment]
Closing as it's a FiveM issue. From what I've read, it's fixed in the latest artifact versions so once we update to those (soon), this hopefully won't be an issue anymore.
