### ISSUE TITLE
Cocaine Mission Bug report

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#1367]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198397274352/home
**Summary:**
Write a short summary of what you are experiencing.
When doing a cocaine run when you land in the water for the past 2 days there hasn't been a package you can interact with.  You can hear the beeping of the beacon for the package but you never get the option to pick it up.  
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
start mission at the desk, fly to the package location, land and pick up package, return to the airfield hanger to complete the mission.
**Expected Results:**
What are the expected results?
to be able to fly to the package  spot and pick the package up to complete the mission and obtain a brick of cocaine
**Actual Results:**
What are the actual results?
for the past 2 days you've not been able to pick the package up in the water.  This has happened  to numerous people that have attempted to do the mission.  Randomly it will work  as intended.
## Additional Information
I tried  to replicate this in the test server by crashing the plane or having the mission time out and I've not been able to replicate the issue in the test environment.
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
CID: 68 - Job Data: Mechanic, Los Santos Customs, Tow Driver
**Server:**
What server/community did this issue occur in?
na/eu main
**Notes:**
For anything else noteworthy.

**Comment by Masik52** [comment]
potential way to replicate, let the timer for the mission run out w/o picking up the package end mission next attempt I wasn't able to pick up the package and it also showed 2 waypoints for the package.

**Comment by DaxterPancake** [comment]
I have experienced this myself aswell. You pay the 1k, get the plane and land it in the water but the package is nowhere to be found, sometimes there isn't even any beeping. 
I can try to get you a video if you need.

**Comment by InZidiuZ** [comment]
I am very certain it's the same issue as with #1364, so closing this for the same reason.

**Comment by JC-5** [comment]
This is still an issue.
