### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jamalghota** [InZidiuZ/op-framework-issue-tracker#1369]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561199079586936/

**Summary:**
When someone puts me in car trunk,suddenly i get disappeared and fall below the city

**Steps to Reproduce:**
When someone puts me in car trunk,suddenly i get disappeared and fall below the city

**Expected Results:**
Pls fix the bug asap

**Actual Results:**
Not fixed bug

## Additional Information

**Screenshots:**

**Game Resolution:**
1920×1080

**Player Data:**

Server:
Server 1

**Notes:**

**Comment by InZidiuZ** [comment]
Read the README file
