### ISSUE TITLE
Remove assets from El Rancho Blvd if possible

### ISSUE THREAD

**Issue by essjaybee** [InZidiuZ/op-framework-issue-tracker#137]
**Reporter:**
It's OMGPointless#1823 again

**Summary:**
Transporter job, trailer spawns at tight locations, today I aim to see if we can fix my favourite /canceljob: **El Rancho Blvd.**

![20190701163204_1](https://user-images.githubusercontent.com/2750716/60445315-478f3e80-9c1f-11e9-9da0-5b9fa1e90408.jpg)

**Steps to Reproduce:**
I'm not sure, maybe it happens every time, maybe it's luck. Maybe it's desync. Maybe it's the evil static assets in the middle that will wreck your car and flip trailers. 

But basically, go to El Rancho Blvd. 

![20190701163316_1](https://user-images.githubusercontent.com/2750716/60445010-a99b7400-9c1e-11e9-9a28-f0dd0dacd6b8.jpg)
_These evil creatures + stairs, makes..._
![20190701163921_1](https://user-images.githubusercontent.com/2750716/60445085-cf287d80-9c1e-11e9-914e-6f7a376031c7.jpg)
_This spawning spot a mess_

**Expected Results:**
To get my trailer without having to either destroy it or smash the trailer out and hope for good fortunes.

**Actual Results:**
What are the actual results?
![20190701163204_1](https://user-images.githubusercontent.com/2750716/60445198-0ac34780-9c1f-11e9-8521-07f1e0adfb4b.jpg)

## Additional Information

**Screenshots:**
![20190701163204_1](https://user-images.githubusercontent.com/2750716/60445203-0e56ce80-9c1f-11e9-8217-23d38fed5542.jpg)
![20190701163238_1](https://user-images.githubusercontent.com/2750716/60445206-0f87fb80-9c1f-11e9-82ca-3c69a265b967.jpg)
![20190701163337_1](https://user-images.githubusercontent.com/2750716/60445231-1747a000-9c1f-11e9-9732-f7714a5c2860.jpg)

![20190701163502_1](https://user-images.githubusercontent.com/2750716/60445244-1dd61780-9c1f-11e9-99de-e9677916bfe1.jpg)
_Eventually managed to get it on after bending the rear and smashing my headlights, woopsie._ 

**Player Data:**
Char Id: 543
Transporter

**Notes:**
![20190701163520_1](https://user-images.githubusercontent.com/2750716/60445284-35ad9b80-9c1f-11e9-9e00-fad2d129bc44.jpg)
_Shared fuel poggers, nothing else in F8._

Is it possible to just remove the evil trailers in the middle?

**Comment by InZidiuZ** [comment]
Horrendous.

Anyways, removing the trailers is possible, but would require a loop to run & check if they exist, and if they do, we'd delete them. Instead, I moved the trailer ahead a little, and changed its heading, which hopefully resolves the issue.

**InZidiuZ**
*OP-FW Developer*
