### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by aronliljar** [InZidiuZ/op-framework-issue-tracker#1370]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/id/aronliljar

**Summary:**
Hearing everyone on the server

**Steps to Reproduce:**
I have no idea how this happened but when i went past the LSPD the ground didnt load correctly and i heard everyone on the server until i left the area, this happens on a lot of random areas which i cant say where.

**Expected Results:**
Hearing everyone?

**Actual Results:**
Hearing everyone 

## Additional Information

**Screenshots:**
dont really have screenshots other than a 2 minute clip i recorded

**Game Resolution:**
1920x1080

**Player Data:**
https://cdn.discordapp.com/attachments/496508374779953203/754061227444928562/unknown.png

**Server:**
Legacy Roleplay #1
**Notes:**
dont really know anything much more about it

**Comment by InZidiuZ** [comment]
Read the README file
