### ISSUE TITLE
Caesars Place 2 Gate Addition & Some Changes.

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1371]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**YES**

**Summary:**
**1) Caesars Place 2 Don't have Gate at Entry**

![20200912012502_1](https://user-images.githubusercontent.com/56230822/92968625-1a802200-f499-11ea-92c2-ff41573f33b5.jpg)

**I am adding the picture of gate that can we add.**

![20200912013507_1](https://user-images.githubusercontent.com/56230822/92968659-2bc92e80-f499-11ea-95f7-28168448b71e.jpg)
![20200912013502_1](https://user-images.githubusercontent.com/56230822/92968668-2d92f200-f499-11ea-8098-b9119978d0d7.jpg)

**2) The Spot to remove vehicle is weird and too far from main door.** 

![20200912012511_1](https://user-images.githubusercontent.com/56230822/92968801-65019e80-f499-11ea-8716-166ff86d2ad6.jpg)

**This can be added at this location.**

![20200912012530_1](https://user-images.githubusercontent.com/56230822/92968952-a42fef80-f499-11ea-96eb-fdf08a0c419c.jpg)

**3) No water at Pool... (This is optional.. I don't know if we can water in pool or not... its upon you.)**

![20200912012619_1](https://user-images.githubusercontent.com/56230822/92969074-db060580-f499-11ea-8e99-3e42b2b8f374.jpg)

**Reason:**
1) **(About Gate Addition)** The house have luxurious look but having no gate at entry ruins the house owner experience and customers thinks before taking house on rent.
2) **(About Garage Location)** The Garage location right now is outside the gate, this is really odd location and Owner needs to get out of his house to get his vehicle out. This wastes the time of player
3) **(About Adding Water in Pool)** Having No Water in Pool makes no use of Pool at house and POOL PARTY option is missing and Back Side Look of House doesn't look Good.

**Comment by utk2410** [comment]
+1

**Comment by novapurple** [comment]
Believe this was removed because it was annoying to jump over your gate because it didn’t move ? I may be wrong but I believe it was removed for that and you also weren’t able to bring cars into your drive way.

**Comment by utk2410** [comment]
@novapurple Isn't it possible to add the non-automatic doors....? Cause a Mansion without a gate doesn't look luxurious enough. The customers don't prefer buying this house on rent mainly because of its look **( No Gate and No water in pool )**

**>Non-Automatic Door.**
![image](https://user-images.githubusercontent.com/71107690/92992580-aaf64b00-f509-11ea-9688-3a1919280748.png)

**Comment by InZidiuZ** [comment]
@novapurple is right, the gate was removed in the first place as it was a fixed object. This issue tracker is only used for scripting and the framework's development & as we don't script in objects and such, I'll redirect you to the issue tracker for assets where you could suggest these changes.
