### ISSUE TITLE
 Portola/Spanish/Rockford Disappearing Garbage Route Bug

### ISSUE THREAD

**Issue by cwisdasaur** [InZidiuZ/op-framework-issue-tracker#1374]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561197994133097/

**Summary:**
Write a short summary of what you are experiencing.
In my experience, the garbage route at Portola Drive - Spanish Ave - Rockford Hills is broken.  A 2 mile drive from HQ, upon arriving my route will abruptly end saying, return to HQ.  My HUD also disappears at that same moment, consistently. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
1) Run a garbage route
2) Get sent to  Portola Drive - Spanish Ave - Rockford Hills
3) Arrive at the marker and you will be instructed to return to HQ
4) HUD/GPS will be gone until you exit the vehicle, and reset defaults in display settings

**Expected Results:**
What are the expected results?
The expected result is to let the worker run the route at the park there, then return to HQ for a pay check.

**Actual Results:**
What are the actual results?
The worker will drive a 4 mile round trip only to be sent back to HQ.  If he even makes it back to HQ with no HUD/GPS, he will not be paid any money.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://medal.tv/clips/32685730/d1337NOT7h2k

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://imgur.com/a/O7n0j5N

**Server:**
What server/community did this issue occur in?
Legacy Roleplay NA/EU Server

**Notes:**
For anything else noteworthy.

**Comment by its-Frost** [comment]
Big +1 dawg

**Comment by InZidiuZ** [comment]
See #958.

A local temporary workaround could be to set all [these three options](https://gyazo.com/8b87097b6902b31efc9efb4911c6c593) to max, found under the 'Graphics' settings.
