### ISSUE TITLE
[job/ems] On/OFF Duty Button

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1375]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
As Per The New Update There Are Doors Which Are Now Lock/Unlockable So, As If A EMS Want To Go On Duty It Gets Spam Due To Doors Lock / Unlock Is Also Take Place As You Go On/Off Duty Which Is Like Ten Times You Go On And Off Duty. If By Any Chance The Button For Going On/OFF Duty Keybind Changed Any Other Alphabet Like F Or ETC. So No Timestamp Would be Spammed And EMS Won't Get Problem Responding Calls With Door issue And Going On/Off Duty.Sometimes They Won't Know When They Went Off Duty Until Going To Take Out Ambulance Before Responding To Call

**Reason:**
Why would your suggestion be a good change to the framework?

The Below Screenshots Are For The Same :-

On/Off Duty [ Keybind should Be Changed By Any Chance ] :
![1](https://user-images.githubusercontent.com/64654455/93117977-34aa4200-f6dd-11ea-8068-51a8d33a0df1.png)

The Door Towards Locker Room :
![2](https://user-images.githubusercontent.com/64654455/93117989-36740580-f6dd-11ea-8220-786d7b6c2f94.png)

3.The Door For The Entry Inside Reception :
![3](https://user-images.githubusercontent.com/64654455/93117996-37a53280-f6dd-11ea-9e5f-58316823a564.png)

**Comment by InZidiuZ** [comment]
As a temporary workaround, the "Press to sign on duty" text now has a smaller radius to prevent this sort of collision.
