### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1376]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/avilashsengupta/

**Summary:**
When entering into the server for the very first time. Owned properties don't show up on the spawn location list. 

**Steps to Reproduce:**
enter the city for the very first time

**Expected Results:**
owned properties show on the spawn location list

**Actual Results:**
owned properties don't show on the spawn location list

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
Legacy Roleplay India 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This should now be resolved with version 3096.
