### ISSUE TITLE
Purchasable Block Suggestion 

### ISSUE THREAD

**Issue by z-Lunar** [InZidiuZ/op-framework-issue-tracker#1377]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
yes.

**Summary:**
Write a summary of what your suggestion is about.
An addition to the list of available blocks to purchase + some interiors inside the block.

Which block? Eclipse Boulevard 
How Many Interiors/Apartments? 5
Block Price? $75000 Upkeep ($15000 or more per apartment) ALL the interiors inside this block are High End Apartments or Higher as listed in #public-information in discord. "High-End Apartment - 15000/w | Storage = 7500"

**Reason:**
Why would your suggestion be a good change to the framework?
I feel my suggestion would be a good addition to the city...in the sense it would add some diversity to the current standards of homes, as it stands $15000 houses don't have any visibility to the outside world...given I understand why they're blocked off but it would also be dope to see a "select few" that do have this option. 

![image](https://user-images.githubusercontent.com/46366594/93177513-8b714500-f6f8-11ea-9b98-9d192a5d9ae4.png)
![image](https://user-images.githubusercontent.com/46366594/93177522-8e6c3580-f6f8-11ea-9282-583e706eaa11.png)
![image](https://user-images.githubusercontent.com/46366594/93177554-9af08e00-f6f8-11ea-95ce-ab91951201bb.png)
![image](https://user-images.githubusercontent.com/46366594/93177672-c5dae200-f6f8-11ea-99e4-0e6a29a6b156.png)

[https://gta.fandom.com/wiki/Eclipse_Towers](url)
[https://www.gtabase.com/grand-theft-auto-v/properties/gta-online/eclipse-towers-apt-3](url)

**Comment by InZidiuZ** [comment]
This wouldn't work at all with how the current housing system is set up, and neither will it in the foreseeable future, so will close and decline this suggestion.
