### ISSUE TITLE
[illegal/burglaries] Gold Bars in House Robbery

### ISSUE THREAD

**Issue by its-vishal** [InZidiuZ/op-framework-issue-tracker#1378]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Summary:**
As of now we cannot find Gold Bars in House Robbery and This Kind of a unfair. Off course the chances of getting gold bar should be low. But this should be added

**Reason:**
If we can find gold bars in Garbage, Then Gold Bars should also be added in house robbery.

**Comment by nautam24** [comment]
No it should not be there because people doing garbage for this if you change it then all people will go towards house robbery

**Comment by bhosalevishu** [comment]
> No it should not be there because people doing garbage for this. Garbage is famous for this only and if you change it then all people will go towards house robbery. It will unbalance the game.

Okay.. then why all people don't do Sunken Ship..? it also gives gold bar... 
Why all. people don't do garbage..?
it also gives gold bar...
Off course the drop of the gold bar will be low... not like you getting gold bar in every house.. getting one in full night is enough.. giving 1000$ per night not a big deal... 😑

**Comment by nautam24** [comment]
> > No it should not be there because people doing garbage for this. Garbage is famous for this only and if you change it then all people will go towards house robbery. It will unbalance the game.
> 
> 
> 
> Okay.. then why all people don't do Sunken Ship..? it also gives gold bar... 
> 
> Why all. people don't do garbage..?
> 
> it also gives gold bar...
> 
> Off course the drop of the gold bar will be low... not like you getting gold bar in every house.. getting one in full night is enough.. giving 1000$ per night not a big deal... 😑

Bro its not like this because in house robbery you can easily get 400-500 dollars per night and also you can get the good stuffs which price ranges from 1500-2000 so adding gold bar will buff the house robbery and people will do house robbery only instead of garbage and also for gang its bonus because gangs cant do garbage and plus you told that scuba diving gives gold bar but you have to travel large distance and its time consuming task so there should be gold bar because in scuba diving you will not get ket set, .50 and micro smg and other valuable stuff. So adding gold bar in house robbery in not suitable suggestion.

**Comment by bhosalevishu** [comment]
who said Sunken ship not give key sets? and how adding 1000$ in a house robbery will unbalance game..? 😅

**Comment by bhosalevishu** [comment]
sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars..

**Comment by bhosalevishu** [comment]
this not unbalance your game?

**Comment by nautam24** [comment]
> sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars.. 

Waah tu kar ke dikha 1800 per run maine to itna profit kabhi nai dekha maine 50 bar to kiya hi hoga +uske upar gold bar sahi he bhai

Suun scuba me 1 run pe 800 milte he including scrap aluminium and steel and initial investment is 500$ for oxygen tank but if you are lucky then you will get thermite, goldbar and key so it will add max 1000 so its not unbalanced

**Comment by ppthegamer** [comment]
> > sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars..
> 
> Waah tu kar ke dikha 1800 per run maine to itna profit kabhi nai dekha maine 50 bar to kiya hi hoga +uske upar gold bar sahi he bhai
> 
> Suun scuba me 1 run pe 800 milte he including scrap aluminium and steel and initial investment is 500$ for oxygen tank but if you are lucky then you will get thermite, goldbar and key so it will add max 1000 so its not unbalanced

By selling keys and thermite you can earn more than 1k

**Comment by nautam24** [comment]
> > > sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars..
> 
> > 
> 
> > Waah tu kar ke dikha 1800 per run maine to itna profit kabhi nai dekha maine 50 bar to kiya hi hoga +uske upar gold bar sahi he bhai
> 
> > 
> 
> > Suun scuba me 1 run pe 800 milte he including scrap aluminium and steel and initial investment is 500$ for oxygen tank but if you are lucky then you will get thermite, goldbar and key so it will add max 1000 so its not unbalanced
> 
> 
> 
> By selling keys and thermite you can earn more than 1k 

Bro legacy WL me key ki price 600 and thermite ki 800-1000 and normal server me key ki price 800 and thermite 700 and there is a slim chance to get both in single run and selling key and thermite is risky to get scammed by others so its already balanced.

**Comment by bhosalevishu** [comment]
> > > > sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars..
> > 
> > 
> > > 
> > 
> > 
> > > Waah tu kar ke dikha 1800 per run maine to itna profit kabhi nai dekha maine 50 bar to kiya hi hoga +uske upar gold bar sahi he bhai
> > 
> > 
> > > 
> > 
> > 
> > > Suun scuba me 1 run pe 800 milte he including scrap aluminium and steel and initial investment is 500$ for oxygen tank but if you are lucky then you will get thermite, goldbar and key so it will add max 1000 so its not unbalanced
> > 
> > 
> > By selling keys and thermite you can earn more than 1k
> 
> Bro legacy WL me key ki price 600 and thermite ki 800-1000 and normal server me key ki price 800 and thermite 700 and there is a slim chance to get both in single run and selling key and thermite is risky to get scammed by others so its already balanced.

**Kabse whitelisted ho..? **

**Comment by nautam24** [comment]
> > > > > sunken ship gives around 1200-1800$ per run.. where you also get thermite, keys, gold bars..
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Waah tu kar ke dikha 1800 per run maine to itna profit kabhi nai dekha maine 50 bar to kiya hi hoga +uske upar gold bar sahi he bhai
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Suun scuba me 1 run pe 800 milte he including scrap aluminium and steel and initial investment is 500$ for oxygen tank but if you are lucky then you will get thermite, goldbar and key so it will add max 1000 so its not unbalanced
> 
> > > 
> 
> > > 
> 
> > > By selling keys and thermite you can earn more than 1k
> 
> > 
> 
> > Bro legacy WL me key ki price 600 and thermite ki 800-1000 and normal server me key ki price 800 and thermite 700 and there is a slim chance to get both in single run and selling key and thermite is risky to get scammed by others so its already balanced.
> 
> 
> 
> **Kabse whitelisted ho..? **

This is not for Wl server this for game balance bro and i dont have personal issue with your concerns i am from normal server. kuch problem ho to bolna

**Comment by bhosalevishu** [comment]
"Then no point in discussing this topic with you"

I add suggestions to github after thinking about all possibilities and if you think this is bad idea.. then InzidiuZ kabka ye suggestion close kr deta..

i have been playing Legacy since one year.. and I know how things work... adding suggestions just improves players experience and giving someone one gold bar in a night.. don't unbalance the game... And talking about thermites.. I have sold thermites at 2750 one time.. its your mind, how you use and with whom you deal with for money.. Thanks... I have no more time to reply this topic... 🙏🙂

**Comment by nautam24** [comment]
> "Then no point in discussing this topic with you"
> 
> 
> 
> I add suggestions to github after thinking about all possibilities and if you think this is bad idea.. then InzidiuZ kabka ye suggestion close kr deta..
> 
> 
> 
> i have been playing Legacy since one year.. and I know how things work... adding suggestions just improves players experience and giving someone one gold bar in a night.. don't unbalance the game... And talking about thermites.. I have sold thermites at 2750 one time.. its your mind, how you use and with whom you deal with for money.. Thanks... I have no more time to reply this topic... 🙏🙂

Ahhh.. i know that you will show your attitude.. i am in legacy since 1 year and right now i am playing in WL so bhai apna attitude apne paas rakho and me abhi kuch nai boluga btw time nikala karo sir i know aap bahut paise vale he ghamand he but jab baat discussion ki aati he tab discuss karo tera point agar impactful nai he to esa mat likh ke no more time for discussion...
Now i end my point and conversation also

**Comment by Ravi1199** [comment]
> > "Then no point in discussing this topic with you"
> > I add suggestions to github after thinking about all possibilities and if you think this is bad idea.. then InzidiuZ kabka ye suggestion close kr deta..
> > i have been playing Legacy since one year.. and I know how things work... adding suggestions just improves players experience and giving someone one gold bar in a night.. don't unbalance the game... And talking about thermites.. I have sold thermites at 2750 one time.. its your mind, how you use and with whom you deal with for money.. Thanks... I have no more time to reply this topic... 🙏🙂
> 
> Ahhh.. i know that you will show your attitude.. i am in legacy since 1 year and right now i am playing in WL so bhai apna attitude apne paas rakho and me abhi kuch nai boluga btw time nikala karo sir i know aap bahut paise vale he ghamand he but jab baat discussion ki aati he tab discuss karo tera point agar impactful nai he to esa mat likh ke no more time for discussion...
> Now i end my point and conversation also

Dude its not about attitude and by the way he is playing in whitelist from past more than one year and he have done so many things for the server development and for increasing the RP in servers. So think more than twice before saying any thing to anyone with out knowing about anyone.

**Comment by DaxterPancake** [comment]
Personally I feel like this isn't needed.
Instead we should add a different item, lets say 'Gold Chain' or 'Rolex' which can then be sold using a fence, adding a variety of items and activities. 
The server is constantly being worked on, so we don't need to add the same items into everything.
