### ISSUE TITLE
Premium Dealership - Unable to Purchase Ladybird - Reads Insufficient funds with more than 35k cash

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1379]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/id/nohbob/

**Summary:**
Was unable to purchase the Ladybird for Listed Price ($35000)

**Steps to Reproduce:**
Have Highest Tier (Godlike)
1. Went to Exclusive Dealership
2. Had 38500 Cash on me
3. Selected Ladybird
4. Insufficent Funds

**Expected Results:**
1.  Purchase Car

**Actual Results:**
1.  Results in "Insufficient Funds'
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://i.imgur.com/nb4QKhL.png
https://i.imgur.com/Onzc0RD.png

**Game Resolution:**
What is your game's resolution?
2560X1440
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Character ID: 86 - Job Data: Bar and Club, Bar Jobs, Bar Owner
**Server:**
What server/community did this issue occur in?
N/A

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has been resolved. I'd suggest not trying to purchase any of the 'Legendary' vehicles until 3095 is live.
