### ISSUE TITLE
Casino

### ISSUE THREAD

**Issue by FilipQeh** [InZidiuZ/op-framework-issue-tracker#138]
**Name:**
Filip Johnson / F.Johnson#7465

**Summary:**
Opening the **_CASINO_** and having gamble nights with working slots/roulette or 21. Also having a Company or a big Gang run this would be great. There was this other server that implemented this perfectly, now it may not have been a GTA server but it was Rp related. Project Silverlake Arma 3 Life had this perfect implementation of a big casino that was run by the "Mob" and it was really great for RP.

**Reason:**
I really feel like it would be a fun place to hang out on late nights and get positive and fun rp experiences, Would encourage more RP than grinding money without interacting with anyone.
![Screenshot_112](https://user-images.githubusercontent.com/51554704/60447306-76a7af00-9c23-11e9-9901-37f53248bfbf.png)
![Screenshot_113](https://user-images.githubusercontent.com/51554704/60447307-76a7af00-9c23-11e9-8138-26e1d4e3c972.png)

**Comment by InZidiuZ** [comment]
Hey,

This is already a card on the [Trello](https://trello.com/c/sqJE9cH1/276-gambling). Won't be doing anything with this until we've got some interiors to work with though, so closing this until then.

**InZidiuZ**
*OP-FW Developer*
