### ISSUE TITLE
No Caesars Place 4 in /Blocks & Also Not Available to Sell/Purchase.

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1380]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Player Identification:**
http://steamcommunity.com/id/vishalbhosale

**Summary:**
Caesars Place 4 is not available to purchase and also not in /Blocks nor in Company Info. I Given information in Screenshots. I am able to locate Caesars Place 4 but its not visible in Company Info.

**Steps to Reproduce:**
Add Caesars Place 4 in Company Info. or in  /Blocks

**Expected Results:**
It should be available to purchase and sell property.

**Actual Results:**
There is not Caesars Place 4 available to sell.

**Screenshots:**
![1](https://user-images.githubusercontent.com/56230822/93274042-fc872a00-f7d6-11ea-9061-feb211cb947a.png)
![4](https://user-images.githubusercontent.com/56230822/93274046-01e47480-f7d7-11ea-91ac-64495dc8f505.png)
![3](https://user-images.githubusercontent.com/56230822/93274047-027d0b00-f7d7-11ea-92a0-a0cc0ba01540.png)
![2](https://user-images.githubusercontent.com/56230822/93274049-027d0b00-f7d7-11ea-8695-24abe5564e45.png)

**Game Resolution:**
1920x1080

**Player Data:**
Logan Petrova Character ID: 386 Job Data: Bars and Club, Bar Jobs, Bar Owner, 

**Server:**
Legacy INDIA Whitelisted

**Comment by InZidiuZ** [comment]
You have to purchase the block after the change.

**Comment by KaiEagle** [comment]
That's sad.
