### ISSUE TITLE
Commands Substitutes For suspect in/out, impound

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1381]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
To Add A Shortcut for suspect In/out ,Impound Like We Have For hardcuff We can do hc  To Hard Cuff A Person 

**Reason:**
Why would your suggestion be a good change to the framework?
This Would be Very Helpful for PD And EMS To Do The Procedure More Quickly

**Comment by InZidiuZ** [comment]
Once the currently deprecated police system is rewritten, most likely, yes, until then, no.
