### ISSUE TITLE
EDM car Issue

### ISSUE THREAD

**Issue by MrJoker00** [InZidiuZ/op-framework-issue-tracker#1382]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/id/Sky_Snoopy/

**Summary:**
Bought a New Mercedes AMG C63 and after saving it , Its turn out into Subaru SSTI
**Steps to Reproduce:**
Went to buy New Mercedes AMG C63 in Heroic Tier
Bought It 
Saved it in garage 
When i take out again its became Subaru SSTI

**Expected Results:**
New Mercedes AMG C63

**Actual Results:**
Turned into Subaru SSTI

## Additional Information

**Screenshots:**
https://imgur.com/dteE1mo

**Game Resolution:**
1366x768

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
legacy India WL

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3098.

**Comment by MrJoker00** [comment]
New Issue:
Not able to enter without VPN 
Server:
Legacy India WL

When entered to see Mercedes issue has been solved or with vpn , it was not been solved yet. Still got SSTI Subaru. 

Main Issues:
Not able to entered India WL Legacy without VPN
Mercedes AMG C63 is still Subaru SSTI in my garage.
