### ISSUE TITLE
EDM cars BUG !

### ISSUE THREAD

**Issue by Spyro17** [InZidiuZ/op-framework-issue-tracker#1383]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/SpyroYoutube/
**Summary:**
Write a short summary of what you are experiencing.
When the server was updated with alpha_2.7.0.3076! i went to EDM to buy new cars , I bought 2 cars , one was Mercedes C63 it was fine and i drove it to garage near EDM and saved it then i went to EDM to buy another Car and i bought Nissan Titan ,as soon i clicked on purchase my car started to fluctuate for me and i was not able to sit inside so i decided to went to my home to retrieve it but both my cars Mercedes and Nissan Titan were not showing in my Garage , I also tried to reconnect to the server to check the issue still exist or not but  the issue was there . 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Step 1 : Went to EDM
Step 2 : Bought Nissan Titan and Mercedes C63
Step 3 : Both cars were not in garage 
Step 4 : Couldn't able to retrieve both cars as well .
**Expected Results:**
What are the expected results?
Both Cars should be back in garage 
**Actual Results:**
What are the actual results?
both cars will be back in garage as normal
## Additional Information
no
**Screenshots:**
If suitable, include some screenshots.
unfortunately i was not recording 
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://www.linkpicture.com/q/my-id.png
**Server:**
What server/community did this issue occur in?
Legacy India Whitelist Server
**Notes:**
For anything else noteworthy.
no sir .

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3098.

**Comment by Spyro17** [comment]
> This issue has been resolved with version 3098.

I am not able to enter the server after latest Build .

**Comment by InZidiuZ** [comment]
...which server?

**Comment by Spyro17** [comment]
Legacy India Whitelist sir

**Comment by InZidiuZ** [comment]
Could be more specific than just 'not able to enter'?

**Comment by Spyro17** [comment]
Yes sir , yesterday when Alpha 3076 was released ,i purchased 2 cars , Nissan Titan and AMG C63  , after the purchase of Nissan Titan,it started to fluctuate  in my eyes and i was not able to sit inside car , so i decided to go and retrieve it ,but both my cars were not showing up in any garage, so after the latest build i am trying to enter in city but its keep giving me that error .
Plus sir AMG C63 price was 75000$ but when i purchased that car it deducted only 45000$ and when i was trying to retrieve My Merc first it was showing SSTI in garage , that means it was converted into Saburu and  then i waited for the server update and now after the update i am getting this error , i tried everything ,clearing Cache folder and reinstalling fiveM but the issue still presist .

**Comment by Spyro17** [comment]
https://www.linkpicture.com/q/no-cars.png
https://www.linkpicture.com/q/nuksan.png
Bro here is my id and garage list , there is no cars 
i went to server again by using vpn and bought Nissan Titan Again and still bro no cars in my garage ,i lost my 125000$ on this bug and today is the last day of my priority :(
