### ISSUE TITLE
Block: Panorama Drive (175) - Price is set to $3500 per week, but has a Trailer Apartment type

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1384]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/id/nohbob/

**Summary:**
Panorama Drive (175) - Price is set to $3500 per week, but has a Trailer Apartment type.  The cost should be $1000 for the block of 1 Trailers. 

**Steps to Reproduce:**
Go to Yellowjack
/blocks
Notice Maintenance Cost is $3500 per week
Own Block 175
Walk up to front door of trailer in back
/Enter Trailer
Interior is Trailer type (so should be $1000.00)

**Expected Results:**
Cost of Block should be $1000 or Interior Should match Price point

**Actual Results:**
Cost for Block is $3500 and the interior is a $1000 Trailer interior. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://i.imgur.com/7M5LZse.png

Game Resolution:
What is your game's resolution?
2560X1440

Player Data:
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Character ID: 86 - Job Data: Bar and Club, Bar Jobs, Bar Owner
Server:
What server/community did this issue occur in?
N/A

Notes:
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
The prices in /blocks are hard-coded and are at this time inaccurate/outdated. This won't be fixed until it's made automatic.
