### ISSUE TITLE
Bug report: Tackling making your weapon fire

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1385]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1 
**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
**Include what steps that are needed in order to reproduce this issue.**
So you need to been aiming with /ads on and aim. Someone else tackles you the shot gets fired you can see 7 bullets in start and then 6 at the end of the video. No one else can hear it but the person aiming in ads.
**Expected Results:**
What are the expected results?
Shouldnt be firing unless you press the trigger button when tackled by someone.
**Actual Results:**
What are the actual results?
Shot is fired from the gun when tackled by someone
## Additional Information
https://youtu.be/KeRLBxxvpL4

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/6a01de2c0ce42fde13c23a165e8d8ea3
**Server:**
What server/community did this issue occur in?
India Public servers
**Notes:**
For anything else noteworthy.

**Comment by DooZolz** [comment]
This happened to me as well. + 1

**Comment by AdeptCL** [comment]
This hasn't happened to me, but one thing that has is I will /ads and shoot while looking down the sights, fire once but for me, it fires 2 or 3 times. Whereas everyone else only sees me shoot once.

It takes the 2-3 extra bullets away, although an individual only gets shot once.
