### ISSUE TITLE
Bug report: Activity points stuck at 0 or at a particular number

### ISSUE THREAD

**Issue by sanju-007** [InZidiuZ/op-framework-issue-tracker#1387]
EVEN THOU ON DUTY-EMS OR PD POINTS RESETS TO 0 OR GETS STUCK TO PARTICULAR NUMBER
PROOF:
![image](https://user-images.githubusercontent.com/68018322/93349951-bde48480-f855-11ea-874a-762e2209bab2.png)

**Comment by InZidiuZ** [comment]
Read the README file
