### ISSUE TITLE
Suggestion - Make DA a PD role

### ISSUE THREAD

**Issue by DakotaGillette** [InZidiuZ/op-framework-issue-tracker#139]
**Name:**
Steve Steve
DJG#0001

**Summary:**
Making the District Attorney job a PD role.

**Reason:**
This idea was previously discussed among the lawyers, and since then I've also brought it up to the detectives, and other PD members. Currently, with no official law firm, the District Attorney's have no actual salary. We've had to essentially move on to other jobs. As DA, we write arrest and search warrants for detectives, and represent police in any legal matters. I think it would only make sense to add the District Attorney role as a PD role. This would help with the salary issue, as well as allowing Detectives to continue their role play of actually arresting and searching people once they've collected all the proper information. If I recall, the District Attorney salary was $2000, and I think District Senior Attorney was around $2500, so whatever the equivalent to that is in OP-FW would be sufficient for us to continue to roleplay of DA.

**Comment by InZidiuZ** [comment]
Hey,

Lawyer-related stuff will most likely go under the planned state system as well as the company system, but closing for now, as I won't be adding a "DA" role to PD, for now.

**InZidiuZ**
*OP-FW Developer*
