### ISSUE TITLE
Suggestion: can you put thermite and cool stuff in garbage so we can get it because last time I work 6-7 hrs and i got two thermite... 

### ISSUE THREAD

**Issue by RDX1** [InZidiuZ/op-framework-issue-tracker#1390]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by DaxterPancake** [comment]
Follow the template.
