### ISSUE TITLE
[game/inventory] Show weapon serial number on the inventory

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1394]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yeah

**Summary:**
My suggestion is to add the serial number of the 'unknown' weapons in the inventory too.

**Reason:**
Because when you get evidence and you have the serial number, you have to shoot/analyze all the 'suspect weapons' and see the casing serial. It would be easier if it was seen in the inventory, to facilitate action for PD.

**Comment by InZidiuZ** [comment]
This has since been done.
