### ISSUE TITLE
Character info Bar out of screen/ yoga centre bug

### ISSUE THREAD

**Issue by shubhboy** [InZidiuZ/op-framework-issue-tracker#1396]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561199031078142/

**Summary:**
After Alpha 2.6 update my chacrater healthbar and other info bars & gun bullets count info display out of screen.... i was tried everything change resolution,display full screen(exclusive), clear cache, reinstall fivem but still same/  2nd bug can't do yoga in yoga centre

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
bottom left information bars fit in screen. /  2nd bug press E to do yoga

**Actual Results:**
out of screen character information bars  / 2nd bug cant do yoga in yoga centre
![Inked20200921134839_1_LI](https://user-images.githubusercontent.com/65948827/93751675-17183380-fc1b-11ea-824f-4e98a9839a5f.jpg)
![20200921135428_1](https://user-images.githubusercontent.com/65948827/93751710-27c8a980-fc1b-11ea-9c92-5c760f132e9c.jpg)

## Additional Information

**Screenshots:**
check attached file of Ss

**Game Resolution:**
1360*768

**Player Data:**
character ID - 669 Timestamp : 2020-09-21 09:31:32

**Server:**
Legacy Roleplay India

**Notes:**
For anything else noteworthy.

**Comment by bhosalevishu** [comment]
for Yoga Bug.... Make this three settings full.

![image](https://user-images.githubusercontent.com/56230822/94028659-a79c7280-fdd9-11ea-8ef6-3bfcc48f0ae9.png)
.

**Comment by shubhboy** [comment]
@bhosalevishu what about character info bar did you know?

**Comment by InZidiuZ** [comment]
The other issue should be the "Safezone Size" under "Display" settings

**Comment by shubhboy** [comment]
Its working thanks man 😊
