### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KurFuE** [InZidiuZ/op-framework-issue-tracker#1397]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/kurfu3/

**Summary:**
Write a short summary of what you are experiencing.
suddenly i am getting 10 to 5 fps and my game is crashing. Its happening from today only

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Dont know

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1366x768

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
every server of legacy roleplay

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Great work on filling out the template... this likely also isn't an issue with the framework.
