### ISSUE TITLE
Items reappearing in the inventory.

### ISSUE THREAD

**Issue by ernigmas695** [InZidiuZ/op-framework-issue-tracker#1398]
https://drive.google.com/file/d/18dVPgbRtTKRnDeg5HcM7pOaq_Oopc1g3/view?usp=sharing
as soon as i put something from my character's inventory to my house inventory, after some minutes it is reappearing back from the house inventory to my pocket inventory nd vice versa. Have provided the video link for that

**Comment by DaxterPancake** [comment]
Follow the template.
