### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ravi1199** [InZidiuZ/op-framework-issue-tracker#1399]
**Assurance:**
Yes

**Summary:**
The new Shift(hold) + Walk doesn't make any changes in roleplay according to me. 

**Reason:**
Before we used to press shift once for continuous run. But now the same things happens by just holding the shift continuously.
And while doing some jobs for example: Garbage, delivery  jobs, etc. It doesn't make that much sense and it just do the same work doesn't make any diiference. But now the difference after new update is that we need to hold shift continuously instead of pressing once.

**Comment by InZidiuZ** [comment]
This was intentionally done to prevent accidental running into groups of people as well as to prevent some behavior in first person that made first person not a viable option to play in.
