### ISSUE TITLE
Mech towing at docks

### ISSUE THREAD

**Issue by XeineZ** [InZidiuZ/op-framework-issue-tracker#140]
**Reporter:**
Xz#5620

**Summary:**
Vehicle blocking the entry at docks when towing

**Steps to Reproduce:**
Have a car or truck on your flatbed whilst trying to enter the garage at the docks

**Expected Results:**
Enter the garage with the car still being towed

**Actual Results:**
You have to take the car off the truck and then repair the cars engine to drive it into the mech shop

**Notes:**
Also an annoying car spawns in the exit sometimes, if there is anyway to stop that. Maybe add something small to prevent the car spawning there.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. The fix for it will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
