### ISSUE TITLE
Items No Longer Stacking / Disappearing Items / Inventory Not Saving Bug

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1400]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Player Identification:**
https://steamcommunity.com/id/daxtertherealmvp/

**Summary:**
Inventories have been bugged since the new update has come out. 
I've done some testing and originally I thought that the inventories were just completely bugged and you couldn't put more than 1 item inside a storage.
After more testing, I found that it is an issue with items stacking. I was able to place things inside of my houses if I didn't stack them inside of eachother. But either way, the inventories are bugged and aren't allowing stacking of items. You need to nap for your items to re-appear or wait a certain amount of time.

**Steps to Reproduce:**
Have an item inside storage already, try to stack more items on top of it. 

**Expected Results:**
Items go into inventory correctly and are able to be stored.

**Actual Results:**
Items appear to stack in the inventory but actually don't. The items won't be in the correct storage and will appear to not be in your pockets. You will need to exit the city and re-enter or completely restart your game for the items to re-appear.

## Additional Information

**Screenshots:**
[Video 1](https://streamable.com/y4okfy) - Demonstrating item bug, Trying to stack items on top of eachother.
[Video 2](https://streamable.com/ururql) - Demonstrating that NOT stacking items allows for inventory to work properly.

**Game Resolution:**
1920 x 1080

**Player Data:**
![image](https://user-images.githubusercontent.com/50828532/93991739-f5ac7880-fdcf-11ea-8496-3f2ccaf225ba.png)

**Server:**
EU/NA

**Comment by InZidiuZ** [comment]
This issue has now been resolved as of version 3151.
