### ISSUE TITLE
Bug report for things reappearing in inventory after being kept in house inventory

### ISSUE THREAD

**Issue by ernigmas695** [InZidiuZ/op-framework-issue-tracker#1401]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/enigmas17

**Summary:**
Write a short summary of what you are experiencing.
As soon as i put some of my items from my pocket inventory to my house inventory, after sometime it appears back in my pocket inventory and vice versa.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Fix the code of items coming to the origin place.

**Expected Results:**
What are the expected results?
The things once put into another inventory should not come back again.
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://drive.google.com/file/d/18dVPgbRtTKRnDeg5HcM7pOaq_Oopc1g3/view?usp=sharing

**Game Resolution:**
What is your game's resolution?
1080P
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
CID-120
**Server:**
What server/community did this issue occur in?
Whitelist India Legacy Role Play
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Closing as it is likely the same issue as reported in #1400
