### ISSUE TITLE
FiveM problem

### ISSUE THREAD

**Issue by fghxgf** [InZidiuZ/op-framework-issue-tracker#1402]
plz help me i am etting two error in FiveM 
i am getting this error
![PNG](https://user-images.githubusercontent.com/71773975/94023597-07901a80-fdd4-11ea-86f9-38532c947400.PNG)
![Capture](https://user-images.githubusercontent.com/71773975/94023646-17a7fa00-fdd4-11ea-9921-3a68d7bd8af8.PNG)

**Comment by Nuziatella** [comment]
This is not a framework issue. Make sure your anti-virus and/or firewall isn't blocking connections to FiveM. Re-install FiveM if the issue does not resolve itself.

**Comment by fghxgf** [comment]
antivirus off hai

**Comment by fghxgf** [comment]
re install bhi ki

> This is not a framework issue. Make sure your anti-virus and/or firewall isn't blocking connections to FiveM. Re-install FiveM if the issue does not resolve itself.

re install bhi kiya
aur FiveM localaapdata me install nahi ho rha hai

**Comment by ultrahacx** [comment]
Its your internet issue. Nothing related with framework whatsoever

**Comment by fghxgf** [comment]
> Its your internet issue. Nothing related with framework whatsoever

network bhi change kar liya
phir bhi work nahi kiya

**Comment by fghxgf** [comment]
![Uploading df.PNG…]()

**Comment by fghxgf** [comment]
![df](https://user-images.githubusercontent.com/71773975/94026989-0103a200-fdd8-11ea-810c-6869d81aa7b0.PNG)

**Comment by bhosalevishu** [comment]
Its not server issue.. its your fivem issue... **(HINDI)** --> ye server ka issue nahi he.. ye tumhara fivem ka issue he.. yaha pe daalke kuch nahi hoga...)

**Comment by fghxgf** [comment]
> Its not server issue.. its your fivem issue... **(HINDI)** --> ye server ka issue nahi he.. ye tumhara fivem ka issue he.. yaha pe daalke kuch nahi hoga...)

bro plz help me

**Comment by TheDaRk69** [comment]
In English, Don't think the language you are speaking is International. And ask this in #help channel, not here. Also read the readme file, follow template...
