### ISSUE TITLE
Vehicle armour is too bad.

### ISSUE THREAD

**Issue by MaximaVoid** [InZidiuZ/op-framework-issue-tracker#1403]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/maximavoid

**Summary:**
So I hit my sandking XL against a wall at around 100 mph and all the tires burst and not only sandking almost every car has this problem. Then my sultan hit against a wall, caught fire and exploded. After this I picked another car which went underground hit against lord knows what and exploded and i died while underground then resurfaced.

**Steps to Reproduce:**
I explained that in summary

**Expected Results:**
Cars should experience some damage. that's it

**Actual Results:**
Car's tires would pop or it would blast immediately after catching fire.

## Additional Information
I encountered another bug, So I bought elegy retro custom today and it exploded by itself while running on road plz do fix that too.

**Screenshots:**
I didnt take screenshots, it happened all at once

**Game Resolution:**
1280 X 720

**Player Data:**
I just turned off my game, cant give you that rn but I can send you a ss if you DM me tommorrow

**Server:**
What server/community did this issue occur in?
server 3 and server 4

**Notes:**
player ID 213 entered benny with garbage truck while i was in with my elegy and I came out and got off my car then he ran me over, but I thought I should give him a warning rather than reporting him.

**Comment by InZidiuZ** [comment]
This is not a bug. Create a balancing issue/suggestion.
