### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by Syndac1995** [InZidiuZ/op-framework-issue-tracker#1404]
When u have a stacked item u can split it by dropping it on the ground pick it up and it will still be on the ground and u can pick it up again and keep it i think u can do it over and over but i didnt try

**Comment by Syndac1995** [comment]
i found this out  with fertilizer  and it also worked with advanced lockpicks i havent found anything else that works so maybe its just those 2

**Comment by InZidiuZ** [comment]
Read the README file
