### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by meetmonpara** [InZidiuZ/op-framework-issue-tracker#1405]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/Meetmonpara/

**Summary:**
Write a short summary of what you are experiencing. I took reskin yesterday in Legacy Roleplay India #1 before update because I accidentally got my face tattooed. After update Joined the server again and the tattoo was still on my face.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results? Tattoo should’ve been removed after reskin

**Actual Results:**
What are the actual results? Tattoo didn’t get removed

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1600 X 1900

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted. https://drive.google.com/file/d/1arfz5V-E9aMjP6FvDx6taFQiEqJNp4zq/view?usp=drivesdk

**Server:**
What server/community did this issue occur in? Legacy Roleplay India #1 (Normal Server)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is not a bug, you'd have to get it manually removed from the database.
