### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by meetmonpara** [InZidiuZ/op-framework-issue-tracker#1406]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Write a summary of what your suggestion is about. New pillbox- 

https://youtu.be/mdfa4hKMtcI

**Reason:**
Why would your suggestion be a good change to the framework? This hospital would be really nice for better roleplay

**Comment by InZidiuZ** [comment]
a) wrong issue tracker and b), do you just assume we have the files for this hospital? (because we don't)
