### ISSUE TITLE
[external/clothing] /delete_all_outfits command

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1407]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
The addition of a /deletealloutfits command.
**Reason:**
Due to the fact I keep breaking everybodies outfits due to adding more streamed clothing, I believe it would be a welcomed addition to add a /deletealloutfits command that allows you to delete all outfits you have saved so you can start fresh and not have to delete every outfit you have saved one by one.

**Comment by bhosalevishu** [comment]
Some additional suggestion to this.. can we add shortcut command like /saveout to save outfit & /delout to delete or something like this... ?

**Comment by InZidiuZ** [comment]
This has now been added.
