### ISSUE TITLE
Paper Bag Bug When Player is Cuffed.

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#1408]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
http://steamcommunity.com/id/vishalbhosale

**Summary:**
If player is cuffed and you wear him a paper bag. Player don't go in FPP View. and When you uncuff player he can go in FPP or TPP views.

**Steps to Reproduce:**
Don't Know

**Expected Results:**
Player should go in FPP View when applied cuff and paper bag at same time.

**Actual Results:**
Player stays in TPP when you apply Cuff and paper bag at same time. 

**Video**

https://youtu.be/5khG2dd-dzo

**Game Resolution:**
1920x1080

**Player Data:**
Logan Petrova Character ID: 386 Job Data: Bars and Club, Bar Jobs, Bar Owner.

**Server:**
Legacy INDIA Whitelisted & Test Server Also

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3167.
