### ISSUE TITLE
[game/jail] /jail changes or /unjail command

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1409]
**Assurance:**
**Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?**
Yes

**Summary:**
**Write a summary of what your suggestion is about.**
Allow the overwriting of sentences with the /jail command or /unjail command which drops the sentence to 0.

**Reason:**
**Why would your suggestion be a good change to the framework?**
Mistakes happen and though rarely it leads to the issue that when jailing sometimes you accidentally sentence them to the incorrect amount and there is no way to fix the issue when that occurs in the server. Both changes don't need to happen just one or the other.

**Comment by KidDano** [comment]
+1 for this, would be nice if you can just overwrite the jail sentence so if you fucked up you can just rejail for the correct time.

**Comment by DaxterPancake** [comment]
I'm going to bump this again because someone hypothetically jailed themselves today instead of a criminal for 107months and couldn't un-jail themselves :)

**Comment by InZidiuZ** [comment]
This has since been added.
