### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by theangrybagel** [InZidiuZ/op-framework-issue-tracker#141]
**Reporter:**
theangrybagel (bob bib)

**Summary:**
Issues with hair colors. It seems like my hair randomly switches colors every few seconds. It could be that other players are changing their own hair colors, and it’s updating other hairs of other people.  

**Steps to Reproduce:**
Just look at your hair. 

## Additional Information

**Game Resolution:**
Fullscreen (1920x1080)

**Notes:**
There’s also an issue with facial hair not appearing, I’ll write a report on that when I’m able to get more info.

**Comment by SteezyRen** [comment]
Are you using a custom character model or a premade civ model?
I had that issue with the civ model but not so much the custom character model.

**Comment by InZidiuZ** [comment]
Hey,

This does indeed happen with some custom character models, as mentioned by @SteezyRen. If you're still having issues with it, ask for a "reskin" in /report, and a staff member will force a reskin for you.

**InZidiuZ**
*OP-FW Developer*
