### ISSUE TITLE
Microphone Bugs - Speaking in “Global Chat”

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#1410]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
DCS281

**Summary:**
While attempting to “view” or listen in on the new microphone “bug”, for around 2-3 seconds, the person that is listening in to the microphone goes into the global voice chat in the server.

**Steps to Reproduce:**
Place the new microphone bug somewhere and attempt to listen in to it. As you are going into the “viewing” of the microphone, you can speak in voice chat and you will be speaking in the “global” voice chat in the server.

**Expected Results:**
The person will be heard by everyone in the server when they speak as they are entering the “listening” mode of the microphone bug.

**Actual Results:**
What was expected.

## Additional Information

**Screenshots:**
N/A

**Game Resolution:**
N/A

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
NA/EU

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue should now be resolved with version 3167.
