### ISSUE TITLE
Bug report - Radio Chop Shop

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1413]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/id/gighulgg/

**Summary:**
When Radio Chop Shop is ordering to bring new car to take them apart for scraps, the radio system is working fine as its refreshing periodically as it should be, BUT JUST 1 of 10 cars were found by me and basing on my experience on other server of Legacy I can ensure you that I know how to find them. They just literally not resp at all. Only one out of 10 which I found is attached to screenshots and it was in a middle of a road, furthermore - it was ghost car and I couldn't enter car whatsoever.  Script is not working. Please have a look, diagnose and fix.
![20200926213036_1](https://user-images.githubusercontent.com/71882732/94350405-4f21db00-004e-11eb-965b-15ac4e0cb00b.jpg)
 
edit<
We found second car on following screenshots - On first screen again car in a middle of a road visible by player. on second screen, other player do not see this car. Please fix.
![one](https://user-images.githubusercontent.com/71882732/94350788-28fe3a00-0052-11eb-9785-0a3383775a18.png)
![two](https://user-images.githubusercontent.com/71882732/94350789-2a2f6700-0052-11eb-9c7d-c2c4e7edbe9b.png)

**Expected Results:**
Fix and make vehicles to be visible and spawning properly. It very important branch of crime income.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
Attached.

**Game Resolution:**
n/a

**Player Data:**
n/a

**Server:**
POLAND EU/NA

**Notes:**
For anything else noteworthy.

**Comment by gighul** [comment]
EDIT: after few restarts, and next day seems working. At least FOR NOW and 2 tries in row

**Comment by gighul** [comment]
Once again its still not working.

**Comment by InZidiuZ** [comment]
See [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1098#issuecomment-647027202).
