### ISSUE TITLE
[game/k9] K-9 Police Dog

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1415]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
/policedog command for police officers. Police dog can smell drugs/find criminals by their smell. Police dog should have ability to put it in the police cruiser and take it out. Police dog should have keybind to attack criminal by aiming gun at the criminal or something.

**Reason:**
Why would your suggestion be a good change to the framework?
It will improve police RP and would be cool to patrol around with dog.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
