### ISSUE TITLE
New colors for police pants.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1416]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add new colors for pants. Right now there is no pants for LSPD (dark-blue) that fits the LSPD shirts. There is blue pants but they don't fit the color the LSPD shirts are.

**Reason:**
Why would your suggestion be a good change to the framework?
Police uniforms would look much better!

**Comment by InZidiuZ** [comment]
Read the README file, this is the wrong issue tracker for assets
