### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by SirPiff** [InZidiuZ/op-framework-issue-tracker#1417]
Many people have experienced this from what I know, I'm unsure if you are aware of the issue, so I decided to post it here - trunks/gloveboxes or general inventory movement doesn't seem to save properly, I'm not sure how to re-create it, but so far I've had this issue with trunks mostly.

I put in 12 bags of weed into my motorbike earlier today, they poofed after a while (it didn't get stolen, as I had been next to it for the whole time.)

I'm unsure of what causes this issue, but I know a lot of people I know have experienced this. I hope you can figure it out and fix it. thank you!

**Comment by InZidiuZ** [comment]
Read the README file (this should be resolved with latest versions, though)
