### ISSUE TITLE
Suggestion new selling system for PDM

### ISSUE THREAD

**Issue by DEADLYZOB** [InZidiuZ/op-framework-issue-tracker#1418]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Summary:**
In this new selling system if anyone want to buy car he need one PDM salesman . without PDM he can't buy car because only PDM salesmans has power to sell car like he will sell car with /sellcar (server id or cid id) (slot id) (commission) 

**Reason:**
In asia server like in Indian subdivision we spawn car on slot id 1 in city 1 then that car will also spawn in slot 1 in city 2 then what happened is some players buy car in other server without commission and many new players come in PDM if one PDM salesman is showing car to anyone then what happened is he buys car and run . so this new system will totally finish this problem 

Why would your suggestion be a good change to the framework?
Many server has same selling system if this framework make this system possible than framework can share this system with other server also or may be your server will be first to make this thing possible .

**Comment by InZidiuZ** [comment]
This will not be added at this time. In the future, vehicles in a dealership will be server-specific, so then that issue shouldn't occur.
