### ISSUE TITLE
[game/voice] Issues regarding the current voice system. 

### ISSUE THREAD

**Issue by LikeConnorr** [InZidiuZ/op-framework-issue-tracker#1419]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes, I have read through `README.md`**

**Player Identification:**
What is your steam profile?
**https://steamcommunity.com/profiles/76561198142268064/**

**Summary:**
**Issue 1:**
The current voice system seems to cut out and lag at random intervals. It will either become extremely glitchy, or you won't be able to hear someone whatsoever (regardless of their distance from you). This cannot be fixed by switching between whisper, normal, and shouting. This cannot be fixed by re-logging, though sometimes may help it temporarily. 

**Issue 2:**
The current voice system when using a radio seems to cut out and lag at random intervals. It will either become extremely glitchy, or you won't be able to hear someone whatsoever (regardless of their distance from you). This cannot be fixed by switching between whisper, normal, and shouting. This cannot be fixed by re-logging, though sometimes may help it temporarily. This cannot be fixed by changing radio volume and/or sounds.

**Issue 3:**
The current voice system when using a phone seems to cut out and lag at random intervals. It will either become extremely glitchy, or you won't be able to hear someone whatsoever (regardless of their distance from you). This cannot be fixed by switching between whisper, normal, and shouting. This cannot be fixed by re-logging, though sometimes may help it temporarily. 

**Steps to Reproduce:**
**Issue 1:**
A. Stand near an individual or a group of individuals. 
B. Communicate with each other, ensure to move around and switch between whisper, normal, and shouting **(Not Always Necessary)**.
C. Hear results

**Issue 2:**
A. Go away from an individual or a group of individuals.
B. Communicate with each other using the radio, ensure to move around and switch between whisper, normal, and shouting **(Not Always Necessary)**. 
C. Hear results

**Issue 3:**
A. Go away from an individual or a group of individuals.
B. Communicate with each other using the mobile phone (calling them), ensure to move around and switch between whisper, normal, and shouting **(Not Always Necessary)**.
C. Hear results

**Expected Results:**
**Issue 1, 2 & 3:**
All individuals should be able to hear each other without having to turn their in-game voice on/off or re-logging. When leaving a radio channel, you should not hear communications within that radio anymore.

**Actual Results:**
**Issue 1:**
Individuals with often cut out or you won't be able to hear them at all until vigorous position and microphone adjustments. This does not always fix it. 

**Issue 2:**
Individuals with often cut out or you won't be able to hear them at all until vigorous microphone adjustments. You'll often still be able to hear the radio clicks, but no voices. If the voices are working per usual, you'll often hear everyone on the radio frequency even if you leave the frequency. **(Not sure about dropping the radio or turning the volume to 0)**. The radio also has a habit of cutting out others' voices when driving at high speeds, though this is extremely minor. 

**Issue 3:**
Individuals with often cut out or you won't be able to hear them at all until vigorous microphone adjustments. The call doesn't end, it just remains silent until one of the individuals fixes their issues and re-dials. 

## Additional Information

**Screenshots:**
Can't seem to locate any errors, the bug report pop-up has not shown either.

**Game Resolution:**
1920x1080

**Player Data:**
This bug is global across all characters. Almost all EU/NA1 players have experienced this a lot or not so much recently. 

**Server:**
Legacy Roleplay EU/NA1 - Most likely happening in the other servers providing that they utilize the same voice system.

**Notes:**
This was not so much of an issue when mumble was first introduced, therefore this must be due to recent changes.

**Comment by DaxterPancake** [comment]
I've noticed that every now and again my voice chat will just completely stop working. One second people can hear me and the next they can't. Usually it is fixed by turning my voice chat on and off again. I don't know if this is a me thing or an issue with our current voice script.

**Comment by InZidiuZ** [comment]
Looking at the 3 issues mentioned, I believe this very possibly won't be in my hands & rather FiveM's.

Hitching voices/voice lag is usually seen when there's packet loss present on either the sender or the target's client. I suspect some people have a lot of these issues because of a bad connection as others seem to be mostly fine and unaffected by this, including me. Please do come with information on what your PL status is when these issues occur. (type `cl_drawPerf 1` in the F8 console to show packet loss.)

There could be some issues on how voice-levels are set on players when using the phone and radio which *could* cause some mishaps, though I somewhat doubt that.

Though there is one system that could have a direct effect on the voice system which I'll disable on the EU/NA server for the upcoming restart (the restart happening right now) & we can see if these issues become less frequent or if they continue as previously. (if they continue as normally it's likely out of my control)

As I said previously, I haven't had many issues like this myself, so please do come with more information here.

**Comment by InZidiuZ** [comment]
I doubt that'd be an issue with our voice system, @DaxterPancake.

**Comment by jethiya** [comment]
> I've noticed that every now and again my voice chat will just completely stop working. One second people can hear me and the next they can't. Usually it is fixed by turning my voice chat on and off again. I don't know if this is a me thing or an issue with our current voice script.

Its more or less a global issue. Mostly faced by players with high pings.

**Comment by DaxterPancake** [comment]
I get 300ms+ and I have never had an issue with laggy voice or anything, just with the damn voice chat turning off sometimes.
Makes no sense to me.

**Comment by AdeptCL** [comment]
The voice turning off (although on in the settings) is common with myself too. It usually brings back to life after a few refreshes of turning it off and back on. However, I am needing to do this at least once every 15-20 minutes.

**Comment by LikeConnorr** [comment]
> Looking at the 3 issues mentioned, I believe this very possibly won't be in my hands & rather FiveM's.
> 
> Hitching voices/voice lag is usually seen when there's packet loss present on either the sender or the target's client. I suspect some people have a lot of these issues because of a bad connection as others seem to be mostly fine and unaffected by this, including me. Please do come with information on what your PL status is when these issues occur. (type `cl_drawPerf 1` in the F8 console to show packet loss.)
> 
> There could be some issues on how voice-levels are set on players when using the phone and radio which _could_ cause some mishaps, though I somewhat doubt that.
> 
> Though there is one system that could have a direct effect on the voice system which I'll disable on the EU/NA server for the upcoming restart (the restart happening right now) & we can see if these issues become less frequent or if they continue as previously. (if they continue as normally it's likely out of my control)
> 
> As I said previously, I haven't had many issues like this myself, so please do come with more information here.

I have experienced this issue today with voice & phone calls while performance stats reading 31ms.

**Comment by InZidiuZ** [comment]
I never suggested it was a ping issue... packet loss is something completely different.

**Comment by LikeConnorr** [comment]
> I never suggested it was a ping issue... packet loss is something completely different.

I only saw PC related specs and ping when looking at what you told me, only just looked back and realized it does say packet loss too. Floats between 1 & 2% with or without the issue. Not sure if that's bad or good.

**Comment by InZidiuZ** [comment]
Yea... at 1-2% PL is usually when voice hitching starts to occur from what I've seen from others,

**Comment by LikeConnorr** [comment]
> Yea... at 1-2% PL is usually when voice hitching starts to occur from what I've seen from others,

I honestly don't think it's packet loss causing it, most likely a FiveM update then. I & others had no issues after you changed to the in-game voice, and the problems have started occurring only very recently.

**Comment by InZidiuZ** [comment]
PL causing voice hitching has been a thing since before we started using Mumble.

**Comment by LikeConnorr** [comment]
> PL causing voice hitching has been a thing since before we started using Mumble.

Understandable, but this seems much worse. The voice chat rarely lags, you just can't hear anyone completely until re-logging or playing around with your voice settings.

**Comment by InZidiuZ** [comment]
We haven't made any changes to it in a long time, so either FiveM made some changes that caused this or your internet started having issues causing PL, perhaps? Personally, I haven't seen any changes in the voice quality/stability, though it should also be noted I don't use it much.

**Comment by InZidiuZ** [comment]
A few days ago an issue causing the players talking on the radio as the radio is turned off to not stop being heard was resolved. About a week ago a system that splits players into separate voice channels was also disabled.

Has anyone noticed any improvements?

I'm wanting to bring back the channel-splitting system as I believe that lowers network usage.

**Comment by Masik52** [comment]
The only thing I’ve noticed is at times when I turn my radio off or change frequency I will still hear the old frequency and it requires a soft log to fix it.

**Comment by novapurple** [comment]
I know, I have issues talking on the phone with certain people but can talk to them in person or on radio perfectly fine. Also a lot of the times they can’t seem to hear me unless I turn my voice chat on and off about 2-3 Tim’s

**Comment by InZidiuZ** [comment]
I've sorted the issue you described in version 3219 with the switching to another frequency, @Masik52. I also got some other minor issues resolved which probably would've caused problems at times.

**Comment by InZidiuZ** [comment]
I'll be closing this as there doesn't seem to be any more specific issues besides the voice hitching and having to 'reset' your voice at times, though that's probably two things not up to me to resolve.
