### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1420]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
The /revive is only working for you it doesn't revive other people when you try to revive someone else with 
**"/revive [Server ID] [Injury]** then it will revive only yourself, not someone else. I have also tried to revive the whole server thing with **-1** that too will only revive yourself & will remove your injury.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I think you forgot to add the server ID thing instead of added injury placement in place of the server ID.

**Expected Results:**
What are the expected results?
When we do **/revive 2 1** then the person with server ID 2 should be revived with no injury & -1 should revive the whole server.

**Comment by InZidiuZ** [comment]
This issue should be resolved with version 3168.
