### ISSUE TITLE
[game/admin_command] - revive command.

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1421]
**Summary:**
After tonight's update there was several things changes and there is a problem, I have assigned highest possible roles to my account and I cannot /revive anyone. Command basically is no longer an option in menu. Please kindly have a look.

**Expected Results:**
Restore command.

**Screenshots:**
![1](https://user-images.githubusercontent.com/71882732/94681510-e07d9f80-0323-11eb-9c5d-8a4c1758810e.png)

**Server:**
POLAND eu/na

**Comment by Nuziatella** [comment]
#1420 

This issue should be resolved with version 3168.
