### ISSUE TITLE
[jobs/mechanic] Material Computer for Sandy Shores Mechanic Shop.

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/op-framework-issue-tracker#1422]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes.**

**Summary:**
Write a summary of what your suggestion is about.
**Adding a Material Computer to the Mechanic Shop in Sandy Shores.**

**Reason:**
Why would your suggestion be a good change to the framework?
**Currently there isn't a Material Computer in the Mechanic Shop in Sandy Shores unlike the other Mechanic Shops in the city. Adding a Material Computer would help the Mechanics that want to work in Sandy Shores from packing all the Materials with them for every repair hoping they have enough materials to do the job.**

**Comment by KookieNCoffee1** [comment]
+1 This would be very beneficial to be able to properly use the mechanic shop in Sandy Shores - I think it would be good if there was also an ATM placed inside, if possible.

**Comment by InZidiuZ** [comment]
This has since been added.
