### ISSUE TITLE
[game/commands] ingame commands not working (Missing locale)

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1423]
**Summary:**
Commands /try , /dice , /card are not working correctly. When used there are "missing locale" errors. It was not working from the beginning.
When I changed language in game to /language en-US - there was option to revive but all polish translated ones was deleted obviously. Please kindly have a look and fix /language pl-Pl language codec.

**Expected Results:**
Fix mentioned commands: 
/dice (polish translation is server /kostka)
/try
/card (polish translation in server /karta)

**Screenshots:**
Try:
![dice](https://user-images.githubusercontent.com/71882732/94729402-e4301700-0361-11eb-8d26-340db84b5f50.png)
Dice:
![kostka](https://user-images.githubusercontent.com/71882732/94729429-edb97f00-0361-11eb-9545-40c5a40a34f1.png)
Card:
![karta](https://user-images.githubusercontent.com/71882732/94729442-f5792380-0361-11eb-97de-c40a55ca355e.png)

**Server:**
POLAND EU/NA

**Comment by InZidiuZ** [comment]
You have to create a PR and update the pl-PL language file on the [op-framework-public](https://github.com/InZidiuZ/op-framework-public) repository. You can find more information in [this discord message](https://discordapp.com/channels/618449264271687682/756914166425583656/756917126249316502).
