### ISSUE TITLE
[POLICE] Spike strips

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1424]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add spike strips to police. Buy a spike strip from the police armory and it's deployable/undeployable for once. 

**Reason:**
Why would your suggestion be a good change to the framework?
Improve rp and would be cool to stop vehicles with spike strips.

**Comment by InZidiuZ** [comment]
This is already a thing. Do `/spawnobject spike` as police to spawn.
