### ISSUE TITLE
[game/inventory] Can't shoot while you are using some specific items

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#1425]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yeah

**Summary:**
That players can't shoot while they doing specifics actions. Like while they put on a vest, healing (IFAK or medikit) and others.

**Reason:**
Because some people use this to their advantage (especially in drive-bys) to do PG and keep shooting while doing these actions. This would avoid the use of these items consecutively (spamming), through the hotkey.

**Comment by InZidiuZ** [comment]
I just tested locally & from what I can see, you're already unable to shoot while using said items.

**Comment by Igna28** [comment]
You're right, you can't shoot while using medikit and IFAK, but with the vest you can: https://streamable.com/hzofg2

**Comment by InZidiuZ** [comment]
This has now been resolved with version 3185.
