### ISSUE TITLE
[jobs/police] /CPR for PD

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1426]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
/CPR for PD
**Reason:**
Why would your suggestion be a good change to the framework?
This would be good for use for PD that is "medically certified when there is no EMS on duty to help up suspects or anyone else that may need to be treated, of course, this would be regulated to where you cannot use this command unless you are medically certified by Pillbox Medical for "CPR" Would provide good RP with people going to pillbox and Cops and EMS interacting with each other and EMS certifying officers for CPR use on the field.

**Comment by novapurple** [comment]
> /e cpr

This was referring to a command that would actually pick the person up. Not an animation.

**Comment by twooot** [comment]
PD has /cpr
