### ISSUE TITLE
in normal servers of indian division people are facing soo much lag and High Ping issues , you should change it to singapore please . or you can change it to 64 slots again i request you because people are leaving servers because of these things .

### ISSUE THREAD

**Issue by anaydixit** [InZidiuZ/op-framework-issue-tracker#1427]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by InZidiuZ** [comment]
Read the README file
