### ISSUE TITLE
Error Report Bug 

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1429]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/id/avilashsengupta/

**Summary:**
After this error report dialog box (which will be provided below) keys for the doors (as EMS/PD) and vehicles stop working. You cannot pass vehicle keys nor lock/unlock your vehicle and same goes with door system as well. 

Screenshot - https://ibb.co/YBd19vz

**Steps to Reproduce:**
try the above mentioned actions after the error report 

**Expected Results:**
Mentioned actions should work properly 

**Actual Results:**
They stop working after the repro.

**Comment by InZidiuZ** [comment]
What exactly is the repro here? 🤔

**Comment by Nuziatella** [comment]
Just by sitting around the area of pillbox. Though what they are not showing and I'll try to grab a screenshot of it is the console error which points to an issue with the tram. This error pops up generally in any area of the tram and is random. Though seems to occur if you afk near the area for an extended period of time

**Comment by InZidiuZ** [comment]
I've added some debugging with version 3201 which will include information as to when the native causing issues is being called. I have suspicion this *could* be a GTA/FiveM issue. If you get this error again, please check your F8 console and see if you can find the error in between a 'setting cruise speed' and 'finished setting cruise speed' trace. (or even just a 'setting' then an error with no finish.)

The traces look like [this](https://gyazo.com/57ce50acdeb09190ec4c0aae6c93d1d1).

**Comment by InZidiuZ** [comment]
Has anyone managed to capture anything?

**Comment by InZidiuZ** [comment]
I'll be closing this and removing the traces again as there hasn't been anything reported.
