### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YNGhost** [InZidiuZ/op-framework-issue-tracker#143]
**Name:**
YNghost
 I YNghost#5765
**Summary:**

Having the PD can track the car license plate auto readable without doing checkplate 
**Reason:**

This is good for everyone in PD and makes PD member life easy

**Comment by InZidiuZ** [comment]
>Having the PD can track the car license plate auto readable without doing checkplate

Huh?

**Comment by YNGhost** [comment]
I meant to say was scan the vehicle plate, when we have the radar activated and behind a vehicle such as in this screenshot https://gyazo.com/2dfcc469038543973e2f3d4a5a37feaa

**Comment by InZidiuZ** [comment]
/checkplate won't be directly related to the radar, the radar only does speed, etc., it doesn't have a database & not planning to create one for it, so will close this.
