### ISSUE TITLE
Bug report | Can't connect to legacy Bangladesh| Resources are not downloading.

### ISSUE THREAD

**Issue by darkness96240** [InZidiuZ/op-framework-issue-tracker#1431]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198994558226/
**Summary:**
Write a short summary of what you are experiencing.
When connecting to Legacy Bangladesh resources aren't  downloading. Tried with ip. Bcz of this issue people are invisible to some people in the server. This is not happening on other sub divisions.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Join Legacy Bangladesh without any cache.
**Expected Results:**
What are the expected results?
Resources should download.
**Actual Results:**
What are the actual results?
Resources are not downloading 
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://media.discordapp.net/attachments/715256124731031592/762223685208768542/Screenshot_557.png?width=845&height=475

https://media.discordapp.net/attachments/677897821617258496/762227433004859422/unknown.png?width=845&height=475
**Game Resolution:**
What is your game's resolution?
1920×1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Bangladesh 
**Notes:**
For anything else noteworthy.
This is experienced by most of the players of the server.

**Comment by MRALPHA10** [comment]
+1 Same Issue

**Comment by DrCrazyBDYT** [comment]
+1 Same issue

**Comment by SantoOp** [comment]
+1 Same issue

**Comment by InZidiuZ** [comment]
This is not related to the framework.
