### ISSUE TITLE
/frequency Command Substitute

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1434]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
The **/frequency Command]** Can or If Possible We Should  Have a Substitute for the Same Like [ /freq or /radio ]  

**Reason:**
Why would your suggestion be a good change to the framework?
It Might Get Some Time Like If You Are Having in a RP Situation And Need To Quickly Connect Via Talking It Would Be Beneficial

**Comment by DaxterPancake** [comment]
I'd like /freq as I can't spell frequency half the time :)

**Comment by InZidiuZ** [comment]
I've added '/freq' as a substitute on the en-US language file.
