### ISSUE TITLE
[animations/emotes] /tightencuffs /tc Suggestion

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#1435]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

After gathering some other opinions about a post I made in the #police-sugggestions channel on discord, ( http://prntscr.com/utpv87 ) I'm proposing a /tightencuffs and /tc (shortcut) command. The way this would work is if a suspect is /softcuff or /sc 'ed and an officer now feels the need to shackle the person still (/hardcuff /hc), Instead of having to uncuff them then /hardcuff after, make it to where if you're in a close enough range to the suspect and they are staying still/walking slowly near you then you can /tc on them, which would change them from the soft cuffed state to a hard cuffed state.

**Reason:**
Why would your suggestion be a good change to the framework?

I feel this would be a good change to the framework simply because it just seems realistic and plausible. I really don't feel this would negatively affect anyone who might be getting placed in cuffs either. Since it's still possible to switch from soft cuffs to hard cuffs without them getting away in the first place. This would basically just be adding shackles as well.

**Comment by twooot** [comment]
This isn't an issue anymore since you can hardcuff sofcuffed people
