### ISSUE TITLE
[jobs/ems] /drugtest command should be able to use by EMS

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1436]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
If A EMS Is Having Some Session Like Giving Therapy Or Treating Someone Should Also be Able To Do /drugtest To Check Whether the Patient Is Alcoholic Or Have Taken Some Drugs Recently.
**Reason:**
Why would your suggestion be a good change to the framework?
Like The Police Checks Someone For Consuming Drugs Same EMS Should Be Able To Check To Confirm Is The Patient Need Some Kind Of Treatment For The Same.

**Comment by T4NZIM** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
