### ISSUE TITLE
Keybind issue

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1437]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Kodetops/

**Summary:**
Write a short summary of what you are experiencing.
Many players can't save keybindings on my server. Other servers allow to save keybinds.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Change and then save keybindings.

**Expected Results:**
What are the expected results?
It to save the keybinds.

**Actual Results:**
What are the actual results?
Error, Not allowing to save them.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Estonia Legacy

**Notes:**
For anything else noteworthy.
Players can save keybinds on another servers but not on Legacy Estonia

**Comment by InZidiuZ** [comment]
> Change and then save keybindings.

Could you be a bit more specific on how to reproduce this? As far as I know there isn't any 'saving', it's all done in the background.

> Error, Not allowing to save them.

'error'?

**Comment by glocknine234** [comment]
To reproduce this issue I need to change keybinds and save them in settings.

No error, Just message that inputs are unbound and can't save them.

**Comment by InZidiuZ** [comment]
I suppose you're referring to GTA keybinds then? And not the actual /command_bind* commands added by our framework?

**Comment by glocknine234** [comment]
Yes, GTA keybinds.

**Comment by InZidiuZ** [comment]
The OP Framework does nothing to the default GTA keybinds. It could've been because of the 2060 build being enabled, though that is no longer the case so it might be resolved now.

**Comment by glocknine234** [comment]
Yea probably.
