### ISSUE TITLE
Can't chop shop/sell cocaine.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1438]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Kodetops/

**Summary:**
Write a short summary of what you are experiencing.
Can't chop shop or sell cocaine.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Sell cocaine or chop shop.

**Expected Results:**
What are the expected results?
Able to sell the cocaine.

**Actual Results:**
What are the actual results?
Not allowing to sell cocaine.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Estonia Legacy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read over the README file again
