### ISSUE TITLE
[jobs/vanilla_unicorn] Add Dressing Room to the Vanilla Unicorn

### ISSUE THREAD

**Issue by Poetiics** [InZidiuZ/op-framework-issue-tracker#1439]
Name:
Baby Driver (Owner of Vanilla Unicorn)
Poetiics#7119

Summary:
Write a short summary of what your suggestion is about.

We'd like to see a clothing location added in the back changing room of the vanilla unicorn for dancers

Link:
Here is an image of the actual dressing room at the VU
![image](https://user-images.githubusercontent.com/72463964/95238210-2e3c5100-07d7-11eb-9d1a-85febaed3afa.png)

Reason:
It will create a more natural role playing feel for the dancers, security, and bartenders to meet at the club and get in uniform before events.

**Comment by InZidiuZ** [comment]
This has since been done.
