### ISSUE TITLE
Bug report| No Recoil in This Camera mode.

### ISSUE THREAD

**Issue by darkness96240** [InZidiuZ/op-framework-issue-tracker#1440]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198994558226/
**Summary:**
Write a short summary of what you are experiencing.
I am not sure if this is a op-fw issue or not.
If you enable this settings>Camera>First Person vehicle hood>On 
You will experience no recoil in any of the gun in FPP mode.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Enable settings>Camera>First Person vehicle hood>On and shoot any gun in FPP
**Expected Results:**
What are the expected results?
There should be recoil on the gun.
**Actual Results:**
What are the actual results?
No recoil on any guns.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://imgur.com/MGbCyrQ
**Game Resolution:**
What is your game's resolution?
1366x768
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
n/a
**Server:**
What server/community did this issue occur in?
Test Server/Live servers
**Notes:**
For anything else noteworthy.

**Comment by darkness96240** [comment]
can i get a reply?

**Comment by InZidiuZ** [comment]
I tried reproducing with the 'First Person Vehicle Hood' option enabled, but I was not able to find any differences with the recoil.

**Comment by InZidiuZ** [comment]
Closing due to no response
