### ISSUE TITLE
[base/commands] Command bind

### ISSUE THREAD

**Issue by TheDaRk69** [InZidiuZ/op-framework-issue-tracker#1441]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
The new added command bind is actually great. But the problem is I binded carry to PAGE UP and . When I open the map and press PAGE UP to zoom in the map, if someone is nearby me gets carried. So my suggestion is when we press pause menu, the command bind shouldn't work

**Reason:**
Why would your suggestion be a good change to the framework?
This will prevent activating commands while we are in the pause menu

**Comment by InZidiuZ** [comment]
This has now been done with version 3488.
