### ISSUE TITLE
[?] Adding a changing/clothing closet in PDM

### ISSUE THREAD

**Issue by VaydeHunt** [InZidiuZ/op-framework-issue-tracker#1442]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Summary:
Write a summary of what your suggestion is about.
Adding a changing area in PDM would help a lot of people who are out and about doing other errands/activities come in and easily change.  If I'm doing other stuff but want to clock in to sell it's easier to be able to have a fitting room & change instead of driving to the nearest clothing store/closet.

Reason:
Why would your suggestion be a good change to the framework?
This will insure players to be properly dressed and have a better time working here at PDM!

**Comment by twooot** [comment]
Done. Only took about 1 year
