### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zonaG** [InZidiuZ/op-framework-issue-tracker#1443]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
The Vagos would like a simple mechanic computer located on the east side in La Mesa sector. I have added images of the location via the link below.We are wanting to buy parts and repair vehicles there.  [http://imgur.com/a/ur8S72I](http://imgur.com/a/ur8S72I) 

**Reason:**
Having more mechanic shops and businesses would add to roleplay and make competition between the mechanic shops.

**Comment by bhosalevishu** [comment]
Link to this Mod: https://www.gta5-mods.com/maps/vagos-savehouse-1-0-0-mlo

**Comment by zonaG** [comment]
Yes! Thats exactly what we are looking to getSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Vishal Bhosale <notifications@github.com> Date: 10/9/20  12:49 PM  (GMT-07:00) To: InZidiuZ/op-framework-issue-tracker <op-framework-issue-tracker@noreply.github.com> Cc: zonaG <angelhernandez6699@gmail.com>, Author <author@noreply.github.com> Subject: Re: [InZidiuZ/op-framework-issue-tracker] Suggestion (#1443) 
Link to this Mod: https://www.gta5-mods.com/maps/vagos-savehouse-1-0-0-mlo

**Comment by DaxterPancake** [comment]
This is in the wrong tracker, this should be in the asset tracker which is located [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
