### ISSUE TITLE
[game/racing] Checkpoint Racing System

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1444]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I was thinking if we can get the Checkpoint and Lap Racing System would be very good 
Eg:- https://github.com/Artnod-FiveM-Mods/esx_races
**Reason:**
Why would your suggestion be a good change to the framework?
Bcz Everyone Love to Race and its increase illegal race and all which will increase more RP

**Comment by twooot** [comment]
We have a racing script now
