### ISSUE TITLE
Personal car getting freezed

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1446]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
So this started after the new patch came today (for me) when we take out our personal vehicle from the garage then it gets freeze in one place we can't drive it or sometimes store it back into the garage we can't even give the keys to somebody else & sometimes can't even unlock or lock the vehicle even though the vehicle is in front of me, sometimes while driving it also it gets froze

**Expected Results:**
What are the expected results?
The vehicle should not be frozen in one place.

**Server:**
What server/community did this issue occur in?
India Whitelis

**Comment by KaiEagle** [comment]
& one more thing not able to give keys even though I have the keys on me it shows **No nearby vehicle found**.

**Comment by KaiEagle** [comment]
not able to open the doors of the vehicle too from outside.

**Comment by cwisdasaur** [comment]
I've personally been experience the same issue very recently in NA/EU unfortunately.  I've also met others with the same problem. Vehicle is inoperable even after being /tow(ed).  Only fix I found was towing the vehicle to a garage and storing it or having it impounded.

**Comment by RobinWell** [comment]
To resolve this issue, we as staff have had to get in the driver seat, and noclip with the vehicle, have it hover over the ground, and drop it down. It seems like the vehicle sinks underneath the ground, which results it in getting stuck.

**Comment by KaiEagle** [comment]
> To resolve this issue, we as staff have had to get in the driver seat, and noclip with the vehicle, have it hover over the ground, and drop it down. It seems like the vehicle sinks underneath the ground, which results it in getting stuck.

You can just set the person who is in driving seat to Unfrozen :|

**Comment by InZidiuZ** [comment]
I believe this is no longer an issue and if it was, it would've been FiveM-related. Feel free to create another issue or reopen this one if it is still a consistent issue, though.
