### ISSUE TITLE
[Ingame/commands] disappearing /me /do /description commands + crashing police cars.

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1447]
**Summary:**
While beta testing server before go live we encountered an major issue that we cannot resolve or find solution to avoid ourselves. Namely, when we were just staying on various locations on map just randomly narrative commands such as:
/me /do /description just disappears. Like you can use them but they are not visible on screen. Its problematic since only reconnect helps to get it working again and I am afraid that when we go live people will get irritated and wont play anymore.

Also just entering police cars (not every time) randomly crashes all people in sight. I have been told that its problem because of FiveM update and cant be helped but I didnt hear about problem with it on Indian server for instance so why it happens on polish one. 

With both these critical problems the overall opinion on server start may cause irreversible bad opinion which may end up in reduced amount of players.

**Expected Results:**
Analyse screenshot that appears on screen when commands stops working and provide solution/adjust script.

## Additional Information

**Screenshots:**
Screenshot is regarding the problem with narrative commands.
Crashes regarding the police cars just freeze FiveM and close it.
![image_2020-10-11_180506](https://user-images.githubusercontent.com/71882732/95683542-4acbf500-0bec-11eb-8e1b-c57db82ef3d2.png)

**Server:**
POLAND EU/NA

**Comment by InZidiuZ** [comment]
Read the README file
