### ISSUE TITLE
[INGAME/COMMANDS] narrative commands.

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1448]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/id/gighulgg/

**Summary:**
While beta testing server before go live we encountered an major issue that we cannot resolve or find solution to avoid ourselves. Namely, when we were just staying on various locations on map just randomly narrative commands such as:
/me /do /description just disappears. Like you can use them but they are not visible on screen. Its problematic since only reconnect helps to get it working again and I am afraid that when we go live people will get irritated and wont play anymore.
The problem is accompanied by the error listed in the screenshot, we have tried to get an idea how to solve it without re log (re log helps but unfortunately it can happen again in next 2 minutes or 30 minutes or so). We were testing in with 10 people at most online and sometimes it happens even when I am alone at server. 
Please kindly advise us and help cause if we go live next week (as we wanted to) and players will encounter such inconvenience I truly believe they wont be happy and encouraged to play with us anymore.

**Steps to Reproduce:**
There is no clear cause, circumstances or location for this problem to occur.

**Expected Results:**
For everyone around to be able to see narrative commands above each character.

**Actual Results:**
When someone have used (for instance):
"/description hat is red" other players do not see it
"/me picking up the hat from floor" other players do not see it
"/do hat is on the floor" other players do not see it

## Additional Information

**Screenshots:**
![globalfuctions](https://user-images.githubusercontent.com/71882732/95761938-53d0cb00-0cad-11eb-87a1-193c6e79f51c.png)

**Server:**
Poland NA/EU

**Comment by gighul** [comment]
Same error happened multiple times from SQL database
![image_2020-10-12_182601](https://user-images.githubusercontent.com/71882732/95769568-613f8280-0cb8-11eb-8efd-abc0bbfbd7b4.png)

**Comment by gighul** [comment]
Another example regarding it.
1) connecting to server as always, choosing character. 
![loading](https://user-images.githubusercontent.com/71882732/95793065-0e2ff480-0ce5-11eb-98cd-e8e9d4d64960.png)
2) I tried twice to connect, firstly at interior of police station at paleto bay (attached error appears immediately) then I went outside interior, reconnected and for like 10 seconds all was fine, I went into interior through door and again same error
![image_2020-10-12_234731](https://user-images.githubusercontent.com/71882732/95793164-4afbeb80-0ce5-11eb-8bb0-3e2c0cfe8a6a.png)
To be clear, this error do not close FiveM, but when it appears you cannot see any narrative commands from players or yourself

**Comment by gighul** [comment]
Found an repro pattern how to trigger issue.
Plain and simple, when you login and approach people with description / me / do you get this every time
There is no added recorded scene when we logged in and others do not had description - in that scenario there was no bug.
Additionally, people that was already in server and they played for a while with each other, set /description and while seeing each other for a quite time did not receive error. Only person that is recording was crashed multiple times.
https://youtu.be/l6leIqK9GJA

**Comment by InZidiuZ** [comment]
This issue has now been resolved
