### ISSUE TITLE
OneSync Force Respawn

### ISSUE THREAD

**Issue by Clorox54** [InZidiuZ/op-framework-issue-tracker#145]
**Reporter:**
Who is reporting this? Please include discord name.
Clorox
**Summary:**
Write a short summary of what you're experiencing.
I have had three instances today where players games crash or they log out and when they return they have been force re spawned at the hospital. Seems that each case happened on a one sync server.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Unknown
**Expected Results:**
What are the expected results?
N/A
**Actual Results:**
What are the actual results?
N/A
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
Unknown
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Unknown
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

After investigating this, it seems I miss-managed some variables which would prevent the database from updating a player's current "death" state to false when receiving CPR. This has now been sorted and should be fixed after next patch. Don't believe this was OneSync-related.

**InZidiuZ**
*OP-FW Developer*
