### ISSUE TITLE
increase normal jobs for make server's more interesting .

### ISSUE THREAD

**Issue by anaydixit** [InZidiuZ/op-framework-issue-tracker#1450]
You should increase some normal jobs in the servers from that server will become more interesting as players will have more things to explore .

**Comment by KingsINSANE** [comment]
True, after some times these jobs are kinda boring

**Comment by KingsINSANE** [comment]
Try to add some more business like clothing stores or food truck or resturant, pharmacy and thing like we can earn some money and live like real

**Comment by InZidiuZ** [comment]
Read the README file
