### ISSUE TITLE
[?] Add new store type/ Black Market?

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1452]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I think it would be a good idea to make a separate location that does not have a blimp, and classify it as a black market kinda thing. Remove some of the items from the tool store we currently have and bring them over to this store instead. You can even add even crazier things down the line that would obviously never be in real store in a normal world. Items that could be included 
Handcuffs 
Body armor 
Ejector seat
Etc.
**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by cwisdasaur** [comment]
None of the things you listed are contraband that would require a black market. People usually traffic illegal goods on the black market for cash.  Any unpermitted drug or weapon sale are examples of a black markets that currently exist in city.

**Comment by novapurple** [comment]
The black market is just a name because some of these items don’t fit inside reality if being inside of a tool store. And with these being put into such a place they then would be illegal. Just gives people another location to go and buy things other than the tool shop in grove they have been to a million times.

**Comment by AdeptCL** [comment]
I like the idea of a black market, with removing some of the more discreet items from the toolshop and adding them elsewhere.

Maybe the black market could have items like handcuffs, adv lockpicks, armour, ammo (at a slightly cheaper price)? This would also be somewhere without tax due to the pricing of some of these items anyways.

**Comment by novapurple** [comment]
> I like the idea of a black market, with removing some of the more discreet items from the toolshop and adding them elsewhere.
> 
> Maybe the black market could have items like handcuffs, adv lockpicks, armour, ammo (at a slightly cheaper price)? This would also be somewhere without tax due to the pricing of some of these items anyways.

Especially ammo. It dosnet make any sense why we can’t have rifles but yet we can casually buy the ammo for it 😂

**Comment by AdeptCL** [comment]
> I like the idea of a black market, with removing some of the more discreet items from the toolshop and adding them elsewhere.
> 
> Maybe the black market could have items like handcuffs, adv lockpicks, armour, ammo (at a slightly cheaper price)? This would also be somewhere without tax due to the pricing of some of these items anyways.

Following on from this, depending on how difficult it may be to do it, the "black market" location could change maybe once a month? There are so many discreet locations especially in the alleyways of Vinewood/Rockford. There are also some locations which could be used in Sandy/Grapeseed too.

**Comment by cwisdasaur** [comment]
The black in black market stands for illegal.  "Ex The adjective 'Black' refers to shady or illegal dealings in said rations. Ergo, the black market is actually an entire economy unto itself." The market location idea is neat tho, kind of reminds me of Jabba's place or Califorinia.

**Comment by cwisdasaur** [comment]
> > I like the idea of a black market, with removing some of the more discreet items from the toolshop and adding them elsewhere.
> > Maybe the black market could have items like handcuffs, adv lockpicks, armour, ammo (at a slightly cheaper price)? This would also be somewhere without tax due to the pricing of some of these items anyways.
> 
> Following on from this, depending on how difficult it may be to do it, the "black market" location could change maybe once a month? There are so many discreet locations especially in the alleyways of Vinewood/Rockford. There are also some locations which could be used in Sandy/Grapeseed too.

It actually

> > I like the idea of a black market, with removing some of the more discreet items from the toolshop and adding them elsewhere.
> > Maybe the black market could have items like handcuffs, adv lockpicks, armour, ammo (at a slightly cheaper price)? This would also be somewhere without tax due to the pricing of some of these items anyways.
> 
> Especially ammo. It dosnet make any sense why we can’t have rifles but yet we can casually buy the ammo for it 😂

Makes perfect sense.  Ammunition (at least in America) is not illegal.  Heavy grade firearms, their possessions, and sales, are permitted and regulated, but bullets are not.  Americans, who are not police, are supposed to keep their weapon and ammunition seperate. Bullets don't kill people, loaded guns do.  You can buy bullets on the internet in America (from most states) with without even possessing an ID, it's rad!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
