### ISSUE TITLE
[game/inventory] New way to get paper bags

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1453]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes
**Summary:**
Write a summary of what your suggestion is about.

Remove the paper bags from the tool store and make it where you can purchase “meals and other food items” from the burger shot( utilizes this MLO we have) and when you eat the Meal it quenches your thirst and hunger about 60% each. After eating the meal you are left with the “paperbag” to do whatever you want with it. This I think is a better way to have the bags in the city rather than buying bags from a store.

**Reason:**
Why would your suggestion be a good change to the framework?
Would create RP in going to burger shot and utilizing the MLO, also would make more sense you get the Burger shot Bag from burger shot.

**Comment by InZidiuZ** [comment]
When opening a burger shot delivery item, you'll now get a paper bag too. The item will be left in the tool store for now, though.
