### ISSUE TITLE
[jobs/*] /hours PD and EMS

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1454]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
A way to check your amount of time clocked on duty for EMS or PD /hours  0.50 would equal 30 irl minutes.
**Reason:**
Why would your suggestion be a good change to the framework?
Sometimes you don’t know how many hours you have in the week from your very tight schedule of you maining your crim but you don’t want to get striked for not being on duty(joke) but on a real note this will be useful to people that are very tight on time regarding having multiple characters and utilizing time on all of them efficiently.

**Comment by twooot** [comment]
We have a better hour tracker now
