### ISSUE TITLE
[jobs/*] /duty PD and EMS

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1455]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
have an On duty command, until we get an app that could do it for when the phone comes out.
Down the road we could make this a phone app. But for now there could be a command that allows cops to go on duty on their (phone) thru a command, /duty will toggle you being on duty or not.
**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good suggestion because many of of cops have head pops and when this happens we have to go back to MRPD to go back on duty. Which is kinda silly for us fo head pop in the middle of nowhere and then we join back into the city and find our car where ever it is and driving it around while off duty with no tracker. So this would help very much with things like that. Or if you are in an on going situation you can go right back to it after the head pop due to all Pd communication only allowed while on duty.

**Comment by twooot** [comment]
I don't think PD/EMS should be able to clock on duty from anywhere, this would be easily abused
