### ISSUE TITLE
[jobs/mechanic] Suggestion

### ISSUE THREAD

**Issue by frenzy602** [InZidiuZ/op-framework-issue-tracker#1456]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?
plz increase the mechanic salary  because we get less car to repair and we need to give 30% to the department  so we earn 500 from a car that we can also earn from other job and we need to be active all the time and control all the city and my mechanic friend all think salary should increase like 40or50

**Comment by bhosalevishu** [comment]
I guess, Mechanic Job is not whitelisted in Main Server. Its whitelisted in Indian Servers Only.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
