### ISSUE TITLE
[jobs/ems] Stretcher

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1457]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
EMS stretcher so ems could drag injured persons into the van or /escort to EMS.

**Reason:**
Why would your suggestion be a good change to the framework?
It would improve RP and you could transport person to hospital.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
