### ISSUE TITLE
[?] PD Bean Bag Shotgun

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1458]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
A bean bag shotgun that PD would use when breaching banks, dealing with suspects and doing correction officer positions without having to use “real bullets”
**Reason:**
Why would your suggestion be a good change to the framework?
Would be cool added RP and allow cops to have a specific shotgun for them. And creating other opportunities to not have to use lethal force but only put the suspect down to detain them.
![578D2D97-FB46-482C-A947-6C111C806897](https://user-images.githubusercontent.com/58092783/96392608-a10bdb80-118a-11eb-91df-c2131395eef5.jpeg)

**Comment by Nuziatella** [comment]
Fantastic idea and adds many elements of roleplay.

**Comment by twooot** [comment]
Done
