### ISSUE TITLE
Certain Bikes can't be reviewed in the mech shops

### ISSUE THREAD

**Issue by iampoh** [InZidiuZ/op-framework-issue-tracker#146]
**Reporter:**
IamPoh, Poh#1913

**Summary:**
When a motorcycle is damaged, we take it to the mechanic shop and the nightblades can be reviewed but other motorcycles like the zombie bobber and chopper can't be reviewed. Also when the contender truck is being repaired, the repairs dont stay and if the body is being repaired on the truck, the vehicle vanishes

**Steps to Reproduce:**
Damage a zombie bobber and take to mech shop, put in red box and no review option pops up

**Expected Results:**
Fix so the motorcycles can be recognized in the red box to be reviewed and repaired

**Actual Results:**
Certain motorcycles cannot be reviewed to be repaired

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/570750579773800459/595426386609438765/2019-07-01_19-15-08.mp4

https://cdn.discordapp.com/attachments/570750579773800459/595429278557143060/unknown.png

**Game Resolution:**
1080p

**Player Data:**
![image](https://user-images.githubusercontent.com/52433631/60475911-c9d72d00-9c36-11e9-80b0-aeb3e22e1f0c.png)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. After next patch, you should be able to put the "zombie" bikes in the center of the red squares, and still get the option to review the vehicle.

**InZidiuZ**
*OP-FW Developer*
