### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rajatborde** [InZidiuZ/op-framework-issue-tracker#1460]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
A bug related to Chop-Shop for specific car Named BISON.

## Additional Information
A Vehicle named BISON was a hotspot in Chop-Shop, when we try to submit the Vehicle it does not get submit. It happened to me twice, you can see the two Attached videos for better clarification what actually happened with me.

**Video Proof**
https://drive.google.com/file/d/1TyHLHeX0EQABXSwOwKNOguxsaX-U_Hj0/view?usp=sharing
https://drive.google.com/file/d/1YnB4ySpb7TE-rlz8pDRBN8eTlJCXtkhN/view?usp=sharing

**Server:**
Legacy Roleplay India #1

**Comment by bhosalevishu** [comment]
This Bug also happens with Tornado Muscle Car and New car request doesn't come unless you submit the previous car.

**Comment by InZidiuZ** [comment]
Not able to reproduce. Also see [this](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1469#issuecomment-713962357) response, guessing that might be the case.
