### ISSUE TITLE
CNetObJVehiclePool Size Error (with fix?)

### ISSUE THREAD

**Issue by cwisdasaur** [InZidiuZ/op-framework-issue-tracker#1461]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this 

GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561197994133097/

**Summary:**
Write a short summary of what you are experiencing.
A month ago I used to receive a headpop and the error told me to raise the CNetObjVehiclePool Size. After speaking with staff, I did what the error said and the issue seems to be resolved.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Drive any vehicle and get CNetObJVehiclePool Size error.

**Expected Results:**
What are the expected results?
Not to get the error.

**Actual Results:**
What are the actual results?
The only thing that I can conclude from speaking with others who have encountered the error and development is that the error occurs randomly, I have not had the error in one month so I am unable to relay what my console could have shown.  

## Additional Information
The reason I have not had the error for a month is because I changed a variable in my gameconfig.xml. I changed Vehicles PoolSize from 300 to 320. 

**Screenshots:**
https://imgur.com/1UW0fDJ
https://imgur.com/iOAhPcg
https://imgur.com/6rSE6ty

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://imgur.com/duF5TUz

**Server:**
What server/community did this issue occur in?
Legacy NA/EU

**Notes:**
For anything else noteworthy.
I passed this information on to one fellow and it helped him too.
None of this is rocket science but this could be related to https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1446 in some way.
Thank you to anyone who spoke with me on this.

**Comment by InZidiuZ** [comment]
Hi, I'll be closing this issue as it's a problem with FiveM & not our framework.
