### ISSUE TITLE
Rain

### ISSUE THREAD

**Issue by stardome101** [InZidiuZ/op-framework-issue-tracker#1464]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes!
**Summary:**
Write a summary of what your suggestion is about.
Turn the rain in LS back on! It doesn't have to be ALL THE TIME but the rain is a really nice addition to the city. 
**Reason:**
Why would your suggestion be a good change to the framework?
The rain is pretty, and the cities of the world aren't always sunny. It makes for good photos that we can show to those wanting to try out our server. I will post an example of what I think is a nice photo below. It can also make cop chases more interesting! 
![cfcdc7760aed4fc275ebe3f3b2b3355f](https://user-images.githubusercontent.com/57492114/96599927-50aa9000-12e8-11eb-9230-af7008e2bfba.jpg)

**Comment by AdeptCL** [comment]
I do miss some of the fun in the rain, when it came to driving/roleplay scenarios/atmosphere of a scenario.

**Comment by Ollie0976** [comment]
+1 please bring back the rain brings some real good photo opportunities and cool driving shit :D

**Comment by novapurple** [comment]
yes, I need rain to make my prison life even more miserable.

**Comment by TrialByCombxt** [comment]
+1 Rain super cool, I like rain. Rain = Water. Water = Cool. We need water. Without water, we die.

**Comment by stardome101** [comment]
> yes, I need rain to make my prison life even more miserable.

Just don't be in prison 4Head

**Comment by z-Lunar** [comment]
fat +1

**Comment by Roadingo** [comment]
Agreed +1

**Comment by Masik52** [comment]
As long as the weather is synced for everyone. Nothing worse than being in a chase with someone and your is car sliding all over but the car your chasing sticking to the ground because there’s no rain for them.

**Comment by InZidiuZ** [comment]
The reason rain isn't in the natural weather cycle is because it creates puddles which currently effects all the player houses. In the future, if that is resolved, it'd be added into the natural cycle, but until then it will not. There are the 'weather spell' items now, though.
