### ISSUE TITLE
Bug report :- I left the city alive normaly but when I came back I was mugged unconscious. So please help me or give my stuff back.  

### ISSUE THREAD

**Issue by RajvirSinghMajotra** [InZidiuZ/op-framework-issue-tracker#1465]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by AdeptCL** [comment]
This bug report has not been completed correctly.

Also, we do not have any compensation processes here. Unfortunately, bugs do happen. There is also a chance you may have been bleeding which sometimes does result in you logging into the server and waking up in the hospital.

**Comment by InZidiuZ** [comment]
Read the README file
