### ISSUE TITLE
Bug report of Legacy Roleplay India # 1

### ISSUE THREAD

**Issue by RajvirSinghMajotra** [InZidiuZ/op-framework-issue-tracker#1466]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
crazyBoi007
**Summary:**
Write a short summary of what you are experiencing.
I was in city 1. I left the city normally and was not dead. But when I came back to the city next day I was mugged unconscious in pill box. If u have any suggestion please tell me and if you are able to please give me my stuff back. 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?
I think they will help me and give my stuff back.
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Leagcy roleplay India #1
**Notes:**
For anything else noteworthy.

**Comment by AdeptCL** [comment]
> Also, we do not have any compensation processes here. Unfortunately, bugs do happen. There is also a chance you may have been bleeding which sometimes does result in you logging into the server and waking up in the hospital.

Quoted from your other report you made.

**Comment by RajvirSinghMajotra** [comment]
At least can I get my stuff back, Please?

**Comment by AdeptCL** [comment]
I will quote myself **again**:

> Also, we do not have any compensation processes here.

**Comment by Nuziatella** [comment]
To clarify Adept. We have no idea what stuff you lost and we have no way I've adding it back into the server as staff can not spawn items and/or money.

**Comment by RajvirSinghMajotra** [comment]
It was just a phone, a sns pistol, 2 bandages, and 5- 1oz weed

**Comment by Nuziatella** [comment]
We can't spawn money to purchase these items nor can we verify what you lost. As @AdeptCL said, we have no way of compensating for lost items and/or money.

**Comment by RajvirSinghMajotra** [comment]
Just the phone and sns pistol?

**Comment by AdeptCL** [comment]
> We have no way of compensating for lost items and/or money.

You **will not** be getting anything back.

**Comment by RajvirSinghMajotra** [comment]
Come on man, please?

**Comment by AdeptCL** [comment]
@RajvirSinghMajotra Please read what we are saying... we can't do anything, there isn't anything we can do. It's not something this server has. We do not have a compensation process.

**Comment by bhosalevishu** [comment]
@RajvirSinghMajotra Go to LHS

**Comment by RajvirSinghMajotra** [comment]
What is LHS
