### ISSUE TITLE
Chop Shop Doesn't Submit the Vehicle

### ISSUE THREAD

**Issue by Ravzyy** [InZidiuZ/op-framework-issue-tracker#1469]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/ravzyygaming/

**Summary:**
The Chop Shop radio said it was BISON which was needed top be submitted. I found the car and tried to submit at the Chop Shop and didn't really take my request. This might be a glitch, Please fix!

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?
The car which is matched with the Chop Shop radio should be submitted.

**Actual Results:**
What are the actual results?
It doesn't seem to accept my request when clicked on the E muzzle.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
[Screenhsot](https://drive.google.com/file/d/1i1EfT5M56m2Sc7zzocrmf8E6Xmek458w/view?usp=sharing)

**Game Resolution:**
What is your game's resolution?
1920*1080 (75Hz)

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
[In Game Info](https://drive.google.com/file/d/1BY-B6DfUJLVrFEsxv6zKWhOF6CXpD_2U/view?usp=sharing)

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India #1466  

**Notes:**
For anything else noteworthy.

**Comment by Dinoreaper5** [comment]
Sometimes that happens, until chop is fully fixed and running smoothly, if stuff like that happens, you just have to wait for the tsunami to rolls in.

**Comment by KaiEagle** [comment]
No, actually Bison got 3 models in it. If the model you are submitting is not getting accepted that means it's the other model of the bison.

**Comment by InZidiuZ** [comment]
Read the README file & closing in favor of #1460
