### ISSUE TITLE
[illegal/guns] Gun running cool down

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1470]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
Give a cool down on gun running.
**Reason:**
Why would your suggestion be a good change to the framework?
It would create a more realistic approach to the gun running, and will better the gun economy. Currently I think the fastest you can do it is in 35 seconds for the keys and code. So it takes about 35 seconds for a gun and I think this is way too low. It’s nearly impossible for any gang to “hold it down” when people can run in there and do 15 sets in 15 minutes. I think the cool down should prob be half of the coke plane maybe 5- 10 minutes for one run (1 set)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
