### ISSUE TITLE
Mayor's Office

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1471]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
A little while ago the Mayor's Office interior was added but seems like the keys were not assigned to the state job so one is able to enter the Mayor's office because of it. (Including Mayor :|)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Assign the keys to **State Job.** 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://cdn.discordapp.com/attachments/521973785218252802/765877596646539284/FiveM_b2060_GTAProcess_iqoz4qhgka.png

**Server:**
What server/community did this issue occur in?
India WL

**Comment by InZidiuZ** [comment]
This issue has now been resolved with version 3218.
