### ISSUE TITLE
[vehicles/garages] Vehicle Return.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1473]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Im thinking about to rework the garage little bit. If player has already his vehicle out he can't return that same vehicle. Right now if player wants to example repair his car he can just return his car for 250$ and get a brand new car. Another example: Someone steals player's car and the player will go and return the car. It's no point for him to be worried about his car because he can just return his car. Please disable returning ability if player already has same vehicle spawned. No one want's to repair their car through mechanic if they can just simply return their car and get a new car.

**Reason:**
Why would your suggestion be a good change to the framework?
It would improve RP overall and will do it more realistic.

**Comment by glocknine234** [comment]
.

**Comment by nikkoendres** [comment]
I agree completely, I lose concern for the state of my vehicle because I know whenever restart happens it will return to how it was when I pulled it out. Vehicle state should constantly be updated the garage when someone interacts with it such as getting in or out of the vehicle.

**Comment by twooot** [comment]
This should be implemented
