### ISSUE TITLE
[game/status] Vehicle Odor.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1476]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
If player drinks alcoholic drinks or smokes weed inside the car the smell will remain there until he washes his car at the car wash. Example player smokes weed inside the car and if police approaches him he can do /smell or something and it will tell to police if theres any weed smell coming out from the car window. Or if you open car window and approach that message would come to chat like "Alcohol smell coming out from the window or weed smell coming out from the window"

**Reason:**
Why would your suggestion be a good change to the framework?
It will improve police rp and would be very cool.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
