### ISSUE TITLE
[base/commands] When binding a command to Numpad 3, an error appears that reads, "System: This command is not available"

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#1477]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
https://steamcommunity.com/id/nohbob

**Summary:**
Since the most recent update, when using a key that is bound to NUMPAD 3, an error appears every time I use the key.  This changed recently, as I have had that bound that way for the past 6+ months.

**Steps to Reproduce:**
Rebind a key in the command to Numpad 3
When pressed you will get a red error that reads System: This command is not available"

**Expected Results:**
What are the expected results?
Error does not appear

**Actual Results:**
What are the actual results?
Error Appears

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://imgur.com/a/88svIzV

**Game Resolution:**
What is your game's resolution?
2560 X 1440
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Characters ID:86 - Job Data: Bar and Club, Bar Jobs, Bar Owner
**Server:**
What server/community did this issue occur in?
International

**Notes:**
Please note, I cleared my cache after this started happening.

**Comment by InZidiuZ** [comment]
Which command is bound to the keybind?

**Comment by b-hess** [comment]
Special Action for Radio, the same happens when you use the numkeys for flying.

**Comment by InZidiuZ** [comment]
🤔 I am not sure what you mean, could you explain further?

**Comment by b-hess** [comment]
So here is a short video.  Showing the Keybinding, the error everytime I use the keybind.
https://streamable.com/36f7ef

**Comment by InZidiuZ** [comment]
I need to know how to reproduce this. How did you create that command bind, what exactly did you type in the parameters of the `/command_bind_add` command in order to get this to happen?

My guess is that the command that is set to execute on this bind is no longer a valid command.

**Comment by b-hess** [comment]
I mapped the Numpad 3 key to my push-to-talk button.  I didn't use the /command_bind_add command at all.

**Comment by InZidiuZ** [comment]
This issue turned out to be a keybinding from another server interfering. Closing this issue as it's not an issue related to the framework.
