### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#148]
**Name:** AdeptCL#0402.

**Summary:** The coke deals currently happening - or so I'm only aware of - similar to the weed deals, i.e. Grove area, which makes sense for drugs. However, what about adding the possibility of selling cokes in the Hills of Los Santos to the richest? Higher award, but higher risk? 
Realistically, coke is very common with the richest as seen via celebrities.

**Reason:** It would spread the amount of focus on the Grove area, and almost split the population concentration in certain areas. Not only that you could essentially do it so that every successful coke deal can be triggered to the PD by bystanders/locals in the area.

**Comment by tankfurious** [comment]
Ehh have you even sold coke?

**Comment by AdeptCL** [comment]
> Ehh have you even sold coke?

I am going to assume I have missed something then.. but I've been working with some people.

**Comment by tankfurious** [comment]
yes you have ;)

**Comment by InZidiuZ** [comment]
You just suggested something that's already a thing, so will close this. :p
