### ISSUE TITLE
[?] Police Megaphone

### ISSUE THREAD

**Issue by OmkarRahangdale** [InZidiuZ/op-framework-issue-tracker#1482]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I think a police car megaphone would be a good addition since it becomes easy to warn suspects during chase while maintaining a safe distance.

**Reason:**
Why would your suggestion be a good change to the framework?
It can also be used to warn suspects in a lot of situations and adds a more realistic feeling to the situation.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
