### ISSUE TITLE
[vehicles/gadgets] Police Helicopter Locked On Vehicle Traveling Information

### ISSUE THREAD

**Issue by RobinWell** [InZidiuZ/op-framework-issue-tracker#1483]
**Assurance:**
I have read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
When the Police Helicopter locks on to a vehicle, it only gives you the information about the vehicle. I would like to have a function added to this, where when you lock onto a vehicle, you get information in the bottom right corner, containing what street the locked on vehicle is traveling, as well as what direction. Ex: Alta Street, North Bound.

**Reason:**
It would enable the chance for Air1 to give callouts when in a chase, to streamline the given information in a pursuit, as well as enabling Air1 to give callouts on where the suspects vehicle is traveling.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
