### ISSUE TITLE
Removing Blimps and Local Flown Helicopters

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1484]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes i have

**Summary:**
Removing local blimps and local flown helicopters

**Reason:**
Blimps have been an issue for a bit now, and i think that if you're in the city for more than an hour you will encounter one in the middle of the street, or hear a loud explosion from time to time, these blimps add nothing to the RP and they only seem to take the immersion away when one lands or when one blows up, same with helicopters, it's okay to have them flying from time to time but most times they just bounce up and down in the air and land or blow up in the middle of the road.

the removal of the blimp and local flown helicopters would not take anything away from RP, if anything it'd be nice to stop hearing these loud explosions and seeing these massive objects falling from the sky.

**Comment by Imaghost1337** [comment]
Massive +1

**Comment by gighul** [comment]
yeah +1

**Comment by InZidiuZ** [comment]
Removing something that isn't working as intended isn't really a good fix... so no. If it persists for months, then maybe, but we're not on the latest FiveM artifact and I believe the FiveM canary client has a lot of of changes not on the release update channel yet.
