### ISSUE TITLE
my car colour changes when removed from garage

### ISSUE THREAD

**Issue by matwankarsiddhant** [InZidiuZ/op-framework-issue-tracker#1485]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
What is your steam profile?
matwankar.siddhant

**Summary:**
Write a short summary of what you are experiencing.
I purchased a a car from PDM (Alpha sports), then i modified it, changed the colour and stored it in the garage. Everytime i remove it from the garage now, my car for 1 second shows me my colour and then changes to the stock model. I tried retrieving it from other garages to after rejoining the server but no success. It shows my car in Black but my car is chrome with all mods. Engine,Trasmission,Armor,Lights,Neons,Bumpers,Tiers and it shows nothing. It shows only for a second before changing to stock.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Resolve the issue please

**Expected Results:**
What are the expected results?
When i remove my car from the garage, it should show me all my mods and my original purchased color for the car.

**Actual Results:**
What are the actual results?
It shows a stock car after 1 second of showing my purchased colour and does not change back from there. also at the tuning shop does not show me any of my purchased mods. I have spent a lot of money only on my mods. Please help

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![Screenshot (4)](https://user-images.githubusercontent.com/73554011/97457113-73c7e600-195f-11eb-9406-aa5116225c4d.png)

![Screenshot (5)](https://user-images.githubusercontent.com/73554011/97457409-bab5db80-195f-11eb-9fe1-d37aba2d3996.png)

**Game Resolution:**
What is your game's resolution?
1920*1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Screenshot (2)](https://user-images.githubusercontent.com/73554011/97457175-83dfc580-195f-11eb-82fd-b7c923f6ab42.png)

![Screenshot (3)](https://user-images.githubusercontent.com/73554011/97457331-a83ba200-195f-11eb-8b12-e8e592b2c7ef.png)

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India 1&2

**Notes:**
For anything else noteworthy.
Please help me as i have spent a lot of money on the car and also retrieving it.

**Comment by matwankarsiddhant** [comment]
Now the color automatically changed to yellow from black. Pls help me

**Comment by InZidiuZ** [comment]
Not able to reproduce locally. Guessing the issue is related to how we currently apply vehicle modifications. In the future this should not be an issue as we'll be applying them properly.

**Comment by matwankarsiddhant** [comment]
what do i do for now? as all my mods are gone

**Comment by glocknine234** [comment]
My 2 players had the same problem, sometimes his car spawned with mods sometimes not.

**Comment by matwankarsiddhant** [comment]
so what is the solution? or there is none? ill have to play like that only?
