### ISSUE TITLE
[jobs/police] Vehicle-related reports show incorrect color(s)

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1486]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
When you are on duty as a officer and you get hold-on, or car stealing call then it always shows metallic black as a car's color. When you steal white car, police will get noticed that metallic black car was stolen.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Steal a car.

**Expected Results:**
What are the expected results?
It to show different and true colors.

**Actual Results:**
What are the actual results?
Always showing only one color.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Estonia Legacy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue should be resolved with version 3263.
