### ISSUE TITLE
[illegal/stockade] Remove dispatch call when stealing the bank truck.

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1487]
**Assurance:**
Yes

**Summary:**
My suggestion is about removing the dispatch call when stealing a bank truck. It doesn't give the criminals any chance to setup, it's pretty hard setting up when the cops are on ur ass the entire time. I don't really understand the reasoning for sending an alert to the police for stealing the bank truck anyway...

**Reason:**
It will not only improve the PERFORAMNCE of the "op-framework" resource file but it will also give cops something to do instead of just sitting around all day. You know they complain about not having shoot outs but then respond to a bank truck with ARs without even identifying if the suspects are using Class 2s or not. (just a thought) hehe

**Comment by KidDano** [comment]
+1 the alarm should only be send to dispatch when the doors are being opened, once they started lockpicking the truck should be anchored so they cant move it and only the person who started lockpicking the doors should be the only one that can take the gold bars out, this prevents all the criminals involved to all take the bars at the same time and finish super fast.

**Comment by xRunnin** [comment]
+1 That tracker does not give crims chance to setup, I think the tracker thing must activate when they lockpick the doors. Adding more gold bars would be nice too like 15 to 40 gold bars is a good number randomly depends if you lucky.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
