### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DrCrazyBDYT** [InZidiuZ/op-framework-issue-tracker#1488]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I think crossairs does not feel like real life when anyone points a gun there should be no crossair to make it more realistic. The recoil is now good but if the recoil can be like the old day it will fell great again. It takes a lot of time to reduce stress with (weed) and it pretty annoying to wait for that much time. Now in city there are no new stuff and people's are bored the gun crafting and new jobs should be added quickly as possible to legacy it will be good for the server. there are a lots of fights happens in the city but there is no good pistol for pd to use in the fight like criminals carrys .50 and  heavy pistols but police have combat pistol its a good pistol but not good like.50 or heavy pistol if the pd heavy can be add the police can fight with the criminals with pistols too it will be a  fair fight for both of them. There are free models character faces that can't fit all mask in clothing and that's why people use the same face in the server if the faces are fix people can use all the mask that is in the clothing. 

**Reason:**
Why would your suggestion be a good change to the framework?
I ask my friends who plays rp in legacy and they also Think that my suggestion will be good for framework and i want more players to play on legacy and make the server grow more

**Comment by SantoOp** [comment]
+1

**Comment by DaxterPancake** [comment]
All good in theory, until you realize most people will just use crosshairs in fights..

**Comment by DaxterPancake** [comment]
Wait now that I read more into your post..

What exactly are you suggesting here?

**Comment by InZidiuZ** [comment]
Read the README file one more time, please...
