### ISSUE TITLE
Voice Issues

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1489]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/avilashsengupta/

**Summary:**
Initially on entering the server the voice seems to be flawless after a few moments the following occurs : 
1. Voice disconnects automatically we need to turn voice chat on/off to re-enable it.
2. Some players can hear me while others can't. 
3. This issue can also be seen on voice over radio

**Expected Results:**
Smooth voice functioning 

**Actual Results:**
Voice Disconnects

**Comment by InZidiuZ** [comment]
There's not much I can do with this... I'd imagine this would be an issue with FiveM as well, as the actual voice server and such isn't developed by us at all.
