### ISSUE TITLE
Suggestion for PD/SWAT

### ISSUE THREAD

**Issue by BulletMagnet1337** [InZidiuZ/op-framework-issue-tracker#149]
**Name:**
@BulletMagnet#4737

**Summary:**
For training purposes, could we please have the ability to spawn in manikins the same way we would for cones, barriers, spikestrips? Call it "Training dummy" or something.  Ingame classname for this item is: prop_dummy_01
https://objects.gt-mp.net/objects/prop_dummy_01.jpg

**Reason:**
It would be great for FTO's when running simulations, as well as for SWAT training.

**Comment by BulletMagnet1337** [comment]
Alternatively, this could also / instead be used: https://objects.gt-mp.net/objects/pil_prop_fs_target_03.jpg

**Comment by InZidiuZ** [comment]
Hey,

I've now added the ability to spawn both the dummy & the target prop. This will be available after next patch.

**InZidiuZ**
*OP-FW Developer*
