### ISSUE TITLE
[Clothing] Face Mask for SOL

### ISSUE THREAD

**Issue by ultrahacx** [InZidiuZ/op-framework-issue-tracker#1490]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
Write a summary of what your suggestion is about.
- Custom SOL facemask/bandana resource ready to be streamed made by me. 
Files:
[sol_mask.zip](https://github.com/InZidiuZ/op-framework-issue-tracker/files/5464487/sol_mask.zip)

**Reason:**
Why would your suggestion be a good change to the framework?
- It would be nice to see more custom clothing for gangs and let the players deep dive into the RP maybe.

**Comment by DaxterPancake** [comment]
This is the wrong tracker for this. 

This would be for the assets tracker.

**Comment by ultrahacx** [comment]
Shoot. Didn't notice that. Thanks for pointing it out
