### ISSUE TITLE
[illegal/chop_shop] Timer for Chop Shop Vehicles isn't working properly

### ISSUE THREAD

**Issue by its-vishal** [InZidiuZ/op-framework-issue-tracker#1491]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
There Should be Timer for Vehicles which comes in Chop Shop. There was a Car Kuruma, we were searching that vehicle for more than 3 hours but we didn't got the vehicle and we have to wait for next car until server restarts. although its available in PDM, but taking PDM Test Drive Car to Chop Shop Looks Like Unfair.

![image](https://user-images.githubusercontent.com/56230822/97754984-686ee900-1b1e-11eb-9b15-efdf54fbe1a4.png)

There should be Time of 30 Minutes or 45 Minutes to Find The Vehicle as sometimes some models don't show up.

**Reason:**
As I said, The Car KURUMA never spotted, we wasted more than 3 Hours.  Timer will give chance to chop other models of vehicle and we don't have to wait for Server Restart.

**Comment by its-vishal** [comment]
![image](https://user-images.githubusercontent.com/56230822/97775145-617ac180-1b84-11eb-8cd7-8f79d560865e.png)

Today we were searching for this car for more than 4 hours... but this car didn't spawned anywhere...

**Comment by KaiEagle** [comment]
> ![image](https://user-images.githubusercontent.com/56230822/97775145-617ac180-1b84-11eb-8cd7-8f79d560865e.png)
> 
> Today we were searching for this car for more than 4 hours... but this car didn't spawned anywhere...

Well this car do spawn It's the monkey blista first model xD

**Comment by its-vishal** [comment]
@KaiEagle Sorry, But We also didn't found that one also... I know its name is Gogo Monkey Blista 😛 The thing is Cars are not spawning when it's required.

**Comment by InZidiuZ** [comment]
There already is a timeout system in place meant to issue a new model if the requested one isn't delivered for 30 minutes. Going to give this the 'bug' label instead, then.

**Comment by InZidiuZ** [comment]
This issue should be resolved with version 3264.
