### ISSUE TITLE
[Inventory] Pistol stacking.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1492]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Allow to stack pistols in inventorys, right now you can't stack them and only set them separate on gridline.

**Reason:**
Why would your suggestion be a good change to the framework?
In evidence lockers it's taking too much space when you have to put firearms separately and can't stack them.

**Comment by novapurple** [comment]
If this happened it would be kinda a pain in the ass to look at the SN:

**Comment by InZidiuZ** [comment]
They're not stackable for a reason. This will not be done.
