### ISSUE TITLE
[vehicles/gadgets] Disable spotlight for rear seat passengers.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1493]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Please could you disable spotlight if you sit in rear seat so only driver and passenger seat could move it?

**Reason:**
Why would your suggestion be a good change to the framework?
Because its unrealistic + everyone, included handcuffed criminals can control a spotlight.

**Comment by T4NZIM** [comment]
When you are chasing with heli, co pilot sits in the rear seat. So if it gets removed for rear seat passengers, ho co-pilot is supposed to use it? And if someone uses it from rear seat, or hand cuffed criminals, It's a clear fail rp and power gaming. Just make an announcement like that they can't use it and that's it I guess...
