### ISSUE TITLE
[vehicles/garages] Vehicle windows don't save properly

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1494]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
Glocknine

**Summary:**
Write a short summary of what you are experiencing.
If i take out my buffalo it has broken windows, however everytime i repair my windows and put it back into garage and take it out it still has broken windows. Some of the players have had problems with garage too like example tuning their car and taking their car out but car comes out default as they bought it, no cosmetics, no respray etc.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Take garage out.

**Expected Results:**
What are the expected results?
It to give me my car back fixed.

**Actual Results:**
What are the actual results?
Car coming out broken however I fixed it.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Estonia Legacy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
> Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

Can you also provide the vehicle id of the vehicle you're having issues with this on?

**Comment by glocknine234** [comment]
How can i see what vehicle ID it is?

**Comment by InZidiuZ** [comment]
When you're in the garage menu there should be a box that looks like "PLATE (VEHICLE ID)"

**Comment by glocknine234** [comment]
23 but i think its fixed now. It works, you can close this ticket.

**Comment by cwisdasaur** [comment]
I have the same issues gimme one second before closing, will edit.

**Comment by glocknine234** [comment]
I'm not sure if its fixed but when i spawned my car yesterday it was fine.

**Comment by cwisdasaur** [comment]
Preliminary testing shows that it is resolved for me too. Thank you so much.

**Comment by glocknine234** [comment]
I still have this problem. Just took my car out yesterday and windows were broken.
