### ISSUE TITLE
[Bank] Bank robbery is broken.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1495]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
Glocknine

**Summary:**
Write a short summary of what you are experiencing.
When I try to rob a bank by going towards the vault it gives me an error screen. If i click "abort" and walk towards the vault i can't use thermite there or something.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Walk towards the vault in a bank.

**Expected Results:**
What are the expected results?
It to give no error and allowing me to pour thermite near the vault.

**Actual Results:**
What are the actual results?
Giving me an error and not allowing me to pour thermite.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![20201101201945_1](https://user-images.githubusercontent.com/70439794/97815388-5912ab80-1c96-11eb-929e-d89ed47bcff2.jpg)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia

**Notes:**
For anything else noteworthy.
Bank robbery worked like 2 weeks ago but not anymore. It happens in every bank.

**Comment by InZidiuZ** [comment]
This issue should be resolved with version 3231.
