### ISSUE TITLE
[vehicles/plates] Admin-spawned fake plate does not work

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1496]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/gighulgg/

**Summary:**
Write a short summary of what you are experiencing.
When user attempts to change plates in private/stolen car with item "fake_plate" then receives following error:
![image_2020-11-02_111854](https://user-images.githubusercontent.com/71882732/97856877-31a2f980-1cfd-11eb-81bd-e123ff7c212d.png)
It happens every time. It prevents us from various options to create an outstanding robbery, to confuse enemies or police. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Using item triggers error immediately, 100% times.

**Expected Results:**
What are the expected results?
Fix script that will work on private/stolen cars.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![FiveM_GTAProcess 2020-11-02 10-51-52](https://user-images.githubusercontent.com/71882732/97857038-70d14a80-1cfd-11eb-9fdf-9fc9ce93b9db.png)
![FiveM_GTAProcess 2020-11-02 10-51-56](https://user-images.githubusercontent.com/71882732/97857045-7333a480-1cfd-11eb-8a9d-e0466387a8f8.png)
![FiveM_GTAProcess 2020-11-02 10-52-06](https://user-images.githubusercontent.com/71882732/97857056-7595fe80-1cfd-11eb-81f7-e21b2b8a2dc7.png)

**Server:**
What server/community did this issue occur in?
Poland subdivision, EU/NA

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3267.
