### ISSUE TITLE
[?] Addition Of Cloth change , Exit City and Lock Door in Weazel News

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/op-framework-issue-tracker#1497]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**

Write a summary of what your suggestion is about.
Add cloth changing,Exit City and lock door in Weazel News HQ 

**Reason:**

Why would your suggestion be a good change to the framework?

Now there is HQ for WN but we can't change clothes and exit city from weazel news like PD and EMS. If these are added then reporters can change their clothes directly from their and leave city. Because in indian servers their is a dress for reporters and to make those clothes we have to clothing store everytime. 

And their is no door lock in HQ which means anyone in server can come to HQ anytime and do anything which is not good from RP point of view.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
