### ISSUE TITLE
[game/items] Alarm System

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1498]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Players could buy alarms from shops for their vehicles to prevent thieves. I made a list for alarms that should be in shop.

[Vehicles]

1. NoSnitch Alarm ($1.000):

Delay: 1.5 seconds
Triggers on being Towed: No
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: No
Lockpick attempts before alarm triggers: 3

2. Standard ($1.500):

Delay: 12.5 seconds
Triggers on being Towed: Yes
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: Yes
Lockpick attempts before alarm triggers: 4

3. Moderate Alarm ($3.500):

Delay: 7.5 seconds
Triggers on being Towed: No
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: No
Lockpick attempts before alarm triggers: 2

4. LS-AT Alarm ($5.000):

Delay: 12.5 seconds
Triggers on being Towed: Yes
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: No
Lockpick attempts before alarm triggers: 1

5. Advanced Alarm ($9.000):

Delay: 3.5 seconds
Triggers on being Towed: Yes
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: Yes
Delay before alerting the LSPD: 10 seconds
Lockpick attempts before alarm triggers: 2

6. Ultra-Advanced ($18.000):

Delay: 0 seconds
Triggers on being Towed: Yes
Alerts the owner over SMS: Yes
Alerts the LSPD with a message: Yes
Delay before alerting the LSPD: 5 seconds
Lockpick attempts before alarm triggers: 1

**Reason:**
Why would your suggestion be a good change to the framework?
Improve RP and more stuff to spend money on.

**Comment by SirPiff** [comment]
+1 will no longer have my car stolen so easily waiting for governor speech to start

**Comment by twooot** [comment]
I added car alarms
