### ISSUE TITLE
Personal Car Getting Stuck Again and Again Serious Issue !!! Please resolve ASAP

### ISSUE THREAD

**Issue by rudranshsinghmahra** [InZidiuZ/op-framework-issue-tracker#1499]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
 Yes I have read all the rules

**Player Identification:**
What is your steam profile?  https://steamcommunity.com/profiles/76561198804226336/

**Summary:**
Hello my car is again and again getting stuck when I leave my personal vehicle and when i enter in the vehicle again only the engine starts but the car doesn't move forward neither by accelerating or by pushing with another vehicle. The only way is that i have to retrieve it from the garage again and again which cost me 250 dollar each time and you know spending that much amount is very tough not only me but many people are facing this issue. Request you to fix this bug on urgent basis as soon as possible.

**Game Resolution:**
What is your game's resolution? 1920*1080

**Server:**
What server/community did this issue occur in? In server 2

**Comment by InZidiuZ** [comment]
Read the README file
