### ISSUE TITLE
Vehicle inventory balance

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#150]
**Name:**
SteezyRen#2828

**Summary:**
For starters this is going to be tedious and I apologize in advance. It seems all vehicles have a 400 weight capacity in which that doesn’t entirely makes sense. Some vehicles don’t even have trunks and has the same storage capacity as a utility van. 

There should be different storage capacity per vehicle class with exceptions to some. 

Not sure what your coding is like for storage capacity but if you need help with determining storage per vehicle I will gladly assist with that. I did a fork on github with storage capacity on another server but I would assume the coding there will be different than the custom framework here. So I can simply just provide numerical values for all vehicles if need be. 

**Reason**
My motorcycle shouldn’t be able to hold 400 lbs of Mech parts when that’s what my van is already doing lol.

**Comment by InZidiuZ** [comment]
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/142

If you'd like to hit me up with some *suggestion* values, then for sure, that would be great. :)

**Comment by InZidiuZ** [comment]
Hey,

This has now been done to a few vehicle classes, and will now close this. More vehicles will be tweaked after time, but will start off with these to make sure everything works properly.

**InZidiuZ**
*OP-FW Developer*
