### ISSUE TITLE
[jobs/police] Evidence locker capacity

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#1500]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Increasing the size of the evidence locker or adding a separate evidence locker in the basement of MRPD

**Reason:**
Why would your suggestion be a good change to the framework?  It would allow people to not potentially lose items they are able to get back after being arrested.  our current locker fills up rather quick and is emptied out potentially tossing out items that civilians would be able to get back

**Comment by glocknine234** [comment]
Or just they could add command /removeitem so you could remove them from the evidence locker.

**Comment by glocknine234** [comment]
Example if you have it full then make a event, Transporting illegal firearms/drugs to Sandy Shores for drop-out and players could attack the convoy and take evidence-stuff. Would be cool imo.

**Comment by DaxterPancake** [comment]
Would it be possible as a branch off to this, to allow police access to a command (or maybe above a certain rank, not all police) such as "/storage 1" which would open a smaller storage crate which would be used to store evidence/weapons/ANYTHING that is needed for a case file?
As it stands right now, FIB are having to store their evidence in either the evidence locker or in their personal lockers which eventually gets confusing/annoys people. With this system the sorting of evidence would be easy as you'd be able to assign a storage 'crate' to a specific case.
For example, if FIB is investigating the Bean Machine, we'd assign that storage crate 7 which would be "/storage 7".

**Comment by InZidiuZ** [comment]
This has since been done.
