### ISSUE TITLE
[vehicles/controls] VehControl NUI Menu

### ISSUE THREAD

**Issue by its-vishal** [InZidiuZ/op-framework-issue-tracker#1501]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Summary:**
This Menu Gives Following Control to Operate easily without commands
-Hood
-Trunk
-Doors
-Windows
-Interior Light
-Change Seats
![image](https://user-images.githubusercontent.com/56230822/98215121-6321fc00-1f6d-11eb-9e99-a11b3800eaf8.png)

**Link**
https://github.com/Manvaril/vehcontrol

**Reason:**
This will be a great addition to the server as this will save the time and will be handy to operate vehicle

**Comment by KingsINSANE** [comment]
This feature is great and along with this there is a menu which offer various character menus like give key and 
![Uploading Screenshot_20201111-184352.jpg…]()
