### ISSUE TITLE
GARBAGE COLLECTOR JOB 

### ISSUE THREAD

**Issue by shreyasmedade** [InZidiuZ/op-framework-issue-tracker#1503]
Sir I Can't Earn Money By Any Job ! I Tried Garbage Collector Job For Atleast 9 Times And I Didn't Earned A Single Rupee From It ! And I Am Also Not Getting Any Interest When I Am Out Of The City ! And Please Please Please I Request You I Beg You Sort This Issue I Can't Earn A Single Money !

**Comment by InZidiuZ** [comment]
Read the README file

**Comment by shreyasmedade** [comment]
What I Have To Read The Five M Read Me File??

**Comment by InZidiuZ** [comment]
https://github.com/InZidiuZ/op-framework-issue-tracker/blob/master/README.md

**Comment by shreyasmedade** [comment]
Sir But I Wrote Everything In English And I have Provided Proper Information Which I Have ! Where And What I Wrote Wrong?

**Comment by InZidiuZ** [comment]
...clearly you didn't read the file
