### ISSUE TITLE
[Cars] Add FiveM dlc vehicles to PDM.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1504]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add DLC vehicles to PDM. They look so good etc. You should add these:
![image](https://user-images.githubusercontent.com/70439794/98452242-2402cf00-2156-11eb-9751-dc9262f5758b.png) Tempesta

![image](https://user-images.githubusercontent.com/70439794/98452129-33cde380-2155-11eb-86b2-9f49927885d2.png) Cheetah2

![image](https://user-images.githubusercontent.com/70439794/98452133-3a5c5b00-2155-11eb-9c69-149fec98a605.png) Torero

![image](https://user-images.githubusercontent.com/70439794/98452141-4b0cd100-2155-11eb-9262-270f0aff090f.png) Raiden
 
![image](https://user-images.githubusercontent.com/70439794/98452146-58c25680-2155-11eb-8c87-f30a1010cf5a.png) Comet5

![image](https://user-images.githubusercontent.com/70439794/98452148-5eb83780-2155-11eb-95a4-bb485dab5cdf.png) Dominator3

![image](https://user-images.githubusercontent.com/70439794/98452150-6972cc80-2155-11eb-8892-025e2bd6a2dc.png) Jester3

![image](https://user-images.githubusercontent.com/70439794/98452158-7db6c980-2155-11eb-81f8-a1e1827bd933.png) Gauntlet4

![image](https://user-images.githubusercontent.com/70439794/98452163-827b7d80-2155-11eb-8ff6-dbf15bff37dd.png) Nebula

![image](https://user-images.githubusercontent.com/70439794/98452170-8a3b2200-2155-11eb-9942-6b774a92d95d.png) Hellion

You can spawn them with /sv (Name) right now ,but players can't buy them from PDM.

**Reason:**
Why would your suggestion be a good change to the framework?
They are beautiful.

**Comment by AdeptCL** [comment]
This probably needs to go into the Assets Tracker, found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker).
