### ISSUE TITLE
[Bank] /closebank not working.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1505]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
When I go infront of bank doors and type /closebank then nothing happens and doors will not be closed.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Type /closebank.

**Expected Results:**
What are the expected results?
It to close bank doors.

**Actual Results:**
What are the actual results?
Not closing them.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
I tried to reproduce this but was not able to. Are you able to provide some more details as to which banks this was done at, and perhaps a video of you doing it? Did you also try closing the bank while inside?

**Comment by glocknine234** [comment]
Is /closebank only working after bank robbery or anytime?

**Comment by InZidiuZ** [comment]
During or after a robbery

**Comment by glocknine234** [comment]
It started to work again somehow, but thanks for responding.
