### ISSUE TITLE
[jobs/ems] EMS salary

### ISSUE THREAD

**Issue by rounaksingh12** [InZidiuZ/op-framework-issue-tracker#1506]
**Assurance:**
Have you read through the rules- Yes

**Summary:**

SIR, MY IDEA IS LIKE THERE SHOULD BE SALARY FOR EMS LIKE THEY GET IN 1 WHOLE DAY OR FOR EVERY PATIENT THEY HELP OR BASED ON WORKING HOURS SO IT WILL BE A EARNING FOR EMS TOO.
**Reason:**
As I have seen many ems don't have much money to buy a bike or car and they work very hard. Travel far away to treat and bring patients and work for 24/7 . But what they get nothing not even they can afford a scooter. They have to works hours to get one.

**Comment by AdeptCL** [comment]
EMS pay cheques are very good. As someone who has spent almost a year in EMS, there is absolutely no need to increase it.
If you play on the character as your main (so you spend more time on it), and are a 'Specialist', you can earn $102 every 5 minutes (I think it is). This totals to $1224 every IRL hour. 

If this is your main character, you get these payments even off-duty. So let's expand it a little further... Let's say you spend 6 hours in the server off-duty but on your EMS character, you can earn $7344 just from doing nothing. If you're on-duty and doing doctor work, you can earn even more based on the extra(s) you get.

As a Deputy Director of EMS in the main server, I earn $158 (I think) every 5 minutes. Again if we follow the same example above, every IRL hour, I earn $1896. Every 6 hour session off-duty or on-duty (no doctor work), I earn $11376. This is very good and does not need to be adjusted.

**Comment by Rithvikk05** [comment]
EMS Pay Grades Are Divided And Set Up In Perfect Manner To Maintain The Economy And Also Of Other Jobs Too Like : PD And PDM. 

As Such Your Point For No Money To Buy A Bike Or Car Its Your fault You Are Not Saving Money For Vehicles

And Also Within No. Of Hours No One Gets A Car or Bike If You See According To IRL Life You Have To Save Each Penny For A Vehicle Or For A House. 😄

**Comment by InZidiuZ** [comment]
This will not be done at this time.
