### ISSUE TITLE
ALT+F1 Doesn't work.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1507]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
Glocknine

**Summary:**
Write a short summary of what you are experiencing.
When I hold ALT then F1 hint pops out on right down corner of screen. When I hold ALT and F1 both nothing happens and it doesnt record.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Hold ALT+F1

**Expected Results:**
What are the expected results?
It to record.

**Actual Results:**
What are the actual results?
Nothing happens, not recording.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia

**Notes:**
For anything else noteworthy.

**Comment by KaiEagle** [comment]
You might have your Shadowplay screenshot thing on.

**Comment by glocknine234** [comment]
What do you mean? You mean i need to hit ALT+F9 and then press ALT+F1?

**Comment by KaiEagle** [comment]
Go to shadowplay - settings - Keyboard shortcuts - Change the shortcut key for Save a screenshot to the gallery

**Comment by glocknine234** [comment]
Thanks, I'll try.
