### ISSUE TITLE
[police] LAPD Livery

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1508]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Please make LAPD style livery on pd vehicles with better quality. Right now they are jaggy and not with good quality. 

**Reason:**
Why would your suggestion be a good change to the framework?
IT would look better.

**Comment by InZidiuZ** [comment]
This is an asset-related suggestion, so use the other issue tracker as the README file says
