### ISSUE TITLE
Moonshine

### ISSUE THREAD

**Issue by Valkrium** [InZidiuZ/op-framework-issue-tracker#151]
**Name:**
Roastedddd#2903

**Summary:**
Moonshine processing, selling, and possibly consumable

**Reason:**
Like how you're able to process and make drugs. why not do alcohol processing, giving you another variety of illegal substance that is liquid gold to players with possession meaning jail time.

**Comment by SteezyRen** [comment]
I like heroine more :P

**Comment by jaymssmith** [comment]
more drugs more variety in rp

**Comment by InZidiuZ** [comment]
Hey,

Will close this as *moonshine* isn't planned to be added any time soon. More illegal activities, however, are planned. Instead of only adding more drugs, we also plan to add illegal gun crafting, heists, and oxy.

**InZidiuZ**
*OP-FW Developer*
