### ISSUE TITLE
Bug report (Vindicator boost effect)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1510]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1/
**Summary:**
Write a short summary of what you are experiencing.
So when you drive the Dinka Vindicator and press E it shows the boost vision I couldn't see any kind of impact on speed.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Just take a Dinka Vindicator from pdm on testdrive and while driving it press and hold e to see the boost effect.
**Expected Results:**
What are the expected results?
Shouldn't have the boost effect
**Actual Results:**
What are the actual results?
The screen effect shows the of boost kinda like the Oppressor bike of sorts but it has no impact on speed just a screen effect.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://youtu.be/6YbqTmEGm3A
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/45ae215bef7a44206c1d112cda06b859
**Server:**
What server/community did this issue occur in?
Legacy India WL 
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
I looked further into what this was and it's a system called "KERS".

Here's an explanation I found on the [GTA fandom wiki](https://gta.fandom.com/wiki/Vindicator):
> Similar to the Lectro, the Vindicator has a KERS boost ability, which means the excess energy lost by braking can be re-gained via the usage of the horn button. Compared to the Lectro, the Vindicator is better suited for KERS because its poor handling means that the motorcycle brakes in more corners than similar bikes, therefore generating more KERS boost opportunities.

[This](https://www.youtube.com/watch?v=2LbhOiyL95g&ab_channel=RaijinGaming) is a video showing it being used. I also tested it and it worked as expected.

Not going to disable this as I don't believe that would be required at this time.
