### ISSUE TITLE
Bug report (Microphone doesnt work in noclip

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1511]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1/
**Summary:**
Write a short summary of what you are experiencing.
So you if you using /noclip and try and speak the person you are next to in noclip cant 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
use /noclip and use ingame voice the pink indicator works but the person you are next to you doesn't work like they cant hear you but the pink voice bar moves and indicates your voice is working. 
**Expected Results:**
What are the expected results?
They should be able to hear you like before they could.
**Actual Results:**
What are the actual results?
The pink indicator shows its working but the person you are next to in noclip cant hear you.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/45ae215bef7a44206c1d112cda06b859
**Server:**
What server/community did this issue occur in?
India WL and Public
**Notes:**
For anything else noteworthy.

**Comment by AdeptCL** [comment]
I do feel like individuals should be able to hear you if you're noclipping.
As a staff member, it means we can communicate with individuals without having to TP to them. Not only this, during events such as Halloween, Matt (Matt;)#7784) did an event of a ghost, but could communicate if he stopped noclipping.

**Comment by KaiEagle** [comment]
> I do feel like individuals should be able to hear you if you're noclipping.
> As a staff member, it means we can communicate with individuals without having to TP to them. Not only this, during events such as Halloween, Matt (Matt;)#7784) did an event of a ghost, but could communicate if he stopped noclipping.

It used to work before now it doesn't :|

**Comment by GuArDiAn-ops** [comment]
> I do feel like individuals should be able to hear you if you're noclipping.
> As a staff member, it means we can communicate with individuals without having to TP to them. Not only this, during events such as Halloween, Matt (Matt;)#7784) did an event of a ghost, but could communicate if he stopped noclipping.

It should to work back when we had toko :c sadly it isnt working anymore or we can have rp of sorts were there is a ghost or an event.

**Comment by InZidiuZ** [comment]
You'll be able to use your mic while in noclip properly after version 3277.
