### ISSUE TITLE
[jobs/pdm] PDM database

### ISSUE THREAD

**Issue by ItsGUARDIAN** [InZidiuZ/op-framework-issue-tracker#1512]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Was thinking of a computer in the side office in pdm where you can use it like the police database which has list of vehicles sold and finance pending lists which pdm boss or ceo can have access to.
**Reason:**
Why would your suggestion be a good change to the framework?
This would honestly improve rp where can check the due finances of cars and has an ingame database where they can check info when they are checking finances or assisting police with inquiries for the same. It can also work on the tablet like the stocks but only for like pdm boss or ceo. Kinda should look like this in the tablet and computer. 
https://gyazo.com/d5d27dbad9c3ca04d88d7a4386340a91 
You should get options like check register or like check finances tabs perhaps thats the best I could find to the idea.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
