### ISSUE TITLE
Bug report(Block without garage)

### ISSUE THREAD

**Issue by keepcodingstar** [InZidiuZ/op-framework-issue-tracker#1513]
**Assurance:**
Yes I abide by the rules

**Player Identification:**
https://steamcommunity.com/profiles/76561198877377893/

**Summary:**
Missing garage in eclipse blvd block(77).

**Steps to Reproduce:**
add a car garage

**Expected Results:**
there should have been a garage

**Actual Results:**
there exists a physical garage but no point to store and take out cars.

## Additional Information

**Screenshots:**
https://imgur.com/NIy5HNB

**Game Resolution:**
1902 x 1033

**Player Data:**
https://imgur.com/9I1vlQa

**Server:**
Legacy Roleplay Bangladesh #1

**Notes:**
We treat the full block as a gang HQ and since their is no garage we suffer running to nearest garage and bring out cars.

**Comment by Mr4LFA** [comment]
Sir,
We suffer too much to take out cars.
Please Add a Garage

**Comment by FarhanST** [comment]
It's been **3 months** !
No garage option to take out cars. Please fix it.

**Comment by Shanto16** [comment]
This block is the HQ of a gang, you know how important it is to have a garage.

**Comment by AdeptCL** [comment]
This block is used by a lot of people across all our subdivisions. Stop mass panicking over it.
The suggestion has been made, and it will be looked into.

A garage is not exactly a priority for server development.

**Comment by InZidiuZ** [comment]
This is not a *bug*. Feel free to create another issue about this set as a suggestion.
