### ISSUE TITLE
[jobs/ems] EMS improvements

### ISSUE THREAD

**Issue by keepcodingstar** [InZidiuZ/op-framework-issue-tracker#1514]
**Assurance:**
Yes i abide by the rules

**Summary:**
1. The power to heal someone else by applying EMS bandages in my inventory to the other person(without doctor sign-in)(this will increase ems rp by far we can rp like a real medic, a battle medic even).
2. Power to see someone's injuries(without doctor sign-in) and more info of what happened to them (since there is no mechanics for differentiating between a burnt body and normal body) {info about his hp after examining the patient). 

**Reason:**
it is asked by patients daily and i have been thinking about this from a long time.
I am a EMS in Legacy Roleplay Bangladesh #1 from more than 2 months and i personally feel that EMS RP is kind of a low mostly people treat us like a service(not like police). All people including police treat us like cpr machines and nothing more EMS should get more powers. Police has got all the powers they should have got but not EMS however we believe both are important for perfect rp.

**Comment by AdeptCL** [comment]
I have always said something like a /bandage command for EMS only which allows EMS to RP on-scene small scenarios. But even this suggestion of applying a bandage to someone that you have in your inventory would improve the on-scene RP scenarios.

The /cpr function is becoming bulky and just doesn't fit in with a majority of the medical RP scenarios we have.

**Comment by Rithvikk05** [comment]
I Guess The Second Point Thing Is Gonna Come Up. For EMS To Look Injuries While On Scene 💯

**Comment by AdeptCL** [comment]
I think there is already a GitHub for this, and I think it's mine...

**Comment by its-Frost** [comment]
no

**Comment by AdeptCL** [comment]
There is a couple actually: #744 and #1110

**Comment by twooot** [comment]
> Power to see someone's injuries
This has been done

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
