### ISSUE TITLE
[game/hospitalization] Bed rest system

### ISSUE THREAD

**Issue by keepcodingstar** [InZidiuZ/op-framework-issue-tracker#1515]
**Assurance:**
Yes i abide by the rules

**Summary:**
Doctors with sign-in or even ems who makes someone to the check-in should be able to assign bed rest to people depending on the injuries. Where people could not move out of there bed. Hospital can also charge money for the bedrest. It can also lead to a nurse system inside pillbox just saying.

**Reason:**
EMS should have the power to assign bed rest depending on how brutally someone was injured. People just want to take heal and go back grinding. It will give a stop to that. In real we all avoid going to hospitals while in RP people love going to hospitals give it a thought.

**Comment by AdeptCL** [comment]
I feel like this would be a good way of keeping people in ICU, without having them just reconnect an hour later and run away so they don't face PD.
I think this should only apply to the beds at the back of the hospital, i.e. the patient rooms. As in the area where they get treated, it could get really busy and cause issues with people just being on top of eachother.

/set_bed_time [id] [time scale, 5sec, 5min, 5hr]

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
