### ISSUE TITLE
Light options to vehicles

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1516]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
I think currently we have only two light options for every vehicle i.e stock & xeon , so adding of new light options would add more aesthetics to the vehicles along with other modifications available. 

**Reason:**
More modifications and aesthetic options would be available to the players to add into their vehicles.

**Comment by AdeptCL** [comment]
This probably needs to go into the Assets Tracker, found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker).
