### ISSUE TITLE
Gun Run hack turns full black

### ISSUE THREAD

**Issue by badass0403** [InZidiuZ/op-framework-issue-tracker#1517]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/smokydude/
**Summary:**
Write a short summary of what you are experiencing.
after using the chip in Lester's House...when we got to match INZIDIUZ , that time that whole screen turns fully black nd this continues.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
It happens to me all the time when i start GUN RUN.
**Expected Results:**
What are the expected results?
If it would have fixed it wld be much appretiated.
**Actual Results:**
What are the actual results?
I have checked it in every legacy servers..same for all.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![20201111113930_1](https://user-images.githubusercontent.com/74286443/98775303-dd8dc880-2412-11eb-865d-a3267c9f9910.jpg)

**Game Resolution:**
What is your game's resolution?
1280*720
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![20201111114034_1](https://user-images.githubusercontent.com/74286443/98775321-e5e60380-2412-11eb-9cb3-9aea915e68ce.jpg)

**Server:**
What server/community did this issue occur in?
All Legacy Servers
**Notes:**
For anything else noteworthy.
Thanks.

**Comment by InZidiuZ** [comment]
Is this something only you are experiencing?

**Comment by badass0403** [comment]
> 
> 
> Is this something only you are experiencing?

yeap bro!

**Comment by InZidiuZ** [comment]
This is likely to be an issue with your game or FiveM as no one else has been experiencing this issue. Try to verify your game files. Closing this issue though as it's likely not an issue with the framework.
