### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KaliaaAndy** [InZidiuZ/op-framework-issue-tracker#1518]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
https://steamcommunity.com/id/Anand1236

**Summary:**
So I had Two EDM Cars Full upgraded worth 80-90k $ easily on both cars
Nissan Titan Warrior
Aston Martin Vanquash 

now Mods Are not there Please help me to retrieve Mods or Kindly refund 
**Steps to Reproduce:**
It Happened with my both edm cars

**Expected Results:**
it should have Full Mods upgraded

**Actual Results:**
Basic Cars no mods there

## Additional Information

**Screenshots:**
![IMG-20201111-WA0019](https://user-images.githubusercontent.com/74291722/98787642-c6a4a180-2425-11eb-80fe-f9e2e98b2bc6.jpeg)
![IMG-20201111-WA0021](https://user-images.githubusercontent.com/74291722/98787684-d4f2bd80-2425-11eb-9962-085b3cf84eb2.jpg)
![IMG-20201111-WA0022](https://user-images.githubusercontent.com/74291722/98787685-d623ea80-2425-11eb-8465-4772043cba31.jpg)
![IMG-20201111-WA0024](https://user-images.githubusercontent.com/74291722/98787690-d7551780-2425-11eb-98cb-454071502c40.jpg)
![IMG-20201111-WA0025](https://user-images.githubusercontent.com/74291722/98787691-d7edae00-2425-11eb-8214-eff5f1589994.jpg)
![IMG-20201111-WA0026](https://user-images.githubusercontent.com/74291722/98787694-d8864480-2425-11eb-87e0-867193efac74.jpg)
![IMG-20201111-WA0027](https://user-images.githubusercontent.com/74291722/98787696-d91edb00-2425-11eb-82d2-f1c768432589.jpg)
![IMG-20201111-WA0028](https://user-images.githubusercontent.com/74291722/98787698-d9b77180-2425-11eb-947b-7e80be837e4a.jpg)
![IMG-20201111-WA0030](https://user-images.githubusercontent.com/74291722/98787701-da500800-2425-11eb-978d-a82bc6783961.jpg)
![IMG-20201111-WA0031](https://user-images.githubusercontent.com/74291722/98787705-dae89e80-2425-11eb-94bd-fe48a008724e.jpg)
![IMG-20201111-WA0032](https://user-images.githubusercontent.com/74291722/98787713-dc19cb80-2425-11eb-9fc4-931709603f99.jpg)
![IMG-20201111-WA0033](https://user-images.githubusercontent.com/74291722/98787715-dd4af880-2425-11eb-8167-4d5acee1e2e6.jpg)
![IMG-20201111-WA0034](https://user-images.githubusercontent.com/74291722/98787718-dde38f00-2425-11eb-81b6-2564016ed9da.jpg)
![IMG-20201111-WA0035](https://user-images.githubusercontent.com/74291722/98787721-de7c2580-2425-11eb-978a-807a9437d936.jpg)
![IMG-20201111-WA0037](https://user-images.githubusercontent.com/74291722/98787727-df14bc00-2425-11eb-8076-ab6aa861eac8.jpg)
![IMG-20201111-WA0039](https://user-images.githubusercontent.com/74291722/98787729-e045e900-2425-11eb-8438-5eee53d9e483.jpg)
![IMG-20201111-WA0040](https://user-images.githubusercontent.com/74291722/98787731-e0de7f80-2425-11eb-949c-a33dc029a678.jpg)
![IMG-20201111-WA0029](https://user-images.githubusercontent.com/74291722/98787735-e1771600-2425-11eb-9ed4-c64791a922c9.jpg)
![IMG-20201111-WA0023](https://user-images.githubusercontent.com/74291722/98787737-e20fac80-2425-11eb-9c48-3a41147f34a5.jpg)
![IMG-20201111-WA0038](https://user-images.githubusercontent.com/74291722/98787744-e2a84300-2425-11eb-9407-7c2c5cb3ba72.jpg)
![IMG-20201111-WA0036](https://user-images.githubusercontent.com/74291722/98787746-e3d97000-2425-11eb-9d60-17da79ed17ab.jpg)

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
Server 1 aswell as server 2

**Notes:**
Please help me

**Comment by KaliaaAndy** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/74291722/98789493-5e0af400-2428-11eb-8094-45cf998d02b6.png)

**Comment by KaliaaAndy** [comment]
Please Resolve this Issue ASAP!
I want Either my EDM cars to be Like as it was before Else Refund me Money in game So I can Again Mod 
and If any additional information needed Please Let me know.

I Hope Devs Can help me in this matter

Regards
KaliaaAndy
(KaliaaEsports)

**Comment by Nuziatella** [comment]
You need more detail on what exactly was happening to cause the loss of the modifications. Did you do the modifications and not put the vehicles away in the garage? Did you get an error of some type? Etc....

As far as refunding you, that's going to be a **_no._** Currently there is no means or way to replace lost items and/or money. Use the search function and you would have been more than aware that refunds, reimbursements, and replacements will not be given.

**Comment by KaliaaAndy** [comment]
@Nuziatella I am Pretty Much Aware Of Stuffs!
I Did Modifications And Also Stored in garage and then after some time i went to garage And as usual took my car out of garage and some error came and game crashed once i came back again all mods of edm cars were gone !!! woof like magic

As far as Refunding Thats going to be a no!
then there is no point of Playing RP when admins and Other Devs Dont even care loss of Player Which is actually a customer.
and as an customer I expect some support!

**Comment by InZidiuZ** [comment]
This is a framework that is being used by multiple different communities. How the different communities decide to handle refunds on cases like this, is up to them.

**Comment by KaliaaAndy** [comment]
@InZidiuZ So Tell Me Where should a Player Go ? to ask For Help!
when we raise complaint in their Discord Server They Give us Link Of GIthub!
When we Seek for Support we are forced to get server Mute for 2 days and more !

So where should We Go!
the mods which are vanished After Sudden Crash of Fivem is surely a bug it happen with my friend too!!

**Comment by InZidiuZ** [comment]
The GitHub is to report issues and bugs or create suggestions for the framework. If you're wanting to be reimbursed, the discord guild of your community would be the place to go, though they may decide to not give you any compensation.

**Comment by InZidiuZ** [comment]
Going to close this issue though as it doesn't really have any new information. See my response on #1485 for more information.
