### ISSUE TITLE
Keybinds doesn't work.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1520]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
If I press somekind of button like example T for chat or P for phone or hotbar to take weapons out then it sometimes doesn't work. Example I'm trying to take pistol out with number 4, sometimes I have to press 1x times number 4, sometimes 4x times, sometimes 5x times. It should always take pistol out at first try but it's not.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Press something example T, P, 1-4.

**Expected Results:**
What are the expected results?
It to work with first try.

**Actual Results:**
What are the actual results?
Not coming out with first try, sometimes have to press 4 times before gun comes out.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia.

**Notes:**
For anything else noteworthy.

**Comment by glocknine234** [comment]
No errors in F8 btw.

**Comment by InZidiuZ** [comment]
This issue should have been resolved with version 3274.
