### ISSUE TITLE
Bug report ( Mounted weapons on PDM vehicles)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1521]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1/
**Summary:**
Write a short summary of what you are experiencing.
Saw after randomly checking a car for upgrade one of the person who bought the car upgraded mounted in LSC and turns out it started firing so I went to check most cars and found few with guns that actually fire. They can kill a player after a few shots from them also when firing them on a player it freezes them on a location infront of the guns itself.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Just take the any of these cars on testdrive - Annis Savastre , Lampadati Viseries, Ocelot Ardent ,Phister Comet Safari the ones that dont have upgrades in the LSC shop choose Mounted Guns and it fires rapid firing bullets which cause damage to player and freezes them on the spot.
**Expected Results:**
What are the expected results?
They shouldn't be shooting or freezing a player in position.
**Actual Results:**
What are the actual results?
They shoot bullets which everyone can hear and see and cause damage to player health and kills them.
## Additional Information
https://youtu.be/tzZctw9gCOI
https://youtu.be/WHNaN1694ho
https://youtu.be/582Wr4dcrYc
 https://youtu.be/pDGRaSFkFi4
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920 x 1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/45ae215bef7a44206c1d112cda06b859
**Server:**
What server/community did this issue occur in?
India WL
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue should be resolved with version 3281.
