### ISSUE TITLE
[Handcuffs] Hardcuffed players in police vehicle.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1523]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine
**Summary:**
Write a short summary of what you are experiencing.
Please remove ability that players who are hardcuffed have ability to come out from vehicle by themselves + use spotlight.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Hardcuffed person needs to be in car and press F so they will come out. Or press G and they could use spotlight.

**Expected Results:**
What are the expected results?
Them not to come out.

**Actual Results:**
What are the actual results?
They can come out.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
These issues have been resolved with version 3298.
