### ISSUE TITLE
[?] Job Announcements

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1524]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
There should be commands like /police, /ems, /government etc. For example: /police Civilians, please stay away from that x area or /ems There is a dangerous virus in the city if you see someone who has it please report him to the EMS.
**Reason:**
Why would your suggestion be a good change to the framework?
Improve RP and this would be so necessary in my opinion.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
