### ISSUE TITLE
[player/ped] DP clothing // Clothing off/on

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1525]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Please add this script dpclothing or something else. https://forum.cfx.re/t/dpclothing-1-0-3-clothing-variations-and-toggles-gloves-vest-top-hair-bag-and-more/1326317 .You can do anything, set helmet visor down/up, take watch off, take gloves off and put them on again, take shirt off etc.

**Reason:**
Why would your suggestion be a good change to the framework?
Would improve RP and would be very cool to take your clothes/accessories off.

**Comment by gighul** [comment]
huge +1

**Comment by glocknine234** [comment]
Same, you can take off literally ANYTHING :D

**Comment by AdeptCL** [comment]
I’ve always said a feature like this would be cool. As someone who plays a biker, actually taking our biker cuts off for patch removals, additions, etc has always been something involved in the roleplay we do. Being able to actually do this, I think will be great.

**Comment by InZidiuZ** [comment]
This has since been added.
