### ISSUE TITLE
[commands] Command not available.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1526]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
All of the players have problems, if you press numpad 4 or 8 then in chat it says "Command not available" and some of the players when they press W then they get "command not available" aswell.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Press W or numpad 1-8

**Expected Results:**
What are the expected results?
It to give nothing in chat.

**Actual Results:**
What are the actual results?
Command not available spamming in chat
## Additional Information
Nobody have active /binds
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia
**Notes:**
For anything else noteworthy.
Most of this happens with police officers.

**Comment by InZidiuZ** [comment]
See #1477. Try resetting your FiveM keybinds.
