### ISSUE TITLE
[game/game] Infinite stamina for animal models

### ISSUE THREAD

**Issue by OPG1233** [InZidiuZ/op-framework-issue-tracker#1527]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? - Yes.

**Summary:**
Write a summary of what your suggestion is about. - My suggestion is that dogs should be able to run for longer than 8 seconds. After those 8 seconds, the ped is forced to walk.

**Reason:**
Why would your suggestion be a good change to the framework? - well first of all it's unrealistic for humans to be able to run faster than dogs. second of all, it's only fair because animal peds are not allowed to use vehicles of any kind and their only transportation is on foot.

**Comment by InZidiuZ** [comment]
All animal peds will have infinite stamina as of version 3493.
