### ISSUE TITLE
Suggestion ( State department can adjust/reduce maintenance)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1528]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There should be an option for state department probably Mayor role or Manager role to have permissions to set and change or reduce maintenance of blocks.
**Reason:**
Why would your suggestion be a good change to the framework?
This suggestion would honestly improve rp in most community where State can promote expensive blocks which some rarely buy with some kind of business rp per say. State and real estate company can rp and maybe settle on reduce cost of maintenance. It will also help State conduct rp of rent reduce of blocks and giving a chance to company owners instead of going bankrupt it kinda would allow them to rework the finances and balance it out rather than it just going bankrupt straight away. Maybe a limit can be set on how much percent of maintenance can be reduce maximum. It will also help economy like in irl companies can get a payment plan and still be in business after recovering bankruptcy.

**Comment by InZidiuZ** [comment]
Blocks' maintenance costs are based on the properties you get with the block, and these are hardcoded for various reasons, and that will not be changed any time soon. If you want cheaper maintenance fees, the cost for the different shells is what needs to be reduced.
