### ISSUE TITLE
[items] Phones

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1529]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Maybe the phone needs a bit of rework, it looks kinda default and would be cool to see new phone. The current phone is been here for like a year or something I think, maybe add a new phone, ability to send pictures through SMS/tweets. If you swim phone can't be used, Maybe SIM cards, Ability to track phone locations by Police only if they are turned ON, Make phonebooths useable, Add new apps to phones, Maybe rechargeable batteries for smartphones, 

**Reason:**
Why would your suggestion be a good change to the framework?
Would be cool and phones are used almost all of the time so it would be actually cool to get a new phone.

**Comment by InZidiuZ** [comment]
Read the README file
