### ISSUE TITLE
Crime Scene cleaning

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#153]
**Name:**
Johan Skylar || Badwolf#3160
**Summary:**
In addition to you adding the ability for police to finding bullet fragments and Blood of DNA test and all that it should be possible to be able to call a cleaner to clean a crime scene and prevent police from finding. it would be nice for there to be special items like detergents or high alcohol cleaners the cleaners can use to clean the blood to prevent police from having access to them

**Reason:**
Why would your suggestion be a good addition to Legacy?

This makes it that people with enough connections could get away with crime like in the real world. This could balance it out and make roleplay more exciting and in depth. It could also create situations where cleaners plan these evidence to implicate a rival or someone else.

**Comment by InZidiuZ** [comment]
Hey,

Closing this for now as it's currently irrelevant.

**InZidiuZ**
*OP-FW Developer*
