### ISSUE TITLE
Increasing /roll limit past 100

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#1530]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

We have been organising a Dice rolling event, and came to realise there is a limit with the /roll command, only allowing rolls up to 100. We want to host a event with cascading rolls

Example
First player rolls 1 in 20000 (/roll 1 20000 = 15499)
next player rolls (/roll 1 15499 = 10030)
next player rolls (/roll 1 10030 = 3203)
next player rolls (/roll 1 3203 = 293)
next player rolls (/roll 1 293 = 29)
next player rolls (/roll 1 29 = 3)
next player rolls (/roll 1 3 = 1)

First to reach the number 1 wins.

Either raising the limit, or creating a new command for higher rolls

![](https://cdn.discordapp.com/attachments/751240255117721700/777683617912062022/20201115185613_1.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?

Allow for more events and RP to come from an existing system in place. Dice rolling can be used as a gambling feature for players to put up money and other items on the line with a risk.

**Comment by InZidiuZ** [comment]
This has been done with version 3353.
