### ISSUE TITLE
[animations/emotes] Being able to shoot while proning.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1531]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Players should be able to shoot with a firearm example sniper while they are proning.
**Reason:**
Why would your suggestion be a good change to the framework?
Would improve RP and would be cool.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
