### ISSUE TITLE
Jerrycan refueling

### ISSUE THREAD

**Issue by DarakhTech** [InZidiuZ/op-framework-issue-tracker#1532]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
Darakh741

**Summary:**
One can use an infinite amount of fuel while using a jerrycan

**Steps to Reproduce:**
Purchase a jerry can ->Use the jerrycan from inventory -> Refuel a vehicle -> Keep it back in the inventory -> Once again use the jerry

**Expected Results:**
On reusing, Jerrycan should have a reduced/null amount of fuel left in it, based upon the first use.

**Actual Results:**
After every use, the jerry can have 100units of fuel in it.

## Additional Information

**Server:**
Legacy India Whitelisted

**Comment by InZidiuZ** [comment]
> Keep it back in the inventory

As in unequipping the jerrycan, then equipping it again?

**Comment by DarakhTech** [comment]
Yes

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3350.
