### ISSUE TITLE
Bug report - Vehicles not coming out of garage

### ISSUE THREAD

**Issue by RyanShlap** [InZidiuZ/op-framework-issue-tracker#1533]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/FlapperShlapper/

**Summary:**
Loaded into the city and tried to pull out a vehicle. Said vehicle was withdrawn but no vehicle appeared. I tried it 3 times with 3 different vehicles and still the same result. Also the issue where the vehicles spawn in as local vehicles and we have to hot wire them.

**Steps to Reproduce:**
Remove vehicle from garage.

**Expected Results:**
Your vehicle shows up when it has been withdrawn

**Actual Results:**
No vehicle appearing as per the clip. 

## Additional Information

**Screenshots:**
No screenshots but I have a clip - https://streamable.com/n1oihi

**Game Resolution:**
1920x1080

**Player Data:**
https://imgur.com/qQWxjcE

**Server:**
Legacy NA/EU

**Notes:**
No notes :)

**Comment by InZidiuZ** [comment]
This is/was likely a FiveM issue, so I'll be closing this. Is it still happening though, or has it stopped since?
