### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1535]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I suggest updating EUP to 8.9 version by Alex Ashfold.

**Reason:**
Why would your suggestion be a good change to the framework?
This update would greatly improve experience from game, especially for players in emergency services. Clothes on the server look totally outdated compared to the newest version of EUP, in an aspect of quality of models and textures, but also in variety of different pieces of clothing. I think having this would make this server stand out in one more positive way, because at least in Poland nobody has it even yet.

**Comment by ReqsoN** [comment]
I think it's really good idea. The newest version of EUP will help put yourself in the role of police officer.

**Comment by InZidiuZ** [comment]
Please redirect this to the assets-related issue tracker
