### ISSUE TITLE
[handcuffs] Fixes for hardcuffed players

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1536]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
Please disable the ability to come out from the vehicle by yourself and turn the spotlight on while being hardcuffed. Also you can't (/suspect in) while the officer is in driver's seat.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Hardcuffed player needs to be in vehicle and press F or G. Type /suspect in while somebody is in driver's seat.
**Expected Results:**
What are the expected results?
Hardcuffed players are not able to come out by themselves or control spotlight, also there should be chance to /suspect in while somebody is in driver's seat.

**Actual Results:**
What are the actual results?
Hardcuffed players are able to use the spotlight, come out from the police car by themselves etc.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Wasn't this resolved in #1493?

**Comment by glocknine234** [comment]
No

**Comment by InZidiuZ** [comment]
I just checked again, and it seems it was resolved in #1493. Remember, updates are only pushed every Tuesday to production servers.
