### ISSUE TITLE
Bug report (PDM Testdrive Refund)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1537]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes
Player Identification:
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1/
Summary:
Write a short summary of what you are experiencing.
So what is happening is that when you give cars or bikes for testdrive sometimes it doesnt return you the $500 deposit and sometimes it gives someone $1500 probably $500 from 2 other people who didnt get it back i guess.
Steps to Reproduce:
Include what steps that are needed in order to reproduce this issue.
Take a bike from testdrive like 4-5 times and driving around and returning it either it returns you $1500 or nothing.
Expected Results:
What are the expected results?
Should return everyone $500 and not $1500 to some 
Actual Results:
What are the actual results?
Gives some people $1500 refund and some people no refund of the testdrive deposit

Additional Information

Screenshots:
If suitable, include some screenshots.

Game Resolution:
What is your game's resolution?
1920 x 1080
Player Data:
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/45ae215bef7a44206c1d112cda06b859
Server:
What server/community did this issue occur in?
India WL
Notes:
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
I rewrote the 'test drive' system so hopefully this will be resolved with version 3348.
