### ISSUE TITLE
[Radio] Tac Channels for PD radio

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1538]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
Make Tac channels for PD so it's easier to us to communicate. For example if you have a pursuit you say "callsign 10-80, TAC 3" and then press numpad 3 then you'll connect to tac channel 3 instantly. Basically, 3 different radio channels to talk in, because if there's 2 different situations example 2 different pursuits then how you going to talk in radio? TAC 1 for numpad 1, TAC 2 for numpad 2, TAC 3 for numpad 3. 

**Reason:**
Why would your suggestion be a good change to the framework?
It's realistic and would be a lot easier to communicate

**Comment by novapurple** [comment]
If you are in a pursuit wouldn’t you want all units to be aware of it ? Seems pretty useless to do this and wouldn’t even imagine doing his in a helicopter where you would constantly be changing radios.

**Comment by glocknine234** [comment]
When there's no active calls, every single officer is in main radio channel. If there's 10-80 he will say "10-80 TAC1" what means "theres pursuit, come to channel 1" And every officer who will be in pursuit is going to connect to tac 1. Also you can't control your helicopter with numpad 1-3

**Comment by InZidiuZ** [comment]
> For example if you have a pursuit you say "callsign 10-80, TAC 3" and then press numpad 3 then you'll connect to tac channel 3 instantly.

`/bind_add tac3 118 /frequency 3`, no? 118 is numpad 9, as numpad 3 can't be found [here](https://docs.fivem.net/docs/game-references/controls/).

**Comment by glocknine234** [comment]
Oh alright.
