### ISSUE TITLE
Ammo saving between pistols

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1539]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
When player loads ammo to gun and police confiscates his gun then he wont lose any ammo. If he takes another gun he has same ammo that he had in old gun.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Load ammo to combat pistol, throw combat pistol away. Buy a vintage pistol and you'll have "free" ammo that you had in combat pistol.

**Expected Results:**
What are the expected results?
When you lose your gun, you'll lose tour magazine/loaded ammo.

**Actual Results:**
What are the actual results?
Ammo saving to every pistol.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is intended behavior. The current ammo system does not allow for ammo to be bound to guns, instead it's just bound to your character. In the future this is intended to be changed.
