### ISSUE TITLE
Addition of addrenaline shots

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#154]
**Name:**
Johan Skylar || Badwolf#3160

**Summary:**
I think it would be a nice idea to add adrenaline shots that could make players run faster and or jump slight higher like the coc effect in N* instead of letting coc have that effect. Having an adrenaline shot could make users have a focus effect like Michael's special ability in the story line for a shot while but not a powerful and for a very short while if the user has a gun equipped. Coc could then be used as a stress reducer and could prevent a user from gaining stress for a longer time while participating in a stressful activity like shooting or driving fast.

**Reason:**
This would be give as the chance to differentiate ourselves from N* and also make coc not as over-powered but just useful enough in criminal activity and would also create variety for users.

**Comment by SteezyRen** [comment]
There is a drink in game that already helps with running faster, although it could use a longer duration than a couple seconds. 

If we are going to use drugs as a form of performance increases that would have to come after stress levels are implemented into the server.

**Comment by jaymssmith** [comment]
yes thats what i was thinking 
this is very vaible when stress system is implemented since coc will be very important then and i know there is a drink that does that but its quite short and an adrenalie shot could be a better version since it would take longer to wear off and if possible will have more advantages than just running. but it will be OP if doesnt affect your stress or increase your stress at a higher level

**Comment by InZidiuZ** [comment]
Hey,

At this time this will not be added, so closing this.

**InZidiuZ**
*OP-FW Developer*
