### ISSUE TITLE
[illegal/burglaries] Adding jewelry items to house robberies,

### ISSUE THREAD

**Issue by xRunnin** [InZidiuZ/op-framework-issue-tracker#1540]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Yes Boss!**

**Summary:**
Write a summary of what your suggestion is about.

**Adding the new jewelry items to house robberies.**

**Reason:**
Why would your suggestion be a good change to the framework?

Adding like silver , gold or even diamond jewelry to houses loot table would add more variety in valuable items acquired.
This can make house robberies/burglary more profitable for criminals. A lot of burglars rob houses for jewelry so this would make sense adding it. Just think of robbing houses and getting 1 diamond necklace or watch.
In few words more content for the house robbery.

**Comment by InZidiuZ** [comment]
This has now been done.
