### ISSUE TITLE
[jobs/mechanic] Suggestions To Increase Mechanic RP

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#1541]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
On behalf of Mechanic department (Legacy Roleplay India) I Ayush Pandit Discord: ayushpandit99#1842  had some suggestions that should be implemented.

1) Review of vehicle and workbench should be only accessible by Mechanic
2) Adding an  " Personal Stash" For Each And Every Mechanic [ just like PD ] & closet where we can directly change clothes and logout from. [This Can Be Implemented In Mosley's Repair Shop As It Has Locker Area]
3) Mechanic should have an official radio channel.
4) Being Able To Go On Duty/Off Duty (Like PD))
5. Adding More Impound Lots At Location: Paleto Bay ,Sandy Shores(adding this is will reduce time and allow more tows outside city)
6. Addition Of Impound Lot Near Sandy Shore And Paleto Bay(this will help to tow more vehicles outside city)
7. Increase The Cost In Retrive To 1000(So That People Prefer To Repair The Vehicle Rather Then To Retrieve)
7. Mechanic's should get custom salaries depending on their Positions 
Some positions & salaries can be like this 
Intern $40
Lead $60
Adept $70
Expert $80
Veteran $90
CEO & Boss/Owner $100
**Reason:**
Why would your suggestion be a good change to the framework?
It will enhance Mechanic RP.. and it will help reduce self-repairs .. addition of personal stash would allow to store material used for repairing so it would keep the players inventory bit free.. also as currently each and every post of mechanic gets same 20 dollar so increasing basic salary according to the post would be beneficial and would make difference of post ..addition of impound lot  will reduce time and allow more tows outside city
[EDITIED AFTER ADDITION OF NEW REPAIR SHOP]

**Comment by Rithvikk05** [comment]
The Work Of Mechanic Is To Tow The Vehicle And I Don't Think You Should Regret Towing Normal [Local] Vehicle Rather Asking For Impound Power If You Are Joining Mechanic Department [Even Whitelisted or Not ] You Should Do It Cause You Joined It By Your Own Wish.


And The Interior And Truck That Would Be  Good. And Salaries 👍

**Comment by acharekarshubham** [comment]
impound power should be give to those people, whose rank are above lead mechanics (role).

**Comment by Rithvikk05** [comment]
> impound power should be give to those people, whose rank are above lead mechanics (role).

Its Not About Rank Why Is The Job Name Mechanic If You Willing To Get Impound Power To Impound Local Vehicles. Mechanic Work is Tow And This Would Be Breaking Mechanic RP For Sure If It Comes. 😃

**Comment by Ronak31032002** [comment]
Even i feel EMS PDM shouldn't have Impound cars option but As mechanics are not available 24/7 we need to give them as it may chaos in that particular area. But looking at the Mechanic side It will create a 100% motivation if they get impound money on the normal cars as well I won't say give 1000$ or even 400$ per vehicle on every impound But give as much as needed It will eventually be no-ones loss and City will be clean there will be work as well And Last time as it was stated by developers that removing such jobs from Life Invader won't be possible as framework runs on many server and many servers don't have these jobs whitelisted. But i would request the developers if possible As Garage 1 on the groove street is the biggest repair shop in all the cities If possible to get a big repair center over there Just like Weazel News I know its not a 2-3 days work But i trust the developers.

**Comment by Rithvikk05** [comment]
If You Are From Legacy Roleplay India :) You Are Getting Salary From Govt. [Mayor] The Salary Given Above Are The Same. And Its A Rule Too If I Am Not Wrong That If You Are Getting Money From Mayor You Are Asked To Tow Local Vehicles Also For Free. Also After Reading Your Point You Are Willing To Have Much Money Then RP Cause You Don't Want To Tow Vehicles If You Don't Get Money For The Same :(.  There Are 5 Repair Shop Do Visit Them You Will Know Very Well. And I Have No Idea About A Developer Stating Removing Such Jobs **[Don't Know Which Jobs]**  😞

**Comment by ayushpandit99** [comment]
> > Even i feel EMS PDM shouldn't have Impound cars option but As mechanics are not available 24/7 we need to give them as it may chaos in that particular area. But looking at the Mechanic side It will create a 100% motivation if they get impound money on the normal cars as well I won't say give 1000$ or even 400$ per vehicle on every impound But give as much as needed It will eventually be no-ones loss and City will be clean there will be work as well And Last time as it was stated by developers that removing such jobs from Life Invader won't be possible as framework runs on many server and many servers don't have these jobs whitelisted. But i would request the developers if possible As Garage 1 on the groove street is the biggest repair shop in all the cities If possible to get a big repair center over there Just like Weazel News I know its not a 2-3 days work But i trust the developers.
> 
> You Are Getting Salary From Govt. [Mayor] The Salary Given Above Are The Same. And Its A Rule Too If I Am Not Wrong That If You Are Getting Money From Mayor You Are Asked To Tow Local Vehicles Also For Free. Also After Reading Your Point You Are Willing To Have Much Money Then RP Cause You Don't Want To Tow Vehicles If You Don't Get Money For The Same :(. There Are 5 Repair Shop Do Visit Them You Will Know Very Well. And I Have No Idea About A Developer Stating Removing Such Jobs **[Don't Know Which Jobs]** 😞
> Talking About Mechanics And Turning Into EMS/PDM Means Like Jealous About Other Department Having Such Powers. And It Was A Power From The Beginning Of Server Not Being Given To Them Recently.
> 
> Rest Points Are Great And Have No Issue. [Just Impound Power To Mechanics Will Break The RP, If Mechanics Will Not Tow Local Vehicles And Will Only Tow Vehicles In Which They Will Get Money]

Regarding Getting Salary From Govt[Mayor] It is just limited to whitelist ... in blacklist  there is just 20 dollars for every post weather it is Intern mechanic or Veteran Mechanic...

**Comment by glocknine234** [comment]
I accept with all of these points. Good suggestion.

**Comment by gamingsdox** [comment]
one more point basic and advance repair kit should be exclusively available at repairshop store at low cost to only mechanics.

**Comment by glocknine234** [comment]
Repair kits should only repair vehicle engine so it will give more point to go to mechanic. Also many people don't go to mechanic they just return their car...

**Comment by Ronak31032002** [comment]
> > Even i feel EMS PDM shouldn't have Impound cars option but As mechanics are not available 24/7 we need to give them as it may chaos in that particular area. But looking at the Mechanic side It will create a 100% motivation if they get impound money on the normal cars as well I won't say give 1000$ or even 400$ per vehicle on every impound But give as much as needed It will eventually be no-ones loss and City will be clean there will be work as well And Last time as it was stated by developers that removing such jobs from Life Invader won't be possible as framework runs on many server and many servers don't have these jobs whitelisted. But i would request the developers if possible As Garage 1 on the groove street is the biggest repair shop in all the cities If possible to get a big repair center over there Just like Weazel News I know its not a 2-3 days work But i trust the developers.
> 
> You Are Getting Salary From Govt. [Mayor] The Salary Given Above Are The Same. And Its A Rule Too If I Am Not Wrong That If You Are Getting Money From Mayor You Are Asked To Tow Local Vehicles Also For Free. Also After Reading Your Point You Are Willing To Have Much Money Then RP Cause You Don't Want To Tow Vehicles If You Don't Get Money For The Same :(. There Are 5 Repair Shop Do Visit Them You Will Know Very Well. And I Have No Idea About A Developer Stating Removing Such Jobs **[Don't Know Which Jobs]** 😞
> Talking About Mechanics And Turning Into EMS/PDM Means Like Jealous About Other Department Having Such Powers. And It Was A Power From The Beginning Of Server Not Being Given To Them Recently.
> 
> Rest Points Are Great And Have No Issue. [Just Impound Power To Mechanics Will Break The RP, If Mechanics Will Not Tow Local Vehicles And Will Only Tow Vehicles In Which They Will Get Money]

I think so you are in a wrong faith that We get salary from Mayor and if we were that thirsty of Money we would have never joined and worked for so long in this department Its just if we could get that money 250 or 300$ per normal vehicle I dont think theres any issue in that whereas i already told my fellow people getting this job as whitelisted and using roles for salary then obviously it will be overpowered and i dont think having salary like PD Ems is any option But getting money from local tows should be definetly an option 
Whereas talking about the rest of the repair shops 75% of server always visits only groove street repair shop Not to worry wherever and however far they are So if we can get a new interior for the same repair shop wont be bad also getting 1 or 2 vehicles in which we can take huge vehicles

**Comment by novapurple** [comment]
If you had this you would have an issue of people towing every single car they see...

**Comment by Ronak31032002** [comment]
> If you had this you would have an issue of people towing every single car they see...

Maybe this will create awareness people are not serious about cars and just recklessly leave it on road park it wherever they want do whatever they want if towing that simultaneously will create a spam and a boost of money but maybe we can even get a solution for this

**Comment by GuArDiAn-ops** [comment]
/impound might be misused hence should remain only with ems and pd for now as it is used only when necessary. Otherwise they will impound for no reason. Maybe some cash for local cars might be a good thing instead of that

**Comment by T4NZIM** [comment]
> /impound might be misused hence should remain only with ems and pd for now as it is used only when necessary. Otherwise they will impound for no reason. Maybe some cash for local cars might be a good thing instead of that

Then mechanics will start impounding all the locals car for money even sometimes gunpoint at the locals to make them come out from their vehicles and then impound it for money. So no need of this...

**Comment by acharekarshubham** [comment]
if such thing happen then his characters will get strike or fire from job permanently

**Comment by acharekarshubham** [comment]
> > /impound might be misused hence should remain only with ems and pd for now as it is used only when necessary. Otherwise they will impound for no reason. Maybe some cash for local cars might be a good thing instead of that
> 
> Then mechanics will start impounding all the locals car for money even sometimes gunpoint at the locals to make them come out from their vehicles and then impound it for money. So no need of this...

if such thing happen then his characters will get strike or fire from job permanently

**Comment by Deggan8** [comment]
In my opinion I think the mechanic RP is fine, the player needs to out the effort into the RP and the money is fine. The only major change to mechanic RP would be a complete overhaul of the Car system and include multiple things such as, oil tank, suspension, brakes etc etc which would include different parts(materials) to fix. What I think that each mechanic shop should hold is their own owners having access to it as a business(regardless of criminals etc) or Lost owns theirs, SOL owns theirs they have access to lock it up and open it and can hire people and give them access to locking system. This doesn't need to involve a pay increase on each "level" of mechanic but allows them to open and close and work in the shop. You could lock all work benches to only whitelisted characters to stop self repairs. I also think each mechanic shop should have a storage system to allow them to store materials ( I understand this could be misused for self storage) however you could limit it to only 5 slots but give it alot of weight as materials are stackable. I agree with the repair kits but maybe only allow basic repair kits in megamall and give mechanics advance repair kits. Also my character doesn't work at flywheels anymore but they should also get all the changes and have their own pc included (personally I prefer the PC to go away and allow the characters to source their own supply through roleplay) but I understand why the PC is there. I also think all repair shops should have multiple repair stations to allow multiple mechanics to work

**Comment by ayushpandit99** [comment]
As Now Main Server Too Made The Mechanic Job Whitelisted I think its good time to implement the above points.

**Comment by ayushpandit99** [comment]
closing this as most of the things are added :) thanks !
