### ISSUE TITLE
Evo livery issue

### ISSUE THREAD

**Issue by Skaithighs** [InZidiuZ/op-framework-issue-tracker#1544]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
The Evo has a red livery on the hood titled "Bandanas imports and customs", It doesn't matter how many times you remove this livery it is still on the car whenever you put it in the garage and bring it back out. It will reappear each time. This isn't directly related but it seems to be the more people that are inside of the Evo the worse it handles and the speed is affected. I understand this is realistic however this doesn't happen with any other cars. The Mercedes still does 230 with 4 people in it.
**Reason:**
The livery on the car is more annoying that you have to remove it each time it is removed from the garage. it's pretty frustrating and as far the speed issue its just more related to the other vehicles that are exclusive.
![image](https://user-images.githubusercontent.com/52269307/100165627-a7405680-2eb2-11eb-9be7-a5907fa47ac9.png)
![image](https://user-images.githubusercontent.com/52269307/100165644-ae676480-2eb2-11eb-8ccb-b8782476b87b.png)

**Comment by InZidiuZ** [comment]
Use the assets-related issue tracker for this.
