### ISSUE TITLE
[vehicles/keys] Engine keybind

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1545]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Make ignition system that if you leave your car while the engine is running so players could steal it without hotwiring and set keybind for the engine to turn it on/off. When you come out from your vehicle while the engine is running someone could enter your vehicle and drive off. Right now if someone tries to steal your car it's not possible because he needs to hotwire it somehow? My suggestion is that vehicle is driveable to everyone while the engine is running, if the engine isn't running then players must hotwire it. Maybe O keybind to turn your engine off/on because it would be more useful if this suggestion will be added.
**Reason:**
Why would your suggestion be a good change to the framework?
Would improve RP and it would be more realistic.

**Comment by InZidiuZ** [comment]
Read point 11 in the README file. The engine keybind can already be done with /command_bind_add, though, so it will not be implemented as suggested here.

**Comment by glocknine234** [comment]
But you can't leave your car engine running while you aren't in vehicle.

**Comment by InZidiuZ** [comment]
Hold F to leave the engine running, @glocknine234

**Comment by glocknine234** [comment]
But if you leave the engine running can /anyone/ go and drive your car without hotwiring?

**Comment by InZidiuZ** [comment]
No, not at this time, though that behavior could be changed

**Comment by glocknine234** [comment]
Okay, that was my point actually to steal cars while their engine is running without hotwiring. But I'm going to close this ticket now, thanks tho.
