### ISSUE TITLE
[?] new low/mid crime activity

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1546]
**Assurance:**
Yes.

**Summary:**
A new low/mid-end criminal activity for 1 or 2 people. A delivery job, that requires a shoot-out with armed peds. Start-up cost of $1000.

**Reason:**
After discussions with different members of the Police Department, it seems other than a potential shoot-out after a bank/jewellery/bank truck. It seems people tend to hit and dip. This blocking any potential cop roleplay from starting. This suggestion I am putting forward is to bring some new variety, but also a new way for criminals to do some "jobs". This will also be random locations spread across the map, meaning you can't just plan before you do it, a getaway route.

This is how it would begin/play out...
There will be a door in - [somewhere like Grapeseed](https://gta.fandom.com/wiki/Grapeseed_Main_Street?file=GrapeseedMainStreet-GTAV.png) - which a door function - like Oxy - will be present. "Press [E] to begin a job for $1,000" will show. This will then give a ping location of one of the potential 4 locations:

- Vespucci Dock/Boat area
- Powerplant area
- Southside Scrapyard area
- Vineyard Carpark area

_These are all just potential areas which can be used. It can be anything with a wide enough space to allow open gun fights._

At this location, there will be a Weazel News Rumpo van (empty trunk), but also 5-6 x armed pedestrians. As a player who has triggered this event, the peds will be alerted to those that shoot them (which means other people can see these peds too). This will bring shots fired alerts to the Police Department which brings their interest into this situation too. Obviously, as shots are being exchanged, they shouldn't just storm in and not value their life. But sweeping up after the shots would bring their RP.

Once the armed peds have been killed, you will be able to grab the Weazel News Rumpo van and drive to a [location](https://gta.fandom.com/wiki/Harmony?file=Harmony-GTAV.png). If I am not mistaken, one of the doors opens at the small gas station (right hand side of the location), which means you can drive the vehicle into it to trigger the delivery of the Weazel News Rumpo van. After this van has been delivered to a location, you will receive items similar to the jewellery store but at a reduced rate. 1 job shouldn't exceed $10,000 (when selling the items). So that it balances well with the start-up cost, plus the other systems like bans/jewellery store/etc.

**Comment by AdeptCL** [comment]
Addition: There should definitely be a cooldown on this to every 15-30 minutes, so people don't hard grind it, or have 6 groups of people spam it. And it should only be able to be triggered with a minimum of 2 Police on duty.

**Comment by glocknine234** [comment]
Little suggestion for areas by me is "Yacht near Vespucci" Yacht would be cool to use and it has interior etc.

**Comment by AdeptCL** [comment]
The Yacht should definitely not be used. It needs to be an open area that can be accessed by a vehicle with wheels.

**Comment by glocknine234** [comment]
Maybe shoot armed peds down in yacht and steal a package that you need to find on yacht, no?

**Comment by AdeptCL** [comment]
Different to this idea. This idea would be a van, that you need to deliver somewhere, after shooting the armed peds.

**Comment by glocknine234** [comment]
Yeah.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
