### ISSUE TITLE
Logs update

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#1547]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Jewelry Items selling logs like the ones of Materials & other items.

**Reason:**
Why would your suggestion be a good change to the framework?
Well, you never know who is the corrupt cop :P

**Comment by InZidiuZ** [comment]
This has been added with version 3385.
