### ISSUE TITLE
 [Suggestion] Taking off / putting on clothing system

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1549]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.
The idea is about to change script of taking off and putting on clothes. Now to do so we need write /hat /mask /glasses which makes awkward roleplay while we are coming down to :
-surgery rp
-spontaneous going out to the beach
-urgent need of changing clothes (being chased)
and many many others. perhaps window that appears after writing /clothesmenu
![image_2020-11-28_135543](https://user-images.githubusercontent.com/71882732/100516070-66ca2c80-3181-11eb-8637-eea001da6d88.png)
And when we trigger "legs" our trousers goes off etc

**Reason:**
Why would your suggestion be a good change to the framework?
Improving overall roleplay potential of spontaneity situations and awkward "/description has no tshirt" when he clearly have one

**Comment by glocknine234** [comment]
#1525

**Comment by gighul** [comment]
did not noticed that, closing then.
