### ISSUE TITLE
Bug report - Chop Shop bug

### ISSUE THREAD

**Issue by RemedyUK** [InZidiuZ/op-framework-issue-tracker#155]
**Reporter:**
remedy#2078

**Summary:**
Vehicles showing incorrectly on the radio, it says 1 place and a road name in a different area sometimes.

**Steps to Reproduce:**
Random

**Expected Results:**
Displayed correctly

**Actual Results:**
As above

## Additional Information

**Screenshots:**

https://imgur.com/PwGPQvs

**Player Data:**

https://imgur.com/undefined

**Comment by InZidiuZ** [comment]
Hey,

The location is found using the vehicle's current coordinates when selected, so this won't be an issue unless it's moved afterwards.

**InZidiuZ**
*OP-FW Developer*
