### ISSUE TITLE
[jobs/activity] SASP / EMS Priority enhancement

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1553]
**Assurance:**
Yes

**Summary:**
As individual priority was discontinued, I feel a boost is needed for members of the whitelisted jobs who put in an extreme amount of effort and still struggle to enter the city. I do not know the current cap for priority with the jobs, but it needs to be raised, or the points system needs to be reworked. Someone who had 30 hours on duty only had low tier job priority. 

A way to rework it could be going off hours on duty - 4 hours minimum for police should not give priority, but instead ~8 hours give low priority, ~14 hours give medium priority, ~20 hours give high priority.

**Reason:**
I know of someone who spend 30 hours on duty, yet still had low tier job priority. With a queue of almost 20 people, he spent more than an hour in the queue to get in, even when he is a valuable asset to the job and needs to be available relatively quickly in most situations due to their role. In general, most SASP/EMS are valuable and should receive better priority the longer they have been on duty for.

**Comment by InZidiuZ** [comment]
Adjustments to the job priority has since been made. There is also an out-of-server 'discord job priority' now.
