### ISSUE TITLE
ped_messages command

### ISSUE THREAD

**Issue by Rithvikk05** [InZidiuZ/op-framework-issue-tracker#1554]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
If We Are Able To Turn On /ped_messages Command To See In Chat Too. And If Possible There Should Be A Command To Turn Off like  /ped_messages off To Stop Seeing The, in Chat

**Reason:**
Why would your suggestion be a good change to the framework?
Just Sometimes When Someone Is Doing /description [Any Messaages] It Keep On Coming On The Chat And It Diverts Mind

**Comment by GuArDiAn-ops** [comment]
/ped_messages works like if you do it a few times to turn them off

**Comment by InZidiuZ** [comment]
...what
