### ISSUE TITLE
No off duty count for EMS

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/op-framework-issue-tracker#1559]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/asttanzim

**Summary:**
Write a short summary of what you are experiencing.
This is only for EMS, after the Alpha 2.13 update, if you go to any "Press E to exit city" option and press E, you go off duty but the bot that makes the log of on duty and off duty doesn't make any off duty log.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Go on duty as an EMS, go to any "Press E to exit city" and press E, it will take you off duty. But there won't be any log that you went off duty.

**Expected Results:**
What are the expected results?
Go off duty and "End of shift, 10-42 BOT" make a log for that.

**Actual Results:**
What are the actual results?
You are off duty but there's just on duty log, no off duty log

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
[On Duty](https://cdn.discordapp.com/attachments/478192950296444968/785026629511675924/On_duty.jpg) 
[Off Duty](https://cdn.discordapp.com/attachments/478192950296444968/785026622780604416/Off_duty.jpg)
[Timestamp](https://cdn.discordapp.com/attachments/478192950296444968/785026628270555156/Timestamp.jpg)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
[Player Data Info](https://cdn.discordapp.com/attachments/478192950296444968/785027580708388884/unknown.png)

**Server:**
What server/community did this issue occur in?
Legacy Roleplay Bangladesh

**Notes:**
For anything else noteworthy.
I'm not sure about the Police but I'm pretty sure that it's same for the Police too.

**Comment by InZidiuZ** [comment]
This has been resolved with version 3536.
