### ISSUE TITLE
Bug report - Items Dissappearing from Trunk, possible trunk dupe

### ISSUE THREAD

**Issue by baroncelli022** [InZidiuZ/op-framework-issue-tracker#156]
**Reporter:**
baroncelli022#9071

**Summary:**
Multiple times I have seen items go missing from my trunk, even in between driving to locations or while I'm standing next to it. This almost always coincides w my vehicle being stolen. Several times in the last 72 hrs, even with multiple log outs. I know there are protections in place, so I am more confused than anything. I do believe it is possible to steal someone car, and farm the trunk for items, possibly using a tow truck as Ive seen one present. There is a player who I believe has done this to me multiple times - duping me out of more than 35k in inventory (please ban this guy if proven true - he rarely logs out which I believe is to preserve the stolen/duped vehicles.)

**Steps to Reproduce:**
Spawn an owned vehicle, log out or just spawn another one. 

**Expected Results:**
Trunk inventory items are not able to be duplicated.

**Actual Results:**
Players can take items out of the duped trunk, unsure what happens at that point.

## Additional Information

**Screenshots:**
Sorry I do not have any with F8, it didn't really click w me what was happening. Here are 2 screenshots a short time apart showing the trunk change from when I ss'd it at the gas station, to when I finished talking to my friend. Never went in the trunk, was in or next to the vehicle the whole time.
For some reason could not get my screenshots in this post. I can send them directly if you think they would be helpful.

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 180 - Job Data: Taxi, Downtown Cab Co., Amatuer 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Not really a bug, and not really an easy way to solve this. Vehicle inventories are just secondary inventories based on the vehicle's plate. You'll just have to make sure not to store too many items in one vehicle, and if it's lost, don't continue to use it until next restart.

**InZidiuZ
*OP-FW Developer*

**Comment by baroncelli022** [comment]
Ok, understood I think. However, just to be clear, so this guy can just keep taking advantage of this?

**Comment by InZidiuZ** [comment]
Well, whenever you open a secondary inventory it's logged, so you could try to make staff look for who's doing it & ban the person.

**Comment by baroncelli022** [comment]
Great to know, thank you for taking the time to reply!
