### ISSUE TITLE
EDM Cosmetics Disappearing

### ISSUE THREAD

**Issue by dxvyxd** [InZidiuZ/op-framework-issue-tracker#1561]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198150253624/

**Summary:**
Write a short summary of what you are experiencing.
I bought the Nissan GTR from the Exclusive Dealership about a week ago and i bought around 15k in cosmetic upgrades. When i stored the car and pulled it out, it was perfectly fine and looked the same with all the same upgrades. However after a server restart, I pulled my GTR out of the garage and all the upgrades were gone. I thought this was a one time bug where if i bought the cosmetics again it would stay. But this has happend twice now and i believe it happens with alot of cars, not just the GTR.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
From what i have heard it only happens to Exclusive Dealership cars:
Buy an EDM car
Upgrade it/Put cosmetics on it
Store it
Wait for a restart/Force a restart
pull it out.

**Expected Results:**
What are the expected results?
The car should come out of the garage with all the cosmetics etc.

**Actual Results:**
What are the actual results?
Its almost like the car reset after the server restart. All the cosmetics disappear.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Before restart:
https://prnt.sc/vwxx6k
After restart:
https://prnt.sc/vwxxka

**Game Resolution:**
What is your game's resolution?
2560x1440

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://prnt.sc/vwxwjf

**Server:**
What server/community did this issue occur in?
Main server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This bug is more complicated than what said in the repro. I've commented on this matter a few times previously, but basically, this won't be fixed until the vehicle modification system is rewritten.
