### ISSUE TITLE
[New Prison] Prison enhancement.

### ISSUE THREAD

**Issue by hypeisrealx** [InZidiuZ/op-framework-issue-tracker#1562]
**Assurance:**
Yes

**Summary:**
Current prison interior is buggy and empty. I suggest this one https://www.youtube.com/watch?v=1r4qfFCjwag&ab_channel=UncleJust. It's much better and not laggy, it has much better hitboxes, much more prison cells. The new prison has much more potential for good jailRP for PD and for crime.
**Reason:**
Overall I think this is a improvement for good cause. Has a better potential for better rp as i said.

**Comment by gighul** [comment]
+1

**Comment by Reyess14** [comment]
good idea

**Comment by ChudyBykk** [comment]
good idea

**Comment by Piotr18** [comment]
Good idea

**Comment by AdeptCL** [comment]
Commenting does nothing. React to the post with a thumbs up.

**Comment by gighul** [comment]
@InZidiuZ Could you tell us if its somewhere in your backlog?

**Comment by InZidiuZ** [comment]
Read the README file. Use the assets issue tracker for assets-related issues.
