### ISSUE TITLE
[game/phone] BurgerShot speed dialer like PD,EMS,Taxi

### ISSUE THREAD

**Issue by ppthegamer** [InZidiuZ/op-framework-issue-tracker#1563]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is about adding speed dialer like PD, EMS, Taxi, and Mechanics.

**Reason:**
Why would your suggestion be a good change to the framework?
As the BugerShot delivery is added to the server if the speed dialer comes for BurgerShot it would be better because in the Indian WL server BurgerShot was started before the BurgerShot delivery came and people ask for home delivery and it's hard to deliver the burger at the exact location. If it is added players can do delivery to normal civilians and instead of delivering to locals and it would increase the RP too. Players can make their own menu for variety I have attached which we are using
![Menu](https://user-images.githubusercontent.com/63738935/101317736-18094a80-3885-11eb-9551-7390509ba453.jpg)
.

**Comment by Heba6** [comment]
I totally agree with this idea .. this dude is doing great burger shot RP

**Comment by InZidiuZ** [comment]
This has since been added.
