### ISSUE TITLE
Lost Items (40 Cocaine Bags)

### ISSUE THREAD

**Issue by TheDireMan** [InZidiuZ/op-framework-issue-tracker#1564]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Player Identification:**
What is your steam profile?

https://steamcommunity.com/profiles/76561198143888859/

**Summary:**
Write a short summary of what you are experiencing.

i have lost 40 cocaine bags in a locked bike and Silo a staff members said that it was a scuff issue and it should reappear after tsunami and they have not returned.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

40 bags go into a bike
Bike Blows up
Pulls bike out of the garage by "retrieve" 
checks trunk not there

**Expected Results:**
What are the expected results?

Losing the items

**Actual Results:**
What are the actual results?

Lost my shit

## Additional Information

40 bags gone witness Jake Jennings he put them into the bike and I confirmed it

**Screenshots:**
If suitable, include some screenshots.

None 

**Game Resolution:**
What is your game's resolution?

1920 x 1080 1080p

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

Char ID 21089

**Server:**
What server/community did this issue occur in?

Legacy EU / NA

**Notes:**
For anything else noteworthy.

I hope I can get my items back it took me a while to get them and this is my first time losing something and it is something major to me.

**Comment by InZidiuZ** [comment]
I tried retracing your logs to see what had happened, but I couldn't find out where you had taken the items into the bike's inventory. Though on the other hand, it seems like you found the items on the 10th again. Will close this report as it's not of much use.
