### ISSUE TITLE
"Missing Locale" Scuffed UI 

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#1567]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/dcs_281/

**Summary:**
Write a short summary of what you are experiencing.

Due to me having a horrible PC that progressively gets worse by the day.. when my PC hits max CPU Usage or Memory Usage (Too many tabs, programs, etc. open), it "scuffs" me out whilst in the city and also closes the program or tab that I cam opening (which is a PC issue). However, when it does this, I mess up while in the city and have issues such as not being able to "use" items or open my inventory. When I try to take a soft nap, I am greeted by a "missing locale" UI, and the main menu makes it seem like I am not on the main server, as it says things such as "OP-Framework". and saying some interesting things in the changelogs while in the main menu LMFAO. I don't know if this is just my PC being horrible, if so... then I am probably the only one that could get it, but was just reporting it due to it being an issue maybe? idk.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Obviously you would probably need a terrible PC. I personally had a Google Doc that had lots of info on it as well as Spotify which is why my PC's CPU/Memory hit it's max limit.

**Expected Results:**
What are the expected results?

I expect for my PC to blackscreen and then for me to not be able to enter my inventory and for me to get the "missing locale" UI issue.

**Actual Results:**
What are the actual results?

What I expected is what had happened the 3 times that this has occurred. A hard nap fixed it all 3 times and I was then back to normal.

## Additional Information

This might not be an issue, but just my PC being garbage, idk.

**Screenshots:**
If suitable, include some screenshots.

https://cdn.discordapp.com/attachments/752369678298644621/785034323626950656/unknown.png

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

Main Server / International

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Are there any errors when this happens?

**Comment by InZidiuZ** [comment]
I've made some changes and on version 3548 and later, this is unlikely to still be an issue. If it happens after that version, please check your F8 console for errors & either reopen this issue or create a new one.

**Comment by DCS281** [comment]
I didn't check my F8 Console when it happened, but it seems me restarting my PC has made it not happen again.
