### ISSUE TITLE
Suggestion: Add a gun licence and a feature in gunshops where u can buy guns with only licence.

### ISSUE THREAD

**Issue by Lumi322** [InZidiuZ/op-framework-issue-tracker#1569]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
A new gun licence feature that can be used to buy guns. Only the police could give out the licence.
Also adding a new cmd where police could check the licence and take it away.
**Reason:**
Why would your suggestion be a good change to the framework?
Less DM, less RDM adds more roleplay.

**Comment by InZidiuZ** [comment]
Read the README file
