### ISSUE TITLE
Drug Activity to those unemployed only

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#157]
**Name:**
SteezyRen#2828

**Summary:**
Currently, there are people who stay clocked on as a mechanic for the convenience of being able to repair vehicles but aren't actually doing work as mechanics cause they are focusing their time on drug runs. Not saying all people do this but would rather take out the option all together if someone is going to accept calls as a mechanic while running drugs. I even found a taxi cab once at weed pick-up and not sure if it was a locals car or not but that was one more taxi that was unavailable to take calls.

What I suggest is that if you want to have the ability to use your 'E' ability on any of the functions for drugs it would require you to not be "clocked-on" as Taxi or Mechanic since those two jobs can be called upon by people. 

**Reason:**
I want to be able to clock in as a mechanic and have people actually phone out to me instead of just repairing a car and seeing a random mechanic come in, fix their stuff, and leave but not taking calls. Mechanics aren't just driving around in a sedan. There is nothing they can theoretically do as a proper mechanic while doing that.

**Comment by Scrubject** [comment]
Guilty as charged but I actually agree. Had this idea as well and I think it would be a good change for anyone serious about being a mechanic but people could still pick up the job whenever they need repairs. However i think anything that could be done to fix that would cause more problems than it would solve as if your car breaks down and no mechanics are on you'd be SOL.

**Comment by SteezyRen** [comment]
They would only be SOL if they are too lazy to go to life invader and switch jobs in the event that there are no mechanics. @Scrubject you are just one of many people who do that. In fact, last night I did everything but mechanic work while my current job was a mechanic but it wasn't an issue simply cause I didn't get a single call that entire night.

In the given moment, if you aren't grinding transporter you are a mechanic (select few who actually RP other jobs) while doing whatever you want.

**Comment by Scrubject** [comment]
@SteezyRen I meant that you would be SOL if they made it so that you couldn't just swap to mechanic, the problem previously addressed. "People could still pick up the job whenever they need repairs..."

**Comment by InZidiuZ** [comment]
Hey,

Anyone are able to repair their own cars, which is the intention. We're not trying to combat this, as the "mechanic" job was replaced by a "towing" job.

If you wish to repair your car, and have the materials, then sure. Of course it removes some RP from the people that wish to be a mechanic and help others, so the solution to that would be whitelisting mechanics again, but then we'd have a constant lack of mechanics, and would have to bring back repairs in LSC, which isn't something I'm interested in.

There's no really solving this issue, so why even try?

Other jobs are the same too, our goal isn't too force all the taxi-drivers to pick up customers as soon as they get a call, they do so if they are able to in that particular moment.

**InZidiuZ**
*OP-FW Developer*
