### ISSUE TITLE
Can't enter police vehicles.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1573]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
GlockNine

**Summary:**
Write a short summary of what you are experiencing.
When someone is already on passenger seat in the police cruiser then driver sometimes can't enter to driver seat until passenger comes out and steps in after driver.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Let the passenger sit on passenger seat then let the driver sit in the driver seat whilst passenger is in passenger seat.

**Expected Results:**
What are the expected results?
Driver should be able to enter the car at all the time while passenger is on the passenger seat.

**Actual Results:**
What are the actual results?
Can't go to driver seat while passenger is on passenger seat.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Estonia

**Notes:**
For anything else noteworthy.
No, the police car wasn't locked or anything, It happened to me like 3-4 times today and yesterday.

**Comment by InZidiuZ** [comment]
This is likely to be a FiveM/OneSync issue. Feel free to reopen this or create a new issue if it's still an issue in 2-3 weeks.
