### ISSUE TITLE
Garage retrieval not taking cash

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1574]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561198185121513/

**Summary:**
So when I go to any garage, and try and retrieve my vehicle for 250 dollars. It says I don't have enough balance in "either" accounts, but I have 1.9k on me.

**Steps to Reproduce:**
Make it so it takes your cash form you when retrieving a vehicle from the garage.

**Expected Results:**
The expected results are that when you retrieve a vehicle from the garage it takes your cash from you. 

**Actual Results:**
The actual results is that it doesn't take your cash from you when it should.

## Additional Information

**Screenshots:**

Picture of the bug: https://gyazo.com/f5de57aa6ae41291454a043f226d0e5d
F8 Console: https://gyazo.com/d291069e956d0c1edd974155057b9d38

**Game Resolution:**
1980x1080 or 

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/f0578f2de6a4615c487bd40de149593f

**Server:**
Legacy EU/NA (The best one of them all)

**Notes:**

**Comment by InZidiuZ** [comment]
This issue has now been resolved with version 3588.
