### ISSUE TITLE
its a request . if it is possible please add more stylish PDM Cars !!Suggestion

### ISSUE THREAD

**Issue by harrybbbbbbb** [InZidiuZ/op-framework-issue-tracker#1575]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by InZidiuZ** [comment]
Read the README file
