### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HARSHGHETIYA123** [InZidiuZ/op-framework-issue-tracker#1577]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561199091232872/

**Summary:**
i mantion 29 object is underground so i can't move. this is a one type of wall bug. so i try all but 29 object (furniture) not move.
so please help me.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
set storage in mantion.

**Actual Results:**
it is underground.
## Additional Information

**Screenshots:**
![20201217133748_1](https://user-images.githubusercontent.com/76151882/102465326-8a431180-4073-11eb-8e5b-a2700640cf60.jpg)

**Game Resolution:**
1980*1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![20201217134335_1](https://user-images.githubusercontent.com/76151882/102465358-9202b600-4073-11eb-82ee-522b2742fef0.jpg)

**Server:**
lagecy roleplay 1

**Notes:**
please fix this bug because in storage mamy type of item avalible

**Comment by InZidiuZ** [comment]
Read the README file
