### ISSUE TITLE
[weapons] adding newest weapons from dlcs

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1579]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I'd love to see on the  server all new weapons added in GTA online dlcs. I'm talking about perico pistol, combat shotgun, military rifle, ceramic pistol and navy revolver. Of course all of them would be weapons obtainable from gunrunning, maybe ceramic pistol could be legally purchasable from ammu-nation or at least easly found in house robberies.

**Reason:**
Why would your suggestion be a good change to the framework?
These weapons can't be called OP in comparison to weapons that are already on server and every new gun is some addition to diversity on the server.

**Comment by glocknine234** [comment]
Can't add them unless fivem makes a new update

**Comment by InZidiuZ** [comment]
The DLC weapons as well as all other things that come with them (vehicles, maps, features, etc.) will be added once it's available in FiveM on a stable build.
