### ISSUE TITLE
Services on phone and calling out to them

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#158]
**Name:**
SteezyRen#2828

**Summary:**
If there are no mechanics or taxis in the city and you don't know so you reach out for one there is no way they are just not checking their phones or if there are actually any taxis. So instead of just waiting for a response on your phone if there are actually no mechanics or taxis on duty then a text should auto-generate back to the sender saying "No one is available to take your call"

I don't think this is something that is necessary for SASP/EMS as it can be a form of powergaming.

**Reason:**
I believe that it would be useful to know if there are any mechanics/taxis in the server without having to tweet "Is there any mechanics/taxis in server X"
I think I texted taxis 3 times and just waited patiently as I needed a ride to my car that was rather far to run to.

**Comment by InZidiuZ** [comment]
Hey,

Will not be making any changes to the current phone as a new one is in the works (see "Projects"), will note this down though, and if still relevant for the new phone, take this into consideration. Closing for now.

**InZidiuZ**
*OP-FW Developer*
