### ISSUE TITLE
[game/inventory] attachments and tints for weapons

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1580]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
It would be great if you could generally add attachments and tints on server. So I'm thinking about system similar to normal gta. In ammu-nations players would be able to modify their weapons and equip all attechments available in the game, of course except explosive rounds or any other considered OP. This is my idea how to implement this feature, but I would really love to see it added on the server in any other way.

**Reason:**
Why would your suggestion be a good change to the framework?
This would make guns much more visually appealing for players and it won't change the balance between different fractions on server, because it would accessible for everybody.

**Comment by twooot** [comment]
Attachments have been added

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
