### ISSUE TITLE
[Police station] changing police station to different one

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1581]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I just suggest changing Mission Row police station to this one,
link to preview on youtube:
https://www.youtube.com/watch?v=QNixFfwvzCY
link to all files:
http://www.mediafire.com/file/1ilfcvh0xberrw4/Cowboy_-_MRPD_-_Update_3.0.zip/file

**Reason:**
Why would your suggestion be a good change to the framework?
This police station is offering much more features and visual update compared to the current one. For me the best one of them is normal full-sized garage, but also the shooting range if it could be scripted same way as shooting ranges in ammu-nations.

**Comment by ultrahacx** [comment]
Wow. Never saw people pirating and leaking things so confidently.

**Comment by InZidiuZ** [comment]
Use the assets issue tracker for assets-related issues.
