### ISSUE TITLE
[game/miscellaneous] Creating scenes

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1582]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
New cmd called /createscene [duration] [text] and you would be able to leave /do message somewhere. Example /createscene 30 minutes this window is broken. It's same like leaving a note somewhere, but instead of note you could leave a /do cmd somewhere.

**Reason:**
Why would your suggestion be a good change to the framework?
Improve RP.

**Comment by DaxterPancake** [comment]
I believe this would be benificial to the roleplay on our servers.

Currently in the NA/EU server we have a serial killer who is using the notepad system to roleplay evidence around bodies. With the addition of scenes, the killer would be able to stage the scene easier. It could also be used for setting up shops/burgershot/selling cars.. anything you can think of.

**Comment by CreamSlush** [comment]
This should be looked at again. This was brought up in gang suggestions and people seeming to be on board with something like this implemented. It can enhance any type of RP and doesn't just benefit one area.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
