### ISSUE TITLE
#police-timestamps does not populate 10-42s on game crash/force quit

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1583]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/designatio/

**Summary:**
Write a short summary of what you are experiencing.
#police-timestamps channel on Discord does not populate a 10-42 message sometimes when police force quit with f8+quit or their game crashes always. It use to make a 10-42 message almost every time someone would f8+quit or crash but now rarely does. This is causing issues with checking activity for police.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Go 10-41 on-duty and a 10-41 message will populate. Upon your game crashing or f8+quitting, a 10-42 timestamp will likely not populate. 

**Expected Results:**
What are the expected results?
Force quitting or game crashing should make a 10-42 message in #police-timestamps.

**Actual Results:**
What are the actual results?
Force quitting or game crashing does not make a 10-42 message in #police-timestamps most of the time.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![image](https://user-images.githubusercontent.com/68749716/102674235-59420a00-4163-11eb-9197-44df854bd05e.png)
Screenshot shows BladeDance having multiple 10-41 messages in a row with no 10-42. He either quit or crashed and a 10-42 message was not populated. 

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
NA/EU main server.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3616.
