### ISSUE TITLE
Bar and Club job cannot use designated doors with keys

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1585]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/id/mattxiv

**Summary:**
Players with the Bar and Club job cannot unlock and lock doors to bars.

**Steps to Reproduce:**
Set your job to Bar and Club, department to Bar Jobs and position to Bar Owner and try to lock/unlock a door at vanilla unicorn

**Expected Results:**
The door is able to be locked and unlocked

**Actual Results:**
Nothing happens

## Additional Information

**Screenshots:**
https://prnt.sc/w63i9r

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 20 - Job Data: Bar and Club, Bar Jobs, Bar Owner

**Server:**
EU/NA #1

**Notes:**
This happens for all individual Bar Jobs, such as Owner, Manager, Security, Bartender.
This was tested at Bahama Mama's and Vanilla Unicorn

**Comment by InZidiuZ** [comment]
The 'Bar and Club' job has now been added to all these interiors as well. Previously it was just the 'Business' and their corresponding departments that worked. This change will be live with version 3617.
