### ISSUE TITLE
[game/objects] Unmoveable and/or unbreakable objects for Police/EMS

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1586]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Using the spawnobject or /so tool, you can spawn cones, barriers, spikes, dummies, and targets. There should be an option to have the object spawn like normal (can be easily moved and broken), spawn completely frozen (cars, people, etc. cannot move the object), or unbreakable (cars cannot break barriers). 

Having objects like cones and barriers that cannot be broken would be wonderful for creating road blocks, checkpoints, or blocking off crime scenes as police WITHOUT the cones and barriers being _constantly_ moved and out of sync for everyone. If they were frozen, they would all be in the same place for everyone. 

Having barriers or targets that could not be broken would be useful as well. Making a barrier frozen is great but if it can be broken by a car it simply makes a mess and puts things out of sync for everyone. This one is not so necessary considering it might be powergaming if used improperly, but if used properly it would be a good addition. 

Having more objects, like floodlights, police checkpoint signs, stop signs, or traffic signs be able to be spawned by police would also be a great addition.

**Reason:**
Why would your suggestion be a good change to the framework?

Having frozen and/or unbreakable objects would keep everything in sync and in the same place for all players and not have the hassle of them moving and breaking everywhere when setting up crime scenes, roadblocks, or checkpoints. Having all the objects synced for everyone by being frozen would create more cop/traffic RP through checkpoints.

**Comment by InZidiuZ** [comment]
Spawned props that can move (like barriers and cones) will now be properly networked, so they won't desync. Non-networked props (like spikes) will be frozen in position. NPCs should now also respect the barriers more, instead of just randomly ramming them.

I'll also note down the suggested props & see if they can be added.
