### ISSUE TITLE
[weapons/weapons] Addition of Firing Modes to weapons .

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1587]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Ability given to the player to choose between the available firing modes supported by that particular weapon.

**Reason:**
Would put the firing system to a whole new level , save bullets and it might save your ass at a gun fight. 

Video link :
https://imgur.com/a/x7T11Nr

**Comment by Doughnut2001** [comment]
Holy shit this would be good, or give ammu nation the ability to sell the semi auto, less hard hitting versions of class 2's and 3's, would definetly be interesting to see and could add to the PD RP as well

**Comment by twooot** [comment]
This is already a feature actually.
Full Auto: Hold down your left mouse button
Semi Auto: Click your left mouse button repeatedly
