### ISSUE TITLE
[game/phone] Improve phones

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1588]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Could you guys make it that if we are near someone who gets a phone call we could hear the ringtone and caller speaking in the phone? Also if we take a phone away from someone we could see his contacts, messages etc.

**Reason:**
Why would your suggestion be a good change to the framework?
Would Improve lot of rp.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
