### ISSUE TITLE
[garage/gates] Remove the gates of public garages

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1589]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Please remove the gates of the public garages
**Reason:**
Why would your suggestion be a good change to the framework?
They never open and you have to ram through them which will break your car + some garages spawn your car through the gate and the car will be so broken.

**Comment by InZidiuZ** [comment]
These were automatically removed previously, but due to a mistake, that stopped happening. The issue has since been resolved.
