### ISSUE TITLE
Lottery Tickets

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#159]
**Name:**
SteezyRen#2828

**Summary:**
This is a huge shot in the dark but here goes nothing.

A lottery ticket system in which buying a ticket costs $X per ticket and it's 3 numbers from 1-49 that is selected by the purchaser and every few days numbers are generated on discord with winning numbers and how many winning tickets there are. Upon being the winning ticket they would be able to sell the ticket with set numbers for the prize pool. No winners = pool gets bigger. 

If you wish to eject money from the server take a 10% fee from the winning prize. 

Holy hell as I type this and picture the coding it seems like it could be a nightmare

**Reason:**
I think it's something that people can get excited for and people will create lottery pools, etc. Something that I haven't seen any server pull off and can definitely see this being closed as it seems like a nightmare to do lol

**Comment by AmokBSN** [comment]
Not too much of a fan of lottery tickets. I remember in the nuked city, first day my friend bought a ticket and 30 mins later had $150k, almost wanted to puke in my mouth. 

I get it's all luck based but the economy would get a little out of control unless winnings were capped at 5k-10k

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
