### ISSUE TITLE
[game/objects] Add ATM and garage blip at docs workshop.

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1591]
**Summary:**
Write a summary of what your suggestion is about.
Plain and simply to add ATM and garage blip at docs workshop which is attached to screenshot below.
![atm](https://user-images.githubusercontent.com/71882732/103080684-a1838100-45d6-11eb-857a-5b96066b1443.png)

**Reason:**
Why would your suggestion be a good change to the framework?
Purely RP background, this is quite far away from any ATM or garage and people often forget to either take money with them or have a little amount of time and may need to put back the car in the garage and log off. It would be small thing but 
comfortable solutions for players.

**Comment by InZidiuZ** [comment]
Use the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for this.
