### ISSUE TITLE
[game/security_cameras] Addition of home security cameras 

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1593]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
With this addition the players will have access to their property cameras as well as have access to there doorbell cams. 
We can make this feature mobile (similar to /seccam) and have access to all the property cameras or we can only use the doorbell cam when the player is inside their property  

**Reason:**
Why would your suggestion be a good change to the framework?
1. This would increase rp
2. Avoid unwanted guests
3. Level up the property features.

**Comment by AdeptCL** [comment]
I personally just think this would be a useless feature to bring that would take up server resources and development time. How would it bring more roleplay?

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
