### ISSUE TITLE
[jobs/police] More PD callouts

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1594]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Please add more PD callouts to chat like Reckless driver (High speed, Crashing into posts, walls etc. , person seen with a firearm, Fight going on (Player is punching NPC), Driveby etc.
**Reason:**
Why would your suggestion be a good change to the framework?
Improve RP and this would be more realistic.

**Comment by glocknine234** [comment]
+ Commands if this update will take effect like: /cc - /clearcallouts which can be used only by High ranks in PD like Captain and Commissioner to clear all the callouts in the chat.

**Comment by Doughnut2001** [comment]
> * Commands if this update will take effect like: /cc - /clearcallouts which can be used only by High ranks in PD like Captain and Commissioner to clear all the callouts in the chat.

We can already do /cls to clear the chat, why would we need to have a command that does the same for only 2 people that are mostly off duty?

**Comment by glocknine234** [comment]
What are you talking about? You can only delete CHAT for everyone or for yourself, If there's a situation where you would want to delete callouts in the chat for ON-Duty officers then you're supposed to /clsall and everyone lose their chat? I don't get your point

**Comment by AverageStatistic** [comment]
> What are you talking about? You can only delete CHAT for everyone or for yourself, If there's a situation where you would want to delete callouts in the chat for ON-Duty officers then you're supposed to /clsall and everyone lose their chat? I don't get your point

??? Cops can just do it for themselves if they dont want the chat box to filled with new calls. (/cls)
