### ISSUE TITLE
[game/death] Revamp Ragdoll Physics

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1595]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes, I have

**Summary:**

Making Ragdoll physics last longer instead of it being an immediate death animation if possible, like giving them 5 seconds to ragdoll

**Reason:**

It breaks immersion and it teleports bodies when they fall from cliffs/get ran over by locals, in car crashes the individuals always go down where the car impacts, not where it stops, people end up in unrecoverable locations when falling from cliffs, making it impossible to help them to pillbox even with helicopters, since you can't really carry people inside of them, even as police.

it would be a lot more immersive if it were possible to revamp ragdoll physics.

**Comment by glocknine234** [comment]
If ragdoll is being used many people can't see dead bodies cause of the sync, people are unable to carry them out from the vehicle if they're dead etc. It looks so cool how the people die with animation + If ragdoll is being used and player dies it will drop the body in unrealistic way like he has broken bones.

**Comment by Doughnut2001** [comment]
> 
> 
> If ragdoll is being used many people can't see dead bodies cause of the sync, people are unable to carry them out from the vehicle if they're dead etc. It looks so cool how the people die with animation + If ragdoll is being used and player dies it will drop the body in unrealistic way like he has broken bones.

i'm talking about giving them like 5 seconds to ragdoll and then go down so that it doesn't look like they teleport, and the euphoria technology that gta v uses is very far from broken joints.

**Comment by AdeptCL** [comment]
Ragdoll improvements would definitely make things more realistic. A 3-5 second period in which the body actively falls over/hits the ground rather than just teleporting to a straight passout animation.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
