### ISSUE TITLE
[jobs/police] Change EMS and PD calls to 911 in chat.

### ISSUE THREAD

**Issue by glocknine234** [InZidiuZ/op-framework-issue-tracker#1596]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
If PD or EMS gets a callout then it will come to Chat saying "911 Dispatch (callout id): (Location) (message)" and everyone in PD or EMS will see this. EMS would able to see EMS and PD calls and PD would be able to see PD and EMS calls. I don't think that callouts should come to the phone anymore and it's just better for PD and EMS that they get their callouts in the chat. Also a new command something called "/trace (callout ID) and it will set a waypoint on the map where that callout was made.

**Reason:**
Why would your suggestion be a good change to the framework?
Would be comfortable to see EMS and PD callouts both for Officers and Medics.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
