### ISSUE TITLE
[*] Find Zombie Pills 

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1598]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Add Zombie Pills to House robberies, and garbage collection.
**Reason:**
Why would your suggestion be a good change to the framework?
Zombie Pills were very fun to use while the advent calendar was around and they were going for around 2-3k for a pill so it had a good economic price that came naturally , now there is no way to obtain them. So a good way IMO to keep them around in the city is to add them to house robberies and garbage collection. would entice people to rob houses as well.

**Comment by AdeptCL** [comment]
Zombie pills should be a seasonal feature, and not something that is just in constant rotation imo.

**Comment by InZidiuZ** [comment]
It's *possible* to find them through the garbage job now, though they'll be very rare.
