### ISSUE TITLE
MC Patches in Decals

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#160]
**Name:**
Scrubject#1646 (Seth Ramsey)

**Summary:**
I think that it would be great if using the Decal tab in clothing, we could access the MC Patches present in GTA Online's biker update. I'm referring to the patches that show up on you vest/jacket when you're in an MC displaying your rank.

 I'm not sure if there would be any issues using the very textures/models as they were added as an update to GTA Online, but they would be nice to have for anyone Rping being in a club, Lost MC or otherwise.

**Comment by InZidiuZ** [comment]
Hey,

I believe all the available decals are already in the clothing system. If not, though, then I have no idea on how to add the "MC" ones in. At one point I'll probably be revamping the entire clothing system, maybe I'll figure it out then, but for now I will close this.

**InZidiuZ**
*OP-FW Developer*
