### ISSUE TITLE
Schlagen GT cannot drive on sand/dirt (check video linked)

### ISSUE THREAD

**Issue by Jackieskii** [InZidiuZ/op-framework-issue-tracker#1600]
when trying to drive the Schlagen GT (PDM car) on sand or dirt, the car just spins its wheels and barely moves an inch. have tried storing it/retrieving it. nothing works, seems to be an issue with the cars code.

video link: https://streamable.com/9u836v

**Comment by AdeptCL** [comment]
This is an assets issue, please redo this [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose).

**Comment by InZidiuZ** [comment]
Read the README file
