### ISSUE TITLE
[*] Longer Range on Assault Rifles

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1602]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I have

**Summary:**
After some shooutouts today i think we can agree that the Range on the Assault rifles is painfully short, sometimes as a criminal you can be shooting at a helicopter and it won't get hit if it's like 100 meters away and same goes from the helicopter to people on the ground.

Clip: https://clips.twitch.tv/PreciousConcernedStarPJSalt (this happened while VIP's were in)

This also removes the option for people to be able to flank others from far away in active shooting situations
some real examples:
- I was on one side of the big bridge that goes over the river near sandy and there was people on the other side of it shooting at officers and air one, i was taking shots at them and none of them would hit due to range, even though i had my sights directly on them.
- Pd was on a shootout on a building that 7 other criminals were holding, i set up across the highway to try and take mid range shots at them and they would not land because of range
- There was a shootout after a jewellery store where suspects would have the range to hit us with their .50 cal pistols but we couldn't reach them with our Combat pistols or our rifles from the same distance.

**Reason:**
People would be able to shoot further than 100-200 meters with rifles adding toward marskmen being a possibility in Criminal Roleplay or Pd Roleplay in active shootout situations, possibly adding to better tactical planning and longer range engagements.
And it's pretty unrealistic that a Rifle made for long engagements Can't really do long engagements due to how the city is wired.

**Comment by Doughnut2001** [comment]
edit: wrong fuckin clip lmao

**Comment by InZidiuZ** [comment]
Ranges on bullets have since been increased. If you'd like to suggest additional changes, please do so in the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
