### ISSUE TITLE
YellowJack Keys

### ISSUE THREAD

**Issue by Deggan8** [InZidiuZ/op-framework-issue-tracker#1603]
The keys for Yellowjack aren't working. There is no Prompt to lock and Unlock it. Checking other Bars this is showing the prompt in order to lock and unlock the bar.

**Comment by AdeptCL** [comment]
Is this still an occurring issue? @Deggan8

**Comment by Deggan8** [comment]
Just seen this, yes Currently there is no keys to yellowjack and doors are always unlocked

**Comment by glocknine234** [comment]
Set job: Business
Set department: Bar
Set Position: Barman

**Comment by InZidiuZ** [comment]
Read the README file
