### ISSUE TITLE
New Mission Row Police Department Interior

### ISSUE THREAD

**Issue by brennan-ennis** [InZidiuZ/op-framework-issue-tracker#1604]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion includes taking and putting in the MRPD Interior sold by Gabz on his website 
(found here: https://www.gabzv.com/products/mission-row-police-department)

**Reason:**
Why would your suggestion be a good change to the framework?
The new interior could create lots of new roleplay scenarios due to all the inclusions it has. A press room, reception room, new interrogation rooms, and some training rooms are all new rooms that would create more RP for cops and the civilians/criminals who visit MRPD. I would personally make sure these rooms are utilized throughout all PD members. It might also be time for a fresh coat of paint for such a utilized building in the city. As it stands, we have the Pillbox Medical Center from the same developer so we know the MLO is likely quality. Please at least take a look at the preview video and consider! Thank you!

**Comment by InZidiuZ** [comment]
Use the assets issue tracker for assets-related issues. This has already been added though, I believe.
