### ISSUE TITLE
Pillbox Medical Center Interior V2

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#1605]
**Summary:**
I noticed the suggestion for the updated Mission Row and saw there was a Version 2 for Pillbox. I would gladly purchase it if it were able to become a thing. https://www.gabzv.com/products/pillbox-hospital-v2?pr_prod_strat=copurchase&pr_rec_pid=6313421078679&pr_ref_pid=5768424554647&pr_seq=uniform

**Reason:**
I believe this would add a lot more interactions with the city since Pillbox is kind of the center of the city at times. I don't want to encourage people to hang out here however if there are a lot of people here at one time this would free up some of the issues. The biggest highlights would be the garage below, the additional parking near lower pillbox in which people can use that to alleviate all the parking in the front area of Pillbox as well as the removal of the jump there since its very unrealistic anyways.

**Comment by InZidiuZ** [comment]
Use the assets issue tracker for assets-related issues. This has already been added though, I believe.
