### ISSUE TITLE
[vehicles/gadgets] Improvements To Air One Camera

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1607]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I Have.
**Summary:**
There should be an indicator in the air one camera that tells you which way the camera is pointing relative to the helicopter, like on irl helo cameras.
(like in battlefield there's an indicator telling you where the turret of the tank is pointing in relation to the body)
**Reason:**
many times people fly and they can't folllow vehicles or people all that well because they don't know where the helicopter is pointing in relation to the camera, since it's fullscreen. All it takes is for the pilot to hover and you can't tell where the helicopter is pointing without having to unlock and look around and relaying the little information you have to the pilot. losing track of the car you're following.

**Comment by AdeptCL** [comment]
Do you mean like a compass? I.e. North heading, etc?

**Comment by Doughnut2001** [comment]
> Do you mean like a compass? I.e. North heading, etc?

No, it's local to the helicopter, it should only tell you where the camera is pointing relative to the nose of the helicopter

**Comment by Doughnut2001** [comment]
![20210114_081919](https://user-images.githubusercontent.com/52846859/104584416-5a226a80-5641-11eb-8f2e-1e2ba16795c9.jpg)

**Comment by Doughnut2001** [comment]
a 2D top view of the helicopter  as an indicator inside of the air one camera hud so that you know where the camera is pointing relative to the body of the aircraft to help you know where the hell you're flying, the red thing moves following the air one camera while the helicopter always points up in the hud.

**Comment by AdeptCL** [comment]
I see what you mean, so for the Pilot?

**Comment by Doughnut2001** [comment]
> I see what you mean, so for the Pilot?

For whoever is using the air one camera. It's in the air air one camera hud.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
