### ISSUE TITLE
[game/radio] Radio Filters

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1608]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
I've read that it may be possible to add radio filters to the in-game mumble radio plug in, it would be absolutely insane for you to look into this and have this in the city in the most positive way.

https://forum.cfx.re/t/mumble-filter-voice-to-sound-like-from-radio/1112160

**Reason:**
It would be a great boost to immersion, you wouldn't feel like the people you're talking to are right by you, or inside of your head and it would make it easier to distinguish who is talking in a police situation where there's multiple people in front of you.
it would be amazing.

**Comment by LikeConnorr** [comment]
+1.

It would be nice if it was optional in the /overview UI (like the radio clicks), rather than forced.

**Comment by InZidiuZ** [comment]
This has since been added.
