### ISSUE TITLE
Restarts done locally depending on the subdivision, reverting back to two restart cycles. 

### ISSUE THREAD

**Issue by LikeConnorr** [InZidiuZ/op-framework-issue-tracker#1609]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Recently, restart times were adjusted for flexibility across the neighboring subdivisions. I am suggesting/inquiring about the possibility of returning to **two restarts**, though having them take place locally depending on the server the player is connected to. It would be beneficial to have a restart in the earlier times, and later during the peak times for **ALL** servers.

**Reason:**
Taking into account the popularity of the OP-FW framework, a lot of users have taken a heavy hit by the adjusted restart times - particularly the EU/NA division. This has limited time-specific roleplay and those who come around during peak times across the EU/NA division without priority have been disadvantaged by this change.

I, and many others, share the opinion that 1 restart is unhealthy for the community - and evidently in the past few days has caused endless problems for players inc. severe lag, game crashes, and heavily contributed to other factors that the community struggles with alone. For example, the density of players & vehicles around the center of the city. Having 2 restarts allowed fresh roleplay to commence, and put everyone at a fresh standpoint for the following 12 hours. 

Although I am unsure whether this is possible, I think it should be considered a priority over the coming weeks. The previous times worked perfectly for those across the EU/NA division, and although we must consider other OP-FW players, we should avoid changing something that isn't broken & make a change that will benefit **everyone**. 

From someone who has been roleplaying for 2 years, the current system in effect makes it extremely difficult to carry out scheduled roleplay f/e meetings, gatherings, discussions, and makes it problematic to get into the server w/o raising slots **(which I feel that 68 is enough, and another change to this is unnecessary)**, or going AFK for a prolonged amount of time until the player is ready to roleplay. 

In my opinion, I feel a **local** restart at 10 AM & 10 PM for all subdivisions is perfect. 

Suggestion Credit: Yours Truly, [A-23] @mxttx

**Comment by AverageStatistic** [comment]
I used to ruleeee the queueeeeeee

**Comment by SoniMatt** [comment]
Hoping this happens. I hate sitting in queue for 3 hours just to be tired by the time i get in along with it being dead quiet since i missed all the fun while in queue

**Comment by LikeConnorr** [comment]
Providing the recent changes allowing 90 slots, if this were to be kept consistent the restart times would not need to be changed - though I can almost guarantee two restart cycles is the healthiest option for the server. My first suggestion still stands before this one though, it was absolutely fine before.

**Comment by InZidiuZ** [comment]
> I am suggesting/inquiring about the possibility of returning to two restarts, though having them take place locally depending on the server the player is connected to
Pushing server updates while other servers are running have previously proven to be problematic, so this is not an option.

> in the past few days has caused endless problems for players inc. severe lag, game crashes
Do you have *anything* whatsoever to back this up or are you just including this to dramatize the situation? It could also be some sort of placebo effect, perhaps?

> For example, the density of players & vehicles around the center of the city.
This is the only thing that I could think of that could cause issues from the longer uptimes, but then again, vehicles can easily be cleared by police, EMS and staff members. There could of course be other things that prevent the server from running stably after longer uptimes (which is the reason we had 6 restarts/day in the early days), but OneSync has become increasingly stable and bug-free, now to the point where I can't see much of a benefit for the extra restart.

> The previous times worked perfectly for those across the EU/NA division
Not for all Legacy subdivisions, though, as some had issues with restarts happening at their prime time which was problematic for them.

> we should avoid changing something that isn't broken
But... what about changing things to improve them?

Closing this though as it's not related to the framework's development. (See §9 in the README file)
