### ISSUE TITLE
Scuffed repair station Buccaneer Way

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#161]
**Reporter:**
SteezyRen#2828

**Summary:**
I am trying to go inside the repair station with my flatbed and a vehicle towed but it's saying "There is a vehicle blocking the entry way". No vehicle on the outside and none on the inside. There is nothing blocking it. Someone else was able to get into it with their flatbed with no vehicle towed, it worked. So I untowed the vehicle I had on and it still wouldn't let me in.

**Steps to Reproduce:**
1. Possibly have a vehicle towed on your flatbed
2. Try to enter the repair station with flatbed in Buccaneer Way
3. "There is a vehicle blocking the entry way"

**Expected Results:**
To be able to go inside the repair station :(

**Actual Results:**
Can't get inside

## Additional Information

**Screenshots:**
https://i.imgur.com/OoLmNPf.png
https://i.imgur.com/SHXDmqr.png
https://i.imgur.com/r4sCsg1.jpg

**Game Resolution:**
1920 x 1080

**Player Data:**
Provided in screenshots

**Notes:**
For anything else noteworthy.

**Comment by SteezyRen** [comment]
Tried again without my car on flatbed and another flatbed currently inside being worked on and it let me in. But can't get in with my car on my flatbed which defeats the purpose of being able to fix cars lol

**Comment by Scrubject** [comment]
So when a vehicle is destroyed you're SOL? had this very issue on 2 separate occasions.

**Comment by SteezyRen** [comment]
@Scrubject Not entirely SOL but you would need a repair kit instead of taking it to mechanic.

**Comment by tankfurious** [comment]
a good mechanic would carry a repair kit. all you have to do is ask for a road side repair

**Comment by SteezyRen** [comment]
> a good mechanic would carry a repair kit. all you have to do is ask for a road side repair

I'd prefer to tow their vehicle and RP working on it with them instead of just spamming my repair kit on the road to fix a totaled car and hope that repair kit doesn't break.

**Comment by tankfurious** [comment]
im saying if you come across a scuff situation ie not been able to tow into rep shop. you can untow outside rep the car and drive it in.

**Comment by SteezyRen** [comment]
Not if the car is totaled. Which is what I’m getting at originally. To be able to repair totaled cars without just being able to buy a repair kit.

**Comment by InZidiuZ** [comment]
I suppose this is the same issue as https://github.com/InZidiuZ/op-framework-issue-tracker/issues/140, so will close this.
