### ISSUE TITLE
Parking Area Bug

### ISSUE THREAD

**Issue by MrHitmanDrHitman** [InZidiuZ/op-framework-issue-tracker#1611]
1. 
There is always one car parked there or suddenly comes out of no where and drops over my bike. This issue always gives problem when no mechanics around. 

2. 
Also Sometimes I get my bike out from my Rented House Garage and I don't get the key and asks for hotwire my own bike. I try retrieving the bike and get it out again but the problem repeats.

**Comment by InZidiuZ** [comment]
Read the README file

**Comment by MrHitmanDrHitman** [comment]
> Read the README file

I see no read me file here

**Comment by AdeptCL** [comment]
here[https://github.com/InZidiuZ/op-framework-issue-tracker/blob/master/README.md](url)

**Comment by MrHitmanDrHitman** [comment]
That link doesn't open any file "No result Matched your Search"
