### ISSUE TITLE
Missing Garage for Trailer

### ISSUE THREAD

**Issue by Drylala** [InZidiuZ/op-framework-issue-tracker#1612]
**Assurance:**
I've read myself through the rules

**Player Identification:**
https://steamcommunity.com/id/see_the_Art/

**Summary:**
I feel pretty sad about my missing Garage. I really like the Trailer behind Yellow Jack. But i can't use it, since i can't pull out my Vehicals there. I heard also that other friends of mine can see and use it, without having access to my Trailer (or even before i baught it)

**Steps to Reproduce:**
It's nothing more then putting my Garage between Yellow Jack and the Trailer (where it prob belongs since of the free space there)

**Expected Results:**
Useable Garage Marker so i can pull out/turn in my Vehicals that i own, next to my Owned Trailer behind Yellow Jack

**Actual Results:**
That i will be able use a Garage marker for my Trailer.

## Additional Information
I guess my Garage that is missing, belongs to another house too, since a friend of mine can see it/use it, but he doesn't own the trailer os has access to it

**Screenshots:**
Sadly no-

**Game Resolution:**
1600x2000

**Player Data:**
Can't realy show a screenshot of the missing Garage, since i don't know where i would find it.

**Server:**
Legacy NA/EU server, FiveM.

**Notes:**
Thank you very much for reading it ♥

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
