### ISSUE TITLE
[game/health] Reskin/Tattoo Removal for EMS

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#1613]
**Assurance:**
Yes

**Summary:**
About some sort of ingame mechanism which can be helpful to remove tattoo.

**Reason:**
the reason behind my suggestion is that as a ingame admin many players came to us to remove tattoo which they get may be accidently or they don't want those tattoo now. and the reskin mech. doesn't work on tattoos return when you change your outfit or relog server. the only option we've is to create another character . but by doing this all the work they've done on their previous character will be nothing but waste . so have a look on this issue and if possible add such mechanism. and if this belongs to medic dept. then a new rp i.e. laser therapy / tattoo removal can be introduced in server.

**Comment by LikeConnorr** [comment]
This would include adding a function that would allow doctors to reskin patients providing that the surgery is deemed 'medically appropriate/possible'. Although in an ideal world this would be lovely, it could be a concern for possible abuse - only admins can reskin for this reason.

Although I have been apart of the community for almost 2 years (and currently the only doctor in the city license to provide surgery), I doubt the access would be given regardless of level o/ trust. Now it is easy to request an admin to do it for me & the patient, though they are not always available and admins are strict on giving them - and this would need to be changed if there was a roleplay reason behind it (i.e., surgery). 

Would be amazing for this to be taken into consideration though.

**Comment by Vikky98** [comment]
> This would include adding a function that would allow doctors to reskin patients providing that the surgery is deemed 'medically appropriate/possible'. Although in an ideal world this would be lovely, it could be a concern for possible abuse - only admins can reskin for this reason.
> 
> Although I have been apart of the community for almost 2 years (and currently the only doctor in the city license to provide surgery), I doubt the access would be given regardless of level o/ trust. Now it is easy to request an admin to do it for me & the patient, though they are not always available and admins are strict on giving them - and this would need to be changed if there was a roleplay reason behind it (i.e., surgery).
> 
> Would be amazing for this to be taken into consideration though.

totally agreed with the point you placed . that was only a idea of surgery rp thing. but it would be great if reskin is able to remove tattoo for permanent and we don't have to make a new character if we got a tattoo by mistake or something.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
