### ISSUE TITLE
 Put all resources/client downloads on Amazon AWS Cloudfront for instant download speed

### ISSUE THREAD

**Issue by aay4abdullah** [InZidiuZ/op-framework-issue-tracker#1616]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.
 Suggestion is to put all resources/client downloads on Amazon AWS Cloudfront for instant download speed. as fivem server speeds are very slow and takes ages to download resources . it'd be better if you put all resources/client downloads on Amazon AWS Cloudfront for instant download speed

**Reason:**
Why would your suggestion be a good change to the framework?
help faster downnloads/wont pause RP

**Comment by InZidiuZ** [comment]
Read the README file. This is not related to the framework's development. Upgrades to the infrastructure running all our servers are imminent, though.
