### ISSUE TITLE
Bug report | Paleto Medical Has No Check-In

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1618]
**Assurance:**
Yes.

**Player Identification:**
https://steamcommunity.com/id/AdeptCL/

**Summary:**
A check-in feature at Paleto Bay Medical.

**Steps to Reproduce:**
I'm not sure if this is meant to be a bug or suggestion, aka if it's meant to be there already or not.

**Expected Results:**
Have a check-in feature at the Paleto Bay Medical reception desk.

**Actual Results:**
There is currently no check-in feature at the Paleto Bay Medical reception desk.

## Additional Information

**Server:**
Across all OP-FW servers.

**Comment by InZidiuZ** [comment]
This is not a bug, functionality for it is just not added yet.
