### ISSUE TITLE
[*] Regarding Addition of Lockers and clothing spot in Mosley Repair shop

### ISSUE THREAD

**Issue by NOTMIRCHI** [InZidiuZ/op-framework-issue-tracker#1619]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
 Yes
**Summary:**
Write a summary of what your suggestion is about.
Can you add a clothing spot and personal locker in mosley's repair shop. As it would be easier for mechanics to keep the scarps in the locker rather than their pockets and car trunks. 
**Reason:**
Why would your suggestion be a good change to the framework?
This will increase the mechanic RP a lot as the new repair shop already have a locker room design.

**Comment by ayushpandit99** [comment]
i have already added this point + some of the other points from my department side in 
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1541

**Comment by InZidiuZ** [comment]
This has since been done.
