### ISSUE TITLE
Airdrop can't be collected

### ISSUE THREAD

**Issue by smallfatcat** [InZidiuZ/op-framework-issue-tracker#162]
Reporter:
SmallFatCat#0249

Summary:
The airdrop for the coke mission cannot be picked up. Happens when the parachute on the box is still open. Seems to be related to the height at which the box spawns in, the higher it is above the waves the more likely the issue is to happen. Previously a workaround of ramming the parachute with the plane would destroy the parachute and allow pickup of the box. That no longer seems to work.

Steps to Reproduce:
Hard to reproduce other than to keep running missions, player has no control over how the box spawns in.

Expected Results:
You should be able to pick up the airdrop when the parachute is still deployed, or the parachute should always be removed from the box.

Actual Results:
As you can't pick up the box, you can't complete the mission.

**Comment by InZidiuZ** [comment]
Hey,

Not sure why it sometimes doesn't register as being in water, but I've added the possibility to pick the drop up, even though the parachute is still attached, which hopefully makes this less of an issue.

**InZidiuZ**
*OP-FW Developer*
