### ISSUE TITLE
[jobs/mechanic] Regarding addition of New Tow Truck

### ISSUE THREAD

**Issue by NOTMIRCHI** [InZidiuZ/op-framework-issue-tracker#1620]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Write a summary of what your suggestion is about.
 Can you add a 2nd Tow truck in OP-FW . The tow truck which was originally used in GTA 5 by franklin. 
**Reason:**
Why would your suggestion be a good change to the framework?
This would add new variety vehicle to tow and impound it thereafter. This tow trick has its siren lights too. It would be faster than the original one, it also could be something like Rapid Response unit for mechanic.

Image link : https://i.redd.it/o1zotdluik601.png

**Comment by 8017RAZ** [comment]
> **Assurance:**
> Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
> Yes.
> **Summary:**
> Write a summary of what your suggestion is about.
> Can you add a 2nd Tow truck in OP-FW . The tow truck which was originally used in GTA 5 by franklin.
> **Reason:**
> Why would your suggestion be a good change to the framework?
> This would add new variety vehicle to tow and impound it thereafter. This tow trick has its siren lights too. It would be faster than the original one, it also could be something like Rapid Response unit for mechanic.
> 
> Image link : https://i.redd.it/o1zotdluik601.png

That is good suggestion

**Comment by Nuziatella** [comment]
Soon(tm)

**Comment by twooot** [comment]
This tow truck is very scuffy with the chain, which is why i'll not be adding it to the list of purchasable vehicles.
