### ISSUE TITLE
[jobs/police] Small Notification when a civilian come to MRPD.

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1621]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
New PD is very much restricted for civilians there should be an E interaction where if a civilian comes and press E then all On-duty get a notification and there should be a cooldown too like in 1 min one time something like that. Rather than shouting on their mic xD. https://i.ravicant.in/7r1yb749h
**Reason:**
Why would your suggestion be a good change to the framework?
it will increase interaction btw cops and civilians more.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
