### ISSUE TITLE
Clothing not displaying Bug report

### ISSUE THREAD

**Issue by kunalb84** [InZidiuZ/op-framework-issue-tracker#1624]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes

**Player Identification:**
What is your steam profile?
76561198154437380

**Summary:**
Write a short summary of what you are experiencing.
I cannot change clothes, when I go the clothing store I choose clothes and then I can see nothing is changed even I cannot see the option in that menu

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Go to clothing store, Press E, then choose clothing- no options 

**Expected Results:**
What are the expected results?
Change of clothes

**Actual Results:**
What are the actual results?
Nothing, no clothes changed

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Link to video-https://www.youtube.com/watch?v=CCCPuQCDDuA

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Video-https://www.youtube.com/watch?v=CCCPuQCDDuA

**Server:**
What server/community did this issue occur in?
Public server 2 145.239.205.202:30181

**Notes:**
For anything else noteworthy.
Also I can see some white shredded thing on my head which changes colour as I move, don't know what it is.

**Comment by TCruxer** [comment]
You are using a PED model and not a Freemode model that's why you don't have clothing options.

Cruxer
Lead Asset Dev

**Comment by kunalb84** [comment]
Hi,

Thanks for letting me know the cause of the problem. Can you suggest if I
can change to a freemode model or if I want to change clothes of ped model,
can I do it?

Regards
Kunal
