### ISSUE TITLE
[base/admin] Useful Staff Commands

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#1625]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Just some quick admin tools that would be nice and make our job easier in the city.

**/check_job [id]** Returns the player's job description to the staff member to allow and check if the job change was accurate.
**/check_death** : Returns the kill logs for the last minute to easily find hackers without relying on opening the admin panel 
**/check_death [id]** variant of the previous allowing us to check a specific player's last death log ( might be easier to implement)

**Reason:**
Why would your suggestion be a good change to the framework?
Makes our job as staff members easier and stress free. Thanks Ben

**Comment by Nuziatella** [comment]
This really would be a nice quality of life upgrade

**Comment by InZidiuZ** [comment]
When setting someone's job now, you'll receive a confirmation message with the updated details. Two commands have been added for the death suggestion, /recent_deaths and /player_death. You can also use /check_deaths and /check_death as those have been set as substitutes.
