### ISSUE TITLE
Pillbox Bug

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1626]
**Player Identification:**
http://steamcommunity.com/id/mattxiv

**Summary:**
The beds in pillbox are only letting one person check in at a time, indicating to many "the beds are full", even when they are not. This could be due to the new hospital in Paleto messing up with the numbers in pillbox, I did check paleto though and nobody was checked in or near there at the time.

**Steps to Reproduce:**
Check in at pillbox with one person already checked in, unknown what causes this bug.

**Expected Results:**
You are able to check in with ease.

**Actual Results:**
It tells you the beds are full and you have to wait until nobody is on the beds anymore.

# Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/476149162333831196/806256768609943562/unknown.png
What it says when we can't check in (there was only one person on a bed during this time)

https://prnt.sc/y23uao
The only bed at pillbox which was "working"

**Server:**
Legacy EU/NA

**Comment by mxttx** [comment]
This extended to all beds in pillbox being unable to be used by the end of the day and EMS & Staff was forced to keep reviving people when they came to pillbox.

**Comment by InZidiuZ** [comment]
This issue should now be resolved.
