### ISSUE TITLE
Bug report (Players showing in player list but not in the server)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1628]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Guardian3-1
**Summary:**
Write a short summary of what you are experiencing.
So when you press u ingame to check the player list some names are still in the list even though the player has left the server you cant spectate them. You can do /kick a number of times it shows the player has been kicked but name still remains on the list.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Not too sure about the repro as I cant find the exact reason for it happening checking through logs the player exited the city reason "exiting" 
**Expected Results:**
What are the expected results?
Player names and steam name shouldnt be displayed after they have left the city
**Actual Results:**
What are the actual results?
names still appear on player list even though the player has left the city
## Additional Information
https://gyazo.com/ed1fb5cb7ac9df0a838b138a60f15345
**Screenshots:**
If suitable, include some screenshots.
https://gyazo.com/ed1fb5cb7ac9df0a838b138a60f15345
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/995ced21acf2928340ce647f0f1e447a
**Server:**
What server/community did this issue occur in?
India Semi-Whitelist Public 1
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is a FiveM issue. It should hopefully be resolved with the latest FiveM artifact versions, so when we update those, the issue may perish.
