### ISSUE TITLE
[game/clothing] Suggestion

### ISSUE THREAD

**Issue by sahara87** [InZidiuZ/op-framework-issue-tracker#1629]
**Assurance:**
 Yes

**Summary:**
When applying a mask using the /mask command or at a clothing store, the character model's face should be set to the default male / female face to avoid parts of the face clipping through the mask. 

https://media.discordapp.net/attachments/806242616316264458/806244300232458270/unknown.png

**Reason:**
This would be a good addition to the framework because people with different faces are very limited when it comes to selecting masks from the clothing store and are unable to choose masks like a basic balaclava or bandana due to facial features clipping through it ruining the aesthetic.

**Comment by twooot** [comment]
There is masks which dont hide your face though like earpieces for example. Setting the face to the default face would look very weird
