### ISSUE TITLE
[jobs/mechanic]Extra tow trucking activity

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/op-framework-issue-tracker#1630]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
-Yes

My discord is SmythGG#8913 feel free to dm me with any questions.

Summary
Tow truckers get paid $25-$150(random amount)(this money gets deposited straight into the players bank account) to impound local cars to keep the city cleaner. Not allowed to abuse the local cars and impound every car the player sees(Honor system). Only allowed to impound cars that are blown up or left behind in the street or parking lots.
Cops can also call tow truckers to impound cars for them which provides more rp for both parties.

This would help the d-sync and scuff in the server because the server wouldn't have all the blown up cars and cars left behind to constantly load in.

**Comment by InZidiuZ** [comment]
This has now been done.
