### ISSUE TITLE
[game/mdt] Court House info

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/op-framework-issue-tracker#1632]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
-Yes

My discord is SmythGG#8913 feel free to dm me with any questions. 

Summary
Court house front desk able to provide your warrants/search criminal records of yourself and other civilians in the city.
Walk up to front desk of court house and press E then it pops up a civilian version of the police mdt to search warrants and criminal records.

**Comment by InZidiuZ** [comment]
This suggestion is being rejected for the time being.
