### ISSUE TITLE
[jobs/fishing] Fishing 

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/op-framework-issue-tracker#1633]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
-Yes

My discord is SmythGG#8913 feel free to dm me with any questions.

Summary
Fishing as a civilian activity / sell your fish to a npc on the pier to make money.($25-$100 per fish) (Able to catch fish and other materials like thermite / keys / guns.

This would improve rp because everyone hanging around fishing can talk with each other and this would also help cut down on all the people always hanging out at pillbox by giving them another way to make money.

**Comment by DaxterPancake** [comment]
Closing in favour of #766 

Cheers,
Daxter
Project Manager.
