### ISSUE TITLE
sending messages in phone

### ISSUE THREAD

**Issue by bigjoeshow** [InZidiuZ/op-framework-issue-tracker#1637]
**Assurance:**
yes
**Player Identification:**
big_joe_show
**Summary:**
when sending a message in my phone, when i type p while typing the message, the phone pulls up and i cant type unless i hit backspace until the phone gets put back away. delays calling 911 trying to get help.
**Steps to Reproduce:**
send a message to police, type p.
**Expected Results:**
that i can type uninterrupted
**Actual Results:**
the phone pulls up and i cannot resume typing until i hit backspace to put away the phone.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
legacyrp
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Try to use mouse input instead. This will be a wontfix, though, as the current phone is deprecated and set to be removed hopefully soon.
