### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/op-framework-issue-tracker#1638]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198967366497/

**Summary:**
Write a short summary of what you are experiencing.
When i get into a car it removes my hat and i cant put it back on while in the car.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
where a hat then enter a vehicle and type /hat 

**Expected Results:**
What are the expected results?
when i enter a vehicle my hat shouldnt be taken off my character.

**Actual Results:**
What are the actual results?
when i enter a vehicle my hat get removed 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
default 

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/78629138/107474926-4800f280-6b41-11eb-90f0-0807d141bd9d.png)

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by PsychoGrandpa** [comment]
I faced this issue too. When wearing a cap, the command /hat makes the character wear the cap again inside the car. But for hats that are too large, /hat makes no changes. The character stays without a hat inside the car.

**Comment by InZidiuZ** [comment]
Probably default GTA behavior. If not, then it'd be due to the old & deprecated clothing system, so this will remain a wontfix until later.
