### ISSUE TITLE
[game/inventory] Add normal First Aid to EMS Store.

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/op-framework-issue-tracker#1639]
****Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Normal First Aid should be added to EMS store.
You guys decide the price.
If the price is a bit low then people would want to buy bandages from the EMS Store. 
_Alternative_ I guess there should be a command where the ems does a bandaging emote and heals other player by 15% to stop their bleeding.

**Reason:**
Why would your suggestion be a good change to the framework?
Because some of the citizens bleed and they ask for First Aids and they cant use the EMS one so we have to visit stores to buy those. It will be easier if it was available in the EMS store.

**Comment by T4NZIM** [comment]
About the bandage command, This should be able to stop bleeding as CPR doesn't fix bleeding.
And add the normal first aid kit in the EMS store and keep the price the same as **EMS First Aid Kit** but only EMS can buy it but anyone can use it- That's my suggestion

**Comment by twooot** [comment]
this was done
