### ISSUE TITLE
Reconnecting prevents the death timer

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#164]
**Reporter:**
SteezyRen#2828

**Summary:**
When you die you just have to relog if you want to skip waiting 5 mins.

**Steps to Reproduce:**
1. Die
2. Disconnect/Reconnect
3. Now at the hospital

**Expected Results:**
1. Die
2. Disconnect/Reconnect
3. Still dead with timer counting down

**Actual Results:**
Step 3 is missing.

**Comment by InZidiuZ** [comment]
Hey,

This is intentional, and won't be changed at this time.

**InZidiuZ**
*OP-FW Developer*
