### ISSUE TITLE
[game/inventory] Item Durability

### ISSUE THREAD

**Issue by LikeConnorr** [InZidiuZ/op-framework-issue-tracker#1641]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes.

**Summary:**
I am suggesting we add item durability for all items. This is where items would wear off to where they will eventually become destroyed. Items will lose durability for 2 reasons.

**1. Item Usage**
This will be what decreases the status of the item the most/quickest. However, it should wear at different speeds depending on the item. For example, guns are stronger due to them being metal/steel. 

**2. Hoarding**
Overtime (a longer period), the item will wear from rust/mould/non-usage. This is to prevent people from hoarding items.

**Reason:**
This is the main solution to needing a wipe so often. Without durability, the server will become overwhelmed with items in the economy. This will force people to RP more, attaining the items once again when destroyed.

**Comment by LikeConnorr** [comment]
Another addition would be a reforging system, and with the usage of current materials in the server, you can repair your items with a reforging tool :)

**Comment by mxttx** [comment]
This can even be on one time use things such as metal, toolkits, etc. Food can go mouldy, metal can go rusty, guns and lethal weapons can be broken, etc.

Like Connor said, this would stop any need for wipes unless absolutely necessary. 
It would stop gangs from sitting on guns, thus making them use them more and thus creating more roleplay.
This goes for any item, for example, it stops people from buying 100 burgers and 100 waters and never having to visit a store again, now they will not stockpile and instead if they are hungry create a roleplay scenario of visiting the stores, increasing interaction for everyone, as minimal as it may be.

**Comment by mxttx** [comment]
**(Though there was another suggestion about this, it was brief and lost in the sauce.)** https://github.com/InZidiuZ/op-framework-issue-tracker/issues/872

**Comment by Nuziatella** [comment]
I entirely agree. The no decay system just causes quite a few balancing issues which in turn cause convoluted processes to counter the no decay system. An example would be, while might be unique to the 1 server, an individual stopped playing some 5+ months ago starts to play again, gets into a situation, and pulls out a bullpup rifle mkII. For those who are unfamiliar it would appear this individual just spawned in a gun into an inventory. Resulting into a whole situation OOC which takes time away from the ability to RP.  A decay system would just prevent situations like these from happening and would correct the balancing issue of individuals mass stock piling a given resource.

Something to note, raw materials should not decay.
Scrap Metal
Steel
Aluminum
Glass
Rubber

**Comment by AdeptCL** [comment]
I believe hoarding is something that is a massive issue right now within the server of the North American/European. I'm not too sure on the Asian subdivisions. 

Certain items, such as guns, chips, keys, etc should all come with some form of durability. It stops the increasing hoarding issue and forces a circulation of items plus economy, or forces usage.

With Chop Shop having the ability to find pistols/shotguns, House Robberies having the ability to find pistols/uzis, and now Zombie Pills having the ability to find what we think a range of weapons. It's only right that a durability feature will effectively work alongside all of these activities. It creates a continuous flow of items/economy/usage, while providing so much roleplay across the board.

I agree with @Nuziatella, in that certain items such as materials should not decay. But what I will say is that if or whenever an ability to craft things from these materials comes to the server, this would be the point that they should also begin to decay.

**Comment by keepcodingstar** [comment]
If i had to fix the economy i would have increased the flow of weapons and keys in city. There are cities which gives keys in normal jobs like burger shot and taco delivery. And there exists cities where civilians can spawn anything depending on there RP. If I found class-3 weapons easily I would not Hoard weapons.

**Comment by twooot** [comment]
this was done
