### ISSUE TITLE
Small Suggestion on ID Cards .

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1642]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Add info about Department where your character works on ID cards.
https://i.ravicant.in/6LjuJl1fr.png
**Reason:**
Why would your suggestion be a good change to the framework?
It Will increase the RP

**Comment by InZidiuZ** [comment]
This won't be done as jobs (I assume that's what you mean) change at a constant.
