### ISSUE TITLE
Locks

### ISSUE THREAD

**Issue by stardome101** [InZidiuZ/op-framework-issue-tracker#1643]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I would like to have locks on the Bahama Mamas doors.
**Reason:**
Why would your suggestion be a good change to the framework?
Well, every other club/bar seems to have them and we USED to... but they disappeared :( Can they come back?

**Comment by InZidiuZ** [comment]
But... they already do?

**Comment by stardome101** [comment]
nuh uh not yesterday

**Comment by InZidiuZ** [comment]
Are you saying that the locks aren't on the doors, or that you can't lock/unlock them? Because the locks are definitely there.

**Comment by stardome101** [comment]
OH yeah, there is no option to lock/unlock them but they work on every other club door for me. Not sure whats up with that :D

**Comment by InZidiuZ** [comment]
This is being resolved
