### ISSUE TITLE
Mechanic shop bug with windows

### ISSUE THREAD

**Issue by jarmetgg** [InZidiuZ/op-framework-issue-tracker#1645]
Noticed a new bug when repairing vehicles. 

When reviewing a busted car, it will say that some widows are cracked but actually are in the vehicle. Usually they are the front and rear windows. When placing a window inside the car, the car would take the window but still says cracked when reviewing. Tried storing and bringing back the vehicles but the issue is still there. 

https://youtu.be/wpMhBP_LEhI

**Comment by InZidiuZ** [comment]
Read the README file
