### ISSUE TITLE
CAR WENT TO IMPOUND LOT DIRECTLY FROM HOUSE GARAGE

### ISSUE THREAD

**Issue by MrHitmanDrHitman** [InZidiuZ/op-framework-issue-tracker#1646]
So I just went to LSC for changing my car color, I changed color, washed my car, came to my home at Procopio Drive, Stored the car. 

2 seconds later I opened Vehicle list and that car is showing in impound lot. How is this possible. 

Attached Image below. 
![image](https://user-images.githubusercontent.com/59993622/108049419-3dc58380-706e-11eb-8d5e-47e8d49a9af8.png)

**Comment by InZidiuZ** [comment]
Read the README file
