### ISSUE TITLE
Holding F at the back of a burnt/out of service car lets you get into it and you burn alive.

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#1647]
**Assurance:**
Yes

**Player Identification:**
http://steamcommunity.com/id/mattxiv

**Summary:**
Holding F at the back of a car disabled blown up car lets you in and burns you until you die even if you get out. I believe this bug is exclusive to cars "without" back doors (which makes you just slide into them instead of opening a door). A car which exhibits this is the Ladybird and is a 4 seater.

**Steps to Reproduce:**
Buy a Ladybird,
Disable it and have it blow up,
Holding F at the back of the car makes you hop into the back of it and you start to burn.

**Expected Results:**
Not be able to enter the car after it has blown up.

**Actual Results:**
You are able to enter the car and you burn to a crisp.

## Additional Information

**Screenshots:**
For your amusement and to outline the bug, I have clipped experiencing this in the server.
https://medal.tv/clips/44216940/d1337foE7q5r

**Comment by InZidiuZ** [comment]
This issue has been resolved with version 3797.
