### ISSUE TITLE
[jobs/up_n_atom] Delivery job

### ISSUE THREAD

**Issue by YhLadd** [InZidiuZ/op-framework-issue-tracker#1648]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
I recently got Up-n-Atom as a business, I only have the outside of the building which is fine I just wanted a similar delivery job to BurgerShot if possible so my employees could make a bit of money when its quiet and not have to rely on me to pay them out of my own money (I don't have a shop to buy /sell items from for my business either so its my own personal money iv saved up id be paying them with and not profits).

**Reason:**
Why would your suggestion be a good change to the framework?
This suggestion would be a good change to the framework because it can create more jobs for people and help the economy as well as encourage people to work at my business and make them actually able to make money. When hiring people the main thing they ask is if I have a delivery job like BurgerShot.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
