### ISSUE TITLE
FINANCE Payment and companies bug 

### ISSUE THREAD

**Issue by nikhil6356** [InZidiuZ/op-framework-issue-tracker#1649]
**Assurance:**
no
**Player Identification:**
https://steamcommunity.com/profiles/76561198930892132/

**Summary:**
WHEN I type companies and go to purchases everything is blank and even the home button is giving blank screen ,not being able to pay my finance 
Even i show my id card no name is shown on that 

**Steps to Reproduce:**
1.TYPE ( /companies) got to purchases , nothing showing up
2.press home and blank screen 

**Expected Results:**
blank screen with no options
![123123123](https://user-images.githubusercontent.com/79253090/108338067-de957980-71fb-11eb-9272-48cfc4836f5d.PNG)
![finance](https://user-images.githubusercontent.com/79253090/108338070-dfc6a680-71fb-11eb-8c89-e310292b8fd7.PNG)

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
1360X768

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![info](https://user-images.githubusercontent.com/79253090/108339230-2cf74800-71fd-11eb-8794-a73338631840.PNG)

**Server:**
They said  me to reinstall five m and the whole game also to delete the cache folder in five root directory but nothing worked .

**Notes:**
PLEASE FIX THIS FAST I GRIND MANY HOURS IN THIS GAME.

**Comment by InZidiuZ** [comment]
Could you provide a log file of a session when this happens?

You can find the log files by going to:
`%localappdata%\FiveM\FiveM Application Data` -> `logs`

**Comment by nikhil6356** [comment]
here is the log file..
[](url)
[CitizenFX_log_2021-02-28T135826.log](https://github.com/InZidiuZ/op-framework-issue-tracker/files/6056907/CitizenFX_log_2021-02-28T135826.log)

**Comment by nikhil6356** [comment]
> Could you provide a log file of a session when this happens?
> 
> You can find the log files by going to:
> `%localappdata%\FiveM\FiveM Application Data` -> `logs`

[CitizenFX_log_2021-02-28T135826.log](https://github.com/InZidiuZ/op-framework-issue-tracker/files/6056909/CitizenFX_log_2021-02-28T135826.log)

**Comment by InZidiuZ** [comment]
I have no clue on how to resolve this. Most certainly a local issue. I couldn't find anything in the log file either. I would suggest checking out the FiveM forum and/or discord for solutions.
