### ISSUE TITLE
Died when respawning

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#165]
**Reporter:**
Lars. #9309
**Summary:**
I respawned after dying while being cuffed. I died instantly at the hospital bed and i was still cuffed.

**Steps to Reproduce:**
Kill someone who is cuffed and let him respawn.

**Expected Results:**
Respawn and be alive.

**Actual Results:**
Respawn and die instantly still being cuffed.

## Additional Information

**Screenshots:**
https://i.imgur.com/qMz6wVM.png
https://i.imgur.com/2b6nlCG.png

**Game Resolution:**
1920x1080

**Player Data:**
https://i.imgur.com/grv8hir.png

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
