### ISSUE TITLE
Black loading screen while trying to load into house

### ISSUE THREAD

**Issue by missskinny** [InZidiuZ/op-framework-issue-tracker#1650]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes.
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/battery-acid/
**Summary:**
Write a short summary of what you are experiencing.
me and many other people keep having issues with trying to load into houses, they try entering, and it just gets stuck on a black loading screen and never actually loads into the house.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
enter the house
**Expected Results:**
What are the expected results?
to enter the house
**Actual Results:**
What are the actual results?
you get stuck on a loading screen forces you to relog 
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
no screenshots but i have a recording.

https://user-images.githubusercontent.com/76709628/108574008-2099ea80-72e4-11eb-9510-11ed0805b60a.mp4

**Game Resolution:**
What is your game's resolution?
fullscreen 1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Screenshot (1351)](https://user-images.githubusercontent.com/76709628/108574051-432c0380-72e4-11eb-94e0-5383647e2dcc.png)

**Server:**
What server/community did this issue occur in?
Legacy
**Notes:**
For anything else noteworthy.
maybe take out the loading screen and just make it an insta teleport?

**Comment by RyanShlap** [comment]
I too have the same issue when I spawn in at my property at the nudest camp. Every time I join the server and spawn there that's when I have the issue. If I spawn at the bus station then go there I'm fine.

**Comment by YhLadd** [comment]
I tend to get this issue alot when swapping characters, when I switch from one apartment to my other character and go into his apartment it usually does this bug.

**Comment by InZidiuZ** [comment]
I believe this issue has since been resolved. If you're still experiencing such issues, please reopen this issue or create a new one.
