### ISSUE TITLE
[game/doors] Comedy Club Suggestion

### ISSUE THREAD

**Issue by MsBBBones** [InZidiuZ/op-framework-issue-tracker#1651]
**Assurance:**
Yes, I have.

**Summary:**
I would like to submit a request for there to be an ability to lock the Comedy Club's doors. I recently purchased the business and I'm super excited! However, I noticed there are more and more people going and coming from the club with no authorization (it's currently still closed). The really big concern I have is the group of people who were hanging out there the other day doing not-so-legal things at the crack of dawn! I'm just hoping we can add some locks on the doors so we can control the access a lot easier.

**Reason:**
I think this would be a great addition to the Framework because it'll allow for easier population control, as well as boost the want/need to attend the club by creating exclusivity. It also makes it so much easier for the staff and I to feel safe.

**Comment by InZidiuZ** [comment]
Door locks have now been added.
