### ISSUE TITLE
[game/mdt] Adding MDT for EMS and Sasp

### ISSUE THREAD

**Issue by Jeetez** [InZidiuZ/op-framework-issue-tracker#1653]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
My suggestion is about adding up MDT for ems and Sasp.(both separate)
Which can be used by the Sasp /ems players. Which will increase a lot of rp. Help keeping the records and all other sort of stuff that is used in a MDT. It would help the Sasp/ems players a lot. And more rp would be generated

**Reason:**
This would increase alot of rp.
In terms of Sasp files would be stored and quickly be accessed through any officer/medical for rp purpose.(while on duty) . 

Records of patient/criminals would be available at a place. For eg. Some personal vehicle having a active code red on it but that info couldn't be shared anywhere else than in rp. If all the officers go off. Then the information would be of no use. With the help of MDT any officer would know. What are the active situations in city.

Same goes for ems. From patient records to surgery records. Alot of things can start from MDT is all I mean :)

**Comment by 8017RAZ** [comment]
Yes that's Good

**Comment by Nuziatella** [comment]
This has already been requested #1015

**Comment by gighul** [comment]
following up on this, ready thing to just add 
![image](https://user-images.githubusercontent.com/71882732/118262828-bdb88980-b4b5-11eb-801d-965e661287e9.png)
[
[LSPD_MDT.zip](https://github.com/InZidiuZ/op-framework-issue-tracker/files/6478381/LSPD_MDT.zip)
](url)

**Comment by InZidiuZ** [comment]
This suggestion is being rejected for the time being.
