### ISSUE TITLE
[jobs/*] Adding a new Job system for POLICE/EMS/PDM Staffs like /Company's System

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/op-framework-issue-tracker#1654]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
**Adding a job system as like the  /company's for Police/EMS/PDM**
Atm, we have to ask the server Admins for Police/EMS/PDM Job roles/positions. But sometimes the staff aren't available on the server or they're busy in some situation. Hence we can add a better system where the X ranking staff/Higher ranking staffs like SASP Commissioner or cops with X ranking, EMS's All Directors, PDM Boss will have a special command or will have a tablet like /companies where they can give the job to anybody also can set their rank/position like the Company Employee System. All can remove/fired someone from that tablet.
**Reason:**
Why would your suggestion be a good change to the framework?
This will make a better impact on the framework as its logical. By this, we can make better RP sense for giving job/badge stuff. Also, this will be better stuff as compared to our present system.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
