### ISSUE TITLE
[jobs/ems] Adding a system/command from where the Higher ranking[All Directors] EMS can do /resking or Plastic Surgery

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/op-framework-issue-tracker#1655]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
As our game mechanics, EMS can do plastic surgery but the thing is here that every time they have to ask the server admins to do reskin which is very difficult, sometimes. But here we can add a new system from where only higher ranking EMS like all the directors will have a special command prompt from where they can do plastic surgery/reskin.
**Reason:**
Why would your suggestion be a good change to the framework?
It'll make a good change to the framework as it's reasonable. By giving this command prompt to all the directors will make EMS's plastic surgery easier for the EMS staff.

**Comment by Nuziatella** [comment]
This can lead to heavy abuse without strict moderation. If a person needs this type of thing they can just /report and ask a member of staff. While I understand the frustration with having to wait, that's the only con. Waiting.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
