### ISSUE TITLE
Smooth Skin 

### ISSUE THREAD

**Issue by missskinny** [InZidiuZ/op-framework-issue-tracker#1656]
**Assurance:**
I have read the read me.

**Summary:**
I and many other people I have talked with think smooth skin would make a nice difference not necessarily just rp, but also in the aesthetics of the game. I'm tired of my 21 year old character looking like she is just a 50 year old woman with veiny hands who never wears sunscreen and spent too much time at the beach tanning. Something that ruins immersion for some people is nametags, well for me it's the wrinkly, damaged, sun spotted, leathery skin on all of these people in the city who are for the most part in their 20s. I have never seen anyone with this kind of skin at such a young age, and it just makes me feel weird when I turn my character around or take a picture of her (or any of them) just to see a face full of marks that belong to someone double her age. The skin details are even more visible to someone with a graphics mod. The smooth skin mod also allows the wrinkle add ons in the game still so if someone happened to want to make an older character, they still could with the smooth skin mod. Even gta online characters don't have this kind of skin, so I have no idea why fivem characters would. Also with some of the skintones, they have five o'clock shadows to them and I have seen girls use the skins solely because it was the skintone they wanted, but with the smooth skin mod it completely gets rid of the shadow so then that way they can have their skintone without having to look like they just shaved their beard. I will include screenshots of how awful the skin looks with and without a graphics mod, how a gta online character's skin looks (ignore the outfit though the screenshot was accidental and I was in the middle of changing into a winter outfit), and how the smooth skin looks when its on a character (girl with the red hair + girl with the pink hair). 

**Link to Mod:** (also even though it is made for female characters, I do believe men can still have the smooth skin as well as long as the skin files for the men are replaced with those as well)
https://www.gta5-mods.com/player/improving-all-mp-female-characters-appearance-1-0 

**Reason:**
Why would your suggestion be a good change to the framework?
I think it would be a good change because I know it is not a super difficult task to implement it and it would help make the younger characters look more youthful and not like they have 5 kids and are tired of life. 

**Images:** (there are alot)
![maeve's selfie](https://user-images.githubusercontent.com/76709628/109182168-bd341080-775a-11eb-8a77-987b4aca2301.png)
![Screenshot (131)](https://user-images.githubusercontent.com/76709628/109182170-bdcca700-775a-11eb-8e11-b3a0bee8f6e0.png)
![20201226162454_1](https://user-images.githubusercontent.com/76709628/109182174-be653d80-775a-11eb-9cba-5699b61eaae4.jpg)
![FiveM_GTAProcess 2021-02-25 10-43-35](https://user-images.githubusercontent.com/76709628/109182176-be653d80-775a-11eb-901c-d437ec14857e.png)
![FiveM_GTAProcess 2021-02-25 10-43-31](https://user-images.githubusercontent.com/76709628/109182178-befdd400-775a-11eb-90a1-ae8801301173.png)
![FiveM_GTAProcess 2021-02-25 10-43-25](https://user-images.githubusercontent.com/76709628/109182180-befdd400-775a-11eb-9124-23a82625d338.png)
![FiveM_GTAProcess 2021-02-25 10-43-00](https://user-images.githubusercontent.com/76709628/109182183-bf966a80-775a-11eb-91b7-17b6261a6d78.png)
![FiveM_GTAProcess 2021-02-25 10-42-53](https://user-images.githubusercontent.com/76709628/109182184-c02f0100-775a-11eb-8f7b-59acf18cae60.png)
![FiveM_GTAProcess 2021-02-25 10-42-48](https://user-images.githubusercontent.com/76709628/109182186-c02f0100-775a-11eb-8156-173e9381dc27.png)
![FiveM_GTAProcess 2021-02-25 10-42-06](https://user-images.githubusercontent.com/76709628/109182188-c0c79780-775a-11eb-81cf-6befcb5e18bd.png)
![FiveM_GTAProcess 2021-02-25 10-38-59](https://user-images.githubusercontent.com/76709628/109182190-c1602e00-775a-11eb-9fea-e839301570bb.png)
![FiveM_GTAProcess 2021-02-25 10-38-46](https://user-images.githubusercontent.com/76709628/109182193-c1602e00-775a-11eb-9a33-a22a1f012692.png)
![FiveM_GTAProcess 2021-02-25 10-37-27](https://user-images.githubusercontent.com/76709628/109182196-c1f8c480-775a-11eb-8fb6-5f2cd5092525.png)
![FiveM_GTAProcess 2021-02-25 10-37-12](https://user-images.githubusercontent.com/76709628/109182202-c2915b00-775a-11eb-9678-d6002dc1bbb5.png)
![Screenshot (1316)](https://user-images.githubusercontent.com/76709628/109182204-c2915b00-775a-11eb-99b4-439f61ff9f2f.png)
![bKVm11y](https://user-images.githubusercontent.com/76709628/109182205-c329f180-775a-11eb-933c-378e6c08df97.png)
![Screenshot (144)](https://user-images.githubusercontent.com/76709628/109182206-c329f180-775a-11eb-98eb-9ad029b280d8.png)
![Screenshot (155)](https://user-images.githubusercontent.com/76709628/109182207-c329f180-775a-11eb-8ff8-1bf184ba19e9.png)
![Screenshot (253)](https://user-images.githubusercontent.com/76709628/109182211-c3c28800-775a-11eb-908c-ca49f7e189d5.png)
![Screenshot (494)](https://user-images.githubusercontent.com/76709628/109182213-c3c28800-775a-11eb-86cb-e8a5e6fafa97.png)
![Screenshot (199)](https://user-images.githubusercontent.com/76709628/109182216-c45b1e80-775a-11eb-942a-700678584733.png)

**Comment by punanipress** [comment]
YES PLEASEEEEE

**Comment by nataliaaaaaaaaa** [comment]
omg yess we need thisss, i need to get rid of my 5 o'clock shadow :/

**Comment by Doughnut2001** [comment]
I don't think a lot of people really care about this very small detail, I personally don't see an issue with regular GTA skin.

**Comment by missskinny** [comment]
> I don't think a lot of people really care about this very small detail, I personally don't see an issue with regular GTA skin.

oh trust me there are many people who would rather us have smooth skin instead of not having it. Also if you or any other people happen to not see an issue with the skin already in game, then that means that if they add it, it shouldn't be a problem because then the people who want smooth skin can have it, and the people who dont care can just ignore it since it probably isnt seen as a big change to someone who doesnt look at details like that

**Comment by InZidiuZ** [comment]
This is an assets-related suggestion. Please redirect this to [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker) issue tracker.
