### ISSUE TITLE
Raspbery Hacking Issues

### ISSUE THREAD

**Issue by Sahil0171** [InZidiuZ/op-framework-issue-tracker#1658]
1> In the Raspbery hacking terminal there is a hack Called "Disable City Power Plant" When I Have done that hack successfully it says "Cutting City power" But it Doesn't cut the power.

2> In the Raspbery Hacking Terminal there is a hack called "Unlock nearby Vehicle" when I have done that hack successfully it should open the doors and start the engines but it only opens the doors when I enter the vehicle it asks for Hotwire 

I would be happy If You Fix this issues.Thank You.

**Comment by PsychoGrandpa** [comment]
Commenting on the 2nd point.
This does make the glovebox accessible but whenever we press K while standing beside the trunk it says **The Vehicle is Locked**.

**Comment by InZidiuZ** [comment]
Read the README file.
