### ISSUE TITLE
Bring Some New Jobs and  suggestion for Raspbery hack 

### ISSUE THREAD

**Issue by Sahil0171** [InZidiuZ/op-framework-issue-tracker#1659]
1• As we've been doing the same jobs again and again. It would be great if we get new Jobs Like "Mining,Wood cutting,Chicken selling"

2•Please Bring A new hack in the raspbery hack.The Hack I wanted Was "Finding other players Location By using his phone Number"It could help us a lot and Bring a Juicy hacking Rp.

THANK YOU

**Comment by ultrahacx** [comment]
Regarding the raspberry suggestion, it will not be implemented soon if anytime as people are not ready for that kind of RP and it would be highly abused by the players.

**Comment by InZidiuZ** [comment]
Read the README file
