### ISSUE TITLE
BIKE KEEPS BLOWING UP

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#166]
**Reporter:**
Who is reporting this? Please include discord name. Allen#0069

**Summary:**
Write a short summary of what you're experiencing. Whenever I take my bike out of my garage, it blows up, so I can't exactly take it out without it blowing up.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue. Not quite sure.

**Expected Results:**
What are the expected results? I expect to take out my bike, and it doesn't blow up!

**Actual Results:**
What are the actual results? My bike blows up

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution? 

**Player Data:**
Write /info whilst ingame and provide the information you're given. 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Please update "Additional Information". Closing until then.
