### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Torpedo02** [InZidiuZ/op-framework-issue-tracker#1660]
**Assurance:**
no

**Player Identification:**
https://steamcommunity.com/profiles/76561198840725668/

**Summary:**
I am Pretty sure i stored my taxi in garage C in which i kept all of my items..and the very next day when i came back to the city my taxi was at impound lot and when i retrieved it, there was nothing in my trunk.

**Steps to Reproduce:**
Just Store any car in your garage.

**Expected Results:**
The vehicle must be stored inside the garage.

**Actual Results:**
The vehicle is stored in your POV but it actually comes out

## Additional Information

**Screenshots:**
n/a

**Game Resolution:**
1920*1080

**Player Data:**
![20210227174452_1](https://user-images.githubusercontent.com/64065580/109386958-53fff900-7924-11eb-8402-f36abf62ab7c.jpg)

**Server:**
 Legacy India 2

**Notes:**
n/a

**Comment by PsychoGrandpa** [comment]
So about impound lot,
Nowadays theres a glitch, whenever we store a car it says "out" or "impound lot".
Dunno anything about the inventory wipe, but this is happening to a lot of people. I suggest from next time screen record and keep a footage of all of your stash and do /info while the screen records. This might help admins get your stuffs back.

**Comment by Torpedo02** [comment]
i mean sir how could we know that this thing gonna happen to us? i lost
most of my valuable stuff..abd the admins are asking me foor a video proof
and this kind of thing had happen to me for the first time and its not
like soome small things have gone but it had many guns in them and how
could an individual know that this gonna happen to him so that it could
record it down..i mean i know that admins are busy with several things but
the only thing that could provide a solid proof in this case is going
through the players logs...we all invested alot oof time gathering he stuff
which i had in that taxi and now its lost atleast can i expect some of
stuff back not all of them! but some..and secondly random looting is not
allowed in the server and this is a case of random looting as well..

**Comment by InZidiuZ** [comment]
Hey, I have no idea what happened & with the lack of information, it's not much I can do to investigate further. Will close this. Feel free to create another issue if you get more info on this.
