### ISSUE TITLE
[game/?] Taking people hostage

### ISSUE THREAD

**Issue by unknownwooptiewoop** [InZidiuZ/op-framework-issue-tracker#1661]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
It's regarding an animation/command in order to realistically have someone in a position where they are a hostage. It allows you to freely move with someone whilst aiming a gun to their head with the ability to either shoot or release them.

https://forum.cfx.re/t/release-take-hostage/840235

**Reason:**
Why would your suggestion be a good change to the framework?
I think it would be a good suggestion because it would really improve the "Hostage" RP from all the sides, criminal, civilian and police. It would also make it look more realistic and honestly quite cool.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
