### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Retrizz** [InZidiuZ/op-framework-issue-tracker#1662]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561198311939767/

**Summary:**
Upgrading my car and losing all upgrades

**Steps to Reproduce:**
I drove the car into the customs, upgraded the armour, colour and underglow, went to store it and once I did, it still had the tag "out" so i retrieved the vehicle and it is back to how it was before.

**Expected Results:**
I expect my car to be pulled out with the upgrades I have just put on it.

**Actual Results:**
I pull my car out and it has been stripped of all the upgrades I added to it.

## Additional Information

**Screenshots:**

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
Legacy Roleplay#1

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
For one, read the README file. And the LSC system is long deprecated so this issue would be left as a wontfix.
