### ISSUE TITLE
The public vehicle repair station located at the south-most part of the city should get an ATM placed inside.

### ISSUE THREAD

**Issue by KingOSSS** [InZidiuZ/op-framework-issue-tracker#1663]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES
**Summary:**
I suggest the public vehicle repair station located at the most southern part of the city should get an ATM placed inside.
**Reason:**
With a few established mechanic shops already in the city, it is difficult for solo people who want to just be a solo practitioner to try and work as mechanics. And it is even more difficult when the public repair station is so far from everything and has no ATM inside. I personally like the challenge of going against the established shops and getting clients while being at a disadvantage as that's part of my character's personality. But not having an ATM inside the shop just doesn't make sense since all the other ones have it for pure quality of life reason. Having an ATM in that mechanic shop will help many others like me who want to run their own car repairing business and will make rp so much more enjoyable.

**Comment by InZidiuZ** [comment]
This is an assets-related suggestion. Please redirect this to [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker) issue tracker.
