### ISSUE TITLE
[jobs/?] Food business

### ISSUE THREAD

**Issue by YhLadd** [InZidiuZ/op-framework-issue-tracker#1664]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Fast food or any food place should be able to get unique food which has benefits over 24/7 / gas station food or just food with benefits over the shops food.

**Reason:**
Why would your suggestion be a good change to the framework?
This would encourage people to go to fast food places and get food instead of just going to a 24/7. This would create a ton more roleplay for the business owners. As a previous worker for Burgershot and now owner of Up-n-Atom not many people bother getting food from our places (other than a select few) even with Up-n-Atoms burgers being $20 which is 2/3 dollars more than what I buy them for from the shops and what everyone else pays and free delivery they still don't really bother.
I feel like this would help a ton with any place that sells food and make people go down. The food could be more  filling than the shop food or give benefits like a sugar rush which makes people run a little faster or something maybe.
With this there would also need to be a place to get this food, Burgershot has their own shop but Up-n-atom has to buy its food from a 24/7 and i guess its the same for taco farmer however I'm not fully sure.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
