### ISSUE TITLE
Suggestion  Link /report with Discord Webhook 

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1665]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
It would be good if any player does/report with reason admin get a notification on discord in embed Form with his reason.
Something like this - https://i.ravicant.in/fRe9
**Reason:**
Why would your suggestion be a good change to the framework?
I mean it's hard for an admin to be in-game 24/7 or when you have more server like India #1/#2 so with the help of this admin can get notified on discord that someone reported or they need help and admin can help them as soon as possible if they are in different server.

**Comment by Nuziatella** [comment]
Also, slight quality of life addition is to include capture of /ban <etc> to print into a discord channel as well

**Comment by InZidiuZ** [comment]
Should we do one channel for all of this, or multiple different channels?

**Comment by Nuziatella** [comment]
One channel, would be ambiguous to have multiple

**Comment by InZidiuZ** [comment]
Yea but, what if you for whatever reason want to have some of this data public and some not? We could make it optional & let server managers adjust it to their liking.

**Comment by Nuziatella** [comment]
This is a personal opinion, but I can't see a situation where it would be ethically reasonable to make reports and bans available for public consumption other than opening the opportunity for targeting. If the door remains open to log other things which are not staff related then I could agree on making it configurable. For just those 2 features I don't think it would be healthy for a community

**Comment by InZidiuZ** [comment]
That's true. I'll keep it single channel for now. If it's requested in the future that multi-channel support is added, I'll do that then.

**Comment by InZidiuZ** [comment]
This has now been added. Reports, bans and kicks will be logged. It is disabled by default as a webhook needs to be added for it to work.
