### ISSUE TITLE
[jobs/police] Seize/Unseize command for PD

### ISSUE THREAD

**Issue by ItsGUARDIAN** [InZidiuZ/op-framework-issue-tracker#1666]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Addition of /seize command for police it would work in a way like  /sieze and /unsieze (for ex: /sieze number plate) this would show the car in player garage seized and cant be retrieved until it is unseized by PD.
**Reason:**
Why would your suggestion be a good change to the framework?
This about benefit PD when they seize a vehicle and create more rp when the individual returns to get the vehicle unseized after the time has passed or he is proved innocent.

**Comment by Sharpeye0420** [comment]
Nice idea , Additional to this I prefer it to seize the vehicle no matter if vehicle has fake number plate. Thinking it IRL , police seize a vehicle so no matter it has fake plate or not.

**Comment by Simmba-R** [comment]
+1 , It would be Great if we add this.

**Comment by TheRonineh** [comment]
We so need this, great idea

**Comment by beasthemant1** [comment]
+1 Yeah this is a good idea.

**Comment by ravicant** [comment]
@Sharpeye0420 @Simmba-R @TheRonineh @beasthemant1 this is not the right way to support any thread or suggestion there is a thumbs up  emo you can use that all of you please Read Rule no. 8 https://github.com/InZidiuZ/op-framework-issue-tracker#rules

**Comment by jai9997** [comment]
+1, good idea

**Comment by Nuziatella** [comment]
A better way to modify this is to have a separate impound for when police do /impound and have a spot in the outside parking lot of MRPD where people can go to retrieve their vehicles from a police impound. The fee should be higher in 2 stages. 1st stage - $1000 misdemeanor and 2nd stage $2000 felonies. So /impound 1 or /impound 2

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
