### ISSUE TITLE
Bug report: Mechanic Review system

### ISSUE THREAD

**Issue by GaM3rShadow** [InZidiuZ/op-framework-issue-tracker#1667]
Assurance: Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Player Identification: What is your steam profile?
https://steamcommunity.com/id/GaM3rShadow/

Summary: Write a short summary of what you are experiencing.
Facing issues in mechanic review system. When I am reviewing any vehicle it is showing every windows in that vehicle is broken. While there is no windows are broken(visually).
If there is any windows is broken the review system is showing every windows is broken and if we try to repair we have to use unlimited glasses still not getting the broken window repaired.

Steps to Reproduce: Include what steps that are needed in order to reproduce this issue.
Bring a vehicle to the mechanic shop and review it.

Expected Results: What are the expected results?
Only broken windows should show in review system. And get repaired properly.

Actual Results: What are the actual results?
Showing every windows including non broken also.

Additional Information

Screenshots: If suitable, include some screenshots.
Video Link: https://drive.google.com/file/d/1UfLJ_UXkTyoekp8HcxN46iC-PCWbAajC/view?usp=sharing

Game Resolution: What is your game's resolution?
1920x1080

Player Data: Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Character ID: 440- Job Data: Mechanic, Los Santos Customs, Tow Driver

Server: What server/community did this issue occur in?
Legacy Roleplay Bangladesh

Notes: For anything else noteworthy.
Its happening with every vehicle and same result for everyone

**Comment by InZidiuZ** [comment]
I will leave this as a wontfix as this is related to a deprecated system.
