### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by iAintLion11** [InZidiuZ/op-framework-issue-tracker#1669]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
FB_iAintLion11
**Summary:**
Write a short summary of what you are experiencing.
Both of my owned vehicles are scuffed. Engine will not turn on. cars have been through server resets and also through anything possible in game by mechanic and police.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?
To fixe both my cars or at least refund me for all the money and hard work and time i put into it all (if u can fix it)
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
2021-03-01 18:50:37
**Notes:**
For anything else noteworthy.
both cars did the exact same thing. broke down after a crash at high speeds and leaked gas, then when repaired and refuled just makes a noise like its trying to start but doesnt. PLEASE PLEASE PLEASE HELP ME!!!

**Comment by ayushpandit99** [comment]
tow the vehicle by the mechanic bring it to repair shop to fix the vehicle then try using jerry can("One Who Has The Keys Of The Vehicle") if this doesn't fix then try giving keys to some other person and do same if this too doesn't work then tow the vehicle and bring it to the fuel station and place it in a way that you can fill the fuel from the fuel pump directly .. mostly this will fix your issue..

**Comment by iAintLion11** [comment]
Okay me and several mechanics have tried all of this besides fueling it
directly from gas station. We spent hours on hours trying to figure it out.
I will try to fuel it from a gas station and let you know how it goes.

**Comment by iAintLion11** [comment]
i got both cars fixed. thank u for your time
