### ISSUE TITLE
Removing cuffs when treated at hospital “reapawning”

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#167]
**Reporter:**
SteezyRen#2828

**Summary**
People dying with cuffs on. Respawning at hospital still in cuffs. 

**Steps to Reproduce**
1. Get cuffed
2. Die
3. Respawn at Hospital with cuffs on still 

**Expected Results**
Respawn without still being cuffed

**Actual Results:**
The opposite of said above.

**Comment by InZidiuZ** [comment]
Same as #165, so closing.
