### ISSUE TITLE
Suggestion: Bringing back the LSPD fleet

### ISSUE THREAD

**Issue by ENDLE5S** [InZidiuZ/op-framework-issue-tracker#1670]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes, I have.

**Summary:**
Write a summary of what your suggestion is about.

Hi, I'm a member of the polish server community and I'm writing that suggestion on behalf of the server's police department. We were talking about our police lately, and all of us are confused about us driving SASP vehicles with LSPD badges on our arms. So our suggestion and request is to bring back the LSPD cruisers fleet. I know that it is the big deal because it would change Police Department on every server around the world but I still think it would be a good idea.

**Reason:**
Why would your suggestion be a good change to the framework?

We think that our suggestion would be a good change because maybe you guys don't really care about your uniforms etc. but here in Poland people are different. Sometimes some random pedestrians are laughing at us because they don't know if we're LSPD or SASP(yes, they are paying attention to it, and so do we). 

Peace out.

**Comment by BUSZ3KK** [comment]
I think it was a good suggestion, most of the clothes in EUP it's for LSPD. Also, the LSPD paint job was better than actually. (I don't mean they are ugly in any way, but the simple LSPD paint jobs that were a while ago were better)

**Comment by Saszkaxd** [comment]
Good idea

**Comment by InZidiuZ** [comment]
This is related to assets. Please post this on the assets issue tracker. (Link is in the README file.)
