### ISSUE TITLE
[game/items] Alcohol effects

### ISSUE THREAD

**Issue by howiethief** [InZidiuZ/op-framework-issue-tracker#1671]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
I would like to suggest adding an Alcohol effect to the city as currently alcohol does nothing, and i dont mean an effect as in cons/pros to your stats, but just a drunk effect in general. (link to show better what i mean below)

https://youtu.be/A8UZTiFr3UU

**Reason:**

There is no other reason to add this other than roleplay, which imo is the best reason :)

Personally i think it would be great and add a lot of fun rp as it actually forces you to "be drunk" when you drink ingame, where as now someone can go chug 20 bottles of vodka at the VU and walk/drive out of there as if nothing happened. 

It would open up more RP for cops as well cus they could actually tell if someone is drunk driving or something like that.
Imo its a small thing to add for a lot of fun and a lot of roleplay opportunity.

**Comment by twooot** [comment]
This was done
