### ISSUE TITLE
Shoulder swap camera

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#1672]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes i have
**Summary:**
Adding a simple script that lets your camera swap shoulders while aiming a weapon on the press of the middle mouse button 
Reference link: https://www.gta5-mods.com/scripts/shoulder-swap-camera

**Reason:**
It is currently not possible to peek the left side of an object while aiming, the camera is always to the right side meaning that sometimes you have no way of seeing the enemy, while they on the other hand can see you and shoot you.

This becomes a big issue in room clearing and close combat, making it impossible to have a fair fight sometimes.
It's a lot more evident in humane labs where people can shoot your exposed knee, or they can shoot you before you can see them, and it becomes very dangerous and almost impossible to survive while peeking to the left.
Newer games like tom clancy's ghost recon and the division have already added these, even in rockstar's latest title RDR2 it's an option, it helps a lot during combat.

**Comment by InZidiuZ** [comment]
I've added this feature now. While you're aiming with a weapon, you'll be able to press X to switch to the other camera. [Here's a preview](https://gyazo.com/1a5ad56d5e77bcf73f8d2b0d1b7d0060).
