### ISSUE TITLE
Add custom race track system link GTA online pass from one check point to another Check point. Because the current Race system is old and it only goes/follows the root marked in map so mostely its like a long race from one point to another point with out turns. Add the check points will help the players to create there custom tracks with twist and turns. Many people are interested in race PLEASE revamp the race system.

### ISSUE THREAD

**Issue by Abhishek7410** [InZidiuZ/op-framework-issue-tracker#1673]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by Nuziatella** [comment]
Please review this before making a request: [Read Me](https://github.com/InZidiuZ/op-framework-issue-tracker/blob/master/README.md)
Also, use the search function. This has already been requested #840
