### ISSUE TITLE
[vehicles/?] Please add Steering Wheel/Pedal/Manual Shifter support!

### ISSUE THREAD

**Issue by OGWanKen0bi** [InZidiuZ/op-framework-issue-tracker#1674]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Summary:**
Providing Steering Wheel/Pedals/Manual Shifter support

**Reason:**
Why would your suggestion be a good change to the framework?
Many other RP servers offer wheel/pedal/shifter support to add to the immersion of RP.  It would be amazing if one could drive in 1st person perspective with an actual wheel/pedal/shifter.  As racing is becoming more prevalent, this will be an option sought after by racers and bring more growth to the server!

**Comment by InZidiuZ** [comment]
'an actual wheel/pedal/shifter' being a physical pedal thing? Like [these](https://gyazo.com/332a8518f30d74423ab3149a079d881a)?

**Comment by OGWanKen0bi** [comment]
exactly those! I have the Logitech G920 and there are some other RP servers that have a mod that brings up a menu in game to configure your steering wheel so you can use it to drive around in game!

like [](https://youtu.be/FqN7JuryX4A) <this

**Comment by OGWanKen0bi** [comment]
[this](https://youtu.be/FqN7JuryX4A)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
