### ISSUE TITLE
[weapons/?] Suggestion Changes regarding stowing long weapons

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1675]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I propose to make system of stowing weapons on back similar to this mod: https://www.lcpdfr.com/downloads/gta5mods/scripts/24264-stow-that-weapon/ 
I'm mainly talking about weapon on back having same attachments and tints as our item in game, but feature of deleting this prop while in car would useful too. Lastly, It would be awesome if cops would have their weapons in front of them like in this picture: https://cdn.discordapp.com/attachments/667088244944404480/667293403830157312/Grand_Theft_Auto_V_Screenshot_2019.09.05_-_23.04.52.73.png 
Coords for this style of stowing: OffsetPosition = 0.0,0.27,-0.02 Rotation = 0.0,320,175

**Reason:**
Why would your suggestion be a good change to the framework?
It would really improve visual experience while using long guns. Especialy in case of MK 2 weapons, which have their barrels as separate attachments and it looks bizarre. Not mentioning lack of magazines and guns being partly visible on the back of the seat in cars.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
