### ISSUE TITLE
[weapons/attachments] Adding Flashlight in pd  Weapons

### ISSUE THREAD

**Issue by Jeetez** [InZidiuZ/op-framework-issue-tracker#1676]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.

Adding of Flashlight in PD weapons like the smg ,carbine and Shotgun. Which will increase the visiblity to police officers.

**Reason:**
Due to the addition of raspberry there are multiple and frequent number of power cuts in the city. lit everyone goes blind(almost) . In combat situations if Flashlight is added to PD Weapons. PD can have visibility in the situatiion. this is also done irl.i.e. a flashlight is attached to side of of Weapon.|
 
Why would your suggestion be a good change to the framework?

This will increase rp of PD. and also come as a realistic comparison with irl and rp

**Comment by pepaj420** [comment]
I think adding it pistol would be nice too.

**Comment by InZidiuZ** [comment]
This won't be done before the inventory is rewritten with more functionality.

**Comment by twooot** [comment]
This was done to a few pd guns
