### ISSUE TITLE
[jobs/taco_deliveries] Local Food Delivery Job

### ISSUE THREAD

**Issue by SmythGG** [InZidiuZ/op-framework-issue-tracker#1677]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Matthew Gibbs Taco Farmer Owner (SmythGG#8913)

My suggestion is about adding local food delivery jobs for Taco Farmer and Up n Atom like what Burgershot has currently. Burgershot can deliver food to locals and make good money off of that. Taco Farmer and Up n Atom doesn't have anything like that which is discouraging to the employees. I'm the owner of Taco Farmer and I would love for me and my employees to be able to go around to locals and legally deliver food. There are not enough legal jobs in the city once you have a government job.

**Reason:**
Why would your suggestion be a good change to the framework?
This suggestion would be a great addition to Legacy because it would add another LEGAL job to the server and give all the employees who work for Taco Farmer and Up n Atom more ways to do their job and make money especially when the city is slow and there arent a lot of people around to sell food to.

**Comment by Blckzilian** [comment]
It's an awesome idea and its only fair to the other resturants aswell since one can already do it. You would see a lot more people trying to apply for jobs around the food industry in the city and at the same time make the city grow even more.

**Comment by mrfishess** [comment]
Great idea!!! xooxoxxoo

**Comment by bestdriverinthecity** [comment]
░░░░░░░░░░░░░░░░░░░░░▄▀░░▌
░░░░░░░░░░░░░░░░░░░▄▀▐░░░▌
░░░░░░░░░░░░░░░░▄▀▀▒▐▒░░░▌
░░░░░▄▀▀▄░░░▄▄▀▀▒▒▒▒▌▒▒░░▌
░░░░▐▒░░░▀▄▀▒▒▒▒▒▒▒▒▒▒▒▒▒█
░░░░▌▒░░░░▒▀▄▒▒▒▒▒▒▒▒▒▒▒▒▒▀▄
░░░░▐▒░░░░░▒▒▒▒▒▒▒▒▒▌▒▐▒▒▒▒▒▀▄
░░░░▌▀▄░░▒▒▒▒▒▒▒▒▐▒▒▒▌▒▌▒▄▄▒▒▐
░░░▌▌▒▒▀▒▒▒▒▒▒▒▒▒▒▐▒▒▒▒▒█▄█▌▒▒▌
░▄▀▒▐▒▒▒▒▒▒▒▒▒▒▒▄▀█▌▒▒▒▒▒▀▀▒▒▐░░░▄
▀▒▒▒▒▌▒▒▒▒▒▒▒▄▒▐███▌▄▒▒▒▒▒▒▒▄▀▀▀▀
▒▒▒▒▒▐▒▒▒▒▒▄▀▒▒▒▀▀▀▒▒▒▒▄█▀░░▒▌▀▀▄▄
▒▒▒▒▒▒█▒▄▄▀▒▒▒▒▒▒▒▒▒▒▒░░▐▒▀▄▀▄░░░░▀
▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▄▒▒▒▒▄▀▒▒▒▌░░▀▄
▒▒▒▒▒▒▒▒▀▄▒▒▒▒▒▒▒▒▀▀▀▀▒▒▒▄▀

**Comment by YhLadd** [comment]
As the owner of Up-n-Atom I would also love this idea would help the community with jobs a ton

**Comment by HentaiSenpaiTV** [comment]
Agreed

**Comment by SmythGG** [comment]
Would love to see this in the city soon!! As a legal person I have no legal job opportunities other than scuba. Please add this!

**Comment by YhLadd** [comment]
Also wanted to add that I made a post over a month ago now about this issue.

**Comment by SmythGG** [comment]
With all the new vehicles coming out and employees wanting to find new jobs because the rest of the food industry doesn't have the same opportunities that burger shot does it would be very beneficial to get these deliveries added to the city sooner than later so we can all have the same opportunities to make money and serve the people and locals of the city. Personally as a legal business owner in the server the only way for me to make money when we are not open is to mindlessly grind scuba which provides little to no rp while doing it. Hope to see this soon, Thanks!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
