### ISSUE TITLE
Clothes - [dpClothes]

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/op-framework-issue-tracker#1678]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Add a script to take off clothes and others part of clothes.

**Reason:**
A large part of the community thinks that script changes the gameplay and most importantly, it would improve the roleplay, where instead of a description you can actually take it off.

**Comment by InZidiuZ** [comment]
This has since been added.
