### ISSUE TITLE
[game/panic_button] Panic button for public services [/pb]

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/op-framework-issue-tracker#1679]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
My suggestion is about the short command /PB.

**Reason:**
/pb, a shortcut of word panic button, the command will help all people on duty when somebody want to fast call to all units on the city to their positions, use a command /bp and then automatically sets the GPS with its location for everyone who is on duty.

**Comment by gighul** [comment]
Huge +1, highly value RP improvement.
To make it go smoothly maybe there should be 1 minute cooldown between each /pb that can be used. And /pb will last on map for 1 exact minute.
In this way we should avoid frozen blips at map.

**Comment by ainstaylor** [comment]
This would be awesome to have, perhaps it could send an audio alert to people who are on duty and/or dispatch notification. Would it be easier to integrate if it sent a dispatch alert and a text message via the 911 with a default message along with a location?

**Comment by twooot** [comment]
this was added for PD and EMS
