### ISSUE TITLE
PD Vehicle modifications.

### ISSUE THREAD

**Issue by TRParagon** [InZidiuZ/op-framework-issue-tracker#168]
**Name:**
Paragon#9700

**Summary:**
Every single vehicle in the PD arsenal especially the Charger and the FPIU have a front bumper that if damaged slightly it starts hitting curbs like a tank, to top that all the vehicle's armor is at -20% it seems hitting 1 pole or a suspect shooting at the engine with 3-4 bullets disables our vehicle and cannot proceed to pursue, Anothing thing are HighWay Patrol vehicles they should be in Faster in terms of top speed than regular ones.

**Reason:**
Yes implement an automatic 100% armor for PD vehicles and improve some of the HighWay Patrol Vehicles in terms of performance, would help the PD immensely.

**Comment by jaymssmith** [comment]
100% is kinda absurd about 40% should be fine and they should have a custom shop of their own where they can increase it, but i agree they need a buff especially high way patrol cars. Its way too easy to get away from them but they shouldnt be mad over powered. I think a top speed of about 170 would be fine for the highway patrol cars but that should affect something like its body armor or something so they are not over powered and cops should be able to get upgrades or something at a specialized Custom shop for only cop cars

**Comment by InZidiuZ** [comment]
Hey,

Police vehicles now have 60% armor by default, and EMS have 100%. Some other handling-related changes were also done by @Karpenko to improve bullet resistance, and other damage.

**InZidiuZ**
*OP-FW Developer*
