### ISSUE TITLE
[?] Adding some /refresh_[?] commands for betterment of the Framework

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/op-framework-issue-tracker#1680]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Adding Some /refresh_[?] commands for players on their daily basis.
**Reason:**
Why would your suggestion be a good change to the framework?

**/refresh_ped** -Will refresh your Ped. As sometimes a player's ped got bugged or not behaving like as usual. Atm, we've to go to the city exit point and exit the city to refresh our the ped. It will be really helpful if you add /refresh_ped, then we can refresh our ped on any spot, any time.

**/refresh_tracker** -will refresh the tracker list. As nowadays, people are complaining about trackers that they're getting some trackers bugged to one place on their map. As one thing I've noticed that those who are on-duty in their jobs for a time being like more than 1 or 2 hours, get to see some bugged trackers on their map. But those who came on duty recently, don't see any bugged trackers. So, if it's possible adding a new system, where if we do /refresh_tracker, will make the tracker list refresh as like the new-comer on duty player's list. So it will be great to fix the Interruption/bugs of the trackers.

**Comment by twooot** [comment]
I don't really see a need for the ped to get refreshed. The trackers have been fixed so there is no need for a tracker refresh command
