### ISSUE TITLE
/checkplate Issue

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#1681]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?

Cruxer

**Summary:**
Write a short summary of what you are experiencing.
/checkplate function for both PDM Boss and Police has a few issues regarding cars with unpaid finances. If for example you run a plate and the owner hasn't paid their finances for the last week it'll write owner has not paid their finances... But if you are running a plate with let's say 2-3 months behind all its payments it won't write anything as if the car was paid for completely with no problem.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
1) /checkplate a car that hasn't paid their finances for months.

**Expected Results:**
What are the expected results?
/Checkplate returns owner hasn't paid their finances even when it's been a few weeks/months
**Actual Results:**
What are the actual results?
Nothing plate comes back clean

**Game Resolution:**
What is your game's resolution?
1920x1080

**Server:**
What server/community did this issue occur in?
Main servers

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
