### ISSUE TITLE
[game/items] Effect after alcohol and drugs.

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/op-framework-issue-tracker#1682]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Better roleplay with alcohol.

**Reason:**
The idea that I came up with Gighul is to diversify the system of effects after stimulants.
This will able to empathize with the role of a drunk person.

My idea and list...
Alcohol:
Beer - No visual effect. But drunk walk style for the next 3 minutes.
Vodka - When you do one jump you fall over. But drunk walk style for the next 8 minutes.
Tequila - Same as vodka. Drunk walk style for the next 7 minutes.
Whiskey - Same as vodka. Drunk walk style for the next 7 minutes.
Cider - You fall over every second jump. drunk walk style for the next 3 minutes.
Rum - Same as vodka. But drunk walk style for the next 5 minutes.
Absinthe - When you sprint or jump, you fall over. Drunk walk style for the next 12 minutes.
Wine - No effect. But drunk walk style for the next 5 minutes.

Drugs:
Oxy - In real life after oxy you are sleepy, tired, or dizzy, I think on our server oxy can give a 25% slow for the player but still heal wounds
Coke - I think it's good but maybe add a hurried style of the walk for the next 10 minutes.
Weed (Joint) - I think it's the same as cocaine, but if we want to add something, we give a 15% chance for the cough animation.`

**Comment by gighul** [comment]
Yeah, would be an great addition. Real effect after using various substances

**Comment by twooot** [comment]
Alcohol has affects now. Oxy has overdosing

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
