### ISSUE TITLE
[jobs/trucking] Slight buff/Change to the Trucking Script

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/op-framework-issue-tracker#1683]
**Assurance:**
Yes
**Summary:**
So currently every time there's a server restart, ALL trucking locations have 0 deliveries to be made, which realistically, would never actually happen, if possible, make it to where when the servers are restarted, and the trucking script get's "started" with the server, all trucking delivery posts get 2-3 jobs immediately put into their registry for people to take.

**Reason:**
I feel like this would 1. Help truckers start doing their job quicker, which would lead to RP with them happening quicker/possibly more often, and 2. It's not so much as a "grindy buff" but something that just would be a QOL change/upgrade.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
