### ISSUE TITLE
Bug Report - Staff - Setting job doesn't show the position is set on the new notification

### ISSUE THREAD

**Issue by ainstaylor** [InZidiuZ/op-framework-issue-tracker#1684]
**Assurance:**
Yes
**Player Identification:**
https://steamcommunity.com/profiles/76561199105726768/

**Summary:**
When setting someones job you now get a notification to say what job has been set. When you do /setjob you get the correct notification, and when you do /setdepartment you get the correct notification but when you do /setposition it shows up as none.
This happened when I was trying to set someones position as a tow driver.

**Steps to Reproduce:**
Do /setjob id Mechanic - /setdepartment id Los Santos Customs - /setposition id Tow Driver
The notifications will pop up but the last notification after doing /setposition will show as none.

**Expected Results:**
After doing /setposition id Tow Driver it should show position is set as Tow Driver in the notification.

**Actual Results:**
It shows as None

## Additional Information
The screenshow shows when I tried twice to /setposition id Mechanic and got a notification that said none. After checking the admin panel the user did infact have the Tow Driver position.

**Screenshots:**
https://i.imgur.com/x7SCtSO.png
https://i.imgur.com/rUdRkoG.png

**Game Resolution:**
1920x1080

**Player Data:**
https://i.imgur.com/UmXuVfr.png

**Server:**
International

**Notes:**
-

**Comment by InZidiuZ** [comment]
This has now been resolved.
