### ISSUE TITLE
[weapons/wearable] New system of holsters

### ISSUE THREAD

**Issue by pepaj420** [InZidiuZ/op-framework-issue-tracker#1685]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
System of holsters like in this mod:
https://www.lcpdfr.com/downloads/gta5mods/scripts/8017-cop-holster/page/18/?tab=comments#comment-276841
It means simply there would be a list of pistols which if unholstered make model of holster swap to similar, but without gun inside, If weapon is holstered model would be swapped back. It could work on same basis with tasers.

**Reason:**
Why would your suggestion be a good change to the framework?
Small feature, but it would look very satisfying. Almost every holster in game has its gunless equivalent, so there want be any problems with assets.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
