### ISSUE TITLE
[jobs/ems] EMS Doctor Sign In Location Change to Dr. Room 373 PC DESK - Suggestion

### ISSUE THREAD

**Issue by MrHitmanDrHitman** [InZidiuZ/op-framework-issue-tracker#1686]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes.

**Summary:**
Write a summary of what your suggestion is about.

Whole EMS Team Faced This Problem, Whenever We Use EMS Locker or Dress Change Circle in EMS Dressing/Locker Room, Most Of The Time We Press "E" on Doctor Sign In Mistakenly. This Some Times Leads To A Big Problem When No Body Realizes That They Signed In As Doctor, Many Times EMS Went On A MedEvac Call Outside City And That Time People Checked In To PillBox Medical Center and They Were Stuck There Without Treatment. 

In LEGACY BANGLADESH We EMS Team Discussed On It, About Doctor Sign In this '**Doctor Office 373**' Computer Desk is Very Good Location in our Opinion. 

![20210313011110_1](https://user-images.githubusercontent.com/59993622/110990917-f941b500-8399-11eb-8bc4-1e06bb72ed47.jpg)
![20210313011136_1](https://user-images.githubusercontent.com/59993622/110990927-fb0b7880-8399-11eb-913f-377de67684eb.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?

Doing This Will Help Us Do Our Job As EMS More Smoothly.

**Comment by ainstaylor** [comment]
I agree with moving doctor sign on duty as it is quite easy to accidentally sign on and then it can cause problems. I'm not sure the suggested place is good enough as it could again be accidentally pressed. Perhaps a doctors room would work better or the treatment room. I disagree with opening up the downstairs reception desk to check in as people will think they can sneak their downed friends into pillbox via the bottom reception when EMS are on duty.

**Comment by MrHitmanDrHitman** [comment]
About the Doctor Sign In, It can be moved to a doctor's room too. 
But in Kitchen, People mostly use 'K' and Door Lock 'E' is out of range from the suggested area. 


When there are more than 2 EMS On Duty, One Can Stay at Downstairs Reception. When there is enough EMS, they can handle the issue, when there is less EMS a strict announcement against lazy Role-Players will work. 
If still it's not that good, maybe make store there, so people can buy First Aid Kit. (At least it will be used)

**Comment by ainstaylor** [comment]
I don't like the idea of having to split people who are on duty up to man the downstairs reception, ems workers like to socialise with each other whilst waiting on calls or patients. Also personally I think it's a bit powerful having to put out server announcements about calling EMS, currently EMS tweet they are on duty and people should always call and wait for a response regardless of EMS being on duty, repetitive server announcements don't fix the issue and spoil peoples immersion into roleplay. Repeat offenders ideally should be personally warned and punished accordingly instead of targeting the whole server.

**Comment by MrHitmanDrHitman** [comment]
I do agree on that note, That is why I want to cancel the second Check In and get the Pharmacy Store Instead. Or Make a EMS Tool Shop for buying Oxygen Tank, Bolt Cutter, Parachute etc.

About Doctor Sign In this '**Doctor Office 373**' Computer Desk is Very Good Location in my Opinion. 

![20210313011110_1](https://user-images.githubusercontent.com/59993622/110990917-f941b500-8399-11eb-8bc4-1e06bb72ed47.jpg)
![20210313011136_1](https://user-images.githubusercontent.com/59993622/110990927-fb0b7880-8399-11eb-913f-377de67684eb.jpg)

**Comment by BmFarhan** [comment]
Kindly, please the README.md file here [https://github.com/InZidiuZ/op-framework-issue-tracker/blob/master/README.md](url)
As you've attached multiple things in one place.

**Comment by MrHitmanDrHitman** [comment]
Fixed my mistake here @BmFarhan

**Comment by InZidiuZ** [comment]
I looked into this, and the suggested room that the on-duty marker would be moved to, is too far away from the reception. There also doesn't seem to be any issues with door locks & the on-duty marker colliding, so not sure why you're having issues with that. If you have a better location not far away from the reception, then feel free to reopen this issue or create another one.
