### ISSUE TITLE
Bug report - Random player death upon spawning into the server

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1687]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561198083628029/

**Summary:**
Quite a few mentions from various communication channels including my own experience of exiting the server either outside or inside an interior (or house) and upon re-entering the server you spawn at pillbox as if you died. You get the "you have been mugged" and lost of inventory items as well as being charged for your stay. The time frame is not relevant as it's happened from simply leaving and rejoining. Admin panel doesn't reflect cause of death. Just says character unloaded and then loaded followed by being charged at pillbox. 

**Steps to Reproduce:**
Exit city marker and quit or F8 > Quit. Rejoin server and spawn at pillbox dead. Random and not easy to re-produce. 

**Expected Results:**
What are the expected results?
Wake up not dead if you weren't dead upon exit.

**Actual Results:**
What are the actual results?
As mentioned above. Randomly waking up dead at pillbox even though when you exited you were not dead. 

## Additional Information

**Screenshots:**
https://gyazo.com/c02e92fecfbc6672bcee84761fc7d4af
Most recent user who asked about this behavior 

**Game Resolution:**
What is your game's resolution?
2k

**Server:**
What server/community did this issue occur in?
main server

**Comment by InZidiuZ** [comment]
I believe this issue is related to the training system. I've made some adjustments to hopefully prevent this from happening, though I wasn't able to get a consistent repro so no guarantees.
