### ISSUE TITLE
Rework of Fire Chili Shop!

### ISSUE THREAD

**Issue by CillerYoutube** [InZidiuZ/op-framework-issue-tracker#1688]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes!**
**Summary:**
Howdy, my name is Ciller. I would love for you guys to rework the shop "Ring of Fire Chili Shop" into a Donut Shop! I have already contacted state about the purchase. Everything is ready to go!

**Reason:**
I feel like this would add another fun restaurant to the city that servers a different type of food. I would hope to upscale to be like atom burger, therefore my employees could work all day. I'm loving the city and I would love to become a restaurant owner! Thank you! If you need to contact me about anything contact me on discord Ciller#1100

**Comment by InZidiuZ** [comment]
Are you suggesting an interior to be added to the shop?

**Comment by CillerYoutube** [comment]
> Are you suggesting an interior to be added to the shop?

I want to start up a a donut shop business like burgershot. People can do orders anytime, interior, donut instead of chili, etc.

**Comment by InZidiuZ** [comment]
Okay, if you're just suggesting deliveries then this is the place to do it. If you were suggesting an interior however, or both, that would have to be redirect to [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker) issue tracker.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
