### ISSUE TITLE
[illegal/*] untaxed money from illegal activities.

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1689]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**_YES_**

**Summary:**
Introducing a system of untaxed money, simply speaking there will be two types of money in server.
Regular one, you can buy with these everything like you used to this point. (e.g cars, food, houses literally everything)
Untaxed money which will be earned from llegal income such as:
-OXY sidejob
-Money stolen from local NPCs during a car steal
-House robbery
-Selling drugs
-Selling jewelry from robbery
-Money from shop/bank robbery

In the same time we should add hidden place when you can rent car for delivery jobs, we may pay 1000$ deposite which will be refund after completing the course 
(system may be simmilar as OXY sidejob, going here and there, deliver packages then **untaxed** money will be changed for **taxed**)
For every 10,000 there may be one trip for 5miles.
If truck will be heavily damaged then deposite cannot be refund.

**Reason:**
It implements high quality system which reflects real life crime activities.
Additional RP thread, possibility for crime organisations to hire people just for laundery.

**Comment by Nuziatella** [comment]
Splitting the economy is generally unhealthy and makes for difficult balance. While the idea is refreshing, overall this type of change can lead to it's own subset of imbalance and inequalities.

**Comment by gighul** [comment]
> Splitting the economy is generally unhealthy and makes for difficult balance. While the idea is refreshing, overall this type of change can lead to it's own subset of imbalance and inequalities.

socialism is unhealthy and still exist xD

**Comment by kloocek** [comment]
I think the untaxed money has no sense, at least in the cases in which you wrote out.
When an NPC gives you money (in the case of car theft), he is a legally working person and gives us the money earned.

**Comment by gighul** [comment]
> I think the untaxed money has no sense, at least in the cases in which you wrote out.
> When an NPC gives you money (in the case of car theft), he is a legally working person and gives us the money earned.

What you just said means you do not understand the concept of illegal income.
This person you robbed had these money all the time and worked for it, had it documented by bank transfer check or something, in a moment you rob him you earn money in a way that you did not meet the criteria of LEGAL INCOME.
fyi

**Comment by Nuziatella** [comment]
But, the money is still just that, money. Your asking to make 2 different types of currency. Does this require a separate bank account? Does this need to be an item in inventory that doesn't reflect /cash on hand? Does 2 values need to appear when you /cash? Does PDM require only "legal" money? What about EDM, pillbox, etc..? Creating 2 separate economies with 2 different economies is just superfluous. When I go to the store to purchase something, they don't ask if it's "legal" income. They just expect payment. Again, while your idea is interesting; it suffers from a huge swath of imbalances which would only goes negative effect on economies. 

Another suggestion that separates the "legal" money from "dirty money" has already been suggested. Now being able to get money that can't be used yet until it's "cleaned" is a tried and tested system which I think is the direction you are trying to head. #979

**Comment by ainstaylor** [comment]
Many people do cash jobs, sell drugs/weapons for cash, it is illegal money however it is somewhat hard for the banks and governments to trace. Hence why it is a relatively safe method of payment. The only time the government would question things is if perhaps you work as a garbage man but own a mansion and multiple expensive cars. I don't like the idea of two separate money systems.

**Comment by gighul** [comment]
thank you for your entry

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
