### ISSUE TITLE
Suggestion - Metadata for Jerry Cans

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1690]
**Assurance:**
Yes

**Summary:**
I think that there should be metadata for Jerry Cans because right now as you can see in this photo: https://gyazo.com/52f9d4cd2168fbf31742d06d3a09e371 all it has is a description... but It would be helpful if it had something like "Fuel: 70%"

**Reason:**
It would help the framework because when people have jerry cans they will need to actually "use", or pull out the jerry can in order to see the amount of fuel left inside of it. It would be helpful if you could just hover over the actual item and have it say "Fuel: 70%" instead of having to actually pull it out. Also according to my calculatiolhns "op-framework" runs at 0.8 ms and it would bring that ms down to around 0.2 if we added this.

**Comment by InZidiuZ** [comment]
This has now been done.
