### ISSUE TITLE
[jobs/*] Changing extras on Police/EMS Vehicles

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#1691]
**Assurance**
Yes

**Summary**
Change the current extra system for Police/EMS vehicles from, for example, "/extra 1 on", to "/extra 1". A toggle system essentially for the extras instead.

**Reason**
Would make adding and removing specific extras from vehicle just a bit easier, and IMO a lot more efficient. Just a small change that really wouldn't affect anyone in a negative way and makes getting vehicles out of the garage, and selecting their extras easier.

**Comment by twooot** [comment]
If you're just looking to set your extras faster, you can do something like /extra 2,3,5 on now and toggle a bunch of extras on at once

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
