### ISSUE TITLE
t/Unit_ID improvement

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/op-framework-issue-tracker#1695]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Unit ids should be different for different characters. Suppose you have an EMS character and SASP character, when you put a unit id for your EMS character, it remains the same in SASP character. You have to put the SASP unit id again. It creates character mixup. 

**Reason:**
Why would your suggestion be a good change to the framework?
It would avoid character mixups and will be easy for us to not put unit ids again and again on character change!

**Comment by InZidiuZ** [comment]
This has now been done.
