### ISSUE TITLE
Suggestion - Add /outfit area in Mechanic shops

### ISSUE THREAD

**Issue by uniquevoid6969** [InZidiuZ/op-framework-issue-tracker#1697]
**Assurance:**
Yes

**Summary:**
Most mechanic shops if not each one has a location that would be ideal for the employees to `/outfit work` or `/outfit` 
this would be mostly for convenience so the employees of the mechanic shops can change into mechanic outfits or work clothes at the shop and change into any other outfits after they stop working without having to go to a clothing store each time.

I use to work over at TheLostMC there is a dresser with jackets and boots in the new building next to the material computer that could be used as a changing location for them,

![gabz-map-lost-mc-26536532476055_1000x1000](https://user-images.githubusercontent.com/81113308/111919289-a9c94c00-8a5f-11eb-86cb-17cc0de21194.png)

over at Mosley's, we have an entire locker room around in the back. that could have the area in it to change outfits.

![763736-0_20200227223444_1](https://user-images.githubusercontent.com/81113308/111919145-d2047b00-8a5e-11eb-8651-07e55866615f.png)

I'm not sure if the other Mechanic locations have changing areas but since these two shops are currently the largest in the city and employ the most people I think starting with these two would be a good idea. and if any other shop owners like flywheel or the one up in Paleto want one it could be added later on.

**Reason:**
Mostly for convenience just a nice touch I don't think it would be that difficult to drop the region down for the command so people can use it in those locations and it would help out allow the shops to enforce dress code policies a little better. etc

**Comment by InZidiuZ** [comment]
This has now been done on both of the suggested locations.
