### ISSUE TITLE
[game/properties] Loading issues

### ISSUE THREAD

**Issue by scarlexknigght** [InZidiuZ/op-framework-issue-tracker#1698]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
 https://steamcommunity.com/id/scarlexknigght/

**Summary:**
Forum Drive Complex B; apartment 17 seems to be causing an issue for people whereas we enter the house, the screen is completely black and even the house in my company tablet says 20/20 occupied instead of 21/21 houses occupied which I believe the apartment 17 seems to be a bug and the people residing in that house lost all their stuff as well.

**Steps to Reproduce:**
Include what steps are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/81098231/111925198-d7e57500-8acd-11eb-9278-d89b46e40b1d.png)
![image](https://user-images.githubusercontent.com/81098231/111925268-1c711080-8ace-11eb-9107-230e971f05a4.png)

**Game Resolution:**
What is your game's resolution?

**Player Data:**
![image](https://user-images.githubusercontent.com/81098231/111925281-33affe00-8ace-11eb-82c9-7d6a55bcd468.png)

**Server:**
Legacy India Roleplay Server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
> Forum Drive Complex B; apartment 17 seems to be causing an issue for people whereas we enter the house, the screen is completely black

Does this happen at a constant? Does it ever work?

**Comment by scarlexknigght** [comment]
Nope, it worked in the beginning and now it's constantly black. Initially, when I gave the house to the person, it was working and after 4 days or so, he was unable to enter the house, just black screen so we thought it might be his cache issue or so, and then other people tried as well by giving access to the house and everyone seems to face the same issue.

**Comment by InZidiuZ** [comment]
Is this still happening? I just tried locally and it did load. Perhaps there is some furniture causing issues. You said this was on the 'Legacy Roleplay India' server, but which one? Public or WL? I can try to copy the furniture from whichever server it is on & then see fi I can reproduce it locally.

**Comment by InZidiuZ** [comment]
Never mind, I just saw the screenshot which indicates that it's the public server. I'll take a look now.

**Comment by scarlexknigght** [comment]
Let me know what will be the issue cause there are tenants staying there and they have their stuffs as well.

**Comment by InZidiuZ** [comment]
I looked further into it and found out that the furniture object labeled "Cabinet 3" was the culprit here. I've removed that model from the furniture list, and when it is attempted to be loaded, it'll be replaced with an American flag.
