### ISSUE TITLE
Drugs Adjustments

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#170]
**Name:**
Badwolf#3160

**Summary:**
I think when the city gets the company and other systems public i think weed and coc should be removed from the public. the introduction of weed seeds will be pretty nice 

**Reason:**
It would be nice for things to be a lot more secretive when it come to illegal things

**Comment by InZidiuZ** [comment]
Hey,

This suggestion isn't really relevant at the moment, so closing. This has also been discussed on previous occasions.

**InZidiuZ**
*OP-FW Developer*
