### ISSUE TITLE
[jobs/ems] Make Sandy Shores Medical Center open to spawn ambulances and check in patients

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/op-framework-issue-tracker#1700]
**Assurance:**
Yes

**Summary:**
To open up Sandy Shores Medical Center to allow spawning/repair of vehicles and allow patients to check in and be healed.

**Reason:**
As an EMS I have been making significantly more calls up to the Sandy Shores area as of late. Unfortunately for the patients they are roughly smack in the middle between Paleto Bay Hospital and Pill Box making their drive to either location long and dangerous depending on how locals are. Opening a location there would make it easier for citizens of Sandy Shores to be treated for simple  injuries as well as easier for ems to drop the patients off at a more central location.

**Comment by InZidiuZ** [comment]
This would most likely require an interior, which would have to be suggested in [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker) issue tracker.

**Comment by InZidiuZ** [comment]
This has since been done.
