### ISSUE TITLE
[jobs/mechanic] Tow Driver not able to impound local owned vehicles

### ISSUE THREAD

**Issue by DexDynex** [InZidiuZ/op-framework-issue-tracker#1701]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/iDynex

**Summary:**
Write a short summary of what you are experiencing.
After the latest update that was pushed to the server Tow drivers are no longer able to impound local cars. (player owned vehicles are working fine)

Tow driver is able to /tow the vehicle onto their tow truck, the issue is when turning the vehicle into the impound lot. The local vehicle stays on the back of the tow after hitting 'E' on the prompt to turn it in. The prompt goes away, no money is issued to the tow driver and they are left with the vehicle.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I set myself as a standard tow driver and was able replicate the issue by:

1.Finding an illegally parked local owned vehicle.
2.Back the tow up to the car and perform a /tow
3.Local car is put on the back of the truck.
4.Drive tow truck to impound lot and back the truck up to the impound spot.
5.Press 'E' on the prompt to turn the vehicle in.
    The local vehicle is still on the bed of the tow and no money is issued.

**Expected Results:**
What are the expected results?
The local car is supposed to be turned into the impound lot and the tow driver is to be issued $50 per local vehicle impounded.

**Actual Results:**
What are the actual results?
The local vehicle is still on the bed of the tow and no money is issued.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![Tow info](https://user-images.githubusercontent.com/80129893/112187077-22531880-8bd8-11eb-9b69-325bf06ae5d3.PNG)
![Attempt Impound](https://user-images.githubusercontent.com/80129893/112187093-25e69f80-8bd8-11eb-937e-fc20dbc85a69.PNG)
![After Attempt](https://user-images.githubusercontent.com/80129893/112187108-2a12bd00-8bd8-11eb-9b9b-724933761152.PNG)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Tow info](https://user-images.githubusercontent.com/80129893/112187363-6a723b00-8bd8-11eb-8f25-6c4a3f4a10f8.PNG)

**Server:**
What server/community did this issue occur in?
International (NA/EU)

**Notes:**
For anything else noteworthy.
This was first reported by a Tow Driver and then three others reported it with the same job info that I have in the screenshot above. As I stated above turning in player owned vehicles is working and returning a payment of $450 to the driver.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
