### ISSUE TITLE
[jobs/ems] Suggestion/issue with the EMS Doctor Sign In

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/op-framework-issue-tracker#1704]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Do some to prevent the issue with ems Doctor sign in

Step: 1
Adding commands like /doctor_sign_on/off
making it as the command will help people more, as sometimes ems unintentionally sign in as a doctor and go too far from pillbox to respond calls, in between they forget about their doctor sign in and then the patients can't get treated.
But there is some complication here too, like: there are 2 hospitals on the server. So need to make 2 different command-based systems.

Step: 2
Decrease the range of Doctor sign-on. 
 Here are some pictures, from where you can clearly see the range is kinda higher than as usual.
 --> [1](https://gyazo.com/56da4136aa7027f127549ebb0376128a)
 Also while locking doors
 --> [2](https://gyazo.com/f0df7ed13756f2b976615637928e0449)
 Also while changing outfits
 --> [3](https://gyazo.com/02acdd3b805e6ebfc560b4cf9d0cf797)
 So decreasing the range also may work for the unintentional doctor sign-on.
 
 Step: 3
 Changing the place of doctor sign-on
 I got some locations where you place the doctor's sign on easily and also closer to the ward area.
 Place -->1, The staff room in ward A [Link](https://gyazo.com/e3ebf0991d5fd443a556f4e987c0a624)
 As its quite a big room, so it'll easier to place it there [Link](https://gyazo.com/93e5c27999ab69a37aa47b858492af1c)
  
**Reason:**
Why would your suggestion be a good change to the framework?
As I said before, people are facing problems with unintentional doctor sign-on. So making it possible will help them a-lot!

**Comment by twooot** [comment]
This is fixed now with the doctor sign in being moved
