### ISSUE TITLE
[game/inventory] Can We Reduce the Amount for PD Tracker and MicroPhone 

### ISSUE THREAD

**Issue by imDazzler** [InZidiuZ/op-framework-issue-tracker#1705]
**Assurance:**

**Summary:**
The Amount for PD Vehicle Tracker & PD Microphone is 2000$ Right Now Can You reduce It to 500 or 700 as If we use this in Any Kind of Situation This is very Costly to Purchase.

Link:

**Reason:**
As its not possible to Purchase this items as its too Much Costly

**Comment by DaxterPancake** [comment]
Personally, I feel like because of what these items do, the price is fine. If you can't afford to buy any, then maybe ask someone in PD higher than you to. We have no issue with the prices in the International server.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
