### ISSUE TITLE
[game/doors] Suggestion: EMS/PD can unlock doors when on duty.

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1706]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I suggest that when EMS or PD is on duty, they can unlock "locked" doors that they would not normally be able to unlock.

**Reason:**
Why would your suggestion be a good change to the framework?
When responding to PD for example we will need PD to open up the gates/doors to get into the Officer/Patient that could be down and need medical attention.  It is the same thing if someone owns a business and has the doors locked and something happens we have a way to get to them and bring them out.  We would not have access to anything else inside the locked doors except for bringing the patient out.

**Comment by mxttx** [comment]
maybe work this into /breach - if door is not a teleporter to a player owned house, instead make it perform an animation of breaking a door down and then it becoming unlocked.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
