### ISSUE TITLE
[illegal/chopshop] Potential new way of doing Chopshop

### ISSUE THREAD

**Issue by ThatGuyJayXD** [InZidiuZ/op-framework-issue-tracker#1707]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
So my suggestion is with the introduction of the new raspberry chip i think it would be a good idea to add in some form of way for us to obtain a list of chop cars either by using the raspberry chip or a normal hacking chip at a computer somewhere on the map (Could use lesters now its not used for guns). The idea behind it would be to go to the computer and use either of the chips that you would want to use either the raspberry or normal hacking chip, you would get some form of hacking game and after completing the hack game you would be given either a list of cars that you could chop in a set time so either (6,12,24 Hours) or once per restart whatever you would think would be a good / fair amount. You could also make it so that people had to use something like the Decryption keys in an order which would also mean that it would remove a bunch of them from circulation same as the old gun ruinning ways. 
**Reason:**
Why would your suggestion be a good change to the framework?
I believe that a change to the way chopshop is currently now would be very benefitial due to the fact that the current way it is done can sometimes be problematic as in the specific car that it requests is blown up or disabled beyond repair also the fact that in its current state people will "Spam" chop to get the certain items like .50's other weapons, thermite , keys and so on where as some people do chop just as a different way of passing time. I know chop in the current way it is its more like a competition to see who gets the car first but i believe more people would enjoy if it was changed up a little bit. Plus adding in the ability for people to have to use a chip and keys would limit the amount of "danny's / New people" just knowing how to do it instantly and make them have to actually get over an obstacle or two before being able to just chop cars.

**Comment by nikkoendres** [comment]
I love the idea, it would be super interesting if there was a specific list of cars that had to be chopped and the list wouldn't change until one of every car was delivered or tsunami. Instead of it being a race for one car it could become who gets the most cars out of a 8 car list.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
