### ISSUE TITLE
[vehicles/garages] Changes in Vehicle Retrieval System

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#1709]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Vehicle Retrieval Cost Should be Increase To 1000$ Also Vehicle Should Remain(Shown as Out) Even On Sever Restart(If it's not stored in the garage)

**Reason:**
Why would your suggestion be a good change to the framework?
as the current system is being abused by people as they don't store their damaged vehicle as they know it will come back in the garage as last stored form on server restart. (this not storing thing also increases the load on the server as there are more vehicles lying around (hidden places where mech don't usually go ) and on roads)  also, people intentionally blast their vehicle rather than getting it repaired as retrieval of the vehicle just cost 250$ and repair cost would be higher so to save money.

**Comment by NOTMIRCHI** [comment]
This is a good suggestion. As people just wait for the restart to get their vehicles fully fixed....or just retrieve them from a far away garage.

**Comment by scarlexknigght** [comment]
I have a better suggestion:- 
The retrieve for different types of vehicles should have different prices like for example; supercars can be up to $1000 and bikes could be something around $250 cause it kind of makes sense as well and talking about the server restart thing; The whole point of the server restart thing you mentioned does make sense, no doubt! But then again it's a normal server so I don't think it should be that much of a try-hard thing but it is quite profitable for the mechanic department.

**Comment by ayushpandit99** [comment]
yea I agree with dynamic price retrieval based on vehicle category it's good and fair and obio and this is not limited to legacy India most sub-divisions people do this thing

**Comment by InZidiuZ** [comment]
> they don't store their damaged vehicle as they know it will come back in the garage as last stored form on server restart
Wouldn't a better solution to that issue be to have damage save as it's changed? So that it couldn't be abused like it is now.

**Comment by ayushpandit99** [comment]
> > they don't store their damaged vehicle as they know it will come back in the garage as last stored form on server restart
> 
> Wouldn't a better solution to that issue be to have damage save as it's changed? So that it couldn't be abused like it is now.

hmm but what to do of the burned vehicle? will it be saved as burned?

**Comment by InZidiuZ** [comment]
It would just come out with a broken engine & low body health

**Comment by ayushpandit99** [comment]
> It would just come out with a broken engine & low body health

seems good then!

**Comment by Subzi-wala** [comment]
> It would just come out with a broken engine & low body health

Very nice idea!!!

**Comment by twooot** [comment]
This has pretty much been done
