### ISSUE TITLE
Not able to store Medical Helicopter at Pillbox

### ISSUE THREAD

**Issue by CoffeeConquest** [InZidiuZ/op-framework-issue-tracker#171]
**Reporter:**
Z-104 F.Goldberg

**Summary:**
Not able to store the medical helicopter

**Steps to Reproduce:**
Spawn helicopter as an EMS, try to park it again

**Expected Results:**
Helicopter disapers

**Actual Results:**
Helicopter does not disapear

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. After next patch, you should be able to properly park a helicopter.

**InZidiuZ**
*OP-FW Developer*
