### ISSUE TITLE
request - Limit Speed on Trash Trucks

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1711]
Would request a 75mph limit be put on trash trucks for 2 reasons.

1.  its more realistic
2. would be a public service as a LOT of accidents and damage happen from them trying to do 110 on the way back from routes.  less tows, and local cars sitting damaged / abandoned.

**Comment by AverageStatistic** [comment]
No

**Comment by InZidiuZ** [comment]
Read the README file
