### ISSUE TITLE
Issue - LostMC Garage issue

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1713]
In the single bay garage, when a car is in that bay, no other functions work.  You cant fill a car with a jerry can, the car wash next door is unusable, and you cant even use the "H" muscle to change outfits in that area.  This is new as of the push from Tuesday.  Tested and confirmed with many people.

Happy to relay more details or help if needed, just let me know.  Thanks!!

**Comment by riedling11** [comment]
Boomboxes also cant be controlled.

**Comment by InZidiuZ** [comment]
Read the README file
