### ISSUE TITLE
[vehicles/boat_shop] Boat shop

### ISSUE THREAD

**Issue by c-ef** [InZidiuZ/op-framework-issue-tracker#1714]
**Assurance:**
I have

**Summary:**
I love to see a boat shop and boat garages. Being able to purchase boats and use them.
https://github.com/esx-framework/esx_boat

**Reason:**
Boats would advance a lot of roleplay and allow a lot of different and new situations occur within the servers. It will also give some people with a lot of amount of money to spend it on. I believe it would add a whole new aspect inside the servers.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
