### ISSUE TITLE
Issue in LostMC Repair Bay (single bay building)

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1715]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?  Yes

**Player Identification:**
https://steamcommunity.com/id/riedling/

**Summary:**
The single bay building in LostMC is broken since Tuesday.  If a car is in teh bay, you cant use the carwash, you cant use a jerry can to fuel a car, you cant use a boombox, and can't use the "H" to pull up the appearance wheel.  Its like no other "muscles" can be used while the bay is populated.  After the car leaves, all work as expected.

**Steps to Reproduce:**
Pull a car into the bay, and attempt any of the things mentioned above.

**Expected Results:**
They should all work properly

**Actual Results:**
none of the actions work

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
3840x2160

**Player Data:**

[info.pdf](https://github.com/InZidiuZ/op-framework-issue-tracker/files/6216070/info.pdf)

**Server:**
EU server I believe, i connect to c3s1.op-framework.com

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Did you do anything to make this happen? Did you get any errors? I tried reproducing it as shown [here](https://gyazo.com/859740ced2d5686f3ada00ae80925117), but I wasn't successful.

**Comment by riedling11** [comment]
No, we put different cars in the bay, and its fairly consistant.  I just tested, with a car in the bay, i went into the car wash, and while i can flex the e muscle, and no wash.

**Comment by riedling11** [comment]
OH.,  Its the single bay one.  Not the one with 4 bays, so the one across teh way.

**Comment by riedling11** [comment]
so park a car in the repair bay, THEN try to get a wash.

**Comment by InZidiuZ** [comment]
Could you post a gif or video of it?

**Comment by riedling11** [comment]
ill try, it happens in the other bay too.. there are 2 cars being repaired in the bay, and im trying to use the clothing ring, no dice.

**Comment by riedling11** [comment]
what about a discordia screen share?

**Comment by ayushpandit99** [comment]
i did try to reproduce this yea you cannot open the dpclothing ,cannot fill petrol through jerry can inside the left side small repair shop and  in lmc repair shop here is the video link  though the washing seemed to work fine
https://youtu.be/33YNNDGptlE

**Comment by riedling11** [comment]
video is accurate.  Same is true in our other bay in the ither building.  I'm trying to record a video showing a car in teh bay, and the car wash next to it not working.  at least this is a good start, Thanks @ayushpandit99

**Comment by ayushpandit99** [comment]
the jerry is un-useable in every repair shop when the vehicle is lined up for repair ie
![20210328005211_1](https://user-images.githubusercontent.com/68945345/112732422-ddc0d780-8f5f-11eb-8220-697caf9d9cf8.jpg)

**Comment by riedling11** [comment]
Thats new from Tuesday.  If a car comes in with a bad issue, leaking fuel, we cant fix the car, then add gas to drive it out.

**Comment by InZidiuZ** [comment]
Okay I think I know what's going on. I've pushed some fixes that'll be live everywhere on the next restart in 2 hours. Please let me know if this is still an issue after that.

**Comment by riedling11** [comment]
I've got a few more tests to run, but looks promising!! Was able to see clothing wheel and jerry can in the one bay so far.. ill report back shortly

**Comment by riedling11** [comment]
ill keep checking, but it looks fixed.  ill close this for now, THANKS!!!
