### ISSUE TITLE
[game/inventory] Storage Lockers at LostMC

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1716]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Would like to request some mechanic storage lockers at LostMC.

**Reason:**
Other shops in the area have this feature (Flywheels), and it would really help us out.  Currently we have to store materials in vehicles all over the place, which is inefficient, and also exposes them to theft.

**Comment by ScotsMan-07** [comment]
Agree

**Comment by HentaiSenpaiTV** [comment]
Yeah they need to put in those lockers for use im so sick and tired of losing money because my fucking materials poof out of my car even tho i garage it

**Comment by riedling11** [comment]
We have no properties close by for storage, so it makes it extremely difficult to get new mechanics when they cant store materials on site for use.  They dont make any money when buying from the computer.

**Comment by rajbastakoti** [comment]
as a lost mc mechanic , this has happened to me a lot of times , besides locker  no properties / garage are near to it which makes task difficult

**Comment by PoshoGH** [comment]
+10000

**Comment by InZidiuZ** [comment]
This has now been added.
