### ISSUE TITLE
[?] Storage at the Docks Mechanic Shop/Slight adjustment of Teleports

### ISSUE THREAD

**Issue by iiDrop** [InZidiuZ/op-framework-issue-tracker#1717]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I have fully read all the rules and understood them

**Summary:**
Would like to request some storage lockers at The Docks Mechanic shop.
Teleports for vehicles would it be possible to make the radius bigger or just move them slightly.   
Lock Office door if possible to keep storage in there and its safe

**Reason:**
Why would your suggestion be a good change to the framework?
Storage:
We have to keep materials in pockets or in cars/flatbeds also with it only being a teleport marker with no lockable doors its easy to get in there and see a personal vehicle, which could easily be robbed.

Teleports:
Reason behind having them moved slightly is its a mechanic shop, people come for repairs but with how close they are to the exit 90% of time people always end up crashing into the invisible wall meaning they leave with damaged vehicles

**Comment by twooot** [comment]
The docks mechanic shop is barely used and after careful consideration i have decided to remove it (or as the kids say these days YEEET)

**Comment by iiDrop** [comment]
1 year later 😂
