### ISSUE TITLE
[jobs/hunting] Suggestion for added features of hunting

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/op-framework-issue-tracker#1718]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**

Hello, I have a suggestion to the already added hunting permit stuff from the government to give hunting alittle more role play and bonus. Add a hunting store to buy items for the trip also not sure how to change the script at all but other servers I have been on, you can hunt all the animals to get skins and leather and sell them for some money. I think this would add another aspect to the server and role play that is there. And bring more to the hunting side of things. I have been asking in game for hunting supply for a few days and have gotten  no response. Also I have had a few people message me asking how to get permits and everything so. If this can be brought to the server I think it would open up another side of people’s characters and role play.

Hunting store https://www.gta5-mods.com/maps/mlo-hunting-equipment-store-add-on-sp-fivem
Hunting script https://forum.cfx.re/t/release-esx-hunting-hunt-animals-and-sell-meat/157872
A video of it https://m.youtube.com/watch?v=iENrLdxJJzA

**Reason:**
Why would your suggestion be a good change to the framework?
As I stated above this would add more to the hunting permit stuff already in place and give more to the role play of hunters. Submitted by KrigTroff #8460 on discord

**Comment by KrigTroff** [comment]
Also adding this into the server would give people something else todo beside crime all the time. Also it gives us good and legal citizens something to do. Cause right now there really is nothing for us to do. I understand the game and what it’s based around.  roleplay is roleplay not everyone that is not PD or EMS want to do crime some of us need and want to be legal law abiding people. Just need something for us also.

**Comment by KrigTroff** [comment]
any more updates on hunting, I know hunting licenses have been booming this last month, and the hunting store was setup. I go hunting at least once or twice a week. Would love to see more done with this for citizens.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
