### ISSUE TITLE
[jobs/ems] EMS Boats

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1719]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
My suggestion is that we are able to spawn EMS boats at any waterway to pick up patients in the water.
**Reason:**
Why would your suggestion be a good change to the framework?
Since I have been in the city we have had several patients in the water and no real easy way of getting to them.  With having an EMS boat it would be quick and easy to reach the patients in the water.

**Comment by twooot** [comment]
this has been done
