### ISSUE TITLE
Suggestion: Instead of only using coke for money, make the ability to form it into Crack for use in getaways. Make it consumable, but only sellable to other players.

### ISSUE THREAD

**Issue by Serpentamer** [InZidiuZ/op-framework-issue-tracker#172]
**Name:**
Who is suggesting this? Please include discord name.
James Dean#3814
**Summary:**
Write a short summary of what your suggestion is about.
 Instead of only using coke for money, make the ability to form it into Crack for use in getaways. Make it consumable, but only sellable to other players. You could make it so you have to get a recipe from someone. Would just add to the RP and make it less of a money farm and more of a resource.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would add content, and would also give more things to RP, finding out the recipe and how/where to cook. Would make it about more then just money, you can use it as a resource. It could make your stress meter go up and fog your vision, dehydrate you extremely fast, and other things like this.

**Comment by SteezyRen** [comment]
I like the idea. Would have to wait until stress is incorporated into the game otherwise there is no penalty for just popping crack for convenience.

**Comment by jaymssmith** [comment]
its a very good idea but i dont think it should be used for a getaway like in No*... we could make it unique and make it an extensive stress reliever so it maintains it importance in criminal activity and add something like an adrenaline shot to create variety... i suggested that earlier you can check it

**Comment by SteezyRen** [comment]
This can be closed with the release of most recent patch.
