### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by cammyyeet** [InZidiuZ/op-framework-issue-tracker#1720]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yeah

**Player Identification:**
What is your steam profile?
ArtificialKing

**Summary:**
Write a short summary of what you are experiencing.
Spoilers don't show their preview in the customs shops.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Goto a customs shop and attempt to preview a spoiler, it doesn't show.

**Expected Results:**
What are the expected results?
It should show a preview of the spoiler.

**Actual Results:**
What are the actual results?
It doesn't show a preview.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
All

**Notes:**
For anything else noteworthy.
This is an issue for everyone.

**Comment by InZidiuZ** [comment]
This is intended behavior as previewing spoilers repairs the vehicle.
