### ISSUE TITLE
Adjustment, bug or vehicle adjustments to semi truck and slamvan.

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/op-framework-issue-tracker#1721]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile?
KrigTroff #8469
**Summary:**
Write a short summary of what you are experiencing.

Summary:
I have been doing the trucking job ever since I join this server, I have noticed that regardless of what amount of fuel in the truck, when you get it repaired it goes back to about 64% every time. Even if you have a fuel tank or on empty, also the semi trucks from the job are way slower then local semis by almost 50+ mph, top speed I got my truck to is about 120, but local semis I can get to 160+ on the same route from vine wood toward sandy or grapeseed. Also in the custom shops when trying to add neon lights to the truck it takes you under the world and can’t see anything, then when you come back or exit out in that view the truck becomes scuffed and you can get back in the truck and it’s stuck.
Also the slamvan has a braking issue, it basically does not brake at all regardless of what level of upgrade brake you put on it. Can the brakes be adjusted at all. 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
For the semi truck, buy one from the trucking job and drive it around the city, then go steal a local semi truck and watch the speed difference. For the fuel issue it seems to happen to all vehicles getting repaired fuel it up before repairing and watch the fuel gauge drop. For the slam van, buy a new one from pdm drive and see how long it takes to slowdown, then go to customs out on brake upgrades and see it it take the same to slow it down.
**Expected Results:**
What are the expected results?
For the semi adjusting speed to match other trucks, for the slamvan being able to brake better inside of stopping a mile down the road. For the fuel issue, not wasting money on fuel to watch it go away cause the repair emptied or filled the tank.
**Actual Results:**
What are the actual results? Not sure what to put here. But would like speed adjusted to brought semi trucks, and slamvan brake adjusted to stop the vehicle.
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
NA legacy
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Read the README file. Only one issue per bug/suggestion. For the vehicle handling adjustments, use [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) issue tracker. For the fuel resetting, please create a new issue with some more info such as screenshots from the F8 console and if possible, a video of the issue occurring.
