### ISSUE TITLE
Storage Lockers at Garbage

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1722]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository? Yes

Summary:
Would like to request some storage lockers at Garbage HQ.

Reason:
This would help curtail some of the robberies that are happening in the area.  People come to work and run 10+ runs in a shift, with no place to store items they may find on their routes.  A bank of lockers on the receiving dock (to the left of the steps where employees spawn trucks) would allow workers to store their items after every trip, making robberies not worth the risk (over time).

**Comment by InZidiuZ** [comment]
This will not be added at this time.
