### ISSUE TITLE
Water Cooler at Garbage HQ

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1723]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository? Yes

Summary:
Would like to request a water cooler at Garbage HQ

Reason:
in combination with the locker request, this would make a great addition for the security staff that are employed by the Management Company. Having a little water would be awesome as there isn't a store exceptionally close, and would serve a large number of employees, both of the Management company, as well as the Garbage guys themselves.

**Comment by InZidiuZ** [comment]
Please redirect this to the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker).
