### ISSUE TITLE
Remove Propane Tank in Garbage HQ Parkling Lot

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1724]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Would like to ask the massive propane tank be removed.  

**Reason:**
It has been getting shot or crashed into multiple times a day, and is causing all the cars parked to explode.  With the high volume of trash trucks waiting to empty, if they get exploded, it then causes the chain reaction to spread to the alley, effectively halting all trash until tow drivers can be located.  I spoke to the Governor, Teddy, and he agreed it would be a good idea...

**Comment by XwezioGH** [comment]
Thank you for your suggestion.

Although this should of been put in https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

I will have this done by tomorrow.

**Xwezio
Asset Team**

**Comment by riedling11** [comment]
I sincerely apologize, was just in the wrong tab :/.  Let me know if you want me to delete, and recreate.

**Comment by XwezioGH** [comment]
This has now been added

@InZidiuZ could you close this please.

**Xwezio
Asset Team**

**Comment by riedling11** [comment]
@XwezioGH I wanted the tank removed, not added :)  Can we get it removed permanently?

**Comment by jethiya** [comment]
It has been removed. Go through the latest commit.

**Comment by ultrahacx** [comment]
@riedling11 He meant the fetaure has been added i.e. tank has been removed.

**Comment by riedling11** [comment]
I understand, I'm standing looking at it atm ;)

**Comment by ultrahacx** [comment]
It will be updated after the next global update most probably. Changes made are not instant to the live servers.

**Comment by riedling11** [comment]
understood, thought it would be a small change at the daily reboot, ill keep an eye out
