### ISSUE TITLE
[game/hospitalization] Remove medical fees for animals

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/op-framework-issue-tracker#1725]
**Assurance:**
Yes

**Summary:**
Remove medical fees from Animal characters

**Reason:**
The animals of our city play a crucial role of adding more life to the city as well as bringing out more interactions for players in the city. Unfortunately they get injured easily and frequently and can easily go into debt. I think it would be one less thing for those players to worry about so they can focus on being the animals they are.

**Comment by twooot** [comment]
Get your owner to pay for them? Theoretically you'd still be charged by the vet
