### ISSUE TITLE
[jobs/ems] EMS Vehicle Retrieval in Sandy Shores and Paleto bay

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1727]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Looking to see if we can get all the vehicles that are currently at the pillbox in the city to be available at Sandy Shores and Paleto.

**Reason:**
Why would your suggestion be a good change to the framework?
I believe this would be a good change due to the current ambulances that we are able to get from Sandy Shores and Paleto will bug out and eventually disappear.

**Comment by InZidiuZ** [comment]
I just checked & the same vehicles are in all of the 3 hospitals.

**Comment by superiorchicken007** [comment]
![pillbox](https://user-images.githubusercontent.com/81419197/113571371-46552780-95e4-11eb-82a0-74adcd4b1832.png)
![paleto](https://user-images.githubusercontent.com/81419197/113571372-46edbe00-95e4-11eb-92f6-896d386706cd.png)
![Sandy](https://user-images.githubusercontent.com/81419197/113571376-47865480-95e4-11eb-804d-e28dc0c9db5e.png)
I understand that.  Those 3 ambulances bug out and disappear on their own.  I was looking to see if we can get all of the vehicle options at those 2 locations.  I attached screen shots of what we can get at the Pillbox compared to the other ones.  The F450 ambulance does not bug out like the other ones.

**Comment by InZidiuZ** [comment]
Ohh, I forgot about the add-on vehicles. I don't have those enabled on my local server. I've added them now, though.
