### ISSUE TITLE
A new car

### ISSUE THREAD

**Issue by RajvirSinghMajotra** [InZidiuZ/op-framework-issue-tracker#1728]
**Assurance:**
Yes

**Summary:**
A new car for legacy RP 

**Reason:**
There is a DLC car in GTA 5 online that looks similar to Mitsubishi Eclipse used by paul walker in 'Fast and Furious'. Its name is Maibatsu Penumbra FF. If u add this car to Legacy servers, it would be great. Some people modify Anis Elegy Retro custom as paul walker's skyline and some Modify Dinka Jester classic as Paul walker's Supra. If u add that car also, it would be great as we will be able to make Paul walker's Eclipse also. The link for the car's photo is below. 
https://www.google.com/search?q=Maibatsu+Penumbra+FF&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjki57eqeTvAhVOwzgGHTQGACsQ_AUoAXoECAEQAw&biw=1920&bih=1007

**Comment by joevapes3** [comment]
If it's Paul Walkers Eclipse that your interested in, keep an eye out for the exclusive shop, as there is already an actual Eclipse that is already in the vehicle packs, and will eventually make it into the exclusive dealership rotation. With that said, this model may possibly be considered in the future, but currently no new vehicle packs are being added at this moment. I appreciate the suggestion and will keep this in mind.

**Comment by InZidiuZ** [comment]
If you're suggesting an add-on vehicle, you'd have to use [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) issue tracker. If it's a vehicle from the latest GTA version(s), then it'll be added once we switch over to a later build.
