### ISSUE TITLE
[game/handcuffs] Minigame to uncuff yourself 

### ISSUE THREAD

**Issue by shadowcls** [InZidiuZ/op-framework-issue-tracker#1730]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion would be to add a way to uncuff yourself, no matter what type of cuff it is with a medium or more complex difficulty minigame/looong progress bar. Or if you have already an item in your inventory like so pliers or bolt cutters to actually be able to do it on your own with a higher chance of success. 

**Reason:**
Why would your suggestion be a good change to the framework?
I would think it will be good because you actually have a chance of escaping different scenarios in which you might not have control. Already have experience with this, been cuffed and left in the middle of nowhere with no other chance than to just walk across the map.

**Comment by claymstehling** [comment]
Any update on this :D

**Comment by panpawn** [comment]
The time to break out of cuffs should only be when someone is first cuffing you, if you fail you fail. You should also only be able to break out of cuffs so many times (3? 4?) before it stops giving you the option.

Other than that, I support this.
