### ISSUE TITLE
[jobs/trucking] Suggestion adding rewards or items to trucking missions

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/op-framework-issue-tracker#1731]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?yes

Name:
Who is suggesting this? KrigTroff#8460

Summary:
Looking over the life invader jobs and different things. Garbage job is the best for new players or just getting started because they can make quick cash and have random chances at getting items.(gold bars, zombie pills, etc...) which makes a lot of people pick that to make money and stay with it forever till they can get into more things. Where semi trucking get you only a small cash amount depends if on the run. We do not get any random items or anything special. A thought would be to add something to trucking to give other professions a chance to compete or spread the role play to other areas of the island. Making trucking bring something to the game that gangs or people would want. Stuff can always fall off the trucks. ( drugs, guns, jewels, parts for cars, etc). Or if not adding anything maybe increase the reward for trips. I have been trucking since I joined the legacy NA server cause it works for the background and RP I am doing. But so many people try it for a day or two till they find out what they can make from garbage. Currently I mean one zombie pill sells for about 2k. That is 4 -6 trips for truckers to go from all the way north to all the way south if lucky to get a load.

Just had another thought for the gangs , shops or government to add something to the server and role play. Maybe once a week or every few days. Have a special truck load to deliver to some group or store. That could pay out a good amount to the trucker and be stole by someone. Having the truck get hijacked. Some many people use small cars or cargo vans to move and store everything. Why not bring in truck loads of stuff for delivery. Ie guns, ammo, car parts, drugs... truckers could deliver these to different store or groups around the area.

Link:
I do not have any links, but just adding something that is already in the game or adding something new to only semi trucking to make it worth having us around.

Reason:
Why would your suggestion be a good addition to Legacy?
It would spread the new players or people out across the land. Semi trucking takes you all over the island. It would cut down on all the garbage trucks and give another profession something unique to the role play and island.

**Comment by AverageStatistic** [comment]
I'd love just for the trucking job to get a boost in pay overall. Very low paying considering the risks with the job, having to own your own truck, do repairs on it (a lot more frequent than garbage, if waste drivers ever have to repair their vehicles.). I'll give an example of how trucking is not that great; You take a job from the Jamestown Cargo station, drive it to a drop off on Route 68 near the training facility, and get paid $350. Then, you get screwed over by their possibly not being a load to take from there to somewhere else, and go on a drastic mission to try and find a trailer to drop somewhere else. Basically making $350, in DOUBLE the amount of time it takes to probably do 2 garbage runs for the more efficient waste management workers.

**Comment by rajbastakoti** [comment]
the job of trucking id far more left out as compared to the jobs like burger and garbage , for trucking people need to by truck repair it and make a lot of effort driving ,also salary is just 16 $ , the item idea is also good , also the payment needs to be increased  a lot (double maybe )  for truck delivery / misson

**Comment by twooot** [comment]
All jobs now have item rewards
