### ISSUE TITLE
[game/items] Balancing IFAKs and Oxy

### ISSUE THREAD

**Issue by sahara87** [InZidiuZ/op-framework-issue-tracker#1732]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Balancing to IFAKs and Oxy, increase in Oxy drop rate.

**Reason:**
Without a doubt, IFAKs are seen as oxy for the PD but are not comparable in the current state of the framework. The IFAK currently costs $200 each (w/o tax), weighs (5.00), and has a total animation time of 20 seconds, compared to oxy costing $150 each (street value), weighing (2.00), and having a total animation time of 2-3 seconds. The use of IFAKs is to stop bleeding, whereas the use of oxy is to stop all injuries apart from the head injury and stop bleeding. That being said, I think it is fair to say that they are quite unbalanced, oxy being the much better healing item. 

To balance both items I am suggesting the following changes: 
The IFAK's price is increased to $500 each (w/o tax) and the weight remains at (5.00), this is to counter players buying and carrying an insane amount of IFAKs at once. The animation time is reduced to 2-3 seconds and the use is changed to fix all injuries apart from the head injury.

I believe this balancing will bring a positive change to the server and the economy, making the IFAK item a lot more viable considering little to none of the PD actually use them.

----------------------------------------------------------------------------------------------------------------------------------------------

Following the changes listed above, I have done some research regarding the drop rate of oxy bottles. After completing 10 oxy runs in a fully upgraded and repaired Nissan GTR R35, I found that the average bottles per run is 1.8, the average profit per run is $1,905, and the average time to complete the run is 20 minutes and 25 seconds. 
(results - https://gyazo.com/4eacfc9a61413207e26358a61c2c82a0)

Currently, there is quite a limited supply of oxy bottles in the server. That being said, I believe an increase in the drop rate would lead to less grinding and more roleplay when it comes to distribution. Oxy bottles are not something you can sell to locals meaning the only way this change would affect the money economy is the price that it is distributed at. In my opinion, the average drop rate should be increased to 3 bottles per run meaning the street value price would drop to $100 for example. This would bring more interactions when it comes to sales because the distributors will be able to gain more bottles in a shorter amount of time.

**Comment by twooot** [comment]
IFAK is now the same as oxy
