### ISSUE TITLE
Weapon Attachments

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1733]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is to consider weapon attachments becoming a thing, with some guns it could very cool to see like extended magazines for like the AP pistol, Tec-9s and Uzi. Where as the bigger two-handed guns would be cool to see like scopes and things to use with these guns. I do not know the difficulty of this suggestion considering how the inventory works.

**Reason:**
Why would your suggestion be a good change to the framework?
Could be a useful addition to better gun fights on all sides of it since some guns will benefit from extended mags and some will benefit from the scopes to shoot longer ranges. Even including possibly suppresors since these would let people do things more stealthy.

**Comment by InZidiuZ** [comment]
Closing as it's already suggested in #1580.
