### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PsychoGrandpa** [InZidiuZ/op-framework-issue-tracker#1734]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adding a weazel news helicopter and other vehicles related to it. 

**Reason:**
Why would your suggestion be a good change to the framework?
Would help a news reporter to include footage of a fight or a chase in their news reports.

**Comment by InZidiuZ** [comment]
There is no weazel news helicopter in the game, so you'd have to suggest something like that to be added in the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
