### ISSUE TITLE
[game/doors] sound bug while opening/closing doors

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1736]
**Summary:**
In sum, in new prison interior there is major issue ongoing with door locks.
Namely, while closing doors there happens for doors to have bugged **ongoing constant** sound of moving doors even when they are perfectly still. Only way to get rid of it is /noclip an major distance away and come back.

**Steps to Reproduce:**
Step first, open door
Step two, make a few steps back and while doors are about to be closed approach them and click "e"
Step three, doors unnaturally closes instantly without animation (can be seen on video)

**Expected Results:**
Doors sound should not be bugged, it makes people from DOC (deprtament of corrections) goes crazy as we have very active group of people (20 people in total) who plays only jail rp and are in interior most of time.

**Actual Results:**
Very often people unintentional bugs doors as showed in video below and bug sound which will never go away untill server restart or /noclip away

**Screenshots:**
https://www.youtube.com/watch?v=ALp43Oi4Mos
(sorry about speaking polish, will be translated later on)
0:08 first time bugged
0:40 second time
1:15 third time

**Suggestion**
At other servers in Poland people avoided this issue with changing the type doors in assets, changed to these at mission row 
cells for instance.
This is perhaps most solid option to resolve issue for good as these doors just do not make sound while opening.

**Server:**
EU/NA Polish subdivision (but I guess this happens in every subdivision)

EDIT:
under following link there is map edited by us
https://megawrzuta.pl/download/4b9f3729c09b5dcc153e2ae50431172f.html
we basically changed doors to the ones that do not make problems at all, few changes has been made as well with fences, added few changes that disallows prisoners to run away on roofs. 
Door name that we replaced is v_ilev_ph_cellgate

**Comment by gighul** [comment]
This is actually pretty urgent as its annoying issue. May discourage people to play at prison. Please kindly have a look at mentioned suggestion.

**Comment by gighul** [comment]
bump

**Comment by gighul** [comment]
bump

**Comment by 7d4ys** [comment]
bump

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
