### ISSUE TITLE
[jobs/dealership] Suggestion Adding On-duty / Off- Duty Option For PDM

### ISSUE THREAD

**Issue by Jeetez** [InZidiuZ/op-framework-issue-tracker#1737]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adding a On-duty/off-duty Option for PDM which would have the same timestamps system as EMS and Law-enforcement.

**Reason:**
Why would your suggestion be a good change to the framework?
-Adding a On-duty/off-duty option for the PDM would have a proper Timestamps For The PDM management to Overwatch The PDM Employees.
- Would Show which Player went On/off-duty just as SASP & EMS.
-While The PDM employees are Off duty They Wont be able to take Out any Cars for showcasing In any slots.Which would Keep a Proper management Of PDM.
- Clusters which have more than 1 servers Will have a Proper Logs For the Players who have PDM Role in-game as Taking out 1 vehicle in any of the server which will lead to Spawning the same vehicle in other servers( Talking about clusters have more than 1 servers).
-Adding this, Wouldn't Lead to the Misuse of Players having PDM Powers of Taking out a vehicle in any server Which leads to the same vehicle Being spawned In other server within the same slot

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
