### ISSUE TITLE
[base/admin] Bringing back the /sv for staff

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1738]
**Assurance:**
Yes ma'am.

**Summary:**
Bringing back the ability for staff (or staff level+) to have access to /sv, mainly for the growing Los Santos Aviation.

**Reason:**
During Ori's (Governor Vedder's) reign, we had the ability to spawn in certain aircraft/special aircrafts to those who provided and went through some roleplay in obtaining their aviation license through now a standing company, Los Santos Aviation.

One thing I felt was appropriate during this period, was individuals who would require a certain aircraft (from my experience) would do something like "/report Pilot B-12 request <model name> at Hanger 2 at Los Santos Airport". Then, certain staff would then allow that individual to obtain that aircraft correctly. If this was abused, we simply just "/dv yes" or "/impound" the aircraft.

What I am suggesting is bringing this ability back **or** giving a certain ability to Snr Mods+ or Admins+ to be able to do this and spawn them in for those, who request it correctly and can provide proof of "having a pilot's license".

**Comment by Spitfire2k6** [comment]
This would be very much appreciated by the LSA community

**Comment by Spitfire2k6** [comment]
@InZidiuZ This can be closed as it's now redundant with the airport spawners.
