### ISSUE TITLE
[game/items] Camera Item / Zoom Feature On /e camera

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1739]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Adding a camera item or a zoom feature to the /e camera command so that we can have an item that can take photos that isn't our phones/has a better range compared to phones.

**Reason:**
Why would your suggestion be a good change to the framework?
I think it would be a good addition due to the fact that many people enjoy taking photos and it would be more realistic to take photos with a camera instead of a phone. It would also mean that people can take photos from further way than phones and have the ability to take photos without it being powerful (example: binoculars).

**Comment by DaxterPancake** [comment]
An alternate idea to add on to this is to have a PD Camera (when used it can see evidence on ground) and a regular camera (which doesn't see evidence on ground).

**Comment by Deggan8** [comment]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Correct 

**Summary:**
This GitHub is for a very much needed item for the PD to use for Evidence gathering and Roleplay

Currently they have Torches which will show Evidence however taking a screenshot and using this can be a bit more complicated. 

Having access to a Camera which will act like a video camera (Already available for news) which will show you in first person but have a overlay showing [Street name] - [Date&Time] for evidence reasons. While in this view it will show all the evidence within the area. 

The Camera would need to be able to:

Zoom in/out
Show Evidence within the local area (Like the torch can)
Have an overlay to look professional.
When used it could have an emote of /e Camera to show that you're taking photos. 

Personally I don't think it would need to be PD only as this could open up Private Investigators and be an item we could use 

This way they can use third party applications to take a screenshot such as Gyazo. 


**Reason:**
Why would your suggestion be a good change to the framework?

This would help Roleplay a huge amount. Evidence Gathering is crucial for PD and a healthy DOJ system. This will make it smoother and would break immersion when PD have to resort to telephones to record/zoom.

**Comment by Spitfire2k6** [comment]
A camera item as described by Dreggan above is the preferable solution in my opinion. I don't like the idea of an emote allowing you to zoom. Having an actual item is much preferable.

**Comment by Nuziatella** [comment]
This has been completed.
