### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by twelvyy** [InZidiuZ/op-framework-issue-tracker#174]
**Name:**
Who is suggesting this? Please include discord name.
@twelvyy#0666
**Summary:**
Write a short summary of what your suggestion is about.
Utilizing Lester's home interior as a place to hack cameras for heists. 
**Reason:**
Why would your suggestion be a good addition to Legacy?
The interior of Lester's home includes multiple PC's, and monitors that Lester uses for hacking in the story mode, would be an awesome roleplay opportunity to utilize that setup. 
![maxresdefault](https://user-images.githubusercontent.com/52603762/60757612-8718aa80-9fd2-11e9-8887-c42ecf3c2df0.jpg)

**Comment by InZidiuZ** [comment]
Hey,

When we get cameras, possibly, but until then I'm closing this.

**InZidiuZ**
*OP-FW Developer*
