### ISSUE TITLE
[jobs/paintball] Making Paintball Arena a business

### ISSUE THREAD

**Issue by Deggan8** [InZidiuZ/op-framework-issue-tracker#1740]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
What this Github would be for is to have the Paintball arena set up with features similar to most other businesses within the city. 

- Putting Locks on the door so that someone can roleplay into owning the business.
- Adding a "locker" or storage space only employees can access, This could help with storage for "replica/paintball" guns 
- optional (Maybe adding a store which would have access to discounted Bullets) This would allow us to provide these to the customers and feel more realistic when going to paintball that you would purchase packs from the retailer. - **The price could match the price that PD pay for their ammunition in order to help promote roleplay benefits** 
- Providing Paintball Printed guns or even a paintball gun itself (https://www.gta5-mods.com/weapons/paintball-gun) which could be provided to the owner by PD in shipment orders. 
- As you designed the paintball Map maybe having a / command that would allow the owner to change the paintball Map in the future if you design more arenas. This will give variety in the games too. 

EDIT:
With the Jobs you could allow: 
Owner
2x Manager
Unlimited Receptionists

The managers would allow for a day and night shift manager and they will be able to manage the receptionists. 
They would all have access to the storage/lockers where we could store the paintball guns
All employees would also have access to the Store (If put in place) in order to purchase bullets to sell to the clients. 

**Reason:**
With some of these changes it could provide more roleplay to the city. It would allow some civilians to boost their own RP by owning a business. 
It would provide a great escape from Gang wars or PDvsCrim where they can enjoy some fun games for the city. 
With the guns being brought in this would create some roleplay with PD in order to validate and check these guns.
I have seen your design and worked on a company in my server to help boost this system you have already put into the city. With some of these changes  it could bring more RP to the city and bring different aspects of roleplay within the city.

**Comment by Deggan8** [comment]
optional (Maybe adding a store which would have access to discounted Bullets) This would allow us to provide these to the customers and feel more realistic when going to paintball that you would purchase packs from the retailer.

This would also be a benefit for players as a reward for Roleplaying by getting discounted bullets than going to an NPC in order to purchase these. 

Rewarding plays for roleplay is the best way forward 

In the future if you ever done a crafting system this could also help with this as I could craft rubber into rubber bullets or replica bullets for this. Promoting even more roleplay for the buying and selling of materials.

**Comment by Spitfire2k6** [comment]
This is a weird case. I don't think we should be adding any changes to paintball unless it's separated from live weapons.
I don't see how someone owning the paintball arena would create more RP other than a way for said owner to make money for doing next to nothing.
When you start a round of paintball you should spawn with a "paintball gun" and no access to your inventory.

**Comment by Deggan8** [comment]
Well this is RP, Having business's helps boost RP in the city. It's not all about making money however having this as a business would allow you to expand and give back to the city. Having an empty shell where people just go shoot each other, this is lack of RP and more FPS. Having this set up as a business promotes multiple RP scenarios.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
