### ISSUE TITLE
remodel interior of Mirror Park Tavern and add workstations

### ISSUE THREAD

**Issue by nikkoendres** [InZidiuZ/op-framework-issue-tracker#1741]
**Assurance:**
yes

**Summary:**
All it would take would cleaning up the blood stains and removing the posters on the walls and adding a workstation for bartenders. I'm not asking for a entire remodel just the interior be cleaned up the way an actual business would look.

**Reason:**
I am currently the owner of the Mirror Park Tavern and with it now being recognized by the state as a business that can be owned the inside is super dirty and cluttered. If it was an actual business that was just recently recognized as a bar it would be cleaned up and a workstation added accordingly for events.

**Comment by InZidiuZ** [comment]
This issue tracker is for framework development only. Please use [this](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) issue tracker for assets-related issues.
