### ISSUE TITLE
[game/companies] Real estate RP enhancement

### ISSUE THREAD

**Issue by scarlexknigght** [InZidiuZ/op-framework-issue-tracker#1742]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? **Yes**
 
**Summary:**
This is in regards to Real Estate RP where they should get the option to revoke access to houses and also be able to transfer ownership of the houses. It would also be amazing if the employees of the company should have access to the information of the properties on their tablets (/companies) but not be able to manage properties and the only owner is able to do that though and after removing the access of the tenants, they will get 1 week's time or how much ever the real estate agents give time according to their RP with the tenants (overdue) to remove their belongings or other agendas before the house access is gone completely to prevent misuse of the power from the real estate agents side.

**Reason:**
There are a lot of people who want to remove their access or transfer ownership of the house because sometimes the owner of the house gets banned from the server so the tenants living with that person are not able to pay and loses everything until the house is gone and have to be purchased again and also if their house was furnished then the all the hard work goes to waste as well or else when the tenants have paid 2 months advance rent and in between they realize they don't want it anymore or want to shift houses so they want their access removed along with their money being refunded back to them or not according to what the companies policies be.

**Comment by MrHitmanDrHitman** [comment]
I totally agree with the idea, I have faced all these issues mentioned above and it really ruins gaming experience.

**Comment by MitHasan** [comment]
totally agree with this idea

**Comment by rajatborde** [comment]
agreed

**Comment by iGreatWhite** [comment]
Utilize the reaction system within github on the original post if you have none other to say than agreed. it keeps the comments clear for feedback to be brought up.

**Comment by beasthemant1** [comment]
It's a great suggestion, I would also like to add if we company employees or the owner can see if the tenants have paid the rent in advance or not and their due date since most people pay rent in advance and for people managing the companies should be able to retrieve such information.

**Comment by DebeliFetus** [comment]
I would also add if we could get employs that can actually sell houses and apartments

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
