### ISSUE TITLE
[jobs/trucking] Addition of job items in inventory

### ISSUE THREAD

**Issue by itshazelsaurus** [InZidiuZ/op-framework-issue-tracker#1743]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
So, currently, trucking is basically point to point. The idea that I have is connect the job list to a piece of paper that acts like an id. This would help with the cops pulling over the truckers and showing the load to bring more RP.  There would be a chance to forge documents and etc with a forgery office etc. 

**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good addition to the trucking so that cops can go off the load etc. It would be a good addition for other good RP

**Comment by DaxterPancake** [comment]
I like the idea of this, I feel like this would connect well with the transporting of illegal goods if that was to be added to trucking. It could work sort of like the ID, where once they accept a route to take, a piece of paper is added to their inventory that, when used, shows a delivery docket to those around you. The police could then see what is being transported and where it is going to. If illegal goods was added to the trucking job, they would NOT get a delivery docket and would have to try and explain to officers why they didn't have one.

**Comment by nikkoendres** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
