### ISSUE TITLE
Enhancement of Racing feature 

### ISSUE THREAD

**Issue by gautamkhanduja** [InZidiuZ/op-framework-issue-tracker#1744]
It would be great if you could change the current system of racing in legacy.
The current race feature only allows us to keep 1 lap of race as after it the race ends.Also it is possible to go offroad and take a shortcut to win the race which defeats the whole purpose of race.
So I suggest the following changes

It would help more in rp if race is not based on going from starting to end point but also going through checkpoints in between.Doing so will remove the taking of shortcuts while racing and 2 or more laps can also be added on the same racing track.

Thank you

**Comment by DaxterPancake** [comment]
Please follow the correct format [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).
