### ISSUE TITLE
[external/wk_was2x] Wraith ARS to be also used by the Co-driver 

### ISSUE THREAD

**Issue by Jeetez** [InZidiuZ/op-framework-issue-tracker#1745]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**

It's regarding the Wraith ARS system in the PD cars Which should Also be able to used by the co driver sitting in the car.

**Reason:**
Why would your suggestion be a good change to the framework?

-This would Increase the Rp between the PD officers one who would be driving and the other one who would look after the Wraith System. 

The system can be seen by 2 People rather the one one driving so it's useful.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
