### ISSUE TITLE
New Racing system

### ISSUE THREAD

**Issue by gautamkhanduja** [InZidiuZ/op-framework-issue-tracker#1746]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
There should be a new racing system which will include going throught the checkpoints in between and not only from one point to another plus multiple laps could be done on a race track

**Reason:**
This will enhance the rp of roleplayers interested in racing with longer races due to multiple laps and without any cheating since no one can skip a checkpoint.Because currently one can easily go offroading and win a race by cheating which defeats the purpose of the race.

**Comment by ultrahacx** [comment]
Please look into existing suggestions before opening a new one. There's already an open racing suggestion which you can find [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/840).

I would suggest closing this issue and following up on the pre-existing issue to keep the suggestions clean and non-repetative.
