### ISSUE TITLE
Elegy Retro Custom Rework/Rebalance

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#1747]
**Assurance:**
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

**Summary:**
Hello, I'm posting here as I would like to make a suggestion that the Elegy Retro Custom should be given another look in terms of its performance in Legacy RP. As someone from the race scene in character, I race with many cars and have test driven many in the tracks and there is simply one car that stands out amongst all others in terms of its performance, being the Elegy Retro. This car in my opinion and the opinion of others in the scene is that it carries way too many strengths and very little weakness in comparison to other cars in its class. The handling is very forgiving, too forgiving in fact, with the car having immensely good brakes (at stock by the way) and it can carry itself through corners at high speeds where a lot of other cars cannot. It's AWD drive-train means it has fantastic launch compared to other cars, backed up with good acceleration and an insanely competitive top speed. The car also seems to have an issue where it reaches speeds that it isn't usually meant to reach. From what me and others have noticed, it seems to occur after the car has been damaged slightly, as after some damage is manages to reach speeds of almost 210 mp/h. The car has very good grip, meaning that coupled with everything else mentioned, the car outclasses many cars that are even double or triple its price point. The only weakness to the car I can think of is that its handling takes a hit in offroad scenarios, however I don't see that as a good enough issue for what is a car made for normal asphalt based racing.

**Reason:**
I believe that another look at this car would be not only beneficial to the race scene within RP but also would make for a lot more interesting driving with the car for the owner. The car in its current state simply outclasses most vehicles that it comes across in a big way which in the end promotes less diversity as its simply not worth having a car that is clearly under-performing compared to the Elegy Retro. I feel that some testing should be done on this car so that it can be better evaluated what needs to be changed to bring it more in line with other vehicles. For the integrity of diversity in the race scene of Legacy, I think this should be looked at.

**Comment by InZidiuZ** [comment]
Please redirect this issue to the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
