### ISSUE TITLE
[game/items] Weazel News Police Scanner Suggestion

### ISSUE THREAD

**Issue by WeazelMicky** [InZidiuZ/op-framework-issue-tracker#1750]
**Assurance:**
Yes

**Summary:**
911 calls to be broadcasted to News Journalists as they are to law enforcement.

**Reason:**
If registered Journalists or even select (Real) Journalists could have access to a police scanner or receive 911 call alerts, this would make for a better RP. The current system has Journalists just chasing around cops to get footage to report the news. This isn't really feasible due to how quick the police cars are, and the journalists only get the starting or, if they are lucky, the end of a robbery. Having 911 calls go to journalists would give them the ability to search the area that home robbery's, shootings, etc., are taking place in and capture footage to either report in the news and sell the footage to the police or even other criminals. The RP possibilities would be endless.

**Comment by WeazelMicky** [comment]
Bump. Plz

**Comment by InZidiuZ** [comment]
This has since been done.
