### ISSUE TITLE
[vehicles/garages] Personal home garage is inaccessible with certain vehicles

### ISSUE THREAD

**Issue by PaulPetersonG** [InZidiuZ/op-framework-issue-tracker#1751]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/id/xfL/

**Discord**
x.#6339

**Summary:**
The vehicle storing location is way to far from the street. Wall and staircase block access.

**Steps to Reproduce:**
Try to store a vehicle without climbing the stairs.

**Expected Results:**
Vehicle should be stored.

**Actual Results:**
Vehicle can not be stored.

## Additional Information
Proposing moving the garage slot closer to the street. Possibly at the bottom of the stairs at the street.

**Screenshots:**
https://imgur.com/a/5Lbk97j

**Game Resolution:**
1920x1080

**Player Data:**
https://imgur.com/b9q9YaI

**Server:**
Legacy RP #1

**Notes:**
I recently got a roommate in character and he can not get one of his vehicles up the stairs to store it. Also his other vehicle gets scratched every time he goes up and needs repairs after storing. It's also pretty hard to RP climbing stairs to store a vehicle in a garage. Login screen address is Amarillo Vista 2

**Comment by InZidiuZ** [comment]
The garage has now been moved down to the road.
