### ISSUE TITLE
[game/scoreboard] Display people in vicinity in ID list 

### ISSUE THREAD

**Issue by Supbro112** [InZidiuZ/op-framework-issue-tracker#1752]
I was thinking of maybe adding a secondary display menu when hitting the U key to display IDs. So instead of having to scroll to ID 312 when you want to report someone, there should be a  secondary window that shows the STEAM IDs of those in the vicinity of you. Not sure how big it should be but it would make it much easier to report people. I am putting this suggestion in because recently I had a problem with being RDMd and when trying to get the STEAM ID they left quicker than I scroll to their ID. 

Basically, instead of making people scroll through a long list of IDs, it will also display those in the vicinity of the character in a secondary list so it will be easier to determine their ID before they leave the game.

EDIT: Another idea would be to display the ones in your vicinity at the top of the main list and then after all the ones in the vicinity are shown, it starts the regular list below them,

Idea below:

![TEMPLATE](https://user-images.githubusercontent.com/52581779/114644562-5aacba80-9c9d-11eb-8af4-cdee558ce9fe.png)

**Comment by Spitfire2k6** [comment]
I don't think this is needed. Staff don't need the steam ID, only the ServerID (paypal)

**Comment by DaxterPancake** [comment]
> I don't think this is needed. Staff don't need the steam ID, only the ServerID (paypal)

I'm going to disagree due to the fact that it gives both ServerID and SteamID in his mock up. Seeing ServerIDs in vicinity could be extremely helpful.

**Comment by iGreatWhite** [comment]
Also when making player reports. This would put all nearby IDs in one section for staff to have versus having to scroll through and find each ID in the list.

**Comment by twooot** [comment]
You don't need to get their steam id. You only need their server id (paypal) once they leave you have all the time in the world to scroll to their server id and if they exit the city there is a "Recent Disconnects" tab which would include their id
