### ISSUE TITLE
[base/admin] New command /spectate ID for staff

### ISSUE THREAD

**Issue by ainstaylor** [InZidiuZ/op-framework-issue-tracker#1753]
**Assurance:**
Yes sir

**Summary:**
Can staff have a command that is /spectate ID - sometimes when a report comes in about someone and you need to spectate them quickly it can be time consuming to find them on the player list, especially when server has 224 people on and the person is in the middle of the list.

**Reason:**
It would enable staff to deal with on-going situations quickly and more efficiently.

**Comment by Spitfire2k6** [comment]
Another option/addition to this would be having mouse control with scrolling enabled in the admin menu

**Comment by milan60** [comment]
The command seems to only work once you've looked at the player list in the /admin panel. If you try to spectate someone that wasn't on the list last time you looked at it, it won’t work until you look at it again.

**Comment by DaxterPancake** [comment]
The script is depriciated. You don't have to look at the player list, you just need to do /admin and close it. Once you have done that you can spectate anyone in the city.

**Comment by DaxterPancake** [comment]
Since this has since been added, I will be closing this.

Cheers,
Daxter.
Project Manager.
