### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#1754]
**Assurance:** Yes
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:** In game MDT
Write a summary of what your suggestion is about.

**Reason:** 
Why would your suggestion be a good change to the framework?

I believe this would enhance in game RP and would allow us to not have to deal with outside game assets and would allow us to keep more stuff in game rather than relying on discord
Why would your suggestion be a good addition to Legacy?
I feel it would be a huge upgrade for PD and would also allow us to track things much easier rather than using a google doc to track everything

**Comment by FossiiLs** [comment]
+1 A MDT is highly needed. PD has been relying on a 3rd party MDT that is no near effective as an in game would be.

**Comment by scarlexknigght** [comment]
+1, It can increase lawyer RP as well as they can get the information about the police reports in-game during the court case and can get access to the warrants and everything.

**Comment by rajbastakoti** [comment]
also , there are rp scenario where players say sth about a lost vehicle or sth , and we as a pd dont even have track of vehicles , criminal history and that kind of , and rp cant go foreward from that point , this makes me a sad cop

**Comment by InZidiuZ** [comment]
This has already been suggested in #1653.
