### ISSUE TITLE
[game/hospitalization] Stuck on never ending loading screen when you re-spawn "all beds are occupied"

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#1755]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561198185121513/

**Summary:**
So when you respawn it puts you on a never ending loading screen if the beds are occupied. It gave me a notification saying `All beds are occupied` and then hasn't stopped loading since.

**Steps to Reproduce:**
Make sure all beds are occupied, and then try respawning and it should be a never ending loading screen.

**Expected Results:**
To not be stuck on this infinite loading screen because it forces you to re-log.

**Actual Results:**
You get stuck in the loading screen.

## Additional Information

**Screenshots:**
https://gyazo.com/fceed85449cedd6fd8b6cc761480fdbf - been stuck here for a while now

**Game Resolution:**
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
Legacy Main EU/NA

**Notes:**

**Comment by InZidiuZ** [comment]
A temporary workaround for your issue has been pushed.
