### ISSUE TITLE
[?] Dogs jumping

### ISSUE THREAD

**Issue by Lunoticc** [InZidiuZ/op-framework-issue-tracker#1756]
**Assurance:**
yes

**Summary:**
i have been trying to jump to go to people to make for better rp

**Reason:**
For better rp

**Comment by DaxterPancake** [comment]
Press spacebar.

If this isn't what you were refering too, please remake this with more detail.

Thanks,
Daxter.
**Project Manager.**

**Comment by Lunoticc** [comment]
yes this is because for alot of rp us dogs can't do much i am wanting the ability to jump so we can get on cars if our owner asks and dog parks plus much more

**Comment by InZidiuZ** [comment]
I think this might be a limit of the game itself.

**Comment by Lunoticc** [comment]
hello anyone

**Comment by DaxterPancake** [comment]
You were given a reply. There are many things to do for the server that are more important than allowing animals to jump.
