### ISSUE TITLE
[game/items] Suggestion to add cream-cookie and coffee on server. 

### ISSUE THREAD

**Issue by Saszkaxd** [InZidiuZ/op-framework-issue-tracker#1757]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? - Yes

**Summary:**
Add cream-cookie and coffee on server as a food item, that can be bought in bean machine on vinewood. 
![kremowka](https://user-images.githubusercontent.com/80044399/115113055-a22a9380-9f88-11eb-8910-dffe84a16944.jpg)
**Reason:**
It will add a new type of food that can be sold in bean machine and it will add more functionality to this place.

**Comment by InZidiuZ** [comment]
This has now been added.
