### ISSUE TITLE
[vehicles/vehicles] Cars stealing upgrades.

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#1758]
**Assurance:**
Yes 

**Player Identification:**
Cruxer

**Summary:**
I think I figured out why some people are complaining about losing thier upgrades on their cars all the time lately. I'm not sure how or why but I will show you the steps that made it happen for me.

**Steps to Reproduce:**
Context: I was in the city a long time that day and therefore and taken out quite a few cars.

The cars we are looking at is one occurence but I had the same thing happen a second time on another date with different cars
This is the initial car color of the car that will lose/steal another car's upgrades.
![Screenshot_20210418-052154.png](https://user-images.githubusercontent.com/43392378/115140686-8bc31d00-a006-11eb-9f62-761547d98cdd.png)

Step 1 I customized this car that I had used previously and decided to change how it looked. And then store it and take it back out to make sure the car keeps it's upgrades
![Screenshot_20210418-051939.png](https://user-images.githubusercontent.com/43392378/115140702-a1384700-a006-11eb-9871-4b90cd2f3ef0.png)

Step 2 after driving it for a while I decide to switch back to the 1 st car shown without storing the other one. 
Clip showing what happened:

https://clips.twitch.tv/VainPrettyCheetahUncleNox-nbvcQq0TIq8RIihv

**Expected Results:**
Don't steal the other car's upgrades

**Actual Results:**
Steals the upgrades
## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
 CID 13

**Server:**
Main servers

**Comment by InZidiuZ** [comment]
It is already known why this happens, and it's been said before that it'll be fixed once certain systems are rewritten.
