### ISSUE TITLE
Holiday requests/ Apartment time bulk buys

### ISSUE THREAD

**Issue by TMearns1609** [InZidiuZ/op-framework-issue-tracker#176]
**Name:**
Discord : Mearnz#5346

**Summary:**
A holiday request form (eg a google form) that allows players to submit requests for time away from the server and not lose their apartments. The current apartment system would mean that a holiday of a week would mean you lose the apartment which is punishment that isn't deserved for an IRL break. My suggestion would be to enter the details of this break into a form, and if approved by staff, would allow the user the requested time off. They then must return to the server within 3 days of their end date to reclaim the apt. or have it be vacant like the current system. For extended holidays it could be at the discretion of the staff as to whether to allow the holiday/ need to see a form of proof as this could be used to block apt. for extended periods of time if abused.

**Reason:**
I'm away for 2 weeks soon and I would really appreciate my hard work of the weeks before my holiday not to be erased due to my holiday, the only current solution is to store it with a friend, but then I could be out of an apt. upon my return and it is trusting someone else to make their payments. Also, IRL holidays don't mean I lose my house. 😄

**Comment by SteezyRen** [comment]
I think the best way to do it would just have the option for people to rent out a motel for:

- 1 week
- 2 weeks (5% discount)
- 1 month  (10% discount)

This would be the simplest way to incorporate that idea without having to do forms, having someone assigned to review forms, etc.

1 month isn't game breaking in regards to availability in my opinion and if it becomes an issue then there are plenty of other hotels that can be added for rental.

**Comment by TMearns1609** [comment]
Even so if a month isn't *too* game breaking you could just bulk buy, without discounts (although I wouldn't mind more money in my pocket 😉 ). Obvious problem with a max of a month purchase is this screws people on a breaks longer than a month, but at that point is it really a holiday and are you still able to be considered active. Not to mention they would probably have more pressing issues at hand if they're away for that long and, so to come full circle, I agree that a month is an okay amount of time.

**Comment by InZidiuZ** [comment]
Hey,

The 1-week limit is in place to prevent people from stacking up a room, just to leave the server & not use the room again. We currently only have 150 rooms split to 7 motels, which isn't a particularly great amount. In the future though, we'll have apartments, houses, etc., so it won't be an issue.

I won't create any "holiday request" for now though, but I would recommend storing your items in personal vehicles if you're going away for a long time, or hit me up on discord & I'm sure I can change your expiry date to whenever you're back.

**InZidiuZ**
*OP-FW Developer*
