### ISSUE TITLE
[jobs/tattooartist] Put sentient people behind the needle.

### ISSUE THREAD

**Issue by Wolffest1991** [InZidiuZ/op-framework-issue-tracker#1760]
Here's my thought-baby:
Tattooing consists of simply standing in a circle and possibly getting your whole body blasted with ink within a matter of minutes. 
**INSTEAD** Have people tattoo people. Make it so some interaction needs to happen in order for you to have something put on your body permanently. Right now, if you make a mistake in the tattooing circle, its there FOREVER! Lets make it have a few more steps in the process. 
If tattooing was a job, it would create a few potentials for RP. In the event that tattooing does become a job, artists will need supplies: Steel, rubber and alcohol (vodka) for artists to craft sterile needles, ink and ink cups. This would give cause for divers and "cleaners" to stop at a tattoo shop to sell  items to artists like they would a mechanic. 
The tattooing chairs in the shops could be interactable, flex "e" and appear on the chair . There could be a crafting location where an artist can craft the materials for tattoos. And they could also have an animation where they are "working" on the customer like a mechanic would a car. 

While tattoo removal isn't as easy as going and saying "I don't want this anymore." I thought I might offer a possible solution: Can skin color be added to tattoo options, because you can get the same tattoo over an existing one. If the new tattoo is tattooed over the existing one in their skin tone, it could possibly act as either a cover-up OR "removal".

Fully aware this could be a huge project to undertake, but it could also be what sets this city apart.

**Comment by DaxterPancake** [comment]
Really cool idea, but please remake following the template found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).

Thank you.
Daxter.
**Project Manager.**
