### ISSUE TITLE
[jobs/tattoo_artist] Put sentient people behind the needle

### ISSUE THREAD

**Issue by Wolffest1991** [InZidiuZ/op-framework-issue-tracker#1761]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes

**Summary:**
Write a summary of what your suggestion is about. 
Here's my thought-baby: Tattooing consists of simply standing in a circle and possibly getting your whole body blasted with ink within a matter of minutes. 
**INSTEAD** Have people tattoo people. Make it so some interaction needs to happen in order for you to have something put on your body permanently. Right now, if you make a mistake in the tattooing circle, its there FOREVER! Lets make it have a few more steps in the process. 
If tattooing was a job, it would create a few potentials for RP. In the event that tattooing does become a job, artists will need supplies: Steel, rubber and alcohol (vodka) for artists to craft sterile needles, ink and ink cups. This would give cause for divers and "cleaners" to stop at a tattoo shop to sell  items to artists like they would a mechanic. 
The tattooing chairs in the shops could be interactable, flex "e" and appear on the chair . There could be a crafting location where an artist can craft the materials for tattoos. And they could also have an animation where they are "working" on the customer like a mechanic would a car. 
While tattoo removal isn't as easy as going and saying "I don't want this anymore." I thought I might offer a possible solution: Can skin color be added to tattoo options, because you can get the same tattoo over an existing one. If the new tattoo is tattooed over the existing one in their skin tone, it could possibly act as either a cover-up OR "removal".

**Reason:**
Why would your suggestion be a good change to the framework?
This could create both jobs and avenues for RP. On the subject of jobs, the ones we currently have seem to be getting saturated, even the whitelisted jobs are starting to get crowded. There are 6 tattoo locations in Los Santos, each of them being a potential new spot to hang out and get a tattoo.

**Comment by rajbastakoti** [comment]
nice idea , this makes tatto (permanet thing ) bit more serious as IRL  and adds rp for players

**Comment by tannerds12** [comment]
I think this is a great idea!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
