### ISSUE TITLE
[game/boomboxes] Boombox in my server dont work it never loads the ui for all players 

### ISSUE THREAD

**Issue by SuryaSharma-RoyalLuck** [InZidiuZ/op-framework-issue-tracker#1762]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198190963745/

**Summary:**
When you use boombox you get stuck either your friend has to pick it up or you get stuck and have to quit the game and comeback as the ui never loads !!

**Steps to Reproduce:**
Just take a boombox in Legacy Nepal and use it ! It will trigger it !! 

**Expected Results:**
What are the expected results?
 You will get stuck

**Actual Results:**
You will get stuck if no help cant use any thing after that just mouse works 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
normal 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Nepal 

**Notes:**
i have uploaded a clip on youtube here is the link :-  https://youtu.be/wMgyA3Z9-_w

**Comment by InZidiuZ** [comment]
This issue has since been resolved.
