### ISSUE TITLE
[game/blips] Add a Map Blip for City Hall

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/op-framework-issue-tracker#1763]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Can we please add a map icon for City Hall? 

**Reason:**
City Hall is a hub for a lot of civ RP with state events, meetings, etc. happening there regularly. However, it can be difficult to direct people to the location without a map icon. It also can be confusing because there is an icon for the court house, so often times newer players will end up going to the wrong place.

**Comment by InZidiuZ** [comment]
This has now been done.
