### ISSUE TITLE
[base/admin] Ability for staff to check other players' playtime

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1764]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There is a feature ingame to check your /playtime I was suggesting that when an ingame admin runs this command eg(/playtime server id of player) this would provide the staff the playtime of the player. This would honestly help as to see someone's playtime you need to go on the web panel and check this might make it more efficient when you are giving any warnings to new players.
**Reason:**
Why would your suggestion be a good change to the framework?
Adding this feature this minor update to the command would help staff being able to check playtimes and issue warnings or kick/ban on depending the playtime and the teams decision without having to open the panel to check the play time.

**Comment by rajbastakoti** [comment]
also , the playtime on  the admin site is ( measured in seconds) can we make it as hours ,
 this would make things easier for admins

**Comment by InZidiuZ** [comment]
> also , the playtime on the admin site is ( measured in seconds) can we make it as hours ,
> this would make things easier for admins

That is an issue with the admin panel itself, and has already been reported [here](https://github.com/ExpDev07/legacy-rp-admin-v3/issues/58).

**Comment by InZidiuZ** [comment]
This has now been added.
