### ISSUE TITLE
[vehicles/?] Addition of car controls UI

### ISSUE THREAD

**Issue by ItsGUARDIAN** [InZidiuZ/op-framework-issue-tracker#1765]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
Write a short summary of what your suggestion is about.
Addition of a UI that displays buttons that are actually present in cars such as the engine start/stop windows , and also the door locking and lighting controls.
https://gyazo.com/f8555a608d249dc2b67e0fb418265e10
https://forum.cfx.re/t/release-standalone-vehcontrol-nui-menu/1746959
**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good addition to legacy as this would be more realistic and convenient for everyone and this could possibly create more realistic rp for the players.

**Comment by twooot** [comment]
Was added
