### ISSUE TITLE
legacy glitch city 2 boombox

### ISSUE THREAD

**Issue by chickenmaggi** [InZidiuZ/op-framework-issue-tracker#1766]
the boombox of city 2 in legacy server is not working, whenever we try to use the boombox, we get stuck there and we can't move until somebody carry us to somewhere away from boombox. there's some glitch i guess. please fix it as soon as possible

**Comment by iGreatWhite** [comment]
I would recommend remaking your suggestion using the template provided. Otherwise it makes bug reports hard to look over.

**Comment by DaxterPancake** [comment]
Remake using the bug report found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).

Thanks,
Daxter.
**Project Manager.**
