### ISSUE TITLE
[game/inventory] Add a bag as storage

### ISSUE THREAD

**Issue by NitroGamer80** [InZidiuZ/op-framework-issue-tracker#1768]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Add a bag which people can carry at their back in which we can store things stuffs like food, guns, lockpick etc, as it makes it unrealistic carrying so many things in our pocket.
 
Example:
https://cdn.discordapp.com/attachments/670635060143063040/834485304206557194/unknown.png

**Reason:**
As I told it to make it unrealistic carrying so many things in our pocket, it will make it realistic as well as make sense carrying many things in the bag.

**Comment by ainstaylor** [comment]
This makes it easy to hide items from the police and other people.

**Comment by NitroGamer80** [comment]
> This makes it easy to hide items from the police and other people.

police wouldn't check us until we are arrested or suspect of any case and it is fine.

**Comment by nikkoendres** [comment]
How it used to be back in the day was rifles and smgs wouldnt show up on your back so if you where carrying one you had to have a duffle bag in your outfit, would be cool to see something like this again where if you have a duffle bag on it dosnt show anything on your back.

**Comment by twooot** [comment]
I added the ability for burgershot and bean machine to package any food into a paper bag for you. However i will not give people the ability to put anything into bags or backpacks
