### ISSUE TITLE
Bug report Black Infinite loading screen trying to enter house

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/op-framework-issue-tracker#1769]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Player Identification:**
What is your steam profile?
KrigTroff#8460
**Summary:**
Write a short summary of what you are experiencing.
I am getting the infinite loading screen when trying to enter my house on Mirror Park Boulevard 4. It is a custom furniture house. I have not had any issues till this last update. I have cleared my cache and was able to get in twice today. Then third time got the black screen again. had to disconnect and reconnect every time I get stuck in the loop. It has happened to me on every house type. I am able to break into the houses during robbing hour fine. But not enter my houses normally. 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue. Just tiring to enter into the house, 

**Expected Results:**
What are the expected results? Be able to use my house again. 

**Actual Results:**
What are the actual results? Infinite Black loading screen every time I try to enter the houses. I

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1600
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
legacy RP NA/EU
**Notes:**
For anything else noteworthy.

**Comment by seekertransformer** [comment]
I am having this same Issue w my Apt On Laguna, Black screen wont load also same when ppl try visiting
![Screenshot (18)](https://user-images.githubusercontent.com/82508942/115601760-03a57780-a293-11eb-9094-594d25ddc6d7.png)

**Comment by InZidiuZ** [comment]
> Apt On Laguna

Can you give the exact address and what server it is?

**Comment by KrigTroff** [comment]
Did you need anymore information from me Inzidiuz? Just making sure.

**Comment by seekertransformer** [comment]
> 
> 
> > Apt On Laguna
> 
> Can you give the exact address and what server it is?

I just read the README.md , Im new to this so sorry if this counts as a hijack. I figured it'd be easier than putting up a whole new thread. My bad, excuse me plz if im in violation! 

Address:  Las Lagunas Boulevard 5 / Apt 1
Server: Legacy RP (im in U.S. this is what i connect to  >connect c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
I was asking @seekertransformer for more information, @KrigTroff.

> Im new to this so sorry if this counts as a hijack

No it does not, you're good. It's the same issue experience for both.

> Las Lagunas Boulevard 5 / Apt 1

Do you mean "Las Lagunas Boulevard Apt. Complex E", @seekertransformer?

**Comment by InZidiuZ** [comment]
Okay, for your house, @KrigTroff, it turned out to be a 'USA flag' causing the loading issues. I'm not exactly sure as to why it's not working properly anymore, but I have removed it from the furniture list, and now when it attempts to load that model, it'll replace it with a toilet.

**Comment by InZidiuZ** [comment]
I'm also going to guess that it was the same model for you, @seekertransformer. Though if it's still an issue on next restart, please create another issue.

**Comment by KrigTroff** [comment]
Sorry to ask, will this be a hot fix, or do have to wait till tuesday?

**Comment by InZidiuZ** [comment]
It'll most likely be pushed with tomorrow's restart.

**Comment by riedling11** [comment]
same for me.

**Comment by Alkereo** [comment]
Same for me, Alta Street 6 / Apt2

**Comment by Masik52** [comment]
Calafia rd 7 in stab city is doing this for me but not others. I’ve tried clearing cache but it still doesn’t seem to fix the issue
