### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Cesar420** [InZidiuZ/op-framework-issue-tracker#177]
**Reporter:**
Who is reporting this? Please include discord name.  Cesar#6882

**Summary:**
Write a short summary of what you're experiencing.  So I logged on my character screen(ingame character name is Cesar Ortega senior). and when I press to join as this character, I joined the city as a totally different character,like a fresh new character, no cars in garage,no items nothing. If I will be able to talk to you to discord I can probably describe it even better then here on papers. I also made a new character yesterday,and I think they somehow switch placed or something.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Send me a DM on discord, closing.
