### ISSUE TITLE
[jobs/tuner] "Tuner Job" to Replace LSC

### ISSUE THREAD

**Issue by Jabadab** [InZidiuZ/op-framework-issue-tracker#1770]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
A tuner job that is based on a similar system to the mechanics, potentially a crafting system with items from Chop & Sunken Ship to craft upgrades, cosmetics could either be left in the original LSC (Since most people want to see how it looks before purchasing) or also be craftable.

An example for all the upgrades could maybe be something like this:

Combination of Scrap/Metal/Steel/Aluminum (maybe add more items? Gears, Pistons, etc.)
The amount required should obviously be left up to the devs for balance.

Not sure how hard it would be to re-code the mechanic job to something like this, but I think it'd be a neat way of making more purchasable businesses.

**Reason:**
Why would your suggestion be a good change to the framework?
With the number of people we currently have, people are always looking for things to roleplay with, LSC has been something anyone can use for a long time, with changing this, it would give opportunity for more people to purchase places such as Benny's to modify peoples cars for them, bringing a lot more interaction with people in your day whilst in Legacy.

**Comment by ItsBeckyy** [comment]
I have already put in a business plan for this

**Comment by twooot** [comment]
We kinda have the midnight club for this
