### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NitroGamer80** [InZidiuZ/op-framework-issue-tracker#1772]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
As I have been in the city for several weeks and noticed that there is only two main way to earn money that is selling cocaine and weed else garbage, add more ways to earn money(decent), like adding more jobs in life invader, more illegal ways in which we get more money.

**Reason:**
As there are very few ways in which we earn a decent amount of money which makes player grind more instead of doing roleplay, I saw the maximum number of people grind instead of doing roleplay (I mean maximum of the time not whole time),
adding more money earning ways will increase roleplay in the server(more money-making doesn't mean like too much, I mean a pretty more than current ways) because people will not have to grind major of the days(for example: grinding weed, flying cocaine plane maximum of the day).

**Comment by InZidiuZ** [comment]
Closing this as it's too vague and isn't suggesting anything specific.
