### ISSUE TITLE
[game/inventory] Move lockers at Lost MC

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1774]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?  yes

**Summary:**
Would like to see the lockers moved from inside the MC to inside the Garage bays somewhere.  Possibly one in each building, as we have 2 shops.

**Reason:**
for RP, the mechanics NEVER go into the MC Clubhouse for obvious reasons.  Having the lockers in the MC Clubhouse makes them unusable by quite a lot of people, or causes the RP to be very poor.

**Comment by InZidiuZ** [comment]
Any suggestions for where exacly?

**Comment by Insidious-Space** [comment]
> Any suggestions for where exactly?

In the building opposite ideally, either in the room with the computer and bed to the right or the room to the left with the table inside.

**Comment by PsychoGrandpa** [comment]
Theres no locker in both the buildings so he is suggesting to add one right here (1st picture) another right here (2nd picture)
[https://imgur.com/a/x83mHSh](url)
[https://imgur.com/a/ZUHMMig](url)

**Comment by riedling11** [comment]
yes agreed, if they could be placed in both offices, one in each building, that would be ideal.  else anywhere in the bays would be fine.  next to the car wash in the smaller building, and anywhere in the larger, 4 bay building as well.

**Comment by InZidiuZ** [comment]
Two lockers have now been added at the suggested spots.
