### ISSUE TITLE
[illegal/*] Robberies Improvements

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1775]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
I have thought about this idea for a good amount of time and with how the server is right now, it could be a decent improvement for all aspects. I was thinking to possibly tie in a progression system to robberies as a whole so people would have a tougher time acquiring the items and things needed to hit banks and jewelry stores. With stores, you could have rare chances at, lets say for example of an item to use to get into banks (could be changed at anytime) key cards, These would be used to swipe at the vault door to get access inside. This would make bank robberies more rare, but the off chance that you might get an item from a bank robbery that can lead you to being able to open the jewelry store and rob that.

**Reason:**
I feel like this suggestion could be a good start to try and brainstorm ideas for Robbery Improvements in the server as robbing banks and jewelry stores take little preparation and people hit them over and over and make tons of money for no reason.

**Comment by iGreatWhite** [comment]
Okay so after some thinking here is a rough outline of the system that I thought of in my head:

House Robberies or Security Truck Robberies > Chance at Safecracking Kits
- Safecracking Kits would be a rare item to drop from houses and Bank Trucks so that it could circulate around the economy by buying and selling.

Store Robberies > Use Safecracking Kit on Safe for a chance at keycard
- With Store robberies, you can still hit the registers for a chance at money but would not get any of the rare items to hit a fleeca bank.

Bank Robberies > Use Keycard at Vault Door for a chance at Security card
- You would get three chances at getting a Security card because there is three spots to collect money.
- Possibly allowing people to lockpick the Teller Door and collect money from behind the counter as well.

Jewelry Store Robberies > Use Security card at Office Door to unlock the cases
- These are like the pinnacle of robberies for now since there is no way to hit Paleto or the vault.

Any feedback on this system would be great. This is something that I have brainstormed for a little bit now and slowly want to see if we can push it to action.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
