### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by robin-401** [InZidiuZ/op-framework-issue-tracker#1776]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-Yes

**Player Identification:**
What is your steam profile?
-Jax
**Summary:**
Write a short summary of what you are experiencing.
-When we enter the game there is no spawn location for house that we own..we can not spawn at our houses.there is only 4 spawn location showing...but if we leave city by bus,train station then there is showing spawn location for our houses..i dont know is it a bug or new edition..if bug u should fix it!
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Can you please provide more information? You've filled out only 3 out of 10 sections.

**Comment by PsychoGrandpa** [comment]
> Can you please provide more information? You've filled out only 3 out of 10 sections.

I have a house in Character 1(C1) and no house in (C2). 
The spawn option that is supposed to be on C1 shows on C2. If we try to enter that house with C2 we are spawned just at the door and cannot actually enter the house.
If we enter the city and try to spawn with C1 we will not have the spawn option to our house. We will have to spawn at train/bus station and from their exit the city again to be able to teleport to our house. If its still confusing then Ill post a video.
(Bangladesh Subversion)

**Comment by rajbastakoti** [comment]
> > Can you please provide more information? You've filled out only 3 out of 10 sections.
> 
> I have a house in Character 1(C1) and no house in Character 2(C2).
> The spawn option that is supposed to be on C1 shows on C2. If we try to enter that house with C2 we are spawned just at the door and cannot actually enter the house.
> If we enter the city and try to spawn with C1 we will not have the spawn option to our house. We will have to spawn at train/bus station and from their exit the city again to be able to teleport to our house. If its still confusing then Ill post a video.
> (Bangladesh Subversion)

this happend to me also , 
it doesnot happens to everyone but few people are having it

**Comment by InZidiuZ** [comment]
This issue should now be resolved. I was having a hard time reproducing it, though I don't think it'll be an issue anymore. If it is, please create a new issue or reopen this one.
