### ISSUE TITLE
[game/billiard] Add Billiards game script

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1777]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Add the billiards game script to give people something unique to do while they are roleplaying.

**Reason:**
Why would your suggestion be a good change to the framework?
Adds more content that every single member of the community across all servers to take part in.

**Reference:**
https://forum.cfx.re/t/release-paid-standalone-pool-billiards-for-your-server/2349316

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
