### ISSUE TITLE
Discord invite link

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#178]
**Name:**
SteezyRen#2828

**Summary:**
At the moment maintaining 50 discord nitro boosts can be quite difficult and have noticed it fluctuating. Being under 50 concurrent nitro boosts makes the vanity URL a dead URL unfortunately which means the URL on the top left when in game isn't really helpful to new people who join the server

I suggest going back to a non-vanity URL that has no expiration and putting that up on the top left instead of our vanity URL :(

**Reason:**
No need to have a dead amazing link on the top left of our screen unless we can maintain 50 concurrent nitro boosts on discord.

**Comment by InZidiuZ** [comment]
Hey,

Yes. :(

**InZidiuZ**
*OP-FW Developer*
