### ISSUE TITLE
St. Fiacre Hospital Ambulance Spawn location

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1780]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I am looking to see if we are able to move the spawn point for the ambulances at St. Fiacre Hospital.
**Reason:**
Why would your suggestion be a good change to the framework?
Where the current spawn location you are unable to pull the ambulance out of the garage without having to force it under the signs by speeding out and you are unable to pull it back into the garage.

**Comment by InZidiuZ** [comment]
Please use the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for issues relating to add-on assets.
