### ISSUE TITLE
Bug report infinite Black Loading Screen again

### ISSUE THREAD

**Issue by KrigTroff** [InZidiuZ/op-framework-issue-tracker#1782]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile? KrigTroff#8460

**Summary:**
Write a short summary of what you are experiencing. Black Loading Screen, for me and several others when we try to enter Nikola Avenue 1. Mansion Layout.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue. Just try to enter the house.

**Expected Results:**
What are the expected results? Beale to enter the house. 

**Actual Results:**
What are the actual results? Black Screen of loading

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920X1600

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in? EU/NA Legacy Server

**Notes:**
For anything else noteworthy.

**Comment by Insidious-Space** [comment]
This is also an issue at Nikola Place 1

**Comment by ItsLevitation** [comment]
Its especially bad if you have a lot of furniture put down

**Comment by InZidiuZ** [comment]
Closing this in favor of #1773. I checked both of your houses as well (assuming both was on the international Legacy server), but I loaded in without problem. (see my response on #1773)
