### ISSUE TITLE
ignore this please

### ISSUE THREAD

**Issue by SamBro164** [InZidiuZ/op-framework-issue-tracker#1783]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198394505995/

**Summary:**
Write a short summary of what you are experiencing.
All the vehicles that i drive won't go past 50mph. Cruise control is off reinstalled fiveM, rejoined the server. nothing works. Others tried to drive the same vehicle and they could go past 50mph but I couldn't

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
It doesn't go away. whenever i drive, vehicles don't go past 50 mph.

**Expected Results:**
What are the expected results?
Vehicles should go past 50 mph

**Actual Results:**
What are the actual results?
vehicles don't go past 50 mph

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1366x768

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![2021-04-26](https://user-images.githubusercontent.com/83183784/116034343-c2410d80-a680-11eb-8138-559f6dd1c289.png)

**Server:**
What server/community did this issue occur in?
legecy rp india #1 and #2

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Closing due to no proper repro. I have no clue how to fix this & it seems like a local issue as I've never seen anyone else have this issue. You could also ask the manager of your server to wipe your user data, perhaps.
