### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rushankkala68** [InZidiuZ/op-framework-issue-tracker#1784]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198419516008/

**Summary:**
Write a short summary of what you are experiencing.
When we do /blocks in-game where the smoke tree block exist it shows only 10 houses in that, when we own the block there it shows 11 houses in the company tablet and also I am able to enter the 11 house but not able to sell that house to anyone or buy it for my self as well.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?
In /blocks the there must be 11 houses and also be able to sell the 11th one

**Actual Results:**
What are the actual results?
Not able to sell that 11th house and there are 10 houses showing in /blocks

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1080p

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India
**Notes:**
here is the video link 
https://youtu.be/WURHTHOiceQ

For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
