### ISSUE TITLE
/playtime [Server_ID] Bug

### ISSUE THREAD

**Issue by CaptSpider4** [InZidiuZ/op-framework-issue-tracker#1786]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/CaptSpider4/

**Summary:**
Write a short summary of what you are experiencing.
/playtime [Server_ID] command have a bug, It shows steam name of the staff member who is running command when we check playtime of the players. However it sometimes shows their ( Player's ) steam name itself.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
-

**Expected Results:**
What are the expected results?
Should show the steam name of the player whose playtime its showing.

**Actual Results:**
What are the actual results?
Shows steam name admin who checks playtime

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
First playtime is mine, second and third are playtime of some players 
https://gyazo.com/371b0c646a66c0651de6edb579755139

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
-

**Server:**
What server/community did this issue occur in?
Legacy India #1 & Legacy India #2

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has since been resolved.
