### ISSUE TITLE
[illegal/weed] Increase weed selling time or price of weed

### ISSUE THREAD

**Issue by NitroGamer80** [InZidiuZ/op-framework-issue-tracker#1787]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Increase weed selling time, if we sell weed from 7 am we get 300-400 but it is like 7-8 or 7-9 else the price drops below 200, so slightly increase the time or the selling price of weed, as there are fewer ways in which we can earn decent money, one of them is weed.

**Reason:**
It will give a slight increase in rp, as it will give more money so people will not have to grind that much.

**Comment by InZidiuZ** [comment]
It drops as more people sell & the demand lowers. 7AM just happens to be when the 'demand' resets. We could perhaps decide on how much the demand is lowered using the amount of players online, so it'd be work well on servers with both 20 players & 200.

**Comment by NitroGamer80** [comment]
> It drops as more people sell & the demand lowers. 7AM just happens to be when the 'demand' resets. We could perhaps decide on how much the demand is lowered using the amount of players online, so it'd be work well on servers with both 20 players & 200.

yeah I mean to say that don't lower it to much as many people are playing from last few days.

**Comment by KrigTroff** [comment]
There are good days and bad days, to sell stuff it’s not always about the money, it’s the risk to push your product. Even in the real world, people will sell for lower prices just to get what they can. It seem fine to me, just have to work harder and roleplay more to make it work. I honestly do not think it needs to be changed. People need to stop always looking for more money. Roleplay is not always about the money.

**Comment by NitroGamer80** [comment]
> There are good days and bad days, to sell stuff it’s not always about the money, it’s the risk to push your product. Even in the real world, people will sell for lower prices just to get what they can. It seem fine to me, just have to work harder and roleplay more to make it work. I honestly do not think it needs to be changed. People need to stop always looking for more money. Roleplay is not always about the money.

So you want that people grind major of the time instead of doing the actual roleplay?

**Comment by DaxterPancake** [comment]
Alternatively we could go to a system where the more officers **on duty** means you'll get paid a little bit more. Means that people want to sell with a lot of police around and risk jail time.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
