### ISSUE TITLE
[game/emails] E-mail System

### ISSUE THREAD

**Issue by rajbastakoti** [InZidiuZ/op-framework-issue-tracker#1788]
**Name:**
Who is suggesting this? Please include discord name.
Grishma , RajGrishma#9781

**Summary:**
Write a short summary of what your suggestion is abou
i want to suggest adding an in game email system as IRL , which can make the comms of players more better 
for this if we can have an two email system where players have personal email and a kind of group/common email(shared )
in which everyone can have a personal one but group emails could be made more hard to make  (only could be made if player has certain items like laptop / have a furniture )
as a communication system , 

for example if company wants to talk to one another  , theres no system where there could be communication besides knowing owners number or mention on twitter 
also , if police wants to talk with a business owner its same thing ,
i think we are limiting the communication by just phone numbers .

also if someone does illegal good sale s rp and while doing that rp if they dont want to give their identity ,(/number )
its done the resources availabel till now makes these kinf of things impossible ,
if there was such e mail kind of system  the person could tell i am (thermitedealer@legacy or th like that ) this would be better

also this could be used as system to properly manage the new  business we are having on our server ,
for example if (X) want to thorw party at a bar , and its already owned by some one else(Y) , there are no chances X can tell hello y i want to do this until and unless X knows / has number of Y ,
( this thing cant be on twitter like hello y i want your bar cuz i want to do some cocain party )

same things with gang if Example TLMC wants to talk to GSF , theres no way of comms available , until and unless some one' number is available , it cant be on twitter either 

this has made me feel so limited in so many situations , also i came to know  many people felt need of this , i think more things can be brought into the system

**Link:**
If there are any links to what you're suggesting, please add them here.

**Reason:**
Why would your suggestion be a good addition to Legacy?

this will solve the problem we are having as a character in rp , 
the twitter is just so public and the phone message is just for a single person and a dark chat no one even can get idea whats going on
this would make the in rp communications more better and help in several aspects of rp  ,
 make things more managed in rp ( business , real estaes , doj ,nearly every jobs can get more managed )
also many things like notification management of jobs/propertyor vehicle payments as an additional features

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
