### ISSUE TITLE
[game/warehouse] Remove Warehouse and Add Pawn Shop

### ISSUE THREAD

**Issue by nikkoendres** [InZidiuZ/op-framework-issue-tracker#1789]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
First of all the warehouse is agreeably the most scuffed location in the entire city. When entering the warehouse people just accept the fact that when they come back out their car will most likely not be there anymore in their eyes. I see the current warehouse as being a means of allowing grinding of a job for extensive periods of time with little to none interaction with another person. I see the removal of the warehouse as a way of taking a bottomless pit of money that is grinded 24/7 out of the city for the better. With the warehouse no longer existing people who grind diving and other means of maintaining materials (Scrap, Glass, Aluminum ect.) would be forced to sell to people who need such materials directly(mechanics).

**Reason:**
I think my change would be a good addition to the framework because it would allow the city to stop relying on game mechanics and rely more on good RP for people to make profit. Alongside this suggestion could be the introduction of something like a pawn shop that is run by workers (players) that are able to sell commodities (jewelry, watches, gold bars) to a interactable menu like everyone does now. This change would promote more RP within the city between people selling and buying valuables.

**Comment by Deggan8** [comment]
With this you might be able to take your Idea a step further. 

With the Warehouse: You could make this a recycling centre. Someone could Own this and you could change some of the materials you find into Recycling materials. The owner/Worker of the Recycling centre could have a system in the warehouse which exchanges this recycling material to Steel, Scrap, Aluminium etc. 

This would increase RP with the sellers of the Recycling Materials to the Players at the Warehouse, then Mechanic shops can place Orders to the Warehouse for Materials for their shop. 

Adding the Recycling Materials to Scrapyard, Diving and Trash but removing the selling spot from the warehouse. 
You could still have drops for Steel, Scrap etc in these locations and it means the person collecting these materials can still RP and sell to Mechanic shops.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
