### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#179]
**Name:**
badwolf#3160

**Summary:**
I think its quite unrealistic that the police main firearm can't be taken if. Its understandable if their side arm isnt able to be taken of them  because realistically police hide those in their waist band but in IRL if cops are ambushed its possible for take their weapons of them. But crimanal on the server will have to trust that the police wont pull out the weapon even though the criminal might have indicated taking away their weapons. 

**Reason:**
This will make it more realistic and prevent criminals from being victims or failrp

**Comment by InZidiuZ** [comment]
Hey,

After next update, police are able to customize their loadouts. However, we won't allow them to actually drop them as items, as that would quickly make police-robbing a very common thing, and also quickly break the economy.

**InZidiuZ**
*OP-FW Developer*
