### ISSUE TITLE
[game/death] Improve Game Mechanics Towards Downed People.

### ISSUE THREAD

**Issue by nikkoendres** [InZidiuZ/op-framework-issue-tracker#1790]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
The current state of the ways you can interact mechanically with fellow "criminals" in my opinion is at a minimal, I believe everyone should be able to /escort, and a form of /suspect in towards downed people. In reality if multiple people got injured you wouldn't put one in your trunk and leave the others to come back, you would fit as many people you could into open seats within the car. My suggestion for allowing /escort of a downed person by someone who cant already (Police, EMS) would keep the work(coding) towards introducing such a feature to a minimal, there would be no need for a new system entirely just something as simple as giving "criminals" the ability to /escort someone to a vehicle and using /supsect in to put them inside the vehicle while downed. 

Additionally I would like to see the feature added of when a person is downed inside a vehicle they stay inside the vehicle instead of slipping through the floor. Obviously the current system is not very realistic and functional in a way where after a shootout between two vehicles is over the downed individuals are scattered randomly depending on how long the shootout lasted. Alongside this change I would suggest if peoples bodies where to stay inside the vehicle their collisions would be turned off to prevent blocking of bullets.

**Reason:**
My suggestion would be good for the framework because it would give the ability of manipulating downed people into vehicles to "criminals" like police and ems already have. My suggestion is a very minimal tweak that would benefit the framework significantly and change the way shootouts and interaction towards downed individuals occur for "criminals".

**Comment by DaxterPancake** [comment]
I don't believe that everyone needs a /escort as they can just carry them to the car but I believe the /suspect in and /suspect out could be useful.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
