### ISSUE TITLE
[vehicles/modifications] Underglow Not Saving Bug

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1791]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/igreatwhite/

**Summary:**
Write a short summary of what you are experiencing.
Neon Underglow is not saving when you put it on and then take out your car.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Put underglow on the car
Select a color
Store the car
Go back to LS customs and see that under neon color there is no option selected like before

**Expected Results:**
What are the expected results?
Neon underglow to work properly when applied and to save on taken out the garage

**Actual Results:**
What are the actual results?
Neon underglow is bugged when the car is pulled back out after reapplying the color

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Cannot send anything right now not in game.
**Game Resolution:**
What is your game's resolution?
1080p
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
Not in game if needed i can get it
**Server:**
What server/community did this issue occur in?
International
**Notes:**
For anything else noteworthy.
N/A

**Comment by nikkoendres** [comment]
The garage system must not be accounting for the underglow state / color when stored.

**Comment by InZidiuZ** [comment]
This will be left as a wontfix until the vehicle system is rewritten.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
