### ISSUE TITLE
[maps/*] Removal of Vagos Graffiti and additional West Side Bloods Graffiti added Vespucci 

### ISSUE THREAD

**Issue by Scribbyz** [InZidiuZ/op-framework-issue-tracker#1793]
**Name:**
Dylan Sikes, scribby#4100

**Summary:**
Removal of the Vagos graffiti that is currently down at Vespucci, Melenoma Street. With also the addition of new graffiti being sprayed onto the wall for the current gang that is holding this turf. (Links for both Street location and wall for additional Graffiti included in **links**)

**Link:**
https://gyazo.com/a58e169e47cd792f89d82787b8724acc (Street Location with Vagos graffiti) 
https://cdn.discordapp.com/attachments/808352160957464616/836758522850967572/image0.png (West Side Blood Logo/Graffiti) 
https://cdn.discordapp.com/attachments/758228983778246709/837048533420736542/unknown.png (Wall location for new graffiti) 

**Reason:**
Currently the turf itself is owned by the West Side Bloods (EU/NA Server). They own the full block that has been identified in the street location link. The group have been around for the last 3 months and is continously growing with up to 15 members. We believe it would be much better for our turf/area that we hang out at constantly to not have another gangs graffiti. We've created our own graffiti that we would love to spray onto the walls so our area is known to be run by us and not the opposing gang "Vagos". This would also give our members and other outside eyes the look at the block/turf that we actually own it. For a RP situation it does not look good that a gangs current hang around spot/living place has graffiti from another gang. If possible we would have taken the necessary actions to clean the graffiti off or spray over.

**Comment by InZidiuZ** [comment]
This would be something for the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
