### ISSUE TITLE
[Game/Weazel_news] Improvement in Weazel news vehicles.

### ISSUE THREAD

**Issue by azpranto** [InZidiuZ/op-framework-issue-tracker#1796]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Weazel news vehicles need to improve. We can't shoot any event, race or robbery scene. We need a news helicopter with a camera in game to improve news reporter rp. And news vans are not realistic. In real life, usually news vans have some antennas, wireless receivers etc. But in game we don't have any of these.

**Reason:**
It will help both in news rp and other rp's. Unique then any other server out there and people will be more interested about news rp as they have a chance to ride a helicopter. 

Vehicles pack: 
https://forum.cfx.re/t/release-weazel-news-pack-news-vehicles-pack-2-2-discontinued/171540

**Comment by InZidiuZ** [comment]
There are no additional 'news vehicles' in the default game. You'd have to suggest some assets to be added in the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
