### ISSUE TITLE
Jobs aint getting Paychecks - Bug report | (Legacy India subdivision)

### ISSUE THREAD

**Issue by Sharpeye0420** [InZidiuZ/op-framework-issue-tracker#1798]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/sharpeye25/

**Summary:**
Write a short summary of what you are experiencing.
Jobs aint getting paychecks. Irrespective of how many times I reset the job. I tried giving job again after getting unemployed. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Get any job PD/EMS and there is no paycheck getting credited. 

**Expected Results:**
What are the expected results?
It should be getting paid every few minutes like it was 2 days back I guess. 

**Actual Results:**
What are the actual results?
Salary getting credited every 5 minutes I guess.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1080*786 

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/05390052b64022b15a7f09f104e608f4

**Server:**
What server/community did this issue occur in?
Legacy India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
If this is an issue after the next update, please create another ticket.

**Comment by Abhishek7410** [comment]
Its still same , not getting paychecks
