### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#180]
**Name:** AdeptCL#0402

**Summary:** Under the bed cash storage.

**Reason:** For "group work", it would be helpful to store the cash into an area which can be accessed and know that that amount is from "group work". Having said this, when taxes are implemented into the server, it will allow the hidden cash to be non-deductible for tax because it isn't stored in the bank.

The idea is to have a storage for cash, that is separate to everyone's bank for holding cash that technically should be between a group of people.

Also, it could be used as a "saving" system for the people who are trying to save for a new vehicle/etc.

**Comment by InZidiuZ** [comment]
Hey,

Closing this as it isn't particularly relevant at the moment. Possibly when a proper housing system is implemented, but don't really see the need to have it for "group work". Taxes would also just effect store purchases, such as when buying consumables, weapons, tools, etc.

**InZidiuZ**
*OP-FW Developer*
