### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rushankkala68** [InZidiuZ/op-framework-issue-tracker#1800]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198419516008/

**Summary:**
Write a short summary of what you are experiencing.
/blocks has been fixed for smoke tree road 11 but still not able to sell the property

**Steps to Reproduce:**

**Expected Results:**
What are the expected results?
able to sell smoke tree road 11

**Actual Results:**
What are the actual results?
it show in tablet but not able to sell it to anyone
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1080p
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India
**Notes:**
https://youtu.be/F8LfL00Alok 
this is the link for refrence

**Comment by InZidiuZ** [comment]
This has since been resolved.
