### ISSUE TITLE
Suggestion: Please Remove Locals from La Fuente Blanca

### ISSUE THREAD

**Issue by terpsaucin** [InZidiuZ/op-framework-issue-tracker#1801]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There is a swarm of locals with guns that manifest at the La Fuente Blanca every 10-15 minutes, it doesnt matter if you have a weapon out or not anywhere from 2-12 people will just start shooting. Putting it a formal request to have them removed. 

**Reason:**
Why would your suggestion be a good change to the framework?
The police are getting APB's about the gun fire from the locals on a borderline obscene level. I know that this happens at Lost MC as well after every nightly reset but they seem to not come back through the day, I feel like this is wasting the PD's time sending people up every hour to see what's going on, and it is also messing with our ability to conduct underground business. As Lost MC is a business I don't think that there will ever be a gang shoot out there but I would hate to see a situation where the police don't get involved with the Blanca because they think its just another local situation as that kind of breaks into their RP as well. 

Thanks!

**Comment by InZidiuZ** [comment]
This has now been done.
