### ISSUE TITLE
[base/admin] Enhancement of toggled features such as /ind and /voice_debug

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1802]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
My suggestion is to add a notification on screen when /ind or /voice_debug is enabled for a player the admin would get a notification like "toggled voice_debug on for XYZ" https://gyazo.com/fd4e7341a2b6ad79ffed10c84ed92a4c
**Reason:**
Why would your suggestion be a good change to the framework?
This would be help for admins to know if the feature is turned on or off because the current feature only shows the feature has been toggled doesnt state feature as on or off. This would be helpful in events as well when vehicles are repaired or something but we arent clear if the feature is in on or off  state.

**Comment by milan60** [comment]
This was implemented
