### ISSUE TITLE
[jobs/?] Second car dealership

### ISSUE THREAD

**Issue by baritonebear** [InZidiuZ/op-framework-issue-tracker#1803]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes - baritonebear#4908

**Summary:**
Have business proposal pending to utilize the luxury car dealership located in Rockwood. Was told by Ace to submit to city architects to ensure it was a viable plan. The building is already open and unused, the following changes are requested as part of the proposal:

1.  Lockable doors on exterior and interior (adding a door between the lobby and show-floor would be beneficial if possible)
2.  Usable car slots (probably 4) across the show-floor, controlled by the computer in the lobby. Preferably with the small stands removed from being in the way.
3.  One test drive spawn point and one purchase spawn point in each vehicle bay to avoid stacking car spawns.
4.  A nearby garage as there is a lack of parking in the area. Suggestions include either public parking in the area just north of the dealership adjacent to Boulevard Del Perro, or behind the dealership in the alley.
5.  An ATM preferably inside the dealership for security, or on an outside wall similar to PDM.
6. A storage locker/changing room in the area behind the lobby instead of additional office space.

Additional suggested possibilities proposed to the city, but not required to run the operation:
1. An additional EDM purchase point on the pedestal position in the show-floor to keep people safer when carrying cash for EDM purchases. Otherwise this will be used as a used-car consignment show spot.
2. A way to scrap low worth cars for ONLY legal materials. This would remove unsellable cars from garages and provide mechanics with an additional source of materials.

**Reason:**
Why would your suggestion be a good change to the framework?
The whole purpose of the business proposal is to provide the citizens with a luxurious, safe experience when purchasing new and used vehicles. PDM's close proximity to all the things around legion square means that it has been subject to a lot of stressful challenges for both employees and customers, as well as causing strain on the city just through means of a large number of people. Having an additional car dealership would help split up the population (similar to the new pillbox), as well as provide established citizens a more secure location. 

A full outline of the proposed business can be found here: 
https://docs.google.com/document/d/1QA7hnjghCw8eMhcXR71kvk7TMp2MI7w7LVSDmMwd3UY/edit

**Comment by riedling11** [comment]
100% support.  We need an alternative to PDM.

**Comment by Casperrrino** [comment]
This would be so beneficial to the city! It would alleviate headaches in a highly populated area and would put to use an amazing interior not currently being utilized in the city.

**Comment by Smach90** [comment]
This will give alternatives to pdm so that others can experience buying a car in a different way.

**Comment by Geevum** [comment]
I feel that the city could use a more upscale option from PDM and located away from the busy downtown area.

**Comment by XinarTheNeko** [comment]
100% love this suggestion, splitting the flow of people would defently be benefictical as I often experience heavy headaces by PDM

**Comment by TheDisguisedLion** [comment]
This would benefit the city greatly! Having two separate locations would give the citizens the options to go somewhere else to purchase vehicles, give the city another location to have more interactions with each other, and also create a competitive market in selling vehicles.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
