### ISSUE TITLE
[vehicles/rentals] Faggios For Hire

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#1804]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Summary:**
So the idea is to create a hiring station at the player creation point (Airport) where any player can hire a scooter and reach their desired destinations. Also as soon as the player leaves their seat a de-spawn timer would get triggered which would come up something like " 200 secs to end the rent " so after completing that the vehicle would de spawn itself which would stop players from misusing them. 
**Reason:**
This would not only stop players from randomly shooting at npc's for their vehicle but also provide an extra option over taxi's where they could save few bucks

**Comment by rajbastakoti** [comment]
player creation point (Airport) to city for a player was easier when we had a metro / transit system but since we dont have this now players face problem s . 
good idea ,

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
