### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rushankkala68** [InZidiuZ/op-framework-issue-tracker#1805]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.
Decals for the pdm uniform.

**Reason:**
Why would your suggestion be a good change to the framework?
There are limited uniform for pdm if there would be some decals for pdm dress it would be nice and also give us the variety of dress for pdm

https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fgtawiki%2Fimages%2Fd%2Fd7%2FPremiumDeluxeMotorsport-GTAV-Logo.png%2Frevision%2Flatest%3Fcb%3D20180812101840&imgrefurl=https%3A%2F%2Fgta.fandom.com%2Fwiki%2FPremium_Deluxe_Motorsport&tbnid=ZTmiG8O8SRdMiM&vet=12ahUKEwjgldi91rrwAhVa1XMBHdwKD8MQMygAegQIARBs..i&docid=E-tBtxUQeBo-VM&w=256&h=128&q=premium%20delues%20motorsport%20logo&ved=2ahUKEwjgldi91rrwAhVa1XMBHdwKD8MQMygAegQIARBs

**Comment by InZidiuZ** [comment]
Use the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for this.
