### ISSUE TITLE
[animations/library] Similar to dog emotes, emotes for cats

### ISSUE THREAD

**Issue by twooot** [InZidiuZ/op-framework-issue-tracker#1807]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*We have animal emotes, but sadly they only work for dogs, it would be nice to have similar emotes (lying down, sitting, etc.) for cat Peds as well.*

**Reason:**
Why would your suggestion be a good change to the framework?
*It allows people to have richer animal RP with not only dogs*

**Comment by milan60** [comment]
This is somewhat implemented, the only thing that would be nice to have now is a sit emote as well, then I'm happy :)))
