### ISSUE TITLE
[jobs/?] Restaurant Functions to Reflect Approved Business Plan "Casa Blanca" 

### ISSUE THREAD

**Issue by terpsaucin** [InZidiuZ/op-framework-issue-tracker#1808]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes.

**Summary:**
Write a summary of what your suggestion is about.

The following is a list of requests to have implemented at the Italian "Mafia Themed" restaurant that we have recently purchased. All features listed here were approved by Gov. Winters before he left office. 

**LIST OF FEATURES**

- [ ] Food menu for purchase at bar. 
- [ ] Pizza  (“King Veloce” $80.00 - A pizza fit for a King… or maybe even a Queen.) Named after Abby King.
- [ ] Pizza Delivery system that mirrors Burger Shots.
- [ ] Pizza Delivery for player to player interaction via phone. (wish list) 
- [ ] Map Marker

### EXAMPLE PICTURES

<a href="https://ibb.co/KFyLm6B"><img src="https://i.ibb.co/TmhbrcJ/map.jpg" alt="map" border="0" /></a>

<a href="https://ibb.co/Jn8Rg4f"><img src="https://i.ibb.co/5TCWwyN/deliveryzone.jpg" alt="deliveryzone" border="0" /></a>

<a href="https://ibb.co/ZcgBps9"><img src="https://i.ibb.co/9y4bkXP/casa-blanca-menu.png" alt="casa-blanca-menu" border="0" /></a>

<a href="https://ibb.co/wRvxx9f"><img src="https://i.ibb.co/kxdWWRt/CASABLANCA-WHITE.png" alt="CASABLANCA-WHITE" border="0"></a>

**Reason:**
Why would your suggestion be a good change to the framework?

Our primary focus with this location is to provide exciting and unique RP in the basement of the restaurant via underground gambling. We have created a system via current in-game commands and Excel spreadsheets to deliver a pretty solid gambling experience including blackjack for up to 4 people at the same time per table and roulette for how ever many people we can fit. A lot of people in the town have also requested pizza for what seems to be a long time and we would like to be able to provide this experience. 

As I am part of the interior asset team, I can provide server ready image assets for the exteriors as well as image assets for the menu. 

The purpose of the "Burger Shot" delivery system is so we can have the funds to bank roll the underground gambling at night as people are already walking away with a lot of money and it making us have to be in city working almost 24/7 to cover it. As our primary focus is the RP of the basement we don't care about money we just want to be able to provide the experience and not have to grind out bank roll else where. Pizza will always be delivered in uniform (shown below) and the system will not be abused for personal gain. 

<a href="https://ibb.co/DVZHDBd"><img src="https://i.ibb.co/dWRw0NZ/Screenshot-2021-05-10-154741.png" alt="Screenshot-2021-05-10-154741" border="0" /></a>

### If you have any questions or would like to discuss this further I can be reached in the Legacy discord server, my name in there is "D" 

Thanks!

**Comment by DevilDoc-007** [comment]
My only suggestion would be to the menu and would maybe be a "dolce" or sweet red desert wine and breadsticks or bruschetta

**Comment by Nuziatella** [comment]
Custom Signage on exterior of building and windows.
 Lock on door for underground gambling basement.
 ATM for customers and gamblers.
 
 These suggestions need to go to the correct github. 
[Legacy Assets Issues]( https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

**Comment by terpsaucin** [comment]
> Custom Signage on exterior of building and windows.
> Lock on door for underground gambling basement.
> ATM for customers and gamblers.
> 
> These suggestions need to go to the correct github.
> [Legacy Assets Issues](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

apologies, will update right now

**Comment by AnitaSh0wer** [comment]
As the new owner of Casa Blanca, I would like to implement this proposal! I want Casa Blanca to bring a one of a kind, fine dining experience to Los Santos as well as a more diverse food menu to the community. This plan covers everything I imagined for this endeavour and hope to welcome guests soon!

**Comment by Frostposeidon** [comment]
I LOVE the idea to have more variety of food in the city and place to take people on dates etc is amazing the plans and layout is so thoughted out careful designed I see big future for Casa Blanca I hope to see this proposal go throw as be amazing part to the city!!!!!

**Comment by kaycorriher** [comment]
I think these steps of providing food tailored to the Italian theme is crucial for the role play interactions that can come from this business. Personally, i can’t wait to order a pizza and complain about the wrong toppings on it.

**Comment by AnfewMac** [comment]
YESSSSS!!! This definitely needs to be implemented! Need some variety to the city! Such a great looking restaurant for it just to sit there not being utilized.

**Comment by HorribleFriend** [comment]
This would be an awesome addition to the city and would spice up the food variation!

**Comment by Smolnisno** [comment]
I think this a great idea especially with the city starting to get more packed again and events starting to bloom more too. this will 100% be beneficial for the city.

**Comment by CowboyRoyWalker** [comment]
I love the idea of this. Bringing a fancier establishment while also bringing in a exciting pizza delivery system would make people have more options to what they want. I also love the gambling area, as that brings more places to go have some fun while enjoying fine dining.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
