### ISSUE TITLE
{Revised }Jobs aint getting Paychecks - Bug report | (Legacy India subdivision) 

### ISSUE THREAD

**Issue by Sharpeye0420** [InZidiuZ/op-framework-issue-tracker#1809]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/sharpeye25/

**Summary:**
Write a short summary of what you are experiencing.
Jobs ain't getting paychecks. Irrespective of how many times I reset the job. I tried giving job again after getting unemployed. 
I registered this before and as asked me to open the ticket if remains same after the server restart and its same. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Get any job PD/EMS and there is no paycheck getting credited.

**Expected Results:**
What are the expected results?
It should be getting paid every 5 minutes like it was few days back I guess.

**Actual Results:**
What are the actual results?
Salary getting credited every 5 minutes I guess.

## Additional Information
Revision of ticket #1798

**Screenshots:**
If suitable, include some screenshots.
nope  

**Game Resolution:**
What is your game's resolution?
1080*786

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/05390052b64022b15a7f09f104e608f4

**Server:**
What server/community did this issue occur in?
Legacy India

**Comment by InZidiuZ** [comment]
This has now been resolved.
