### ISSUE TITLE
Bug report - Police off duty to criminal character.

### ISSUE THREAD

**Issue by XBTech** [InZidiuZ/op-framework-issue-tracker#181]
**Reporter:**
@Cruxer#4806 a.k.a. C. Rendell or Buck

**Summary:**
I went off duty to my criminal character and the blimps of other officers were still showing

**Steps to Reproduce:**
1) Went off duty at the desk in PD.
2) Went to the locker room to exit city and change character.
3) Clicked on my cop character again by accident and spawned at train station.
4) Exited the city from the train station.
5) Went on my criminal.

**Expected Results:**
Blimps of other officers should vanish.

**Actual Results:**
I haven't done further testings on this issue but in my case the blimps of other officers were still showing and they could still see mine.

## Additional Information
To fix the issue I had to completely exit the game and join in as my criminal.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst in game and provide the information you're given.
Not currently in game at the moment so I do not possess that info.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. Issue was caused by improper calls as well as a minor typo which would prevent the created *blips* from being stored, so they later could be removed again.

**InZidiuZ**
*OP-FW Developer*
