### ISSUE TITLE
Trash Workers get Government Texts in Phone

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1810]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
iGreatWhite

**Summary:**
Write a short summary of what you are experiencing.
the Garbage Worker job is under "government" so if you text the government number, all trash workers get the message

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
the Garbage Worker job is under "government" so if you text the government number, all trash workers get the message

**Expected Results:**
What are the expected results?
Trash Workers do not get government texts

**Actual Results:**
What are the actual results?
the Garbage Worker job is under "government" so if you text the government number, all trash workers get the message

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
N/A

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
International

**Notes:**
For anything else noteworthy.
N/A

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
