### ISSUE TITLE
Bug report - cannot repair Zombie chopper and other bikes at Moseley's

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1811]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/riedling/

**Summary:**
Write a short summary of what you are experiencing.
Zombie choppers and other bikes cannot be repaired in the 4 main bays at Moseleys

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
bring bike into bay, needing a repair, and move it into all areas inside the box to see if it can be repaired.

**Expected Results:**
What are the expected results?  option to <R>eview vehicle shoudl appear and then allow mechanic to repair bike.

**Actual Results:**
What are the actual results? the <r>epair vehicle does not appear.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![info](https://user-images.githubusercontent.com/26015469/118012853-1bfb3600-b317-11eb-95b3-3317a582c8d4.png)

**Server:**
What server/community did this issue occur in? Legacy Roleplay #1

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved
