### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SuryaSharma-RoyalLuck** [InZidiuZ/op-framework-issue-tracker#1812]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198190963745/

**Summary:**
Write a short summary of what you are experiencing.
The oxy is marked as false in my server.cfg but is still not working

**Steps to Reproduce:**
Mark the disable oxy runs as false in server.cfg  

**Expected Results:**
What are the expected results?
you are unable to do oxy runs 

**Actual Results:**
What are the actual results?
you are unable to do oxy runs 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
here is a short video showing it :- https://www.youtube.com/watch?v=6pp3KzUXZ-o

**Game Resolution:**
What is your game's resolution?
1080*1920

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Nepal s-13

**Notes:**
The oxy is marked as false in my server.cfg but is still not working

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
