### ISSUE TITLE
[game/?] Character card

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1813]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

The character card is a system of perks and skills that the character we control has / may have. However, these are not attributes such as: strength, agility or charisma, but the skills that unlock / enable the character to perform certain activities or give passive benefits such as: 30% discount in each general store for all products.

You can distribute points in any way you like. **For example**: When you enter the server for the first time, you spend one point on Burglar and save your choice. 
Then, after a week of playing, you open the character card again and add a second point in Locksmith. As you can see skill points, you can give away whenever you like. 
Unless you decide you don't need them, then you can leave the card blank and not give out any of them.

It is strictly forbidden to use the individual words taken from the character sheet and any IC slang associated with it. Specializations in which you invest your three points are to be skills learned by your character over time. 
Using phrases such as: Which locksmith rank do you have? How good a businessman are you? I am looking for a good chemist! shall be severely punished.
	
	                           **_THE CHOICE OF DISTRIBUTE POINTS CANNOT BE REVERSED._** 

Skill Points are designed and limited in such a way as to FORCE people to the fact that they need to interact with someone and make them realize that their character is incapable of being self-sufficient.

Namely, we got 3 points which we can choose and assign to 8 different abilities.

1) Locksmith -
Level 1 - significantly higher (about 30%) chance of opening car at first attempt with lockpick, noticeable faster process of opening lock , without ANY given point you cannot try lockpick ANY vault/safe
Level 2 - 100% chance to open car at first attempt, access to rob Pacific Standard Bank / Casino / Humane Labs (something big, in general)

2) Chemist - 
Level 1 - ability to craft drugs of quality range 40-60% (the lower % the lower price)
Level 2 - ability to craft drugs of quality range 70-100% (the higher % the higher price), planting high tier weed seeds

3) Drug Dealer -
Level 1 - ability to sell drugs of range 40-100% quality without gaining stress with significantly higher chance of successful transaction, selling range of goods 1-3oz per transaction
Level 2 - selling range of goods 2-5oz per transaction, guaranteed 10-20% more money from sellings

4) Weapon Dealer -
Level 1 - ability to register illegal weapon (fake documents)
Level 2 - access to blackmarket in which he can buy goods such as: silencer, laser scope, extended magazine, ability to personalize guns (color, stickers)

5) Burglar - 
Level 1 - higher chance to loot valuable goods
Level 2 - decreased level of stress gaining during burglary (making less noise while moving in house)

6) Businessman - 
Level 1 - significantly increased salary from legal jobs
Level 2 - 30% discount while buying goods in markets/gas stations/bars/restaurants, 10% discount on buying cars, 20% discount from medical fines

7) Mechanic -
Level 1 - access to more advanced repairs and services (for instance, without points you cannot repair cars from EDM/no access to tuner-chip)
Level 2 - more and greater goods from Chop-Shop script, significantly cheaper repair kits

8) Rifleman -
Level 1 - significantly decreased stress gaining while shooting
Level 2 - reduces recoil with FPV with both light and heavy guns

**Reason:**
Why would your suggestion be a good change to the framework?

Its balance system which diverse people whom wants to play 'legal' roleplay and benefits in certain way and people who would like to play specified profession.

The idea mentioned above really influences the development of the level of roleplay to such an extent that people will be forced to gather in groups that each individuals will be a part of a puzzle picture. No more one man army who can rob bank, steal cars, produce drugs as a one person.

**Comment by rajbastakoti** [comment]
it was so smooth , man hope this to be in legacy very soon

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
