### ISSUE TITLE
[illegal/?] Selling system and available drugs rework

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1814]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

_SELLING DRUGS REWORK_

**No more selling zones**, you should be able to sell whenever you pleases (_maybe at least restrict it to urbaned areas, not allowed in woods and hills_) at first present system which distinguished zones to sell certain drugs was entertaining but in a long run its boring and restrict players from more creative roleplay scenarios.

Requirements of AT LEAST 2 police officers at duty to engage sellings:
2-4 Police officers no bonus of sellings
4-8 Police officers 10% more money bonus
8-12 Police officers 15% more money bonus

NPCs reaction for drugs offer:
NPC agrees and buys goods FREQUENT
NPC disagrees and does nothing FREQUENT
NPC disagrees and wants to beat your ass RARE
NPC disagrees and runs away and sends information to police department dispatch FREQUENT
NPC disagrees and makes photo of you and sends it to police department dispatch RARE

Present drugs system works as it spawns NPC nearby and we need to approach him to sell it (approximately 60% chance that NPC won't disappear due to some bug, more less).

As the ratio of spawning NPCs on streets is significantly higher than ever there is huge potential to take this to the next level (and vast majority of people enjoys is)

More variable system is to scan nearby areas (let's say about 10-20 meters radius) with actually existing NPCs with /dealer command. Triggering command will start scanning.
After 5 seconds of loading the closest NPC to us will be interested in buying goods from us.

_WEED_
Concept of new weed seeds system:
People will still plant, harvest weed at house (harvesting weed from fields idea is retarded)
Seeds can be found during some legal works such as garbage collecting, harvesting fruits/vegetables in orchards / house robbery.
Drop rate of seeds should be adjusted accordingly with the quality of the final product.

We can distinguish weed into certain types:
High quality:
White widow THC content 100%
Purple Haze THC content 80%
Gorilla Glue THC content 70%

Low quality:
Strawberry Haze THC content 40%
Swamp Haze THC content 30%

_METH_
Meth production, two ways of creation meth

Meth (white) 70-100% quality from laboratory environment requires items such as:
Methylamine (organic chemical compound)
Aceton (organic chemical compound)
Chemical equipment such as glass tubes, pipes etc
Needs profesional lab equipment to craft combined items (such as in La Fuenta Blanca)
Meth (brown) 60-70% quality from campers production (Breaking Bad vibes)
Creation process with camper:
You receive from NPC location of spawned camper, your task to create meth is following:
Ride a random distance between 8-10 kilometers in some hills environment scenery with a following conditions:
-If you will hit something really hard and damage car, your equipment will be broken and meth creation process is over
-If you will drive over 50mp/h you will get busted
-If you drive slower than 15mp/h (for a longer period of time than 3 seconds) your camper will be noticed by the local NPC and will be reported as “drug activity” for the police department dispatch.
-you need to have companion (requires exactly 2 users, cannot be more than 2 people, cannot start alone)

_**OPIUM**_
Opium is made from the poppy flower, so the process may begin with harvesting them in the field
**Opium production**
Step 1, harvest poppy seed from fields
Step 2, lab process to produce opium product
Step 3, packing opium

Present **cocaine** and **LSD**, **oxy** would be appreciated as well, having diverse options with drugs will make game even better.

**Druga hierarchy** should be:
1) meth
2) cocaine
3) opium
4) weed
5) lsd/oxy

**Reason:**
Why would your suggestion be a good change to the framework?

Its greatly improved version of developing the criminal underworld, merging both option to harvest to some extent and make them at home (with lower quality) and with more sustainable enviroment (there are few intereios which will fit it) making it better.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
