### ISSUE TITLE
[jobs/taxi] Taxi rework

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1815]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

Firstly, there needs to be information for both client and taxi driver that the course has been accepted by this certain taxi driver and if another player tries to accept the same course order will be notified “sorry, this order has been already taken by someone else”.
This is what needs to be changed for players courses to make it easier and pleasant.

Secondly, script to scan nearby areas for potential NPCs clients. This is an opportunity to work even in circumstances when there are no active players/no orders. 
Range of course distances should be from 3 to 10 kilometers. 
-The longer distance, the higher payout
-Chance of getting tips from NPCs
System is to scan nearby areas (let's say about 10-20 meters radius) with actually existing NPCs with /taxi command. Triggering command will start scanning.
After 5 seconds of loading the closest NPC to us will be interested in buying goods from us.

**_Optionally_**, after exceeding the amount of 50 / 100 / 150 courses you will have available new types of taxi (exclusive, faster, more durable) to drive at your disposal. Taxi cars in my opinion should not be private but corporate property. 
-Spawning system such as the present Garbage Collector.
-You cannot return a vehicle if it's too damaged

**Reason:**
Why would your suggestion be a good change to the framework?

Its efficient and crucial improvement to the job.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
