### ISSUE TITLE
[game/items] Handcuffs function

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1816]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

The general idea is to rework how people can be searched, at present moment to do so we need to have to be handscuffed and **_/steal_** command.
It leads to comic situations when someone wants to search other one, but will not be able do it due to fact there are no handcuffs. 

My suggestion that we should be able to be searched under two circumstances:
-after using /e handsup (_all variations_)
-after reaching 0hp and being at BW state 

From now handcuffs should be used only to immobilize person rarther than search purposes. And as we have handcuffs perhaps we should buy as well "keys" with them in pack, maybe its better idea to open them like that than destroying with heavy scizzors.

**Reason:**
Why would your suggestion be a good change to the framework?

Present solution to search someone is not immersive friendly, leads to awkward situations and is totally outdated.
Changing it to mentioned suggestion above would be appreciated.

**Comment by iGreatWhite** [comment]
In addition to this, I feel like there should be a separate command such as /rob where you would get all your money taken off of you in addition to looking in their pockets.

I also feel like for more immersion when you start to steal from someone an animation should play of you sticking them up with a gun and robbing them for a few seconds.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
