### ISSUE TITLE
[jobs/?]  Vintner job

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1817]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

**_Vintner job idea_**
(I was bartender for almost 2 years at university, have a bit knowledge in this field, all ideas below are simplified to make it more rp friendly)

First of all, there should be a blip to initiate the “new order” for employees.
**1)** Start order (choosing which type of vine we would like to brew)

**2)** There are few fields around Vinery on which we need to go to harvest grapes
in result we are able to harvest various types of vine strains
**_CHARDONNAY_** (white wine)
_**MERLOT**_ (red wine)
_**PINOT NOIR**_ (pink wine)
_**PINOT GRIGIO**_ (sparkling vine)
Each field of these 4 will contain only a certain type, so there will be 4 types of grapes to harvest.
Harvested item should look the same but differs in description, for instance:
Grapes (Merlot strain), Grapes (Pinot Grigio strain)

**3)** Coming back with grapes packs
Each pack of grapes will be transformed into the final product, 1 pack = 1 wine according to its type.
From this point, we may just store wines within the wine fridge and await the orders from players OR go for local orders similar to present Burger Shot.

Vinery should be added as well to phone for order purposes.

For delivery there may be available company Burrito spawner blip, not too fast and exclusive car but immersive suits perfect the delivery purposes.
Car cannot be return if its too damaged, must be fixed first.

**Reason:**
Why would your suggestion be a good change to the framework?

Greatly enhances RP potential and fulfill vinery interior purpose with 100%,

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
