### ISSUE TITLE
[game/licenses] Licenses in game

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1818]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

License system rework idea in general is to implement major changes how licenses are distributed.
Currently our ID is **_driving license, id, gun license_**
With new system it will be distinguised into separate:

ID which can be optained in halltown as its now by any moment
Driving license which will be issued by Department of Justice in halltown building
Gun License which will be issued and distributed by SASP/DOJ (im more into SASP, by chief of police precisely)

Present lack of driving license exams are not immersive at all so it may require either implementing automated script to do quick run-and-go ride and with positive score results in passed exam. It will force people to make license for jobs that requires such and make them to respect more rules of traveling in road and land traffic.

Gun license which will be required to posses gun legaly, present system allows people to buy gun whenever they want and do not make this guy something really valuable. Gun should be be allowed to buy without license at all, and types of guns should be reduced in shop.

**Reason:**
Why would your suggestion be a good change to the framework?

Highly improve immesrive aspect of mentioned licenses, forces people to respect what they earn.

**Comment by milan60** [comment]
Would also be nice to have a Pilots license which would not only act as a license but would maybe allow people with that license to pull out certain planes in one of the hangars.

**Comment by gighul** [comment]
Yeah +1

**Comment by gighul** [comment]
![picture](https://user-images.githubusercontent.com/71882732/118303355-a2657280-b4e5-11eb-82bc-1587d64a2fba.png)
Of course everything could be just one item, something like that.
With options for mentioned institiutions to revoke license.

**Comment by rajbastakoti** [comment]
this would improve the system of every player having same card forever ,  and add rp to people and specially a tool for pd to have track of civlians
