### ISSUE TITLE
[game/items] Bean Bag shotgun

### ISSUE THREAD

**Issue by gighul** [InZidiuZ/op-framework-issue-tracker#1819]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.

Less lethal, not killing but making our character ragdoll for 5-10 seconds after reaching point of 1% HP.
Great addition to police armory fleet, would be used in certain situations that do not require deadly force, to distract the gatherings of people.
![obraz_2021-05-14_145924](https://user-images.githubusercontent.com/71882732/118274045-f3b13a00-b4c4-11eb-94ae-f13d815906c6.png)
https://es.gta5-mods.com/weapons/bean-bag-shotgun-nee__

**Reason:**
Why would your suggestion be a good change to the framework?

Alternative for police to adjust to less aggresive scenarios, more options to adjust roleplay. Good feature for prison guards perhaps?

**Comment by twooot** [comment]
Bean bag shotty was added
