### ISSUE TITLE
Bug report - Tow Driver

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-issue-tracker#182]
**Reporter:**
Soni#3614

**Summary:**
Car pops back onto the flatbed after i untow it

**Steps to Reproduce:**
Tow the car, untow it. Drive off

**Expected Results:**
Car appears back on the flatbed as i drive off

**Actual Results:**
As i am driving off it appears back on the flatbed

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
ID: 319 -Job Data: Mechanic, Los Santos Customs, Tow Driver

**Comment by InZidiuZ** [comment]
Hey,

Unable to replicate, so closing. If more information is gathered, feel free to update this issue & let me know.

**InZidiuZ**
*OP-FW Developer*
