### ISSUE TITLE
Suggestion: Make staff indestructible while spectating

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1820]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*Whenever you spectate someone you are placed below them which means that when you spectate someone who is swimming you will drown. It would be nice to be indestructible while spectating, so you don't go down and have to revive yourself.*

**Reason:**
Why would your suggestion be a good change to the framework?
*Staff is invincible while no-clipping, so it would only make sense to be invincible while spectating as well.*

**Comment by InZidiuZ** [comment]
The current spectating system is deprecated and won't be improved on at this time.
