### ISSUE TITLE
[game] Drug selling system

### ISSUE THREAD

**Issue by sQuexinho** [InZidiuZ/op-framework-issue-tracker#1821]
**Assurance:**
Yes 

**Summary:**
Hi, i think you should improve drug selling system e.g selling drug to nearbest npc and having cooldown (15 sec) and then you can sell another package also you can add different type of weed. (rudelantis,indica or other)

**Reason:**
In my opinion it will be better cause it will be more realistic and it will be much more immersive than running to spawned npc on middle of the road. Greating from Poland

**Comment by gighul** [comment]
#1814

**Comment by InZidiuZ** [comment]
Closing in favor of #1814.
