### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sheikh0** [InZidiuZ/op-framework-issue-tracker#1822]
**Assurance:**
Yes

**Summary:**
i think you should add that peds take random packets of drugs like 1 ped take 2 bag of cocaine and some ped take 1 bag and in weed some take 3 1Oz and some take 1Oz it should be randomly and set that 3 bag can max be taken by peds.

**Reason:**
Reason is there is more risk on selling drugs and take more time then previous drug selling method.

**Comment by InZidiuZ** [comment]
Closing in favor of #1814.
