### ISSUE TITLE
[game/boomboxes] Soundcloud for boomboxes

### ISSUE THREAD

**Issue by Imthebaer** [InZidiuZ/op-framework-issue-tracker#1823]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
To create a more diverse selection in platforms for the boombox
**Reason:**
Why would your suggestion be a good change to the framework?
youtube has a VERY limited library of DMCA free music for people to use and more over has a very limited music library as compared to other platforms (see soundcloud, bandcamp, Junodownlod)

**Comment by twooot** [comment]
Closed in favor of #2534
