### ISSUE TITLE
[jobs/?] Taco stuff

### ISSUE THREAD

**Issue by MalcolmFrosty** [InZidiuZ/op-framework-issue-tracker#1824]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**

_Issues:_
**Can't hear people outside from inside the window and vice versa (even when yelling)
No locks on doors** 

_Improvements needed:_
**Redo interior
Make Taco Truck a job vehicle (remove from PDM)**

_Redo/add menu options that can only be bought at taco farmer (see below)_
    **Real churros
    burritos
    nachos
    horchata
    fried ice cream
    quesadilla**

_deliveries both on the phone in favorites and local_
    **For local- may need ingredients**

**Reason:**
Why would your suggestion be a good change to the framework?

 _These changes will make the Taco Farmer able to be used as a business, it will also bring better RP / Food options for Los Santos. Taco Farmer workers will have something to do besides collecting paychecks. If Taco Farmer had a delivery option or was open at all, people would be able to get food even if Burger shot / Bean Machine didn't have any staff online. Currently anyone can steal / buy a Taco truck and pose as a Taco vendor even though the truck has Taco Farmer logos on it. Make Taco truck a job vehicle to improve RP._

**Comment by deviousrabbit** [comment]
Also, add Taco farmer to the GPS on the map.
Maybe even some Margaritas and Mexican hot chocolate

**Comment by Djmeowzle** [comment]
A fix to the windows, GPS marker, and maybe a Contact on the phone would start getting this place going!

**Comment by vlaskgar** [comment]
That taco truck is fun to see. When it shows up, it's a party. Taco Farmer deserves some love.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
