### ISSUE TITLE
[vehicles/garages] Add A Garage At Airport ( Aviation RP)  

### ISSUE THREAD

**Issue by Ashraf2112** [InZidiuZ/op-framework-issue-tracker#1825]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
We are waiting for a while now for the Aviation RP and we know that there are many roles for it already. To start the RP we need a good spaced garage at the Airport where we can take out our Heli/Private Planes. This would allow us to do the RP & The Garage would make it happen. 

**Reason:**
Why would your suggestion be a good change to the framework?
This will allow us to teach people how to fly and experience a different roleplay along the way. This Garage will allow people to park their Heli & increase RP. 

For Example: The Garage Could be here https://prnt.sc/12z8qf1

**Comment by GloriousMaruf** [comment]
Good Idea.

**Comment by mdmostofa87** [comment]
agree with it

**Comment by mdmostofa87** [comment]
aviation garage + boat garage. we will go fishing with our own boat

**Comment by ILLEG4L-creator** [comment]
Good Idea

**Comment by twooot** [comment]
Done. I added a garage that is bound to the licenses. So you need to have one of the licenses to see the garage and be able to pull out vehicles there
