### ISSUE TITLE
Weazel news hotline doesn't work 

### ISSUE THREAD

**Issue by azpranto** [InZidiuZ/op-framework-issue-tracker#1827]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/AssassinZ_2077

**Summary:**
Write a short summary of what you are experiencing.
In last update, we got a hotline of weazel news in phone. But that doesn't work for news reporters. If anyone sends any message in WN hotline, no reporter get that message.
I have tested it so many times, didn't get any result.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue. Should fix that hotline

**Expected Results:**
What are the expected results? All reporters will get messages from all civilians in weazel news hotline. 

**Actual Results:**
What are the actual results? Reporters don't get any messages from civilians

## Additional Information
Video: https://cdn.discordapp.com/attachments/777722318159347712/841654830254391366/Untitled_2_720p.mp4

**Screenshots:**
If suitable, include some screenshots. It doesn't need SS.

**Game Resolution:**
What is your game's resolution? 1600×900

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted. I have "journalist, weazel news reporter" in "/info"

**Server:**
What server/community did this issue occur in? Tested in legacy Bangladesh and test server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
