### ISSUE TITLE
[?] ?

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#1828]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
add spawn points /Buying point for the new jobs vehicles(Tow Trucks / Burgershot Van/Weazel News vehicles) 

**Reason:**
Why would your suggestion be a good change to the framework?
as these vehicles are already added to server on last asset merge but the spawn points for these vehicles were not created .

**Comment by ayushpandit99** [comment]
please create buy points for the burgers shot van  and mechanic tow trucks as the weazel news vehicles are added but these are left

**Comment by InZidiuZ** [comment]
This has since been done.

**Comment by ayushpandit99** [comment]
i have just checked in the test server the "Spawn Points for " Tow Trucks: 20rambc and towcustom" are not yet added
![20210710163841_1](https://user-images.githubusercontent.com/68945345/125161021-8573b580-e19d-11eb-9d80-05377e81fa22.jpg)
