### ISSUE TITLE
Add flashlight

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#183]
**Name:**
SteezyRen#2828

**Summary:**
Cause why not lol
But let's put the flashlight in the tool shop so we can see in the dark.

**Reason:**
I'm trying to play flashlight tag :P

**Comment by InZidiuZ** [comment]
Hey,

I've added a flashlight to the tool store.

**InZidiuZ**
*OP-FW Developer*
