### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MR-Sallu** [InZidiuZ/op-framework-issue-tracker#1830]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-yes
**Player Identification:**
What is your steam profile?
-https://steamcommunity.com/profiles/76561199112520972
**Summary:**
Write a short summary of what you are experiencing.
-We havebeen Facing a Problem.Everytime we steal the gold truck the lockpick option doesn't appear at the backside.Even if theres enough polices on duty.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
-we are expecting that might fixed as soon as possible

**Expected Results:**
What are the expected results?
-The lockpick option at the backside should appear.

**Comment by InZidiuZ** [comment]
Can you provide video of this issue?

**Comment by InZidiuZ** [comment]
Closing due to no response.
