### ISSUE TITLE
[?] Groom & Growls RX – Veterinary Business

### ISSUE THREAD

**Issue by XinarTheNeko** [InZidiuZ/op-framework-issue-tracker#1831]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes - Neko (XinarTheNeko)#1904 & MsRaynie#6740

**Summary:**
Write a summary of what your suggestion is about.
Groom & Growls RX would partner with Los Santos in an effort to provide much needed veterinary services at a centralized location, as well as grooming and other specialized pet care services for animals of the city.

For this business we would need some help from the constructors for location and specialized items to enhance the role play possibilities and ability to provide sufficient services fit for a Veterinarian and grooming service.

Location:
Work with the State Real Estate department to source an appropriate facility with room for medical, grooming, and boarding needs.  Would also like an area for a lounge so that pet owners can chat while waiting for their pets! Here is some of what we think we need:
1. ATM
2. Water dispenser 
3. Medical beds lowered to the ground (To avoid pet damage when leaving the bed)
4. Reception with store for special items + necessities for the animals
5. Grooming area + Medical area + Lounge / hang out area
6. Storage / locker room / clothing change spot
7. Lockable doors separating work / service space from hang out space
8. More precise plans, thoughts can be provided when we know location/ building possibilities

Items:
We wish to be able to provide services suited for animals as well enhance their rp. To do that we wish for a storefront with some existing essential items as well specialized exclusive items for the animals.
1. Exclusive items include the creation of animal food and stress relief items (Stress ball?) (Maybe even with difference of flavor; Meat & Vegetarian)
2. Existing items that is essentials for animals to stay in the city. Example: Med kits, water, phone (animal tracker), compass ect
3. Little thought, but a re-skin of the bag as a cone that still allows the animal to see when walking, to show a animal has recently been to treatment, like humans sometimes get wheelchair

**Reason:**
Why would your suggestion be a good change to the framework?
Having been in the city about a month now something that was quickly noticed was the difficulties for animals. That include bout infrastructure and how they are treated. All from official workers within police, medical and civilian don't always respect and treat our animals citizens on equal line of humans. As well there is no infrastructure with thought of animals available in the city, too tall hospital beds with danger of repeated injuries and food that can be damaging for an animals health. So we think its time for a service that puts the animals not higher but as an equal to humans, both inside and out!

https://docs.google.com/document/d/1OXui-VNrNQggy9vdycaGMD3aaumS1wcQnEzCuTyEXtg/edit?usp=sharing

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
