### ISSUE TITLE
[base/admin] /tp for staff

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1832]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*As staff sometimes you have to noclip around the city and quite often, your game will crash. It would be nice to be able to mark a position on the map and be able to teleport there via some sort of command (like /tp).*

**Reason:**
Why would your suggestion be a good change to the framework?
*Prevent game crashes for staff in a staff situation*

**Comment by InZidiuZ** [comment]
This has now been done.
