### ISSUE TITLE
[?] Roger's Salvage and Scrap Renovation. 

### ISSUE THREAD

**Issue by MafieCoding** [InZidiuZ/op-framework-issue-tracker#1833]
Yes, the Read.me has been read  

Summary: 

The following is a suggestion/request for a business at the Roger's Salvage and Scrap location in La Puerta. Will attach a video tour of the location that explains the requests and how we have envisioned the business to look and run. As a company, we know that not all requests may be possible, and that some may need to be negotiated and adjusted to fit both the framework and the city needs. 

Roger's Salvage and Scrap business plan needs. 

The ability to process the following items, and any others deemed reasonable by the city. 

	- Tools and melee weapons (Crowbar, knives, Drills Etc)

	- Paper Bags

Our vision is that these items can be processed at the plant, with the result being a chance at a random piece of material. Similar to the chance during the diving. 
I.E. : Worker processed a crowbar, the crowbar was destroyed, the employee then received a piece of scrap metal. 

Roger's Salvage and Scrap location renovation plans. 

Reception area:

Vending machine to be added next to the water cooler that is already on site. 

Node for the residents/customers to be able to sell recyclable items to the business when no attendant is on duty. 

Better lighting. 

Employee Hallway:

Employee storage lockers. 

Employee outfit changing location. 

Vending machine to be added next to the water cooler that is already on site. 

Doors leading from the hallway into the next room to be either removed or fixed to actually work. They currently need to be kicked down. 

Processing Room:

Node for employees to be able to process the items they gather or purchase from residents. 

Area at the top of the machine has a visual bug where other residents become invisible to the eyes of others.

Lockable doors throughout the entire interior of the plant. 

https://www.twitch.tv/mafie/v/1028917706?sr=a&t=345s

Reason: 

This suggestion will allow the city to breathe some life back into the items that have become nothing more than throw away trash for most residents, while also creating a new job and RP scenario. By allowing the residents to be able to sell these items to the plant, you offer new engagement, new income potential, and just more dynamic life. Also the location of the buisness is in an area rarely traveled, getting the residents to explore a new or unknown location. 

There is also potential for future business deals between the plant and repair shops, PD, and warehouse!

**Comment by DaxterPancake** [comment]
This looks great but you need to follow the layout provided for you. 

Either edit this or I will close it and you will have to remake it.

Cheers,
Daxter.
Project Manager.

**Comment by MafieCoding** [comment]
Will edit in a few minutes when back at my PC

**Comment by DaxterPancake** [comment]
I love this idea, I also love the little video you have provided for us.

I actually was thinking of an idea like this recently and created a spreadsheet that listed the output the 'recycle machine' would spit out once you've recycled it.

[Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1kLTJf6vo6B465Zwi9ycGW4ORIn6uzdPtpiJ52s4Aqf4/edit?usp=sharing)

All prices made sure you were never getting back more than the item is worth and also accounts for the possibility of old items coming back into the city.

**Comment by MafieCoding** [comment]
> I love this idea, I also love the little video you have provided for us.
> 
> I actually was thinking of an idea like this recently and created a spreadsheet that listed the output the 'recycle machine' would spit out once you've recycled it.
> 
> [Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1kLTJf6vo6B465Zwi9ycGW4ORIn6uzdPtpiJ52s4Aqf4/edit?usp=sharing)
> 
> All prices made sure you were never getting back more than the item is worth and also accounts for the possibility of old items coming back into the city.

This spreadsheet is absolutely fantastic!

**Comment by MafieCoding** [comment]
Is this something that is possible, I would like to get started on advertising and such if this is gonna happen.

**Comment by DaxterPancake** [comment]
We can't give you an exact date as to when this is going to happen. You will have to be patient.

**Comment by MafieCoding** [comment]
I understand, did not want to seem impatient. Just something I am excited for, and look forward to the possibility of it happening. If you have anything you need from me, I'm available most hours of the day.

**Comment by rajbastakoti** [comment]
excited to have this ! , this would bring a new aspect into how the items are kept or collected currently and just kept as a junk occupying inventory space over usage

**Comment by DaxterPancake** [comment]
This is one of the reasons why this system or a selling system is needed for the city. I checked a lot of these spots and they were mostly melee weapons and device scanners.

![image](https://user-images.githubusercontent.com/50828532/119785318-7220c980-bf12-11eb-81d7-7d88f4bb8c1b.png)

**Comment by MafieCoding** [comment]
> This is one of the reasons why this system or a selling system is needed for the city. I checked a lot of these spots and they were mostly melee weapons and device scanners.
> 
> ![image](https://user-images.githubusercontent.com/50828532/119785318-7220c980-bf12-11eb-81d7-7d88f4bb8c1b.png)

Absolutely one of our main target locations!

**Comment by MafieCoding** [comment]
With the extended population in the city, I feel that the implementing of this would help to limit the ground clutter in the city tremendously. Especially with the continues increase in the popularity of scuba diving. 

I do not know much about coding and framework, but the large amount of items sitting around cannot be healthy for the city's stability at peak times.

**Comment by MafieCoding** [comment]
Was wondering if there has been any further discussion or insights on this topic.

**Comment by antihero6713** [comment]
It's on my list of to do. At least art wise.

**Comment by MafieCoding** [comment]
Oh, that is exciting. Feel free to email me if you want to talk about any of it. Mafie#5389.

**Comment by twooot** [comment]
I added the ability to melt down/scrap certain items and get materials in return

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
