### ISSUE TITLE
Steam: https://steamcommunity.com/profiles/76561197993789770/ I have a Michaels Mansion on Steele Way 5 and every time we try to decorate it our heads pop when we try to enter. Once we get back into the city it's fine until we drive away from it and come back. We have gone through the process of changing out the items we are putting in there and reverted it back several different times.

### ISSUE THREAD

**Issue by kaetarian** [InZidiuZ/op-framework-issue-tracker#1836]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Closing due to not using the template provided. 

Remake this and ensure you're filling in the sections in the actual issue with as much information, screenshots, etc.

Cheers,
Daxter.
Project Manager.
