### ISSUE TITLE
EMS suggestions and some others. 

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#184]
**Name:**
Who is suggesting this? Please include discord name.
AmokBSN#3856
**Summary:**
Write a short summary of what your suggestion is about.

1. EMS needs some kind of 'off road' vehicle, this is to combat injuries often located in hard to reach locations as the current damages quickly and bulky for offroad, not everyone has helicopter training. 

2. Apartments next to Pillbox or close, I understand that some bugs are being worked on at the moment with 'real-estate' however this would be ideal for EMT when off duty to quickly store/get equipment and enter duty. 

3. A screen on the phone to see if any Mechanics/Lawyers/Taxi's are 'on-duty' perhaps under a 'services' section on the phone. This will only be updated when they physically enter duty and be removed when exiting duty. 

4. /bed ability for EMS so we can place patients vertically on a hospital bed with relative ease. 

**Reason:**
Why would your suggestion be a good addition to Legacy?

1. Would be monitored by MTP members and drafted into the SOP if required nothing fast or flashy but just something that's able to have the horsepower to climb hills/steep terrain with ease. 

2. Will increase the number of apartments at 'pink cage' and offer an alternative solution for EMT getting on duty quickly (or for others), I understand there's a spawn very close at the Bus Station. 

3. We will be able to see who is RPing as what particular job and have a number to call if needed when they are officially on duty, this means that when you text a Mechanic, for example, four don't show up all at once 'fighting' over one job.

4. Will increase RP as patients will look more naturally orientated on a hospital bed rather than hanging off the side or requiring loads of re-adjustments.

**Comment by AmokBSN** [comment]
Never noticed that Steezy had also suggested the services on the phone and a number

**Comment by InZidiuZ** [comment]
Hey,

In the future, please create one issue for each suggestion.

1. This will not be added at this time.
2. This will not be added at this time.
3. This will not be added at this time.
4. I suppose this is no longer relevant with the new injury and doctor system.

**InZidiuZ**
*OP-FW Developer*
