### ISSUE TITLE
[game/inventory] Removing public access to bar shops and food shops

### ISSUE THREAD

**Issue by c-ef** [InZidiuZ/op-framework-issue-tracker#1840]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Removing public access to bar shops and food shops limiting the access to the correct business employees.

**Reason:**
This will help promote roleplay and encourage workers to work. Currently at the moment anyone can walk into Burger Shot and grab food from the counter. This should be changed so that a worker has to serve them their food. This is the same with Bars and Clubs.

Whilst doing the above I think it would be fantastic to also raise the price of store bought food to give incentive for people to use restaurants as their main source of food.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
