### ISSUE TITLE
[jobs/*] Los Santos Aviation Job

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1841]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Jobs to support roleplay and vehicle spawner at the airport. (see #1825 )

```
["LSA"] = {
		["Employee"] = {
			["Student"] = {salary = 30},
			["Pilot"] = {salary = 40},
			["Manager"] = {salary = 50},
			["Director"] = {salary = 70}
		}
	},

```
**Reason:**
Why would your suggestion be a good change to the framework?
Support current systems and future systems related to aviation.

**Comment by Saszkaxd** [comment]
This is very good idea, but salary should be higher, for example Director should be 120, Manager 85, Pilot 50 and student shouldn't have a paid job.

**Comment by Nuziatella** [comment]
> This is very good idea, but salary should be higher, for example Director should be 120, Manager 85, Pilot 50 and student shouldn't have a paid job.

No. The pays are based of other pays with equivalent roleplay value.

**Comment by Saszkaxd** [comment]
> > This is very good idea, but salary should be higher, for example Director should be 120, Manager 85, Pilot 50 and student shouldn't have a paid job.
> 
> No. The pays are based of other pays with equivalent roleplay value. 

Yee but PDM Boss earns 112 dollars and that will be more realistic beacues this is fly school and pdm is car dealer ship

**Comment by Nuziatella** [comment]
> > > This is very good idea, but salary should be higher, for example Director should be 120, Manager 85, Pilot 50 and student shouldn't have a paid job.
> > 
> > 
> > No. The pays are based of other pays with equivalent roleplay value.
> 
> Yee but PDM Boss earns 112 dollars and that will be more realistic beacues this is fly school and pdm is car dealer ship

PDM is a business that is required for the overall function of an RP server. An airport is not. The pays that are recommended are balanced against other roles that are enriching but are not required.

**Comment by Saszkaxd** [comment]
I think best option will be to let a player managing airport like PDM.

**Comment by DaxterPancake** [comment]
If the Aviation job paid so high then everyone would join it NOT because they want to RP being a pilot, but because they'll get more money. It does not need to be higher than Nuzi has suggested.

**Comment by Saszkaxd** [comment]
But that would be job that can only given by administrator, and that will be fair then

**Comment by DaxterPancake** [comment]
Almost all high paying jobs are given by the admins. That will stop nothing, unfortunately. 
I understand that in real life a pilot would be paid a lot, but in a roleplay server it just wouldn't work due to people caring more about their fake money than RP.

**Comment by Saszkaxd** [comment]
But if someone make ticket to manage an pilot school and administration will accept that, then someone can took that job, but that person should train people how to fly.

**Comment by DaxterPancake** [comment]
I think you're going way off topic now.

The job should be a thing. 
The high paychecks you are suggestion should not.

**Comment by Spitfire2k6** [comment]
@Saszkaxd I think you should reconsider what's important here. Money should never what incentivises people. 
If people want this job for the pay check they're doing it for the wrong reasons.

**Comment by Nuziatella** [comment]
This has been completed.
