### ISSUE TITLE
Bug report/dying everytime when entering house

### ISSUE THREAD

**Issue by robin-401** [InZidiuZ/op-framework-issue-tracker#1842]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-yes
**Player Identification:**
What is your steam profile?
-https://steamcommunity.com/id/zZFancyZz/
**Summary:**
Write a short summary of what you are experiencing.
-when i spawn at my house i'm dying , after spawning dont know why.This happened to me back to back 3times.If i spawn somewhere else and then enter into my house that problem also happens.Also some of my friends facing the same issue.The houses was brogue ave 3 and grapseed street 3This problem happens sometimes and sometimes i successfully spawn at my house without dying.Dont know its my problem or others.I just need a fix of this problem.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
-Give me some solution so that i can get rid of these.
**Expected Results:**
What are the expected results?
-i should  successfully spawn at every house
**Actual Results:**
What are the actual results?
-dying when spawning at house
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
-https://imgur.com/a/Y2RC9R0
**Game Resolution:**
What is your game's resolution?
-1366x768
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
-Legacy rp Bangladesh subdivision
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Can you provide video of this? What did you do before it happened? Were you dead when you disconnected?

**Comment by InZidiuZ** [comment]
Closing due to no response.
