### ISSUE TITLE
[jobs/ems] EMS Driver

### ISSUE THREAD

**Issue by TheButcherJ** [InZidiuZ/op-framework-issue-tracker#1843]
**Assurance:**
Yes

**Summary:**
So this may be a opinionated suggestion, but I think there should be more incentive for people to pick up people on EMS calls versus being a doctor. I can see a lot of people prefer doctor duty because you make money fixing wounds. If it was something like trash where you go a certain distance and pick up individuals and are rewarded for doing so I think it may be a nice improvement. 

**Reason:**
It would add a nice variety to EMS allowing for other ways of revenue.

**Comment by DaxterPancake** [comment]
Shouldn't your incentive be saving a life.. You already get paid a higher paycheck than regular non-whitelisted jobs.
At the end of the day, you shouldn't be being a doctor because you get more money. You should be doing it for the RP, just like Paramedics.

**Comment by ainstaylor** [comment]
Perhaps we introduce a lower paycheck in EMS for 'Nurses' so people who just want to do doctor duty take a slightly lower paycheck but it is buffed up by the money earnt by treating patients whilst on doctor duty. Currently on the NA/EU server we do seem to have a lot of people who only do strictly doctor duty.

**Comment by cammyyeet** [comment]
EMS are already paid enough. If you want to give incentive for paramedics, remove the tips you get from doctor duty, they really don't give you that much anyway. (If this was to happen I doubt there would be a change, people do doctor duty because they enjoy it. 9 times out of 10 it's for the roleplay or due to someone preferring that role.

**Comment by TheButcherJ** [comment]
@DaxterPancake The incentive of EMS is to save lives that's obvious. The fact is some people prefer to do doctor duty for the financial gain like it or not. I should add that it is not a bad thing at all! Having on duty doctors are GREAT for the RP of everyone. I'm all for keeping it how it is; I thought this might be a better way to incentive driving the same way doctor duty is.

**Comment by twooot** [comment]
Like it was said above, EMS is already a pretty highly paid job. There shouldn't be extra monetary rewards for saving people. That's like adding monetary rewards to arrests for PD.
