### ISSUE TITLE
[illegal/corner] Drug selling rework until something major changes

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1844]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Summary:**
Write a summary of what your suggestion is about.
Change to Selling Drugs so that you can use a dirtbike or motorcycles as well as bicycles.

**Reason:**
Why would your suggestion be a good change to the framework?
This change would be good for the framework because I feel as if selling drugs could be a little better and incentivize people to do it by allowing motorcycles and dirt bikes. One, these vehicles are not as common to see as people driving them around this would give a use to driving a motorcycle or dirt bike.

**Comment by DaxterPancake** [comment]
If we were going to re-introduce dirtbikes and motorcycles back into it then we might aswell re-introduce cars in general. No one will use bicycles unless they are RPing, everyone will pick the fastest street bikes which we already know are an extreme advantage against cops.

**Comment by iGreatWhite** [comment]
True, I just feel like something with this system is kind of eh and can be fixed. I can't point it out yet still thinking, I just thought bikes was a good idea.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
