### ISSUE TITLE
Scuba Tank Disappearance 

### ISSUE THREAD

**Issue by srinac** [InZidiuZ/op-framework-issue-tracker#1845]
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198078124617/

**Summary:**
Scuba Tank disappears if you try to equip while jumping off a jet ski.

**Steps to Reproduce:**
Get a scuba tank
Get on a jet ski
As jumping off, equip scuba tank
Scuba tank disappears and doesn't equip

**Actual Results:**
No scuba tank equipped
## Additional Information

Video proof:
https://www.twitch.tv/videos/1036796611
1:27:45

**Game Resolution:**
2560x1440

**Player Data:**
https://imgur.com/a/pl7BChE

**Server:**
LegacyRP

**Comment by Nuziatella** [comment]
This isn't a bug. You can't equip a scuba tank while jumping off a jet ski. Equip it before you get on the jet ski or equip it before jumping off.

**Comment by srinac** [comment]
> This isn't a bug. You can't equip a scuba tank while jumping off a jet ski. Equip it before you get on the jet ski or equip it before jumping off.

okay I was unaware and it seemed to be a bug but thank you.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
