### ISSUE TITLE
Windows in jail dosen't have colisions

### ISSUE THREAD

**Issue by Saszkaxd** [InZidiuZ/op-framework-issue-tracker#1846]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Saszkur/

**Summary:**
Write a short summary of what you are experiencing.
Windows and doors in jail dosen't have colision

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Just step on window in ambulatory, I link video to this issue.

**Expected Results:**
What are the expected results?
Add colision to windows and doors in jail

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://youtu.be/6nolZCY9aaU

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
I don't have this information, it's from other player

**Server:**
What server/community did this issue occur in?
Legacy Roleplay Poland

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is an issue for the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
