### ISSUE TITLE
[game/evidence] Extended Evidence System

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1847]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Rewrite/Expand the evidence system to allow for different types of evidence to have more in depth evidence gathering.

Evidence types:
**Fingerprints** - If the suspect is not wearing gloves then they leave fingerprints on steering wheels, handles of doors they are robbing, weapons they have used, etc.
**Blood DNA** - When someone is injured in any way, they bleed. This blood falls onto the ground and then police can collect this evidence.
**Hair/Skin DNA** - Goes hand in hand with Blood DNA but instead, the shooter or attacker has a chance to leave small traces of DNA on the scene (this might be OP, would need to be a decently small chance UNLESS they have also been injured then their DNA would be on scene anyway).
**Bullet Casings** - They would work how they do now.
**Bullet Impacts** - They would work how they do now.

In order to gather fingerprints, blood, hair/skin you would need to search an area with a flashlight (or camera if it was added) and it would visually display like the current bullet impacts and casings do. In order to pick up that evidence we would need evidence bags AND a crime scene investigation kit.

If criminals wanted to clean scenes they would have to have a cleaning kit on them. They could use a flashlight to find evidence and use the cleaning kit on it to get rid of evidence. 

Bullet Impacts and Bullet Casings would remain the same though they would need the Alter Casing function fixed.

[Here](https://forum.cfx.re/t/esx-core-evidence-updated-v2-bullet-shells-fingerprints-blood-samples-archives-paid/2041245) is a script that already has a few of the features I am talking about.

**Reason:**
Why would your suggestion be a good change to the framework?
A lot of people are bringing new and interesting roleplay into the city, this includes serial killers and gang crimes. Unless people decide to leave evidence behind on notes that police can find and then investigate, then the only way we can follow up on evidence is to take casings and hope that we catch someone with that weapon on them. Either that or getting a warrant for their phone number or twitter account (which in my opinion ends the RP extremely quickly, which is why we don't do it). I believe that this addition would add a new and extremely fun aspect into the city and increase the realism.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
