### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ILLEG4L-creator** [InZidiuZ/op-framework-issue-tracker#1848]
**Assurance:**
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561199112810047/

**Summary:**
I can not connect to the voice server from last 4/5 days. It is not connecting to any regional server or main sever of Legacy.

**Steps to Reproduce:**
I tried uninstall and reinstall fivem
I tried changing my ISP also. 

**Expected Results:**
It should be connect with the Voice server.

**Actual Results:**
It is still not connecting.

## Additional Information
I could connect the voice server two time after the issue started. But It was for a few minute.

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
720P

**Player Data:**
I attached this to the report attachment.

**Server:**
Legacy Roleplay Bangladesh 
Legacy Roleplay

**Notes:**
I was happened that day when the Carry glitch and Bank glitch was happened. I don't know may be It will be helpful to you.
![20210529224523_1](https://user-images.githubusercontent.com/83420086/120078473-91198a00-c0d1-11eb-8938-b0eaf0ef29cd.jpg)
![20210529225639_1](https://user-images.githubusercontent.com/83420086/120078474-92e34d80-c0d1-11eb-9cb6-a40aba778efa.jpg)

**Comment by InZidiuZ** [comment]
This is not a framework issue.
