### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Qaisahmed72** [InZidiuZ/op-framework-issue-tracker#185]
**Name:**
Qais#2007

**Summary:**
Finding a way for multiplayer preset characters to wear masks/wear different clothing.

**Reason:**
So everyone can RP equally, just because you chose to be a preset character shouldn't mean you cant wear a mask or change your clothing as you please (if possible of course)

**Comment by InZidiuZ** [comment]
Hey,

Unfortunately the "NPC" peds don't have this capability, and probably won't be creating some funky workaround for this anytime soon, so closing. If you wish to be able to wear a mask, either find a model which has some available, or use the freemode models as they have tons of options.

**InZidiuZ**
*OP-FW Developer*
