### ISSUE TITLE
Suggestion: EMS Barrier props

### ISSUE THREAD

**Issue by xplrkai** [InZidiuZ/op-framework-issue-tracker#1850]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes.

**Summary:**
Write a summary of what your suggestion is about.

Just a simple barrier/prop system similar to the PD function but for the EMS

**Reason:**
Why would your suggestion be a good change to the framework?

It'll be good to close off roads and accidents, hopefully, it will also stop the locals from going crazy and hitting other vehicles/people

**Comment by InZidiuZ** [comment]
This has now been added.
