### ISSUE TITLE
[game/inventory] Food Update for the Comedy Club 

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#1851]
Dusty Carrr / claystehling#4598

I wanted to see if it was possible to have some new food items added for the Comedy Club. I wanted to sell Popcorn, Ice cream(Milkshakes are fine), and nachos with jalapenos. Each of these would have an added bonus to eating them. The Popcorn would make you interact with things quick because when you eat popcorn you just want to eat more, and more as well as making you more thirsty. The ice cream would relieve your stress because who doesn't calm down when they are eating ice cream. The nachos with the jalapenos would make you run quicker because of the overwhelming spice.

I think this would be a great addition to Legacy as these items are not in the city currently which would provide a diversity of food for the people inside. As well the effects that come from eating the food would be beneficial to the entire City in a variety of ways. Being able to run faster would benefit both the regular citizens and the cops. The ice cream would allow everyone to to destress other than having to do yoga, smoke a joint or go to bean machine, the popcorn would allow for everyone to work quicker regardless of the jobs. It would allow cops to equip armor quicker, tow truck drivers to tow quicker, mechanics to fix cars quicker, you could fill up your gas quicker. It would offer a lot of new RP interactions with the Comedy Club and the citizens as well.

**Comment by nazarddablazard** [comment]
the city definitely needs this!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
