### ISSUE TITLE
[weapons/ammo] Creating somewhere for ammo to go. 

### ISSUE THREAD

**Issue by Jmolstad** [InZidiuZ/op-framework-issue-tracker#1852]
**Assurance:**
Yes

**Summary:**
Rifle and sub ammo seem to come in surplus when doing trash or robbing houses. The sub is easier to get rid of/use. However the rifle ammo only seems to be needed during gang wars that we have been seeing less and less off. 

In my opinion, it would be really cool if there was a black market arms deal NPC who stayed in one location or every so often moved to different ones. 

You could walk to him and see his inventory and buy or sell to him. Now the cool part could be he never has just anything, his inventory would only consist of what actual players have went and sold to him. So that way it doesn't break the game. 

So if I had 50 rifle ammo I could go sell it all to him and now his inventory consist of 50 rifle ammo. 

Players could sell guns to him to make money along with ammo and his purchase-able inventory would only be backed by what players choose to sell to him. Making a higher market for scratched serial number guns as well. 

**Reason:**

I believe this would be a great asset to the city as it would allow for players to make a little more money on the ammo and encourage some higher level moments in the RP scene. Encourage more gang related interaction and even allow the gangs to have a source of ammo.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
