### ISSUE TITLE
[jobs/news] Spawn location for weazel news vehicles

### ISSUE THREAD

**Issue by azpranto** [InZidiuZ/op-framework-issue-tracker#1853]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
A month ago, I submitted a issue about adding some weazel news vehicles. So, you did accordingly. But you hadn't set a spawn location for those. 

**Reason:**
Why would your suggestion be a good change to the framework?
As the vehicles are already added to the game, it is useless if you don't set a spawn location. New recruits are eagerly waiting for it.

**Comment by Nuziatella** [comment]
This has been added.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
