### ISSUE TITLE
[game/inventory] EMS Store Items

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1854]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Looking to add additional items to the EMS store such as Food items, Drinks, Body Armor.

**Reason:**
Why would your suggestion be a good change to the framework?
Working in EMS for a few months you get tired of eating the same sandwiches and drinking plain water all the time. I am look to add more variety food options that we can eat/drink along with some stress relievers as well.  I am also looking to add EMS Body Armor into the store due to the only way we can replenish our body armor on shift is going all the way down to the hardware store to buy more or to clock off duty and then back on.  I know we don't get into gun fights but locals tend to run us over quite often and it runs out.  The body armor will also help when we implement the Tactical Medical Unit in the near future.  We would also like to see regular first aid kits put into the store so we can buy them quick to hand to the citizens of the city.  There are times where we are running constantly and are unable to stop at a store to pick them up since they are unable to use EMS bandages.

**Comment by twooot** [comment]
I gave you pigeon milk and wonder waffles instead of sandwiches and water. Now the EMS job has the same food items as PD. Body armor is not a thing i will be adding to the EMS store as body armor should not be something EMS should need on a regular basis.
