### ISSUE TITLE
[jobs/?] create cook job 

### ISSUE THREAD

**Issue by vlaskgar** [InZidiuZ/op-framework-issue-tracker#1855]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Create a new cook profession for the food establishments in the city with a food crafting system

**Reason:**
Why would your suggestion be a good change to the framework?
This will make existing jobs at food establishments relevant and immersive while creating new jobs and more player interactions
[LegacyRP cook role.pdf](https://github.com/InZidiuZ/op-framework-issue-tracker/files/6572044/LegacyRP.cook.role.pdf)

**Comment by claymstehling** [comment]
Hi! As the Comedy Club owner, I would LOVE THIS! It would make the immersion that much better

**Comment by vlaskgar** [comment]
That’s awfully generous of you. Feel free to add suggestions. My outline is a first draft.

**Comment by claymstehling** [comment]
yeah! I think even adding more functionality to bartender as well. The ability to mix drinks together and server them as a cocktail would be nice as well!

**Comment by nunsia** [comment]
I think this would be a great addition to Burger Shot too :)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
