### ISSUE TITLE
[game/clothing] Clothing menu rework

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1856]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**YES**

**Summary:**

- Ability to identify selections in clothing menu.
- Changing of camera angle to show pants/shoes better when selecting those items.
- Faster way to move through menu.
- order clothing in a way that it does not get changed when new items are pushed.

**Reason:**
I feel like the current clothing menu is slow to use as you can not move quickly through the options. The ability to identify your selection with an ID in the slider would be helpful for sharing outfit selections with people. 
When choosing pants and shoes you're forced to do an emote to try and see the selection better and it can be hard for newer players to get used it. it's also not a great solution.
When new clothing items are added the ordering gets changed and peoples outfits get messed up. Would it be possible to change this?

**Comment by Smach90** [comment]
Please please please please this 100x!

**Comment by riedling11** [comment]
this would GREATLY enhance the player experience!

**Comment by claymstehling** [comment]
YES PLEASE

**Comment by iGreatWhite** [comment]
The issue that I think most of us players see with the current clothing system. You have to spam left and right arrow to look through the clothes and there is no indication on what clothing item number you are looking at. 

The few things that I think people would love to see to a rework:
- Being able to type in a number and instantly go to that clothing option
- Being able to hold left or right arrow key and scroll through clothes automatically.
- Option to have a view model of your lower body to apply pants and shoes and see them better.
- Also being able to see where in the clothes you are.

**Comment by 8017RAZ** [comment]
that's  a nice Idea

**Comment by twooot** [comment]
### A few things

**Ability to identify selections in clothing menu.**
*I went ahead and added an "ID" parameter, showing which clothing you have selected.*

**Changing of camera angle to show pants/shoes better when selecting those items.**
*I added locked camera angles that make it easy to edit shoes, pants, etc.*

**Faster way to move through menu.**
*Do you have anything in particular in mind*

**Order clothing in a way that it does not get changed when new items are pushed.**
*After speaking to the asset devs, this is not something that is possible.*

@Spitfire2k6

**Comment by Spitfire2k6** [comment]
Hold shift to move 10 at a time?

**Comment by keridwn** [comment]
Or even be able to hold down the arrow key instead of having to spam it to go through the clothes.

**Comment by claymstehling** [comment]
> Or even be able to hold down the arrow key instead of having to spam it to go through the clothes.

I agree with this, would be so nice to just be able to hold.

since you did add ID's you can also just make them enterable as well
