### ISSUE TITLE
[game/radio_stations] Radio Stations

### ISSUE THREAD

**Issue by Spencer10798** [InZidiuZ/op-framework-issue-tracker#1857]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
A whitelisted radio host job where the employee can play music on a radio channel how someone may play music on a boombox. 

The addition of a 1-way radio transmitter that allows the user to broadcast their voice or play music on some channel

The addition of a 1-way radio receiver that allows the user to tune in to a specific radio frequency. This range of frequencies could be different from the traditional radios to prevent eavesdropping, or it could the same to enable it.

The transmitter could be a static object like in a radio station, and the receiver could be a simple item like a walkman or ipod.

**Reason:**
I think that RP in the city could benefit greatly from IC radio stations. Whether it's a music station run by some friends or the official news update station from Weazel News, I think people in the city would enjoy and engage with the radio stations.

**Comment by vlaskgar** [comment]
Maybe use one of the car radio stations as the broadcast channel?

**Comment by Spencer10798** [comment]
> Maybe use one of the car radio stations as the broadcast channel?

That would be awesome to be able to take one of those slots, though I figured that we'd want a separate radio/receiver object so that it could be used outside of cars too.

**Comment by vlaskgar** [comment]
Or possibly update the boombox UI to have a radio station

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
