### ISSUE TITLE
Laptops

### ISSUE THREAD

**Issue by Spencer10798** [InZidiuZ/op-framework-issue-tracker#1858]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
The creation of a laptop item that when used presents a console like the one seen in /comp

Users can create and save 'documents' similar to how they are created with /notepad

An 'email' application could allow you to send a document to another players email, which they would have to open on their laptop

A banking application could allow you to access your bank terminal and make transfers to other accounts

Laptops could be a single object, or multiple different models priced by storage limits (5, 10, 15 documents)

**Reason:**
In addition to making the email system entirely IC, I think that it would foster different avenues of RP if laptops were a usable item. If the laptops had persistent storage it could allow for people to receive or steal laptops from others. Beyond that, it would be beneficial for legal communications in the city to have an IC medium. Over time, the laptops provide a platform for new and different applications that the may be used in the city beyond simply emails.

**Comment by Nuziatella** [comment]
Why wouldn't you use your phone and text them?
Most of these features would be available in the new phone. Having them in 2 locations would be redundant as they would serve the same functionality. 
Why would using the laptop be a better place to house these features as well compared to the phone?

**Comment by Spencer10798** [comment]
> Why wouldn't you use your phone and text them?
> Most of these features would be available in the new phone. Having them in 2 locations would be redundant as they would serve the same functionality.
> Why would using the laptop be a better place to house these features as well compared to the phone?

I guess I envisioned the main draw being a place for formal IC documents to have a place within the game. I think it would greatly help immersion if you were able to open documents in the city rather than having to exit the game to check a discord message linking you to a google doc. Although now knowing that there is another phone system being developed that will have similar functionality, I guess people would just open their phone and use that instead. Surely there are pedantic reasons why a laptop is better than a phone, but having all of that functionality in the phone is much more convenient.
