### ISSUE TITLE
EVO IX Livery

### ISSUE THREAD

**Issue by Jmolstad** [InZidiuZ/op-framework-issue-tracker#1859]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes.

**Player Identification:**
Conner Hedgespeth
OOC: Juupster#0434

**Summary:**
Bought the Evo and it came with a livery. Upon removing it in Los Santos Customs, it just keeps returning on my car every time I garage it. 

**Steps to Reproduce:**
Buy Evo, remove livery, garage it, pull it back out. 

**Expected Results:**
Livery will be still off of vehicle

**Actual Results:**
Livery is on the vehicle 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
This is an issue for [assets tracker.](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
