### ISSUE TITLE
[Suggestion] - Push Vehicle

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-issue-tracker#186]
**Name:**
Anderzenn#0069

**Summary:**
I would like to be able to push cars, either to get them out of the road or to the nearest gas station if I run out of fuel

**Reason:**
This would add realism and if you have a bad crash and your car is in the middle of the road you can push it out of the way. And if you run out of fuel you can push it to the nearest gas station.

**Other:**
Link to a possible script: https://forum.fivem.net/t/release-esx-kr-vehicle-push-push-broken-vehicles-off-the-road/284115

**Comment by SteezyRen** [comment]
I thought I posted something about this but can't seem to find it. Either way, yes :)

**Comment by InZidiuZ** [comment]
Hey,

No.

**InZidiuZ**
*OP-FW Developer*
