### ISSUE TITLE
[maps/burger_shot] Locks on kitchen doors

### ISSUE THREAD

**Issue by nunsia** [InZidiuZ/op-framework-issue-tracker#1861]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes, I have read the README.md.

**Summary:**

Burger Shot needs locks on the doors leading to the kitchen.

**Reason:**
Why would your suggestion be a good change to the framework?

The previous version of Burger Shot had locks on the doors, the new version doesn't and it would be helpful to ensure random people aren't running to the back and ruining those trying to be a chef.

**Comment by InZidiuZ** [comment]
This has now been added.
