### ISSUE TITLE
[?] Dogs can swim

### ISSUE THREAD

**Issue by EvoluTiionZzz** [InZidiuZ/op-framework-issue-tracker#1864]
**Assurance:**
Yes I have read through the read.me
**Summary:**
So i fell into a pool and instantly died i can see this being a thing for cats but dogs like water so i don't see why this is 

**Reason:**
I want this to be changed so that dogs can have fun with their owners and swim with them

**Comment by twooot** [comment]
All animals are hardcoded inside GTA V to die instantly upon contact with water. Bird for example even die on the smallest impact with the ground. Due to it being in GTA its nothing we can change
