### ISSUE TITLE
Bug report: wrong wage for role at bar

### ISSUE THREAD

**Issue by HarleyGraves** [InZidiuZ/op-framework-issue-tracker#1865]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes 

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198953790923/
**Summary:**
Write a short summary of what you are experiencing.
Recently got the role as manager for bar at tequi-la-la - public state records show hourly wage to be $54 but receiving $40.
Realised the issue as both owner, manager and bartenders are now receiving less than other venues since acquiring their roles.
Spoke to admin who could see two different wages for the same role.

Not only myself, but all employees and owner receiving wrong wage. 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Correct the wage system to match other venues within bar and clubs jobs pay.

**Expected Results:**
What are the expected results?

Bars and Clubs
Bar Owner = 70
Bar Manager = 54 
Bar Security =  45
Bartender =  35

**Actual Results:**
What are the actual results?

Owner = 55
bar manager = 40
bartender = 20

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

LegacyRP

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
There are no official 'public state records', so if the list you are looking at is showing a different value, then they're outdated as the only place the actual salaries are officially put is in the framework's back-end.
