### ISSUE TITLE
Burger Shot Delivery Bug

### ISSUE THREAD

**Issue by GramGram420** [InZidiuZ/op-framework-issue-tracker#1866]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?

https://steamcommunity.com/profiles/76561198163722159/
**Summary:**
Write a short summary of what you are experiencing.

when i pickup a local delivery at burger shot, no delivery is started and it is impossible to deliver.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
try to pickup a local delivery at burger shot
**Expected Results:**
What are the expected results?
you get a marker placed on your gps of the location where you should deliver the food.
**Actual Results:**
What are the actual results?
nothing. no delivery is started. 
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![charID](https://user-images.githubusercontent.com/80990917/121611481-547d5500-ca26-11eb-8f2c-a948134b2a17.PNG)

**Server:**
What server/community did this issue occur in?
legacy rp
**Notes:**
For anything else noteworthy.

**Comment by FunsiesFinest** [comment]
Heard this from a few other friends that work there as well. Hoping to get yall back on the road with some burgers!

**Comment by rajbastakoti** [comment]
https://gyazo.com/47140546d63e1de970f254f4686f9a56 /info should be like this

**Comment by Khasnuwr** [comment]
same, we have the same problem, they should fix it ASAP

**Comment by DaxterPancake** [comment]
Closed in favour of #1867.

Cheers,
Daxter.
Project Manager.
