### ISSUE TITLE
Burger Shot Delivery BUG

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/op-framework-issue-tracker#1867]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/smarifmahmud9/

**Summary:**
Write a short summary of what you are experiencing. 
When a Burger Shot employee go for a delivery it says "you already have an active delivery" but don't give us any location in the map. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
You have to make the delivery location marked in the map for players(Burger Shot employee) who goes for Deliveries.

**Expected Results:**
What are the expected results?
I hope you will fix it soon.

**Actual Results:**
What are the actual results?
Burger Shot employee go for a delivery, it gives them delivery location marked in game. After they delivered to the location they got cash.

## Additional Information

**Screenshots:**
https://imgur.com/PutuAvc
https://imgur.com/syBDFiT

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://imgur.com/Bye1Ezp

**Server:**
What server/community did this issue occur in?
**Legacy Roleplay Bangladesh**

**Notes:**
For anything else noteworthy.

**Comment by iGreatWhite** [comment]
#1866 already has this issue reported. Probably would want to keep it all under one issue.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
