### ISSUE TITLE
PTO for Burger Shot employees 

### ISSUE THREAD

**Issue by GramGram420** [InZidiuZ/op-framework-issue-tracker#1868]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
Burger Shot delivery has been down since Tuesday. employees have been without income because we do not receive pay checks and our systems have been down for delivery. I think we should be payed for the days in which we were unable to make deliveries. 
**Reason:**
Why would your suggestion be a good change to the framework?
Employees from burger shot are going into debt against their will because we are unable to earn money. We should get Paid time off while the burger shot systems are down.

**Comment by Nuziatella** [comment]
This isn't a framework issue. This is something you'd take up with your servers burgershot owner/manager.

**Comment by GramGram420** [comment]
understood thanks
