### ISSUE TITLE
All of southside garages are broken, they only work sometimes Bug report

### ISSUE THREAD

**Issue by eBoiBuns** [InZidiuZ/op-framework-issue-tracker#1869]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561198079064773/

**Summary:**
Write a short summary of what you are experiencing.
Garages only work sometimes work in the south side
i want to be able to use the garage I pay for
without spending at least double on retrieving my vehicles

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

try and use garage. mostly the garage at your house which you pay 6000$ a week to use. (old SSK block in particular)

**Expected Results:**
What are the expected results?
it will either spawn a local whip that everyone else but you can see or vice versa.
if it's invisible for the user of the garage, they must hard nap. 
if they can see the local whip, they can retrieve their vehicle and and repeat.

**Actual Results:**
What are the actual results?
good question

## Additional Information
It is unplayable for me. i join into the city, expecting to be able to chill, and use my house/garage only for me to waste $500 -1000$ then proceed to look for a ride to a different garage. it makes me not want to do anything. on top of me grinding my ass off everyday, this is just completely demoralizing. completely gets rid of my desire to continue to progress. 
ive also noticed that the garages work less and less the closer we get to tsunami (same goes for selling drugs, and diving)
you become less efficient as the day progresses (my guess is the server can't handle the load)
a quick fix would be to have an extra tsunami to balance it out (a tsunami every 12 hours)

**Screenshots:**
If suitable, include some screenshots.
https://gyazo.com/63c40ccb3763616087bb330ab90f9da8

https://i.gyazo.com/thumb/1200/49f540dc33c4907608aeba4fa24cc81b-png.jpg

**Game Resolution:**
What is your game's resolution?
2560x1440p
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
EU/NA Legacy rp
ip: connect c3s1.op-framework.com

**Notes:**
For anything else noteworthy.
please help. this has been an issue for over a month. im trying to get everyone to report on it, half of them are lazy, and the other half already think it's being dealt with.

**Comment by eBoiBuns** [comment]
![legacy info](https://user-images.githubusercontent.com/85319419/121792798-7f96ae80-cbb6-11eb-971d-faaff8e3d2b0.png)

**Comment by eBoiBuns** [comment]
![image](https://user-images.githubusercontent.com/85319419/121794102-e621c980-cbc2-11eb-8e73-f0e1bb219159.png)

**Comment by eBoiBuns** [comment]
![image](https://user-images.githubusercontent.com/85319419/121794118-18cbc200-cbc3-11eb-9d91-b18d5c805f03.png)

**Comment by eBoiBuns** [comment]
![image](https://user-images.githubusercontent.com/85319419/121794195-9db6db80-cbc3-11eb-87de-92787d018d1c.png)
How am i supposed to continue rp?

**Comment by iGreatWhite** [comment]
I’m would avoid pulling cars from this garage for now. And let the devs look into it.

**Comment by FullMetalAlphonse** [comment]
Our entire street has the same problem, and there are several other people across the South Side experiencing this as well. I've been using garage D for the mean time but its getting to be extremely inconvenient. Any solutions would be appreciated

**Comment by Detnom** [comment]
Can confirm our entire block suffers this issue, would love to be able to use my garage consistently.

**Comment by InZidiuZ** [comment]
Sounds like an issue with FiveM considering it came out from nowhere. Could you provide a video of what exactly happens? I think this will be difficult to reproduce locally.

**Comment by InZidiuZ** [comment]
I updated the FiveM artifacts on most servers, so maybe this will be less of an issue now.

**Comment by eBoiBuns** [comment]
Where do I send you the video?
Also who would be responsible for fixing this issue if you cannot?

**Comment by InZidiuZ** [comment]
You can post it here. And FiveM would be.

**Comment by InZidiuZ** [comment]
Is this still happening on the current artifact?

**Comment by eBoiBuns** [comment]
The bug still persists. will have video for you soon.

**Comment by InZidiuZ** [comment]
Closing due to no response. This also most certainly is not up to me to fix, unless some clear repro is obtained, in which case you can just reopen this issue or alternatively create a new one.

**Comment by eBoiBuns** [comment]
I am busy man. you took 9 days to respond to me, im sure you could wait a bit. should I
 open a new ticket?

**Comment by iGreatWhite** [comment]
He said to just reopen this one, once you have the correct repro for the issue.

**Comment by eBoiBuns** [comment]
sorry man, don't have time to read
![image](https://user-images.githubusercontent.com/85319419/123701003-79dbd280-d81e-11eb-8f46-33acfee84ef3.png)

**Comment by eBoiBuns** [comment]
https://youtu.be/rl70bT1wsog

**Comment by eBoiBuns** [comment]
https://www.youtube.com/playlist?list=PLOop0WzYKCnPww11HNszU0Cq1WS9kUaz4
