### ISSUE TITLE
[Suggestion] Remove Ambulances Spawned by NPCs

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-issue-tracker#187]
**Name:**
Anderzenn#0069 (Z-105 Brandon Whittle)

**Summary:**
Removing ambulances spawning at pillbox causing EMS not to be able to take out their own Ambulances.

**Reason:**
Currently there are Ambulances spawning up top at pillbox as well as down below, the ones down below are the biggest concern since they're spawning on top of where we bring out our ambulances.

**Comment by Doughnut2001** [comment]
as PD I've been affected by a similar issue on the roof when getting air one out, but the main difference is that PD has a /impound command, I have been called to pillbox to help and try to impound the ambulances  but I am unable to do it, as a member of PD I'd also like this issue to be resolved, mostly on pillbox

**Comment by InZidiuZ** [comment]
Hey,

Yes.

**InZidiuZ**
*OP-FW Developer*
