### ISSUE TITLE
Cocaine gets sold to the same ped most of the time

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#1870]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/igreatwhite

**Summary:**
Write a short summary of what you are experiencing.
When selling coke, you sell to one local then if you press E right after selling to that one local you will sell to the same local over and over.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Press E to sell to the local
Press E again and it should sell to the same local
This is not 100% but works most of the time.

**Expected Results:**
What are the expected results?
To not sell coke to the same local over and over.

**Actual Results:**
What are the actual results?
Coke gets sold to the same local over and over.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
International

**Notes:**
For anything else noteworthy.
N/A

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
