### ISSUE TITLE
[jobs/?] Update to Comedy Club jobs and Pay

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#1871]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

So currently the comedy club doesn't have a security role, even though the paperwork does for the tracker. So I would like to update the roles from Owner, GM, Bartender, Waiter, to Owner, GM, Security, Bartender. I also think with this pay would need to be adjusted and updated as well. 

This is the wages for other bars in the city and if we could get it updated to match that would be amazing
Bars and Clubs
Bar Owner = 70
Bar Manager = 54
Bar Security = 45
Bartender = 35

This is what the club makes
Bars and Clubs
Bar Owner = 50
Bar Manager = 35
Bartender = 25
Waiter = 20 

**Reason:**
Why would your suggestion be a good change to the framework?
It would be more in line with the documents the government has, it would also make more sense payment wise that security wouldn't be getting paid as much as a General Manager.

**Comment by FunsiesFinest** [comment]
you get a job and you get a job! Lets go comedy club!

**Comment by CoggsWorth** [comment]
$35 as a bartender to $35 as a manager who still has to scuba for rent :/

**Comment by iGreatWhite** [comment]
Don’t bite off more than you can chew? If you are finding that you cannot make enough money to pay off weekly with what you have might currently have then look over that within yourself in RP.

**Comment by CoggsWorth** [comment]
No, it was just an example of how the garbage pay sucks for RP. The legal side of it SUCKS and it only is made more boring and difficult over and over. The Irish pub gets normal pay. Making as much as bartenders as a manager is fail rp straight up.

**Comment by DaxterPancake** [comment]
> No, it was just an example of how the garbage pay sucks for RP. The legal side of it SUCKS and it only is made more boring and difficult over and over. The Irish pub gets normal pay. Making as much as bartenders as a manager is fail rp straight up.

Okay, so you shouldn't be doing a job only because of the pay. You should be doing it for the RP that is accosiated with it.

The pay is completely a script thing so no, it's not Fail RP.

Also being combative will get you NOTHING with it comes to getting said pay changed.

**Comment by CoggsWorth** [comment]
> > No, it was just an example of how the garbage pay sucks for RP. The legal side of it SUCKS and it only is made more boring and difficult over and over. The Irish pub gets normal pay. Making as much as bartenders as a manager is fail rp straight up.
> 
> Okay, so you shouldn't be doing a job only because of the pay. You should be doing it for the RP that is accosiated with it.
> 
> The pay is completely a script thing so no, it's not Fail RP.
> 
> Also being combative will get you NOTHING when it comes to getting said pay changed.

Money is HEAVILY intertwined with RP
It's not my business so ¯\_(ツ)_/¯
When you're forcing people into scuba it takes away rp all I'm saying and everyone who actually plays would agree.

**Comment by DaxterPancake** [comment]
No one is forcing you into scuba. There are other ways to make money and if IN CHARACTER you're not happy with the pay then you can deal with that all completely in roleplay.

If you have no ideas to actually help get this suggestion added, then there is no reason to keep commenting on this.

**Comment by CoggsWorth** [comment]
> No one is forcing you into scuba. There are other ways to make money and if IN CHARACTER you're not happy with the pay then you can deal with that all completely in roleplay.
> 
> If you have no ideas to actually help get this suggestion added, then there is no reason to keep commenting on this.

UHHH just change the value to match the people in the city who legit don't work for their cheques? There's my suggestion bud.

**Comment by Nuziatella** [comment]
Pays will not be adjusted.

**Comment by claymstehling** [comment]
Oh okay, can I get a better understanding of why?!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
