### ISSUE TITLE
Bug report/voice issue happening to me

### ISSUE THREAD

**Issue by robin-401** [InZidiuZ/op-framework-issue-tracker#1872]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-yes
**Player Identification:**
What is your steam profile?
-https://steamcommunity.com/id/zZFancyZz/
**Summary:**
Write a short summary of what you are experiencing.
-i am having voice issue.i can hear from radio and phone 
but i am not hearing any voice when someone closed to me talking..meanwhile i can't hear any voice while talking face to face but the opposite guy hears my voice..but i can't.. In the meantime i can hear them through radio or phonecall...please help me to fix it.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.before the recent update all was clean and clear..i am having this issue after the update

**Expected Results:**
What are the expected results?
-i should have my voice thing like before all good.
**Actual Results:**
What are the actual results?
-i cant hear voice from my nearest guy
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
-1366x768
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
-legacy rp Bangladesh 
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
More information would be needed. Please coordinate with staff to get some data with the '/voice_debug' command when you experience this issue. (The staff members would have to use the command and put your server ID in to enable it for you.)

**Comment by robin-401** [comment]
Ok

**Comment by InZidiuZ** [comment]
I'll close this for now. If you get some more data, either reopen this issue or create a new one.
