### ISSUE TITLE
Bug report - Burgershot Local Deliveries not working

### ISSUE THREAD

**Issue by Xef-Morikawa** [InZidiuZ/op-framework-issue-tracker#1873]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/profiles/76561198166394839/

**Summary:**
Since the city update on 6/8/21 I haven't been able to pick up local deliveries. It says I already have an order but nothing is on my GPS for the actual delivery

**Steps to Reproduce:**
Go to the delivery pickup spot in the Burgershot Kitchen. Pick up a delivery. It will tell you that you already have one. Then look at your GPS and here is no order showing

**Expected Results:**
Expected results is to pick up an order and then see the gps route/marker to be able to go deliver the order

**Actual Results:**
You will not have a burgershot order (or maybe there is, but its not on your gps to show you where)

## Additional Information

**Screenshots:**
I don't think I need to give a screenshot, there are a handful of other players who have reported the same bug, our screenshots are/would be all the same.

**Game Resolution:**
1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![FiveM_Xef Morikawa](https://user-images.githubusercontent.com/85817109/121795799-add9b580-cbd9-11eb-82b9-a15091871478.PNG)

**Server:**
Legacy RP

**Notes:**
I hope this can be fixed soon. None of us that work at Burgershot have any income right now, and this isnt a job we want to leave, or a job that can just be picked back up again whenever we want like trash or delivery

**Comment by DaxterPancake** [comment]
Closed in favour of #1867.

Cheers,
Daxter.
Project Manager.
