### ISSUE TITLE
Hole in the South Runway at Zancudo Military Base

### ISSUE THREAD

**Issue by KatLikesTacos** [InZidiuZ/op-framework-issue-tracker#1875]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes, I have. I searched for "zancudo" and "military base" and found no results.

**Player Identification:**
https://steamcommunity.com/profiles/76561198081364000/

**Summary:**
I was driving down the runway and fell through the earth. Tested this on different days to ensure this way not related to build up of entities.

**Steps to Reproduce:**
Drive over the spot in the screenshot below.

**Expected Results:**
To drive on the runway.

**Actual Results:**
Falling through the ground.

## Additional Information

**Screenshots:**
https://i.imgur.com/vdsY72z.jpg

**Game Resolution:**
2560x1440

**Player Data:**
Character ID: 33704 - Job Data: Bar and Club, Car Jobs, Bar Owner

**Server:**
LegacyRP International

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This most likely does not have anything to do with the framework itself. I would suggest posting this in the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) instead.
