### ISSUE TITLE
[game/miscellaneous] More options for /job

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1877]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*The Mechanic and the Tow Driver job are one of the most requested jobs for staff. Currently, you can give someone the Cadet Job, the Apprentice dealer job and the ems job by just doing /job. It would be nice to be able to give the `Mechanic/Los Santos Customs/Tow Driver` and the `Mechanic/Los Santos Customs/Intern Mechanic` job by doing something like `/job [id] mechanic` or `/job [id] tow`.*

```
/job [id] tow      -> Mechanic / Los Santos Customs / Tow Driver
/job [id] mechanic -> Mechanic / Los Santos Customs / Intern Mechanic

This would be pretty helpful aswell:
/job [id] none -> Sets their job, department and position to nothing

Maybe even this:
/job [id] bar -> Bar and Club / Bar Jobs / Bar Security
```

**Reason:**
Why would your suggestion be a good change to the framework?
*Would make it a lot easier to give people the mechanic and tow driver job and get job requests done a lot faster.*

**Comment by InZidiuZ** [comment]
This has now been added.
