### ISSUE TITLE
Bug report: Some animals cannot jump

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1878]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Player Identification:**
What is your steam profile?
*https://steamcommunity.com/id/twooot/*

**Summary:**
Write a short summary of what you are experiencing.
*Cats (i don't know if this applies for dogs aswell) cannot jump up on to things like human peds can. IRL cats jump ontop of stuff all the time and it would be pretty cool for animal rp to allow it for animal peds aswell. I wouldn't make it too high (like how players can climb up high fences) but to the point that cats and dogs can jump onto tables for example.*

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
*Try to jump in an animal ped*

**Expected Results:**
What are the expected results?
*Jumping*

**Actual Results:**
What are the actual results?
*No jumping*

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
*N/A*

**Game Resolution:**
What is your game's resolution?
*2560x1080*

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
*N/A*

**Server:**
What server/community did this issue occur in?
*C3S1*

**Notes:**
For anything else noteworthy.
*N/A*

**Comment by DaxterPancake** [comment]
This was already discussed in a previous ticket.

Some animals are unable to jump because that is a limit with GTA 5 itself.

**Comment by InZidiuZ** [comment]
These peds do not have native jumping animations/functionality. I tried adding a scuffed jumping mechanic similar to the one in '[goat simulator'](https://www.youtube.com/watch?v=_aT0KRJyOdI), but it didn't turn out well and don't want to spend more time on that, so leaving this as a wontfix for now.
