### ISSUE TITLE
[game/inventory] Mechanic Computer Items

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/op-framework-issue-tracker#1879]
Assurance:
Yes

Summary:
Would like to add additional items to the Mechanic computer at discounted rates. Items include, cleaning kits and repair kits.

Reason:
As a mechanic we pride ourselves on top notch customer service. Having the ability to use a cleaning kit to wash a customers car goes a very long way in their eyes. We currently go out of our way to purchase them at much higher cost than actual car wash costs just to make customers smile. It would be incredible to have the ability to purchase these kits at discounted rates, specifically $10-$15 so we can continue supplying our customers with the best service. Other items could include repair kits.

**Comment by vlaskgar** [comment]
That’s a STUpendous idea. Gotta keep them winders wershed.

**Comment by Nuziatella** [comment]
Offering items at a discounted rate for a specific job would also have to have those items locked to that job and only usable by that job as to not destabilize the economy.

**Comment by twooot** [comment]
I believe all mechanic shops now have a cleaning station which solve this issue.
