### ISSUE TITLE
[game/boomboxes] Boombox Playlist

### ISSUE THREAD

**Issue by Spencer10798** [InZidiuZ/op-framework-issue-tracker#1880]
**Assurance:**
Assured

**Summary:**
The ability to input multiple comma separated Youtube URL's in the boombox UI

**Reason:**
If you have 5 songs you want to play, it can be tedious having to alt tab and grab each URL to enter into the boombox.
This is purely a convenience suggestion

**Comment by Xef-Morikawa** [comment]
It would be even more awesome if you could just use a youtube link for a playlist that you have already created there and have the boombox cycle through the playlist. Idk how realistic that is, I know nothing about coding etc.

**Comment by InZidiuZ** [comment]
There is a relatively long list of things that is to be done to the boomboxes to make them better and this is included in that. Hoping to have it done sometime soon.

**Comment by claymstehling** [comment]
Oh this would be so AMAZING to have! The ability to just add in a whole playlist would make a lot people lives easier! :D

**Comment by twooot** [comment]
Closed in favor of #2534
