### ISSUE TITLE
Real Estate - North Rockford Drive house location issue

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#1882]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/ItzBrittanyBitxh/

**Summary:**
Write a short summary of what you are experiencing.

Real Estate - On North Rockford Drive which is currently owned, two houses seem to be located at the same exterior #6 and #7 both locate at the street address of #6. When both are sold, both interiors are linked to #6 and both garages show up there, on the other hand, the physical address of #7 has no house interior or garage present. See attached for street numbers

https://imgur.com/a/WByXv0n

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Has been an issue since block purchase in 2020

**Expected Results:**
What are the expected results?

Sell house #7 and it give access to a house located at physical address #7

**Actual Results:**
What are the actual results?

Sell house #7 and it give access to a house located at physical address #6

## Additional Information
N/A 

**Screenshots:**
If suitable, include some screenshots.

https://cdn.discordapp.com/attachments/834232691514802186/855256561181130783/unknown.png
https://cdn.discordapp.com/attachments/834232691514802186/855256393220489216/unknown.png
https://cdn.discordapp.com/attachments/834232691514802186/855256734703288350/unknown.png

**Game Resolution:**
What is your game's resolution?

1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://imgur.com/a/LrFkqQg

**Server:**
What server/community did this issue occur in?

Main Server - Legacy RP

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
