### ISSUE TITLE
Comedy Club Vortex

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#1883]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/claystehling

**Summary:**
Write a short summary of what you are experiencing.
Anytime someone goes to the upstairs of the Comedy Club, it will essentially make them disappear 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Have someone go through the club with someone down below talking and then have them go up the stairs multiple times and they should get swallowed by the vortex 

**Expected Results:**
What are the expected results?
The upstairs balcony is able to be used for VIP tickets, where people can sit and enjoy the events and talking with their friends and others down below.

**Actual Results:**
What are the actual results?

People go upstairs and usually instantly disappear, and are not able to talk with their friends and have to go in and out of the club to be able to see it 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
(https://clips.twitch.tv/SmellyFastSwordDoggo-j5peUD7Z4KpiIt_J
)
Not a screenshot but here is a clip of it happening in real time 

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/0a61ba2581c8939021160605cec336be

**Server:**
What server/community did this issue occur in?
Main Server - Legacy RP

**Notes:**
For anything else noteworthy.

**Comment by FunsiesFinest** [comment]
begone vortex of doom!

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this. Use [this one](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) instead.
