### ISSUE TITLE
Comedy Club Collison issues 

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#1885]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Player Identification:
What is your steam profile?
https://steamcommunity.com/id/claystehling

Summary:
Write a short summary of what you are experiencing.
Collision missing on some areas of the Comedy Club 

Steps to Reproduce:
Include what steps that are needed in order to reproduce this issue.

Have someone walk through the corner wall and you are able to go in to the void and you are able to punch people and interact things. Climb on the roof and jump down and you will fall into the void. Also you will sometimes fall into the old Comedy club. I attached videos 

Expected Results:
What are the expected results?
That you are not able to walk through the wall and or fall through the floor

Actual Results:
What are the actual results?

You do walk through the wall and you do fall through the floor

Additional Information
Screenshots:
If suitable, include some screenshots.
https://youtu.be/7xoUnrWQOWs
https://youtu.be/AB7H9JJ_-eE
Not a screenshot but here is a clip of it happening in real time

Game Resolution:
What is your game's resolution?
1920x1080

Player Data:
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/0a61ba2581c8939021160605cec336be

Server:
What server/community did this issue occur in?
Main Server - Legacy RP

Notes:
For anything else noteworthy.

**Comment by antihero6713** [comment]
This issue is fixed @InZidiuZ  You can close this task
