### ISSUE TITLE
Bug report (cocaine plane) BUG

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#1887]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? YES

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/meer_mugdha57/

**Summary:**
Write a short summary of what you are experiencing. 1st screenshot- i am trying to find the cocaine brick but i cant find any maybe its a bug or a glitch of FIVEM

2nd screenshot- I Pressed E to get a cocaine plane it took 1000$ but after 1 scnd a plane spawned and suddenly vanished and its showing me that Mission Failed within 2-3 secnds this happens with me 

server - LEGACY BANGLADESH

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. 1st SS- https://imgur.com/a/UsGcTaA

2nd ss- https://imgur.com/a/s63WLqS

**Game Resolution:**
What is your game's resolution? 1280x720

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted. CID- 678 job TAXI

**Server:**
What server/community did this issue occur in? legacy BD

**Notes:**
For anything else noteworthy.

**Comment by Khunter6y9** [comment]
Please fix this issue, it's a legit problem.

**Comment by DaxterPancake** [comment]
Closing in favour of #1884.

**Comment by ekhowan12** [comment]
Please fix this one asap
