### ISSUE TITLE
Bug report Please fix warehouse

### ISSUE THREAD

**Issue by eBoiBuns** [InZidiuZ/op-framework-issue-tracker#1889]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yup
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198079064773/
**Summary:**
Write a short summary of what you are experiencing.
parking lot scuffs all vehicles parked in the area. making them either disappear or turn rock solid so you cannot enter
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
bring vehicle to warehouse. go in, sell goods, come out, get more goods from vehicle (if visible or able to access) go back in, sell, come out, repeat. the vehicle is bound to scuff at some point.
**Expected Results:**
What are the expected results?
whip scuffs
**Actual Results:**
What are the actual results?
## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
2560x1440
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/85319419/122683562-37cae500-d1bd-11eb-84ba-a012a4b7af1a.png)

**Server:**
What server/community did this issue occur in?
EU/NA Legacy RP
**Notes:**
For anything else noteworthy.
it's been like this since I joined the city (around three months)

**Comment by eBoiBuns** [comment]
the picture above illustrates me not being able to get in my whip (rock solid car). i freeze in this position. This is only one bug.

**Comment by InZidiuZ** [comment]
This is an issue with the FiveM server itself, and not the framework. I'll update all the server artifacts shortly, but ultimately it's not up to me to fix.
