### ISSUE TITLE
Separate trunk instances

### ISSUE THREAD

**Issue by Spencer10798** [InZidiuZ/op-framework-issue-tracker#1890]
**Assurance:**
yea

**Player Identification:**
https://steamcommunity.com/id/SpenceDuke/ho

**Summary:**
Separate instances of the pegassi tempesta trunk container. 
When another player places something into my trunk, I can't see it.
If we exchange the items on the ground and I then place it into the trunk, they cannot see it.
Hard napping and garaging multiple times did not help.

**Steps to Reproduce:**
Player 1 puts an item into the trunk
Player 2 looks in the trunk for the item

**Expected Results:**
Player 1 puts an item into the trunk
Player 2 can see it

**Actual Results:**
Player 1 puts an item into the trunk
Player 2 cannot see it

## Additional Information
Only tested on my pegassi tempesta

**Screenshots:**
https://cdn.discordapp.com/attachments/836482214463668244/856561716363132938/Desktop_2021.06.21_-_11.42.54.05.DVR.mp4

https://cdn.discordapp.com/attachments/836482214463668244/856561704099119125/Desktop_2021.06.21_-_11.42.20.03.DVR.mp4

https://cdn.discordapp.com/attachments/836482214463668244/856561682598854686/Desktop_2021.06.21_-_11.31.21.02.DVR.mp4

**Game Resolution:**
3840x2160

**Player Data:**
35961

**Server:**
Legacy International

**Comment by InZidiuZ** [comment]
Was this a one-time thing, or does it happen at a constant? If it just happened once, then it sounds difficult to reproduce.

**Comment by Spencer10798** [comment]
was occurring all day yesterday for me. ill try again today.

**Comment by Spencer10798** [comment]
Nothing happened on the first try today, albeit with many less people in the city. gonna close guessing it was a network thing
