### ISSUE TITLE
[?] Add Changing Circle at Hayes Mechanic Shop

### ISSUE THREAD

**Issue by riedling11** [InZidiuZ/op-framework-issue-tracker#1891]
**Assurance:**
yes

**Summary:**
Add Changing Circle at Hayes Mechanic Shop

**Reason:**
To be on par with other Mechanics Shops, to allow employees to change into and out of their uniforms as the come on and go off shift.  Inside the STAFF ONLY room would be preferred.

**Comment by Smach90** [comment]
Would be nice to have this due to many sassy locals knocking off hats and glasses.

**Comment by dkokkos** [comment]
the locals in that area are wild! please add that!

**Comment by WavyPC** [comment]
would be great for mechanics to able to change, and also recover their hat and glasses back from locals being violent.

**Comment by kallen45901** [comment]
would be nice to have a changing circle so i can get a new hat after being mauled by locals

**Comment by MickSlick** [comment]
Definitely would be nice to have, darn crazy locals, I like my hat and sunglasses!

**Comment by DrewMctavish** [comment]
I blame the locals and fellow colleges too many a time have I been tackled and had to run up the street to the clothing store to fetch my hat again feel lost without it 🤣

**Comment by Gingerninja78** [comment]
would be great to get my hat and glasses back after them being knocked off by the nasty locals :(

**Comment by claymstehling** [comment]
This would be nice to have as I think every other mech shop does
