### ISSUE TITLE
Burgershot Local Deliveries not paying out

### ISSUE THREAD

**Issue by Xef-Morikawa** [InZidiuZ/op-framework-issue-tracker#1893]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198166394839/

**Summary:**
We are now able to pick up deliveries and have the delivery spot on our GPS, but when we make the delivery to the local we are not getting paid and not getting the pop up in the upper right hand corner of the UI telling us how much the delivery paid and how much the tip was

**Steps to Reproduce:**
Pick up a delivery at Burgershot, go to the point on the map and complete the delivery, receive your payment for the delivery

**Expected Results:**
Get your payment for the delivery completed, and have the box in the upper right of the UI pop up to tell you how much the payment was and how much the tip from the local was

**Actual Results:**
Not getting payment or UI pop up

## Additional Information

**Screenshots:**
Not really as screenshot available because nothing pops up in the UI to tell you how much you got paid, and since youre not getting paid there is no money update shown for your cash
![BS No Payment](https://user-images.githubusercontent.com/85817109/122942288-b9e11800-d33b-11eb-8c8b-f126fcbec660.png)

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![BS No Payment_Info](https://user-images.githubusercontent.com/85817109/122942210-a9c93880-d33b-11eb-85b5-6758ac97361f.png)

**Server:**
Legacy

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
