### ISSUE TITLE
Bug report: jewellery shop robbery alarm bug

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/op-framework-issue-tracker#1894]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/smarifmahmud9/
**Summary:**
Write a short summary of what you are experiencing.
After breaking into the Jewelry shop it doesn't triggers any Alarm to Police like police get for Bank_robbery/Store_robbery/Truck_hijacking alarms/notifications.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Player breaks into the Jewelry shop -> triggers Alarm to police.

**Expected Results:**
What are the expected results?
Player breaks into the Jewelry shop -> triggers Alarm to police.

**Actual Results:**
What are the actual results?
Player breaks into the Jewelry shop -> doesn't triggers Alarm to police.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920*1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
**Legacy Roleplay Bangladesh**

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
When did this last happen? Have you specifically tested all the three robberies mentioned? (Jewelry store robbery, store robbery and the stockade heist.)

**Comment by Khasnuwr** [comment]
> When did this last happen? Have you specifically tested all the three robberies mentioned? (Jewelry store robbery, store robbery and the stockade heist.)

police dont receive only jewelry heist alarm, 1 day ago(last )

**Comment by InZidiuZ** [comment]
So it's *only* the jewelry store that doesn't work as intended? Does *anyone* at all get the notifications, or no one at all?

**Comment by Khasnuwr** [comment]
> So it's _only_ the jewelry store that doesn't work as intended? 
Yes, only jewelry store

> Does _anyone_ at all get the notifications, or no one at all?
no one gets notifications

**Comment by Khasnuwr** [comment]
> So it's _only_ the jewelry store that doesn't work as intended? 
**Jewelry** and **store robbery** (both police don't get **alarm notifications**)

> Does _anyone_ at all get the notifications, or no one at all?
no one at all gets notifications.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
