### ISSUE TITLE
[?] Have an aircraft shop where private aviation businesses can build their fleet without rentals.

### ISSUE THREAD

**Issue by BriJustice** [InZidiuZ/op-framework-issue-tracker#1895]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
The general idea is to have an either local and player ran/owned aircraft shop where private aviation businesses can build their fleet and private pilots can purchase their very own aircrafts without renting aircrafts. As of right now, renting aircrafts are free. You don't pay for them so it would be fun if you actually could own an aircraft without being ashamed of saying "No I don't own this plane/helicopter, unfortunately these aircrafts are too expensive so all I can do is rent them". This could work well with this: [https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1825](url) where you could after purchasing an aircraft, store it in a different hangar/garage location.

**Reason:**
The reason why I am suggesting this is because I feel like it could bring somewhat more roleplay into the state of San Andreas, especially for those that like to "bring in the real world into this world". Having access to a private aircraft gives you a status of some wealth and knowledge.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
