### ISSUE TITLE
[?] Aircraft Mechanic Shop (allowing private aircrafts to be repaired and customized as well)

### ISSUE THREAD

**Issue by BriJustice** [InZidiuZ/op-framework-issue-tracker#1896]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
With this suggestion there would be a whole new world of roleplay in the server. If you were to be able to have private aircrafts, you could then check in with an aircraft mechanic shop where you could repair and maintain your aircrafts and also customize them. From experience I know that there are some if not many aircrafts you can change the color of and their livery as well as upgrading their engines and many other things.

**Reason:**
The reason why I think this would bring a whole new world of roleplay opportunities in the server is because, first of all. Even in real life aircrafts do need to be maintained and if something breaks, then it needs to be fixed. Having a player ran business as an Aircraft Mechanic Shop, they would be making money as well as fulfilling their dreams of not only working with cars, but also working with planes and helicopters that are way more expensive and luxurious. I have myself wished to see something like this being a thing in the server ever since I started my first flight lesson which was just a few days ago. After all, if you were to be a pilot, you could also be making a lot of new friends working in the same area as you, talking about aircrafts instead of ground or sea vehicles. I also know for some of the performance classed aircrafts, they can fly extremely fast, and if you wish to look fast, then you better have a livery that makes you look fast. To get that livery you'd have to contact an Aircraft Mechanic and get to business!

**Comment by Nuziatella** [comment]
This won't happen until various other faucets of the framework have been completed to support a garage that supports aircraft.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
