### ISSUE TITLE
[?] Airport Security or Airport Police job

### ISSUE THREAD

**Issue by BriJustice** [InZidiuZ/op-framework-issue-tracker#1897]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes.

**Summary:**
Similar to the normal police departments but they work for LSIA (KLSI) and/or possibly even SSA (KSYD). This job would be for those that would like to protect the restricted area with "NO TRESPASSING" signs all over the place to stop new immigrants and other citizens from entering if they aren't a pilot/ground crew or have no business whatsoever in that area.

**Reason:**
There have been some instances when people have come in stating that they are not a pilot nor they have a valid reasonings for entering the restricted ground area of LSIA. I have myself a few times explained to them that it's a restricted area and not accessible for the public, then asked them if they are a pilot or if they are a student waiting for a certified flight instructor. Many times they said no to either one of them and that is when I had asked them to leave or I would be forced to call the police. 99% of the time they respected the law and drove back outside of the fences, but I had one case when a new immigrant were driving across the runways and causing chaos. I had called the police on him but there were no response. 

So with the help of AS or AP, it would not only take work off of the general police departments, but it would also make good interactions between pilots and the AS/AP.

**Comment by Nuziatella** [comment]
Would the goal here to be just to add a job title and give it a paycheck? 
What other features should this job title have?

**Comment by DaxterPancake** [comment]
Why couldn't we just have a security role that could be used for anything, then in roleplay you hire that security for the airport?

**Comment by BriJustice** [comment]
> Would the goal here to be just to add a job title and give it a paycheck?
> What other features should this job title have?

1. I think so?
2. I'm not really sure to be honest. Security and Police are two whole different things. One enforces the law, protects people and serves the people. The other one is just... security. Security just secures premises and personnel by patrolling around and in the property, they also inspect buildings, give entry permits and so on.



> Why couldn't we just have a security role that could be used for anything, then in roleplay you hire that security for the airport?

1. This in my opinion is a really good idea, just have a security role then in roleplay hire that/them for the airport(s).
