### ISSUE TITLE
[vehicles/garages] LSIA Aircraft spawner adjustment

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1898]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?  **Yes**

**Summary:**
Write a summary of what your suggestion is about.

Adjustment of aircraft ratings.
Please remove:
[p]Besra from Performance (already in management)
[h]Buzzard (not attack version from Military it is already in Helicopter.)

Please move:
[h]Cargobob2 to Heavyweight (need hw heli license)
[p]Tula to military

**Reason:**
Why would your suggestion be a good change to the framework?
After a few weeks of having the spawner these are the balance adjustments I feel would work best for now.

**Comment by InZidiuZ** [comment]
This has now been done.
