### ISSUE TITLE
combat log deterrent

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-issue-tracker#190]
TANKFURIOUS
**Summary:**
lost about 3k to this new combat log deterrent thing. also had no warning of the changes (never combat logged just quit game)

i really think this is a bad addition especially if you have to put your car away at a garage and run to train station or apartment.
pretty much forced to use garage c if you dont have an apartment.

not sure of a work around for this as adding ability to log out at garages could also increase the combat log possibilitys.

not sure how easy it would be to force your entity to stay in for a min or 2 after you log out like dayz

**Comment by SATIN187** [comment]
you Talking about the mugging?

**Comment by tankfurious** [comment]
Nevermind turns out its a bug

**Comment by InZidiuZ** [comment]
Hey,

This was an issue, and should be resolved.

**InZidiuZ**
*OP-FW Developer*
