### ISSUE TITLE
[game/panic_button] Officer Down Button / Panic Button

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-issue-tracker#1900]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
For the longest time now Police have only been able to say "10-14" on radio and it causes a ton of confusion and like 5 minutes of "who was that?" "where were they?" and it takes too damn long for anything to happen. Having an Officer Down button (only available when downed) would eliminate the confusion and allow officers to respond faster. Maybe having an animation for it along with an alert in Dispatch in the top left displaying the Officer's Name and Location

**Reason:**
I am tired of the confusion from officers when someone goes down. Also people like me aren't comfortable using my radio while downed to say "10-14" instead I'd hit my Officer Down Button while remaining silent and injured.

Obviously many servers have this feature. I hope you don't see this as us wanting to clone their ideas but this will be a helpful feature for us in the future. If its a great RP scenario and the Officer can't "reach" their button such as being held up or cuffed, and they still "hit" their button, it should be considered FailRP. Or like I mentioned, having it only available when you are downed. Whether its a command or a second keybind next to the standard "respawn" button

**Comment by Nuziatella** [comment]
This is something that would need a dependent from the UI which is currently deprecated. A new UI is in the works and this could be an addition there.

**Comment by twooot** [comment]
This was done
