### ISSUE TITLE
Can't review cars as a mechanic.

### ISSUE THREAD

**Issue by Detnom** [InZidiuZ/op-framework-issue-tracker#1901]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Detnom/
**Summary:**
Write a short summary of what you are experiencing.
I work as a mechanic in Mosley's. When I try to fix a car, I am able to review a vehicle one time after I fly in, but no review shows up and I'm stuck holding the clipboard until I hard nap (pressing U also works to rid myself of the clipboard, but doesn't let me review another car).
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I have no idea what triggered it, so no idea how to reproduce. Simply pressing R to attempt a review will cause the issue.
**Expected Results:**
What are the expected results?
Pressing R, seeing the car's status and being able to repair the vehicle.
**Actual Results:**
What are the actual results?
I press R, the clipboard comes out and gets stuck in my hand, and I don't see the status of the car.
## Additional Information
Also can't place crafted doors/windows on cars that need them.
**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://cdn.discordapp.com/attachments/857670656090439760/857670712155308093/unknown.png
**Server:**
What server/community did this issue occur in?
Legacy RP International.
**Notes:**
For anything else noteworthy.

**Comment by MetaHatter** [comment]
I had this issue at one point too... Tried everything, including clearing cache. Completely reinstalling FiveM worked.

**Comment by Detnom** [comment]
> I had this issue at one point too... Tried everything, including clearing cache. Completely reinstalling FiveM worked.

Can confirm completely reinstalling FiveM fixed the issue, how interesting. Gonna go ahead and close it with this comment then I guess. If I can figure out how I actually caused the bug, I'll update.
