### ISSUE TITLE
[Bug] Repairing aircraft engine does repair it, but does not stay repaired.

### ISSUE THREAD

**Issue by BriJustice** [InZidiuZ/op-framework-issue-tracker#1902]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes.

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/awawawawawawawa/

**Summary:**
Repairing an aircraft engine with an advanced repair kit to stop engine smoking does not stay functional and goes back to a smoking and broken status.

**Steps to Reproduce:**
1. Use an advanced repair kit to repair the smoking engine of an aircraft
2. Get inside of the aircraft
3. Turn on engine
4. Wait up to 35 seconds

**Expected Results:**
What are the expected results?
The expected results are that the engine will function as it should, but then it will turn itself off and go back smoking.

**Actual Results:**
What are the actual results?
Same as the expected results I think.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
Video: [https://youtu.be/URG4bjv7Ppo](url)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/86401868/123517194-eb414700-d69f-11eb-85be-65ebbbc2ab29.png)

**Server:**
What server/community did this issue occur in?
Legacy RP server, the public english speaking one.

**Notes:**
For anything else noteworthy.
Nothing.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
