### ISSUE TITLE
[game/repair_shop] Ability to cancel crafting a door, window or tire as a mechanic

### ISSUE THREAD

**Issue by puppyani** [InZidiuZ/op-framework-issue-tracker#1903]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Summary: Ability to cancel crafting a door, window or tire as a mechanic. Currently at a workbench, if you hit E too fast or too much, you're locked into making a door or a customer might change their mind about doors / windows, and there's no way to cancel making the item. A lot of times people have made a door by accident (especially in 2nd Gear being in close proximity to the workbench, trying to replace the window or door, and trying to lock the back door bay which all use the E key). 

**Reason:**
Why would your suggestion be a good change to the framework?
This suggestion would be a good, positive change for both the customer and mechanic. It will give mechanics less frustration, it won't waste their materials (doors require 2 scrap to craft), and also prevents awkwardness when dealing with customers (ex. go to make a window, end up making a door by accident - they lose the scrap to the door, then it takes more time to craft the window after - which only delays the customer further).

**Comment by Insidious-Space** [comment]
This would be a great addition. Being able to use X or similar to cancel the craft would be incredibly useful.

**Comment by xplrerin** [comment]
This needs bumped I'm tired of wasting mats 😭

**Comment by AdeptCL** [comment]
Clicking your ESC key, just like pausing, should cancel any forms of animation. Not just this.

**Comment by V4P1Dx69** [comment]
@AdeptCL it won't stop until you just quit your game :v

**Comment by AdeptCL** [comment]
> @AdeptCL it won't stop until you just quit your game :v

That's my point. It should cancel by just clicking ESC but it doesn't.

**Comment by V4P1Dx69** [comment]
@AdeptCL true, tho it's been scuffed from the early days of legacy but still not being looked up.
also, ESC or BACKSPACE would be good if any dev is on to fix it.

**Comment by CloudTheWolf** [comment]
Another option would be to make Wheels, Doors and Tyres Items that mechanics can craft and store (Similar to how they craft repair kits) so even if you do accidently make a door and forget to cancel you don't waste materials

**Comment by twooot** [comment]
done
