### ISSUE TITLE
[game/doors] Ability to keep bay door locked in the open position

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/op-framework-issue-tracker#1904]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Allow bay doors at 2nd Gear, or anywhere that utilizes them, to be locked in the open position.

**Reason:**
Going in and out of the door on foot can be a little irritating so we tend to prop the door open with a bicycle wedged in the corner. Being able to keep the door locked in the open position would just make life a little easier when going in and out frequently on foot all day long.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
