### ISSUE TITLE
[alpha/towjob] Midnight club tuner shop

### ISSUE THREAD

**Issue by tbone0tbone** [InZidiuZ/op-framework-issue-tracker#1905]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
my suggestion is too have the midnight club los santos customs which is lsc 7 turned into a mechanic shop/tuner shop for a business and also add a atm next the office door for convenience and adding a car wash hose  but also keeping it a los santos customs in the attached files i have pictures of the different spots i would think it would be good to put the work benches and where to get materials from and a spot for the workers to change clothes and have "lockers" and the ability to lock it up by the owners
![F1AfhPGwAX](https://user-images.githubusercontent.com/76892405/123739206-43c93d80-d874-11eb-96a8-af2e50796a11.jpg)
![FiveM_b2060_GTAProcess_LSgQjWAuOG](https://user-images.githubusercontent.com/76892405/123739226-49268800-d874-11eb-8c0a-e628c717d25c.jpg)
![kpgHyXEaNz](https://user-images.githubusercontent.com/76892405/123739234-4c217880-d874-11eb-81e6-acadaf4ee10b.jpg)
![LKkjTuvWyZ](https://user-images.githubusercontent.com/76892405/123739245-4e83d280-d874-11eb-9014-b634a762bb72.png)
![mGzLq5klBq](https://user-images.githubusercontent.com/76892405/123739252-50e62c80-d874-11eb-9584-39c399ea8d6e.jpg)
![FiveM_b2060_GTAProcess_TPHwIiN3Ft](https://user-images.githubusercontent.com/76892405/123739312-6eb39180-d874-11eb-84fe-551fe7489921.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?
my suggestion would be a good change because someone would be able to own the shop and would have more areas for repair then most other mechanic shops with the ability to add a spot to tune cars with tuner chips for a fee and the door is big enough with enough space inside to comfortably store and work on semi trucks and tow trucks easily i know theres alot of mechanic shops but i feel this one will be set apart from the rest by the stuff itll offer and rp it brings like the divers who want to sell their materials could come here instead of the warehouse because they are about the same distance and racers would wanna get involved because we would be tuning cars

**Comment by tbone0tbone** [comment]
any updates on this?

**Comment by twooot** [comment]
All done
