### ISSUE TITLE
[game/boomboxes] Alternative to current Boombox implementation

### ISSUE THREAD

**Issue by Stretah** [InZidiuZ/op-framework-issue-tracker#1907]
**Assurance:**
Assured

**Summary:**
I wanted to find a GitHub script for an alternative to the current implementation of the boombox we currently have in city and have found what I believe is an overall better implementation for music in the city. This would allow not only a better RP experience for players but a more immersive experience for businesses. 

Here is the link to the overall suggestion:
(https://forum.cfx.re/t/esx-exm-carmusic-musiceverywhere-a-nui-synchronized-music-script-to-animate-your-server-paid/2119764)

Here is the link to the demonstration of this suggestion:
(https://streamable.com/sfng79)

**Reason:**
I believe this change would be better overall for the framework as it is scalable, customizable and future proof. This will allow music to be played from cars and placed within business and tied to specific jobs. It also addresses the issue many have had with the current boombox implementation that does not allow for a lot of songs to be played on the current system.

**Comment by MissDyna** [comment]
yeah i Dislike the fact that none of my songs work accept a few so trying to pick certain songs makes event's difficult !

**Comment by iGreatWhite** [comment]
It has to deal with APIs that have limits per day. It can only handle so many requests before it rejects all URLs. In addition, it won’t accept anything over 10mins. As well as, there is like 7 legacy servers all with boom boxes so that limit comes pretty quickly. 
Also the alternative linked in this post, has a dependency for ESX which may not work or have to have some serious rework to even put into the server.

**Comment by ultrahacx** [comment]
The current setup of boombox has much more that the above mentioned script such as spatial audio which was specially worked for days and goes through a audio conversion process on backend servers for compatibility with spatial audio and also to maintain performance.

With the above boombox setup, it runs the youtube video instance in your Fivem. If you consider that, you have a chrome tab open for each boombox. Imagine 10-15 boomboxes running in the city. It would be a great performance loss depending upon how good the player's PC setup is.

**Comment by ultrahacx** [comment]
10min song limit might be removed soon as Inzidiuz last mentioned but Im not sure if he even remembers about it. It was implemented as first place to prevent people from playing long songs cause the video needs to be processed to mp3 at backed and then streamed to players which would easily exhaust both API limit and server storage and bandwidth

**Comment by InZidiuZ** [comment]
> It also addresses the issue many have had with the current boombox implementation that does not allow for a lot of songs to be played on the current system.

The linked resource would most likely have *way* less songs available as well as problems with one player being able to hear the song and another one not being able to.

**Comment by Stretah** [comment]
Well would there be a way to implement a better music system for businesses and citizens? I'm aware this would take awhile to implement and create but it would benefit everyone as there are tons of people that just want to have a better/less limiting boombox system. I'm not opposed to the boombox; it just doesn't work well currently.

**Comment by Spencer10798** [comment]
Does this script only support one song at a time? That's a big step backwards if so. Being able to line up multiple songs is a pretty important feature that the current boombox supports.

**Comment by InZidiuZ** [comment]
The script linked here seems to be many, many steps backwards compared to the current one. I don't have any intents to add the one suggested, but elements from that one can be taken and applied to our custom one.

**Comment by Stretah** [comment]
I mean end of the day we just want improvements to be made to the boombox system so whatever works would be helpful.

**Comment by Stretah** [comment]
I know this might be a big undertaking but would it better to add Spotify integration? I understand this would require client-side authentication to Spotify and not sure if that would run into issues with other hearing the music however could that possibly be implemented?

**Comment by InZidiuZ** [comment]
Spotify sounds like a major headache that would probably never really work as you might think/hope.

**Comment by ultrahacx** [comment]
Spotify won't work either way since the CEF aka inbuilt chromium doesnt have EME certification. Even if it would have had EME, managing the Spotify SDK permissions for usage and user login details for Spotify account would not be possible

**Comment by Stretah** [comment]
Hmm, fair enough. What possible solutions/improvements do you all think could be made to the current system in the future?

**Comment by InZidiuZ** [comment]
Here are some I have noted down:
- Fix being able to swim with the boombox.
- Make boombox aware of interior portals somehow.
- Tweak the range and volume levels.
- Improve back-end 3d audio functionality.
- Allow links with a mp3-file to be played.
- Stereos/audio boosters.
- Repeat button.
- Boombox exception command to the /no_copyright.
- Only sync to relevant/nearby players.
- Make native jukebox objects have boombox functionality.
- Ability to queue up entire playlists.
- Increased amount of playable YouTube videos.
- Soundcloud support.

There most likely are other things that can be done too, so feel free to come with your own input.

**Comment by Stretah** [comment]
Good suggestions honestly. I think soundcloud support and the mp3 files would help a lot as well. Would the Mp3 file include client side direct pathing from client machines? I'd assume not because not sure how you'd manage to get that to work.

**Comment by InZidiuZ** [comment]
No, you'd have to upload them somewhere. An easy place to do so is just dragging & dropping it in a discord channel and copying its link.

**Comment by Stretah** [comment]
Yeah that makes much more sense to me. I like the idea of all of those changes though. Especially since YT is so limiting on what songs can and can not be used. MP3 files alleviates that issue.

**Comment by twooot** [comment]
Closed in favor of #2534
