### ISSUE TITLE
Allow EMS to UnCuff

### ISSUE THREAD

**Issue by Ashraf2112** [InZidiuZ/op-framework-issue-tracker#1909]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Since Police has the Power to Give CPR I feel like EMS Should be able to Uncuff a hostage when needed.
**Reason:**
Why would your suggestion be a good change to the framework?
This will allow EMS to uncuff hostages, instead of taking them to a pillbox and checking them in.

**Comment by ekhowan12** [comment]
this will be a good thing for subdivision servers like bangladesh nepal pakistan

**Comment by InZidiuZ** [comment]
This has now been done.
