### ISSUE TITLE
Towing no longer works "properly" due to changes to /flip.

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1910]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/MetaHatter/

**Summary:**
Write a short summary of what you are experiencing.
Towing no longer works "properly" due to changes to /flip.

Towing owned, locked or scuffed cars/husks often required the tow driver to /flip the vehicle in order to "mark" it and then attempt the /tow.  

With the changes to /flip, "marking" no longer happens on a flip attempt so many cars are untowable.  A temporary workaround is to enter the driver's seat (if possible). Entering the seat seems to "mark" the car and towing works about 90% of the time.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Find a car and try to tow it.  You will find that the vast majority are not towable without entering the driver's seat.

**Expected Results:**
What are the expected results?
Typing /tow near a vehicle should move that vehicle to the tow truck bed.  Ideally there would be a command/way to mark a car without relying on /flip or its cooldown.

**Actual Results:**
What are the actual results?
Currently the car remains in place.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
n/a

**Game Resolution:**
What is your game's resolution?
1440p

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Screenshot 2021-07-07 011706](https://user-images.githubusercontent.com/84351858/124704155-9ed8e100-dec1-11eb-89f3-d3cfa33bcd1a.png)

**Server:**
What server/community did this issue occur in?
International: c3s1.op-framework.com

**Notes:**
For anything else noteworthy.

The core issue is that a workaround was "fixed" and cascaded into this bug.  Ideally adding a /tow_mark command, that emulates the effect of flip and getting in the driver's seat, to go with /tow would correct the bug and make towing 10000x easier.

**Comment by QuinnFreeman** [comment]
Can confirm as one of the most active and longest-running tow drivers in the city, towing is in fact scuffed as detailed above.

**Comment by InZidiuZ** [comment]
This issue has now been resolved. You should be able to tow vehicles far more consistently now, even with players inside of the vehicle.
