### ISSUE TITLE
I suggest the Vapid Speedo Van from EDM to have 750 trunk space

### ISSUE THREAD

**Issue by SlugSalesman** [InZidiuZ/op-framework-issue-tracker#1911]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
y
**Summary:**
Write a summary of what your suggestion is about.
I suggest the Vapid Speedo Van from EDM to have 750 trunk space.
**Reason:**
Why would your suggestion be a good change to the framework?
The Vapid Speedo Van is a quite large van compared to other vans that already have 750 space and it currently only sits at 500.

**Comment by InZidiuZ** [comment]
This has now been done.
