### ISSUE TITLE
[?] Adding a garage here

### ISSUE THREAD

**Issue by Deaddro** [InZidiuZ/op-framework-issue-tracker#1912]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

There is no garage in Eclipse Boulevard Manson, Need a garage in Eclipse Boulevard Manson,Not having a garage causes a lot of problems. It is not possible to get a car from another location and many much problem appears for this, If you can add garage it will be helpful.

**Reason:**

There is no garage in Eclipse Boulevard Manson, Need a garage in Eclipse Boulevard Manson,Not having a garage causes a lot of problems. It is not possible to get a car from another location and many much problem appears for this, If you can add garage it will be helpful.

![066AA606-82E1-47B3-9DEA-32B6060DA136](https://user-images.githubusercontent.com/71873145/124751299-47ca1f00-df48-11eb-8ed1-76880fcfce86.jpeg)

**Comment by Deaddro** [comment]
Yes ✌️

**Comment by InZidiuZ** [comment]
I can't see any good spots to put a garage here. Do you have any suggestions?

**Comment by InZidiuZ** [comment]
Never mind. One was added [here](https://gyazo.com/5a6a042980e8595b7e8a9d6dfd1ab1c8).
