### ISSUE TITLE
Tempesta - matte is chrome 

### ISSUE THREAD

**Issue by Spencer10798** [InZidiuZ/op-framework-issue-tracker#1913]
**Assurance:**
once

**Player Identification:**
https://steamcommunity.com/id/SpenceDuke/home

**Summary:**
The Pegassi Tempesta has a primary and secondary color. When you try to respray the secondary color to be a matte paint, it only displays the chrome option and appearance. The primary color supports all matte paints as expected. 

**Steps to Reproduce:**
Enter LSC in a Tempesta, select Respray, Secondary Color, Matte

**Expected Results:**
Matte colors

**Actual Results:**
The only matte color is chrome.

**Game Resolution:**
3840x2160

**Player Data:**
35961

**Server:**
Legacy International

**Comment by InZidiuZ** [comment]
This issue has now been resolved.

**Comment by Spencer10798** [comment]
@InZidiuZ 
![Ex](https://imgur.com/a/C49LkQV)
Effective after next tsunami or should it already be in

**Comment by InZidiuZ** [comment]
On the next update. Live/production servers usually only update every Tuesday.
