### ISSUE TITLE
Suggestion - Paleto Bay Repairs Additions

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1915]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Adding some extra basic functions to the Paleto Bay Repair shop; Parts computer, ATM, and potentially a car wash.

**Reason:**
Why would your suggestion be a good change to the framework?
Recently, the mechanic shop had an update which is incredible. However, there is only a few little problems in which can be appreciated if added:
- Parts buying area, we simply do not have one. There is an office to right hand side as you walk into the mechanic shop, next to the restroom. It's the same location as the past 2 mechanic shops we've had in Paleto Bay.
([https://prnt.sc/19okqqy](https://prnt.sc/19okqqy))

- ATM. Currently, the closest ATM is at the Paleto Bay bank, which to walk/run is quite the distance. There is a space within the mechanic/clubhouse middle part where the ATM can be added.
[https://prnt.sc/19ol3hg](https://prnt.sc/19ol3hg)

- A car wash. There is a large gas station, in which a car was is present close-by. But far enough for individuals working at the shop to be isolated away from it. I'm proposing a car wash function to be added in any of the three locations in the below image. The function would be outside, but more than likely will need a prop also adding that looks like a car was.
[https://prnt.sc/19oltjv](https://prnt.sc/19oltjv)

Finally, this isn't an addition as such, but outside of the doors and in front of the shop as a whole is considered a ped zone. Trucks, and cars all spawn within this area and it can sometimes block the entrance to the mechanic shop. If this could be changed to a no ped zone, it would be appreciated.
[https://prnt.sc/19om7b1](https://prnt.sc/19om7b1)

**Comment by InZidiuZ** [comment]
I added the 'parts buying area' as well as the no ped zones, though for the ATM & car washes, you'd have to create an issue on the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
