### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by robin-401** [InZidiuZ/op-framework-issue-tracker#1916]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
-yes
**Player Identification:**
What is your steam profile?
- https://steamcommunity.com/id/zZFancyZz/
**Summary:**
Write a short summary of what you are experiencing.
-while Reviewing vehicle as a mechanic we cant see vehicle conditions as a result we cant repair Vehicles..there is a script error poping up..
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
-fix this
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
-https://imgur.com/a/Loxy0cI

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
-legacy bangladesh subdivision
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has already been resolved. Wait for an update.
