### ISSUE TITLE
[?] A convenience store @ 2nd Gear

### ISSUE THREAD

**Issue by puppyani** [InZidiuZ/op-framework-issue-tracker#1917]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Currently, there is an empty building on the premises @ 2nd Gear mechanic shop which would be a prime location for a convenience store (like some gas stations around the city have) - there are also no convenience stores in/around this location (closest is around the corner from Mosley's). 

**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good addition to the server as it creates more avenues for RP - convenience stores can be robbed; people are able to grab necessary items when they get repairs / get gas; it brings more to the southside, especially near the airport as mentioned above there are no convenience stores in this part of the map. We get a lot of footfall of new people coming by the shop asking where to get food, phones, etc. so having a convenience store would be an excellent addition to help those that come to us straight from the airport, too (ex. buying a phone to call a taxi to go find a job). 
![20210711124204_1](https://user-images.githubusercontent.com/85951649/125193865-a0e6cb00-e246-11eb-828e-465516ae2fa2.jpg)

**Comment by InZidiuZ** [comment]
Are you asking for an interior to be added there, or just a marker with a store inventory?

**Comment by puppyani** [comment]
> Are you asking for an interior to be added there, or just a marker with a store inventory?

It would be awesome if the interior could be added like other stores!! But if it makes things easier for now, a marker with store inventory will be still a great addition - the interior side can be something that can happen later if it's a lot of work!!

**Comment by InZidiuZ** [comment]
The interior would have to be suggested in [this issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues). Though I could add just a marker for now and then move the marker in when the interior would be added.

**Comment by InZidiuZ** [comment]
I added a marker at the door. Feel free to suggest the store interior to be added and perhaps it will be.
