### ISSUE TITLE
Bug report: Cocaine brick mission

### ISSUE THREAD

**Issue by Khasnuwr** [InZidiuZ/op-framework-issue-tracker#1918]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
https://steamcommunity.com/id/smarifmahmud9/

**Summary:**
Following bugs happening frequently
01. After depositing security money for Pick up run the **plane does not spawn** and **mission failed**. (End)
02. If no. 01 does not happens then go to No. 03
03. The next **Objective: Land and gather the airdrop** the airdrop disappears.

**Steps to Reproduce:**
1. fix plane disappearances after depositing security for the **Pick up run**
2. **Objective: Land and gather the airdrop** the airdrop must not disappears.

**Expected Results:**
depositing security money for Pick up run -> get the plane -> Land and gather the airdrop -> return to the McKenzie airstrip -> adding cocaine brick in inventory.

**Actual Results:**
Depositing security money for Pick up run -> Don't get the plane Mission failed(steps stops).
OR/
Depositing security money for Pick up run -> get the plane -> Land and gather the airdrop: airdrop doesn't spawn (can't complete the mission without gathering airdrop)

## Additional Information

**Screenshots:**
[Problem No. 01](https://imgur.com/undefined)
[Problem No. 02](https://imgur.com/undefined)

**Game Resolution:**
1920*1080

**Server:**
Legacy Roleplay Bangladesh

**Comment by InZidiuZ** [comment]
This is most likely an issue with the FXServer artifacts. I'll note to update all the artifacts all on the hosts later.

**Comment by InZidiuZ** [comment]
*this actually probably was another bug that I now have fixed. It'll be live on next update. (for prod servers, this is usually Tuesdays)
