### ISSUE TITLE
Create Buypoints for Tow Trucks(20ramrbc,towcustom)

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#1919]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Create Buy points for the 20ramrbc and towcustom mechanic tow trucks

**Reason:**
Why would your suggestion be a good change to the framework?
as these vehicles were added in the server in may but buy points regarding the same has not been added yet

**Comment by InZidiuZ** [comment]
This has now been added. You can only spawn them and not purchase them for now, though.
