### ISSUE TITLE
Repairing cars with people inside does not repair correctly

### ISSUE THREAD

**Issue by greatwhite18** [InZidiuZ/op-framework-issue-tracker#192]
**Reporter:**
iGreatWhite#3018

**Summary:**
When you try to repair a car with anyone sitting inside of it. It will not repair and just take the materials from you.

**Steps to Reproduce:**
1) Have materials on you to repair your car.
2) Have someone sit inside of it.
3) Repair it.
4) It will take the materials and not repair the car.

**Expected Results:**
Either tell you there is someone in the car and it cannot be repaired or be able to repair the vehicle with people inside of it properly.

**Actual Results:**
Car repairs and takes materials but doesn't repair at all.

## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
https://imgur.com/hZxlmtx

**Comment by InZidiuZ** [comment]
Hey,

This has to do with entity ownership in GTA, and as I didn't create GTA, I have no easy way of getting this sorted. Solution is just to not have anyone inside. ;) I've added checks to prevent you from repairing a vehicle when someone is inside, though.

**InZidiuZ**
*OP-FW Developer*
