### ISSUE TITLE
Add Police Issue VIP Tracker Item

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1921]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a police provided item that police can use to track individuals.

**Reason:**
Why would your suggestion be a good change to the framework?
There are many VIPs that have gone missing with no means to an end for police or time pressure for the kidnapper(s).  A police issuable item that would track them would aid in closure of open ended situations. Ideally the "last seen" location would remain if enabled to allow police a place to start a search.

**Comment by DaxterPancake** [comment]
This is already a thing but is locked behind strict PD SOP's due to how powerful it can be,

**Comment by DaxterPancake** [comment]
Closing due to already being in the city.

Thank you for the idea!

Regards,
Daxter.
Project Manager.
