### ISSUE TITLE
Lost MC Garage Icon Hidden on Map

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1922]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Currently the Mechanic shop for the Lost MC Compound is hidden underneath the car wash icons on the map
![Lost Compound](https://user-images.githubusercontent.com/84351858/125461899-7e2ec5f9-278d-401d-87b1-f5c5fa708723.png)

I propose that the leftmost car wash icon be removed (there doesn't need to be two there) and/or the Z-Index for the wrench icon place it above the car wash one.
![Lost Compound After](https://user-images.githubusercontent.com/84351858/125462323-5ca410de-9725-4944-b87d-87d9e44c77cd.png)

**Reason:**
Why would your suggestion be a good change to the framework?
Mechanic shops are more valuable to the citizens than a car wash and thus should be more visible.

**Comment by InZidiuZ** [comment]
The 'repair shop' blips will now be prioritized over other blips and I also removed the secondary 'car wash' blip that was previously colliding with the 'repair shop' blip as suggested.
