### ISSUE TITLE
Bug Report: can hear neighbors in the house next to us

### ISSUE THREAD

**Issue by RavenHeartedFox** [InZidiuZ/op-framework-issue-tracker#1923]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
CrowEyedWolf

**Summary:**
While standing in my house, as Ashlyn Bell I was able to hear my neighbors next to me and they could hear me. 

**Steps to Reproduce:**
Have both myself and my neighbor in our houses at the same time and be talking to each other 

**Expected Results:**
We should not be able to hear each other 

**Actual Results:**
We can hear each other 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
1920 x 1080

**Player Data:**
Am currently on mobile and unable to take screenshot. But will be happy to provide one if asked. 

**Server:**
Legacy RP

**Notes:**

**Comment by InZidiuZ** [comment]
This issue should now be resolved. If it's still an issue after the next update, please reopen this issue or create a new one.
