### ISSUE TITLE
[jobs/go_postal] Making GoPostal more interesting and fun

### ISSUE THREAD

**Issue by MaximMitrofanov** [InZidiuZ/op-framework-issue-tracker#1924]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? **Yes**

**Summary:**
GoPostal at where it stands now is a bit boring and tedious, although the premise will stay the same (deliveries duh...), some changes might make things more interesting and dynamic,
What bothers me precisely? the job is static and linear, it gives the player no freedom nor sense of actually doing something,
I have few options in my mind, stuff that might be harder to implement and stuff that can be easier to implement,
Let's start with the easy suggestion, 
I don't remember how many deliveries there are per run but lets say 8, currently you deliver one package and getting a new destination in approximately the same area but sometimes even further areas, the easy implementation that can increase player creativeness and choice is showing all 9 deliveries at the same time and letting the player decide which route he/she would take to perform the task the fastest and not backtracking.

Second suggestion and it's a bit harder to implement but pretty easy imo is regarding the linear structure of having one marker at a time is having 2 deliveries in a walking distance from each other,
It's easier to give an example, the player arrives to their first destination, the player has given the first package and the second package would be in a predetermined radius that is a walking distance from the first delivery, but the third the delivery should be at a driving distance, so basically having a distribution area of a walking distance every two packages, (2 one area, 2 another area, ect.)

Third suggestion is giving the player a choice of a delivery area, having some UI that gives u all the possible routes (Los Santos, Sandy Shores, Paleto Bay) and paying according to how far are the delivers.

Final suggestion is regarding the payouts, we all know why people do the garbage job, why not having in some way a prize system in the GoPostal as well, for example having a really low percentage of the package getting lost / not picked up or the invisible owner didn't claim the package as theirs and having that package and the content rewarded to you, maybe sometimes getting precious stuff and sometimes getting nothing.

**Reason:**
I think some improvements can be made to existing jobs, and after playing around with GoPostal I think those ideas can improve it and give it some more meaning and fun behind it, overall I think people wills tart working more at GoPostal and the city will look more dynamic regarding jobs and not a trash filled city since there are so many garbage workers (lmao)

**Comment by MaxFunoff** [comment]
Just a mockup I added for area selectionin suggestion 3
https://streamable.com/hij26d
