### ISSUE TITLE
[game/darts] Add Ability to Play Darts

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1925]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add the ability to play darts and tally scores to dart boards throughout the city,
Example/Starting Point: https://forum.cfx.re/t/standalone-play-darts-with-your-friends-on-your-own-rules/2583472

Note: I will be happy to donate the Tebex fee to aid in this development.

**Reason:**
Why would your suggestion be a good change to the framework?
To add an additional activity and encourage people to spend time in pubs, clubs and other areas of congregation/socialization.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
