### ISSUE TITLE
[game/doors] Allow Gates and Garages to be either locked in the Open or Closed position

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1926]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Currently all doors can only be locked when closed.  My proposal would be to allow gates and garage doors to be locked in either the open or closed states. This way when businesses are open they clearly appear to be and people will not have to wait for doors.

Affects:
Exterior gates and Garage Doors
Regular building doors should remain as-is.

Process Flow:
If the door is currently open or in the opening animation and 'E' is pressed. Door will lock in the open state.
If the door is closed or in the closing animation and 'E' is pressed. Door will lock closed.

**Reason:**
Why would your suggestion be a good change to the framework?
This would allow for the following:
- Better flowing of traffic. 
- Act as the equivalent of a "Now Open" sign
- Prevent garage door open/close audio spam
- Reduce dependence on frequent proximity checks
- Potentially reduce positional updates between client and server for door states.

Note: There is another open gate ticket that might be aided with this. #1892

**Comment by MetaHatter** [comment]
Note: May be duplicate/extension of #1904

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
