### ISSUE TITLE
Logs Entry for /tp commands into the panel

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1927]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Adding an entry to the player logs when the /tp commands are used just like /noclip.
**Reason:**
Why would your suggestion be a good change to the framework?
Would be helpful to see if the someone is using /tp for admin work or just misusing it for just their benefits.

**Comment by InZidiuZ** [comment]
This has now been done.
