### ISSUE TITLE
[?] Add the ability to throw stuff

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1928]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I would propose the ability to pick up and throw props and potentially downed/dead peds.  Obviously only whitelisted items with throw force specified on an item by item level.

Potential starting points might be here: https://github.com/OfficialNoms/qrp_throw or https://forum.cfx.re/t/release-paid-gta-throwprop/3612663

**Reason:**
Why would your suggestion be a good change to the framework?
There are several possible advantages to this
- Dead locals sitting in the middle of businesses could be "removed"
- Props that are in the way or have fallen and block garage doors, etc can be moved
- Throwing bottles in a bar fight?
- "Removal" of inconvenient propane tanks in certain garages
- Teddy Bear fights!
- Dumping of bodies (allegedly)
- Throwing weapons/drugs/contraband away while running?

Obviously these are "some" options but the feature itself opens up many more possibilities

**Comment by AdeptCL** [comment]
I really like this idea. Especially the idea of throwing contraband, or even some form of weaponry when involved in a bar/street fight.

**Comment by twooot** [comment]
You can now pick up locals

**Comment by twooot** [comment]
You can now throw em too. Like discussed imma close the issue with this
