### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1929]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
o0ochanceo0o

**Summary:**
Write a short summary of what you are experiencing.
Custom maps are not working in FiveM right now.  Can we add something to the server that shows the map and street names?  Right now when we look at the map the street names do not show up anymore (i.e. custom map packs aren't working right now).  Here is the map I used to use before the FiveM issue:
https://dielikekane.com/2017/05/10/dlk-hd-satellite-map-for-fivem/

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is not a bug report. Follow the templates correctly.
