### ISSUE TITLE
Ability to hide chat

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-issue-tracker#193]
**Name:**
Anderzenn#0069

**Summary:**
Option to hide chat

**Reason:**
I would like to be able to hide the chat, since people writing in /ooc can be really annoying and bothersome and also ruin immersion. So the possibility of turning off either /ooc or just chat in general. Would be really nice.

**Comment by RoyalWolfXD** [comment]
This is a great idea, the ability to switch off at least OOC would help player immersion and reduce OOC bickering instantly. If it can be done while still having announcements and Staff PMs that would be optimal in my opinion.

**Comment by InZidiuZ** [comment]
Hey,

I've added the ability to disable OOC chat by doing "/oocoff" (/oocon to re-enable), and also the ability to locally clear your chat using /cls.

**InZidiuZ**
*OP-FW Developer*
