### ISSUE TITLE
PD Vehicle Tracker Glitch!!!!

### ISSUE THREAD

**Issue by zackosaiyajin** [InZidiuZ/op-framework-issue-tracker#1930]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/zackosaiyajin/

**Summary:**
Write a short summary of what you are experiencing.
Jewellery Store was triggered and i thought of putting the vehicle tracker in the robbers vehicle but in the chase that vehicle tracker became a type of gps marker in map.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://media.discordapp.net/attachments/799191457852293150/865284432490266694/unknown.png?width=854&height=480

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
What server and when did this happen?

**Comment by zackosaiyajin** [comment]
On Legacy Roleplay India/Nepal Whitelist at July 15.

**Comment by InZidiuZ** [comment]
This has most likely already been fixed, then. Wait for the prod update on Tuesday and if it's still an issue then, reopen this issue or create a new one.
