### ISSUE TITLE
Facemasks to fit with the bigger faces

### ISSUE THREAD

**Issue by itsmedeimo** [InZidiuZ/op-framework-issue-tracker#1931]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
The ability to be able to have the following mask from the screenshot to fit properly with the bigger/chubbier faces. I have talked with stuff for a plastic surgery but their suggestion was to create a bug report here instead of a plastic surgery for a character who has lived in the city for a while.

**Expected Results:**
What are the expected results?

## Additional Information

**Screenshots:**
![Screenshot](https://i.imgur.com/BDWNKgk.jpg)

**Server:**
LegacyRP

**Comment by DaxterPancake** [comment]
This is not the correct issue tracker.

This has also already been suggested.

Cheers,
Daxter.
Project Manager.
