### ISSUE TITLE
[?] Add Mail Delivery non-whitelist job to Paleto, grapeseed and sandy shores

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1932]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
All of the non-whitelist jobs are focused on the main city (aside from trucking).  I propose adding a job unique to Paleto Bay, Grapeseed and Sandy Shores to deliver mail based on the below script.

Potential Starting point script here: https://forum.cfx.re/t/maildelivery-v1-0-2-standalone-mail-delivery-job-for-paleto-bay-grapeseed-and-sandy-shores-extra-esx-addon/168076/64 

**Reason:**
Why would your suggestion be a good change to the framework?
Currently Sandy, Grapeseed and Paleto are largely ghost towns and the newer players have limited incentive to visit them (or leave the city at all).  Adding a new (or moving an existing) whitelist job will help spread the population out to the lesser visited areas.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
