### ISSUE TITLE
Suggestion Remove or Alter the cop count on Raspberry

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#1933]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**

There is really no reason to know an exact amount of cops on duty other than to see if a bank or jewelry store could be hit.  IMO it should be removed in general.  If it's kept it could be changed to show low, medium, or high cop presence.  Low would mean there isn't enough cops on duty to do jobs, Medium would be there is enough for 24/7 stores, and High would mean Banks and Jewelry stores are able to be hit.

**Reason:**
Why would your suggestion be a good change to the framework?
because there is really no RP reason to know the exact amount of cops who are on duty it's been abused by individuals trying to take a cop on duty and forcing them into unrealistic situations simply because they know there is only 1 cop on duty.

**Comment by ultrahacx** [comment]
This has been resolved in the latest push. It is already live on test server and will be live on all servers after Tuesday's global restart.
You can tes it and let me know if you feel like any futher changes should be made.
