### ISSUE TITLE
[?] Adjust /impound (and maybe /repo) to call a tow w/despawn timer

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1934]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Alter the police/PDM /impound command to automatically call a tow, optimally while specifying a (capped) reward amount.  If a tow does not show after X minutes then despawn the vehicle.

Hypothetical process.
- Officer needs a car towed.
- Types /impound [tow_payment] (defaults to amounts/nearest if none specified)
      - /impound 0 or /impound force can be used when required to immediately clear vehicle but logged to prevent abuse.
- All items are despawned from the vehicle's trunk/glove box and doors are perma-locked
- Signal goes out to tow drivers to pick up and (5-10 minute?) timer starts
- If car is on a tow truck within time allotted, stop the clock, if not despawn vehicle.
- Specified Impound value is paid to tow driver by the impound lot cashier.

This may possibly also add value, by bringing tow, to #1860
Potentially also add to /repo if the car is in city to allow a tow driver a chance to recover a PDM car for non-payment

**Reason:**
Why would your suggestion be a good change to the framework?
Local impound has been abused by people to just get the car out of the way instead of the more RP friendly, albeit slower, tow call.  

This would simplify the process and allow the officer to be on their way while allowing tow drivers to be compensated more than the possible $26 for a local car.  It would also add more for tow to do now that there is a surplus of drivers with the addition of state tow.

**Comment by milan60** [comment]
Doesn't this kind of avoid rp cause officers will just /impound and not wait instead of calling a tow, waiting a bit and then /impound'ing the vehicle?

**Comment by MetaHatter** [comment]
> Doesn't this kind of avoid rp cause officers will just /impound and not wait instead of calling a tow, waiting a bit and then /impound'ing the vehicle?

Covered that in the ticket.  That's occurring already.  Nothing would prevent PD from staying on scene for RP.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
