### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Deaddro** [InZidiuZ/op-framework-issue-tracker#1936]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Mayor and deputy mayor need some special
Vehicle to improve there rp and to make it more realistic,If you can add this it will be helpful.

https://www.gta5-mods.com/vehicles/cadillac-the-beast-presidential-state-car-add-on

https://www.gta5-mods.com/vehicles/cadillac-escalade-president-one-limosine

**Reason:**
Mayor and deputy mayor need some special
Vehicle to improve there rp and to make it more realistic,If you can add this it will be helpful.

**Comment by InZidiuZ** [comment]
This is an assets thing and would have to be reported on [this issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
