### ISSUE TITLE
[?] Add Multiplier to Local/Scuffed Tow based on distance

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1937]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add a multiplier of 1-4x to the towing of local or scuffed vehicles based on the distance to the nearest impound lot.

Process
When a car is added to a truck via /tow (or hooked for hook trucks), calculate the distance to the nearest impound lot.

Add a multiplier to the car payout (property?) based on the below:
  - If under 1 mile - 1x multiplier - Maintains ($25-100 payout)
  - From 1-4 miles - multiplier based on range 
      - i.e. For a car that is added via /tow 1.3 miles from impound, 1,3x the local rate would be in the $32-130 range
      - i.e. For a car that is added via /tow 2.6 miles from impound, 2,6x the local rate would be in the $65-260 range
  - Over 4 miles - 4x multiplier - creates a range of $100-$400 for a long distance tow based on the $25-100 price range.

If the car is untowed/unhooked, reset the multiplier on the car to 1.

**Reason:**
Why would your suggestion be a good change to the framework?
Currently there is a shark pool of tow truck drivers that circle the Pillbox/PDM/Impound area waiting for the next police/private tow while areas near Burgershot or Mirror Park go ignored.  Adding a minor incentive to longer distance tows would spread them out a bit more and reduce the law-breaking mad dashes and over-reliance on PD calls.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
