### ISSUE TITLE
[?] Emotes for couples

### ISSUE THREAD

**Issue by DeadZombieGirl** [InZidiuZ/op-framework-issue-tracker#1938]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes, I did.

**Summary:**
Write a summary of what your suggestion is about.
More emotes that are for couples (especially shared emotes), for example kissing.

**Reason:**
Why would your suggestion be a good change to the framework?
There are a lot of people engaging in romance RP but the range of emotes that would help with that kind of interaction is very limited. New emotes for couples especially shared ones would definitely add a lot to that kind of RP. :)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
