### ISSUE TITLE
[game/inventory] 'use' shortcut to mb3 or other buttons

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#1939]
**Assurance: Have you read through the rules from the README.md file in the root folder of this GitHub repository?**
Yes

**Summary: Write a summary of what your suggestion is about.**
Let people use their middle mouse button (press scroll wheel down) on an item in their inventory to use it as a shortcut to dragging to use.

**Reason: Why would your suggestion be a good change to the framework?**
It would let people use stuff faster, and sometimes depending on someone's machine the dragging animation in inventories can lag, so this would help speed the ability to use things up for everyone.

**Comment by InZidiuZ** [comment]
I can't believe this simple yet great suggestion has been buried for 4 months... 🤦

**Comment by InZidiuZ** [comment]
This has now been added. [Here's a gif](https://gyazo.com/4c42606ce6121bd6fcd9f7707f271e4e) of the feature.
