### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Grimbooze** [InZidiuZ/op-framework-issue-tracker#194]
**Reporter:**
Who is reporting this? Please include discord name.
Grimbooze
**Summary:**
Write a short summary of what you're experiencing.
Whenever I disconnect my facial hair disappears the next time i log on
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Get any beard or mustache at the barber, disconnect, come back to see if it is still there or not
**Expected Results:**
What are the expected results?
for my beard to stay until i change it
**Actual Results:**
What are the actual results?
Doesn't show up when i come back online, still says i have the beard option selected when i go to the barber shop
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1080p
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID:491 Job data: Transportation, trucker, amatuer
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
What player model are you using?

**Comment by InZidiuZ** [comment]
Hey,

At some point in the future, the entire clothing system will be rewritten, also resolving these issues, but it will not be worked on for the time being, so will close this.

**InZidiuZ**
*OP-FW Developer*
