### ISSUE TITLE
[vehicles/garages] Aircraft spawner issue

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1941]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? **Yes**

**Player Identification:**
What is your steam profile? **https://steamcommunity.com/id/Spitfire2k6/**

**Summary:**
Selecting the Tula from **ANY** aircraft spawner pulls out a broken invisible version that throws an error and causes a crash if you try to enter it.
EDIT: Upon further investigation this seems to be happening with more vehicles. So far the Bombushka and Volatol. There is also an issue with crashing when entering the Molotok

**Steps to Reproduce:**
Go to any plane spawner and pull tula from Military section.

**Expected Results:**
Tula appears in sawn location

**Actual Results:**
Semi invisible boxes appear where the Tula should be. Entering the Tula causes a crash.

## Additional Information

**Videos:**
https://www.youtube.com/watch?v=b7oETa9yArk
https://youtu.be/prv4fH8llNY

**Game Resolution:**
What is your game's resolution? **2560*1440**

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/32903722/126758871-9a994564-96bb-47fa-a1a1-c75ddcc21538.png)
This is from test.

**Server:**
What server/community did this issue occur in? Test and NA/EU

**Notes:**
This only started happening on the last update where a few new helicopters were added.

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
