### ISSUE TITLE
[weapons/?] Guns have no ammo and/or can't be reloaded

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1942]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
**What is your steam profile?**
Nuzi

**Summary:**
**Write a short summary of what you are experiencing.**
The following guns currently have unplanned features of having no ammo and can't be reloaded normally:
```
bullpup rifle
compact rifle
machine pistol
mini smg
gusenberg sweeper
combat pdw
heavy pistol
marksman pistol
heavy revolver
double barrel shotgun
sweeper shotgun
heavy shotgun
taser

```
When you pull out the gun it shows 0/0 ammo and will fire at a high rate even though it has no ammo. Once you stop firing the gun will no longer fire. If you reload it with more ammo, it will allow you to fire again but once you reload or stop firing it will go back to 0/0 and you will once again no longer will be able to fire the weapon. 

**Steps to Reproduce:**
**Include what steps that are needed in order to reproduce this issue.**
Pull out any of the guns listed above and attempt to fire it. Reload weapon with ammo and fire again.

**Expected Results:**
**What are the expected results?**
Guns to track current ammo amount and to not show 0/0 and not operating correctly when reloaded.

**Actual Results:**
What are the actual results?
As mentioned in the summary. Guns do not read current ammo and show 0/0. If you reload they'll go back to 0/0 after you fire the gun and/or reload.

**Screenshots:**
**If suitable, include some screenshots.**
n/a

**Game Resolution:**
**What is your game's resolution?**
n/a

**Player Data:**
**Write '/info' whilst in-game and provide a screenshot of the information you are prompted.**
n/a

**Server:**
**What server/community did this issue occur in?**
International and OP-FW Test Environment Server

**Notes:**
**For anything else noteworthy.**
Hi, my name is Nuzi.

**Comment by DaxterPancake** [comment]
Could this also be what is causing the tazer to not fire?

**Comment by Nuziatella** [comment]
Ah yes, forgot about that one. Let me add it to the list

**Comment by InZidiuZ** [comment]
This issue should now be resolved.
