### ISSUE TITLE
[?] Suggestions For /tow job

### ISSUE THREAD

**Issue by LesterNester** [InZidiuZ/op-framework-issue-tracker#1943]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Increase salary of /tow job.
And increase locker storage capacity.
Please add some clothes which is dedicated to Los Santos Customs.

**Reason:**
Why would your suggestion be a good change to the framework?
It will increase rp and people's interest in LSC job .
Materials are heavy . 500 is not enough for mechanics.

**Comment by InZidiuZ** [comment]
The hourly salary probably won't be increased for any job as it's obsolete. Why does lockers need increase capacities? Also, clothes would be an assets thing for the assets issue tracker.

**Comment by AdeptCL** [comment]
Each material is currently at a weight of 5. That means a locker can hold 100 pieces of any material (scrap metal, steel, aluminium, glass, or rubber). For a locker, this is sufficient. It suits what size it should be correctly.

There are ways within roleplay that you can also help with this. An example is housing. Look into purchasing a house nearby, this means you can now hold more materials at a close location.

**Comment by DaxterPancake** [comment]
Locker storage should not be increased as it increases the likelyhood of it being abused for other items that aren't mechanic metals.
