### ISSUE TITLE
[?] /impound for tow job

### ISSUE THREAD

**Issue by LesterNester** [InZidiuZ/op-framework-issue-tracker#1944]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
/impound which is available for EMS , PD , PDM bring this command available for tow job .
**Reason:**
Why would your suggestion be a good change to the framework?
It will help to tow big vehicles which is look silly for trucks & for some buged cars

**Comment by T4NZIM** [comment]
You are a mechanic to tow vehicles, not use /impound, and also you are talking about towing big vehicles and bugged vehicles, a lot of people will misuse this power, fr! So big -1 from my side

**Comment by LesterNester** [comment]
It's up to u if u for an example if u are a police u can also misuse this command .

**Comment by twooot** [comment]
As a tow driver you are supposed to tow the car not use a command to make it poof
