### ISSUE TITLE
Super Admin ( Can't Spawn for everyone) 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1947]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

*Summary:**
When trying to spwan some kind of item for everyone there is a error saying https://prnt.sc/1gtxjz2
Example: /si weapon_fireworks 1 -1
If I write -1 it says, Could not find player with the ID -1

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
