### ISSUE TITLE
[game/phone] Add A HotLine For Pilots ( Aviation) 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1948]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Usually to get a Pilot we need to tweet it out or ask them on Instagram. Adding a HotLine will make it easier to respond to calls as a Pilot & it will create a bit more RP.

**Reason:**
https://prnt.sc/1gtyic2

**Comment by Spitfire2k6** [comment]
If this is for Legacy International it wont help as the phonelines are tied to jobs.
The LSA jobs are not active atm.

**Comment by InZidiuZ** [comment]
There is no pilot job as @Spitfire2k6 said, so we'd have to wait until the new phone and create some system there.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
