### ISSUE TITLE
Chop shop requesting vehicles in Cayo Perico island

### ISSUE THREAD

**Issue by richuvc** [InZidiuZ/op-framework-issue-tracker#1949]
**Assurance:**
Yes

**Player Identification:**
76561198165071466

**Summary:**
Vehicles from the Cayo Perico island are coming for chop (such as Verus, Manchez, Blazer2 etc) with the location said to be at either uncharted territory or pacific ocean at street. 

**Steps to Reproduce:**
Have chop radio and wait

**Expected Results:**
Chop cars come which are available in city

**Actual Results:**
Many times cars come from Cayo Perico which is not obtainable and leads to huge gaps of people not doing chop

**Server:**
Legacy RP

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
