### ISSUE TITLE
Vehicle Added: Kamacho

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#195]
**Name:**
SteezyRen#2828

**Summary:**
Adding of the Kamacho. GTA DLC Vehicle that shouldn't be hard to add and a great car to have.

**Reason:**
I think it adds to variety on vehicles to expect at PDM and I think it's a great car overall. Used to have one and loved everything about it.

https://www.gtainside.com/en/sanandreas/cars/119268-gta-v-canis-kamacho/
![8442-38187267055-5f5af792a1-o](https://user-images.githubusercontent.com/49498560/61109658-47224f00-a43a-11e9-9e0e-22fb68c46205.jpg)

**Comment by InZidiuZ** [comment]
Hey,

This is a suggestion for @Karpenko, get in contact with him.

**InZidiuZ**
*OP-FW Developer*
