### ISSUE TITLE
Suggestion/bug

### ISSUE THREAD

**Issue by Codemonkey098** [InZidiuZ/op-framework-issue-tracker#1950]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Basically my suggestion is to remove the thermal camera from the police helicopter or fix it so it does not see people through buildings or behind solid objects. 

**Reason:**
Why would your suggestion be a good change to the framework?
This would be a good change because currently cops are abusing the thermals to track people anywhere they go no matter where they hide the heli will always give out th location which isn't realistic at all. Especially when you're in a concrete building.

**Comment by DaxterPancake** [comment]
Closing due to only suggesting this due to OOC salt.

Instead I would suggest speaking to the community managers if it's actually being abused.

Cheers,
Daxter.
Project Manager
