### ISSUE TITLE
[jobs/weazel_news] Weazel Heli spawner change

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1951]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Change Heli spawner access from Weazel job to H-cert pilot role.

**Reason:**
Why would your suggestion be a good change to the framework?
From what I have heard, uncertified pilots can spawn helicopters using the Weazel News job without having the pilot certification.  Changing the precondition for the spawner to require the H tier certification would prevent random people flying around the city.

**Comment by azpranto** [comment]
In our subdivision, weazel news is a whitelisted job. So, all the people cannot use that except news employees. So, this might be solved if they make it whitelisted.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
