### ISSUE TITLE
[?] Vehicle spawner or car renter service type thing in Cayo Perico

### ISSUE THREAD

**Issue by Rehan0007** [InZidiuZ/op-framework-issue-tracker#1952]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Summary:**
Write a summary of what your suggestion is about.
Adding a vehicle spawner or car renter service type thing in Cayo_perico.
**Reason:**
Why would your suggestion be a good change to the framework?
Well, in RP when you reach Cayo_perico  you have no way to get a road vehicle other than hotwiring. Now if you think about other RP like police, state employee, good citizens they will also have to hotwire a vehicle and it just ruins the RP. Police don't steal a vehicle and if they do it turns into a fail RP. So adding a car rental type service in Cayo_perico will allow everyone to get a road trip without stealing anything. Thanks.

**Comment by twooot** [comment]
I added garages over there a while back which should resolve this issue
