### ISSUE TITLE
[game/airports] Add Cayo heli garage

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1953]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Write a summary of what your suggestion is about.
Helipad on Cayo needs a garage like as LSIA

**Reason:**
Why would your suggestion be a good change to the framework?
Some pilots going to cayo are not certified for fixed wing and so are stuck if their heli gets lost.

**Comment by twooot** [comment]
This was done
