### ISSUE TITLE
[?] City Jobs pay scale

### ISSUE THREAD

**Issue by WhiteOut03** [InZidiuZ/op-framework-issue-tracker#1954]
**Assurance:**
Bring good paying jobs to the hard working citizens

**Summary:**
Implement a tier system to the pay scale of the jobs in the city, ext. Trash, Deliveries, Trucker.  Start out at flat rate pay such as 20 a hour, depending on deliveries made your hourly pay goes up.  Example: Tier 1 = 25 loads pay goes to 23 a hour, Tier 2 = 75 loads pay goes to 26 a hour.  Could make a 4-5 tier system to where it ends up being more money on the hour considering deliveries delivered.  Have the system reset bi-weekly or monthly

**Reason:**
Honestly, I have been in city for a few months, really enjoy playing, have even brought in a few friends.  Besides robbing banks and jewelry our only source of income in trash.  Just think it would be a good step ahead for people in the city that just isnt yet ready to join the gang life but also wants to enjoy their time and be able to buy the nicer vehicles and houses.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
