### ISSUE TITLE
Edm givecar option 

### ISSUE THREAD

**Issue by Deaddro** [InZidiuZ/op-framework-issue-tracker#1955]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There should be a give car option with edm cars because we can’t give edm cars
**Reason:**
Why would your suggestion be a good change to the framework?
There should be a a give car option with edm cars because then we can sell and buy edm cars like pdm cars

**Comment by InZidiuZ** [comment]
They are intentionally excluded from the normal /givecar command, so no.
