### ISSUE TITLE
[?] Need specific impound power for helicopters and planes in aviation license 

### ISSUE THREAD

**Issue by Deaddro** [InZidiuZ/op-framework-issue-tracker#1956]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There should be a impound power that can only impound helicopters and planes in aviation license  then we can impound plane’s and helicopters because with out helipad we can’t impound helicopters and planes
**Reason:**
There should be a impound power that can only impound helicopters and planes in aviation license then we can impound plane’s and helicopters because with out helipad we can’t impound helicopters and planes,if you can add impound power in aviation license  it will be helpful for aviation rp

**Comment by T4NZIM** [comment]
Aviation isn't a role, and powers can be added to a role I guess. Normal civilians can have this aviation license. So if it's given, there's a high chance people will misuse it.

**Comment by Deaddro** [comment]
@T4NZIM i don’t think so because specific people only get this role only pilot get this role so i don’t think so misuses of it and aviation role need this power

**Comment by T4NZIM** [comment]
Again it's not a role

**Comment by Deaddro** [comment]
@T4NZIM i know it’s not a role but only pilot can get it

**Comment by Deaddro** [comment]
@T4NZIM i think there should be a impound power but that can only impound planes and helicopters.

**Comment by Smach90** [comment]
I think the impound ability is tied to jobs. Not a role. Since there isn't an aviation job I don't think it can be implemented but I could be wrong. Anyways there are garages to store airplanes and helicopters.

**Comment by Deaddro** [comment]
@Smach90  I think InZidiuZ  better know then us

**Comment by Spitfire2k6** [comment]
Pilots have no need to be able to impound aircraft, that's why there is a park function with the spawners.

**Comment by twooot** [comment]
What spitfire said
