### ISSUE TITLE
[jobs/dealership] Add oversized vehicle slot to outside of PDM

### ISSUE THREAD

**Issue by Nuziatella** [InZidiuZ/op-framework-issue-tracker#1957]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
**Yes**

**Summary:**
Write a summary of what your suggestion is about.
**Add another slot outside of PDM for large vehicles. This will enable large base game vehicles to be spawned and purchased.** 
![image](https://user-images.githubusercontent.com/67765305/128212494-9d00198b-43c2-4997-9ae9-69414bdc07f7.png)

**Reason:**
Why would your suggestion be a good change to the framework?
**Currently the framework lacks the ability to spawn large base game vehicles at PDM as the interior is to small to allow them to be spawned inside. Placing an outdoor slot will enable the ability thus allowing PDM to spawn any vehicle available to the base game. Before there wasn't a good spot to add a slot without being disruptive. Now that the back area has been closed off and the slot can be kept clear, this should no longer be an issue.**

**Comment by MetaHatter** [comment]
Another idea would be to put it on the corner outside using a car display ramp:
https://www.carlotstore.com/vehicle-ramps.html

There's enough physical room out there and might get people to stop and look (good for business).

**Comment by Jabadab** [comment]
This hasn't been touched for a while, but I do agree this would be very beneficial, there are many oversized vehicles I've had people ask to buy that we simply do not have as it is too big to fit within the store. #

The photo below could also be a place to put these vehicles, although it may be a bit tight, with this, the option to be able to set a slot to "none" to keep empty while not being used would be perfect for this particular spot, so anyone looking for larger/longer vehicles can be told to "come around the back" to be showcased said vehicles.

![image](https://user-images.githubusercontent.com/81594664/152664933-17ede26f-3a1d-4044-964d-ac7872be3646.png)

Some of the vehicles people have requested to buy, but haven't been able to:

Benson
Pounder
Festival Bus (This could be rented out for events, or blacklisted for business owners)
Vetir (Potentially blacklisted as military and a 10-seater.)
Stretch & Patriot Stretch (limos are cool!)
Fieldmaster (rednecks and their tractors..)
Bus & Dashound
Rental Shuttle Bus & Tour Bus

**Comment by SirPiff** [comment]
Another good place I found for this would be here, probably a lot more space and open.
![download (1)](https://user-images.githubusercontent.com/52291249/152708707-4c1cf19c-faee-4a98-baec-4ff22eaac5a0.png)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
