### ISSUE TITLE
[game/doors] Change Garage/Gate lock key bind

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1958]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Change the key bind for locking garage doors/gates to another key (i.e. "R")

**Reason:**
Why would your suggestion be a good change to the framework?
In small quarters, garage doors and gates are easily unintentionally toggled., Especially in garages where the "E" key is used on many occasions.  This is exceptionally frustrating. Simply reducing the range will not work due to the distance required to lock a garage door.

**Comment by Gingerninja78** [comment]
this would be especially usefull at Hayes where anyone can use the water pumps outside and if they have the towing/mechanics job they unlock the doors and might not notice so the shop is then open, when in fact there is nobody there

**Comment by xarxesthegreat** [comment]
we also have this issue at mosleys because of how close our wash pumps and workbench are to the doors. everytime we use the workbench we lock a door

**Comment by InZidiuZ** [comment]
Switching the button to something else isn't really a good solution as there will almost always be collision with other current (and future) features. A permanent solution would probably be to have a way to press the door itself with your mouse, but for now I won't be changing the button.

If you can make a list though where collisions do happen, I can disable the door locks while you're near the other features.

**Comment by Enryy** [comment]
From what I know in theory via settings - combinations of commands and go to 'Fivem' you could put the option to customize the commands to your liking .. for example if you want inventory on f2 instead of K or open doors with r instead of e

**Comment by MetaHatter** [comment]
The garage doors for the Lost, Harmony and Hayes are the most obvious examples.  Try to fix an engine in any of those shops and you end up locking/unlocking the doors.

Perhaps just as simple as hiding "lock/unlock Door" if the "Repair Engine" option is available so people can't simultaneously trigger both.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
