### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by xarxesthegreat** [InZidiuZ/op-framework-issue-tracker#1959]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile? https://steamcommunity.com/id/_xarx/

**Summary:**
This is specifically about the Obey 8F Drafter. The handling and braking on this car are absolutely abysmal, and the top speed is less than what one would expect. For a $160,000 car in the city it leaves a lot to be desired. No matter what height you set the suspension to on the drafter it does not want to turn.

**Steps to Reproduce:**
Driving a drafter

**Expected Results:**
Being able to turn and stop in a reasonable distance.

**Actual Results:**
The car handles like a large mouth bass trying to navigate inside of a tupperware container. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920?x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted. https://imgur.com/WbgnOqJ

**Server:**
What server/community did this issue occur in? NA/EU

**Notes:**
For anything else noteworthy.

**Comment by Spitfire2k6** [comment]
This is an issue for the [assets git](https://github.com/InZidiuZ/legacy-assets-issue-tracker). Please remake this ticket there and close this one.

**Comment by DaxterPancake** [comment]
As said above, please move this to the correct github.

Cheers,
Daxter.
Project Manager.
