### ISSUE TITLE
Motorcycles vanish after body repair (again)

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#196]
**Reporter:**
Scrubject#1646

**Summary:**
After most recent update, Motorcycles once again vanish after being repaired (body repairs) presumably spawning on the roof of the mechanic cell. I know this happens with the Wolfsbane, Zombie Chopper, Avarus, and Bagger firsthand.

**Comment by InZidiuZ** [comment]
Hey,

Instead of having a set spawn-offset we now use model dimensions to get a specific offset for different vehicles, which should resolved this issue.

**InZidiuZ**
*OP-FW Developer*
