### ISSUE TITLE
Allow X to cancel smoking weed/cigarettes and potentially /tow and /flip

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1960]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Allow X to cancel smoking weed/cigarettes
Potentially allow "X" to cancel /tow and /flip

**Reason:**
Why would your suggestion be a good change to the framework?
Updated ticket to better reflect current issue. "X" does not cancel smoking weed or cigarettes. 
There is also no current way to cancel a tow or flip. X would be a natural fit.

**Comment by iGreatWhite** [comment]
Doesn’t X already do this? I could be wrong but that is another good key to put it on if it doesn’t already.

**Comment by ChocolateNukkat** [comment]
Sometimes pressing the X key does not work and you are forced to type /e c

**Comment by milan60** [comment]
I have only encountered x not working when you are smoking weed, every other time it works normally.
@ChocolateNukkat @MetaHatter have you thought about just setting /e c to a command bind? idk if that works

**Comment by MetaHatter** [comment]
> I have only encountered x not working when you are smoking weed, every other time it works normally.
> @ChocolateNukkat @MetaHatter have you thought about just setting /e c to a command bind? idk if that works

I stand corrected.  Updated ticket to better reflect actual issue. Thanks.

**Comment by twooot** [comment]
I made X be bound to /e c by default now, that should fix the weed/smoking issue

**Comment by twooot** [comment]
Yeah and /tow can be canceled with escape
