### ISSUE TITLE
Adding Nagasaki Shotaro

### ISSUE THREAD

**Issue by PedroTheTurtle** [InZidiuZ/op-framework-issue-tracker#1961]
**Summary:**
The Nagasaki Shotaro is a beautiful bike and I think it would be great to see it on the server. 

**Reason:**
I have always been one to buy all the bikes in GTA because I prefer the bikes to the cars and the Shotaro is not available in-game so I just would like to see it added. I have been roleplaying as a die-hard fan of Tron and have been walking around the city dressed as such and I feel like this bike would complete my character.

**Comment by DaxterPancake** [comment]
This is the incorrect issue tracker.

Please re-create this on [THIS](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) tracker.

Cheers,
Daxter.
Project Manager.
