### ISSUE TITLE
Remove keys from jobs & add new system for keys

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1962]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Remove the keys to doors from a job and create a new system for keys.

**Reason:**
Why would your suggestion be a good change to the framework?
As it stands right now, you have to have a job that is assossiated with a paycheck in order to get keys to a buisness. This disallows you from doing certain avenues of roleplay like purchasing a building to own or working for multiple different businesses. 
By removing keys from a job and instead, creating a system like we now have for pilot licenses.. this will allow for a lot more different avenues of roleplay. 
It would allow people to actually work jobs for the roleplay instead of doing it just so they can lock the doors to their buisness. I personally work for both The Yellow Jack and also Vanilla Unicorn but can only have keys for one of those, despite doing the roleplay in order to work at both locations.
Staff would have to be the ones that give you keys thorough a command such as `/givejobkey <ID> <BUISNESSNAME>` and remove job keys with a command such as `/removejobkey <ID> <BUISNESSNAME>`.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
