### ISSUE TITLE
Suggestion: Add the Nagasaki Shotaro to the Server

### ISSUE THREAD

**Issue by ghost** [InZidiuZ/op-framework-issue-tracker#1963]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes i did 

**Summary:**
My suggestion is to add the Nagasaki Shotaro Bike to the game, like it is in GTA online.

**Reason:**
We already got the fitting Suit in the Legacy Server and it would be a nice addition to be able to buy the Nagasaki Shotaro and drive around with fitting Bike and Suit. 

Please consider adding it, thank you in advance for reading my suggestion <3

**Comment by Nuziatella** [comment]
This isn't the place for this. Go to [Here.](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

**Comment by DaxterPancake** [comment]
This is the incorrect issue tracker.

Please re-create this on THIS tracker.

Cheers,
Daxter.
Project Manager.
