### ISSUE TITLE
EMS Body Armor

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#1964]
**Name:**
superiorchicken#2703

**Summary:**
Looking to add EMS Body Armor into ems store.

**Link:**
N/A

**Reason:**
We have opened up our TECC (Tactical Emergency Critical Care) division under EMS which responds to active shooter situations with PD. Currently we have to drive to the Mega Mall to purchase Body Armor before responding to the scene. It will be much easier and make it quicker to respond to the scene without making an additional scene.

**Comment by twooot** [comment]
Idk how i feel about giving body armor to EMS. EMS aren't supposed to get shot, they are supposed to join the scene when things are cleared up

**Comment by superiorchicken007** [comment]
I know we are not supposed to get shot but it has happened in the past and we were downed.  That is the reason I requested it.

**Comment by twooot** [comment]
Yeah i dont think body armor is something that makes sense in an ems store
