### ISSUE TITLE
Add locks to Paleto Bay Repair Shop

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1965]
**Assurance:**
Yes ma'am.

**Summary:**
Add locks to all openings door at the Paleto Bay Repair Shop, internally and externally.

**Reason:**
The shop itself acts as a Clubhouse, but also as a fully functional mechanic shop. Every door within the shop should have the ability to be locked to allow the building to be closed when there is nobody present. The job it should be assigned to would be _mechanic_. 
If needed, I can provide screenshots of each door in the shop. There are 4 parts to the shop: the bar, the repair area, clubhouse area, and also the showroom area. All doors across all areas should have the ability to be locked.

**Comment by AdeptCL** [comment]
Just going to bump this again, please. A few additions have been added to other mechanic shops, we'd just like to request locks to doors.

**Comment by AdeptCL** [comment]
Hey, don't want to be a pain but it would be very helpful to have keys for this mechanic shop.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
