### ISSUE TITLE
Vehicles being stored will sometimes say "Vehicle stored" and not disappear.

### ISSUE THREAD

**Issue by TheEpTic** [InZidiuZ/op-framework-issue-tracker#1967]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
https://steamcommunity.com/id/TheEpTic/

**Summary:**
After a long period of time, couple of hours maybe, certain cars will no longer disappear when going in to the garage. It will say they've been stored but nothing happens to the car itself. 

**Steps to Reproduce:**
Pull a car out, wait a few hours, try store it. It's really dependent on the person and car as it happens to my Supra sometimes, but not to my friend's Supra.

**Expected Results:**
To store, and disappear.

**Actual Results:**
It claims to store, but doesn't do anything.

## Additional Information

**Screenshots:**
https://www.youtube.com/watch?v=9t6o38HDlIE

**Game Resolution:**
1920x1080

**Player Data:**
https://demented.fish/J3dtPUqOklHhiujmWPVkj2w53COjCA.png

**Server:**
EU/NA International

**Notes:**
The bug actually started occurring on the build around "8 Jul 2021" - I know this because I clipped that video right as it started happening, and thought someone else would of put in the bug report already. That should hopefully give you a good starting point with it.

**Comment by TheEpTic** [comment]
Hey, I also wanna weight in about how much this affects the servers. As staff, we're forced to noclip these cars to the open water as /dv doesn't work on them at all.

With all the imports that this happens to, I can only imagine how much strain this could have on people or the server itself.

Just thought I'd throw that in there in case it helped push this through.

**Comment by Sinister-Neonfire** [comment]
Personally this is one of my priorities to try isolate, along with the issue of head popping at the sandy chop. It's a tricky one though, as it's been difficult to reliably replicate the issue.

**Comment by twooot** [comment]
i'm pretty sure a lot of garage related issues have since been fixed with the recent updates
