### ISSUE TITLE
House Interiors too close | South Rockford Drive

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#1968]
**Assurance:**
Yes Sar

**Player Identification:**
https://steamcommunity.com/id/ItzBrittanyBitxh/

**Summary:**
Two houses with the same / very close interior. If a player  is in apartment 1, then the person in apartment 2 can see then and talk to them as if its the same house.

**Steps to Reproduce:**
Sell both houses to different people, and enter, they will see each other.

**Expected Results:**
Each interior is separate, where you cannot see or hear each other

**Actual Results:**
You can see and hear both parties in separate houses.

## Additional Information

Block: 51 Addy's: South Rockford Drive 4 / Apt1 +  South Rockford Drive 4 / Apt2

**Screenshots:**

https://imgur.com/a/SkM7J6l
https://imgur.com/a/IaE7MTs

**Game Resolution:**
1920x1080

**Player Data:**

https://imgur.com/a/OaS5Zqu

**Server:**

Na / Main

**Notes:**

Seems like the interiors are simply too close together or ontop of each other.. Maybe?

**Comment by InZidiuZ** [comment]
There is a basic system that attempts to move interiors apart, but I suppose it doesn't work that well if it's failing in this case. Since this we've 'muted' players who are in other properties. For now, not more will be done with this.
