### ISSUE TITLE
Add "DV" To Trusted Role 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1969]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
It would be nice to have the Delete vehicle option for trusted role. Making it easier if cars are blocking spwan point & sometimes /impound doesn't work on certain situation. So it would make it easier.

**Comment by InZidiuZ** [comment]
I agree, this has now been done.
