### ISSUE TITLE
[assn: damage control] Nerf hand-to-hand damage.

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#197]
**Name:**
Scrubject#1646

**Summary:**
I think it would be great to be able to get into fist-fights with players or locals, without the threat of essentially losing your life. My proposal is to either drastically reduce the damage that fists, and possibly even blunt weapons in general deal to players. Or to implement some kind of system that checks the type of damage that finished you off, either downing you (lethal) or possibly knocking you out for some time.

**Reason:**
It would be really nice to not be instantly destroyed when someone hits you with their bare hands.

**Comment by SteezyRen** [comment]
I would also like to see a nerf on melee damage. I need some fight nights in my life and currently one punch causes head trauma.

**Comment by Scrubject** [comment]
I'd really like this to be implemented so that I could try to set up some kind of fight club-esque, underground cage matches with betting, security and the works. I've been looking forward to a change that would allow this to happen for a while.

**Comment by InZidiuZ** [comment]
Damage levels for all weapons are currently being reworked. If you have additional feedback for improvements after 2.5, please create another issue.
