### ISSUE TITLE
Add Car Garages "near" Airport Hangers

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#1970]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a car storage garage near (within 0.5 miles of) the following: 
- Devin Weston hanger at KLSI
- Hanger at KSYD (Sandy)
- Hanger at Cayo Perico Airport

**Reason:**
Why would your suggestion be a good change to the framework?
Often, when flying away from the airport you return to no car. It had poofed.  This is especially true of Cayo trips.  Being able to safely store/retrieve a vehicle in a guarded garage will prevent you from being stranded due to the bug.

Alternatively. Make poofing stop, but garage might be simpler temporary fix. :)

**Comment by Spitfire2k6** [comment]
This could work as a solution to the car poofing issue but I think it'd be better to have the issue fixed rather than adding these garages. I don't like the idea of people being able to hide their cars in garages at the airports with how illegal licensing works.

**Comment by twooot** [comment]
We have a garage near cayo and a garage near lsia now. The garage in sandy is too close imo to add another garage
