### ISSUE TITLE
Adding clothing options and faces for a local character.

### ISSUE THREAD

**Issue by VinnyPistone** [InZidiuZ/op-framework-issue-tracker#1971]
**Assurance:**
Yes, I have.

**Summary:**
The local character I'm suggesting outfits and a few masks for currently has very few outfits but I think it's possible to add several outfits and masks for the character. P.S: I will be attaching the picture of the character down below.

**Reason:**
Currently. it's not quite possible to do certain RP scenarios with the currently available outfits.

Picture:
![20210706091408_1](https://user-images.githubusercontent.com/89471617/130646522-2b055b9c-2f95-410b-9ab9-a0dea40b85a3.jpg)

**Comment by DaxterPancake** [comment]
This is the incorrect issue tracker.

You need to post this in the [asset github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

Cheers,
Daxter.
