### ISSUE TITLE
[game/items] Add Camera to Tool Store

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1972]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Add a camera into the tool store that does the same thing as the PD camera except that anyone can buy it and use it.

**Reason:**
Why would your suggestion be a good change to the framework?
Currently we struggle with what we allow as 'valid' footage to use in RP. Can civilians wear body cams? Or should they have to pull their phone out? Adding the camera that PD has to the tool store would only add another avenue in RP that is valid for people to record/take photos of anything they'd like.

**Comment by claymstehling** [comment]
I love this!

**Comment by InZidiuZ** [comment]
This ahs now been added.
