### ISSUE TITLE
Make bins/trash cans/dumpsters searchable

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1973]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Allow bins/trash cans/dumpsters to be searched and find random items inside of them.

**Reason:**
Why would your suggestion be a good change to the framework?
This would allow more avenues of roleplay and would give an alternative to finding certain items. For example, being able to search a random bin and finding a weed seed (really rare find) to spread out the distubution and stop making a LEGAL job chaotic with illegal items. Not only that but adding melee weapons, food, etc.. To allow for homeless RP. This addition could then tie into other jobs/activities as you could continue to add items into it such as wine bottles, batteries, recipe items.. anything is possible.

**Comment by exclusivegirl** [comment]
Have you ever gone up to a dumpster and tried to place an item in it? You already can and anyone can then search that dumpster and find that item. I dont think it gives anything random, just what other citizens have thrown away in it.

**Comment by DaxterPancake** [comment]
I know that. That's not what I want the dumpsters to do. I want every trash can and dumpster to be searchable and have a chance to have random items in it. Not items that people have put in there.

**Comment by twooot** [comment]
I mean this is pretty much exactly what the garbage job already provides

**Comment by claymstehling** [comment]
> I mean this is pretty much exactly what the garbage job already provides

This is true, but the suggestion would allow for everyone regardless of their job to search it. :D

**Comment by twooot** [comment]
This has been done
