### ISSUE TITLE
Selling of metals in bulk

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1974]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Allow us to sell metals, rubber, glass in bulk like you can with watches, necklaces, etc.

**Reason:**
Why would your suggestion be a good change to the framework?
It would be a quality of life thing and it would also mean that the staff panel isn't clogged up with spam of someone selling 1 metal a billion times.

**Comment by twooot** [comment]
This has been done
