### ISSUE TITLE
[game/inventory] Inventory exceeding weight limit

### ISSUE THREAD

**Issue by OreoEatingHusky** [InZidiuZ/op-framework-issue-tracker#1975]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

**Player Identification:**
What is your steam profile? OreoEatingHusky

**Summary:**
Write a short summary of what you are experiencing. I was putting stuff in my glovebox and by accident managed to get the storage over the max of 50
![Screenshot 2021-08-27 004848](https://user-images.githubusercontent.com/89625730/131075392-b9757a2c-9717-46e5-8d12-2b5ad977d790.png)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue. I have not tested it with trunk, house storage or my pockets but with  a glovebox if you have an empty space in the glovebox you can switch something in glovebox with something in your inventory and have the glovebox exceed the max space of 50. I discovered it by accidently trading my handcuffs in glovebox for 6 first aid kits and as seen in my screenshot i was able to get 64/50 in the glovebox. 

**Expected Results:**
What are the expected results? To not be able to move all of the first aid kits

**Actual Results:**
What are the actual results? More storage taken than should have been.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted. the time stamp will be off by probably 10-20 minutes
![Screenshot 2021-08-27 011233](https://user-images.githubusercontent.com/89625730/131075373-d04313e1-e908-4b39-8892-e98cd5d742ea.png)

**Server:**
What server/community did this issue occur in? Legacyrp

**Notes:**
For anything else noteworthy.

**Comment by Nuziatella** [comment]
How much character inventory weight was available?

**Comment by OreoEatingHusky** [comment]
At the time my character weight was around 180-190.  Don't remember exactly but I was able to purchase 2 scuba tanks after before space was full
________________________________

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
