### ISSUE TITLE
[illegal/*] Add gold watches, silver watches or necklaces as a rare drop when robbing a ped

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#1976]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.
Add jewelry items as a rare drop when holding up a ped.

**Reason:**
Why would your suggestion be a good change to the framework?
It makes sense that you would be able to steal more than just their money if you hold up an ped/NPC with a gun. My suggestion is to make a rare drop of Gold Watch, Silver Watch, Necklace when holding up an NPC for money. It's realstic and would be a nice suprise, especially for people who are RPing as a petty criminal/homeless person.

**Comment by Nuziatella** [comment]
This is possible. Would we make the chance and type of drop dependent on area in which the ped is being robbed?

**Comment by DaxterPancake** [comment]
Maybe when there is more items to get, but as for right now I don't believe it needs to be location based. That would just add more coding needed. 

I'd just allow all those items to be dropped by any ped. Except for animals (if we can still rob them, I am not sure if we can?).

**Comment by AdeptCL** [comment]
If this is added, my only suggestion to give some form of benefit to the PD on this, is when you rob someone, the Police get a respond of description of the person(if it's even possible).

Otherwise, you may find people spam holding people up in areas which police usually won't have enough time to reach.

**Comment by lildiavolo** [comment]
This sounds nice but I think some fine tuning need to be done for it to not be abused/be useless. Not really sure what the drop chance might be but if people find that they can just spam rob Peds with no repercussions for some easy money that'll get abused or on the other hand it'll be so rare that nobody will even bother doing it as part of a RP and rather just randomly get it when robbing cars once every blue moon. 
Overall, it's a nice flavorful thing to have and def worth experimenting with the values as I do think it'll overall be more positive than if at all negative!

**Comment by DaxterPancake** [comment]
> This sounds nice but I think some fine tuning need to be done for it to not be abused/be useless. 

If people are spam robbing peds with no RP reason that can be dealt with by either police of staff. The drop would be quite rare and I don't believe the pay out would be worth people doing nothing but robbing peds. It'd just be a nice rare drop for those who do rob peds as part of their RP.

**Comment by twooot** [comment]
This sounds really easily abusable.

**Comment by claymstehling** [comment]
> This sounds really easily abusable.

You can make it to where there are only certain areas that they can be robbed at and at certain times, like weed. I feel like everything gotten could also incorporated into #531

**Comment by twooot** [comment]
This would make people rob every ped that crosses their path. People will grind robbing locals and it will just lead to issues
