### ISSUE TITLE
[base/admin] /tp_here for staff

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1977]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yep*

**Summary:**
Write a summary of what your suggestion is about.
*It'd be nice in addition to the `/tp_player` command to have a command like `/tp_here` that does the opposite (teleporting a player to you).*

**Reason:**
Why would your suggestion be a good change to the framework?
*If you have to teleport someone, you wouldn't have to scroll through the entire admin thing anymore*

**Comment by Nuziatella** [comment]
Yes!

**Comment by InZidiuZ** [comment]
This has since been added.
