### ISSUE TITLE
Walking style change on pressing Ctrl

### ISSUE THREAD

**Issue by T4NZIM** [InZidiuZ/op-framework-issue-tracker#1978]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/asttanzim

**Summary:**
Write a short summary of what you are experiencing.
Pressing **Ctrl** resets walking style to normal

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Select any walking style, Press **Ctrl**. The walking style goes back to Normal (Reset)

**Expected Results:**
What are the expected results?
The walking style should remain the same as it was selected

**Actual Results:**
What are the actual results?
Walking style resets to normal

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
N/A

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
Legacy Roleplay Bangladesh

**Notes:**
For anything else noteworthy.
Nope!

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
