### ISSUE TITLE
Car upgrade Skuff

### ISSUE THREAD

**Issue by marcf1979** [InZidiuZ/op-framework-issue-tracker#1979]
i went the other day and upgraded the paint and Spoiler on my Merc. when I stored it it was fine. Later that day I went and added Max Engine, Tint, Max Trans, Turbo, Chassis and Max Armor it was 21,900 worth in upgrades when I went to store it in my house it stored then said it was still out. when I retrieved it all the upgrades were gone. not looking for a refund just upset spent that money for upgrades and everything is just gone

**Comment by DaxterPancake** [comment]
Remake this following the template. 

This is also the wrong github.

Go [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose), for the correct place to post this.

Cheers,
Daxter.
Project Manager.

**Comment by exclusivegirl** [comment]
@DaxterPancake wasnt that the github he originally posted to? https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/486

**Comment by marcf1979** [comment]
it was and Nuzi told me to Move it here

**Comment by Spitfire2k6** [comment]
> it was and Nuzi told me to Move it here

Yep, just remake using this template in this tracker
