### ISSUE TITLE
Cars adjusted needs done soon

### ISSUE THREAD

**Issue by zezimajr** [InZidiuZ/op-framework-issue-tracker#198]
**Name:**
Jade Smith#8349

**Summary:**
Bought a $27500 car it tops out at 113 bought the max engine/transmission its max speed didnt change just about any local car goes faster than it (was told its any car thats not a local car doesnt have stats) was really bummed to spend all that money and it perform so bad
**Reason:**
Nobodys going to want to buy cars if they perform worse than local cars

**Comment by SteezyRen** [comment]
**PS:** This is the case for all imported cars (non-local vehicles) that haven't been adjusted for.

**Comment by InZidiuZ** [comment]
Hey,

This has already been addressed previously. Use the GitHub's search function, you'll find the answer there.

**InZidiuZ**
*OP-FW Developer*
