### ISSUE TITLE
[base/admin] /invisible command for staff

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#1980]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Mhm*

**Summary:**
Write a summary of what your suggestion is about.
*It'd be cool to have a /invisible command that makes you invisible as staff.*

**Reason:**
Why would your suggestion be a good change to the framework?
*When you need to teleport somewhere for example and you want to make sure you are not seen for example.*

**Comment by InZidiuZ** [comment]
This has since been added.
