### ISSUE TITLE
Green Wonderland Map Icon Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1981]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Green Wonderland is Los Santos' only legal recreational and medical marijuana dispensary.  We have been open since April 2021 and would like to add a map location to the GPS.

**Reason:**
Why would your suggestion be a good change to the framework?
Would make it easier for citizens to find the shop and know that there is a legal marijuana dispensary in the city.

**Comment by DaxterPancake** [comment]
Are you creating these instead of your original issue or creating them again to create more visibility?

**Comment by vicarsrd** [comment]
I've been told that sometimes it's easier to split these out rather than have one bulk submission so I was going to split them out to make it easier for the developers to track individual items.

**Comment by twooot** [comment]
This was done
