### ISSUE TITLE
Green Wonderland Jobs Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1982]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Green Wonderland is Los Santos' only legal recreational and medical marijuana dispensary.  We have been open since April 2021 and have locks on our building.  We would like jobs created so we can lock doors and get salaries.  We could mimic the job framework of PDM.

**Reason:**
Why would your suggestion be a good change to the framework?
It would enable employees to lock the doors, thus protecting employees and customers.

**Comment by tftwsaaron** [comment]
this has been taken care of and can be closed

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
