### ISSUE TITLE
Green Wonderland Products Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1983]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Green Wonderland is Los Santos' only legal recreational and medical marijuana dispensary.  We have been open since April 2021 and would like to add edibles (brownies, cookies, candy) and drinks (energy drinks, etc) infused with marijuana we could sell in the shop.  We could include a crafting table in the back of Green Wonderland where employees can use weed to craft these (like the mechanics shop) or have a shop behind a locked door only employees can access that employees can purchase these products to resell (like Bean Machine).

Edibles to relieve stress, fill hunger, gain armor.
Drinks to relieve stress, fill thirst, gain armor, (gain energy boost with energy drink).

**Reason:**
Why would your suggestion be a good change to the framework?
This would give new ways for people in the city to fix armor, hunger, thirst, energy, etc.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
