### ISSUE TITLE
Green Wonderland Item Move Suggestion

### ISSUE THREAD

**Issue by vicarsrd** [InZidiuZ/op-framework-issue-tracker#1984]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Green Wonderland is Los Santos' only legal recreational and medical marijuana dispensary.  We have been open since April 2021 and would like to swap the location of the ATM and the water jug.

**Reason:**
Why would your suggestion be a good change to the framework?
People in the store often end up buying a snack instead of using the ATM because of the close proximity of the ATM and the vending machine.

**Comment by DaxterPancake** [comment]
This is the wrong github for this suggestion.

Please recreate [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose).

Also please give more information on where you'd like the ATM and water jug to be moved to. Photos are also appriciated. 

Cheers,
Daxter.
Project Manager.
