### ISSUE TITLE
/takehostage animation addition

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1985]
**Assurance:**
Yes ma'am.

**Summary:**
Introducing a /takehostage command/animation.
[https://forum.cfx.re/t/release-take-hostage/840235](https://forum.cfx.re/t/release-take-hostage/840235)

**Reason:**
Introduce an ability to use a /takehostage command when someone has their hands up. This will bring a little bit more of a fluidity to movement throughout situations, like robberies/kidnappings/etc. There's not much to say really as it's pretty straight forward.

**Comment by DaxterPancake** [comment]
This is already suggested in #1661 

Closing in favour of that one.

Cheers,
Daxter.
Project Manager.
