### ISSUE TITLE
[game/evidence] Evidence and Law Enforcement Investigation RP

### ISSUE THREAD

**Issue by lordfuzzywig** [InZidiuZ/op-framework-issue-tracker#1987]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.

One of the big detractors to good police investigations in the current framework is the ability to properly investigate crimes other than shootings. Right now, eyewitness testimony is the prime evidentiary standard for any crime that is not a shooting. Thus, any knife crime, theft, burglary, etc. is literally not able to be investigated -- or certainly not prosecuted with any evidentiary standard -- unless it was witnessed. I thus propose the following:

1. Implement fingerprints that exist on doors (houses, car doors, and steering wheels) that can be obtained via evidence bags. They would exist in the world similar to bullet casings, and only show the last person to touch the door/steering wheel/house door and could "wash off" or smudge within 15 or 30 minutes. Fingerprints inside a vehicle could be found and bagged when using a special item or command while inside a vehicle.
1a. Fingerprints would require a "check" against whether the player is actively wearing gloves at the time to see if they leave fingerprints. Likewise, snowy or rainy weather would cause no fingerprints to exist or, when fingerprints would have existed, they get "washed off."
1b. Fingerprints could be tampered with and smudged by criminals.
1c. Fingerprints would also be obfuscated similarly to unregistered firearms where the identity/owner of the fingerprints is not available immediately and would require further forensic study and comparison. (Assign an ID similar to CID to each player for their "fingerprint" serial#?)
1d. Item called UV flashlight or Latent Print Powder for this?
1e. Often, especially on convenience stores, suspects make it away before officers arrive and officers have no leads because there is no good way to catch the license plate of the vehicle on camera on convenience stores. Having prints for hasty, opportunistic criminals that are not wearing gloves would give officers something to go on.

2. Implement blood, also similar to casings. When fistfights happen, small splatter may exist at the scene. Likewise, when a person is stabbed, blood may be found. Similar to fingerprints, some forensic study would be required to identify to whom the blood belongs as it would be far too powerful to just point directly at a particular person. A similar system to fingerprints where a number or some sort of alphanumeric string was assigned to each player would be ideal to force officers to properly investigate crime.
2a. Criminals could clean the blood up if they are diligent in attempting to hide their crime. Perhaps adding a new item called bleach that is consumed to do this? Likewise, rainy weather would degrade or remove the blood evidence.
2b. Blood could indicate type of splatter -- High velocity splatter for GSWs, sharp object spatter for knives/machetes/etc., blunt object spatter for dull weapons like pool cues, bats, etc.
2c. Implement new "blood test" for officers to need to perform on a suspect when probable cause exists to collect blood sample for cross-referencing. May require subpoena from DOJ or something similar to allow for extra depth in roleplay, and/or may also include EMS for "law draw" as exists in reality.

3. Evidence markers which can exist either as props or as a "step one" for casing/blood/fingerprint examination and pictures. This would allow officers to take better crime scene photographs, having real physical items that exist and can be photographed from a distance, instead of needing to hunt for casings which disappear from view at a certain range. This could also be a consumable item similar to evidence bags where, for diligent officers, the first press of E while holding a flashlight places an evidence marker at the location(s), and the second press of E collects the evidence.
3a. Add extra layer of difficulty for police when maintaining cordon as foot traffic could degrade quality of evidence/remove evidence? Make officers properly protect a crime scene.

4. Possible addition of "police tape" to show police cordon for crime scene to this end. Often, people just waltz in and out of a crime scene which tampers with evidence collection.

**Reason:**
Why would your suggestion be a good change to the framework?

A big frustration I have witnessed, both on a person level and as a police officer on the server, is the inability to investigate certain crimes. People often break into cars, and tying them to it unless we have them red-handed is difficult. Likewise, when someone is stabbed, immersion can be broken when asking a person to remember their assailant -- particularly when the victim's wounds are severe and/or life-threatening. Being able to point to a car and say, "They got in that car, but they're not in it anymore" would be valuable evidence and allow officers to find latent prints on the vehicle (assuming no one has tampered with it or diligently cleaned it using items and the person wasn't wearing gloves) allowing them to tie suspects to particular vehicles and would increase the requirements for evidence-gathering on every scene.

No longer could officers just walk away after not finding casings. Each thing touched would become valuable evidence, needed to be properly catalogued for prosecution. Likewise, officers would need to be expeditious in evidence gathering as weather would be a factor in the collection of evidence.

Thank you so much for the consideration.

**Comment by DaxterPancake** [comment]
I also suggested something similar but your explination is a million times better, though. 
Mine can be found at #1847 

I don't see a reason why we would need bleach since we already have 'cleaning kits' which could be adapted to be used instead.

Also I believe a 'Crime Scene Investigation Kit' or 'CSI Kit' would cover all bases for looking for finger prints, etc. 

Other than that, I love the idea. I'm in FIB and have been hoping for a more in depth evidence system for years.

**Comment by lordfuzzywig** [comment]
Shoot. Sorry Daxter. I had searched and I guess I completely overlooked your suggestion.

**Comment by panpawn** [comment]
+1, we already have a DNA sample command. Once someone's DNA is on sampled and on file, we could document it on a suspect's MDT profile. The 'evidence' for DNA could contain the person's character ID, and we would only 'know' who it is if the person has their DNA on file.

Additionally, blood being dropped (or having a chance of being dropped) at a front door of a house that was lockpicked and being robbed could add to PC to breach/charge etc during house robberies, as it'd show signs of forced entry.

**Comment by superiorchicken007** [comment]
This would be good especially if there is a shootout there a chance of DNA being dropped by everyone that was shot.  This would be a great addition to the PD side.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
