### ISSUE TITLE
[?] Mosley's Enhancements

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#1988]
**Assurance:**
Yuuuuuup I read it.

**Summary:**
Since Plague has left the city and Mosley's has become a neutral shop again we have slowly begun to become a social hub for the southside. Due to this, we would like to see if it would be possible to make a few changes to the main shop floor. 

Remove the blue car lift next to the office.
Clear out the seating area and move vending machines and water cooler from back hallway up front for customer use.
Placement of 4 permanent yoga mats on the floor somewhere in the front of the shop.
Move the work bench slightly to the right so it is out of range of the door lock on our bay door facing Carson Avenue
Move the ATM slightly to the right so that it no longer gets triggered by anyone that has a mechanic job and tries to use the door, or tries to use the ATM and unlocks the door.

**Reason:**
This would be a good addition to the framework because it provides a better appearance for the front of the shop than it currently is. We have a lot of dead space that isn't used, and adding this would improve our usage of the space and help provide additional things for our customers when they come in and wait for a repair.

**Comment by MoolanRooge** [comment]
Yesssss please

**Comment by TalosTG** [comment]
100% agree, especially given people are going to be looking for new hubs now that the garbage rule has been put in place.

**Comment by DaxterPancake** [comment]
I believe Lunar is working on making some changes to Mosleys so, I'll send this to him.

**Comment by InZidiuZ** [comment]
All of these but the work bench are assets-related. How come you even want the workbench moved? When you're near the workbench door locking is disable to prevent you from doing two actions at once. Is that what you're annoyed about?

**Comment by SilkyDrip** [comment]
Any chance we can work in the Mosley's staff shirts and what not into this somewhere as we have been waiting for months?

**Comment by AdeptCL** [comment]
Shirts/clothing are assets. Not framework based. They can be posted here: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues 

Also, assets take a long time. As asset updates do not happen very often. They all come in at one time, rather than multiple updates which are very time consuming.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
