### ISSUE TITLE
A filter for specific steam identifiers to not be able to connect to the servers

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#1989]
**Assurance:**

Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes
**Summary:**

Write a summary of what your suggestion is about.

It is not possible for us to ban a specific hex if it hasn't logged into the server yet, but by creating a filter that will not let a list of steam identifiers to join if it tries to join the server and is in the filter list the filter would show perhaps a system ban. According to Inzidiuz this can be done by adding the steam identifier to the database manually which can later perhaps be added to the admin panel in later stages (Might suggest it to the GitHub repo soon)

**Reason:**

### **Why would your suggestion be a good change to the framework?**

Most subdivisions have a list of identifiers of cheaters which can be added to it the filter. This can be very helpful during server wipes as well by just adding the permanent ban / cheater identifiers in the filter.

**Comment by InZidiuZ** [comment]
This has now been added.
