### ISSUE TITLE
[?] A change in /repair and /impound (for EMS + PD)

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1990]
**Assurance:**
Yes ma'am.

**Summary:**
Force a cost for /repair ($25) and /impound ($50) for EMS + PD.

**Reason:**
A common perception from what I've seen is the salaries of both the EMS department and Police department. This isn't to say it's undeserved, because having a character formerly a part of EMS, they can be the backbone of the community. However, a common occurrence is discussions that these jobs earn too much money, without many options to utilise it besides job items, vehicles and houses.

I believe that if a small cost to the /repair and /impound option might assist things in terms of the economy.

From my knowledge, the lowest salaries of EMS + PD sit around the $60 mark. This is for individuals who are rarely on their own. Let's say that if an average hour count of on-duty activity is 10 hours per week, they would earn around $7200. I understand if they have finances/rent/etc then this will depreciate.

Adding these two costs might also switch up how "reckless" people drive their job vehicles too as they will understand there is going to be a cost associated to the repair of it. Especially a lot of the time when EMS + PD (not all) avoid repair shops completely because they can get a free repair or free impound.
 
I have also seen people with these jobs /impound their vehicle because it was a little bit broken from a chase or a medical call, then instantly pull another one out.

**Comment by AdeptCL** [comment]
All the millions that Spencer has in his bank account can also finally be put to use. ;)

**Comment by DaxterPancake** [comment]
I think this is a nice way to make things feel more realistic. I'd even be okay with the price for a repair being higher (though that may just make people go and get a new car).

Now, for impounds I think $25-$50 is fair, because you also have to keep in mind that officers are also trying to keep the lag and load in the server down by clearing up the streets ESPECIALLY in the city. There are abandoned cars everywhere. Though if feesable, it should always try to go to a tow truck driver first.

**Comment by AdeptCL** [comment]
If there was a way for cops to /impoundtag a vehicle too, it gives a small $reward boost. Stops the tow drivers impound ANYTHING they see, but also gives reason for the Police to co-operate with the tow drivers too.
Rather than spending their own money for a tow driver. The /impoundtag provides that income for the tow drivers. I understand that may be a new GitHub though.

**Comment by xarxesthegreat** [comment]
we periodically get PD that come in with their cruisers to Mosleys and it would be awesome to see more of them doing it honestly. I love seeing them come in for the RP factor, so if it was changed to where they had to come to repair shops for that it would be amazing.

**Comment by InZidiuZ** [comment]
This has now been done.
