### ISSUE TITLE
Reduce changing circle radius in pillbox

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#1991]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Reduce changing circle radius in pillbox

**Reason:**
Why would your suggestion be a good change to the framework?
Reduce changing circle radius in pillbox so it can not be used outside of the changing room, this will stop the general public using is at a changing spot. Should cut down on number of people at pillbox for non medical reasons and makes more sense realistically.

**Comment by xplrkai** [comment]
I've been wanting this for the longest time.

**Comment by twooot** [comment]
lmao this is gonna make people mad who loose their hat near pillbox kekw

**Comment by twooot** [comment]
This has been done
