### ISSUE TITLE
New sellable item drops

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1992]
**Assurance:**
Yes ma'am.

**Summary:**
Addition of new sellable items (Nintendos, sellable mobile phones, toys, etc) from activities like house robberies, chop shop, etc.

**Reason:**
Adding new sellable items alongside what is already available, could work hand and hand with GitHub #1789. It adds new variety to the loot pool from the regular items. If this would added, I would love to see a market open up to sell these items across roleplay. Group A sells a bunch of mobile phones/electronics to Person A, who then distributes across Person B, C, and D. They all then sell accordingly.

They offer no feature. But to have more items like this will only allow more unique discussions / deals / trades to happen.

**Comment by DaxterPancake** [comment]
I feel this could branch off of #996 which is to add more to house robberies. That would then connect into #531 which is an addition of a pawn shop/fence. I understand we have something of the sort right now but I feel that the pawn/fence idea should be expanded apon and the additions of more items to pawn would be amazing to see.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
