### ISSUE TITLE
Allow Taxi Meter on Other Cars ( w the Taxi Role) 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1994]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
In my Sub, we are doing Uber RP & Other RP related to Taxi. But we are not able to use the Taximeter on other cars than the Taxi itself. If we were allowed to use it on other cars ( Uber) It would create the RP even better. So A Person with the Taxi role; should be able to use the taxi meter on other cars. 

Pic: https://prnt.sc/1rirtm8

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
