### ISSUE TITLE
New Taxi ( Enhance Taxi RP) 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1995]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
A lot of people are very interested in Taxi in my Sub. I feel like we need a different-looking taxi. It would make civilians actually want to call " Taxi". As of now its very hard to get calls but with the upgrade of the Taxi it will make everything

Pic of the Car: https://www.gta5-mods.com/paintjobs/mercedes-benz-c63-amg-hungarian-taxi-jezus9

**Comment by DaxterPancake** [comment]
As said above, please post this in the correct asset github.

Cheers,
Daxter.
Project Manager.
