### ISSUE TITLE
Allow Staff to use /reset_status

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#1996]
**Assurance:**
yes

**Summary:**
Sometimes staff needs this power to get rid of stress when they are chilling & especially when spectating someone, its very annoying to die coz of no food. 

**Reason:**
Why would your suggestion be a good change to the framework?
It will make it better for staff members, so they don't die because of food and high stress makes it worse to spectate.

**Comment by AdeptCL** [comment]
From what I know, this is already a command. Whether or not it's accessible for the regular staff or for super-admins, I don't know.

**Comment by GuArDiAn-ops** [comment]
The command can be accessed by super-admins only currently not regular staff.

**Comment by milan60** [comment]
I think what they are asking is not if it can be added but if it can be made accessible to use for staff

**Comment by Princek101** [comment]
Yes, making it suitable for normal staff would be great and not just super admin.

**Comment by twooot** [comment]
In my opinion this could be abused way to easily.
