### ISSUE TITLE
Rewrite of the Taxi job

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#1997]
**Assurance:**
Yes ma'am.

**Summary:**
A rewrite of the Taxi job from Life Invader, adding an additional option to "taxi" locals.

**Reason:**
When we currently look at the legal jobs offered by the Life Invader building, the most commonly used jobs are Garbage Collecting and Transporter. There is always so many people who come into the server, choose the Taxi job, but soon move away from it when they realise it forces you to find players to offer a taxi service to. However, this isn't the issue, the issue is that they're moved away from this job because 75%+ of the community have their own vehicles and therefore do not require a taxi.

What I am suggesting is adding an alternate "job" within the Taxi job in which acts similar to the Garbage Collecting job. Player A (taxi driver) is required to go to Location A, local will "hop" into the vehicle. Then, Player A has to take the local to Location B (it's destination). A small timer would happen (5 - 10 seconds), in which the taxi has to be within the proximity of Location B. Finally, a pay out of $100-200 is given. The pay out should be balanced enough that brings the job to the attention of people, while also competing correctly against other legal activities.

**Comment by DaxterPancake** [comment]
Closing in favour of #127 and #1815 

Cheers,
Daxter
