### ISSUE TITLE
Car Duplication bug when repairing

### ISSUE THREAD

**Issue by greatwhite18** [InZidiuZ/op-framework-issue-tracker#200]
**Reporter:**
iGreatWhite#3018

**Summary:**
Sometimes when repairing a car it will duplicate and make another copy of itself.

**Steps to Reproduce:**
Not really a straight what to reproduce this but I have a video showing it happening.

**Expected Results:**
Only 1 car appearing and repairing correctly

**Actual Results:**
Car repairs and duplicates.

## Additional Information

**Video:**
https://streamable.com/jmyax

**Game Resolution:**
1920x1080

**Player Data:**
https://imgur.com/hZxlmtx

**Comment by InZidiuZ** [comment]
Hey,

This may be resolved, probably not, not sure what's causing it, but maybe.

**InZidiuZ**
*OP-FW Developer*
