### ISSUE TITLE
[vehicles/garages] Aircraft spawner adjustments

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#2000]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

**General**
- Spitfire needs added to the military list
- Air Force 1 is currently listed as "Unknown"

**LSIA**
- Alkonost is too big for inside, needs moved to outside spawn at LSIA

**Sandy airfield & Cayo**

**Remove**
- Jet
- Cargo Plane
- Alkonost
- Air force 1

**Reason:**
Why would your suggestion be a good change to the framework?
Some vehicles are too big for the spawns

**Comment by Spitfire2k6** [comment]
Partially implemented, Still need AFO removed from small airport list.

**Comment by InZidiuZ** [comment]
I think this has since been done. If not, please create a new issue or reopen this one.
