### ISSUE TITLE
Give Alcohol Effects when Consumed (Drunk, Blackout, etc)

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2002]
Nia Emerson (selliee#8806)

As owner of Bahama Mama's, I think it would be extremely beneficial not only from a business standpoint, but city as well to make it so when alcohol is consumed it has effects such as getting drunk, blacking out, etc. It will drive business for all of the local bars in the city and make hosting parties, having get togethers more fun for those of us who enjoy a drink or two.

https://www.youtube.com/watch?v=d9h4niYhxQo
https://www.youtube.com/watch?v=MOqC974SqgA
https://www.youtube.com/watch?v=n51q2fl0ajM&t=819s (8 mins in)

Why I and others view this suggestion as an important addition to Legacy is because currently there are quite a few ways to obtain alcohol within the city, whether it be from trash, or a bar... it has zero use. People throw away their trash vodka because it is useless. Bar's from an RP standpoint could have a huge boost in sales and business if effects such as the ones in the videos listed above are implemented. The city has plenty of drugs that have effects, alcohol should be the next one on the list.

**Comment by DaxterPancake** [comment]
Please follow the template that can be found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new?assignees=&labels=suggestion&template=suggestion.md&title=Suggestion).

**Comment by DaxterPancake** [comment]
Actually, I will be closing this in favour of #1671 & #1682 due to them already suggesting the same thing.

Thank you,
Daxter.
Project Manager.
