### ISSUE TITLE
Player Ids should be visible for staff after a /player_id command

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#2003]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

The suggestion is about displaying the player list without the clipboard emote for admins  to toggle it using a command  during admin work with a proper display of players id for quick action or spectate. 

**Reason:**
Why would your suggestion be a good change to the framework?

This feature should allow admins to have easy display of the players ids during admin work ( can be toggled on and off like noclip) and also might slightly reduce the onesync bug of the clipboard being stuck in your hand after a few times pressing "U".

**Comment by InZidiuZ** [comment]
This has now been added.
