### ISSUE TITLE
Stuck in Stock Franklin Interior

### ISSUE THREAD

**Issue by shelby0341** [InZidiuZ/op-framework-issue-tracker#2004]
Randomly on Kimble Hill Drive 5, I go into my house and get "stuck" in stock Franklin interior. I can't move, can't type, can't /report, can't leave the house. I did find a F8 error which I have attached the file. I've cleared my cache and still had the same issue. Sometimes I walk into the house just fine, but this is the third time it's happened now in the past two days.
![error](https://user-images.githubusercontent.com/84191689/133014761-da6af130-d1ea-4f90-bdaa-e90e182711a2.png)

**Comment by DaxterPancake** [comment]
Please remake following the template provided to you when you make a bug report found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).

Cheers,
Daxter.
Project Manager.
