### ISSUE TITLE
Random Stock Interior Freezing Issue Upon Entering Kimble Hill House

### ISSUE THREAD

**Issue by shelby0341** [InZidiuZ/op-framework-issue-tracker#2005]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
ID: 76561197961549251
https://steamcommunity.com/id/sheLBY/

**Summary:**
Write a short summary of what you are experiencing.
Randomly when I enter my house at Kimble Hill, Drive 5, I will get stuck in stock Franklin interior. I cannot type to do /report, I cannot move, I cannot use my phone, I cannot exit the house. This has happened three times now in two days, and I'll always get stuck in the same spot. I can still see OOC chat when people type, I hear the stock Franklin interior house music playing, I can hear cars crashing and my thirst/hunger still go down, but I cannot do anything. I have cleared my cache after the first two times, and it still did it a third time.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
It has happened twice when I've gone from my next door neighbors house (Drive 3) to my house, but it's also happened once when I've been out of my house for an hour, and just went into my house. But sometimes I can walk into my house and fly into my house just fine. It doesn't seem to be a consistent thing that I can replicate.

**Expected Results:**
What are the expected results?
I expect to load into my own house with my own custom furniture, being able to move about.

**Actual Results:**
What are the actual results?
I will randomly get stuck as described above in stock Franklin interior, not being able to do anything.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![error](https://user-images.githubusercontent.com/84191689/133017895-2f88a89b-8b15-4bcd-a8bb-f8ce54a02b97.png)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![info](https://user-images.githubusercontent.com/84191689/133018084-7e07fc26-e078-4067-9077-070a51b48c17.png)

**Server:**
What server/community did this issue occur in?
The main Legacy server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
If this is still an issue, please create a new issue or reopen this one.
