### ISSUE TITLE
Suggestion: Track vehicles with phone app

### ISSUE THREAD

**Issue by TriGod10** [InZidiuZ/op-framework-issue-tracker#2006]
**Assurance:**
Yes

**Summary:**
There should be a function in the phone to track the vehicle registered to our ID.

**Reason:**
I think it will make easier for the people to find their vehicle which was lost and could easily get their vehicle.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
