### ISSUE TITLE
Door Locks/ATM for O'Malleys Irish Pub

### ISSUE THREAD

**Issue by kschreck0105** [InZidiuZ/op-framework-issue-tracker#2007]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.
**Summary:**
Looking to add Locking Doors to the Front Door and back Garage entrances to O'Malley's. As well as adding an ATM to the Inside.

**Reason:**
We are wanting to be able to secure the building while should a dangerous event happens outside. For the ATM, we are wanting one inside the business for the conveniences of our patrons to have quicker access to their money.

**Comment by twooot** [comment]
Door locks were added, atms would be something for the https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
