### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DeanoY92** [InZidiuZ/op-framework-issue-tracker#2008]
**Assurance:**
Yes

**Summary:**
PD & EMS to not be able to repair wherever they want / repair their own vehicles and have to go to repair shops.

**Reason:**
Making it so EMS and Police cannot /repair their vehicles makes it so police and ems will be forced to drive better and safer during any incidents or while responding to incidents. This would cut down on accidents just getting to an incident and enforce better driving concepts. Not only that but it would force police to rethink the maneuvers they take during chases. If they can no longer chase a car then they will have to find a local mechanic shop to repair their vehicle (which could take some time). This allows for a more realistic chase for the criminals instead of police just leaving the chase for a minute or two and doing /repair just to join back in on the chase. Currently there is no punishment for the police driving poorly. This also allows for a more natural economic flow when it comes to PD and EMS. Having to repair their vehicles gives them a reason to be on that character more so they can afford the repair costs/or make them more wary of destroying their vehicles.

**Comment by TCruxer** [comment]
Gonna have to disagree with this just based off the fact if you've ever tried fixing a cop car it swaps all the extras on it. Not to mention that ability is there because cops are on constant calls and all that would end up happening is that they would take another car out.

**Comment by TCruxer** [comment]
Also if you've been on the PD force you'd know that they don't repair during active chases only between calls.

**Comment by Stretah** [comment]
I disagree with you on that Cruxer. I think taking another vehicle out would be fail RP honestly. I get maybe needing to have the command in place in instances where no mechanic shops are available as Adept stated but the fact that the extras change isn't a huge deal in the grand scheme of things.

**Comment by Spitfire2k6** [comment]
I've not once seen a cop do a /repair mid scenario.

**Comment by DeanoY92** [comment]
> I've not once seen a cop do a /repair mid scenario.

Actually, i've seen it a couple of times. "Breaking off to get a repair" Mid way through catching people. 
One of my favourites was "I need fuel" And they literally went round the corner to a PD swapped. Done. 
Hence the frustration that lies with all this.

**Comment by Robin-CZ** [comment]
I personally think that PD should be charged for doing /repair, there should be an incentive for PD to go to a mechanic shop over doing /repair, currently there is none.

**Comment by Spitfire2k6** [comment]
I don't think some of you understand how worthless money is to 80% of cops. Most cops are just that, cops. The character only exists for police RP. The only thing they spend money on is supplies and tow tips. The only cops this would hurt are the few who use the character outside of Police RP.

**Comment by Masik52** [comment]
When a cop car is repaired it strips the extras off meaning it may have only one small light bar inside the vehicle and you’re not able to add the ones you need back on without getting a new vehicle out. This is why the repair command was brought in.  A charge to repair would be fine. I’ve never once seen a cop break off for fuel to only go get a new car out. If they did that, they shouldn’t and you should report it as they can easily go get fuel at a station.  I honestly don’t recall anyone anytime recently going to repair their car mid chase either.

**Comment by KatLikesTacos** [comment]
> I disagree with you on that Cruxer. I think taking another vehicle out would be fail RP honestly. I get maybe needing to have the command in place in instances where no mechanic shops are available as Adept stated but the fact that the extras change isn't a huge deal in the grand scheme of things.

Actually, PD rules REQUIRE certain extras to be equipped depending on your rank. So in RP, officers could potentially be punished for getting a necessary repair if shops were the only way to repair. 

I agree with Adept, there should be more of a penalty for not protecting your vehicle. But then again, people take tires on cop cars just because, ram the vehicles just because they can, and all sorts of trolly behavior. 🤷‍♀️

**Comment by Stretah** [comment]
> > I disagree with you on that Cruxer. I think taking another vehicle out would be fail RP honestly. I get maybe needing to have the command in place in instances where no mechanic shops are available as Adept stated but the fact that the extras change isn't a huge deal in the grand scheme of things.
> 
> Actually, PD rules REQUIRE certain extras to be equipped depending on your rank. So in RP, officers could potentially be punished for getting a necessary repair if shops were the only way to repair.
> 
> I agree with Adept, there should be more of a penalty for not protecting your vehicle. But then again, people take tires on cop cars just because, ram the vehicles just because they can, and all sorts of trolly behavior. 🤷‍♀️

If there are rules behind it then that's fair enough. Maybe we need to come to some sort of decision as far as what is acceptable for both crim and cop then?

**Comment by twooot** [comment]
Making PD go to mechanics won't work because it will strip the extras. If /repair would cost money, cops would just pull out another car instead of repairing. I feel like the underlying issue that lead to this Suggestion is more something that needs to be set through rules or changes in the SOP / harsher punishments.
