### ISSUE TITLE
Remove Weasle News Heli Spawner

### ISSUE THREAD

**Issue by lildiavolo** [InZidiuZ/op-framework-issue-tracker#2009]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Remove helicopter spawner from Weasle News roof. Add Weasle News heli as an option for those with a pilot license.

**Reason:**
Why would your suggestion be a good change to the framework?

In it's current state, getting the Weasle News heli requires nothing but getting the reporter job from life invader and then spawning one in.
This makes getting helis super easy and basically invalidates all the changes and Rp that's been added behind getting access to aircrafts.
It also makes no sense in RP for Weasle News to be handing out helis to every single reporter without them having proper flight training that would come with a pilot license.
The change I suggest is for Weasle News helicopters spawner to be removed from the Weasle news building roof, and instead have the weasle news heli be an option with the other aircrafts for those with a valid pilot license. This will still let those flight capable and trained reporters to pull the heli when needed (altho they will have to go to the airport to get one) and remove the easy accessibility to it from those who in an RP sense should never be able to get their hands on one to begin with.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
