### ISSUE TITLE
[SUGGESTION] Police department

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#201]
**Name:**
Ethan Banks | Oliver Porter | Doughnut#1718

**Summary:**
Hello, I have an idea regarding the police sirens, it would be a lot more realistic and fun if we had more control over the sirens, like having a separate button for the horn and one for the sirens 
or maybe adding a HI-LO sound option.

I have found a mod that has this exact description and it is right here 
It's a FiveM server plugin so I guess it's easier than coding one yourself :D https://forum.fivem.net/t/release-luxart-vehicle-control/17304

**Reason:**
Why would your suggestion be a good addition to Legacy?

I believe that most of the PD including me and the EMS or any emergency service that may be in Legacy would love to see this!
I also feel like it would be more realistic compared to IRL sirens, it would be more fun to have more control over the sirens while going trough intersections and I am pretty sure that everyone would like more realism to be implemented into Legacy :)
Thanks in advance!

**Comment by greatwhite18** [comment]
BE SURE TO FOLLOW THE TEMPLATES PROVIDED WHEN MAKING ISSUES/SUGGESTIONS.

Here is the suggestion template:


**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by Doughnut2001** [comment]
> BE SURE TO FOLLOW THE TEMPLATES PROVIDED WHEN MAKING ISSUES/SUGGESTIONS.
> 
> Here is the suggestion template:
> 
> ```
> **Name:**
> Who is suggesting this? Please include discord name.
> 
> **Summary:**
> Write a short summary of what your suggestion is about.
> 
> **Reason:**
> Why would your suggestion be a good addition to Legacy?
> ```


I'm sorry, the format should be fixed now, thanks for letting me know :D

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added. Possibly in the future, but closing for now.

**InZidiuZ**
*OP-FW Developer*
