### ISSUE TITLE
Harmony Repair changes.

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#2010]
**Assurance:**
Yes

**Summary:**

We would love to make some overall improvements to 'Harmony Repair' which is based on route 68. Below is a change that could be awesome for the quality of life at the shop in RP!

1.Adding an additional repair bay outside of the shop for larger vehicles like Tow trucks ect. Location: https://imgur.com/a/5XbD7TI

**Reason:**

It has recently opened on main server and we are going to give a decent shot, bringing more people to the harmony area in general, with the ability to experience new places and a fresh location!

**Comment by CloudTheWolf** [comment]
Superceded by https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/528

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
