### ISSUE TITLE
Kissaki Sushi addtions

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/op-framework-issue-tracker#2011]
Name:
Arty Sanders, Owner of Kissaki Sushi, Bossace#7764

Summary:
To add additions to Kissaki Sushi in order to be able to enhance experiences, serve food, and hold events with actually things to sell and serve.

https://media.discordapp.net/attachments/885756412842622977/885762228865871922/GPS.png

Sushi Roll logo on map for gps purposes:

https://cdn.discordapp.com/attachments/885756412842622977/885762228865871922/GPS.png

A role so employees can have keys and ideally paychecks with roles like Owner, managers, servers, etc.

Locks for all exterior doors and garage, also kitchen, employee room, and office door.

https://media.discordapp.net/attachments/885756412842622977/885756515032637440/Front_three_doors_together.png

https://media.discordapp.net/attachments/885756412842622977/885756917727776768/Side_exterior_door.jpg

https://media.discordapp.net/attachments/885756412842622977/885757593346248775/2nd_floor_exterior_door.png

https://media.discordapp.net/attachments/885756412842622977/885757150436143234/Garage_door.png

https://media.discordapp.net/attachments/885756412842622977/885757013135614002/Kitchen_and_Employee_room_doors.png

https://cdn.discordapp.com/attachments/885756412842622977/885758810369691668/Manager_office_2nd_floor.jpg

Lockers for employees to store items as well as clothes changing station by locker room so staff can change clothes

https://media.discordapp.net/attachments/885756412842622977/885757799487897650/Changing_room_and_locker.png?width=1040&height=443

To ensure customers have to interact with staff have the places to buy food and drinks in the kitchen so people can’t just run in and buy it.

https://media.discordapp.net/attachments/885756412842622977/885757737936519198/Kitchen.png

Custom drinks like Sake, Shochu, Tea, Plum wine, Highball, Chuhai. These could optionally include perks like being drunk effects on the screen or even fill up your thirst.

Custom foods like multiple different sushi rolls (California roll, spicy tuna roll, dragon roll, rainbow roll, spider roll, and the shrimp tempura roll), edamame, ramen. The sushi rolls could have possible effects like swim faster, hold breath longer, etc. Ramen could fill you up even more, edamame as an appetizer could fill you up less.

Link:
Links in summary

Reason:
To enhance and add to the restaurant rp. Not to have other traditional desserts or typical beer drinks so we can work with other businesses to buy from them as a supplier and say we have beer from draft from other businesses to side promote them as well as other desserts.

**Comment by claymstehling** [comment]
YEs please. I would love for Kissaki to be used more and I think this would make it that much easier to use

**Comment by claymstehling** [comment]
Any updates to this on the back end! I know this would add a lot for RP all around

**Comment by kaycorriher** [comment]
I love hanging out in this restaurant and think importing themed foods would increase the ability to role play out of this building. Not just for this owner but for all future owners as well
