### ISSUE TITLE
Move the "Shop" in Bars, Cafes and Burgershot

### ISSUE THREAD

**Issue by nimsaJChu** [InZidiuZ/op-framework-issue-tracker#2013]
Name:
Jasmin Tortuga, nimsaJ#9194

*Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

yes, i did

Summary:
Moving the little Arrow-shop inside Businesses behind the Counter or into some kind of Staff Area.

Reason:
It would be very helpful for the RP to not have those little "shops" accesible for Customers. I work both at a Bar and at BurgerShot (and i guess its not different in BeanMachine) and i see a lot of people coming in without a word buying the stuff they need for themselves. When i ask them "How can i help you?" they either say nothing and just leave or they say "I just bought what i need myself". If we'd put the Arrow behind the counter they'd actually need to talk to the working people and that would actually be a realistic RP. And if people wanna buy something without talking they can still go to a gasstation, so there wouldnt be anything "locked away"

**Comment by DaxterPancake** [comment]
Please edit this following the template that can be found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new?assignees=&labels=suggestion&template=suggestion.md&title=Suggestion).

It has a few more checks than the asset github does. 

Cheers,
Daxter.

**Comment by RetroCharles** [comment]
I agree with having that Arrow shop behind the counter, to have a more realistic interactions in businesses.

**Comment by twooot** [comment]
This has been done
