### ISSUE TITLE
Changes to how certain Businesses operate

### ISSUE THREAD

**Issue by MVirk22** [InZidiuZ/op-framework-issue-tracker#2014]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
I am making this suggestion regarding the current laws that prevent people who commit felony crimes from working at any legal businesses such as Bean Machine, Comedy Club, Bahama Mama's etc. There are multiple issues with the current rule. As it stands right now, working at these business doesn't pay you well enough for you which forces you to either grind scuba or participate in illegal activities to offset the lack of income. The owners shouldn't also be forced to baby sit their employees and if a employee does commit a felony crime then it should be the employees that get punished by losing their jobs and not the business by it getting put under review or possibly losing the business. 
If this rule/law does remain the same then the business owners should get more freedom to control how much their employees are paid, how many types of position can be created and how many positions from each category can be created. 
Employees also shouldn't have to buy the product from kiosk and then upcharge them at an extremely small profit. 
And just like burger shot, other business should also be allowed to do local deliveries.

**Reason:**
This would be a good change for the framework as it will encourage the employees working at these legal businesses to dedicate their time working at the business and provide good rp instead of being forced to find other ways to make money. People shouldn't make more money doing 2 hours of scuba providing no RP as compared working hard an entire day at one of these businesses. Owners of businesses should also have more freedom to control the paychecks of the employees and positions if they are being restricted by the state to only hire certain type of people and if they are the ones at risk for the actions of their employees outside of the business at their own personal time.

**Comment by DaxterPancake** [comment]
Those 'rules' are completely in character. This is not script related. If you want it changed, find out how to do it in the city.

Cheers,
Daxter.
Project Manager.
