### ISSUE TITLE
[base/admin] /selfuncuff or /su

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#2016]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*For staff, it would be nice to have the ability to be able to uncuff yourself-*

**Reason:**
Why would your suggestion be a good change to the framework?
*If someone cuffs you while you're trying to deal with a staff situation, you have no way of uncuffing yourself except for someone else to come and uncuff you. This would be a kinda powerful feature, so it should definitely be logged to prevent abuse, but I feel like it's definitely needed.*

**Comment by InZidiuZ** [comment]
This has now been added.
