### ISSUE TITLE
Suggestion no off-duty texts for police & ems

### ISSUE THREAD

**Issue by twooot** [InZidiuZ/op-framework-issue-tracker#2017]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*Cops and EMS shouldn't get 911 calls while off-duty.*

**Reason:**
Why would your suggestion be a good change to the framework?
*I didn't know if I should have put this as a bug report, but in real life, cops or EMS wouldn't get 911 calls from dispatch when they're off duty. It's also annoying when you're trying to have some fun off-duty and keep getting texts.*

**Comment by superiorchicken007** [comment]
As annoying at the 911 calls are.  I do EMS in real life and we still get them on our phones when we are off duty.  We are able to switch it on and off but we can still get them.

**Comment by joevapes3** [comment]
I think the ability to turn them off and and on would be good. IRL police keep their radio's on off duty as well and isn't uncommon.

**Comment by InZidiuZ** [comment]
This has since been done.
