### ISSUE TITLE
[base/admin] /freeze and /unfreeze

### ISSUE THREAD

**Issue by milan60** [InZidiuZ/op-framework-issue-tracker#2018]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*/freeze server-id to freeze a player /unfreeze server-id to unfreeze them*

**Reason:**
Why would your suggestion be a good change to the framework?
*It's annoying to have to go through the /admin panel every time you want to freeze someone.*

**Comment by InZidiuZ** [comment]
This has now been added.
