### ISSUE TITLE
Ability for superadmin's to move player in queue (Suggestion)

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#2019]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
_Yes_ 
**Summary:**
Write a summary of what your suggestion is about.
_Ability to move someone from the joining server queue. The idea is basically to be able to move someone from 10/32 to 1/32 or something higher. Because there are instances in big events people or participants have their head pop off and when they join they area kinda in the back of the queue sometimes._
**Reason:**
Why would your suggestion be a good change to the framework?
_This could be helpful during events as having a lot of people in the same spot does make things to weird usually some players experience a crash giving them a temporary high position in the queue to join back the server for events etc._

**Comment by milan60** [comment]
This has been done
