### ISSUE TITLE
Female Character Face Resetting

### ISSUE THREAD

**Issue by TaxEhh** [InZidiuZ/op-framework-issue-tracker#202]
**Reporter:**
Taxii (Taxi#0926)

**Summary:**
Female character models face keeps resetting to the FIRST creation made.  After multiple reskins from staff certain things are triggering the old face to come back?

**Steps to Reproduce:**
Upon going to the hospital and checking in then out, face was reset to FIRST creation.
Also upon putting a motorcycle helmet on, when taking off face was reset.

## Additional Information
As previously stated, once face was changed back I asked for a reskin from staff, it worked for awhile but then reverted back.

**Comment by InZidiuZ** [comment]
What player model are you using?

**Comment by TaxEhh** [comment]
> What player model are you using?

"mp_f_freemode_01"

**Comment by TaxEhh** [comment]
> What player model are you using?

"mp_f_freemode_01"

**Comment by InZidiuZ** [comment]
Hey,

At some point in the future, the entire clothing system will be rewritten, also resolving these issues, but it will not be worked on for the time being, so will close this.

**InZidiuZ**
*OP-FW Developer*
