### ISSUE TITLE
Creating a private endpoint to sync queue data (Suggestion) 

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#2020]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
_Yes_
**Summary:**
Write a summary of what your suggestion is about.
_Creating a private endpoint to sync queue data to able to fetch the data in the web panel for a list of queue._
**Reason:**
Why would your suggestion be a good change to the framework?
_Having a private endpoint to fetch data would allow the data in the webpanel improving the player/queue list._

**Comment by InZidiuZ** [comment]
A restrictred /queue.json GET route has now been added.
