### ISSUE TITLE
Bahama Mama's updates

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2021]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
There are a few things that I would like to request to be put in / removed from the bar. 

 Building Keys. With the new construction came no locks, I would like to have locks put on the front door, garage door, the door next to the garage, the service door, and the casino door. 

Possible Pay increase. When I purchased the bar, the Salaries for bar/club were $70 (owner), $53 (Manager), $35 (Bartender). After I started hiring, the salary got changed for staff. $40 (Manager) and $20 (Bartender). I do not think that this is a fair salary for positions that rely solely on their hourly salary + people coming into the bar for making money. Unlike other businesses in the city, like Burger shot, whos salaries are higher + have an additional ways of earning money, its a little discouraging for people to want to work at the bar when they can go make $20 an hour working trash + getting $200-300 per trash trip. 

Effects added to alcohol to increase RP. Everyone in the city really wants effects added to the alcohol. It would increase jobs for police, ems, and also enhance RP if alcohol could make you pass out, and get you drunk. Overall, it would be extremely beneficial to the city. 

 Alcohol Purchasing (Stores). I would like to request that the current one on the first floor be moved behind the bar and an additional one be put up stairs behind the second bar on the second floor. 

 Changing Rooms. In the new construction there is an employee locker room, I would like to request a changing station be placed there if possible, for the employees to be able to change into and out of their uniforms.

Storage. I would like to request a place of storage in the garage where there is alcohol on shelves if possible.

Local Bartender. I would love to request removal of her inside of the bar. During a recent event, there were almost 100 of this bartender that spawned inside the club, resulting in a lot of head issues and ruined the event due to everyone needing to vacate the premises so admins could handle the issue. 

**Reason:**
Majority of these changes that are being requested I believe would help with RP. Moving the purchase point for alcohol, when you go to a bar.. its not usually self serve right? Moving it behind the counter will enhance the RP for those who come in looking to purchase alcohol. Instead of going to the purchase point, avoiding interaction with the staff and buying alcohol then leaving.. it makes it so those coming into the bar actually have to RP for the alcohol.  Removing the bartender inside would help with head issues in future events.  Storage would be important just so employees, managers and owner have a place to put / store items such as food, and left over alcohol from events to be utilized for future events.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
