### ISSUE TITLE
New names for the inside track horse's (Suggestion)

### ISSUE THREAD

**Issue by ItsGUARDIAN** [InZidiuZ/op-framework-issue-tracker#2022]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
Some new names for the inside track horse's since the current names are limited and perhaps players can suggest better or new names to add to the list for ultrahacx to perhaps add in the future.
**Reason:**
Why would your suggestion be a good change to the framework?
Current names are from gta online scripts perhaps players selecting can have better names perhaps opening a tracker and everyone can just vote them if they are offensive or not

**Comment by GuArDiAn-ops** [comment]
RICHMOND_TIGER
