### ISSUE TITLE
[?] Check for helicopter license for weazle news

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#2023]
**Assurance:**
**Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?** 
Yes

**Summary:**
**Write a summary of what your suggestion is about.**
restrict heli spawner on weazle news to the helicopter license.
**Reason:**
**Why would your suggestion be a good change to the framework?**
Currently all aviation is locked behind licensing (or wl jobs) except Weazle news news helicopters. Can we add a check to the weazle news heli spawner for the heli license?

**Comment by claymstehling** [comment]
Yes, please. The amount of times I have seen random weazle news helis flying about by random people. This would a great check to prevent that

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
