### ISSUE TITLE
DOL Tactical vest needs reworking for the ladies

### ISSUE THREAD

**Issue by SilkyDrip** [InZidiuZ/op-framework-issue-tracker#2024]
Currently the DOL tactical vest is not available for the women in DOL. Is there a possibility someone can help us out and correct this? We also entered textures for our shirts 4 months ago and I do not see them available.

**Comment by DaxterPancake** [comment]
You're in the incorrect github, the correct one is [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues). Pleae follow the template.
