### ISSUE TITLE
Positioning of items on character model's back

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2025]
**Assurance:**
Yes ma'am.

**Summary:**
Changing the angle at which items (weaponry) are when attached the back of the character model.

**Reason:**
I just think when a baseball bat, axe, or even a rifle is positioned directly vertical on the character model, it looks kind of awkward. This is more of a quality suggestion, and won't really benefit anything. There is something it could help with, and that's the hiding of the item. Recently, a lot of players have began to utilise the backpacks from the assets to hide the weaponry they have on their back, with the addition of a slightly change of angle, it may hide it slightly more to avoid the awkwardness of people not realising it's "hidden" in a bag.

**Comment by xarxesthegreat** [comment]
Currently there's no way to full hide an AK on your back, but if turned at a slight angle it would allow them to hide inside of the largest camping backpack, thus improving rp.

**Comment by DaxterPancake** [comment]
Backpacks were not added to hide weaponry and personally I feel it's powerful to be using them as such. 

The fact that weapons show on your back at all means that the purpose is for there to be a risk to holding them, such as police being able to see it. 

Backpacks are causing way too much confusion and are being used to powergame in my opinion. I'd rather remove all backpacks than allow them to be used to abuse the system we have in place.

**Comment by MetaHatter** [comment]
I agree. If the guns were actually in a backpack there would be no way to instantly draw them as if they were just on your back.   There should be a container system to carry weapons rather than relying on backpacks that were intended to be cosmetic only.  At least then there would be a delay to hiding and retrieving them.

**Comment by 8017RAZ** [comment]
+1
