### ISSUE TITLE
Add Fixed Wing Small Airport planes to McKenzie Field

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2026]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add the ability to pull out and park small, fixed-wing aircraft at McKenzie Filed in Grapeseed.  Perhaps at "traditional" plane spawn location inside the hanger.

**Reason:**
Why would your suggestion be a good change to the framework?
As an airport there should be a way to park and take off from that location.  Additionally, it's remote location should provide for more RP opportunities than the fairly public Sandy Shores.  It should be limited to small fixed wing due to the size of the runway.

**Comment by InZidiuZ** [comment]
This has now been added.
