### ISSUE TITLE
Suggestion New clothing/barber menu (with numbers and stuff)

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/op-framework-issue-tracker#2027]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
In my opinion a new menu should be added to the clothing / barber shop with number it would be much more convenient to use

**Reason:**

More comfortable and more intuitive for new players

in many cases I don't know how to use it well for example when I have to make a dress like that of a friend of mine it takes years to do it

**Comment by Enryy** [comment]
any update?

**Comment by cammybruh** [comment]
I believe there is already a suggestion that has been looked at similar to this. I believe a new UI for clothing is already on the todo list.

**Comment by Enryy** [comment]
hope well

**Comment by twooot** [comment]
Closing as this has pretty much been implemented in #1856
