### ISSUE TITLE
/playsound for Staff 

### ISSUE THREAD

**Issue by Princek101** [InZidiuZ/op-framework-issue-tracker#2029]
**Assurance:**
Yes

**Summary:**
Currently, the option to play sound for all players is only allowed for SuperAdmin. If this feature was allowed for staff it would be pretty cool. Well, at least we can use it during Server events if Superadmin is not there. Also, it would be used in RP to make it a bit more realistic.

**Reason:**
Why would your suggestion be a good change to the framework?
^

**Comment by milan60** [comment]
This will stay a super-admin command as it could easily get abused by staff
