### ISSUE TITLE
Discord Invite Link display

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#203]
**Name:**
Steezy

**Summary:**
Another github post on this unfortunately. Maintaining 50 nitro boosts has been rather difficult and it's probably easier to just set the discord invite link displayed in game to the permanent non-vanity URL :(

https://discordapp.com/invite/6j2uEjj

**Comment by InZidiuZ** [comment]
Hey

Yes, but you do not need to suggest this. I see so myself, and it's not fw-related. ;)

**InZidiuZ**
*OP-FW Developer*
