### ISSUE TITLE
PD Stun gun license issue

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2031]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/asttanzim

**Summary:**
Write a short summary of what you are experiencing.
All PD guns should come with a license as they can only be purchased from PD store. It's all good unless it's for the PD stun gun. Because PD Stun Gun doesn't come with a license.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Buy a PD stun gun and it should come with a license and serial number.

**Expected Results:**
What are the expected results?
Should come with a license and a serial number.

**Actual Results:**
What are the actual results?
PD Stun gun doesn't come with license.

## Additional Information
All other guns are ok and come with serial numbers and licenses.

**Screenshots:**
If suitable, include some screenshots.
N/A

**Game Resolution:**
What is your game's resolution?
N/A

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
All

**Notes:**
For anything else noteworthy.
Ummm....no?

**Comment by InZidiuZ** [comment]
@milan60 has resolved this issue.
