### ISSUE TITLE
Re-addition of the weed processing (same/new location)

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2032]
**Assurance:**
Yes ma'am.

**Summary:**
Re-adding the weed processing location, to the same or new location.

**Reason:**
Quality of life/RP. Right now, a whole avenue of RP was removed when weed was changed. Although I agree that the weed field should have removed, the processing location should not have been removed. There has to be a 2nd location other than (grow in house) -> (sell on street). Having that process placed in the middle of the journey, adds a new avenue of RP.

**Comment by MetaHatter** [comment]
I was thinking this as well as the fact that weed is SUPER accessible in general for resale since it can be grown in house and sold quickly. Imagine if processing was required to resell... and it was on Cayo. 🤔

**Comment by z-Lunar** [comment]
> Like with the warehouse, make it so you can "give" 4 x quarters, and in return you get 1 x ounce. Add an animation to it, and a timer.
> 
> I know it's not that simple. But doable.

what about a weed field type warehouse, that anyone can see & enter but is controllable by gangs if found? 🤔

**Comment by xarxesthegreat** [comment]
I would just love to see a re-introduction of the weed field itself tbh. To keep it from being farmed as it was perhaps remove the drop of seeds and make the weed there be a different strain that can't be packed but has the same benefits when smoked. 

Would also love to see a rolling papers item added to grocery stores to add an extra step needed to be able to roll joints just for roleplay purposes.

**Comment by twooot** [comment]
This is not a dev issue. The weed field and processing were never removed, they can be enabled/disabled by server managers using the server config
