### ISSUE TITLE
Personal Suggestion for op-fw

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#2033]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
Write a summary of what your suggestion is about.

My suggestion is to add a new ui in our op-fw servers and change our current in-game mobile phone 
and another suggestion is to add a road mod in op-fw if possible just like no-pixel rp.

example of the road mod- https://www.youtube.com/watch?v=WtCnygk-Tr8&t=19s
example for the new ui- https://imgur.com/a/RIJak5a
example for new phone- https://imgur.com/a/qkyxx8t

**Reason:**
Why would your suggestion be a good change to the framework?

i think the new ui will give people new experience, a new thing. and our persent ui is almost 2.5 years old so this is my personal suggestion to add a new ui

and for the road mod i think it will give us a good environment if you add a road mod its gonna look nice as well
and for the ingame phone i would like to request to add a new phone ui because our present phone is also as old just like our ui
thank you.

**Comment by InZidiuZ** [comment]
I can't tell if you're joking or not, but either way, no...

**Comment by Mugdha57** [comment]
thank you, it was just a personal suggestion ( no joke)
