### ISSUE TITLE
Suspect in/out short command

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2034]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Just like police can do /sc, /hc, /uc to soft cuff, hard cuff and uncuff, add /si for **s**uspect **i**n and /so for **s**uspect **o**ut. 

**Reason:**
Why would your suggestion be a good change to the framework?
This would make suspect in/out commands faster and would be very helpful.

**Comment by milan60** [comment]
This was done
