### ISSUE TITLE
Updates to O'Malley's Irish Pub

### ISSUE THREAD

**Issue by kschreck0105** [InZidiuZ/op-framework-issue-tracker#2035]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Summary:**
A few updates to O'Malley's Irish Pub. 
1. The removal of the local Bartender from behind the bar. Meaning less people in the way and no issue of the local to get mad and start a fight with the staff or customers in the Pub.

2. Add usable Lockers for the staff to use in the Garage Area. (Picture 1)

3. Add a Clothing Changing Area in the Office Adjacent to the Garage for Pub Staff to utilize. (Picture 2)

4. Additionally would like to request an ATM point in the Pub, on the wall under/next to "The Temple Pub' pictures on the far wall. (Picture 3)

**Reason:**
It will enhance the RP by not having the local bartender randomly starting a fight because people are moving around behind the bar. The lockers will help store any unused alcohol or food and other items we use at the pub(i.e. patio chairs for out front, camp tables, campfires and boomboxes). As well as allow our staff to store personal items there while on the clock and not to be encumbered while working. Having a changing area will help the staff out due to the many theme nights we have (every Monday at minimum) so we can change right there with out having to drive to other places in the city to change. Adding an ATM will help out people who come in to have quick access to cash and not force them to drive down the street to another business that may not be open. Currently we are dependent on the ATM at Lost Repair Shop and sometimes they aren't open when we have our events. That being said, we are the only business in the city that does not have an ATM on the property or extremely nearby or is dependent on another business to be open to use the nearest ATM. 
![2_Lockers](https://user-images.githubusercontent.com/68434249/136302311-7a76316c-107f-424c-b3d4-672647f05b09.png)
![3_Clothing Change Area](https://user-images.githubusercontent.com/68434249/136302312-5a911519-22ed-4841-a35f-e385dd96bf73.png)
![4_ATM Location](https://user-images.githubusercontent.com/68434249/136302315-c7d339c7-c0c9-4a5d-9db0-a3ef462884cd.png)
l.

**Comment by claymstehling** [comment]
This would be such a great addition to O'Malley's! I already saw the improvement from the movement of the arrow behind the bar in Bahama Mamas and I think every bar and restaurant would benefit greatly from it! 


Honestly every change being suggested is such a great QOL thing that it would really benefit the RP in the city.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
