### ISSUE TITLE
Add Trains / Metro to the city

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2037]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes!

**Summary:**
Add Trains and/or a metro system to the city. This would either be a way to allow player to get around the city legally and quickly and could also add new jobs to the city.

Eg:

Metro Trains would allow players to travel around the city/state. For example, after flying into the city players could either:
1 - Hope for a taxi driver to be there to take them into the city
2 - Steal a car
3 - Walk 
4 - Take the subway

Freight Trains could either add a whole new job where players have to transport goods from 1 location to another and depending on how they do affects their pay. (Eg fines for breaking traffic laws, damage to train, being late, being early) or could add new kinds of work to the trucker job where they either collect goods to deliver or have to deliver jobs to a train depot by a specific time.

A Metro Driver Job could be another thing added to the city that allows players to drive a specific route and could be paid based on passengers taken (With both locals and players). 

**Reason:**
Why would your suggestion be a good change to the framework?

This would add a new way to get around the city, and would add a safe and fast way for new players to get from the Airport into the city.

Additionally it could also add new jobs / job tasks adding more things to do for players in the city

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
