### ISSUE TITLE
Bug: Western Fallen Turns Invisible while riding

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#2039]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Player Identification:**
What is your steam profile?

https://steamcommunity.com/id/NotoriousRSCZ/

**Summary:**
Write a short summary of what you are experiencing.

Western Fallen (Lost MC Bike) becomes invisible when someone is at a far enough distance (about 40 meters)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Have someone watch someone else ride a Lost MC Bike away from them, this should reproduce the issue fairly easily.

**Expected Results:**
What are the expected results?

Bike becomes invisible when far enough away.

**Actual Results:**
What are the actual results?

Bike becomes invisible.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

2560x1440

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

![image](https://user-images.githubusercontent.com/75344976/136587945-f42a331e-7063-4dd8-8866-64832934c7ff.png)

**Server:**
What server/community did this issue occur in?

Legacy RP (Main NA/EU server)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is an assets issue, please refer to [this issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for issues like this.
