### ISSUE TITLE
Add /Suspect in for Helicopters

### ISSUE THREAD

**Issue by FossiiLs** [InZidiuZ/op-framework-issue-tracker#204]
**Name:**
FossiiLs_#4043

**Summary:**
Add the ability to /suspect in for individuals who are downed in inaccessible locations.

**Reason:**
3 people fell off the crane and landed in different locations that were not accessible by foot. Air 1 responded but was unable to rescue the individuals due to not being able to put them in the helicopter.

**Comment by InZidiuZ** [comment]
Hey,

Yes.

**InZidiuZ**
*OP-FW Developer*
