### ISSUE TITLE
Bahama Mama's Changes

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2040]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
The Bar at Bahama Mama's was removed fully, it should have been placed behind the bar (see picture below)

Id also like to request the removal of the blue door (currently there are two sets of doors on the front, the glass ones are what belong, and the blue ones need to be removed, see pic)

Also would like to request locks on the doors pictured below.

The storage added is not accessible, when i press the k button like it tells me to, to access personal storage and place something down, it places it onto the floor (pic below)

**Reason:**
Why would your suggestion be a good change to the framework?

A bar, needs a bar so for RP, the bar is needed. The removal of the door + placing locks for safety of our staff + citizens inside. 
![image](https://user-images.githubusercontent.com/90532434/136630239-55e4812f-1bd5-4c93-9c29-53b99424b4a2.png)
![image](https://user-images.githubusercontent.com/90532434/136630254-607f1a20-85d9-4d86-9ee5-9c2ff110fc97.png)
![image](https://user-images.githubusercontent.com/90532434/136630264-09270adf-bd43-4580-815f-b2eef8abeab5.png)

![image](https://user-images.githubusercontent.com/90532434/136630271-5363e367-f99d-4f65-895a-12d8db3ccbaf.png)
![image](https://user-images.githubusercontent.com/90532434/136631168-d758bbfc-2a32-4550-a7eb-95063e60ba58.png)

**Comment by antihero6713** [comment]
Blue doors have been removed for next update

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
