### ISSUE TITLE
Suggestion: Transfer ownership of companies

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/op-framework-issue-tracker#2041]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
In legacy company’s ,we can’t transfer ownership of our company there should be a way to transfer the ownership of company,if it is possible then company blocks and the people who got house should not be removed
**Reason:**
Why would your suggestion be a good change to the framework?
Now it is feels like unrealistic because we can’t transfer ownership in irl people can transfer ownership of there company’s,if it is possible the rp will be increase and more realistic and people who want to transfer there company ownership it will be helpful for them .

**Comment by InZidiuZ** [comment]
Who should be able to transfer the company? The company owner themselves, or the state/mayor?

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
