### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Frostposeidon** [InZidiuZ/op-framework-issue-tracker#2045]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561199180819297/

**Summary:**
Write a short summary of what you are experiencing.

The Mustang Boss GT sport license plate dose not appear when I pull it out of the Garage there times where I have to storage it and bring it back out multiple times until the license plate is there but often when I go for a repair the license plate is gone like fresh car has replace it without the license plate and its the same when I get a repair the license plate can vanish off the car.  

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Anytime I go to bring out The Mustang boss GT the license plate not there and you have to storage it and bring it out over and over till you see it and it happens more than often than it should same when you repair the car.
 
**Expected Results:**
What are the expected results?

The right plate to be there so I am not spending my first five minutes waiting for the plate to be on the car.

**Actual Results:**
What are the actual results?

When the mustang boss has been taken out the garage the license plate is not there and when you go for a repair the plate vanish as well like a fresh car been placed without the license plate.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 
1920 X 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![20211013141409_1](https://user-images.githubusercontent.com/92272276/137146015-422bfba8-e68b-4b72-a401-caaf6e7d0171.jpg)

**Server:**
What server/community did this issue occur in?

Legacy International

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This issue should have since been resolved. I tested it locally as well, and I was able to pull it out within any problem. If this is still an issue, feel free to reopen this issue or DM me on discord.
