### ISSUE TITLE
Workable tv system 

### ISSUE THREAD

**Issue by Maruf2471** [InZidiuZ/op-framework-issue-tracker#2046]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Need workable tv on courtroom like theater  because it will help to show the evidence and 
**Reason:**
Need workable tv on courtroom like theater  because it will help to show the evidence

**Comment by InZidiuZ** [comment]
Could you explain a bit more in detail what you want, exactly? What should these TVs actually display?

**Comment by InZidiuZ** [comment]
Closing due to no response.
