### ISSUE TITLE
[jobs/mechanic] Replace Tow Text Messages with Tow App

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2049]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Rather than an SMS being sent to all mechanics, have Mechanic calls in a "Tow Manager App" that only shows requests that have not been accepted but a Tow Truck driver.

The process would be the same for Citizens but for the Tows/Mechanics the process could be:

Request Received (Shows distance from player) => Accept Job (Removes Request from all other On-Duty Tows) => Tow Truck driver then gets GPS Coordinates and option to call or message the sender.

Once done the Tow truck driver then marks the job as complete.  

Additionally the app could allow the player to go "Off Duty" to stop getting alerts as well as keep a record of Local and Citizen vehicles impended while on duty.

**Reason:**
This would:

1) Allow Tow truck drivers/mechanics to go on/off duty for Mechanic calls so they don't contently keep getting messages while they are not working, or are running the repair shop instead of towing.

2) Remove the need for "Tow Torpedos" and having 2 or more trucks show up for a single job.

3) Provide an In-City way for Tows to tally up their work as some mechanics require tows to log how many impounds they do.

4) Provide a way to know if someone has already responded to a call  (Related to point 2) as each mechanic shop is on their own radio frequency  so there is no way for all tows to know if something is being actioned.

**Comment by InZidiuZ** [comment]
A **BUNCH** of phone apps have been on hold for ages due to the current phone being deprecated and a pain to work on. Hopefully in the near future we create a new one that would be easier to work on and expan on.

Until then, though, this most likely won't be done.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
