### ISSUE TITLE
Suggestion Police Department

### ISSUE THREAD

**Issue by psyCOSMO** [InZidiuZ/op-framework-issue-tracker#205]
**Name:**
psyCOSMO#0476

**Summary:**
Fine someone via plate number of the vehicle,
Like in real life I think that the option for police officers to fine someone via their plate number will be a good addition,
But wait a second some people will say that people will just steal other locals cars and drive like nuts and then the owner will be fined for that, well that happens sometimes in real life but people usually go ahead and report their car stolen, so to negate that effect add an ability for cops to flag a vehicle as stolen when a civilian comes to PD and says to the officer that his car got stolen,
So then the officer will check the plate before fining it and will know that the car is indeed stolen,
Impounding a car that is flagged stolen will remove it from the stolen list also an officer should have the option to remove the stolen flag on a vehicle with like a command like that:
/flag #platenumber
/unflag #platenumber 

Also I really think that the /radar should show the plate number of the vehicles when they read their speed.

**Reason:**
Some super cars are really almost impossible to pursuit against and if the officer lose visual on them the criminals won't be punished, to balance that effect we don't want just to make the cops cars over powered and catch everything, but we do want to punish the person that committed the crime.
And also it can be used to fine illegally parked cars and etc.

**Comment by FossiiLs** [comment]
We can flag plates already, only issue is that people don't report vehicles being stolen. If they do report it stolen, they don't have their plate numbers or are too lazy to get it. So maybe having something on their phone that will list their vehicles and plate numbers so it just makes it easier?

**Comment by InZidiuZ** [comment]
Hey,

/checkplate and /flagplate is already a thing.

>Also I really think that the /radar should show the plate number of the vehicles when they read their speed.

Please create another issue for this.

**InZidiuZ**
*OP-FW Developer*
