### ISSUE TITLE
Two Tone Haircolour

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2050]
**Assurance:**
Yes

**Summary:**
I'm suggesting giving us the ability to have two tones of colour in our hair. [Example](https://cdn.discordapp.com/attachments/250843607995514880/899825287867551794/sddefault.png)

**Reason:**
I think this would be a great addition to Legacy as it would allow each person to style their hair in a more unique way, allowing them to set themselves apart from others. It opens up more costume ideas and allows different types of addon hair to be used, as some require two tones hair to work properly. I personally feel like everyone would enjoy being able to customize themselves a little bit more.

**Comment by keridwn** [comment]
I feel like this would also set us apart from other servers. Not many from what I have experienced have the two toned hair colors. It also expands the choices for those in the city and creates more chances for individuality.

**Comment by InZidiuZ** [comment]
'to Legacy'.. typo? I think you meant to type OP-FW!

**Comment by mxttx** [comment]
I really love this idea. https://docs.fivem.net/natives/?_0xBB43F090

**Comment by twooot** [comment]
Pogchamp this has been done i'm so fucking excited omg
