### ISSUE TITLE
Multiple BurgerShot delivery at One Ride

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2052]
**Assurance:**
Yes

**Summary:**
Multiple BurgerShot delivery at one ride.

**Reason:**
In the BurgerShot delivery mission, we can take one delivery at a time. But in real life, food deliveryman often delivers multiple orders at one ride. They take multiple ordered food at once and delivers them one after another.

If we can get another option to take like 5 deliveries (Just an example) at one ride it would be great. People will deliver food to one place and after that he will go to the next one Or he may choose which place he wants to go first. 
We can keep both delivery option (one delivery per ride and five delivery per ride). It will suit good with the real life and also will make the delivery better.

Here is a table where we can place the option for Multiple Deliveries at One Ride. [Image](https://imgur.com/a/GChv9zp)

**Comment by rakibulhasan456** [comment]
@AdeptCL We get most of the deliveries in city. The payout goes from around 220 to 330, average is around 275-280. For each delivery you have to go to the point and come back for the second one, averaging 4min+ per delivery. If you want to earn $2500 thats at least like 35min+ of delivering. 

I dont know how BurgerShot management works in other city, but in our Bangladesh Subdivision we have daily limit for the employee. They have 20 deliveries each day. If anyone breaks the limit he gets a strike and gets fired if he repeats that. So, there is no way to grind in our subdivision. 

We have no doubt that what I suggested is matches with the real world.  Now lets say I am going to take 5 deliveries per ride. So I need to go from BurgerShot to point A, then point B, C, D & E. With our current model we need to go from BurgerShot to point A then coming back to BurgerShot then to point B and it continues like this. If you compare it for 5 deliveries with two different model, it saves the 4x Time of coming back to BurgerShot from a delivery, So, 4/5 min for 5 deliveries. How much a player earns in 4/5 min in legal job? Not much. I hope the change doesnt make it huge grindable.

**Comment by qKelta** [comment]
> As much as this is being upvoted, I do think this is only going to make people want to grind it more as the efficiency of grinding money increases 5x (based on your example).
> 
> I don't know the figures, but let's say the deliveries equal $500 per drop off. You go from making $500 per ~2-5 minutes. To then, $2500 per ~8-10 minutes. For a legal job, some would consider this too high.

So how it works is usually anything under 2 miles makes 200-280. 2-4 makes around 300-400, 5+ miles ive never got more then 580. But by that time you went across the entire map.

**Comment by twooot** [comment]
Stop being lazy. JK, like adept said it would only make people want to grind it more
