### ISSUE TITLE
Garage at MRPD

### ISSUE THREAD

**Issue by baritonebear** [InZidiuZ/op-framework-issue-tracker#2053]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Suggesting a usable garage at MRPD for officers to store their cars when they go to work.

**Reason:**
Because with the current fivem bug of "locals" stealing every car in the garage, combined with the fact that the doors don't always want to lock... we end up either having to pay to retrieve or unimpound our personal vehicles regularly. :(

**Comment by MetaHatter** [comment]
Just a note: This issue happens to literally every job. Even those that don't provide a free car and /impound ability.  It's a huge pain in the ***.

Ideally we can figure out a long-term, city-wide fix somehow.

**Comment by twooot** [comment]
I feel like if we start adding garages to MRPD we would also have to add garages to all the mechanic shops for mechanics, the hospitals for ems, then people at the different bars and clubs might want some too, etc. I don't feel particularly comfortable snow flaking the PD job even more.

**Comment by twooot** [comment]
lol i did this
