### ISSUE TITLE
Allow Garaging of Other People's Cars

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2054]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add the ability for a player to store any players car in the garage and return it to the owner.

**Reason:**
Why would your suggestion be a good change to the framework?
With the new "Impound at Tsunami" event, cars that were loaned cannot be returned and are thus impounded.  Allowing people to store cars for others will provide a method to return loaned cars before they are hauled away.  Will also address head pops and cars left in front of the garage by Dannys.

**Comment by claymstehling** [comment]
Yes, please, shared garages would be SUCH a great thing. I agree put it under level 2, but the ability to share cars with people that you share a house with would just make so many things easier

**Comment by InZidiuZ** [comment]
Shared garages sounds cool! Though I would suggest creating a new issue for that as to not hijack this thread. It would also need some way to be 'loaded' on a server and prevent it from being loaded on another server to continue the 'multi-server' support for the framework.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
