### ISSUE TITLE
Vehicle Spawner at BurgerShot

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2056]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Vehicle Spawner at BurgerShot to spawn those vehicle that has BurgerShot Livery.

**Reason:**
Why would your suggestion be a good change to the framework?

BurgerShot was always the main attraction when it comes for food. After stopping feeding in Pillbox and withdrawing burger from 24/7, the delivery request has gone up. BurgerShot employee delivers the food with their own vehicle or they uses civilian vehicle. When it comes to deliver with a personal exotic looking vehicle it looks less realistic. There are some vehicle that has BurgerShot livery. Delivering with those vehicle looks more realistic and fun. Employees can also use those as an on duty vehicle to do delivery mission just like some other jobs. This change will make BurgerShot to deliver food as a proper way.

As per my knowledge there are 4 different vehicle that has BurgerShot Livery.

1. Lampadati Novak [Image](https://imgur.com/a/YCk5Irf)
2. Declasse Burger Shot Stallion [Image](https://imgur.com/a/fyWwdn9)
3. Hotring Sabre [Image](https://imgur.com/a/WuCu47t)
4. Mercedes Benz BurgerShot Van [Image](https://imgur.com/a/KlVwwYP)

There is a small part in the BurgerShot parking where we can place the vehicle spawner. [Place Image](https://imgur.com/a/pzPOTXM)

Making these change will bring betterment in the BurgerShot and also will help to do RP better and will bring new possibilities in the city.

**Comment by MetaHatter** [comment]
If the employee can afford a "personal exotic looking vehicle" that "doesn't look realistic", I'm sure they can manage a BurgerShot vehicle in the budget.

I agree this is not necessary for this job.

**Comment by twooot** [comment]
Ok, so I'm definitely not going to add a spawner for vehicles like the Lampadati Novak, Declasse Burger Shot Stallion or the Hotring Sabre. I would maybe consider it for the Mercedes-Benz BurgerShot Van because that makes somewhat sense for deliveries.

**Comment by claymstehling** [comment]
> Ok, so I'm definitely not going to add a spawner for vehicles like the Lampadati Novak, Declasse Burger Shot Stallion or the Hotring Sabre. I would maybe consider it for the Mercedes-Benz BurgerShot Van because that makes somewhat sense for deliveries.

I personally like the idea that you would be forced to do the delivery in the Benz Van, rather than in personal vehicles  

It would promote the business more. 
It would hold those employees more liable
It honestly would be great to see them driving around the same way you see trash trucks, go postal. 


If this was implemented I could see the same thing for Bean Machine as well. Give them the ability to deliver to locals and force it to be in something like this https://www.gta5-mods.com/paintjobs/karin-dilettante-livery-bean-machine

**Comment by rakibulhasan456** [comment]
> Ok, so I'm definitely not going to add a spawner for vehicles like the Lampadati Novak, Declasse Burger Shot Stallion or the Hotring Sabre. I would maybe consider it for the Mercedes-Benz BurgerShot Van because that makes somewhat sense for deliveries.

We will be really happy even if its only Mercedes Benz Burger Shot Van. It will really be helpful for many purpose. Please make it work. We are looking forward to it. Much Love.

**Comment by twooot** [comment]
Added a spawner for the van but none of the other cars
