### ISSUE TITLE
Suggestion - Move Body Armor From Tool Store to Ammu-Nation

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2058]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
**Yes**

**Summary:**
Move Body Armor From Tool Store to Ammu-Nation

**Reason:**
Why would your suggestion be a good change to the framework?
It would make more sense and work with the fact Ammu-Nation has body Armor on display in the store, this would also make Body Armor more widely available around the city.

**Comment by twooot** [comment]
Yeah you right, it makes more sense in Ammu-Nation tbh

**Comment by twooot** [comment]
This has been done
