### ISSUE TITLE
New version of the Dominator 

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#206]
**Name:**
Randy James
#4851

**Summary:**
Uplift this car. The old dominator goes 140 + and better handling. This car goes 110 at a high
**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Hey,

This is a suggestion for @Karpenko, get in contact with him.

**InZidiuZ**
*OP-FW Developer*
