### ISSUE TITLE
Casa Blanca Delivery & Food Suggestions

### ISSUE THREAD

**Issue by AnfewMac** [InZidiuZ/op-framework-issue-tracker#2060]
**CASA BLANCA ITALIAN RESTAURANT**

**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes I have

**Summary:**
I am currently the new owner of Casa Blanca Italian Restaurant and I would like to implement a pizza delivery system and food service system for Casa Blanca like how Burger Shot is set up but with Italian eatery.

**Reason:**
From what I have been told by many people in the city they think a pizza delivery service would be a great job addition to the city. Citizens in the city have already mentioned we need more food options other than burgers at Burger Shot. Not only would this allow for variety to the city but would also create some legal jobs for the citizens of Los Santos. 

Items we would like to have added to the Casa Blanca restaurant.

Food added to the consignment behind the bar area for employees to be able to sell said items. ( this can be items such as different variety of alcohol and non-alcohol beverages and food such as pizza or lasagna.) We are thinking the food can mirror the prices of Burger Shot prices so there is not a problem with undercutting each other.

Pizza Delivery just like Burger Shot with the same type of phone system Burger Shot has for citizens can call in a delivery. I have never been to a city where there is not pizza being delivered. There has been many people who have mentioned there needs to be different food in the city. This is that opportunity.

If there is anything I can do to help get this system set in place please let me know. Thank you very much!

I/We (The Gambetti Family) would like to see this come into play.

**Comment by AdeptCL** [comment]
I do like the idea of the introduction of new foods, like cooked meat was. 
However, having something similar to the Burger Shot, but for pizza would be a huge boost to quality of roleplay, and small avenues of roleplay. There is a similar post for the Japanese restaurant too (#2011). 

This wouldn't need a big overhaul just yet. You could begin the process with the introduction of some new items; margherita pizza, pepperoni pizza and vegi pizza. Then, the roleplay of deliveries can begin there before a job/mechanic is introduced like Burger Shot.

**Comment by AnfewMac** [comment]
> I do like the idea of the introduction of new foods, like cooked meat was. However, having something similar to the Burger Shot, but for pizza would be a huge boost to quality of roleplay, and small avenues of roleplay. There is a similar post for the Japanese restaurant too (#2011).
> 
> This wouldn't need a big overhaul just yet. You could begin the process with the introduction of some new items; margherita pizza, pepperoni pizza and vegi pizza. Then, the roleplay of deliveries can begin there before a job/mechanic is introduced like Burger Shot.

That would be a tremendous start and would be something I think could be enjoyed.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
