### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by qKelta** [InZidiuZ/op-framework-issue-tracker#2061]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

Alright so I had the idea of maybe being able to become a jeweler. I currently go to art school for game design and have years of experience in blender. I thought it would be cool if there was a way for me to be able to make custom chains for maybe gangs or people who just have the money to do so. I would have handful of guys who go around taking orders then during that week I would make those chains that are specified and maybe somehow be able to send you guys those models to you guys to be imported into the city. Kind of like what you guys are doing with the chest armor with the custom logos and name. I just want to help bring something extra to the community thats not just made for gangs. Something that can let me express my creativity but also bring something cool that can give gangs, friends, couples, and single individuals something to look foreword to. It could even be used for weddings or gang initiations. 
**Reason:**
Why would your suggestion be a good change to the framework?

I think It could be a good change to the framework because it would bring something that even other cities could use to expand the possibilities in there cities and give the entire community something cool to play around with. Whether they want to use it as a way to flex there money or use it as a friendship bond I really think it could give something not entirely unique but different then most servers. You can even choose if it's ran by the developers or by individuals within the server.

**Comment by AdeptCL** [comment]
This sounds like something that would be submitted on the Asset suggestion area (https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues). 

I doubt it'll be a straight addition. You should create some generic ones based on groups already in the international server, and submit them on the Assets suggestion area for approval.

**Comment by twooot** [comment]
Do you mean you would be able to cutomize jewelry in-game? Or do you want to add new types of jewelry?
If its the first one then i don't really think thats possible and if its the second one you can make a few and submit them as an asset suggestion to be added

**Comment by qKelta** [comment]
> Do you mean you would be able to cutomize jewelry in-game? Or do you want to add new types of jewelry? If its the first one then i don't really think thats possible and if its the second one you can make a few and submit them as an asset suggestion to be added

Not exactly the second but kinda. I currently got to art school to get a degree in game design and have been using blender for years. I was wanting to become a jeweler and be able to make custom chains and what not to be imported into city where I would then sell it. Kind of like how NoPixel does it.

**Comment by qKelta** [comment]
for example this isnt much but i started an outline for the blancos to eventually fill in the detail with diamonds and what not.
as well as a gambetti one im still working on.
![image](https://user-images.githubusercontent.com/93496538/140848481-f1803ad6-b08d-470b-b110-272ec877a200.png)
![image](https://user-images.githubusercontent.com/93496538/140848533-297960f2-5a35-4a3a-b325-2d50c1a4633a.png)

**Comment by InZidiuZ** [comment]
Cool idea! However, this would be something for the assets issue tracker as this isn't really something we'd be able to implement dynamically on a framework level. (See §6)
