### ISSUE TITLE
Add Supply Storage tied to Stock for Businesses

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2062]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Note: This is spitballing an idea for input/thoughts.

Add a large storage for business owners and managers to add stock to for future sales. Allow setting of prices for employees to retrieve these items from stock.  Obviously drop rates for certain items (like alcohol) would have to be adjusted to ensure ample supply for sale in the world. These items could add more variety to the delivery jobs.

Examples: 

- Mechanic computers are no longer infinite but pull from a stock that the business owner or manage would need to supply at prices set by the shop
- Burger Shot, and other restaurants, could use a similar system using the meat now available.
- Bars could require purchasing and stocking of alcohol from players. 
- Perhaps even add a Life Invader job that delivers supplies to the convenience stores using this system to allow for more finite inventory in them.
- 

**Reason:**
Why would your suggestion be a good change to the framework?
This system would potentially allow businesses to purchase more items in larger quantities over time, allow them to "take a cut" if deemed necessary, enable a greater flexibility in the player driven part of the economy for off hours and reduce the dependence on NPC vendors.  It would also add an element of management currently missing.

**Comment by AdeptCL** [comment]
I would really love this. Allows full track of materials used/sold/purchased/etc.

**Comment by cammybruh** [comment]
I believe this is what they intend to do later down the line. I’d absolutely love for this to come into fruition!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
