### ISSUE TITLE
Bean Machine local deliveries 

### ISSUE THREAD

**Issue by Brookiedoughh** [InZidiuZ/op-framework-issue-tracker#2063]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
We would like the location of the "kiosk" to be moved back behind the counter/bar instead of in front of the counter, or even in the employee break room, if possible. Additionally, I would like to have local deliveries to be added to Bean Machine. This will help my employees make money and let them have a stable income. 

**Reason:**
Why would your suggestion be a good change to the framework?
Adding these features would provide more business to Bean Machine. We have had issues in the past where customers ignore working baristas and buy items themselves, even after trying to get their attention. If the inventory is moved out of direct sight from the customers this will increase my employees sales benefiting them. The local deliveries will also help my employees financially giving them more incentive to keep working hard, and it will be easier to keep employees.

**Comment by lolayygaming** [comment]
I think this would eliminate alot of issues with people self serving when we're in the shop ready to serve the customers!

**Comment by Cuckarot** [comment]
As someone who used to work there, I can attest that these would both be great changes to the RP of being there. Too often I would have customers just completely ignore me trying to RP as a barista to help them and just self serve. Also, the local deliveries are a great idea as you only make roughly 10 dollars per item you have a customer buy, and when business is slow like it has been, it is hard to make an honest living that way.

**Comment by MVirk22** [comment]
These are really vital and awesome suggestions for Bean Machine to operate successfully. Currently the employee's make barely any money cause they have to buy the product from the kiosk themselves and then upcharge it and sell it at a small profit of $8 per item which is not enough and it forces the employees to go do scuba to supplement their income. Adding local deliveries would really help the business a lot as it will provide the employees with an appropriate source of income and encourage more employees to work at Bean Machine and for even longer durations.

**Comment by staticisdead** [comment]
I believe implementing local deliveries for Bean Machine will increase the amount of people wanting to work for the café. This will give employees a more stable income and increase the foot traffic at the shop giving more RP opportunities.

**Comment by MVirk22** [comment]
I would also like to suggest a pay increase for all the employees and the owner of the restaurant as well. It is currently less than other businesses. I had made this suggestion before and it was mentioned that it's something that needs to be handled in city but it doesn't seem like the governors have any control over the paychecks and it's something that needs to be handled by the devs.

**Comment by TheCuppcake** [comment]
I agree with all of the suggestions here. It is a quality of life thing for the business and also the employees/citizens. It would greatly improve the businesses revenue as well.

**Comment by MaxieL99** [comment]
I would also like to suggest a more clothes, drinks and foods, like drinks side: Ice coffee, Frappes, Green tea, Ice tea and Milkshake. Food side: Pancakes, Croissant and Pies, Clothes side: more Shirts and Hats, Also we get Locs orders too so we don't wait for citizens to orders

**Comment by DaxterPancake** [comment]
> I would also like to suggest a more clothes, drinks and foods, like drinks side: Ice coffee, Frappes, Green tea, Ice tea and Milkshake. Food side: Pancakes, Croissant and Pies, Clothes side: more Shirts and Hats, Also we get Locs orders too so we don't wait for citizens to orders

Clothing is suggested [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

It's also helpful to provide examples of what clothing you'd like changed & logos, etc. Even provide links or create things yourself.

**Comment by MaxieL99** [comment]
> > I would also like to suggest a more clothes, drinks and foods, like drinks side: Ice coffee, Frappes, Green tea, Ice tea and Milkshake. Food side: Pancakes, Croissant and Pies, Clothes side: more Shirts and Hats, Also we get Locs orders too so we don't wait for citizens to orders
> 
> Clothing is suggested [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
> 
> It's also helpful to provide examples of what clothing you'd like changed & logos, etc. Even provide links or create things yourself.

Same as Burgershot's shirts but for Bean Machine and for hat Bean Machine logo on it like 2nd gear hat

**Comment by DaxterPancake** [comment]
> > > I would also like to suggest a more clothes, drinks and foods, like drinks side: Ice coffee, Frappes, Green tea, Ice tea and Milkshake. Food side: Pancakes, Croissant and Pies, Clothes side: more Shirts and Hats, Also we get Locs orders too so we don't wait for citizens to orders
> > 
> > 
> > Clothing is suggested [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
> > It's also helpful to provide examples of what clothing you'd like changed & logos, etc. Even provide links or create things yourself.
> 
> Same as Burgershot's shirts but for Bean Machine and for hat Bean Machine logo on it like 2nd gear hat

Like I said above. This is not the place for clothing suggestions.

**Comment by Brookiedoughh** [comment]
In the past few days, Bean Machine has hired multiple employees just to have them resign solely because the lack of income. It is hard for them to simply pay rent for example. Having these changes put in place will help keep employees at our business long term.  Thank you.

**Comment by vol5** [comment]
The kiosk change seems like a very reasonable ask. The fact that people can buy without interacting is odd and degrades the experience. I witnessed a similar situation at burgershot the other day. The delivery add would solve the problem of employee retention due to lack of income when rp is not flowing hot. Deliveries would be giving people the option to have something when rp is not there. That is a tough situation. If employees are not making enough they will just leave to grind something else since you are locked into the job. From dev side I can see fear that once this would be added, people would choose delivery grind over rp serving. Its a fair concern. But, that option should still be there though. Sometimes people just want to put their head down and grind. A solution to this fear could be (People have to serve so many citizens per week to have access for delivery) and (employees would have to invest X-number of time into the business to gain access for delivery) - Enforced by Owner and Management. With these things aside in my opinion the least that could happen is a price reduction for the vendor products so employees can make more profit. All this to say I'm for these changes, with a few extra ideas I feel could be of value.

**Comment by claymstehling** [comment]
I think this has been half implemented but would definitely love to see the local deliveries implemented

**Comment by Brookiedoughh** [comment]
Yes, the kiosk has been moved and made for employees only! Honestly made me so happy. However, I would still love to have local deliveries for Bean Machine if possible.

**Comment by twooot** [comment]
I believe bean machine has local deliveries now and also had their paycheck increased to match burgershot
