### ISSUE TITLE
Alert System for Vehicle Lockpick / theft.

### ISSUE THREAD

**Issue by DeanoY92** [InZidiuZ/op-framework-issue-tracker#2064]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Adding an optional "Alert" system for vehicles through benny's etc. So people could chose to have an alert system that could run through their phone, make them aware if their vehicle is being lockpicked or attempted theft / tracking system of some form would be great.  
**Reason:**
Why would your suggestion be a good change to the framework?
I feel like this would benefit alot of people that want to do Scuba but alas dont because of the constant thefts that go on within the city, would stop duplicate cars and the likes.

**Comment by InZidiuZ** [comment]
Cool idea! I don't think it'll happen anytime soon, though, as the phone we currently have is deprecated and isn't exactly a pleasure to work on and extend.

**Comment by twooot** [comment]
I did this
