### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TriGod10** [InZidiuZ/op-framework-issue-tracker#2066]
**Assurance:**
New liveries for PD vehicle

**Summary:**
Can you add new state trooper and pursued vehicle liveries for all pd vehicle.

**Reason:**
It would increase the rp and would be great for PD.

**Comment by AdeptCL** [comment]
1) Wrong GitHub. You need the Assets GitHub. 

2) Liveries do not improve roleplay.

**Comment by 8017RAZ** [comment]
> 1. Wrong GitHub. You need the Assets GitHub.
> 2. Liveries do not improve roleplay.

+1 (need new liveries but not now)

**Comment by InZidiuZ** [comment]
As @AdeptCL said, this is the wrong issue tracker. This issue tracker is for the OP framework, not assets.
