### ISSUE TITLE
Reduction of Rubber Weight from 5 to 1

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2067]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Reduce the weight of rubber from 5 to 1

**Reason:**
Why would your suggestion be a good change to the framework?
With the price adjustments to rubber to make it viable for mechanics also dramatically decreased it's value to suppliers. Allowing people to carry more would offset the change (i.e. more can be carried out of the ocean). In addition, it would allow mechanics to hold the item in their lockers in amounts that would not sacrifice as much valuable scrap space.

**Comment by twooot** [comment]
I wouldn't go down all the way to 1 pound weight, i changed it from 5 to 2. If we notice it's still too heavy, we can revisit this.

**Comment by MetaHatter** [comment]
Fair and I agree. I was 50/50 on the amount (1 or 2). Erroring on the side of caution is definitely safer.
