### ISSUE TITLE
[illegal/cocaine] Replace da Plane

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2068]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
I would like to propose replacing the Coke Plane with a Coke Boat system

Process steps:
- Talk to an NPC at specific location at particular time(s) and receive a phone number and secret code. NPC then "walks away" until next time.  Only waits idle there for 5 minutes max.
- Player text messages the secret code to the phone number.
- System sends a time and "random" coordinates to a circular zone in the ocean back to player.
- Player will want to get a boat to that circle by the drop time.
- When the time arrives, an NPC plane flies over and drops the package to a random location in the circle. At this time, PD is alerted to the zone location due to suspicious air traffic.
- Players will have to locate and retrieve the floating package with a boat and then escape before the police can catch them.
- Additionally, If, in the future, there is a flag for players in whitelisted groups that flag could determine if the NPC is step 1 speaks to them. (anti-Danny tech)

**Reason:**
As its located in a seperate instance, the current process removes people from the city proper and reduces potential RP interactions.

Currently the location also presents an overall lack of risk. Its remote location offers too many windows for effortless acquisition. As a tier 2 illicit good it should be harder for people to acquire and easier for a tier 2 group to defend.

Its also annoying for PD to properly RP against.  Either they camp a location they aren’t supposed to know about, or the deed is done by the time they get there.

The proposed new system will essentially gamify the process and create many more opportunities for player interactions. (Plus add a reason to buy boats *wink*)

Ideally the steps above could also be broken into reusable framework functions for use in future jobs/activities.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
