### ISSUE TITLE
Suggestion - Hospital

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-issue-tracker#207]
**Name:**
Nate

**Summary:**
EMS should have the ability to lock doors in the hospital(particularly the surgery room). 

I know this poses an issue for if no EMS are on and people could get locked in. Perhaps a solution being a 1 way teleporter from inside the surgery room, for people to leave. But the only way in is through the doors that can be locked.

**Reason:**
Far too many people rush into the hospital and go back there, which is unrealistic. Giving EMS the ability to lock the doors would keep out uninvited guests.

**Comment by InZidiuZ** [comment]
Hey,

Yes.

**InZidiuZ**
*OP-FW Developer*
