### ISSUE TITLE
Suggestion - Rework job restaurant (Burger shot, Bean machine etc...)

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/op-framework-issue-tracker#2070]
**Summary:**
Seeing the mechanics of grilling and cooking venison...I thought you could do something like this with restaurant as well

for example: take away the public blip to display the food and make it private only to the staff of the burger shot, in this blip they will find the ingredients to make a sandwich so slice of bread and raw meat... they will have to cook it and then join them to the slice of bread 

this is just an example... I don't know what foods are in the burger shot

or an example of the bean machine could be with coffee... they buy the coffee beans, grind them once ground and got the coffee powder you have to put it in the purge and after a while gives you a cup of coffee

**Reason:**
Increased visual rp within restaurants and more things for restaurant employees to do and new ways to earn money

**Comment by InZidiuZ** [comment]
Closing due to §4 and §11. This issue has suggestions for two systems and they're not very detailed. A suggestion should include as much information on how the feature should be implemented as possible.
