### ISSUE TITLE
Change position for illegal things

### ISSUE THREAD

**Issue by kloocek** [InZidiuZ/op-framework-issue-tracker#2071]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Sure.

**Summary:**
Write a summary of what your suggestion is about.
I think changing the position of drugs and where to use flash drives or anything illegal can be changed, it will be a lot of fun by finding new places where it may have been hidden while also being something fresh

**Reason:**
Why would your suggestion be a good change to the framework?
Everyone knows the current places, even a person who has never been on the server, knows them too. In my opinion changing them every so long period of time will be a bit of fun for players.

**Comment by InZidiuZ** [comment]
This is just going to be an issue again in a week or two though, when 'everyone' figures out the new spots. Seems like a very temporary workaround to this, so will close this.
