### ISSUE TITLE
[?] PD Purchasable Vehicles.

### ISSUE THREAD

**Issue by z-Lunar** [InZidiuZ/op-framework-issue-tracker#2072]
Assurance: Have you read through the rules from the README.md file in the root folder of this GitHub repository? Yeah

Summary: Write a summary of what your suggestion is about.
Basically as it stands, PD Makes $100+ a paycheck, that piles a shit ton after about a week on duty & they have nothing to spend that cash on besides the armory. TLDR, my idea is to add a garage to MRPD Motor pool for personal vehicles, Replace the vehicle spawner with a vehicle purchase. Vary price by vehicle class/rank restriction. 

In addition to this, perhaps a change to the current "/repair" system, Charge price of parts + tax & "commission" for the repair with "/repair" this encourages players to visit mechanic shops to repair this cars instead of just being lazy and using "/repair". also covers no mechanics being around.

[-] Trooper - $5000
Chevrolet Caprice
Ford Explorer

[-] Trooper First Class - $7500
Ford Crown Victoria
Ford F150

[-] Senior Trooper - $10000
(2014) Dodge Charger
Ford Taurus
Kawasaki PD Bike

[-] Corporal - $12500
(2018) Chevrolet Tahoe

[-] Sergeant - $13500
(2018) Dodge Charger
(2013) Chevrolet Tahoe

[-] Sergeant First Class - $15000
Dodge Ram 

[-] Interceptor Units (Speed) - $25000
Dodge Challenger/Corvette

Reason: Why would your suggestion be a good change to the framework?
I genuinely feel as this would help the economy flow a bit with the shitpile ton of money some cops have, & encourage RP between cops and civilians. 

thanks for reading.

**Comment by KatLikesTacos** [comment]
I like this idea! Wouldn't it require a change to how the extras work in order to routinely visit mechanic shops? From what I've been told, taking a PD vehicle to a get a proper repair can cause the extra to fall off. I wonder if it would be possible to translate those extras into Benny's customs options instead, so they save to the vehicle permanently?

**Comment by claymstehling** [comment]
I love this, I love this, I love this. I have always thought PD should own their own vehicles. It would stop them from impounding them randomly and would actually have meaning more if they crashed them. I also love that it would make them go to mech shops more. I have always wanted to see more police interacting with the community and this is one way to get it started.

**Comment by z-Lunar** [comment]
> I like this idea! Wouldn't it require a change to how the extras work in order to routinely visit mechanic shops? From what I've been told, taking a PD vehicle to a get a proper repair can cause the extra to fall off. I wonder if it would be possible to translate those extras into Benny's customs options instead, so they save to the vehicle permanently?

mmm I don't wanna speak for Vehicle Developers, but I am sure we could somehow remedy a way to make the "/Extra **" command to work when you pull out your vehicle from MRPD?..I didn't think about the repairs messing with extras.

**Comment by z-Lunar** [comment]
> I love this, I love this, I love this. I have always thought PD should own their own vehicles. It would stop them from impounding them randomly and would actually have meaning more if they crashed them. I also love that it would make them go to mech shops more. I have always wanted to see more police interacting with the community and this is one way to get it started.

same here, your message is my same thought process currently, if I remember correctly a long time ago..."pre-opfw" we used to own our own vehicles as cops.

**Comment by xarxesthegreat** [comment]
> > I like this idea! Wouldn't it require a change to how the extras work in order to routinely visit mechanic shops? From what I've been told, taking a PD vehicle to a get a proper repair can cause the extra to fall off. I wonder if it would be possible to translate those extras into Benny's customs options instead, so they save to the vehicle permanently?
> 
> mmm I don't wanna speak for Vehicle Developers, but I am sure we could somehow remedy a way to make the "/Extra **" command to work when you pull out your vehicle from MRPD?..I didn't think about the repairs messing with extras.

perhaps make it so that /extras can be used within x feet of a repair bay at a mechanic shop? That way they get a repair at Mosleys, throw their extras back on, and then go back out on patrol. It would boost the economy a lot as well by pushing more repairs to civilian owned shops that have felt a hit to their wallets since the population cap was lowered for the server.

**Comment by twooot** [comment]
This is something that will get implemented. Here are my plans for it:

- PD Garage is limited to 5 vehicles (you can only own 5 cars)
- You're able to sell your vehicles back for half the price you bought them for
- Everyone can buy any car (Like it is rn as this is something that gets handled in RP not dev)
- PD garage is separate from the normal garage
- Repair command will charge a significant amount to be used
- Helicopters, Bearcats, Prison busses, etc. will still be spawnable without pay
- PD garage will be like the normal garage (retrieve, store, pull out) and you will be able to store your personal vehicles in it too
- You can only use the PD garage when you have the correct job
    - This means when you resign or get fired you still own the vehicles, but you will not be able to pull them out until you reinstate, for example

Let me know your thoughts on it. :)

**Comment by claymstehling** [comment]
> This is something that will get implemented. Here are my plans for it:
> 
> * PD Garage is limited to 5 vehicles (you can only own 5 cars)
> * You're able to sell your vehicles back for half the price you bought them for
> * Everyone can buy any car (Like it is rn as this is something that gets handled in RP not dev)
> * PD garage is separate from the normal garage
> * Repair command will charge a significant amount to be used
> * Helicopters, Bearcats, Prison busses, etc. will still be spawnable without pay
> * PD garage will be like the normal garage (retrieve, store, pull out) and you will be able to store your personal vehicles in it too
> * You can only use the PD garage when you have the correct job
>   
>   * This means when you resign or get fired you still own the vehicles, but you will not be able to pull them out until you reinstate, for example
> 
> Let me know your thoughts on it. :)

I personally love all of them twoot. I think the repair one charging a lot(hopefully more, maybe 2.5x the average repair prices) will also incentivize them to go to the mechs more. I love this all personally :D

**Comment by Djmeowzle** [comment]
This sounds amazing and would be cool to have different mods saved to the car, like cosmetics and performance, that way cops can work on making their own car faster to keep up with criminals.

**Comment by z-Lunar** [comment]
> This is something that will get implemented. Here are my plans for it:
> 
> 
> 
> - PD Garage is limited to 5 vehicles (you can only own 5 cars)
> 
> - You're able to sell your vehicles back for half the price you bought them for
> 
> - Everyone can buy any car (Like it is rn as this is something that gets handled in RP not dev)
> 
> - PD garage is separate from the normal garage
> 
> - Repair command will charge a significant amount to be used
> 
> - Helicopters, Bearcats, Prison busses, etc. will still be spawnable without pay
> 
> - PD garage will be like the normal garage (retrieve, store, pull out) and you will be able to store your personal vehicles in it too
> 
> - You can only use the PD garage when you have the correct job
> 
>     - This means when you resign or get fired you still own the vehicles, but you will not be able to pull them out until you reinstate, for example
> 
> 
> 
> Let me know your thoughts on it. :)

This sounds awesome, and I agree with Clay on the /repair price being something boosted to increase the odds of people going to mechanics

**Comment by rakibulhasan456** [comment]
Really liked the idea here. Now police drives recklessly and has no care about their car. They are over speeding like hell without any reason, ramming and acts like nothing happened. If this gets implemented, police will start to value their car and will start to take care of their driving which is much needed to make a balance with the normal citizen. More RP areas and balancing changes, so it's a big YEP YEP from me.

**Comment by xarxesthegreat** [comment]
> This is something that will get implemented. Here are my plans for it:
> 
> * PD Garage is limited to 5 vehicles (you can only own 5 cars)
> * You're able to sell your vehicles back for half the price you bought them for
> * Everyone can buy any car (Like it is rn as this is something that gets handled in RP not dev)
> * PD garage is separate from the normal garage
> * Repair command will charge a significant amount to be used
> * Helicopters, Bearcats, Prison busses, etc. will still be spawnable without pay
> * PD garage will be like the normal garage (retrieve, store, pull out) and you will be able to store your personal vehicles in it too
> * You can only use the PD garage when you have the correct job
>   
>   * This means when you resign or get fired you still own the vehicles, but you will not be able to pull them out until you reinstate, for example
> 
> Let me know your thoughts on it. :)

I assume we would see a change to /extra and/or a fix for the fact replacing doors removes all extras? If so, I love this idea.

**Comment by panpawn** [comment]
When this is implemented, how will changing extras/liveries work once a car has been purchased for a while?

**Comment by Milan345** [comment]
It's been so long, when is this getting implemented??

**Comment by twooot** [comment]
> It's been so long, when is this getting implemented??

@Milan345 You realize there is 349 other open issues, some having been open for about 3 years now

**Comment by Milan345** [comment]
> > It's been so long, when is this getting implemented??
> 
> @Milan345 You realize there is 349 other open issues, some having been open for about 3 years now

np,, just asking

**Comment by twooot** [comment]
This has been done
