### ISSUE TITLE
Expanded Mechanic Lockers

### ISSUE THREAD

**Issue by AZTricky** [InZidiuZ/op-framework-issue-tracker#2074]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Expanding Mechanic Lockers to 750-1000lbs

**Reason:**
Why would your suggestion be a good change to the framework?
Currently, with the lockers at 500lbs, all mechanics are limited to around 100 material items in their locker. While normally this can be fine for a shift, when things gets busy a mechanic can blow through this quickly and I have many at my shop who still feel the need to bring extra vehicles to store more materials to cover for this, even more so if the mechanic is trying to work a long shift. Every single mechanic I have at The LostMC Mechanic Shop have expressed that having larger lockers would be a benefit for their work so I suggest raising to 750 or 1000lbs if you could. Thanks!

**Comment by AdeptCL** [comment]
At the moment, you can only hold around 20 pieces of each material in the locker. On average, this is only 4-5 cars worth of repairs. The doubling of space will allow more storage to be held.

**Comment by InZidiuZ** [comment]
Locker inventories have now been increased to 100 slots, from 50.
