### ISSUE TITLE
Emote machine broke, maybe, I don't know

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#2075]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
a long time ago

**Player Identification:**
[What is your steam profile?](https://steamcommunity.com/profiles/76561198105957484)

**Summary:**
Ever since one of the last updates, emotes involving props don't work for me and others anymore. 

**Steps to Reproduce:**
Perform any prop emotes, As far as I can tell, no other specific steps. 

**Expected Results:**
For me to be able to make jokes again using prop emotes. I love holding that big torch flashlight and telling people I'm gonna push it up their ass if they don't behave on traffic stops.

**Actual Results:**
pain

## Additional Information

**Screenshots:**
I have a video showing the issue, I took it immediately after joining the server and did not take out a gun or perform any action. 
As you can see the props appear briefly then disappear. I noticed others may see some props as you use them like copbeacon while you won't, but they generally don't show.

https://youtu.be/TzArN9P0W3U

**Game Resolution:**
800x 680

**Player Data:**
I already closed the game I can't be bothered to open it again unless it's necessary

**Server:**
EU/NA #1

**Comment by InZidiuZ** [comment]
Thank you sir for the superior report. Thanks to the video presented I was able to quickly fix this issue.
