### ISSUE TITLE
Additions to the Arcade

### ISSUE THREAD

**Issue by Gingerninja78** [InZidiuZ/op-framework-issue-tracker#2076]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
i would like to suggest some much needed additions to the Arcade on popular street
An ATM beside the karaoke stage, or if that cannot be done just outside the front door
A vendor at the white mark in the picture for employees to sell food/drinks
addition of some snack items as well as the usual water and cola:
1. pidgeon milk $125 
2. pizza slices $15 similar effect as Belgian Fries but less stress reduction and a little more hunger repleneshment as dough fills you up a little more
3. hot dogs $10 food repleneshment same as tacos
4. nachos $10 as hotdogs
5. wonder waffles
also able to purchase alcohol and soft drinks from the vendor marker

**Reason:**
Why would your suggestion be a good change to the framework?
these changes/additions would be very benificial to the framework as it will give alot more roleplay opportunities for the arcade to be used as a gathering place for gamers and people wanting a chilled out place to chat and meet others. The food/drink items would obviously help with the interactions and bring some more variety to the diet of Los Santos.
As a Vendor would be placed in the Arcade could it be possible for the locks to be set to lock default at tsunamis? 
![unknown](https://user-images.githubusercontent.com/86062293/143804129-ac5ae8ae-6bb8-4d4c-b2ba-eca1c161a1a8.png)

**Comment by Salvatore-Lincoln** [comment]
really good idea's @Gingerninja78

**Comment by claymstehling** [comment]
Heya! I would love all of this in the city it would allow for so much more RP with the Arcade! :D

**Comment by MetaHatter** [comment]
InZidiuZ does not do the map updates for the framework so please don't try to reach out directly.  The github submission will be reviewed by the people that do and if it is approved it will be implemented.   No promises on acceptance or timing.

Thank you for understanding.

**Comment by RustyWaters07** [comment]
Fair enough. Only reason I reached out was I saw he had assigned this to himself last year.

**Comment by Biqley** [comment]
Change suggestions seem pretty solid and would be able to improve the arcade significantly, Ive been to the arcade and its a really cool spot but is definitely lacking some core mechanics to it that would be awesome to have.

**Comment by InZidiuZ** [comment]
I've added a store as well as made the doors lock by default on server-start. For the ATM suggestion, you'd have to post [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker) as that would be an asset issue.
