### ISSUE TITLE
Passout/K.O Mechanic for Fist fights & Snowballs

### ISSUE THREAD

**Issue by ItsLevitation** [InZidiuZ/op-framework-issue-tracker#2077]
Jay Tarantino
Discord: Levitation#4252

Summary:

Make it so that fist fighting doesn't require an EMS worker/Hospital, and also heavily reduce the damage that snowballs do.

Link:
N/A but ideally it would be a 60-120 second timer before being allowed to stand up again.

Reason:

I firmly believe that it would be a useful feature to allow people to only be temporarily knocked out after a fist fight for (x) amount of time instead of downed until reaching a hospital. This would encourage more fist fights instead of resorting right to weapons, hopefully encourage more fight night events/activities in the PFC arena as well.

It is super inconvenient and frankly slightly unnecessary that being punched a few times would permanently down someone.

With that being said, I'd also like to discuss the possibility to nerf how much damage snowballs do, so that we can have snowball fights less dangerous than if we were to shoot each other with real guns (lol)

Although they seem like small changes, I really do believe this would be a positive addition to the community.

**Comment by InZidiuZ** [comment]
See rule §11 for issues. Try to only put one topic per issue.

**Comment by MetaHatter** [comment]
Since snowballs are fixed this is now a single item ticket.

I agree bare fists should be a knockout
