### ISSUE TITLE
Taco Farmer South Side

### ISSUE THREAD

**Issue by Ryoats** [InZidiuZ/op-framework-issue-tracker#2078]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I purchased the Taco Farmer recently and i would like to get it up and running as a legit business. The things i had in mind where 
1) Adding a point of sales terminal at the cash register for transactions 
2) Make the windows able to open/close so customers can talk to employees from the streets 
3) Adding an owner salary, as well as manager and employee salary. 
4) Adding a point of sales to purchase the tacos from the state in the back of the kitchen 
5) Make the doors lockable
6)Adding delivery jobs similar to burger shot

**Reason:**
Why would your suggestion be a good change to the framework?
I think these improvements will inhence the rp exponentially for everyone invloved. Currently there are no jobs set up and as owner i have no way to hire employees in any meaningful way.

**Comment by LilDurk1** [comment]
Love the idea hope to see it happen!!!

**Comment by jhawnn** [comment]
I love this!

**Comment by claymstehling** [comment]
I agree I love this would add competition to Burger Shot and Bean machine, and establish Taco Farmer as a more legit business

**Comment by kaycorriher** [comment]
I love what Taco Farmer is adding to the city without a current infrastructure. If they could have some of the other luxuries that other business have (lockable doors, menu with employee only access, paychecks). Overall, its always an enjoyable experience to go to the Taco Farmer location and buy tacos over the convivence stores.

**Comment by Not333** [comment]
Please hook up these Taco Farmer upgrades.    The shop could be so much more then it is.
