### ISSUE TITLE
Add time remaining until next available spin at the casino.

### ISSUE THREAD

**Issue by DennisGHOSTDOGE** [InZidiuZ/op-framework-issue-tracker#2079]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yup, I have.

**Summary:**
Write a summary of what your suggestion is about.

I think we should add a time of how long it takes until you get your next spin at the casino. This should be displayed when you are at the wheel, and you cannot spin it, instead of the "You have already spun the wheel as many times as it is permited" or whatever it says.

**Reason:**
Why would your suggestion be a good change to the framework?

It's just nice to know, I'd say.

**Comment by twooot** [comment]
This has been done
