### ISSUE TITLE
[Suggestion] EMS Timestamps

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-issue-tracker#208]
**Name:**
Anderzenn#0069 (Z-105 B. Whittle)

**Summary:**
It would be really nice if the ems timestamps had actual timestamps on them, from an administrative pov. We need to check how active our members of the EMS are.

**Reason:**
I would really like it if the ems timestamps said an actual time for when the person signed on duty, and when they signed off duty. (Possible even a little thing next to it saying how long they were on for because that would make everything so much easier for us)

It would help us MTP and Board Members incredibly with checking activity of our members.
Now you might be thinking "Discord has the timestamps already" and yeah, they do. Until a week has passed, when a week has passed it just says the date instead without a time.

Example on timestamp post after a week has passed.
![image](https://user-images.githubusercontent.com/12025450/61175121-6213d100-a5aa-11e9-82a0-dc3e343eafb1.png)

**Comment by InZidiuZ** [comment]
Hey,

No.

**InZidiuZ**
*OP-FW Developer*
