### ISSUE TITLE
Add Cayo Perico Garage

### ISSUE THREAD

**Issue by hypeisrealx** [InZidiuZ/op-framework-issue-tracker#2080]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? - Yessir

**Summary:**
Hi, me and my fellow cartel players have no way of spawning their cars on Cayo Perico, i would be nice if you could add one garage in this spot - ![alt text](https://i.imgur.com/2ngfGLQ.png)

**Reason:**
More ways to RP on Cayo Perico island.

**Comment by twooot** [comment]
This has been done
