### ISSUE TITLE
Squid Games Invite Card

### ISSUE THREAD

**Issue by RoyalLuck** [InZidiuZ/op-framework-issue-tracker#2082]
---
name: Squid Games Invite Card !! 
about: As we are trying to make squid games happen and some of the dress also have been added it would be a really good item that could be added "A Squid Game Invite Card " 
title: 'Squid Games Invite Card'
labels: Squid Games
---

**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes 

**Summary:**
Write a summary of what your suggestion is about.
Squid Games Invite card will be an item which could probably be spawnned by the admins and the cards will be given to only the ones who are invited for the squid games as in the official series of squid games the card could be also flahed like we show a police batch or our id cards .

**Reason:**
Why would your suggestion be a good change to the framework?
This would help alot of player's come join our server as Squid Games is really popular and on christmas I think making a game like Squid Games in RP would be a very nice advancement of the OP framework and all its servers . As not only it will attract players but it will increase Roleplay as you there will be a lot of intraction betwwen all the RP players !! invite cards look like this in real life images are attached both of real life and in a five m server ![aewgzghlaiq71](https://user-images.githubusercontent.com/72332952/144231026-ef5b413d-7dd8-4d3d-bf61-60c60e4a4ab1.png)
![9c441824ad52a6a5209a089dc9b8c2dcb414067a](https://user-images.githubusercontent.com/72332952/144231153-b6bb3b44-a362-4c22-8282-bee5104345c0.jpg)

**Comment by ahkhan473** [comment]
MY SUGGESTION IS THAT SERVER ONWER SHOULD WORK AND CREATE COMPANY OFR COCAINE RENEW LICENSE
AFTER PAYING THE MONEY
AND THEY SHOULD RECRUIT PEOPLE HOW CAN EVERY DAY OR WITH TWO DAYS GAP FOR COCAIEN AS STATE EMPLOYEE

**Comment by twooot** [comment]
Suggestion is not relevant anymore
