### ISSUE TITLE
Suggestion: Kate Knight PillBox Memorial Photo

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2084]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Write a summary of what your suggestion is about.

- As a Kate was crucial member of EMS and seeing all the current and former EMS staff, if there is a customizable picture frame in pillbox a visual reminder of her impact to the legacy community. 

**Reason:**
Why would your suggestion be a good change to the framework?

- A memorial to someone who dedicated a good portion of their last couple years to this community. 

![image](https://user-images.githubusercontent.com/85036959/144496728-170d7b83-29df-41cd-8426-11fc6d34d2d2.jpeg)

**Comment by Lunabelle666** [comment]
I think this would mean a lot to a lot of people.

**Comment by DaxterPancake** [comment]
A memorial in her honor is already in the works, thank you so much for this suggestion. Feel free to reachout to Lunar if you have any more ideas. Thank you.
