### ISSUE TITLE
Adding Personal Locker and Vehicle Parking at Palomino FIB Building

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/op-framework-issue-tracker#2087]
**Assurance:**
Yes

**Summary:**
There are currently no Personal lockers and vehicle parking at Palomino FIB building (Sustancia RD | N.O.O.S.E).

**Reason:**
There are currently no Personal lockers and vehicle parking at Palomino FIB building (Sustancia RD | N.O.O.S.E) , but there is a vehicle spanner present. We need the personal locker in the building because it is too far away from the city PD, adding this would be great as we would be able to access our personal stuffs from the locker as an FIB Agent. 
![Desktop Screenshot 2021 12 05 - 15 25 04 44](https://user-images.githubusercontent.com/64458489/144743582-e5a4f399-e0b7-445a-8380-9e6f445aabd0.png)

And about Vehicle parking, there is a vehicle spawner and would be great to have a vehicle parking at that building as well.
![Desktop Screenshot 2021 12 05 - 15 21 10 30](https://user-images.githubusercontent.com/64458489/144743590-d2489678-8a11-4067-9682-88efdb277434.png)

Thankyou❤

**Comment by T4NZ1M** [comment]
Great Idea, a locker should be added near the clothing ring and the parking should be added as well because, at all the PDs, there are vehicle parking

**Comment by T4NZ1M** [comment]
One more thing about the vehicle parking, EMS can park vehicles from the spawner menu. So would be great to have this feature for PD too!

**Comment by Khasnuwr** [comment]
me bhi
comment

**Comment by Milan345** [comment]
Yeah, can't find any personal locker and a parking spot. It should be added.

**Comment by CloudTheWolf** [comment]
> One more thing about the vehicle parking, EMS can park vehicles from the spawner menu. So would be great to have this feature for PD too!

At MRPD there is a separate place to park, Separate from the spawner.

**Comment by T4NZ1M** [comment]
> > One more thing about the vehicle parking, EMS can park vehicles from the spawner menu. So would be great to have this feature for PD too!
> 
> At MRPD there is a separate place to park, Separate from the spawner.

Yes but I'm talking about the EMS system, EMS gets spawner menu and parking menu together, Like this:
1. Vehicle List,
2. Park Vehicle
3. Close Menu.
But police has two different place to spawn and park cars and that's what I'm talking about.

**Comment by CloudTheWolf** [comment]
> > > One more thing about the vehicle parking, EMS can park vehicles from the spawner menu. So would be great to have this feature for PD too!
> > 
> > 
> > At MRPD there is a separate place to park, Separate from the spawner.
> 
> Yes but I'm talking about the EMS system, EMS gets spawner menu and parking menu together, Like this:
> 
> 1. Vehicle List,
> 2. Park Vehicle
> 3. Close Menu.
>    But police has two different place to spawn and park cars and that's what I'm talking about.

Yeah, that's what I thought. not sure why there are separate locations. Would defiantly be better to combine them (Potentially allowing for 2  vehicle spawners at larger PDs)

**Comment by twooot** [comment]
This has been done
