### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by EddyHonein** [InZidiuZ/op-framework-issue-tracker#209]
**Reporter:**
Who is reporting this? Eddy.00
#3093.

**Summary:**
My character is getting deleted (Not main one)

**Steps to Reproduce:**
-Create the character
-Roleplay using him
-Disconnecting
-coming back and realize it is removed

**Expected Results:**
I expect my character not being deleted

**Actual Results:**
What are the actual results?
character getting deleted
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
Happened more than once.

**Comment by InZidiuZ** [comment]
Closing due to not filling out the template properly.
