### ISSUE TITLE
[jobs/police] Add blips for garages

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#2090]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Blips on PD vehicle spawners/parking only visible for police

**Reason:**
Sometimes it's hard to locate the vehicle spawners, especially for newer cops.
Adding a blip to Car/boat/helicopter spawners and parking that only PD can see would alleviate this while providing minimal intrusion for the rest of the players.

**Comment by CloudTheWolf** [comment]
I think they are the red down arrow (Like what is shown at your personal garage / public garages).
Maybe have job vehicle spawners for PD (and EMS) show as green (or some other colour), which only show when you are within a certain distance of one?  
I added EMS as, other than Pillbox, it's hard to know where to get a vehicle. Which is what I think @Spitfire2k6 is referring to, and would be beneficial for PD _and_ EMS

**Comment by Spitfire2k6** [comment]
> I think they are the red down arrow (Like what is shown at your personal garage / public garages). Maybe have job vehicle spawners for PD (and EMS) show as green (or some other colour), which only show when you are within a certain distance of one? I added EMS as, other than Pillbox, it's hard to know where to get a vehicle. Which is what I think @Spitfire2k6 is referring to, and would be beneficial for PD _and_ EMS

Yes this is what I was referring to, the same blips used on garages currently but locked to the job that can use them.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
