### ISSUE TITLE
Winery Map Marker

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2093]
Assurance: Yes

Summary: The Winery could benefit from a custom map marker.

Map Marker image:

Png1: 2000x2000px with transparent background

https://cdn.discordapp.com/attachments/876565140902924298/919050850922528808/vineyard_map_logo2k.png

Png2: 100x100px with transparent background

https://cdn.discordapp.com/attachments/876565140902924298/919050851149041674/vineyard_map_logo100px.png

If any color/image-size adjustments are required, this can be done and a new one sent.

Reason:

This removes the issue for people not knowing where to go. We have had issues with individuals not knowing where to go and this has come up multiple times during events. A map logo clearly displays location, and also gives info to new/old players which in turn could provide more business overall. No pings required, just visibility . As a business in the city a marker on the map is extremely vital to smooth operation.

**Comment by vol5** [comment]
With white outline.

100x100px
https://cdn.discordapp.com/attachments/876565140902924298/922202665214181407/vineyard_map_logo_white100px.png

2000x2000px
https://cdn.discordapp.com/attachments/876565140902924298/922202665428074536/vineyard_map_logo2k_white.png

**Comment by claymstehling** [comment]
Yes please

**Comment by twooot** [comment]
Its really painful and horrible to add custom images as blip icons. All blips are chosen from a set of blips that are available in gta v natively (https://wiki.rage.mp/index.php?title=Blips). I picked this one for now, please let me know if you find a better one (including color).

![image](https://cdn.discordapp.com/attachments/697681033264365588/924812185731997786/2021-12-27_00_53_01.png)

**Comment by vol5** [comment]
Hell yeah, that is solid for now. Ill take a look at the other options though. Thank you TWOOOT!

**Comment by twooot** [comment]
This has been done
