### ISSUE TITLE
Suggestion - Ingame Document/Paperwork

### ISSUE THREAD

**Issue by Milan345** [InZidiuZ/op-framework-issue-tracker#2094]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yes

Name:
O'Doyle#3386

Summary:
it's all about document/paperwork ingame

Link:
Link1: https://forum.cfx.re/t/release-documents-system-paid-esx-qbcore-vrp-standalone/2386305
Link2: https://github.com/apoiat/ESX_Documents
Link3: https://forum.cfx.re/t/release-esx-documents/547648

Reason:
We only have notepad as an ingame document. Implementing document system would help doing all the paperwork ingame instead of doing it in discord/other ooc applications. Also helping many job such as Lawyer, EMS, SASP etc in issuing warrants, Medical reports, citizen criminal record.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
