### ISSUE TITLE
Reevaluate Price of Burger Shot & Bean Machine Items

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2095]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

The Purchase point in Burger Shot and Bean Machine has moved which will definitely make the RP better. With those changes the price of the items should reevaluate. 

From now employees will need to give more time in serving food in the shop than before. But they still needs to buy the food and serve them to the customer. The employees don't really make profit selling the food to the customer. 

If we make the food price lower, the employees can earn some money from it. They can sell food according to the current price and make some profit. While the normal people won't need to pay extra money for the food.

So, I am suggesting to lower the Food price of these shops.

Here is a suggested price:

**Burger Shot**

- Hamburger - $15 > $7
- Cheeseburger - $15 > $7
- Belgian Fries - $25 > $12
- Burger Shot Package - $80 > $50
- Water - Unchanged**
- Coke - Unchanged**
- Green Apple Juice - Unchanged**

**Bean Machine**

- Bean Coffee - $25 > $12
- Cappuccino - $25 > $12
- Espresso - $25 > $12
- Cream Cookie - $25 > $12
- Cheesecake - $25 > $12
- Chocolate Cake - $25 > $12
- Wonder Waffle - $25 > $12
- Donut - Unchanged**

**These items are available in 24/7 store.

In Burger Shot, normal people may not be able reach to the purchase point, but for the Bean Machine, they can purchase the food at low price if they get any chance. So, If these price can be lowered only for the shop employees, then the normal people won't be able to misuse the price.

**Reason:**
Why would your suggestion be a good change to the framework?

If the price remains same then the employees don't really earning according to the time and work they are doing in these shops. They will ultimately lose some encouragement in serving food because they are not gaining much out of it. 

So, the objective will be to cheer up the people in Shop RP and to ensure that the employee gets some profit from it.

**Comment by CloudTheWolf** [comment]
> In Burger Shot, normal people may not be able reach to the purchase point, but for the Bean Machine, they can purchase the food at low price if they get any chance. So, If these price can be lowered only for the shop employees, then the normal people won't be able to misuse the price.

I believe this has already been addressed so that there store points are not locked to the job (Similar to Mechanic computers)

**Comment by rakibulhasan456** [comment]
@CloudTheWolf Yes, now it's locked to the job, that's a good change. 

So now If the price gets lowerd (just like the mechanic shop ) the employees would have get the benefit from these SHOP RP…

**Comment by twooot** [comment]
> > In Burger Shot, normal people may not be able reach to the purchase point, but for the Bean Machine, they can purchase the food at low price if they get any chance. So, If these price can be lowered only for the shop employees, then the normal people won't be able to misuse the price.
> 
> I believe this has already been addressed so that there store points are not locked to the job (Similar to Mechanic computers)

The stores are now locked to the job

**Comment by twooot** [comment]
I went over the prices. I didn't go quite as low as you suggested, but I dropped them a significant bit.
