### ISSUE TITLE
Reworking med kits

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2096]
**Assurance:**
Have you read through the rules from the README.md file in the root folder of this GitHub repository?

- Yes

**Summary:**
Write a summary of what your suggestion is about.

- Personally, the way medkits currently work as health boosters to the point you can go back to full health after being shot multiple times feels very distracting from realistic RP/shootouts. I don't think medkits should allow their effect to "stack" or simply give you another full chance. 
This is not only the case in shootouts, but in many other situations when peds survive usually consequential scenarios (heavy car crashes, flying out of the car window, falling from high roofs etc.) with little to no effect. Limiting the use of medkits could improve RP as to people becoming more careful with what they do (reduced speed, no risky jumps for little reason) and them also using hospital services accordingly.
Here is what I think could improve its use:

- either add a downtime to using medkits so they cannot stack the effect
- or make it so medkits only have an effect when bleeding, ergo they stop the bleeding and increase your health by a little, but cannot be used afterwards.

I realise this is a delicate issue, as shootouts can be a big part of gang/police RP. But this is why it is a suggestion after all.

**Reason:**
Why would your suggestion be a good change to the framework?

- This will still give a vital role to medkits, but doesn't allow it to become a cheap tool to avoid RP.

**Comment by claymstehling** [comment]
I feel like IFAK's would fall under here as well as they don't really have a use currently

**Comment by TheOneLizard** [comment]
if medkits were to only stop bleeding, IFAK's could give actual health boosts and make it contraband. That would give them purpose and make them a precious item to have, would open up new dynamics to firefights

**Comment by MetaHatter** [comment]
It seems that the concern is clear, but there are multiple suggestions here lacking some details.  Would you be requesting a longer time between use or a longer time that you are immobile/actively using the item?  Do you have a number of seconds in mind?  How much health would you want it to restore?  Would this apply equally to PD as well?

The more detail that's included the easier it is.

**Comment by TheOneLizard** [comment]
I appreciate the input. I'm not exactly sure how to balance things out nicely, but below I will make three different suggestions of how it could work.

Hard nerf:

- medkits do not heal, they only stop a bleeding.
- health increasing items could be the IFAK, oxy or the soon to be introduced meth. (IFAK is however supposedly gonna be the oxy prop, unless I misunderstood sth)

-> this would make illegal items attractive to have for crims, but obviously they would either be contraband or class A


Semi-hard nerf:

- medkits can still heal, but only up to half your health.

-> would still make medkits viable, but not blatantly too powerful


Light nerf:

- medkits still heal as before, however they have a cooldown in usage of 20-30 seconds.

-> this would not allow anyone to camp for too long just to restore health


Personally, I favour the first option, as it increases the intensity behind a gunfight, and such events have more meaning behind it as they become riskier.

In case the hard nerf happens, would PD require an equivalent health booster they can use? I think that would highly depend on how common health boosters would be.

Maybe this is giving a better understanding of the matter.

**Comment by twooot** [comment]
> I feel like IFAK's would fall under here as well as they don't really have a use currently

IFAKS were balanced with OXY, they are the same now

**Comment by twooot** [comment]
Medkits, IFAK and oxy's affects all have been reduced and i did do a short cooldown for first aid kits but time wise they will still restore more health than ifak/oxy
