### ISSUE TITLE
Suggestion: Department of Corrections

### ISSUE THREAD

**Issue by Skonchy** [InZidiuZ/op-framework-issue-tracker#2097]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes

**Summary:**
Below is a list of changes that would make the Department of Corrections a fully fleshed-out piece of content that would extend RP on the server. These changes were thought of as ways to improve player experience while in jail, while also affording more RP for all involved in the justice system. Not all of the below are necessary, just a collection of ideas that would take RP to the next level in and around the prison.

1) If there are active DOC, place an inmate in a cell when jailed similar to how peds are sent to beds upon checking in at Pillbox Medical Centre.
2) Inmate Work Details
     a) Move cleaning out of the yard and into the laundry room/around the interior to incentivize players cooperating with DOC. If possible, have this conditional with whether DOC is on duty or not as with 1)
     b) Allow inmates to cook in the kitchens with the ability to find contraband and earn money, as well as feed their fellow inmates.
     c) Allow inmates to create stashes around the prison given enough time to create it. Stashes can only be seen with the flashlight similar to evidence but accessible by hitting k within range as normal **when not a law enforcement/DOC character**
     d) **Potentially New Interior for this one.** Allow inmates to stamp license plates to earn money with a chance to generate fake license plates or receive raw materials.
     e) Allow inmates to be taken off-site to the mine to work for money with the ability to find contraband.
     f) Inmates given a life sentence (permanent or semi-permanent stays) are given a special job which pays 0, making them reliant on work detail for commissary money. These inmates would then have access to a special list of "lifer only contraband" that could be given at the same chance as regular contraband from the above jobs.  This contraband could then be smuggled out and impact the outside economy as lifers would be the only source of this contraband.
3) Implement /jailalter for DOC. Give safety parameters to avoid over/under-charging / abusing and add logs to prosecute abusers.
4) Commissary System
      a) Have a shop that inmates can use to purchase medkits, food and drinks, miscellaneous items
5) Implement the pay phones
     a) Inmates have their phones and radios confiscated upon being brought into the prison. Allowing inmates to make calls using the pay phones for a cheap cost would be great. Limit to manually input number or existing contact list. No texting availability.
6) Remote Command Center
     a) Allow DOC players in "the Bubble" command center in the prison to open/close any jail door or gate from within the Bubble.
     b) Allow DOC players in "the Bubble" to activate a PA System to broadcast their voice to all players inside the prison grounds to make prison-wide announcements.
7) Current Interior Bug Fixes
     a) There is a gate which can be accessed from the hallway between the cell block and the laundry room, without being in sight.
     b) Fix the main door to the prison. Door unlocks and opens but has a stationary second door behind it. (Just to the left of the gate when looking at the gate)

**Reason:**
Why would your suggestion be a good change to the framework?
The Department of Corrections being added into the framework expands whats possible for role play on OPFW. The above features take steps to shift the idea of prison from a punishment (OOC) to an enjoyable OOC experience that is purely for IC punishments and character growth.

**Comment by Nuziatella** [comment]
> **Assurance:** Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes
> 
> **Summary:** Below is a list of changes that would make the Department of Corrections a fully fleshed-out piece of content that would extend RP on the server. These changes were thought of as ways to improve player experience while in jail, while also affording more RP for all involved in the justice system. Not all of the below are necessary, just a collection of ideas that would take RP to the next level in and around the prison.
> 
> 1. If there are active DOC, place an inmate in a cell when jailed similar to how peds are sent to beds upon checking in at Pillbox Medical Centre.
> 2. Inmate Work Details
>    a) Move cleaning out of the yard and into the laundry room/around the interior to incentivize players cooperating with DOC. If possible, have this conditional with whether DOC is on duty or not as with 1)
>    b) Allow inmates to cook in the kitchens with the ability to find contraband and earn money, as well as feed their fellow inmates.
>    c) Allow inmates to create stashes around the prison given enough time to create it. Stashes can only be seen with the flashlight similar to evidence but accessible by hitting k within range as normal **when not a law enforcement/DOC character**
>    d) **Potentially New Interior for this one.** Allow inmates to stamp license plates to earn money with a chance to generate fake license plates or receive raw materials.
>    e) Allow inmates to be taken off-site to the mine to work for money with the ability to find contraband.
>    f) Inmates given a life sentence (permanent or semi-permanent stays) are given a special job which pays 0, making them reliant on work detail for commissary money. These inmates would then have access to a special list of "lifer only contraband" that could be given at the same chance as regular contraband from the above jobs.  This contraband could then be smuggled out and impact the outside economy as lifers would be the only source of this contraband.
> 3. Implement /jailalter for DOC. Give safety parameters to avoid over/under-charging / abusing and add logs to prosecute abusers.
> 4. Commissary System
>    a) Have a shop that inmates can use to purchase medkits, food and drinks, miscellaneous items
> 5. Implement the pay phones
>    a) Inmates have their phones and radios confiscated upon being brought into the prison. Allowing inmates to make calls using the pay phones for a cheap cost would be great. Limit to manually input number or existing contact list. No texting availability.
> 6. Remote Command Center
>    a) Allow DOC players in "the Bubble" command center in the prison to open/close any jail door or gate from within the Bubble.
>    b) Allow DOC players in "the Bubble" to activate a PA System to broadcast their voice to all players inside the prison grounds to make prison-wide announcements.
> 7. Current Interior Bug Fixes
>    a) There is a gate which can be accessed from the hallway between the cell block and the laundry room, without being in sight.
>    b) Fix the main door to the prison. Door unlocks and opens but has a stationary second door behind it. (Just to the left of the gate when looking at the gate)
> 
> **Reason:** Why would your suggestion be a good change to the framework? The Department of Corrections being added into the framework expands whats possible for role play on OPFW. The above features take steps to shift the idea of prison from a punishment (OOC) to an enjoyable OOC experience that is purely for IC punishments and character growth.

Ok. Let's break this down.

1. Moving the spawn in location is something that can be moved but why should it be moved? This seems like something that can lead to abuse or briefing. 

2. A) Jobs are left in the open and public areas to make them not reliant on other systems or prevent abuse.
 B) Adding contraband is something that could be done but not in the short term as various systems and aspects need to be discussed. Also, what items "should" an inmate be able to find? 

C) Currently this option isn't available but if it were able to be available there is possible abuse that could be had. What decides the user ability to create these permanent inventories similar to lockers? Who decides this? Can't any inmate create these? Can you create more than one? Can there only be a limited amount? What decides how long "permanent" is? What prevents abuse from criminal and/or correctional officers?  Etc.. 

D) Creative and interesting. You would need to consult the assets GitHub and request such an interior 1st and with an ok from a map developer then submit script support in this GitHub. 

E) redundant with other systems requested above

F) are there any current lifers? Is there community support across the divisions for this? This seems specific and unique to certain circumstances and/or characters. Server Managers/community managers can spawn items into inventories to support this feature temporarily. For the scripting time investment required by the script developers to support this feature, it lacks the framework wide impact to dedicate the time that could potentially be spent on it. They can weight in themselves, but I don't see this as a likely feature.

3. This is already a feature available via the /jail /unjail command.

4. There is complimentary vending machines in the lobby. As far as medkits and other items, I don't see this is something that would be required. If a person is injured where they could require a medkit, they could just request ems. I don't see why would deny roleplay opportunity here.
 
5. The current phone system does not support this feature but it's something the script developers can visit and see if it's possible with our current phone script.

6. This is the intention of the bubble. Very nice request! 

7. This isn't the correct GitHub for this request. Submit your request on assets GitHub. [Assets Github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

**Comment by Skonchy** [comment]
> Ok. Let's break this down.
> 
> 1. Moving the spawn in location is something that can be moved but why should it be moved? This seems like something that can lead to abuse or griefing.
> 2. A) Jobs are left in the open and public areas to make them not reliant on other systems or prevent abuse.
>    B) Adding contraband is something that could be done but not in the short term as various systems and aspects need to be discussed. Also, what items "should" an inmate be able to find?
> 
> C) Currently this option isn't available but if it were able to be available there is possible abuse that could be had. What decides the user ability to create these permanent inventories similar to lockers? Who decides this? Can't any inmate create these? Can you create more than one? Can there only be a limited amount? What decides how long "permanent" is? What prevents abuse from criminal and/or correctional officers? Etc..
> 
> D) Creative and interesting. You would need to consult the assets GitHub and request such an interior 1st and with an ok from a map developer then submit script support in this GitHub.
> 
> E) redundant with other systems requested above
> 
> F) are there any current lifers? Is there community support across the divisions for this? This seems specific and unique to certain circumstances and/or characters. Server Managers/community managers can spawn items into inventories to support this feature temporarily. For the scripting time investment required by the script developers to support this feature, it lacks the framework wide impact to dedicate the time that could potentially be spent on it. They can weight in themselves, but I don't see this as a likely feature.
> 
> 3. This is already a feature available via the /jail /unjail command.
> 4. There is complimentary vending machines in the lobby. As far as medkits and other items, I don't see this is something that would be required. If a person is injured where they could require a medkit, they could just request ems. I don't see why would deny roleplay opportunity here.
> 5. The current phone system does not support this feature but it's something the script developers can visit and see if it's possible with our current phone script.
> 6. This is the intention of the bubble. Very nice request!
> 7. This isn't the correct GitHub for this request. Submit your request on assets GitHub. [Assets Github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)


1) If this system is conditional with whether a Corrections player is around, how could it be abused? Additionally if there ARE DOC around, how could it be abused? We have procedures in place that entirely center around the criminal PLAYERS having a good time, so leaving someone in a cell unattended will not happen. In the same way, how could any of this process be considered griefing? The idea with everything is to extent RP past the point of arrest, and to incentivize players to engage in this RP.

2) I agree with parts of this statement. I think leaving the cleaning job out in the yard to expedite release **when there aren't DOC around** is perfect and fits the climate of the server. Like I said above, the request is centered around extending RP and if all jobs are left available to the public without engaging with DOC, the truth is players will not engage with DOC. That is one of the sad truths of being in a public server. The contraband being produced from jobs should remain in restricted jobs that require interaction with DOC. This adds incentive for players to truly engage in the prison system as they have the possibility to get something physical for their characters out of it.
     b) I've only put a small amount of thought into what contraband should be able to be found but very small amounts of weed to be rolled into joints, cigarettes, acid tablets, maybe even oxy on a very rare chance. Small concealable weapons like switchblades, brass knuckles, and knives. Maybe long term introduce a "shiv" weapon.

      c) I know this one is a tall ask as there is no system remotely close to this currently. **At the end of the day, I don't know your systems as well as you do, so I'd like this to be a conversation. The following are just my initial ideas.** To determine when a user can create a stash: I'm not sure if Bolingbroke has its own zone code in FiveM's natives but if so, if the player is in that zone then they have the ability to create a stash. If the prison doesn't have a zone, it wouldn't be too hard to grab four points just around the prison and if the player is within the contained area, the stash can be created. As for the specifics of what "permanent" is, I'd think a stash that persists for a week is a good fit. This allows players which are coming in for reasonable sentences multiple times a week to interact with the stash system, as well as simulates facility shake downs in the event the stashes aren't found. I think that 1 stash per inmate at any time is a good start as it scales the best with population. Any inmate would be able to create these and I'd like to see these inventories be much smaller, perhaps only 2 or 3 spaces to hold items. Ideally, all inmates would be able to access all stashes, granted they knew the locations. I'm not sure how these storages *could be* abused as their intention is to hide items from corrections officers. The corrections side of it would be to find them and destroy them at reasonable intervals, defined in SOPs.
      
      d) There's a couple out there that just don't match the quality of the rest of the prison currently.
      
      **HEADING TO WORK THE REST WILL BE EDITTED.**

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
