### ISSUE TITLE
About the t/[command]

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2098]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
#1185 In this suggestion, it was said that "You can now use commands without prepending the "/". That would mean ooc hello would work as well." But actually, this doesn't work for every command. /e [emotes], job special commands don't work without entering "/".
Also if you don't enter "/", suggestions also don't pop up. So either add "/" automatically when pressing "T" or add support for all commands without the "/"
 
**Reason:**
Why would your suggestion be a good change to the framework?
As there is no use of the "T" bar without entering "/" before entering commands, so I think this should be added, and also as it already supports some commands without the "/", then why not all commands :)

**Comment by InZidiuZ** [comment]
This issue has now been resolved. Doing 'e wave' in the chat will now work as expected.
