### ISSUE TITLE
Towing Hot Vehicle - Timer/Idle

### ISSUE THREAD

**Issue by nealj121** [InZidiuZ/op-framework-issue-tracker#210]
**Name:**
neal121#8063

**Summary:**
Hot Vehicles while towing can be a real pain to discover.

**Reason:**
It would be great if the timer on the hot vehicle radio was less. I have spent 20minutes going in circles, checking alleys, checking hidden garages for a car I am sure is gone... I checked entire street. All of vinewood basically. Streets around it. Nothing. 

Plus maybe more than 1 car at a time in case you have 2-4 other tow trucks out and about.

**Comment by InZidiuZ** [comment]
Hey,

Instead of the hot vehicle staying "hot" for up to 30 minutes, the timer has been reduced to 20 minutes instead. This change will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
