### ISSUE TITLE
Not able to store car after doing upgrades

### ISSUE THREAD

**Issue by Epps30** [InZidiuZ/op-framework-issue-tracker#2100]
Today I was driving my vehicle around, drove it to second gear to get a repair and my friend wanted to put upgrades on it for me. I gave her keys and she bought the spoiler, 100% armor and turbo. We then went to a garage to store the vehicle and when we tried, it said i no longer owned my vehicle. The vehicle then was recognized as a local car as we found out when advised by staff to tow the car and impound it. The upgrades were completely lost.

**Comment by twooot** [comment]
I cant reproduce this, is this still an issue or could it have been a one time thing considering cars scuff sometimes

**Comment by twooot** [comment]
Closing because of no response
