### ISSUE TITLE
Garage Not Working Correctly 

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/op-framework-issue-tracker#2101]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Djmeowzle

**Summary:**
Write a short summary of what you are experiencing.
The garage at my newly bought house, Joad Lane 1 isn't able to store any vehicle that isn't directly over the garage marker.

**Steps to Reproduce:**
Include what steps are needed in order to reproduce this issue.
Take a vehicle where the driver's seat is too high up for the garage, Ex: Phantom, and try to park it normally.

**Expected Results:**
What are the expected results?
The car should go into garage without problems

**Actual Results:**
What are the actual results?
"no vehicle found" pops up, no other info.

## Additional Information
Again, cars driven over the marker will park, but all others will not.

**Game Resolution:**
What is your game's resolution?
1920x1080 16:9

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://imgur.com/a/uB30xbl

**Server:**
What server/community did this issue occur in?
Legacy Roleplay #1

**Notes:**
For anything else noteworthy.
Twoot better be the one pushing the fix <3 all seriousness, take your time, I know it's not that high priority, but if it's an easy fix of moving the garage location, that will work.

**Comment by twooot** [comment]
I cant replicate that issue
