### ISSUE TITLE
Suggestion Removed snowball damage

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#2103]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Remove snowball damage. injuries and headshot ragdoll

**Reason:**
Why would your suggestion be a good change to the framework?
They hurt more than most bullets, it makes no sense.

**Comment by Nuziatella** [comment]
This will be done.

**Comment by twooot** [comment]
This has been done
