### ISSUE TITLE
Suggestion Hayes Improvements

### ISSUE THREAD

**Issue by staticisdead** [InZidiuZ/op-framework-issue-tracker#2106]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
1. Lockers moved into the staff room along with adding a changing circle
2. Moving the material purchasing to the Laptop at the front counter
3. Replacing the Bean Machine coffee machine with a snack machine
4. Replacing the bay doors with the same door style as second gear or adding the ability to lock the doors in the up position
5. Removing invisible desk/shelving from the staff room and from behind the counter along with the items on them
6.  Removing the dumpster on the west side of the building

**Reason:**
Why would your suggestion be a good change to the framework?
1. Putting the lockers into the staff room and adding a changing circle will give employees a place to feel comfortable to change into their work attire and dress to code
2. Moving the material purchasing to the laptop up front will not only give space for the lockers in the staff room it also keeps the rp of it locked to a computer for ordering parts
3. Replacing the coffee machine with a snack helps keep the employee at the shop as well as provides food for customers in need instead of expired coffee that burns their insides :)
4. Replacing or adjusting the Bay door will help customers to know when employees are there instead of driving by because the doors are closed in their prospective.
5. Removing the shelving/desk and items floating will make for a more immersive environment
6. Removing the dumpster will keep it from bugging out and flying though the wall into people sitting on the couch inside

**Comment by CloudTheWolf** [comment]
@staticisdead this would probably be one for https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by RetroCharles** [comment]
I believe the requests above would definitely help with the overall experience at Hayes Auto body for both the employees and customers.

The accessibility to have a changing circle can help provide staff with a place to quickly change in and out of uniform.
The personal lockers into staff room and Material purchase shop to the front desk, makes more sense in an "real world" immersion aspect.
Adjusting the bay doors to stay open when locked is very essential. Having the doors close when inside the shop (even when working on cars) creates an awkward customer experience. Also having the ability to lock the doors in an "open" position can make the shop more appealing during business hours.
The dumpster needs to be removed on the side of Hayes, bugs out, or constantly getting hit and hitting customers/cars inside the shop.
Also Snacks > over
:) Hopefully we can see these improvements in city very soon!
