### ISSUE TITLE
Add Pillbox in Cayo Perico

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2107]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add a pillbox in Cayo Perico. So that we can check-in there in emergency situation.

**Reason:**
Why would your suggestion be a good change to the framework?

If someone goes down in cayo perico its not possible to bring him back to city without the help of police/ems. Sometimes there is no EMS in city and that time we have nothing to do but to take respawn. It is impossible for anyone to bring someone to city without the help of police/ems because when you try to cross the cayo border the body drops in the water. But only if there was a pillbox in cayo, we could have use it in emergency situation.

**Comment by CloudTheWolf** [comment]
I believe this is already in the works

**Comment by twooot** [comment]
This is already in the works. We are finishing up a custom interior for the cayo medical station and then it will be integrated into the framework

**Comment by twooot** [comment]
This has been done
