### ISSUE TITLE
Suggestion: Add command for police to take off cuffed suspects mask/hat/glasses

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2108]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
Add a command for police to use to take off a cuffed suspects hat/gloves/fingerprints (perhaps something like ``/remove_hat_mask_glasses``). This command would assumingly be proximity based.

**Reason:**
_Why would your suggestion be a good change to the framework?_
It would make sense that a police officer could take off a suspects hat/mask/glasses if they're cuffed. Often people won't comply with police doing it with /me, or will take a long time to figure out to do so. Adding this as a command would smooth line this part of the RP that happens with nearly every suspect.

**Comment by DaxterPancake** [comment]
Alternatively you could add three more buttons to the current H menu for police that remove hat, glasses or mask when standing behind a cuffed suspect.

**Comment by claymstehling** [comment]
> Alternatively you could add three more buttons to the current H menu for police that remove hat, glasses or mask when standing behind a cuffed suspect.

that would be dope

**Comment by twooot** [comment]
This has been done.
/remove_mask [server-id]
/remove_hat [server-id]
/remove_gloves [server-id]
/remove_glasses [server-id]
