### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Frostposeidon** [InZidiuZ/op-framework-issue-tracker#2109]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
2013 Ford Mustang Shelby GT500 the tail lights and breaks
**Reason:**
Why would your suggestion be a good change to the framework?
I think it be great and effective to have the tail lights turn down so they are not bright to the point it's like flood lights on the back of the car and the breaks don't exist i have fully upgraded the whole car and the breaks are bad like i have to use hand break to get the car to stop i  would like to have the breaks fixed please if possible i have attach a photo of the tail lights as well.
thank you 

Kind Regards

FROST LXII[]
![20211224155648_1](https://user-images.githubusercontent.com/92272276/147363370-60948818-7be4-4806-ae31-0e2e8c3b2047.jpg)

**Comment by SirPiff** [comment]
What do you mean? I love having a portable beacon of Gondor, give people the true flashbang experience.

But yeah I agree it's very bright.

**Comment by twooot** [comment]
This is an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
