### ISSUE TITLE
PDM listed as favorites contact

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#211]
**Name:**
SteezyRen

**Summary:**
Instead of PDM tweeting out to people trying to get a hold of us I recommend that PDM should be listed in everyones phone under favorites so they can text us to see if anyone is available to take appointments.

**Reason:**
As fun as it is to just stand in the shop doing nothing until someone comes in, I think it would be more eventful if people made appointments via text message to PDM and anyone in the city whose current job is PDM can reply to the text. That way we don't have to spam twitter in game or discord whenever we are in a city.

**Comment by InZidiuZ** [comment]
Hey,

Will not be making any changes to the current phone as a new one is in the works (see "Projects"), will note this down though, and if still relevant for the new phone, take this into consideration. Closing for now.

**InZidiuZ**
*OP-FW Developer*
