### ISSUE TITLE
[vehicle/wheelchair] Make the wheelchair not require fuel 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2110]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
The wheelchair vehicle that EMS provide to patients following ICU/Surgery has a fuel system that does not make sense, since it has no engine. As such I feel this vehicle should not use fuel / battery. (Potentially reduce the top speed as well)

**Reason:**
This would allow for more enhanced EMS/Injured individual RP and remove limitations on what the patient can do while in a wheelchair.

**Comment by InZidiuZ** [comment]
The wheelchair is an addon-asset. I would suggest making a suggestion about it [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues), and suggest the vehicle class to be changed to 13 ('Cycles') which would prevent it from requiring fuel.

**Comment by CloudTheWolf** [comment]
Raised (Here: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/570) and got the following response
>joevapes3 commented 1 hour ago
>So this would require script intervention, as the wheelchair dummy model is based on a vehicle, not a bike. So when you try to change it's class to bike it crashes the asset. I would suggest making a suggestion here: https://github.com/InZidiuZ/op-framework-issue-tracker/issues
