### ISSUE TITLE
Alert PD of lethal weapon related pillbox admission

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2112]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Upon admission to a public hospital (not Granny) for injuries suffered from a firearm or stabbing weapon inform PD.

Process
- Player checks in to the hospital
- System determines if injury is from bullets/stabbing
- If so, "heal" timer is increased to 5 minutes and Police are alerted with CID/Name/Location (EMS/PD can release early)
- If no one manually releases the patient they are free to go.
- If not, on inspection, have the injury show the bullet impact (w/serial or collectable for evidence?) or type of wound (knife, machete, etc)

**Reason:**
Why would your suggestion be a good change to the framework?
Reporting these types of injuries occurs OOC and makes sense. It will increase the use of underground medical facilities else provide PD with evidence potentially tying a person to a scene.

This ties to suggestion #2111 as part of an overhaul to criminal medical care.

**Comment by twooot** [comment]
I don't think this would be a good addition. You're pretty much preventing criminals from checking into pillbox
