### ISSUE TITLE
Changing of Bar's

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2113]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Changing the bars for the bars and clubs to work the same as Burger Shot and Bean Machine. Locked to the job and cheaper for the employees to purchase.

**Reason:**
Why would your suggestion be a good change to the framework?

This would be great as the changes made to Burger Shot and Bean Machine already are providing for a great change, I think it should be transferred over to the Bars and Clubs. Cokes are very cheap, and then Whiskey is $200 and Vodka is $100, I feel like the prices are not comparable, I think altering these prices to reflect the changes else where in the framework will allow for a lot more RP and a lot more transactions occurring at business's. I also think that the shops should be locked to the job at hand. Nobody should be able to run in and buy the drinks randomly from the bars.

**Comment by Sabakyo** [comment]
I think this would allow for a lot more fluid Roleplay. This would really allow bartenders at these locations to actually make profit on the drinks as the current retail rate is already at the top of the budget of what players are willing to pay for the drinks.

This lets the business make some profit on the drinks and the bartenders have the opportunity to make a cut outside of the ticks and tips.

**Comment by twooot** [comment]
This has been done
