### ISSUE TITLE
EMS Stun Gun

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2114]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add an EMS stun gun that has a MUCH longer duration i.e. 1 minute. (Maybe make it pink or orange)

**Reason:**
Why would your suggestion be a good change to the framework?
EMS are often prohibited from carrying lethal weapons of any kind.  Enabling a longer stun time for EMS-only stun guns will allow them more time to escape a bad situation. It will also, hopefully, help to discourage trolling around pillbox.

**Comment by claymstehling** [comment]
Honestly, yeah I love this. I think it would definitely discourage trolling and would allow them to protect themselves even more if there was a mountain lion situation as well.

**Comment by DaxterPancake** [comment]
I don't really see why this would be needed.

If you're in a bad situation or what you could percieve as a bad situation then you can call the police to help you.

If there is trolling around pillbox, report it so that staff can tell them to piss off.

**Comment by Sabakyo** [comment]
I can see it's uses with specific situations but those can be dealt with through the existing stun gun. The situations around trolling is a culture one and should be directed to staff anyways.

**Comment by CloudTheWolf** [comment]
The only use I could see would be for Mountain Rescue to deal with the Mountain Lions. Maybe have it be Purple, only work on Animal Locals, and call it "EMS Tranquilizer" with a 30 ~ 60 second Duration?

**Comment by twooot** [comment]
> I don't really see why this would be needed.
> 
> If you're in a bad situation or what you could percieve as a bad situation then you can call the police to help you.
> 
> If there is trolling around pillbox, report it so that staff can tell them to piss off.

I agree with Daxter. Instead of tasing people EMS should call PD to deal with certain suspects. Spam tasing is already considered powerful so i'm not giving people the ability to pretty much spam tase someone by tasing them once

**Comment by TheOneLizard** [comment]
I would agree with a tranquiliser gun for animals, so ems is not threatened by cougars anymore when having to do rescues up north
