### ISSUE TITLE
Underwater valuable item collecting job in Cayo Perico

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2115]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Underwater valuable item collecting job in Cayo Perico. The collection is similar to the sunken ship but it has different items and some additional procedure to get the items.

Items that will get from underwater:

- **Coins**
- **Oyster**

There will be different types of coin,

1. **Gold Coin** - These are valuable and drop rates are low.
2. **Silver Coin** - Better drop rate and less valuable than Gold Coin,
3. **Copper Coin** - Drop rate is more and less valuable.

There will be decent amount of Oyster drop rate. Oyster needs to be harvested and after that we will get **Pearl**.

After harvesting oyster we will get different types of Pearl,

1. **South Sea Pearl/White Pearl** - It has low drop rate and highest value.
2. **Tahitian Pearl/Black Pearl** - Less valuable then White Pearl and better drop rate.
3. **Akoya Pearl** - It is more common and worth less.

After getting different types of coins and pearls we can sell them to pawn shops in main city.

[Item Collecting Location](https://imgur.com/OsDHc0v)
[Pearl Harvesting Location](https://imgur.com/snygRAL)
[Harvesting Table](https://imgur.com/K7h5Bgx) - Need to clean the table and put some harvesting stuff.

As people will go to cayo perico either by plane/boat, the selling price should be more reasonable from which they could actually earn something.

**Reason:**
Why would your suggestion be a good change to the framework?

Most of the people goes to Cayo Perico for cocaine business. People don't go there regularly for party or tourist purpose. After removing that from cayo perico it reduced the attraction to this island. So a regular activity in this island will increase the attraction to this island which will make more RP around there. As people needs to come here by plane/boat it will also create more aviation and boat RP. Hope this new job will attract more people to the cayo perico regularly.

**Comment by antihero6713** [comment]
I like this idea

**Comment by twooot** [comment]
We have something similar now, i'm gonna close the issue for now. If there is anything else let me know
