### ISSUE TITLE
Adding ATM inside N.O.O.S.E (FIB) Building 

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/op-framework-issue-tracker#2116]
**Assurance:**
YES

**Summary:**
Adding ATM inside N.O.O.S.E (FIB) Building to Withdraw and Deposit money.

**Reason:**
Need to add ATM in N.O.O.S.E (FIB) Building, it is functional right now and all the other Medical centers and PDs have ATM, So it would be great to have ATM in this NOOSE (FIB) building as well.

SUGGESTED PLACE INSIDE NOOSE BUILDING:
![Desktop Screenshot 2021 12 26 - 15 48 40 57](https://user-images.githubusercontent.com/64458489/147811827-d6136c34-1653-4636-b448-9ebc9adaf940.png)
![Desktop Screenshot 2021 12 26 - 15 46 42 52](https://user-images.githubusercontent.com/64458489/147811848-40c4f82a-7f1b-4961-872b-dbca4233ae38.png)
![Desktop Screenshot 2021 12 26 - 15 47 42 86](https://user-images.githubusercontent.com/64458489/147811857-eabcb28f-6c1a-41f0-82e8-341978ab6261.png)

LOCATION:
![noose](https://user-images.githubusercontent.com/64458489/147811910-014b0e0c-9910-4be4-ad3b-e5fa5a9f1187.png)
![Desktop Screenshot 2021 12 26 - 15 50 45 18](https://user-images.githubusercontent.com/64458489/147811865-ecdebdb6-965a-43a8-bd98-0097c75336d3.png)

**Comment by Khasnuwr** [comment]
vote dilaam 🥇

**Comment by twooot** [comment]
This is an issue for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
