### ISSUE TITLE
PD disable airlift command

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2117]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add PD command for downed suspects that either prevents them airlifting or forces airlift to a Boilingbroke "medical area".

**Reason:**
Why would your suggestion be a good change to the framework?
To reduce the chance of a rule break that would require staff intervention.  It should not affect any scenarios negatively as the airlift functionality is only supposed to be used when no one is near.

**Comment by twooot** [comment]
This could very easily be abused imo
