### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by tbone0tbone** [InZidiuZ/op-framework-issue-tracker#2118]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Write a summary of what your suggestion is about.
Channel up and down buttons for radio 
**Reason:**
Why would your suggestion be a good change to the framework? This suggestion would be beneficial to roleplay because as a mainly police character player we switch between pd and ems radio quite frequently and also get into multiple scenarios at the same time it would be nice to utilize the quick button to go up or down if there’s a bank robbery going on and another chase happens at the same time it would be nice being able to have one of the scenarios switch radios on the fly instead of needing to pause to either pull the radio out or use the /freq command

**Comment by claymstehling** [comment]
this is a thing with CRTL + (any arrow key)

**Comment by tbone0tbone** [comment]
Wait really? Now I feel dumb
