### ISSUE TITLE
2.5k Lucky Wheel Spin Keybind Change

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2119]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes!

**Summary:**
Write a summary of what your suggestion is about.
Change the keybind from E to G (or whatever you want) for the 2.5k spins on the Lucky Wheel.

**Reason:**
Why would your suggestion be a good change to the framework?
There have been many instances of people accidently spending 2.5k when they mean to use their free spin at the Lucky Wheel. By changing the keybind away from E, it will stop people from accidently spending that money and force them to read and fully commit to what they're doing if that's what they intended to do.

**Comment by claymstehling** [comment]
I agree. I think this would be very useful! :D

**Comment by InZidiuZ** [comment]
'E' is the 'interaction key' in GTA, so I won't just change it to another button as it seems kinda hacky. Instead I can make it a hold-to-use thing which should be even more effective, as what wouldn't stop people from just pressing the other, new button?
