### ISSUE TITLE
Suggestion: Sandy Shores Hospital

### ISSUE THREAD

**Issue by greatwhite18** [InZidiuZ/op-framework-issue-tracker#212]
**Name:**
@iGreatWhite#3018

**Summary**
Possible working hospital in Sandy Shores for check ins.

**Reason:**
This way if people are any where up in Paleto or Sandy Shores there is a closer hospital to work out of than taking someone all the way down to Pillbox Medical

**Comment by InZidiuZ** [comment]
Hey,

Would need to create interiors for a hospital in Sandy Shores, which will not happen at this time, so closing.

**InZidiuZ**
*OP-FW Developer*
