### ISSUE TITLE
Suggestion: Tattoo spot changes

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2121]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

yes

**Summary:**
Write a summary of what your suggestion is about.

When you go to get a tattoo it automatically takes off your tattoo, it should also lock you into the spot like the clothing ones.

**Reason:**
Why would your suggestion be a good change to the framework?

I think this would be great because it would automatically take your clothes off and lock you to the spot like the normal clothing ones do. I think this would allow for a lot less mishaps when purchasing a tattoo.

**Comment by twooot** [comment]
Ok, tattoo spot should now take off your clothing automatically when you go in the menu. Adding the cameras is not something i'll be doing though, since this is an alpha script and it would be easier to completely rewrite it than adding cameras
