### ISSUE TITLE
Aviation Job

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2122]
**Assurance:**
I have read the rules

**Summary:**
Add a job similar to trucking for aviation.

_What is the job?_
Cayo Perico is getting built up, hospitals and other infrastructure incoming, maybe even housing for civilians.
This will require a lot of resources, among one of them wood, mainly in the form of planks and beams.
The best place to get these would be the lumberyard at Paleto Bay, however it would only be transportable efficiently via air.

There's a few places where planes could land around Paleto and the lumberyard, depending on what type of aircraft would be used.

Here are the options:
Seaplane landing spots:
- https://cdn.discordapp.com/attachments/906476986443108383/927168509610442802/20220102112452_1.jpg
- https://cdn.discordapp.com/attachments/906476986443108383/927168509413314581/20220102112315_1.jpg

Landplane landing spots:
- https://cdn.discordapp.com/attachments/906476986443108383/927168508809322556/20220102112618_1.jpg
- https://cdn.discordapp.com/attachments/906476986443108383/927168509165862922/20220102112648_1.jpg

Planes that could be imported and used:
- Seaplane: https://de.gta5-mods.com/vehicles/de-havilland-canada-dhc-6-300-twin-otter-seaplane-add-on-i-liveries
- Landplane: https://de.gta5-mods.com/vehicles/de-havilland-canada-dhc-6-300-twin-otter-add-on-i-liveries

The job would be tied to the heavyweight fixed wing license handed out by the state. Without that license, the job cannot be performed.
Spawning a job plane would work similar to delivery trucks.

_How does a pilot benefit from the job?_
The minimum amount of money a student pilot invests into the two licenses required would add up to 18k dollars. Hence, I would consider the job to be paying around the same amount as the delivery job. Aviation deliveries may be faster, but require more preparation, and it would be a one-way job as there will be no deliveries from Cayo to Paleto.

**Reason:**
- increases purpose and activity within aviation RP aside of "just having a private license"
- increases traffic around Cayo and Paleto
- increases air traffic
- adds a new legal job route for variety
- adds RP behind building up Cayo's infrastructure

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
