### ISSUE TITLE
81 Renault and 88 Peugeot Customization Issues

### ISSUE THREAD

**Issue by AZTricky** [InZidiuZ/op-framework-issue-tracker#2123]
**Assurance:**
Yes

**Player Identification:**
AZTricky

**Summary:**
I'm unsure if this is intentional or a bug or a little of both so I'm submitting as a bug.
Both the 1988 Peugeot 205 GTi Rally and 1981 Renault 5 Turbo Rally have problems in the customization shops. Unable to change wheels, tint does nothing, zero engine upgrades, and most importantly, no armor which deeply hurts either of these cars survivability in the city. Also with the Renault if you swap back and forth between the "Stock" livery and the first custom one you get different liveries at random.

**Steps to Reproduce:**
Bring either car to the custom shop.

**Expected Results:**
Standard upgrade that are available to any other car in the city.

**Actual Results:**
As described in the summary

## Additional Information

**Screenshots:**
Attached

**Game Resolution:**
3440x1400

**Player Data:**
Test Server info.

**Server:**
Same results on Live International Server and on the OP Framework Test Server.

**Notes:**
For anything else noteworthy
![20220105121037_1](https://user-images.githubusercontent.com/39101698/148275083-27706f9f-5584-4c7b-a737-3f8724978b11.jpg)
![20220105115805_1](https://user-images.githubusercontent.com/39101698/148275086-ae27f2b0-7eea-46ec-a9c8-13e73f0cb49a.jpg)
![20220105115814_1](https://user-images.githubusercontent.com/39101698/148275087-8f952dc1-d87b-49b4-bd9d-fc85b8df3d3f.jpg)
![20220105115833_1](https://user-images.githubusercontent.com/39101698/148275088-96e829a4-fcaf-43b2-8d71-fbff99927089.jpg)
![20220105115836_1](https://user-images.githubusercontent.com/39101698/148275090-9c600526-5abb-4918-bd3e-bfb6f2ab0bf7.jpg)
.

**Comment by twooot** [comment]
This would be an asset issue (https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) but has been fixed by the asset dev team.
