### ISSUE TITLE
Midnight club repair shop additions

### ISSUE THREAD

**Issue by Smolnisno** [InZidiuZ/op-framework-issue-tracker#2124]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I would like to suggest an ATM and car wash bay to be added to the Midnight club shop.
1. ATM near the office entrance where it's easily accessible.

2.Car wash bay near the entrance / exit of the door

**Reason:**
Why would your suggestion be a good change to the framework?
These additions would greatly benefit the future owner of the repair shop as customers do not always carry cash on them and would need it to pay the mechanic. If one isn't added it can cause huge issues with people not being able to pay a mechanic for the work.
The car wash bay would be good for customers to get a free complimentary car wash as other repair shops offer it and would be very weird for that shop to be left out.

**Comment by twooot** [comment]
Thats an issue for the asset issue tracker

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
