### ISSUE TITLE
PD /raid Command

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#2125]
**Assurance:**
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes!

**Summary:**
Have a command for officers that is similar to /breach, however a "/raid" command would allow for the officers that do it next to a house/apartment entry point (door) to enter the house just as they would if they were to own the house or have keys to it, being able to search all of the storages inside, move furniture, etc. 

**Reason:**
This would allow for the entire process of Search Warrants and Raids to be a lot smoother and not force officers to get Raid suspects into custody before their raids ever happen. This creates a grey area where they are "technically" detained by police however realistically, SWAT would be able to go up to any door and bust it down, search the property, etc. if there was a signed Search Warrant. This will also allow for the suspects to have a lot better RP compared to sitting locked in a cell while their houses are being raided, as well as it gives them a large chance to possibly intercept a Raid as it happens. It removes the grey area of forcing officers to get raid suspects into their custody, and forcing them to give the officers "keys" to their houses, meaning telling the suspects that they need house access as it is the only way to actually search what is inside.

If this was implemented, it would obviously have to be watched over as if it was implemented as a PD command any officer could technically do it and abuse it, however it would be heavily limited to FIB & SWAT only, which includes a large group of trusted officers that have been involved in multiple raids and Search Warrants. This would allow for better RP on both sides as crims and cops, as it would make it more realistic and more of a RNG factor to what happens during a raid, compared to now where we have to trap the suspects as their houses get taken.

With this, in RP, if the suspects aren't instantly caught, this would allow for a lot more cop vs crim RP as if there was a raid to happen and the person isn't there, it would force officers to get an Arrest Warrant for the suspect that owned the property, giving once again more RP to both the cops and criminals involved as they try to evade getting caught once they realize their property was raided.

With the command possibly being abused, this can also be said for lots of things, an example being a garage being added to Cayo Perico. The argument being said for that to be added is that it would bring more RP, in this case of the /raid command, the same exact argument can be made. I can also tell you as the Head of FIB, an exact way of how the command would be used and not abused. 

(nothing to really attach, this has been an idea for a long time and from someone who has done multiple raids over my 2 years in the server, I believe it will greatly help the RP that goes into a Search Warrant)

**Comment by MetaHatter** [comment]
This could very easily be abused.

**Comment by DCS281** [comment]
this is true however I think it can easily be limited to a select amount of people considering the amount of things it can change. I also know that lots of other stuff that is added everyday can also be abused, and especially it being a PD command, announcements and limitations are made all the time so that officers don't abuse the power that they are given

**Comment by ImArteria** [comment]
Although this would be hard to implement, regardless this would add roleplay all around. A lot of times we are held back from any sort of conflict RP when it comes to raids because we have to raid their entire properties. This would be a very solid command to add, may be hard to implement but would improve overall quality of roleplay and immersion instead of asking the individuals with warrants to give a certain CID the keys to a house.

**Comment by teddythedev** [comment]
A lot of commands can be abused, would just need to be monitored and logged like other commands. Shouldn't not implement something that could help roleplay because of that.

**Comment by DaxterPancake** [comment]
Personally I believe people would much prefer this command with monitoring over the fact they are arrested and have zero chance to fight back or be involved in the RP at all. It's a much better solution to how we have to do it now and I believe this addition would suit both criminals and cops better.

**Comment by DaxterPancake** [comment]
If you don't wish for it to be a command for cops, then you could easily just make it an item that has to be spawned in so that said item can be given ONLY to those who should be using it instead of the whole of the police force.

**Comment by joevapes3** [comment]
This is needed massively for enhancing roleplay and server balance.

**Comment by joevapes3** [comment]
> This could very easily be abused.

Every single command in PD can be abused, that's why pd is a whitelist job and anyone caught abusing this would be terminated from pd immediately. Though I'd like to think the current people we have hired and the people we choose to hire, I wouldn't have to worry about in that capacity.

**Comment by MetaHatter** [comment]
Do not misunderstand where I was coming from.  I was not stating that a better way to handle raids was not necessary. I was stating that specifically having a command used by police that would allow full access to houses and the ability to move furniture is significantly more powerful than anything non-staff have currently and needs to be handled with extreme care.  

If not thought out completely, it could potentially be used wipe out a significant amount of any player's progress with no easy way to revert it.  Terminating an officer won't bring their stuff back.

I agree there should be a better way.  Daxter's idea of an item, possibly issued by staff, to enable the raid is intriguing.

**Comment by twooot** [comment]
So I'm thinking of a battering ram. It'd be an item in the PD store and then every subdivision is able to limit its usage by themselves however they feel needed.

**Comment by DCS281** [comment]
I think that would be a great idea

**Comment by Boutton** [comment]
Would it be possible to make it a breaching charge have it be a little explosion. Think that would be very cool. Shoutout to Ready or not for the suggestion.

**Comment by twooot** [comment]
This has been done
