### ISSUE TITLE
Vehicle make and model for PD

### ISSUE THREAD

**Issue by TheJayNation** [InZidiuZ/op-framework-issue-tracker#2126]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Vehicle make and model on screen for PD when we are behind a vehicle.

**Reason:**
Make it easier for callouts, not everyone knows all makes and models of vehicles, especially PDM cars.

**Comment by panpawn** [comment]
I don't really see how this would make sense - either you know a car or you don't. Why would PD have a way to tell what a car in front of them is during a chase at all times but civilians wouldn't?

Maybe the alternative here would be that the model could come up when you run the plate?

**Comment by InZidiuZ** [comment]
The radar is an [external script](https://github.com/WolfKnight98/wk_wars2x) so if you want that feature, I would suggest making a suggestion there. I won't adjust the script to have that added as it's a pretty complex UI. We can alternatively, as @panpawn said, make it show up with the `/checkplate` command.

**Comment by InZidiuZ** [comment]
>  We can alternatively, as @panpawn said, make it show up with the `/checkplate` command if it is voted for.

I'll be implementing this.

**Comment by TECHSAVYDUDE** [comment]
Is it possible for the make/model to be original to the car it was registered with; in that if it’s a fake plate it wouldn’t necessarily match the car it’s attached to?

**Comment by InZidiuZ** [comment]
> Is it possible for the make/model to be original to the car it was registered with; in that if it’s a fake plate it wouldn’t necessarily match the car it’s attached to?

I've had this one the backlog forever & finally got to it. This should now be the case. If you chop a bison & get a fake plate from it, and attach that to another vehicle, 'bison' will be returned in '/checkplate'.
