### ISSUE TITLE
Suggestion: Add local car part upgrade items to chop shop drops

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2127]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
Right now, almost everyone uses a personal vehicle in crimes like robberies. If there were items added to chop shop that fully upgraded 1 part of a local car only, this could incentivize people to use/experiment with local cars more. 

How it'd work is, people would do chop shop, and have a decent chance of finding an item like "Local Engine Upgrade". This would be a 1-time use-able item only in a local car and would fully upgrade its engine. There would be one of these for all of the performance upgrades.

**Reason:**
_Why would your suggestion be a good change to the framework?_
This would encourage people to not use their own cars in robberies and have more variation for the kinds of cars people use. This would also add more advantage for people to use the chop shop and would create a market for people to sell/buy the parts.

**Comment by claymstehling** [comment]
I like it, but would it bring local cars to the same benefit as personal cars? 

The reason people use their personal cars is they are simply just better.

Though like you said if they are able to upgrade the car at no monetary cost, will have RP costs, I think would be dope and if it brought it up to a personal car's ability even better.

But would they install it? Or would they have to go to a mech shop to get it installed?

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
