### ISSUE TITLE
PD/DOJ Timed Vehicle Impounds

### ISSUE THREAD

**Issue by CreamSlush** [InZidiuZ/op-framework-issue-tracker#2128]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Add a new impound option for either PD or Judges. "/impound [license plate] [time]" Ex.  "/impound 63HKE875 3d" and "/removeimpound [license plate]" Ex."/removeimpound 63HKE875"
This would be a timed impound to impound vehicles for a period of time. Could have the option by also being permanently impounded by just the time being 999d. The remove impound option is there if a mistake was made while impounding, or if there ever is a RP reasoning to possibly pay a fine to remove a vehicle from impound early. Once the impound has completed it's time, it could be retrieved from the impound lot or maybe their garage.
If this was to be added, maybe fake license plates could be looked into more seeing if we can get "/vincheck" to check a vehicles vin number. As of now "/mileage" works as a way to get the license plate, but currently there's no real reason to go through the process if checking the vin.
 
**Reason:**
Cops and Crims currently bump heads a lot with certain vehicles being used for robberies. People are able to throw a fake licenses plate on a vehicle and magickly there's no way for the vehicle to come back to them. The only way I believe is with "/mileage", but regardless there's no charge nor mechanic for us to punish them for this. I think a good median for both sides will be a timed impound on vehicles for High Command PD or Judges to have access to. This puts those vehicles on hold for being used too much if caught and serves as a little punishment for using personal vehicles.  This would depend on how High Command wants to use this command on making a strike system. But say the first time getting caught with their vehicle is a warning. Second time could be a 1 day impound hold. It could keep increasing on each offense and what not, or however they would decide to use the command.

**Comment by twooot** [comment]
PD cars are balanced to keep up with high speed EDM cars. Thats the reason people use their personal cars, since you have a better chance at getting away

**Comment by claymstehling** [comment]
I think this would be great for many reasons, like listed above. I definitely don't think that it should be used that often as it just gets a little powergamey to me. But I think there is a need for this in the city .

It would also give cops a little bit more RP as I think this is how it should have to be. Car gets caught, was used in many robberies before and was caught before --> PD calls tow(won't work without a driver) --> Driver goes and grabs car ---> Brings it to PD garage --> Drops it off and PD can impound in certain area inside PD. 

This would give RP to the PD as well as tow drivers around the city. Also gives the criminal time to fight back for their car if they are quick enough.

**Comment by Vedder742** [comment]
Seems like another good feature to steer the server away from cops v robbers and more towards roleplay. I'm sure we can set up a balanced system for PD to go through the court system to seize vehicles for different amounts of time.

**Comment by MetaHatter** [comment]
There is potential impact to the towing job here. PD calls are the bulk of their income.  I agree that there's some sound reasoning behind limiting the use of the same personal car over and over again, just not sure this is the ideal solution.

**Comment by claymstehling** [comment]
> There is potential impact to the towing job here. PD calls are the bulk of their income. I agree that there's some sound reasoning behind limiting the use of the same personal car over and over again, just not sure this is the ideal solution.

mhm this was my concern that it would take away from the PD calls to the mech line that are a majority of the income. Which is why I think it wouldn't work unless they got it towed to the PD. Would still keep the money there and would provide more RP

**Comment by AverageStatistic** [comment]
> I think this would be great for many reasons, like listed above. I definitely don't think that it should be used that often as it just gets a little powergamey to me. But I think there is a need for this in the city .
> 
> It would also give cops a little bit more RP as I think this is how it should have to be. Car gets caught, was used in many robberies before and was caught before --> PD calls tow(won't work without a driver) --> Driver goes and grabs car ---> Brings it to PD garage --> Drops it off and PD can impound in certain area inside PD.
> 
> This would give RP to the PD as well as tow drivers around the city. Also gives the criminal time to fight back for their car if they are quick enough.

Very much agree with this

**Comment by CreamSlush** [comment]
> There is potential impact to the towing job here. PD calls are the bulk of their income. I agree that there's some sound reasoning behind limiting the use of the same personal car over and over again, just not sure this is the ideal solution.

Not sure how this would effect it. The feature would enhance tow calls... They would need to be called to tow the vehicle to MRPD.

**Comment by CreamSlush** [comment]
Also to add this, if the VIN feature was to be added, it would probably need to work from standing next to the vehicle. Kinda like "/impound". The issue could arise that you won't be able to get the VIN if people start blowing up their vehicles.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
