### ISSUE TITLE
Suggestion - Green Worderland Addition

### ISSUE THREAD

**Issue by Enryy** [InZidiuZ/op-framework-issue-tracker#2129]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
could you add exclusive items for the company, like mariujana biscuits, bongs, Maybe purple haze? A type that is exclusive to green worderland and has different effects than the usual marijuana.

and all this can be purchased via a blip 

**Reason:**
At the moment there is only 1 mariujana and you can find it everywhere... I mean, if you can find it everywhere the greenworderland what's the point?

**Comment by claymstehling** [comment]
I would love this for green wonderland I think this would allow them a lot more to offer in the city and enhance their RP quite a lot

**Comment by Enryy** [comment]
Speriamo che venga preso in considerazione

**Comment by claymstehling** [comment]
My thoughts are 

Weed brownies : Fills hunger up, takes a bit to kick in, does get stronger over time. Would release stress but would take time. Would give small amount of armor. The more you eat the stronger it gets, but it comes with a /e passout4 risk. We all know if you eat to many too quickly you get hit HARD

Bongs : Would be a one time use, makes you thirsty, but if hit for long enough it would relief all stress and would fill your armor up significantly

Gummies: Gives a bit of hunger, gives a small amount of armor, relieves stress like joints but less.

**Comment by MetaHatter** [comment]
Can always start small with the creation of "Doobie Snacks" brownies. 

Regular weed could be changed to add hunger (munchies) and the brownie could simply add armor with no debuff?

**Comment by Enryy** [comment]
Yes, this would also be a great place to start... an item bong would have been epic.

**Comment by Enryy** [comment]
As far as the bong is concerned, you could also insert a sound that everyone can hear once you use it: 

for example, this one: 

https://www.youtube.com/watch?v=kceJXOKu_3g

**Comment by RetroCharles** [comment]
Yes! more strains and more consumables for happy lettuce

**Comment by tftwsaaron** [comment]
These would be great additions to Green Wonderland

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
