### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by skyy-reginald** [InZidiuZ/op-framework-issue-tracker#213]
**Reporter:**
Skyy#1536

**Summary**
Livery will not stay on the car after it being bought. 

**Steps to Reproduce:**
Buy the vapid desert raid. Buy the $1500 livery, fuck the car up, repair the body and boom the livery is gone. Or buy the livery, store the car, pull the car back out, and boom the livery is gone. 

**Expected Results:**
For the livery to stay on the car no matter what I do unless I return the car to stock. 

**Actual Results:**
Livery is only temporary. 

## Additional Information

**Screenshots:**
https://plays.tv/video/5d2a9f0044545f4178/is-second-time-paid-for-wrap-lost-3k-

**Game Resolution**
1920x1080

**Player Data**
Not in game atm

**Notes:**
Thad is a nerd :)

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved, and the fix for it will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
