### ISSUE TITLE
Ridiculously low download speeds for downloading content manifest and assets

### ISSUE THREAD

**Issue by richuvc** [InZidiuZ/op-framework-issue-tracker#2130]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/richu_v/

**Summary:**
Download speeds for downloading content manifest and other assets right before the server starts loading is capped at 0.1mbps speed. I have checked my internet speed and i consistently get above 100mbps for both download and upload. Ive also tried other servers and they run fine too. The issue is only with the legacy server.
Additionally others are also experiencing the same issue. The few that ive talked to are also from the region as me (South India). I dont know if this is just coincidence or if it one of the reasons.
Ive also faced this issue a few months ago and i wasnt able to log in for weeks on end then and had to wait for a new update to come out. The issue also happened immediately after an update (since wednesday i believe)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I dont know how others can reproduce this issue. But every time i log in it happens. I can even show it on stream if needed.

**Expected Results:**
What are the expected results?
I download the content manifest and assets in under a minute and game starts loading

**Actual Results:**
What are the actual results?
Takes forever to download the content manifests and assets. The few who managed to do it after 5 hours got hit with connection failed after that

## Additional Information

**Server:**
What server/community did this issue occur in?
Legacy Roleplay - main server

**Notes:**
Ive got a godlike ticket just getting wasted without me logging in :*(

**Comment by InZidiuZ** [comment]
This is not related to the framework's development. This is a problem with hosting.
