### ISSUE TITLE
Blinkers not working properly Bug report

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2132]
**Assurance:**
Si Senor

**Player Identification:**

**Summary:**
Blinkers no longer working properly, left blinker works, but when you attempt to use the right independently, or as a hazard indicator, it does not work at all.

**Steps to Reproduce:**
Try to use the right blinker and it wont work, but the left one will (with arrow keys)

**Expected Results:**
Left blinker will work, hazards will work if both arrow keys are pressed, right can work independently as well.

**Actual Results:**
Left blinker works, hazards dont, right doesn't.

## Additional Information

**Screenshots:**
Pretty self explanatory 

**Game Resolution:**
1920x1080 16:9

**Player Data:**
https://i.imgur.com/G7G1xUR.png

**Server:**
EU/NA

**Notes:**
None papi

**Comment by InZidiuZ** [comment]
This issue has now been fixed.
