### ISSUE TITLE
Basic Food Store in Paleto 

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2133]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a convenience store to the convenience store in Paleto 
https://cdn.discordapp.com/attachments/630409333636595732/931691107362963476/20220114172727_1.jpg
**Reason:**
Why would your suggestion be a good change to the framework?
I think this would be great because adding the ability to buy food up here just makes sense. It should have a shop where people can buy food like every other convenience store

**Comment by DaxterPancake** [comment]
Interior ideas (that would be an asset suggestion): 
https://www.gta5-mods.com/maps/paleto-247-store-mlo-sp-fivem
https://www.gta5-mods.com/maps/paleto-liquor-mlo-sp-fivem

**Comment by claymstehling** [comment]
> Interior ideas (that would be an asset suggestion): https://www.gta5-mods.com/maps/paleto-247-store-mlo-sp-fivem https://www.gta5-mods.com/maps/paleto-liquor-mlo-sp-fivem

oh yes this would be amazing

**Comment by twooot** [comment]
The interior would be something to suggest on the asset issue tracker. Once that's done, adding the store itself it would be very easy. https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by claymstehling** [comment]
mhm my thought with it now is that it would be like the Second gear store. Outside until it's done, then moved inside the MLO

**Comment by RetroCharles** [comment]
Omg yess!! Paleto people be starving out there!!

**Comment by InZidiuZ** [comment]
Will close this. Once (or if) an add-on interior is added, a store will be created alongside with it.
