### ISSUE TITLE
Small improvements to aviation

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2135]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- yes

**Summary:**
Write a summary of what your suggestion is about.
- disable aircraft to automatically start up when getting in the first time. instead have them start up by using /engine
- airport staff often parks airport vehicles in the Devon Weston Hangar for no reason. These vehicles get in the way all the time to pull out / taxi aircraft. remove the NPC paths into the hangar if possible.

**Reason:**
Why would your suggestion be a good change to the framework?
- automatic start up is an annoying mechanic and it improves aviation RP with callouts especially with student pilots if it were disabled.
- as said before, these vehicles get in the way all the time. Remove these paths, and pilots don't have to rely on /impound commands that are restricted to certain jobs.

**Comment by twooot** [comment]
Aircrafts will now no longer startup their engine automatically. The removal of NPC paths into the hangar is not really doable nicely
