### ISSUE TITLE
Trash Picking and Recycling

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2136]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
This suggestion includes a multitude of new jobs/reworks that would encourage more roleplay to happen overall while giving criminals more activities to do. Below is a list of a few things I've gathered that would improve the criminal roleplay, giving them something else to do and possibly setting up some new features down the road.

**Trash Picking**
- Every Dumpster now contains a small inventory (Which I believe they already do) which randomized items inside which overall can be used for a multitude of roleplay purposes. The mechanic of it would be pretty simple, walk up to a dumpster, go into the inventory and drag and drop what it would be. The loot pool would look something similar to this.
Dumpsters contain a random pool of the following items:
Rubber (Low Chance)
Glass (Low Chance)
Scrap (Low Chance)
Weed Seeds
Food Items 
Low Tier Weapons (Micro Uzi, Marksman Pistol, etc) (Really Low Chance)
Lockpicks
Random small furniture, chair, umbrella, etc
Phone/Radio
Soda Cans/Rubber Boots/Glass Bottles (See Recycling)

The dumpsters on these trash cans would also refresh every 2-3 hours, restocking loot in all dumpsters making it so people who are awake early don't have the advantage at taking all the good loot.

Above would be an example loot pool from trash picking, which is mainly consisted of items you would see be thrown away (depending on the low tier weapons, which could always be changed) and would add roleplay ways to get some other items like phones, mechanical parts, weed seeds. That being said, instead of a new roleplayer coming into the server and having to go to a store to buy a phone, they could possibly find a trash phone! Overall would increase roleplay all around, especially for items like soda cans, rubber boots, and glass bottles (which ties into the next suggestion)

**Recycling**
Recycling would take place at the scrap yard in Sandy Shores. It used to be the old chop shop, and now is only used for purchasing the chop radio. In the building at chop shop, is an abandoned warehouse where a ped would be at the desk (https://i.imgur.com/cswbP8D.jpeg) asking what you would like recycled. You would than put your items into an inventory (almost like a glovebox), wait a set amount of time, and your items would turn into parts to use. 
That being said, items from trash picking (Soda Cans, Rubber Boots, Glass Bottles) would be recycled into it's respective mechanical part.

Something else to note, that could be down the line, is you could recycle unwanted pistols/guns which would turn into mechanical parts as well. If something Legacy wanted in the future was gun crafting, this could be a primary way to receive gun parts to craft a weapon. This would open up a possible development path to make guns more universal and new-roleplayer friend if it were to be a feature. As it stands, this adds a new way for mechanics to get more roleplay out of finding new parts, and even finding some new items that typically could only be purchased at certain stores.

**Reason:**
Overall, and I mostly covered this in the above paragraphs, but this would add a new job line for people to create more roleplay out of. Even such, legal people could also participate in this activity by taking only certain things. Overall, I think this idea is something that could bring a lot more roleplay to Legacy scene by adding another way to give mechanics/criminals a way to obtain certain items or make money without it being economy breaking. It's something that takes a good amount of work, but would be rewarded for it.

@Tweet

**Comment by twooot** [comment]
This has been done
