### ISSUE TITLE
Robberies Updates/Changes/Additions

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2137]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Overall, this suggestion is a suggestion which adds/changes the chains of robberies to give criminals something to work for, instead of doing trash/trucking to receive items for high scale robberies and instead builds a better story for criminals to follow in order to work for higher scale robberies. That being said, I want to start off with regular banks.

**Regular Banks**
Bank Robberies still provide the same payout, but have a wider loot pool now. 
- Deposit boxes also have chances to contain necklaces, silver watches, and a gold bar (Not a lot of jewelry, maybe 1-3 pieces). You would also only be able to obtain decryption keys from banks. All jobs, such as Chop Shop, Garbage, etc, no longer drop decryption keys and now can only be obtained from Banks. 
- This being said, roughly the same payout with a chance to get a gold bar which doesn't really change much. At the same time, now that you could only get decryption keys from banks, this would encourage criminals to go through the roleplay of robbing banks first to build up to a jewelry store. This would decrease the amount of Jewelry stores hit in a day, increase the amount of banks, and therefore thin out the economy in a healthy way instead of people robbing a jewelry store everyday from built up stacks of decryption keys. 

**Paleto Bay Bank Robbery**
- This bank would function almost the exact same as your standard regular bank with a few exceptions. Due to this being so far out of the way, the pay would be increased. A regular bank has three deposit boxes, as to where Paleto Bank would have four deposit boxes. 
- To rob this bank, one would use a chip on the main door (https://i.imgur.com/ZADNLpz.png)
- Once you hack into the bank, you would than encounter four deposit boxes that use thermite (https://i.imgur.com/54zRxHH.jpeg). 
- The same drop rates would occur such as keys, gold bars, some jewelry, cash, etc. 
- Police RP would occur and would force criminals to think of a unique getaway plan from Paleto Bay, and would bring more RP to Paleto
- This would require 6 cops on duty (instead of 4 like a regular bank) due to it being a little more high priority

**Jewelry Store Robbery**
- Only one change for Jewelry stores, upon successful hacking of the computer you now have a small chance to receiver a "Laser Cutter" item (which will be used in another robbery). Everything else stays the same, loot pool, process, etc.

**Pacific Standard Bank Robbery**
I know this has personally been a bank a lot of cops and criminals have been requesting for a while. Hence why I'm here with a step-by-step process with pictures on how it would work, and even briefly discussed it with Twoot (@Tweet). 
- A starting note would be that this would be the largest robbery at this moment. This robbery would be the hardest to rob due to cops, but also due to the items required and the amount of time it takes. That being said, let's hop into the process.
- To start the robbery process, the individual would walk to the left of the front door and be encountered with this staircase (https://i.imgur.com/FIEuefg.jpeg)
- When you walk up the stair case and follow the balcony, you find this door locked with an alarm above it. The individual performing the robbery would use an advanced lockpick on the door, sounding the alarm for PD. (https://i.imgur.com/tn66xrt.jpeg)
- At this point, there are two offices which belong to the "CEOs" and have access to the doors. The individual would "use" a raspberry to begin a hacking process (since raspberries are used through /terminal, and don't actually have a "use" feature it would make a perfect fit) and are thrown through a hacking process. (https://i.imgur.com/NpixVif.jpeg)
- Something I want to note, is down the hall from the offices is a door that would need to be permanently locked and not able to be picked with a lockpick (https://i.imgur.com/vweLRtU.png), this would skip a step in the robbery process if left unlocked.
- Once you go back into the lobby, you'll notice that this door next to the tellers area is now unlocked and can be walked through (https://i.imgur.com/PAFhzlx.jpeg)
- You are approached by another door with a keypad, in which you now have to use a chip (not a raspberry) to hack the door open (https://i.imgur.com/ditL2pK.jpeg)
- Once you have completed the hacking process, you are approached by the large vault door (https://i.imgur.com/8WFp55v.jpeg) which you would use a laser cutter (found during a low chance of Jewelry store robberies) to open the large vault door
- The final obstacle would be the last door, simply needing an advanced lockpick to break through (https://i.imgur.com/IhgjqD1.png)
- At this point you are in front of the vault which would contain 7 different robbery spots, each giving a set amount of gold bars (possibly similar to the newer bank truck, not the old one before people comment), (https://i.imgur.com/uI2Aq6Y.jpeg)

This being said, there is a couple things that would need to be kept in mind about this robbery. The PSB is where gold bars are sold, which is fine but the problem would be the ATMs on the inside are accessible and could easily be abused. At this point, whether it's a staff or development thing, this would need to be kept an eye out for and handled accordingly in whichever matter so people aren't selling/depositing all the money into their bank so they can't lose it. 
Perhaps adding a 6 hour cooldown inbetween PSBs to prevent chain robbing (also would probably be less due to not having the desired amount of cops on at all hours)
- This would require 8 cops on duty, being 6 max criminals allowed in the bank so it is kept somewhat fair. Especially with raspberries, criminals could figure out on their own when is the best time to rob the bank.
- This bank would not be something that is robbed everyday due to the low chance of receiving a laser cutter from a Jewelry store.

**Reason:**
As simply put, this would open up a lot of different aspects for criminal RP (which at the same time, improves cop roleplay). For one, these changes (being decryption keys and laser cutter) would force criminals to rob small scale things in order to hit the big jobs. This would prevent this being added, and four PSBs being robbed in a day. Overall, this would give criminals something to look forward to, in order to gain more money on weapons/cars/etc. This would definitely affect the economy if abused, hence why putting appropriate timers would be necessary.
This would improve cop RP as well by giving them something new and unique to respond to, and give them opportunities to create new SOPs on these larger banks and how they should be handled. At the same time, it's something new that people would be excited for and as a whole, I think the community would benefit from!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
