### ISSUE TITLE
Adding an ATM and CarWash station to the Midnight Club

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#2139]
**Assurance:**
Yas queen

**Summary:**
Adding an ATM and CarWash station to the Midnight Club / Tuner Shop (repair shop 9)

ATM (for convince sake)- https://imgur.com/a/ySXaXoD

Adding a carwash station. This is aimed to be more of a "Detailing zone" - The shop is focused more around tuning and the finer RP details, not as much on mechanic ect. So workers will use emotes as such as /e Clean to polish up a vehicle and then finish it off by actually using the cleaning machine to clean the car of visible dirt. 

As this is going to be used as a "zone" to pull up to, I have added an image of where this could be, which would require the car lift shown in this image to be removed, so the machine can be added. -  https://imgur.com/a/k2Oeq4j

**Reason:**
This business is owned in the main server  as of a two days ago and after being open, these are the two main concerns for the business as a whole, just some user friendly additions that could make the shop and RP flow better as a whole :D

**Comment by twooot** [comment]
This would be something for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
