### ISSUE TITLE
Suggestion Extra weapons for PD armory 

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-issue-tracker#214]
**Name:**
Sercan#0001

**Summary:**
Adding shotgun, carbine rifle and special rifle to the armory.

**Reason:**
Let the officer to choose between a shotgun or carbine rifle. Give swat a different weapon to make them different as they are called Special Weapon And Tactics

**Comment by InZidiuZ** [comment]
Hey,

At this time this will not be added.

**InZidiuZ**
*OP-FW Developer*
