### ISSUE TITLE
Add Security or gruppe 6 vehicles 

### ISSUE THREAD

**Issue by JohnBaker456** [InZidiuZ/op-framework-issue-tracker#2140]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Add Gruppe 6 vehicles

**Reason:**
people do security RP in international servers sometimes and in other legacy servers I feel like if those vehicles are added it would improve quality rp and it's needed I do security RP in legacy and I feel like some people need it in international server and other legacy servers

https://forum.cfx.re/t/release-gruppe6-security-cars-addon-pack/52574

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
