### ISSUE TITLE
[tow/impound] EDM/Addon vehicle impounds not paying full amount

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2142]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/CloudTheWolf/ 

**Summary:**
Write a short summary of what you are experiencing.
When impounding some player owned vehicles the mechanic only gets $50 instead of the expected $450, This looks to only be for Addon/EDM Vehicles (Such as the AMG)

**Steps to Reproduce:**
Requires 2 people
* Have a Second Person get an EDM Car.
* Tow the car to an impound 

**Expected Results:**
What are the expected results?
* You should get $450

**Actual Results:**
What are the actual results?
* You will only get $50 but in the towImpounds API Endpoint it shows as a Citizen vehicle 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
N/A

**Game Resolution:**
What is your game's resolution?
N/A

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
c3s1 (International)

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This has been fixed
