### ISSUE TITLE
Wall issue 

### ISSUE THREAD

**Issue by OreoEatingHusky** [InZidiuZ/op-framework-issue-tracker#2143]
![Screenshot 2022-01-19 131330](https://user-images.githubusercontent.com/89625730/150189979-416ea718-a56b-4efb-ad68-acba5d8fea5d.png)
I found a wall at the back of the Sandy Shores hanger that you can just walk/drive through.

**Comment by twooot** [comment]
This would be something for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
