### ISSUE TITLE
Add Mushrooms

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2144]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add mushrooms as a harvestable drug. 

- Spawns should be in a WIDE area, near forest trees and relatively rare
- Consuming them should give 30-90 seconds of Twoot special™ side effects (and reduce stress by a large amount)
- They should not be instanced to allow for interactions
- Maybe make them easier night picking ;)
- Sell point(s) should be added in RP appropriate locations.  Perhaps Paleto area due to the proximity to the nudist camp and/or hippie camp or UFO camp in Sandy.

**Reason:**
Why would your suggestion be a good change to the framework?
Another activity. One that will spread people around the northern parts of the map. Plus new market for cash flow.

**Comment by twooot** [comment]
This was done
