### ISSUE TITLE
Custom tow trucks cannot be used for towing

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2145]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
MetaHatter

**Summary:**
Write a short summary of what you are experiencing.
Using /tow on the "towcustom" Flatbed (and other addon) tow vehicle does not work

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

- Be a mechanic
- Check out custom tow vehicle from impound
- try /tow

**Expected Results:**
What are the expected results?
Vehicle should go up on the bed as it does with the standard flatbed

**Actual Results:**
What are the actual results?
Nothing happens

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?
1440p

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
n/a

**Server:**
What server/community did this issue occur in?
International

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This has been done
