### ISSUE TITLE
Add Props for Drug Handoffs

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2146]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Show a prop in hand when a drug handoff is made.

**Reason:**
Why would your suggestion be a good change to the framework?
PD would actually be able to get photo evidence and be more certain of an actual crime before confronting citizens.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/J7D407IFNQ.png)
