### ISSUE TITLE
Randomize drug sell points

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2148]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Randomize/Shuffle drug sale points every 2-4 weeks. 

**Reason:**
Why would your suggestion be a good change to the framework?
This will force people the seek out new locations on a regular basis and limit camping the same spot ad nauseum.  Pro crims would know the potential hot spots over time and retain their advantage over others.

**Comment by coalaura** [comment]
dont really like the idea to be completely honest
