### ISSUE TITLE
Simplify the taxi meter/job

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2150]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Reduce the complexity of the Taxi job with multiple small tweaks to the meter:
- Have the taxi meter always display for anyone entering a Taxi vehicle
- Set a keybind to toggle the meter running
- Remove the commands to change rates (move to city config option)
- Update the graphic for the taxi meter to inform the driver how to toggle the running of the meter.
- Optionally payment can be calculated and extracted equally from all passengers automatically, with confirmation, in some way.

**Reason:**
Why would your suggestion be a good change to the framework?
Taxi is currently horribly underutilized. I believe this is partially due to the complexity of the job.  As it is a Life Invader job, it is common for newer, less experienced, players to take this job.  The meter is a bit complicated to use even for veteran players.  Simplifying the meter would present significantly less frustration for players. Visibility of the meter to the passengers would be helpful for them as well.

Hypothetically this is largely removing functionality so it "should" be easier than building a new system

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
