### ISSUE TITLE
Add Fatigue Meter

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2151]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a fatigue meter to the player that, when depleted, renders them unconscious for a time unless someone uses /wake to get them up.  Potentially impact vision/driving if extremely fatigued.

The meter would deplete slowly over time, but faster when:
- Slowly over time
- Consuming something - i.e. drugs/drinks that cause drowsiness
- Sprinting (but not a lot because chases are fun)
- Swimming (slowly with scuba gear on, Fast by default)
- Swinging melee weapons (weight based multiplier)
- Getting punched bare-fisted or with the boxing gloves mentioned in #2147  (nerf actual punching damage)
- Being shot by a tranquilizer or "training" gun 😉

The meter would raise when:
- Unconscious. (quickly - awoken automatically when the bar is full)
- Standing still (slowly). Sitting (moderately), Laying down (quickly)
- Drinking coffee, green apples or consuming "other stimulants"
- Checking into a hospital 
- Visiting an apartment 
- Renting a hotel room (creating possible hotel owner job)

**Reason:**
Why would your suggestion be a good change to the framework?

This addition would allow for: 
- Additional consumable variety and demand.  
- Potential job creation.
- Reduction of never-ending "sending it into the water" strats
- Bare fisted and boxing matches to take place with low impact on health and self-revive

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
