### ISSUE TITLE
Streamer Mode Suggestion

### ISSUE THREAD

**Issue by claymstehling** [InZidiuZ/op-framework-issue-tracker#2152]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Add more to the streamer_mode command
**Reason:**
Why would your suggestion be a good change to the framework?
So I think it would be nice if the streamer_mode command automatically toggled the no_copyright command as well as hide you radio station if changing it. The radio change would only hide the pop up in the top right of the screen that says your radio station. I also think that if you have streamer_mode toggled it wouldn't show the freq on your radio if you pulled it up to change, and the command wouldn't be stored in your used previous commands.
[(https://gyazo.com/37f4f1fb7e842b656132bb6bd75029a1)]

I think it would be amazing as it would prevent a lot of meta gaming and would allow for less DMCA issues :D

**Comment by InZidiuZ** [comment]
I like the radio station idea, though I feel like the 'no copyright' thing is a bit excessive as I frequently see streamers using boomboxes when they are able to control the area they're in.

**Comment by twooot** [comment]
How would you set your radio if you cant see the frequency

**Comment by twooot** [comment]
closed cause old
