### ISSUE TITLE
Ability to save callers number in phone

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/op-framework-issue-tracker#2153]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes i did already
**Summary:**
As we are playing in OP_FW for a long time I think most of the people face this. When someone send you text in your phone or give you a call there should be a option of saving the number from there. IRL we can do this and If we get this it will be easier

**Reason:**
It will make the people's life easy. Currently if someone wants to save a number they need to memories then save. If we get an update based on this people will get to use a new way of in-game phone using.Thank you

**Comment by Enryy** [comment]
Let's say that the phone needs to be updated a little bit on everything, there are a lot of missing features very important for us gamers that create quite a frustration like the fact that there is no way to take pictures to send on twitter/private messages, or like the fact that there is no SIM system and you are always forced to keep the phone number you always had without the possibility to change it, there is no way to make group calls or things like that... I think it's time to start working on a new phone with new features

**Comment by Enryy** [comment]
I think putting one like this (temporarily) would be great... it definitely has many more functions than this current phone such as only saving photos in the gallery or that there is a special section for advertising companies.

https://github.com/qbcore-framework/qb-phone

**Comment by Simo9999** [comment]
yes, exactly, in my opinion it would also be perfect to update the bank app, it blocks a little being able to turn money only in cash

**Comment by SeriumTW** [comment]
> Penso che metterne uno come questo (temporaneamente) sarebbe fantastico... ha sicuramente molte più funzioni di questo telefono attuale come il solo salvataggio delle foto nella galleria o che c'è una sezione speciale per le società pubblicitarie.
> 
> https://github.com/qbcore-framework/qb-phone

We need a better temporary phone that would give so much more rp experience to our users. The phone change would make everyone happy and content.

**Comment by Kryte** [comment]
I agree, gamers need a new phone to improve interactions and to make RP easier.
Legacy is a server that has always brought modernity and quality, a new phone would really be ideal to take a further step forward.
