### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/op-framework-issue-tracker#2154]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes i did
**Summary:**
In main server all the hospitals are needed but in our server we have less number of player and because of so many hospital people takes their wounded friend to the hospital by their own. It ruins the Ems prewet tried to stop this by closing the door of the hospital but its not working as we thought. Most of the time we pass our time by doing nothing.it will be best of there is a lock at the main entry door of every hospital. As locks are only visible to the job holder it will be easer if we lock the door and people wont be able to enter the hospital to check in

**Reason:**
1.Helps EMS RP in sub-continent server
2.People wont be able to use the carry bug exploid.

**Comment by twooot** [comment]
This has been done
