### ISSUE TITLE
Cayo Perico Hospital functionalities

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2156]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
Write a summary of what your suggestion is about.
- Cayo Perico hospital should function as the airlift hospital for Cayo Perico.
- The airlift is not as advanced as the Pillbox airlift, as it will only heal your health (maybe only half), but not fix your injuries.

**Reason:**
Why would your suggestion be a good change to the framework?
- Allows for Cayo Perico hospital to have a bigger role in the city. 
- Includes a more realistic approach for airlifts not to be automatically putting you back to the city.
- Allows for advanced roleplay scenarios where peds who want to ICU need to be transferred.
- Increases the importance of Angel One within EMS.
- Won't allow easy fixes to injuries, as the infrastructure and technology on Cayo Perico would be limited to treat these to the fullest.

**Comment by twooot** [comment]
This has been done, it's going to be the same as pillbox doe (fix injuries and revive)
