### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nightfoxlive** [InZidiuZ/op-framework-issue-tracker#2157]
**Assurance:**
yes

**Summary:**
the vw golf mk4 1998 somehow has no access to the trunk even though there is one, thought it was a me problem but has happened a few days in a row now. also has a strange mud affect where the car doesnt get dirty it just changes to a lighter colour

**Reason:**
Just a quality of life change that i think would be better, would like to be able to use the trunk

**Comment by twooot** [comment]
Its going to be fixed with the next update

**Comment by twooot** [comment]
The mud effect you will have to open an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
