### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nightfoxlive** [InZidiuZ/op-framework-issue-tracker#2158]
**Assurance:**
yes

**Summary:**
the Mclaren 765lt similar to the golf, doesnt get dirty it just gradually gets a lighter colour, not sure if this was intentional just means it needs cleaned every 5 minutes if you wanna show what colour it really is. 

**Reason:**
Again just a quality of life change, would make more sense if it started looking dirty rather than just change colour in my opinion. Thanks

**Comment by twooot** [comment]
This is something for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
