### ISSUE TITLE
Add functionality to outside workbench @ 2nd Gear

### ISSUE THREAD

**Issue by Amoxicot** [InZidiuZ/op-framework-issue-tracker#2159]
**Assurance:**
Yes I have read the readme.

**Summary:**
Add the ability to use workbench outside of the shop @ 2nd Gear. The workbench itself was added to the outside bay but the functionality is not there. If that could be added, that would be great!

**Reason:**
With the bench now being outside, doors, windows, and tires can now be crafted outside instead of having to run all around with windows and doors.

**Comment by twooot** [comment]
This has been done
