### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Weedwhack** [InZidiuZ/op-framework-issue-tracker#216]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
WeedWhack#5541
Pleb4Life
**Summary:**
Write a short summary of what you're experiencing.
After getting the PDM role in game I am no loner getting a passive paycheck.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Just be online and not receive paycheck.
**Expected Results:**
What are the expected results?
To get a passive paycheck like all the ither jobs.
**Actual Results:**
What are the actual results?
Not getting a passive paycheck.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
ID:1379 - Job Data: vehicle dealership, premium deluxe motorsport, apprentice.
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This should be resolved after next patch. Ask for another job-set from staff after next update has been released.

**InZidiuZ**
*OP-FW Developer*
