### ISSUE TITLE
Suggestion - Taxi Whitelisting

### ISSUE THREAD

**Issue by RyanShlap** [InZidiuZ/op-framework-issue-tracker#2160]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes!

**Summary:**
Essentially the Downtown Cab Co. Could be a run business by a trusted individual from the staff team or essentially a community member that's dedicated to do the task. I feel whitelisting this job and with a simple Google form application just to get some details from the individual applying and then doing an interview will add a lot to the roleplay before even getting the job. SOPs could be written up as per most employers do these days and have a ranking structure within the job system which a higher rank could potentially let you use your personal vehicle and the taxi meter would be usable in such vehicle based on your job and not the vehicle you drive. I feel if you higher the pay scale and reduce the costs of taxis will show more initiative to get people to sign up. Taxis are essential in this day and age and to stop people standing on the back of tow trucks doing 70mph and a McLaren doing 100mph it will add to the emersion of the server.

**Reason:**
I think my suggestion for would be good for the server to add that extra aspect of life that is lacking within the server in some ways. It will definitely improve roleplay scenarios as you can meet a lot of different people while doing the job and establish contacts for other things outside of the taxi job itself. It will deter people from using tow trucks as a taxi and when someone's vehicle is totalled they could just call a taxi like normal people would. Which will also lower the rate at which people steal vehicles as well.

**Comment by xarxesthegreat** [comment]
This would add so much more roleplay to the server and create a smoother first entrance to the server for new players. I love it!

**Comment by RyanShlap** [comment]
> This would add so much more roleplay to the server and create a smoother first entrance to the server for new players. I love it!

Essentially the airport could be used as a taxi rank for the new entrees as well.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
