### ISSUE TITLE
Helicopter altitude lock

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2161]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Currently pressing "Z" while flying a plane lock its speed and altitude. So I'm suggesting the same for heli, to lock speed and altitude.

**Reason:**
Why would your suggestion be a good change to the framework?
Would make flying heli a lot easier and as Plane already has a feature like this, then why no Helicopters!

**Comment by TheOneLizard** [comment]
I really would never recommend speed locks for planes to begin with. I would also personally not like an altitude lock quite in general. It should be dependent on your own abilites to control the altitude.

Furthermore, on a map that has drastic and fast changes in AGL (while AGL is also sometimes not working and just becomes ASL), I'm not sure how to make that work in a way it's worthwhile.

Again, all personal opinion ofc

**Comment by InZidiuZ** [comment]
I agree with @TheOneLizard here, there shouldn't be a super strict lock like the cruise control on planes and helicopters. The 'cruise control' is already a form of auto-pilot for airplanes and I don't think we'll be expanding this feature any further. Will close this.
