### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2163]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yep.

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/Goooooody/

**Summary:**
Some players department label do not show up on their tracker.

**Steps to Reproduce:**
There aren't any definite steps to reproduce but some users including the one shown in the screenshot have this showing on their derpartmentLabel

**Expected Results:**
To have their rank in EMS displayed

**Actual Results:**
Unknown: departmentLabel appears

## Additional Information

**Screenshots:**
https://imgur.com/Ae1VVtW

**Game Resolution:**
1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://i.imgur.com/5u2i6gA.png

**Server:**
Legacy International; 54.36.229.159:30121

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This has been fixed
