### ISSUE TITLE
[maps/pillbox] Move Doctor Duty Blip

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2164]
**Assurance:**
Yes

**Summary:**
Move the Doctor duty marker in Pillbox to this location to prevent Accidently going on doctor duty.
At other hospitals it's already in a similar location to the ward, but at Pillbox it's in the changing room

**Image of Location**
https://media.discordapp.net/attachments/806541364506394675/937803214428962876/2022-01-31_20_06_40-FiveM_-_Legacy_Roleplay___Custom_Framework___Active_Staff__Development___Join_u.png

**Reason:**
Why would your suggestion be a good change to the framework?

This would prevent accidently going on Doctor duty when changing outfits or accessing lockers

**Comment by TheOneLizard** [comment]
this would be long overdue :D

**Comment by mastersamii** [comment]
To open the door we press "E"
To get on doctor duty we press "E"
To change clothes we press "E"

Almost every time I go in that room and press "E" I end up on dr duty by accident.

Moving this to the ER would make sense and would honestly cause fewer mishaps within the EMS field.

**Comment by superiorchicken007** [comment]
I know this was also made awhile ago in #1704 but would make it easier.

**Comment by twooot** [comment]
Doctor sign in has been moved
