### ISSUE TITLE
Suggestion - Add clothing circles for patient use at hospitals. 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2165]
**Assurance:**
Yes

**Summary:**
To allow more in-depth RP there should be a location for patients to change outfits to things like Patient Gowns, Casts etc.

Locations suggestions:

Pillbox: Ward C Restroom

https://cdn.discordapp.com/attachments/806541364506394675/937803434969686056/2022-01-31_20_08_08-FiveM_-_Legacy_Roleplay___Custom_Framework___Active_Staff__Development___Join_u.png

St F - ICU Ward:

 https://cdn.discordapp.com/attachments/806541364506394675/937803585113174016/2022-01-31_20_08_47-FiveM_-_Legacy_Roleplay___Custom_Framework___Active_Staff__Development___Join_u.png
 
 Sandy Medical - Rest Room (Also change to locked, by default):
 https://cdn.discordapp.com/attachments/806541364506394675/937803682857234482/2022-01-31_20_09_49-FiveM_-_Legacy_Roleplay___Custom_Framework___Active_Staff__Development___Join_u.png

The Bay Medical Centre:
 No Suitable Location Found, but I doubt we would have ICU there anyway. 

**Reason:**
This would allow for more In-Depth RP and allow patients to change without having to go out of the ward to do this.

**Comment by mastersamii** [comment]
Adding clothing spots even if the only one that gets added is the one in ward-C of pillbox will allow patients to get fitted with casts after dr appointments and get into medical gowns for surgeries and icus...

Everything stated above will help EMS as a whole to create more in-depth and enjoyable RP!

I think that this would be absolutely fantastic if it's added!

**Comment by CloudTheWolf** [comment]
Discovered that the suggestion location has an Outfit spot similar to what is at Mechanic Shops, which is EMS Only. (No marker so was not aware, and seems to be pointless since there is a clothing spot in the staff room)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
