### ISSUE TITLE
Treasure Hunting

### ISSUE THREAD

**Issue by PeppermintOW** [InZidiuZ/op-framework-issue-tracker#2166]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

In treasure hunting you would use a device (whether it would be a scanning device or a newly added metal detector) to scan a certain area for goods.

**Reason:**
Why would your suggestion be a good change to the framework?

Everyone loves RNG and lots of options to make money or things to do in the city so I believe treasure hunting would be a good addition to the city for both new and present players. Just has how you would need to purchase a diving tank at the tool store and go diving in a certain area, you should be able to purchase a device scanner or a metal detector (it would be a newly added item) to scan the ground of a specific area for items (like a beach somewhere in Paleto). When you use the device scanner/metal detector, as you're walking around in a scannable area, there would be a circle with a color around the device and beeping sound. 

-Red: It would mean that you're far away from an item and the device would have slow beeping sounds.
-Yellow: It would mean that you are getting closer to an item and the sound of the beeping would start to increase.
-Green: Green would mean that you have found the item and the beeping would be extremely fast.

After it has shown the green circle, your character would stop in animation and let the device search which would take a few seconds.
After searching it would show what item you have found.

You would be able to gain items like:
- Jewelry (rarer than most items)
- Watches and compasses
- A phone
- Materials
- Broken bottles
- Guns (Trash pistol, .50, some of the new pistols, combats which should be rare and other rare guns)
- Food drinks (Beer etc.)
- Other items (maybe weed seeds etc)
- Maybe some new, not so useful items (baseball etc.)
- Or you may get nothing at all.

To balance this, there would be rarity on different items and the device should maybe have durability or a certain numbers of times you can search using that item. So a newly bought metal detector would have a total number of 15-20 searches on it until its no longer usable and you would need to buy a new one (maybe $500).

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
