### ISSUE TITLE
Airlift to Closest Hospital

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2167]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
When you airlift it should drop you at the nearest hospital.

- Y >= 4100 -> Paleto 
- Y = 1500-4099 -> Sandy Hospital
- Y <1500 X >= 700 -> Saint F
- Y <1500 X < 700 -> Pillbox
- Cayo -> Cayo hospital

**Reason:**
Why would your suggestion be a good change to the framework?

- It would reduce congestion and, by extension, headaches around the hospital by distributing the population more evenly.
- It would create more traffic in lesser populated cities/towns.
- It would reduce the time to get to the hospital in the event someone is forced to airlift near you.
- It makes more sense in RP that you would be airlifted to the "nearest" hospital.

**Comment by twooot** [comment]
This has been done
