### ISSUE TITLE
Suggestion: Add breach charges for PD

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2168]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
This item would be usable by PD for doors that are locked. It'd attach to the door and explode, causing the lock to break and the door to open.

**Reason:**
_Why would your suggestion be a good change to the framework?_
With more locked doors becoming a thing, it's possible people might want to lock themselves in a garage/shop. Rightfully so, and it'd make sense if they could if PD had a counter. Obviously this would come with RP guidelines and if abused would mean RP consequences.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
