### ISSUE TITLE
Confiscate items before sending to prison

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2169]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adding a command such as /confiscate <ID> which will confiscate all of someones items. They would then be sent to prison and able to obtain their items back when their time is over and they collect them from a location outside the front of the prison.

**Reason:**
Why would your suggestion be a good change to the framework?
This would allow for a more realistic prison RP & also create a drive for people to interact with eachother or with DoC to be able to survive throughout being in prison.

I believe that an addition like this should only come when/if we have the ability to obtain food and drinks in the yard of the prison or we have a system in place to obtain items while doing prison jobs. Otherwise people would just starve if DoC is not around and the interor of the prison is locked.

This system would also ensure that dirty criminals will be able to obtain all their legal items back without having to come to MRPD and flag down an officer.

**Comment by twooot** [comment]
I feel like its more of PD's or DOC's job to search someone and take their stuff off of them instead of making it a command that just poofs items and you collect em later

**Comment by DaxterPancake** [comment]
> I feel like its more of PD's or DOC's job to search someone and take their stuff off of them instead of making it a command that just poofs items and you collect em later

Sorry, I forgot to mention that PD would be the ones removing their items from them with the command.
The way I imagined it working was as follows:

1. Arrest dirty criminal and take to MRPD
2. Take all ILLEGAL items from them
3. Work out their time and fines
4. Use /confiscate which will remove all their remaining items
5. Send them to prison

It solves multiple problems and issues that we are currently facing without a steady DoC. It would make it so that we don't have to rely on people to have a functioning and non-problematic prison system.

**Comment by lildiavolo** [comment]
It would be very cool of instead of just "soft napping" to get out of jail, you actually had to go through a specified area (that you can only access after your prison time ran out) and there's an office or something there where you would go and collect your belongings. Command would make it easier so the system works all the time, but when DoC are there it will create RP by having them be the ones handing out said confiscated items.
I do think it's an idea that can be looked into and implemented, might just need to be figured out on exactly how it would be.
+1 just cause I think there's some meat to the idea.

**Comment by superiorchicken007** [comment]
> It would be very cool of instead of just "soft napping" to get out of jail, you actually had to go through a specified area (that you can only access after your prison time ran out) and there's an office or something there where you would go and collect your belongings. Command would make it easier so the system works all the time, but when DoC are there it will create RP by having them be the ones handing out said confiscated items. I do think it's an idea that can be looked into and implemented, might just need to be figured out on exactly how it would be. +1 just cause I think there's some meat to the idea.

This would be nice to check out at the front desk, collect your items and then you get teleported to the front gates instead of hard napping.

**Comment by twooot** [comment]
> It would be very cool of instead of just "soft napping" to get out of jail, you actually had to go through a specified area (that you can only access after your prison time ran out) and there's an office or something there where you would go and collect your belongings. Command would make it easier so the system works all the time, but when DoC are there it will create RP by having them be the ones handing out said confiscated items. I do think it's an idea that can be looked into and implemented, might just need to be figured out on exactly how it would be. +1 just cause I think there's some meat to the idea.

This has been done now :)))

**Comment by twooot** [comment]
I've been thinking about it and i like the fact that PD has to make sure they take all the illegals more than having it all be done with one command. Allows in general for more RP opportunities since officers can forget to take items n stuff and theoretically if you had a functioning DOC you could even have them do it.
