### ISSUE TITLE
hospital door's going to bed lock and unlocked

### ISSUE THREAD

**Issue by Sinwolfie** [InZidiuZ/op-framework-issue-tracker#217]
**Name:**
Ems Jayson Sinwolfie, sinisterwolfie#4508

**Summary:**
have the doors going to the beds lock and unlock for ems. having the hospital a green zone too

**Reason:**
I'm having to fear for my life at the hospital scared and its happening more and more the past week where people are pulling weapons guns bats machete's in the room with the beds and im really get sick and tired of not feeling safe in the hospital and with the door locking and unlocking for ems would help out cause it will cut down on the people just coming in and starting fight with the patients and when telling them to wait in the waiting room and not listening to me. also will cut down on trying to talk to the patients when people are over talking me and the patients that are there to get treated. something really needs to be done cause i am at my wit's end cause everyday im fearing for my life in a hospital that should be safe and its not

**Comment by Ninjapex** [comment]
+1 I also think that once EMS are on duty, they should have the option to lock/unlock the doors in the operating room. There's no reason they should be there, if a doctor is on duty. They can open the door for them. It ensures quality roleplay from EMS to patients rather than getting threaten by other people while they are trying to work.

**Comment by greatwhite18** [comment]
I believe this is already in the works for being tested and put towards the live servers. However, the owner can tell you that for sure or not if that is the case.

**Comment by InZidiuZ** [comment]
Hey,

This has already been done, and will be live with next patch.

**InZidiuZ**
*OP-FW Developer*
