### ISSUE TITLE
Item drops when doing prison jobs

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2170]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add various new items that drop while doing prison jobs.

**Reason:**
Why would your suggestion be a good change to the framework?
As it stands, prison RP is exremely stale. It's boring. DoC is barely there and criminals want to get out as fast as they can. This can create hostile environments when people are HUT or sent into prison for a long time.

My suggestion is to add varing item drops when people complete a prison job. This would mean multiple new items would need to be created in order for it to make sense in a prison environment.

My ideas are as follows:
Cigarettes - That's a given, decently common drop chance.
Crack - A drug that only drops from the prison jobs and cannot be sold to peds in the city. Instead, its usage is much like cocaine but without losing health when you take it. Instead this drug would heavily blur your vision but allow you to run really fast.
Pruno ([Prison Wine](https://dudefoods.com/wp-content/uploads/2011/05/PrisonWine7.jpg)) - An alcoholic drink that can only be obtained from the prison. Gets you fucked up.
Shank - A variation of a melee weapon only obtainable in prison. A toothbrush that has been sharpened or we could go for [this](https://www.gta5-mods.com/weapons/screwdriver) or [this](https://www.gta5-mods.com/weapons/prison-knife-stabber).
Advil - A stress reliever only obtained in the prison. Works like Tic Tacs except in a cute [little box of painkillers](https://static.chemistwarehouse.com.au/ams/media/pi/47743/3DF_800.jpg) commonly obtained in prison.
Plastic Fork, Spoon or Knife - My idea with this one is to allow certain doors inside of the prison to be lockpicked with these utensils. I would limit it to only some of the interor doors inside of the prison MLO to allow prisoners to utilize some of the lesser known rooms for their RP.
Prison Phone - Much like a [nokia brick phone](https://upload.wikimedia.org/wikipedia/commons/7/78/Nokia_3310_Blue_R7309170_%28retouch%29.png). This phone would be an extremely rare drop. My aim with this one is to have an avenue for prisoners to find and utilize a phone to contact the outside world. As it stands currently police do not take phone and radios when sending people to prison but if we were to impliment this system found [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2169) then this would be a fair way for both normal criminals and HUT prisoners to obtain a phone. I would limit this phone to only phone calls.
Bandaids (First Aid Kits) - A box of bandaids that do the exact same thing as a first aid kit. Just thought a little box of bandaids would be cute.
Food - Any varying foods, could utilize what we already have or drop food trays or whatever you think is cool.
Water - Water or Coke to quench thirst.

With the above items (or more if you are feeling creative) I feel that prison RP would florish again. It would give people something to do inside of the prison and allow people to roleplay with eachother in order to collect items or trade, etc.

**Comment by ImArteria** [comment]
This is definitely a Zerochamp idea

**Comment by lildiavolo** [comment]
+1, Make prison more interesting. It should be part of the RP experience, not a soft ban.

**Comment by coalaura** [comment]
not exactly those items but there are item drops now
