### ISSUE TITLE
Harley Davidson Streetglide (both versions) Handling

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#2171]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

This is being posted to let the developers know that the Harley Davidson Streetglide still has exceedingly poor handling and other issues. The steering on the bike is very poor, its difficult to make a 90 degree turn even at 20-30 mph. The speed is very lack luster compared to the rest of the bikes. The bike should handle "heavier" than slimmer bikes, but this is far too much. It's not viable as a bike to ride in any capacity with the current handling settings. Furthermore, like all EDM bikes (or a lot of them), it bounces off the ground while riding and staying still, however I've found that it's bad enough with the Streetglide that it causes it enough damage to get a fuel leak.

**Reason:**
Why would your suggestion be a good change to the framework?

The bike is owned by many roleplayers including those who play as bikers within the server. This bike did handle well in the past but now the handling is so poor that it's not worth purchasing. Both the new and old version of the Streetglide handle this way which has resulted in people who had the old version to not ride it anymore.

**Comment by twooot** [comment]
This would be an issue for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
