### ISSUE TITLE
PDM Logo in Decals

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2173]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add PDM Logo in Decals.

**Reason:**
Why would your suggestion be a good change to the framework?

As a PDM employee we often wear suit at workplace. If we had a decals with PDM logo we could use it with our suit. With the help of that it will be easier to recognize a PDM employee.

**Comment by MrFraud** [comment]
Appreciate with him.

**Comment by mdmostofa87** [comment]
this would be great

**Comment by MetaHatter** [comment]
This is in the wrong place, it should be in the asset tracker

**Comment by rakibulhasan456** [comment]
> This is in the wrong place, it should be in the asset tracker

Thanks! I have posted this in the Asset Tracker..

**Comment by twooot** [comment]
closing as its in the asset tracker now
