### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2174]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
[What is your steam profile?](https://steamcommunity.com/id/Goooooody/)

**Summary:**
I'm not sure if this is intentional but when the dab defaults back to no emote, or you try to walk from it, your character goes into the t-pose for a moment.

**Steps to Reproduce:**
Do /e dab

**Expected Results:**
To just resort back to your normal character walk/stance

**Actual Results:**
You T-Pose for a little bit.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://youtu.be/jRF89CjqRCg

**Game Resolution:**
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://i.imgur.com/JcQkTwM.png

**Server:**
What server/community did this issue occur in?
Legacy International: 54.36.229.159:30121

**Notes:**
Just want to know if this is intentional, you will see what is meant from the video

**Comment by twooot** [comment]
This has been fixed
