### ISSUE TITLE
Lock all local driven cars

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2176]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
- Make all local driven vehicles locked by default when occupied. 
- Require a lockpick on the door to open prior to taking keys.
- Fix "taking keys" process so that the car cannot be started/driven until after the meter is full. (there is currently a bug where you can drive away instantly)

**Reason:**
Why would your suggestion be a good change to the framework?
Currently the "ideal' method for acquiring transportation is by shooting a local in the head and driving off almost instantly in their car.  This is a super violent way just to get to the local store for milk.  

- It is more accurate from an RP perspective.  Murder for a vehicle should be rare.
- People will likely choose the easier path of picking a parked car or calling a cab/friend.
- This slower overall process will also increase the opportunity for the police to catch the crime in progress.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
