### ISSUE TITLE
Changes in /saveoutfit command

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2177]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
The current "/saveoutfit" system saves clothes and hairs/beards and all kinds of barbershop customizations. So I'm suggesting making "/saveoutfit" only save customizations made from clothing stores, not barber shops, meaning hair/beards will not be saved with "/saveoutfit".

**Reason:**
Why would your suggestion be a good change to the framework?
This looks kinda weird that changing outfit actually changes your hairstyle. Also if you want to update your hair, you have to wear it every time and change it again and again. So making this change would make it a lot easier.

**Comment by twooot** [comment]
I put it up to a vote and the majority was against implementing this
