### ISSUE TITLE
Changes in /outfit

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2178]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
If you save an outfit for Ex. 1, with glasses, hats, or anything from the accessories section and then save another for Ex,2 without anything from accessories, and apply the /outfit 2 over the outfit with accessories, the accessories items still remain. So the suggestion will be if you save an outfit without accessories but you're already wearing an accessories item, applying that no accessories outfit will remove that currently wearing accessories. Like normal clothes, if you save an outfit without a shirt, you're wearing a shirt and apply the no shirt saved outfit, it removes the shirt you're currently wearing.

**Reason:**
Why would your suggestion be a good change to the framework?
It would avoid conflicts

**Comment by twooot** [comment]
This has been fixed
