### ISSUE TITLE
Door lock changes

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2179]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
If you press E to lock a door and while it's showing Locking and it takes too much time, locking fails and asks you to press E again to lock it. So when you press E, it should be closed no matter how much time it takes. Also when the door says Locking, you can't lock/unlock any other doors.

**Reason:**
Why would your suggestion be a good change to the framework?
When you're in a hurry and press E to lock the door, but someone is blocking the door or it's taking time, the door actually doesn't lock, and when you're locking another door, you can't unlock/lock any other doors which kinda takes some time to wait for the other door to close, kinda weird. So adding these features would be much easier to lock/unlock doors.

**Comment by T4NZ1M** [comment]
Slow locking is not what I meant, I'm saying if it does take time to lock, and a specific time passes and is still not closed yet, then it doesn't lock. Also if one door is saying "Locking", you can't interact with other doors.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
