### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TheDeign** [InZidiuZ/op-framework-issue-tracker#218]
**Reporter:**
Bailey (Deign)
#1537
Steam: IamDehydrated

**Summary:**
Vehicle in garage keeps exploding when taking it out of garage

**Steps to Reproduce:**
Blow up vehicle, go to garage, get vehicle from impound and remove it from garage.

**Expected Results:**
Vehicle not be blown up and able to be towed or fixed with repair kit.

**Actual Results:**
Vehicle blows up

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Closing due to a lack of information, please create another report *or* edit this one and comment on it.

**InZidiuZ**
*OP-FW Developer*
