### ISSUE TITLE
Base Item Degradation Rate on Storage Location(s)

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2180]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
_**ONE**_ of these two (or perhaps split the difference)
- Degrade items half as fast when stored in a house
- Degrade items twice as fast when stored in a car or a business locker

Keep the rate of degradation in inventory the same.

**Reason:**
Why would your suggestion be a good change to the framework?
I see this has having several positive benefits.
- From an RP perspective, it's more logical that things would last longer in a climate-controlled environment
- Resellers of items would need storehouses to maintain product value
- Incentivize house purchasing to offset the reduced demand caused by implementing degradation
- Disincentivize the very strange practice of buying 20 vans to use as primary storage.
- Increase risk (It's currently too easy to just scatter cars everywhere to mitigate risk)

**Comment by nmunson86** [comment]
i would actually like this almost more than the gun cleaning kit.

**Comment by twooot** [comment]
this was done (something like this)
