### ISSUE TITLE
Bike Riding Styles

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#2183]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

I would love to see an addition for bikers within the city by adding riding styles. I am aware that in the MC update for GTA Online there is a way to change your riding style. It could be added to the F3 menu where the walking styles and emotes reside.

**Reason:**
Why would your suggestion be a good change to the framework?

It would add variation and a slight aesthetic personality touch to bikers in the city. It is another customization option for their character. I know that this is something that has been requested by people who ride bikes within the city however I believe a Git suggestion hasn't been made for it.

**Comment by RetroCharles** [comment]
I've noticed new emotes as well with driving where characters can lean their arms out the windows while steering with 1 hand. I believe adding some riding styles would be great as well and give more appreciation to characters who love and enjoy their motorcycles.

**Comment by PoshoGH** [comment]
Bikers make up a big amount of the player base whether it be MCs or just players riding any bike as their go-to. Riding styles will definitely improve their RP significantly
