### ISSUE TITLE
Facial changes during character creation.

### ISSUE THREAD

**Issue by Damiansssz** [InZidiuZ/op-framework-issue-tracker#2184]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes, I did it.

**Summary:**
Good evening, we have received proposals from various players, such as:
Add the ability to change facial features, while creating the character.
Personally, being able to change the nose, chin, cheekbone height and facial features in general is very important, above all, because it is what characterizes and diversifies one character from another.
Being forced to simply choose the face to put on creates a problem of equality of the various characters, which takes away the freedom of imagination and immersion of the role-playing game and, in fact, the uniqueness of each character.
The proposal was appreciated by many players and staffers, precisely because it is a great strength of the role-playing game, that of being able to be free, to customize your character, to your liking.

**Reason:**
This change would be very convenient and useful, as it would create uniqueness between the various characters and because, whoever comes to fivem, wants to try something different, from the usual gta characters, he wants to create something of his own and that differentiates him from another person.

**Comment by InZidiuZ** [comment]
This has already been implemented to some extent and is planned to be implemented even further soon alongside #2393.
