### ISSUE TITLE
Suggestion: Add inventory items for hat/glasses/mask

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2185]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

Yes
**Summary:**
_Write a summary of what your suggestion is about._
Create inventory items for hats/masks/glasses that are taken off so that someone can give someone else their hat/glasses/mask. Also, if someone gets punched where their hat/glasses are knocked off, put them as items dropped on the ground that people can actually pick back up to put back on. If someone wasn't wearing a hat or glasses when they get punched, then those respective items would not drop when punched.

**Reason:**
_Why would your suggestion be a good change to the framework?_
It'd let people exchange hats/glasses/masks which they would otherwise be able to do which would add to RP. It'd also let people actually be able to pickup their glasses/hat that got knocked off. In addition, if someone wanted to carry multiple hats with them, such as a baseball cap and motorcycle helmet this would also allow for it.

**Comment by twooot** [comment]
This wouldn't work with clothing updates really since they would kinda shuffle the items too

**Comment by panpawn** [comment]
>This wouldn't work with clothing updates really since they would kinda shuffle the items too
When this happens, people would just have to get new ones as they remake their outfits. This doesn't happen *that* often that I think it'd be worth this not happening because of it.
