### ISSUE TITLE
Suggestion: Burger Shot Changes / Improvements 

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2186]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Hello I am the owner of Burger Shot and I would like to suggest some changes + importing new things! Here is my list below:
1. New Interior --> https://www.youtube.com/watch?v=h47N3ES_4tA
2. I would love to add some new food with some effects such as: Ice cream / Milkshakes. Both giving a "sugar high", and if you consume too much, too quick you get a head injury [symbolizes a brain freeze]. I would love to also start selling chicken sandwiches + chicken tenders [the new interior promotes these items].
3. I would love to have something implemented where the employees have to utilize the kitchen to make the food that is ordered. [Details in the reasons section]
4. More of a "issue", but ever since the store was moved behind the counter at BS, the food does not stack and we are unable to purchase in quantities. This makes it hard / time consuming for when we have citizen deliveries.
5. I would love personal lockers added into the establishment. 

**Reason:**
Why would your suggestion be a good change to the framework?

My suggestions would be a great thing for better RP.  The new interior would give the establishment more areas for not only the customers, but employees to actually enjoy. Open bathrooms, an office space, an improved kitchen, and more space to be able to actually sit in booths / tables to RP dine in style. 
With adding new foods such as Ice cream, milkshakes, chicken sandwiches, tenders, would make RP more realistic. Fast food places have these items and yes, burger shot is a "burger place" but normally burger places do have milkshakes and ice cream. I also think it would be a great thing to have for those who want to RP as not eating red meat. 

Implementing a system in the kitchen were employees have to craft a "meal" or "burger" would greatly improve RP. As great as it is to have a store for quick purchase, in reality when you go to a restaurant or even a fast food place, there are people working in the kitchen making food. This system should have options: Fries, Cheese burger, burger, Meal. That way no matter what someone orders, an employee is able to make it in the kitchen fresh to sell in the front or bring to their delivery. Of course, I do think that we should keep the store that we have just incase we do get a larger order that might take too long for people who place it via the app. 
As for things to make the food with, I think that the employee should be able to pull out the necessary amounts of patties and vegetables from the fridge, to start making the food. I would like the preparation area utilized by having to chop / cut the vegetables: fresh potatoes for fries, lettuce, tomato for the sandwiches. 

I also would love it if something could be implemented that caters to dine-in serving. Such as "carrying" the food to tables for the customers seated and waiting, and it be in an employees hands similar to how the new teddy bear and rose are, and you hand it off by giving it to the customer. 
 

I understand that this is a lot, but I appreciate anything being done, thank you!

**Comment by RetroCharles** [comment]
This suggestion seems to be very fun and interactive for both the customers and employees. Especially the crafting of meals, as BS has an amazing aesthetic kitchen, it be great to add some functionality to it. 

The New interior linked by OP gives BS a much more presentable, fun and cleaner look overall. and adding the "carrying" of food to tables can also enhance the dine-in experience along with the new interior as the tables that are currently in BS have leftover food and gives majority of the tables an unpleasant look for customers to dine-in. 

In-city currently BS has been a very popular spot for people to hangout and mingle, giving BS a little more love can be greatly appreciated by the entire city community and not just Burger shot employees alone. 

I hope to see this suggestion implemented soon! Can't wait to see the outcome.

**Comment by twooot** [comment]
So for now i implemented crafting into burgershot. You'll have to buy things like potatos, lettuce, buns, patties, etc. and then cut/fry/cook/etc. them

**Comment by kaycorriher** [comment]
Would love to see more RP coming out of Burger Shot. I go in there and sit down to have a meal and just see people run in and out instead of staying at the restaurant to enjoy the food and conversations with the people.

**Comment by InZidiuZ** [comment]
Closing in favor of #2369.
