### ISSUE TITLE
Suggestion - Air Freshener Item

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/op-framework-issue-tracker#2187]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Create an air freshener item that works similar to the tictacs that were recently brought in. 
On use: Lower a very small amount of stress and execute the /e sniff animation
Can be sold at convenience stores

**Reason:**
Why would your suggestion be a good change to the framework?

Ever since 2nd Gear was founded we've always pushed the finest smelling air fresheners on our customers. Normally we just rp it out by grabbing a box and letting people "take" air fresheners out of the box. I think it would be super cool if we could have actual physical ones added to convenience stores across the city and be able to physically hand them to our customers.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
