### ISSUE TITLE
Unable to retrieve vehicle from shared garage (Row Lowenstein)

### ISSUE THREAD

**Issue by zyronex** [InZidiuZ/op-framework-issue-tracker#2189]
**Assurance:**
Yes.

**Summary:**
I have keys to two apartments: Row Lowenstein Blvd. Apt. Complex A and B. Both buildings share a garage. When I park my car in the garage, I unable to choose the garage, which is fine, but when I come another day, there's a chance I get the other garage, which means I can't take my car out.

**Steps to Reproduce:**
Get a key to an apartment at Row Lowenstein Blvd. Apt. Complex A and then a key to an apartment at Row Lowenstein Blvd. Apt. Complex B. Park your car there. Come back another day and see which garage you get.

I tried closing and reopening the garage menu a few times, but it's always the same garage at that point.

I also tried taking a soft nap and waking up at the apartment that has the garage with my car, but that also doesn't seem to work.

**Expected Results:**
This could be solved in a couple different ways. The easiest seems to separate the two markers so you can walk up to the garage you want; they could even be in the same area. Alternatively, when accessing the garage, perhaps it could prompt you with the names of the garages at the marker.

**Actual Results:**
I have no control over the garage I park my car in or which garage I get when I try to retrieve my car.

## Additional Information

**Screenshots:**
![20220217164541_1](https://user-images.githubusercontent.com/97766748/154586121-89ac22a7-5fc9-4e3c-bed5-4dad46f3e2a3.jpg)

**Comment by twooot** [comment]
This has been fixed
