### ISSUE TITLE
Suggestion - Add Clothing Store Commnds

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2190]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Have commands for each clothing item that can only be used at clothing stores to allow setting a specific item of clothing / texture 
The commend could be /set{{Item}} \<\<ID\>\> \<\<Texture\>\> 
For example if I wanted to put on Shirt 82 with Texture 20 I could do /setShirt 82 20 

**Reason:**
Why would your suggestion be a good change to the framework?
This would help make setting up uniform a lot easier, rather spending a lot of time spamming Left/Right arrows to find something, especially for EMS/PD who may have multiple outfits that need setting up

**Comment by panpawn** [comment]
I think what would make more sense to accomplish the same goal would be to for a new clothing menu that allows people to manually type in numbers.

**Comment by MetaHatter** [comment]
I agree, it would be ideal to type in the numbers. That being said, perhaps a modifier key (i.e. LShift+Arrows) that will let you jump 10 items at a time might also be helpful.

**Comment by twooot** [comment]
You can now hold down Shift to move faster through the menu

**Comment by twooot** [comment]
I think this will kinda resolve itself when we rewrite the clothing ui
