### ISSUE TITLE
Suggestion: Make /remove_[hat/glasses/mask] proximity based

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2191]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
Instead of requiring an ID after the `/remove_[hat/glasses/mask]` commands, make it be proximity based instead like `/confiscate`.

**Reason:**
_Why would your suggestion be a good change to the framework?_
It'd be less awkward to have to pull out the clipboard when removing a hat/mask/glasses and would be easier.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
