### ISSUE TITLE
Yellow Pages for ads Suggestion

### ISSUE THREAD

**Issue by ScoochiScooter** [InZidiuZ/op-framework-issue-tracker#2192]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Twitter is supposed to be a place for goofs and giggles not a place for HUGE advertisement's that take up half your screen I think that there should be a new app on the phone something like yellow pages for ads a place where you can post advertisements for businesses and personal as well 
**Reason:**
Why would your suggestion be a good change to the framework?
I think that with a specific page for ads I think that there is more RP to come out of businesses not even legal businesses or even at all just a place where you can post ads for the community and I think it would work well across all the different servers of Legacy

**Comment by kucej** [comment]
It doesn't have to be phone-based , until we get a new phone. You could just add /yellowpages that opens a tablet-like site, where people can advertise, or something similar. But yeah, we are defo missing yellow pages, advertising on twitter is meh.

**Comment by coalaura** [comment]
This would be something for https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2447
