### ISSUE TITLE
Antibiotics Paleto Sell Spot

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2194]
Assurance:
Yes

Summary:
Write a summary of what your suggestion is about.
Make Antibiotics a sellable drug. Not like weed or coke. But utilize the same sell system for jewelry/diamonds.

Pops Pills in Paleto

Price: 100-200 (range)

Location>

https://cdn.discordapp.com/attachments/876565140902924298/945346508159594566/Screenshot_2022-02-21_104428.png

https://cdn.discordapp.com/attachments/876565140902924298/945346508792938586/Screenshot_2022-02-21_104812.png

**Reason:**
This would add more value to Paleto by turning something almost useless into something that feeds into the economy. If people are coming from trash all the way up here odds are they might fuck up their vehicle along the way. Sol would theoretically benefit from this. On top of that I feel that even though its a small addition, anything that can benefit up north and away from the city is something to consider.

**Comment by twooot** [comment]
Antibiotics aren't meant to be a drug. They are there to enhance EMS RP. I would rather add a different new drug

**Comment by vol5** [comment]
> Antibiotics aren't meant to be a drug. They are there to enhance EMS RP. I would rather add a different new drug

You having a clear defined vision for them is great. If they a re not meant to be sellable that is understandable.
