### ISSUE TITLE
Aerobatic smoke

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2195]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
- Yes

**Summary:**
Write a summary of what your suggestion is about.
- Enable the use of aerobatic smoke for planes listed in "performance" certification.

**Reason:**
Why would your suggestion be a good change to the framework?
- The effect already exists in vanilla gtao
- would find an enhanced use for airshows launched by state

**Comment by twooot** [comment]
Ben did this
