### ISSUE TITLE
Suggestion: Oil Gauge for Cars

### ISSUE THREAD

**Issue by stubiewonder** [InZidiuZ/op-framework-issue-tracker#2196]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Summary:
Write a summary of what your suggestion is about.
Add an oil gauge to vehicles that decays extremely slowly normally. When reaching certain oil levels, slow the vehicle's top speed down until refilled by a new item, oil kit, sold at stores. Impacts cause the oil levels to drop faster. May encourage safer driving and add additional RP.

The meter would deplete slowly over time, but faster when:

    Vehicle impacts/accidents
    Driving at high speeds   

The meter can only be filled by an oil kit purchased at a store, $200-$400, weighs 20 lbs

Oil Level Tiers

	0-25% - slowest -- Have an oil light come on
	26-50% - noticeably slower -- Have an oil light come on
	51-75% - slightly slower
	76-100% - full speed

Reason:
Why would your suggestion be a good change to the framework?

       Additional rp potential
       More interactivity with vehicles
       Incentivize safer driving

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
