### ISSUE TITLE
Suggestion | PD Heli Tracker

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2197]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
When an EMS/PD are in Angel One/Air One change the tracker into a Helicopter icon

**Reason:**
It reduces confusion, mainly for PD, and it's a nice quality of life change

**Comment by InZidiuZ** [comment]
This has now been done.
