### ISSUE TITLE
Ability to /escort for everyone

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2198]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
The ability for everyone to escort a person.

**Reason:**
Why would your suggestion be a good change to the framework?

Currently only the PD & EMS has the ability to escort a person. Only they can put a person in a car which has no trunk. They can put someone in Helicopter, Plane or in Boat. But the normal people don't have the ability to do that. If someone is unconscious at a place where only Heli/Plane/Boat can go or we need to bring someone with these kind of vehicle, in that case normal people don't have the ability to help. If there is no EMS, he has to take air lift. If we have the ability to escort we can help our friend in emergency situation like this. I hope this change will bring more RP in emergency situation. And will help if its in a critical place and also when there is no medical service available.

**Comment by Mugdha57** [comment]
people will start misusing this command

**Comment by rakibulhasan456** [comment]
In that case maybe we can introduce a new way to put someone in plane/heli/car from where the person can get out just like you get out from a car trunk if someone puts you in there. It will work like /carry but you can put a person in a vehicle which has no trunk space. In that situation maybe people wont be able to misuse it.

**Comment by panpawn** [comment]
Would this give people access to /suspect too? This would mean people who get hardcuffed and placed in cars can be taken by non-police.

Perhaps adding a brief timer to the suspect command would help balance it?

**Comment by MetaHatter** [comment]
I lean more towards just adding a "Press E to put in" function for a carried person to boats and helicopters. /escort can be easily abused.

**Comment by Mugdha57** [comment]
+1 Agreed with @MetaHatter

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
