### ISSUE TITLE
Make smoke trail on plane command available to plane license

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2199]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Make the smoke trail on plane command bound to license.

**Reason:**
Why would your suggestion be a good change to the framework?

Currently it is only available for the Super Admin which makes it hard to use for the licensed pilot when necessary. The smoke trail helps a lot for the flight instructor in training scenario. The student can easily follow in training which makes the training much easier. Also for special event/occasion preparation, the pilots can use it for training. If it is bound to the license then we won't need to call a Super Admin every time. It will make things easier for everyone.

**Comment by InZidiuZ** [comment]
This has now been done.
