### ISSUE TITLE
Repair Shop near Grapeseed | Sandy Shores

### ISSUE THREAD

**Issue by greatwhite18** [InZidiuZ/op-framework-issue-tracker#220]
**Name:**
iGreatWhite#3018

**Summary:**
A repair shop up near sandy shores and grapeseed would be great so we do not have to go all the way back down to the city to repair our vehicles. This is an actual repair shop with a garage door for vehicles and a regular door for people. I am not sure if it is as easy as copy pasting the shell for the small repair shop in grove street and making another instance up here. Let me know what you think about this.

----------------------------------------------------------------------------------------------------------
**Screenshots:**
![unknown](https://user-images.githubusercontent.com/30253522/61278470-1e1afa80-a769-11e9-96c9-25febaa3fdf8.png)
![unknown](https://user-images.githubusercontent.com/30253522/61278489-25da9f00-a769-11e9-8fef-e42288923edd.png)

**Comment by Ninjapex** [comment]
+1 It's a hassle going all the way back into town just to get a fix.

**Comment by SteezyRen** [comment]
+1000

**Comment by InZidiuZ** [comment]
Hey,

I've added a repair shop near Sandy Shores, so closing this.

**InZidiuZ**
*OP-FW Developer*
