### ISSUE TITLE
Private Garage at PDM

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2201]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add Private Garage at PDM.

**Reason:**
Why would your suggestion be a good change to the framework?

A private garage at PDM will help a lot with the Used Cars buying and selling RP. The nearest garage from PDM is Garage C. If we want to show a used car, we need to go other garages to show a vehicle. If we get a private garage at PDM it will be much more easier for the PDM employees to show a vehicle. We can easily buy/show/sell a vehicle if we get a garage here. Also it will allow the employees to park there vehicle there.

**Comment by lildiavolo** [comment]
This just makes sense tbh. If luxury Autos can get it, PDM should've been had it. Pretty self explanatory. +1

**Comment by MetaHatter** [comment]
Luxury Autos is a used car dealer, PDM is a new car dealer.  If we add a garage for used car sales to PDM would we also want to add new car sales to Luxury?

**Comment by twooot** [comment]
yeah PDM doesn't sell used cars, thats the whole point of luxury autos lol
