### ISSUE TITLE
[Suggestion] Drug selling changes

### ISSUE THREAD

**Issue by Spitfire2k6** [InZidiuZ/op-framework-issue-tracker#2202]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 
Yes

**Summary:**
Write a summary of what your suggestion is about.
Have it so there must be at least 1-2 cop on duty for drug sales to work.
Change it so it doesn't reset the price at a set time. eg 7am weed 6pm coke

**Reason:**
Why would your suggestion be a good change to the framework?
Selling drugs has no risk when there are no cops on duty so people will wait until there are none. Have it so there must be at least 1 cop on duty for drug sales to work.
People also camp the selling locations and wait for a certain time to hit to maximise profits, have it so the peak time changes and you dont have 10 people trying to sell coke at 6pm because there are no cops around

**Comment by lildiavolo** [comment]
I overall think this would be a healthy change. 
Minimum requirement for cops would make it so people don't just "cheese" the system by only selling early EU times when there's zero cops on duty. I think 2 would be a good number.
It is also very awkward to have 6 people running around vinewood when 6PM hits. It's not noticeable with weed cause of the different areas you can sell at, but with coke it becomes a circus at times. 
Not exactly sure what would be better tbh. Maybe just a set price between xxx and xxx for each drug that's random everytime you sell regardless of the time. (Example : coke bags sell between 400 and 800 regardless what time of the day it is). This would also make it so when 1-2 cops show up in those early EU times, they're not instantly overwhelmed by a large group of people selling and practically be incapable of doing anything about it.
I also think coke should have a larger radius of selling if not more places to sell at (there's only one that majority are aware of so i don't think another one exists, maybe i'm wrong) but this is a different topic.
+1

**Comment by Spitfire2k6** [comment]
> 

I disagree, the amount of money you make from it is too high for the 0 risk that comes with it.

**Comment by Spitfire2k6** [comment]
> I agree with the randomization of the times. Cop precondition for drugs is a bit tougher as it will limit crim activities during off-hours to basically houses (which is time limited already).
> 
> I would personally prefer the randomization of primetime as well as sell locations per #2148 to reduce the powergaming.

I disagree, the amount of money you make from it is too high for the 0 risk that comes with it.

**Comment by twooot** [comment]
oh shit old issues, this is done btw
