### ISSUE TITLE
Suggestion : Weed seeds from house robberies.

### ISSUE THREAD

**Issue by lildiavolo** [InZidiuZ/op-framework-issue-tracker#2203]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Add weed seeds to house robbing loot table.

**Reason:**
Why would your suggestion be a good change to the framework?

Weed seeds are mainly obtained from garbage runs, a job that you need to have and grind to get your hands on some. Not only that a lot of people that do want to grow weed already have whitelisted jobs and can't really drop them to become garbage grinders, but also the vast majority of people who do already grind garbage and get weed seeds will not sell you any because planting them and selling the weed that they harvest is just way more beneficial to them. You might be able to get your hands on any if you literally sat in garbage HQ and harassed every single worker you see into selling you them but we all already agreed that we don't want that to be a thing on the server for very obvious reasons. 
That's why I'm suggesting that weed seeds become obtainable from houses, I would even replace the 1q of weed drop with weed seeds as I think it's a drop rate that I think would be good and nobody wants that musty old 1q of weed that sat in a drawer for the past 2 weeks anyways. This would offer another way for all us filthy criminals that wanna sell weed another way to get our hands on the seeds without having to become garbage HQ andys.

**Comment by AdeptCL** [comment]
A big playing card in this, is that it is easier to find hard drugs (cocaine and oxy), than weed seeds.
This isn't how it should be in my opinion, it should be more common and easier to find seeds.

**Comment by MetaHatter** [comment]
You do not need to grind anything to get them. You can buy them from people that do.  One of the main points of having them in a job is to increase player interactions.

**Comment by lildiavolo** [comment]
> You do not need to grind anything to get them. You can buy them from people that do. One of the main points of having them in a job is to increase player interactions.

Like I said, most people who get them will just keep them for themselves as it's way more profit to do so. Obviously, it's not impossible to get and you can find people who would sell them to you but the chance of that being the case is very low. 
Weed simply shouldn't be this hard to get IMO like adept mentioned especially compared to the other drugs.

**Comment by twooot** [comment]
I do a lot of balancing changes and part of the balancing changes are that i make sure you cant get everything through one job. You need to do multiple jobs and i make sure you can get certain things only through one job and then give every job its own special thing. Garbage has weed seeds, i INTENTIONALLY removed weed seeds from everywhere else.

Thank you for coming to my TED talk
