### ISSUE TITLE
The ability to have 1 WL and 1 LI job.

### ISSUE THREAD

**Issue by Amoxicot** [InZidiuZ/op-framework-issue-tracker#2204]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I have.

**Summary:**

Basically allowing someone to have 2 jobs in the city. 1 WL and 1 LI job simultaneously. They would only obtain 1 check per hour, that being the WL check since that would be the higher paid one.

Now a days people have 2 jobs to make ends meet. So why not allow that in the server as well? Say for instance, a bartender. They are basically only doing their job during events and on the rare occasion they "open the bar" to have people come hang out. Why not allow them to go do a government job while keeping their WL job? Same with mechanics. When repairs are few and far between it seems anymore since there is the chance to have 6 shops open at 1 time, maybe allow the employees to go do some government work during the down time?

**Reason:**
This suggestion would seem to be good for the server because it would allow people to interact a lot more due to being able to have their WL job as well as a LI job. 

They could RP at their WL aka
Bartender during events
Mechanics
BM
BS

As well as RP at their LI jobs to obtain items to sell to other members of the server thus creating more RP and possibly more storylines.

Then maybe if this was something that could be done then their would actually be taxi drivers available :D

**Comment by Amoxicot** [comment]
Now this is all suggested if the ability to actually have this done, framework wise. Not sure of the limitations when it comes to job codes.

**Comment by twooot** [comment]
I dont think this would be a good addition. There is multiple ways to make money outside of jobs for people who are in whitelisted jobs and more are being added
