### ISSUE TITLE
Suggestion for Police(Vehicle) Megaphone.

### ISSUE THREAD

**Issue by DC0402** [InZidiuZ/op-framework-issue-tracker#2206]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes i do.
**Summary:**
Write a summary of what your suggestion is about.
Suggestion for Police(Vehicle) Megaphone. Its going to give us a chance to enhance our RP.
**Reason:**
Why would your suggestion be a good change to the framework?
Suggestion for Police(Vehicle) Megaphone. Its going to give us a chance to enhance our RP - as it increases our communication with the criminals. Its very hard to constantly switch the voice volumes to communicate calls and shout to the criminals while in a running chase- which they don't always get to hear either. It would be great if you add this in our server for quality RP. For Example: [Megaphone Video Idea](https://youtube.com/clip/UgkxYCXHvxvMRpIHCzbSivVWZc5V5Xmx86SB)

**Comment by ekhowan12** [comment]
really a good suggestion for police side.it will help police to give warnings .highly recommended

**Comment by keepcodingstar** [comment]
It would be better if we add a hotkey for the megaphone(push-to-use)

**Comment by V4P1Dx69** [comment]
Also for more, we can add an actual item in PD Armory named "PD Megaphone" and can trigger the megaphone with some kind of hotkey like *Shift+N* Etc.

**Comment by DC0402** [comment]
> It would be better if we add a hotkey for the megaphone(push-to-use)

Yup

**Comment by DC0402** [comment]
> Also for more, we can add an actual item in PD Armory named "PD Megaphone" and can trigger the megaphone with some kind of hotkey like _Shift+N_ Etc.

In my opinion only Vehicle would be much better. Thanks for the suggestion BTW.

**Comment by MetaHatter** [comment]
I would just use the megaphone to put it up to your mouth then when you talk in proximity it's amplified.  
Use the megaphone item again to put it away.

That way it mimics the mechanics used for roses/bears/boxing gloves and doesn't require an additional keybind.

**Comment by Mugdha57** [comment]
it would help the police a lot...

**Comment by panpawn** [comment]
I think this should have some sort of a voice filter so that it can be differentiated when someone is yelling vs using a vehicle megaphone
