### ISSUE TITLE
Changes to Store Robberies

### ISSUE THREAD

**Issue by CKylezz** [InZidiuZ/op-framework-issue-tracker#2207]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Automatically close Store Robberies without the need of cop RP'ers. 
Set the minimum cop number to 3 cops. If that's not what it is currently.
Give each individual store a 30min random CD.
Give all stores a shared 10-15min CD.
Review the loot of the stores, possibly add items (To be discussed) and set the payout to a low but consistent number. 1.5-2k.

**All** numbers could be played around, these were put together after not a lot of thought or discussion.

**Reason:**
Right now, the cop RP'ers have control over when and how to close robberies. That is so the police force can control scenes effectively and the roleplay from those scenes to be fully played out before another one pops. As well as controling the chain robbing within the server. 

For robberies such as banks and jewelry stores, i tend to be completely behind that concept, since it's a scene that involves preparation, other players and a high risk high reward mentality.

For right now, part of the roleplay that we are losing and is very much unused by most crim RP'ers is store robberies. Although you will always hear about how players within the server want new heists, i believe a change to make all current heists more relevant would be a low effort - high reward type of situation.

Stores are a good way to get involved with the robbery RP. With high risk and low reward, it rewards the ballsy crim RP'ers that have nothing to lose and low effort.

Although it could use some tweaks to avoid abuse and the grind for money, it's not a bad thing in general to reward players dedicated to that RP with more options to make their living.
 
There's also the issue where cops genuinely forget them open ALL the time and will take a full restart time to ever see them pop again.

**Comment by AdeptCL** [comment]
Although it is a robbery, and in the category of banks/jewellery stores... They're very miniscule in comparison. 
Respectfully, store hits should be often and ~decent income. Earning between $1,500 and $2,500 per store hit, but having the ability to do multiple without the need for cop presence as mentioned above, I believe this could benefit both police-sided and criminal-sided roleplay.

**Comment by superiorchicken007** [comment]
I would say if its the same store getting hit back to back it should be a low amount but if its been awhile since the store was hit it should be more.  (due to a store being robbed they wouldn't have as much money)

**Comment by twooot** [comment]
> Automatically close Store Robberies without the need of cop RP'ers.

no

>  Set the minimum cop number to 3 cops. If that's not what it is currently.

this can be configured in the server config

>Give each individual store a 30min random CD.
Give all stores a shared 10-15min CD.
Review the loot of the stores, possibly add items (To be discussed) and set the payout to a low but consistent number. 1.5-2k.

Store robberies are very well balanced where they are right now
