### ISSUE TITLE
[Suggestion] Cayo Perico Weed Field Iteration

### ISSUE THREAD

**Issue by Fugitive-HD** [InZidiuZ/op-framework-issue-tracker#2208]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
  *The Issue*:
   - the weed field was a good way for entry-level criminals to get into the criminal lifestyle
   - Cayo Perico is an island that has a lot of potential for RP but is seemingly unused for the most part
   
*Proposed Solution*:
The proposed solution that myself and 3 other members of the community had was to use Cayo Perico as a weed harvesting field with various areas of the island be used for harvesting to prevent 1 gang from choke holding the weed on the island

**Reason:**
The Reasoning behind using Cayo Perico as a weed field island is as follows:
Cayo Perico is an island that for the most part is not utilized, the island's aesthetic is one that would fit some sort of drug operation however hasn't seen much action of that nature since the island's introduction, adding the weed field to Cayo Perico would add some purpose to the island as well as add some RP to the island in the form of gangs attempting to fight for different control over certain fields on the island, this would also add new RP for police responding to suspicious person calls on Cayo, as well as possibly responding to gang disputes on the island and other things of that nature, in general adding more RP to an otherwise unused island.

The Reasoning Behind Re-introducing a weed field is as follows:
The weed field re-introduction would introduce a way for low-level criminals to have a way to get their foot in the door in the criminal RP by doing low-level drug trade activity which has the chance of them running into and interacting with already established gang RP members who also visit the field, hence giving them a gateway into the criminal and gang RP world.

*For Devs or Nerds - MDA table for the proposed idea*: [MDA_Cayo Perico.docx](https://github.com/InZidiuZ/op-framework-issue-tracker/files/8161593/MDA_Cayo.Perico.docx)

People Who contributed to this idea (discords):
Caioo#3064
Xae'raan#8008
Fugitive HD#2568(writter)
superiorchicken#0001

**Comment by twooot** [comment]
Cool idea, implemented some variation of this but it is up to the server managers of each subdivision to enable or disable it
