### ISSUE TITLE
[Maps/Harmony] Add Outside Bay to Harmony Repair 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2209]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Due to the Interior of the harmony repair shop being bound to the same MLO as Lost we would like to shift our focus on having outside bays. This would be beneficial as there is a lot of trucking traffic in there area now.

To remove the need to any Map changes, could we get just 1 Outside bay, mirroring how they have it at Lost
Outside Bay at Lost: https://i.imgur.com/gnWQkh2.jpg
Here: https://i.imgur.com/n7MR2BF.jpg

**Reason:**
Why would your suggestion be a good change to the framework?

Currently Harmony only has 1 bay so can not effectively handle multiple customers, as well as not being able to repair larger vehicle without the risk of them ending up at Go Postal or on the roof. This would allow mechanics to repair any vehicle that needs one (Including small aircraft, Tow Trucks and Phantoms) and would allow us to offer repairs to Truckers who often use the truck stop over the road

**Comment by twooot** [comment]
Done
