### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MindofMonsters** [InZidiuZ/op-framework-issue-tracker#221]
**Name:**
MindOfMonsters#8045

**Summary:**
Give some way for the journalist job to find scoops in Los Santos. Such as being able to tap into the police or EMS scanners.

**Reason:**
Would add depth to the Journalist job and allow them to provide better stories.

**Comment by InZidiuZ** [comment]
Hey,

At this time this will not be added, so closing this.

**InZidiuZ**
*OP-FW Developer*
