### ISSUE TITLE
Battering Ram Broken

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#2210]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/id/dcs_281/

**Summary:**
Upon use of the Battering Ram in order to attempt to enter a property for a Search Warrant, the Battering Ram did not work and did not allow for not only the user of the item to enter the house, but the people around the user as well. All of which are supposed to enter the property upon the Battering Ram's use. Whenever it was used, a message was displayed over and over no matter if we used a new Battering Ram item or not.

**Steps to Reproduce:**
Use a battering ram on a property.

**Expected Results:**
The user along with anyone else around them to be able to enter the property upon the item's use and have full access to search the property in the event of a raid.

**Actual Results:**
The item does not work, and a message constantly displays that we should wait before using it.

## Additional Information

**Screenshots:**
https://i.imgur.com/wXKdGHe.png

**Player Data:**
CID: 112
Nathan Spencer

**Server:**
Legacy Roleplay International

**Comment by twooot** [comment]
I think this is fixed
