### ISSUE TITLE
Move Cesars Place 2 Garage

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2211]
**Summary:**
I would like to move the garage of Cesars Place 2 to a more useful location up by the garage.

**Reason:**
This would be a good change because currently it is down by the road. The house has a huge round-a-bout driveway and still has the garage down by the road. I have been told that this is because the gate that used to be there did not open so the garage was moved outside for that reason, however since then that gate has been removed and the driveway is fully accessible.

![image](https://user-images.githubusercontent.com/47933692/156820091-fc38a16d-8884-4cd2-9ffb-51e4b3b2b4dd.png)

Sorry I took the photo at night, but you can see where the garage is at the bottom, and if it could be moved to near where the arrow is that would be great.

**Comment by twooot** [comment]
This has been done
