### ISSUE TITLE
/dispatch system for Cops

### ISSUE THREAD

**Issue by CKylezz** [InZidiuZ/op-framework-issue-tracker#2212]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**

Add a /dispatch command, which inputs a manual dispatch call to the local dispatch for on-duty officers.

Ex:
/dispatch callsigns insert message

/dispatch 128 10-11 black sultan occupied 3 times southbound elgin. One 77 appreciated.

that dispatch call would then show up under the list of calls, alongside hotwiring, suspicious person calls and whatever else.

**Reason:**
The "local" dispatch (https://i.imgur.com/O0QtnPy.png) while on patrol will notify officers of whatever is going on during patrol - be it a vehicle theft or a shots fired call. 

This system would allow cop RP'ers to manually input dispatch calls. Helping radio traffic to stay clear during other callouts and situations. 

If a chase is happening, the commns from that chase wouldn't have to be broken to notify units about my traffic stop. Or if other units are on a different radio channel this "global" dispatch would allow for better communications between multiple frequencies.

This will allow for versatility and better communications from the entire police department.

**Comment by Mugdha57** [comment]
it will be a complicated job to do ffs.

while police pursuit using this /dispatch command. anyway i like the idea it will surely reduce the radio traffic +1 about this.

**Comment by panpawn** [comment]
I'd just call it a 311 system and make it /311

**Comment by twooot** [comment]
I'll add it

**Comment by twooot** [comment]
This has been done
