### ISSUE TITLE
Zoom function for clothing camera

### ISSUE THREAD

**Issue by Stretah** [InZidiuZ/op-framework-issue-tracker#2214]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Adding a zoom in & out function to the clothing camera system.

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow users to zoom in and out on clothing items to get a better idea of what is being changed.

**Comment by twooot** [comment]
Done
