### ISSUE TITLE
Wax kit for cars

### ISSUE THREAD

**Issue by Stretah** [InZidiuZ/op-framework-issue-tracker#2215]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

A wax kit for mechanics to purchase from the computer that can be sold to customers. The wax kit would allow for someone's car to not get dirty over a longer period of time

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow mechanics to sell an item only available to them bringing more RP to the customers and shops and allow customers to stop their cars from getting dirty over a period of time.

**Comment by DHXIIX** [comment]
PLUS FREAKIN 1 MAN

**Comment by RetroCharles** [comment]
This -- or even as service that can only be done at repair shops and by mechanics.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.

**Comment by coalaura** [comment]
#2883
