### ISSUE TITLE
Adding the ability to resist arrest when getting cuffed.

### ISSUE THREAD

**Issue by Althusa** [InZidiuZ/op-framework-issue-tracker#2216]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**

My suggestion is the ability to slip cuffs/resist cuffs. So, adding a mini-game or something to add the chance of resisting and running again. This would give that 3rd option to crims when running on foot.

**Reason:**
Why would your suggestion be a good change to the framework?

The reasoning behind this addition is to help improve the criminal experience. This would decrease the hostility between the police and the crims considering it would not be so toxic when in a foot pursuit. I understand how this could be seen as one sided but if you look at it from a criminal side, it can be really annoying when you get tackled and hard cuffed with no chance to get out. Once again the positives to it is a better experience for both criminals and cops. A lot of people have agreed on me with these even cops. I see this as a really good addition and make a lot of people happy. Thank you.

**Comment by panpawn** [comment]
I think if this does happen and is fairly do-able, then cops would default to hard cuffing and civs would need a way to escort/suspect in/out. I also think someone should only be able to resist maybe 3-4 times before it stops giving you the option.

**Comment by superiorchicken007** [comment]
Honestly as being a cop I would love for them to have a chance of "breaking cuffs" and being able to run.

**Comment by twooot** [comment]
Included in this suggestion #2228
