### ISSUE TITLE
PizzaThis Addition

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2217]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I have read it

**Summary:**
Overall, our idea would be to add another restaurant to Legacy for people to eat at. This essentially would add competition for Burgershot and would open up other RP avenues without an extraordinary amount of work. 

To keep things basic, the overall products would be as follows
**Finished Products:**
- Plain Cheese Pizza
- Pineapple Pizza
- Coke
- Bottle of Water
- Rootbeer

In the back of the restaurant, you would be able to buy the following products to craft pizzas
**Ingredients:** 
- Dough
- Can of Sauce
- Block of Cheese
- Pineapples/Garlic 

In the back, there would be a table and oven where you use these products.
**Steps to Create:**
- The dough would need to be spread out and created into its circular shape
- The sauce would need to be spread on the dough
- The cheese would need to be grated/spread on the Pizza
- (OPTIONAL) Pineapple would need to be cut/placed on top of the Cheese
- The Pizza would need to be cooked in the oven.

- This would than produce either 8 slices of Plain Cheese Pizza, or 8 slices of Pineapple Pizza. These slices could be sold individually or packed into a "meal" (pizza box) to present an entire pizza box. The 8 slices would obviously be miniscule compared to the full meal, along with 1/2 cokes.

**Customer Interaction**
- A new Phone Line would be created name "Pizza" or "PizzaThis" which would work like the Burgershot line, where people send a text where they request pizza or a delivery to people who don't feel like driving.

- There will be a front desk where people can walk in and purchase meals/slices in order to satisfy their hunger and/or thirst.

- Deliveries would work like Burgershot deliveries, dropping off meals for a tip and making money back by dedicating time. 

**Reason:**
This suggestion would be good for a multitude of reasons. 
- This would add a friendly and competitive roleplay by adding options for people to choose where to get food from. That being said, Burgershot is essentially the best spot to get food from and is in place to add roleplay to get good food instead of dragging and dropping food into our inventories. That being said, adding another joint for people to get "good" food at in Legacy. This would create a friendly "competition" and another business that is not mechanic based that would allow different groups of people to go to. Between Burgershot and PizzaThis, the business competition would exist between who can gain the most customers, location of them, and overall add another job for people to roleplay as if they do not fit in a certain cliche. 
- This essentially wouldn't be the most complicated thing to add to the server. The only things that would need to be "added" is the actual items and the interior. The rest of the code can pretty much just be copied from Burgershot since the same process exists, being crafting the food, making a meal, and selling it. If people wanted to go on "runs", than you can do that as well and would follow the same idea as Burgershot deliveries.
- A lot of people have to drive across town to go to Burgershot, we were thinking somewhere by Vinewood or Mirror Park. This would make it easier for Police, Lost MC, and other individuals who live in these areas by having an easier place to get decent food at. It would create equal roleplay, if not more due to the availability of jobs.
- For people who like the roleplay of going on dates, taking friends out to eat, etc, there is a little bit more of a "distinct" place to go instead of Burgershot and the Steakhouse to do this roleplay at.

**Comment by nunsia** [comment]
grape idea, i think this would bring a lot of roleplay, however I don't think pineapples are well appreciated by some people. I think this idea would totally move forward if the pineapples were taken off.

**Comment by ImArteria** [comment]
> grape idea, i think this would bring a lot of roleplay, however I don't think pineapples are well appreciated by some people. I think this idea would totally move forward if the pineapples were taken off.

I agree. I dislike Pineapple by Layla vouched for it.

**Comment by poopgawd** [comment]
Listen. I thought having pineapple pizza, being the most hated thing in Legacy would be a good "paying homage" food to the city. lol

**Comment by skyy-reginald** [comment]
Could make a banana pizza since Layla loves bananas hehehehehe

**Comment by ImArteria** [comment]
UPDATE:

For some reason it won't let me edit it, but we also think Rootbeer and Garlic Knots would be good additions as well.

**Comment by Enryy** [comment]
^^

**Comment by Djibouti11** [comment]
this is very pog frog, while i agree pineapple is heinous on pizza, it really has a place in the community

**Comment by kaycorriher** [comment]
I think that the addition of any food based business would be greatly beneficial to the server. Currently, you can only buy quality food from Burger Shot and Bean Machine. However, bean food is not is satisfying as Burgers. 

Any competition to food Burger Shot is a great addition in my opinion. And pineapple on pizza would be quite the conversation starter

**Comment by xarxesthegreat** [comment]
> this is very pog frog, while i agree pineapple is heinous on pizza, it really has a place in the community

While your opinions on pineapple pizza are sacrilegious at best I think due to it being a long running meme in the Legacy community now that it's required. 

Overall this is a great idea and hope that it can be implemented in the server.

**Comment by SilkyDrip** [comment]
I would love to see it as it is truly something we lack and would be owned by some of the best people I know of in city to interact with.

**Comment by antihero6713** [comment]
Work will be begin shortly on this.

**Comment by nunsia** [comment]
> Work will be begin shortly on this. 

@antihero6713 how is that coming along? :)

**Comment by antihero6713** [comment]
We have fury working on it currently. We will get screen shot soon-ish i hope

**Comment by antihero6713** [comment]
![image](https://user-images.githubusercontent.com/25892037/166400810-4222d92c-7a9c-4a45-96ff-75b6b5e90453.png)
update on interior with some custom props no textures

**Comment by InZidiuZ** [comment]
The interior is required before adding any features. Please reopen or create a new issue once the interior has been added.
