### ISSUE TITLE
Check Tune Command

### ISSUE THREAD

**Issue by Stretah** [InZidiuZ/op-framework-issue-tracker#2218]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Have the ability for civilians and PD to use a command to check if a vehicle has had an illegal tune applied to the vehicle.

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow PD to crack down on illegal modifications to vehicles and allow racers/civilians to check to make sure their tunes are being applied when using the tuner chip.

**Comment by DaxterPancake** [comment]
I like this suggestion mostly for the cop side, we are currently trying to figure out an RP way to check for illegal modifications (engine 5) as we are starting a case on it which should bring more cop RP to racers and the like. A command like this would make this so much easier than the current plan on lockpicking a car and driving it to bennies.

**Comment by SirPiff** [comment]
completely agree, this should've come with the addition of EMS 5 IMO as pretty sure the intention was for ems5 to be an illegal mod.

A command to downgrade to 4 potentially would be nice too, although unsure about people malding about that.

**Comment by twooot** [comment]
IRL you wouldn't be able to know if a car has illegal tunes just by hopping inside it. I think having to bring it to a mechanic who then checks it for you brings more rp. I'll add the command but not for PD :)
