### ISSUE TITLE
[jobs/ems] paycheck and structure additions and reconfiguration

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2220]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
My suggestion is to add 3 more pay check tiers into what we already have.  Would add the addition of Sr. Paramedic, Sr. Specialist and Sergeant First Class.  The new paycheck structure would be as follows if accepted or adjusted by the dev's with what they see fit.

EMT - [55$]
Paramedic - [70$]
Sr. Paramedic - [82$]
Specialist - [96$]
Sr. Specialist - [102$]
Sergeant - [110$]
Sergeant First Class - [118$]
Lieutenant - [126$]
Captain - [134$]
Assistant Director - [138$]
Deputy Director - [146$]
Director - [154$]

**Reason:**
Why would your suggestion be a good change to the framework?
I believe the addition of the 3 new positions will help out with adding new ranks and responsibilities into EMS along with having more opportunities for advancement.  I based the new positions off of currently what SASP has but with different titles.

**Comment by twooot** [comment]
Done
