### ISSUE TITLE
Mount Zonah Changes

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2221]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
The removal of locks some doors on the ICU floor that lead to your death.
Addition of locks on the surgical wing where no one can enter.
Locks set as unlocked on the 2nd floor instead of locked.
Addition of moving the Morgue teleporter to the Morgue in Mt. Z

**Reason:**
Why would your suggestion be a good change to the framework?

Removing the locks on the ICU floor and keeping the doors permanently locked would be good so no one accidently unlocks the door and then falls to their death.

Addition of locks on the surgical wing would be great so no one just randomly walks in during a procedure.

Setting the locked doors to unlocked after server reset so people can go outside and enjoy the air while exploring the hospital or waiting for someone in ICU or Surgery.

Moving the Morgue teleporter to the Morgue in Mt. Zonah would be good.  This way we don't have to drive across the city to use the current morgue we do have.  This way after someone Perma's or does not make it we can escort them down to the Morgue where friends and family can visit all in one place.

**Photos**
![Add locks (1)](https://user-images.githubusercontent.com/81419197/158814804-8453e605-e088-4df9-9a76-9da5cf8ceee3.jpg)
![Add locks (2)](https://user-images.githubusercontent.com/81419197/158814805-54f71274-d21a-4fff-8678-222998b9f1af.jpg)
![Double Locks](https://user-images.githubusercontent.com/81419197/158814807-89909e44-ad7c-4d96-a4d3-e926b139cb2a.jpg)
![Morgue](https://user-images.githubusercontent.com/81419197/158814808-7c239b9d-258a-47ab-b3e2-bd904b4697f4.jpg)
![Remove Locks (1)](https://user-images.githubusercontent.com/81419197/158814810-c841b0aa-0717-4829-ae58-bd37a5eba6a3.jpg)
![Remove Locks (2)](https://user-images.githubusercontent.com/81419197/158814813-8d282eaf-216f-4406-9c69-857130e17c61.jpg)
![Unlocked (1)](https://user-images.githubusercontent.com/81419197/158814816-bbf755b3-3afc-4452-82a0-516fc2f46ff5.jpg)
![Unlocked (2)](https://user-images.githubusercontent.com/81419197/158814817-623fe730-aca1-481e-9771-4ddeb06ec7f1.jpg)
![Unlocked (3)](https://user-images.githubusercontent.com/81419197/158814818-2698b715-4ce6-4489-9f27-c97ea33a7382.jpg)
![Unlocked (4)](https://user-images.githubusercontent.com/81419197/158814819-867d051c-33e6-41b5-b410-5489eb340b8d.jpg)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
