### ISSUE TITLE
Suggestions for the dispensary

### ISSUE THREAD

**Issue by tftwsaaron** [InZidiuZ/op-framework-issue-tracker#2222]
Name:
TftwsAaron#4141

Summary: Suggestion for a new craftable item that would dramatically improve traffic and vitality to the weed store Green Wonderland along with some minor storage adjustments. 

New Item: Blunt

Weight: 1lb

Images: 100x and 1000x
![blunt_100x](https://user-images.githubusercontent.com/86331939/157926727-3b5aa024-70d6-4257-b989-2c100f8c2c31.png)

![blunt_1000x](https://user-images.githubusercontent.com/86331939/157926989-325f859f-8861-479d-9993-497c5e26d45a.png)

Effects: 
(pros) +25% armor per blunt with stress relief same as joint. 

(cons) Munchies degrades hunger faster over time or a large chunk each use.

Crafting:  https://cdn.discordapp.com/attachments/875896107257983037/954407759984619540/InkedScreenshot_2022-03-18_114347_LI.jpg
2q > 1 Blunt
1oz > 2 Blunt's
Location - back room table in shop.

It would be amazing if we could receive a shared storage locker or even a personal storage locker. This would improve the quality of life of the store especially if we had a new product.
Storage Location: https://cdn.discordapp.com/attachments/875896107257983037/954407760475332628/InkedScreenshot_2022-03-18_114149_LI.jpg

This would be a great change to the framework, providing the weed store with unique product to sell outside of the standard weed market. Possibly giving the store way more traffic and easing into crafting implementation across other businesses/systems in Legacy. The store is a unique place that has its own little stoner community and we would like to add more unique rp value to the people that enjoy it.

**Comment by Enryy** [comment]
add exclusive items for the company, like mariujana biscuits, bong etc... with different effects than regular marijuana

At the moment there is only 1 mariujana and you can find it everywhere... I mean, if you can find it everywhere the greenworderland what's the point?

**Comment by ThisIsNotDex** [comment]
I'm not sure how much regular joints add for armor, but it seems far too large of a step up in my opinion for it to be +25% armor

**Comment by tftwsaaron** [comment]
currently 10%

> I'm not sure how much regular joints add for armor, but it seems far too large of a step up in my opinion for it to be +25% armor

**Comment by twooot** [comment]
I added vapes to the store
