### ISSUE TITLE
[?/?] Gavel at MRPD courtroom

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#2223]
**Assurance:**
Yes

**Name:**
Matt;)#7784

**Summary:**
Please add a functioning gavel to the MRPD courtroom for extra intense situations so the judge can take control.

**Link:**
No links, but there is currently a gavel at the courthouse near garage A. 

**Reason:**
The gavel adds to the realism, lets a judge take control of situations and makes the MRPD courtroom more like a courtroom and appealing to be at rather than get the transport to garage A courthouse. A gavel is needed for proceedings, such as moving a trial underway, initiating a recess, etc. 

Justice Erin Reid has also backed this, we would use it all the time. <3

**Note:**
Whether this gavel can be made quieter or not is another story, but I can promise it will not be abused by the judges in terms of noise, etc. It will be used only when necessary. If PD are reluctant for this change, they can surely deal with anyone messing with the gavel from PD internally.

**Comment by nunsia** [comment]
Love this idea. Should also be loud enough for the whole of MRPD to hear so they have no excuse to be loud near the courtroom when a case is in session.

**Comment by InZidiuZ** [comment]
This has now been done.
