### ISSUE TITLE
Legacy Trading Cards - Money Sink + Insane Community RP

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2224]
Assurance: Yes

Name:
vol 5#3752 - Bill Brook

Summary: Trading cards that inject dopamine in all the right spots. Providing personalization satisfying one of the deepest human urges - The desire to be important. Cards are focused on characters inside the legacy rp universe all while acting as a money sink. With a goal of a game creation around it. Molded around a gambling loop for maximum engagement. This vision reels people in who actively play to feel a part of something even if they are not on a card themselves. The cards have insane community and interaction building potential. Also acting as a way for collectors to get enjoyment with a system like this, especially all the old heads. Hence the conceptualization. Who would not want to collect themselves on a card or their friends or people who have come and gone and left their mark on this place. This engages an amazing group of people and connections all boiling down to RNG.  Below I outline the vision for this and how I would best see fit for implementation. 
------------------------------------------------
Item: Legacy Trading Cards Edition 1 (box)
(Does not degrade)
3lbs
Image: https://cdn.discordapp.com/attachments/948737926676758578/948938539423391785/1ST_EDITION_BOX.png

On use generates 3 random cards from loot pool. Gives player the 3 rng cards and consumes box.
------------------------------------------------
(Currently sitting at 100 cards created)
Cards Info:
Top - Title/Name
Middle - Stat/Effect
Bottom - Funny quote or phrase
1lbs
------------------------------------------------
Loot pools and rarity tiers of cards from top to bottom. From most common to most rare with probability examples. Card quantity may change.

Rarity: 
1 box = 3 cards (Probability from 100 pack purchases or 300 cards total)

[quanity rarity - classification differentiation (probability in decimal value ev: expected value per info above)]

28 Bronze - No stat bonus (0.60 ev: 180)
20 Silver - Stat Bonus (0.20 ev: 60)
14 Gold - Bigger Stat Bonus (0.12 ev: 36)
8 Holo - Massive Stat bonus or unique bonus (0.04 ev: 12)
7 Foil - Unique bonus (0.015 ev: 4.5)
2 Relic - Insane (0.005 ev: 1.5)
3 Headache - Purposeful fuckup (.0025 ev: 0.75)
16 Missprint - Export fuckup (.0012 ev: 0.36)
2 Ethereal -  Most rare (.0005 ev: 0.15)
x Promotional - Event cards (Extremely Limited)
Link to all currently created cards: https://drive.google.com/drive/folders/1t6sdr0GoWli3OoFr0AULhSBKR91hQxsR?usp=sharing

- Buyback at random door sell spot in usd: could all be one sell spot or multiple. I do feel like this would add value in the sense that it would consume the mass quantity of cards generated. It would also feed the addiction to the money sink all while still being a net loss buying boxes since the probabilities are so low in the first place. This is not a complete sink since individuals would retain some value but gives the option for the consumer to think they can profit off buying packs all while that is not the mathematical reality.

(values can always be changed as you see fit)
BRONZE: 50
SILVER: 100
GOLD: 150
HOLO: 500
FOIL: 1000
RELIC: 3000
HEADACHE: 5000
MISSPRINT: 7500
ETHEREAL: 15000
------------------------------------------------
Card Feature: Can be displayed like CID Cards or PD badges.
This offers more personalization and lets people show off their new/old card so a collector can have that satisfaction of displaying what they have. Currently in the server people love to show off their id collection and that scratches the same itch. It just 
------------------------------------------------
Product sourcing???? This would most likely be best served as a buy location item. While crafting from wood to paper and fruit to ink. Then Paper+ink = box would be cool. I do feel that it would be a bit much. But that is entirely up to yall as the dev team. 
------------------------------------------------
Money/Business
I feel that it would make the most wholistic sense that the business would earn a % of the money per purchase of a box if it was from buy spot. Preferably it would be best if it was profitable for the creator or future potential creators since this is COMPLETELY CUSTOM ART made for the city and not just a random in game item. Of course not insane money but somewhere around (70%-80%) Sent to a business account in game. Of which the owner of said business would gain access to. Implementation of a system for this would add the most RP value if a comic store MLO was introduced. Where employees could sell the boxes/packs/cards. But this could also be a convivence store item to be fair. 
------------------------------------------------
I thought one day this would be a cool Idea. I like to create shit so here we are. From one little Idea we have custom artwork based off personas in Legacy RP. Not everyone is in here but there is room for expansion. I am just trying to add value to this wild mini universe where I can. If this becomes a thing cool. The goal of this is to add another layer to the world/economy all while making people inside the world feel a sense of importance. To bring a more unique aspect of rp, because for some weird reason people like to collect shit. I think ive wrote enough and everyone that takes a look, sees how much value this can add to the city. I hope you enjoyed the read!

-Big Chungus

**Comment by navonody1** [comment]
Gimme gimme.

**Comment by twooot** [comment]
yes

**Comment by vol5** [comment]
The goal is Edition 1, could use more individuals so within the next few days people will want ones made and that can take some time (Yet still limited completing at around 120ish in totality). Then Edition 2 in the future where there is a partial or full redesign and Edition 1 would be vaulted. I also plan to make small limited edition/stylized cards that would differentiate from the standard design or color scheme that could pop up for a week then disappear. Exclusivity and engagement. These will essentially immortalize personas/people/characters in the Legacy universe which is fucking insane.

**Comment by vol5** [comment]
> yes

Big T out here KILLING IT

**Comment by twooot** [comment]
This has been done

**Comment by vol5** [comment]
> This has been done

Thank you very much for realizing this creation. This is fucking wild... You been putting in that work. SHEEEEEEEEESHHH

**Comment by BunnySAngel** [comment]
Hola is Trading card now in RP or Removed? beacause i have seen selling spot
