### ISSUE TITLE
Slower Swimming in First Person

### ISSUE THREAD

**Issue by Brynjar708** [InZidiuZ/op-framework-issue-tracker#2225]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
[What is your steam profile?](https://steamcommunity.com/profiles/76561197993942076/)

**Summary:**
When swimming through first person you move at the 'normal' third person speed.

**Steps to Reproduce:**
Swim in first person

**Expected Results:**
Faster swimming

**Actual Results:**
Swim speeds matching third person.

## Additional Information

**Screenshots:**
Not suitable

**Game Resolution:**
Return swimming in first person to original speed.

**Player Data:**
![image](https://user-images.githubusercontent.com/101660311/159635203-1660cd6a-987c-4874-8586-134ecc2d5d8f.png)

**Server:**
Legacy RP (US)

**Notes:**
NA

**Comment by MetaHatter** [comment]
It is my understanding that swimming used to be faster pre-rewrite.  It's already a pretty monotonous and lonely job.  Likely worth a look.

**Comment by twooot** [comment]
Placebo, but ok ig
