### ISSUE TITLE
Tunershop Warrener

### ISSUE THREAD

**Issue by HowieTheBrave** [InZidiuZ/op-framework-issue-tracker#2226]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/1337xHavthu/

**Summary:**

The Warrener truck in the Tunershop was made into a "drift truck" i think, however it can barely even do that it just spins and redlines gains 0 speed, cant drift a corner, its basically useless. Its to the point where i tell people who want the truck not to buy it because it is undriveable.

**Steps to Reproduce:**
Drive the Warrener truck

**Expected Results:**
For it to drive like a normal car.  (preferably non drift, people dont want this to be a drift car)

**Actual Results:**
It doesnt drive

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
Legacy

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
