### ISSUE TITLE
J store as an actual store

### ISSUE THREAD

**Issue by Stretah** [InZidiuZ/op-framework-issue-tracker#2227]
**Assurance:**
Yes

**Summary:**
The idea would to have the J store be open and sell items such as diamonds and other things(more expensive than selling obviously). This could be either a store icon or owned by players.

**Reason:**
This change would allow for a more natural way for robbers to take hostages and rob the store itself. Would also allow the legal members of society to purchase goods such as diamonds, etc. without having to purchase (more than likely) illegally obtained goods from strangers.

I think this idea has a lot of potential and could be expanded upon.

**Comment by ThisIsNotDex** [comment]
Seems just weird from an RP stand point to take someone hostage is already working there to rob it, or shopping. I think its fine just how it is, and the RP can be done by people selling jewelry to show its "legit"

**Comment by nunsia** [comment]
I agree with Dex, I feel it would be way too easy for the "employees" of the store to be taken hostage, and if it was made into an actual business, it would be quite unfair to the workers of that business to have their RP cucked multiple times a day. I understand it would be the risk they take owning or working at the store, but in reality; it would cause more headache than fun.

**Comment by CloudTheWolf** [comment]
With Mining and being able to make rings I feel this is no longer needed

**Comment by twooot** [comment]
closed because of the reasons stated above
