### ISSUE TITLE
PD Rifle in PD Cars.

### ISSUE THREAD

**Issue by MeaLeigh** [InZidiuZ/op-framework-issue-tracker#2229]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes.

**Summary:**
The suggestion that I would like to propose involves the basic PD rifle and PD machine gun. I suggest these weapons are spawned in the trunk of the cop cars when they are pulled out of the motor pool (such as how cones and spike strips are now). I also suggest charging a "rental fee" when these vehicles are pulled out of the motor pool to counter the issue of PD members not having to pay for their equipment. The weapons in question would be "registered" to whoever pulled out the vehicle in the first place to account for keeping track of serial numbers or at the bare minimum would come back to "PD authorized weapon".

**Reason:**
The reason I think this suggestion could be beneficial is because it would allow officers that are patrolling to have access to their heavier weapons without having to break immersion by them constantly walking around with AR's on their backs. It would also help to balance PD vs Criminal situations by allowing there to be an actual escalation of force depending on the types of weapons are being used against PD. For example: At a Bank robbery the criminals inside of the bank are only carrying pistols. PD would then only use their service pistols to match force. If the criminals inside the bank had class 2 or 3's then PD would be able to go to their trunks and get out their respective counter weapon to match force.

**Comment by twooot** [comment]
No, they should be registered to the person and should be something that owned
