### ISSUE TITLE
Outfits

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-issue-tracker#223]
**Name:**
SATIN187#5716

**Summary:**
Possibly adding the ability to change outfits in your apartment

**Reason:**
It would be more ideal since most of the time you load into the server you dont load in with the outfit you want to use

**Comment by InZidiuZ** [comment]
Hey,

This has already been done, and will be live with next patch.

**InZidiuZ**
*OP-FW Developer*
