### ISSUE TITLE
Make grocery store food better again

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2230]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
This suggestion is about a change to current state of food in the server. I just want to preface by saying, yes RP will continue at establishments such as Burgershot, Bean Machine, the Steak place, and PizzaThis in the future, even with this suggestion. That suggestion being, make the sandwiches/tacos you can purchase from 24/7 not absolute dog doodoo. From the last time I used them, they only seem to give around 5-10% hunger regen, compared to establishments food which seem to do 30ish% hunger regen PLUS stress relief. I just want to be able to get some food and not have to drive down to BS, Bean Machine, or wherever else in order to not have to purchase 15 tacos in order to fill my hunger back up. This also looks out for the people in Sandy and Paleto who dont have immediate access to these establishments which are based in the city.

**Reason:**
Simply to just make it possible to survive w/o having to travel all the way to burgershot/ bean machine, in order to get food that doesnt completely suck.

**Comment by twooot** [comment]
I see your point, butuuut:
> I just want to be able to get some food and not have to drive down to BS, Bean Machine, or wherever else in order to not have to purchase 15 tacos in order to fill my hunger back up.
THIS is the entire reason why i made the change in the first place. I see the point of people in sandy or paleto but making grocery store food better again is working against my other idea

**Comment by twooot** [comment]
Go to burgershot or bean machine if you dont like the grocery store food
