### ISSUE TITLE
Suggestion Outside Bay for PDM

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2231]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

I'd like to suggest a New bay for PDM. This bay would be outside beside where you currently come from whenever you send a person out on a test drive. The purpose of this is to sell some vehicles that will not currently fit inside of PDM or be able to put some of the bigger vehicles we have outside. Vehicles that don't fit our as follows
Stretch (Limo)
Patriot Stretch (Limo)
Would also allow us to put some vehicles outside that struggle to fit into PDM such as the sand king. It opens up the possibility for us to sell some utility vehicles in the future as well like maybe the other Trucks etc. 
https://cdn.discordapp.com/attachments/914555550338011196/948063539346702357/unknown.png

**Reason:**
Why would your suggestion be a good change to the framework?

Honestly, I've spoken to quite a few business owners who have shown great interest in being able to purchase stretch limos for their businesses and future adventures they want to take their business on. Wither this is for business meetings, business opportunity or the possibility of just looking part of the higher class. As of right now the only way to Acquire one of these vehicles that is the normal Limo is buying stealing it from some of the nightclubs within vinewood. 

Adding an outside pay also allows us to put other vehicles on the inside since some of the larger ones take up to much space and only fit into Certain Slots within PDM. This can create new RP opportunities for creative individuals in the server as well as add to RP for some that have been looking for this already.

**Comment by twooot** [comment]
this is done
