### ISSUE TITLE
PDM Commission Change

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2232]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

As of right now within PDM Commission can be changed from 0%-15%, this adds to the overall cost of the vehicle not included. I am suggesting that this commission can still be edited however it can be between 10-25% and it is included within the overall vehicles price. 
As of right now if a car costs 100k with 10% it costs 110k to purchase. Depending on the level of PDM employee this money is then split. so for senior, It's 7k commission and 3k into the business. 

I am suggesting that the commission be included within the price of the vehicle so if the commission value changes the vehicle will become slightly cheaper. so if the base car costs 50k when it is put onto the PDM floor it will be at the set 25% costing 62500k and as the commission is changed this price will be lower. So 10% would be 55k. 

**Reason:**
Why would your suggestion be a good change to the framework?

This would benefit PDM as the system currently in place can be very confusing for people that are new to the city, especially when the cars are not set values like if it's 3220 the commission has to be worked out each time if any questions are asked. They will see a vehicle on the catalogue that PDM currently uses and be surprised whenever they are sold it's an extra amount on top of the vehicle. 

Some people have proven confused by this, others upset. The idea behind this is to create a better experience for those who currently work inside PDM and any Employees or newcomers to the city in the future who do not fully understand the commission system. 

This would also create a flat once payment like MIDNIGHT currently has in place. If a car costs 40k at midnight, It is 40k. Same as EDM. There are 0 hidden costs and no confusion. With the price changing as the commission changes between the suggested 10%-25% this would hopefully create more RP haggling as well with any customer that comes in and wants the car a little cheaper than what it is sold for.

**Comment by superiorchicken007** [comment]
I agree that having it as 1 set price is a good idea this way they know how much it is.  As for the commission you can still create RP haggling with the original 0-15%.  Not sure why changing it to 10-25% would be any better especially with how the economy is currently.  If you are looking to increase the price of the vehicle you can just set the base price higher and leave it with the same commission.

As of now I believe PDM automatically gets a percentage of the sale into the business account.

**Comment by Thebackyarddad** [comment]
Car buying experience is all about the store and customer trying to each get their best deal.  Including commission into the sale price, displaying one price, helps keep this immersion as authentic as possible. At the dealership, you don't argue with the salesman over what his profit is on the sale of the car. Being able to "negotiate" the price of the car with a customer offers way more RP. Also, displaying multiple costs to the customers can be confusing/disheartening. They check the catalog, find their car, save up the amount of money listed on the website, to only be told nope you are 5-15% short of that.

**Comment by Skai97** [comment]
> I agree that having it as 1 set price is a good idea this way they know how much it is. As for the commission you can still create RP haggling with the original 0-15%. Not sure why changing it to 10-25% would be any better especially with how the economy is currently. If you are looking to increase the price of the vehicle you can just set the base price higher and leave it with the same commission.
> 
> As of now I believe PDM automatically gets a percentage of the sale into the business account.

**Comment by Skai97** [comment]
Well, the thought process with the commission changes is to make it a one-time price where there are no hidden fees with how commission currently works. As of right now, a PDM employee can set the commission to 0 and there will be no extra charge however the result of this is themselves and the business makes no money. If my other suggestion is looked at the "Price suggestion" changes the vehicles within PDM will be cheaper entirely so the 10%-25% commission change on the price is so PDM so not get affected as a business in the current economy.

Despite everyone's belief, PDM does not make a lot of money each week. We average 20-50k per week, if cars are cheaper this will also be affected. The commission change would hopefully balance this respectfully.

**Comment by MetaHatter** [comment]
PDM prices are going to be completely reworked soon™. It is possible that this might be unnecessary after that update.  

Regarding the rate, IMHO 15% is the max it should go.  $15,000 commission on a single $100k car sale is MORE than generous.  Some jobs require hardcore grinding to get that. i.e. Even a mechanic would likely have to work for days unless someone is super generous w/tips.

I also agree that negotiating the commission is a valuable part of car sales RP.  Competing on rates applies downward pricing pressure and certain salespeople might be selected based on lower offered rates.

**Comment by Skai97** [comment]
I completely agree that 15k commission is quite a bit of money to get from a single sale however we do not sell these expensive cars this often, Our sales logs consist of cars that cost around the 5k mark. I understand where you are coming from however ask any of my employees that are currently at PDM

We cannot just Simply "Grind" PDM, we have recently created a check-in system and seeing that some people could sit at PDM for 4-6 hours and not make a single sale I feel the word "grind" should not even be used in consideration with PDM. It's more of a trait of "luck" that you happen to be there whenever a person comes in to purchase one of these cars. The only real option they have to "grind" is diving which completely defeats the purpose of them applying to a job for the people of legacy and to communicate with the public into isolation under da wata.

Myself have been part of PDM for long over a year and this discussion comes up again and again.

**Comment by JohnWhicked** [comment]
A lot of the more expensive vehicles get financed which lowers the commission a lot but we don't get anything after they buy the vehicle and drive off. For a 100K car on finance an apprentice would get $1875, that just doesn't feel right.

The 10 most common vehicle prices are all lower than 20K, 100K or more is in the 38th place. We don't sell that many expensive cars as you might think we do.

**Comment by Skai97** [comment]
Its like winning the lotto whenever we sell an expensive car lmao, is how rare it is for someone to upfront something at 115k

**Comment by SirPiff** [comment]
Currently, I'm swapping to garbage if sales aren't happening, because otherwise, I'm simply unable just to afford rent even as a Senior Salesman, some change could definitely help.

**Comment by JohnWhicked** [comment]
Plus, if this system would be implemented we could actually do a sale with certain vehicles as we arn't just changing the commission.

**Comment by twooot** [comment]
So, i changed the commission to be based on the upfront price always. I also added the commission price to the end of the string. The prices right now are balanced in a way to have commission on top, so i dont want to lower the prices of the car as they are right now.

We can either leave it as it is now with the changes:
![image](https://i.imgur.com/bS0tA2U.png)

Or we can do something like this:
![image](https://i.imgur.com/UsjsCLw.png)
which includes the commission in the price (it shows the base price and adds the commission ontop before displaying that)

**Comment by MetaHatter** [comment]
What about:
[8] Purchase: $3450 | [9] Finance: $1200 Now + $375/wk for 8 weeks | [E] Fees: $450 (15%)

With newlines (adds a bit of flexibility): 
[8] Purchase: $3450 
[9] Finance: $1200 Now + $375/wk for 8 weeks
[E] Included Fees: $450 (15%)

Finance expectation is clearer with an actual weekly amount
Using "Fees" eliminates the need for an abbreviation
Placing the $ amount after Fees and the % in the parenthesis just feels more consistent.

**Comment by Thebackyarddad** [comment]
I like this option meta. Changing to fees helps a lot. And everyone hates doing math.

**Comment by twooot** [comment]
newlines will look like absolute ass

**Comment by twooot** [comment]
I think this has been resolved
