### ISSUE TITLE
PDM Price Suggestion changes

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2233]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
I'm not sure if this is an asset or framework, this can be moved. 
**Summary:**
Write a summary of what your suggestion is about.

This suggestion comes back to my last one with the commission included changes. Just an updated price list for PDM. The prices of PDM cars have never really been changed and because of this have slowly become very outdated. 
For example, some of the EDM counterparts to the PDM cars are 20-50k cheaper within the server. 
Some cars that are not much to look at cost ridiculous amounts. 

**Reason:**
Why would your suggestion be a good change to the framework?

This would be a good change as it would benefit the server players as most of the vehicles would be priced a lot more fairly. Some of the cars right now cost within the 100k range and you don't get a lot for that price. The supercars cost the same amount of money as the server exclusive 1/x cars that come from the wheel with half to none of the wow factors those cars give off. 

The purpose of this change is to push some of those unique vehicles out into the server with high price tags. Overall lowering the price of PDM vehicles more or less all around to make a lot of them more accessible to the players within Legacy. I'm fully aware that financing is still an option however with the new changes to the repo system a lot of people don't wanna take the risk of financing super expensive cars. The supercars cost 400k flat without the added % of commission on top of that. 

I (PDM owner) and several other people created a price list together based on the performance and look of the vehicles within PDM (Stock vehicles) However we did our best to compile and put what we considered fair prices based on the amount that had sold since PDM opened, how they drove. 

https://docs.google.com/spreadsheets/d/1itFH0j36ahl-_lKhNUEUMgeelOGnYtOUNWk4GlvMOLM/edit?usp=sharing

PDM cars have always been priced Based on Cosmetic and performance but due to the long longevity of PDM, I think this has become a little outdated and just isn't the case anymore. Some of the fastest cars in PDM cost 10k while the worst ones cost upwards of 200k

**Comment by twooot** [comment]
Price list has been updated and the changes we discussed in DMs were implemented aswell
