### ISSUE TITLE
Suggestion: Add "DOC" item seizure functionality

### ISSUE THREAD

**Issue by panpawn** [InZidiuZ/op-framework-issue-tracker#2234]
**Assurance:**
_Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?_
Yes

**Summary:**
_Write a summary of what your suggestion is about._
Essentially, once a suspect is in the cells and cuffed, police would be able to ``/confiscate_items`` or ``/seize_items`` which would remove all items on a suspect before they get sent off to jail. Then, once they're out they either get their items back automatically or get an item "DOC Seized Possessions Bag", and when used would give them all of the items back out of the bag.

Essentially how it'd be roleplayed is that the police take a suspect's items off them and place in in a bag for DOC, and when they get out of jail they get the items and/or the bag back. 

**Reason:**
_Why would your suggestion be a good change to the framework?_
As it stands, police have to manually take items off of suspects and return items that weren't illegal. However, this creates for people to bring stuff in jail that they shouldn't necessarily have (a phone, lockpicks, etc). By having a mechanic where items can easily be removed and then given back to suspects, this helps realism. In addition, it helps alleviate PD wiping their evidence locker and/or losing items that were marked as to be returned.

**Comment by twooot** [comment]
I feel like this can all be done through rp. Yes it would be nice to have it all automated but it feels more realistic for someone to have the items taken off them, since you could then also rp having not found certain items and criminals could secretly bring them into the prison. DOC has access to the /search command afaik

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
