### ISSUE TITLE
Suggestion: Communications jammer 

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#2236]
**Assurance:**
Always ❤️

**Summary:**
Add a communications jammer item into the database. Availability of this item should be scarce. Place one on the ground to intercept and stop all radio signal, phone signal, ems/police tracker and police panic buttons. The range of this item should be medium to low range, with some sort of small cylinder mimicking the staff detection radius being seen by the owner of the jammer. Multiple jammers can be used to set up a large perimeter. 

Perhaps there could be some settings via an interface much like the jukebox, which allows all frequencies to be jammed except a certain typed radio frequency, allows you to check whether you want phone jammed, trackers jammed, and police panic button jammed. 

If radio is jammed (they are not on the right frequency), they hear static when trying to use it (think phasmophobia hunt).

If phone is jammed, they see a white screen with "No signal... ... ..." instead of their home screen, and they cannot be reached by calling them. Texts should still go through, but they'd only be able to view them after getting out of the jammer's radius. Calls would come up as missed calls.

If trackers are jammed, immediately in the radius of the jammer, all trackers are hidden.

If panic buttons are jammed, you can still "send a panic alarm" but nobody else receives it, essentially it is a text that comes up and when you do /panic or X then it says sent panic but nothing actually comes up for anyone since it was intercepted.

Jammers should be able to be picked up to remove their effects or destroyed by shooting at it. 

**Reason:**
Criminals can use this to ensure no backup arrives and they get their job done how they want it. They can communicate themselves by setting the frequency on the jammer.

Police can use this in the same way criminals can use it, even jamming everything except frequency 1, which means there would be a large market for this item. It should not be able to be bought in police stores, and police should find someone out in city to buy it from them in bulk in necessary. They can obviously choose not to jam trackers.

This adds depths and proves intent for a good and well thought out plan if jammers are brought and set up before hand.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
