### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2237]
**Assurance:**
Yes

**Summary:**
With the police panic buttons I believe people within a 5-10m or so radius should be able to hear it off the officers body, as if you press your panic button and you are near someone you theoretically would hear it if it had a returning sound. I think with this the sound should also be changed

**Reason:**
It makes crims more aware that you have pushed your panic button and allows them to be aware that units are responding quickly creating fear for them.

Some sound suggestions I have are below;

https://www.youtube.com/watch?v=4-A3b9ztnDQ - Trim it down to just one bleep, preferably the last as its longer and clearer.

https://www.youtube.com/watch?v=BwvwN_u7PFI

**Comment by nunsia** [comment]
Personally, I do not see the need for this. Any criminal would or should know that if they down a cop, they more or less likely would have called for back up before they went down, or hit their panic button.

**Comment by twooot** [comment]
There is no need for this, the whole point of the panic button is to make it HARDER for criminals to kill cops, making it MORE DIFFICULT. It should require a lot of knowledge and proper planning, accounting for the cops pressing their panic button, so adding a sound would defeat the point
