### ISSUE TITLE
Suggestion: burner phones

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#2238]
**Assurance:**
Always <3

**Summary:**
Add an item which resembles a flip phone and is named "Burner Phone"...

This has functionality purely for texts and calls. Very old phone which cannot be hacked, so most high level criminals use it. 
Upon purchase this phone should be given a unique phone number, shown in the item's description or similar, much like any other phone number so it cannot be distinguished from any regular phone.

Again, this works like a normal phone, minus lots of functionality i.e. being able to go on twitter, etc.. It can receive calls to that number, it can make calls. It can receive texts to that number, it can text.

Upon the deletion of the phone in the inventory (which can be checked when the server is starting up, only for example, this is likely costly to search), the phone number goes back into the pool of those which are unused and any texts and calls sent from that number should be hidden (not deleted, as recipients of this text should still have it) so if someone else gets that number from character creation then they won't see anything.

If I have any more ideas I will edit this, or please just reach out to me on Discord. Matt;)#7784

**Reason:**
Adds to the realism and roleplay of criminal entities. Makes them feel a little safer when sending texts, and yes while someone could use dark chat for the same thing, I feel this is on another level in terms of security, different but still better than a normal phone. Not a necessary addition, but something that could be really cool and add so much depth and mystery to some characters. Can also be used to schedule deals. Honestly, people can figure out what they'd like to use them for the most.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
