### ISSUE TITLE
Quest Cluckin' Bell open Suggestion

### ISSUE THREAD

**Issue by MaxieL99** [InZidiuZ/op-framework-issue-tracker#2239]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
A building for Cluckin' Bell. A place for people in the city to meet up and grab some fried chicken. Served to go or to be enjoyed with their friends inside of Cluckin' Bell.

**Reason:**
Why would your suggestion be a good change to the framework?
A new workplace/place to hang out and a delicious verity of new foods and drinks.

**Comment by coalaura** [comment]
We already have 2 more restaurants planned i think this would be too much competition and would struggle to stay active
