### ISSUE TITLE
Tweeting city district

### ISSUE THREAD

**Issue by thinkclint** [InZidiuZ/op-framework-issue-tracker#224]
**Name:**
ThinkClint (Logen Baker)

**Summary:**
This is just an idea - I don't know the usability of it, but it may help if each tweet had a subtle tag for what server the tweet is from. Could be something as simple as text at the end of the tweet in a light gray.
e.g.
"Hey, we're having a pool party at the PlayBoy Mansion! Come Join us. _(district 3)_"
"(district 3)" would be in a light gray.

**Reason:**
It would help with some of the confusion about what is happening where.

![tweetDistrict-a1](https://user-images.githubusercontent.com/52273598/61348364-f0e05200-a825-11e9-9c6f-5d8426862cc5.jpg)
- example a1 ^

![tweetDistrict-b1](https://user-images.githubusercontent.com/52273598/61348362-f047bb80-a825-11e9-8df1-0336ddba85bf.jpg)

- example b1 ^

![tweetDistrict-c1](https://user-images.githubusercontent.com/52273598/61348363-f047bb80-a825-11e9-95ec-c615fc83039f.jpg)

- example c1 ^

**Comment by Anderzenn** [comment]
This is a great idea and will be put into the Twitter on the phone that we are currently developing.

**Anderzenn**
*OP-FW UI Developer*
