### ISSUE TITLE
Boat Anchors

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2240]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add ability to lock a boat's X/Y position (anchor) with the "L" key

**Reason:**
Why would your suggestion be a good change to the framework?
So boats don't float away and IRL anchors are a thing.

**Comment by TheOneLizard** [comment]
I was thinking of this too!

With the potentially not so far away (?) implementation of SeaDM (SoonTM), I wouldn't recommend "L" tho, as it would still be used to lock the boat.

but maybe "T" could be used?

**Comment by MetaHatter** [comment]
Free standalone script that MAY be helpful
https://forum.cfx.re/t/free-standalone-boat-anchor/4834845

**Comment by twooot** [comment]
this has been done pls dont suggest external scripts i hate external scripts reeeeee
