### ISSUE TITLE
Variable PDM Test Drive deposit

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2241]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Make the Test Drive deposit for required for a PDM vehicle be between 2% of the total cost of the vehicle (minus commission).
Additionally put 0.5% "Administrative Fee" that would not be reimbursed and would go to the salesperson

Example Fees:
$ 25,000 Car  = $500 Deposit and $125 to salesperson ($600 total)
$ 50,000 Car  = $1000 Deposit and $250 to salesperson ($1250 total)
$100,000 Car = $2000 Deposit and $500 to salesperson ($2500 total)
$200,000 Car = $4000 Deposit and $1000 to salesperson ($5000 total)

**Reason:**
Why would your suggestion be a good change to the framework?
- Limit access to top tier cars for Danny's and newer players.
- Add an additional revenue stream for PDM workers and incentivize "getting you behind the wheel of this car"
- RP a sort of "credit worthiness".  There aint no one letting me drive off with a $300k car without a hefty deposit IRL.
- Decrease the likelihood that a supercar will be seen without someone actually owning it.

**Comment by SirPiff** [comment]
Honestly, a great addition to make test drives worth sitting at PDM for.

**Comment by Skai97** [comment]
Test driving has become a common "joke" among PDM workers this would honestly be a good change and would make people be more respectful when testing driving these vehicles or actually bring them back to pdm.

**Comment by twooot** [comment]
I've added a 3rd parameter to the /testdrive command now. It allows you to specify the deposit amount. That way each subdivision can decide on their own how high they want it to be.

![yes](https://raw.twoot.org/HAQuRORu96.png)
