### ISSUE TITLE
Parachute Visability tweak

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2242]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Change parachutes to only be visible when in the clothing store or when equipped.

**Reason:**
Why would your suggestion be a good change to the framework?
- Makes sense from an RP perspective
- Adds a cost to the "Can't see my gun cuz backpack BS"

**Comment by CloudTheWolf** [comment]
Another thought, could it not just be removed from the clothing store, and make the Parachute clothing show it on the player when they use it (Similar to how the Oxygen Tanks work)

**Comment by MetaHatter** [comment]
That's what I am saying.  Clothing store will set your aesthetic for it and it will show that version when physically equipped outside of the store.

**Comment by twooot** [comment]
It already shows the parachute when you equip it, there is no need for it to be hidden when selected in the clothing store, we have it in the clothing store for cosmetic purposes so hiding it would completely defeat the point of having it in the clothing store in the first place

**Comment by CloudTheWolf** [comment]
> It already shows the parachute when you equip it.
In the test server it does not show a parachute when you equip it.
