### ISSUE TITLE
[alpha/health] EMS /stabilize command

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2243]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add /stabilize command for ems that stops the force respawn timer 

**Reason:**
Why would your suggestion be a good change to the framework?
To allow ample time to treat downed players

**Comment by CloudTheWolf** [comment]
This is something we defiantly need as so many Danny's airlift out of situations. 
Would also be good for PD to have this as well to prevent suspects from airlifting.

**Comment by superiorchicken007** [comment]
> This is something we defiantly need as so many Danny's airlift out of situations. Would also be good for PD to have this as well to prevent suspects from airlifting.

From what i'm getting.  This is just to stop the force respawn timer incase the scene goes for longer than an hour.  It wouldn't stop them from airlifting.  But I could be wrong with what Meta is getting at.

**Comment by coalaura** [comment]
Added a /stabilize command that will reset the timer until respawn ("Please wait 5 minutes.......") and the force respawn timer.
