### ISSUE TITLE
Addition Of Map Item To Allow Seeing Street Names On Foot

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2244]
**Assurance:**
YES MATE

**Summary:**
Add an item that you can purchase from the tool store called 'map' which allows us to see the street names while we are not inside of a car. 
Like this:
![image](https://user-images.githubusercontent.com/50828532/161885917-5f3b77f8-1b85-4135-a2c3-4aa0df8593a2.png)

**Reason:**
This would allow my dumb ass to be able to make comms on radio to PD about where I am on foot. My PC is shit and I don't want to add more load to it by adding the street name maps and what not that other people have. It would just be a lot more convienient to know where I am and be able to convey it.

**Comment by nunsia** [comment]
I like this, my forgetful ass has been on GTA for almost 2 years now and I still haven't learned any of the street names :)

**Comment by InZidiuZ** [comment]
This has now been done.
