### ISSUE TITLE
/undercover remove from cop 'amount'

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2245]
**Assurance:**
Yes

**Summary:**
Currently the /undercover command only does one thing, my idea is that /undercover removes you from the active on duty number for robberies so that those people who are going 'undercover' or on 'stakeouts' don't have to screw over the rest of the officers by contibuting to a number.

**Reason:**
The reason why this would be helpful would be because currently FIB or any division that allows for doing undercover work or stakeout work contributes to the total amount of officers on duty, therefore allowing criminals to rob banks or J stores when there is little to no cops around. This means that either 1. The undercover officer has to stop their operation to go attend to one of those robberies or 2. ignore it and the cops are left with too little numbers to respond putting them at a huge disadvantage. This has proven to be a huge issue on the International server and makes it extremely hard to do any type of investigating on the off times of the server.

**Comment by InZidiuZ** [comment]
This has now been done. Whether or not you are undercover is now tracked on the server, and we use that to get the 'current amount of on-duty cops' for bank robberies, stockade robberies, jewelry robberies and store robberies.
