### ISSUE TITLE
New prison activities

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2246]
**Assurance:**
Yes.

**Summary:**
New activities within the prison facility interior, with ability to find items or earn cash.

**Reason:**
At the moment, prison life has picked up again in terms of members of the Dpt of Corrections activity. 
However, in terms of inmates and characters based around prison life, they have two options... run their time down through the outside activities, or roleplay that doesn't benefit them mechanically.

I am suggesting that the jobs outside in the yard remain, and keep them the same that they decrease time of their sentence. But, create some new "jobs" / activities that are found within the interior of the prison. The current interior includes cell blocks, a full equipped kitchen, gymnasium, laundry, etc. See below the list of activities I believe could be added to assist both the roleplay and mechanical benefits to roleplay to help inmates:

_Main Cell Block_
Job 01 - **cleaning**
- In a couple of the cells, there can be an option to clean the cells, which will trigger a "/e clean" emote. It will last up to 30 seconds, and in return, there is a chance they could either get a small amount of cash, or a item which makes sense (rusty blade, lockpicks, drugs, mobile phones, etc).

_Gymnasium_
Job 02 - **working out**
- This can trigger any of the emotes which signify a workout; chin up, press/push up, sit up, etc. Again, it will last up to 30 seconds, and in return, there is a chance they can get a small amount of cash. Finding an item doesn't make sense in this activity. It should also reduce stress.

_Kitchen_
Job 03 - **cleaning dishes**
- This will trigger a "/e clean" emote. It will last up to 30 seconds, and in return, there is a chance they could either get a small amount of cash, or a item which makes sense (rusty blade, glass bottles, etc).

Job 04 - **cooking**
- This will trigger the "/e bbq" emote. It will last up to a minute, and in return, there is a chance they could get a small amount of cash, or a food-based item (burgers, cooked meat, etc). 

_Laundry Room_
Job 05 - **stuck in the washing machine step bro**
- This will trigger a "/e mechanic2" (I think it is) and last a couple of seconds while they're "doing the laundry". In return, there is a chance they could either get a small amount of cash, or a item which makes sense (rusty blade, lockpicks, drugs, mobile phones, etc).

These jobs should not reduce time, but more aim to improve the roleplay. The items they find are contraband. Building roleplay reasons for the members of the Dpt of Corrections to work correctly in ensuring the prison is a safe place. DoC is aiming to build a prison inmate schedule, which would work very well alongside this whole suggestion. It also means if the server reaches a point of allowing "life characters" in prison, they will continuously have a reason to be around and contribute to the RP. Rather than, wait for DoC, interact through verbal means, and leave.

**Comment by coalaura** [comment]
#2482
