### ISSUE TITLE
Grafitti/Tagging Crim Activity

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2247]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
So all and all, this suggestion is another crim activity that people can do for money, which would add some roleplay for southsiders/people who want to do criminal activity but something more petty.

Overall, there would be a few different spots where you could talk to NPCs/spots to "pick up" spray paint cans. Some of these spots could be on Grove Street, Fudge/Amarillo area, The Barrio, and perhaps a neutral spot like a door under Power Street (or in a spot that's will almost never been a gang hangout area). Essentially this would work like a garbage run or an oxy run. You would go to these different spots, and would "spray paint" or create "grafitti". You would get paid per run, nothing too crazy because it's petty work. If I had to aim for an amount, I would say paying more than garbage but less than oxy. Perhaps get paid like $150 per spot, with about 8 different spots totalling around $1200 per full "run". This would also have a percentage to trigger a "suspicious" persons call and if an officer went up to the call, they could use their flashlight and find an "empty spraypaint can" laying on the floor. 

Another possible thing that could go into this, is it could be a good way to open up the world of weapon tints. After these 8 runs (or more so people don't grind spray paint cans) you would receive one spray paint can from the NPC. In turn you could "use" the can and would allow you to select which gun to apply a tint to and which tint. Since the NPC is in multiple areas, it would not allow any group to dominate something that is universal. 

**Reason:**

- Overall, this would add more roleplay for police officers. "Vandalism" is something that isn't really used in the penal code and it could lead investigation as to who is vandalizing the southside. Typically in the real world, we do see a lot of graffiti in places like southsides, under highways, lowkey walls that people don't see. 

- This would add more "petty crime" that isn't too serious in terms of charges. It's good for people who are trying to get into crime, and allows them to have some choice to stand out when choosing their weapon colors.

- Many gangs/criminals would benefit RP wise from tinted guns. This not only would allow gangs to stand out by using their color gun if they choose, but would add roleplay in selling spraypaint cans to other people who don't know where to get them. Overall, this would open up a basic avenue where people can get these products and start spreading them around.

- This would add more roleplay for southsiders who typically don't take high criminal processes and just like to "chill on their block". Would allow groups like Vagos, Ballas, GSF, whoever it is to have something to do while still doing criminal activity.

**Comment by vol5** [comment]
This is an amazing idea. Hats off to you for this suggestion. Its unique, adds value and would create cool experiences. This would get people exploring the city more while diversifying crim content in what I feel is a very dope way. The content loop would be awesome if weapon paint is tied behind it. Even without the weapon spray this would be great stand alone. Best suggestion ive seen a while. Described very well. We 100% could use more awesome implementation with things like this.

**Comment by Enryy** [comment]
^^
