### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Funkallnight** [InZidiuZ/op-framework-issue-tracker#225]
**Reporter:**
discord: SNAQS#8360
steam: FUNK

**Summary:**
i bought the livery for the ubermacht sentinel classic doesnt stay when you store your car

**Steps to Reproduce:**
buy car, buy livery, store car, pull out and livery is gone

**Expected Results:**
livery to be permanent

**Actual Results:**
only lasts until you put it awsay

**Additional Information**
i lost about 6-7k cause i though i was fucking something up and kept buying different liveries once they got erased, but i realized its when you store it. i believe my friend has a clip of my car losing the livery if needed.

**Comment by dreamviz** [comment]
We had this same problem. Owner said it has been fixed and will be live in the next patch :)

**Comment by InZidiuZ** [comment]
As @dreamviz said, this has already been resolved.
