### ISSUE TITLE
[game/inventory] Allow players to give items directly to other player.

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2250]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Rather than having to drop items on the floor for other people to pick up, allow players to give an item to another player.

Then the player presses either Y or N to accept or deny the item. 

**Reason:**
Why would your suggestion be a good change to the framework?

This would improve interactions between players and allow a more immersive experience

**Comment by twooot** [comment]
It would not help with the recent issues of  items going into the ghost inventory since you could have the same or a similar issue here since its related to the inventory script in general. I like the idea tho

**Comment by coalaura** [comment]
done
