### ISSUE TITLE
[alpha/robberies] Bank Robbery Improvements 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2251]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

To improve Bank Robbery RP players should get "Cash" items rather than money that they then have to find a local that will "Launder" it and turn the item into real money. 

Alternatively "Money Laundering" could be gang activity to further enhance Gang/Crim RP.

This could be both a local and a gang thing that has slightly a higher pay-out when a gang does it compared to a local.

The local could be in random locations that change frequently to make it so PD can't camp the local.

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow more advanced RP and make it so Crims have to be a lot more carful with chases and what they do after chases.

**Comment by coalaura** [comment]
I've thought about this a lot and i am really not a fan of cash as an item tbh
