### ISSUE TITLE
Move Compass / Street name HUD Elements to better location

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2252]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Move the Street Name and Compass HUD Elements to the centre screen (Either at the Top or Bottom)

**Reason:**
Why would your suggestion be a good change to the framework?
This would be a more efficient location for these HUD Element  and would mean, for PD, when you are Solo Secondary you don't have to take your eyes off the road to see where you are.

**Comment by ThisIsNotDex** [comment]
I personally would hate it anywhere other than where it is right now, if there was a command to swap between the two, it'd be fine with me. But I do not want mine to move

**Comment by nunsia** [comment]
No thank you, I appreciate where it is now. Also there are different things that can happen that would make it an issue e.g the messages at the bottom of your screen that staff put sometimes and the watermark and metrics at the top centre of the screen. I think it's fine where it is now.

**Comment by twooot** [comment]
I do not believe moving it is a good idea. It encourages you to learn the street names and irl if you wouldn't know the name you would have to look down on your GPS too so it doesn't make sense to have a random floating text in the middle of your fov.
