### ISSUE TITLE
Removal of the clipboard emote for checking server ID's

### ISSUE THREAD

**Issue by xarxesthegreat** [InZidiuZ/op-framework-issue-tracker#2253]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Removal of the /e clipboard part of checking player ID's or "paypal numbers." 

**Reason:**

It's almost always something that causes roleplay to come to an immediate hault as soon as people start pulling clipboards and it ruins the mood. If there's a situation where a report needs to be made it shouldn't ruin on-going roleplay because you have to pull your clipboard out and announce it to everyone around you that you're checking someone's ID. Removal of this would allow for less immersion breaks to occur and for roleplay to continue without it being awkward after.

**Comment by twooot** [comment]
Yes but you should also not be able to check someones server id without anyone around you knowing. There is a reason why we have the clipboard in the first place
