### ISSUE TITLE
Taser Adjustments

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2254]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Slow down taser reload time with one or both of the below methods
- slow down the animation and reload to 10 seconds
- force the reloader to stand still or walk (i.e. block sprint)

Potentially increase the range of the taser for additional balance.

**Reason:**
Why would your suggestion be a good change to the framework?
Tasers are currently very powerful for what they are. Fleeing/chasing on foot is not skill based enough.  Reducing the fire rate of the taser will reduce the use and force a better shot giving people a better chance of escape on foot.

**Comment by nunsia** [comment]
- I think adding a cartridge like someone else has suggested is better than slowing reload time. People would be more mindful of when they are using their taser as cartridges would cost money. 

I do however like the no sprinting thing, but that would cuck PD in foot chases, but I guess that could help with their aim 🤪

**Comment by twooot** [comment]
I like the idea of slowing down the reload time, i'll see what i can do. However i also like the idea of cartridges, but that would require a bit more work to get working.

**Comment by twooot** [comment]
As a first step i reduced the range quite a bit and slowed down the reload time

**Comment by twooot** [comment]
I think this has somewhat been solved and the rest would be #2162
