### ISSUE TITLE
[game/airports] Livery Command For Pilots

### ISSUE THREAD

**Issue by Djmeowzle** [InZidiuZ/op-framework-issue-tracker#2256]
Name:
Djmeowzle#4701 | Thomas Jones :)

Summary:
Let pilots be able to use the /livery command while inside of an airport hanger and plane

Reason:
Most aircraft do have liveries, such as the Seabreeze and Shamal, and making use of all liveries possible would be very helpful to the Aviation RP

**Comment by coalaura** [comment]
Pilots now have access to the /set_livery command (while being the driver of a plane/heli)
