### ISSUE TITLE
Backpack Item Suggestion

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2257]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
To get around the fact that people try to hide larger weapons behind backpack clothing introduce a "Backpack" item that could be purchased from the Tool store.
The initial weight would be 0 but would increase based on the contents (Maybe cap at 100?) and with a limit of 1 backpack being carriable at a time.
If a weapon that usually shows on a persons back is put in the bag, it no longer shows on their back. 
Additionally, the bag could be placed on the floor as a prop to further enhance RP.

Tied in with #2242, the bag style could be selected from a clothing store, but only show when they actually have the item.

**Reason:**
Why would your suggestion be a good change to the framework?

This would allow criminals to actually hide the weapons in backpacks rather than complain when PD see the gun on their back because it clipped out if the bag clothing. 

This would also add a delay to being able to get weapons from the bag as they would first have the get it out of the backpack, which means they would have to be more careful about how when they go to grab the weapon in situations.

They could also drop the bag when escaping from police which would be a more RP Friendly way to hide items, rather than seeing an Arrow showing a ground inventory, and would mean PD have to actively look for the bag if the suspect no longer has it.

Additionally, when trying to escape from cops they could actually drop the bag somewhere

**Comment by TECHSAVYDUDE** [comment]
I feel like this is a solid idea for smaller arms that could be stored easily in a bag. 

Where I see a potential issue is with long guns (which is the crux of this suggestion). So if we're talking about storing long guns and rifles that can "in theory" be broken down into parts (like the classic tommy gun in a violin case); then it should take longer to "pull out/store" them than a simple . 

And maybe some sort of animation that shows them removing and storing weapons.

**Comment by InZidiuZ** [comment]
This has been discussed a lot recently and due to a lot of opposition it will not be done at this time.
