### ISSUE TITLE
Earplugs

### ISSUE THREAD

**Issue by HowieTheBrave** [InZidiuZ/op-framework-issue-tracker#2259]
My suggestion is to add Earplugs that would allow you to click a button or use an item that makes it so you can only hear people within a certain distance, like a reverse from the talking distance basically controlling your hearing radius instead.

Reason for this is because some fucking people just dont know how to not fucking shout 24/7 regardless of them having a 1 on 1 conversation or in a group, meaning sometimes you try to walk off into another corner of the area you're in to have a private conversation with someone but you cant hear them whispering cus some dipshit thinks the entire world needs to hear what they have to say all the time. 

Thank you for your time.

**Comment by vol5** [comment]
> Could potentially also lower SFX when you put them in so you can hear voices better.

Would improve erp with less distraction. Im all for this!

**Comment by coalaura** [comment]
added ear defenders
