### ISSUE TITLE
Multiple Coke Planes

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-issue-tracker#226]
**Name:**
Nate

**Summary:**
Allow for a coke plane to be spawned from Sandy Airfield. There can only be one plane at a time, but this helps with the camping as they won't be able to just sit at one air field and prevent others from running it or robbing them.

In addition, if it's at all possible to reduce the sound of the plane used for coke, or the distance from which it can be heard. It can be heard from half way across the map causing people to run to the air field to rob the person when they land.

**Reason:**
All that to prevent camping drug locations from gangs and have more roleplay/movement.

**Comment by InZidiuZ** [comment]
Hey,

:)

**InZidiuZ**
*OP-FW Developer*
