### ISSUE TITLE
Store Safe Doors

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2260]
**Assurance:**
Yep

**Summary:**
Make it so safe doors in stores open when they have been cracked.

**Reason:**
There is no visual indication whether a safe was actually cracked or not, which makes it difficult for either side to determine what really happened. With the safe door open, it would be perfectly clear that the safe has been cracked.

**Comment by twooot** [comment]
The small safe in stores is a prop so i do not believe it is nicely doable to have it be open
