### ISSUE TITLE
Suggestion: Give "holding up your pistol/one handed weapon" priority/override over certain "emotes".

### ISSUE THREAD

**Issue by mxttx** [InZidiuZ/op-framework-issue-tracker#2262]
**Assurance:**
Always. <3

**Summary:**
The holding up feature (right-click) when using a pistol should take priority or override emotes so that the action is performed without lowering the pistol.

I'm not sure if this can even be done, but if it can, then this could be really pog.

**Reason:**
When holding up your pistol to someone, using any form of in game feature has the devastating affect to sometimes lower the pistol whilst they do that. More often than not, this isn't the outcome that anyone wants (other than the opposing side to the situation which can capitalise on the seconds it takes to lower the pistol, perform the emote, and then raise it again). For example, when in a hostage situation, you have to lower the gun to open the door to a car. 

A real life example follows: a criminal wouldn't lower a pistol to open their car door, never mind taking their eyes off the hostage in fear that the police will capitalise over this. Of course, with two handed weapons, this proposed override should not happen and you should have to lower the gun in order to perform emotes. Furthermore, **this override should not be for all emotes. Flipping a car would require both hands. Common sense should be used to get a full list of things which can be done without lowering the weapon.**

This can be extended to the police using pistols too, and would allow them to do things with "one arm with the pistol raised" whilst performing actions such as opening doors without lowering the pistol. I think this would increase fluidity of roleplay and allow for more complex situations to unfold within roleplay. 

It is my opinion that the split second it takes to lower a gun to open a car door is starting to be "abused" and over-capitalised to shut down roleplay. Abuse is a strong word so I will put it in quotation marks as to not poison the motive of this suggestion.

If there's a way to look at the guns you can shoot whilst in a passenger seat of a vehicle, then that list of guns should be the guns which have this "override". (Not in the passenger seat of a car with sliding doors, I hope this distinction would have been obvious!)

**Comment by coalaura** [comment]
Opening a door to a car or other actions you described are all things that are native in GTA. This wouldn't really be possible to continuously aim your weapon while you get in a car or similar things
