### ISSUE TITLE
Change Self Driving Chip Max Speed from 89MPH > 125MPH

### ISSUE THREAD

**Issue by TheDireMan** [InZidiuZ/op-framework-issue-tracker#2263]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Increasing the Self Driving Chip Max speed from 89MPH to 125MPH or Higher

**Reason:**
So i think it would be good due to the fact that Freeways in the server are a 100MPH and the self driving chip does not even allow 90MPH so i think that allowing the chip to go above and beyond the speed limit is a good idea or allowing the driver to exceed the 125MPH limit would also be a good idea.

**Comment by twooot** [comment]
Does 140mph sound good?

**Comment by TheDireMan** [comment]
Yes it does :)
