### ISSUE TITLE
DOC On Duty

### ISSUE THREAD

**Issue by leahh05** [InZidiuZ/op-framework-issue-tracker#2264]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Make it so those with DOC is not clocked on under 'Law Enforcement' (essentially, so on the MDT it shows DOC separately from PD, even if the individual has both a PD and DOC character. Right now, if a DOC is on duty who also has a SASP character, they're being shown under Law Enforcement). The image attached explains it a lot easier than I have.
![peters](https://user-images.githubusercontent.com/80722313/164551331-e7841cd4-d182-41ab-a89f-6b3867a9b5a0.png)

**Reason:**
Would definitely make it a lot easier to distinguish who is on duty from DOC, and make it easier for prison transports etc.

**Comment by twooot** [comment]
i added a few more variables to the api endpoint, which should allow CYCLON1AN to make it work
