### ISSUE TITLE
Allow EMS to check in people for free

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2265]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Allow EMS to check in an escorted player to bypass the hospital fee.

**Reason:**
Why would your suggestion be a good change to the framework?
Currently there is no (non-rule) incentive for people to call EMS. Checking yourself in is simply faster and easier.  Removing the fee charged by the hospital when an EMS staff member checks you in would incentivize people to actually use EMS without penalizing them more when no one is on duty.  

Note: This should be ONLY for EMS.  No other job (yes, even PD) should get the benefit of removing the charge as it would defeat the purpose.

**Comment by twooot** [comment]
I like the idea, additionally i would even add the feature of when ems check you in you get your hunger and thirst refilled

**Comment by twooot** [comment]
done
