### ISSUE TITLE
Any job that isn't whitelisted having the same pay

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2267]
**Assurance:**
Yes, I can.

**Summary:**
Addition to #2266 number, putting anyone without a whitelisted job onto the same value of pay ($20-25).

**Reason:**
With the suggestion made in #2266, it makes sense that anyone without a whitelisted job to be on the same value of pay, which then gives them free reign to how they make their money. Each Life Invader job gives you different items, therefore using these items to produce an income.

**Comment by DaxterPancake** [comment]
I like this, making the None, None, None job give a base income of $20 is also healthy in terms of new players. It could take them awhile to figure out how to go and get a job so this would allow them to be passively making money while learning how the city works.

This would be a great addition aswell as making the current life invader jobs be availble to everyone.

**Comment by InZidiuZ** [comment]
This has now been done. All the Life Invader jobs now make $20.
