### ISSUE TITLE
New job | POP's Diner

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2268]
**Assurance:**
Hurl yeah.

**Summary:**
Creating a new hospitality based job for POP's Diner.

**Reason:**
As suggestion ([here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/619)) is about the addition of the POP's Diner MLO/interior. It would also be sweet to come along with a job set up (like Bean Machine, Burger Shot, etc). The job/location will have the ability to sell burgers, fries, and milkshakes (new item required).

It was also have a function that if you work there, you can trigger "POP's delivery runs". Very much like Burger Shot and Bean Machine, it will prioritise Blaine County for deliveries, and pay a little less due to the smaller distance.

Twoot mentioned she'd like to see more in the North. Here is a very good suggestion to accommodate that as it will provide positive roleplay to the starving North.

**Comment by InZidiuZ** [comment]
Closing as the interior was rejected for this, which would be required first to create this.
