### ISSUE TITLE
Armor Disappears after leaving city

### ISSUE THREAD

**Issue by greatwhite18** [InZidiuZ/op-framework-issue-tracker#227]
**Reporter:**
iGreatwhite#3018 | https://steamcommunity.com/id/igreatwhite/
**Summary:**
When I smoke 10 joints for armor or apply chest armor. It will disappear if I log out or exit the city.

**Steps to Reproduce:**
1) Smoke 10 joints or buy chest armor
2) Exit the city
3) Come back with no armor.

**Expected Results:**
To have the armor valued preserved on exit of the city.

**Actual Results:**
Lose armor when coming back to the city

## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
https://imgur.com/hZxlmtx

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved, and will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
