### ISSUE TITLE
Different Garage Location/Direction

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#2271]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
At a house one of my characters owns, Mirror Park Boulevard 6, the garage location or pull out location for vehicles is close to a wall, causing larger vehicles such as semi-trucks, etc. to not have enough room to sit properly, causing them to bug out and instantly flip as soon as we pull the vehicles out of our garage.

**Reason:**
Would be able to pull out my vehicles at my garage at my house without them being instantly flipped and most of the time stuck.

[Photo of Issue](https://i.imgur.com/UA1hJMH.jpeg)

**Comment by twooot** [comment]
![https://i.imgur.com/csxl7lS.jpg](https://i.imgur.com/csxl7lS.jpg)
