### ISSUE TITLE
/dutyon for pd/ems

### ISSUE THREAD

**Issue by tbone0tbone** [InZidiuZ/op-framework-issue-tracker#2273]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
if someone head pops in a chase or for ems if they are treating a individual and they come back they have to go back to pd/mt.z to sign back in which can waste time
**Reason:**
Why would your suggestion be a good change to the framework?
i think it would be nice for those people to be able to come back in to the city and go right back to what they are doing without going out of the way to the stations

**Comment by TheEpTic** [comment]
This would be great if it was limited to one time use after reconnecting. Similar to how the reconnect prio detects that you're reconnecting, I'm sure it can be limited to headpop/reconnect situations only.

**Comment by twooot** [comment]
We can't nicely detect if you headpopped or not and just giving it to people i think would cause it to get abused :/

**Comment by twooot** [comment]
Also what if you scuff out and F8 quit to hardnap cause you cant make it back to MRPD or other situations similar like this one. I'm gonna say no on this one for now
