### ISSUE TITLE
Refreshed Emergency Calls

### ISSUE THREAD

**Issue by bigfootgiant** [InZidiuZ/op-framework-issue-tracker#2274]
Is it possible that the 911/Emergency Calls for EMS gets refreshed from the response box in mobile phone after every time the ems character is selected from the character selection screen ?!?

This way the box won't fill up with too many past messages and there won't be a chaos whilst attending the call in a multiple call situation.

**Comment by superiorchicken007** [comment]
You can delete all the old messages as soon as you fly in.  It solves the issue of having a lot of previous messages from the previous day.

**Comment by twooot** [comment]
Yeah, what if you do need to look at old messages etc.
