### ISSUE TITLE
infusion oven for green wounderland

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2276]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Ppl buy X food item from Bean machine, Burger shot or any other whitelisted food place. Bring them to green wounder land where we can infuse then with 1 q weed to ad the effect of a joint

**Reason:**
Increased sales for everyone. And eatables at the same time. Its a win win,

**Comment by coalaura** [comment]
hmmm i'm not too sure about this. I've added brownies now, idk how i would feel about being able to infuse any food
