### ISSUE TITLE
Local delivery for green wounderland

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2278]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary**
Local delivery
 
**Reason:**
I woulde like to hire more ppl and fill our roster but there arent enoghe sales to go arounde and the salery arent highe enoghe to attract them pro paycheck farmers but with local delivery there woulde acually be somthing for us to do then sitting there 5-6 houers a day watching netflix looking whit puppy eyes on every car driveing by

**Comment by twooot** [comment]
Closed in favor of this #2309
