### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HarryGoogleit** [InZidiuZ/op-framework-issue-tracker#2279]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Add a atm inside pdm like inside a locked door where the clothing store is where normal people cant go which does not have ant cool down in it.

**Reason:**
Why would your suggestion be a good change to the framework?
it is very time consuming to put all the Commission in 5k by 5k and takes for ever not really very fun.

**Comment by SirPiff** [comment]
PDM can use bank balance.

You do not need to pull money out to purchase cars.
