### ISSUE TITLE
State security badge and searching

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/op-framework-issue-tracker#2280]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes o did

**Summary:**
I have a suggestion about the State security badge. The work of state security is to protect the mayor and other state employees. If someone takes an appointment to meet the mayor their job is to search that person to make sure that there is no threat. But without any search option state security are not able to do that.
Another suggestion is there is no authorized vehicle and car for state security which is necessary. 
 

**Reason:**
it will improve the rp of state security

**Comment by itachi069** [comment]
Agree state sec should have a Badge also and the ability to search people.

**Comment by twooot** [comment]
Soooooooo, i'm not giving state security /search. I added a new job (Job: Government, Department: State, Position: Security) which has an 80$ paycheck and has the ability to do /frisk which should be sufficient for what you want to do. I'd love to add a badge/id but i would need a logo for it similar to this for example: 
![badge_sasp](https://user-images.githubusercontent.com/32370325/168306336-2a9855f8-b029-4a9f-87e6-337ae0e3db46.png)

**Comment by ekhowan12** [comment]
i will make a badge(logo) and send u

**Comment by twooot** [comment]
![lmao](https://c.tenor.com/OWrqUWuNRHEAAAAC/thumbs-up-internet.gif)

**Comment by GodyFromDiscord** [comment]
I want to add onto this, can we have a badge for State Employees? To show them authenticity and job title, I think something like this, the state seal, would be a good logo for the ID. 
![state_baddge](https://user-images.githubusercontent.com/60844168/168307769-1bf201cf-cd5f-4e5d-8fcb-e1ca9bd2a8c9.png)

**Comment by ekhowan12** [comment]
yes this one looks real....good idea

**Comment by ekhowan12** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/78637016/168308811-4233cda5-f1b9-48cd-ab57-662360f6fcd6.png)
we were using this xD

**Comment by ekhowan12** [comment]
![state badge-01](https://user-images.githubusercontent.com/78637016/168411510-6636f53e-1663-4240-acd2-f5befbd14feb.png)
I've sent you the AI file in your discord  Twoot .

**Comment by ekhowan12** [comment]
![state badge-02-01](https://user-images.githubusercontent.com/78637016/168412264-c270d310-8755-4238-af88-a2293c8c93d5.png)
this is another one.

**Comment by superiorchicken007** [comment]
> I want to add onto this, can we have a badge for State Employees? To show them authenticity and job title, I think something like this, the state seal, would be a good logo for the ID. ![state_baddge](https://user-images.githubusercontent.com/60844168/168307769-1bf201cf-cd5f-4e5d-8fcb-e1ca9bd2a8c9.png)

To be honest I like this one out of the ones submitted. This way it can be used with any state job and with the addition of a state security job it will say state security instead of employee.
