### ISSUE TITLE
Change "Cruise" to "Limiter"

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2281]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Change "Cruise" in the HUD to "Limiter" and add an /sl and/or /limit command(s).

**Reason:**
Why would your suggestion be a good change to the framework?
Currently the HUD is misleading. Cruise control, has access to acceleration to speed up a car to speed and hold it. A Speed Limiter caps your acceleration.  The current functionality mirrors the latter.

**Comment by zyronex** [comment]
Or what about making it a true cruise control? Car speeds up and maintains the speed without having to press down on the gas?

**Comment by ChiknLegPiss** [comment]
> Or what about making it a true cruise control? Car speeds up and maintains the speed without having to press down on the gas?

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/629
