### ISSUE TITLE
Show Minimap when Phone is Out

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2282]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Show the minimap when on foot and the phone is in your hand. Hide it when the phone is pocketed.

**Reason:**
Why would your suggestion be a good change to the framework?
Presumably a phone has a map app to show you where you are.  In lieu of an entirely new phone system, showing the minimap while the phone is out (on foot) would provide this functionality.  It would also make deliveries easier for people.

**Comment by twooot** [comment]
This has been done
