### ISSUE TITLE
[external/gcphone] Automatically add dash when dialing phone number

### ISSUE THREAD

**Issue by zyronex** [InZidiuZ/op-framework-issue-tracker#2285]
**Summary:**
When dialing a phone number, automatically add a dash after the third number, since there isn't a way to add a dash, and it's required for the call to go through.

**Reason:**
Right now you have to save a number in order to call a person. While you have the ability to enter a number, that call won't go through without a dash. Since there are numbers with letters on the dial pad, it would be interesting to be able to register custom numbers that spell something, and then actually call them from memory.

Here are just some business examples:

Burger Shot: BUY-MEAT
Luxury Autos: LUX-AUTO
945 Studios: 945-STUD
Midnight Tuner Shop: CAR-TUNE
Marlow Vineyard: MAR-LOWE

But could also be useful for organizations or individuals:

GET-GUNS
BUY-DRUG

I think it would be a fun opportunity for branding, people calling one another without having to add them as a contact, especially if the number is easy to remember, and nudge people to register more custom numbers.

**Image:**
![166175561-9ba4a27f-07a3-425e-b2b1-bfa23095d66a](https://user-images.githubusercontent.com/97766748/167919881-1c075e4f-5a5b-4e82-94b1-224dc8c7c7af.jpeg)

**Comment by coalaura** [comment]
Closing in favor of #2447
