### ISSUE TITLE
[alpha/tow] Several quality-of-life changes/updates/upgrades to Mosley's Mechanic Workshop

### ISSUE THREAD

**Issue by puppyani** [InZidiuZ/op-framework-issue-tracker#2287]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Several quality-of-life changes/updates/upgrades to Mosley's Mechanic Workshop to make things easier for both workers and clients alike.

1.  New doors in the style of Hayes/MRPD garage doors - The doors when they open are also very slow, or slow to respond to opening.

2. Making it so that locals/local cars can't appear in the building. Currently, locals/cars keep appearing in the building, specifically in the back areas where we are unable to tow anything out.

3.  Move the ATM to a different location away from doors in the building - currently, when staff try to lock the door next to the ATM, we get sucked into using the ATM. 

4. Move the materials computer down to one of the front offices - currently the computer is in the upstairs part in the back. Our main trading floor is out the front part.

5. Add a car wash to the backdoor area for tows/big rigs/or other vehicles that are repaired here.

6. Add outside work bay or two in the back/side fenced part for bigger rigs.

7. The vehicle lift in the front area removed and replaced with second workbench. (the lift doesn't serve any purpose).

**Reason:**
Why would your suggestion be a good change to the framework?

1.  Currently all four main doors get stuck and/or disappear for different people. It's a big issue experienced by everyone and sometimes it causes clients to turn away from the shop. Changing the doors will highly improve part of the service we give at Mosley's!

2. This one will improve awkwardness of finding locals in the staff areas and not being able to do anything or having to report it.

3. Moving the ATM will be highly beneficial to staff as this hinders us when we are working / going out back for materials and coming back in and locking the door behind us. Those few seconds can seem like an eternity to someone who's in for a quick repair.

4. Like the above reasoning, the materials computer is out back and upstairs. Sometimes if we run out of mats we have to go buy them from the computer, moving it down to one of the front computers will improve the quality of working here as well as the service we provide by being prompt.

5/6/7 self explainitory QOL changes for the shop.

**Comment by Detnom** [comment]
All of these changes would definitely improve everyone's experience at Mosley's, and allow us to serve people better. The place has needed some attention for a while now.

**Comment by TheCuppcake** [comment]
This would immensely benefit the quality of my RP and all of the mechanics in mosleys. These changes would be so wonderful, please please pleaseee.

**Comment by Lohtx** [comment]
All of these things would greatly help with my experience at Mosley's as well as being a mechanic there.

**Comment by QuantumSGT** [comment]
As a Ex-Hayes Mechanic, the doors are improved in the sense that we can lock them at Mosleys but yes, the amount of people who come in and end up smashing their cars up simply trying to leave or maybe coming by for a window and ending up with more damage than expected. All because they tried entering the workshop. Outside bays would be amazing too to spread the work load to more than one area but yes, we need the materials purchasing to be on the PCs near the workshop and not a 30 second run away. The store gets busy and it sucks when you need that single piece of rubber but have to travel for it.

**Comment by BazzDarkday** [comment]
Outside bays would be an amazing feature for sure, aswell as the truck wash station. I think the workbench instead of the vehicle lift would serve a really good use of the space that’s there. 
The doors, a fix for those I think would be appreciated by the whole community for sure.

**Comment by Biqley** [comment]
All these ideas are spot on and I am 100% on board with. This would provide an even smoother workflow environment for not only the mechanics but for the customers as well!

**Comment by SummerVincenzo** [comment]
all of these suggestions would be ideal. it would make our service more efficient for the customers and far more smooth and enjoyable for the mechanics working there!

**Comment by zooxoxo** [comment]
All of these suggestions would make the experience of the customers and mechanics immensely greater and have been needed for a while. No one should have to break the doors and hoods on their cars while entering or leaving the workshop. The ATM machine being moved to a slightly different location would clear up a lot of chaos.

**Comment by ayushpandit99** [comment]
I would agree with the changes as currently, the doors at mosleys are working "client-side" so there are issues like its open for some and not open for others also as the front bays are used more in the mosleys adding the material buying computer in the front bay office it self would reduce the time of mechs ..

**Comment by itachi069** [comment]
I agree with all of this suggestions. This would be great for the people of mosley's and customers.

**Comment by twooot** [comment]
Almost all of these are asset issues: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by puppyani** [comment]
> Almost all of these are asset issues: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

I've added these to the issues area BTW.

**Comment by coalaura** [comment]
the outside area is that really needed? considering you have the back area

**Comment by coalaura** [comment]
this is basically all done and the rest are asset issues
