### ISSUE TITLE
Z-Pills Revisited

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2288]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Bring Back Z-Pills 
Remove all drops and cash rewards.  
Disable ammo use
Disable weapon degradation

**Reason:**
Why would your suggestion be a good change to the framework?
This would allow people to freely use Zpills for shooting practice and gun testing without the randomness of materializing loot out of a pill.  Bringing back the game loop without the part that doesn't work for RP.

**Comment by xarxesthegreat** [comment]
I feel like this would just lead to z pills being how acid was back in the day where people that got them on their trash runs just end up dropping them on the ground as they're viewed as "useless"

**Comment by vol5** [comment]
If this is the only way it can come back, I feel we are better off having it vs not having it at all. With that said I would much prefer something similar to how it previously existed still. 

Keep a loot pool and cash but remove gun drops
Disable ammo use
Disable weapon degradation
Keep Rarity of item
Retain value, whether that is adding of items specific only to it

The loot IMO should be retained and the z-pill should act just as another gameplay loop with rewards like it was in the past. Keep it rare, so people are excited to find it and make it worthwhile without guns.

**Comment by InZidiuZ** [comment]
After a lot of discussion in the [discord guild](https://discord.gg/opfw), it's been decided to bring back the Zombie pills like they were before, except that the loot table has been changed slightly and the pills are more rare. An alternative for a 'combat practice' is also being considered.
