### ISSUE TITLE
Aviation - Helipad Additions

### ISSUE THREAD

**Issue by DennisGHOSTDOGE** [InZidiuZ/op-framework-issue-tracker#2289]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes I have

**Summary:**
Write a summary of what your suggestion is about.

Basically, add some helipads, add some access to helipads.

**Reason:**
Why would your suggestion be a good change to the framework?

Currently, helicopters are barely used. Pretty much the only times are private pilots that use them for transportation. Yet this is still not very practical, due to the laws prohibiting landing on buildings (which may have ways to get down from) as well as streets, which obviously have access. We do have a few very good helipads (Sandy Shores, LSIA Helipad 3, Casino Helipad, the one next to Hayes), but many others lack access, and this is a dump of all of the changes. There are also some suggestions for new helipads, at locations that would be frequently visited. Helicopters are also not going to replace cars, since cars are still somewhat a sign of status, because you can upgrade your car and make it look just like you want through spoilers and other body mods. Helicopters however have to be rented at the airport, and can't be upgraded, so people would still be interested in cars for status, as well as storage (that doesn't disappear, or randomly scuff).

**Small Changes:**

1. Maze Bank Tower Helipad
I have landed on this helipad many times, and every single time I was confused, why the elevator, which is even in normal GTA 5, is not here.
![image](https://user-images.githubusercontent.com/69167054/169039948-d7f5b179-563e-4d98-8aa5-d55295f57a71.png)
![image](https://user-images.githubusercontent.com/69167054/169039984-948ae7a6-5eb7-429b-abb4-678892c9b1a3.png)

2. Burgershot Helipad
I have landed on this helipad only once, since there is no way down / back up. Suggesting a ladder over here:
![image](https://user-images.githubusercontent.com/69167054/169040126-86d24a5f-649b-4580-bd80-4631a1779357.png)
![image](https://user-images.githubusercontent.com/69167054/169040144-01fb9e56-a120-4683-81be-4c3aa503a824.png)

3. Casino
I know I called this helipad great, yet you have to go a VERY long way down from the helipad. Therefore I'd suggest an elevator over here:
![image](https://user-images.githubusercontent.com/69167054/169047457-35302906-f760-400b-8b91-32c739b692c1.png)
![image](https://user-images.githubusercontent.com/69167054/169047504-ba3e490e-f113-4944-bbab-120cfe7c0d61.png)

**New Helipads:**

This section will probably be fairly long, since I believe most of the businesses, especially if they do not have a helipad near them, should have a helipad.

1. 2nd Gear
I know what you might be thinking: "But wait, aren't they in between some helipads and the airport?" Well, although that might be true, both are far enough away, that I wouldn't really consider  them close. Therefore I would love to see a helipad on this store. 
![image](https://user-images.githubusercontent.com/69167054/169042383-98b61fc9-04ec-4c19-9542-a399a49a1df3.png)
![image](https://user-images.githubusercontent.com/69167054/169042476-83c8a49e-b42b-40b3-8811-cabe722634ed.png)
What I would love to see is a helipad up on the roof, and then a ladder down, on the side of the building.

2. Mosleys
This shop being in the middle of the city, with no other landing possibilities anywhere close, and this also being a popular hangout spot, a helipad would be very practical. It would also mean workers could be airlifted to and from work by friends / commercial pilots.
![image](https://user-images.githubusercontent.com/69167054/169043606-39eecbca-149d-46e1-b04a-9484e149e8bd.png)
![image](https://user-images.githubusercontent.com/69167054/169043666-30e4bb44-e466-45c6-8dbf-3ed2a314da97.png)
Here the ladders already exist, so just putting a helipad on this roof would already be enough.

3. Midnight
Another shop that has no quick access by air. Another reason why this is here, is because the owner just recently got his helicopter license as well.
![image](https://user-images.githubusercontent.com/69167054/169044507-8a2f2e2a-aa46-4328-88db-6f3327293896.png)
![image](https://user-images.githubusercontent.com/69167054/169044561-8e1666c3-0ead-4e19-8012-4e803b75c4bd.png)
This spot is reachable by ladders already, so no need for them, just a helipad missing.

4. Luxury Autos
This is one more shop that gets accessed a lot, and many people hang out at. Currently the roof is not accessible.
![image](https://user-images.githubusercontent.com/69167054/169045599-6e751d9a-f394-4637-ab10-36e3d6919038.png)
![image](https://user-images.githubusercontent.com/69167054/169045645-7bd20b8b-65ac-4eef-859e-104f24e7e48b.png)
I'd suggest an elevator back here, and then a helipad on the roof.

5. Bean Machine
Another spot where people like to meet. Also, employees might just want to fly around or something.
![image](https://user-images.githubusercontent.com/69167054/169046558-6ba4197a-f1ee-4122-9cb0-9d2963a4bd40.png)
![image](https://user-images.githubusercontent.com/69167054/169046591-f63815a2-60c6-4dce-9f9e-a04000f1ece7.png)
The roof is accessible, the helipad just needs to be added.

This list is of course not entirely complete, and it is intended that you, if you have an idea for a new helipad, or a change for an existing one, you would respond saying what you want to change.

Have a nice day.

**Comment by twooot** [comment]
I've added all the helipads. Regarding the Burgershot ladder or adding all the entirely new helipads, that's something for the asset GitHub: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
