### ISSUE TITLE
slot issue

### ISSUE THREAD

**Issue by hughed** [InZidiuZ/op-framework-issue-tracker#229]
unable to create new character in slot 1 if i have deleted the previous character,(does not save the progress)

have slot 1 filled with a character, delete character. Create new one play for a bit buy some stuff and exit city. The character you have just created does not save

**Comment by SteezyRen** [comment]
For starters, there was a template provided for creating a bug report. Don't just delete the entire template to post as you please. This makes finding your issue a lot harder to fix.

I suggest closing this and redoing it but actually following the template provided.

**Comment by hughed** [comment]
no
