### ISSUE TITLE
HairTie

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2291]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
Right if Any player has new hairstyles and if he uses any hat it comes out. So my suggestion was if there should be an in-game item if players use it your hairstyle changes into any specific hairstyle which doesn't glitch out and when players use it back then it goes back to their old hairstyle.

**Reason:**
Why would your suggestion be a good change to the framework?
it will allow players to go for a new hairstyle that will not glitch out on hats.

**Comment by nunsia** [comment]
I like this idea, so many hairstyles on women are cute, but my character (Sia) always wears a bucket hat, but is forced to have ugly hair because it's the only one that works with the hat.

**Comment by ravicant** [comment]
Just icon Suggestion 
![download](https://user-images.githubusercontent.com/49905280/181825972-b797a9c1-8d97-47be-96d8-46d60d7891fc.png)

**Comment by twooot** [comment]
Closing in favor of #2453
