### ISSUE TITLE
Suggestion - Improvements for DOJ

### ISSUE THREAD

**Issue by Lunabelle666** [InZidiuZ/op-framework-issue-tracker#2292]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
I wanted to suggest a couple of things to help improve quality of life for those in DOJ.

1. Locks on the inner doors of the courthouse that would be lockable by members of DOJ. This would not include the front doors that allow citizens the ability to purchase their ID's but instead the doors to the courtroom itself and the judge's quarters. This is because nearly every court case that we have at the courthouse turns to chaos or a shoot out, or random people show up and RDM and it creates a break in the flow of RP. Being able to lock the doors would help in those situations.

2. A DOJ phone line, similar to the Burgershot line or the state line. This would be incredibly helpful as it is often difficult to contact a lawyer or member of DOJ and the main way PD and civilians reach out is via twitter. This would allow for people to get quick responses from members of DOJ as not all people watch twitter close enough to catch when they are requested.

3. DOJ identification cards, this would be similar to PD/EMS badges. They would be purchasable by members of DOJ to show that they are members. This will make things easier for PD when DOJ go there to deal with different matters, as many officers don't know where to check the roster for DOJ members. They could have Department of justice written on them as well as their position and name. The DA's department could even have a different symbol on it if possible to show they are prosecution.

**Reason:**
I think this would improve quality of life for DOJ members. People in DOJ work really hard to try and provide great RP for all those around and I think that these would be great tools in which to provide better RP for everyone involved.

**Comment by twooot** [comment]
Courthouse doors done

**Comment by Milan345** [comment]
+1, also adding ingame documents/paperwork will increase activity as well as quality of life for the DOJ members. 
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2094#issue-1077404166

**Comment by Lunabelle666** [comment]
I am so grateful for the courthouse doors being done. In the time since it's been done, we have been able to use the courthouse a lot more as it's now safer for everyone. 

I still think a DOJ phone line would be incredible as we have a lot of members of the public texting the state line to try and contact lawyers within the city. So having a line of contact would be amazing.

I can also provide pictures of possible badge pictures if needed for bar licensed individuals. As we have this for PD, EMS, State security and hunting. It would be amazing as for the accomplishment of going through law school and passing the bar exam, they can have a card that shows they are bar licensed, possibly with their position being, lawyer, ADA, DA, Judge, etc.

**Comment by DaxterPancake** [comment]
I believe a DOJ phoneline would be extremely benificial to the Lawyer/Judge RP in the server. 

Being able to easily contact a judge, lawyers or paralegal would not only be extremely benificial to police but also civilians and criminals alike. DOJ roleplay is always going to be needed in the city. Potentially in the future it could even remove the need for rp-lawyer-appointments for the international server and leave all the of the talking, scheduling and what not to phonecalls and texts in the city.

**Comment by coalaura** [comment]
closed in favor of #2591
