### ISSUE TITLE
Changes to Aviation Licenses

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2293]
**Assurance:**
Always.

**Summary:**

1. Add aviation license "Commercial"
    - Move all _Blimps_ from "Management" to "Commercial"
    - Move _Miljet_ from "Management" to "Commercial"
    - Move _Luxor Deluxe_ from "Management" to "Commercial"
    - Move _Swift Deluxe_ from "Management" to "Commercial"
    - Move _Volatus_ from "Certified Flight Instructor" to "Commercial"

2. Add aviation license "Utility"
    - Move _Skylift_ from "Management" to "Utility"

3. Expand "Performance" license 
    - Move _Pyro_ from "Management" to "Performance"
    - Move _Besra_ from "Management" to "Performance"

4. Some very small changes:
    - Rename _Weazel News Big Snitch_ back to _Maverick_
    - Rename _SuperVolito_ to _Weazel News Big Snitch_

**Reason:**

1. With the in RP introduced "Commercial" license, I'd like to give an extra to those pilots who invest in that opportunity and use some "Management" aircraft that otherwise would barely ever get used. Hence, for those that go this extra route of RP, a nice additional trinket to have exclusive aircraft available.

2. With this additional license containing the Skylift only, I'd be able to hand this license to high ranked EMS and PD with A1 certs after short instructions, in order for them to expand on their RP. EMS (specifically the Fire&Rescue department) could be using this aircraft to recover vehicles that may have been involved in accidents on mountainsides, PD could be finding use of it to be able to recover vehicles that have purposely been drowned in the sea to avoid possession charges.
Singling out this license would allow emergency services to have access to this very useful aircraft without them having to go through the process getting a private license if not wanted. Aviation RP would still be improved as specific instructors would be able to hand out the license after sufficient training.

3. These two aircraft would be a perfect fit for the Performance license and don't necessarily need to be wasted in the cramped Management license, adding a few more options to those pilots get this far.

4. Simple name change given that the SuperVolito is actually the helicopter with the Weazel News livery and the camera, unlike the Maverick.

**Comment by twooot** [comment]
This has been done

**Comment by TheOneLizard** [comment]
> This has been done

sorry to bring this up again, but we are still missing the blimps in the commercial license. Could you take care of that too? :)

**Comment by twooot** [comment]
I got rid of them cause i dont really want blimps
