### ISSUE TITLE
EMS Store Additions/Changes

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/op-framework-issue-tracker#2294]
**Assurance:**
Yes

**Summary:**
In short, we as EMS need a few more things added to the EMS store to help and improve our roleplay overall. As it stands, we are missing a few crucial things in our store that we have to go out of our way to get on a regular basis.

**Body Armor**
**Fire Extinguishers**
**Mannequins**
**Flashlights**

**Reason:**
1. We have a TECC unit that is more focused on providing medical roleplay in a shooting environment/on standby during PD shootouts. During these shootouts, there is a strong possibility that EMS could get shot/held up/involved if need be. Having armor if something does happen should provide us the beneficial roleplay we need
Standing around at any hospital tends to bring newer people to the hospital and most of them end up shooting/punching/hurting us EMS. If one EMS is on duty and goes down due to newer people shooting the one EMS on duty, it’s kind of a bad thing. There isn’t a way to stop it, but bodyarmor would prevent this situation from happening. Responding to some calls in specific areas also gets violent. Locals/Mountain lions do take a toll on our body armor/health and is a pain to get more. Cars also like to run over people as well.

2. With the further development of the Fire Department, fire extinguisher items would make for good roleplay instead of having to find one on a wall or drive all the way down to a tool store. It would make all of our lives easier.

3. We could use mannequins as well to further our medical roleplay instead of having an EMS “play dead” or injured in order to get training done.

4. Flashlights are the final item we need. With spotlights not being properly functional, we have to use flashlights in order to see in the dark.

**Comment by twooot** [comment]
> Body Armor
Not happening. I've already discussed this many times prior

> Fire Extinguishers
> Mannequins
> Flashlights
All done
