### ISSUE TITLE
Suggestion - Crypto Mining for In Server currency

### ISSUE THREAD

**Issue by mrbuckels** [InZidiuZ/op-framework-issue-tracker#2296]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes 

**Summary:**
Create the ability for player to mine or hack an in server crypto currency. This currency would exist only within the server and have no link of affiliation with any real world crypto. Create devices that a player could purchase using legal means through a store, these items should be fairly expensive as they have the potential to generate significant profits. Once a player has the in server currency they could trade between other players to purchase more black market items. This currency could also be turned into cash using some type of fence that would take a percentage of the crypto. It would be nice to see the "fence" location move periodically making it more difficult to turn the crypto into money that would be useable in the city for day to day life. Another addition to this could be the ability to find a usb stick or other small device that could be hacked possibly using the rasberry, it would be single use and if successful in the hacking the return would be a very small amount of the in city crypto. This would give players the chance to find crypto without having to purchase an expensive item to gain it. Down the road it might be interesting to see this in city currency be used as a way to access additional criminal activities that might be developed such as buying an item needed for a casino heist hopefully making it more difficult to prepare for and something to strive in attaining.

**Reason:**
Why would your suggestion be a good change to the framework? This would add a new type of black market roleplay to the server and add an intersting bit to the economy.

**Comment by coalaura** [comment]
closing this in favor of #3107
