### ISSUE TITLE
Weazel News Camera

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2297]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
When utilizing the camera for the Weazel News Job allow it to automatically go to cinematic mode where it takes all notifications off your screen.

**Reason:**
I believe this would be a great change for the citizens that want to RP as news reporters and when they are recording the news I believe having a notification pop up on screen during it would cause for a bad recording.

**Comment by coalaura** [comment]
done
