### ISSUE TITLE
Suggestion - More Uses for the Map item / Location to buy the map

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2298]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
1) A suggestion for the location to buy the map could be somewhere on the Pier or another tourist location.

2) As well as showing the current street name, players could save marker locations (Middle Click) then give that map to another player to share locations. (Eg to share a location to do gun deals)

**Reason:**
This would add more uses to the Map Item, as well as allow players to share locations. Would also mean if PD find a marked map they could setup sting operations which opens the door for more RP.

**Comment by twooot** [comment]
Done. You can now use the map item to set the location on it and if there is already one set it will mark it on your gps. To remove a location from a map again you can use /clear_map.

As always, have fun trying to find the store :)
