### ISSUE TITLE
Suggestion - Add CAD Terminal HUD element to Emergency Vehicles 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2299]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
In PD Vehicles there is a computer, that could add a HUD Element that shows Dispatch permanently (Can be shown/hidden)
This could look something like this 

![Example](https://i.imgur.com/s2Wv7ch.png)

For Multiple calls for the same type at the same location it could add a counter if they happen in quick succession

Eg

| Code  | Description |
| ------------- | ------------- |
| 10-90 | Alta Bank |
| 911 | New 911 Call |
| 10-71 | Shots Fired - Route 68 x3 |

**Reason:**
Why would your suggestion be a good change to the framework?
This would add a more RP Friendly dispatch HUD and allow you to see dispatch calls more clearly while driving.

**Comment by twooot** [comment]
Feel like this would massively clog up your screen ngl

**Comment by twooot** [comment]
closed cause old, not needed and would clog up your ui
