### ISSUE TITLE
Casino Night Club

### ISSUE THREAD

**Issue by FB-Toobtv22** [InZidiuZ/op-framework-issue-tracker#2302]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
*Yes*

**Summary:**
Write a summary of what your suggestion is about.
*My name is Zachary Goff Russell in and out of the city CID 66802. I am currently the new owner of previously "Casino Royale" now "Casino Night Club," in mirror park off Mirror Park Blvd. The suggestions I have are Locks on the Main door as well as the office door, Storage location behind the bar as well as a safe in the office. I would also like to have a marker added to the map.*

**Reason:**
Why would your suggestion be a good change to the framework?
*This would be a good change to the framework due to the face that it would make working for the employees so much easier, as well as easier to store alcohol in the office for employees to access when needed. The marker will make it easier for new people in the city to find the locations as well as the adding/removing props suggestion I submitted before this! Thank you for your time FB-Toob_tv22#0327*

**Comment by vol5** [comment]
You put all the info in the title. That info needs to go where assurance, summary and reason is now. You should not have all the info in the title.

**Comment by MetaHatter** [comment]
Reformat for readability 

Assurance: 
Yes 

Summary: 
My name is Zachary Goff Russell in and out of the city CID 66802. I am currently the new owner of previously "Casino Royale" now "Casino Night Club," in mirror park off Mirror Park Blvd. The suggestions I have are Locks on the Main door as well as the office door, Storage location behind the bar as well as a safe in the office. I would also like to have a marker added to the map. 

Reason: 
This would be a good change to the framework due to the face that it would make working for the employees so much easier, as well as easier to store alcohol in the office for employees to access when needed. The marker will make it easier for new people in the city to find the locations as well as the adding/removing props suggestion I submitted before this! Thank you for your time 

FB-Toob_tv22#0327

**Comment by MetaHatter** [comment]
One additional note: I always thought this was supposed to be an illegal underground casino.  Which is why no map marker/advertisements.  Is this no longer the case? (in any regional server)

**Comment by FB-Toobtv22** [comment]
As far as I am concerned this is no longer the case as the city is making gambling illegal. I have to have a gambling license in order to own the casino, therefore can be made in to a legitimate business.  Sent from Mail for Windows From: MetaHatterSent: Friday, May 20, 2022 4:55 PMTo: InZidiuZ/op-framework-issue-trackerCc: FB-Toobtv22; AuthorSubject: Re: [InZidiuZ/op-framework-issue-tracker] Assurance: Yes Summary: My name is Zachary Goff Russell in and out of the city CID 66802. I am currently the new owner of previously "Casino Royale" now "Casino Night Club," in mirror park off Mirror Park Blvd. The suggestions I have are Locks on the Main door as well as the office door, Storage location behind the bar as well as a safe in the office. I would also like to have a marker added to the map. Reason: This would be a good change to the framework due to the face that it would make working for the employees so much easier, as well as easier to store alcohol in the office for employees to access when needed. The marker will make it easier for new people in the city to find the locations as well as the adding/removing props suggestion I submitted before this! Thank you for your time FB-Toob_tv22#0327 (Issue #2302) One additional note: I always thought this was supposed to be an illegal underground casino. Which is why no map marker/advertisements. Is this no longer the case? (in any regional server)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by twooot** [comment]
Lord have mercy with your formatting my friend

**Comment by coalaura** [comment]
I dont think a marker should be added since the idea was it to be an underground casino spot. Interior is cool but since you dont play the server anymore and its currently unused i'm gonna close this
