### ISSUE TITLE
Truckers Job Bug report

### ISSUE THREAD

**Issue by HyperNemesisX** [InZidiuZ/op-framework-issue-tracker#2303]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/HyperNemesisX/

**Summary:**
Write a short summary of what you are experiencing.
There's An Issue With Truckers Job, It Says Issues Occurred : Error : Not In Job. I Relogged To Check If Its Bugged From My Side, But Still It Showed The Same Error, Than I Thought I Should Change The Job To Unemployed Than Change It Back To Truckers Job From Life Invader, Just To Check If Its Working Or Not, But Still It Showed The Same Error.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Select any offer listed on truckers job panel, Deliver The Transporting Unit Will Reproduce The Same Issue

**Expected Results:**
What are the expected results?
It Should Have Given The Payload Amount Mentioned on offer listed in truckers job panel.

**Actual Results:**
What are the actual results?
It Showing error Issues Occurred : Error : Not in Job, while I am already on Truckers job as u can see on screenshots..

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://i.imgur.com/TucRy7v.png

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://i.imgur.com/K5zWndP.png

**Server:**
What server/community did this issue occur in?
Legacy India

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
Closing since this is quite old, please reopen if its still an issue
