### ISSUE TITLE
Recently We are facing Lot of Frame Drops For some reason.

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2304]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/ravicant1/
**Summary:**
Write a short summary of what you are experiencing.
When You spend some time in server You face a lot frame drop
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
When You spend like 30 min in server it happen suddenly 
**Expected Results:**
What are the expected results?
You face a lot FPS Drop
**Actual Results:**
What are the actual results?
You face a lot FPS Drop
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://img.ravicant.in/u/NzVrYpm.jpg
**Game Resolution:**
What is your game's resolution?
1920 X 1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://img.ravicant.in/u/0hb5Q88.png
**Server:**
What server/community did this issue occur in?
Legacy Roleplay India
**Notes:**
For anything else noteworthy.
No

**Comment by ChiknLegPiss** [comment]
Yup facing framedrops frequently in Legacy Bangladesh too, screen freezes for a second or two. No audio. Also gets fixed after 15 mins or so.

**Comment by 8017RAZ** [comment]
> **Assurance:** Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes **Player Identification:** What is your steam profile? https://steamcommunity.com/id/ravicant1/ **Summary:** Write a short summary of what you are experiencing. When You spend some time in server You face a lot frame drop **Steps to Reproduce:** Include what steps that are needed in order to reproduce this issue. When You spend like 30 min in server it happen suddenly **Expected Results:** What are the expected results? You face a lot FPS Drop **Actual Results:** What are the actual results? You face a lot FPS Drop
> 
> ## Additional Information
> **Screenshots:** If suitable, include some screenshots. https://img.ravicant.in/u/NzVrYpm.jpg **Game Resolution:** What is your game's resolution? 1920 X 1080 **Player Data:** Write '/info' whilst in-game and provide a screenshot of the information you are prompted. https://img.ravicant.in/u/0hb5Q88.png **Server:** What server/community did this issue occur in? Legacy Roleplay India **Notes:** For anything else noteworthy. No

i think it happens for some specified areas

**Comment by twooot** [comment]
i believe this was fixed
