### ISSUE TITLE
Convenient Inventory Slot QOL Adjustment

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2305]
Assurance: Yes

Summary: 
This would be a nice QOL Adjustment nothing more. The inventory UI is a 5x5 block system. 
When you enter the inventory. It will only display 5x4 of the inventory slots with the 4th row being partially cut off and the 5th row not visible. Removing the UI cutoff to make the 5th row visible and the scroll bar for the main character inventory would be much more convenient. The player should be able to see all the items in their inventory and not only a portion of it.

Reason:

- Gives players access to full character inventory.
- Removes unnecessary barriers to see what you have
- Less UI lag cause no scrolling
- Makes cop's lives easier

https://cdn.discordapp.com/attachments/964218681204834318/978563353104494622/Screenshot_2022-05-24_034046.png

**Comment by twooot** [comment]
The inventory size is dependant on your resolution

Example with my resolution i only see 3 rows :)
https://i.twoot.org/Cufo7/WOBabuPI59.png
