### ISSUE TITLE
Improvements to Drugs.

### ISSUE THREAD

**Issue by imdiavolo** [InZidiuZ/op-framework-issue-tracker#2307]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes

**Summary:**
Write a summary of what your suggestion is about.
Changes to a lot of the current drugs/processes to be more interactive and relevant in the current state of the server. These changes will also aim to make all the different zones have some sort of relevancy as well when it comes to what goes down in them in relation of drugs.

**Reason:**
Why would your suggestion be a good change to the framework?

= Oxy :
As it stands, oxy is in an okay shape. How the process itself works has been relatively the same for a while and it does fine for what it aims to do. Yes, the concept of selling oxy to locals to get oxy yourself sort of makes no sense but no change is needed when it comes to pure functionality. The one change I would suggest is as follows : 
- Move the door back to/if not closer to Paleto. Reasoning behind this suggestion is for that zone to have something going on in it. It went from having maybe too much to nothing, which leaves it relatively hollow when it comes to what goes on drug wise except for the occasional drug drop offs which IMO isn't enough for how large the area is. It also just makes sense from a roleplay perspective judging on who controls it and been controlling the process for years.

= Cocaine :
Cocaine importing itself is probably as good as it can get system wise. It's interactive, exciting and does a good job at what it aims to do. The location itself is not awful although it gets metagamed a lot, that's not something that should be in mind or if relevancy to a system. The changes I would suggest in relation of cocaine is as follow :
- Cocaine processing should not be in the middle of no where. Yes, it's cool to have it be a random isolated area concept wise, But that coolness turns into a chore and redundancy very fast. Cocaine processing IMO should be in a location that's in the middle of the main city. Somewhere that's easily accessible to everyone if you know it's there, but also hidden from the passing by. there is hundreds of possible interiors and locations where this can work and honestly, the specifics don't matter that much. Cocaine processing is a lot of roleplay potential if done right, and the aim of this change is to take advantage of that. It needs to be in an area where a gang can decide that it's what they want to control and have the ability to do so with ease. Be near a buyable block or at least not too far off one ect. 
- Cocaine selling : Maybe just make the area slightly bigger. Like the full street and across the street as well. Nothing major here, just feels very awkward to be constrained to a tiny portion of a single street and even more awkward when there's 7 people there going through the same thing with you. Would be nice to have but nothing that's really really really necessary. 

= Weed :
Weed processing is back, good. That is a major thing that people wanted and it does do a lot of encouraging people to interact with that system and also maybe attract interest to those who might wanna control it. I feel like weed also went through a lot of changes that might or might not have been that good for it. Here's what I think would maybe work better :
- Honestly, going back to the old system we had is probably for the best. Weed should be a entry drug and something that's easily accessible but the profit matches it. Some version of a weed field would be nice, maybe the same way shrooms are now but just weed instead. It shouldn't be strictly getting weed seeds (which is tied to ONE LEGAL JOB), planting them at home and selling the weed for a lot of money. It should be that you get it pretty easily, make a couple hundred dollars off it once you figure out how to process it and have it be something you can do to get yourself up and start making money. If you wanna grow some at your home, that can be an extra option but not the only option. Overall, just change weed to be easier access but less profit and have it truly be an entry drug for the upcoming criminals.

= Acid :
Acid is one of those drugs that are sort of just there. Yes, some people do sell it and it truly is probably the entry drug right now but It does feel like more could be done with it. I know that a lot of people just have acid laying around, probably expired as they never bothered to sell it or use it. The acquisition is whatever honestly, probably as best as it can be. But here's some suggestions to maybe enhance it and make it more interesting :
- While acquisition is fine as it stands, I don't think it should be as straight forward as "find acid > sell to local > make money". I think adding a couple steps here and there and increasing the profit on it would make it more interesting. Maybe when you find the item "Acid", you only find one pill and it's not sellable. In order to sell it, you need to continue finding more and collecting four of the said item which like I stated is only ONE PILL now. When you collect 4 pills, you go to X area (Can be a pharmacy door, some underground packaging basement ect) where you would need to "pack" or "bag" said pills into a bundle of 4 pills that's now sellable to locals. This new bundle would sell for a good price (Maybe x4 of what Acid currently sells for). And for fun, maybe have it that if someone uses the whole bundle, they trip for x4 the time and a small % to just be downed from it.
All of this would do a couple things : Make the whole thing from point A to Z a little more involved. Maybe create some more interactions with other people/gangs/crims when it comes to trying to pack the pills. Making it worth the effort to go out of your way to sell acid as the price will match the effort you put in. Maybe even the option to people selling it for cheaper prices for people to sell to locals for profit.

= Shrooms :
Shrooms had their hype for a bit when they were selling for a ridiculous amount then died out right after those prices got nerfed. Shrooms are can be made interesting as they got a lot of potential. What I suggest shrooms to be is as follows : 
- How you obtain shrooms right now is fine, It can be fun to go on a shroom hunting trip. I'm not sure on the exact functionality of it as it stands on the live servers but I picture it being something like this : Shrooms can grow in a lot of mountains/hills, they're just relatively less frequent and harder to find. Maybe even have it so people can combine hunting and collecting mushrooms by having animals spawn in those mountains and hills. Maybe have it so that if more people are around, more shrooms spawn so it's both beneficial to go alone or as a group. The numbers balancing will take a while to perfect but with constant changes it will get there eventually. Adding a little system similar to what I suggested above for acid where if you wanna sell to locals, you first need to collect X amount of shrooms (let's say 3), wait for them to ripe up before being able to "bag them". Maybe add an item called "Plastic bag" that you can find in dumpsters frequently that you need before bagging the shrooms. Whole thing can be as simple as " Have 3 ripe shrooms + 1 Plastic bag > go to X area > bag shrooms > sell 'bagged shrooms' to locals ". Obviously , when you sell a bag of shrooms, it sells for a good price to make going through the whole process worth it.
- Having shrooms actually be usable would be nice to enhance the RP of the drug rather than it just being strictly for money making.

= Meth :
It should not be tied to a job, It should not be controlled by a singular person. Not sure about the functionality of it so I can't comment on that. All I can say is that it makes sense for it to be in Sandy. hopefully it will be something that you can smoke and have a random functionality like giving you half your armor slowly over a period of time + reducing stress but can't be smoked in cars. Honestly, anything that would make it not be only useful to sell to locals would be nice. IMO, how I see meth working is " Get the ingredients for it > Go to X area that has a meth lab > Make the meth and bag it there (Maybe use the plastic bag item I suggested as well) > Sell to locals/people. "
Like I said, I don't really know how it works right now because It's being funneled to a singular person who isn't even around, and that's really what should change before good feedback around meth can come. I also think it should just be another whitelisted drug that a gang can control. 

I think having 3 Non-whitelisted drugs ( Shrooms, Weed, Acid ) and 3 Whitelisted drugs ( Oxy, Cocaine, Meth ) is probably a good way to have things be balanced out. The goal of all of this is to hopefully make every drug be relevant and just give criminals some more things to do/control and interact with. Hopefully this will allow newer gangs to form with goals in their mind that are not too out of the limits of what's possible. I know that there's probably a lot of flaws in everything that I suggested but I do think that It's a good start. Hopefully us as a community can continue to suggest things to improve systems more and more. 
 Thank you for coming to my TED-TALK.

**Comment by microwavablepizza** [comment]
I do agree, I think that weed and acid should be more accessible than through one job. In addition to meth, it shouldn't be controlled by one person. It'll open up more gateways for more groups to have a presence in the city and a startup for crims. Good ted talk!

**Comment by imdiavolo** [comment]
> I do agree, I think that weed and acid should be more accessible than through one job. In addition to meth, it shouldn't be controlled by one person. It'll open up more gateways for more groups to have a presence in the city and a startup for crims. Good ted talk!

For weed, I do agree which is reflected in the suggestion I made about bringing back some form of weed field.
For Acid, There's a secondary method that's pretty much accessible to everyone so it's not only just one job. That's to my knowledge at least unless something has changed.

**Comment by Lohtx** [comment]
I love all these ideas and it would be so great for mine and other roleplay. 
I do really think that coke selling locations should expand and be in maybe another spot just to stretch it out. 
As someone who has to fight off people who join the server and watch a video on how to fly the coke plane and know its locations, I do think that it should be moved to another location. 
I do also think that shrooms should be sold in more than one place as well, although people don't sell them as much because of the time that it takes for them to be ready to sell. It would be cool if you could bag them up and sell them.

**Comment by coalaura** [comment]
a lot of this has changed and is potentially no longer relevant, closing
