### ISSUE TITLE
Scrapping Guns

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2308]
Assurance: Yes

Summary:
Guns should feed back into the economy when DECAYED FULLY, rather than just be a complete waste of an item and space once decayed. Since the server is going in the direction of "crafting" it would only make sense to add guns to the list of scrapable items. This surely would get more people moving around guns in general and would create some solid RP scenarios with the purchasing of broken firearms. 

[Scale material output by weight of the item]

Gun breakdown to Scrap by weight:
> 10lb = 2 scrap
> 15lb = 3 scrap, 1 aluminum
> 20lb = 4 scrap, 2 aluminum, 1 steel
> 40lb = 8 scrap, 4 aluminum, 2 steel

Location: Somewhere in Paleto to get people traveling up north more.

Secondary Location: Rodger Scrapyard in the city at the lathe.

Reasons:

- Immediate value add for Realtors
- Provides material boost for mechanics
- Turns items that are complete waste into something
- Creates some return on what you spent on guns
- Provides an additional layer to the crafting economy overall
- Adds immediate value to trash guns and any current existing gun

**Comment by HowieTheBrave** [comment]
Big thumbs up, defo needs to be a thing instead of just throwing guns on the floor

**Comment by twooot** [comment]
This has already been done
