### ISSUE TITLE
Requesting for add Delivery van,delivery option,weed seeds in the store at GREEN WONDERLAND Shop.

### ISSUE THREAD

**Issue by RHINO08** [InZidiuZ/op-framework-issue-tracker#2309]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes I have

**Summary:**
Write a summary of what your suggestion is about.

we need a delivery van at the shop garage, add a delivery option, and weed seeds in the store at green wonderland.

**Reason:**
Why would your suggestion be a good change to the framework?

Yeah, I think it's a good change to the framework. After adding Vape at the green wonderland store it makes a good RP environment. On the other hand, we can sell weeds in this shop and it's being famous day by day. So basically now we need a van for delivery like other jobs burger shot and bean machine. We also need weed seeds at the shop because it's a legal business if we get this we can grow weed at our home by using weed seeds. if there is a delivery option in the shop many players can get a new thing on the server like Burger shot and bean machine.

**Comment by FaLLeN1121** [comment]
need this

**Comment by PiuPiu535** [comment]
i need this badllyyyyy pleaceeeeeeeeeeeeeeeeeeeeeeeee

**Comment by TBxRuSheR** [comment]
need this

**Comment by ekhowan12** [comment]
I don't think it is logical . As people use this kinda shop to buy vape weed personally ,because these places are like some kinda hangout place to the user. Apart from this maximum you can put a bike as there is a VAN already exist in the PDM for green wonderland

**Comment by ravicant** [comment]
I think There Should Be Away where You can multiply weed seed like crossbreed or some shit if possible like rust

**Comment by ghostfreak070** [comment]
about Green wonderlands van if it already exists in the PDM then we don't need it and about the delivery job NO WAAYYYYYYYYYYYYY.You don't do delivery and grind like Burgershot on Green Wonderland

**Comment by 8017RAZ** [comment]
No need because already 2 delivery jobs are there

**Comment by Puucko4090** [comment]
As the current owner of green wounderland i say this, 3 ppl are currently activly working there we got 6 salemen spots 2 manager spots 1 owner spot as sales are progresivly riseing atm since packegin are back and the vapes, having a full crew whit current sales are not sustainable living whit local delivery how ever i coulde fill the roster cus there be enoughe income/work for everyone.As for delivery van/car pdm has no sutch vehicle we currently use pony smoke on the water van because its the closest we got but an actuall livery for us woulde be nice

**Comment by coalaura** [comment]
Delivery vans are not needed. If you really wish to have some there are some purchasable in PDM: https://pdm.wiese2.org/#9c07db65a8258aea1550268ce18d9041
