### ISSUE TITLE
Status bar cancel

### ISSUE THREAD

**Issue by TRParagon** [InZidiuZ/op-framework-issue-tracker#231]
**Reporter:**
Paragon#9700
https://steamcommunity.com/id/reseth96

**Summary:**
Most of the status bars are now able to be canceled such as the ATM retrieval and other things.

**Steps to Reproduce:**
Any situation that requires a status bar is potentially able to be canceled.

**Expected Results:**
Cuts down on time about doing anything involving status bars that don't have an end goal other than to just wait.

**Actual Results:**
n/a

## Additional Information

**Screenshots:**
n/a

**Game Resolution:**
1920x1080

**Player Data:**
Out of the game rn so can't get it.

**Notes:**
Nothing of notes.

**Comment by InZidiuZ** [comment]
What button is used to cancel? 🤔

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*

**Comment by TRParagon** [comment]
Sorry the cancel button is backspace or right click I think right click shouldn't be binded to it
