### ISSUE TITLE
Mechanic shops & Vin scratching 

### ISSUE THREAD

**Issue by CowboyRoyWalker** [InZidiuZ/op-framework-issue-tracker#2313]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yES 
**Summary:**
Write a summary of what your suggestion is about.

This is github is over bringing new ideas and possibly changes to some of the mechanic shops. With midnight having NOS i feel Mechanic shops should get a little love too. 
Each mechanic shop would get something that could bring more economy and excitment to each shop while also bringing in a lot of business and possibly reasons for mechanics to stay around a little longer. 

One of the reasons could be Vin scratching a tool to use if you don't want a certain car to trace back to you, but potential trace back to another name or even come back to no one at all. With Vin scratching individuals would have to go to a mechanic shop who is designated the only ones to give it. In which the charge of scratching the vin would vary from what kind of vehicle it is. Only PDM vehicles would be able to have the VIN scratched with potentially EDM cars in the future after some time. Prices can range from 10k to 100k depending again on the vehicle. For the Mechanic shops I think should have them it should be Mosleys and Hayes the ability to vin scratch. With that being said when an individual is paid they must give at least half to the business owner and they can pocket the other half, so it still helps the business with events. 

SOL and Lost mechanic shops should have the ability to only scratch Bike vins while also the ability to install certain parts on the bikes. Examples could be giving the Bike a boost in speed or breaking to even faster fixing of said bikes. I feel with a MC they would know how to fix bikes faster then a typical mechanic, but also maybe Bikers can have exclusive repair kits that are FOR said bikes. Normal civilains can buy them off these MCs mechanic shops, but it's around 150-200 for said bike repair kits. 

Another thing for Vin scratches is they could be a totally seperate thing and be held down by a group that does them for a certain price like the mechanic shops would. One of the spots for the scratching can be Pacific Bluffs due to the mechanic shop in the building.  The gang doing it would have to keep logs of each vin scratch, and submit it to someone. For each vin scratch they do they can pocket all the money or give it out to the group all together. 

For cops when they look a vin up instead of it saying the vin it would just say SCRATCHED. 

**Reason:**
Why would your suggestion be a good change to the framework?

I feel vin scratching would bring a new dynamic to the criminal world and the cop world. Cops who believe they're getting closed to catching a criminal and find the vin is scratched out, so they have to search more for evidence and what vehicles the person has. Scratching can also benefit criminals when robbing banks, J-Stores, or even runs when they have high class drugs in their vehicles. Vinscratching would also help push for people to buy more PDM cars or even tuner cars as they are the only cars that can be vin scratched.

**Comment by CloudTheWolf** [comment]
So 2 things on this.

First you wouldn't really go to a licenced mechanic for this, as... well it's Illegal. This could be something SOL and Lost did from a Gang perspective but not something they would do from their shop (Maybe they have to get an item that can do it)


And second, this would leave out 2nd Gear, Harmony and the Mirror Park Mechanic Shop from benefiting from it. (Bearing in mind some sub divisions may not have a Lost, SOL Mosley's or Hayes Open)

**Comment by coalaura** [comment]
vin scratching has been solved by boosting becoming a thing
