### ISSUE TITLE
Police Microphone Bug

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2315]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
https://steamcommunity.com/id/alfeysprankles

**Summary:**
I was trying to put a microphone bug at Burger Shot for an FIB situation and was getting the following error. We tried to place them at various spots and on people and got the error every time. These worked a few months ago, so not really sure what happened.

**Steps to Reproduce:**
- Buy Microphone Bug
- Try to put bug on the ground
- Get Error

**Expected Results:**
- Be able to successfully place the bug

**Actual Results:**
- Error that is shown in the screenshots

## Additional Information

**Screenshots:**
![FiveM_b2545_GTAProcess_B1rG4Hko1E](https://user-images.githubusercontent.com/47933692/171563051-cccb607c-5d3c-4ec9-bb80-c5e0e8d7a712.png)

**Server:**
International Server

**Notes:**
None

**Comment by twooot** [comment]
Has been fixed

**Comment by Ai80-8** [comment]
Delete it all
