### ISSUE TITLE
Drug Sale Recall:

### ISSUE THREAD

**Issue by CruzClementina** [InZidiuZ/op-framework-issue-tracker#2318]
**Assurance:**
Yes.

**Summary:**
What if drugs could be sold anywhere within the state?
(maybe not everywhere but providing more areas in which things can be sold), with the thought process of higher risk = higher reward/payout. 
That way when PD is given a **66 call** and its treated as the call should be, which is as a suspicious person call, and reduce the whole "oh it's a 66 on Vinewood they have to be selling coke" 
 "It's on the pier at 7 am they have to be selling weed" 
 PD rolls up and starts drug testing... where is the RP?

This change would make it so it forces further RP for all parties. 

Revisiting the thought with the thought process of higher risk = higher reward/payout... selling in the city, where there's more PD presence = higher payout, but if they want to be rats and sell in like Sandy or Paleto where there's little to no PD presence they get a lower payout. To encourage sales within the city but also reduce the knowledge of DrugX is only sold here so every time PD responds to a 66 they treat it like a drug sale when it shouldn't. 🤔

**Reason:**
Just better RP all around

**Comment by coalaura** [comment]
I don't like the idea of being able to sell srugs anywhere. All the drug sell spots are very well balanced between risk and reward
