### ISSUE TITLE
BurgerShot Personal Locker for Employees or Owner/Manager

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2319]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Addition of shared locker for Boss & Manager or Personal locker in the locker room
![image](https://user-images.githubusercontent.com/29286961/172047078-31d3dd66-7548-425b-b808-83f8954def31.png)
![image](https://user-images.githubusercontent.com/29286961/172876739-0fd3e671-e757-43c0-89d6-7af20da72942.png)

**Reason:**
Why would your suggestion be a good change to the framework?
As when we come at burgershot to work we need space in our pockets so if there is a locker it would be easy at least the owners should have a locker there.

**Comment by twooot** [comment]
Burgershot has no need for a locker
