### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#232]
**Name:**
Lars. #9309

**Summary:**
Hey dudes, i was just wondering. When selling oxy the NPC sometimes runs away or attack you. When you kill the NPC it will say '' Press E to pick up Oxy ''.
Is it normal that that picked up oxy doesnt go into your inventory.

**Comment by InZidiuZ** [comment]
Hey,

Yes, it just adds it in memory, letting you sell one more oxy. You receive the item by chance when selling oxy to the buyers.

**InZidiuZ**
*OP-FW Developer*
