### ISSUE TITLE
Housing | Open Door QOL

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2320]
Assurance: Yes

Summary:
Change the Open-door key from H to G. 

Reasons:

- Current door open system is already scuffed rn.

- There is no reason for the d/p clothing menu to show up when letting players in the door.

https://cdn.discordapp.com/attachments/876565140902924298/983346395132080148/Screenshot_2022-06-06_081112.png

**Comment by twooot** [comment]
done
