### ISSUE TITLE
Local truck heists

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2321]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
hijacking of  local semi trucks and deliver them to random places arounde los santos for a reward(like the trucking places)

**Reason:**
A fun activety for everyone, gets ppl moveing arounde more moste ppl sit on there butts all day waiting for drug prime or house cleaning times. We need a daytime low tier crime thing to do i think this coulde be a good compliment to chop cars cus lets face it moste ppl arent built to chop cars xD

**Comment by vol5** [comment]
This would be cool.

**Comment by Mugdha57** [comment]
this will be nice .
cz thn we will have something similar like chop shop.

**Comment by coalaura** [comment]
I feel like this is basically just a copy paste of the bank truck tho

**Comment by coalaura** [comment]
its like a mix of chop, bank trucks and boosting
