### ISSUE TITLE
Bean Machine Delivery Price Increase

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2322]
Request you to please increase the Delivery Price for Sandy & Paleto side delivery. 

Now if we going for paleto side delivery we get 450 to 480, 
city price is well and good , for paleto & sandy slightly increase, if we get 550 to 600, it will be great.

Thank You

**Comment by twooot** [comment]
I believe the current payout if very good and does not need an increase
