### ISSUE TITLE
BurgerShot parking

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2323]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a personal garage for only BurgerShot Employee's as it's becomes really hard to park anywhere near BurgerShot as we have lots of employees who have their own cars and it's difficult to park anywhere as people just come and starts lockpicking to still the cars.

**Reason:**
Why would your suggestion be a good change to the framework?
If there is parking it would help in FPS as there will be few cars around near BurgerShot Employee can park their car in garage so there is more space for civilians to park vehicle.

You can create a garage at this locations.
![FiveM_b2545_GTAProcess_CNYJLGqej6](https://user-images.githubusercontent.com/29286961/172876297-ba47aea5-b752-47dc-96fd-3ac3b7eaefd6.jpg)
![FiveM_b2545_GTAProcess_RVBHya4JX8](https://user-images.githubusercontent.com/29286961/172876301-14034513-b4a5-4045-a6c4-e336cd32725b.jpg)

**Comment by MetaHatter** [comment]
Just a couple things.

- Cars will likely not be spawnable/storable in that location... Too many people park there during the normal course of the day.  (It would be like when too many cars are too close to a public garage) Either cars would get poofed or we would end up with cars spawning under other cars. Do you have another location in mind?
- I personally dislike car poofing parking lots near businesses.  Car theft is a thing even IRL and the framework has car alarms to address it.  It's asking to remove a potential player interaction.

**Comment by KaiEagle** [comment]
> Just a couple things.
> 
> * Cars will likely not be spawnable/storable in that location... Too many people park there during the normal course of the day.  (It would be like when too many cars are too close to a public garage) Either cars would get poofed or we would end up with cars spawning under other cars. Do you have another location in mind?
> * I personally dislike car poofing parking lots near businesses.  Car theft is a thing even IRL and the framework has car alarms to address it.  It's asking to remove a potential player interaction.

Adding a public garage here is also a good option
![FiveM_b2545_GTAProcess_H74hrlPcdo](https://user-images.githubusercontent.com/29286961/173014609-a34496d8-1e4c-4012-845d-28273aae5638.jpg)
![FiveM_b2545_GTAProcess_wJCTfR7hEd](https://user-images.githubusercontent.com/29286961/173014595-578da5f4-d856-4fc2-85d6-a51f297e4a4e.jpg)

**Comment by KaiEagle** [comment]
> * I personally dislike car poofing parking lots near businesses.  Car theft is a thing even IRL and the framework has car alarms to address it.  It's asking to remove a potential player interaction.
about this point I do agree.

**Comment by twooot** [comment]
i can look into a public garage near burgershot
