### ISSUE TITLE
Workable Cash Registry

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2324]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Workable cash registry, the cash registry show below can be used to charge customer like when you press E the registry will open or the employee needs to do "/regis" or "/registry" to open the nearest registry then add the amount the customer to charge with then the customer can do "/pay" or "/payment" to open the nearest registry the amount payed by the customer will directly go in the desired restaurant account.  
![image](https://user-images.githubusercontent.com/29286961/173013370-83d54b06-799a-470e-867f-ec0a8102e5c0.png)

**Reason:**
Why would your suggestion be a good change to the framework?
This would change the payment system of all the restaurant and it's way simpler and ez (keep aside the coding part :P)

**Comment by coalaura** [comment]
this is basically /bill now
