### ISSUE TITLE
Flares = Loot

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2325]
**Revised**

Assurance: Yes

Summary:
Change flares to act similarly to the way they do in GTA Online. But instead with only a 1-3% chance to drop a care package that has sick loot inside. Then the crate disappears after being opened.

[Fun loot examples]

> High-tier guns
> Armor
> Weather Spells
> Z-pill
> Lottery Tickets
> Grenades
> etc

Reasons:

- Fun

**Comment by twooot** [comment]
uhm.......lootboxes?

**Comment by vol5** [comment]
> uhm.......lootboxes?

Would be nutty. Then again im a loot fiend so...

**Comment by SirPiff** [comment]
this man lives for gambling, I love it.

**Comment by twooot** [comment]
I dont like the lootbox idea, since it is an rp server in the end. What exactly do you mean with you "want flares to work like in gta online"
