### ISSUE TITLE
Phone Use in Car QOL Update

### ISSUE THREAD

**Issue by mawest11** [InZidiuZ/op-framework-issue-tracker#2326]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**

When on a phone call while driving a vehicle and someone hangs up on you, your phone remains open (if on mouse control) and you cannot control the vehicle. This update would fully close out your phone so you do not lose any control of the vehicle.

**Reason:**
Why would your suggestion be a good change to the framework?

This would be a nice QOL update so that you are not caught off guard when someone hangs up on you. This will eliminate any unanticipated losses of control of the vehicle and crashes, especially serious ones on the highway.

**Comment by twooot** [comment]
With mouse control activated you use your mouse to navigate your phone, prohibiting all controls from going through, if you dont want this you can turn off mouse control and use your keyboard to control your phone, allowing you to keep driving
