### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2327]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes!

**Player Identification:**
What is your steam profile?
CloudTheWolf (steam:110000103fea0db)

**Summary:**
Write a short summary of what you are experiencing.
When Buying "PD Empty Evidence Bag" from the PD store, the player is instead given the item "Empty Evidence Bag"

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
* Have a PD Character
* Go to buy a "PD Empty Evidence Bag" from the Armoury 

**Expected Results:**
What are the expected results?
Player should get a "PD Empty Evidence Bag"

**Actual Results:**
What are the actual results?
Player gets an "Empty Evidence Bag"

## Additional Information
N/A

**Screenshots:**
If suitable, include some screenshots.
![ss1](https://i.imgur.com/b0Ah9V9.png)

**Game Resolution:**
What is your game's resolution?
1920 x 1080 

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![Player Info](https://i.imgur.com/7mOJKqw.png)

**Server:**
What server/community did this issue occur in?
c3s1

**Notes:**
For anything else noteworthy.
N/A

**Comment by tbone0tbone** [comment]
Civilians can pick up evidence bags and have been able to pick them up for a while I wouldn’t say this is a bug just need to have the right rp for them to need to have them or use them but I’m not a dev so they can decide whether this is a big or not

**Comment by superiorchicken007** [comment]
This has been in effect for a little bit.  Certain items will come as normal items that anyone can pick up.  This was also made for EMS as well for first aid kits for example where EMS can buy from the store but allow anyone to use them.

**Comment by twooot** [comment]
kekw this is a feature not a bug
