### ISSUE TITLE
Suggestion - Add street name for camera in PD heli

### ISSUE THREAD

**Issue by Sharpeye0420** [InZidiuZ/op-framework-issue-tracker#2328]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

This is to suggest addition of street names or maybe map visible In airone camera. 

**Reason:**
Why would your suggestion be a good change to the framework?

It becomes very hard to give calls on radio as co pilot can not see street name while using camera and chasing suspect. ![image](https://user-images.githubusercontent.com/77230476/173422038-df782e97-5b0e-4d12-b25c-7cfc0194e2bb.png) 
So it will be nice if we can get something like 
This.

**Comment by TheOneLizard** [comment]
maybe we could just keep the minimap active while in the heli camera? I guess that would mitigate the problem too

**Comment by InZidiuZ** [comment]
This has now been done.
