### ISSUE TITLE
Lock Green Wonderland by default

### ISSUE THREAD

**Issue by Sharpeye0420** [InZidiuZ/op-framework-issue-tracker#2329]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about. 

Change default lock status to **LOCKED** for green wonderland shop

**Reason:**
Why would your suggestion be a good change to the framework?

Currently after every server re-start shop locks get unlocked and player can access store in absence of staff of shop too. So it will be great if default status be at locked rather than unlocked.

**Comment by twooot** [comment]
they cant actually use the store tho, no?
