### ISSUE TITLE
Coquette Blackfin repair

### ISSUE THREAD

**Issue by Shifty123** [InZidiuZ/op-framework-issue-tracker#233]
**Reporter:**
Shifty | Shifty#4167

**Summary:**
The Coquette blackfin comes out of the garage in 2 ways, With the metal top on or off. I have spent around 10-20 glass trying to repair all the windows and when they are all repaired, it removes the metal top and i cannot repair the front windshield. When i take it back out to fix, all of the windows i just repaired are now re-broken.

**Steps to Reproduce:**
Break all the windows on a blackfin and then try repairing the window
**Expected Results:**
You would repair all of the windows

**Actual Results:**
You repair some of the windows only for the metal roof to be removed on one of the last windows, destroying all the windows you fixed

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 3022 - Job Data: Journalist, Weazel news, Reporter

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

I've tested all the available roof-related natives, "vehicle mod" native and livery natives, but, none of them seem to return different values, meaning I won't be able to know whether the roof is on, or not. Don't really have any way to resolve this issue, currently, so will remove this car from the dealership. Closing this though, as there's not much more I can do.

**InZidiuZ**
*OP-FW Developer*
