### ISSUE TITLE
Giving baseballs more purpose

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2330]
Assurance: Yes

Summary:
Make baseballs sellable (random location), give them physics like snowballs (ability to knock people over), and allow them to be retrieved off the ground.

>Random Sell location ($50-$150)
>Knock People over with a headshot
>Props_manage retrieval from ground

Reasons:

I'm taking a look at some items in specific and suggesting utility for them if they do not really have one. Also, the intent being giving them raw transmutable value rather than just being dead drops.

**Comment by twooot** [comment]
As said in #2355 baseballs are now able to be picked up, i can look into having them damage other players (possibly making them like snowballs) but i don't really think a selling spot is a good idea
