### ISSUE TITLE
 Rrequire ATM & TV Banner in the bean machine 

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2333]
Request you to place a ATM in bean machine.

2 TV is hanging on bean machine, need to place bean machine menu card into tv screen .. 

if you do this it will help us a lot.

provide the size of tv screen , so that i can provide bean machine menu card as per your given size.

this menu card is valid only legacy india
reference Photo Link
https://cdn.discordapp.com/attachments/840178806726721606/986886573968740383/unknown.png
https://cdn.discordapp.com/attachments/840178806726721606/986886603366608926/Screenshot_165.png

**Comment by twooot** [comment]
Wrong github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
