### ISSUE TITLE
Bean Machine Shop Counter Shift 

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2334]
Request you to please shift the bean Machine Counter to Kitchen ..
Or do one thing hide the deafult price, so that customer can see the item not the price. 

refrence image link:
https://cdn.discordapp.com/attachments/777722318159347712/984310723826040842/20220609001340_1.jpg

customer can access from here.

please look into this matter.

thank you

**Comment by HellRaiser5** [comment]
any update regarding this issue .. sir please update this .. its very very imp .. lots of people come and go to the counter and opened it.... they are just arguing price is low .. u charged higher bla bla .. and typically they dont understand what the rp they are doing in bean machine. the whole rp is fucked up .. please shift the counter into the kitchen. packing place is good dont need to change.

**Comment by twooot** [comment]
You can now no longer access stores at all if you dont have the job
