### ISSUE TITLE
Establish business bank account for Videogeddon

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/op-framework-issue-tracker#2335]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I would like to establish a Company account for Videogeddon Arcade. Would to like to call it "Rogue Holdings".

**Reason:**
Why would your suggestion be a good change to the framework?
The purpose of the business account is so the business can function as a front for an IC gang. It would allow for additional criminal RP (Money Laundering) as well as help establish a war chest of sorts so we can separate personal finances from gang finances.

**Comment by twooot** [comment]
If you want to make a company you have to /apply in city not make it a feature request, or am i misunderstanding something?

**Comment by RustyWaters07** [comment]
Unless I'm misunderstanding terminology, i already have a business. In
order to have a separate account for that business, do i need to /apply as
well in city?

**Comment by twooot** [comment]
I'm not fairly certain i understand what you need. /apply is the in city way to get a company registered with state, which would also have its own "bank account" i'm pretty sure. If you are talking about a shared account like PDm or the tuner shop, this will not be added
