### ISSUE TITLE
/dispatch [message] for PD

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#2336]
Name:
Meer Mugdha#2444

Summary:
There should be a option so that police officers can put manual dispatch call, for a example, there is a chase going on with huge radio traffic and an officer needs to give call in the radio at the same time.

So in my opinion, if we add a option like.. [/911 (Message)] it will be so helpful. and also it will reduce radio traffics a lot.

Reason:
It will reduce a huge radio traffic calls. (extra calls, which might not necessary on that particular situation)

**Comment by ekhowan12** [comment]
it should be included if possible.

**Comment by twooot** [comment]
I feel like this would get abused

**Comment by Mugdha57** [comment]
> I feel like this would get abused

make it like when you use this dispatch call, there will be a ped animation.
and while down/cuffed you can't use this dispatch call.

trust me it will be so helpful.  and if someone does abuse this it will be considered as powergaming
