### ISSUE TITLE
Ability to fill paper bags

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2337]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
When you press G at the Package Meal it opens a inventory of paper bag in which you can place the eatable things you desire.
![FiveM_b2545_GTAProcess_j6S0sDQiTC](https://user-images.githubusercontent.com/29286961/174437865-2df431a4-f9fe-4a29-9bc5-e31df608f038.png)

**Reason:**
Why would your suggestion be a good change to the framework?
This would save inventory space a lot and would help burgershot have many types of meal in the menu.

**Comment by twooot** [comment]
This has been done
