### ISSUE TITLE
Bike blows up when taking out of Garage

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#234]
**Reporter:**
Allen#8921
https://steamcommunity.com/profiles/76561198260006559

**Summary:**
Whenever I take my bike(s) out of Garage A, it goes on fire then it blows up and it doesn't give me time to repair it etc.

**Steps to Reproduce:**
Any steps that you can do to make bikes not blow up when it's taken out of a Garage.

**Expected Results:**
I expect the bike not to blow up after taking it out of a Garage

**Actual Results:**
Bike blows up when I take it out of Garage

## Additional Information

**Screenshots:**
N/A

**Game Resolution:**
1920x1080

**Player Data:**
ID: 136 - PDM Apprentice

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
