### ISSUE TITLE
Sperate bank account for buisness expenses 2nd Gear

### ISSUE THREAD

**Issue by MillerManPlays** [InZidiuZ/op-framework-issue-tracker#2340]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I would like a seperate bank acount for my buisness.

**Reason:**
Why would your suggestion be a good change to the framework?
I think this would be a good idea becasue as a mechanic shop we need lots of mats so this is a way to like buy a block that employees can pay for as an extra storage for materials, The seperate account would be so i dont have to mix my inome and what they give for the houses for example.

**Comment by twooot** [comment]
You can /apply to create your own company, comanies are not added though dev work
