### ISSUE TITLE
Burgershot Food Warmer

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2341]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add a warmer in the burgershot where the food placed inside decay 2x slower just like when you place something in trunk.
You can place the warmer here
![FiveM_b2545_GTAProcess_L0ESzFgur0](https://user-images.githubusercontent.com/29286961/174658126-f8846a51-6b64-47a8-b37e-fad7a71f6d5b.png)

**Reason:**
Why would your suggestion be a good change to the framework?
There is one more suggestion which would prove this warmer a lot beneficial.

**Comment by twooot** [comment]
The food lasts a whole day, i dont think we really need this
