### ISSUE TITLE
Shroom Collection Balance

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2343]
Assurance: Yes

Summary:
Increase the quantity of shrooms people can collect not by increasing the overall locations that they spawn but by cluster quantity.

> 1. Increase cluster range to (1-5) previously (1-3)
> 2. Significantly increase the probability that shrooms can cluster

It's much more enjoyable to find a larger quantity of shrooms in a cluster vs more of them to find overall. Players would be stoked to see a 4-cluster or a 5-cluster vs just one lousy shroom every 100ft. A change like this would also give shroom collection a more realistic representation of how they grow IRL.

---------------------------------------------------------------------------------------------------------------------------------------------------

Reason: Due to the nerf of price and quantity near-simultaneously a while back, I feel that shrooms have lost their fun as a drug and overall enjoyment as an activity. The price nerf is somewhat okay, but the quantity number decreasing by 50% is way too heavy IMO. Speaking from personal experience I've thoroughly enjoyed the activity of collecting shrooms. The above suggestion would "fix the enjoyment factor" IMO. Increasing the chance that they can cluster and a slight bump in potential cluster number. The dopamine a player receives with this change would be 3x than before, along with it being way more balanced than when it was introduced. Even now the risk-to-reward factor is shit so any slight buff of this nature would be amazing.

This IMO is the best way to make this activity better without increasing the raw sale price.

**Comment by ShaquilleOatmeal007** [comment]
I couldnt agree more. Since the nerf and decrease in quantity, shroom selling has become very unpopular and I barely see anyone doing it. IMO I think this would increase the more people who pick and sell shrooms and revive this part of the drug system.

**Comment by mawest11** [comment]
I totally agree as well. When I find 2 or more shrooms clustered together I get that dopamine rush too. Increasing the clusters and adjusting the quantity numbers a bit will still provide a solid balance with the nerfed prices. Great suggestion!

**Comment by InZidiuZ** [comment]
Some balancing changes based on this suggestion has now been made. Feel free to reach out directly to me in DMs for feedback on the changes as I don't want to make this discussion too public.
