### ISSUE TITLE
Check In Button with a Timer

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/op-framework-issue-tracker#2345]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes I did.

**Summary:**
When standing around the Check In at Mount Zonah, sometimes people accidentally check in by pressing "E". A suggested change would be to make it a 3-5 second timer instead to make sure you actually intend to check in. So by holding "E" for 3-5 seconds you confirm you want to check in.

**Reason:**
Sometimes when there's a 911 or PD call and people, especially EMS, check in it takes away from the time to respond as they are stuck in the bed for quite a while.

**Comment by twooot** [comment]
Sounds reasonable

**Comment by twooot** [comment]
done
