### ISSUE TITLE
Add a convenience fee

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#2346]
**Assurance:**
Yes

**Summary:**
Make convenience stores more convenient than reasonable. 

Currently right now if you need something, food for example. You can easily go there and fill up same with water and other things. I think it's totally reasonable to be able to do it. But I believe it should be about convenience, not an easy way to get food. Same thing for bandages for example. I suggest that the price gets increased in the convenience stores as a "convenience fee", however, have the items offered cheaper at a more appropriate spot, but less convenient without this "convenience fee". How this would work is bandages could be sold at hospitals for a fraction of the price. Body armors, while not at the local stores, should be swapped over to ammunations. Certain items could be limited to certains stores and so on. 

**Reason:**
It forces roleplay in the sense that if you want value for your money, the food and drinks would be bought from BurgerShot or BeanMachine as an example. If you need bandages you will go to a hospital and buy medical supplies. But if you are lazy and just want the convenience without the roleplay you will have to pay extra. In short, it makes convenience more expensive, but allows cheaper alternatives if you offer roleplay in return. Also, any money going to BurgerShot or similar is circulated in the economy and doesn't end up in a huge slush fund that just sits with all the money.

**Comment by twooot** [comment]
the food in grocery stores already fills you up a lot less than restaurant food like bean machine and burger shot, no need to add an extra fee, you can get first aid kits a lot cheaper at mount zonah and body armors are already at ammu nation
