### ISSUE TITLE
BEAN MACHINE PUBLIC COUNTER

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2347]
request you to add a public counter like burgershot in every table at bean machine. if you add this it will be more realistic than now.

One more thing, if you increase little bit the amount of hunger and thirst for every product in bean machine, that will be better. 

Remove donut and cream cookie, add some new item with more effective that will be s great thing  for bean machine.

**Comment by twooot** [comment]
not gonna remove items, there is some new items coming, not gonna add public counters to every single table atr bean machine

**Comment by HellRaiser5** [comment]
dont add every single table .. make at least one table, I think that will be greate.. please do this
