### ISSUE TITLE
Invisible Character Bug With Females character 

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2348]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/ravicant1/

**Summary:**
Write a short summary of what you are experiencing.
So, After the New Character update where you can select a mother and father in the face section if anyone tries to create a new female character for 80% of people, it appears invisible but if you had a female character before that update people are able to see them properly.

**Steps to Reproduce:**
Include what steps are needed in order to reproduce this issue.
Make New Female Character with the current update
it will be scuffed for other people 
Try to make a character before that update

**Expected Results:**
What are the expected results?
New Character will be scuffed for others and the old one works just fine

**Actual Results:**
What are the actual results?
New Character Appears to be invisible for others.

## Additional Information

New Ped Model Data - https://img.ravicant.in/u/1YrAngK.txt
Old Ped mode data - https://img.ravicant.in/u/ND1zfFE.txt

**Screenshots:**
If suitable, include some screenshots.
With New Character System 

https://img.ravicant.in/u/46ADf7B.jpg - My Pov
https://img.ravicant.in/u/0Pjt9zN.png - someonelse pov

With Old Character

https://img.ravicant.in/u/BVid6cx.jpg - My Pov
https://img.ravicant.in/u/TlOGvFN.png - someonelse pov

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
New Character Player Data - https://img.ravicant.in/u/46ADf7B.jpg
Old Character Player Data - https://img.ravicant.in/u/BVid6cx.jpg

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India

**Notes:**
For anything else noteworthy.
Sometimes it gets fixed automatically most of the time it won't.

**Comment by twooot** [comment]
fairly certain this is a fivem bug, if not it should be fixed with the most recent restart
