### ISSUE TITLE
Add T-shirt and Hoodie for Videogeddon employees

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/op-framework-issue-tracker#2349]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I would like to add two shirt options for Videogeddon Arcade employees to wear. One being a t-shirt (which I believe is already in the base game) and another being a hoodie.
**Reason:**
Why would your suggestion be a good change to the framework?
Employees of the business stand apart from patrons. Also, pretty much all other active businesses have their own apparel.

**Comment by ravicant** [comment]
You Should open ur suggestion here - https://github.com/InZidiuZ/legacy-assets-issue-tracker

**Comment by AdeptCL** [comment]
This will likely be closed because it's an asset suggestion you've made, but this is the framework GitHub.
