### ISSUE TITLE
Nancy

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2353]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? 

**Summary:**
a picture of a devius looking nurse stealin yer stuffs when it happens

**Reason:**
More amusing then just seeing black screen and what gets stolen ^^

**Comment by twooot** [comment]
uhm

**Comment by twooot** [comment]
no?
