### ISSUE TITLE
Crafting station bugged

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2354]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
Lots of crafting station's are bugged once you complete the crafting process one item will be used from your inventory and it won't give anything back in return and then it won't let you use any crafting station unless you restart your FiveM

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
Make it use all the essential items needed to craft the item and give back the finish product.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://user-images.githubusercontent.com/29286961/176252373-74759fa8-9bdf-4d20-a5c8-0f4b0da85dd5.mp4

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/29286961/176252477-09a8cd4e-c72e-4c71-994c-5dd095b6762d.png)

**Server:**
What server/community did this issue occur in?
Legacy India

**Comment by twooot** [comment]
fixed
