### ISSUE TITLE
Let me pick up a baseball, after I throw it.

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#2355]
**Assurance:**
Yes 

**Summary:**
Currently, when you "use" the baseball item, it equipts like a weapon, then you can throw it. HOWEVER you cannot pick it back up, it "uses" the baseball as a one time use.

Why can I not pick up this poor baseball? 

**Reason:**

I have many skills, and playing fetch is one of them - let me throw and then pickup the baseball and throw it again, over and over. 
![sad baseball](https://user-images.githubusercontent.com/74515485/176343657-35b33357-7ee8-4987-87bc-e095d3274f43.PNG)

**Comment by InZidiuZ** [comment]
This has now been done!
