### ISSUE TITLE
Unlimited bullets bug

### ISSUE THREAD

**Issue by PremKarira** [InZidiuZ/op-framework-issue-tracker#2356]
**Player Identification:**
 https://steamcommunity.com/id/prem46/

**Summary:**
weapon glitch : any amout of bullets i fire, it is not decreasing....
had 243 (7)... shot 6 bullets.. then 243(1)... after waiting 2s.... it is 237 (7)....till here it is normal... .  then getting in car. it is 243(7)
after that fired so many shots .,, still 243 (7) 

**Steps to Reproduce:**
two different videos.
https://drive.google.com/file/d/1rM99rSsfkpY4keiq9ZW9Ax0evh0-7cQ4/view?usp=sharing
https://drive.google.com/file/d/19yLhBGg5kJt85-HpESkDq3-c7zt-y0J4/view?usp=sharing

**Expected Results:**
bullets should decrease

**Actual Results:**
they are not decreasing,, still 243(7)

**Comment by superiorchicken007** [comment]
@PremKarira what does it say when you use the /ammo command when you have your gun out.  Check to see what that says before and after you shoot.  Sounds like you might have more ammo then what can be shown.

**Comment by twooot** [comment]
i'm pretty sure you just overstacked ammo
