### ISSUE TITLE
Ability to holster a firearm/melee weapon in a vehicle

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2358]
**Assurance:**
Yes.

**Summary:**
Ability to holster a firearm/melee weapon in a vehicle.

**Reason:**
The ability to holster a firearm/melee weapon that you normally wouldn't be able to pull out while in a vehicle can be a benefit to the server. For both police-based roleplay, and criminal-based roleplay. 

Currently, the system only allows you to hold onto a "2 hand" firearm or a melee weapon if you've already drawn it before getting into a vehicle. So although it is a minor thing, because of the potential response of "just make sure to pull it out before you get into a vehicle". It could open up a branch of new experiences when it comes to police v crim chases, or crim v crim conflicts.

The roleplay behind it is that it is either placed onto the floor while driving, or it's on your lap. It's a very simple thing in the grand scheme of things. As a side note, I do also think this could benefit the mentality of "car fights". An ability to pull out your larger firearm in the midst of a moving vehicle will allow people to have better experiences when wanting to participate in conflict.

**Comment by scufflord** [comment]
this would be great, especially for usage of the two handers that are compatible with bikes. currently if i want to roll around with a sawed off shotgun for example I'd need to park somewhere, pull it out, then get on the bike. It feels clunky to have to do it like this, especially considering you can use it off a bike with no issues after that.

**Comment by InZidiuZ** [comment]
This has now been done.
