### ISSUE TITLE
Re-enabling 1st person perspective when aiming a gun in a vehicle

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#2359]
**Assurance:**
Yes.

**Summary:**
It's a marmite-like suggestion, but to re-enable the first person perspective when aiming/shooting a gun from a vehicle.

**Reason:**
We're a roleplay server. If you can't see the benefit in the suggestion, you shouldn't be playing on this roleplay server.

The first person perspective from within a vehicle makes it difficult to shoot backwards, meaning it becomes a tactical situation in which you're going to want the conflicting vehicle or person in front of you. It also creates a situation in which crim on crim action will be slowed down because it's about the limited perspective you now would have when shooting somebody from a vehicle. 

I remember a time when this was a thing, and I can say from my POV, that it was one of the best times on the Legacy Roleplay server for crim on crim action. It felt like a fair playing field. You can argue with "get better", but if that's your response, visit my first sentence under reason.

**Comment by twooot** [comment]
not a dev issue, its a config flag that can be enabled and disabled for each server
