### ISSUE TITLE
Tow/Mechanic Duplication Bug

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#236]
**Reporter:**
Beezy#6584 username is SleezyBeezy

**Summary:**
Towed a car to the repair shop down near the docks on my flatbed. Took the car off and inspected it and repaired it. As the body was repaired, it spawned a duplicate of the same car on top of it. I had to tow one off so he could repair it again as it damaged it. The duplicated car didnt work with the same key or anything but was the same exact car he had color and all. 

**Steps to Reproduce:**
Haven't attempted to duplicate the glitch.

**Expected Results:**
Repair the car as the normal mechanic.

**Actual Results:**
Resulted in 2 of the same car on top of each other.

## Additional Information
I don't know if it was due to the fact that my flatbed was too close to the car so when it repaired it might of glitched but not understanding how it made a copy of the same vehicle. Also the vehicle was completely broke and when i took it off the flatbed at the shop, the engine was already fixed. Don't know if that's related or not as it was the first time i used the tow truck.
**Screenshots:**
Didn't get a screen shot. My apology, i was just going to join your stream and let you know about the issue but you weren't online so I reported it here instead.

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID 1628, Job Data : Mechanic, Los Santos Customs, Tow Driver

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This is a bug which has been happening for a while, but without proper debug information or a working repro, I won't be able to fix this, so closing for now. If it happens again, make sure to screenshot your /info and F8 console immediately.

**InZidiuZ**
*OP-FW Developer*
