### ISSUE TITLE
Physical Hunting License QOL update

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2361]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I suggest adding a physical hunting license into the city.

Currently we have an out of city hunting license and hunting license database which has everyone's license for everyone in the international server.  I would like to suggest a "badge" for hunting that has been introduced in several whitelisted jobs recently as a hunting license that someone can carry on their person.

Just like with the state job and handing out aviation licenses adding a /give_license "hunting" will give you access to a hidden store (just like how the garages work for aviation) at the hunting store where you can buy the license and also have the Hunting Rifle added to the special hunting store as well.  PD can also use the /Check_license command that they already have to see if its valid (incase the license was revoked but still have the badge on them).  PD can also use the /Remove_license to remove the hunting license if they were involved in any crimes (would be SOP and subdivision related)

I have an example of what we can use for the license. (I have a box for a picture if you can) and if a picture is not able to be produced then I would say how a regular ID is but with the layout of the example (move information around so it looks good)

![Hunting License Example](https://user-images.githubusercontent.com/81419197/177248529-e6e00d37-c09a-4f0d-8dd8-58fc8c4b4bf1.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?
I believe this would be a QOL improvement for hunting with having a physical license that you can carry in the city that can be checked by PD instead of them going externally into a database to look it up.

**Comment by twooot** [comment]
![license](https://raw.twoot.org/VUsiqici77.png)
