### ISSUE TITLE
PD Impound suggestion

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2362]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
As the /pd_impound shows that the maximum time period is 12 hours (720 minutes) it would be great if max time period is removed so we could impound the vehicle more then 12 hours.
![image](https://user-images.githubusercontent.com/29286961/177372943-3af721d4-b02b-405f-831b-c8994f1dbce0.png)

**Reason:**
Why would your suggestion be a good change to the framework?
12 hours is too short period of time to impound a vehicle involved in major crimes so we needed to set our own time period.

**Comment by tbone0tbone** [comment]
Anything longer then 12 hours is way over kill

**Comment by twooot** [comment]
anything over 12 hours is a long time for a vehicle impound, so no
