### ISSUE TITLE
No one can see my character.

### ISSUE THREAD

**Issue by RHINO08** [InZidiuZ/op-framework-issue-tracker#2365]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
https://steamcommunity.com/profiles/76561199155468573/

**Summary:**
No one can see my character. Every time when I create my character result is the same.
I have proof that no one can see me. 
video link ( https://drive.google.com/file/d/1Tg9b-hNHJuVTqK1HqI8TNmGwT9DGJAIW/view?usp=sharing )

**Steps to Reproduce:**
Whatever you want I want to fix my issue.

**Expected Results:**
Please fix my issue.

**Actual Results:**
I don't know, but I can't make another character in the server for this issue.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
1920x1080

**Player Data:**
![20220706174538_1](https://user-images.githubusercontent.com/74284208/177591931-5919a241-5109-4583-8890-5ad881515ea3.jpg)

**Server:**
Legacy Roleplay Bangladesh

**Notes:**
Nop!!

**Comment by CloudTheWolf** [comment]
I see from the screenshot this is on the Bangladesh server.
Does this also happen on the International Server?

**Comment by twooot** [comment]
this is a fivem bug i'm fairly sure
