### ISSUE TITLE
Suggestion - Ingame MDT

### ISSUE THREAD

**Issue by PineAppleJuice921** [InZidiuZ/op-framework-issue-tracker#2366]
There should be an ingame mdt instead of updating using software doj for police. /mdt ingame would open medu for updating criminal reocrds properly.

**Comment by twooot** [comment]
NO NEED TO HAVE CAPS TITLE

**Comment by V4P1Dx69** [comment]
@twooot NO NEED TO HAVE CAPS COMMENT

**Comment by Mugdha57** [comment]
MDT COMING sooon..... sooon.....

**Comment by PineAppleJuice921** [comment]
ingame mdt using /mdt should be there for a more proprt experince.

**Comment by PineAppleJuice921** [comment]
> NO NEED TO HAVE CAPS TITLE

Sorry. But could in game /mdt be available?

**Comment by InZidiuZ** [comment]
We won't be adding a custom MDT that is built-in with the framework anytime soon. However I've created a script that allows server owners to put their MDT website into an iframe which would be accessible in-game.
