### ISSUE TITLE
SOL:SA Repairs Outdoor Bay + Workbench

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#2368]
**Summary:**
Requesting a external repair bay at sol:sa repairs for bigger vehicles (With the workbench for easier crafting access). We're across from one of the busiest trucking spots and repairing their trucks is next to impossible. 

**Reason:**
Having them ram their truck into the door holds up other customers and is just a big pain - At the end of the day we'd like to match other mechanic shops and keep customers in the north - So an outdoor bay would be beneficial and a big help to us and our subdivisions.

**Suggested spot:**
red = slot for vehicle
blue = mechanic workbench needed
![unknown](https://user-images.githubusercontent.com/77466954/177827277-6005909f-8f36-4fa4-b16a-c413a8a1a6d2.png)

**Comment by Mugdha57** [comment]
great idea!!

**Comment by InZidiuZ** [comment]
I would be down to add this, but it would be a bit awkward without any workbench there yet. I would suggest making a suggestion [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) to have the map change done.

Once that's been done feel free to reach out to me in DMs or reopen this issue.
