### ISSUE TITLE
Cars invisible inside Custom Shop

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#237]
![invisible shop](https://user-images.githubusercontent.com/50811631/61570182-09847e00-aa59-11e9-8004-a330e5d16ec8.png)
**Reporter:**
Beezy#6584  username SleezyBeezy

**Summary:**
Just purchased the Kamacho and went to put some upgrades on it at the Customs shop. When i drove in and it change to the tune screen, the car disappeared with me still inside. Anything done to the truck still sticks but i can't see anything i'm doing or what it looks like for modifications. I spoke with another individual about 10 minutes later that just purchased the Jester and said the same thing.

**Steps to Reproduce:**
I tried to put the vehicle in the garage and pull it back out and it came back with the same result. Even put the truck in the garage, logged and closed FiveM then relogged back in to get the same issue.

**Expected Results:**
Car to be visible while doing modifications to it.

**Actual Results:**
Car is invisible including me inside the vehicle.

## Additional Information
I don't know if this bug has anything to do with the OneSync servers that just went live but hopefully can be resolved or is already being worked on.
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID 1628   - Job Data: Mechanic, Lost Santos Customs, Tow Driver
Timestamp : 2019-07-20  00:10:07

**Notes:**
For anything else noteworthy.

**Comment by greatwhite18** [comment]
It has to do with the OneSync server more than likely to do with the issues during phone calls, tattoos disappearing, voice chat breaking up quite often.

**Comment by InZidiuZ** [comment]
Hey,

This is indeed OneSync-related, and will not be fixed for now. Hoping FiveM fixes the native the invisibility relies on soon, which won't require me to create a workaround for this.

**InZidiuZ**
*OP-FW Developer*
