### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Dallebaaz** [InZidiuZ/op-framework-issue-tracker#2370]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

increase in EMS Salary at lower ranks being a EMT /EMT ADV lately i have not been able to just satisfy the needs in city of myself due to low salary due which the cost overall around the city is more likely to do other jobs when off duty and have no time to do have fun or meet other people or enjoy which make us like a grinder i literally had to geind my negative account to positive doing mining cuz i had no other job which is suitable with me being a ems

**Reason:**
Why would your suggestion be a good change to the framework?

like me there would be other people who would somehow join ems too we already have lack of ems around city and when people join it and face the problem they would have the first mindset of leaving the job which is no longer a benefit to us also the increment to our salary is to only satisfy our basic needs food water a transportation vehicle some cash to spend over stuff for fun when not on duty.

**Comment by twooot** [comment]
The EMS paychecks are exactly the same as the PD ones. PD has a lot more expenses and still gets by. I do not think there is a need to increase the EMS paychecks at this time
