### ISSUE TITLE
EMS Bandage item/First Aid Kit rework

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2371]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

My suggestion is to introduce Bandages into the city that you can buy at stores just like the first aid kits. The bandage item will be used to stop bleeding and minimally heal someone a very tiny bit (i.e. 5hp).  With the introduction of the Bandages I would then suggest removing the First Aid Kits out of the Convivence stores and only make them purchasable (for a price increase) at the hospital or grant EMS the ability to craft bandages into a first aid kit for cheaper that they can sell to citizens.  The reason the First Aid Kit would be more expensive is if EMS is not around there is still a way to obtain them.  I would still keep that you can gain them through other means i.e trucking, trash, house robberies, etc. but change it to what would make a sensible economic impact.

Here is an example inventory icon:

![Bandage](https://user-images.githubusercontent.com/81419197/178226789-f26e589f-5bdc-4d17-8423-1d97f9e9b626.png)

**Reason:**
Why would your suggestion be a good change to the framework?
I believe this would give more RP for EMS and also allow a new item to be used in the city.

**Comment by twooot** [comment]
done
