### ISSUE TITLE
Bean Machine Items Improvement

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2372]
Recently i found that bean machine product quality is not so good, few days back cheese cake was a good amount of hunger relief and stress relief, yesterday i found that cheesecake hunger relief reduced very little bit of amount hunger can relief.

Same thing with espresso, few days ago after using espresso running speed nicely boost and lasting time also good. recently i found that espresso was not good right now running boost decrease and also the lasting time.

I don't know  its a bug or something else. 

requesting you to please check the item quality each and every product in bean machine , if its working perfectly then well and good otherwise please fix this thing.

one more thing if you increase little bit of effect after using the items that will be much better. need to more effective after using this items bean Coffee, Waffle & Espresso.

if this is remain same then its very difficult to run Bean Machine in Indian server.

if you think all product is good and working perfectly then please reduce the basic price so that we can reduce the sell price.

Extra. - Add Some new product that will be great.

**Comment by twooot** [comment]
> think all eating smoking consumables are a bit bugged atm giving random hunger destress relife
Not a bug, thats a feature. Food doesn'T will you up EXACTLY the same way every time, same goes for stress relief, drinks, etc.
