### ISSUE TITLE
Suggestion - Daily Contract

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2375]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Every day have a contract that players can accept from an local (Potentially have this local rotate to a new location daily, so players have to try and find them)

Eg:

Day 1: Local at the Steel Works and asks you to bring him 10 Steel, and he'll pay you $5000
Day 2: Local at the Pier is looking for an Emerald Ring and will pay $2000 for one 
Day 3: Local at Al Dente's on Hawick Avenue needs 15 Raw Meat and will pay $6000 
etc

Another option would be a "Job Board" where you get the Daily Job details and that tells you what you need to do and where to go with the desired item. or limit it to 2 / 3 jobs as day (or even 1 job every 1/2 hours)

**Reason:**
Why would your suggestion be a good change to the framework?
This would add a new legal way for players to make some money each day and get players out of just grinding for 1 thing.

This could also be a good way to introduce players to new activities added.

Eg Fishing gets added and a player gets the following request from the local / job board:
"Bring a rainbow trout that weighs at least 15lb to the Irish Pub"

**Comment by antihero6713** [comment]
I like the idea as well.

**Comment by MetaHatter** [comment]
I like the idea... 

Might be tough to balance just right though... 

For example, dollar amounts would have to be adjusted or other cash opportunities would likely need a lowered cap.
Perhaps $1k/$3k/$5k for the three tasks here this with hunting cap lowered to $15k and mining to 22.5k/day.

I would also focus primarily on decent quantities of items that people usually ignore to help give them a purpose.

**Comment by vol5** [comment]
This is Daily Contract Vendor idea I feel should be considered heavily. Here are some examples from a short vision of it. I do not like the idea of the vendor moving for practical use. More focus on structuring these around specific job types, for potential future application. 

NPC Vendor stands in one location all the time and has 3 contracts that reset daily. Or could be 3 daily with a fourth that refreshes every hour or so. Structure and balance would have to be fine-tuned as meta said. 

Contracts are random from a library of prebuilt ones most likely or rng ranged. Some amazing, some not so good and some illegal. If a vendor is to be added to Trucking for instance. It may need some new specific items that only come from the trucking loot pool as drops. Considering how much cross pollination of loot there is for the base jobs. Things like hunting and mining would be fine already. 

Eg. Trucker Vendor 

Daily Contract example A = Payout:  3.5k, Pack of Cigarettes, 1 beer, random item.

Name: Get-er fixed....
Description: Hey listen... We are gonna fix her up the right way! With some elbow grease and Blain Countys finest.

[Requirements]- Legal
1x Advanced Repair Kit
4x Wood Pallet - only drops from trucking delivery
4x Rubber
1x Jerry Can
1x Crowbar

Daily Contract example B = Payout:  3.5k, Pack of Cigarettes, 1 beer, random item.

Name: The American Way
Description: A few of our guys drive the truck without bald eagles around their waist. This city is dangerous, and we can't afford to lose them. 

[Requirements]- Illegal 
2x Pistol .50
2x .45
1x Air Freshener - only drops from trucking delivery
4x Cigarette Pack
1x Lighter

These contracts could be turn in where there is ui that you click at the NPC then items get pulled from inventory. Or they are items you pick up from the vendor and have them on you physically. With the ladder you could make them more interactive having a requirement like travel 20mi and functions as a checklist/tasklist that tells you if you can turn it in or not.

The goal being Focus on incentivizing the player to login DAILY, and diversifying the content loop. A ton of games use this mechanic.. Why not here?

**Comment by DaxterPancake** [comment]
I love this idea and think it would be an amazing addition. It adds another insentive for people to come on everday to fill this contract.

**Comment by CloudTheWolf** [comment]
One thing to note, I hear NPCs are not exactly reliable for spawning in, so this could be another app on the tablet, or maybe accessible from a computer in Life Invader (Or both)

**Comment by DaxterPancake** [comment]
Alternative could be a bulletin board that you walk up to to get your contract for the day. Could be at life invader or any location you think is suitable. I know that NPC spawning could be a headache as Cloud said.

**Comment by TheOneLizard** [comment]
That's a shame, because if it were NPCs, it could be 6 different ones in total, but only 1 random one has a daily contract for you, and which one it is changes every day. Would give some additional investment to get it from the right person by actively seeking them out first.
Then again, that could also be done for bulletin boards. Have 6 boards in total, only 1 will give you a daily contract.

**Comment by vol5** [comment]
> One thing to note, I hear NPCs are not exactly reliable for spawning in, so this could be another app on the tablet, or maybe accessible from a computer in Life Invader (Or both)

I don't understand what you mean by this. Is that an OPFW thing? Because almost every FiveM server has a PED locked in one location to act as a vendor or a ui spot.

**Comment by coalaura** [comment]
I like the idea as well.

**Comment by ImArteria** [comment]
I like the idea as well.

**Comment by CloudTheWolf** [comment]
I see this as done now, with further discussion on Daily Activities here: #2741
