### ISSUE TITLE
[game/taxi] Local Taxi calls

### ISSUE THREAD

**Issue by 06Krishna2004** [InZidiuZ/op-framework-issue-tracker#2378]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

In server no one calls for taxi , everyone just robs the car but there are some people who want to do taxi jobs. So can we add taxi system like gta story mode. peds calling taxi?

**Reason:**
Why would your suggestion be a good change to the framework?

Taxi drivers don’t get any RP. That’s the main reason

**Comment by twooot** [comment]
I believe this is something MetaHatter is working on currently. I don't know the ETA but its being worked on :)

**Comment by DopeIndar** [comment]
This is a great Idea. Just Like Burgershot and BeanMachine Employees can Deliver to Locals Players with Taxi Job will also have Locals calling them for Hire.

**Comment by Breezy368** [comment]
I see this is an old thread, but bumping it to know if this is still being worked on?

**Comment by coalaura** [comment]
due to how scuffy NPCs tend to be, i don't think this would work out. I tried the same idea when i made the bus job and it just ended up being super scuffy
