### ISSUE TITLE
Suggestion - Vanilla Unicorn Improvements

### ISSUE THREAD

**Issue by abirali098** [InZidiuZ/op-framework-issue-tracker#2379]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes.

**Summary:**
Write a summary of what your suggestion is about.

01. vanilla unicorn has no owner role. so need to be added to the owner's role.

02. People are shy to dance in clubs. this is why no one joins as a dancer. So it would be better if you add a system to do the dance with the bot. If this is the case, this business will always be running and the RP will be better.

03. Add some food and drink here ( Food: burger, sandwich. Drink: coke, water, coffee. ). Because many people get hungry while partying here, they can satisfy their hunger in this place if there is some food here. and its shop can be used by everyone, it is better if it is made so that only the employees here can use it.

04. It is better to open a helpline for the Vanilla Unicorn on mobile so that anyone in need can easily contact them.

05. One important point is that no one wants to take a job here because only RP is here, they cannot earn any income here. So it would have been better if the delivery system like burger shot and bean machine was added here ( alcohol delivery ).

**Reason:**
Why would your suggestion be a good change to the framework?

Vanilla Unicorn RP is very low and has no income. This is the main reason. So we think doing the above can make a lot of RP with vanilla unicorns.
![Screenshot_1](https://user-images.githubusercontent.com/103858728/179353848-4028b3ed-0d76-4d15-b731-ab056cb361b4.png)
![Screenshot_3](https://user-images.githubusercontent.com/103858728/179353849-50f7e0ff-bc30-4c9a-81a9-26a9855505ff.png)

**Comment by superiorchicken007** [comment]
There is a Vanilla Unicorn business job that can be assigned (Business, Vanilla Unicorn, (Owner, Manager, etc.)

I don't believe the VU would need food in its store.  You can RP and have someone come and cater the food when you have events or go to the businesses and work on a deal to supply food. 

I also think your dancers having a stage name and possibly a mask where no one knows who they are would be better than having a PED just dancing.

You are able to make money working here by creating RP.  You can make specialty cocktails and upcharge from what you purchase the alcohol from.  You have the ability to charge whatever you want and as long as its more than what you paid for that is all profit.  You can also charge a cover fee for people coming into the club and again that is more money.

**Comment by twooot** [comment]
1. "Manager" is what the owner would get
2. This may be a case in your division but a lot of other divisions manage to get this done properly. I don't think local dancers would be a nice addition since you would be avoiding RP instead of having more RP.
3. I added some food to the bar shops
4. There is no need for a helpline for Vanilla Unicorn
5. There will not be local devlieries for Vanilla Unicorn, thats stupid. They are a strip club not a delivery service. You can make a lot of money with the VU if you do it properly, but it requires effort and it **requires you to RP**
