### ISSUE TITLE
Can't fix my tires

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#238]
**Reporter:**
Allen#8921
https://steamcommunity.com/profiles/76561198260006559

**Summary:**
I am trying to fix my broken tires, but when I add my tires in, they don't affect my vehicle at all, and I just have broken tires still.

**Steps to Reproduce:**
Whatever steps that lets you fix the tires.

**Expected Results:**
Adding tires and it actually working.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
N/A

**Game Resolution:**
1920x1080

**Player Data:**
Player ID: 136 - Job Data: PDM Apprentice

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved.

**InZidiuZ**
*OP-FW Developer*
