### ISSUE TITLE
 Suggestion: Add locks to the doors at the hayes repair shop

### ISSUE THREAD

**Issue by divyummm** [InZidiuZ/op-framework-issue-tracker#2380]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
Need locks at hayes auto body repair shop (4) as the dor open constantly by anyone who passes there even the locals walk it gets open.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by twooot** [comment]
Please follow the format with issues and suggestions, thx

**Comment by InZidiuZ** [comment]
This has now been done!
