### ISSUE TITLE
green wounderland female model green wounderland t-shirt

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2381]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Need a female model Green wounder land work T-shirt,white/black color options

**Reason:**
Why would your suggestion be a good change to the framework? Because we aint sexist assholes ? xD

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker. This is for framework changes only. For asset changes use [this issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
