### ISSUE TITLE
PD Glovebox/Compartment Box/Area

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2382]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
If you can increase the glovebox capacity for cops as referring it to compartment area where we can put our weapons.

**Reason:**
Why would your suggestion be a good change to the framework?
Cops carrying lots of guns on their back feels a little bit weird and SWAT doesn't have to go to PD to switch their Guns they can just put it in the compartment area/glovebox so whenever they need a specific gun they don't have to rush back to PD.
![image](https://user-images.githubusercontent.com/29286961/179994103-ceba7226-1793-4857-ad40-918c7c69fff9.png)

**Comment by InZidiuZ** [comment]
What about using the trunk to store larger guns?

**Comment by InZidiuZ** [comment]
After additional discussion, this suggestion is being rejected.
