### ISSUE TITLE
Reusable Water Bottle Item

### ISSUE THREAD

**Issue by mohitshukla22** [InZidiuZ/op-framework-issue-tracker#2384]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
The Water Cooler offers water free of cost, so why not refill our bottles from the cooler for free. Maybe if the degrade bar changes to the level of water remaining. This idea came to me while I was watering my weed plants with a purchased water bottle and was watching the water cooler which was installed in my home (which offers free water just for drinking)

![Screenshot (636)](https://user-images.githubusercontent.com/74307364/180375626-08707d2b-403a-45ff-91fc-6d37096
![Screenshot (635)](https://user-images.githubusercontent.com/74307364/180376102-3781ca92-5581-4cbb-840b-1b7fea863653.png)
10294.png)

**Comment by AdeptCL** [comment]
> This is a cute idea but I already see the flaw with it. You purchase water in order to be able to water your weed plants, why should you get that water for free by just installing a water cooler in your home so you don't actually have to leave your house and buy water.
> 
> An addition that stops players from actually having to go out and do something doesn't make sense to me.

Following this, what about a new drinking object, which looks like [this](https://www.verywellfit.com/thmb/TdRTn99hPla45W4hQrVVhAopLgo=/900x0/filters:no_upscale():max_bytes(150000):strip_icc()/NalgeneWideMouthWaterBottle-32oz-5a832e5eff1b78003752f1b9.jpeg). This would be like a coke can in which you can't use it against a weed plant, but can be refilled / be used 3-4 times before requiring a refill.

**Comment by twooot** [comment]
Eeeeh, i don't really know about this. Same concerns that daxter had. (Also fuck the turtles)

**Comment by twooot** [comment]
I added them
