### ISSUE TITLE
Mechanic - Material Cost Adjustments

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2385]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

- Reduce cost of doors/trunk/hood from 2 scrap to 1 scrap each
- Increase base cost of engine repairs by 1 aluminum
- Increase base cost of body repairs by 1 steel

**Reason:**
Why would your suggestion be a good change to the framework?
Several purposes
- Slightly reduce the overall maximum cost of repairs to help newer players (and now PD/EMS)
- The cost to replace all missing doors is disproportionate with their value, so people are choosing to drive without them
- Full Armor makes repairing vehicles body and engine VERY cheap over a long period of "normal use"
- Mechanics currently have a MUCH greater need for scrap than the other two mats. This will help balance the stock level management game.

**Comment by InZidiuZ** [comment]
This has now been done!

**Comment by ayushpandit99** [comment]
This change would overall cost more to the people than less... as before the base price for repair   1 Scrap =65 2 Scrap =130  for engine and body now the base price itself would be 2 Scrap +1 Al+ 1 Steel Which Would Cost You =335 also we get scrap quickly rather than steel and al so (For Ex chopping 1 car you get 10-12 scrap where as just  2-3 steel and 2-3 al)i think the change should be reverted back and for the door, it should be 65 for 1 door difference being 65 but in case of the engine body combine the difference is 205 $

**Comment by MetaHatter** [comment]
It will increase the base cost yes, but the maximum will go down.  $150 for a decent amount of damage on a fully armored car was too low.

We can adjust drop rates on steel and/or aluminum if they prove to be too scarce.

**Comment by ayushpandit99** [comment]
no max cost won't get lower as now max cost would be 6 scarps + 3 steel and 3 al for engine body

**Comment by CaptSpider4** [comment]
After testing few times these are possible damages ( there might be other possibilities idk )

Minor Damage
Engine   1 Scrap 1 Steel  = $180
Body      1 Scrap 1 Al = $155

Moderate Damage
Engine  1 Scrap 2 Steel = $295
Body     1 Scrap 2 Al  = $245

Heavy Damage
Engine  2 Scrap 2 Steel = $360
Body     2 Scrap 2 Al = $310

Severe Damage
Engine  3 Scrap 2 Steel = $425
Body     3 Scrap 2 Al = $375

Extreme Damage
Engine  3 Scrap 3 Steel  = $540
Body     3 Scrap 3 Al = $465 

Based on Scrap = $65, Steel = $115, Al = $90

So maximum cost goes for $1005 ( without doors tyres windows that would increase more )

So decreasing Steel and Al price would balance a bit
Maybe Steel for $100 and Al for $80

**Comment by MetaHatter** [comment]
Calculations without doors is not the true maximum. 

Using your prices of $65 scrap, maximum cost for 6 doors was $780.  It will now be $390. 

That is a difference of $390.  One additional aluminum and steel is, using your prices, $210.  

Maximum repair cost will go down by $180.

This cost swing can vary based on shop markup but it's still a net savings for max repair and slight increase for minor repair. Exactly as I stated.

**Comment by CloudTheWolf** [comment]
So from a mechanic perspective I can give a clearer insight into Cost to mechanic vs cost Customer

All Buying Costs are based on getting materials from other players, not the warehouse computer
All Selling prices Exclude any discounts given by the mechanic / shop

Extreme Damage Repair 
| Type | Buy Cost | Sell Price |
|-------------------------|----|----|
|Engine 3 Scrap 3 Steel|$420 | $570 
|Body 3 Scrap 3 Al|$360 | $495 
|6 x Doors|$300 | $420 
|4 x Windows|$140 | $180 
|4 x Wheels|$40 | $80 

| Repair Type | Cost | Price |
| -------------|-------|------|
| Engine and Body |$780|$1065|
|^ + Doors|$1080|$1485|
|^ + Windows| $1220| $1665|
|^ + Wheels | $1260 | $1745 |
