### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AbuAbdullahAlAsif** [InZidiuZ/op-framework-issue-tracker#2386]
Name: Abdullah Al Asif 
Discord : Healer ᴷᴼᴰ#5984

**Summary:**
I've a mask request sir. We are need this face mask for  LSPD. you know whole world has been affected by covid 19 as similar we want to play in GTA 5 RP. Basically there don't have Police mask. If you put the face mask in the server it will help use to continue our RP properly. if you think about  assets increase then i think we already have a black face mask you just put LSPD or BCSO LOGO on this mask.
> already have [Image] : ( https://cdn.discordapp.com/attachments/982018570659713184/1000515283854839818/Screenshot_77.png )
> need this type of logo [Image] :  ( https://cdn.discordapp.com/attachments/974665000717258765/1000367892468076554/unknown.png )

**Reason:**
It will help people in legacy Bangladesh as well as the people who do RolePlay as Police .Its my humble request sir .Please put this.

**Comment by Mugdha57** [comment]
post this in op-fw.
#clothing-suggestion

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this. Use [this one](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for clothing suggestions.
