### ISSUE TITLE
Auto Capitalise Names/ No Numbers

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2388]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
I think when players are creating a new character numbers should not be allowed in their name and the first letter of both the surname/forename/double barrel name should be auto capitalised.

**Reason:**
Why would your suggestion be a good change to the framework?
Well from an RP sense it's just more realistic and makes sense, no one's name has numbers in and it's always capitalised seeing as your name is a noun, there's people with multiple capital letters in their name and it's just not really realistic

**Comment by InZidiuZ** [comment]
Auto-capitalization of the first character in the names has already been a thing for a while. I've also now added a check to make sure there are no numbers included.
