### ISSUE TITLE
Suggestion to add more locals to Sandy Shores and Grapeseed to Combat how grindy Meth Selling feels

### ISSUE THREAD

**Issue by Scardab** [InZidiuZ/op-framework-issue-tracker#2389]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
I have a suggestion for the process of selling meth. When going around and trying to sell meth, I have noticed a pattern, which is that there is not that many locals in Sandy Shores and Grapeseed.

There are times where you will find a good cluster of locals, but more often then not, I find myself roaming around searching for a needle in a haystack. Then when it comes to finally finding locals, they usually are by themselves or in a group of 2. Especially with having to wait a while after leaving your car before you can sell, it can become very stale, boring, and slow.

Adding more locals in these areas would make selling meth feel less grindy.

Finding one local, getting out of the car, waiting for a while, selling it, getting back into car, searching again, repeat. This would be fine if the locals were it bigger groups or easy to find, but this hasn't been the case in my experience.

**Reason:**
Meth isn't really as hyped up as it should be. People know it's there, but people don't really care to make or sell it. I believe a big part of this is because of how grindy it feels playing hide and seek with locals in order to sell them. Adding more locals or larger clusters to grapeseed and sandy shores would make it so people don't have to search so long just to find 1 or 2 locals, wait, sell, then repeat the searching process. It'll free up time and make things more enjoyable.

**Comment by InZidiuZ** [comment]
This most likely is because of a FiveM issue with population creation. To try to combat this though I will increase the population levels of walking peds to always be at 100%, but I am doubtful it will work that well.

Feel free to contact me directly via DMs to provide some feedback if this changed anything.
