### ISSUE TITLE
Renewing Motel Lease text update

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#239]
**Reporter:**
SteezyRen

**Summary:**
When you are due to make a payment on your Motel and you go to the reception it says
"Rent a room for $XXXX" which can be a little misleading for people who currently want to just make a payment. Not sure if it's something that can easily be changed for anyone who has a current motel when they go to the reception for it to instead say "Make payment for Motel for $XXXX"

**Steps to Reproduce:**
1. Have a prompt in game telling you that you need to make a payment on motel that is due by X days
2. Go to reception to try to make payment
3. Says "Rent a room for $X amount" 

-----------------------

Not sure if this is a bug or just a suggestion, so sorry in advance for mislabeling.

**Comment by InZidiuZ** [comment]
Hey,

Not really a bug, more of a suggestion, but I added a check for the 3D text & it will now display "Press E to renew your motel room" when a motel room is already rented.

**InZidiuZ**
*OP-FW Developer*
