### ISSUE TITLE
Suggestion: Altitude & Time in Air One Camera

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2392]
**Summary:**
Add Altitude and Server Time to the Air One Camera.

**Reason:**
Recently the street names were added to the helicopter air one camera. Server Time will help because it is great to track the order of pictures in terms of FIB as well as DOJ roleplay. We have this in the PD Camera to serve this purpose so it would be great in the Air One Camera. The Altitude will also help because the current altitude meter in the camera tops out at 400 feet, which most of the time helicopters will be higher than that altitude. This again will help out in DOJ roleplay to figure out what height the helicopter was at when the photo was taken.

**Comment by InZidiuZ** [comment]
This has now been done.
