### ISSUE TITLE
New Ice-cream Parlor

### ISSUE THREAD

**Issue by ChanceTheDice** [InZidiuZ/op-framework-issue-tracker#2394]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

I want to request building a new food location. I have heard there are a couple about to open but so far everything is hot and ready food. I think it's time for a dessert! We need an ice cream parlor!

I want to set up a cute parlor that could be a fun hang out and a good date spot to boost some more of the social RP in the city, the added variety of food will help make the eating seem less repetitive since the citizens can choose from more places. 

There is a perfect little spot with a parking lot and a restaurant that could easily be converted into a parlor. The assets for the restaurant are already in the city too as there is a chain of ice cream stores called The Cherry Popper. This building is on the intersection of Mirror Park Blvd and East Mirror Dr. It's clear on the other side of the city from the currently existing stores so that we can also try to distribute business 

**Reason:**
Why would your suggestion be an excellent change to the framework?

It makes sense to add a variety of food to the city and this also offers more places for your citizens to choose to work. On top of that, I've expressed this idea to multiple people in the city already and every single person has expressed excitement at the idea! 

I'm unaware of the work it will take to remodel this building and honestly I haven't a clue how long it will take you but I want to create something that this city will love. I have a menu I'll add below but I'm not sure what prices might be placed at. The logo and a personal car are already in the city too but you'd have to whitelist the livery on the car. 

**_MENU:_**

 **PLEASE KEEP IN MIND THESE ARE ALL OPTIONAL**

_Actual Cherry Popper products_

The Cherry Popper, an actual classic of Cherry Popper that is a cherry shaped icecream bar.

The Chocolate Chufty, a chocolate cream pop

The Starfish Sandwich, an icecream sandwich shaped like a star with a smiley face on it

The Freeze Sucka, a blue ice pop shaped like a gun

**Original Ideas**

Milkshakes

Cookies

Cookie cake

Sundaes

Smoothies

Slushies

Icecream Cake

Location on map
![20220726164902_1](https://user-images.githubusercontent.com/110052454/181122611-3c069027-eb9c-4c22-b6ba-42ec53c41cdc.jpg)

Logo
![image](https://user-images.githubusercontent.com/110052454/181122782-d727cc25-8712-4392-bdc2-a194a5916fda.png)

Existing location example on the pier
![image](https://user-images.githubusercontent.com/110052454/181122878-790dcc78-ee79-450d-9ae9-003ff1294cae.png)

The building I want to use called Horny's
![20220726172649_1](https://user-images.githubusercontent.com/110052454/181123002-8b3b8b09-b3e6-4d7f-92fc-1a7094428f2f.jpg)

**Comment by superiorchicken007** [comment]
I know I did just did some research and found 2 MLO's but idk if they are able to be used.

https://www.youtube.com/watch?v=E3yHMgMCBDk
Located on Hawick Ave.

https://www.youtube.com/watch?v=1SDEfUXTtn0
On the Pier.

If this business does come into the city you can also utilize the Cherry Popper Ice Cream truck for events!

**Comment by DaxterPancake** [comment]
MLO's/maps need to be in the asset github.

**Comment by MetaHatter** [comment]
Is there anything special about the food (i.e. effects, etc)? 
Will there be a delivery service required?
Any custom functionality at all?

If not, Daxter is correct, it's an asset request for the asset github.

**Comment by superiorchicken007** [comment]
> MLO's/maps need to be in the asset github.

I didn't see what Github this was. I just seen it on the OP-FW as a recent addition so I posted on it.

**Comment by ChanceTheDice** [comment]
> MLO's/maps need to be in the asset github.

Bare with me I'm trying to learn all this. What is MLO

**Comment by ChanceTheDice** [comment]
> Is there anything special about the food (i.e. effects, etc)? Will there be a delivery service required? Any custom functionality at all?
> 
> If not, Daxter is correct, it's an asset request for the asset github.

I'm still working on that a little. I imagine since ice-cream is a stress food it'll reduce stress and maybe a few would do something like give a sugar rush making you faster. I'm not sure if that makes its effects too similar to Burgershot though

**Comment by ChanceTheDice** [comment]
> Is there anything special about the food (i.e. effects, etc)? Will there be a delivery service required? Any custom functionality at all?
> 
> If not, Daxter is correct, it's an asset request for the asset github.

I also forgot to address it but yes I would love for there to be deliver vehicles since all the other places do. If we had ice-cream trucks driving around that would be so much fun!

**Comment by InZidiuZ** [comment]
We're not able to do anything with this before an interior is added, which you'd have to suggest [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues). Until that is added, I will close this. Once an interior is available, you could reopen this issue or create a new one.

When suggesting items, it is also very helpful if some base-images are added to the post. (high resolution, without shadows etc. as we scale them down and run them through our standard filters to make them fit with the other icons we have.)
