### ISSUE TITLE
Adding value to Flares

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2395]
Assurance: Yes

Summary:
Change flare's active duration to last longer and make them purchasable via PD and fire dept.

[Adjustments]

> Extend Flare duration from 50s to 2min when used.
> Increase Flare height 2-3x so they are more visible from a larger radius in the city. 

Reasons:

- More utility, duration is currently too short IMO
- Its an additive RP layer for police with crashes and distress signals
- Would promote more use of the item which is the end goal.

**Comment by superiorchicken007** [comment]
Also goes along with #544

**Comment by twooot** [comment]
Not sure about them being purchasable really but i extended the duration
