### ISSUE TITLE
Fishing License SoonTM

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2396]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes

Summary:
Write a summary of what your suggestion is about.
I suggest adding a physical fishing license into the city.

With seeing the GitHub updates including fishing in the possible near future I am looking to try and get ahead of the game and suggest a Fishing License just like the hunting license that was added into the server.

Just like with the state job and handing out aviation licenses adding a /give_license "Fishing" will give you access to a hidden store to pick up their license. PD can also use the /Check_license command that they already have to see if its valid (incase the license was revoked but still have the badge on them). PD can also use the /Remove_license to remove the hunting license if they were involved in any crimes (would be SOP and subdivision related)

Can be just like the current license but change the wording to "Fishing License"

![68747470733a2f2f7261772e74776f6f742e6f72672f565573697169636937372e706e67](https://user-images.githubusercontent.com/81419197/181214393-ce35f7f6-d267-411b-a29f-a9730ff1c0ee.png)

**Reason:**
Why would your suggestion be a good change to the framework?
I believe this would be a good improvement for fishing with having a physical license that you can carry in the city that can be checked by PD instead of them going externally into a database to look it up.

Again this is to try and get ahead of the curve before there are alot of licenses that we have to manually input into the panel after fishing would be introduced.

**Comment by twooot** [comment]
so many licenses :wah:

**Comment by twooot** [comment]
Done
