### ISSUE TITLE
Enhancing Crim and Cop Getaway RP

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2398]
Assurance: Yes

Summary:
Add a meter coin item to increase the amount of time it takes for a vehicle to de-spawn when no players are near it. Promoting crims to experiment with a variety of getaway plans.

Item: [Coin](https://cdn.discordapp.com/attachments/922707886059180073/1001793209690759228/meter_coin_100.png)
Weight: 1lb
Item Description: This spot is bought and paid for...
Item Effect: Only works when inside storage of the vehicle. (Effect does not stack)

[How to get the item]
Have the item be almost as rare as a z-pill and put it in a variety of loot pools like chop.

I have no idea how despawning works with vehicles and even if this is possible. But something of the sort would provide value.

The intent for the meter coin is to be an item that would significantly extend the duration at which vehicles stay in a location whilst no players are around. This would act as an anchor for the vehicle so players can then plan more in-depth "Getaways" with things like boats and Helicopters. The goal is not to make it anchor the vehicle indefinitely, but add "more duration than there is now within reason" suggested 1-2h? 

I am not a bank farming crim nor a cop main so further perspectives on this would be great. But, just from watching streams, playing the server, etc. There seems to be a lack of depth when it comes to getaways. Especially with experimentation since cars and boats will despawn quite often. This would hopefully change that.

Reasons:

- Increases cop and crim RP
- Adds more depth to escape plans.
- Has direct utility

**Comment by InZidiuZ** [comment]
Vehicles created by the server never despawn (garage vehicles. PD vehicles, etc.). If they are created by a client (i.e. NPC population vehicles) they will despawn when all players lose scope of it (go far away from it).

**Comment by vol5** [comment]
> Vehicles created by the server never despawn

I would not agree that this is entirely true. I and many people have had multiple instances where player-spawned vehicles disappear when players lose scope of them. Many people can attest to this...

**Comment by twooot** [comment]
I feel like this is a very odd and unrealistic feature. Having a vehicle disappear if you dont use a coin on it, i don't like the idea

**Comment by vol5** [comment]
> I feel like this is a very odd and unrealistic feature. Having a vehicle disappear if you dont use a coin on it, i don't like the idea

This is a fair assessment. It is unrealistic and odd. The only way to reach the main goal of this, in the end, is to ensure that the player-spawned vehicles do not despawn. The coin is not needed. But it's very often the case, that server-spawned vehicles poof which should be looked into.

**Comment by InZidiuZ** [comment]
> I would not agree

This is expected behavior from FiveM & it's been said that is the intention by them. A player that is assigned ownership to a vehicle created by the server would still have the ability to delete it, so a cheater would be able to, for example. Though if they just randomly get removed without any player causing it, then it's probably a FiveM bug.

**Comment by vol5** [comment]
> > I would not agree
> 
> This is expected behavior from FiveM & it's been said that is the intention by them. A player that is assigned ownership to a vehicle created by the server would still have the ability to delete it, so a cheater would be able to, for example. Though if they just randomly get removed without any player causing it, then it's probably a FiveM bug.

Understood, this is most likely the case then and I'll close this up. Thank you for the thorough explanation!
