### ISSUE TITLE
Improving functionality of /inspect

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2399]
**Assurance:**
always

**Summary:**
Instead of the /inspect command for EMS returning a single injury or just saying "multiple injuries" with no further detail, have the word "injury" popup in each place the patient is found to have an injury, just like cracked windows are shown for mechanics when examining a car.
If it is easier from a dev standpoint, have the popup that the patient themselves sees visible for like 3 seconds, again, like for mechanics.

**Reason:**
This would greatly help EMS with more realistic interaction with their patients. When "multiple injuries" pops up, all we can do at that point is ask the patient where they are injured, ruining the point behind introducing the command in the first place.
It'll help us assess better and faster where to treat a patient and what to prioritise.
During treatment, we can still interact with the patient by asking them about their pain level, how the injuries came to be etc, giving plenty of RP options aside of the awkward "where are you injured?/where does it hurt?"

**Comment by CloudTheWolf** [comment]
@TheOneLizard sounds like an alterative to this: 
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2248

**Comment by TheOneLizard** [comment]
It definitely is, I was just no longer aware of that one

**Comment by twooot** [comment]
Done
