### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by EddyHonein** [InZidiuZ/op-framework-issue-tracker#240]
**Reporter:**
Discord:"Loading..."
Steam link: https://steamcommunity.com/id/Dc_Hades/

Summary:
Write a short summary of what you're experiencing.
Every time i create a new character it gets deleted after disconnecting.

Steps to Reproduce:
Include what steps that are needed in order to reproduce the issue.
1)create character
2)roleplay using this character
3)disconnect
4)come back not finding it
Expected Results:
What are the expected results?
I expect having my character
Actual Results:
What are the actual results?
Character getting deleted
## Additional Information
this happens everytime
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
non available
**Game Resolution:**
What is your game's resolution?
1920 x 1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Comment by InZidiuZ** [comment]
Hey,

Your characters weren't being deleted, but buried beneath the new ones created. Not sure how to reproduce this, so if you manage to do so, please let me know so I can get this resolved. I fixed up your characters though, so your user shouldn't be bugged & you'll be able to play normally again.

**InZidiuZ**
*OP-FW Developer*
