### ISSUE TITLE
Goodfellas Pizza Shop Addition (Food)

### ISSUE THREAD

**Issue by skyy-reginald** [InZidiuZ/op-framework-issue-tracker#2400]
**Summary:**
- Adding locks to Goodfellas Pizza shop
- Adding food items 
- Adding delivery system (just like burgershot)
- Adding food cooking system
- Adding jobs for the store
- Goodfellas phone line on favorites 

**Reason:**

Goodfellas is located on Vinewood so it can create more RP opportunities for people by letting them sell pizza to locals, bringing a new date spot for couples, and starting a fast food "rivalry" between Burger Shot and Goodfellas.

I understand possibly not all food can be brought in but I figured I would list some so that you had a variety to choose from. 

Antihero finished the interior and is just putting final touches on it. 

Overall, mechanic and script wise, it would be a copy of Burger Shot with the food items being swapped. I don’t feel like it would take too much work since, mechanically, it’s essentially a clone so developers wouldn’t have to spend too much time on it. The biggest undertaking would be making the food variables and adding pictures for said food.

**Food** 

Cheese Pizza
- block of cheese
- Can of sauce 
- Dough 

Pepperoni Pizza
- block of cheese
- Can of sauce
- Dough
- Pepperoni 

Pineapple Pizza
- block of cheese
- Can of sauce
- Dough 
- Pineapple

Garlic Knots
- dough
- Garlic

Mozzarella sticks
- block of cheese 
- Bread crumbs

Chicken Wings
- chicken 
- Sauce 

Bag
- however many slices and drinks the customer wants 

Root Beer (new drink for the city) 

Root Beer Float (new drink for the city) 

Goodfellas mug that can be refilled with root beer (Not really sure on this one)

**Process**

Pizza 
- buy dough, cheese, sauce, and topping of choice
- Put al ingredients together (5 sec) 
- Cook (5 sec)

Garlic Knots
- buy dough and garlic 
- Put ingredients together (5 sec)
- Cook (5 sec)

Mozzarella Sticks
- buy cheese and bread crumbs 
- Put ingredients together (5 sec)
- Cook (5 sec)

Chicken Wings
- buy chicken and sauce
- Put ingredients together (5 sec)
- Cook (5 sec)

**Possible Food Buffs**
- Pizza (Stress Relief)
- Mozzarella Sticks (sell scrap,aluminum, steel, and gold bars for more) 
- Chicken Wings (sell gems for more) 
- Garlic Knots (sell fish for more) (for when/If fishing comes to the city) 
- Root Beer (caffeine speed boost) 
- Root Beer Float (Stress Relief) 

I am not sure this is possible but I figured I would list it just in case. 

If pictures of food items are needed I can try to help with that as well.

**Comment by scufflord** [comment]
For legal reasons, I need pineapple pizza in city. This would be a great addition to the framework

**Comment by InZidiuZ** [comment]
The same thing as was said in #2217 stands here.

> The interior is required before adding any features. Please reopen or create a new issue _once_ the interior has been added.

**Comment by skyy-reginald** [comment]
The interior is finished :(

**Comment by InZidiuZ** [comment]
Not pushed yet
