### ISSUE TITLE
Robbery Additions/Store Robbery Changes

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2401]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
(This suggestion is being re-opened due to it still being relevant within development, with a removal of the regular bank changes due to Twootie doing that already <3)

**Store Robbery Changes**
The overall purpose of this suggestion is to add a "progression" system into the robbery system. Being with banks and jewelry stores as it is, you receive keys from banks and use them at Jewelry stores.

- Store Robberies give the same amount of cash, but now can have additional items in the safe.
- The safe now has a possibility of giving the following (not all - given by chance) loot pool: 1-2 Thermite, 1-2 random decryption keys, 1 Chip, 1 gold bar, 1-3 necklaces, random food items.
- By adding the above into the loot pool, it would further encourage people who are looking to rob a bank and more down the line, a sense of a direction to go by robbing a store.

**Paleto Bay Bank Robbery**

- This bank would function almost the exact same as your standard regular bank with a few exceptions. Due to this being so far out of the way, the pay would be increased. A regular bank has three deposit boxes, as to where Paleto Bank would have four deposit boxes.
- To rob this bank, one would use a chip on the main door (https://i.imgur.com/ZADNLpz.png)
- Once you hack into the bank, you would than encounter four deposit boxes that use thermite (https://i.imgur.com/54zRxHH.jpeg).
- The same drop rates would occur such as keys, gold bars, some jewelry, cash, etc.
- Police RP would occur and would force criminals to think of a unique getaway plan from Paleto Bay, and would bring more RP to Paleto
- This would require 6 cops on duty (instead of 4 like a regular bank) due to it being a little more high priority

**Jewelry Store Robbery**

- Only one change for Jewelry stores, upon successful hacking of the computer you now have a small chance to receiver a "Laser Cutter" item (which will be used in another robbery). Everything else stays the same, loot pool, process, etc.

**Pacific Standard Bank**
I know this has personally been a bank a lot of cops and criminals have been requesting for a while. Hence why I'm here with a step-by-step process with pictures on how it would work.

- A starting note would be that this would be the largest robbery at this moment. This robbery would be the hardest to rob due to cops, but also due to the items required and the amount of time it takes. That being said, let's hop into the process.
- To start the robbery process, the individual would walk to the left of the front door and be encountered with this staircase (https://i.imgur.com/FIEuefg.jpeg)
- When you walk up the stair case and follow the balcony, you find this door locked with an alarm above it. The individual performing the robbery would use an advanced lockpick on the door, sounding the alarm for PD. (https://i.imgur.com/tn66xrt.jpeg)
- At this point, there are two offices which belong to the "CEOs" and have access to the doors. The individual would "use" a raspberry to begin a hacking process (since raspberries are used through /terminal, and don't actually have a "use" feature it would make a perfect fit) and are thrown through a hacking process. (https://i.imgur.com/NpixVif.jpeg)
- Something I want to note, is down the hall from the offices is a door that would need to be permanently locked and not able to be picked with a lockpick (https://i.imgur.com/vweLRtU.png), this would skip a step in the robbery process if left unlocked.
- Once you go back into the lobby, you'll notice that this door next to the tellers area is now unlocked and can be walked through (https://i.imgur.com/PAFhzlx.jpeg)
- You are approached by another door with a keypad, in which you now have to use a chip (not a raspberry) to hack the door open (https://i.imgur.com/ditL2pK.jpeg)
- Once you have completed the hacking process, you are approached by the large vault door (https://i.imgur.com/8WFp55v.jpeg) which you would use a laser cutter (found during a low chance of Jewelry store robberies) to open the large vault door
- The final obstacle would be the last door, simply needing an advanced lockpick to break through (https://i.imgur.com/IhgjqD1.png)
- At this point you are in front of the vault which would contain 7 different robbery spots, each giving a set amount of gold bars (possibly similar to the newer bank truck, not the old one before people comment), (https://i.imgur.com/uI2Aq6Y.jpeg)

This being said, there is a couple things that would need to be kept in mind about this robbery. The PSB is where gold bars are sold, which is fine but the problem would be the ATMs on the inside are accessible and could easily be abused. At this point, whether it's a staff or development thing, this would need to be kept an eye out for and handled accordingly in whichever matter so people aren't selling/depositing all the money into their bank so they can't lose it.
Perhaps adding a 6 hour cooldown inbetween PSBs to prevent chain robbing (also would probably be less due to not having the desired amount of cops on at all hours)

- This would require 8 cops on duty, being 6 max criminals allowed in the bank so it is kept somewhat fair. Especially with raspberries, criminals could figure out on their own when is the best time to rob the bank.
- This bank would not be something that is robbed everyday due to the low chance of receiving a laser cutter from a Jewelry store.

**TDLR Changes - For Ben**

- Add a progression system into robberies.
- Stores have an expanded loot pool of a gold bar, items needed for a bank robbery, or random food
- Regular banks have no changes needed at this date
- Paleto Bank is available, has "4" safe boxes to rob instead of 3
- Jewelry Store now has a rare chance to drop a laser cutter after hacking the computer
- Pacific Standard Bank can be robbed using the laser cutter and an assortment of other items

Roughly with the above, it would follow this system of progression among criminals
Store > Fleeca Bank/Paleto > Jewelry Store > Pacific Standard Bank

**Reason:**
As simply put, this would open up a lot of different aspects for criminal RP (which at the same time, improves cop roleplay). For one, these changes (being the laser cutter) would force criminals to rob small scale things in order to hit the big jobs. This would prevent this being added, and four PSBs being robbed in a day. Overall, this would give criminals something to look forward to, in order to gain more money on weapons/cars/etc. This would definitely affect the economy if abused, hence why putting appropriate timers would be necessary.
This would improve cop RP as well by giving them something new and unique to respond to, and give them opportunities to create new SOPs on these larger banks and how they should be handled. At the same time, it's something new that people would be excited for and as a whole, I think the community would benefit from!

**Comment by GodyFromDiscord** [comment]
I love the ideas, would love if some others could give feedback on it as well

**Comment by twooot** [comment]
Not a big fan of the extra items in stores since stores are very well balanced where they are right now.

**Comment by ImArteria** [comment]
> Not a big fan of the extra items in stores since stores are very well balanced where they are right now.

At the time of making this suggestion, I dont think Thermite was craftable and the original intention was just to add some sort of progression system to robberies. The main things are PSB/Paleto bank

**Comment by ImArteria** [comment]
Since that this Github is pretty old I am making a few adjustments here in the comments section for these robberies. 
Store Robberies, leave the same. 
Bank Changes have already been done. 

**Paleto Robbery**
Would recommend to follow the changes I originally listed

**Pacific Standard Bank**
Process kept mostly the same except a minor change. No longer use a lockpick on the door that leads to the CEO offices, it now requires a person on the outside to join in. 

- A starting note would be that this would be the largest robbery at this moment. This robbery would be the hardest to rob due to cops, but also due to the items required and the amount of time it takes. That being said, let's hop into the process.
- To start the robbery process, the individual would walk to the left of the front door and be encountered with this staircase (https://i.imgur.com/FIEuefg.jpeg)
- A person on the outside must be staged up at the Vinewood Water and Power, located here (https://i.imgur.com/yVqiTFW.jpeg) to which they would use thermite on any three of these power boxes to cut the power, allowing access into the CEO offices 
- At this point, there are two offices which belong to the "CEOs" and have access to the doors. The individual would "use" a raspberry to begin a hacking process (since raspberries are used through /terminal, and don't actually have a "use" feature it would make a perfect fit) and are thrown through a hacking process. (https://i.imgur.com/NpixVif.jpeg)
- Something I want to note, is down the hall from the offices is a door that would need to be permanently locked and not able to be picked with a lockpick (https://i.imgur.com/vweLRtU.png), this would skip a step in the robbery process if left unlocked.
- Once you go back into the lobby, you'll notice that this door next to the tellers area is now unlocked and can be walked through (https://i.imgur.com/PAFhzlx.jpeg)
- You are approached by another door with a keypad, in which you now have to use a chip (not a raspberry) to hack the door open (https://i.imgur.com/ditL2pK.jpeg)
- Once you have completed the hacking process, you are approached by the large vault door (https://i.imgur.com/8WFp55v.jpeg) which you would use a laser cutter (found during a low chance of Jewelry store robberies) to open the large vault door
- The final obstacle would be the last door, simply needing an advanced lockpick to break through (https://i.imgur.com/IhgjqD1.png)
- At this point you are in front of the vault which would contain 7 different robbery spots, each giving a set amount of gold bars (possibly similar to the newer bank truck, not the old one before people comment), (https://i.imgur.com/uI2Aq6Y.jpeg)


**New Robbery Addition - Classified Documents Heist**
This robbery would essentially be a robbery on the "old FIB Building". It has the interior and everything already so it's pretty set up (https://i.imgur.com/VCZcdmG.png)
- Individuals would enter from underneath, https://i.imgur.com/8s4kNJq.png , and have to navigate through the destroyed building
- The end goal is the Server room, where they can start plugging decryption keys in to "hack into" FIB's network where classified documents are ( https://i.imgur.com/LR12Ccm.jpeg ) 
- Once they use the decryption keys on FIB's system, they would receive "Classified Documents" items which if they leave the area safely, could sell them at a specific place related to GTA lore
- Since in the Lore, Lester is about "The government is watching us" and conspiracy theories, it would be the perfect place to sell these documents ( https://i.imgur.com/TX2fFEY.jpeg )

**Comment by ImArteria** [comment]
Honestly random thought as I was looking through my githubs. A train heist would be pretty cool.
It's always moving. Different spots all parts of the day. The rewards, I don't know but would still be cool.

**Comment by coalaura** [comment]
Paleto bank is now robbable with the extra benefit of having 1 more spot to pick valuables from (basically a 30% increase in loot)

**Comment by coalaura** [comment]
I'm gonna close this one as the majority has been completed and i'd recommend making a github JUST for pacific standard
