### ISSUE TITLE
QOL Changes for Midnight Tuner shop

### ISSUE THREAD

**Issue by sameerv95** [InZidiuZ/op-framework-issue-tracker#2404]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
1. Add 'Upgrade' command to Tuners. 
2. Add new Vehicles to midnight tuner
3. Decrease the prices of performance upgrades at tuners.
4. Bring some custom visuals upgrades which can be found only at midnight tuners.
**Reason:**
Why would your suggestion be a good change to the framework?
1. As a mechanic can check all the upgrades done on a particular vehicle but tuners can't use that command. It will really help tuners to check what all upgrades has been done on a vehicle and increase the RP rather then always putting the vehicle on deck and check everything one by one.

2. Can developers add some more vehicles to tuner? as their are many more vehicles in GTA online which are needed in Midnight tuner as it got only 19 vehicles options to choose from.

3. Can developers decrease the prices of performances upgrades at tuner by 30/20% it will give more RP to Tuners as people will choose midnight tuners rather then going to benny's for performance upgrades. And IRL tuners does both visuals and performance upgrades.

4. Can developers bring some 'Only Midnight Tuner' visual upgrades to shop? something which we cant get from Benny's or LS customs like Horns or some custom Body work. Like tuner has level 5 engine which we cant find in Benny's.

**Comment by twooot** [comment]
1. I don't see any need for a command
2. No, the point of the tuner shop is to sell the cars of the tuner DLC and upgrade/customize cars NOT be another dealerhip
3. No
4. Nope
5. I've added the tuner job to have access to that command
6. Like i said in point 2.
7. No, there is a reason why performance upgrades are not reduced
8. No
