### ISSUE TITLE
Adding entries for items lost after respawning

### ISSUE THREAD

**Issue by ItsGUARDIAN** [InZidiuZ/op-framework-issue-tracker#2405]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.
Adding a database entry for the items someone looses when taking a respawn so that it can be later added as a suggestion for the admin panel logs too if this feature is added.
**Reason:**
Why would your suggestion be a good change to the framework?
Most of the times it will be useful when a cheater kills someone and they take respawn to reimburse them or someone dies due to glitches and game crashes or a similar situations.

**Comment by twooot** [comment]
added a log entry for it
