### ISSUE TITLE
[game/radio] Persist Radio Frequency per radio

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2406]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
- Store the most recent radio frequency per radio  
- On Login the radio remembers the frequency
- Radio can be "used" from inventory to set as the active radio
- Add current frequency in hover-over description
- Frequency to be hidden when streamer mode is on. (or add /freq_hide command)
- PD/EMS Radios retain the unlootable flag

**Reason:**
Why would your suggestion be a good change to the framework?
- It makes sense that a radio would remember it's channel regardless of your naps
- Would increase value of radios by adding a reason to carry more than one
- Makes the item into a loot risk as a looter will gain the frequency (PD/rival gangs/etc)
- Would allow people to preset radios for distribution at events, etc.
- Would allow for cold drop radios for RP i.e. "go to this location and take the radio out of the trash and wait for more instructions"
- Streamers would be less prone to revealing the frequency on streams

**Comment by vol5** [comment]
This is a damn good idea.

**Comment by Mugdha57** [comment]
damnn this is a really OP suggestion...

**Comment by twooot** [comment]
I like the idea, BUT what if you have multiple radios on you? When you do /freq which one would remember the freqency? On login which frequency would it use if you have multiple?

**Comment by vol5** [comment]
Have it default via left to right, top to bottom inventory prio. So, if radio A is in Hotbar slot 1 and radio B is in Hotbar slot 5 it then remembers freq A on login.

**Comment by MetaHatter** [comment]
> I like the idea, BUT what if you have multiple radios on you? When you do /freq which one would remember the freqency? On login which frequency would it use if you have multiple?

- Only one radio would be active at a time.  
- "use" the item to make it the active radio. 
- /freq would change the "active" radio and store it until it's changed.
- If a unique radio id could be assigned, similar to a license plate, a command could be added to allow hotkey selecting it. (i.e. /radio_select Q3E5RT23)

Login could either use the last "active" radio, or simply require the user to "use" the radio they want upon login.

**Comment by twooot** [comment]
> "use" the item to make it the active radio.

what about the radio ui tho

> If a unique radio id could be assigned, similar to a license plate, a command could be added to allow hotkey selecting it. (i.e. /radio_select Q3E5RT23)

That sounds like a pain and an ugly solution

**Comment by MetaHatter** [comment]
> > "use" the item to make it the active radio.
> 
> what about the radio ui tho

Radio UI for the "used" radio would show

> > If a unique radio id could be assigned, similar to a license plate, a command could be added to allow hotkey selecting it. (i.e. /radio_select Q3E5RT23)
> 
> That sounds like a pain and an ugly solution

Open to other suggestions. Would assume most people would just MMB click or "use" the radio they want so may not be necessary at all.

**Comment by twooot** [comment]
For now i've added it so the last frequency you were on is remembered for each character and you rejoin it when you load back in

**Comment by coalaura** [comment]
Ok i dont really think i'd want the frequency to be on the radio tbh. With it saving on the character i think that already basically does the whole remembering part
