### ISSUE TITLE
Zombie Pills causing wanted level when a suppressor is used

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2407]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? yerrrr

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/scufflord/

**Summary:**
Write a short summary of what you are experiencing.
When using a zombie pill with a suppressed weapon it causes the SWAT gear zombies to act as normal GTA V cops and trigger a wanted level. 

**Steps to Reproduce:**
Put suppressor on weapon
Enter z pill
Shoot

This was specifically done with an AP with a suppressor and extended mag on it, not clear if it will occur with other suppressed weapons.

**Expected Results:**
What are the expected results?
Not to get a wanted level

**Actual Results:**
What are the actual results?
Mini-map starts flashing blue and red, SWAT zombies get marked as PD on the mini-map, and a wanted level appears. 

## Additional Information

**Screenshots:**
n/a

**Game Resolution:**
1920x1080

**Player Data:**

https://cdn.discordapp.com/attachments/845947698628001862/1003051403067011242/unknown.png

**Server:**
What server/community did this issue occur in?
Legacy Roleplay #1 International 

**Notes:**
For anything else noteworthy.

**Comment by scufflord** [comment]
After some further testing we're only able to replicate this issue with the AP, and the wanted level bug even occurs outside of zombie pills.

**Comment by InZidiuZ** [comment]
This should no longer happen.
