### ISSUE TITLE
Adding more utility to [Basic Repair Kits]

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2408]
Assurance: Yes

Summary: Give each mechanic shop a deconstruction table for basic repair kits. 

Deconstruction: (Basic Repair Kit)

[Output]
> 1 Scrap
> 1 Aluminum

[Lost Example](https://cdn.discordapp.com/attachments/876537143391051776/1003259369095450694/unknown.png)

Reasons:

- Increases mechanic interaction
- converts a less used item into a material gain for the economy
- makes congruent sense for mechanics to handle the deconstruction of said item
- gives more value to that item itself, considering it hardly gets used in comparison with the advanced repair kits

**Comment by CloudTheWolf** [comment]
I feel like something that players can easily buy shouldn't really be "Deconstruct-able"

**Comment by scufflord** [comment]
On the other hand, maybe a way to combine multiple basics into an advanced repair kit? Throw a pipe wrench and a hammer in and it upgrades a basic to an advanced (just an example)

**Comment by twooot** [comment]
done

**Comment by vol5** [comment]
> On the other hand, maybe a way to combine multiple basics into an advanced repair kit? Throw a pipe wrench and a hammer in and it upgrades a basic to an advanced (just an example)

I like this. Though I do feel it should be one or the other to upgrade since requiring one hammer and a pipe wrench might be to requirement heavy to the point where it would go unused. or combining them into each other... What did you end up settling with @twooot
