### ISSUE TITLE
Thermite Crafting

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2409]
Assurance: Yes

Summary: Add more utility to mining by giving people the option to break down gems for a chance to get iron oxide AKA (Rust). You would then use this rust to make thermite.

Deconstruction: (gems)

[Requirements]
> [Deconstruction Bench?](https://cdn.discordapp.com/attachments/876537143391051776/1003279762682298368/unknown.png)
> Gem of any type
> Hammer (has a chance to break each use)

Chance to get Rust from breakdown: 5-10%

Morganite: lottery gets run 3x
Ruby: lottery gets run 2 times
Sapphire: lottery gets run 1 times
Emerald: lottery gets run 1 times

[Thermite Crafting Recipe]
> 1 Rust (Iron Oxide)
> 1 Aluminum

Reasons:

- Makes the world more dynamic

- Adds more utility to mining considering its penalties

- Adds more depth to mining and crafting in general

**Comment by CloudTheWolf** [comment]
I feel like, if anything it makes more sense for players to use Scrap or Steel to get rust.

This could also encourage more people back to Scuba.

There could also be different ways to make it that could impact the amount / quality 

Eg 

Method 1: 
Combine scarp with Iron sulphate to get a low Iron Oxide Yield. Iron sulphate can be found in fertilizer so also adds a new use for this item

Method 2: 

Using a battery, Water and Scarp to perform Electrolysis, players then need to Filter and Bake the output to get the rust.
Once again, adds new uses for Items. and could be an "average" Yield

Method 3 

Use Steel to make Steel Wool (Which could be made at the forge) (or just use steel), then combine with either Hydrogen Peroxide (New Item) or Salt Water (Collected using an empty water bottle at the beach) then again Filter and bake, depending on the oxidizer used, could impact the quality / yield

**Comment by twooot** [comment]
bruh idk chemistry but this sounds nice

**Comment by vol5** [comment]
> I feel like, if anything it makes more sense for players to use Scrap or Steel to get rust.
> 
> This could also encourage more people back to Scuba.
> 
> There could also be different ways to make it that could impact the amount / quality
> 
> Eg
> 
> Method 1: Combine scarp with Iron sulphate to get a low Iron Oxide Yield. Iron sulphate can be found in fertilizer so also adds a new use for this item
> 
> Method 2:
> 
> Using a battery, Water and Scarp to perform Electrolysis, players then need to Filter and Bake the output to get the rust. Once again, adds new uses for Items. and could be an "average" Yield
> 
> Method 3
> 
> Use Steel to make Steel Wool (Which could be made at the forge) (or just use steel), then combine with either Hydrogen Peroxide (New Item) or Salt Water (Collected using an empty water bottle at the beach) then again Filter and bake, depending on the oxidizer used, could impact the quality / yield

This retains the main goal while utilizing preexisting items in a new way. I like this. Like T said not a chemist but I fuck with it.

**Comment by twooot** [comment]
![yes](https://raw.twoot.org/GUnAroCa13.png)

done

**Comment by vol5** [comment]
HOT
