### ISSUE TITLE
Suggestion - VU Improvements

### ISSUE THREAD

**Issue by Spider-07** [InZidiuZ/op-framework-issue-tracker#2412]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Need Some Improvements For Vanilla Unicorn : 

1. It is better to increase the salary that I get after a few minutes.

2. Many times I see there are many locals in the bar. So it is better if you turn off the local auto-response from the bar.

3. Added some food ( Sandwich and S'mores) to the bar. It would be better if the food could be changed to add burger and coke.

4. Add a music system to the bar.

**Reason:**
Why would your suggestion be a good change to the framework?

We think doing the above can generate a lot more RP with vanilla unicorns.

**Comment by twooot** [comment]
> It is better to increase the salary that I get after a few minutes

No

> Many times I see there are many locals in the bar. So it is better if you turn off the local auto-response from the bar.

I removed the locals from the bar

> Added some food ( Sandwich and S'mores) to the bar. It would be better if the food could be changed to add burger and coke.

This has already been done

> Add a music system to the bar.

You can purchase a boombox at the tool store down the road

**Comment by Spider-07** [comment]
> > It is better to increase the salary that I get after a few minutes
> 
> No
> 
It would be better to increase the salary a little

> > Many times I see there are many locals in the bar. So it is better if you turn off the local auto-response from the bar.
> 
> I removed the locals from the bar
> 
Thank You

> > Added some food ( Sandwich and S'mores) to the bar. It would be better if the food could be changed to add burger and coke.
> 
> This has already been done
> 
No soft drinks and snacks here. There are many people who don't drink alcohol, they want soft drinks, snacks so adding some soft drinks is better.

> > Add a music system to the bar.
> 
> You can purchase a boombox at the tool store down the road
Now we are doing this with a boombox. Adding a music system to the front bar is good

Another thing is that the main door is always open after restarting the server, so it is better to keep this door closed. And everyone can use this bar shop but it would be better if it is made in such a way that only bar staff can use it.

![image](https://user-images.githubusercontent.com/103858728/182969630-bad07da1-32aa-4d7a-a023-cd13bd657c6f.png)
![pngwing com](https://user-images.githubusercontent.com/103858728/182972603-ee785be9-0cc9-43b7-8b08-0ca527095ded.png)
![pngegg (5)](https://user-images.githubusercontent.com/103858728/182972606-8e8230c2-9a2b-43fd-a196-0fa117315bae.png)
![pngegg (4)](https://user-images.githubusercontent.com/103858728/182972608-62d363de-c85a-4a6d-83e2-85ddfed28edd.png)
![pngegg (3)](https://user-images.githubusercontent.com/103858728/182972610-d46f2a93-b083-4c54-ab1f-c79c200493c6.png)
![pngegg (2)](https://user-images.githubusercontent.com/103858728/182972611-af71e32f-f5e7-4c16-88a1-aa1655c575ee.png)
![pngegg (1)](https://user-images.githubusercontent.com/103858728/182972615-6e4d763e-20fc-4e39-adbc-5ad7ae44ae29.png)
![pngegg](https://user-images.githubusercontent.com/103858728/182972617-065a3517-91a9-4f24-b53d-c890d45bafc8.png)
![pngwing com (9)](https://user-images.githubusercontent.com/103858728/182972620-6227ee75-e174-43fd-b2ef-439149d6cb83.png)
![pngwing com (8)](https://user-images.githubusercontent.com/103858728/182972622-37c3f593-d47c-4632-9a40-9b63dd801e46.png)
![pngwing com (7)](https://user-images.githubusercontent.com/103858728/182972623-41aed13a-f793-4a99-a83a-95a62fad7746.png)
![pngwing com (6)](https://user-images.githubusercontent.com/103858728/182972627-91ab88df-4215-455c-913d-0c4f0754498e.png)
![pngwing com (5)](https://user-images.githubusercontent.com/103858728/182972628-36ece529-bd9f-4f5f-9115-f8024ce80513.png)
![pngwing com (4)](https://user-images.githubusercontent.com/103858728/182972630-25842053-b7d0-497e-804d-0880f0b8834b.png)
![pngwing com (3)](https://user-images.githubusercontent.com/103858728/182972634-554112ff-1244-4cb7-bee2-2690ccae1453.png)
![pngwing com (2)](https://user-images.githubusercontent.com/103858728/182972638-c9af7a16-32e0-4aca-981f-608e3d0ca0b4.png)
![pngwing com (1)](https://user-images.githubusercontent.com/103858728/182972641-b88ff076-5f7f-4dec-bc13-f313a050c868.png)
