### ISSUE TITLE
Suggestion - Improvements RP

### ISSUE THREAD

**Issue by Spider-07** [InZidiuZ/op-framework-issue-tracker#2413]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

There is no mechanic shop in sandy. If the car breaks down on that side of sandy, you have to go to that town. So it is very good if you open the mechanic shop of sandy. This will make Sandy people's life easier and increase some more RP.

**Reason:**
Why would your suggestion be a good change to the framework?

This will make Sandy people's life easier and increase some more RP.

**Comment by twooot** [comment]
There used to be a mechanic shop but it was removed

**Comment by Spider-07** [comment]
Open it again
