### ISSUE TITLE
Suggestion - Some Business Ideas

### ISSUE THREAD

**Issue by Spider-07** [InZidiuZ/op-framework-issue-tracker#2414]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

Let's open a gemstones business. Basically, a business can be opened, those companies will buy all the gemstones from people and the company employees can sell them. And this company will also have ring crafting under it, so if anyone wants to buy a ring, then they have to buy from this company.

This company will have 3 posts an owner, manager, gem collector, etc. So the job of gemstone collectors is that gemstone collectors will buy gemstones from common people they will give them to the manager and take from the manager the amount of money he spent. Now the manager will collect the gems from all the gem collectors and bear his expenses. Now the manager will give all the gems to the owner and the owner will bear the cost of the manager. Then the owner will sell all the gems (the owner's office will have a spot for selling gems and only that spot can be sold). Now the owner will pay the salaries of all his officers from the money that will be available from this. And the manager can be given other work, the manager can do ring crafting and this ring crafting will also be done in this office.

Note: Another business can be opened in the same way. And their work will be to buy all skins, meat, fish, and fruits from people and they will sell them.

**Reason:**
Why would your suggestion be a good change to the framework?

This will bring innovation to the city and will see a lot of RP.

**Comment by twooot** [comment]
You can open this company through rp, i don't want to job lock Gems and rings
