### ISSUE TITLE
Sync in game radio stations globally

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2415]
Assurance: Yes

Summary: Making in-game radio music from cars and random ambient backgrounds the same. What I mean by this is when two people are in the car, and you play the in-game radio stations. You hear a completely different song. If there was any way to sync the radio songs globally, I feel people would actually listen to the radio.

This is a minor request but would be a dope value add for old heads of the game. If it's not possible all good but I would assume it is and is like that in gta online. Where the music is the same.

Reasons:

- Makes the world more dynamic

- This is the main reason that a core game feature like the radio is hardly used and syncing it would fix that

- improves the game world experience

**Comment by InZidiuZ** [comment]
This is something that would need to be done by FiveM and they've stated multiple times that it's very difficult unfortunately. ([Here's](https://cdn.discordapp.com/attachments/720305303182115008/1004885162544336896/Capture.PNG) one example I found.)
