### ISSUE TITLE
Suggestion - Vehicle Radios Default To Off

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2416]
**Assurance:**
Yes

**Summary:**
When players enter a vehicle for the first time after purchasing or pulling out from a garage the radio should start as turned off.
If not for all vehicles, at least for vehicles in the Emergency class. 

**Reason:**
When entering a vehicle for the first time the radio always turns on, this is an issue for EMS / PD as the Radio toggle is also the toggle for the emergency lights. 

I'm sure it used to be like this but can't remember when it changed

**Comment by twooot** [comment]
Imagine having radio volume turned on

**Comment by twooot** [comment]
done
