### ISSUE TITLE
Craftable Electronics

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2417]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yerrrrr

**Summary:**
This has multiple parts to it, so it may be a little confusing. I think adding the ability through a crafting location somewhere on the map to add the ability to combine a spare phone, radio, and raspberry pi into a device scanner would be pretty cool. Could either be done by combining those three items together, or by scrapping them to get spare parts from each one (antennae from radio, hacking parts from the raspberry etc) and then combining those parts somewhere else to be able to craft a device scanner. Could also open this up as a way to craft different electronics by scrapping those devices, and then being able to craft things like raspberry's and chips. 
 
 Also add the ability to break down chips and raspberry pi's to be able to get some additional decryption keys. This will help increase the amount of chips on the street, but will keep them locked behind roleplay because you will need to know where to go in order to break down those parts. 

**Reason:**
Why would your suggestion be a good change to the framework? 

I feel like this will add an easy means of getting rid of the sudden influx of spare radios and phones from zombie pills popping up, and allow people to more easily combat FIB/detective work through easier access to device scanners and other electronics that are key to criminal activity. With the current system of banks being the main source of keys for the entire city it is limiting peoples ability to get them, and adding the breakdown location it would make it a bit easier for those doing activities that need them to be able to get them if they aren't skilled enough to be able to do a bank robbery.

**Comment by twooot** [comment]
done
