### ISSUE TITLE
add notice for everyone

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2419]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Add notice command for everyone not just super admin and currently we can add only three lines in it instead if you make it html format and add limit to words instead of rows/columns it would be great.

**Reason:**
Why would your suggestion be a good change to the framework?
This would actually help a lot of restaurant's and also enhance to RP experience of everyone on the server like some things can't be just done by /me.

**Comment by CloudTheWolf** [comment]
Maybe this could be done with a "Sign Post" item

**Comment by twooot** [comment]
No this will be abused
