### ISSUE TITLE
Knockouts

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/op-framework-issue-tracker#242]
**Name:**
Blanket#0404

**Summary:**
Instead of punches resorting immediately to a 'death' message it would instead 'knock' the player out. Let's say there's a slight chance that punching will actually kill a player but a larger chance that punching will instead rag-doll the player onto the ground for a set amount of time (2 minutes or something like that) before they stand back up. 

**Reason:**
This would prevent 'off-spawn' minges from attacking and killing new players.
It would also allow for a bit more realism, I don't believe a couple punches should always force you to be hospitalized all the time, having the 'knocked out' timer would allow people to role-play being knocked out and regaining conscious rather than having to be carried to Pillbox every time.

**Comment by Ninjapex** [comment]
+1 Would also prevent those crazy prison fights resulting in deaths. :)

**Comment by Scrubject** [comment]
Was thinking the same thing in my issue below. I think it's on his radar as it's been up for almost 2 weeks.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
