### ISSUE TITLE
Suggestion - Add more Purchasable Props

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2420]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Add more probs for players to buy that could enhance RP, and allow Criminals to use them in creative ways.

These could include:

 - prop_barrier_work06a
 - prop_barrier_work06b
 - prop_barrier_work01a
 - prop_barrier_wat_03b
 - prop_ld_barrier_01

**Reason:**
Why would your suggestion be a good change to the framework?
This would enhance RP and add more Items to the city

**Comment by InZidiuZ** [comment]
This has now been added. They are available for purchase in the tool store.
![Bh2KsMiV](https://user-images.githubusercontent.com/22295402/183301683-db28949c-fbe3-4ad6-b9fe-f857b7f6f18c.jpg)
