### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by yoginhk** [InZidiuZ/op-framework-issue-tracker#2421]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
-Add a 2sec timer to retrieve the vehicle in the garage
-change mining to places near the water bodies

**Reason:**
Why would your suggestion be a good change to the framework?
-timer because I don't know whether it happens with other players or only with me i.e. if I press a button once while in the menus it registers as two click 
-Gemstones are mostly font near water bodies irl so...

**Comment by twooot** [comment]
> Add a 2sec timer to retrieve the vehicle in the garage

No, i did however change it so you cannot press the button twice while its still retrieving

> change mining to places near the water bodies

There are already other mining places, you will however have to find them by yourself
