### ISSUE TITLE
EDM Garage

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2422]
Assurance: Yes

Summary: Put a garage outside edm. 

I feel it would be of great benefit to the buying experience at EDM if there was a garage to store vehicles. It would be nice to buy a car and drive off without worrying about the one you left behind.

Reasons:

- Convenience

**Comment by King2704** [comment]
I like this

**Comment by superiorchicken007** [comment]
I don't want to be that guy but there is a garage a block and a half away. You can park there, run to EDM or get a taxi and then buy a car to drive off.

**Comment by scufflord** [comment]
As an alternative, maybe give the user the option to have the vehicle delivered from PDM/EDM directly to their garage instead of spawning and having to be driven if they don't want to.

**Comment by vol5** [comment]
> I don't want to be that guy but there is a garage a block and a half away. You can park there, run to EDM or get a taxi and then buy a car to drive off.

You make a good point LMAO

**Comment by twooot** [comment]
yeah no
