### ISSUE TITLE
New Drug running process and consumable - Moonshine

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2423]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? YERRRRR

**Summary:**
I'm a redneck with a muscle car obsession, and I feel it in my bones that I must carry on the legacy of my NASCAR driving forefathers... I have the need for moonshine! This first link will be a DIY moonshine guide to cover the basics of how the process works, and what items will need to be introduced in order to make the mash.

https://www.northstills.com/how-to-make-moonshine-diy/

It goes into pretty solid detail about how it works. Weirdly enough I found a moonshine still prop under Olympic Freeway that already is included in GTA so we can use this for it. 

https://cdn.discordapp.com/attachments/845947698628001862/1005236778615177358/unknown.png

Essentially how I envision it to work is one of two ways - option one allows the player to gather materials - metal, copper piping, a barrel etc - and create a moonshine still inside their house, or option two like my kin used to do it... they go somewhere down in a holler and let nature help with the process. 

Once the still has been placed players can use a grill to formulate the mash, and then run it through the still. The distillation process should take a while - allowing BCSO to possibly stumble upon the still out in the wild and thus leading to interaction between PD and criminals. I'm thinking 5-10 minutes. If a batch is cooked inside a house, then I think it should produce half of whatever the normal 'shine run would make if you made it out in the wild - to encourage roleplay. 

Once complete, the player will either have 1 full run done if it was done outside, or half a run done if it was done inside - so they'll have to make a second batch of mash and run it through the still again. The still can degrade with usage - say 20 runs before the pipes start to corrode and you have to rebuild the still all over again. 

The player then will take their full run - represented by a case full of mason jars -  to a remote liquor store or bar. I've included a screenshot of a possible location, although the back door of the Yellow Jack bar in Sandy Shores may be a good alternative. This will start a run that combines parts of the cocaine import process and an oxy run. The player must drive from location to location dropping off a jar at 8-10 locations all over Blaine County with a time limit for a run of 15 minutes. As soon as the run starts PD should have a chance at getting a ping at any of the drop locations for suspicious activity - just like other drug sales. When the player arrives at a location, they'll find a local waiting in a car, and they deliver it to the local, with a chance for it to instead be a delivery to a door on a house or other building in Blaine County. Each run MUST be done in a player owned car - not on a bike. 

https://cdn.discordapp.com/attachments/845947698628001862/1005263174385274890/unknown.png

I'm not quite sure what the payout should be exactly for this, but I do like the concept from oxy of locals attempting to rob you for the 'shine, so perhaps that could be included as a possibility thus allowing players to potentially keep some of their product for consumption later on. Each drop off should pay a small sum, with the run ending back at the starting point for a larger total payout for completing the run.

The benefit of consuming the moonshine should be both EXTREMELY beneficial while also having a pretty major drawback. Make each jar of shine have two uses each, with the first use inducing some mild alcohol effects that are already in the city, providing a damage resistance buff, and active health/armor regeneration up to 50% each. Nothing screams terrifying like an angry man with a shotgun chugging jars of moonshine and charging at you, and they don't call it firewater for nothing. Using the same jar twice rapidly will amplify the drunk effect and provide a 100% regen and an increased percentage damage resistance.

**Reason:**
Why would your suggestion be a good change to the framework? I feel this would be a good addition to the framework because it's something truly unique to Legacy - I've never heard of running moonshine anywhere else. It takes parts of processes that people already enjoy every day and combines them together, and provides new roleplay for BCSO. Plus, who doesn't like to drink a little bit of 'shine every once in a while?

**Comment by vol5** [comment]
It seems like a reasonable value add. But, the realtor inside me would prefer for this to be exclusive to house ownership while it may not make the most thematic sense. Either way, Moonshine would be huge. The Red Dead system could kind of be copied in a sense. Where you have the still and you need ingredients. It takes an extended period of time before the process is complete. Then you go on sell runs. I do like the idea of something similar to the oxy runs with selling jars would be fucking DOPE. This is a fitting idea for Legacy imo and BCSO would love this shit.

**Comment by twooot** [comment]
Ok, the majority is implemented, I looked at the tutorial you linked and used the prop that you found but went a bit off script and implemented the making of moonshine how I felt it seemed cool/nice to do. It is currently a single location, but made in a way that more locations can be added. Ingredients, etc. have to be found out in RP as always. Selling will be a soon:tm: but for now, it acts like a strong alcohol (it is consumable)

**Comment by twooot** [comment]
![oi fam ye](https://i.coalaura.org/boQigusi16.png)

**Comment by twooot** [comment]
selling is done too
