### ISSUE TITLE
Anchor bugged

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2424]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/KaiEagle

**Summary:**
Write a short summary of what you are experiencing.
When you try to anchor a boat it will get anchor but also will disable the boat and won't be drivable again even if you disconnect the anchor the boat won't budge even if you fix it with admin command :/

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
When anchoring the boat make it so it doesn't get disable and still driven after disconnecting the anchor.

## Additional Information

**Video:**
If suitable, include some screenshots.
https://streamable.com/5q4q7g

**Server:**
What server/community did this issue occur in?
It was on test server but it's bugged on live server's too.

**Notes:**
For anything else noteworthy.
If you need log of it do let me know.

**Comment by twooot** [comment]
Fixed
