### ISSUE TITLE
Disable Local Traffic on Lake Vinewood Estates

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2425]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yerrrr

**Summary:**
We own all of the houses on this street on the international server, and the local cars that come through have a bad habit of piling up on each other and then randomly deciding to either explode or phase through walls and fences. is there any possibility of making it so locals dont drive up here? I had a pileup of 20-30 cars I had to shove off the edge of the hill yesterday cause it got so bad. Picture attached below of the road in question. 

https://cdn.discordapp.com/attachments/850128950818373673/1005627165594898544/unknown.png

**Reason:**
Why would your suggestion be a good change to the framework? Would decrease load from having a bunch of blown up or abandones local vehicles, and would improve quality of life for people attempting to roleplay in this area, as it's a very high traffic area.

**Comment by InZidiuZ** [comment]
I've made them not spawn on that street now, though they are still able to drive up from the main road. However, this should _hopefully_ reduce the amount of vehicles that pile up. I tried doing some hacky stuff with the navmesh with scripts on the intersection as well, but I wasn't able to get anything nice going.

To get rid of the cars we'd probably have to remove the navmeshes completely by streaming new assets, which is something you'd have to suggest on the assets issue tracker.
