### ISSUE TITLE
Increase the Quantity of  Aluminum And Steel And Decrease Scrap From Chop Shop

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#2426]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Currently, after the changes made to the mechanic repairs, it requires more Steel and  Aluminum for repairs but the availability of both materials is relatively way less when compared to scarp 
**Reason:**
Why would your suggestion be a good change to the framework?
it will balance the repair cost as currently the demand of al and steel is quite more and the supply is way less

**Comment by MetaHatter** [comment]
There are quite a few other ways to get those materials in city already.  I feel that it just hasn't been long enough for people to discover or leverage the potential profit of those formerly overlooked activities provided by the new demand curve.  

I say we give it a bit of time to see how the other sources balance before taking action.

**Comment by InZidiuZ** [comment]
While what you suggested wasn't exactly done, some balancing changes to the framework has now been made. This should also make chop shop a better activity.
