### ISSUE TITLE
Addition of locker at the Burger Shot. 

### ISSUE THREAD

**Issue by jethiya** [InZidiuZ/op-framework-issue-tracker#2428]
**Summary:**
addition of lockers for the employees at the Burger Shot. 

**Reason:**
https://imgur.com/P5p6JyK

**Comment by KaiEagle** [comment]
Well locker for burgershot will be great as I make to employee's sign Employee Contract and make them sign it and have to place it home so it makes it really difficult to separate it from the things I own and there are lots of Contrats so if there is a locker inside BurgerShor it would  make it really easier for us to keep burgershot related things there.

**Comment by MetaHatter** [comment]
That image is not a reason. 

Please format any suggestions properly.

Additionally, I am not sure that BurgerShot employees need the storage.  They're not holding hundreds of pounds of materials like mechanics.

**Comment by twooot** [comment]
I have said this many times already, burgershot is not getting a locker there is no need for one
