### ISSUE TITLE
Garage at/near Trash HQ

### ISSUE THREAD

**Issue by taylorwiffed** [InZidiuZ/op-framework-issue-tracker#2429]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yup! 

**Summary:**
Write a summary of what your suggestion is about.

My suggestion is to add a garage to or near Trash HQ. 

**Reason:**
Why would your suggestion be a good change to the framework?

Especially with everyone getting a starter car when they fly in for the first time, garbage is the one job that gets kinda screwed in the car category. Let me explain: 

Trucking: You own your truck. You can leave your personal car in the garage and get out your Phantom or whatever truck you have.
Taxi: Same, you own your taxi. You get it out of the garage and you are good to go. 
Journalist: You buy a Weazel News van, so you have a vehicle to just take out and use. 
Delivery: You have the garage near old EDM that is one block away. Easy peasy.

Then there is trash. The closest garage is Maze Bank and that is not close in the sense that the GoPostal one is. 

So, the benefits: 
- Personal cars won't poof anymore and cost almost an entire trash run or more to retrieve
- People are stealing less cars outside trash. This helps them potentially avoid getting a record that would stop them from getting a whitelisted job
- People will hopefully stop parking their personal cars all over the trash return which ends up making that process more difficult.

[Trash HQ map](https://legacy-roleplay.com/index.php?attachments/garbage2-png.195/)
[Delivery Job map](https://legacy-roleplay.com/index.php?attachments/deliver2-png.198/)

**Comment by MetaHatter** [comment]
Agree there likely should be a garage near there.  I wouldn't have it immediately near it due to the existing traffic. Perhaps by the Ammunation... like this?
![2022-08-08 01_28_29](https://user-images.githubusercontent.com/84351858/183345797-e8aedede-8612-4790-bdba-a378cf60c949.png)

**Comment by taylorwiffed** [comment]
Yo yes! It could be like we are getting our cars out of that warehouse!

**Comment by CloudTheWolf** [comment]
This could double as a parking area near the Trucker station when you go to buy a phantom

**Comment by twooot** [comment]
Done
![img](https://raw.twoot.org/QOTEdIJa10.png)
