### ISSUE TITLE
Addition of blip for Mirror Park Repair And Remove  Blip of Fly Wheels And Additional Material Buying Computer And Locker in Front Side of  Mosley

### ISSUE THREAD

**Issue by ayushpandit99** [InZidiuZ/op-framework-issue-tracker#2430]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.

As Mirror Park Repair Shop Just Got Added Blip for same is not yet added Also  Fly Wheels(Repair Shop2 ) got removed but its blip is still there 
Regarding Mosley's Addition 
Add Material Buying Computer In Front Side[ik this should be another issue ]

![20220808120015_1](https://user-images.githubusercontent.com/68945345/183354730-65219609-6f0d-4a48-8f37-be5c447dafe2.jpg)

Add Locker In Front Side
![20220808121121_1](https://user-images.githubusercontent.com/68945345/183355436-93d615f1-ed76-427e-b219-63fb5502c1ae.jpg)

**Reason:**
Why would your suggestion be a good change to the framework?
As blips are not updated and for Mosley's the front side is used most and the current material buying computer and lockers are in the backside so the addition of this would help save quite a lot of time for Mosley's employees

**Comment by InZidiuZ** [comment]
All of this but the lockers have now been done.
