### ISSUE TITLE
New Bean Machine menu items

### ISSUE THREAD

**Issue by InZidiuZ** [InZidiuZ/op-framework-issue-tracker#2432]
**Summary:**
Add the new menu items [as suggested in ticket-0366](https://www.inzidiuz.com/u/2JV7Hg7D.png) in the discord guild.

**Comment by taylorwiffed** [comment]
Maybe also iced coffee/cold brew?!

**Comment by HellRaiser5** [comment]
add 1 or 2 food items. make it good effective
