### ISSUE TITLE
Add Phone Favorites line for Videogeddon Arcade

### ISSUE THREAD

**Issue by RustyWaters07** [InZidiuZ/op-framework-issue-tracker#2433]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
Would like to add to pre-programmed favorites a line for Videogeddon that people can call for food/drink delivery
**Reason:**
Why would your suggestion be a good change to the framework?
People already hit us up for deliveries; this would give us the same advantage that Burger Shot and Bean Machine have currently so we don't have to advertise our personal numbers on Twitter.

**Comment by Stephy-baby** [comment]
This would be amazing for us

**Comment by twooot** [comment]
but the arcade is not supposed to be delivering food???

**Comment by RustyWaters07** [comment]
never saw that in the fine print...any particular reason we shouldn't be able to?

**Comment by DaxterPancake** [comment]
Because you are an arcade that already has the exclusivity of the VR games and custom food just for you. It makes no sense for you to ALSO be a good delivery place. We try not to have one place monopolising everything.

**Comment by RustyWaters07** [comment]
I can respect that. Hadn't really thought of it like that but it makes sense. Thanks anyway!
