### ISSUE TITLE
Add some hypebeast stuff and face tattoos like some rappers faces. Also add some more hypebeast clothing

### ISSUE THREAD

**Issue by darshitmachhi** [InZidiuZ/op-framework-issue-tracker#2434]
Add some hypebeast stuff and face tattoos like some rappers faces.
Also add some more hypebeast clothing

**Comment by MetaHatter** [comment]
This isn't the proper github for clothing requests. Please submit your suggestions [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=enhancement&template=suggestion.md&title=Suggestion)
