### ISSUE TITLE
Add labels or some stickers for health bar , stress bar , etc , for beginners to understand 

### ISSUE THREAD

**Issue by darshitmachhi** [InZidiuZ/op-framework-issue-tracker#2435]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by CloudTheWolf** [comment]
@darshitmachhi did you forget to fill out the form?

**Comment by twooot** [comment]
The majority of people seem to be against adding texts onto the hud ![image](https://raw.twoot.org/fANaxEno36.png)
