### ISSUE TITLE
Reload Bug Heavy Rifle

### ISSUE THREAD

**Issue by NotEvolverX** [InZidiuZ/op-framework-issue-tracker#2436]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198882703297/

**Summary:**
Write a short summary of what you are experiencing.
When you will attach a extended in heavy rifle every time you equip the rifle it will get reload and if you will equip the gun in a vehicle then your ammo gets 0-
0

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
attach a extended in heavy rifle and equip it

**Expected Results:**
What are the expected results?
When equipping the gun no reload should be there

**Actual Results:**
What are the actual results?
You gets a reload when equip heavy rifle attached with extended 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
N/A

**Game Resolution:**
What is your game's resolution?
1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://gyazo.com/c5d787345d064e06fbca698c82e4bb09

**Server:**
What server/community did this issue occur in?
Legacy India

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
I cannot replicate this. When i attach the extended clip on the heavy rifle and equip it its perfectly fine

**Comment by KaiEagle** [comment]
> I cannot replicate this. When i attach the extended clip on the heavy rifle and equip it its perfectly fine

It's also bugged with PD VF Combat Pistol
https://streamable.com/u6hxyt

**Comment by NotEvolverX** [comment]
> I cannot replicate this. When i attach the extended clip on the heavy rifle and equip it its perfectly fine

https://youtu.be/V0hCP1g3aTs
here is a clip :(

**Comment by twooot** [comment]
I rewrote the entire ammo system, reopen if this is still an issue after the next update
