### ISSUE TITLE
Suggestion - Vanilla Unicorn Some Improvement

### ISSUE THREAD

**Issue by abiralikhan098** [InZidiuZ/op-framework-issue-tracker#2437]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

**1. VANILLA UNICORN MENU UPDATE:-**

**_FOODS MENU:_**
1. Pizza Slice
2. Hot Dog
3. Nachos
4. Wonder Waffle

**_NON-ALCOHOLIC DRINKS MENU:_**
1. Water
2. Coke
3. Soda
4. Lemonade
5. Ice Tea
6. Energy Drink

**2. The main door is always open, so it is better to keep this door closed.**

**3. Everyone can see and use the shop. Many times anyone who comes buys things by himself. This disrupts the RP of Vanilla Unicorn. So it would be great if only bar employees can use this**

**4. Need a DJ role**

**Reason:**
Why would your suggestion be a good change to the framework?

RP of vanilla unicorn is very low so if you do the above you can make a lot of RP with vanilla unicorn. we think doing the above can generate a lot more RP with vanilla unicorns.

**Comment by rakibulhasan456** [comment]
New food in the Vanilla will help to boost and create new ways of RP. Specially in the sub division, where people doesn't often engage with the vanilla unicorn.

**Comment by twooot** [comment]
1. NO, I'm not adding new food. Vanilla unicorn is not a restaurant. It already has some food items and plenty of alcoholic items, there is absolutely NO need for custom food for the VU.
2. I've locked the door by default now
3. I've now locked the store to the job
4. I've added a DJ position for the VU job
