### ISSUE TITLE
Bug report - Pedestrian Barrier Missing Collision

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2438]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

The Pedestrian Barrier Item currently has no collision.

**Steps to Reproduce:**
Place a pedestrian barrier and walk into it

**Expected Results:**
What are the expected results?
Barrier stop person walking any further

**Actual Results:**
What are the actual results?
Players/NPCs can walk right though the barrier

## Additional Information
The object prop_ld_barrier_01 looks to not have any collision
I suggest change the model from prop_ld_barrier_01 to ba_prop_battle_barrier_01c to fix this (Tested on Test server using spawn_prop and can confirm this has collision

**Game Resolution:**
What is your game's resolution?
1920 x 1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
c3s1 (Replicated on c2s1)

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This has now been done.
