### ISSUE TITLE
Suggestion - PD Barrier to have different model to Non-PD Barrier

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2439]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

With the introduction of Barriers at the tool store, PD barriers were also changed to the Non-PD Versions.

I feel like PD Barriers should still use the prop_barrier_work05 model.

**Reason:**
Why would your suggestion be a good change to the framework?

It would make sense that PD would have different barriers and would help players tell the difference between PD closing off a road / area compared to a gang

**Comment by InZidiuZ** [comment]
Oh ops, this was not intended

**Comment by InZidiuZ** [comment]
Are you sure it wasn't just the already-existing barriers that were converted to the other model? You should still be able to purchase PD barriers (with the old model) in the PD store.

**Comment by CloudTheWolf** [comment]
tested and yeah, looks like old ones were converted, but buying new ones have the correct model

**Comment by InZidiuZ** [comment]
Okay, everything is fine then, will close
