### ISSUE TITLE
Add locks for EMS Pharmacy

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2440]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adding a lock for the EMS pharmacy door.

**Reason:**
Why would your suggestion be a good change to the framework?
The Pharmacy belongs to the hospital. No civilians should be able to go get something from the pharmacy without any EMS.

**Comment by MetaHatter** [comment]
It only sells "over the counter" medicine.  What if no EMS are in city?

**Comment by T4NZ1M** [comment]
> 

By default, it will be unlocked?

**Comment by twooot** [comment]
No, the whole point of the pharmacy is that **its a shop open to the public**
