### ISSUE TITLE
Bug report - Side door on Route 68 3 Causing infinite loading

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2441]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/CloudTheWolf/

**Summary:**
Write a short summary of what you are experiencing.

At the House Route 68 3 There are 2 doors, one on the front and a side door (Where locals sometimes sit)

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Try and enter the door and it will get stuck on loading

**Expected Results:**
What are the expected results?
Door should not be interactable

**Actual Results:**
What are the actual results?

Player interacts and gets stuck on loading screen, needs to either be unloaded or F8 -> Quit

## Additional Information
Logs: https://pastebin.com/raw/h6iT7SV2

**Screenshots:**
If suitable, include some screenshots.
Problem Door:
![Location](https://cdn.discordapp.com/attachments/777722318159347712/999061425534279800/unknown.png)

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
c3s1 replicated on c2s1

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
![hmmm](https://raw.twoot.org/hUyIfUke77.png)

**Comment by coalaura** [comment]
This doesn't seem to be an issue on my dev server and since this report is quite old i'm gonna close it
