### ISSUE TITLE
Bug report - Prison no collision

### ISSUE THREAD

**Issue by Sharpeye0420** [InZidiuZ/op-framework-issue-tracker#2442]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
 
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/sharpeye25/

**Summary:**
There is no collision with grid at Prison

**Steps to Reproduce:**
Just go to main prison and try crossing Grid mentioned

**Expected Results:**
Should be there a collision

**Actual Results:**
No collision

## Additional Information

**Screenshots:**
Adding video https://youtu.be/-ZHCyVyemho

**Game Resolution:**
1080

**Player Data:**
https://gyazo.com/db28415eb78cbe01dffa06e1ce2c0c5a

**Server:**
Legacy India

**Comment by twooot** [comment]
This would be a bug for the asset issue tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
