### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by abiralikhan098** [InZidiuZ/op-framework-issue-tracker#2444]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

yes

**Summary:**
Write a summary of what your suggestion is about.

**Vanilla Unicorn Improvement**

Need a refrigerator in vanilla unicorn.

**Reason:**
Why would your suggestion be a good change to the framework?

We think doing the above can generate a lot more RP with vanilla unicorns.

**Comment by twooot** [comment]
I feel like i am constantly repeating myself. I have closed like 10 issues all requesting the same thing at this point.

**NO**, the VU will **NOT** get food. Its a strip club its **NOT A RESTAURANT**
