### ISSUE TITLE
Improvements to Yellow Jack

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2445]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yep

**Summary:**
I'm going through the process of purchasing the Yellow Jack on the International server and remember it having a second floor before, as well as a bunch of other customizations done to it that have seemingly been removed. I was hoping that MLO would be able to be brought back in to replace the boring default building that is there. 

**Reason:**
Why would your suggestion be a good change to the framework? Would allow a new business to prosper on the international server, and open up roleplay opportunities for the other servers as well.

**Comment by MetaHatter** [comment]
That MLO was scuffed and caused headpops. It's why it was removed.

**Comment by scufflord** [comment]
Is there any other way to potentially expand the interior, as well as fix up the exterior a bit as far as seating or something similar. Looking to use this place more-so as an event center for the north, and less as a bar, with a bit of fun 1%er MC stuff thrown in as well.

**Comment by MetaHatter** [comment]
Would be a question for the asset issue tracker.  This is the wrong github,

[https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=enhancement&template=suggestion.md&title=Suggestion](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=enhancement&template=suggestion.md&title=Suggestion )
