### ISSUE TITLE
Addition of a Sawzall for conversion of pump shotguns into sawed offs

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2446]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Write a summary of what your suggestion is about. Everybody like the classic 12 gauge pump shotgun, but you know what's even better? Doing a drive by on bikes using sawed off shotguns. Currently, sawed off shotguns are only available from a gun computer, and can't be found elsewhere. What I'm suggesting is the addition of a powered saw (example: https://www.homedepot.com/p/Milwaukee-12-Amp-SAWZALL-Reciprocating-Saw-with-Case-6519-31/202438078) that is a one time use for a price of $1500-2500 from the tool store, that when used allows a user to turn a normal Pump Shotgun into a Sawed off Shotgun, plus a piece or two of various materials (steel and scrap mainly) 

**Reason:**
Why would your suggestion be a good change to the framework? I believe it would be a good change to the framework because it adds extra options for people that come across pump shotguns from chop instead of JUST being a jewelry store gun. It will also add to biker RP, and expand upon the current philosophy of crafting that Legacy has had for a while. The sawzall item could end up having other uses later on as well, it isn't just limited to this!

**Comment by twooot** [comment]
done
