### ISSUE TITLE
remove red poles outside green wounderland

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2448]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
they are the wrong color, they dont provide the protection needed, the placement is bad

**Reason:**
they take away more then they give ,and to prevent bike dannys i still have to use the parisol's

**Comment by MetaHatter** [comment]
These were added because the umbrellas were causing headaches for people in the area.   If Dannys are still an issue, /report can be used, like every other business.

This also needs to be requested in the asset github.

**Comment by twooot** [comment]
https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
