### ISSUE TITLE
Financing Vehicles.. Bug or Feature?

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#245]
**Reporter:**
Steezy

**Summary:**
Currently having any outstanding finance that are due, regardless of how recent you make a payment towards your vehicle, you can not finance another vehicle. You would have to completely pay off your financed vehicle before you can finance another vehicle.

**Steps to Reproduce:**
1. Finance a car
2. Wait a few days, make a payment towards your /finance
3. Try to finance another car
![FiveM_GTAProcess_2019-07-20_18-41-21](https://user-images.githubusercontent.com/49498560/61586371-212a3800-ab27-11e9-81a8-bc0812f27152.png)

**Expected Results:**
Should be able to finance another car or at least have the option for people to sell their current outstanding financed vehicles for a percentage back towards what they have paid towards the vehicle.

So you finance a vehicle that costs $10,000 total. You have made $4000 in payments in total and no longer want the car. You can sell the car for a % back of the $4000 you have made towards the car.

**Actual Results:**
Have to pay off finances in order to finance another vehicle

## Additional Information

**Screenshots:**
![FiveM_GTAProcess_2019-07-20_19-48-49](https://user-images.githubusercontent.com/49498560/61586396-88e08300-ab27-11e9-8eac-84e40328bd7e.png)

**Player Data:**
![FiveM_GTAProcess_2019-07-20_18-44-01](https://user-images.githubusercontent.com/49498560/61586397-939b1800-ab27-11e9-8b06-3d3735cd012d.png)

**Comment by InZidiuZ** [comment]
Hey,

This is a feature, as it's supposed to remove the trust between you & the dealership if you decide to ignore your outstanding finances.

**InZidiuZ**
*OP-FW Developer*
