### ISSUE TITLE
Removal of Fridge from Penthouse

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2452]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Removal of Fridge from every Penthouse or you can just add it to the config file so the subdivision's can edit it
![image](https://user-images.githubusercontent.com/29286961/186893164-20929ef5-ebbc-4f0b-bb23-053bef01b1fd.png)

**Reason:**
Why would your suggestion be a good change to the framework?
People just buy food/beer from Fridge as it's way cheaper and also beer is only available in the penthouse currently after the recent Bar shop restrictions.

**Comment by twooot** [comment]
Sub divisions can already edit every stores inventory, the fridge counts as a store

**Comment by KaiEagle** [comment]
![image](https://user-images.githubusercontent.com/29286961/188140877-fff40272-5759-4094-98f3-63f3af9b504c.png)
He did tried I think but the update didn't went through so thought it's not editable.

**Comment by twooot** [comment]
> ![image](https://user-images.githubusercontent.com/29286961/188140877-fff40272-5759-4094-98f3-63f3af9b504c.png)
> 
> He did tried I think but the update didn't went through so thought it's not editable.

penthouse_fridge
