### ISSUE TITLE
[external/dpclothing] Re-add tie up hair part of dpClothing

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2453]
**Assurance:**
I think so, yeah.

**Summary:**
The original dpClothing script has a spot where you can put your hair up into a bun. I'd like this to be re-added for a specific reason that I will list below. 

**Reason:**
Not only will it be realistic to be able to put your hair up and down BUT the main reason I am suggesting it, is that as it stands there is no way to allow custom (non gta native) hair to fit into hats. If we had this addition we could set native hairs for every addon hair that people could swap to in order to wear hats that they want to without having to go to the barber to swap it Or change outfits every time they want to wear a hat. 

I'd be happy to help with the code when it comes to choosing which hairstyle should look like what when put up or to allow for a hat to be worn.

https://forum.cfx.re/t/dpclothing-1-0-3-clothing-variations-and-toggles-gloves-vest-top-hair-bag-and-more/1326317/1

**Comment by twooot** [comment]
bet

**Comment by twooot** [comment]
now just waiting on @DaxterPancake to get me a list of variations
