### ISSUE TITLE
Disable bike/cycle locking

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2455]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Disable locking the bike/cycle if someone is riding a bike/cycle. But if someone is not, then you can lock it from outside

**Reason:**
Why would your suggestion be a good change to the framework?
It's not realistic to lock someone when someone is riding it and you can't get out because it's locked. So adding this feature would be great

**Comment by CloudTheWolf** [comment]
If your on the bicycle, you can just unlock it right? (The same as going to seat 1 in a car and unlocking)

**Comment by T4NZ1M** [comment]
> If your on the bicycle, you can just unlock it right? (The same as going to seat 1 in a car and unlocking)

Yes but if someone is already in seat 1, then you can't do anything, that's why I'm suggesting disabling it for bikes. I've seen some people doing it which is Powergaming ofc but it's better to turn it off from the server side, right?

**Comment by twooot** [comment]
It would make sense that you can lock your bike tho, like bike locks? It would be awful not being able to make sure nobody steals your bike

**Comment by T4NZ1M** [comment]
> It would make sense that you can lock your bike tho, like bike locks? It would be awful not being able to make sure nobody steals your bike

My main point is if you're in the 2nd seat of a bike and someone is riding the bike already and he locks the bike, then you can't exit the bike. I'm suggesting disabling exiting while it's locked.

**Comment by MetaHatter** [comment]
...or you can choose not to climb on the back of bikes of people that might do that.  And possibly report someone dong it intentionally for trolling/powergaming

People stealing/trunk wiping a bike is a far bigger potential problem, probably best to leave the locks there.

**Comment by twooot** [comment]
yeah after thinking about it for a while i dont think we should get rid of bike locking
