### ISSUE TITLE
[Suggestion] Prevent driver from leaving vehicle / changing seat while in LS Customs

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2456]
**Assurance:**
Yes

**Summary:**
When using LS Customs, if you accidently press F you exit the vehicle (Unless belt is on/door is locked) you leave the vehicle, and it can no longer be accessed (Unless staff can use `/ev`)

Either the driver should not be able to leave the drivers seat, or if there is no driver the car should automatically be ejected from the customs shop.

**Reason:**
Why would your suggestion be a good change to the framework?

Prevent people having vehicles getting stuck in LS Customs

**Comment by twooot** [comment]
You can actually get back into the vehicle by unlocking it and then holding F
