### ISSUE TITLE
[game/spying] Have the Device Scanner detect Radio Jammers

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2457]
**Assurance:**
Yes

**Summary:**
The current device scanners that PD and civs have access to, be able to scan for the location of radio jammers. When the Device Scanner is used, it will detect for the radio jammer within (X) meter radius. And give some sort of indication, maybe by rough compass direction, or some sort of visual effect on screen to direct closer to the location.

**Reason:**
As it stands now, the radio jammer can be set and forget, and possibly in some spots that would be impossible to find. Criminals and cops both have access to this tool, and if either were to need to find the location of it, they could with the scanner.

**Comment by coalaura** [comment]
Done

![yes](https://i.shrt.day/SOSIDAmO36.png)
