### ISSUE TITLE
Equipped Weapon Display - Suggestion

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2458]
**Assurance:**
Yes

**Summary:**
Revert back to the old ammo indicator in the top right of the screen. Reduce screen clutter, and unneeded ammo indicators.

**Reason:**
The old ammo indicator in the top right seamlessly integrated with the visual look of a players screen. Overall just a cleaner look. And only showed up when someone was holding a firearm. With the new current one, even when holding a melee weapon such as a flashlight or a knife, the indicator in the bottom left pops up and says it has infinite ammo. 

Reverting to the old indicator would clean up the look of a players screen, and prevent infinite ammo indicators from popping when holding melee weapons as well.

**Comment by twooot** [comment]
The ammo indicator will not be reverted
