### ISSUE TITLE
[Weapons/Jerry Can] - Ammo and Fuel level not synced

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2459]
**Assurance:**
Yes

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
1 - Get a Jerry Can from a Fuel Station. 
2 - Equip Jerry Can
3 - See Ammo Infinite and fuel level is 100%
4 - Use Jerry Can to pour fuel on ground and see the Fuel Level stay at 100%

**Expected Results:**
Jerry Can Ammo and Fuel Capacity should be synced. 
Eg I have 100 "Ammo", I put 30% in my Car, and I then have 70% Remaining, Ammo shows 70, I start to pour fuel on the ground and the ammo reduces, I stop when I have 50 Ammo, I check and it should say I have 50% fuel remaining.

**Actual Results:**
What are the actual results?
Jerry Can has Infinite fuel when used in it's weapon state (Pouring fuel on the ground) and Fuel Amount in description does not decrease unless used to fuel a vehicle. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![Fuel](https://cdn.discordapp.com/attachments/777722318159347712/1013554439770091642/unknown.png)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?

International (c3s1)

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This should(tm) be fixed
