### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#246]
**Reporter:**
Warpwnge
Steam: https://steamcommunity.com/id/warpwnge/

**Summary:**
1. The trucker job. Sometimes, though a bit rarely, when accepting a job, the trailer will pop into existence and merge with another trailer already in that spot and results in your cargo flipping and/or catching on fire and being destroyed.

2. I decided to wait for my time to expire since I couldn't accept another one. Then I found that even if the time expires, you still have the job and still cannot accept another job. To fix this issue, I had to re-log, which isn't too much of an issue, though I can see it being problematic if the servers are all full and busy at the same time, so you end up losing your spot.

3. I have also come across some destinations being in precarious spots, forcing you to squeeze in between buildings, explosive tanks (That sucked), and other trailers which can end up damaging your vehicle with enough impacts.

**Steps to Reproduce:**
1. Accept a job where there is very, very little space.
2. Expire the time.
3. Drop off cargo in finish areas.

**Expected Results:**
1. Being able to retrieve a trailer without damage or impossibility.
2. When time runs out, your job is canceled, though maybe you can keep the trailer so it becomes dead weight?
3. Being able to complete a job without sweating to death over being exploded apart, or worrying about needlessly damaging your vehicle against obstacles.

**Actual Results:**
1. Some trailers pop into existence in bad spots.
2. Time runs out but doesn't cancel the job.
3. Some destinations are in tight or dangerous spots.

## Additional Information

**Screenshots:**
- (About the F8 console... uuhhhh... I'm not sure what that's for, though I also feel in this screenshot it isn't needed?)
https://i.imgur.com/8pBCgFi.jpg

- Destroyed cargo where it merged with another trailer (Now de-spawned after re-log)
https://i.imgur.com/SufFnPv.jpg

- Needless tight area. I'm backed up as if if I'm picking up the trailer.
https://i.imgur.com/75yeudG.jpg
- Once picked up, this is what I have to try to navigate.
https://i.imgur.com/dEE56zz.jpg

- Dangerous drop off/pick up location
https://i.imgur.com/zQLWY1V.jpg

**Game Resolution:**
1920x1080

**Player Data:**
https://i.imgur.com/ltcZva6.png

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

You're able to do /canceljob to cancel a job completely, you are not required to relog to do so. I also moved some of the *very* tight arrival locations.

**InZidiuZ**
*OP-FW Developer*
