### ISSUE TITLE
[vehicles/garages] ability to name or tag vehicles in the garage

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2460]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Summary:**
Being able to either custom name or at least tag a vehicle in your garage that way if you have multiple rumpos or other vehicles of the same make and model you can tell them apart. 

**Reason:**
Why would your suggestion be a good change to the framework? It would save people time instead of pulling out 400 rumpos or golf carts or whatever,

**Comment by DaxterPancake** [comment]
This promotes people storing their things in cars instead of in houses. We don't want to promote that, people use cars because they know it is harder to get caught using them to store illegal things.

**Comment by coalaura** [comment]
daxter does have a point here ngl

**Comment by gadjinee** [comment]
> This promotes people storing their things in cars instead of in houses. We don't want to promote that, people use cars because they know it is harder to get caught using them to store illegal things.

Agree with that, renting economy would go down hill, people would live in public garages as most already do

**Comment by coalaura** [comment]
this has somewhat been solved with the color coding
