### ISSUE TITLE
Addition of a credit card item

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2462]
**Assurance:**
Yes

**Summary:**
Add a credit card item that when on our person will allow us to purchase things from any store using the money in our bank if we don't have the cash on us.

**Reason:**
Purchasing items at any of the stores means that you must have the cash on you at the time, if you do not then you have to leave the store to find an ATM and then return. The addition of a credit card item would mean that if the cash isn't on you it would automatically then take it from your bank instead, saving you the trip to an ATM. This could then be adapted down the line if we wish with pin numbers and storing it inside a wallet, etc.

**Comment by twooot** [comment]
I'm not really a big fan of adding more items that just clog up your inventory, what do you think about the idea of making it so you can pay with bank with your smart watch (like apple pay)?

**Comment by DaxterPancake** [comment]
> I'm not really a big fan of adding more items that just clog up your inventory, what do you think about the idea of making it so you can pay with bank with your smart watch (like apple pay)?

Love that idea!
