### ISSUE TITLE
Forcing 1st Person when aiming a gun in a vehicle

### ISSUE THREAD

**Issue by TheDireMan** [InZidiuZ/op-framework-issue-tracker#2463]
So basically a large issue I'm seeing is a lot of people in the Arena community are coming over into Legacy and then using the fact that that you can shoot out of you're vehicles in 3rd person now to promote "fair fighting" amongst all groups and making it fair for everyone from people who want Arena to people who haven't picked up a gun it makes it fair and the point that I'm raising is that by putting people to be forced to look in 1st person it can then promote foot fights.

This is so guns like AK and MP9 can be used to the fullest potential instead of relying on the deterioration system to make sure the city is not overflowing with guns.

**Comment by twooot** [comment]
This is already a config flag that server managers can enable if they wish
