### ISSUE TITLE
Can the Jerry Can

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2464]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Remove visual of Jerry Can model from back when in inventory. Keep it, as is, in hand on use.

**Reason:**
Why would your suggestion be a good change to the framework?
- There is no practical or RP reason to show it
- If you WANT to RP carrying the can you can "use" it
- It looks really wonky to have a huge can on your back.
- It makes guns harder to see
- What's it stuck on with? Flextape?

**Comment by TheOneLizard** [comment]
alternative idea: make it flammable when shot at, people will stop making it a habit of carrying them around all the time 

Additionally: Would it be possible to make jerry cans refillable, just like the refillable water bottle?

**Comment by twooot** [comment]
But its a huge jerry can, no? Wouldn't it make sense that such a huge item would be visible somewhere?

**Comment by CloudTheWolf** [comment]
Have to agree, were are you going to pull it from when you go to use it??

**Comment by MetaHatter** [comment]
We already suspend disbelief with shovels, metal detectors, 200lbs of raw meat, tents, lawn chairs, umbrellas, etc.

The Jerry can back there is, at this point, the exception not the rule and it looks silly stuck to the back like that.

Again if there was a mechanic or purpose for its visibility I might think differently but as is, it's more immersion breaking than it is useful.

**Comment by twooot** [comment]
yeah thinking about it no i dont like getting rid of it
