### ISSUE TITLE
Hub customization

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2465]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
![image](https://user-images.githubusercontent.com/29286961/187675807-f559c14c-3a45-4759-9def-cfb46bd3d5a2.png)
The old times of legacy the direction radar & location was on top of the screen which was really good for some people who just love to watch on top instead of looking down at the bottom. I was thinking if you can let people choose between them like people can do /hud and they can choose whether they want the direction/location on top or want it near the map (like it's right now)

**Reason:**
Why would your suggestion be a good change to the framework?
Some people can't drive while looking down even when in heli people like it top of the screen instead of at the bottom.

**Comment by twooot** [comment]
The map, hud and every ui items is carefully aligned to work with every resolution and aspect ratio. I don't think adding the ability to move random UI elements around is a good idea
