### ISSUE TITLE
Server sided Keybinds

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2466]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
![image](https://user-images.githubusercontent.com/29286961/187676830-bf49cd3f-58d2-4ff6-b4eb-b82c37a11bea.png)
If there are more server sided keybinds like there are right now of police radar, people can also change the keybinds of inventory (of course the annoying M) phone and other similar things.

**Reason:**
Why would your suggestion be a good change to the framework?
It would let people customize the keybinds as the like and would not press the wrong key at the wrong time.

**Comment by twooot** [comment]
I dont see a need to be able to change those keys. I also dont see how the M key is annoying since its literally not used for anything else?

If you want to add new keybinds FiveM actually offers a solution for that on their own
