### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by divyummm** [InZidiuZ/op-framework-issue-tracker#2469]
**Assurance:**
yes

**Summary:**
Adding of new locks to harmony repair shop , adding of new repair slot on the outer side of the shop , removal of los santos customs from the shop

**Reason:**
Why would your suggestion be a good change to the framework?
as locks necessary for the shop owner and employee as the garage door opening randomly is quite not good as there is only one slot for repair as there is lot of space in right side of shop as adding of new slot is so much handy as there is only one slot for repair. also the one slot have los santos customs also which is needed to be removed

**Comment by divyummm** [comment]
Assurance:
yes

Summary:
Adding of new locks to harmony repair shop , adding of new repair slot on the outer side of the shop , removal of los santos customs from the shop

Reason:
Why would your suggestion be a good change to the framework?
as locks necessary for the shop owner and employee as the garage door opening randomly is quite not good as there is only one slot for repair as there is lot of space in right side of shop as adding of new slot is so much handy as there is only one slot for repair. also the one slot have los santos customs also which is needed to be removed

**Comment by CloudTheWolf** [comment]
So locks probably won't be added, and we probably won't want to remove LS Customs (since this is the only one between the city and paleto)

As for an outside bay, there is already one on the right hand side of the building (align the rear of the vehicle with the rear of the building)

**Comment by twooot** [comment]
cloud explained it for you
