### ISSUE TITLE
Hot Vehicles: Car Color

### ISSUE THREAD

**Issue by nealj121** [InZidiuZ/op-framework-issue-tracker#247]
**Name:**
neal121#8063

**Summary:**
Hot vehicles on the radio should list the color of vehicle. For towing purposes, I would expect this would be a thing to be said over the radio.

**Reason:**
Well it told a hot vehicle (RADIUS) was at the airport. I went over. I checked the parking lots and the parking ramps, I must have checked well over a dozen of these cars and even found more after in the same area. I just gave up... radius after radius. It would be great to give the color so I can save a little bit of time checking car after car.

**Comment by InZidiuZ** [comment]
Hey,

This has already been discussed previously, but we ultimately decided to leave the colors out of the radio chatter.

**InZidiuZ**
*OP-FW Developer*
