### ISSUE TITLE
Require More Slot for Harmony Repair Shop

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2471]
Currently 1 Repair Slot is Available for Harmony Repair Shop . Add 2 More Slot for Repair so that we can repair 3 car at a time .. 

beside the shop few space available .. please add 2 more slot thank you. 
photograph link for your reference
https://cdn.discordapp.com/attachments/877901773627605033/1015134699674423307/20220902111112_1.jpg
https://cdn.discordapp.com/attachments/877901773627605033/1015134699951239188/20220902111134_1.jpg
https://cdn.discordapp.com/attachments/877901773627605033/1015135617392316447/20220902111541_1.jpg

**Comment by twooot** [comment]
That is already a repair spot

**Comment by twooot** [comment]
Harmony has 2 spots i think adding a 3rd one would make it too crowded

**Comment by HellRaiser5** [comment]
no there is only one spot .. please recheck .... then closed this issue .. if 2 slot available then fine .. otherwise please add 1 more slot

**Comment by Seagle0** [comment]
plz can you send outside 2nd spot image. bec we can't find it.

**Comment by twooot** [comment]
#2209

**Comment by Seagle0** [comment]
thank you

**Comment by HellRaiser5** [comment]
as per this : https://i.imgur.com/n7MR2BF.jpg 
bro can't find the 2nd location just checked ...

**Comment by CloudTheWolf** [comment]
> as per this : https://i.imgur.com/n7MR2BF.jpg bro can't find the 2nd location just checked ...
This is the outline of the bay based on how we use it in the international server
![image](https://media.discordapp.net/attachments/905246521623216177/950890877360963644/unknown.png)
