### ISSUE TITLE
Level of mechanic determining work speed

### ISSUE THREAD

**Issue by Biqley** [InZidiuZ/op-framework-issue-tracker#2472]
**Assurance:**
Yes

**Summary:**
Basically suggesting that the rank of a mechanic determines how fast they are able to do crafting like car parts and advanced repair kits. Obviously veteran mechanic level would be fastest in doing above said actions, and intern mechanic would be the speed it is now or changed on how you see fit.

**Reason:**
I believe this would be a good change because it would provice quality of life in terms of making job positions worthy/worth working towards.

**Comment by twooot** [comment]
they are worthy working towards cause they provide a bigger paycheck meaning more money in the end. I really dont like the idea of a leveling system where depending on your job level you do things quicker/faster
