### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by KingCobraYT** [InZidiuZ/op-framework-issue-tracker#2473]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES

**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561199049580590/

**Summary:**
Write a short summary of what you are experiencing.
An error occurred while trying to retrieve your vehicle .I try to reconnect and retrieve from other garage but still same

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
please help me to retrieve my car

**Expected Results:**
What are the expected results?
I can get my car 

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
An error occurred while trying to retrieve your vehicle

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/112762671/188271680-952c76b9-9b47-494d-abea-cb497bd81249.png)

**Server:**
What server/community did this issue occur in?
India legacy 

**Notes:**
For anything else noteworthy.
No thanks for asking

**Comment by twooot** [comment]
Try using cash, this should be fixed next update
