### ISSUE TITLE
Paintball Logs

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2474]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Ad an result Log to paintball, kills/down's/win/losses

**Reason:**
A fun littel competion of who is really the best arena danny :P

**Comment by InZidiuZ** [comment]
By log, do you mean for staff, or a notification for whoever that participated/are nearby? Or what do you mean?

**Comment by InZidiuZ** [comment]
Closing due to no response.
