### ISSUE TITLE
Force Feeding

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2475]
Assurance: Yes

Summary: Give players the ability to force-feed others' food along with being able to use a limited selection of non "food" items such as cocaine, oxy, and I-FAK's.

[Force-Feeding]

Requirements:

> Players need to be handcuffed
> Duration of feeding 5 seconds
> If tackled = canceled

Reasons:

- Additional torture methods

- It's hilarious and fun

- Enhances ERP

(Crim Pov) Someone fed me cocaine and I OD on it.... LMAO

Idk if any of you have played Ark Survival Evolved but its a core mechanic in the game which I feel would be beneficial and hilarious for RP. This is a fun feature that would 100% get usage and I feel people would enjoy it. This is something unique that can open up the door for negative foods being made and used as items.

**Comment by twooot** [comment]
uhhmmmmm, funny idea but i dont really like it. Removing control from someone like that doesn't sound nice and it may be fun with friends but you know that there are a bunch of idiots out there
