### ISSUE TITLE
[game/items] Eating Spoiled Food

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2476]
Assurance: Yes

Summary: Make expired food edible with a chance of a large penalty for more realism.

[Eating Spoiled Food]

Requirements:

> Food needs to be fully expired

[Mechanic] - 25% chance to execute

> Player throws up
> Cool visual effect of disorientation (twoot special)
> Lose all of your hunger
> Lose 25% of your water

Reasons:

- Too much expired food lying around

- Additive to make the world more dynamic

- Goes well with #2475

This mechanic would not influence the purchase of food items in a negative way IMO. With a 1 in 4 chance of the penalties displayed above, this would be vastly more negative than it is becoming the food-eating meta. This would exist as an extra unique mechanic for better RP.

**Comment by vol5** [comment]
The goal here with this suggestion is to give people another option via a cool rp mechanic. If the practicality isn't there I understand. I still feel even though fairly negative, It would get some usage.

If you wanted to focus more on solving the issue of spoiled food lying everywhere... We could get fertilizer crafting from the fully expired food. Something like:

Compost/Fertilizer
eg.
> 1 Shroom (any stage)
> 2 water (any stage)
> 2 Food of any kind (fully expired)

**Comment by coalaura** [comment]
#3228
