### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sherrypanaich** [InZidiuZ/op-framework-issue-tracker#2478]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes, I have read all

**Summary:**
Write a summary of what your suggestion is about.
locals should be there in strip club for dance either then real players as dancers and dancing in the club
**Reason:**
Why would your suggestion be a good change to the framework?
a lot of people think that dancing in strip club is a full of insulting job and no one want to join this kind of job ever so, better to take locals in place of them

**Comment by DaxterPancake** [comment]
This is only an issue with your subdivision.  International server has many events at the strip club involving players dancing and players then paying them.

**Comment by sherrypanaich** [comment]
its really hard in my subdivision however there are too less girls as well in the city so, if anything can be done on that would be good

**Comment by twooot** [comment]
Like i've said in the 3 billion other issues that asked for the same thing: THIS WILL NOT HAPPEN and my decision will not change no matter how many more issues about this exact topic will be opened
