### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sherrypanaich** [InZidiuZ/op-framework-issue-tracker#2479]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Make mr laren 715 better in amour / speed because smaller mc laren 618 is way better then its bigger model in both things and alot of problems in bigger model as well

**Reason:**
Why would your suggestion be a good change to the framework?
car getting damage soo quick even with max amour on it

**Comment by twooot** [comment]
This would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
