### ISSUE TITLE
Public Helipad 

### ISSUE THREAD

**Issue by VeteranJungle** [InZidiuZ/op-framework-issue-tracker#2480]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
There is no publicly available helipad in the Paleto area. A publicly available helipad in the area would be nice for private pilots in the North. 

**Reason:**
Why would your suggestion be a good change to the framework?

I believe that having a public helipad in Paleto will bring more air travel, making travelling to Paleto seem less like a task and hopefully bring more activity to this slow portion of the city. It would also open up the possibility for more use of the islands off of the north west coast of the state

**Comment by antihero6713** [comment]
I can look into this for ya

**Comment by scufflord** [comment]
The big empty contruction site next to the gas station and repair shop might be a good spot for one similar to the platform at La Fuenta Blanca

**Comment by CloudTheWolf** [comment]
Another good spot could be opposite the hospital in one of 2 locations (The last side is where EMS land)
![a](https://i.imgur.com/9D9lwvT.jpg)

**Comment by itachi069** [comment]
https://media.discordapp.net/attachments/959466959987171358/1016755508595675186/20220906230259_1.jpg?width=1202&height=676
yea this is also a good location as @scufflord said

**Comment by twooot** [comment]
@antihero6713 let me know once you have your side done and i'll get the functionality implemented

**Comment by antihero6713** [comment]
Added the heli pad here 

https://cdn.discordapp.com/attachments/697579059642761306/1017990293745832026/unknown.png
