### ISSUE TITLE
Non Alcoholic Beverages at Bars

### ISSUE THREAD

**Issue by PeezyTooEasy** [InZidiuZ/op-framework-issue-tracker#2481]
Assurance: 
Yes

Summary:
Bars are starting to open up in the city and on the menus (Except for the Arcade I believe) Do not have alcohol free options on the menu for customers. Items such as Coke, Water and Pigeon Milk could be good for customers looking for a beverage that does not intoxicate them. 

Reason:
When people want to hit the bars with friends and do not want to drink alcohol they can have other options to choose from on the menu. Maybe they’re the DD for the night or just do not want to drink.

**Comment by twooot** [comment]
done
