### ISSUE TITLE
New DOJ Identification card

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2483]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
As I saw today in the teasers a new Identification card for the civilians, I think there should be a new identification card for the DOJ too so the civilians can identify them as the DOJ person.

**Reason:**
Why would your suggestion be a good change to the framework?
A lot of people don't acknowledge person as DOJ as they don't have any identification on them so the DOJ person needs to ask them to check mail for their identity every time for identification, this would help DOJ and Civilians both a lot.

**Comment by twooot** [comment]
I really dont think DOJ need a special badge just for them
