### ISSUE TITLE
Allow editing of heist payouts via server config

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2484]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
There should be a way to control the loot of bank and jewelry heists or any heist or job so that if any sub-division wants to increase or decrease payout they can easily.
**Reason:**
Why would your suggestion be a good change to the framework?
It will help other subdivisions to manage their economies.

**Comment by CloudTheWolf** [comment]
This is probably something that could be added to the cluster.cfgn

Maybe something like the following:

(The higher the weight the higher the chance it drops)

`bank_loot_override: "[{\"item\":\"ITEM_NAME\",\"weight\":5},{\"item\":\"ITEM_NAME\",\"weight\":3},{\"item\":\"ITEM_NAME\",\"weight\":1}]"`

`jstore_loot_override: "[{\"item\":\"ITEM_NAME\",\"weight\":5},{\"item\":\"ITEM_NAME\",\"weight\":3},{\"item\":\"ITEM_NAME\",\"weight\":1}]"`

`shop_loot_override: "[{\"item\":\"ITEM_NAME\",\"weight\":5},{\"item\":\"ITEM_NAME\",\"weight\":3},{\"item\":\"ITEM_NAME\",\"weight\":1}]"`

**Comment by twooot** [comment]
idk if this would be a good idea considering that they are all very carefully balanced
