### ISSUE TITLE
Crim ATM Robbery

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2485]
Summary: Create a new atm robbing system that allows players to hack, break and rob them for monetary gain. Something to add more variety with cop vs crim gameplay.

[Atm Robbery Conditions + Requirements]
> is wall atm in city only
> Not on cooldown (this cooldown could be global or individual)
> Chip
> Hammer

| Steps | Description |
| --- | --- |
| `Step 1` | Use chip to [hack](https://cdn.discordapp.com/attachments/876537143391051776/1018053307970900008/unknown.png) the atm, disabling is usual functionality |
| `Step 2` | Perform the hacking minigame correctly to open the front panel and [Trigger Anonymous Police Tip] |
| `Step 3` | Use the hammer to smash open the exposed portion of the atm |
| `Step 4` | Press [E] Begin [looting](https://cdn.discordapp.com/attachments/876537143391051776/1018052986582351933/unknown.png) the atm for cash |

[Step 3] - Smashing ATM with the hammer
> Duration 8s
> Add a loot pool to this part of the robbery in specific (PCB, CPU, SD, chip, wires, etc.)

[Step 4] - Looting
> Continuous looting until complete or player cancels
> Cash max potential 7.5k
> Overall looting duration for max payout = 3 mins
> Loot tick rate, $370-$470 every 10s

A common complaint from players is that there is "NOT ENOUGH TO DO". Here is a unique CRIMINAL thing to do that creates interaction on both sides. The suggested values here can surely change for the best balance. I feel that the ATM robberies surely could add value and drive more RP overall. That is mainly determined by how beneficial the activity is to complete, so things like the loot table could become more enticing while still being congruent with the idea. Overall, this is not entirely 1:1 realistic but still thematically wholesome. 

Reasons:

- New Activity

- Creates a more dynamic world

**Comment by twooot** [comment]
This sounds like a cash and grab to me, the point of robberies is the interaction with police tho

**Comment by vol5** [comment]
You are correct that it would be a smash and grab. If you have a slight fear that players would be gone by the time you get there. You would have complete control over the amount of time something like this takes with step 4 and the looting duration. 

The activity could still be aimed toward interaction with the police. Maybe step 4 was to be structured around fully completing the process of robbing it for the reward. Then giving police more time to respond. I just don't know what the avg response time is. Someone like yourself would know better than I.

The goal for this idea was not to be like a main huge lineup 6 cars, get scene command etc. But more of an underlying layer that happens somewhat often and is fast-paced. A few cops pull up and stop the robber and chase them.

**Comment by twooot** [comment]
IF you extend the time then people wont do it cause pd is gonna arrest you when they show up. And we cant have it be a cash and grab really cause yk we are here to rp not to make easy pixel money. All in all i dont like the idea
