### ISSUE TITLE
Arena Scoreboard/Leaderboard

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2486]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
It would be great if there is a scoreboard system for the ongoing match in Arena with Total Kills / Total Deaths which can be triggered while holding down a key.

**Reason:**
Why would your suggestion be a good change to the framework?
This would be really good for flexing your stats and also would help to conduct events with max kills and stuff.

**Comment by InZidiuZ** [comment]
This has since been added.
