### ISSUE TITLE
I got a million cleaning kits

### ISSUE THREAD

**Issue by Puucko4090** [InZidiuZ/op-framework-issue-tracker#2487]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Summary:**
Write a summary of what your suggestion is about.
What if locals tipped you 50-75bucks if u cleaned there cars at red lights etc :P
**Reason:**
Why would your suggestion be a good change to the framework? 
A littel amusing feat that woulde put cleaning kits to acuall use instead if pileing up ppls storage or end up in randome piles arounde the city^^

**Comment by vol5** [comment]
This would be very cool! Like you said, we got millions of these things...

**Comment by twooot** [comment]
What if you like cleaned random players cars

**Comment by Puucko4090** [comment]
Ido but hey never tip xD

**Comment by twooot** [comment]
done
