### ISSUE TITLE
Bug report - Arcade bar items bug

### ISSUE THREAD

**Issue by itachi069** [InZidiuZ/op-framework-issue-tracker#2489]
Assurance:
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
Player Identification:
What is your steam profile?
https://steamcommunity.com/profiles/76561199151584595/

Summary:
Write a short summary of what you are experiencing.

People who don't have Arcade Bar role! The bar items is not consumable/can't pickup items in pocket without the Arcade Bar role. And item name showing missing locale. It's happening in Legacy BD.

Steps to Reproduce:
Include what steps that are needed in order to reproduce this issue.

Buy some items from Arcade bar like- Arena pill, pizza, hotdog, nachos etc. Then give it to someone without the arcade bar role, they cant pick the items.

Expected Results:
What are the expected results?
Without the bar role it should pick the items in pocket.

## Additional Information

Screenshots:
If suitable, include some screenshots.
![Screenshot 2022-09-12 172513](https://user-images.githubusercontent.com/88096551/189645433-679a11d7-512e-40e4-8c91-ad27e9995e99.png)

Game Resolution:
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

Server:
What server/community did this issue occur in?
Legacy Bangladesh
Notes:
For anything else noteworthy.

**Comment by twooot** [comment]
i cannot reproduce this locally, if its still an issue after the next update reopen the issue
