### ISSUE TITLE
ADD an AMROR FOR A GANG( Black Mafia)

### ISSUE THREAD

**Issue by Gust123Battle** [InZidiuZ/op-framework-issue-tracker#2491]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
YES
**Summary:**
Write a summary of what your suggestion is about.
So We want to add an armor for an Black Mafia it is an gang in legacy roleplay india. We wanted this armor to be in legacy roleplay india because we think that it will give us a good and quality RP for our gang and we have no Black Mafia named jacket/shirt/pant/mask/armor so we are highly requisition to get that armor on legacy roleplay india. THis armor is already on Legacy but we wanted a new texture of that in that  our name and logo will be changed. Also The armor ID-31 in legacy roleplay india so it is a request to add that armor 
**Reason:**
Why would your suggestion be a good change to the framework?
It will be a good change in legacy roleplay india becuase it will give more Gang RP.

The armor PIC 
![IMG_20220912_234057](https://user-images.githubusercontent.com/95690117/189726538-dc68c691-5679-4cf0-8e87-27e558a02947.png)
In this armor. Where BlackWater has been written in front and rear we want BlackMafia on that with same font and thickness
and in LEFT where there is a LOGO we want our logo that is attached below
![Picsart_22-09-13_00-20-11-656](https://user-images.githubusercontent.com/95690117/189734085-4ee3cd77-4428-4623-90a8-24e5cb786e6c.png)

**Comment by CloudTheWolf** [comment]
@Gust123Battle Wrong GitHub,  this should go in https://github.com/InZidiuZ/legacy-assets-issue-tracker/

**Comment by Gust123Battle** [comment]
@CloudTheWolf Ok done
