### ISSUE TITLE
Add an Ammunation in Chumash

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#2492]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Adding ammunition in this place here, it already has the doors and inside functioning
![image](https://user-images.githubusercontent.com/60844168/189743939-d2571b09-f670-41e5-ad2f-50e4bcc88d88.png)

![image](https://user-images.githubusercontent.com/60844168/189743983-430bdc7a-18e0-44ba-88a7-372824117bae.png)

![image](https://user-images.githubusercontent.com/60844168/189744012-65be2503-9f43-47b6-91ee-26d82a169024.png)

**Reason:**
Why would your suggestion be a good change to the framework?

Well a lot of people live up in Chumash and the north area, it's a nice place to reside and why not have it there, you have a bank, clothing store, convenience shop, tattoo parlor and some nice ass houses, would be a nice addition to have on to living the upnorth style

**Comment by Badger47-2** [comment]
Yea this would be a great addition to the Chumash area

**Comment by BrittBee48** [comment]
Hell Yeah, this a necessity!

**Comment by twooot** [comment]
done
