### ISSUE TITLE
Hey. I bought a car from edm today it's vw gti and it's a 4 seater car and have some glitches like no one is able to sit on back side seats whenever we switch seats then we got disappeared...and is this car command/wheel_offset isn't working properly.. kindly assist me on thisBug report

### ISSUE THREAD

**Issue by wickedsir** [InZidiuZ/op-framework-issue-tracker#2493]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
This would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
Next time try to make your title short and use answer the questions in the issue template itself
