### ISSUE TITLE
Gun Breakdown Revision

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2494]
Summary: Allow guns to be broken down at any stage of degradation, currently they have to be fully degraded.

At this point it is just slowing down the removal of items and would help the economy become more fluid if able to be converted at any stage of degradation. This adjustment would help mechanics a lot. Not only mechanics but Realtors would benefit greatly, removing the amazon warehouse simulator gun decay loop. On top of this, reducing the overall gun count widely helps those that sell them.

Reasons:

- QOL

**Comment by twooot** [comment]
ok
