### ISSUE TITLE
Decryption Key Breakdown QOL

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2495]
Summary: Allow decryption keys to have a 3:1 breakdown ratio when degraded. Meaning you can craft 1 decryption key from 3 broken ones. This is a fairly selfish request in hopes to convert more things found from cleaned houses as a realtor and turning them into usable items. As they currently stand, they are fully dead once decayed.

Eg. [Decryption Key Collection](https://cdn.discordapp.com/attachments/876565140902924298/1018081097344614410/unknown.png)

The other option here would be instead of a 3:1 crafting ratio, make the decryption keys breakdown at random into one component from the list of components already used to craft them. 

(side note)
Not sure if you had something in mind for the chips or wanted to wait for future items. 

I don't find it unreasonable that you would be able to salvage 33% of the degraded keys you find. The current crafting is by no means easy, this would reduce some of that and convert these dead items into interaction. 

- QOL

**Comment by MetaHatter** [comment]
- The point of the degradation rate is to remove the item completely from the city to force people to continually seek them out. 
- More universal and accessible interaction is already provided via the current supply opportunities.
- Realty already provides a LOT of valued items from cleaned expired housing. It really doesn't need more.

**Comment by vol5** [comment]
Points 1 and 2 are fair. For point 3 I disagree since it has lost the majority of its value after degradation was implemented. 90% of the time drugs are unusable. I see where you are coming from though and this suggestion is largely not required. Going to close this up.
