### ISSUE TITLE
Suggestion regarding different role for FIB

### ISSUE THREAD

**Issue by souravind** [InZidiuZ/op-framework-issue-tracker#2496]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
I think it would be nice if different role can be created(with different designation) for the FIB Department. Right now there is same role like SASP for the FIB Department. Also if possible different coloured trackers can be created for FIB. 

**Reason:**
The main reason behind this is FIB officers will have their own designation which is different from SASP as their work procedure is different from SASP. And different tracker colour will also help them to track their department's officers who are on-duty.

**Comment by GodyFromDiscord** [comment]
Not really needed IMO, FIB should know who their officers are and it's really easy to find them on the tracker...

**Comment by souravind** [comment]
But what about Designations?

**Comment by DaxterPancake** [comment]
> Not really needed IMO, FIB should know who their officers are and it's really easy to find them on the tracker...

The same could literally be said for BCSO though? But they got their own colours and ranks for their division.

**Comment by GodyFromDiscord** [comment]
> > Not really needed IMO, FIB should know who their officers are and it's really easy to find them on the tracker...
> 
> 
> 
> The same could literally be said for BCSO though? But they got their own colours and ranks for their division. 

If you want to put it that way then SWAT FTP, management and IA should all have their colours and ranks for divisions. 

BCSO SASP and Highway are divisions that are meant to be used to covered specific regions, not exactly tasks and such that the other divisions have. What are you going to do if someone is in FIB and Highway, or others? If you can tell me a legitimate reason to why separate trackers and colours should be used on those id be happy to hear it out. But I'm throwing my opinion there and I think others would agree

**Comment by DaxterPancake** [comment]
SWAT could have their own colour and ranks, that would actually be extremely helpful in operations. Good idea! Management and IA don't need it as it's better for both divisions to be incognito around other officers so that people aren't on their best behaviour when they are around.

There are currently locations, objects and commands that would actually benefit being locked behind an FIB rank so that staff are not having to constantly check if they are being abused or used in a malicious way. As it stands currently, all of PD can access them therefore they could be considered high risk.

I don't really care either way I just don't think it's fair to shut the idea down just because FIB should know who their officers are and it's _really easy to find them on the tracker_. It's actually impossible to find FIB coz we are always undercover doing shit so the colour doesn't really matter anyway.

**Comment by GodyFromDiscord** [comment]
> SWAT could have their own colour and ranks, that would actually be extremely helpful in operations. Good idea! Management and IA don't need it as it's better for both divisions to be incognito around other officers so that people aren't on their best behaviour when they are around.
> 
> 
> 
> There are currently locations, objects and commands that would actually benefit being locked behind an FIB rank so that staff are not having to constantly check if they are being abused or used in a malicious way. As it stands currently, all of PD can access them therefore they could be considered high risk.
> 
> 
> 
> I don't really care either way I just don't think it's fair to shut the idea down just because FIB should know who their officers are and it's _really easy to find them on the tracker_. It's actually impossible to find FIB coz we are always undercover doing shit so the colour doesn't really matter anyway.
> 
> 

What about FTP?

If so the idea should be expanded to SWAT as well and not just limited to FIB therefore you can then limit certain buildings like swat and fib buildings and stores

**Comment by souravind** [comment]
Guys, there was also a main point of having different roles/ranks for the FIB Department... Please share your opinion on that also

**Comment by DaxterPancake** [comment]
I see the how FTP also getting it would be helpful ESPECIALLY for cadets.

The only problem I see is that obviously this would be a lot of work for the script developers.



> Guys, there was also a main point of having different roles/ranks for the FIB Department... Please share your opinion on that also

The discussion is literally about the main point. This discussion is helpful to the development process.

**Comment by KaiEagle** [comment]
I believe there should be following trackers/department IG but don't see a need of different ranks and also don't see a need of management tracker.
SASP - Blue
SAHP - Dark Blue
BCSO - Yellow
Park Ranger - Green
DOC - White
FIB - Light Blue
SWAT - Black 
FTP - Brown
Training - Silver
IA - Dark Brown

**Comment by MetaHatter** [comment]
There is a major consideration that needs to be taken in this... The purpose of the tracker is to quickly and easily identify what other emergency units are nearby.  If the map looks like Christmas lights, it makes the trackers themselves harder to track and identify quickly.

The mini-map should be for utility and there is no reason, in my opinion to color the trackers more than they are (as those are for jurisdictional reasons).   It will do more harm than good.

Clothing and cruiser addons/liveries exist for personal customization.

**Comment by GodyFromDiscord** [comment]
If anything if people really want an FIB rank, then just keep it the same colour as SASP as it really just creates more confusion having a rainbow on your map

**Comment by twooot** [comment]
I really don't want to add even more jobs for every department inside SASP. I'll happily give badges for every division that people can come up with, but I'm not adding more jobs. SASP, BCSO and highway is what it will stay at, everything else can be handled through RP perfectly fine
