### ISSUE TITLE
House robbery suggestion

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#250]
**Name:**
DegenTheo#2209

**Summary:**
House robberies, You would use the existing lockpick to break in to houses and get items such as plastic, scrap and maybe other items

**Reason:**
I think it would give players more stuff to do, And create more roleplay

**Comment by SATIN187** [comment]
I love this idea add in the possibility of getting guns and stuff but make it a lower percentage

**Comment by InZidiuZ** [comment]
Hey,

This is already on the [Trello](https://trello.com/b/PuHkmQx3/op-framework-development), but we'll need the housing system implemented before robberies, so closing.

**InZidiuZ**
*OP-FW Developer*
