### ISSUE TITLE
Suggestion - Police Radio Scanner

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2500]
**Assurance:**
Yes

**Summary:**

Have a craftable item that allows criminals to "Listen In" to PD Dispatch. 

This item would have to be recharged and could last for about 10 - 15 minuets of uninterrupted use. After which it would need to be recharged.

This item would have to be crafted using items such as:

A Radio, an RF Antenna, a Radio Frequency Decrypter and a 7.4 Volt Battery. (New items could be obtained though, Robbing Houses as well as be split between Trash, Go Postal and Trucking jobs.)

Form some balancing, along side the short battery life, it could potentially only decrypt some of the message (Only provide the dispatch call type such Eg `10-90: Robbery In Progress At [UNABLE TO DECRYPT]`) and/or automatically turn of after a certain amount of time with a cool down to turn back on.

**Reason:**
Why would your suggestion be a good change to the framework?

This would add more complexity to the Crim/PD Interactions as well as allow criminals to "Listen In" to police radio chatter while setting up for a Bank/J-Store etc.

**Comment by twooot** [comment]
this seems very powerful

**Comment by twooot** [comment]
yeah balancing wise i dont really think this would be a good idea
