### ISSUE TITLE
Make Smoke Grenades great again

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2501]
Summary:

Smokegrenades are barely ever used for anything in their current state. They only last about a minute, have a rather small coverage and are pretty much seethrough. With the addition of Vapes that issue got even more visible. 

[smoke from a vape](https://cdn.discordapp.com/attachments/876565140902924298/1021546275767849020/unknown.png)
[smoke from a smoke grenade](https://cdn.discordapp.com/attachments/876565140902924298/1021554368685822022/unknown.png)

[Adjustments]

> Increasing the duration(3-5min)
> Increase Thickness of smoke by a large margin
> Widen AOE radius

[Crafting]

> Make them craftable

Both, Pd and crims will be able to utilize smoke in gunfights to create more dynamic RP experiences. This item goes largly unutilized. It would be really cool to see it in action and im sure the SWAT team would be more than happy to use it. Considering PD can just buy them from the store crims should have the option to craft them instead of only getting them from the lucky wheel.

Reasons:

- QOL

- Enhanced gunfights

**Comment by KaiEagle** [comment]
There is a GTA weapon called smoke grenade launcher, the smoke opacity of that smoke grenade is pretty good tbh

**Comment by GodyFromDiscord** [comment]
3-5 minutes is way too long, a typical smoke grenade lasts between 40-80 seconds

**Comment by vol5** [comment]
> 3-5 minutes is way too long, a typical smoke grenade lasts between 40-80 seconds

3-5mins may be a bit too long, if it were to be 90s-120s that would seem reasonable. It's a game. The duration of it does not have to be 1:1.

**Comment by vol5** [comment]
@KaiEagle The density of that smoke grenade from the launcher is good but aoe is a bit light and the duration is very low.

**Comment by twooot** [comment]
> There is a GTA weapon called smoke grenade launcher, the smoke opacity of that smoke grenade is pretty good tbh

thats the same grenade i'm 99% sure

**Comment by vol5** [comment]
It is not the same grenade or if it is. The grenade is not functioning correctly. The smoke they put out is completely different.
