### ISSUE TITLE
[game/zombie] Allow BR Weapons to be used in the zombie pill

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2502]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
As there are weapons called BR weapon which are only usable in Arena and Battle Royale it would be great if you can also make it usable while playing Zombie VR (Zombie Pill).

**Reason:**
Why would your suggestion be a good change to the framework?
If the weapons are usable in Zombie VR then the Arcade can sell those weapons as a Digital content :)

**Comment by coalaura** [comment]
Since you can actually keep the items in the zombie pill, i dont think this is a good idea
