### ISSUE TITLE
Store Robbery Adjustments

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2503]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
- Limit the robbing of stores to only stores withing city limits (i.e. not Harmony, Sandy, Paleto or Chumash)
- Loot tables should be balanced for solo or solo w/hostage
- Potentially slightly slow down the robbery process
- Double-check the reliability (to make any scuffs from the past are fixed)

**Reason:**
Why would your suggestion be a good change to the framework?
- Improves the soloable, entry level robbery option by eliminating range-based min-maxxing
- Allows for stores to be more viable for PD/crim RP 
- Reduced radius would increase risk and allow for potentially increasing payout

**Comment by CloudTheWolf** [comment]
So I feel limiting Store robberies to only in the city limits is a bad move as this is essentially restricting Criminal / PD RP to within the city limits but also this could be difficult  / impossible as I suspect  this is tied to the Interior Archetypes `v_shop_247` `v_gen_liquor` and `v_gasstation`.

Now, as for Loot Tables I feel this could be split into a Tier system where each tier takes longer, but increased the loot chances.

Eg:

Tier 1 - Holdup: Players hold up the convenience store and just rob the registers (Liquor Store has 1, Gas Station/247 have 2 each), takes 45 seconds to loot each register, and has a small amount of cash with a very low chance for keys etc.

Tier 2 - The safe (Basically the same as what it is at the moment, but it takes slightly longer)

Tier 3 - Both Tier 1 and 2 combined

**Comment by MetaHatter** [comment]
As currently, PD simply has no reason to react to these robberies out of the city as they cannot physically get there in time. In lieu of pd regularly patrolling up north, which won't happen due to player count, this at least will make robberies a viable RP option again. 

The North will simply not lose as much as the city will gain. Especially since this reduction would create significant opportunities for PD to actually confront/catch the perpetrator creating RP scenarios and would, hypothetically, allow us to increase the payouts as a result.

**Comment by twooot** [comment]
> Limit the robbing of stores to only stores withing city limits (i.e. not Harmony, Sandy, Paleto or Chumash)

Does not make sense in rp imo.

> Loot tables should be balanced for solo or solo w/hostage

How would this be done????

> Potentially slightly slow down the robbery process

I think for the amount of money you get the speed is decent, you gotta be good at it and quick to be able to pull it off, get out and drive away before the cops show up.

> Double-check the reliability (to make any scuffs from the past are fixed)

Taking a look at it rn

**Comment by MetaHatter** [comment]
> > Limit the robbing of stores to only stores withing city limits (i.e. not Harmony, Sandy, Paleto or Chumash)
> 
> Does not make sense in rp imo.

Thoughts on having the more valuable items from the robberies only drop in the city then? (would make sense that rural towns would have less to steal)

> > Loot tables should be balanced for solo or solo w/hostage
> 
> How would this be done????

I think they are already, just wanted to note it since I don't know what the loot tables actually are.

> > Potentially slightly slow down the robbery process
> 
> I think for the amount of money you get the speed is decent, you gotta be good at it and quick to be able to pull it off, get out and drive away before the cops show up.

Agree. 

Main issue is the power-gaming by only hitting areas FAR from PD presence.  My loot table tweak suggestion above might alleviate that.  Still make them robbable everywhere but the city is the "ideal"

> > Double-check the reliability (to make any scuffs from the past are fixed)
> 
> Taking a look at it rn

Thanks! This has been one of the largest issues people have.  Either scuff or the perception of scuff.

**Comment by twooot** [comment]
Okay so store robberies are fully functional again now and the further away from the city they are the less the payout will be
