### ISSUE TITLE
BoomBoxes Bug report

### ISSUE THREAD

**Issue by LilMack24** [InZidiuZ/op-framework-issue-tracker#2504]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198309743139/
**Summary:**
Write a short summary of what you are experiencing.

The BoomBoxes are currently very bugged. It won't take any videos and it seems only a very select few works. I don't know what causes the videos to work though! 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Lyric videos or Videos from a noncertified account don't work like they should.

**Expected Results:**
What are the expected results?

Typically if you put in a video that isn't copywriter claimed (or whatever it typically is for it to work) it would play

**Actual Results:**
What are the actual results?

No music plays!

## Additional Information

Sorry idk if this has been brought up :D!

**Server:**
What server/community did this issue occur in?

Legacy NA/EU

**Notes:**
thanks for all your work!

**Comment by InZidiuZ** [comment]
This should now be fixed.
