### ISSUE TITLE
FPS Boost Command

### ISSUE THREAD

**Issue by vermajai93** [InZidiuZ/op-framework-issue-tracker#2507]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

Yes

**Summary:**
Write a summary of what your suggestion is about.

I played on a different server recently which had a /fps_boost command.
It basically gives you an option to choose what kind of PC config you have:
1. High end
2. Medium end
3. Low end

Choosing a medium end or low end pc gives you a tremendous FPS boost and could help so many people who don't have a high end gaming pc. The graphic quality is set to low is what I felt. Any possibility to add a similar command on legacy server?

If not, do you think it would be possible to allow (some) graphic quality options to be set at local level and not server level so players have the option to choose low texture quality, water quality etc.

Thanks in advance.

**Reason:**
Why would your suggestion be a good change to the framework?

It could help so many people and give them a chance to play at a decent or even high fps who don't have a high end gaming pc.

These options would do away with the need of useless fps mods which makes the game look worse than vice City.

**Comment by GodyFromDiscord** [comment]
Try this https://downloadmoreram.com/

**Comment by twooot** [comment]
Or this https://downloadmorecores.com/

**Comment by twooot** [comment]
But in all seriousness, no. If we knew how to speed up fps we would already build it into the framework. We constantly improve things when we discover them. We don't "set settings serverside", you have full control over all graphics settings that there are in the game
![lmao](https://raw.twoot.org/MAdEvEjU28.png)

**Comment by vermajai93** [comment]
I'm not a developer and I'm sure you guys do everything to keep the server optimised.
But can you please check [this GitHub link](https://github.com/alp1x/qb-fpsbooster) once? Maybe you can figure out what they're doing to boost fps on their server and possibly do the same in OP-Framework?

The reason I'm so keen on this is because even people with decent builds face sudden fps drops near specific locations.

PS. This is not the server that I played on, but it worked pretty similarly.

**Comment by twooot** [comment]
You do realize we are not a qb-core server right? Most of the "optimizations" that script does would fuck massively with the framework

**Comment by vermajai93** [comment]
Just wanted you to take a look to see if something similar can be implemented on OP-Framework. 

Because there must be something that qb framework people must be adjusting to gain fps boost right? I'm sure coding may be different but at the core, they may be reducing shadow quality, trees shader or something to reduce system load. I was hoping something similar could be achieved on this framework as well.

As I said, I'm not a developer, that's why I'm reaching out to the experts to see what is and isn't possible.

**Comment by GodyFromDiscord** [comment]
All of the stuff you listed is what you can control inside of your FiveM game settings, it was already said that everything that can be optimised is already optimised within the framework, you've already been told something like this will not be implemented, and if you're experiencing issues then maybe tune your game settings.
