### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by brycepsd** [InZidiuZ/op-framework-issue-tracker#251]
**Reporter:**
Bryce.psd#8276 & https://steamcommunity.com/id/bryce_psd/
**Summary:**
My BMX bike is broke now because physics were added to the GTA cars. My character is a BMX king and I can't even jump without completely dying.

**Steps to Reproduce:**
Get on a bike. Go forward. Jump. Dead

**Expected Results:**
Not to be dead from one jump.

**Actual Results:**
Dead from one jump.

## Additional Information
It probably is a small fix but literally just need the bikes to not be affected by the car physics.

**Game Resolution:**
1920x1080

**Player Data:**
Not In game currently

**Notes:**
Please fix, Herald needs to hit the ramps again.

**Comment by InZidiuZ** [comment]
Hey,

This isn't really my area, so I will close this & forward it to Karpenko, as he's the on taking care of most of the asset-related things.

**InZidiuZ**
*OP_FW Developer*

**Comment by RGDaviid** [comment]
Hello @brycepsd ,

I was riding the BMX myself a few minutes ago and it seemed to work just fine. I'm not sure what the issue was however i will take a closer look at this. If possible can you Send me a video of this happening. So far i've not been able to re-create this bug.  

**Karpenko**
_OP_FW Vehicle Developer_

**Comment by brycepsd** [comment]
Hey I actually streamed the bug yesterday, let me find it and clip it and I can get back to you. I even had a friend try it and it happened too.

**Comment by brycepsd** [comment]
[Here you go](https://www.twitch.tv/videos/456144776l)

**Comment by RGDaviid** [comment]
@brycepsd Not sure if this is an issue from my side but the link seems to pop this up. 

![image](https://user-images.githubusercontent.com/40771170/61598682-37182580-ac19-11e9-8070-f4ded61f0ae6.png)

**Comment by brycepsd** [comment]
Oh my bad Here [Link](https://www.twitch.tv/videos/456144776)

**Comment by RGDaviid** [comment]
Hmm. I don't seem to have the same Issue but i may know what's causing it. I'll take a look at it and try get a fix for you.

**Comment by brycepsd** [comment]
Okay yea Thanks, I think it's just because of the physics change with the GTA vehicles causing it to have more control in the air. I don't think a bike moves like that in real life XD.

**Comment by RGDaviid** [comment]
Were you holding the Shift Key when you jumped?

**Comment by brycepsd** [comment]
Yea I like to b-hop to get places so I have Capslock on to go faster+hold shift and spam space. But the issue just seems to be the amount of control in the air. A bike shouldn't let you sway from left to right in the 3 seconds it's in the air.

**Comment by RGDaviid** [comment]
Alright i'll get it checked out.

**Comment by N8teZero** [comment]
Quick fix is to not shift jump. BMX are meant for tricks, which you can do much easier now for more fun :) If you'd like to travel faster, get a motorcycle. :D

**Comment by brycepsd** [comment]
@N8teZero I do use BMX for tricks to but as someone who goes to a skatepark often. Clearly the BMX in game has a bit more physics when in the air. For example in a single jump you can sway from left to right back to left in that amount of time. That is beyond difficult in a real life scenerio.

**Comment by RGDaviid** [comment]
Alright so for the time being i've lowered the Jumpforce back to the standard value and the lean forces. Should be fine now! But i will probably edit the BMX handling in the future. As N8te said it was made to be more fun however it clearly didn't work. 

_It was made for American Bunny Hops in mind._

**Comment by N8teZero** [comment]
Indeed @RGDaviid 

For me, it was more of a skill thing. Me n my pals were getting really good at mastering tricks and finding things to do stunts on. The jump force and rotation is tricky, but it's supposed to be. Once you learn to control it, far more rewarding. Not everything is meant to be realistic, some things are just for fun.

**Comment by brycepsd** [comment]
@N8teZero I mean yea u can master tricks but I'd rather be able to do what you can actually do in real life instead of being able to ET by the moon.

**Comment by RGDaviid** [comment]
@N8teZero I did also find it more fun but we'll need to give it some time. although in real life it's possible to Bunny Hop far higher than GTA Standard Phyisics allows.

**Comment by brycepsd** [comment]
@RGDaviid I agree, I wanna say that the perfect amount would be between the update and the Standard Physics.
