### ISSUE TITLE
Hold both players still during (soft) cuff animation

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#2512]
When a player gets cuffed either by another player or by a cop using "soft cuffing". The player cuffing is stuck in the cuffing animation while the player being cuffed can keep moving freely. Ideally/realistically both players should be held still until the animation is complete. Otherwise, I noticed this sometimes creates a disadvantage on the cuffing player and allows questionable RP to take place for the sake of getting away. Such as continuing to run away, or getting into cars etc.

The gif below shows the issue happening in an actual situation
https://gyazo.com/87b9d22d51fe8d57e630a06867893bd8

**Comment by Mugdha57** [comment]
i was thinking to report the same thing..

**Comment by DaxterPancake** [comment]
I agree with this idea, too many times do criminals call cops powerful or have cops uncuff them because they were 'too far away' to be cuffed.

**Comment by Vedder742** [comment]
> I agree with this idea, too many times do criminals call cops powerful or have cops uncuff them because they were 'too far away' to be cuffed.

That is also a great point, while we're on this topic it could be cool if cuffing only worked on people from behind the ped, and the range was slightly tweaked. Here's a relevant example of situations that could be avoided:
https://gyazo.com/b6d86480fa64111d415543754f8b6eba

Another fantastic source: I have been cuffed by a cop while standing face to face before and it brought the toxic league of legends player out of me.

**Comment by twooot** [comment]
Ok so i couldn't replicate cancelling out of the being cuffed animation but i did some improvements to the script, if its still an issue after the next update please let me know

**Comment by twooot** [comment]
Gonna close this for now, please reopen if still an issue (after update)
