### ISSUE TITLE
Meri 3rd Floor wali Rolls Royce me jo aage Logo nikalta hai wo show nahi ho raha it's only showing me just black car model is Rolls Royce Wraith.

### ISSUE THREAD

**Issue by vishaljoon1** [InZidiuZ/op-framework-issue-tracker#2514]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?

**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by vishaljoon1** [comment]
Meri 3rd Floor wali Rolls Royce Wraith me jo Logo hota hai aage hood pr wo show nhi hora sirf black dikhra hai jese ki kisi ne nikala hua ho esa.

**Comment by KaiEagle** [comment]
> Meri 3rd Floor wali Rolls Royce Wraith me jo Logo hota hai aage hood pr wo show nhi hora sirf black dikhra hai jese ki kisi ne nikala hua ho esa.

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues 
It's an asset issue please refer to the asset repository 
Ya asset ka issue hai ya wali joh link ha udahr ek issue create karo 
🙂

**Comment by twooot** [comment]
1. Put your issue or suggestion in english
2. Follow the template
3. Don't put your entire issue/suggestion in the title
