### ISSUE TITLE
Increase the Bahama Mamas Bar Hourly salary .It would help to increase our income source.Effective for bar Rp as well 

### ISSUE THREAD

**Issue by MahaditulAlif** [InZidiuZ/op-framework-issue-tracker#2515]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by twooot** [comment]
no, the salaries are balanced where they are right now also **follow the template and dont put your entire suggestion in the title**
