### ISSUE TITLE
O'Malley's Requests

### ISSUE THREAD

**Issue by HawkALoogieSoup** [InZidiuZ/op-framework-issue-tracker#2517]
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository?
Yes
Summary:
Hi I'm Bart Johnson owner of the O'Malley's I had a  request  I would like to make for the Bar
I was wondering if we could get a new item added to the menu. We were wanting to see "Irish Coffee" added to the menu here at O'Malley's just some coffee with a bit of whiskey in it. Just something nice to add into the bar and have people enjoy.
Reason:
It's just something to fit the bar and overall something nice to enjoy when you come to O'Malley's.

**Comment by twooot** [comment]
I love the idea!

**Comment by twooot** [comment]
done
