### ISSUE TITLE
O'Malley's Picture change request

### ISSUE THREAD

**Issue by HawkALoogieSoup** [InZidiuZ/op-framework-issue-tracker#2518]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Hi I'm Bart Johnson Owner of O'Malley's. We would like this photo in the bar https://cdn.discordapp.com/attachments/732645123153723396/1026733739784544306/OldPhoto.PNG to be changed into this photo https://cdn.discordapp.com/attachments/732645123153723396/1026661513613807726/Darraghcrop2.png?

**Reason:**
The photo we want overall fits into the bar better, but it also is a photo of a bar patron and business partner that has left the city to start a new chapter in his life. Overall it would make myself and others really happy to have the photo hanging in the bar.

**Comment by DaxterPancake** [comment]
This is the incorrect github for this as this is a asset request, you can find the correct github [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
