### ISSUE TITLE
GARAGE BUG

### ISSUE THREAD

**Issue by 00hitman00** [InZidiuZ/op-framework-issue-tracker#2519]
There is a Garage Bug, Sometimes I fail to store my vehicle, it says- "Is this your your vehicle?" and doesn't store the vehicle. Happened manytimes, I had to Press F8 and quit, then after coming back I was able to store the vehicle. 

Please fix this asap!

**Comment by InZidiuZ** [comment]
Please follow the template when filing bug reports.
