### ISSUE TITLE
Suggestion: Display Images similar to Cinema

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2521]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Expand the Cinema script or something similar to allow for us to display images on whiteboards/bulletin boards/etc.

**Reason:**
My reasoning is mainly for PD, but I am sure there are other uses. I want to bring back more "shift meetings" and it would be super easy to prepare a "slideshow" of images that I could put on the whiteboard in the class room of MRPD that would include statistics, latest warrants, etc. I could also just create simple videos and pause them as well, so if that is the case then I would like to add that white board in the classroom of MRPD to the "TV" list instead of just the small one next to it.

**Comment by InZidiuZ** [comment]
The DUIs (what the cinema uses to render video) doesn't blend in with the environment at all, so for billboards etc. it looks really, really strange, so I don't think this will happen anytime soon.

**Comment by InZidiuZ** [comment]
Support for displaying images (and other uploaded content like .mp4, etc.) has now been added. You can see a [preview here](https://inzidiuz.com/bC3nNk.mp4).
