### ISSUE TITLE
Bean Machine TV Screen fix For Cinema

### ISSUE THREAD

**Issue by HellRaiser5** [InZidiuZ/op-framework-issue-tracker#2522]
Both TV Screen not in Actual Position, 
Reference image Below
https://cdn.discordapp.com/attachments/877901773627605033/1027276654655049728/20221005231639_1.jpg
https://cdn.discordapp.com/attachments/877901773627605033/1027276654260801536/20221005231614_1.jpg

**Comment by DaxterPancake** [comment]
This should be fixed with next update. We have to manually fit every screen to every TV so it takes time.

**Comment by HellRaiser5** [comment]
okkzz
