### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ninja2op** [InZidiuZ/op-framework-issue-tracker#2523]
So I brought a motel for 1750 bucks in legacy Indian role play but I can’t enter in the motel and the money is deducted from my bank account 
![6524DE5F-3B72-4FF3-88F9-F5B00641A646](https://user-images.githubusercontent.com/115107263/194223489-364ec7b0-ab7a-471b-85e6-51a5aef7e9c0.png)

**Comment by CloudTheWolf** [comment]
1) Are you sure your room didn't expire? (They expire after 7 IRL days)
2) Are you sure you are at the correct door?
3) Have you raised this with your servers staff?

**Comment by InZidiuZ** [comment]
Please follow the template when filing bug reports.
