### ISSUE TITLE
The possibility of having Red and Green Police Dummies. 

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2525]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Could colored dummies be added to the PD armory, Red and Green dummies specifically? Training purposes

**Reason:**
Having the ability to have green and red dummies inside the PD locker would be a great asset for SWAT/PD training purposes. We can use green dummies in place of Civs, and red as Criminals. These could also be used at the weekly SWAT/PD training that takes place. In place of hostages so we don't have to use live hostages (PD personnel) in training situations.  In SWAT/PD our emphasis is put on being the frontline this also includes breaching buildings, having Dummies to use as Civ and Criminal would benefit in training situations as we can prepare them to hopefully not shoot Innocent people.

**Comment by GodyFromDiscord** [comment]
This would be an asset request so please create the issue at the repo listed below and close this one:

https://github.com/InZidiuZ/legacy-assets-issue-tracker
