### ISSUE TITLE
add new shops  so other people can buy there own business

### ISSUE THREAD

**Issue by 6969hub** [InZidiuZ/op-framework-issue-tracker#2526]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by vol5** [comment]
Please take a look at others GitHub submissions and change your formatting if you plan to send in submissions in the future. This below is structure on how to format it "you left them blank". Also, anything map related should go in here https://github.com/InZidiuZ/legacy-assets-issue-tracker

> Assurance:
> Have you read through the rules from the README.md file in the root folder of this GitHub repository?

> Summary:
> Write a summary of what your suggestion is about.

> Reason:
> Why would your suggestion be a good change to the framework?

The title is not meant to be used as the entirety of what you mean to convey. Also do not send in general statements. What do you expect the devs to do with this? "add new shops so other people can buy there own business" That is way to general and for anything of this nature to be considered you must put in more effort than that.

**Comment by twooot** [comment]
This issue is incomplete, please follow the template next time
