### ISSUE TITLE
Suggestion - Tablet "Web Browser" App

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2527]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add a Web Browser app to the Tablet that is restricted to certain domains (Config controlled for so sub-divisions can control this)

Eg for the international server it could be limited to:

https://*.wiese2.org (For PDM)
https://*.twoot.org (For EDM / Any new sites)
https://legacymdt.com (For PD MDT, when CYCLON1AN gets around to adding SSL Cert)
https://*.legacyrp.company (For Mechanic/Bar/Arcade Websites & EMS MDT)

**Reason:**
Why would your suggestion be a good change to the framework?

Currently, for a lot of the whitelisted companies, including mechanics, as well as PD there is a lot of having to tab in and out of the game to do certain things. (Writing PD Reports / checking MDT profiles, mechanic shops using pricing calculators etc)
Having these be available in city could allow for a more interactive experience, especially for players with 1 monitor.

**Comment by twooot** [comment]
This will not always work. The owner of a website needs to set certain headers for it to be able to be displayed in an iframe. However i will be adding a PDM and EDM app
