### ISSUE TITLE
Suggestion: Add kiosks into pdm

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#2528]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
With the addition of the pdm catalog to the tablets it would be amazing if we could have a couple kiosks added to pdm that would only be able to browse the catalog.  You’d walk up to the kiosk and be given an interact option which would then open the tablet pdm app. 

**Reason:**
This would be a good addition to the server as it would allow the player base to view what vehicles pdm has access to. Newer players may not be willing to purchase a tablet right away and it would allow them to view everything. Also people don’t always carry their tablets on them.  Rather than pdm employees dropping notes with the web address of the catalog they wouldn’t have to go outside the server to view it.

**Comment by nunsia** [comment]
Additionally it could also be added to EDM? Or also have the EDM catalog on the kiosks at PDM :D

**Comment by antihero6713** [comment]
If this is something we want to go after and need a custom prop to visually see it. Let me know

**Comment by twooot** [comment]
Done

![https://raw.twoot.org/bAWaXexE82.png](https://raw.twoot.org/bAWaXexE82.png)
![https://raw.twoot.org/zahiMEWe85.png](https://raw.twoot.org/zahiMEWe85.png)

**Comment by twooot** [comment]
And for EDM too ofc ![https://raw.twoot.org/TIcIYUNe76.png](https://raw.twoot.org/TIcIYUNe76.png)
