### ISSUE TITLE
Incognito phone calls

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#253]
**Name:**
Warpwnge
Steam: https://steamcommunity.com/id/warpwnge/

**Summary:**
I've noticed you can do incognito phone calls with others, but you HAVE to message them first. I feel that Person A should be able to get Person B's phone number without Person B getting Person A's phone number. Person A can then incognito call Person B through the contacts list instead of just through the text messaging, without having to reveal their number.

**Reason:**
I feel this could add a bit of extra "Mystery" and anonymity to certain characters that don't wish to just hand out their phone numbers, but would be looking to get people to work under them or something.

**Comment by Anderzenn** [comment]
Hey,
This is already in the plans for the new Phone that we are working on :)

**Anderzenn**
*OP-FW UI Developer*
