### ISSUE TITLE
[alpha/guns] Bug report: Getting stuck while gun running

### ISSUE THREAD

**Issue by BigEasy404** [InZidiuZ/op-framework-issue-tracker#2530]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
No

**Player Identification:**
What is your steam profile?
BigEasy404

**Summary:**
Write a short summary of what you are experiencing.
Today on our gun running island, I got stuck on 4 separate occasions outside of the shed. I could not move, emote, or put anything in my hand from my inventory, yet others around me were fine. I also could not be tackled and was not lagging. On one occasion my character was floating a few feet off the ground and appeared to be free falling in place. The only fix each time was to be carried to the computer and complete the first hack. When it told me the order to enter the keys I immediately was fixed. At first I thought this was an area of the island but the final instance it happened again when i was in a different area of the island. The outlier each time..I was using binoculars. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I believe you would just need to be on our gun running island and use binoculars. The first 3x I was by the white picket fence right in front of the shed. The final instance I was standing near the tree about 20 yards south of the white fence. The binoculars work, but when you put away the binoculars and attempt to walk off is where issues begin.

**Expected Results:**
What are the expected results?
I put away the binoculars and am able to continue moving freely as I was before using them.

**Actual Results:**
What are the actual results?
I could not move (walk, run, crouch). I was stuck in place.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.
![image](https://user-images.githubusercontent.com/115578599/195165841-4939e045-3957-4f48-bffc-0a4200ba1e59.png)

![image](https://user-images.githubusercontent.com/115578599/195166325-d9f61049-e6ec-44a7-9495-5dd6621d44c8.png)

**Game Resolution:**
What is your game's resolution?
2560x1440

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
![image](https://user-images.githubusercontent.com/115578599/195160266-62eaab10-2703-4205-8c03-372a489faa8a.png)

**Server:**
What server/community did this issue occur in?
Legacy

**Notes:**
For anything else noteworthy.

**Comment by coalaura** [comment]
i rewrote the gun running script and this should not be an issue anymore
