### ISSUE TITLE
At present in boombox we have to add single single songs . It can be good if we can add playlist in boombox .

### ISSUE THREAD

**Issue by Verma61** [InZidiuZ/op-framework-issue-tracker#2532]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Summary:**
Write a summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good change to the framework?

**Comment by twooot** [comment]
closed in favor of #1880 also please follow the format next time
