### ISSUE TITLE
[Items/GPS] - GPS Still shows even when Item is removed from inventory

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2533]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile? steam:110000103fea0db 

**Summary:**
Write a short summary of what you are experiencing.

After using the GPS Item, players are presented with the GPS UI however this UI stays and the player stays in the same pose even when the item is removed from the inventory

**Steps to Reproduce:**
1) Get a GPS
2) Use the GPS
3) Press K and move the GPS Item from your inventory to the ground (Or have someone take it from you)

**Expected Results:**
The GPU UI should close and the player should stop holding the "phone" (GPS)

**Actual Results:**
What are the actual results?
UI stays on the screen and is fully usable.

## Additional Information
N/A

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
N/A

**Server:**
What server/community did this issue occur in?
c3s1 (International)

**Notes:**
For anything else noteworthy.

**Comment by twooot** [comment]
Fixed
