### ISSUE TITLE
PD Vehicle Glovebox item deterioration - Suggestion

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2535]
**Assurance:**
Yes

**Summary:**
For PD personal vehicles, make the glovebox *not* deteriorate items faster than they would in, for example, a locker, or a house. And instead, make them deteriorate just as fast as if they were stored in a house, or locker. 
(Possibly the trunks too? Idk maybe other people use their trunks for their weapons so including the possibility)

**Reason:**
Currently with how the International server's PD does things, non-SWAT (and command) cannot carry their rifles or SMG's on their person, and can instead carry them in their gloveboxes, and bring out when needed. (Which I think most, if not all officers who can have one in their car, do.) Now, since items wear faster in cars, this mean when store our weapons in our gloveboxes, they wear A LOT faster than someone who'd be carrying it on their backs. I have found myself buying a lot more rifles because of this wearing, and it would honestly just be nice to have my rifle that I barely ever have to use anyway, not be close to wearing out before I actually need to use it.

**Comment by superiorchicken007** [comment]
Im going to be that guy. I think it should not be changed. you can store your rifle in your locker at the end of your shift or when you go off duty.  This is more because of SOP's and not really a "server" issue.  I know PD has decent paychecks.  I have had the same issue but started hanging my rifle in my locker.

**Comment by ThisIsNotDex** [comment]
> Im going to be that guy. I think it should not be changed. you can store your rifle in your locker at the end of your shift or when you go off duty. This is more because of SOP's and not really a "server" issue. I know PD has decent paychecks. I have had the same issue but started hanging my rifle in my locker.

I don't think this suggestion effects anyone in a negative way. Yes the SOP's make us do it this way now, but we can just change the server to reflect that. And also PD paychecks are good, but, only for people that are doing 10+ hours a week probably. Because im around 4-6 hours a week, and I have not broken 30k in months because of the cost of the job outweighing how much I make in the hours that I can put in. (Which me saying this just points out that other people in the same situation don't need to spend so much money)

**Comment by twooot** [comment]
PD will not get any advantages when it comes to item degradation. There was a previous suggestion asking for more space in PD gloveboxes and it got denied for the same reason.
