### ISSUE TITLE
[game/arena] Arena Chat

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2536]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
As a lot have been developed in Arena I would also like to suggest adding **"Arena Chat"** in which people playing in Arena can only see it.

**Reason:**
Why would your suggestion be a good change to the framework?
As there some things which we only need to communicate between Arena people but there is nothing right now from which it can be done. Using OOC just spams the OOC out of Arena too so it would be great if this will be added.

**Comment by InZidiuZ** [comment]
This has since been added.
