### ISSUE TITLE
[game/inventory?] Allow PD to be able to take EMS/Security/etc. badges

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2537]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
Give PD jobs the ability to move EMS, Government, etc realted badges (i.e. job specific badges)

**Reason:**
Why would your suggestion be a good change to the framework?
RP wise, if a EMS worker or Government worker were to be arrested and have their badges on them, PD has to send them to prison with the badges on them. Instead of turning them into the Head of their Department at a later date, PD could take these badges and return them to the appropriate department. Also if EMS or Government were to ask for the badge at a later date, theoretically they would have to handcuff the person to remove the badge from the fired persons pocket.

**Comment by ImArteria** [comment]
1-up this. I arrested that dirty criminal scumbag Kathryn Santos and I couldnt take her EMS badge off her.

**Comment by twooot** [comment]
i dont think this is really needed since this happens pretty rarely and its not PDs job to decide when badges are to be taken away

**Comment by teddythedev** [comment]
Yeah arresting someone doesn’t mean they are automatically fired. It would be up to their job to bring them in and fire them.
