### ISSUE TITLE
Bug report: Scuffed houses in paleto

### ISSUE THREAD

**Issue by InnerChaos32** [InZidiuZ/op-framework-issue-tracker#2538]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

**Player Identification:**
What is your steam profile?
steam:1100001078534c6

**Summary:**
These 3 houses on Paletto Blvd. are getting worse by the day. When you enter then and walk through, your whole player model vibrates up and down. Here recently everytime I park a car in front of the house on the lawn, I come out of the house and can not enter the vehicle. Happened twice today on house 4 and I had just hard napped after the first time.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
![Houses](https://user-images.githubusercontent.com/116005925/196201222-39680c97-41b8-45a3-9d45-f7302d981251.png)

What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Do you have any clips of this?

**Comment by InZidiuZ** [comment]
Closing due to no response. If you get any clips, please create a new issue.
