### ISSUE TITLE
[game/tablet] Add a "New Game" button to Minesweeper (on the tablet)

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2539]
**Assurance:**
Yes

**Summary:**
When you lose a game of minesweeper on the tablet, there is no prompt to start a new game, or to return to the minesweeper home page. So maybe add a 'Play Again' or home image next to "You Lost" at the top, so you can select a new (X)x(X) option again.

**Reason:**
All the other games have some kind of restart, or home, or play again option, except minesweeper.

**Comment by coalaura** [comment]
done (added highscores too)
