### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#254]
**Name:**
Lars. #9309

**Summary:**
Would be cool if you would fly through the windshield of the car even when you got your seatbelt on. Only if you are above a certain speed, say 100mph for example.

**Reason:**
Think it would be realistic and more fun aswell, let me know what you think :)

**Comment by InZidiuZ** [comment]
Hey,

The belts have already been carefully adjusted to where they are now, and will not be modified for the time being.

**InZidiuZ**
*OP-FW Developer*
