### ISSUE TITLE
PD On-Duty Counter - Downed State

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2542]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.
 - When an officer is in a downed state, remove them temporarily from the on-duty count for banks/stores
 - When they are revived, add them back to the on-duty count

**Reason:**
Why would your suggestion be a good change to the framework?
Currently, officers on duty are counted for stores/banks regardless of health status.  This leads to situations, particularly when fewer PD are online, where officers can be in a downed state and a bank/store can be hit.  Obviously, the downed officers cannot respond to the 10-90 while down.  

This could also slightly reduce the chances of officers being targeted as people would be aware it would potentially hold up jobs.

**Comment by InZidiuZ** [comment]
This has now been done.
