### ISSUE TITLE
Designer Drugs (combine different drugs)

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2543]
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
Write a summary of what your suggestion is about.

Add designer drugs to the city.  

1 Process location, possibly Humane Labs? Since science...

Some ideas:
- Combine 1 Coke, 2 Meth, 1 Green Apple to make a "Liquid Coronary"
        2x the sprint duration and 1.25x the speed of Coke/green apple combined
        NPC sale location in downtown, (for all the overworked employees)
- Combine 2 Oxy, 4 oz weed to make some "Hundred"
       Must be rolled and smoked to keep GW in the loop -> "Rolled Hundred"
       Will ragdoll you for 2 minutes but fully heal/armor you.
        NPC sell location in Southside by MegaMall/Grove St
- Combine 4 Acid, 4 shrooms (any quality) to make a "Bahamas Vacation"
       Will make you drunk animation, blur vision, and randomly punch around you for 5 minutes
       NPC sell location in Vinewood Hills. 

NPC Sell price based on 1.25x the total sell price ranges on the total core ingredients
Obviously all Class A

**Reason:**
Why would your suggestion be a good change to the framework?
- Provide more than 1-2 uses for core drugs in the city to drive up demand and break up monotonous grind
- More places/items for PD/FIB to RP around
- Another place for crims to meet/tax/control/party
- Make less useful/profitable drugs, more valuable without breaking the economy.
- Remove excess low-end items from the economy
- Add additional opportunities to the player economy (as people will be looking to purchase what they lack)
- Add more grindable work leading to more profit for the that put forth the effort

**Comment by coalaura** [comment]
> Combine 1 Coke, 2 Meth, 1 Green Apple to make a "Liquid Coronary"
2x the sprint duration and 1.25x the speed of Coke/green apple combined
NPC sale location in downtown, (for all the overworked employees)

way too op

> Combine 2 Oxy, 4 oz weed to make some "Hundred"
Must be rolled and smoked to keep GW in the loop -> "Rolled Hundred"
Will ragdoll you for 2 minutes but fully heal/armor you.
NPC sell location in Southside by MegaMall/Grove St

2 minutes ragdoll is way too long and not worth full armor considering you can get drunk to get full armor or smoke weed

> Combine 4 Acid, 4 shrooms (any quality) to make a "Bahamas Vacation"
Will make you drunk animation, blur vision, and randomly punch around you for 5 minutes
NPC sell location in Vinewood Hills.

has no positive effect?

**Comment by MetaHatter** [comment]
These were just starting point conceptual examples... Possible tweaks below:

> > Combine 1 Coke, 2 Meth, 1 Green Apple to make a "Liquid Coronary"
> > 2x the sprint duration and 1.25x the speed of Coke/green apple combined
> > NPC sale location in downtown, (for all the overworked employees)
> 
> way too op
> 

Maybe just 1.5x the sprint duration? Or 2x the duration but you OD twice as fast?

> > Combine 2 Oxy, 4 oz weed to make some "Hundred"
> > Must be rolled and smoked to keep GW in the loop -> "Rolled Hundred"
> > Will ragdoll you for 2 minutes but fully heal/armor you.
> > NPC sell location in Southside by MegaMall/Grove St
> 
> 2 minutes ragdoll is way too long and not worth full armor considering you can get drunk to get full armor or smoke weed
> 

Could this maybe be a heal over time?  Like 75 health over 5 seconds or something?  Or even stress reduction over time? Stress immunity for 5 seconds?
Just spit-balling ideas to make it worthwhile.

> > Combine 4 Acid, 4 shrooms (any quality) to make a "Bahamas Vacation"
> > Will make you drunk animation, blur vision, and randomly punch around you for 5 minutes
> > NPC sell location in Vinewood Hills.
> 
> has no positive effect?

These are easily acquired items so it would be mostly for memes/NPC sales and to create potential social interactions w/trading.  5 minutes might be too long, maybe 60 seconds.

Again, all these effects are secondary to trying to give more purpose to existing drugs and add RP opportunities across the criminal spectrum

**Comment by coalaura** [comment]
If i'm being honest i would rather add a new unique drug than add new drugs by allowing people to combine existing ones
