### ISSUE TITLE
[alpha/vehicles] Free PDM LS customs for testdrives (visual upgrades only)

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2546]
**Assurance:**
Yes

**Summary:**
At PDM, with the current repair bay it has, lets turn that into a "Free" Benny's where people can **ONLY** customize _test drives_ at no charge. Allowing people to equip cars with visual upgrades only,  **NO** engine upgrades to avoid people abusing test drives, so they can see how the car would look with customizations they would add on if they were to buy it. 

Location (Remove Vehicle Lifts): https://i.imgur.com/6pApK3F.jpeg  

Some possibilities for the implementation of the feature could be, people are put onto a normal test drive, and a salesperson can open up the gates to allow them to drive into the bay, and enter it like a Benny's, then they can backspace out of the menu.
_If this option is done, possibly remove/keep all upgrades added, not sure, could be discussed in random polls_

Possibility 2, add a command such as "/preview (paypal) (vehicle slot)" and this would place the customer into the vehicle **AT** the customization location, and would turn the vehicle engine on, but freeze the car so it cannot be driven away. Then the customer would just press backspace to back out of whatever menu they are in, and once on the main list when they hit backspace again it despawns the vehicle, and places them Just in front of the white box pictured above.

**Either of these options would Face their car away from the wall, as well as other people can see the car as they are upgrading it**

**Reason:**
This would allow people who are potentially purchasing PDM vehicles see the vehicle they want fully equipped with upgrades they would add, without costing them anything like a normal Benny's / LSC. 

This feature could be thought of like a vehicle manufacturers website, where you can build and customize a car to your specification, and see what it would like before purchasing it.

**Comment by twooot** [comment]
People can already easily check what upgrades there are by driving into LS customs and just not actually purchasing stuff, no?

**Comment by FragileLiz** [comment]
You can see individual upgrades, but it can be difficult to see how they look if you get a test drive car that’s black. Also you might get a color that clashes with liveries/color accents and that makes it kind of a pain to tell what things look like unless you pay to change the primary/secondary colors. It would also be nice if you were able to see what combinations of cosmetic upgrades looked like before purchase, especially with how many options a lot of the PDM cars have.

**Comment by MetaHatter** [comment]
Would be interesting if Benny's tallied the total and you only paid on a confirmed checkout. This would potentially solve this concern as well as making the Benny's experience subjectively better overall.

Not sure how feasible that would be though.

**Comment by twooot** [comment]
bennies needs to b rewritten someday anyways tbh, script is ass currently. Would be a thought to keep in mind if we ever get to that

**Comment by CruzClementina** [comment]
To continue with this - I think this would really help sell cars. 
When you go into Midnight they are able to customize the cars as they wish and display them. If this were allowed it would let people take the car and see all the potential that some of the cars have.

**Comment by ThisIsNotDex** [comment]
> People can already easily check what upgrades there are by driving into LS customs and just not actually purchasing stuff, no?

Late reply, but to answer that, like Fragile said, it would be to help people to equip the customizations that they would put on a car if they were to purchase it. Instead of looking at and trying to remember what the front bumper looked like with a hood you also liked.

**Comment by coalaura** [comment]
Done
