### ISSUE TITLE
[vehicles/garages] Add a public garage at the VU

### ISSUE THREAD

**Issue by EXO1111** [InZidiuZ/op-framework-issue-tracker#2549]
### Assurance

I have read the `README.md`

### Summary

adding a garage to the carpark of VANILLA UNICORN for employees.

### Reason

i think adding a garage in the vu carpark would be great, it's super annoying coming outside and seeing that your car has completely disappeared. it'll save employees time, its convenient and cars shouldn't be really despawning in the first place so i do believe it most certainly should be added and would improve the server.

**Comment by CloudTheWolf** [comment]
I think this is a good idea as there is no public garage near by and means the outside parking can be for customers.
Other business (Luxury Autos) have a business garage so I see no reason VU get one.
Bean Machine have a Normal Garage behind them, and the arcade have a secure area for parking.

**Comment by twooot** [comment]
done
