### ISSUE TITLE
Lost MC EUP 

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#255]
**Name:**
DegenTheo#2209

**Summary:**
I would love to see custom jackets with the Lost MC logo on the back. It would be really cool for people that use the normal playermodels.

**Comment by InZidiuZ** [comment]
Hey,

I've already looked into this, but found out that all the *proper* The Lost MC clothing wasn't for the freemode models. Anyways, closing for now, as I have no way of implementing this. If *you* do, however, find some clothing for the *freemode* model(s), then feel free to message me on discord.

**InZidiuZ**
*OP-FW Developer*
