### ISSUE TITLE
Airport Spawner

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2552]
### Assurance

I have read the `README.md`

### Summary

It would be great if there is a heli spawner at Weazel News HQ. 
![FiveM_b2699_GTAProcess_56H32Hf7zC](https://user-images.githubusercontent.com/29286961/198285653-3857f141-2ba7-4106-a229-c4a29a981efb.png) (Somewhere over here)
![FiveM_b2699_GTAProcess_DAw9jazIc4](https://user-images.githubusercontent.com/29286961/198285664-361263a8-df41-4045-823c-3c0e2f0ad3f2.png) (HQ location)

### Reason

So the Weazel News Employee don't have to run to a different heli spawner for their heli for spawning the heli.

**Comment by CloudTheWolf** [comment]
I'm sure there is a spawner there still (I know there used to be)
But I believe it locked behind both a job and licence

**Comment by twooot** [comment]
if you have the job you can access it ![asdf](https://raw.twoot.org/YArAbaro49.png)
