### ISSUE TITLE
[alpha/vehicles] Suggestion - Reduce Police livery price

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2553]
### Assurance

I have read the `README.md`

### Summary

Reduce the cost of police liveries down to like $200. Right now I think they are about $1,200-$1,500.

### Reason

For FIB and SWAT (in the international server) often times both divisions have to swap the liveries on their vehicles from marked units, to blacked out livery for operations. The high cost of theses liveries and having to switch between them often really hurts the bank account when cops who don't get 15+ hours a week don't make any more money than they already have because of the cost of the job.

**Comment by Mugdha57** [comment]
Agreed!! often!! ftos need to change their liveries.

**Comment by teddythedev** [comment]
If we allowed multiple cars in the other suggestion we wouldn’t need to change this

**Comment by ThisIsNotDex** [comment]
> If we allowed multiple cars in the other suggestion we wouldn’t need to change this

I guess, _but_ still would be nice to not have them cost so much for when someone does buy a car, and puts whatever livery on.

**Comment by coalaura** [comment]
done
