### ISSUE TITLE
[vehicles/garages] Suggestion - Making all PD vehicles purchasable/increasing inventory slots

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2554]
### Assurance

I have read the `README.md`

### Summary

The ability to purchase more of the police vehicles we have available to us inside of PD. 

- Increasing the amount of ownable vehicles in the PD garage to 8, Being part of multiple divisions means the need to own more than 4 vehicles so we have to pick and choose. 
- The ability to purchase the vehicles that we currently just "Pull" from the PD garage. Having the option to purchase these vehicles allows us to have our liveries applied, and Be able to use the trunk storage and glovebox of those cars. This includes the Bike units, Speed units, and Armored vehicles. 
- Owning vehicles such as the Bearcat would allow divisions like SWAT to keep the trunk of that vehicle full so it's ready for anything. Having the trunk of the vehicle loaded with PD assets such as Extra guns, Ammo, and Body armor. 
- Trunk space of larger vehicles increased to 750, Useful for raids and needing to move mass amounts of items. Useful for FIB and SWAT. vehicles such as the Bearcat, Tahoe, RAM Truck, and F150. 

### Reason

Overall these are useful assets to Legacy PD however this change would make them more useful and save us time when needing to load these vehicles for situations.
Pros
PD spends less time adding extras and liveries to their car. Having to guess certain extras per vehicle. 
PD can have items and armory assets inside the trunks of more vehicles, benefiting certain divisions by having armored vehicles ready to go.
Cons
These vehicles can be expensive, not everyone in PD is loaded. 
Making the other vehicles purchasable and customizable.

**Comment by superiorchicken007** [comment]
I was going to suggest the same thing however make it so you can only a maximum of 1 vehicle each (i.e. 1 Caprice, 1 F250, ect.) but open it up so you can have more of each like 8-10 like @Skai97 suggested.

**Comment by ThisIsNotDex** [comment]
This is a great idea, it would be nice to have regular marked vehicles for patrol use, and have another one ready to go in an instant that can be unmarked. With any gear already inside.

And also, **possibly** add the ability to rename vehicles, so that if you have 2 tahoes or 2 explorers, for example, you can rename them. Such as "(Un)Marked Tahoe" "(Un)Marked Explorer"

**Comment by teddythedev** [comment]
Would love to see at least bike units, speed units, and bearcat be moved to purchasable. Then upping owned vehicles to 8 would be ideal.

we really make use of the trunks for supplies in shootouts and that would help handle that, plus then people can’t just not care about a speed or bike and just get a new one when they crash or Fuck it up. 

I do also like the idea of multiple of the same vehicle. Never should that be used for just switching out if your vehicle is damaged and having multiple that way. It should only be used if you need an unmarked car or something for divisional work

**Comment by twooot** [comment]
> Increasing the amount of ownable vehicles in the PD garage to 8, Being part of multiple divisions means the need to own more than 4 vehicles so we have to pick and choose.

Yes can do that, maybe not 8 but 6 or so

> The ability to purchase the vehicles that we currently just "Pull" from the PD garage. Having the option to purchase these vehicles allows us to have our liveries applied, and Be able to use the trunk storage and glovebox of those cars. This includes the Bike units, Speed units, and Armored vehicles.

No, these are not patrol vehicles and should not be owned by players. There is a reason they are in a separate spawner.

> Trunk space of larger vehicles increased to 750, Useful for raids and needing to move mass amounts of items. Useful for FIB and SWAT. vehicles such as the Bearcat, Tahoe, RAM Truck, and F150.

Yes, that i can do too

**Comment by twooot** [comment]
> Would love to see at least bike units, speed units, and bearcat be moved to purchasable. Then upping owned vehicles to 8 would be ideal.
> 
> we really make use of the trunks for supplies in shootouts and that would help handle that, plus then people can’t just not care about a speed or bike and just get a new one when they crash or Fuck it up.
> 
> I do also like the idea of multiple of the same vehicle. Never should that be used for just switching out if your vehicle is damaged and having multiple that way. It should only be used if you need an unmarked car or something for divisional work

I also wont add the ability to own multiple of the same car. I went over this with twentz in pretty big detail and my decision has not changed

**Comment by teddythedev** [comment]
Sounds good if we aren’t able to move those to garages.. wasn’t really because of patrol the only reason was being able to stock them with gear for shootouts which is a big use of them and it’s spawned we can’t do that quickly. 

If we don’t make the bearcat purchasable then no need to up the trunk size just the other bigger vehicles.

Thanks for everything

**Comment by teddythedev** [comment]
If you can’t own multiple of the same vehicle either then no need to up from 4 to 6 really either just trunk size I guess 😂

**Comment by superiorchicken007** [comment]
The only reason I say to add 2 more is because of Divisional work.  I also agree with the trunk sizes especially with the bearcat.  That would not be good to place items in the back due to it being a "Local" vehicle and the trunks used to scuff out (Not sure if they still do or not)  But I do agree about not being able to own multiple of the same car.

**Comment by twooot** [comment]
> If we don’t make the bearcat purchasable then no need to up the trunk size just the other bigger vehicles.

Why no need, it would still be useful to have a bigger trunk for shootouts and other occasions, no?

**Comment by teddythedev** [comment]
So divisional work you would just use a car you normally don’t drive then blacked out? Because like SWAT patrol is the 18 charger which many already use that as their patrol car too.

**Comment by teddythedev** [comment]
> > If we don’t make the bearcat purchasable then no need to up the trunk size just the other bigger vehicles.
> 
> Why no need, it would still be useful to have a bigger trunk for shootouts and other occasions, no?

I don’t think anyone will stock it that full with the possibility of losing it since it’s spawned in and for raids we only put stuff in vehicles that are purchased now

**Comment by teddythedev** [comment]
But I guess it doesn’t hurt to up it if some people want to

**Comment by superiorchicken007** [comment]
> 

SWAT Patrol has several vehicles they can use in the SOP's. Yes the 18 is ideal but most also use the Taurus, Tahoe, and Crown Vic. Personally I use the Tahoe for both SWAT and IA. I am just thinking of others is all.

**Comment by teddythedev** [comment]
My thought was swat people who are certified to drive the bearcat (who are the only ones who can take it out anyways right now) would be able to purchase one and load it with gear, ammo, guns etc and grab it for a shootout. They still could just will take a lot longer and shootout probably done by that point. 

But I totally understand why we wouldn’t want those purchased as well

**Comment by teddythedev** [comment]
> SWAT Patrol has several vehicles they can use in the SOP's. Yes the 18 is ideal but most also use the Taurus, Tahoe, and Crown Vic. Personally I use the Tahoe for both SWAT and IA. I am just thinking of others is all.

Yeah makes sense. No harm in making it 6 then for those especially if you can’t purchase the same vehicle.

**Comment by teddythedev** [comment]
Laura if you want to DM me we could talk more about It too unless you want to just keep through here

**Comment by MetaHatter** [comment]
Really off the wall thought... What if the bearcat trunk was a mobile PD store?  
Probably too crazy of an idea (and not sure if it's even possible).

**Comment by twooot** [comment]
> Really off the wall thought... What if the bearcat trunk was a mobile PD store?

too op imo

**Comment by twooot** [comment]
Increased max ownable vehicles from 4 to 6 and increased trunk sizes for bigger vehicles.
