### ISSUE TITLE
Suggestion - PD Spotlight to Search for Casings

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2555]
### Assurance

I have read the `README.md`

### Summary

By using the 'G' key, you can toggle on the spotlight on a PD vehicle. It would then show up any casings in a reasonably small area (same as flashlight) that are on the ground.

### Reason

This would be incredibly useful for searching large areas for bullet casings. It is a tedious process and can take a long time. You would still have to exit the vehicle, take a picture of the casings with the camera, use the flashlight to find them and pick them up, but it makes the step of actually looking for the casings much quicker. It would be especially useful when searching for casings over a large area.

**Comment by ImArteria** [comment]
On top of this, make Spot Lights work for everyone again 🙏

**Comment by twooot** [comment]
No, you would not be able to spot a casing with a spotlight from inside a moving car

**Comment by twooot** [comment]
The point is that you have to get out with a flashlight, putting you into a vulnerable position and also INCREASING the time it takes to collect evidence
