### ISSUE TITLE
 [alpha/vehicles] Suggestion - Mechanic LS Customs / Changes to Midnight Customs

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2556]
### Assurance

I have read the `README.md`

### Summary

To further enhance RP and try to improve the Mechanic / Player Relations I think I would be a good idea to have Mechanics be able to do _some_ of the the customs work, similar to Midnight.
Essentially giving Mechanics and Tuners 3 Specialities each, and both being able to do engine upgrades (With Midnight keeping EMS 5 as their Special)

Eg:

**Mechanics offer discounts on:**
 - Engine Upgrades (Upto EMS: 4)
 - Transmission
 - Breaks
 - Wheels

**Tuner Shops offer discounts on:**
- Engine Upgrades (Upto EMS: 5)
- Turbo Tuning
- Suspension
- Cosmetics (Respray & Liveries) [Could allow for Some future liveries to be Midnight Exclusive in future]

### Reason

This would:
- Provide more RP for Mechanics
- Give players more options for getting upgrades Cheaper 
- Give Midnight some competition and allow players to get some upgrades cheaper when they are closed 
- Add opportunities for Exclusives and other deal in future.

**Comment by twooot** [comment]
I think this would drive away customers away from midnight even more
