### ISSUE TITLE
[alpha/tow] Suggestion - Harmony Improvements 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2557]
### Assurance

I have read the `README.md`

### Summary

I would like the following changes made to Harmony:

1 - Add functionality the Outside Workbench (As discussed in discord)
2 - Move the LS Customs from the Inside Bay to the Spray Booth (Inside Car Wash) 
3 - If Possible Remove car wash functionality from Spray Booth, as we now have an Air Unit (Not sure if this is tied to the MLO or Co-Ordinate Based) 

### Reason

1 - As we now have a Workbench and outside bay, it would be nice to not have to run in and out of the shop to craft
2 - This would allow us to use both bays and still let people come in and use the customs
3 - Not _required_ but if suggestion 2 is done would make it a better experience.

**Comment by twooot** [comment]
All done except for the car wash, which is tied to the object itself not the location
