### ISSUE TITLE
Suggestion - Add a Collectors Bazaar

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2558]
### Assurance

I have read the `README.md`

### Summary

Add a Collector's Bazaar at the following location that will buy a large variety of items from players for largely TERRIBLE prices.

This Bazaar with be marked clearly on the map and included in the New Player Brochure

![bazaar Location](https://user-images.githubusercontent.com/84351858/198889249-244762e5-2a8c-48c3-8f59-752a53289383.png)

Items that can be sold there (proposed)

Junk Collector	
cleaning kit	$10
phone		$100
basic pick	$20
advanced pick	$40
basic repair	$20
adv repair	$40
watch		$50
Compass		$25
Body Armor	$50
	
Sports Collector	
Baseball			$10
Baseball Bat		$10
Golf Club			$10
Pool Cue			$10
	
Adventurer	
Leather			$10
Meat			$5
Hunting Rifle		$100
Bear Trap			$100
Treasure Map Piece	$50
	
Gun Collector	
Stun Gun		$50
.45 Pistol		$100
SNS			$100
Vintage		$100
Damaged Gun	$10
Taser Cartridge$10
Pistol Ammo	$10
Sub Ammo	$10
Rifle Ammo	$10
Sniper Ammo	$10
Shotgun Ammo$10
	
Weapon Collector	
Cavalry Dagger$20
Broken Bottle	$3
Crowbar		$20
Flashlight		$10
Hammer		$20
Hatchet		$20
Brass Knuckles	$20
Knife		$10
Machete		$20
Switchblade	$20
Nightstick	$10
Pipe Wrench	$50
Battle Axe	$50
Stone Hatchet	$50
	
Metal Collector	
Scrap		$10
Aluminum	$20
Steel		$30
Glass		$5
Rubber		$4
	
Jewelry Collector	
Raw Gems	$50
Refined Gems	$150
Gold Bar		$250
Necklace		$50
silver watches	$50
diamond		$1,000

Proposed Stalls
![Bazaar Stalls](https://user-images.githubusercontent.com/84351858/198889250-27f5a447-3637-40f4-be5f-9f4a5a3387bb.png)

### Reason

This will provide a multitude of functions, all of which are beneficial to RP, socializing and the economy

- Will create a place for beginner players to sell the items they find with little knowledge of the city (some money is better than no money)
- Will create a place for veteran players to dump excess items
- Will create a location for people to congregate and meet new people
- Players can use this spot to meet up to trade (instead of Trash HQ)
- Will foster socializing as people communicate to learn the REAL Places to sell the items for good money
- Will remove excess items from the world
- Close enough to MRPD to simplify patrolling for shenanigans  

Added location benefit: There is a wall surrounding the location that will partially reduce the chances for VDM

**Comment by twooot** [comment]
done
