### ISSUE TITLE
[game/doors] Suggestion - Add Locks to Harmony Repair doors

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2559]
### Assurance

I have read the `README.md`

### Summary

Following the removal of the LS Customs inside the Harmony mechanic shop, can we have locks added to the 3 doors and have them lock by default when the server restarts.

This would mirror the locks that they have at the LostMC, who use the same interior.

### Reason

This would allow the harmony mechanic shop to be closed to the public while interviews / meetings are taking place.

Any mechanics working while the meetings/interviews are happening could still do repairs using the Outside bay / workbench and there is an ATM over the road for customers.

**Comment by twooot** [comment]
done
