### ISSUE TITLE
PDM REPO

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#256]
**Name:**
Who is suggesting this? Cricketx818

**Summary:**
I think you should Allow PDM Employs with ranks of "Senior Sales, Assistant Manager, & Boss" To Impound cars OR to run plates, to see if cars are behind payments or not. Or even just the Boss can impound the cars and others can just run plates so the system doesn't get abused, Sometimes the parking lot gets filled with Local cars and people cant come in & PD is to busy to come and impound it.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Reason why I think this will be a good Idea is because, Some people bought cars one OPFW was out and they have decided on not to pay the payments, And they can not buy another car until they are paid till payday, So I think this will be a great Idea. Thanks

**Comment by HazzerEFC** [comment]
this sounds like a good idea, but i think all vehicles that we sell should be notified to police automatically and they should send us wanted vehicles, and it would cost them to get the vehicle back the finance and *an extra charge* Failure to do so will keep the vehicle impounded. that way, PD mechanics and PDM all get a bit in it.
not sure what you think

**Comment by Cricketx818** [comment]
If you are late on payments and the car gets impounded It would not make sense to get the car back, if it gets impounded its gone forever until you buy another one. Also we sell over 10-20 cars on a daily bases so it will be impossible for PD to remember all the cars that need to get impounded.

**Comment by HazzerEFC** [comment]
seems fair on a realistic level

**Comment by Cricketx818** [comment]
If legacy was whitelisted for sure that would be possible but we get new people in everyday and come in and buy cars, so it will be very very hard for PD to remember that's what I meant

**Comment by InZidiuZ** [comment]
Hey,

I've added the ability for PDM workers to do /impound, but if abused, it will be removed again.

**InZidiuZ**
*OP-FW Developer*
