### ISSUE TITLE
Suggestion - Owning Pets

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2560]
### Assurance

I have read the `README.md`

### Summary

So Super admins can Spawn Animals ( Ped ) and Give them Task To Follow Specific Player which works as their Pet In-game we can Make Them Fear Less and Much More I think There should be a way to own a Pet that Follows them around there should be a Pet animation so You can Play With Your Pets and Maybe add A Inventory Item or command so when people Use that their Pet Will Spawn and to use that command you need to buy that Pets From Store and Maybe only those people can own it who have Prio which sound cooler So that It has Some Importance in Server maybe Only God Like that I think You guys can decide I love Dogs and I want Dog Pet in Rp :)

### Reason

It will Increase RP and Those who are Cat or Dog Lovers They can Own pets in the Game which will be Much cooler and more exciting.

**Comment by twooot** [comment]
Peds in general are very very very scuffy. So if superadmins want to do it yeah sure go for it but its not an intended design and i dont think we need npc animal pets
