### ISSUE TITLE
There should be a storage locker for Luxury Autos Employees - 

### ISSUE THREAD

**Issue by eDshot47** [InZidiuZ/op-framework-issue-tracker#2562]
### Assurance

I have read the `README.md`

### Summary

As the title suggests a storage locker will help employees keep their belongings inside the locker similar to Burgershot and other businesses. It's simple and I think almost any business-related mlo's should have a usable locker for their employees to use. business-related.

### Reason

It will be easy to store their belongings and keep them safe. In-RP we can store some documents that we otherwise kept in car trunks or house it will be more organized and I believe it will be a good quality of life improvement overall.

**Comment by twooot** [comment]
No, there is absolutely no need for a locker
