### ISSUE TITLE
Joint Item Buff

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2563]
### Assurance

I have read the `README.md`

### Summary

Summary: Adjust the joint item mechanic from giving 10% armor and stress relief to how the alcohol armor effect currently works. Along with this change make the alcohol armor fill to cap out at like 10% so it does not fully replenish your armor. Essentially switching out the effects. This makes more congruent sense for a smoking mechanic where a player is locked in position for an extended period of time and brings value back to weed outside of sale value.

Having a few interactions seeing that some players will pro getting drunk and waiting for the armor is cool but still dumb at the same time. Rolling papers were added for GW to hard push the interaction incentive there. The whole alcohol situation mitigates that.

### Reason

- Current joint item is not used enough by players
- QOL
- More interaction at Green Wonderland

**Comment by twooot** [comment]
i buffed joints a bit and changed them to work more over time than all at once. Wont change alcohol tho
