### ISSUE TITLE
Suggestion - Pressing the "Escape" key closes the MDT 🙏 

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2564]
### Assurance

I have read the `README.md`

### Summary

When you do /mdt, your only way to close it is by pressing the "X" button. I am humbly requesting that when you press "Escape", it also closes the menu

### Reason

My roleplay is extremely hindered by making me click the "X" as opposed to pressing Escape. 
(On a real note this is just a quality of life thing)

**Comment by ThisIsNotDex** [comment]
Big ups

**Comment by CloudTheWolf** [comment]
The only issue with this is, if you hit escape in error while writing a report you'll have to start over (#2565 in relation to this)

**Comment by twooot** [comment]
Not nicely doable due to the fact its an external site. Any pressing x is fine imo. Same reason you cant exit out of the PDM and EDM catalogs using escape
