### ISSUE TITLE
[game/mdt] QOL Suggestion - Don't reload page when opening MDT (External MDT)

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2565]
### Assurance

I have read the `README.md`

### Summary

When using the MDT command with an external site, if you after the first time opening it after flying in, it should just remain on the page the player was last on (Eg on an incident) rather than reloading back to the dashboard

### Reason

This would allow players to "Minimise" the MDT if they need to grab some information, Eg they need to add a missing image to Data Dump, before continuing with the report they are writing rather then risk losing work because they hadn't saved

**Comment by twooot** [comment]
Fixed
