### ISSUE TITLE
Suggestion - On Duty Time Tracking per tracker

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2566]
### Assurance

I have read the `README.md`

### Summary

We currently track the total time on duty if you are on normal tracker and/or undercover. Would we be able to track the total time per tracker so that we can make sure people aren't abusing the tracker system?

### Reason

Would help make sure people are using the trackers properly and be able to see how much time people are patrolling vs undercover vs training.

**Comment by Mugdha57** [comment]
This is really a good suggestion.

**Comment by coalaura** [comment]
Duty time (for "Law Enforcement") now looks like this:
```json
{"103":1456,"104":1311,"101":174,"106":{"training":16,"normal":765,"undercover":9},"93":1268,"95":3503,"96":290,"97":3744,"105":249,"92":3248,"98":2988,"100":81}
```

Old weeks will still persist with just a single number and any tracking from now on is split into "training", "normal" and "undercover".
