### ISSUE TITLE
[game/airports] Aircraft security deposits

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#2567]
### Assurance

I have read the `README.md`

### Summary

I propose spawning an aircraft should cost a certain amount of money depending on the license type being used (regardless of how the license was obtained). And the money can be returned when the aircraft is parked back at any hangar, perhaps minus a small fee that would realistically cover "renting" it, taking it out, fuel costs etc.

### Reason

Once you are licensed, you are able to use and take out a variety of aircrafts with no financial burden and almost no limits. This ability in itself is unrealistic, and I think the deposit I propose or any other step should be taken to balance this feature out for the long run, and hopefully provide an incentive to return aircrafts, not wanna crash them, and generally operate them reasonably and realistically.

**Comment by vol5** [comment]
This is an interesting idea. But is not needed if ownership was implemented. Its reasonable provided ownership is not a SoonTM implementation.

**Comment by ThisIsNotDex** [comment]
Yeah, could possibly build off the pre-existing code for test drives. (Not sure, I know squat about coding)

**Comment by coalaura** [comment]
this has been done

**Comment by King2704** [comment]
This is just gonna result in people losing money due to them not being able to store them most of the time. (this happens atleast 50% of the time) Making helicopters ownable would probably be a bit more dev work but a better solution imo since this would also allow people to customize them.

**Comment by MetaHatter** [comment]
An alternative solution would be to look into fixing potential storage problems.
