### ISSUE TITLE
Suggestion - Change the high temperature for the seasons

### ISSUE THREAD

**Issue by taylorwiffed** [InZidiuZ/op-framework-issue-tracker#2568]
### Assurance

I have read the `README.md`

### Summary

Now that the smart watch says the temperature, having it go from 80F to 17F and snowing and back to 80F is odd. If caps were set for the temperature based on the season, it would feel more appropriate. 

### Reason

I live in New England, where our weather can change drastically in a day, but 80 - 17 - 80 is apocalypse type ish :D Just a suggestion for the immersion in the seasons.

**Comment by twooot** [comment]
Ok i think i've figured out a somewhat decent solution based on the day of the year
