### ISSUE TITLE
Nagasaki BF400

### ISSUE THREAD

**Issue by Pizzzaa** [InZidiuZ/op-framework-issue-tracker#257]
**Reporter:**
Luis Siul. 

**Summary:**
Usually when you get on any kind of vehicle that vehicle starts the engine on itw "own" but since yesterday when i get on that bike "nagasaki bf400" i have to do /ENGINE to start it. Also i have issues getting on it by that i mean when iam close to it and press "F" to get on it my guy would ran across the street to hop into a car? and i can lock/unluck my bike multiple times and it wont go on.

**Steps to Reproduce:**
Dont know thats why iam reporting it.

**Expected Results:**
Fix. :)

**Actual Results:**
Dont know yet.

## Additional Information

**Screenshots:**
/

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Closing as I'm unable to replicate this, there's no repro and no video. I'd say try clearing your cache to see if that resolves it, it seems very odd there would be issues with that bike, as we haven't made any changes to it. (from what i know) If the issue persists, however, feel free to create another report with a full repro.

**InZidiuZ**
*OP-FW Developer*
