### ISSUE TITLE
Suggestion - PD Nerf (Battering Ram Changes)

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2570]
### Assurance

I have read the `README.md`

### Summary

Few changes to the battering ram to possibly help encourage RP during search warrants/raids
- Everyone with keys gets alerted when the building is breached. That way if the owner is not online, other people are aware and have the opportunity to intercept
- The Battering Ram itself has a 30 second timer to enter the building. This will allow more "time" for people to intercept and get set up, along with PD having to think about who theyre bringing it, what they bring it (depends on what they find/carry out), and how they go about it.

### Reason

The whole idea of it, presented by FIB themselves, is to hopefully add more time for people to intercept during raids. We're hoping that these changes along with a possible staff sided-change will give more incentives to counter the raid. 
As a whole, provide more RP for PD, Criminals, and the server as a whole

**Comment by twooot** [comment]
Nerfing PD? Sorry man, i love PD, i can only buff them.

**Comment by ImArteria** [comment]
> Nerfing PD? Sorry man, i love PD, i can only buff them.

Dude stop being toxic. I am trying to make this server less PD sided so can you please be serious like this isn't funny dude stop it

**Comment by DCS281** [comment]
> > Nerfing PD? Sorry man, i love PD, i can only buff them.
> 
> Dude stop being toxic. I am trying to make this server less PD sided so can you please be serious like this isn't funny dude stop it

Can you please stop being rude to the developer who is constantly buffing PD? That's the entire point here

**Comment by twooot** [comment]
> > Nerfing PD? Sorry man, i love PD, i can only buff them.
> 
> Dude stop being toxic. I am trying to make this server less PD sided so can you please be serious like this isn't funny dude stop it

Listen man, we need to buff PD. They are not overpowered enough yet. DONT YOU UNDERSTAND???

**Comment by ImArteria** [comment]
> > > Nerfing PD? Sorry man, i love PD, i can only buff them.
> > 
> > 
> > Dude stop being toxic. I am trying to make this server less PD sided so can you please be serious like this isn't funny dude stop it
> 
> Listen man, we need to buff PD. They are not overpowered enough yet. DONT YOU UNDERSTAND???

I think I see your point. I want to change this suggestion to create a bot in the FIB database for telling us when a certain crim is not online so we know when to raid them. Thank you for your hard work!

**Comment by twooot** [comment]
> I think I see your point. I want to change this suggestion to create a bot in the FIB database for telling us when a certain crim is not online so we know when to raid them. Thank you for your hard work!

Bet i'll get right on that. Do you still need that database of what houses the crims store their guns in?

**Comment by ImArteria** [comment]
We've been nerfed too hard. I am closing this nerf.
