### ISSUE TITLE
Suggestion - Picking/Selling Fruit

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2571]
### Assurance

I have read the `README.md`

### Summary

Base idea (Laura pls this isn't an essay just pictures and stuff)

- Certain trees/bushes you can walk up to, and press E on them to pick fruit. 
- When you pick the fruit, you can either use it for food or sell it for a very minuscule price (like 5$ a piece or something) at the farmers market in grapeseed
- Would use /e inspect to be the animation of "picking" the fruit (unless you guys find a better one, I couldn't)

**Oranges**
- Grapeseed
https://i.imgur.com/yOd4fIj.png

**Grapes**
- Vineyard
https://i.imgur.com/GQPfszP.jpeg

**Cabbages**
- Grapeseed
https://i.imgur.com/3JqCLoY.jpeg
(There is a Cabbage prop so I'd just place a few here)

**Coconuts**
- Vespucci/Chumash
https://i.imgur.com/dkx1erf.jpeg

**Cherries**
- Paleto 
https://i.imgur.com/w4WHRL3.jpeg

**Apples**
- Paleto
https://i.imgur.com/sDhwfKK.jpeg

**Animation for Tree and other Fruits**
Tree
https://i.imgur.com/gBi3DzD.png

Smaller Fruits
https://i.imgur.com/OadGnRb.png

**Selling Spot**
https://i.imgur.com/FH3FFm4.png
- Grapeseed

### Reason

Really won't bring an insane amount of RP. I just figured this was a cool little idea that wouldn't be too grindy nor get too much money but more of a "healthier" way to get food. In the future if we ever added some type of "Wine" mechanic for the vineyard the grapes would help with that

Something for legal people to do.

**Comment by twooot** [comment]
Ok you can now pick cabbage and pumpkins in paleto. Those can be used to craft other things. I dont like the idea of selling even for a low price cause it will either be too much (everyone is gonna do it) or too little (nobody is gonna do it) since it involves 0 effort. I made the system somewhat configurable so we can add more things to it down the line if there are some good props for it. I'll mark this as done for now

**Comment by ImArteria** [comment]
> Ok you can now pick cabbage and pumpkins in paleto. Those can be used to craft other things. I dont like the idea of selling even for a low price cause it will either be too much (everyone is gonna do it) or too little (nobody is gonna do it) since it involves 0 effort. I made the system somewhat configurable so we can add more things to it down the line if there are some good props for it. I'll mark this as done for now

cabbage
