### ISSUE TITLE
Suggestion - Civilian boat spawner for FIB

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#2574]
### Assurance

I have read the `README.md`

### Summary

Add a civilian boat spawner for undercover officers. Ideally in close proximity to the shoreline of FIB HQ but any place on the map could do.

These boats should be enough but open to everything
Dinghy
Jetmax
Suntrap
Seashark (jetski)

### Reason

Enable police roleplay more conveniently

**Comment by twooot** [comment]
done
