### ISSUE TITLE
Suggestion - Let us steal PD Armor n heals

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2575]
### Assurance

I have read the `README.md`

### Summary

I didn't read the readme thing.

Ok so shit is straightforward af, During a shootout i might run out of heals or armor, usually neither because im top shoota. Anyway PD can rob us when we are down to resupply during a shootout which is actually a good thing, then crims should be able to do it too. I bet u guys r like "noo ppl r just gonna rob cops for their armor or heals" no bro thats way too much work just for a couple of armors and heals n its gonna get mfers banned so they prolly wont wanna risk it. ty that is all. im still gonna complain in gen chat tho

### Reason

It's more balanced for both cops n crims. If cops can take armor and heals off of crims then crims should be able to do that too.

**Comment by twooot** [comment]
yeah sure we can give it a shot. inb4 cops sell their armors and medkits

**Comment by twooot** [comment]
actually just checked, first aid kits and ifak are already robbable
