### ISSUE TITLE
The Luxury Dealership

### ISSUE THREAD

**Issue by ilSensei** [InZidiuZ/op-framework-issue-tracker#2576]
### Assurance

I have read the `README.md`

### Summary

Will be cool to add functions on the Luxury Dealership like as Premium Deluxe Motorsport, but with Super Vehicle Vanilla that's u can't find or buy from Premium Deluxe Motorsport to improve more RP into Dealership.

### Reason

The reason why this function for the framework will be nice, first there is no option in the Luxury Dealership and to see the map completely empty is not good, make option for the Luxury just little different from the PDM but similar like a PDM into the Luxury to make it more visible will be much better for the OP-FW

**Comment by twooot** [comment]
The point of the luxury dealership is to be a used car dealership. They buy up cars and resell them
