### ISSUE TITLE
Fix Pfister Neon

### ISSUE THREAD

**Issue by manaspatil007** [InZidiuZ/op-framework-issue-tracker#2577]
### Assurance

I have read the `README.md`

### Summary

1.When driving the vehicle pickup is to slow.
2.Vehicle has bad handling.
3.Keeps drifting on small turns.
* It use to be so good vehicle but since the new update or Nerf, No one wants to buy the car

### Reason

1.At the Price range of 140000 its a too expensive vehicle with no use.
2.Maybe a fix would help it to sell.
3.Limited sports vehicle have 4 seats

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker, us the assets one instead.
