### ISSUE TITLE
Improvements to SOL Bar

### ISSUE THREAD

**Issue by asifprotick10** [InZidiuZ/op-framework-issue-tracker#2578]
### Assurance

I have read the `README.md`

### Summary

As we know, SOL Bar is a bar in its name, but there is no bar option inside the bar, basically we have to buy drinks from outside and provide them which is a bit of a hassle as there should be a bar option in the SOL Bar like any other bar ( where we can buy drinks and food). Also, there is no clothing spot or business locker in the bar for the people who have the keys to the bar or those who manage the bar. I am suggesting some places where the bar option, clothing spot and business locker can be added. 

**Bar option-** 

![bar1](https://user-images.githubusercontent.com/97613672/202920663-acade0ed-99ac-4638-95d5-196193fc9c78.jpg)

**Suggestion for Bar option place-** 

![bar2](https://user-images.githubusercontent.com/97613672/202920658-6eac8096-6758-4b82-b449-8b4041b0eee2.jpg)
![bar3](https://user-images.githubusercontent.com/97613672/202920656-d78ce9c5-3017-428b-85f7-c70d98e44897.jpg)

**Suggestion for Clothing spot place-**

![clothing](https://user-images.githubusercontent.com/97613672/202920660-528ae4a5-4135-4189-8bb1-3e3e0d6bdb31.jpg)

**Business Locker-**

![locker](https://user-images.githubusercontent.com/97613672/202920661-a7bbfddf-b5b6-4d0f-b30c-a3aa624b04bf.jpg)

**Suggestion for Business Locker place-**

![locker2](https://user-images.githubusercontent.com/97613672/202920653-e1451d85-e7b1-4a6f-93cb-6ef839752052.jpg)

**Paleto SOL Bar-** 

![solbar](https://user-images.githubusercontent.com/97613672/202920616-f3948f42-c41e-4fd7-80bd-5cbae5212962.jpg)

### Reason

This would be good for the improvement of rp as people come to party and chill over at the bar. If the bar option is there, the bartender does not have to go to other places to manage the drinks and food which seems not suitable according to the bar rp. Thus including this bar option would help improve our rp and encourage everyone to do better rp. Therefore, I hope this improvement will be done as all of us are a part of the same community and want to help each other. Thank u.

**Comment by keepcodingstar** [comment]
It makes sense, we have done SOL bar tender RP for one season. we used to buy stuff and sell that there. This suggestion can make things ez. we can host events properly now.

**Comment by Afsun1** [comment]
Great Suggestion. I was also thinking that I will post this suggestion.
if developers can add those features. it will be very helpful, and in future we will able to see some good quality RP 
from SOL bar.

**Comment by DC0402** [comment]
We are doing the SOL bar RP this season, yeah it's really tough to buy things from outside and sell it, I also think it would be really helpful if this thing gets added. ❤️

**Comment by DaxterPancake** [comment]
I kinda feel like it's unfair to give the SOL Mechanic shop a bar also. No other buisness gets to have multiple buisnesses in one, they stick with their one thing.

**Comment by Afsun1** [comment]
> I kinda feel like it's unfair to give the SOL Mechanic shop a bar also. No other buisness gets to have multiple buisnesses in one, they stick with their one thing.

bro read properly.
we are not asking for mechanic shop bar.
we are requesting to add buying option in SOL bar.
there is an individual bar in paleto.

**Comment by DaxterPancake** [comment]
> > I kinda feel like it's unfair to give the SOL Mechanic shop a bar also. No other buisness gets to have multiple buisnesses in one, they stick with their one thing.
> 
> bro read properly. we are not asking for mechanic shop bar. we are requesting to add buying option in SOL bar. there is an individual bar in paleto.

Damn dude, no need to be a dick about it. It's an easy mistake to make when there are two buildings branded the same.

I actually think we planned on removing the SOL name from that bar so I think that'd be cool to be an actual functional bar!

**Comment by Afsun1** [comment]
> I kinda feel like it's unfair to give the SOL Mechanic shop a bar also. No other buisness gets to have multiple buisnesses in one, they stick with their one thing.

we are talking about this BAR
![202920616-f3948f42-c41e-4fd7-80bd-5cbae5212962](https://user-images.githubusercontent.com/97595288/202926611-05aa7f7c-612b-401c-849c-54461b44082d.png)

**Comment by Afsun1** [comment]
> > > I kinda feel like it's unfair to give the SOL Mechanic shop a bar also. No other buisness gets to have multiple buisnesses in one, they stick with their one thing.
> > 
> > 
> > bro read properly. we are not asking for mechanic shop bar. we are requesting to add buying option in SOL bar. there is an individual bar in paleto.
> 
> Damn dude, no need to be a dick about it. It's an easy mistake to make when there are two buildings branded the same.
> 
> I actually think we planned on removing the SOL name from that bar so I think that'd be cool to be an actual functional bar!

yeah bro then go for it.
we don't have any problem about BAR name.
we are just requesting for add some features on that BAR.

**Comment by MetaHatter** [comment]
I am personally not a fan of having any business in the framework exclusively branded with/tied to a gang or MC.  It forces people that want to run that type of business in that area to be a part of a group.  One that may not exist naturally in that region.

IMHO If this was to be done, the SOL branding should be removed.  Otherwise, I'd simply leave it as a clubhouse.

**Comment by keepcodingstar** [comment]
@DaxterPancake TLMC has yellowjack and repairshop both why not SOL.

**Comment by DaxterPancake** [comment]
> @DaxterPancake TLMC has yellowjack and repairshop both why not SOL. Moreover Paleto is lacking a bar in its proximity.

That is completely something to do with your subdivision, not development. The Yellow Jack is completely unbranded so therefore it is not given to a group. So this has nothing to do with what I said.

**Comment by CloudTheWolf** [comment]
> I am personally not a fan of having any business in the framework exclusively branded with/tied to a gang or MC. It forces people that want to run that type of business in that area to be a part of a group. One that may not exist naturally in that region.
> 
> IMHO If this was to be done, the SOL branding should be removed. Otherwise, I'd simply leave it as a clubhouse.

Agreed, this would be like adding a bar to the Lost club house.

At least in the international server I know this was going to be a steak house before food degradation killed that so don't know if any work was done to remove the SOL branding. 

But definitely feel like there should be a decoupling of gangs and businesses, which would allow anyone to they run the it.

**Comment by scufflord** [comment]
> > I am personally not a fan of having any business in the framework exclusively branded with/tied to a gang or MC. It forces people that want to run that type of business in that area to be a part of a group. One that may not exist naturally in that region.
> > IMHO If this was to be done, the SOL branding should be removed. Otherwise, I'd simply leave it as a clubhouse.
> 
> Agreed, this would be like adding a bar to the Lost club house.
> 
> At least in the international server I know this was going to be a steak house before food degradation killed that so don't know if any work was done to remove the SOL branding.
> 
> But definitely feel like there should be a decoupling of gangs and businesses, which would allow anyone to they run the it.

On international at least we still use this building for club business and meetings. We just don't use it an actual bar, just a place to hang out that isn't the mech shop. Helps split criminal activity from the legal business.

**Comment by twooot** [comment]
done
