### ISSUE TITLE
Bug report - Spawning in with an outfit i don't have saved

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-issue-tracker#258]
**Reporter:**
Soni#3614 - https://steamcommunity.com/id/OniSoni/

**Summary:**
I made a swim outfit for a party in game and since then i've deleted it. But i keep spawning with it even though i log out with a different outfit that is saved.

**Steps to Reproduce:**
Simply log in to the server and spawn in

**Expected Results:**
will have the wrong outfit

**Actual Results:**
have the wrong outfit

## Additional Information

**Screenshots:**
https://imgur.com/a/QZwBb44

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 319, Job Data: Transportation, Trucker, Amatuer

**Comment by InZidiuZ** [comment]
Hey,

This issue should now be resolved, the fix will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
