### ISSUE TITLE
Suggestion - Remember Duty State on Crash

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2581]
### Assurance

I have read the `README.md`

### Summary

- Remember PD/EMS duty state in the event of a crash.
- Reset duty to last state upon login if login is within 15 minutes and on the same character.
- If a new character is loaded, set off-duty.
- If an intentional "Exit", set off-duty.

### Reason

In the event of a client crash, PD and EMS are forced to go back to HQ to return to duty.  Enabling duty persistence will allow RP to continue with significantly reduced the negative impact to RP situations.

**Comment by CloudTheWolf** [comment]
This would be extremely helpful in cases where everyone in the chase head pops, allowing the chase to immediately pick up where it left off when people return.

**Comment by coalaura** [comment]
> Remember PD/EMS duty state in the event of a crash.

we cant reliably detect a crash

**Comment by ravicant** [comment]
> > Remember PD/EMS duty state in the event of a crash.
> 
> we cant reliably detect a crash

maybe we can allow players to use duty status command once when they connect so if people crash, they can go on duty immediately.

**Comment by MetaHatter** [comment]
Perhaps just eliminate the crash detection part of the suggestion?  It's not super necessary if there's a time check. 
Could reduce the time to limit issues if necessary.

Reset duty to last state upon login if login is within 5-10 minutes of a previous session and on the same character.

**Comment by CloudTheWolf** [comment]
> maybe we can allow players to use duty status command once when they connect so if people crash, they can go on duty immediately.

As much as I would like this I feel like it would be removed shortly after as someone is bound to abuse it.

> Perhaps just eliminate the crash detection part of the suggestion? It's not super necessary if there's a time check. Could reduce the time to limit issues if necessary.
> 
> Reset duty to last state upon login if login is within 5-10 minutes of a previous session and on the same character.

Or don't remove them from "On Duty" until they are removed from the recent disconnects?

**Comment by coalaura** [comment]
You'll now be set back on duty and back on radio 1/2 if you reconnect within 10 minutes after exiting the game
