### ISSUE TITLE
Suggestion - Improvements to Vehicle Key Sharing

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2583]
### Assurance

I have read the `README.md`

### Summary

When you give someone keys to you vehicle and they head pop or leave the city with them, no one has the keys anymore and you either have to Hotwire the vehicle or get a tow to the nearest garage.

My suggestion would be either;

1) When the person who has your keys leaves the city, the keys are automatically "Mailed" back to you, if you are in the city.
And/Or

2) Players have 2 sets of keys to the vehicle and when they use  `givekey` it gives the spare key to the person, allowing you to still drive if they head pop. (If combined with idea 1 this means if they person driving head pops again then they down lose both keys)

In the event the car is stored or impounded by a tow / pd all keys return to the owner. 

### Reason

This would be especially useful for PD and EMS as when they buddy up they may swap divers, so means the car does not need hotwiring.

This would also be beneficial in chases as if the driver is not the vehicle owner and they head-pop they can easily resume the chase when then return, as it is common for the vehicle owner to not driver if they are having headache issues. 

Additionally this could be useful for Luxury Autos or people looking to sell their car(s) as they would still have the master key. 

As well as that this could lead to more criminal interaction where criminals try and recover vehicles before they get impounded, which is something that we suggest does happen when interviewing for tow drivers.

This would also add some more realism since it is common for you to receive 2 sets of keys when buying a vehicle.

**Comment by coalaura** [comment]
> When the person who has your keys leaves the city, the keys are automatically "Mailed" back to you, if you are in the city.

Makes no sense to magically have your keys back after giving them to someone imo

> Players have 2 sets of keys to the vehicle and when they use givekey it gives the spare key to the person, allowing you to still drive if they head pop. (If combined with idea 1 this means if they person driving head pops again then they down lose both keys)

I am also not a big fan of this since we had abuse of the fact before that people would store their car to "generate" more keys
