### ISSUE TITLE
Suggestion - ATM hacking

### ISSUE THREAD

**Issue by Rohanx04** [InZidiuZ/op-framework-issue-tracker#2584]
### Assurance

I have read the `README.md`

### Summary

Basically small loots at the atm to get cash through methods of hacking and scripting using the tablet and the screw drivers to unlock and get the money out of it

### Reason

This would add a a great rp for both the police dept and the players who are playing. This would be a great task for both the police and the civilian.

**Comment by coalaura** [comment]
This seems just like a smash n grab for me, no real rp for either of the 2 sides

**Comment by coalaura** [comment]
yeah i dont really see how you would give cops or crims any rp with this. You cant really have a hostage when robbing an ATM and without one you'd just basically either get caught instantly or if its a smash n grab you would get money with 0 rp
