### ISSUE TITLE
Bug report - Car Repair and Mechanic 

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2585]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000010f604567

### Summary

When you repair a vehicle Materials don't get used.

### Steps to Reproduce

1. While Repairing the vehicle Press the Engine or Body repair key with the inventory opening key Eg :- E for engine and K for inventory.
2. When You see the Progress bar Just change the slots of all the materials while repairing
3. Your vehicle will be repaired 

### Expected Behavior

while repairing vehicle materials should get used.

### Actual Results

But With this bug materials don't get used.

### Screenshots/Videos

https://www.youtube.com/watch?v=fTzwimBZ9is

### Game Resolution

1920x1080

### Player Data

https://img.ravicant.in/u/t6zWzz7.png

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
this is fixed now
