### ISSUE TITLE
Suggestion - ADD IDENTITY CARD FOR ATTORNEY'S

### ISSUE THREAD

**Issue by Rohanx04** [InZidiuZ/op-framework-issue-tracker#2586]
### Assurance

I have read the `README.md`

### Summary

An ID card for the Attorney for their recognition while doing RP and also to produce at the PD for getting entry access and to meet their clients at the locker or cell. 

### Reason

The ID card can be shown to the client who has requested for name change/ hunting license or any private conversation with any new client. The ID card (CID) can be produced to verify the person as a legal person from the Department of justice. 
Just as the SASP gets it would be easy for an attorney to show his/ her identity to the citizens or to the PD or to produce at the court before the case begins for verification. This would be a lovely addition to RP for the members of the Department of Justice to go through with.

**Comment by DaxterPancake** [comment]
I believe this would be a great addition for DOJ. 

It would make identifiying actually Lawyers, Paralegals and Judges a lot easier and streamlined and easy.

**Comment by Lunabelle666** [comment]
I too think this would be fantastic. It would really help enhance RP and would help define DOJ more as an entity.

Currently we have several forms of ID that help the RP of different groups and also different licenses that show people have gone through certain steps to achieve the things necessary to acquire it. Fishing, pilot, hunting, as an example of the licenses and State Security, the many PD and EMS badges as an example of the ID's.

I truly think that this would be a fantastic incentive for people to partake in more DOJ RP, not just as DOJ but also as clients, as they would have confirmation that the person they are talking to is bar certified.

**Comment by ImArteria** [comment]
Can also vouch. This will save me time from looking at the roster that I have a hard time finding.
(On a real would be a good addition)

**Comment by coalaura** [comment]
WHY ARE YOU SCREAMING AT ME IN THE TITLE

**Comment by coalaura** [comment]
done ![peepee](https://i.coalaura.org/xAqiJUZa11.png)

**Comment by Rohanx04** [comment]
Where can we get the ID card. Like from the SASP or anywhere else ?

**Comment by coalaura** [comment]
in the DOJ office

**Comment by Rohanx04** [comment]
Is it available now ?

**Comment by CloudTheWolf** [comment]
Most Likely wont be in until tomorrow at the earliest, unless a new build has been pushed today
