### ISSUE TITLE
Suggestion - New Gun Run

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2588]
### Assurance

I have read the `README.md`

### Summary

New gun run update was good cz it fixed lot of bug but i think removing the hacking part was a good idea or not i mean i was going to put a new suggestion to change the hacking game but even the old one was not that bad so if possible maybe add that hacking game again maybe when u drill the container after that you have to hack if you fuck up then you will loss the gun.

### Reason

1. It was interesting
2. I knew so many people who didn't know the hacking part how to do the hack so they used to find people who can do it for them which was increasing RP. 
3. and if you fuck up then you will loss shit

**Comment by coalaura** [comment]
There was never a hacking part when drilling the container. Nothing about how you do the gun run changed? I dont think there should be a hacking part at the container aswell

**Comment by ravicant** [comment]
> There was never a hacking part when drilling the container. Nothing about how you do the gun run changed? I dont think there should be a hacking part at the container as well

No So Before it was when you start gun run first u have to do Bruteforce where u Select words one by one after that You have to use specific keys in a specific manner and then you used to get the small minigame that we get in the bank when we use chips where you have to choice 2 ALPHANUMERIC words which are not here now

> I dont think there should be a hacking part at the container as well

It was my suggestion that the minigame should be there that's it.
