### ISSUE TITLE
Trucker location

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#259]
**Reporter:**
Warpwnge

**Summary:**
I found another little finishing spot bug where a trailer shouldn't be. Had to ram it out of the way to finish my job.

**Steps to Reproduce:**
Do the job.

**Expected Results:**
Not to have to ram an obstacle out of the way to finish a job.

**Actual Results:**
Well ...

## Additional Information

**Screenshots:**
https://i.imgur.com/f8wPfc4.jpg

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Not really a bug, you could've labeled this as a suggestion, but I've moved the arrivals a bit to the left, which should make it easier to deliver when there's a truck in the way.

**InZidiuZ**
*OP-FW Developer*
