### ISSUE TITLE
Suggestion - Add 2 apartments on a current block

### ISSUE THREAD

**Issue by antonettedorado98** [InZidiuZ/op-framework-issue-tracker#2590]
### Assurance

I have read the `README.md`

### Summary

Hello! I was wondering if it was possible to add "keys" to two more houses in the Gentry Manor block. Currently there are 8 houses, 6 motel interiors and 2 beach houses. If we could get two more motel interiors added, it would be great. These two doors - attached- are currently unused and have no interiors, confirmed by Twentz who works as a realtor in the server. 

![image](https://user-images.githubusercontent.com/11245930/205472111-f2156d4a-f3be-4610-9c3d-3cec04455d9e.png)

### Reason

I think this change just gives a lot of leniency to the space that the Gentry Manor block provides. TKY has used that area as our home for nearly a year now and with more people joining, it would be great to have space for them call home in the server.

**Comment by coalaura** [comment]
done
