### ISSUE TITLE
Suggestion - DOJ PhoneLine

### ISSUE THREAD

**Issue by Rohanx04** [InZidiuZ/op-framework-issue-tracker#2591]
### Assurance

I have read the `README.md`

### Summary

DOJ PhoneLine (on the favourites section)

### Reason

Being able to easily contact a judge, lawyers or paralegal would not only be extremely benificial to police but also civilians and criminals alike. DOJ roleplay is always going to be needed in the city. Potentially in the future it could even remove the need for rp-lawyer-appointments for the international server and leave all the of the talking, scheduling and what not to phonecalls and texts in the city. It would be pretty be very helpful for the citizens as people nowedays know that the DOJ exists and how they work but they don’t know how to contact or where to meet so this would be the best in addition to all civilian and criminals and as well as the PD to communicate with the DOJ.

**Comment by DaxterPancake** [comment]
I agree that having a phone line for DOJ would be extremely helpful towards their roleplay.

Having a direct line to lawyers, judges, DA's etc would be substancially helpful to both cops and criminals alike and would help them find proper representation. Asking for Lawyers over twitter makes no sense.

**Comment by mrbuckels** [comment]
I think this would increase the chances that people looking for an attorney would actually find one. Trying to keep track of requests on Twitter is nearly impossible some days, and many posts are overlooked.

**Comment by coalaura** [comment]
closing since we now have a "Lawyer" hotline
