### ISSUE TITLE
Bug report - New dance emotes work while in vehicles when a keybind is pressed

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2592]
### Assurance

I have read the `README.md`

### Player Identification

STEAM_0:0:80501824

### Summary

I have two of the new dance emotes bound to my numapd 8, and numpad 9. Whenever im in my cop car and I press those buttons to use the radar and plate reader, the dances activate while in the seat.

### Steps to Reproduce

Have a new emote bound to your numpad, or possibly any other key such as "bind keyboard numpad 8 "e orangejustice"". Then when in a car press it.

### Expected Behavior

Only the radar keys assigned to the numpad should be used, and not any others on top of that.

### Actual Results

It clears the radar/plate, and also does the dance while in the vehicle

### Game Resolution

1920x1080

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
The keybinds are by FiveM, you'll have to change the keybinds or get rid of them since we have no control over your keybinds
