### ISSUE TITLE
Suggestion - Fire Extinguishers to put out grills/campfires

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2595]
### Assurance

I have read the `README.md`

### Summary

Enable the use of Fire extinguishers to put out campfires/grills and diffuse grill bombs at medium range.

optionally let them put out people and cars that are on fire as well.

### Reason

Currently there is no use for fire extinguishers and no counter for grill bombs once they are set.

This would address both.

**Comment by CloudTheWolf** [comment]
I think this would tie into https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2377

**Comment by coalaura** [comment]
fire extinguishers now extingushi fires properly
