### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by Gust123Battle** [InZidiuZ/op-framework-issue-tracker#2596]
### Assurance

I have read the `README.md`

### Player Identification

11000013b76dfe3

### Summary

So recently got an Nissan GTR R34 and it has some weird glitch whenever i store it and take out from garage it's livery and Number Plate.

### Steps to Reproduce

So
1. fix License Plate and Liveries Glitches

### Expected Behavior

The Liver should be same and should not be  and License Plate should not be different than original

### Actual Results

Everytime getting random Liveries and License Plate

### Screenshots/Videos

https://drive.google.com/file/d/1phTH_gJsLkiRw39iw9smgd_2julFwDkS/view?usp=share_link

### Game Resolution

1920x1080

### Player Data

![222](https://user-images.githubusercontent.com/95690117/206155909-b4f975ca-1ea7-4c21-92ac-2da8f3d18565.PNG)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
Ok so, in many cars the "Stock" livery will just select a random livery every time you pull out the car. I'm not sure how fixable that is but it would also be something for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
