### ISSUE TITLE
Suggestion - Lock mech computer mats to mech work

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2597]
### Assurance

I have read the `README.md`

### Summary

Make materials purchased from the mechanic computer only able to be used by mechanics for mechanic work.  

Create 5 new items

- Automotive Glass
- Automotive Rubber
- Automotive Scrap
- Automotive Aluminum
- Automotive Steel

Replace the current materials in the mech computer with these new items for the same relative prices.

Allow these items to be used, **in addition to the player sourced mats**, for the following processes

- Fixing a vehicle body
- Fixing a vehicle engine
- Fixing vehicle windows
- Creating vehicle wheels
- Creating vehicle doors
- Crafting Advanced Repair kits

Old materials acquired in the world will, still be usable for the repairs/crafting.

### Reason

Currently players are shortcutting the player economy and harvesting bulk materials from the bottomless NPC vendor for the crafting of thermite, attachments, etc.  

This has a significant negative impact to the player economy, the viability of activities like scuba/trucking/etc, and the speed that these crafted items are able to enter the world.

Removing the bottomless NPC vendor as a source for these materials will require players to gather them through more appropriate means out in the world or to buy them from players that have harvested them.  Increasing use of those activities and social interactions required to acquire those items.

**Comment by imdiavolo** [comment]
Makes sense to add this as honestly buying mats off the computer to make thermite or attachments makes the whole thing slightly less interactive than it should be. At least instead of asking a mechanic to buy mats for you off the computer, you can maybe get some mats off them that they got off someone else that was running scuba or chop.

**Comment by coalaura** [comment]
This seems a little weird in RP tho if i'm being completely honest. Meaning how come a piece of scrap cant be used to craft something just because of where you got it from?

**Comment by MetaHatter** [comment]
Agree there will be a little RP gymnastics but, considering metals and materials are naturally conducive to having varying quality levels for different uses it's not a huge RP stretch to think that these are just purpose-honed materials (i.e vulcanized rubber, aircraft grade aluminum, temptered glass, etc). 

IMHO it's a tiny RP leap for a huge benefit to the server economy.

**Comment by coalaura** [comment]
can now mark this as completed
