### ISSUE TITLE
Suggestion - Change Holstering/Undercover

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2598]
### Assurance

I have read the `README.md`

### Summary

Change how the holstering/undercover. Cops have the ability to do /undercover while off-duty to "mask" the fact that you are cops and pulling out of your side holster and not your waistband. When you clock on-duty your status of undercover stays even though you might forget you were undercover.

Couple solutions

1. Just make /undercover toggle to false when going on and off duty so that it never messes with on duty stuff.

2. Create a /holster command that people would be able to use to change the way they holster their weapon, and make /undercover only able to do when on duty. It would toggle to false on clock off/clock in.

### Reason

I understand why cops have the different holstering technique, and there is the roleplay that people are trained to pull out their weapons faster, etc. However if I am trained to do something, that doesn't mean I always have to do it. I should have a way to toggle it, which I know there currently is, but is causing issues with some possible SOP breaks. I think solution #1 would be the easiest to not have to worry about it.

**Comment by coalaura** [comment]
done
