### ISSUE TITLE
Arcade Bar Meal Packaging 

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2599]
### Assurance

I have read the `README.md`

### Summary

Just like Burger Shot and Bean Machine having the packaging system. It would be great if you can add it to Arcade Bar too.
Which can be added here 
https://img.kaieagle.me/u/QKRS4F7.png

### Reason

As lots of people come to buy food and as we also give out meals giving them packaged meal will be great! and I don't think it will conflict any restaurant thing as packaging things is provided by any shop.

**Comment by coalaura** [comment]
The arcade bar is like any other bar just that, a bar. Its not meant to be a restaurant and should therefore not be packaging meals or being used as the main food source. The pizza slices for example will eventually probably be removed too for the pizza place
