### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Triachnid** [InZidiuZ/op-framework-issue-tracker#260]
**Reporter:**
VaypeL0rd

**Summary:**
Paleto Bay Chopshop isn't working

**Steps to Reproduce:**
Pickup Hot Car with tow truck and try to chop in Paleto

**Expected Results:**
Car gets chopped

**Actual Results:**
Car doesn't get chopped

## Additional Information

**Screenshots:**
https://i.imgur.com/txji9mp.png

**Game Resolution:**
2560x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

There's no chop shop in Paleto Bay, so I suppose that's what the issue is.

**InZidiuZ**
*OP-FW Developer*

**Comment by Triachnid** [comment]
Sorry I meant Sandy Shores my bad

**Comment by InZidiuZ** [comment]
Hmm okay, but I am certain it's working, there's been countless of chopped vehicles since the last time it was changed, sure you're just not trying to chop a "non-hot vehicle"...?

**Comment by Triachnid** [comment]
Maybe I'm doing it wrong somehow?  I'm sure the vehicle was hot and backed into the area to chop.

**Comment by InZidiuZ** [comment]
"Hot" as in it came from the radio chatter?

**Comment by Triachnid** [comment]
Yes

**Comment by InZidiuZ** [comment]
Are you able to provide a video of this occurrence? Have never seen anything like that happen before.

**Comment by Triachnid** [comment]
I'll have to try and update tomorrow, just got a support ticket of my own
