### ISSUE TITLE
Suggestion - Nerf Phone/Radios Weight

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2601]
### Assurance

I have read the `README.md`

### Summary

Either move the weight (Currently is 10 pounds) of Phone/Radios (or anything else, if someone wants to add additional items into comments) to either 5 pounds or 1 pound

Personally on my cop character, I use roughly about 200-220 pounds out of our 250 pounds of inventory carrying mandatory items. On my crim character, it's about 185. To me personally, it doesn't really make sense to have a "10 pound" phone or "radio" as they would almost be weightless. It would just be something little

### Reason

Would be convenient and make more sense within RP
Pls we carry a lot of things
(Also this is a PD buff as well so that means you have to do it)

**Comment by scufflord** [comment]
Advanced Lockpicks being 10 pounds never made sense to me either, and is something both PD and crims carry so reducing the weight is ALSO a PD buff so you have to do it

**Comment by coalaura** [comment]
the point of them being heavy is that they are useful. We only added "pounds" cause people said it was weird without any unit. I dont want to decrease phone, radio or lockpick weights
