### ISSUE TITLE
/Furniture Rotating Props about the Y-Axis 

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2603]
### Assurance

I have read the `README.md`

### Summary

Currently the menu with /furniture only allows props to be rotated about the X-Axis. Multiple props (such as the Katana or Armor) would look a lot better being horizontal or other fixed positions. Just asking to perhaps make a bind to rotate it about the Y-Axis to continue to make unique designs. 

### Reason

Better House RP ofc
(On a real, just would make designing houses a bit more fun and add some more possibilities)

**Comment by coalaura** [comment]
You can now press F to switch the axis of rotation
![yes](https://i.coalaura.org/RIDuGijo76.png)

**Comment by ImArteria** [comment]
This is an epic, Victory Royale.
