### ISSUE TITLE
Suggestion - Enhance Tow Functionality 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2608]
### Assurance

I have read the `README.md`

### Summary

Implement a system to allow tow drivers tow impound and un-tow aircraft, boats and trailers. 

### Reason

Currently it is possible tow these kinds of vehicles, however you can't impound or un-tow them once they are on, and you have to store your vehicle to get rid of the attached vehicle, and the only way to get rid of them currently is for PD or Staff to "Local Tow" them.

**Comment by taylorwiffed** [comment]
This would be extra awesome because the helis if towable but non functional could be returned to the helipad for the deposit back by the renter!

**Comment by coalaura** [comment]
Most helis and planes should now fit onto a tow truck properly, in my dev server i was able to perfectly fine tow a big heli and then untow it again
