### ISSUE TITLE
Add an export button in companies tab

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2609]
### Assurance

I have read the `README.md`

### Summary

Add an export button in companies tab as shown in the [image](https://img.kaieagle.me/u/0d5ZiCH.png). The purpose of the button would be to export all the current block details like Status, Property Name, Type, Address, Renter, Weekly Income to be exported in a file which can be then open in a excel or google sheet.
An Example
![image](https://user-images.githubusercontent.com/29286961/209434900-a3f12d8f-7d0e-4af1-a2dc-a8e3bd0c696d.png)

### Reason

This would help people to easily manage the blocks and would ease the trouble of typing everything in a sheet yourself and also will help the company employee's to know the details of the tenants and the empty properties.

**Comment by coalaura** [comment]
I've added an export blocks and export properties button that will copy all information to your clipboard as a [CSV](https://en.wikipedia.org/wiki/Comma-separated_values)

![yes](https://i.shrt.day/goSAnufU01.png)
