### ISSUE TITLE
Duplicating stolen keys

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#261]
**Reporter:**
Warpwnge

**Summary:**
Me and a friend just pointed guns at a local at the same time and she gave us both the "1" key to the car, resulting in duplicated keys. In the screenshot, I'm not driving but I have the key matching the plate.

**Steps to Reproduce:**
2 or more people hold up a local driver at the same time.

**Expected Results:**
Only one key.

**Actual Results:**
Multiple keys.

## Additional Information

**Screenshots:**
https://i.imgur.com/yk3FIgy.png

**Game Resolution:**
1920x1080

**Player Data:**
https://i.imgur.com/OjKPIuA.png

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue should now be resolved.

**InZidiuZ**
*OP-FW Developer*
