### ISSUE TITLE
Gruppe 6 Job

### ISSUE THREAD

**Issue by JohnBaker456** [InZidiuZ/op-framework-issue-tracker#2610]
### Assurance

I have read the `README.md`

### Summary

Adding a job for the gruppe 6 corporate security and adding like a clock in system for it and probably a vehicle spawner at the HQ and also clothing spot and where would be the HQ? 
![20221224104431_1](https://user-images.githubusercontent.com/97943270/209448336-498d5d06-ad7d-42ce-8901-cad7722e387c.jpg)
i know it is closed i mean if we are adding a job we can always add interior to open it or make the HQ somewhere else i mean even if we dont have a HQ that's fine we would at least have a job that would make it more official and also give us paychecks and some sort of Badge for Gruppe 6 would be great

### Reason

A new job in the city and also a easy life to the roleplayers that are doing Gruppe 6 rp and ofc it would improve quality rp and then we would get more people and that would add something new in the city and also help us continue the Gruppe 6 RP.

**Comment by coalaura** [comment]
> clock in/out system

I don't see any reason or value of adding this

> Adding a job for it

Why exactly would it need a job? Could you elaborate on this part a bit more?

> Adding a badge

Hmmm, i am somewhat against adding more badges unless it is absolutely necessary

> Adding a vehicle spawner

What kind of vehicles and why? Could you elaborate on this part a bit more?

**Comment by JohnBaker456** [comment]
Job: So here's the thing i have been doing security rp in legacy servers since 2years now and i moved my rp to the main server like 2 or 3 months ago and all these 2 years i have been doing it just on my own so i can bring something new into the rp world and not having a job is a problem since first it's not fully official which really makes it hard for me and other roleplayers and why is that just because first we have to face problems like PD issues since we do not have a proper job PD doesn't understand it they need something official like a badge or job and no one takes Gruppe 6 seriously since we do not have a job and it's just based on some words or some google docs and i think i at least deserve to have some support for what i am doing and i dont mean to be selfish i know it's not a easy thing to add these things and why would you guys just do it for me and basically people want something official so they take this rp seriously and if someone just come and says then just leave this security rp that means i wasted my whole time trying to do something new and we would also get like proper paychecks and proper ranks and everything.

Clock In/Out System: So we have a proper system of being on duty as a security officer and being off duty. Not much to explain here but it's not really needed.

Badge: To show people that we are not impersonating as a Gruppe 6 employee and our job is related to the Law a lot and we could use badge in pd situations and civil situations and yeah.

Vehicle Spawner: So here's the thing i requested the developers to add Gruppe 6 vehicles and they contributed to it and they will be working on it i think so if we could just have a garage at the HQ or something so we can take our Gruppe 6 vehicles out from there and yeah.

Clothing Spot: So we can change our outfit when we come on duty and more quality rp we could just wear our uniform from the HQ instead of going to a clothing store.

Note: I think just getting a job would really help us by us i mean all the people that have or are doing security rp and other things even if they dont get added that wouldn't be a big deal since my main objective is to at least get a Gruppe 6 job.

**Comment by coalaura** [comment]
> first it's not fully official

Thats not the case. there being a job has nothing to do with it being official or not

> no one takes Gruppe 6 seriously since we do not have a job

People will not take you more seriously just because you have a job. Thats not a real argument for it

> i at least deserve to have some support for what i am doing

There are many other businesses that would by your standards be deserving of a custom job too

> So we have a proper system of being on duty as a security officer and being off duty

There is literally no difference between being on and off duty. So you basically want a system that does absolutely nothing but just show a text that says "on duty" or "off duty"?

> To show people that we are not impersonating as a Gruppe 6 employee and our job is related to the Law

Its a private security company, you are not related to the law. Don't try to do PDs job

> i requested the developers to add Gruppe 6 vehicles and they got assigned to it

If i recall correctly you opened a ticket and i told you no, we wont be adding vehicles

**Comment by JohnBaker456** [comment]
Okay i have nothing much to say but one thing i wanna mention is that i never in my life mentioned that we are trying to do PD's job :/
