### ISSUE TITLE
Recurring payment

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2613]
### Assurance

I have read the `README.md`

### Summary

Add a recurring payment method for house payment so people don't have to worry about it.
https://img.kaieagle.me/u/mbHCY8Z.png

### Reason

This will prevent people from losing houses (most new peps forget to pay the rent and they lose their houses.)

**Comment by MetaHatter** [comment]
This has been discussed before. The issue with this is that it will lock houses up when people decide to leave the server for extended periods without giving up the house.  Making them unable for use for an unpredictable and indeterminate time.

You can pre-pay rent if it's a concern.  I usually prepay 4 weeks in advance just to stay safe.

**Comment by coalaura** [comment]
closing for the reason metahatter mentioned
