### ISSUE TITLE
Suggestion - DOC Alert for New Inmates

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2616]
### Assurance

I have read the `README.md`

### Summary

When somebody gets jailed via the /jail command, DOC receives a dispatch alert. For example:

[Dispatch]: A new inmate has arrived.
[Dispatch]: Ben Asher has arrived for 35 months.

The level of detail is flexible but it would be a nice feature to have.

Only clocked-on DOC will receive the message.

### Reason

It would just be a nice feature to add to DOC so we are alerted when a new inmate is local transported.

**Comment by coalaura** [comment]
![yes](https://i.coalaura.org/cetawECE53.png)
done
