### ISSUE TITLE
Suggestion - Add Bagpacks

### ISSUE THREAD

**Issue by RiZiH** [InZidiuZ/op-framework-issue-tracker#2617]
### Assurance

I have read the `README.md`

### Summary

It would be great if bag packs are added to the server. It also makes sense to carry a bag pack when carrying things like lockpick, water bottle, food, etc 

### Reason

1. It will help players to carry more items as inventory gets full for keeping small things like knife, pet, phone etc . 

2. It will also help when players will sell weed, bag packs will help them to take more weeds with them.

3. It will help when minings as player can take more food, drills with them

**Comment by CloudTheWolf** [comment]
This has been asked many times, and to quote Laura the last time this was asked
> I added the ability for burgershot and bean machine to package any food into a paper bag for you. However I will not give people the ability to put anything into bags or backpacks

So I doubt this will be added at all.

**Comment by coalaura** [comment]
like cloud said

**Comment by RiZiH** [comment]
any reason for not giving as it would be very much helpful to carry a bagpack
