### ISSUE TITLE
Suggestion - Add Ability To Plant Weed Seed outside

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2618]
### Assurance

I have read the `README.md`

### Summary

I think weed Planting should be removed the way it is now like planting in the house and changing it to plant it outside on the ground.

### Reason

Why? bcz i think it will Give us more Rp exploring a new place more fun

**Comment by ImArteria** [comment]
This was discussed before. I personally really love this idea as "grow farms" outside can create a huge part of gang RP. I like

**Comment by ravicant** [comment]
I don't know if it's possible or not but I am Just gonna Put it here

To Grow the Best Quality CANNABIS You Need 3 Thing 
1. Enough Sun Light
2. Enough Water
3. And the Right Quantity of Fertilizer

So Right Now We Put Water & fertilizers 5 times I was thinking we can make a combination that will be different for every single player so if any player Has to get the good quality they have to work on their own strain. To Find their best strain they have to find the best combination.

Now The Main Question How are we Gonna does that?

So, There are three Types of Strain

1. Indica
2. Hybrid
3. Sativa

In these 3 Type You have Different Flavors and every flavor have a specific amount of THC/CBD/CBG
eg:- 
id:1
strain:"Acapulco Gold"
thc:"13.70%"
cbd:"0.12%"
cbg:"0.15%"
strainType:"Sativa"
climate:"Humid"
difficulty:"Medium"
fungalResistance:"High"
indoorYieldInGramsMax:500
outdoorYieldInGramsMax:600
floweringWeeksMin:10
floweringWeeksMax:12
heightInInchesMin:50
heightInInchesMax:70
goodEffects:"happy, uplifted, euphoric, creative"
sideEffects:"dry eyes, dry mouth, paranoia, anxiety"
imgThumb:"https://s3.us-west-004.backblazeb2.com/encurate/static/strain/Acapulco-gold.jpg"
imgAttribution:"Anargratos - Self-photographed, CC BY-SA 4.0"
imgAttributionLink:"https://commons.wikimedia.org/w/index.php?curid=8998618"
imgCreativeCommons:true

So we can Do our own calculation and give every flavor its own number of series so if anyone wants to develop that specific kind of Flavored Strain then everyone has to work on it 

So Now How we will decide the value for a specific plant to do that what we can do whenever we use fertilizer we will get a menu that will ask for input and only those seed will ask for input which don't have nay strain name on it 

So we should able to harvest seeds or buds we have to decide when plant is 100% we can also introduce the male female plants to make it more legit so when we will add any plant both seed and when we will harvest it we will get that strain weed seed For eg:-
If i have Acapulco Gold Strain Female Seed if i will combine with male or none strain seed i will get Acapulco Gold Strain Female Seed 3 or 4 from every plants then if i will plant Acapulco Gold Strain Female Seed Alone i will get Acapulco Gold Strain bud then i have to dry it and process it to pack it.

Cop - If cop find any plant they should able to harvest it at any percentage which will delete the plant 

Now Selling Part

There will be some specific strain that will be High Quality Depends on THC level and But Selling Time will be different for strain For eg:- Stavia makes People energetic that why people take it in the morning so if u sell this in the morning so u will get more money compared to night.

**Comment by TheCuppcake** [comment]
This weed rework would add a lot to the current weed RP and really enhance the ways people can create interactions

**Comment by coalaura** [comment]
done

**Comment by coalaura** [comment]
not the strains since those are GW exlusive but you can plant weed plants anywhere now (if the ground is made out of soil ofc)
