### ISSUE TITLE
Repossessions

### ISSUE THREAD

**Issue by DevotionRL** [InZidiuZ/op-framework-issue-tracker#262]
Name:
Devotion#5277

Summary:
with unpaid car finances having the option for higher up dealers to repossess the cars and sell them at cut prices to recoup money for them. for instance say a 40k car was financed and only 1 week was ever paid, repossess the vehicle and advertise for sale including the mods for 30k or around that. someone gets a good deal on the vehicle and the dealership gets the car paid off in other means.

Reason:
its realistic and gives players the chance to buy pre-modified cars from a trusted seller at reduced costs.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not happen. Planning on some other features to prevent ignoring finances in the future, though.

**InZidiuZ**
*OP-FW Developer*
