### ISSUE TITLE
Suggestion - Tool items for mechanics

### ISSUE THREAD

**Issue by BludBuket** [InZidiuZ/op-framework-issue-tracker#2621]
### Assurance

I have read the `README.md`

### Summary

Suggestion - wondering if we can add some more RP to the mechanic roles and add different tools (that are degradeable by how much they get used) for each type of repair that they "have" to have on them for repairs.. This would include a set of wrenches (make different sizes if needed), a cutting torch, socket set. air tool etc. Now they would get these froma travelling tool van (cube van) that a person (like myself) would be selling items (only 2 pieces of each item allowed at a time to stop inventory stacking and require a need for the RP more often. These tools would also be made from different pieces of mats like steel , aluminum. scrap that would be provided by other people.

### Reason

I think it would provide a more realistic approach to mechanics and how the real business operates and also open roles and another business.

**Comment by vol5** [comment]
This suggestion is superfluous...

**Comment by coalaura** [comment]
Yeah i will have to agree with the above comments. Being a mechanic is already stressful enough as it is currently. Trying to get materials, having to do a lot of repairs when the shop is full, etc.

**Comment by BludBuket** [comment]
Fair enough, just an idea. Appreciate most of the feedback

**Comment by vol5** [comment]
> Fair enough, just an idea. Appreciate most of the feedback

Also don't let me being a bit of a dickhead deter you from sending these in... This is your second one. Ideas like this are welcome and do not always succeed. The heart of your suggestion was there and everyone does appreciate that effort to better the place.
