### ISSUE TITLE
Suggestion - /number QOL

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2622]
### Assurance

I have read the `README.md`

### Summary

[Make the /number command last longer]

Its been a common thing where people are not fast enough retaining the information with /number. I feel it should be changed one of two ways.

> A: Have the display duration of /number last longer

> B: Have the /number be a toggle just like /description where you would have to /number a second time to remove it from display.

It may be worth taking a look into adding a delay for the use of /number and spamming /me because "my immersion"

### Reason

- Improves Efficiency
- QOL

**Comment by coalaura** [comment]
> It may be worth taking a look into adding a delay for the use of /number and spamming /me because "my immersion"

this was already done

**Comment by coalaura** [comment]
I dont think the longer /number is really that needed tbh
