### ISSUE TITLE
Suggestion - Armored Truck Heist

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2623]
### Assurance

I have read the `README.md`

### Summary

There has been a long standing player deman for a Heist that requires more then 2 people and with this frame for a new Truck robbery im hoping to be able to provide it. Anyone reading through the suggestion is welcome to point things out and/or add any additional things they think would fit

| Steps | Description |
| --- | --- |
| Step 1 | Locate the armored Truck |
| Step 2 | Kill the AI guarding the Truck and take it|
| Step 3 | Passenger starts the hacking process once they enter the vehicle (similar to the minigame while cooking meth)|
| Step 4 | 3rd person gets to a location to block the tracker signal of the stolen truck |
| Step 5 | Once the Hack has finished deliver the truck to the pinged location on the GPS |
| Step 6 | When arriving at the location Police gets a signal, meanwhile the robbers need to find tools in the immediate area to break open the back of the truck |

[Step 1] Locate the armored Truck

> In this step people have to locate the Truck of which Ive put 2 suggested vehicles here I think would fit the heist. 
[Model a](https://www.gtabase.com/grand-theft-auto-v/vehicles/mtl-brickade) - [Model b](https://www.gtabase.com/grand-theft-auto-v/vehicles/terrorbyte)
[This](https://cdn.discordapp.com/attachments/917478094015717387/1059260957790064690/image.png) would be a fitting location for the truck since it would make sense for a truck guarded by AI with rifles to be parked there.

[Step 2] Kill the AI guarding the Truck and take it

> People will have to shoot the AI guarding the truck and hotwire it in order to get it out of the building

[Step 3] Passenger starts the hacking process once they enter the vehicle 

> Once someone gets in the passenger seat and they have a Hacking laptop (crafted of 1cpu, 1 screen,2 wires, 1 pcb board, 2 aluminium, 1 battery pack) they are able to use it and start the hacking process. The process will work just like the minigame when making meth but with different questions. If the answer is correct it will return a 4 digit code which is needed to suppress the tracker. The total duration of the hack should be around 8-10min.

[Step 4] 3rd person gets to a location to block the tracker signal of the stolen truck

> When you enter the truck it will also show a blip of a satelite or smth similar which will be the location the 3rd person needs to go in order to suppress the tracker signal. Once the person arrives at the location they need to input the 4 digit code within 30 seconds of the other person acquiring the code or the tracker will be visible to the police.

[Step 5] Once the Hack has finished deliver the truck to the pinged location on the GPS

> Once the person in the passenger seat has finished the hack it will ping a location to which you need to deliver the truck. Once you arrive at the location it will give police a signal of a truck breaching a restricted area and police will make their way to the location of the truck.

[Step 6] When arriving at the location Police gets a signal, meanwhile the robbers need to find tools in the immediate area to break open the back of the truck

>Once the truck is at the location you will need to look around the area and find 3 items that are laying on the floor (just like in br or arena) to be able to open the back of the truck. These items should either be rotating or be unique to the heist which will give it another point of potential failure. Potential items could be Explosive charge, metal drill or any other thing capable of going through steel. Once the back door is opened you use the other 2 items you found to open 2 crates which have the Loot inside. The loot could either be straight up money or could be a item you can exchange for money like the jewellery from the J store. Due to the heist having a couple points of failure, 3 person requirement and more preparation I feel like 80k-120k would be a reasonable payout for this. The Heist should also only be able to get hit 2-3 times a day.

I also wanna say again that if anyone has any additions to this feel free to comment down below.

### Reason

- There has been a need for a new Heist for a long time

- This would be a new unique Heist for people to enjoy

- It requires more then 2 people and interaction between them

- It adds more roleplay value to the server

**Comment by coalaura** [comment]
This is exactly like the bank truck?????
