### ISSUE TITLE
Suggestion - small QOL improvements in Mt Zonah

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2624]
### Assurance

I have read the `README.md`

### Summary

**Introduction**
With EMS, every second counts. Everytime we respond to a call, shaving off an extra second can make a huge difference. 

While we aim to provide quality medical roleplay, we can't deny the fact that our response time is sometimes lackluster, which partly is an RP issue, but some parts are due to certain constraints that could potentially be lifted.

**Request 1** 
As we stay at the ready with our ambulances, we face a time-consuming issue when responding to calls up north with Angel One.
We need to use 2 elevators to reach the roof, unlike it was in pillbox with only 1. 

It would be greatly appreciated to have a direct elevator connection from the ground floor to the roof, enabling us to respond quicker. I understand it would not exactly line up logically, but this is why it's a suggestion :) thank you for considering

**Request 2**
To provide better medical RP, we use different outfits in different scenarios. As Angel One pilots, we have a separate uniform that we use in order to protect ourselves accordingly to the conditions that would be met in a fast moving and loud aircraft. However, running into the lockers at the ground floor to change outfits once more adds a lot to our response time.

https://imgur.com/a/UnaQShH
If feasible and doable, a locker prop with an outfit change spot anywhere in this room that connects the elevators with the rooftop would improve said response time, as we are heading this way already. Additionally, given that one of these elevators is also a softnap spot where people go to sleep, they have the option to choose what clothing they come back to the next day.

**Request 3**
The radius of the outfit change spot at Mt Zonah is too large at the moment. You are able to change your outfit outside in the hallway as well as in the breakroom without ever actually entering the lockers. If that radius could be reduced to prevent that, it would be greatly appreciated.

### Reason

I apologise because I named most reasons within the same section above already.

Mainly they are all small quality-of-life improvements that enable us to respond quicker to calls that are already further away.

Thank you for reading and your time!

**Comment by TheOneLizard** [comment]
I've just realised, alternatively to request 2, if Angel One itself becomes an outfit change spot similarly to ambulances, that would be a good solution too.

**Comment by coalaura** [comment]
> Request 1

which elevator at the ground floor do you guys use?

**Comment by TheOneLizard** [comment]
https://imgur.com/a/HvasSCT

this one. there are only 2 elevators on the ground floor. the one above is located right next to the ER and leads to the first floor where the pharmacy is located. 

I'm a little ashamed to say I only now realised that the elevators have never even lined up before 

The other elevator is on the far side of the lobby leading to the garage.

**Comment by CloudTheWolf** [comment]
would be nice to have that elevator go to both the second floor or the roof (Since there are 4 elevators up there)

**Comment by coalaura** [comment]
yeah i mean that was kinda my plan. My idea is to just connect it with the one on the second floor

**Comment by coalaura** [comment]
![yes](https://i.coalaura.org/cOJIZiFi20.png)

**Comment by coalaura** [comment]
also updated the elevators and reduced the clothing spot sizes
