### ISSUE TITLE
Suggestion - Test drive midnight cars

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2625]
### Assurance

I have read the `README.md`

### Summary

ok im a lil drunk so spelling mistakes r not my fault. ok so we actually need to be able to test drive midngith cars the same way we do in pdm

### Reason

Because cars get changed sometimes and i wanna know if a car i wanna buy is still good, sometimes i wanna buyu midnight cars but i need to trust what ppl sauy when they say "yo this car is good" without actually knowing myself. I would like to test drive midnight cars!

**Comment by coalaura** [comment]
very cool dani but there is already an issue open about this lmao #2376

**Comment by Daniini** [comment]
> very cool dani but there is already an issue open about this lmao #2376

sorry i m dumb
