### ISSUE TITLE
Suggestion - Phasing for racers

### ISSUE THREAD

**Issue by Psycho1952** [InZidiuZ/op-framework-issue-tracker#2628]
### Assurance

I have read the `README.md`

### Summary

Okay so im gonna do my best to try and explain this.

We have phasing with locals right now but its not 100% that it will phase because i have no clue how it works lol.

When we start a race we do /race start (name) (amount) (time) and here would be nice to have (phase or phasing) on/off.

Example: /race start holeinone 1$ 15 yes/no(for phasing) we can do phasing like for the whole race or only first 20-30 seconds so maybe add 1 more for space to write like /race start holeinone 1$ 15 yes/no(for phasing) (15 for time of the phasing ) but then if we have bigger race like 15+ cars then phasing trough the whole race.

It would work only for racers who are joined in the race. So if PD is invonvled they should still be able to pit us or ram us or what ever they want to do.It would work only on racers who are joined in the race.Remove the phasing from locals so that we can hit a local incase a PD is chasing us its unfair if we phase trough a local and pd dosent so it would be nice to remove it to balance it.

### Reason

As a racer my self i find it very frustraiting when we have 10+ people racing and we start a race on the first lap half of the racers get sent into the wall or water is very annoying.If the phasing would be added it would improve the racing quality.It would deff push more people into the racing scene because it would be more enjoyable for everyone.People do headache alot who are racing on some certain areas so it would help alot too with that so if person infront of me headaches without phasing i have to dodge him and it would send me flying to the other side if i hit him and that is no fun for me or the guy what headaches.

**Comment by coalaura** [comment]
The "phasing" with locals was added to help with "ghost locals" or npcs that will randomly spawn in front of you cause the game decided it would be a nice spawning place. If you mean add the ability to enable phasing through other racers then thats a clear no.

**Comment by Psycho1952** [comment]
Why is it a clear no?

**Comment by King2704** [comment]
I agree that with the recent ping increase for everyone from eu the first few corners in a race are impossible to drive without someone hitting you with their "bubble" so seeing smth like phasing atleast for the start of the race would be cool.

**Comment by coalaura** [comment]
Cause not only is it very unrealistic to be phasing through other people but the whole thing about you having to make sure you dont hit other people makes racing more difficult and more immersive. If i could just send it without having to care about locals and other players there would be way less fun in racing. With that i'm going to close the suggestion
