### ISSUE TITLE
Suggestion - Fistfights Rework

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2629]
### Assurance

I have read the `README.md`

### Summary

Summary: The primary focus here is to change fistfights from scenarios where you get in a (downed state) to scenarios where you go into an (unconscious state)

[unconscious state] - lasts for short time and player gets back up after duration is over
> Ragdoll for a random duration within a range of time (30s - 1min)
> Gets up off the ground with a restoration of 15% HP
> Give each punch a 1% chance for an instant unconscious state from one swing (adds variety of combat)

[Boxing Gloves: Revision] - Optional
> Increase the chance for ragdoll when punched with boxing gloves

### Reason

- Creates more content scenarios
- Makes the interaction more fun
- Smooths the gameplay experience
- There is no need for a hospital trip after every fistfight

**Comment by MetaHatter** [comment]
I have wanted this for... ever... would be a HUGE QOL/RP addition

Also, might be interesting to add some visual flair to it if you take X hits in a short period you vision gets blurry/dark, etc.

Could also apply for blunt force melee weapons but more severely.  Would be amazing to teach people non-lethal lessons that wouldn't require transport (or GSWs).

**Comment by vol5** [comment]
> add some visual flair to it if you take X hits in a short period you vision gets blurry/dark, etc.

Blurry/dark vision and leaving out the screen shake I like.

> Would be amazing to teach people non-lethal lessons that wouldn't require transport (or GSWs)

I very much like the idea of adding that non-lethal layer as you mention here.

**Comment by ImArteria** [comment]
Ngl if I have a danny run up to me and 1% insta down me without saying shit I might cry

**Comment by scufflord** [comment]
This would be a lot of fun for gang rp. Settle internal disputes with a fistfight, saves the hospital trip after.

**Comment by vol5** [comment]
@ImArteria LMAO it would be hilarious...

@scufflord That is exactly it. The goal there is to give players a better gameplay experience. Fun scenarios like the one you mentioned would be more common and really allows people to have more fun rp around fighting. There is nothing like beating the shit out of each other for 30mins straight.

**Comment by coalaura** [comment]
Something like this has been done (see #teasers)
