### ISSUE TITLE
Money Spent on Bike : Bug report

### ISSUE THREAD

**Issue by FighterXGamer** [InZidiuZ/op-framework-issue-tracker#263]
**Reporter:**
Discord: FighterXGamer YT  Steam Name: Fighter-xXx-

**Summary:**
I spent nearly 2500$ in upgrading my Bike but due to power Failure PC Restarted and when i Rejoin and take my Bike it was the old 1 and money was deducted.
**Steps to Reproduce:**
I am New Person I am short of money and somehow i managed money for upgrade.please Help.

**Expected Results:**
Compensation 

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
PC Restarted and i was unable to take screenshot.

**Game Resolution:**
2560x1440 

**Player Data:**
Character Id : 4720 Job Data : Government , Waste Collector , Employee

**Notes:**
No.

**Comment by InZidiuZ** [comment]
Hey,

Not really a bug-report, I'm not responsible for your computer, and no, there are no compensations for these sort of issues.

**InZidiuZ**
*OP-FW Developer*

**Comment by FighterXGamer** [comment]
![20190723235447_1](https://user-images.githubusercontent.com/53234118/61737316-9145f180-ada5-11e9-9144-caeeaca90ba7.jpg)

**Comment by FighterXGamer** [comment]
White Bike is Bugged... Bro thats my New Bike ..Please Help ..
