### ISSUE TITLE
Bug report -  Legacy Roleplay India House Robbery system.

### ISSUE THREAD

**Issue by bittu5074** [InZidiuZ/op-framework-issue-tracker#2631]
### Assurance

I have read the `README.md`

### Player Identification

STEAM_0:1:548825102

### Summary

When we are starting house robbery we are allowed to press the 'F' button to search the stuffs but as soon as we press the 'F' button and  we just switch our window from FiveM to any other window or when we are in the desktop then the bar which shows us that we are safe or unsure or busted just gets stuck over the place where we switched our window but the search is still going in the background thus making the players get an advantage over it. it means just press the f button and switch the window to get the stuff in background without increasing the bar which shows whether we are busted or something else.

### Steps to Reproduce

Either you guys can change the robbery system in house robberies or you all can add a function when the person changes the window just gets a warning and the search is stopped then and there or he/she gets busted.

### Expected Behavior

As you all may like brothers.

### Actual Results

The person is using this bug for their benefit.

### Game Resolution

1920 x 1080 p

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
I am unable to reproduce this, when i try it the bar still goes up for me
