### ISSUE TITLE
Suggestion - Add timer for scuba tanks

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2633]
### Assurance

I have read the `README.md`

### Summary

One main issue with scuba tanks is that you can never tell if you got 1min left or only 10 seconds. Adding a timer that tells you the exact time of air left inside the scuba tank would solve this issue and probably get a few more people to do scuba again.
This timer could either be included in the Smartwatch or just show up on the hud once you put the scuba gear on.

### Reason

- Prevents unnecessary death
- Scuba QOL

**Comment by TheOneLizard** [comment]
I do not favour this idea.

I am a regular scuba diver myself, and I feel adding a timer only prevents you from having a necessary potential hazard given how lucrative scuba can be.

A risk is always assessed not only by the hazard, but also by the exposure. You are more exposed to the potential hazard only if you choose to be so. Risking being downed only to gather 1 more material item is obviously not worth it. But that is for you to decide, you define the exposure of the risk.

Additionally, oxygen tanks IRL do not come with timers (unless I am not aware of this), they come along with barometers, pressure indicators. They will show you a similarly working indication on how low on oxygen your tank is.

If anything, maybe the current indicator could be replaced by such a barometer, for better immersion. But I truly think an exact timer will not be the solution here.

**Comment by CruzClementina** [comment]
I am also a regular scuba diver, and as someone who is also colorblind that O2 bar is next to impossible to actually monitor. So I do think that something along the lines of a timer added to the smart watches would be a good addition. (even if just from an accessibility standpoint)

With professional scuba diving gear, most divers do have what's called a "diving computer" which is essentially a watch that monitors, depth and dive time information and tracks the O2 levels, as well as a built-in compass and all sorts of other things.
![image](https://user-images.githubusercontent.com/106713037/211866204-054f24af-0d0a-44b1-a37a-af597a6f5200.png)
![image](https://user-images.githubusercontent.com/106713037/211866249-135646c8-70e7-4ee9-9566-cce41f4aeef8.png)
![image](https://user-images.githubusercontent.com/106713037/211866272-0b35e909-4683-4151-9950-39d8101bf701.png)

While I don't necessarily think we need a 15-minute egg timer attached to the smartwatch, I do think that adding some sort of function to the smartwatch for the purpose of scuba diving is a fun idea.

**Comment by navonody1** [comment]
I agree. The oxygen bar is hard to see at times, so some kind of gauge replacement would be a great QOL update for scuba.

**Comment by teddythedev** [comment]
Something with the smart watch would be a great idea. When I scuba dive IRL I have a Garmin that tells me how long I have been down, air time, etc so I can see that being useful.

**Comment by coalaura** [comment]
done (for the smartwatch)
