### ISSUE TITLE
Suggestion - Let us put downed people in cars

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2634]
### Assurance

I have read the `README.md`

### Summary

If people go down I want to be able to put them in a car without handcuffing them, also not needing to be a cop. 

### Reason

I think its a very basic things we need and I dont see a single reason why we shouldnt have it and its a good QOL thing. pls and thank u best devs!!

**Comment by King2704** [comment]
Yes, I 100% agree. It's super annoying when going anywhere in a helicopter and someone goes down you have to get a local car with a trunk or abuse the carry mechanic to get them in the helicopter on someone's shoulder. Same deal with Boats and cars that don't have a trunk or when you have multiple downed people.

**Comment by InZidiuZ** [comment]
Instead of /escort for everyone, we could just do it so you put people into seats with /carry

**Comment by Daniini** [comment]
> Instead of /escort for everyone, we could just do it so you put people into seats with /carry
yes pls that'd be so good

**Comment by scufflord** [comment]
Having InZidiuZ's idea with helicopters also would be awesome. Plenty of times I've wanted to take a helicopter somewhere to get some usage out of my license but thought "What if someone goes down while we're there?" If we could just carry someone up and put them in a seat it would save that massive headache and maybe get more helicopters in the sky.

**Comment by coalaura** [comment]
This has been done
