### ISSUE TITLE
Bug report - PewPew goes wrong location

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2635]
### Assurance

I have read the `README.md`

### Player Identification

https://steamcommunity.com/id/DaniWHT/

### Summary

I have seen and heard ppl complaining about bullets from certain guns going nowhere near where you are aiming, i also have a clip, the reason why im doing a bug report is because i refuse to believe this is intentional. I also dont have any solutions idk how coding works bro. All i got is a clip and ppl experiencing the same thing

### Steps to Reproduce

https://medal.tv/games/gta-v/clips/PYjEDc8We108D

### Expected Behavior

idk if its on purpose or not i dont got answers

### Actual Results

https://medal.tv/games/gta-v/clips/PYjEDc8We108D

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/PYjEDc8We108D

### Game Resolution

idk the persons resolution

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
I've personally never experienced anything this bad. Due to the recoil and bullet travel time you kinda have to lead your shots the further someone is away but i've never seen something that bad before

**Comment by coalaura** [comment]
Here is me shooting the R4-C on my local server https://www.youtube.com/watch?v=dUiISQoVR5w

**Comment by Daniini** [comment]
> Here is me shooting the R4-C on my local server https://www.youtube.com/watch?v=dUiISQoVR5w

yeah i have no idea i just seen ppl complain about special carbine mk2 and i saw this clip
i havent tried since any changes tho

**Comment by coalaura** [comment]
Okay i've tested it in the same location and it turns out if your gun is sticking through the sign there, the bullets will go all the way to the right, while if i move a little more to the right my bullets land where i aimed.

https://www.youtube.com/watch?v=MXk6GZa-4FE (you can see the tracers go all the way to the right)
