### ISSUE TITLE
Suggestion - Nerf Grandmas Price to Check in

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2636]
### Assurance

I have read the `README.md`

### Summary

Grandmas is a low utilized tool within the criminal enterprise. I believe last time I checked it was $2500 to use Grandmas. Suggesting a nerf to either $750 or $1000

Also have the option to "check in" the nearest downed person. 

### Reason

Encourage crims to use Grandmas after they've committed a crime as opposed to "holding down" a hospital

**Comment by DaxterPancake** [comment]
I don't agree with the price being that low, maybe 1.5k-2k at MOST. Instead I suggest allowing players to check people in so it's not awkward because they have to give the money to the person who is downed and then have them check themselves in.

**Comment by coalaura** [comment]
this was done
