### ISSUE TITLE
Suggestion - Gang Activities When No PD In City

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2637]
### Assurance

I have read the `README.md`

### Summary

- Regarding the gang activities when no police are in city (using coke runs as the example here)
Maybe there could be a system where you as a gang can still do the activity but say it could work in either way

< 3 PD online = 1 coke brick at 1=% health
>=3 PD online = 1 coke brick at full health

or even it could be something like 
< 3 PD online = 1/3 of a coke brick 
>=3 PD online = 1 coke brick 

same logic could apply to guns etc but the problem is as a gang trying to gather enough bricks to supply a bunch of other gangs it makes it very hard to do it say now when we are online and there aren't enough PD online

### Reason

I believe it would be good for the framework and mainly the city especially the EU players who want to play during our day and not wait until 4-5pm for PD to appear

**Comment by coalaura** [comment]
No i don't think degrading should be affected by cop numbers. The required amount of cops needed to be on duty is a config parameter that each subdivision can control or disable as they please

**Comment by AaronSmithCoding** [comment]
Sorry just to make it clearer so we are on the same page :)
So right now in the city there are enough PD so we can start a coke run and when completing we get a whole brick

But say in our usual gaming times around 2-5pm there arent any PD in city or not enough shall we say. so in this case the coke run is not available.

The idea was more of a way to allow the activity to run 24/7 but obviously if no cops are on we shouldn't get the whole brick. if it come back as a smaller amount or bad quality then it still allows us to have fun in the city doing these activities but we understand we shouldn't get the full amount

**Comment by coalaura** [comment]
Oh i see, interesting thought. I'll look into that

**Comment by coalaura** [comment]
done

**Comment by AaronSmithCoding** [comment]
Amazing look forward to whats new ic :)
