### ISSUE TITLE
Bug report - Bikes are doing some wild stuff

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2639]
### Assurance

I have read the `README.md`

### Player Identification

  steam:110000104053e90

### Summary

So as bikers, part of our RP is having all of our bikes parked outside of the clubhouse when we're around to be able to show presence and have a vehicle ready at a moments notice if the club needs a patch member to go do something. As of late since a lot of the garage re-work happened bikes have started behaving very strangely. Instead of staying upright, the slightest touch or bubble will send them flying or knocking them over entirely, and it isn't even synced up for all players in the area. They also at times will just start levitating 10+ feet up in the air, or merge themselves into a wall at random times. 

### Steps to Reproduce

Park a bike anywhere.

### Expected Behavior

Bike stands still

### Actual Results

bike goes brrr and does the mambo number 5

### Screenshots/Videos

https://cdn.discordapp.com/attachments/777722318159347712/1054547767139250176/image.png
https://cdn.discordapp.com/attachments/777722318159347712/1057397197014040586/2022-12-27_20-38-38.mp4
https://medal.tv/games/gta-v/clips/PmBNnF2aFMSFw/d1337YuX3hyN?invite=cr-MSxRcGUsNzU0MDQyOSw

### Game Resolution

1920x1080

### Player Data

https://cdn.discordapp.com/attachments/845947698628001862/1063264316427616277/image.png

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
This is pretty confusing and honestly i have no clue what could be causing this

**Comment by ImArteria** [comment]
Ngl seems like a skill issue

**Comment by coalaura** [comment]
I am fairly certain i know what causes this bug now. However there is ANOTHER fivem bug, so its either bikes doing weird stuff or all bikes coming out as sanchez's
