### ISSUE TITLE
New Modified Bike Bugged 

### ISSUE THREAD

**Issue by FighterXGamer** [InZidiuZ/op-framework-issue-tracker#264]
Reporter:
Discord: FighterXGamer YT Steam Name: Fighter-xXx-

Summary:
I spent nearly 2500$ in upgrading my Bike but due to power Failure PC Restarted and when i Rejoin and I cant take my new Bike  and money was deducted.
Steps to Reproduce:
I am New Person I am short of money and somehow i managed money for upgrade.please Help.

Expected Results:
Compensation

Actual Results:
What are the actual results?

Additional Information
Screenshots:
Pic Attached.

Game Resolution:
2560x1440

Player Data:
Character Id : 4720 Job Data : Government , Waste Collector , Employee

Notes:
No.
![20190723235447_1](https://user-images.githubusercontent.com/53234118/61737598-3234ac80-ada6-11e9-8dc6-473abbbd29e5.jpg)

**Comment by InZidiuZ** [comment]
This is a duplicate #263.
