### ISSUE TITLE
Bug report - Fix Spotlights

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2640]
### Assurance

I have read the `README.md`

### Player Identification

steam:1100001059035d3

### Summary

When using the spot light on PD cars, Helicopters, etc. It is only viewable client side and not server side.  I know a few months ago it used to work where someone would use it and everyone around could see it.  As of now it is only the person that turns on the light can see it.

### Steps to Reproduce

Turn on the spot light and have someone around. They wont see it.

### Expected Behavior

Turn on the spot light. Everyone will see it.

### Actual Results

you turn on the spot light and it is only viewed by yourself. 

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
