### ISSUE TITLE
Suggestion - Hunter's Delight and Hunting Balancing

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2643]
### Assurance

I have read the `README.md`

### Summary

Pistol bullets (50$ for 15 rounds) cost just a little less than sniper bullets (45$ for 10 rounds) which are used for the hunting rifle.

To this day, the hunting rifle has seen only little use with regular hunters. I believe the cost difference for its ammo compared to simple pistols only adds on top that an additional gun needs to be financed to fully immerse yourself in hunting RP.
There is what I believe just a little lack of external incentive to use the hunting rifle, and here are a few ideas to change the functionality of the hunting rifle and its importance in order to increase said incentive.

> **reduce low caliber pistol headshot damage to hunting prey, causing it to need 2 bullets in the head to kill prey. Higher calibers like the .50 may still deal 1-shot headshots, but as they are illegal to use, they already have an IC reason to be used less by regular hunters**

This would immediately increase the usage of hunting rifles, as pistols become less feasible and more costly to use for hunting. Alternatively to the above, a new ammo type could be introduced, specifically cathered to hunting and at a lower cost than pistol bullets.

> **introducing "Hunter's Delight", a new gun oil imported to the hunting store, which can only be used with the hunting rifle. 
> Each bottle is single-use. Using a bottle on a hunting rifle the first time will restore it's condition by 50%. Using a bottle on the same rifle a second time, will restore it by 25%. After that, the hunting rifle's condition can no longer be restored. (the values of the restoration can obviously be sth different, or maybe there could be a third cleaning as well, restoring the condition by 12.5%)**

Why make it more complicated than just increasing the durability of the hunting rifle (which could be an option too)? I think this would add a little flavor to hunting and just make it a little more extra. Additionally, once more this item would increase usage of the hunting rifle and with above suggestion put it up in the top spot for a gun to be used for hunting (which it really should be).

### Reason

I believe with most regular hunters just running around with pistols, hunting could use some healthy changes to promote a little bit of realism.

Ultimately, these changes above would cause the hunting rifle to be used almost exclusively when hunting, giving us that external incentive needed to enhance the RP.

**Comment by coalaura** [comment]
Buffed sniper ammo and the hunting rifle degradation. I don't want to add something that can fix guns. In addition to that, hunting has gotten some balancing changes which may make the hunting rifle more worth it again.
