### ISSUE TITLE
Suggestion - Highway PD QOL

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2644]
### Assurance

I have read the `README.md`

### Summary

plx add PD repair spot here kthx <3

![image](https://user-images.githubusercontent.com/4959366/213350251-5ada499d-429d-48d9-8d8e-0f53e692dc0b.png)

There is also a new ATM and a new water fountain in highway PD jsyk (not sure if you would need to add them to a list of some kind for them to work)

### Reason

Highway PD need some love man :(

**Comment by coalaura** [comment]
ATMs and water fountains are bound to the model. Repair spot is added
