### ISSUE TITLE
Suggestion - Cop Should Not get Mugged 

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#2645]
### Assurance

I have read the `README.md`

### Summary

I think when cop's take respawn they should not be mugged by NPC which will save lot of time for cops and money so they can respond on other situation after massive code red.

### Reason

I think it makes sense in rp when someone one take cops to hospital not possible Local EMS will not take care of there stuff

**Comment by King2704** [comment]
All it takes cops to restock is to go to the armory and buy new gear for <5k total and PD usually only has to airlift when there is low numbers around which means its very unlikely there is another situation.

**Comment by coalaura** [comment]
yeah cops have a big enough paycheck to easily stock back up, there is no need for something like this
