### ISSUE TITLE
Suggestion - Bear Traps Shootable

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2646]
### Assurance

I have read the `README.md`

### Summary

Bear Traps need to be shootable to disarm or destroy

### Reason

People are abusing Bear Traps in shootouts and putting them in doors where cops either have to have one person sacrifice, someone crawl to them and try to pick it up, or just sit back and do nothing.

**Comment by coalaura** [comment]
This has been done
