### ISSUE TITLE
Suggestion - Let us cook more than 1 patty at burgershot

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2647]
### Assurance

I have read the `README.md`

### Summary

I want to be able to cook 2-4 patties at once. PLS 4 NOT 2 IM JUST TRYNNA BE REASONABLE

### Reason

Okay so when you work burgershot a lot of the time u will get huge orders, like sometimes PD orders 20 or 40 meals and that shit takes soooo long. Then there is other people that want to get 1 or 2 meals which is bad because they'll have to wait 20-30 minutes for 1 meal because a cop or ems ordered before them. Imo stopping big orders would be stupid and it would be way better if there was just a faster way. It doesnt ruin any RP or make it too easy or anything like that Imo. Being able to only cook 1 patty restricts rp more arguably. So please 4 patties at a time I BEG U

**Comment by kaycorriher** [comment]
This is actually a very good suggestion if you could cook X number of items or put together X number of burgers at one time. 

I have had people walk out after saying its taken too long or I can just go to the arcade where they can just spawner it.

**Comment by coalaura** [comment]
You can now make up to 6 patties, 4 belgian fries and 2 raw fries at once
