### ISSUE TITLE
Mustang GT super from EDM Door Bug report - 

### ISSUE THREAD

**Issue by nightfoxlive** [InZidiuZ/op-framework-issue-tracker#2649]
### Assurance

I have read the `README.md`

### Player Identification

https://steamcommunity.com/id/nightfoxlive/

### Summary

The mustang GT, super seems to not have the closing doors animation, sometimes they close of their own accord and sometimes they stay open meaning the end up gettin taken off by someone driving past. The actual character never closes the doors. 

### Steps to Reproduce

Getting out of the Mustang GT, super from EDM, either side, the character doesnt have the door closing animation meaning the doors stay open half the time 

### Expected Behavior

Expected results would be that my character interacts with the door to open and close it as the result with all other doors, seems like the animation is missing or something 

### Actual Results

The character doesnt interact with the doors at all unless to open, after that the door closes and opens of its own accord and the character doesnt interact with the door to close it upon leaving the car 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/SQycq5vcr1Boj/d13373Ae9ueB?invite=cr-MSxJMHcsMTEwNzA3NjgxLA

### Game Resolution

1920x1080

### Player Data

![image](https://user-images.githubusercontent.com/96830741/213813730-ac0746a6-9f8c-45b7-8c00-c1ae5fe5d52a.png)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Asset github would be the correct one for this https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
