### ISSUE TITLE
Fix Big Bertha <3

### ISSUE THREAD

**Issue by brycepsd** [InZidiuZ/op-framework-issue-tracker#265]
**Reporter:**
Bryce.psd#8276

**Summary:**
I was doing trucking jobs one night and my phantom fell off the road and a rock hit the underneath of it. I thought I was fine till 3 minutes later when I ran out of fuel on the highway. Turns out Big Bertha was leaking all her fuel. I had to consistently get gas canisters and fuel up just to get to the mechanic were I fixed everything up thinking it would fix the leakage. It didn't stop the leakage and I have tried everything such as waiting for a reset, leaving it far way, leaving it in a garage, blowing it up, both repair kits. Nothing seems to work and I have spent over 7k just on trying to figure out how to fix this bug.

**Steps to Reproduce:**
Hit a rock on the underside

**Expected Results:**
Fuel Leakage that can be repaired

**Actual Results:**
Fuel leakage that can't be repaired

## Additional Information

**Screenshots:**
Here is a highlight from my stream. [Link](https://www.twitch.tv/videos/456934924)

**Game Resolution:**
1920x1080

**Player Data:**
Not in game currently

Would be nice to be compensated for constantly buying gas canisters and repair kits <3

**Comment by InZidiuZ** [comment]
Hey,

When taking a car out from the garage it will no longer apply the saved tank-health to the vehicle, as a quick workaround for this. In the future, I suppose the tank will be repairable.

**InZidiuZ**
*OP-FW Developer*
