### ISSUE TITLE
Suggestion - To do some improvements in Twitter app 

### ISSUE THREAD

**Issue by Kabir7700** [InZidiuZ/op-framework-issue-tracker#2650]
### Assurance

I have read the `README.md`

### Summary

While we use Twitter app and upload a picture in it , we can’t  add any additional information / Comment in the same tweet ! We need to do another tweet for it.
So my suggestion is : 
It would be good if we can add comments on the same tweet alongside the picture which we’re uploading.
Additionally it would be good if we can add thing : when we reply to any tweet , it can be counted as comment in respected tweet and not as new tweet. 

### Reason

1.)It seems more realistic. 
2.) sometimes people do spam tweet so once we upload the pic and try to do narrate / add comment regarding same tweet it goes way down and becomes unrealistic to do comment Over.

**Comment by coalaura** [comment]
This would be something for the new phone #2447
