### ISSUE TITLE
Suggestion - Ability to shoot 2 handers out the moonbeam etc....

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2652]
### Assurance

I have read the `README.md`

### Summary

So there are a couple of vehicles that you used to be able to shoot 2 handers out of (listed below) however due to the changes with not being able to shoot automatics out of vehicles, we have lost this ability. 

 - Moonbeam Custom
 - Minivan Custom
 - Gang Rumpo
 - Rumpo

### Reason

The vehicles that have the ability to shoot 2 handers out the car are not powerful vehicles, they have their nuances against the normal "war cars" and don't have the ability to evade easily, along with having a limited view capability when trying to shoot from these vehicles along with the fact that when you shoot a 2 hander out of these vehicles you are largely exposed making it easier for people chasing or being chased to shoot you. taking all this into consideration i feel that it balances itself out, especially as the majority of these vehicles only allow you to shoot from the side and not from the front or back, where as the vehicles that allow you to shoot out the back don't allow you to shoot out the front or the sides.

I feel this would provide good RP and a challenge to anyone that decides to try and use this method in a shootout

**Comment by vol5** [comment]
Given the recent changes, @hell-of-the-devil makes some very good points here. The places where they would even be a good use are very situational and have a massive disadvantages for the player when being used in the manor above.

Having it so you can shoot out of a select list of vehicles like these mentioned above would provide some nuance to the system and would be reasonable IMO.

This sure would provide a good challenge to the players who would then use it for RP and still not be overpowered.
