### ISSUE TITLE
Suggestion - O'Malley's Irish Pub Additions

### ISSUE THREAD

**Issue by tommylikesegg** [InZidiuZ/op-framework-issue-tracker#2653]
### Assurance

I have read the `README.md`

### Summary

Hi, I've just become the new owner of O'Malley's and was wondering if it would be possible to get some new things added to the pub. At the minute the only unique thing is Irish Coffee so it would be awesome if we would be able to sell some more Irish products as well as some proper food that you would find inside of a pub. We made a list of some Irish products you can typically find in an Irish Pub:
Guinness
Jameson
Full Irish Breakfast
Irish Stew
Peanuts
Tayto's
Lucozade

Also would it be possible for us to get some storage added to the pub so employees are able to store anything we will be selling inside of the pub instead of in personal vehicles or personal houses.

### Reason

The Irish pub is very unique in the sense it has a set theme and that theme is Ireland, with more Irish products it would give it a feel of authenticity and would offer more options to people around the city. The storage would be a huge improvement to the pub as it would mean individual bartenders won't have to always have full pockets and have to store items inside personal storage.

**Comment by coalaura** [comment]
done (a few of those items not all)
