### ISSUE TITLE
Suggestion - add momos at bean machine 

### ISSUE THREAD

**Issue by ASHUTOSH0107** [InZidiuZ/op-framework-issue-tracker#2654]
### Assurance

I have read the `README.md`

### Summary

Add some new item in bean machine like momos pasta because user get something new experience and everyone likes momos some people say momos and some said dumplings 

### Reason

I'm suggesting because in bean machine user get coffee cake muffins but when you add momos(dumplings) it is something new for user experience and in Indian server momos are favourite for peoples that's why I'm suggesting you to add momos in bean machine 🙂

**Comment by coalaura** [comment]
what tf is momos? Could you provide some examples as to what you're referring to

**Comment by coalaura** [comment]
Going to close this due to inactivity if there is no response

**Comment by ASHUTOSH0107** [comment]
Momos is like dumplings it's basically originated in china as a dumplings coating of white shell and filling of chicken veggies and panner it is serve with red hot sauce adding momos and pasta in coffee shop is just like innovation of something new combination which helps to boost the sales and player this very well

**Comment by coalaura** [comment]
I don't think bean machine should be selling savory foods

**Comment by ASHUTOSH0107** [comment]
Try once this is something new
