### ISSUE TITLE
Suggestion - Add Toolstore and Metal Selling to Cayo

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2655]
### Assurance

I have read the `README.md`

### Summary

Add a tool store to Cayo that costs more than the main island (import costs). 
Add a metal selling spot to Cayo (paying less than main island).

### Reason

If people want to soley live on Cayo or spend a lot of their time there, they are often forced to go back to the main island in order to make money. It would be nice if there was atleast one way to make money on Cayo without having to leave for those who wish to be there more often.

Purchasing tanks and bringing them to Cayo isn't too big of an issue but would be nice to be able to purchase them for a higher cost at a Cayo tool store.

Selling the materials you collected is a headache though, having a spot/s on Cayo to sell the materials you have gathered but at a lower cost than the main island would be a nice addition. That way if people want to go through the effort of bringing their items back to the main island via boat, plane, helicopter then they can do so for maximum profit but it also allows for people who want to live on Cayo to be able to make money without having to go back and forth.

**Comment by coalaura** [comment]
Where tho

**Comment by DaxterPancake** [comment]
I spent some time looking around Cayo Perico and found a few locations that I believe would work. If you aren't a fan of these then there are some buildings that we could just put the shop at the door of aswell.

All locations could be used as the tool store OR used as a selling spot. 

**1)** [Cayo Perico Hanger Tables](https://media.discordapp.net/attachments/850252046267711498/1069256572917792818/image.png?width=1069&height=566) - [Map Location](https://media.discordapp.net/attachments/850252046267711498/1069256829965705307/image.png?width=562&height=566) - I believe this could make sense as a SELLING spot (potentially for all the materials) as they would store them to export back to the main island.
**2)** [Generic Tool Table 1](https://media.discordapp.net/attachments/850252046267711498/1069253026717630574/image.png?width=934&height=566) - [Map Location](https://media.discordapp.net/attachments/850252046267711498/1069253121865416704/image.png?width=639&height=566) - Could easily be used as a selling spot or tool store as it's just a bunch of various junk and tools on the table.
**3)** [Generic Tool Table 2](https://media.discordapp.net/attachments/850252046267711498/1069253439470714880/image.png?width=1051&height=566) - [Map Location](https://media.discordapp.net/attachments/850252046267711498/1069253616986230794/image.png?width=503&height=566) - Same as previous.
**4)** [Generic Tool Table 3](https://media.discordapp.net/attachments/850252046267711498/1069255754068013156/image.png?width=1093&height=566) - [Map Location](https://media.discordapp.net/attachments/850252046267711498/1069255853649186977/image.png) - Same as previous.
**5)** [Boat Repair Hut](https://media.discordapp.net/attachments/850252046267711498/1069257092239732827/image.png?width=846&height=566) - [Map Location](https://media.discordapp.net/attachments/850252046267711498/1069257269600059433/image.png?width=494&height=566) - Could sell materials here, there is a boat next to the hut that is being repaired so could make sense he would buy materials.

Let me know if you need more ideas as there is a lot of just random doors to buildings we could just chuck it on aswell.

**Comment by ImArteria** [comment]
I like the boat selling spot. Maybe make the door the Toolstore and the boat a spot to sell metal

**Comment by coalaura** [comment]
done
![yes](https://i.coalaura.org/NOqufEso11.png)
