### ISSUE TITLE
Bug report - Disable Tackling While Ragdolled

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2656]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000010ad7281b

### Summary

While you are ragdolled (whether it's after being tackled or generic ragdoll) you can still Hold G to tackle, which is over used and abused

### Steps to Reproduce

- Player B gets Tackled by Player A
- Player A holds Shift + G
- Player B ragdolls

### Expected Behavior

Nothing, Player A is supposed to not be able to tackle

### Actual Results

Player B ragdolls while Player A is still on the ground

### Screenshots/Videos

N/A

### Game Resolution

1920x1080

### Player Data

https://i.imgur.com/vwXE5aR.png

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This has now been resolved.
