### ISSUE TITLE
Bug report - character not moving when selling mushrooms. The character get stuck and doesn't move while rest of the thing works. Tried restarting and selling again but facing the same issue again and again.

### ISSUE THREAD

**Issue by AlexMerssain** [InZidiuZ/op-framework-issue-tracker#2657]
### Assurance

I have read the `README.md`

### Player Identification

Steam ID: 76561199258125299

### Summary

While sellling mushrooms near vaspuchi canals, the character is getting stuck or not moving. While everything around him works normal and is moving. I tried restarting and tried to sell again but i am facing same issue. After the character is getting stuck the only option left to get out of the situation is leave the city Otherwise the character will be stuck for eternity.

### Steps to Reproduce

Having mushrooms 
Going to an npc to sell mushrooms in vaspuci canals
Clicking E to sell mushrooms.
And then character not moving a inch.

### Expected Behavior

The npc buys or runs away and the character can move after selling or offering mushrooms but none of these are happening 

### Actual Results

Character not moving an inch.

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
shrooms were temporarily disabled
