### ISSUE TITLE
Suggestion - yellow pages

### ISSUE THREAD

**Issue by itsdugzy** [InZidiuZ/op-framework-issue-tracker#2658]
### Assurance

I have read the `README.md`

### Summary

I think this city needs a place within the city (not just discord) where people can advertise. Since stuff are tough to add to the current phone, it doesn't have to be phone-based , until we get a new phone. You could just add /yellowpages that opens a tablet-like site, where people can advertise, or something similar. 

### Reason

We are defo missing in-city yellow pages, advertising on twitter is meh.

**Comment by coalaura** [comment]
duplicate #2192
