### ISSUE TITLE
Suggestion - Add Garage to Sandy Airfield Locked to Pilots Licences 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2659]
### Assurance

I have read the `README.md`

### Summary

Add a Garage For Pilots to park their personal vehicles in the Sandy Airfield Hanger.

### Reason

Currently this is the only Public landing area without a safe place to leave a vehicle.

LSIA has a Pilots garage, so would be a nice addition to the air field to encourage RP in the area

**Comment by coalaura** [comment]
done
