### ISSUE TITLE
Suggestion - PayPal/CashApp Phone Script

### ISSUE THREAD

**Issue by JamesThomas126** [InZidiuZ/op-framework-issue-tracker#2660]
### Assurance

I have read the `README.md`

### Summary

I believe this would be a good script to add the server because Insted of having to drive to an atm you could just use the atm in your phone basically.

### Reason

I would like this in the server so that when getting my car repaired paying back friends and it would save time and be more convenient for everyone in the server.

**Comment by coalaura** [comment]
Closing in favor of https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2447
