### ISSUE TITLE
Suggestion - Adding a parking garage to the Prison

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2661]
### Assurance

I have read the `README.md`

### Summary

My suggestion is adding either a public garage to the parking lot of Bolingbroke penitentiary or adding a Police Parking lot like MRPD for personal vehicles.  As of now the closest garage to the Prison is the one in Sandy which is a long distance to either park your vehicle and run to the prison or to leave it out front for it to either be stolen or disappear.

I would be leaning more towards a public parking garage for people that want to visit prisoners but either one would work.

### Reason

This way Correction Officers have a place to park while on duty and also a place for the public to park while visiting prisoners.

**Comment by coalaura** [comment]
done
