### ISSUE TITLE
Suggestion - add a check to /givecar

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#2662]
### Assurance

I have read the `README.md`

### Summary

When giving a car to a player have it display a confirmation message before finalizing the transfer. So you do /givecar and transfer it, but before it goes through a prompt pops up "Do you want to give your Alfa Romeo to Laura?" and then have them do /yes to confirm

### Reason

stops accidental transferring of cars to other players and will save staff the annoyance of having to try and get the car back

**Comment by coalaura** [comment]
instead i just added a distance check (you cant transfer it to someone further than 10 meters). Maybe we'll rewrite that command in the future but for now this should help :)
