### ISSUE TITLE
[game/inventory] - Increase Ground Inventory Weight Capacity

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2663]
### Assurance

I have read the `README.md`

### Summary

Summary: Increase Ground Inventory weight capacity

> Increase weight capacity from 500lb to 2000lb

The massive number of inventories when transporting significant quantities of items is overwhelming.

### Reason

- QOL
- Less overall server inventory piles
- Player convenience

**Comment by coalaura** [comment]
No
