### ISSUE TITLE
Suggestion - Place downed players in Helicopters

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2664]
### Assurance

I have read the `README.md`

### Summary

Summary: With the recent addition of putting players in cars when downed. This function being expanded to Heli would be awesome for civilians.

### Reason

- QOL
- Utility
- Solves issue of being stranded on a lonely island without being able to get off the island

**Comment by coalaura** [comment]
You should call EMS in that case not transport them yourself. Or use a boat to get them to shore. If its on cayo there is a hospital there. I don't think this is needed and it would take away from possible EMS roleplay.
