### ISSUE TITLE
Suggestion - Buying materials as a mechanic without withdrawing cash.

### ISSUE THREAD

**Issue by Manannn924** [InZidiuZ/op-framework-issue-tracker#2665]
### Assurance

I have read the `README.md`

### Summary

It should be possible to buy materials directly , without withdrawing money from ATM/Bank. Due to the smart watch we can buy other stuffs directly . I guess it should be added to mechanic as well.

### Reason

It's very frustrating to go and withdraw cash in between mechanic rp while repairing cars . It would be way easier if we can buy directly with the help of smart watch.

**Comment by superiorchicken007** [comment]
I know that most garages have ATM's. Instead of pulling out the cash you can just transfer it to them which only takes approx. 20 seconds.  However I do agree maybe in the future a /bill command would be nice for businesses that do deliveries.

**Comment by nightfoxlive** [comment]
think this is meant for the computer in mechanic shops, i agree this would make mechanic work a bit smoother

**Comment by coalaura** [comment]
done
