### ISSUE TITLE
Suggestion - Add a blip for SOL Cafe

### ISSUE THREAD

**Issue by Niveet** [InZidiuZ/op-framework-issue-tracker#2666]
### Assurance

I have read the `README.md`

### Summary

Add a basic blip on the map for SOL Cafe. Half of the time, people don't even know there are things up in paleto (Home of the SONS). Having a blip is a good way to attract more people up north. 

### Reason

We have been doing bartender RP for quite some time. We have been getting a lot of requests to update the location of SOL Cafe on the map. Since, all other bars have a blip. I think it's only fair if SOL gets one too.

**Comment by coalaura** [comment]
There was a blip for it but it was requested to be removed

**Comment by Niveet** [comment]
Huh. Can it be a subdivision thing? That can be toggled by managers.

**Comment by MetaHatter** [comment]
I am not a fan of any businesses having gang branding. I say if this is done the branding should be removed.

**Comment by Niveet** [comment]
The funny thing is, Sons of Legacy isn't a full-fledged gang. It's a motorcycle club with 1% outlaw members. Sons of Legacy has repair shop (with branding) which is visible on the map. Cafe isn't any different imo. Server already has lot of limitation on MC roleplay. Removing branding won't do any good

**Comment by coalaura** [comment]
with the branding being gone, i've readded the blip now
