### ISSUE TITLE
Food Suggestion for Japanese restaurant at vine wood!

### ISSUE THREAD

**Issue by Kabir7700** [InZidiuZ/op-framework-issue-tracker#2667]
### Assurance

I have read the `README.md`

### Summary

I’ve added this thing in previous suggestion (#2604 )as well but was included in functionality thing! So just adding a new suggestion for a specified thing ( food and drinks): 

Custom drinks like:

Shochu,
Tea,
Plum wine,
Soya Milk
•Sake
•Amazake
•Ramune

These could optionally include perks like being drunk effects on the screen or even fill up your thirst. :

Custom foods like multiple different

•sushi rolls (California roll, spicy tuna roll, dragon roll, rainbow roll, spider roll) and 

•the shrimp tempura roll),

• edamame,

• ramen.

•Omu-rice

•Onigiri

•Udon Noodles 

Additionally , that would be great if we can get additional perks in food ( For Ex. Armour increase , health increase , stress level decrease ) 

### Reason

This might enhance restaurant RP!

**Comment by coalaura** [comment]
Closing in favor of #2604
