### ISSUE TITLE
Suggestion - PD/Blood Evidence

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2668]
### Assurance

I have read the `README.md`

### Summary

So in short, the overall arching theme of this suggestion is that Blood spilled by any person with the "bleeding" status affect will be dropped on the ground to be collected by evidence. While this may sound "OP" at a first glance, there's a few counter measures to ensure it's not OP and can actually provide a LOT more roleplay.

Each player in the server is assigned a blood type and blood "code". The blood type is purely just for roleplay purposes and so it makes sense in RP. 
**Blood Types**
A+ 
A- 
B+
B-
AB+
AB-
O+
O-

For example, a blood code would be a random set of numbers and letters such as this. 
Zero Hernandez - Blood Type O+ - 1H34k9d9 (yada yada you get the point) for every single character. 

If a person has the bleeding status affect from getting shot, falling, whatever it is, they "leak" (a blood spot is on the ground) every 2-5 seconds. PD can pick this up with evidence bags. 

Something else I want to note is that could possibly only be analyzed by EMS and would reveal "Blood Type O+ - 1H34k9d9" but no name associated with it. In order to get a name, people would have to have that suspect in custody and reveal their bloodtype/blood code along with the fingerprint to prove it.

Once gathered, PD brings it to wherever to analyze the blood and get the above results.Things like /fingerprint or the /dna command would provide the suspect in custody's blood code? Up to you, but I would recommend having some command be able to get a suspect's blood type while in the cells. If they pick up blood on scene, they would have to go through the other process.

**OTHER NOTES**

PD/EMS or whoever processes the blood has access to blood slides now where they can compare. 
[https://i.imgur.com/s7cju1x.png](url)

They can use a PD evidence bag with blood and an empty glass slide to make one full glass slide. If you use two of them, you can process both of them to get a "match" or not a "match" samples of bloods to see who was involved in what.

New Item: **Bleach**
When you use the item, it deletes all blood samples in a small radius so criminals can counter the blood being gathered.

### Reason

- Even if you do have someone's blood from a crime scene and you know who it is, you can't prove anything in court so it wouldn't be OP (for international)
- Would create interactions for PD/EMS and make another possible way to gather evidence
- By gathering blood, FIB/PD can hold interrogations why someone's blood was on scene of a shootout/etc but not actually arrest them
- Makes sense to have this in roleplay

**Comment by coalaura** [comment]
My adjustments to it

- DNA Evidence instead of blood evidence
- Can be collected from scenes the same way you collect bullet casings
- Can only be analyzed by EMS
- /dnasample command to collect a DNA sample from someone (like /fingerprint)
- All produce a DNA evidence bag (which has to be analyzed)
- Once analyzed it will show not the blood type but some code for the DNA

**Comment by ImArteria** [comment]
> My adjustments to it
> 
>     * DNA Evidence instead of blood evidence
> 
>     * Can be collected from scenes the same way you collect bullet casings
> 
>     * Can only be analyzed by EMS
> 
>     * /dnasample command to collect a DNA sample from someone (like /fingerprint)
> 
>     * All produce a DNA evidence bag (which has to be analyzed)
> 
>     * Once analyzed it will show not the blood type but some code for the DNA
> 
>     * Has to be analyzed within like x hours otherwise it'll degrade and not produce a result

Thank you for no Essay tag

**Comment by coalaura** [comment]
I think having generic blood evidence would be too OP even with the restrictions mentioned. Since this issue was made, DNA evidence has been added for vehicles so i'm gonna consider this completed
