### ISSUE TITLE
Suggestion - Cinema Snack

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2669]
### Assurance

I have read the `README.md`

### Summary

To enhance RP around the cinema and promote people coming to movie showings, a special menu available only at the Cinema would increase attendance at movie events and provide snacks to make that experience unique. 

Have a non-job tied item spawner (therefore anyone that comes to the movie can just buy what they want and it cannot be accessed when the doors are not unlocked)

Menu: 
Popcorn
Slushies
Gummy Worms 

### Reason

This would promote movie theater attendance and provide good rp to movie goers. 

People could do like /me spills popcorn or drink then have to pick it up at the end of the movie with. /e janitor.

**Comment by antihero6713** [comment]
I do have popcorn made already and it has a animation for it. Just got to get it together

**Comment by coalaura** [comment]
gummy worms are fucking epic

**Comment by coalaura** [comment]
i've added some very overpriced snacks to the cinema, popcorn gonna be a soontm

![yum](https://i.shrt.day/leCetogo33.png)
