### ISSUE TITLE
Tank Oxygen Level

### ISSUE THREAD

**Issue by capsure** [InZidiuZ/op-framework-issue-tracker#267]
**Name:**
capsure#0737

**Summary:**
Currently when using the tank it just uses the current bar on the hud for the oxygen level left in the tank/lungs.  The issue is when/if you get back up for air that meter fills back up to 100% and doesn't drop back down to the oxygen level left in your tank. And as soon as the air runs out of your tank you start to drown.

**Reason:**
Creating either a separate meter on your hud when the tank is equipped or displaying the actual amount in your tank after going up to the surface would give you a more accurate reading of how much air you have left in your tank and help prevent drowning.

**Comment by InZidiuZ** [comment]
Hey.

The middle bar will now display how much air of the total amount is left.

**InZidiuZ**
*OP-FW Developer*
