### ISSUE TITLE
Suggestion - Make Alcohol Blendable

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2670]
### Assurance

I have read the `README.md`

### Summary

To improve Bar RP, allow the blenders purchasable at mega mall to allow both fruit and alcohol additions therefore bartenders can make mixed drinks.

### Reason

Would make party nights at bars more enjoyable to have like Tequila Tuesdays and have fruity margaritas.

**Comment by Niveet** [comment]
Big fan of this idea

**Comment by coalaura** [comment]
done
