### ISSUE TITLE
Suggestion - to give authority to the owners for giving jobs to new employees in RP

### ISSUE THREAD

**Issue by Kabir7700** [InZidiuZ/op-framework-issue-tracker#2672]
### Assurance

I have read the `README.md`

### Summary

As we know the current scenario where we have to request for roles in Discord where admins add accessibility to the requested member to certain job. 

=> But we can add a laptop kind of thing in a business / mechanic shop / PD / EMS where high command or the owner of business can directly give job after the interview. 

=> so that we no longer have to ask for accessibility from admins ( keys what we call ) and simultaneously owner can revoke the keys as well. 

=> Also promotion and demotions can be done in RP At the same time , the Same way! 

### Reason

It might improve the quality of the Rp 
And that’s more realistic 
We won’t have to wait for admins to give access , owner can directly do it!

**Comment by Niveet** [comment]
100% I think it's very easy to implement restrictions on owners to only maintain and manage their domain roles.

**Comment by coalaura** [comment]
No, this has high potential of abuse. Its much better having jobs be managed by staff only
