### ISSUE TITLE
Suggestion - Add a calculator in game

### ISSUE THREAD

**Issue by Niveet** [InZidiuZ/op-framework-issue-tracker#2673]
### Assurance

I have read the `README.md`

### Summary

There a lot of instances where calculator is needed. I mean, in this economy? Who doesn't. It would be a small QOL to get a calculator in game to calculate stuff without having to alt+tab.

### Reason

It wouldn't change the framework much, rather it will make calculations a tiny bit more efficient.

**Comment by superiorchicken007** [comment]
Could be a new app in the Tablet or the New Phone soonTM
