### ISSUE TITLE
Suggestion - Added a public garage to Harmony mechanic shop

### ISSUE THREAD

**Issue by Seagle0** [InZidiuZ/op-framework-issue-tracker#2674]
### Assurance

I have read the `README.md`

### Summary

Added a public garage to Harmony mechanic shop like other mechanic shops (Mosleys, burgershot).
there is a parking lot in front of the Harmony mechanic shop.
can you please add a public garage there
     thank you

### Reason

It helps my business

**Comment by CloudTheWolf** [comment]
Personally, as the owner in the international server, I don't really see the need for a garage there.
There is a public garage in Sandy, and unlike Mosley's, There aren't 10/15 EDM Cars always there and people always driving in the area.

**Comment by Seagle0** [comment]
but garage D is also available there.

**Comment by coalaura** [comment]
I don't see sufficient reason to add a garage in that area. However, i've added a garage to the motel that is a bit further away since the general area is missing a garage.

![mhm](https://i.shrt.day/VaPorIkA33.png)
![yes](https://i.shrt.day/quKAMuCI22.png)

**Comment by coalaura** [comment]
actually nvm i decided on here instead

![ok](https://i.shrt.day/hoyOROke65.png)

**Comment by Seagle0** [comment]
thank you
