### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by OberonSharma** [InZidiuZ/op-framework-issue-tracker#2675]
### Assurance

I have read the `README.md`

### Player Identification

STEAM_0:0:625692891

### Summary

I am not able to save more outfits in my outfit list. When I save, it shows successful but it doesn't show in the outfit list nor I can apply or delete that outfit. This bug isn't happening with everyone it is with my character only.

### Steps to Reproduce

Please look for some logs or coding because this glitch is happening only with me.

### Expected Behavior

I expect that you may find the bug and solve the solution so that we can do proper roleplay without any disturbances. 

### Actual Results

Results not received yet.

### Screenshots/Videos

[](https://youtube.com/live/2hYBZ7MFevM)

### Game Resolution

2K

### Server

India (c8s1.op-framework.com)

**Comment by superiorchicken007** [comment]
How many outfits do you have saved currently?

**Comment by InZidiuZ** [comment]
I migrated some MySQL queries to use an updated middleware & there were some typos here & there, this was one of them. It is fixed on all live servers as of now.
