### ISSUE TITLE
Suggestion - Local EMS calls improvement

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2676]
### Assurance

I have read the `README.md`

### Summary

Change the system from visual range to audible range for local ems calls when downed. There have been many instances where the peds walk by without calling when vision is obstructed. It may be more beneficial if it worked off of audio range since more calls would get sent overall.

> Change from line of sight to sphere bubble

With an equal range as the player shout toggle.

### Reason

- Increases EMS interaction
- More calls sent = more players get saved
- Less time on ground and more time interactions
- QOL

**Comment by joevapes3** [comment]
Yes this makes alot of sense, I feel the range of the ems calls is very very low, and it would only make sense that the locals hear you as far as you can yell. You can basically ocean dump people by throwing them 5ft off the road and while I 100% agree why the removal of using your phone while down was done, this would only seek to encourage more rp between civilians and EMS. There is plenty of times I've gone down from crashing into the gas pumps and locals that are without a doubt in shouting range ignore you and I miss out on really cool RP with EMS members. Only to wake up at the hospital and they're sitting there bored and seemingly would have enjoyed the rp contact as well.

**Comment by coalaura** [comment]
You would be decreasing the range that locals can find you

**Comment by coalaura** [comment]
Voice range
![yes](https://i.shrt.day/mUzUlEmU51.png)

Current local range
![yes](https://i.shrt.day/dOgaFUpE65.png)

The main idea of the local EMS calls was to make it so people who crash their car or bike or died similarly would be found. The intention was not to make body dumping harder.

**Comment by joevapes3** [comment]
Yah then I'd suggest expanding the range slightly, cause I am down in the same situation I mentioned above at this very moment and with 3 ems on duty and from what I can guess just outside of the range of that circle when I can see locals just walking by on the sidewalk next to me and cars as well on the main road. It would stand to reason that they can hear me if I was yelling but they don't and I'll take a flight to nancy (which mind you I don't care about losing items) but now will miss out from the RP with EMS sadly. 

Here is a pic below to show the example of where I am vs the locals range. 

https://i.imgur.com/2CATHEe.jpeg

**Comment by vol5** [comment]
> The main idea of the local EMS calls was to make it so people who crash their car or bike or died similarly would be found. The intention was not to make body dumping harder.

Wow, It seemed like it was smaller... An increase in range seems okay to me. As joe mentioned above, it would be helpful for these situations. I've had similar instances and it would relieve some of the frustration.

**Comment by joevapes3** [comment]
Here is the second example of how close they are but yet they don't call you in. So yah maybe increasing the radius would be super benefical to the server to allow more RP to occur. 

https://i.imgur.com/DnER4Gy.jpeg

**Comment by coalaura** [comment]
i increased the radius and improved the way we detect if a local can see you
