### ISSUE TITLE
Adding ATM inside Kissaki Sushi

### ISSUE THREAD

**Issue by Liltears33** [InZidiuZ/op-framework-issue-tracker#2677]
### Assurance

I have read the `README.md`

### Summary

I am the owner of Kissaki Sushi and I have had many customers I’ve served ask for an ATM inside my building. It would be a great way for customers to be able to draw out cash to buy food from my employees. Also give the employees the ability to deposit their pay before leaving the property. It would be a great QOL improvement for the city and my company.

### Reason

The only way for customers to get cash quick is to drive away or go across the street the the ATM placed randomly. This is a great hazard for customers and employees to go across a busy street, where they might get hit by a car just trying to get money or deposit money. This will keep my employees and customers safer if we can accommodate them by placing this ATM in the building. I was thinking right by the door in the waiting to be seated area would be an ideal location to place it.

**Comment by InZidiuZ** [comment]
Wrong issue tracker
