### ISSUE TITLE
Suggestion - Improve Trunk Realism

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2679]
### Assurance

I have read the `README.md`

### Summary

Simple 2-part suggestion:

- Make trunks have to be open to access the storage within.
- Make trunks only openable one of three ways 
   - in proximity by the keyholder
   - by someone in the driver's seat 
   - via lockpick

Obviously if the trunk lid is missing, it's free game.

### Reason

Trunk checking has always been weird. It's even more common now.  People have the ability to get in a trunk, grab stuff and leave with no indication or counter other than an animation.  It's completely nonsensical for RP.

This change would make trunks work more truly to real life and protect the contents slightly more than currently available.

The ability to open it via driver's seat and lockpick will still allow PD and others to access the contents if required.

It would have the added bonus of preventing people from shoving others into local trunks.

**Comment by coalaura** [comment]
IRL if someone doesn'T have their car locked i could walk up to it and trunk check them too if you wanna go for realism. Most cars trunks you can easily open from the outside as long as the car is unlocked. Idk if i am a big fan of this suggestion

**Comment by CloudTheWolf** [comment]
I think it's more common for the trunk of a vehicle to require a key, or have the trunk release triggered from the drivers seat  IRL as they are not usually tied to the central locking system (I think, not really dealt with cars IRL so dunno of that is still the case)

However if the vehicle is unlocked anyway there would be nothing stopping someone opening the trunk from the drivers seat anyway so this suggestion probably wouldn't do much and just add an extra step.

**Comment by scufflord** [comment]
> I think it's more common for the trunk of a vehicle to require a key, or have the trunk release triggered from the drivers seat IRL as they are not usually tied to the central locking system (I think, not really dealt with cars IRL so dunno of that is still the case)
> 
> However if the vehicle is unlocked anyway there would be nothing stopping someone opening the trunk from the drivers seat anyway so this suggestion probably wouldn't do much and just add an extra step.

No, there's ALWAYS a release on the outside of the trunk to be able to get into it, however some vehicles will come with an additional trunk release inside of the vehicle as an option. A key isn't always needed as well unless the vehicle is locked as it does tie into the central locking system.

**Comment by MetaHatter** [comment]
> I think it's more common for the trunk of a vehicle to require a key, or have the trunk release triggered from the drivers seat IRL as they are not usually tied to the central locking system (I think, not really dealt with cars IRL so dunno of that is still the case)
> 
> However if the vehicle is unlocked anyway there would be nothing stopping someone opening the trunk from the drivers seat anyway so this suggestion probably wouldn't do much and just add an extra step.

This would separate the trunk from the central locking system as modern trunks usually require you to open the trunk with the key or keyfob in your pocket (have keys), press a button on the fob (proximity w/keys), or pushing a button on the dash.  

People, largely, cannot just open a trunk on any car stopped at a light IRL.

**Comment by scufflord** [comment]
> > I think it's more common for the trunk of a vehicle to require a key, or have the trunk release triggered from the drivers seat IRL as they are not usually tied to the central locking system (I think, not really dealt with cars IRL so dunno of that is still the case)
> > However if the vehicle is unlocked anyway there would be nothing stopping someone opening the trunk from the drivers seat anyway so this suggestion probably wouldn't do much and just add an extra step.
> 
> This would separate the trunk from the central locking system as modern trunks usually require you to open the trunk with the key or keyfob in your pocket (have keys), press a button on the fob (proximity w/keys), or pushing a button on the dash.
> 
> People, largely, cannot just open a trunk on any car stopped at a light IRL. (At least not in the US)

That's not true at all. The only reason people can't just open a trunk on "any car stopped at a light" is BECAUSE they're tied into an automated locking system. As soon as most modern cars move over 5-10 mph they lock and remain locked until placed into park. THAT is the reason that they can't be accessed. However if the car is manually unlocked AFTER that, it remains like that. Or if the vehicle is parked and left unlocked you can walk up and access the trunk.

**Comment by MetaHatter** [comment]
> > > I think it's more common for the trunk of a vehicle to require a key, or have the trunk release triggered from the drivers seat IRL as they are not usually tied to the central locking system (I think, not really dealt with cars IRL so dunno of that is still the case)
> > > However if the vehicle is unlocked anyway there would be nothing stopping someone opening the trunk from the drivers seat anyway so this suggestion probably wouldn't do much and just add an extra step.
> > 
> > 
> > This would separate the trunk from the central locking system as modern trunks usually require you to open the trunk with the key or keyfob in your pocket (have keys), press a button on the fob (proximity w/keys), or pushing a button on the dash.
> > People, largely, cannot just open a trunk on any car stopped at a light IRL. (At least not in the US)
> 
> That's not true at all. The only reason people can't just open a trunk on "any car stopped at a light" is BECAUSE they're tied into an automated locking system. As soon as most modern cars move over 5-10 mph they lock and remain locked until placed into park. THAT is the reason that they can't be accessed. However if the car is manually unlocked AFTER that, it remains like that. Or if the vehicle is parked and left unlocked you can walk up and access the trunk.

I agree... I was trying to find a middle-ground mechanic that we could use in city that would give the same protection against trunk checking that you get IRL that did not require a full auto-lock that would be annoying in game play.

**Comment by coalaura** [comment]
I honestly don't think this really needs to be a thing. It just makes life more difficult for everyone and if you don't want someone to check ur trunk, just lock ur car.

To add another note to the realism part: My mom gave me a lift to the airport the other day. She stopped in front of my apartment with the engine running, i was able to perfectly fine walk up to the trunk, open it and put my bag in it without her needing to press any special buttons or come outside and open it with a key for me. Like mentioned, basically all modern cars lock automatically when you are driving bit when you are stationary in parked gear you can open the trunk perfectly fine.
