### ISSUE TITLE
Female Hairs, Clothing, Accessories

### ISSUE THREAD

**Issue by Handmaiid** [InZidiuZ/op-framework-issue-tracker#268]
**Name:**
**Who is suggesting this?**
Kate Denson - Handmaid#0666

**Summary:**
**Write a short summary of what your suggestion is about.**
I am suggesting more clothing options, hair, and accessories. Here are is an Imgur post with images and download links: https://imgur.com/a/kFOLq91

**Reason:**
**Why would your suggestion be a good addition to Legacy?**
Not only would this be something appreciated by the community, it would also help people express themselves creatively through outfits and simple things such as a hairstyle. Multi-player hair options are VERY limited along with clothing. I think this would be something very appreciated by the community.

**Comment by chromewick** [comment]
omg that long pig tail hair! and the white and black dress! we need more clothes and hairs for the girls. we all are looking the same. one girl felt like she had to change her hair so people would stop calling her by my name. there is like 2-3 hair styles that look good on the girls. the rest just look soo bad and non of the girls would wear them. we need more hairs and clothes for girls. so we can look different.

**Comment by InZidiuZ** [comment]
Hey,

Pleas post this in the asset-related GitHub issue tracker.

**InZidiuZ**
*OP-FW Developer*
