### ISSUE TITLE
Suggestion - Boosting

### ISSUE THREAD

**Issue by zackosaiyajin** [InZidiuZ/op-framework-issue-tracker#2682]
### Assurance

I have read the `README.md`

### Summary

It would be better if we get the contracts within the time period of 10-20 minutes but less increase in XP. But after reaching class A, getting contract can be made slow.

### Reason

Because now getting contracts are really hard. Joining on queue for more than 2-3 hours we are not getting the contracts. So doing this people might be able to have more fun in boosting and can experience a good rp.

**Comment by InZidiuZ** [comment]
The amount of contracts spawned is depending on the server's player count to not overload PD. These contracts are then distributed to the players in the boosting queue. Now that it's a new feature there's probably _a lot_ of people in queue. The amount of contracts that spawn will be tweaked though, but you can't expect every player to be able to be running boosting at the same time.
