### ISSUE TITLE
Bug report - Reskin Heritage Options Not Showing 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2683]
### Assurance

I have read the `README.md`

### Player Identification

steam:110000103fea0db

### Summary

When using the reskin function I found that I was not getting the options in the Heritage menu.

I was only able to get these options to show by changing from a freemode ped, saving and then switching back to a freemode ped.

Could not replicate on the test server, but this may be because my character was made on the old 

### Steps to Reproduce

Enter the reskin menu and go to Heritage 

### Expected Behavior

The Heritage screen loads and shows the options 

### Actual Results

The Heritage screen loads but no options are displayed 

### Screenshots/Videos

![screenshot](https://cdn.discordapp.com/attachments/686057091475046451/1078624516089057290/image.png)

### Game Resolution

1920x1080

### Player Data

![info](https://cdn.discordapp.com/attachments/1054807586194595931/1078710018754482296/FiveM_b2699_GTAProcess_8diXnE5svn.png)

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This should already be fixed.
