### ISSUE TITLE
Bug report - DOC Receiving PD Vehicle Tampering Calls

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2684]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000013fe41b53

### Summary

When clocked on as DOC, we are receiving the 'vehicle is being tampered with (class ABCD) etc' calls which only PD should get.
![image](https://user-images.githubusercontent.com/116962577/221275547-817af29c-ebba-42ba-aa56-a63007485651.png)

### Steps to Reproduce

Clock on as DOC.
Somebody starts tampering with a vehicle.

### Expected Behavior

PD to receive the dispatch call, DOC to not.

### Actual Results

PD and DOC receive the dispatch call.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/116962577/221275547-817af29c-ebba-42ba-aa56-a63007485651.png)

### Game Resolution

1920 x 1080

### Player Data

![image](https://user-images.githubusercontent.com/116962577/221275840-a83eb522-cf25-4c30-8752-b7ed67d78295.png)

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This has now been fixed.
