### ISSUE TITLE
Suggestion - PDM new Job Role

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2685]
### Assurance

I have read the `README.md`

### Summary

I'm the Manager of Premium Deluxe Motorsport in our subdivision, and it's one of the prestigious and desired job in our city. I have seen a lot of dedication among the PDM staff, and some of them have been here since the beginning. Also, new employees are joining occasionally, which creates a long list of positions in PDM.

Currently, this is the designation list of PDM in our subdivision:

1. PDM Boss 
2. Deputy PDM Boss
3. Assistant PDM Boss
4. Manager
5. Deputy Manager
6. Assistant Manager
7. Senior Executive
8. Executive Salesman
9. Senior Salesman
10. Salesman
11. Apprentice

But, we don't have enough in-game role for the designations. We only have **5 roles** and most of them are for the lower rank.

This is the current in-game role and payout list of PDM:

1. Boss - $112
2. Assistant Manager - $82
3. Senior Salesman - $56
4. Salesman - $44
5. Apprentice - $32

3 out of 5 roles is for the starting rank. And after that it's straight to the Assistant Manager, and then it's the Boss. Higher rank doesn't have an in-game role and need to carry a lower role for years.

For example, the Assistant PDM boss has to carry the Assistant Manager role, and a Senior Executive needs carry the Senior Salesman role.

So, I would suggest adding some new roles along with the existing ones and adding the payouts accordingly. I've seen **Executive Salesman**, **Manager**, and **Assistant PDM Boss** rank in other subdivisions, including us, and would love to see the role in the game.

Here is a suggested list of new rank with the existing one and their payouts for PDM:

1. Boss - $112
2. **Assistant Boss - $102**
3. **Manager - $96**
4. Assistant Manager - $82
5. **Executive Salesman - $64**
6. Senior Salesman - $56
7. Salesman - $44
8. Apprentice - $32

### Reason

Currently, PDM doesn't have the sufficient in-game roles compared to the designation list. We need to fill most of the rank with a lower in-game role.

Many people in PDM are carrying a much lower role for years. Also, there are some obvious roles like Manager or Assistant Boss in every business, but they are absent in the PDM role.

So, adding new roles will give meaning to their actual role. And we can finally give something to the higher rank people for their dedication.

**Comment by mdmostofa87** [comment]
I strongly agree with this. PDM really need more ranks and also paychecks need to increase cause PDM is not getting EDM commission like before. So paycheck need to be increase like before

**Comment by coalaura** [comment]
I'm down to add the Executive Salesman but it will decrease the paycheck
