### ISSUE TITLE
Suggestion - Add a blip for the Japanese sushi restaurant

### ISSUE THREAD

**Issue by Kabir7700** [InZidiuZ/op-framework-issue-tracker#2686]
### Assurance

I have read the `README.md`

### Summary

There’s a Japanese restaurant near VINEWOOD 
Which is not map notified. 
So new players in the city and  many of the old players are not aware where this restaurant is. 
So it would be great if we can have a map notification for the Japanese restaurant. 

### Reason

It’ll be good as it’ll be easy for people to identify where this restaurant is as many people are unaware where it really is.

**Comment by coalaura** [comment]
done
