### ISSUE TITLE
Bug report - Aircraft Landing Gear Visuals

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2687]
### Assurance

I have read the `README.md`

### Player Identification

steam:110000143222286

### Summary

Landing gears on aircraft are not pulling up for the passenger.

### Steps to Reproduce

Sit in passenger seat while flying and ask the pilot to pull the landing gear up.

### Expected Behavior

Landing gear goes up and is non-visible to the passenger

### Actual Results

Landing gear remains in static position.

### Screenshots/Videos

![heli](https://user-images.githubusercontent.com/85036959/221330582-9909e903-11de-42e9-ab45-c1d6a48d3c5b.png)
![plane](https://user-images.githubusercontent.com/85036959/221330584-0ed6aaf7-f8df-431a-9f9c-28f995361350.png)

### Game Resolution

1920 x 1080

### Player Data

![info](https://user-images.githubusercontent.com/85036959/221330671-5cc3c90a-4fdb-4b0c-8594-729003d9136f.png)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
I did some fixes, can you check if this is still an issue?

**Comment by coalaura** [comment]
actually nvm that fix didn't work. This is FiveM scuff therefore nothing we can currently fix
