### ISSUE TITLE
Suggestion - BurgerShot food.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#2688]
### Assurance

I have read the `README.md`

### Summary

I am the manager of BurgeShot 
since december the stress is not being reduced from burgershot food by which our sales has been decreased drastically
i agree that its not an RP that BS food relieves stress but other companies like bean machine/kissaki sushi relieves stress which makes our business run low. either all food companies should have this removed or can add it back in our food like before.

### Reason

if our food relieves stress like before it the sales/economy will be balanced like before. right now people consider going in other food places as there they can relieve stress.

**Comment by CloudTheWolf** [comment]
As far as I know most foods no longer relieve stress, so that Green wonderland & joints are the primary stress relievers.

**Comment by Nozimmm** [comment]
> As far as I know most foods no longer relieve stress, so that Green wonderland & joints are the primary stress relievers.

bean machine and kissaki sushi does, all the customer and employees keep on sayin me this.
