### ISSUE TITLE
Suggestion - Check ownership of car in LS Customs

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2689]
### Assurance

I have read the `README.md`

### Summary

When entering LS Customs with a car, have the system run through an ownership check, so only actual owners of the car are able to apply/remove upgrades in a LS Customs.

### Reason

At the moment, any troll/danny or maleficient individual could take your car and take away all upgrades for seemingly no reason, which is usually considered bad RP in my opinion. 

The above solution would eliminate that problem and would still allow Midnight to work, hopefully. Otherwise, maybe ownership could be given to Midnight briefly before returning the car.

Again, personally I see no RP purpose of downgrading someone's car, but this may be discussed here.

**Comment by coalaura** [comment]
No? The whole point of this was to make Midnight work better. Midnight would not be able to work and you wouldn't be able to upgrade your friends car or anything like that if only owners were able to. It happens very rarely that a troll/danny does this and if it happens we can very easily reset the vehicles upgrades to an earlier state and ban the person who did it.

This used to be like this and then i changed it not to be so i will not be changing it back
