### ISSUE TITLE
Weed packing

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#269]
**Reporter:**
Warpwnge

**Summary:**
- Trying to pack weed, thinking I have enough.
- Notice the red bar after 3 tries because I wasn't paying attention.
- Confused.
- Play "Hello Darkness" .. ok, enough meme.
- Looks into inventory, and sees that I DO have enough, however if there is a split stack of less than 4, the processing doesn't pick up the rest in the inventory.

**Steps to Reproduce:**
Split a stack of 1 oz weed into <4, try to process.

**Expected Results:**
Processing should look for 4 1oz in the whole inventory, not the 1st stack it sees.

**Actual Results:**
It looks for a stack and finds <4, does not compute.

## Additional Information

**Screenshots:**
https://i.imgur.com/QS06toO.jpg

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Fix: stack the weed before packaging. :)

**InZidiuZ**
*OP-FW Developer*
