### ISSUE TITLE
Suggestion - Inventory Icon Progress Bar 

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2690]
### Assurance

I have read the `README.md`

### Summary

Have a mini progress bar display when items inside the inventory are being used on top of the icon itself. Similar to how the main one is.

Eg. [Mini progress Icon](https://cdn.discordapp.com/attachments/1004605025324126328/1079597183386521703/icon_progress.png)

### Reason

Often times the FOV floats around or gets obstructed. Its beneficial to the player if the info is provided so as long as they are looking at the icon, they know if its being used or not.

- It looks nice
- Very convenient
- Useful

**Comment by coalaura** [comment]
Really don't think thats needed. There is a progress bar in your hud already, absolutely no need to add another one
![yep](https://i.shrt.day/TOQIWure71.png)
