### ISSUE TITLE
Suggestion - Paleto Bay Steakhouse Additions

### ISSUE THREAD

**Issue by LucasMadrazo** [InZidiuZ/op-framework-issue-tracker#2691]
### Assurance

I have read the `README.md`

### Summary

As the owner of the Steakhouse there is 1 major complaint from the customers and there is 1 major issue when coming to running the business.

1) All clients would love if there was an ATM inside or right outside the property (as it is inconvenient to have to run down the road to the nearest ATM)

2) As we sell Steak ; We have to keep a stock of raw meat and cooked meat for days we are open. We have sold up about 140 pieces of meat and it was difficult running out to the car to grab them ; It would be much more practical if there was storage inside the Kitchen area.

IF POSSIBLE;
I would love to add additional Brazilian Steaks and Brazilian Cocktails;
If this is not possible I understand but there are many different cuts of Brazilian Meat and different Brazilian Cocktails that take a huge role at all Brazilian Steakhouses.

If anything ; I would love more food options and drink options added ; as there are no cocktails in our menu and nothing other than Smores and Sandwiches ; we would love to be able to offer people more options

### Reason

The ATM would be really convenient for the players when they come to the Steakhouse on a regular or during events.
The Storage would be very helpful to make the Steakhouse have a good place to keep the Meat.
Also; I would love to roleplay actually creating drinks with other bottles in the Bar ; but since we only have Bottles available for purchase in our menu - we can't provide any sort of cocktails.

**Comment by xplrerin** [comment]
It would be nice to see a range of foods sold at the steakhouse that are decent. The people up north, Sandy upwards - only have access to grocery stores, all restaurants are in the city. We need access to food and drinks up north too that are slightly better than your grocery store tacos and sandwiches. This also might bring more traffic to the steakhouse for current and future owners.

**Comment by coalaura** [comment]
ATM would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

Closing issue as person who owned it no longer plays
