### ISSUE TITLE
Suggestion - add food and alcohol dealer to saleris  bar

### ISSUE THREAD

**Issue by badman780** [InZidiuZ/op-framework-issue-tracker#2692]
### Assurance

I have read the `README.md`

### Summary

So I'm about to buy it in the#1 city and I would like to be able to sell beer and food so I can make my money back from buying it there's already a private locker imported so I seen no reason why there would not be a food and alcohol dealer imported as well it would be great if this could be done thank you for your time reading this 

### Reason

Well it adds a bar/restaurant to the #1 city and why would I pay 60,000 for a building I can't sell food or drinks from

**Comment by coalaura** [comment]
it already has one
