### ISSUE TITLE
Bug report - Plate not Matching Car

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2693]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000013fe41b53

### Summary

When a plate is looked up, it does not always match the actual vehicle. The car is right, but the owner is wrong.
(yes, I am typing it in correctly & it is not fake plates)

### Steps to Reproduce

Check the plate of a vehicle. I'm not sure what conditions have to be met for it to not work.

### Expected Behavior

The plate matches the VIN and comes back to the right owner.

### Actual Results

Plate comes back to a random owner.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/116962577/221956807-fe0e348d-b909-4b43-ab5e-e5ad08dcf27a.png)

### Game Resolution

1920 x 1080

### Player Data

![image](https://user-images.githubusercontent.com/116962577/221956618-0f712de2-1f46-44f2-8804-8b1d93ea00a1.png)

### Server

International (c3s1.op-framework.com)

**Comment by enutpeanut** [comment]
> is this still an issue after the most recent restart?

Yes, the model is correct but ownership is still wrong.

**Comment by coalaura** [comment]
fixed
