### ISSUE TITLE
Bug report - Collecting too many casings crashes game

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2694]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000010ad7281b

### Summary

Whenever picking up a LOT of casings, your game will crash. Seems to be when the timer is 5+ plus

### Steps to Reproduce

Have an uber-amount of casings on scene, try to collect them. Your game will crash when the timer is up and you lose the casings

### Expected Behavior

You gain the casings after waiting the alotted time

### Actual Results

You crash

### Screenshots/Videos

https://i.imgur.com/81eDLeo.jpeg
Link to roughly 15 second video with me crashing and F8 pulling up. 
https://cdn.discordapp.com/attachments/770530237913497600/1080298755615633518/Cfx.re_0xe7ab5615_2023.02.28_-_20.14.52.12.DVR_Trim.mp4

### Game Resolution

1920x1080

### Player Data

https://i.imgur.com/3wcuMxx.png
https://i.imgur.com/81eDLeo.jpeg

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
skill issue

**Comment by coalaura** [comment]
should be fixed now
