### ISSUE TITLE
Suggestion - Add Window Breaking Item

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2696]
### Assurance

I have read the `README.md`

### Summary

Add an item that would allow people to break the window of a stationary vehicle in order to remove a passenger.

Item, when used in melee proximity to a window, would progress bar for a few seconds and then break that window.

It can be modeled after this:
https://www.amazon.com/Window-Emergency-Breaker-Crushing-Adjustable/dp/B005JGL4XM

It could be restricted to PD if necessary, but I think, with the right timer, it wouldn't be OP.

### Reason

Currently Tasers, as the only way to forcibly remove someone from a car, do not go through windows. Shooting out glass in order to use them is an unnecessary escalation.  

This item would provide a dev adjustable option to remove the glass that would be more realistic for RP than "throw a baseball at it"

**Comment by SammySandbags** [comment]
Could be hand for EMS as well @MetaHatter for people downed in locked vehicles would allow more RP rather than just Sus out and kinda breaking RP.

**Comment by coalaura** [comment]
done ![mhm](https://i.shrt.day/yorUyeMU12.png)
