### ISSUE TITLE
Suggestion - Test Drive at Tuner Shop

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2698]
### Assurance

I have read the `README.md`

### Summary

Tuner Shops do not have test drive feature. It would be better if one can test the vehicle before buying.

### Reason

Everyone asks for it in game.

**Comment by obrew8** [comment]
think this should be a thing for edm aswell, may also encourage donations as people will see if they enjoy the cars

**Comment by coalaura** [comment]
Already suggested here #2376

@obrew8 EDM will not be getting testdrives
