### ISSUE TITLE
Suggestion - Banana Peel

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2699]
### Assurance

I have read the `README.md`

### Summary

Add the Banana Peel as a new item to the game. You would get that item every time you eat a Banana. Once you got the Banana Peel you can throw it just like a Baseball and it will land on the ground causing people to trip over it just like when people walk over ice.  If possible make it affect go-karts too.

### Reason

Unique item that would create a lot of rp scenarios

**Comment by zhefo** [comment]
i love this idea

**Comment by coalaura** [comment]
lmao i like this

**Comment by coalaura** [comment]
While i am not making them throwable, i've implemented this now.

**Comment by vol5** [comment]
Mario cart type beat LMAO
