### ISSUE TITLE
Oxy guy can buy when dead

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#270]
**Reporter:**
Warpwnge

**Summary:**
- Was informed about this.
- Decided to test it. Shot my client.
- Successfully sold oxy to his bleeding corpse for $450+.

**Steps to Reproduce:**
Shoot the oxy client and sell.

**Expected Results:**
Not this.

**Actual Results:**
This.

## Additional Information

**Screenshots:**
https://i.imgur.com/OI1CLsJ.jpg

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
I do feel that "Short summary", "Expected results", and "Actual results" are a bit redundant, though that could just be me.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
