### ISSUE TITLE
Suggestion - Tie Food Satiation to Degradation

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2700]
### Assurance

I have read the `README.md`

### Summary

Make food degradation a multiplier for satiety. 

i.e. 
If food is 10% degraded, full hunger 90% of normal
If food is 50% degraded, fill hunger up half as much as normal
If food is 80% degraded, fill hunger up by 20% of normal.

### Reason

This is to improve several areas:

- Increase the value of freshly made food at player-run locations
- Decrease, and add RNG to, the value of food found in trash
- Discourage people from stockpiling for the entire day
- Encouraging people to cross paths when they travel to get more food more often.
- Add a layer of realism to food.  (if it's left out, it isn't as desirable)

**Comment by coalaura** [comment]
Food already degrades very very fast, other foods degrade slower. This is all balanced with the fact they give you full effect still so i don't think this is really needed tbh and would just add a lot of not neccessary complexity
