### ISSUE TITLE
Bug report - EMS Doctor Duty

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/op-framework-issue-tracker#2701]
### Assurance

I have read the `README.md`

### Player Identification

Sleighwhite

### Summary

I'm pretty sure this is a known issue, but couldn't find an open ticket for it, so adding it here again just in case. If I missed the existing ticket, please disregard. 

Essentially there is a major bug with the way that "Doctor Duty" works for EMS at the minute. When an EMS employee goes on "Doctor Duty" patients can come in to be treated by the doctor, but their injuries are not healed. 

Additionally, this bug was found prior to local EMS calls coming in as well as the "Active EMS" counter on phones, so I don't know what implications "Doctor Duty" would have to those features as far as being considered "on duty." 

### Steps to Reproduce

EMS employee should clock in to "Doctor Duty" and an injured individual should check in for treatment. The EMS employee should then attempt to treat the patient.

### Expected Behavior

All injuries should be treated

### Actual Results

No injuries are treated

### Screenshots/Videos

I don't have any at the moment as I've resigned from EMS for a while due to personal matters.

### Game Resolution

N/A

### Player Data

N/A

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Its not a known issue, since it was never reported. It was reported once and i pushed a fix for it and then nobody said something ever again so i figured it must have been fixed

**Comment by coalaura** [comment]
I just tested this in my dev server with someone else, it doesn't matter if i used /checkin or not i was able to perfectly fine fix their injuries without any problem, are you sure this is still an issue?

**Comment by coalaura** [comment]
I also fixed the "bug" that people were getting charged the full price when checked in using /checkin. Doctor duty has not changed in forever and it has always been working, except for 1-2 days when /checkin was introcuded. I tested it with someone else, its working perfectly fine.

Closing this issue
