### ISSUE TITLE
Suggestion - Move Harmony Outside Bay "Review Vehicle" Marker

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2703]
### Assurance

I have read the `README.md`

### Summary

The review vehicle marker is at the back of the bay, instead of the front.

Can this be moved to the other side of the bay (Where the bike is in the pic below)
![image](https://user-images.githubusercontent.com/7809366/223863469-fbe602e1-87b7-43ab-8549-5222ccc92fa4.png)

### Reason

People are dumb, and never understand pull up to the white line, so having the mechanic be able to stand there and then be able to review would make life easier.

**Comment by coalaura** [comment]
done
