### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Shivi2808** [InZidiuZ/op-framework-issue-tracker#2704]
### Assurance

I have read the `README.md`

### Summary

Pickup trucks (eg. Caracara) should have more storage in their trunk because realistically they have more storage than a rumpo van if you look at it !!

### Reason

The vans are used for the sole purpose of storing more stuff in trunk and they are not too good looking but we have variety of trucks if they have same or more storage because realistically they should then we wont need to spend unnecessary money on vans that we dont like

**Comment by coalaura** [comment]
I don't think Vans should have more storage
