### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#2705]
### Assurance

I have read the `README.md`

### Player Identification

steam:1100001123364ab

### Summary

With the 'thermal goggles' being added, their use is very inconsistent and has a very real possibility to be abused. In the test server, the thermals were tested with different interiors and distances which show inconsistencies. It seems that the thickness and how many walls between people determine who can see who, but even one wall only allows you to see someone through a whole building, through multiple floors. Most glass acts as a one-way thermal vision, and also when a subject is out of range and their thermal cannot be seen, this muzzle flash can be, regardless of distance or wall blocking. 

### Steps to Reproduce

1. Put on goggles
2. Run around with another individual and see the issues

### Expected Behavior

Thermals have very real potential to add a very cool RP effect to RP, but should be limited, With the already limited distance capabilities, it would be suspected these would usually be used in shootout scenarios in close-quarters rooms. I think id expect the distance to be much shorter then it is, id assume its currently around 50ish M distance but should be more like 5-10 and more limited on what can and cant be seen through. 

### Actual Results

The first issue is the inconstancies, some angles allow you to see a whole building when on the opposing side of that wall, that angle is not possible. Secondly, the muzzle flash problem, as detailed in a clip below, even when the ped model is out of range of a thermal or not visible by it, their guns flash still shows very clearly allowing to pinpoint where they are or are coming from. Third, you can see a thermal both in and out of the water, you can see this below too. 

In conclusion, I could assume the finer detailing on this system might be difficult, and while I could see some use for these in RP situations, it should be restricted. they can be limited within the use of PD by command but in the hands of the civ population, they could be powerful, considering they are quite simple to obtain and use indefinitely (assume) 

### Screenshots/Videos

Inside the apartment complex: https://medal.tv/games/gta-v/clips/YHlhPEEkPVhp4/d1337TSSqHks?invite=cr-MSxSeHUsMTQ5ODU1MDMs (seeing above the ceiling and through walls)

Inside of the Hawick agency building: https://medal.tv/games/gta-v/clips/YHlLGHjX5aGbz/d1337XKjXxrY?invite=cr-MSxuMUQsMTQ5ODU1MDMs once again seeing through floors and also showing one-way glass: https://medal.tv/games/gta-v/clips/YHlT0X2d2CsDD/d1337ZR4Pz7f?invite=cr-MSxacUEsMTQ5ODU1MDMs

Inside the Hawick building again, a good example of angles and one-sided perspective: https://medal.tv/games/gta-v/clips/YHm6fP8yfy4Ea/d1337a7FsGVa?invite=cr-MSxBYlUsMTQ5ODU1MDMs

Inside of humane labs: https://medal.tv/games/gta-v/clips/YHndCelh7OiJo/d1337eEzomaV?invite=cr-MSx6algsMTQ5ODU1MDMs showing the distance someone can be seen throughout a building

Inside of humane, showing the muzzle flash issue: https://medal.tv/games/gta-v/clips/YHnVcd-ITH-Yo/d1337GiZeJU2?invite=cr-MSxaRkMsMTQ5ODU1MDMs

Inside the bunker of humane labs, showing water and thermals effects: https://medal.tv/games/gta-v/clips/YHoh0bxsFKVIz/d1337SJlYGum?invite=cr-MSxEY1csMTQ5ODU1MDMs

### Game Resolution

-

### Player Data

-

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Okay, so there is only so much we can customize when it comes to thermals and a lot of it is undocumented. I've gone ahead and done a few more changes, including increasing the noise and decreasing the thickness you can see through quite a bit more. Should be live with the next restart if you wanna go and test again

**Comment by coalaura** [comment]
That said, the major issues i believe should be fixed now
