### ISSUE TITLE
Suggestion - ATM at prison Withdraw only

### ISSUE THREAD

**Issue by ExsertRook** [InZidiuZ/op-framework-issue-tracker#2706]
### Assurance

I have read the `README.md`

### Summary

Make it to where the ATM at the Prison is "Withdraw" only so that people can't deposit money in there but can withdraw money in the need of buying food.

### Reason

This would be useful if in whatever case an officer for some reason forgets to confiscate money off of a suspect that it gives officers a chance to go and confiscate the money off of the suspect rather than them immediately running to the ATM and depositing upwards of 20k in there.
Although officers should still make sure to confiscate money, I feel like this would give officers a second chance to be able to confiscate it off of them.

**Comment by coalaura** [comment]
I don't think the "second chance" is needed
