### ISSUE TITLE
Suggestion - /Jail warning

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#2707]
### Assurance

I have read the `README.md`

### Summary

With DOC slowing becoming a thing in the international server we have noticed that PD will send off inmates without realizing that DOC is on duty even after texting the PD Line and using /Dispatch notifying them.  I believe if someone is "On Duty" with the "Bolingbroke Penitentiary" department job should give a warning when someone uses the /jail command stating something along the lines of "DOC is on duty are you sure you want to send them to jail without contacting them?" and then they would have to write "yes" on the next command almost like how the /wipe command is set up in 2 parts.

### Reason

I believe this would be a good change for the framework so the DOC Officers get the RP they are waiting for when PD finally finds someone that broke the law instead of them just using the local "DOC" to send them to prison.

**Comment by MetaHatter** [comment]
Alternatively, if DOC are on duty, /jail "could" call their dispatch automatically and notify the officer that DOC has been contacted.

Possible logic:
- Officer types /jail command when DOC are on duty.
- Message goes out to all on duty DOC with the prisoner CID/paypal, pickup station and officer unit ID/name
- DOC chooses to accept the pickup.  /jailpickup [CID/paypal]
- Waypoint is added to the station for pickup
- Officer is notified pickup is on the way and be ready to accept DOC

To prevent issues:
- If accepted, prisoner must arrive in the prison range within 15 minutes or they are sent automatically.
- If not accepted by anyone within 3 minutes, they get sent automatically.
- If no DOC are on duty it works as it does now.

**Comment by coalaura** [comment]
i like the warning idea, will take a look at this

**Comment by MetaHatter** [comment]
> > * If accepted, prisoner must arrive in the prison range within 15 minutes or they are sent automatically.
> 
> This would make prison transport breaks impossible, so I disagree with this point. The rest is nice though.

Would need more thought for sure. Just don't want someone stuck in a cell for 45 minutes should the accepting DOC headpop or fly out.

**Comment by superiorchicken007** [comment]
> This would make prison transport breaks impossible, so I disagree with this point. The rest is nice though.
How would this make them impossible? Its just a notification that DOC is on duty so they don't automatically send them right away.  They could still get away during a transport as they are not "jailed yet".

> Would need more thought for sure. Just don't want someone stuck in a cell for 45 minutes should the accepting DOC headpop or fly out.
As for this. Like I said its still a warning, But when they get the second message they could still send them off even though DOC is on duty. Its basically "are you sure" you want to send them. Either Yes = they get sent off or No = You wait until either, DOC takes them or you run the command again and put yes which will send them this way none of that would be affected with making people wait.

I know on the MDT V2 there will be a DOC section to show whos on duty or not so in theory if PD is writing the report they would see that as they begin to process suspect and we will be there already before they are even ready to be sent off.

**Comment by enutpeanut** [comment]
> > This would make prison transport breaks impossible, so I disagree with this point. The rest is nice though.
> 
> How would this make them impossible? Its just a notification that DOC is on duty so they don't automatically send them right away. They could still get away during a transport as they are not "jailed yet".
> 
> > Would need more thought for sure. Just don't want someone stuck in a cell for 45 minutes should the accepting DOC headpop or fly out.
> 
> As for this. Like I said its still a warning, But when they get the second message they could still send them off even though DOC is on duty. Its basically "are you sure" you want to send them. Either Yes = they get sent off or No = You wait until either, DOC takes them or you run the command again and put yes which will send them this way none of that would be affected with making people wait.
> 
> I know on the MDT V2 there will be a DOC section to show whos on duty or not so in theory if PD is writing the report they would see that as they begin to process suspect and we will be there already before they are even ready to be sent off.

I was referencing MetaHatter's point about the 15 minute timer. I love the warning idea!

**Comment by roraraptor** [comment]
Instead of automatically sending the prisoners after a set time, there could be a way to force the command. Something like `/jail -f [CID/PayPal]` that allows the officer to send the prisoner anyway, in cases where DOC doesn't arrive after a reasonable amount of time or can't be reached to confirm they're on their way.

**Comment by coalaura** [comment]
There is now a thing in the phone showing on duty doc

![yes](https://i.shrt.day/LAbeneju12.png)
