### ISSUE TITLE
Suggestion - reduce the amount of food from z pills

### ISSUE THREAD

**Issue by obrew8** [InZidiuZ/op-framework-issue-tracker#2708]
### Assurance

I have read the `README.md`

### Summary

Amount of fruit from looting zombies is too much, would be a nice change to be reduced

### Reason

Doing zombie pills is sometimes infuriating as my inventory is constantly being filled with endless amounts of fruit, tbh i dont see the point as the fruit isnt even a good food item or cant be put in the jackpot etc. Would like to see the fruit either reduced or removed completely

**Comment by DaxterPancake** [comment]
Hear me out.. have you considered eating it? Selling it to people who use it to make better food? Dropping it?

**Comment by obrew8** [comment]
> yeah i do drop it which is why i think its a waste

**Comment by coalaura** [comment]
You can:
- Eat it
- Make moonshine with it
- Give it to other people
