### ISSUE TITLE
Bug report - Fuel while taking out vehicle 

### ISSUE THREAD

**Issue by T4NZ1M** [InZidiuZ/op-framework-issue-tracker#2709]
### Assurance

I have read the `README.md`

### Player Identification

https://steamcommunity.com/id/asttanzim

### Summary

If a car has 100% Fuel, storing it and then taking it out again gives 65% of the fuel and you lose 35% of fuel every time.

### Steps to Reproduce

Have a 100% fuel car, store it, and take it out again.  Or just at any point take out any car, even if the fuel is below 65, you'll still have 65

### Expected Behavior

The car should come out with the exact same amount of fuel it had while storing.

### Actual Results

Car is coming out with 65 Fuel

### Screenshots/Videos

https://discord.com/channels/903968228735332373/1082586296658182194/1084171446823166042

### Game Resolution

1920X1080

### Player Data

N/A

### Server

Bangladesh (c10s1.op-framework.com)

**Comment by coalaura** [comment]
Could you link some screenshots/videos? the discord link you posted i dont seem to have access to

**Comment by coalaura** [comment]
I've done some more fixes, this should hopefully now be fixed
