### ISSUE TITLE
Tuner Chip edit again / Subaru Patch

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#271]
**Name:**
Beezy #6584 | T-22 Mike Beezy steam ID SleezyBeezy

**Summary:**
Tuner chip was nerfed and it wasn't the problem. It now does basically nothing at all. I didnt see huge performance upgrades in any car over 30 mph until the new imports came in although it might of still needed some tweeking, but I feel there is something that was creating the issue. I dont know if the issue that video of the subaru all staff saw was because of a form of coding for the vehicle. The same vehicle was an issue on High Life (the other city i came from) and had to be modified as well. 

**Reason:**
I feel those of us that actually worked for finding those chips should have some form of reward for having them. And the fact it doesnt do much of anything noticeable now. It might need a little more tweeking and testing to get it where exactly you want it. But i didn't feel it to be too overpowering before the nerf. I'm not a coder so i could be completely wrong but i wanted to weigh in as i have modified tons of cars and seen the effects the chip makes on them with speed tests and a stop watch. I went a little overboard.

**Comment by InZidiuZ** [comment]
Hey,

Unless it truly was the Subaru's handling making it go that fast, then the tuner chip may *possibly* be tuned again, but until it's figured out, I won't be doing anything with it. If it's a vehicle issue though, then you'll have to post it [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for Karpenko to take a look.

**InZidiuZ**
*OP-FW Developer*
