### ISSUE TITLE
Suggestion - Remove Thermal Goggles

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2710]
### Assurance

I have read the `README.md`

### Summary

We dont need literally wall hacks on the server its really simple, There is no need for it and if we're gonna have that in the server you might as well unban Heisen Berg/Mr kisser. Its geniunely stupid and it's just wall hacks, A lot of people in discussions and other places have agreed and anyone that does shootouts/has experience with it knows that this is something stupid. ty ty

### Reason

Remove them because they bring nothing to rp and all they really do is just add wall hacks to the server LMFAO, Eulen for 6k

**Comment by coalaura** [comment]
Like i said, i have done fixes to them but they just weren't pushed yet. As you may know, nothing is perfect first try when it gets added. There was already a bug report and i looked into it #2705 
If they are still a huge issue after they have been in use after this update we can talk about it again
