### ISSUE TITLE
Bug report - Vehicle Tampering While on Training

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2711]
### Assurance

I have read the `README.md`

### Player Identification

steam:11000013fe41b53

### Summary

PD still receiving tampering calls even when on training tracker.

### Steps to Reproduce

Clock on as PD.
Go on training tracker.
Someone starts a tampering mission.

### Expected Behavior

No dispatch call.

### Actual Results

Dispatch call.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/116962577/224514322-24c5fdda-806f-407e-8c6e-d69bde0f5f9a.png)

### Game Resolution

1920 x 1080

### Player Data

![image](https://user-images.githubusercontent.com/116962577/224514333-674a7a1e-c24f-4c7f-ac59-6e5f76da1de9.png)

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This has now been fixed.
