### ISSUE TITLE
Bug report - Ford Mustang GT Driver Door Not Shutting

### ISSUE THREAD

**Issue by MillerManPlays** [InZidiuZ/op-framework-issue-tracker#2719]
### Assurance

I have read the `README.md`

### Player Identification

https://steamcommunity.com/id/MillerManGames/

### Summary

When Getting out of the door of the Mustang GT 5.0 the door wont shut properly unless you you push it, or not move from after pressing F.

https://medal.tv/games/gta-v/clips/XkLwEWnCrxXJL/d13377KffobE?invite=cr-MSxsN3QsNzE5MTg2MjQs

### Steps to Reproduce

Pressing F and then hitting another key.

### Expected Behavior

For the door to be fully fixed

### Actual Results

For the door to be somewhat fixed even if it's less buggy as it is.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/XkLwEWnCrxXJL/d13377KffobE?invite=cr-MSxsN3QsNzE5MTg2MjQs

### Game Resolution

1920x1080

### Player Data

82035 - Job Data: Vehicle Dealership, Premium Deluxe Motorsport, Salesman

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
This would be an asset issue, feel free to copy paste it over there https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
