### ISSUE TITLE
/sellcar instead of /givecar

### ISSUE THREAD

**Issue by SteezyRen** [InZidiuZ/op-framework-issue-tracker#272]
**Name:**
Steezy

**Summary:**
Instead of just giving your car to someone in hopes they won’t scam you can we make it like the /race event command where you can /sellcar [ID] [plate] [price] and a prompt will come up for someone to press E to purchase the vehicle for set price. 

**Reason:**
Currently selling vehicles is a huge risk when it really shouldn’t be. Don’t think it should be easy to scam someone for a lot of money with the current system for selling cars.

**Comment by Sleezybeezy** [comment]
i agree. i would actually pay mine off knowing i could sell it for atleast the price it was to buy. or close to it.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be changed.

**InZidiuZ**
*OP-FW Developer*
