### ISSUE TITLE
Suggestion - Require Heli License for Weazel

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2720]
### Assurance

I have read the `README.md`

### Summary

- Require a Heli pilots license to retrieve a Weazel News chopper.
- Remove Journalist job requirement.

### Reason

- Reporters usually don't fly helicopters, helicopter pilots do.
- Devalues the Heli license (legal and non) 
- Bypasses the RP associated with acquiring an actual license

**Comment by coalaura** [comment]
done
