### ISSUE TITLE
Suggestion - Adding a process to Cayo

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2721]
### Assurance

I have read the `README.md`

### Summary

I was wondering looking around Cayo we have some stuff to do but it would be cool to have a process over there that a group could control and bring more action to the island?

I see weed fields so wasnt sure if maybe weed field process could be run over there for example

I think economy wise if it was a way to harvest seeds to sell to people it would bring in a extra stream of income to more people. Plus unless I am unaware the only way for someone to get seeds is doing waste or paying people at waste for them.

### Reason

Yeah, a new process is always a good thing as there are more groups in the city, bring more action to the island.

**Comment by ImArteria** [comment]
We used to have a major process on Cayo and it was ass ngl. There IS something over there, just not on international. If it ever comes to international (pls sia) than we'd be gucci

**Comment by coalaura** [comment]
Cayo **HAS** a process. On the international server that process is disabled. So eventhough on the international server it may not have a process, it does on every other server
