### ISSUE TITLE
Bug report - LSCustoms does not check if you already have the item 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2722]
### Assurance

I have read the `README.md`

### Player Identification

steam:110000103fea0db

### Summary

Currently you can purchase customs for your vehicle that you already have.
I think this should not happen 

### Steps to Reproduce

1 Go to LSCustoms in a vehicle
2 Purchase something 
3 Purchase it again
4 Profit... no wait, debt.

### Expected Behavior

It should not charge the player and, optionally, throw a message saying "You already have this"

### Actual Results

It charges you again

### Screenshots/Videos

N/A

### Game Resolution

1920x1080

### Player Data

N/A

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
but it tells you that you already have it, by the symbol next to the thing that appears instead of the price, no?

**Comment by coalaura** [comment]
fixed
