### ISSUE TITLE
Suggestion - answer and reject calls directly from terminal

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2724]
### Assurance

I have read the `README.md`

### Summary

it would be easier if taking out phone isnt an issue while answering calls.

### Reason

taking out phone sometimes bugs the phone and screen becomes unresponsive

**Comment by ImArteria** [comment]
im confused if this is a bug or suggestion Imma keep it a buck, you should probably go in more detail regardless

**Comment by coalaura** [comment]
I don't think this is a real bug/issue. In the rare case that someone is indeed calling you in the exact same moment you are using the terminal, you can either close out of the terminal and hang up or just wait till your done or for the calling person to hang up themselves
