### ISSUE TITLE
Suggestion - Aircraft Tracker

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2725]
### Assurance

I have read the `README.md`

### Summary

The idea is for a command, something like "/aircraft_tracker" to enable a tracker whilst inside an aircraft. This would create a blip on the map, similar to PD, but a plane or helicopter icon. The blip would only be visible by people in other aircraft with the command also active, and by activating the command you can see other aircraft which have the tracker on. The tracker follows the aircraft much like the Stockade until it is toggled off or put away. It always starts toggled off when someone gets into an aircraft. 

Additionally a "/callsign" command could be added alongside the tracker. It would work like "unit_id" and the blip would have a label for the aircraft's callsign. The callsign will stay the same and appear when the "aircraft_tracker" is toggled on. 

For example, I would do "/callsign 48-D" and this would label my tracker as "48-D". Every time I start a flight, I'd have to do "/aircraft_tracker".

### Reason

This would make legal aviation more interesting and allow aviation authorities to keep track of flights. It will bring immersion to people who partake in aviation roleplay, and even open up ATC roleplay.

**Comment by rakibulhasan456** [comment]
As a pilot from the subdivision, I love your idea. We've wanted this feature for a long time. It helps to find other pilots easily when doing stunts and formation flies.

My fellow pilots and I would be happy to see this feature in the city.

**Comment by TheOneLizard** [comment]
I like the idea, and always wanted sth like it.

The question is more how to make it work. To emphasise on when the tracker is visible and when not, and to whom, I'll make a short list here for a better overview (all imo ofc)

who can see trackers and when:
- PD on duty
- pilots after using command /aircraft_tracker (can only be activated in aircraft and disables when leaving aircraft)
- state personnel when using the command (they do not need to be in an aircraft)

This would be the more complicated and detailed version. Alternatively PD can only see the trackers when using the command as well, and maybe state does not have additional privileges to see the trackers outsite of aircraft.

**Comment by enutpeanut** [comment]
> who can see trackers and when:
> 
> * PD on duty

100%, I think PD on duty should be able to see the trackers when it’s active!

**Comment by enutpeanut** [comment]
To expand on this suggestion, attaching the altitude to the tracker would be great, especially for ATC RP. Potentially show the altitude next to the label, like the waypoint marker.
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116962577/7b8e3569-60a5-4672-a244-d6b0fe1ef8cf)

**Comment by coalaura** [comment]
Flight radar item and /callsign command

![yes](https://i.shrt.day/MY1VTOIGM5.webp)
![yes](https://i.shrt.day/9BIZRVF52C.webp)
![yes](https://i.shrt.day/WCG1JI3W3I.webp)
![yes](https://i.shrt.day/5IPU8NUM32.webp)

**Comment by enutpeanut** [comment]
WOOOOOOOO
