### ISSUE TITLE
Suggestion - Weight change for phone + Pricing change on armor!!

### ISSUE THREAD

**Issue by Daniini** [InZidiuZ/op-framework-issue-tracker#2726]
### Assurance

I have read the `README.md`

### Summary

pretty straightforward!! just change it to 1 or 2 lbs or someshit its annoyin thats its 10!! thank u!!
PLS CHANGE THE ARMOR PRICE TO LIKE 250 LIKE THE PD ONE, I THINK 400 IS CRAZY ESPECIALLY W THE TAX!

### Reason

For the phone, its just annoying that it weighs so much n takes up a lot of space in important situations!!
for the armor, ok so pd pays 250 for it + tax and I get why since they are PD and they have to buy it a lot! would be a good reason for it but the truth is crims use armor waayyy more than cops and i think it should be cheaper, maybe 250-300, PLS! IT COSTS SO MUCH I DONT SEE THE HARM!

**Comment by ImArteria** [comment]
I had a github about the phone/radio weights so I agree with you there. Dont think the armor price should go down. There's a multitude of ways for crims to get armor (assuming you dont mean in a gun fight) like joints, moonshine, alcohol, and cigarettes I think? If you plan to go into a shootout, the $1400 cost is not that big of a concern.

**Comment by Daniini** [comment]
> 

I wanted radio changed but i looked it up n i might b dumb but it looks like legacy got it right w the weight.

the armor im sayin cuz u buy like 1400-1800 worth of armor multiple times everyday or sum shit but yeah it aint THAT important but i'd like it

**Comment by ImArteria** [comment]
> > 
> 
> I wanted radio changed but i looked it up n i might b dumb but it looks like legacy got it right w the weight.
> 
> the armor im sayin cuz u buy like 1400-1800 worth of armor multiple times everyday or sum shit but yeah it aint THAT important but i'd like it

How many mfers are you shootin bruh go drink moonshine

**Comment by Daniini** [comment]
> > > 
> > 
> > 
> > I wanted radio changed but i looked it up n i might b dumb but it looks like legacy got it right w the weight.
> > the armor im sayin cuz u buy like 1400-1800 worth of armor multiple times everyday or sum shit but yeah it aint THAT important but i'd like it
> 
> How many mfers are you shootin bruh go drink moonshine

I JUST USE A LOT OF ARMOR NOT EVEN FOR SHOOTING!! I DONT SHOOT!! I JUST MEAN DURING WAR/CONFLICT

**Comment by coalaura** [comment]
Items weight isn't determined by their irl weight. Rather the more important or useful an item is the heavier it is, therefore causing a drawback of carrying it. You have to decide: Do i carry this item or that one?  
So, no i wont reduce the phones weight. (same deal for radios btw)

Armor cost i understand you, yet like arteria said there is a bunch of other ways of acquiring armor. I'm down to reduce it a little bit, maybe to 300 but thats it.
