### ISSUE TITLE
Suggestion - Improve the /mechanicRepairs API Endpoint

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2727]
### Assurance

I have read the `README.md`

### Summary

The `/mechanicRepairs.json` endpoint currenly has no easy way to differentiate 2 repairs by the same mechanic on the same vehicle  as each repair item has a timestamp.

Would it be possible to somehow split the repairs into their own objects?

eg
```json
{
  "data": [
    {
      "characterId": 1234,
      "repairs": [
        {
          "plate": "27MFR381",
          "timestamp": 1678900329,
          "engine": {
            "timestamp": 1678900329,
            "materialsUsed": [
              {
                "amount": 1,
                "itemName": "scrap"
              },
              {
                "amount": 2,
                "itemName": "steel"
              }
            ]
          }
        },
        {
          "plate": "27MFR381",
          "timestamp": 1678900500,
          "engine": {
            "timestamp": 1678900329,
            "materialsUsed": [
              {
                "amount": 1,
                "itemName": "scrap"
              },
              {
                "amount": 1,
                "itemName": "steel"
              }
            ]
          },
          "body": {
            "timestamp": 1678900534,
            "materialsUsed": [
              {
                "amount": 1,
                "itemName": "scrap"
              },
              {
                "amount": 1,
                "itemName": "aluminum"
              }
            ]
          },
          "door": {
            "timestamp": 1678900500
          }
        }
      ]
    }
  ]
}
```

### Reason

Currently this API Endpoint isn't used due to it not being possible to differentiate between completed repairs.
This change would help better track repairs.

**Comment by InZidiuZ** [comment]
How do you even properly differentiate between two different repairs on the same car? There's no 'start' and no 'end' for the repairs. There's just a bunch of different individual repairs. And all of those, do have timestamps. You can just group together the repairs that happened in a certain time-frame (5 minutes for example), if that's what you want.
