### ISSUE TITLE
Suggestion - Add failure mechanic to store lockpicking

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2728]
### Assurance

I have read the `README.md`

### Summary

Add static or an ever-increasing chance to ruin the lock when you fail a store lockpick.

if a lock gets ruined you can no longer attempt to pick it.

Easy implementation
2nd or 3rd failure, ruin the lock.

RNG implementation
1 failed pick = 20% chance to ruin the lock
2 failed picks = 40% chance to ruin the lock
3 failed picks = 80% chance to ruin the lock
4 failed picks = ruin the lock

### Reason

Currently RP is held up for as long as it takes for the crims to pick all possible locks if there is a hostage.  Regardless of how terrible they are at it.

This would incentivize getting it right the first time and not have everyone waiting around for them to not screw up.

**Comment by coalaura** [comment]
Stores are meant as a kind of "cash and grab" the lockpicking is pretty damn difficult already and they are perfectly balanced where they are right now. No need to make it even harder for the small payout you get
