### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by BlueShirtMonkeyMask** [InZidiuZ/op-framework-issue-tracker#2729]
### Assurance

I have read the `README.md`

### Summary

I was chopping cars and it said to bring me a (dilettante), so I brought him a dilettante car, but it was a PATROL dilettante car, and it wouldn't let me chop it.
No, the locations given have no bearing on whether the car is choppable or not; if you bring the model given to the chop location, you can do your thing.

### Steps to Reproduce

make these vehicles choppable

### Expected Behavior

.

### Actual Results

.

### Screenshots/Videos

![Screenshot_1](https://user-images.githubusercontent.com/127624523/225544237-d7df1fc4-4fcd-4b62-8590-f8ce6e31bc00.png)
![Screenshot_2](https://user-images.githubusercontent.com/127624523/225544240-8cdd00ab-3363-4406-87c3-7bd11ee8e20a.png)

### Game Resolution

.

### Player Data

.

### Server

OP-FW Test Server (c2s1.op-framework.com)

**Comment by ImArteria** [comment]
Pretty sure the car you brought him was a different model that's not in the chop list. I wouldnt say this is a bug because usually it will tell you which model

**Comment by MetaHatter** [comment]
The patrol version of this car is the "dilettante2" and why it did not work.  Not a bug.

**Comment by BlueShirtMonkeyMask** [comment]
> The patrol version of this car is the "dilettante2" and why it did not work. Not a bug.

I'm not sure if the number matters, but this type of car should be set to one.
In my opinion, chopping is enjoyable and entertaining.
However, a change is needed.
Sometimes it gives a location where the car does not even spawn. I usually ignore the location and just google what kind of car it is and drive to the locations where it spawns, on the road, parked, etc.
Looking at the car model, I would most likely know where it should be spawning or parked, as it was given to me once to find issi2 at sandy shores issi2 does not drive around sandy and I tested this I checked every corner, everything there was no issi2 at sandy I called my buddies to figure out if issi2 even drives around sandy and it does not.
Maybe it's the sandys on the highway. but it isn't there.

**Comment by coalaura** [comment]
Patrol version of the dilettante: `dilettante2` https://www.gtabase.com/grand-theft-auto-v/vehicles/dilettante-patrol
Regular version: `dilettante` https://www.gtabase.com/grand-theft-auto-v/vehicles/karin-dilettante

These are 2 separate vehicles. Not a bug

**Comment by coalaura** [comment]
> Sometimes it gives a location where the car does not even spawn. I usually ignore the location and just google what kind of car it is and drive to the locations where it spawns, on the road, parked, etc.

It gives you a location where one of the requested cars was last seen. It could potentially be that that was the only car in that area.
