### ISSUE TITLE
Unequipping Mods Delete Them

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#273]
**Reporter:**
Beezy#6584   steamname SleezyBeezy T-22 Mike Beezy

**Summary:**
Anything you remove from the Customs shop no longer is yours as if it doesnt remember anything you've purchased. I was testing the speed with and without the turbo on my vehicle as it was slower after i bought the turbo until the previous vanilla handling patch went out. So i figured i would test to see if the results were the same and it seems to have fixed the issue except for the fact i can't re-equip something i already purchased. and as it being one of the most expensive mods, its pretty disappointing.
**Steps to Reproduce:**
Literally unequip anything and try to re-equip it and you will have to repurchase it, even in the same screen.
**Expected Results:**
I expect you should be able to equip things you already purchased or atleast maybe add the feature of selling mods back or unequipping them for a small compesation of what you spent incase you want to switch things up or go with a different look.
**Actual Results:**
Actual results are just equip/buy, unequip. That simple.

## Additional Information

**Screenshots:**
https://streamable.com/5auoe

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 1628 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Notes:**
Whichever is easiest, would be appreciated. Is there a posibility of you just readding the mod to the vehicle or sending it to me in some way so i can repurchase it as i want it on my vehicle just wanted to test reporting a bug i heard about incase it wasn't fixed and made more issues with new patch. The plate of the vehicle is 26MXK451.

**Comment by InZidiuZ** [comment]
Hey,

This is not a bug, it was never intended for you to have the ability to re-equip a mod after purchasing another.

**InZidiuZ**
*OP-FW Developer*
