### ISSUE TITLE
Suggestion - To add a new PD compass with street name

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#2730]
### Assurance

I have read the `README.md`

### Summary

I am suggesting to add a new PD compass or a command which will only work in PD vehicles for ex. /compass
this will enable the E N S NE SW direction along with the street name on top of the screen under the watermark.

Example of this - https://imgur.com/a/vIdLenM with only the street name ( Its the BR world in legacy)

### Reason

So the reason i am suggesting this is because players like me who does pd rp with a small monitor (low resolution) its really hard to give radio call outs with the small gps (default) and at the same time its hard to keep visual on the chasing car.
example- https://imgur.com/a/5KXPEmc 
its hard to look at the street names and the directions N S E W he is driving towards.

The main reason i am suggesting this is bcz i do have 1366x768 resolution and its kinda hard to chase with callouts for me.

**Comment by CloudTheWolf** [comment]
As much as I would love this to be where the compass is (Not just for PD), The top middle of the screen could would to crowded for those that don't have the watermark disabled and have metrics on.

**Comment by coalaura** [comment]
yeah like cloud said and i also don't think this is really needed
