### ISSUE TITLE
Bug report - Emotes missing props

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2731]
### Assurance

I have read the `README.md`

### Reporter

MetaHatter#0001

### Summary

Props for some emotes like the cigarette in "/e smoke" are not visible.  

I am unsure of the full extent of this bug.

### Steps to Reproduce

Type "/e smoke" and look at you smoking nothing

### Expected Behavior

The cigarette prop is expected to show

### Actual Results

you do the smoke animation empty handed.

### Game Resolution

1440p

### Server

International (c3s1.op-framework.com)

**Comment by CloudTheWolf** [comment]
I think this is the same when you are actually smoking a joint/cigarette

**Comment by coalaura** [comment]
Did more research and i canrt figure out what is causing it
