### ISSUE TITLE
Suggestion - gem refining automatically

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2733]
### Assurance

I have read the `README.md`

### Summary

I have two suggestions for this

1. when choosing a gem type we can also choose an amount so emerald 30 and that would then auto start the next one 
2. pay a service to deposit my gems and then come back later once they are done. The quantity and rarity of gems will result in the fee to pay

### Reason

Currently when refining gems we have to manually click every 20-40 seconds. When people are doing 30+ gems at a time this becomes tedious. I have stood there many times and heard people say “f this I am bored to do any more” 

I think it wouldn’t add much to economy but for people’s quality of gameplay it would mean a lot. If someone can only come on for 2 hours an evening the thought of standing refining every 20 seconds puts them off

**Comment by ImArteria** [comment]
Pretty sure Mining in terms of economy is very strong and the main thing it requires is time, so dont know if taking a lot of "time" away is key.

**Comment by coalaura** [comment]
The whole point of gem refining is that it takes time and you are forced to be there
