### ISSUE TITLE
Suggestion - New Daily Tasks - Weekly/Monthly reward

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2734]
### Assurance

I have read the `README.md`

### Summary

The daily tasks that have been introduced are a good way to keep people coming back but when it’s daily you find people will stop after a week or so. 

What if after the 4th task is complete you get a [point] and at the end of the week/month those points become for example free wheelspins at casino or tickets into winning a car etc just some bigger prize for the longer term

### Reason

Turning a task that gets people coming back daily will encourage more to come in for longer periods as they will want to earn that big price end of the week/month for getting all the daily tasks done etc

**Comment by InZidiuZ** [comment]
This has now been done. Every day you finish all 4 tasks, you'll get a streak point. If you fail to do all 4 tasks one day, you'll lose your streak. You can see in the video here what it looks like: https://www.inzidiuz.com/u/ZJs2klAl.mp4

When your streak points is 7 or greater, you'll get a second free spin on the Lucky Wheel. This will most likely be expanded on in the future with more streak points giving more rewards.
