### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2735]
### Assurance

I have read the `README.md`

### Reporter

Smiithy#4779

### Summary

Flying to Cayo airspace right before reaching the crossover my plane looks like it hits the edge and breaks :D 

https://user-images.githubusercontent.com/32597507/226159162-89b8f062-7113-454e-807a-599278e02798.mp4

### Steps to Reproduce

flew over to cayo

### Expected Behavior

dont fall apart :D

### Actual Results

having to swim all the way to shore :)

### Screenshots/Videos

https://user-images.githubusercontent.com/32597507/226159208-0684d4d8-eac5-4683-9481-c6e89bc9d092.mp4

### Game Resolution

2560x1440

### Player Data

![image](https://user-images.githubusercontent.com/32597507/226159233-fed7d121-f3ae-4ac4-84d6-f08e1a2fafb3.png)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Its telling you you are too far, don't keep flying if it tells you you are about to be out of bounds. If you fly out of bounds, your plane will break. If it tells you that, that means you need to fly more east
