### ISSUE TITLE
Bug report - gem refining 

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2736]
### Assurance

I have read the `README.md`

### Reporter

BlackHawk#3322

### Summary

option to process disappear after we refine one gem.

### Steps to Reproduce

go to mining refine and refine one gem

### Expected Behavior

contineous one by one refining

### Actual Results

no option after one refine

### Game Resolution

1080p

### Player Data

Character ID:1732 - Job Data: Business, Midnight Tunershopt Tuner
Timestamp: 2023-03-1916: 16:59

### Server

Nepal (c13s1.op-framework.com)

**Comment by gadjinee** [comment]
If you have your car close to the refinery sit in it and go back to refining table it will give you an option again unfortunately you have to repeat it for all the gems

**Comment by sakar5157** [comment]
> If you have your car close to the refinery sit in it and go back to refining table it will give you an option again unfortunately you have to repeat it for all the gems

this is a temporary fix

**Comment by InZidiuZ** [comment]
This should no longer be an issue after next restart.
