### ISSUE TITLE
Diving "job" buffs

### ISSUE THREAD

**Issue by capsure** [InZidiuZ/op-framework-issue-tracker#274]
**Name:**
capsure#0737

**Summary:**
I've got numbers compiled from many dive attempts.
Currently the avg profit per dive is about $800 for about 20min of time required.
Removing "junk" from being a looted item would drastically increase the amount of items collected each run. Right now you have as likely a chance to find junk as you do to find (copper and plastic) which is also basically junk until those items have value. On top of that glass and rubber also have little to no value as there aren't any real mechanics as anybody can fix anything and buy the materials at will.  Even if you find somebody who will buy those materials its at a drastically reduced rate because of how much space they take up in inventory to just sit there.

**Reason:**
Until the other high loot items have value remove junk from being a looted item. This will also indirectly increase the loot chance of thermite which is obviously something that has been tried to be addressed by directly increasing its loot percent. Which to be honest I haven't noticed a difference in drop rates for thermite and if anything its gone down as well as gold is dropped even less now.  Another option would be to allow people to sell glass and rubber as well for the standard $8 a weight unit which would increase profits nearly $400 as well. The $800 profit avg is predicated on you actually getting a gold bar or thermite and then also being able to sell the thermite... If you don't get either of those items your profit is less than $500...

**Comment by InZidiuZ** [comment]
Hey,

>Which to be honest I haven't noticed a difference in drop rates for thermite and if anything its gone down as well as gold is dropped even less now.

No, that is not the case, I even specifically said in the patch-notes it was increased, and *not* decreased. Gold also hasn't been touched. For diving, thermite was made 4 times more common to find than previously.

>On top of that glass and rubber also have little to no value as there aren't any real mechanics

Yes, there are, ever tried finding one through *roleplay*? Not talking about tweeting here, but actually trying to build contacts, friends, stories, etc.

I'll be reducing the weight for rubber & glass, and possibly some more items, but much else won't be done, for now.

**InZidiuZ**
*OP-FW Developer*

**Comment by capsure** [comment]
Yes I play as a mechanic. Nobody uses rubber to fix tires they use repair kits because its much cheaper. And glass is worth $40 a pop.  I've done plenty of mechanic RP and its very time consuming and slow because of the current ability for anyone to be a mechanic and to also access the shop even if you aren't a mechanic. 

 I have read the patch notes and kept up with them I am aware you said you've increased the drop rates of thermite. I wasn't sure if it was only for garbage or chopping or diving or all of them. What I do know is that since the update that increased it I've gone out diving 5 times and got 1 thermite. The previous 5 I got 4 before the update. I've been tracking my numbers so that I could correlate how much stuff ways vs how much stuff sells for and other basic stats related to items and their value.

I don't just put stuff out here on a whim. This is tracked and correlates over time from patch to patch, and since you've obviously been tweaking stuff related to diving and weight and such. I just wanted to put it out there that getting "junk" while diving when you couple all the other factors that 50% of the time when its not junk, its essentially junk.
