### ISSUE TITLE
Suggestion - Daily challenges Feedback & Suggestions  

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2741]
### Assurance

I have read the `README.md`

### Summary

Here is some feedback from daily challenges

1) Some challenges are not worth doing,
For example: 
- Buy 48 boxes of pistol ammo (Reward ~$800 costs ~$2400)
- Take 20 Zombie Pills (Literally costs $30,000 👀)

2) It would be nice to have a Reroll option (With an option to only get Legal challenges for us crazy people who play only Legal Characters xD) 

3) Here are a few suggestions for more challenges:

- Ride a bicycle from the peak of Mount Chilliad to Grapeseed in 120 seconds without falling off
- Parachute from the top of {Maze Bank Tower / Mount Chilliad} and travel at least x Meters before landing.
- Drink a bottle of gasoline
- Do a wheely on a motor cycle and travel at least x meters 
- Enjoy a cup of joe (Promote people wanting to go to Bean Machine)
- Enjoy the smell of a freshly made burger (Promote people wanting to go to Bean Machine)
- Swim from the Lighthouse to the Sunken Ship
- Touch the bottom of Tataviam Reservoir 
- Visit the Haunted Highschool at midnight
- Enjoy the view from the observatory
- Cleanup X items in the ocean (Promote Scuba)
- Have a Coconut fall on your head (Get Coco beans  on Cayo)
- Slip on wet grass
- Do X laps of the Diamond Resort Race Track 
- Wear a paper bag
- Put a paper bag on another person 
- Tackle X locals 

### Reason

Feedback on Daily Challenges

**Comment by CloudTheWolf** [comment]
Here are the suggestions by @vol5
- Swim in 10 different pools
- Emote on someone after knocking them out
- Honk your horn at (x) many local cars
- Reach (x) number of altitude, anywhere
- Fly in heli for x number of time
- Stop at (x) red lights
- Obey the speed limit for 10 mins
- Run around the marathon track 3 times
- Visit (Random Named) landmark
- Smoke a pack of ciggies
- Flash 3 different trading cards
- Repair 1 car with advanced repair kit
- Repair 1 car with normal repair kit
- Change the color of a car
- Give someone a piggy back ride
- Get a piggy back ride
- Withdraw any amount of cash from an atm
- Walk up (x) number of stairs
- Survive a fall of 10m
- Check into the hospital
- Drink a Capri Sun
- Swim (x) number of distance
- Swim in the ocean
- Visit 10 different Islands
- Fill up your car to full
- Make a smoothie
- Break a car window with the (Emergency Window Breaker)
- Wear Ear Defenders
- Drink Bleach
- Peperspray someone
- Stop local traffic
- Knock someone out wearing boxing gloves
- Put a paper bag on someone's head
- Clean a local car
- Leash another person
- Get any vehicle repaired from a mechanic
- Loot 10 trash bins
- Get blackout drunk
- Open a trading card pack
- Join the boosting queue
- Buy (x) soda's from a vending machine
- Do a stunt on a bmx
- Reach a top speed of 180mph+
- Win a round of jackpot
- Put 5 items into a single jackpot bet
- Put 5k worth of items in a single jackpot bet
- Win a jackpot totaling to 20k+ worth of value
- Jump out of a Heli
- Jump out of a Plane
- Ride in a boat for (x) meters
- Change outfits you stinky fuck
- Stand in the rain
- Clean your car at a car wash
- Test drive any pdm car and return it
- Visit EDM
- Throw (x) snowball's
- Throw (x) baseball's
- Break (x) Drills's
- Put a gold bar in your pocket
- Fall down
- Damage an ATM
- Stab a local
- Go up an elevator
- Refine a gemstone
- Pick a Shroom
- Do some cocaine
- Od on cocaine
- Smoke a joint
- Eat a (x fruit)
- Drive around the entire island
- Walk on the beach for (x mins) or (x distance)
- Place down furniture in your house
- Buy a new house/apartment
- Visit Cayo Perico
- Change the color of your car
- BnE a local car
- Walk 1k steps

**Comment by MetaHatter** [comment]
> 1. Some challenges are not worth doing,
>    For example:
> 
> * Buy 48 boxes of pistol ammo (Reward ~$800 costs ~$2400)
> * Take 20 Zombie Pills (Literally costs $30,000 👀)
> 

It could be argued that you will still be able to use the pistol ammo and the Z-Pills are generally profitable so "worth" should take intrinsic value into account. Although I agree the quantities might be high for those two, it's still not really a bad deal overall.

**Comment by vol5** [comment]
> It could be argued that you will still be able to use the pistol ammo and the Z-Pills are generally profitable so "worth" should take intrinsic value into account. Although I agree the quantities might be high for those two, it's still not really a bad deal overall.

You make a good point here, values are a bit to high. For some things like z-pill quantity, scuba material collection, etc. Some ranges around 5-10 would be much better, vs around now where its 20+ would be a good help.

**Comment by CloudTheWolf** [comment]
So recent though for this would be remove the "Get X Kills / Headshots In Arena" as people honestly just cheat the system on this and it reduced the incentive to actually play arena. 

A cool replacement could be something like "Take a photo at X" (Eg Take a photo in the Haunted Highscool)
It might not be possible, but would be also cool for things like "Take a photo of a rabbit", with the Camera Item even giving you the Picture Item as well

**Comment by CloudTheWolf** [comment]
There are a few issues for this now, so better to keep in a single place, see #2887
