### ISSUE TITLE
Bug report - drinking alcohol not incresing armor and character not getting sobber again

### ISSUE THREAD

**Issue by Rayysho** [InZidiuZ/op-framework-issue-tracker#2744]
### Assurance

I have read the `README.md`

### Reporter

Rayysho#1201

### Summary

I drank alcohol and I did not get sober for so long even if i drank water. Plus my Armor did not increase at all .

### Steps to Reproduce

armor should be increasing and I should have got normal if i drank water

### Expected Behavior

nothing

### Actual Results

i did not get sober at all

### Screenshots/Videos

![Screenshot_6](https://user-images.githubusercontent.com/128691769/227163306-024e781e-0240-48d5-8325-150962b16e60.png)

### Game Resolution

gta v

### Player Data

![Screenshot_7](https://user-images.githubusercontent.com/128691769/227163448-925d3de7-ef7a-4424-91f9-baa5c41a8121.png)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
