### ISSUE TITLE
Weapon License Update

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2745]
### Assurance

I have read the `README.md`

### Summary

I am not sure if this is already the case but Is it possible to add/remove weapons to the weapon license with the help of config? Like we need that all guns can only be bought only if the person has a weapon license on him.

### Reason

I am not saying to make it default for all servers if it's in config it will help the other division to make some changes as they like.

**Comment by coalaura** [comment]
Example: `requires_weapon_license = "weapon_pistol,weapon_vintagepistol"`
