### ISSUE TITLE
Show Prop Name while Managing Furniture

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#2747]
### Assurance

I have read the `README.md`

### Summary

While **Managing Nearest** and **Managing Object** during the /furniture, show the prop name at the bottom of the UI.

### Reason

It's very difficult to say which object am I looking at or modifying by looking at the list. There's no name of the furniture while searching for a specific one. Sometimes the angle is very off that it's very hard to say which is what.

Working with the 400 different prop is even more painful. Need to look at each of them carefully and sometimes modify them to see which one is moving. As a result, the furniture goes out of the place.

But with a **prop name**, we can easily understand which one I am going to modify and will help much to search and manage numerous models.

I'm sure most of us has faced problems while modifying the furniture due to the absent model name, and it will definitely be a great edition for the designer and to everyone who does their own furniture.

**Comment by coalaura** [comment]
done
![ye](https://i.shrt.day/NEpiQuRI84.png)
