### ISSUE TITLE
Suggestion - New Player Car QoL Improvement

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2749]
### Assurance

I have read the `README.md`

### Summary

Change the initial New Player car process to reduce clutter and simultaneously teach about public garages.

- Existing waypoint system (if key is pressed) remains to simplify getting to the location
- Add a public garage (interaction point and building) to the Airport parking lot
- Add a GTA native waypoint to the new LSIA garage on first load to ensure it is found
- Car is not automatically spawned and requires use of the garage
- Tooltip is added on arrival telling people to "Access your starter car from the garage"

### Reason

- Many new players do not hit the initial key to get their car
- Cars are often ignored leading to clutter
- Teach New Players about public garage functionality

**Comment by InZidiuZ** [comment]
Several improvements have since been made to this system.
