### ISSUE TITLE
tequi la -la 

### ISSUE THREAD

**Issue by merrick453** [InZidiuZ/op-framework-issue-tracker#2750]
### Assurance

I have read the `README.md`

### Summary

hello i am Adain Mcknight the new owner of tequi la la  my vision for this bar /nightclub is not sucky punk music i believe this bar/nightclub can go from a eye sore  to a gemstone if certin things are fixxed  
1) atm or  a p.o.s system
2) better food or a way to  make food
3) working dj booth
4) bar trays to put food and drinks on after the customer pays
5) not charge the bar tender to server dicks and food 
I believe with everything in me that doing this will be better for legacy

### Reason

the reason why i am suggesting is because 
Tequi LA LA was once known as a biker/dive bar which is a thing of the past
have a revamped bar/nightclub can only make it better 
that is why i am suggestion this to framework it may not be easy but nothing great ever is thank you for reading my suggestion

**Comment by coalaura** [comment]
1. That would be a suggestion for the asset issue tracker [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
2. No, TequiLaLa is a bar, not a restaurant. There is no need for food
3. I dont think we need a whole new DJ system made for the server if there is boomboxes that do the exact same thing
4. Believe this is already being worked on but again, see point 2.
5. No, the point is you buy it and sell it for slightly more, thats how **every** business in the city does it, nobody gets things for free
