### ISSUE TITLE
Bug report - Fuel level of vehicles

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2751]
### Assurance

I have read the `README.md`

### Reporter

Star Groot#2478

### Summary

When getting a car repaired at a mechanic shop the fuel level of the car is set to 65.

### Steps to Reproduce

Damage the car -> repair body and engine -> get back inside the car

### Expected Behavior

(Fuel is at 34) repair body and engine, get back in the car and fuel is still at 34

### Actual Results

When repairing cars the fuel of the car is set to 65

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Should be fixed now
