### ISSUE TITLE
Suggestion - 945 Studios Employee Pay

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2752]
### Assurance

I have read the `README.md`

### Summary

Currently the 945 Studios pay is 40 - 30 - 20

Throughout the entire time of the business being around. No one wants the base job because the pay is to low in comparison to others. So I struggled to employ people officially. Because they can work somewhere else and sell packs at the same time along with photography and adverts etc. Its been a very long time since the business came about and I'm requesting that the lower 2 tiers be changed as greater than the owner pay because of the low amount currently.

Owner - Manager - Employee

I would love for this to be changed to 

> 40 - 55 - 70

Thus making the employee job focused around people who are creating content to put on twitter etc. The goal is to make the job more lucrative for other people and primarily for creators that make content. ie. Pictures, video, etc. I feel it would be of great benefit to give more value to those who make things. Its good rp all around. And when people make things for others it gives them a great sense of importance and more content being made in the server is good all around.

### Reason

- Promotes content creation
- Benefits creators
- Brings more value to art

**Comment by coalaura** [comment]
Most definitely not. The pay is more than enough. You can make a decent profit with the cards
