### ISSUE TITLE
Suggestion - Change Key for Interact With Items

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2753]
### Assurance

I have read the `README.md`

### Summary

Change the keybind for using ATM/Water Cooler/ Yogamat from E to G to stop clashing with Door Lock / Manage Props (For Yogamat) 

### Reason

I have noticed that there is a bit of a clash with some key binds and interactions.

For example:

Door Locks and ATMS/Watercoolers/Using Yoga Matts 
Using a Yoga Mat and Picking Up said Yoga Matt

**Comment by InZidiuZ** [comment]
This should be fixed in other ways, not by just moving the problem to another key and creating inconsistencies, so no
