### ISSUE TITLE
Suggestion - DOJ App

### ISSUE THREAD

**Issue by M4TT3R1** [InZidiuZ/op-framework-issue-tracker#2754]
### Assurance

I have read the `README.md`

### Summary

Adding a DOJ app for the tablet or a DOJ tablet where there would have access to the penal code, government roster, and possibly the court docket. 

### Reason

Being able to navigate these areas while talking to citizens in the city would enhance the RP. Currently you have to have a 2nd monitor and tab over to review which can then make the conversations with citizens laggy by having to pause to tab back and forth between screens. Keeping it all in game, allows smoother conversations and more interactions in the city.

**Comment by coalaura** [comment]
you would still have to open the tablet, open the app, click on the penal code... Doesn't really seem much faster to me ngl. In addition to that the all those documents are different for each subdivision

**Comment by M4TT3R1** [comment]
but when you're doing all those things you can still talk in city while on the tablet. having to pull it up on a 2nd monitor or tab between forces you to not be able to keep talking causing extended pauses.

**Comment by KaiEagle** [comment]
> but when you're doing all those things you can still talk in city while on the tablet. having to pull it up on a 2nd monitor or tab between forces you to not be able to keep talking causing extended pauses.

Go to settings - Audio - Disable (Off) "Mute Audio On Focus Loss" 
Which will let you hear and talk to people around you even when you are Alt+Tab.

**Comment by M4TT3R1** [comment]
you can hear that way, but if ur not on the game screen then push to talk doesnt work.

**Comment by KaiEagle** [comment]
Does work for me

**Comment by coalaura** [comment]
yeah i'm just saying cause i've never had this issue either. I'm a lot of the times doing something else on the side while in city and when someone talks to me i dont even need to focus the game
