### ISSUE TITLE
Add Functionality to Sandy Fire Station

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2755]
### Assurance

I have read the `README.md`

### Summary

Been told this needs to go on hold until Fire Department is split from EMS

The Fire Station is now live, as such please enable Door Looks for the Fire Dept Job

Additionally, please also add the following:

On/Off Duty Spot:
![duty](https://cdn.discordapp.com/attachments/1054807586194595931/1094929477596872814/FiveM_b2699_GTAProcess_FaUNnozXtu.jpg)

Lockers: 
![Lockers](https://cdn.discordapp.com/attachments/1054807586194595931/1094929284256247908/FiveM_b2699_GTAProcess_C5eXzGyoFE.jpg)

Lockers (Alternative Spot)
![Lockers Alt](https://cdn.discordapp.com/attachments/1054807586194595931/1094929193504096296/FiveM_b2699_GTAProcess_PaAE8BRru4.jpg)

Clothing Circle: 
!(Clothing)https://cdn.discordapp.com/attachments/1054807586194595931/1094929223245893632/FiveM_b2699_GTAProcess_AZHkmAdPAF.jpg]

Fly Out Spot
![flyout](https://cdn.discordapp.com/attachments/1054807586194595931/1094929116383432764/FiveM_b2699_GTAProcess_l8MbxiLWiS.jpg)

Personal Vehicle Garage:
![pv garage](https://cdn.discordapp.com/attachments/1054807586194595931/1094928814599045120/FiveM_b2699_GTAProcess_bmSIG3aIZu.jpg)

Job Vehicle Garage / Purchasing Spots
![jv garage](https://cdn.discordapp.com/attachments/1054807586194595931/1094929023957749791/FiveM_b2699_GTAProcess_XpN8fhsGIy.jpg)

Phoenix One Spawner (Or whatever the fire department call their choppers xD)
![helipad](https://cdn.discordapp.com/attachments/1054807586194595931/1094928692557381693/FiveM_b2699_GTAProcess_oiYgZh8nWQ.jpg)

Controller to start the firepit: (If it's something that can be done. Useful for training):
![Firepit](https://cdn.discordapp.com/attachments/1054807586194595931/1094935425157705738/FiveM_b2699_GTAProcess_sRFZdUUFhR.jpg)

### Reason

Add functionality to the new Fire Station

**Comment by coalaura** [comment]
- On/Off Duty Spot
- Lockers
- Clothing Circle
- Job Vehicle Garage
- Phoenix One Spawner
- Locks for the doors
All added

- Fly Out Spot
- Personal Vehicle Garage
Don't think those are needed

- Controller to start the firepit
I don't quite think this would work properly the way i am understanding it. The will just spread out of the containment area
![yes](https://i.shrt.day/WOtOLaFe21.png)
