### ISSUE TITLE
Suggestion - Prison yard Locks

### ISSUE THREAD

**Issue by superiorchicken007** [InZidiuZ/op-framework-issue-tracker#2756]
### Assurance

I have read the `README.md`

### Summary

Ever since the recent map push with the fences in the Prison yard being moved the gates leading to the steps and onto the roof no longer have locks and anyone can go up there at any time.

### Reason

The locks should come back this way prisoners can not just run up onto the roof at any time.  The locks used to be there but are no longer.

**Comment by coalaura** [comment]
could you provide some screenshots so we know which ones exactly you mean?

**Comment by superiorchicken007** [comment]
https://media.discordapp.net/attachments/997655672336429056/1095000939888394361/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000940374921226/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000940890837153/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000941306069124/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000941742280745/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000942233010267/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000942761480232/image.png?width=1042&height=586
https://media.discordapp.net/attachments/997655672336429056/1095000943126401165/image.png?width=1042&height=586

**Comment by superiorchicken007** [comment]
These are the coordinates of the gates

vector4(1747.86, 2562.29, 45.57, 91.58)
vector4(1713.55, 2564.53, 45.56, 78.03)
vector4(1684.93, 2564.29, 45.56, 76.16)
vector4(1617.34, 2574.87, 45.56, 149.0)
vector4(1623.74, 2526.84, 45.56, 111.19)
vector4(1665.09, 2493.48, 45.56, 175.43)
vector4(1714.18, 2488.82, 45.56, 139.44)
vector4(1721.35, 2510.52, 45.56, 233.29)

**Comment by coalaura** [comment]
all done
