### ISSUE TITLE
Suggestion - Superadmin Command for Events

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2757]
### Assurance

I have read the `README.md`

### Summary

With Legacy International hosting various events (usually what I focus on is gang events) it popped into my head when me/Sia hosted an event.

I don't know how possible this would be but ideally when we host events staff usually has to /revive people to have them reset. This usually happens because there is multiple rounds/it ended too quickly so we decided to do a 2nd round. 

What I am suggesting/asking is for the ability to do a command that allows individuals to go into a state where you can "press e to revive". In terms of actual roleplay I obviously wouldn't like this, but this is for special occasions during events where EMS RP/PD RP is typically not involved.

It would sort of be like below
/Downed_Revive (Area Size) (Time) 

Like the /wipe command, it would show a circle highlighting the area and the time would be in minutes. Time would mainly be for so it doesn't linger after the event. If the area does exist after the event, a superadmin can do the following
/Downed_Revive 0 0 Disable 
Disables any "revive" circle. 

If this does get implemented it would have to be taken note you cant "hold e to revive" a person in a vehicle, they must be drug out of the car in a safe spot.
If a person is revived, they are revived with 50 health and no body armor.
When they are in this downed state, the player could either do the same emote as regularly down or a /e crawl to show a difference. 
It also takes 5-10 seconds to "revive" someone
Maybe as well hold F to "execute" maybe to "fully down" someone.

### Reason

- This would make gang events a lot more fluid/enjoyable so staff doesn't have to manually /revive
- Would make gun fights last longer.
- Does not cuck EMS RP since it's a superadmin command (meaning only trusted people can use it) and they would know when it's appropriate. 
- With this implemented it could be possible to implement it into battle royale as well. 
- I guess more "immersive" to press e to revive instead of staff doing /revive
- Overall isn't anything super important/needed, it's something that popped into my head that could add another layer of fun into gang events.

Also please give me feedback as well on this idea

**Comment by coalaura** [comment]
bruh

**Comment by ImArteria** [comment]
Fuck Essay tag, all my homies HATE essay tag

**Comment by coalaura** [comment]
honestly think its faster and easier to just revive people using /revive or /revive_range
