### ISSUE TITLE
Bug report - Nos still has a lot of issues 

### ISSUE THREAD

**Issue by BigPimpinBaby** [InZidiuZ/op-framework-issue-tracker#2758]
### Assurance

I have read the `README.md`

### Reporter

Wes Montayo #4227

### Summary

I'd really like to have a 1 on 1 discussion about the viability of Nos, because it's really not in a good place currently. Heres some issues I'm experiencing

- Sometimes nos is a toggle with shift, sometimes it’s not. 50/50 that you’ll have to tap shift again to stop draining nos
- Purging is random and doesn’t work with shift X, will randomly engage as well
- Temperature gauge sometimes isn’t accurate. Will stay at the same temp for several seconds then suddenly jump 20 degrees very quickly 
- Damage to engine seems inconsistent because of the inconsistency in the temperature garage 
- Nos animation will stop but nos will keep draining which gets very confusing 
- Need to do over 100 to get below 70c so it’s not particularly viable in the city, one sharp turn and you go up 10 degrees so it’s very difficult to lower temps unless you’re on a straight 
- Had to do 190 for 15 seconds just to get it from 90c-70c
- Cannot garage car with nos or you will lose it
- Did a test in the GTR and kept temps under 90c for an entire bottle, and took 30% damage. Same test in a demon and it took virtually no damage
- Essentially everything about nos is inconsistent and difficult, it's a lot of management and risk for very small results 

And in terms of balancing, Nos is a 6 step process to create from gathering materials to the finished bottle, it's extremely time consuming. We have to sell bottles for about 1500 to essentially break even with a small profit. I'd very very much like this RP for our group which I could discuss further. But genuinely it needs to be looked at again 

### Steps to Reproduce

To reproduce it I recommend trying a few different cars as I noticed different behavior, although I'm not sure if that was related or not

Mostly I just tested nos on the highway because its easy to get temperatures down that way. But if you test nos in the city with lots of turns, you can see how difficult it is to lower temps. 

### Expected Behavior

I assume L Shift isnt supposed to be a toggle as it never was before, it was a hold and release use. Temperature gauge is wonky and should be consistent when using nos. Purging apparently is L Shift + X but that only works about half the time for me 

### Actual Results

Mostly what I've mentioned already. Nos continues to drain after you release L shift, purging works with L shift + X sometimes, but also will purge with just L shift randomly. Also you have to press X first then shift, which makes sense but is a little confusing. Also I've had Kathryn Archie and several others in city reproduce these results so I dont think its only on my end. 

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
#2851
