### ISSUE TITLE
Suggestion :Fingerprints.

### ISSUE THREAD

**Issue by Vexzarkov** [InZidiuZ/op-framework-issue-tracker#276]
**Name:**
VexZarkov#0359

**Summary:**
my idea is to have a fingerprint scanner for PD it would allow us to deal with suspects who refuse to get an ID
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would Aid in RP with Police as well as could be used later on for investigation related framework (Leaving Prints at the bank, guns, evidence crims could counter that with Gloves or Burning off their prints if they don't want to be ID'ed) The scanner can be helpful in detecting if the ID is fake in processing ect.

**Comment by InZidiuZ** [comment]
Hey,

DNA, fingerprints, GSR testing, weapon tracing and bullet casings dropping on the ground when shooting is already planned, check the [Trello](https://trello.com/c/T8Ve9gzv/278-police) for more information.

**InZidiuZ**
*OP-FW Developer*
