### ISSUE TITLE
Suggestion - Local Car Upgrade Kit

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2760]
### Assurance

I have read the `README.md`

### Summary

This would be a random drop that would come from the life invader jobs such as trucking, or something that could be found inside of vehicles whenever they are chopped. It would be a rare drop chance. Around the same as the tuner chip. The upgrade kits could look similar to the advanced repair kit. The purpose of the upgrade kit would be as follows;

- A 1-2 time use upgrade for local vehicles only. 
- It would fully upgrade a local car to EMS 4 along with other engine upgrades. 
- The upgrade kit would break after 1-2 uses. 
- This would only work on none personally owned vehicles

Could look something like this as an item

![image](https://user-images.githubusercontent.com/52269307/232157796-b8c3d1c6-aff4-44be-98c6-bb6d0b6b6304.png)

### Reason

Adds another unique drop to chop shop or some of the possible life invader jobs. Could be a new craftable item.

This might increase exploration into more of the local vehicles which could influence purchases at PDM.

We might see the use of more local vehicles during robberies or during common crimes inside the server. Not the personal car for everything. 

This wouldn't be able to be used on PDM test drives.

**Comment by coalaura** [comment]
It seems a bit weird for it not to be working on personal cars but every other car, no?

**Comment by coalaura** [comment]
Also seems VERY op ngl

**Comment by ImArteria** [comment]
Don't really see a use for it, why would people use this versus their personal cars.
I can already see things such as applying it before a vin scratch to keep it on a personal car, on the other hand though maybe it would encourage people to use them during boosts to make chases a bit more fair.

I think the idea is cool but not practical as much as I'd want people to explore more vehicles.

**Comment by ravicant** [comment]
but i think we can make it balance like one kit only upgrade on thing which u can decide what the more upgrade you want to do the more kit you need which is expensive or i would say not make it cartable just spawn in chop shop like you are taking other chopped vehicle upgrade

**Comment by coalaura** [comment]
I get that but when we add a new feature it has to be balanced and work somewhat within RP

**Comment by ImArteria** [comment]
Honestly I feel like a better idea would just be make EDM car upgrades more expensive than PDM. Since the "car is imported" surely parts for it would be imported too and cost more. Would maybe encourage people to try out cheaper cars, or spend a shit ton on EDM

**Comment by vol5** [comment]
@coalaura What are the main concerns on how it would be imbalanced with how @Skai97  suggested it?

Thoughts on lowering it to 1 time use and require a mechanic to put it on the car?

**Comment by coalaura** [comment]
> @coalaura What are the main concerns on how it would be imbalanced with how @Skai97 suggested it?
> 
> Thoughts on lowering it to 1 time use and require a mechanic to put it on the car?

![bruh](https://i.shrt.day/KoGoNoce20.png)

**Comment by Skai97** [comment]
Well the idea is to encourage less use of personal vehicles during crime or even to encourage the use of fake plates. The issue with arteria said is the price of a car or its upgrades dont matter. If its good people will buy it. Look at the mustang and the embalance it caused the last 2 months. Like as crim the roleplay in terms of vehicle usage is very lazy. No harm but as a certified cop main. Pd cars are entirely overpowered atm. So level 2 upgrades would make no difference

**Comment by coalaura** [comment]
Also, no PD cars are not overpowered. They are designed to keep up with fast cars, so people can't just buy the fastest car and guarantee a getaway

**Comment by ImArteria** [comment]
> Well the idea is to encourage less use of personal vehicles during crime or even to encourage the use of fake plates. The issue with arteria said is the price of a car or its upgrades dont matter. If its good people will buy it. Look at the mustang and the embalance it caused the last 2 months. Like as crim the roleplay in terms of vehicle usage is very lazy. No harm but as a certified cop main. Pd cars are entirely overpowered atm. So level 2 upgrades would make no difference

As much as I'd love to say, I want people to use Local/PDM cars more and than balance PD cars to accommodate that. Issue is we dont have an "In RP" Way to deal with people not using fake plates. Realistically DOJ could fix that part.

**Comment by Skai97** [comment]
Pd cars are most definitely very strong. The crown Vic is better than 2 of speed units. They are simple to drive and reward good drivers way to much. If I crash out I can be back on someone in seconds because my car will double clutch from 30 to 100mph+. The meta of "broken" cars has been created because of how good pd cars are. You hear so often I only use this car because nothing else is better than pd cars etc. Yes sometimes cops will lose people in any vehicle but I'm talking about skillful driving. Not jumps or sending it till locals take out pd. 

I like the random vehicle upgrade idea however the kit would be a one use item to help people escape from x crime. The reason it wouldn't be used on personal vehicles is because it might discourage people upgrading those cars. I buy a sultan from pdm. Pull from my garage and pit the upgrade kit on it. At least if its a local vehicle. I'll have to look for it. Steal it or hotwire It

**Comment by MetaHatter** [comment]
- Fake plate use will be unaffected by this items existence.
- I am pretty sure we don't want local cars used for jobs. The car economy is a primary economic driver.
- There are better solutions for PDM - High cost, upgraded, time-limited (3-5 minutes) test drives for example.

I can see this item as having a use for a on-off deal vehicle or for boosting and that's about it.  In which case, the portability and ability to apply a slight upgrade discreetly might be worth the cost.

Outside of this it seems largely unneeded. 
(the rest of the convo is off topic so I'm not going there)

**Comment by coalaura** [comment]
> The meta of "broken" cars has been created because of how good pd cars are.

Not really. I can, 1000000% guarantee you that if PD would use all pantos people would still use broken cars. The meta of broken cars is created because people want to get away and get a lot of pixel money. "I'm just robbing a bank for the roleplay" no you're not. Maybe like .1% of our community but the majority wants to get away quick and get easy money. No matter how much you nerf the PD cars, people WILL use the best cars available so they can make sure they get away. It removes the risk that is designed to be there.

Again, like i said: PD cars are **designed to be fast**. They are meant to be fast. We have to balance them with the top end cars in mind cause thats what people WILL use. "If PD cars weren't so fast crims wouldn't use fast cars" <- this is stupid. The majority of crims WILL use the fastest car available, there is no sweet-talking it, open your eyes, please.

Getaways are supposed to be hard, no matter what car you use. Optimally they would obviously be equally hard no matter the car but that would require all cars to perform the same, which yeah doesn't work...

**Comment by Skai97** [comment]
I don't see how having a kit that max's out a local vehicle until tsunami or its gone is OP considering everybody hits banks and j-stores will fully maxed mustangs anyway. IC, we as PD have to jump through many hoops to get warrants out and what not and DOJ does nothing to punish that behaviour. 

using personal vehicles without a fake plate is normalised on the server because thats how its been for so long. If people abuse broken cars. Those cars should get nerfed but instead pd cars get buffed to keep up with the new broken cars. It's a vicious cycle. 

It's an item that might break the "meta" or benefit people that don't wanna use personal vehicles. Right now there is no other option. Local cars break in 1-2 crashes.

**Comment by Skai97** [comment]
Just promoting for some kind of change to happen

**Comment by coalaura** [comment]
I've implemented the random NPC vehicle upgrades, will be live with the next update. Like i said this item will not work. I've given my reasoning. In addition we are working on a better balancing system with pd cars
