### ISSUE TITLE
Suggestion - Weazel News Magazine as a Collectible Item in Grocery Stores

### ISSUE THREAD

**Issue by roraraptor** [InZidiuZ/op-framework-issue-tracker#2761]
### Assurance

I have read the `README.md`

### Summary

As part of the new Weazel News team on Legacy International, I have been designing a magazine to be released as a PDF. Someone suggested that it would be cool to buy the magazine as an in-game item, like the 945 card packs.

I suggest including the magazine in grocery stores as something people can buy, and replacing the magazines in the store once new releases are published.

However, I realize this would be specific to Legacy International at this time, so if it isn't possible to only add the magazine in Legacy International's grocery stores, I suggest still that it could be added in a similar fashion to the card packs, so Weazel News could distribute the magazines themselves as an alternative.

### Reason

The reporter job at Life Invader has offered very little to the city or its citizens in Legacy International so far, with some notable exceptions. This magazine is an attempt to build Weazel News' credibility and make the reporter job more attractive.

The magazine offers ad space, to add more interaction with businesses (ad design, production, photo shoots, etc.). I believe an in-game item would make such ad space much more valuable, especially considering the magazines would be time-limited collectible items.

Additionally, it's another thing that increases immersion, giving citizens another reason to stop by the grocery store and to interact with one another in-character.

Also, it's fun! It would make it feel worthwhile to put in the time and effort to write articles and produce new content on the regular.

**Comment by roraraptor** [comment]
An example of the type of work put into creating the magazine itself:
![affinity_publisher_weazel_news](https://user-images.githubusercontent.com/17354145/232280867-b89a409e-64df-460c-80a6-47a3946962d6.png)

<img width="540" alt="Weazel News Magazine Ad" src="https://user-images.githubusercontent.com/17354145/232280918-3951d8c3-bc2c-404e-87e6-9f9081ddf88c.png">

**Comment by InZidiuZ** [comment]
This has now been implemented. [Here's a showcase of the feature in a near complete state](https://inzidiuz.com/yzucxG.mp4).
