### ISSUE TITLE
Suggestion - Remove BCFD from EMS counter

### ISSUE THREAD

**Issue by TheOneLizard** [InZidiuZ/op-framework-issue-tracker#2762]
### Assurance

I have read the `README.md`

### Summary

BCFD, when on duty, currently counts towards the EMS counter.

This should not be the case, as they now operate on different terms.

Hence, BCFD should be removed from the EMS counter.

### Reason

People have been calling EMS as it shows that there is EMS on duty. However, it was BCFD that did not respond, and people will get annoyed with that. 
Having people call EMS is not an easy task in the first place, and if people cannot differentiate between BCFD and EMS, they will think that EMS simply doesn't respond.
Yes, if BCFD is on training tracker, that wouldn't be an issue. But this needs to be separated for future purposes anyway, and would be an instant QOL improvement.

**Comment by coalaura** [comment]
No
BCFD is supposed to work together with EMS enhancing roleplay by providing additional help with search and rescue. It is a department WITHIN the Medical job. Its not its own job since its not supposed to be. I am in no way involved in any of the drama between EMS and the fire dep. that is going on on the international server but i will not fundamentally change the job

**Comment by coalaura** [comment]
BCFD is supposed to be like BCSO within SASP. If BCSO would ask for their job to be completely seperate from Law enforcement i would decline it for the same reason. If you make decisions against the fundamental way the job works then its for you to figure out how to make it work, i'm not going to rip apart a job and its usage.

**Comment by coalaura** [comment]
> ### Assurance
> 
> I have read the `README.md`
> 
> ### Summary
> 
> BCFD, when on duty, currently counts towards the EMS counter.
> 
> 
> 
> This should not be the case, as they now operate on different terms.
> 
> 
> 
> Hence, BCFD should be removed from the EMS counter.
> 
> ### Reason
> 
> People have been calling EMS as it shows that there is EMS on duty. However, it was BCFD that did not respond, and people will get annoyed with that. 
> 
> Having people call EMS is not an easy task in the first place, and if people cannot differentiate between BCFD and EMS, they will think that EMS simply doesn't respond.
> 
> Yes, if BCFD is on training tracker, that wouldn't be an issue. But this needs to be separated for future purposes anyway, and would be an instant QOL improvement.

i know what you meant, what i'm saying is BCFD are supposed to be EMS with extra training, basically being part of a division. So no, they are supposed to count towards ems on duty
