### ISSUE TITLE
Suggestion - Weazel News Technical

### ISSUE THREAD

**Issue by James-Miclane** [InZidiuZ/op-framework-issue-tracker#2763]
### Assurance

I have read the `README.md`

### Summary

Weazel News does not have an onsite parking garage like most work areas do and was hoping to see I that would be a possibility or even implemented. I understand it is not as easy as saying he does this but I appreciate you at least looking at this.
Secondly, the Weazel News vans pick up on radio chatter and are able to tell when a car is robbed, shots are fired, or a bank is robbed. The Weazel news helicopters however are not equipped with such technology. I was hoping to see if we could put that ability on the helicopters. If it's not possible I at least appreciate you reading this.

### Reason

This would allow Weazel News employees to store their vehicles on-site without walking to some other part of the city where there is a garage.
The helicopters having radios would help us to better report on active situations while also giving us an aerial view of the situation.

**Comment by coalaura** [comment]
This should work now
