### ISSUE TITLE
Bug report - Weazel News Vans Spawn Incorrectly

### ISSUE THREAD

**Issue by James-Miclane** [InZidiuZ/op-framework-issue-tracker#2764]
### Assurance

I have read the `README.md`

### Reporter

SCP_079#8884

### Summary

Often times when a Weazel News van is spawned in from our back lot the van doesn't register us as owners so we end up having to try and hot wire the car to hope to move it. However, trying to hot wire the van is a problem as it can fail and then that's a whole walk back threw. If you would like to reach me by Email I can hopefully display my eyes and show you what I'm talking about. At the very least thank you for looking at this.

### Steps to Reproduce

In order to have this issue persist all that would have to be done is ignore this filed complaint I guess.

### Expected Behavior

I'm hoping to at best get an email saying it should no longer be a problem, at worst an email saying that nothing can be done as it may just be a problem with the physical city and something the DEV team can't fix.

### Actual Results

The vans tend to lock us out causing us to have to hotwire the van as it won't register us as owning it.

### Screenshots/Videos

Getting that probably would have been a good idea before starting this proses. If I receive an email I can display my eyes and show you what I'm talking about.

### Game Resolution

High quality

### Player Data

Im the director of Weazel News holding a state contract with Governor Ruby. I have a type-H pilot's license. I have the reporter job from Life Invaders.  My phone number is 971-5336 and my CID is 113948.

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
I'll take a look at it. Btw you dont have to fill this form out in character, this is ooc.

"Steps to Reproduce" means what exactly do i need to do to cause the bug to happen, so i can test it properly

"Expected Behavior" means what is supposed to happen but doesn't, not what you expect me to do once the bug is fixed xD

"Game Resolution" means the resolution of your screen in pixels (for example 1920 by 1080)

**Comment by coalaura** [comment]
This should be fixed now
