### ISSUE TITLE
Suggestion - Lean

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2766]
### Assurance

I have read the `README.md`

### Summary

Codeine, accessible in the medicine cabinet at franklin's aunties house. Heals by itself but gives stress. Mixes with green apple soda at the kitchen sink in the same house to make lean. Gives rainbow euphoric effect and reduces stress but does no healing. Possibly sellable but not important. Illegal unless mixed with green apple soda.

### Reason

This is a feature that could help newer people in the city have everyday encounters with friends. Codeine has possible criminal economy boost if the mixed lean is sellable to locals.

**Comment by coalaura** [comment]
added
