### ISSUE TITLE
Suggestion - Evidence Heist

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2767]
### Assurance

I have read the `README.md`

### Summary

Acquirable from an armored truck: GPS intel device for a security contract of a shipment that will arrive in a location where FIB will be handing off the contents of the evidence lockers to local guards. GPS will ping the intel device when FIB are in position.

### Reason

This would be a good RP use of the evidence lockers contents.

**Comment by coalaura** [comment]
This seems like something that can be **entirely** done in roleplay?

**Comment by oceandabs** [comment]
yeah, and help PD train in locations

**Comment by coalaura** [comment]
> yeah, and help PD train in locations

yeah what i meant with my comment is that there id no development needed. This can be entirely done in roleplay and does not need anything done from a development standpoint
