### ISSUE TITLE
Suggestion - Meth Pipe

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2768]
### Assurance

I have read the `README.md`

### Summary

A dab rig at the dispensary for sale. The ability to process weed into shatter or wax that can be used in the dab rig to de stress. A meth pipe to smoke the meth which only provides a rainbow euphoric effect and hurts you slightly.

### Reason

These are perfect tools for quality roleplaying that would also help the economy.

**Comment by ImArteria** [comment]
I like the Meth Pipe idea. Don't think the others are needed.

**Comment by oceandabs** [comment]
Make meth pipes randomly drop with cooking a batch.
