### ISSUE TITLE
Suggestion - Hospital Check In - Walk style

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2769]
### Assurance

I have read the `README.md`

### Summary

The check-in system was changed to reset your walk style once treated by Nancy. This should be changed so its only set to (injured) if you have the following types of injury not every time you check in.

> serious injury or downed

### Reason

- No need for walk style to reset when you just check in with no injury

**Comment by King2704** [comment]
yes pls, its very annoying to change the walking style if you checkin with 70% health

**Comment by coalaura** [comment]
no
