### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by staxlmao** [InZidiuZ/op-framework-issue-tracker#2774]
### Assurance

I have read the `README.md`

### Summary

Make it so we don't have to get out and type "/flip" to flip our car. Make it so we can just flip it by turning wheels like it is in GTA.

### Reason

Imo, this is way better because it makes crim RP better since if we turtle, we can still have a chance of getting away from the police and etc. I also think it is not as realistic when you just get out of the car, and use "superpowers" such as "/flip" to flip the vehicle.

**Comment by staxlmao** [comment]
how do i delete this sorry I didnt see taht yall closed my old suggestion

**Comment by coalaura** [comment]
bruh moment
