### ISSUE TITLE
Suggestion - Car radio

### ISSUE THREAD

**Issue by staxlmao** [InZidiuZ/op-framework-issue-tracker#2776]
### Assurance

I have read the `README.md`

### Summary

Car radio

### Reason

Add car radio where you can save playlists/play music/and change volume while driving without having to put a boombox in your trunk where you still have to manually put in all your songs and you have to get out of the car to change the volume everytime. Imo this is just easier lol.

**Comment by TacticalTyl3r** [comment]
This sounds just like a boombox that you place in your trunk. How would this be easier?

**Comment by staxlmao** [comment]
> 

Lemme reword it

**Comment by coalaura** [comment]
I don't see a reason to add an extra thing when like said, you can just put a boombox in your trunk
