### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by staxlmao** [InZidiuZ/op-framework-issue-tracker#2777]
### Assurance

I have read the `README.md`

### Reporter

stax#3636

### Summary

Idk if this is something that the car is supposed to have, but the EDM Audi RS6 gets dirty almost right after a wash.

### Steps to Reproduce

Idk

### Expected Behavior

For the car to not get dirty as quick. Possibly lower the dirtiness? idk

### Actual Results

Idk

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/131978859/235252949-f98dd08e-95c3-4d90-a285-79eeb26e0d9a.png)

### Game Resolution

1920x1080

### Player Data

![image](https://user-images.githubusercontent.com/131978859/235253891-9c8efc6f-ca5b-4bed-9c1e-af68fc074a3f.png)

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
The framework already decreases how quickly vehicles gets dirty. If it's a problem with this specific add-on model, then it should be reported [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
