### ISSUE TITLE
Suggestion - Gun Crafting

### ISSUE THREAD

**Issue by TheCuppcake** [InZidiuZ/op-framework-issue-tracker#2779]
### Assurance

I have read the `README.md`

### Summary

New whitelisted process - Gun Crafting

Have the group that controls this process have to intercept shipments of gun parts that they have to activate the tracker for by hacking at a set location (to alert FIB) The group must then intercept the shipment, kill the guards and heist the truck before the cops arrive. Once they have taken the truck, they must take it back to a warehouse and scrap the truck where they then get regular chop parts and then all of the contents from the back of the truck. 

Realistically the truck would be full so i think this would need to be a process that has a limit on the time between runs, maybe 2-3 hours and also there would need to be cops on duty. 

This group would then need to go to a secondary location with the parts to then "craft" the guns from the parts that they got (which would be random) 

I would just make sure if u control one gun process, you wouldnt be able to touch the other just so it wouldnt be easy to grind getting guns

### Reason

Currently we have one gun computer and cargo and although those both provide alot of guns into the city, I think creating another process to go alongside the current one could enhance RP in a few ways. 

1. It will force the gun dealers to need to be competitive in prices 
2. It will create a new and exciting investigation for FIB and for cops
3. It will be harder to "hold down" because other crims could come and take the shipment from you if they also have the computer access codes
4. More chances for groups to do things besides shoot cops or eachother
5. Less grinding on the current gun dealers because being one of the primary sources, they have to run the process alot and it can become exhausting.

I personally would love to see more WL processes or even non whitelist (like drugs) come into the city where people can actually immerse themselves into more things and have less grind mentality when it comes to just making money by mining or hunting. Also giving people more shit to do will stop the bored beef that we often see in the server, imo.

**Comment by coalaura** [comment]
I don't necessarily dislike the idea, but I don't want to make importing guns even harder. The gun running process has been working decently well since it was reworked so i'm not too sure about big changes to it

**Comment by oceandabs** [comment]
Gun crafting could be a non-whitelisted process and only certain guns could be made by crafting.

**Comment by coalaura** [comment]
whitelisting or not is not a dev issue, that's decided by the server managers however they want to shape their rules

**Comment by TheCuppcake** [comment]
So i didnt want to rework our current gun running system with this suggestion. I wanted it to act is like a second gun computer so make it even EASIER for people to get guns in the city and add more rp.

**Comment by coalaura** [comment]
wouldn't that however take away RP from the group that runs the guns? Also i believe some subdivisions have staff run the computer so idk how much that would fuck with them

**Comment by coalaura** [comment]
this was done
