### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Stradivarius69** [InZidiuZ/op-framework-issue-tracker#278]
**Name:**
$tradivarius#3034

**Summary:**
Flashbang, Smoke grenade and other stuff.

**Suggestion:**
A new update which came recently, about the bank robbing method. What about adding a smoke grenade or a flash bang for the police. So, they can use it to push inside the bank without any hesitation. 

Also, what about adding some smg's or rifle for the people around the city without pistol and shotgun only?

These are my few opinions to be added in the city soon or not. 

Thanks

**Comment by InZidiuZ** [comment]
Hey,

Heavy weapons & throwables have already been converted to inventory items. But, there hasn't been added any methods to get them yet. Keep in mind we've been on this framework for about a month now, and are slowly adding in features. The plan is to eventually add various interactive methods of getting these guns, but all in good time. :)

**InZidiuZ**
*OP-FW Developer*
