### ISSUE TITLE
Suggestion - EDM Sellback (w/Depreciation)

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2780]
### Assurance

I have read the `README.md`

### Summary

Add the ability, in the EDM garage, to sell the vehicle back, if you own it, to EDM for 25% of the purchase price. 
i.e. receive $50k for a $200k car, $25k for a $100k car, etc

Buyback percentage should be config value so regions can adjust.

### Reason

- Increase the value of buying a train ticket by increasing flexibility and perceived value of an EDM purchase.
- Incentivizes keeping tickets for more than a month because they can trade in to help afford a "better" car.
- Reduces risk of test drive free purchase by allowing a "bad" choice to not be a total loss.
- Increase rarity, and by extension value, of EDM cars in the city by decreasing the amount in garages.
- Removes assets contributing to an individual's current net worth to incentivize further progression.
- Allow people with buyer's remorse to recoup some of their money.
- Provide a way to get a quick influx of cash, but at a significant cost.
- Give people an option to get rid of cars they simply don't want any more.

**Comment by vol5** [comment]
This a great idea that strengthens the value of an edm ticket purchase and would benefit players across the board.. Great suggestion @MetaHatter

**Comment by DARCHgit** [comment]
I've been hope this get implemented for a while. I'm also very on board with this idea. Personally I think 25% return on an EDM vehicle is a bit low, would love to see 50% however any percentage would be very beneficial for city.

**Comment by coalaura** [comment]
Something like this has been done
