### ISSUE TITLE
Gems (Mining)

### ISSUE THREAD

**Issue by MrMeatyy** [InZidiuZ/op-framework-issue-tracker#2781]
### Assurance

I have read the `README.md`

### Summary

I feel like mining for gems can be very competitive 95% of the time and especially with new players constantly joining, its hard for us to make money with all the rich people driving up and down and hogging all the gems. It would be nice if the gems worked like the old weed system, with everyone having their own nodes and everyone will have a chance to make some money at the end of the day, or maybe creating more places for people to go mining. 

### Reason

I've been mining for the past 2 weeks and out of those 2 weeks I had to sit out for 2 days because people constantly hogging and standing around with multiple people with guns. I feel like the old weed system where people get their own nodes that spawn in would benefit the new players that come in and want to make money without sitting there for hours waiting for people to leave the area. I can understand that doing something like this would affect the economy but also adding more places for people to go mining might balance it out a little bit.

**Comment by coalaura** [comment]
No, mining is already very overpowered as it is. There is also 11 different mining spots all across the map, just people haven't tried to go look for most of them
