### ISSUE TITLE
Bug report - Gems are inside Other boulders/rocks

### ISSUE THREAD

**Issue by RilloX01** [InZidiuZ/op-framework-issue-tracker#2782]
### Assurance

I have read the `README.md`

### Reporter

RailedFromBehind#0001

### Summary

Gemstone spawns are a bit scuffy, when scanning the area of gems you can see gems are inside bigger rocks/boulders which you just cannot get/reach. 

### Steps to Reproduce

Go to gem mining site.
scan for gems, and a good percentage of gems are inside rocks.

### Expected Behavior

Gems spawn on top or around the boulders, not underneath/inside

### Actual Results

Gems spawn inside boulders/rocks that are not reachable

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/72838717/236632314-bab80bab-fff3-42d7-89a2-8080d0def4c3.png)

### Game Resolution

1920x1080

### Player Data

![image](https://user-images.githubusercontent.com/72838717/236632395-4e364585-3e3c-41a3-9587-054bedf8ceb7.png)

### Server

International (c3s1.op-framework.com)

**Comment by MrMeatyy** [comment]
Would be nice to see something happen for this.

**Comment by coalaura** [comment]
There is nothing i can do about this other than remove all other spawn areas that have big rocks. Gems respawn after about 30-40 minutes if they are not being mined. If there is a gem in a rock then just ignore it, it'll respawn not too far later

**Comment by RilloX01** [comment]
The Z axis cant be changed????

**Comment by coalaura** [comment]
Its not super easy to nicely detect the surface of the rock perfectly while keeping it performant. To answer your question, yes the z axis can be changed, however you need to calculate the surface height of the rock and its surface normal to properly position the gem on its surface.

**Comment by TheOneLizard** [comment]
Wouldn't it be possible to circumvent the issue by not placing the gems on the rocks, but on the ground surface between the rocks?
The area where they spawn wouldn't change, just the specific locations. Never seen a gem in the ground at the quarry or the mine.
Just a thought

**Comment by RilloX01** [comment]
The problem is that at certain places, sometimes you can only get to 1 gem to have to wait however long for them to respawn. ofc I had some suspicion that they are only appearing under ground because math.random is being used in some capacity. im just giving some insight into why its a pain in the backside, and some things can definitely be done about it. If it be getting actual bang on coords for gems to spawn, spawning them in-between the rocks. or moving the gem location to somewhere else?

**Comment by coalaura** [comment]
> Wouldn't it be possible to circumvent the issue by not placing the gems on the rocks, but on the ground surface between the rocks?
> 
> The area where they spawn wouldn't change, just the specific locations. Never seen a gem in the ground at the quarry or the mine.
> 
> Just a thought

Be my guest if you want to manually define the locations between each rock

**Comment by RilloX01** [comment]
> > Wouldn't it be possible to circumvent the issue by not placing the gems on the rocks, but on the ground surface between the rocks?
> > The area where they spawn wouldn't change, just the specific locations. Never seen a gem in the ground at the quarry or the mine.
> > Just a thought
> 
> Be my guest if you want to manually define the locations between each rock

I would happily do this.

**Comment by coalaura** [comment]
> I would happily do this.

I don't think you understand the sheer size of the area needing coverage. I was mainly saying it more as a joke. I've played around with it trying to come up with decent ways to position the rocks and i did not end up with a decent solution. I decided it is not worth going after so i wont

**Comment by RilloX01** [comment]
> > I would happily do this.
> 
> I don't think you understand the sheer size of the area needing coverage. I was mainly saying it more as a joke. I've played around with it trying to come up with decent ways to position the rocks and i did not end up with a decent solution. I decided it is not worth going after so i wont

No like seriously, tell me where and how many gem positions you need at each location and ill do it.

**Comment by MetaHatter** [comment]
My perspective?

There are simply some gems too deep in ferrous metals for them to be retrievable by a cheap, easily-broken hand drill bought from the megamall.

AKA - IMHO Mining should be a side activity for occasional good money, not a steady, grindable income that replaces working a job in RP.  This "bug" actually seems like a feature to me...

**Comment by RilloX01** [comment]
> 

I can understand this, but im simply pointing out that there are gems under the rocks which are unreachable. if they get removed resulting is less gems in the area, so be it, but gemstone mining is practically everyone's job. in my eyes its setup that way.
