### ISSUE TITLE
Suggestion - /jail HUT command

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2783]
### Assurance

I have read the `README.md`

### Summary

Currently the /jail script does not allow people to be jailed for indefinite amount of time. 

I am suggesting this command, /jail HUT to allow someone to be jailed UNTIL they are /unjail

This could not only work for international /jail HUT where people are held until trial, but also if servers were to allow "lifer" characters. /Jail HUT could keep them in the prison as well.

### Reason

So mfers can be good and I don't have to explain to everyone we HUT that they can't leave the prison in an OOC manner.

**Comment by TacticalTyl3r** [comment]
you could also do /jail 0 almost like the wipe command where it does everything! so make 0 be indef until unjailed.

**Comment by coalaura** [comment]
An indefinite jail command is not something i want to add

**Comment by ImArteria** [comment]
> An indefinite jail command is not something i want to add

Is there the possibility of increasing the maximum time than or something or potentially maybe explaining why an indefinite jail command would be better? While on that topic maybe a fax /fine increase too :sadangry:

**Comment by coalaura** [comment]
its a pretty damn powerful command, there is a reason we have the limits for /fine and /jail

**Comment by ImArteria** [comment]
> its a pretty damn powerful command, there is a reason we have the limits for /fine and /jail

I'm aware of that. It isn't something needed but when people are fined 100k from court dates, I have to /fine 5000 20 times. The /jail 0 or whatever would just be a quality of life so I don't have to have this entire OOC talk with people explaining how the server mechanics won't allow them to be HUT and instead they just "cant" leave the prison and etc. Some of my arrest warrants from raids have hit like 3000 months and etc. I agree it is powerful and I assume the hesitation is because of potential abuse. Really all I can say is a lot of things in PD can be abused and it's the reason it's a whitelisted job. Something like this would make things a bit more fluent in terms of FIB, DOC, and DOJ RP. 

Again it isn't 100% needed, it's something that I would assume is a quality of life addition

**Comment by ThisIsNotDex** [comment]
> its a pretty damn powerful command, there is a reason we have the limits for /fine and /jail

Could possibly have a confirmation command after doing /jailhut where you would have to type something out like /confirmsentence or along those lines. Or even just in general for times that are higher add a fail safe where people need to do a secondary command. 

Also preferably a command vs. like "press Y to confirm" because people may just press Y and not want to second guess themselves. A command would take someone longer and kinda make them look at the time. 

Possibly /confirmsentence (time)

**Comment by coalaura** [comment]
You can now do "/jail 123 hut" which will jail them for 999999 months (about 2 years) which should do the trick. The logs will show "HUT" for the amount of months and they can be unjailed like normal using /unjail.
