### ISSUE TITLE
Suggestion - Mobile app idea - for businesses

### ISSUE THREAD

**Issue by Tasteok** [InZidiuZ/op-framework-issue-tracker#2784]
### Assurance

I have read the `README.md`

### Summary

The suggestion is to add a mobile phone app in city with a directory to local businesses this directory can have phone numbers and gps coordinates if they have a storefront.

### Reason

it would be good for people unfamiliar with the city as well as new businesses without a storefront

**Comment by coalaura** [comment]
why would you need GPS coordinates when there is a blip on the map for each business?
why would you need a phone number directory when there is a hotline for all the big businesses?

![hmm](https://i.shrt.day/caSicumU36.png)
