### ISSUE TITLE
Suggestion - Idea for rings and descriptions on items

### ISSUE THREAD

**Issue by JennyLynn001** [InZidiuZ/op-framework-issue-tracker#2785]
### Assurance

I have read the `README.md`

### Summary

In the city, I have a business named Hidden Gems that deals with rings, gems, and a few other things as well. As of right now, you have the ability to make rings and engrave them but you cannot remove the gem or scratch off the engravings. I have been working in this business for the last two months and I have bought various amount of rings but I cannot resell most of them due to there being engraved names. 

That being said I would like to suggest that there can be a way to either remove the gems from rings or allow Hidden Gems to remove the engravings in order to resell. A lot of people within the city have come to me to purchase and sell me rings and it has been successful. People are even selling me gems instead of going to the locations to sell them, promoting better RP instead of selling to a wall. 

I am 100% committed to this business but the only way I am able to proceed with it and become more successful is if I have the ability to do these things maybe even have my own shop. 

At Hidden Gems, we also offer telegrams. We would like the ability to maybe change descriptions on bears and roses as well. At the moment when you purchase a bear or a rose, it says who it is from but it would be better if we could change the descriptions on these items as well to make things a little more interesting and interactive.

### Reason

Why I believe my suggestion would be a good change to the framework is because it would help promote better interactions and roleplay within the city. Allowing Hidden Gems to become official and allowing us to remove gems from rings, or change engravings and descriptions on items would allow for more job opportunities for people within the city as well. As of right now, people who have rings they no longer want cannot do anything with them which leaves them with no value. Once they had found out about Hidden Gems they have been excited to sell me the rings that have been collecting dust. The only downfall is there are names on some of the engravings which means I cannot resell them nor can anyone else and that is where Hidden Gems comes in. The reason why I cannot resell these rings is that no one wants a ring that has someone else's name on it, they want it to be special so, by allowing the scratching of engravements or the ability to remove the gem would help improve this issue. Right now gems go for x amount of money, but once turned into a ring it ends up priceless and this is what I am trying to prevent with Hidden Gems.

Aside from the gems and rings Hidden Gems also offers a telegram service. I have not been able to do many of these due to the fact that when someone comes to me wanting to surprise someone else without them knowing who it is from, the item whether it is a rose or a bear has my name on it. It would work out better if the business had the ability to change the descriptions to make the experience better. It would also make more interactions come to Hidden Gems rather than buying the items from a wall/door. Maybe even add more items to the shop like a box of chocolates, necklaces, bracelets, earrings, custom watches, etc...

Even if this is not done for my business, I still believe it would be a great change to the city and a lot of people would be happy.

**Comment by kaycorriher** [comment]
I think it would be cool to repurpose rings. A lot of the citys relationships turn over fairly quickly. If there was somewhere that they could be recycled, it would help with "pawn shop" style RP where people can trade these rings where usually they are worthless after the relationship is over.

**Comment by Epps30** [comment]
Would bring a lot of new rp to the city and the idea overall is perfect for the rings cause once you make them they are useless in a sense. Things like this can make the city fresh and possibly bring more jobs for people

**Comment by coalaura** [comment]
I'm not too big on makig the bears and roses have custom descriptions, i feel like it would be a lot more natural to write a note with the rose/bear and you can even sign it using /sign.

I've added a crafting spot where you can break down rings, but to add a bit of "loss" to it you wont be able to get the ring itself back just the gem.
