### ISSUE TITLE
Suggestion - Changes for businesses

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2786]
### Assurance

I have read the `README.md`

### Summary

Clock in / Clock out systems

-Clock in / clock out system that restricts employees to getting a payslip while clocked in.  If they leave the premises, they automatically get clocked out. 
-Payslips would need to be deposited into a bank.
-Having this set up, would make it so civilians can have multiple jobs which will help with places being open and give a more realistic approach to having jobs.
-Having a larger paycheck [$100-300 every 4-5 minutes like how we get paid now] will entice workers to actually work behind the counter and interact with people.
-TO AVOID “PAYCHECK FARMING” ONLY ALLOW A MAX OF 4 EMPLOYEES TO BE ABLE TO BE CLOCKED IN AT ONE TIME.

Business Accounts 

-Business owners should have access to a Business account that all sales are deposited into. This will give business owners great potential to actually RP as a business owner & give bonuses to their employees, making them want to come work. (Also if “Farmable Foods" gets implemented, the business account money would be used to purchase the foods to craft the items for the business).
-With this implementation, it’s important to make sure the registers at businesses are functional. Customers would pay with cash / credit to the register that would automatically be deposited into the business account. 

Farmable Foods

-Burger Shot has Potatoes and Lettuce.. Make it so instead of buying the ingredients from the fridge, we can find plants / seeds around the server & plant them outside and use the items to craft the food.
-There would be a fridge that we can store items in for employees to grab to craft the food with.
-This will get rid of the need to buy from a “fridge” for businesses so it doesn’t cost anything to the employees to make food for customers.
-Having “farmable foods” like the cocoa beans, could give potential to have a FARMING BUSINESS. Giving other business opportunities in the city. 
-Making it so people who hunt can interact with businesses to sell their meat as well, instead of selling it to a door. This increases interactions. 

Making people have to buy food from restaurants 

-Currently there are multiple ways to get food within the city. Stores, fruit stands, trash, z pills. Having this makes it so people do not even need to RP and interact.
-Fruit stands and Stores… Make it so they are “out of stock” of the food / fruit they provide when someone is clocked in on duty for any food restaurant. This implements something similar to what is already done for EMS / PD. 
-This is extremely important. People will argue that food places are not open, but if you ask people who are employed by a food business how often they work and why they don't work more, the answer would be “When I work nobody comes in and I make no money so I don’t want to sit behind a counter when I can go make money by grinding mining or hunting”

Upping the delivery payout & possibly limiting the amount of deliveries.

-I believe that upping the payout for deliveries is beneficial. I know that the hesitation lies on “people grinding” them. But in reality, anyone can grind anything. You have: Mining [20k+ a day], Hunting [20k+ a day], any life invader job.
-Upping the delivery payout will bring back the specialness that White Listed jobs used to have. A year ago, people would fight & die to have a WL job because of the special perks that they had. 
-Upping the deliveries will give managers + owners more RP. They would have to regulate how many [if there’s no set daily limit] their employees do.
-I also believe that Owners should be able to see who is doing deliveries.
-If there is a limit on deliveries because of a pay increase I believe that employees should be able to make a max of 30k-50k a day from deliveries split up into how ever many deliveries to help with minimum “grindy mentality” that is going on in the server as a whole right now.

Custom Foods / items in businesses

-Make it so each business can have custom icons that the owners can edit at their discretion. 
-Having this will make things really awesome and less restrictive and enhance the RP experiences. Businesses can run specials, and change the icons of their food / drink to match seasons.. And whatever specials they are running!

### Reason

It would enhance the RP all together in the server. It would give back the specialness that WHITELISTED Jobs had in the server. It would give both Owners and Employees a greater RP experience.. a more realistic one. 

I believe that these changes would greatly benefit the server and after speaking with many people in the server especially other business owners, these changes are supported by many.

**Comment by Stewiepooie** [comment]
erm i think this could be good for the economy 🤓☝🏽

**Comment by sleighwhite** [comment]
The clock in/out would be awesome. Would need to figure out how to separate it for DOJ/State/PD/EMS jobs, but I like it!

**Comment by selliee** [comment]
Yeah DOJ/State/PD/EMS wouldnt be included. It would be for WL jobs

**Comment by selliee** [comment]
Yeah! The clock in and out would just be for Whitelisted jobs.. Mech, Food places, and other future businesses that would open up in the city!

**Comment by YukioRei** [comment]
I think allowing people to work at multiple places is a good idea as being stuck working at one place forces you into having to either swap jobs or stay and make less with also very little interaction going on.

**Comment by Epps30** [comment]
Would be great for the city, I know personally Id like to work other jobs while having my midnight job and the other changes would a lot of rp

**Comment by Stewiepooie** [comment]
i would like to work multiple things it would be better and fresher instead of working and doing the same thing hours on end

**Comment by KaiEagle** [comment]
I really like this suggestion this would allow people to work at multiple places part-time. But you might need to change how the job roles work :/

**Comment by coalaura** [comment]
how do you prevent people from clocking in and leaving

**Comment by coalaura** [comment]
also clock in was suggested here already: #2786

**Comment by coalaura** [comment]
oops did not mean to close it

**Comment by selliee** [comment]
So I was thinking with how we can milk cows, kill deer, etc. 

is it possible to change how the food is crafted? Instead of buying the stuff from the fridge- can we make it so burger shot has to have a stock/supply of meat/milk/fruits/whatever else obtainable in city, to craft the burgers / shakes.

This would allow I think, more / better RP. Employees already complain about having to pay for the food from the "fridge" and I think it would be cool to change the fridge to have a storage in it for management to throw in the supply of food for employees to use.

example to craft a hamburger: 1 meat, cabbage, [possible to put wheat somewhere to obtain to act as the burger bun]
-for cheeseburger, add 1 milk to the mix

Also with the cool addition of milkshakes, is it possible to get a blender put into burger shot so employees can craft the milkshakes and not have to worry about needing to bring a blender with them?

**Comment by coalaura** [comment]
Ok here is the thing:
1. The incredible overwhelming majority of burgershot workers i've talked to already complain that you sell food that is not on the menu. Nobody is willing to go milk 400 cows every morning so you can sell milkshakes when your entire existing food is incredibly overpowered and lightyears better than any other food in the city.
2. You can buy a blender and put it in burgershot if you really want to sell another shake, there is 0 need for a permenent one
3. Adding more food that does the exact same thing as existing food just has a different name/icon will change NOTHING about how much people buy
4. There is a proper restaurant script in the works which will then also be expanded for burgershot and other restaurants

I've talked to a bunch of people about this who are all annoyed about making burgershot even more complicated. I've also looked at other subdivisions who work with exactly the same thing that the international subdivision works with and they have no issues keeping their business flourishing. I'm going to close this issue for now as i don't think we are making any progress nor will any of these suggestions make burgershot better, rather make employees want to work less there
