### ISSUE TITLE
[jobs/DOC] paycheck and structure additions and reconfiguration

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#2788]
### Assurance

I have read the `README.md`

### Summary

I am looking to add more positions to the current DOC job list. With DOC becoming active I am looking to get paychecks adjusted with new positions that are inline with PD and EMS.  It will give more officers opportunities for advancement.

Corrections Cadet - [55$] - New
Correctional Officer - [70$]
Senior Correctional Officer - [96$]
Sergeant - [110$] - New
Lieutenant - [126$] - New
Captain - [134$]
Assistant Warden - [138$] - New
Deputy Warden - [146$]
Warden - [154$]

### Reason

Like I said above with DOC becoming active I am looking to get paychecks adjusted with new positions that are inline with PD and EMS.  It will give more officers opportunities for advancement. I based the new positions/pay off what is currently set for SASP/EMS has but with different titles.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/fIroQUmA85.png)
