### ISSUE TITLE
Suggestion FOR A JEWLERY STORE 

### ISSUE THREAD

**Issue by hcboss** [InZidiuZ/op-framework-issue-tracker#279]
jewlery store robbing 

add golden watches and gold bars in the jewlery store gold bars 10% rare and watches 90% in 1 roberry make like people can get like 1500-2000 watches having 0 space on inventory. add a place where you can smelt the watches into gold bar like 100 watches= 1 gold bar and you can sell gold bars to warehouses so people get 15-20k per robbery and it makes sense  these is idea from NO-PIXEL :)

**Comment by AdeptCL** [comment]
Did you forget to actually put any information?

**Comment by Anderzenn** [comment]
Please follow the suggestion template.

**Comment by InZidiuZ** [comment]
Hey,

A jewel store robbery is already planned, but currently not a priority. Also follow the template(s) for future issues.

**InZidiuZ**
*OP-FW Developer*
