### ISSUE TITLE
Suggestion - You found nothing message, house robbery

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2790]
### Assurance

I have read the `README.md`

### Summary

It feels like a bug , after searching things nothing comes on the screen. i think its better to have you found nothing message becasue it happens so often .

### Reason

Happens to me all the time, i have started thinking its a bug.

**Comment by coalaura** [comment]
are you sure? if you dont find an item you usually get money, but you dont get nothing

**Comment by sakar5157** [comment]
> are you sure? if you dont find an item you usually get money, but you dont get nothing

looks like its been fixed, i can see you found nothing message now.
