### ISSUE TITLE
Suggestion - Jackpot Functions

### ISSUE THREAD

**Issue by RailedFromBehind** [InZidiuZ/op-framework-issue-tracker#2791]
### Assurance

I have read the `README.md`

### Summary

Select all & Deselect all Button for the Jackpot's UI. 
Also, when you bet items it would be good to know if someone else had bet items too when outside of the UI.
 

### Reason

Select & deselect all seems like a great function to have. after having a good few items in the jackpots inventory, it starts to become impossible to click items to sell or withdraw, i had a bunch of items that i needed to deselect and it was fair to say there was massive delays between clicking the items and it actually being selected/unselected. i think a button to select/deselect everything would make things a lot easier.

For the alert on when someone else puts items in the jackpot, i think this could be a good addition and make the jackpot more competitive. Like myself, i just dump items in there and leave it for 10 or so minutes then check again, ill often find someones put alot more in than me to win my stuffs, with an alert to say someone else has entered, i would have the chance to add more items if need be.

**Comment by InZidiuZ** [comment]
This has now been added. The lag when you had a lot of items has also been fixed. 10 seconds before the jackpot spins there will also now be a sound warning.
