### ISSUE TITLE
Suggestion - Stockade Tracker Location Trigger

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2793]
### Assurance

I have read the `README.md`

### Summary

Enable the stockade tracker automatically if the vehicle is taken North of Y:1300  (approx Galileo Observatory and north)

### Reason

Currently some people have taken a stockades to difficult to reach locations to loot them before there is a possible response from PD. This negatively affects PD RP. 

Having the tracker for the stockade go off automatically when it goes "too far off it's course" makes sense in RP and would allow a PD response for attempts to take the vehicle too far out of the city.

**Comment by ImArteria** [comment]
My suggestion for a good middleground was do similar trackers how Boosting is. Make it something that pulses every 20 seconds or so. So it's still feasible to use them to set up and also give a headsup when going north

**Comment by coalaura** [comment]
since the stockade now constantly has a tracker this would be solved
