### ISSUE TITLE
Bug report - PD /impound

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2794]
### Assurance

I have read the `README.md`

### Reporter

MetaHatter#0001

### Summary

Impounding a car with the PD /impound command is returning the car to the person's last garage.

### Steps to Reproduce

use /impound on a player vehicle

### Expected Behavior

Using /impound should send it to the city impound lot the same way calling a tow to impound a vehicle does.

### Actual Results

The car is returned to the players garage

### Screenshots/Videos

n/a

### Game Resolution

1440p

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
This is not a bug, that is the intended behavior. You are supposed to call a tow or use the pd impound if you want it fully impounded. /impound is a less powerful /dv
