### ISSUE TITLE
Suggestion - Mirror Park Auto Repair workbench placement

### ISSUE THREAD

**Issue by MrAngryCarver** [InZidiuZ/op-framework-issue-tracker#2796]
### Assurance

I have read the `README.md`

### Summary

Currently the primary place for repairs to take place at Mirror Park are the three outside bays. There are at present 2 work benches placed very close together (see picture 1) https://cdn.discordapp.com/attachments/955457439942205460/1107279569028923472/image.png

If possible could one of these work benches be moved closer to the furthest repair bay with the silver grate? Either removing the green lockers and replacing with a workbench or placing the workbench next to the green lockers? (see picture 2) https://cdn.discordapp.com/attachments/955457439942205460/1107279643884666901/image.png

### Reason

When carrying out any repairs to cars in the furthest repair bay, workers are having to walk over to the far side of the shop, craft the item needed and then having to run all the way back to the car being repaired. Having a workbench placed in the requested location would save time for both the employee and the customer having the repair done on their vehicle.

**Comment by coalaura** [comment]
i really dont think this distance is that far ![hmm](https://i.shrt.day/TohotuzE84.png)

**Comment by MrAngryCarver** [comment]
I meant moving the workbench from underneath the office window to that location next to the green lockers. Its was only a thought. If it doesn't make sense to do it then its absolutely fine. I'd just noticed a few times when the shop was busy and more than one person was clocked, on you ended up running into each other when having to scoot back and fourth from the silver grate repair station to the workbench. Especially if the work bench in your attached picture was already in use.
