### ISSUE TITLE
Suggestion - DOC identification Badges

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#2797]
### Assurance

I have read the `README.md`

### Summary

I am trying to see if DOC can get identification badges. When attempting to conduct a prison transport we have been asked before if we had badges to prove that we were DOC and we informed them that we do not.  I was looking to see if we could get some.

### Reason

It would be good because we can easily identify DOC workers.  I attached a photo that could be used for the badge unless you find a better one. 

![BBSPlogo](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/81419197/10c08a18-24c1-43e6-9071-6f7d851c7b87)

**Comment by coalaura** [comment]
this has been done
