### ISSUE TITLE
Bug report - People can be cuffed whilst sitting in vehicles

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2798]
### Assurance

I have read the `README.md`

### Reporter

Hell of the Devil#7395

### Summary

So recently i've seen once or twice where dannies have been handcuffing people whilst people are sitting in a vehicle, after testing i have been able to reproduce this repeatedly and i feel it is not really a great ability to have as it doesn't really make sense and causes the person to be forced out of the car and allows you to immediately start searching them. this can be abused in many ways.

### Steps to Reproduce

stand on top of a vehicle whilst someone else is in a vehicle then use handcuffs, sometimes you need to move around a bit to find the right spot depending on the vehicle but most of the time you can just stand above the person

### Expected Behavior

You shouldn't be able to cuff someone who is sitting in a vehicle

### Actual Results

You are able to cuff someone who is sitting in a vehicle

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/194hwXyiNo9QbT/d1337J35py6D?invite=cr-MSxxNkgsMTk1ODM0MzMs

### Game Resolution

1920 x 1080

### Player Data

https://cdn.discordapp.com/attachments/1066098880275558502/1107554588862718072/FiveM_b2699_GTAProcess_6ZD3vatpMR.png

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
done

**Comment by hell-of-the-devil** [comment]
you're amazing!
