### ISSUE TITLE
Suggestion - Heartbeat Sensor

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2799]
### Assurance

I have read the `README.md`

### Summary

A human presence detection system activated when installed on a smart watch. This will show all civilians on the mini map within a range. Should be available in the taco truck, attaches to a smart watch.

### Reason

This tool will help criminals or police in close quarters situations, to give more tactical combat.

**Comment by DaxterPancake** [comment]
This sounds like it will just be abused 24/7. I don't see any plus side to this at all.
