### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alekslucius** [InZidiuZ/op-framework-issue-tracker#280]
**Name:**
Aleks | Aleks #4118

**Summary:**
2 Phone App ideas, 
1. LoveMeet Dating App, something like Tinder, for GTARP
2. DeepWeb, it would be interesting to post videos, and pictures, of "deepweb" stuff, and would help people find drug locations and such.

**Reason:**
LoveMeet: People are always doing drug runs and at the hospital. it would be for good RP situations, and help EMS also get out of the hospital and Gangs to get out of their territory.
DeepWeb: Would be interesting to see what people, post "darkweb" content. Drug Locations, Gang Stuff, Police Brutality. kind of like a underground "news" for people who can access the app.

**Comment by Anderzenn** [comment]
Hey,

I'll add it to the "Really nice to have" list, it's not a yes or a no, it's a maybe and is not high on the priority list :)

**Anderzenn**
*OP-FW UI Developer*
