### ISSUE TITLE
Bug report - Unable to Retrieve Vehicles Which Cannot be Recovered Manually

### ISSUE THREAD

**Issue by roraraptor** [InZidiuZ/op-framework-issue-tracker#2800]
### Assurance

I have read the `README.md`

### Reporter

RoraRaptor#7971

### Summary

My car ended up in the ocean, so far away from the shore that I can't reach it with a tow truck. When I try to retrieve it at a garage, I just get prompted to go and recover it myself, which I obviously can't do.

### Steps to Reproduce

1. Place vehicle in body of water.
2. Try to retrieve vehicle automatically

### Expected Behavior

I would expect to be able to retrieve my vehicle, paying the dollar amount and then being able to pull out the vehicle from the garage.

### Actual Results

I get a waypoint to the vehicle, leading to the waterlogged vehicle that is unreachable with a tow truck. I then have to wait for the vehicle to de-spawn, which it doesn't do even after multiple rounds of quitting and logging back in.

### Server

International (c3s1.op-framework.com)

**Comment by enutpeanut** [comment]
just don't crash into the water i guess

**Comment by MetaHatter** [comment]
AFAIK this is intended behavior and the vehicle will despawn after a period of time and be available fhen for retrieval.

**Comment by coalaura** [comment]
what metahatter said
