### ISSUE TITLE
Suggestion - Clues for crafting ingredients or locations

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2801]
### Assurance

I have read the `README.md`

### Summary

Currently you can see a crafting table / laptop etc but nothing in the surrounding area gives any hints as to what it could craft or need etc 

Maybe the possibility of having clues near crafting stations to help people figure this stuff out 

### Reason

I think this would help make better rp in groups for example we find a crafting table say for example the nos empty tank…. If that area had clues to the items needed it would make it more fun so our group could be like “let’s go find these items and figure out combos with them” etc

**Comment by AaronSmithCoding** [comment]
I was thinking maybe it could be something like the treasure maps....you get pieces of crafting recipes and then merging them give you the ingredients needed...not the location so then its the fun of taking the exact ingredients all round the city and look for the location etc

**Comment by coalaura** [comment]
All crafting recipes are designed to make sense. Wanna craft a nos tank? probably need metal, wanna craft paint? you probably need a few liquids and a bucket maybe....

I'm not adding hints to crafting spots, i REMOVED the hints, its not supposed to be easy
