### ISSUE TITLE
Suggestion - Inventory/Storage Locks

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#2803]
### Assurance

I have read the `README.md`

### Summary

Allow players to have the option to have some kind of lock for their storage items in apartments/houses. This could be a buyable item from either a store, or from the /furniture menu. 

### Reason

People share access to their houses with friends or allow their friends to pay rent with them. Would be a cool feature to be able to lock your items and unlock them (kind of like you can with whitelisted buildings). Could be a strech, but would maybe also be scripted to allow certain players to have access to the locks too. (Or the whole thing could be made into another level of access ("Level 4").

**Comment by coalaura** [comment]
I really dont see the point, if you are scared that someone will steal your items then dont give them access
