### ISSUE TITLE
Suggestion - Make weed seeds more accessible 

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2804]
### Assurance

I have read the `README.md`

### Summary

Currently unless I am wrong weed seeds are only found from doing waste hq job or a small % when harvesting plants.
IT would be nice if the weed seeds could be gained from other methods such as z pills, cleaning houses, or simply purchasing from Green Wonderland

### Reason

I think the ability to get more weed seeds will open up some more rp /activities for groups/solos
People who have other jobs can only rely on buying from others who do waste and most people keep for themselves or if your lucky to find someone who doesnt know how to use them you buy from them

**Comment by coalaura** [comment]
Weed seeds can be found in quite a few places, not only garbage. They even have very good drop chances
