### ISSUE TITLE
Suggestion - More Keybinds

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#2805]
### Assurance

I have read the `README.md`

### Summary

Something that can becomes very useful to players are keybindings. Things that could be useful to be made into keybinds could be, but are not limited to;

- Radio Volume Up/Down 
- Radio Channel Up/Down
- Ability to change the phone keybind
- Answer & hang up keybind

### Reason

Makes things so much easier especially in more intense situations and just improves the quality of gameplay overall.

**Comment by coalaura** [comment]
> Radio Volume Up/Down

You can now do /radio_volume + or - (bind it to a key and boom, keybind)

> Radio Channel Up/Down

Already a thing (CTRL and arrow keys)

> Ability to change the phone keybind

You'll be able to do this now in the keybind settings

> Answer & hang up keybind

I dont see a need for this
