### ISSUE TITLE
Suggestion - Addition to Tow Job

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#2807]
### Assurance

I have read the `README.md`

### Summary

Allow for civs/PD to instead call for a tow, have it to where they can /impound a car and allow a ping to be brought up instead. So that it allows for PD to impound crashed local cars and have tow truck drivers do something other then wait for actual phone calls. 

### Reason

This would eventually allow for a PD Tow job down the future, and would also allow PD to select certain people for potential PD jobs, furthuring peoples RP rather then just simply putting in a discord/google docs application

**Comment by coalaura** [comment]
why not just call a tow???

**Comment by coalaura** [comment]
PD needs a command allowing them to delete vehicles. There is not always tows on duty. Having /impound send a dispatch or text call to tows wont fix anything cause you will still have PD call local tows as much as they do now
