### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yohan420** [InZidiuZ/op-framework-issue-tracker#281]
**Reporter:**
My name is yohan#2164 and my steam is https://steamcommunity.com/id/yohan_/
**Summary:**
I only have 1 character slot, I do have 4 right but only one is being used and whenever I'm creating an new character it goes into that slot and deletes my previous characters, the thing is my character thats listed there is my first character ever its not the name of the newer character either

**Steps to Reproduce:**
I just create a new character and its only 1 slot out of 4 no matter which spot I pick for the new character and it deletes my old ones, and that bugged slot still has the same name

**Expected Results:**
It should create a new character in a new slot with the right name and backstory

**Actual Results:**
It doesn't create a new character in a slot and deletes my previous one in the bugged slot

## Additional Information

**Screenshots:**
https://gyazo.com/df41127450000172988909024ea83e66

**Game Resolution:**
What is your game's resolution? 1920x1080 144hz

**Player Data:**
https://gyazo.com/f5a6c71dfd451bb21045b520598b28b7

**Notes:**
I'm new to the city too, I don't really need my old characters back but I would like this to be fixed since I can't have multiple characters, thanks!

**Comment by InZidiuZ** [comment]
Hey,

Your characters were being stacked upon each other. I've deleted the latest ones, and sorted the issue out for you. You should be all good now. I don't exactly know what causes this issue, so if you manage to replicate it, please let me know so I can get it permanently resolved.

**InZidiuZ**
*OP-FW Developer*
