### ISSUE TITLE
Bug report - Mosleys script issues

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2810]
### Assurance

I have read the `README.md`

### Reporter

Hell of the Devil#7395

### Summary

Mosleys has a few issues that need to be fixed, some collision issues, some scripting issues and some just mundane annoyances, Below are the currently listed issues that require fixing...

1. The south east single door next to the sliding door requires a door lock  
2. There are multiple material computers in the main office right next to each other
3. The workbench to create Advanced Repair Kits from Basic Repair Kits is still in the old spot
4. A few mapping issues including doors not sitting in frames correctly and the curved wall has no collision (currently working on getting these fixed)

### Steps to Reproduce

Get the mechanic job and go to mosleys and reference the photos above!

### Expected Behavior

1. Door should have a lock
2. there should be only 1 computer
3. The workbench should be in the main work floor
4. Doors should sit correctly in frames and collision should be on the wall 

### Actual Results

1. Door doesn't have a lock
2. there are two computers next to each other
3. the workbench is accessed through the painting in the hallway
4. doors don't fit their frames and collision is not existant

### Screenshots/Videos

1.  https://cdn.discordapp.com/attachments/1066098880275558502/1110984649477459968/FiveM_b2699_GTAProcess_UyTFCiTIk9.jpg

2. https://cdn.discordapp.com/attachments/1110821053397225543/1110825474826960967/image.png https://cdn.discordapp.com/attachments/1110821053397225543/1110825475267379280/image.png

3. https://cdn.discordapp.com/attachments/1110821053397225543/1110986990633095198/image.png

4. https://cdn.discordapp.com/attachments/1066098880275558502/1110981488436068372/FiveM_b2699_GTAProcess_PCyhhr2nPf.jpg https://cdn.discordapp.com/attachments/1066098880275558502/1110982093003034684/FiveM_b2699_GTAProcess_f0rrKAzox7.jpg https://cdn.discordapp.com/attachments/1066098880275558502/1110982386533007400/FiveM_b2699_GTAProcess_2O1dfuZA2g.png https://cdn.discordapp.com/attachments/1066098880275558502/1110991731652038776/FiveM_b2699_GTAProcess_usVu52MFxK.jpg https://cdn.discordapp.com/attachments/1066098880275558502/1110991876191957133/FiveM_b2699_GTAProcess_dl6CPeYTio.jpg

### Game Resolution

1920x1080

### Player Data

https://cdn.discordapp.com/attachments/1066098880275558502/1110992013421191178/FiveM_b2699_GTAProcess_dvX4YXL0st.png

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
mapping issues need to go to the asset issue tracker
