### ISSUE TITLE
Suggestion - Prison Sound Effects

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#2811]
### Assurance

I have read the `README.md`

### Summary

Remove the annoying announcements at Bolingbroke.

### Reason

They're loud, repetitive, and annoying. Some of them were funny at first but if I have to hear them one more time I will go mad. Quality of life update. Please.

**Comment by coalaura** [comment]
i think they add a nice ambiance. It would feel very empty without them
