### ISSUE TITLE
Suggestion - Force Default Walk Style if Cuffed

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2812]
### Assurance

I have read the `README.md`

### Summary

Force walk style to default and prevent walk styles from being changed if handcuffed.

Additionally/Alternatively force walkstyle to default when the sprint key is depressed and back when released. 

### Reason

Currently it is possible to run faster in handcuffs than mechanically intended using walk-style emotes.

**Comment by coalaura** [comment]
you still run slower than everyone else tho

**Comment by MetaHatter** [comment]
Just a quick suggestion for parity and balancing reasons. 

 Not critical, but ideally there would be a universal "run speed" for everyone, regardless, that could be used to balance special cases, like being cuffed, against. 

Using a walkstyle for a run speed boost is using a game mechanic for an unintended purpose.
