### ISSUE TITLE
Suggestion - refueling directly from petrol pump should be cheaper

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2814]
### Assurance

I have read the `README.md`

### Summary

Jerry can price is 250 but if we refuel directly from the gas station, it costs around 1400 for full refuel.

### Reason

its impractical for same amount of fuel.

**Comment by InZidiuZ** [comment]
What server is that on?

**Comment by sakar5157** [comment]
> What server is that on?

Its on legacy Nepal

**Comment by sakar5157** [comment]
> That server has a custom config option making the fuel 6.9 more expensive: https://inzidiuz.com/ER1NmQ.png
> 
> They can either reduce it or make the jerrycans more costly.

alright sir, thank you.
