### ISSUE TITLE
Suggestion - Purge Job Loot if Vacant

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2815]
### Assurance

I have read the `README.md`

### Summary

If a job (bank, store, stockade) has been triggered as available for looting and there are no longer any non-active PD players in a 50m radius, purge the loot from the job.

Alternatively, provide PD with a way to "secure" the loot that remains while the scene is cleared, perhaps by interacting with the loot spots.

### Reason

Currently there is nothing mechanically preventing someone from partially hitting a job, drawing PD away, and having someone else go back to collect the rest of the loot.

**Comment by coalaura** [comment]
Thats what /close_bank, /close_store and /close_jewelry are for
