### ISSUE TITLE
Suggestion - increase the money reward for burger shot delivery outside city

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2817]
### Assurance

I have read the `README.md`

### Summary

We do only get extra 100 ingame money for deliveries outside city. I dont think thats fair for extra 4 miles of distance travelling in a slow burgershot van. I suggest increasing it significantly so that it does not look like a trade of loss.

### Reason

Players are complaining in game for this. I think they are right for the instance.

**Comment by coalaura** [comment]
done
