### ISSUE TITLE
Suggestion - Public Tow Job

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#2820]
### Assurance

I have read the `README.md`

### Summary

Having a public tow job with decent pay per job would be great and would ultimately tidy up the city as a whole. 

### Reason

Allows for new types of interactions for players to have. Can also involve this for players to have the ability to tow PD requested vehicles. 

Yes you can apply to become a mechanic and do this, but not everyone is hiring, and the tows aren't always active and available.

**Comment by coalaura** [comment]
This seems more like a roleplay/business issue than a dev issue. I don't think making tow public is a good idea
