### ISSUE TITLE
Suggestion - /bill should also work with money in the bank if the player has smartwatch

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2821]
### Assurance

I have read the `README.md`

### Summary

players might not have cash all the time. so smartwatch should do it as usual.

### Reason

happens to me all the time XD

**Comment by coalaura** [comment]
that would remove the need for ATMs tho, no?

**Comment by sakar5157** [comment]
> that would remove the need for ATMs tho, no?

this is used for paying bills for the business. 
arent ATMs used for transferring money from player to player?
also smartwatch eliminates the need of cash in the game, correct me if im wrong.

**Comment by coalaura** [comment]
yeah but anyone can use /bill so you would basically give everyone the ability to transfer money without having to use an ATM

**Comment by sakar5157** [comment]
> yeah but anyone can use /bill so you would basically give everyone the ability to transfer money without having to use an ATM
there is  already give_cash option to transfer money from player to player. why not make the /bill command for the ones with whitelisted job holders. 
i think it gives better options in business RP

**Comment by coalaura** [comment]
Cause people will abuse it and job whitelists are not a dev thing but a thing decided by each community

**Comment by sakar5157** [comment]
> Cause people will abuse it and job whitelists are not a dev thing but a thing decided by each community

alright. i got it.
