### ISSUE TITLE
Suggestion - Need Parking Garage behind Hayes Auto Repair

### ISSUE THREAD

**Issue by Dhondu11** [InZidiuZ/op-framework-issue-tracker#2822]
### Assurance

I have read the `README.md`

### Summary

 I am writing to bring your attention to an issue concerning the lack of a nearby garage close of Hayes Auto Repairs. As sometimes when vehicle is fully repaired glass or doors fall down and it will only be fixed after storing vehicle, for that also customers have to go far near coffee bean or Del Pero freeway. Its not convenient to travel to another garage if someone asks for Tow service as it will increase time and many times other garage like mirror park and Mosley mechanics can get there early 

### Reason

It would be nice quality of life change for both customer and mechanic of Hayes auto repairs .

**Comment by coalaura** [comment]
no, the next garage is very close, i don't see a need for another one
![ye](https://i.shrt.day/riVIDuNO34.png)
