### ISSUE TITLE
Suggestion - add a bike for burgershot delivery

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2823]
### Assurance

I have read the `README.md`

### Summary

players are requesting for bike for burgershot delivery as they have to go into alleys for the job.

### Reason

i feel like its realistic in using bikes as compared to taking a van to deliver a single order.

**Comment by coalaura** [comment]
Which bike?

**Comment by sakar5157** [comment]
> Which bike?

anything with the livery and good handling can work.
i have seen police using a custom bike in the game. 
think it will work

**Comment by sakar5157** [comment]
> in that case you'd have to make an asset suggestion https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

alright.  im going for it.
