### ISSUE TITLE
Suggestion - Functional & Lockable Casa Blanca Doors

### ISSUE THREAD

**Issue by seamarob** [InZidiuZ/op-framework-issue-tracker#2825]
### Assurance

I have read the `README.md`

### Summary

This request will involve doors on the property that I wish to relocate and change the locks.

1. The first door will be the front door. I wish to remove the current front door [RED X] and put the new front door within the existing frame [HIGHLIGHTED YELLOW]. With this, I would like the door to be pushed open from either direction and be lockable by all CASA BLANCA STAFF. 

2. Door two I just request for the locks to be changed and access to lock and unlock to be given to CASA BLANCA OWNER and MANAGERS.

Felt proper to do some work in the city to have construction permits pulled and approved by State. 

I have combed through a few issues in regard to Casa Blanca and Doors so I believe there are not currently open threads for this request. I plan to draft an Employee/Salary and GPS Blip next time.

REFERENCES
![doors1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/79816775/9d619a9b-5b31-4a35-bbfa-92dd187f393e)
![doors2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/79816775/8d982c88-608d-4f7c-8879-858e5e2bff98)

### Reason

This would prevent the free range of the business when it’s during closing hours. Having the door able to open and close may save me money instead of it just being stuck wide open. Unfortunately, the business may not be open every moment even though I want it to be, as a fine dining restaurant there are times the doors do need to be locked. This could be due to no staff available, or in case reservations for private meetings or events. I enjoyed making the "Renovation Request Form" and plan to continue so that it provides more Business RP between State and Businesses.

**Comment by kaycorriher** [comment]
This would be an nice start to see a business RP. I've witnessed what they've done with what they have and want to see where they take the Casa Blanca RP.

**Comment by coalaura** [comment]
So salary you wont be able to pick, it would be the Bar and Clubs job most likely. Door locks are not a problem and GPD blip i can add aswell (you can pick out one (and a color) from this list if you want: https://docs.fivem.net/docs/game-references/blips/ )

Adding and moving the doors would be something for the asset github: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by seamarob** [comment]
I don't know if you wanted me to respond here, if not my apologies. I'm cool with that for the salary and I'll get that door moving in the correct place. Blip 89 "C" and Color 46 "Gold" will be great for the blip. Appreciate ya
