### ISSUE TITLE
Suggestion - Add hiking backpacks to hunting store

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2826]
### Assurance

I have read the `README.md`

### Summary

Add a hiking backpack to the hunting store that when in your inventory will show on your back. When this item is in your inventory have all guns that usually display on your back display on your front.

Additional idea if this works/is liked is to then add police backpacks for PD to wear or a backpack store which will allow people to purchase various different backpacks.

### Reason

Backpacks were an integral part of expressing yourself and immersing yourself in your activity (hiking backpacks especially). Since their removal due to abuse from people in the community I have constantly heard people wishing and wanting backpacks back and trying to think of ways to make it happen.

I am unsure of how difficult this task will be to create but I am more than happy to send over the previously removed backpacks to see if you are able to utilize them in some way.

**Comment by seamarob** [comment]
Not sure if this would change up the suggestion, but what if a hiking business was started and the owner was given a shop to purchase backpacks that can expire. This shop could be similar to the way carding trade packs are operating within the city

**Comment by DaxterPancake** [comment]
I don't really think a whole buisness is needed for backpacks. They would serve no purpose other than for RP just like the flowers and teddy bears.

**Comment by seamarob** [comment]
I agree, a simple shop is all that’s needed. I think having the chance to add more interactions via business is never a bad thing. When I say business here I just meant it not being accessible to everyone easily to avoid abusing them.

**Comment by DaxterPancake** [comment]
What do you mean by abusing them? If they server no purpose other than an RP item and the gun would go on their front therefore stopping them from hiding their gun in it.

Ofcourse adding more interations via business is never a bad thing but it also adds unessessary clutter to a simple idea. If someone wants to RP that they own the hunting store and therefore sell the backpacks through RP they can, I see no reason to lock the purchasing itself behind a job, though.

**Comment by seamarob** [comment]
Sorry, I had said this may change the suggestion. I meant if placing guns in front wasn’t able to be done. I wasn’t implying to make complicated that’s my fault
