### ISSUE TITLE
Suggestion - Bahama Mamas Slot Machines and Employees and Salary division

### ISSUE THREAD

**Issue by Rocky1290** [InZidiuZ/op-framework-issue-tracker#2829]
### Assurance

I have read the `README.md`

### Summary

Hi Team,

This is to update that I've a suggestion to create a employee bifurcation with different employees bifurcation and they are as :-

1) Bartender 
* Junior Bartender - 20
* Senior Bartender - 25

2) DJ
* Junior DJ - 30
* Senior DJ - 35

3) Manager 
* Club Manager - 40
* Public Relations Manager - 45

4) Owner - 50

And also there's a suggestion where the slot machines in Bahamas should be made operational.

### Reason

I want to have this employees bifurcation because it would create a lot of RP opportunities and also will push them to do this RP as the bifurcation that we have now along with the salary is comparatively less than any other whitelisted job. And regarding the slot machines the people go to Diamond Casino for gambling but if the slot machines here are made operational then it will create RP as there would be a proper RP behind them coming to the club, do some RP to access the slot machines, playing games and so on. Kindly take this into consideration if you find it can bring some change.

**Comment by seamarob** [comment]
I’m interested in employee positions since it’s something that Casa Blanca is missing from I’ve been told, #2828. Business RP can really grow with an addition of bifurcation being established.
