### ISSUE TITLE
Suggestion: New Legal Whitelisted job. (Security Services)

### ISSUE THREAD

**Issue by Vexzarkov** [InZidiuZ/op-framework-issue-tracker#283]
**Name:**
VexZarkov#0359

**Summary:**
Merryweather Security and Gruppe 6 Security services.

Service: 
- Security Transport
- Armed Security Detail / escorts
- Location Protection (Banks, Stores, Homes, Ect.) 
- High Value Transport.
-Emergency Tactical Response

Who is MerryWeather and Gruppe 6 Security?

We are a private ex-military company and security contractor. We have the experience to take care of your ‘’personal’’ problems in a unstable world we are the stable solution. We will protect and serve for the right amount of payment. We will make sure that harm of any kind wont occur.

Who do we serve?
We serve anyone who is willing to pay (civilians, Businesses, government agency's etc).
As long as our client pay the due of our service, we will do our part.
Contracts prices can be talked on and met on to insure the client is happy with the service they get.

**Reason:**

This would add a new angle into Legal RP. places can request a security company to work their stores locations,protect VIP's, Run goods that may be of risk of being stolen.
this would add a legal form of work for people to do this also adds into new RP ideas from Weekly gold transports ect and many other events can have security services (Weddings ect)

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
