### ISSUE TITLE
Suggestion - Remove Illegal Daily Activities

### ISSUE THREAD

**Issue by RailedFromBehind** [InZidiuZ/op-framework-issue-tracker#2830]
### Assurance

I have read the `README.md`

### Summary

Remove things like chop cars etc.

### Reason

I think removing illegal dailies would get more people to actually do them, although there are many who already do do them, as someone who tried to stay legal, I can see the illegal activities being a problem for people like officers, any public sectors, business owners and just anyone who wants to stay legal. Those few who have to risk their jobs and businesses to do a daily.

**Comment by DaxterPancake** [comment]
I agree with this. Completing all of your dailies gives you rewards in the long term and there is a large group of people who are unable to hit their streak due to some of the tasks being illegal.

**Comment by seamarob** [comment]
I agree, worming your way out of punching locals with police is not the easiest thing I’ve done. Assault is still assault even against locals

**Comment by King2704** [comment]
Thats why you can create a new character or switch to a crim character where you can do those illegal tasks since they carry over different characters.

**Comment by DaxterPancake** [comment]
> Thats why you can create a new character or switch to a crim character where you can do those illegal tasks since they carry over different characters.

I make characters to roleplay and not so I can grind out daily tasks. I don’t wish to create a character just to do the illegal tasks.

At the very least it would be nice to have an option to go at to re-roll a task or tasks to try and get something that is not illegal to do.

**Comment by seamarob** [comment]
RP wise it may be weird to run into someone new that probably isn’t talking to anyone and already knows how to do illegal tasks

**Comment by kieran179** [comment]
Would it not be worth having to go to the daily tasks and selecting if you want to do legal, illegal, or don't care??

**Comment by InZidiuZ** [comment]
I've added a way to pay for a new task like [this](https://inzidiuz.com/DJGpnM.mp4). I've also categorized each activity, and made it impossible to get an illegal one when you pay for a refresh.
