### ISSUE TITLE
Bug report - Voice Issues in MRPD

### ISSUE THREAD

**Issue by Lini-7** [InZidiuZ/op-framework-issue-tracker#2831]
### Assurance

I have read the `README.md`

### Reporter

Lini#8535

### Summary

Officers in MRPD had some voice issues last night, so myself and SmythGG did some testing. There was no static noise or anything that indicates a radio jammer and it only seems to affect people if they meet two things.

There seems to be some sort of link between the **cells of MRPD** and the **outside garage of MRPD**... if Person **A** is in the cells of MRPD, and Person **B** is roughly within that red square, all the way to the roof of MRPD, you cannot hear each other on radio or on phone. If Person **A** leaves the cells, but **Person B** stays in the red square they can hear each other. If Person **B** leaves the red square, but Person **A** stays in the cells, they can also hear each other. If one person enters the area that causes this problem, their voice slowly fades out. It slowly fades back in as they leave the area.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/92475272/d78632e0-e0db-4f94-8eeb-55f0f720517d)

This is true for both radio and phone.

### Steps to Reproduce

You will need two people, one person needs to be in the cells ofMRPD, one person inside the area of the previously shown red-marked area. | Unsure if related: When the bug was found, both people had the **Police job**, and were **on-duty**.

### Expected Behavior

The two people should not be able to hear each other on phone or radio.

If the person in the cells leaves the area, so goes through towards the evidence locker of MRPD, or towards the hallway that leads to the outside garage, they should be able to hear each other.

If the person in the red-marked area leaves through the gates, goes past the fence, or inside MRPD (but not the cells), they should be able to hear each other.

### Actual Results

The "Expected Behaviour" was the results myself and SmythGG had.

### Screenshots/Videos

[https://cdn.discordapp.com/attachments/686057091475046451/1115842773346701413/image.png](url)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/92475272/da6a49c9-2d7f-465c-9c41-8d72d560eeb7)

### Game Resolution

1920x1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/92475272/1a08cb44-d10c-4aa2-8b64-4c9057badc1e)

### Server

International (c3s1.op-framework.com)

**Comment by Lini-7** [comment]
Yes, I am fully aware of that. But that should not result in communication on radio or phone to be hindered by that, right? Especially if it only occurs if one person is in the cells, and the other person is in that specific area.

**Comment by coalaura** [comment]
I have not been able to really reproduce this
