### ISSUE TITLE
Bug report - Burgershot Scripts

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2835]
### Assurance

I have read the `README.md`

### Reporter

BlackHawk#3322

### Summary

patties cannot be grilled as well as potatoes cannot be cut.

### Steps to Reproduce

1. buy 1 patty from store
2. press g at grill
3. buy 3 potatoes from store
4. cut the potatoes at the table

### Expected Behavior

grilled patties and raw fries shall be added to inventory

### Actual Results

it says failed to grill patties

### Screenshots/Videos

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/43814730/7d1966c4-a20d-4f4a-a476-7e3ec366c227)

### Game Resolution

1080p

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/43814730/cb32102b-e8a6-429f-979d-bc7e27396b75)

### Server

Nepal (c13s1.op-framework.com)

**Comment by coalaura** [comment]
already fixed

**Comment by sakar5157** [comment]
> already fixed

Thank you!
