### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by rishabmishra0341** [InZidiuZ/op-framework-issue-tracker#2837]
### Assurance

I have read the `README.md`

### Summary

we want to add cloths for Mirror park auto repair shop we searched but there is no dress available for this shop

### Reason

we recently opened the mirror park auto repair shop in legacy roleplay India but we saw that there is no particular mechanic cloths for mirror park auto repair shop so we want it to be added to the server because its too difficult to handle this without dress and it looks improfessional also without dress and its too difficult to control as well for the management. So, Kindly look into the matter and please add all the clothes for the mirror park auto repair shop.

**Comment by MetaHatter** [comment]
This is an issue for the asset tracker... But there are orange polo shirts for that shop already in the framework.

**Comment by rishabmishra0341** [comment]
Can you please tell me the number of the dress so that i can check it

**Comment by rishabmishra0341** [comment]
I shirt we got but can you guys add more other clothes as mosley is having so that we can give it to the mechanic as per there positions

**Comment by KaiEagle** [comment]
tbh I don't see why the mechanic needs to have a uniform according to the ranks

**Comment by DaxterPancake** [comment]
I am planning on making new clothing for Mirror Park Auto and will do soon soonTM. You will not be getting ranks, as most other shops only have 1-3 different clothing items and having ranks would kinda go crazy. Feel free to re-make this on the correct github if you feel the need to do so.

**Comment by MrAngryCarver** [comment]
I'll love Daxter forever when the Mirror Park clothes come in. Just putting that in the thread.
