### ISSUE TITLE
Bug report - Trucking trailers spawn in the wrong place in multiple locations.

### ISSUE THREAD

**Issue by Hebby11** [InZidiuZ/op-framework-issue-tracker#2839]
### Assurance

I have read the `README.md`

### Reporter

hebby11

### Summary

When getting a job at some cargo stations some the trailers spawn in the wrong places or on top of other trailers, upside down, etc. The locations I can currently remember this happening at are Grand Senora Desert and Los Santos International Airport.
The trailers spawning upside down isn't a big issue because of /flip, but I've had to cancel 5 jobs now because there was no way for me to reach the trailer with my truck.

### Steps to Reproduce

Go to one of the locations with the Trucker job and pick a job to do.

### Expected Behavior

For trailers to spawn in an accessible way. 

### Actual Results

Trailers spawn all over the place, vectors need fixing.

### Screenshots/Videos

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/136635143/28ca1307-1b4a-4848-bc72-4294e005b5dc)

### Game Resolution

1920x1080

### Player Data

Character ID: 123203 - Job Data: Transportation, Trucker, Amateur
Timestamp: 2023-06-14  18:11:04

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This should now be fixed. If it isn't after next update, you can DM me on discord @ b.0
