### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by imChinGLinG** [InZidiuZ/op-framework-issue-tracker#284]
**Reporter:**
Discord name: -ChinGLinG-#3206 Steam: https://steamcommunity.com/id/johnpdsk/

**Summary:**

In the waste collector job, there are 3 checkpoints that it says in top left corner of the screen to pick garbage in that certain place but when you get there, it shows up to return to HQ even if you didn't picked up any trash.

**Steps to Reproduce:**
You simply get the truck, you enter the truck and provides the person in the map to go in that certain checkpoint.

**Expected Results:**
You're supposed to pick up trash in that place.

**Actual Results:**
You don't pick any trash in that place.

## Additional Information

**Screenshots:**

1º checkpoint is near Michael's house: 
![image](https://user-images.githubusercontent.com/53337828/61945901-0e858800-af99-11e9-8b18-a8fd07aafce5.png)
2º checkpoint near the purple marker: 
![image](https://user-images.githubusercontent.com/53337828/61945976-4987bb80-af99-11e9-878b-8d85d46c2da3.png)
3º checkpoint is someone near there, I got 1 time and it said the same thing: 
![image](https://user-images.githubusercontent.com/53337828/61946010-61f7d600-af99-11e9-91ad-3a919bf36337.png)

**Game Resolution:**

1440x1080 77 hz

**Player Data:**
![image](https://user-images.githubusercontent.com/53337828/61945718-9d45d500-af98-11e9-8e7a-e9c8f63d01bf.png)

**Notes:**
When I was picking up the trash and appeared those checkpoints I can confirm that in those 3 checkpoints it will show up that thing, I got those checkpoints like 5 times and some friends of mine also experienced that.

**Comment by InZidiuZ** [comment]
Hey,

The garbage job selects trash bags from memory, and when none in memory are found, it'll tell you to go back to HQ. Try changing your settings if you're having issues with a lack of bags spawning.

Also try driving in slowly, as that may give the bags more time to spawn.

Won't be removing those locations though, for now.

**InZidiuZ**
*OP-FW Developer*
