### ISSUE TITLE
Suggestion - Stop gems from blowing up.

### ISSUE THREAD

**Issue by Hebby11** [InZidiuZ/op-framework-issue-tracker#2840]
### Assurance

I have read the `README.md`

### Summary

Stop unstable gems from blowing up, it's a bit stupid for an RP server. It should be replaced with something else.

### Reason

Gems blowing up are annoying and make no sense. If I went looking for some amethyst at the beach and cracked open the wrong stone it wouldn't suddenly explode like a grenade, it also breaks immersion when your gem mining on the beach with others around and suddenly hear *booom*; it's also difficult to explain to EMS or others why you're on the ground.

Instead you should give the players something like gem dust which is worth nothing, or better yet remove the instability part of the gems altogether as it seems to be a very poorly thought out idea, in my personal opinion.

**Comment by coalaura** [comment]
gemstone scanners exist for a reason

**Comment by King2704** [comment]
removing the risk of blowing up when mining would make it even more op

**Comment by Hebby11** [comment]
> removing the risk of blowing up when mining would make it even more op

It's not even op in the first place. Most the time you don't even get a gem from the stables and most the gems aren't stable in the first place. Plus gems don't have a set sell price and most of them don't sell for much anyway, only morganite and diamond are really worth it. I can make more money doing trucker deliveries than I can gem mining within 30 mins.

**Comment by Hebby11** [comment]
> removing the risk of blowing up when mining would make it even more op

And if you're running an RP server you want your risks to be RP appropriate not whatever this is supposed to be.

**Comment by seamarob** [comment]
What rp are you so immersed in that you can’t use a gem stone scanner to be prepared for a possible explosion? Because if you are looking for stones with your friends to sell as healing crystals to actual people and not locally I’m interested.

**Comment by Hebby11** [comment]
> What rp are you so immersed in that you can’t use a gem stone scanner to be prepared for a possible explosion? Because if you are looking for stones with your friends to sell as healing crystals to actual people and not locally I’m interested.

Seems like a plan, lmao. But fr isn't the point of RP to be immersed? There's no such thing as too much immersion. I have trouble getting immersed when something like a gemstone blows up in my face. It's like growing weed and then suddenly the plant starts on fire. Where's the fire coming from? How did it catch a light so quickly? These are the kinda things I would think.

**Comment by Hebby11** [comment]
> > What rp are you so immersed in that you can’t use a gem stone scanner to be prepared for a possible explosion? Because if you are looking for stones with your friends to sell as healing crystals to actual people and not locally I’m interested.
> 
> Seems like a plan, lmao. But fr isn't the point of RP to be immersed? There's no such thing as too much immersion. I have trouble getting immersed when something like a gemstone blows up in my face. It's like growing weed and then suddenly the plant starts on fire. Where's the fire coming from? How did it catch a light so quickly? These are the kinda things I would think.

I'm not saying make it so gemstone mining has no risks, I'm saying change the risks so they actually make sense.

**Comment by seamarob** [comment]
Yes, but the suggestion just seems to push for mining to be easier to make money rather than to increase immersion. Like instead of exploding you inhale a toxin that takes you out as punishment. I think the exploding is hilarious though.

**Comment by Hebby11** [comment]
> 

See knocking you out I wouldn't have a problem with there's an actual disease you can get from inhaling particles from stuff you mined irl.

**Comment by Hebby11** [comment]
> Yes, but the suggestion just seems to push for mining to be easier to make money rather than to increase immersion. Like instead of exploding you inhale a toxin that takes you out as punishment. I think the exploding is hilarious though.
> 
> By the way that weed thing would be crazy and probably be an idea for house fires to boost BCFD RP hehe

See knocking you out I wouldn't have a problem with there's an actual disease you can get from inhaling particles from stuff you mined irl.

And as long as they gave a logical reason for the weed thing I wouldn't mind it. Like adding the requirement for a grow light because you could have the grow light short circuit or something and start the fire.

**Comment by coalaura** [comment]
mining is very lucrative, if blowing up is ruining your immersion then i cant help you
