### ISSUE TITLE
Suggestion - Add a notification when you complete a daily task

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#2841]
### Assurance

I have read the `README.md`

### Summary

Have a notification display when you have completely your daily task.

### Reason

I played way too many rounds of blackjack because I kept losing count with how many I have done (definitely not because I have a gambling additiction). It would be nice to have a notification display when you complete a task in order to confirm it is done instead of having to drive to the market to check.

**Comment by V4P1Dx69** [comment]
One time I did the `goto cayo` mission. I went there with boat and spent some time there but after coming back I saw nothing was done. So adding a Notification for this would be great!

**Comment by InZidiuZ** [comment]
This has now been done as shown [here](https://inzidiuz.com/N13SuA.mp4).
