### ISSUE TITLE
Suggestion - Adding Arcade Bar Hotline(Favourite) on Phone 

### ISSUE THREAD

**Issue by V4P1Dx69** [InZidiuZ/op-framework-issue-tracker#2842]
### Assurance

I have read the `README.md`

### Summary

Adding an Arcade bar option on the Phone
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/64460439/c6fd09d2-7727-48bb-bf34-92bb843d20c0)

### Reason

This feature will help other players to interact with arcade bar employees easily and conveniently. Also unlike arcade bar other business like burger shot and mechanic has the same feature for them in the phone. So Arcade Bar should get one on that basis.

**Comment by coalaura** [comment]
but why do they need one?

**Comment by V4P1Dx69** [comment]
I just explained that in the **Reason** section. Also for the same reason comedy club and Burgershot have that u may say. I personally felt to have it ig after facing sort of problems. So adding this is purely logical according to me.

**Comment by coalaura** [comment]
burgershot has it since they deliver food same for bean machine. Comedy club imo shouldn't even have one arcade same thing i see no need. Your explanation was "helps interact" i was asking you to provide some more context as to why you think it should be added

**Comment by King2704** [comment]
I think it could help in the case of people asking for arcade employees, with the z pills being on the daily tasks a lot of people keep tweeting out "arcade open?" which could instead go through the phone line now. Or maybe the arcade could then deliver it to them.

**Comment by MetaHatter** [comment]
Agree that it is not needed, nor is the comedy club one.  

TBF I also do not feel BurgerShot or Bean Machine should have them either.

IMHO Businesses are ideally congregation points for multiple people, that normally wouldn't meet, to run into each other and interact.  Deliveries, although "easier", run counter to that.

**Comment by V4P1Dx69** [comment]
My initial point for this was always the interaction. 

Yes, we do interact with the customers through Twitter but sometimes they write down their phone numbers on Twitter and tell us to call them back when we're available. So adding this will help us to get their number on our phone directly and we can call them in seconds. 

Also, *Twitter* as a communication medium isn't as good as *direct phone calls* or *messages*.
I myself feel this very painful to save their phone number from Twitter and then call them back. Also if that's an actual feature we can also supply them bulk amounts easily anywhere.

Maybe I shouldn't bring other business hotlines reference here as context, but facing those problems makes me want this feature more than ever.

If you feel this explanation is worthy you can go for it. 

**Appreciate everyone's time and efforts on this thread <3**

**Comment by DaxterPancake** [comment]
I can personally see the appeal to allowing the Arcade to have its own phoneline. Zombie Pills have ALWAYS been extremely popular, even before they were a daily task. I get into the server at odd times and feel it would be extremely nice to be able to message the Arcade line directly to try and get a delivery of pills, food, alcohol instead of asking on twitter. Just a personal preference thing and as stated above, our current phone has limitations such as not being able to easily copy a number from twitter, whereas if you are texted, you can reply directly to the text.

**Comment by keepcodingstar** [comment]
i think every business should have a phone line at least. Some business having phoneline some not for xyz reson does not do justice to others. Not just arcade make a business section and in it add all businesses.

**Comment by Dibbey** [comment]
> "a lot of people keep tweeting out "arcade open?"

Regarding that, it does end up on Twitter **a lot** pushing out any other tweets or ads for businesses on twitter that share they are open.

And while I don't think every business needs a phone line, Arcade is usually the most asked one on Twitter next to PDM. A phone line could allow direct contact and less traffic of constant "Arcade?" / "Need Zpills, arcade?" tweets. At least in my opinion.

**Comment by KaiEagle** [comment]
tbh I would really like to see restaurant hotlines. 
Reason: Twitter is always spammy with things so it's hard to look whether someone needs something or not. Also when there is no customer around ofc the employee will go out to chill out a bit and when he is out then the customer comes so it's better to have a hotline so people can text it to call for employees.

**Comment by coalaura** [comment]
done
