### ISSUE TITLE
Suggestion - New Job: Hacker

### ISSUE THREAD

**Issue by Ruizixia-Shimizu** [InZidiuZ/op-framework-issue-tracker#2843]
### Assurance

I have read the `README.md`

### Summary

A new "hacker" type job that could include services such as getting rid of a criminal record, temporarily registering a local car to someone, forging ID's and firearm registrations, slightly increasing odds at the casino, being able to create things like fuses and tuner chips among other things that could be expanded upon in the future as more stuff is added. Some additional things that could be added to make this job more viable would be warrants for arrest which could give cops more of a reason to pull people over or talk to them on the street if they matched the description of someone they are looking for or other reasons and increased prison sentences to deter committing repeat or additional crimes without purchasing these services. It should probably be gated behind something like how some workbenches require being in a whitelisted gang maybe behind a test of some sorts?

### Reason

I'm not sure how it could be a good change to just the framework but It could add more variety and dynamic to the RP experience as well as give players more incentive to obtain money to purchase said services. It could also encourage more interaction between players if such services were available and contribute to a more semi realistic experience when committing crimes. I also think it could just be a fun way to spice up the crime system!

**Comment by coalaura** [comment]
> getting rid of a criminal record

"Records" per say are not part of the framework, they are done differently by each subdivision

> temporarily registering a local car to someone, forging ID's and firearm registrations, slightly increasing odds at the casino, being able to create things like fuses and tuner chips among other things that could be expanded upon in the future as more stuff is added

Generally all seems VERY overpowered imo

**Comment by Ruizixia-Shimizu** [comment]
ok that's fair for the records. And it could be limited to a certain amount of times per day or require lots of ingredients for the crafting but understandable if its too overpowered!

**Comment by Hebby11** [comment]
> ok that's fair for the records. And it could be limited to a certain amount of times per day or require lots of ingredients for the crafting but understandable if its too overpowered!

Seems like a good idea to me. If it's not balanced then that seems like a skill issue to me.
