### ISSUE TITLE
Suggestion - Headshots

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2844]
### Assurance

I have read the `README.md`

### Summary

A gun, no matter the gun, should kill with one shot to the head.

### Reason

Shooting someone in the head and having them return fire is not realistic roleplay.

**Comment by MetaHatter** [comment]
Shooting someone in the head ends the roleplay with them. Higher TTK gives people more time to RP.

And there are MANY occasions IRL where a bullet to the head does not kill.  Unless you hit them right at the base of the skull, near the cerebellum, it's not a guaranteed kill. Humans are way more resilient to dying than people give them credit for.

**Comment by KaiEagle** [comment]
The thing you talking about is already in the server and it can be enabled through config but every server hates to see that the fight just ends in 1 bullet also if this thing is enabled then cheaters will use aimbot with head only and ofc you don't want that. The thing you talking about of IRL we cannot always compare RP with IRL things.

**Comment by InZidiuZ** [comment]
As @KaiEagle said, this is already implemented in the framework [here](https://github.com/InZidiuZ/op-framework-public/blob/8028b12f0dfb032b8eff97bb1d72ed5b8e813687/configs/cluster1.cfg#LL20C1-L20C1).
