### ISSUE TITLE
Zombie pill too nerfed?

### ISSUE THREAD

**Issue by therubinpotato** [InZidiuZ/op-framework-issue-tracker#2845]
### Assurance

I have read the `README.md`

### Summary

people are paying so much for nothing
so there is very less rp for arcade

### Reason

would be better if stash is added in arcade thank you

**Comment by MetaHatter** [comment]
Or maybe the arcade is simply charging too much?

**Comment by coalaura** [comment]
i dont think they are too nerfed

**Comment by therubinpotato** [comment]
it cost 1210 + tax 
people are not willing to buy at that price
the max you can get is 1400 or less if you are new
so people never have 2nd thought of buying this

**Comment by coalaura** [comment]
i updated my comment
