### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#2846]
### Assurance

I have read the `README.md`

### Summary

I propose that vape refills at Green Wonderland come as purchasable cartridges that can be combined with an empty vape. 

### Reason

The premise of refilling the vape stays the same, just removes the reliance on having an employee of Green Wonderland around to refill it for the user. Green Wonderland is often the target of chaotic behavior from new people. Most of us do not feel comfortable being there alone, combine that with people's work schedules and lives outside of the game. Green Wonderland is not open enough to provide the demand of vape refills.

**Comment by coalaura** [comment]
I don't think this would be a good idea. I see your concern but this would encourage employees not to be at green wonderland and discourage the RP that happens there
