### ISSUE TITLE
Bug report - vw_prop_vw_cinema_tv_01 screen offset adjustment

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2847]
### Assurance

I have read the `README.md`

### Reporter

hellofthedevil

### Summary

The prop vw_prop_vw_cinema_tv_01 requires a screen offset adjustment as the screen is in the middle of the object and unable to be viewed unless you're noclipped inside the prop, the screen aspect ratio also needs to be adjusted (pictured below)

### Steps to Reproduce

Place down the prop and use the remote to try watch something

### Expected Behavior

you should be able to watch something

### Actual Results

you are unable to watch anything but can hear everything

### Screenshots/Videos

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/4959366/fdee9bdd-9a0c-4fd4-b3ea-7d9419b5a805)

### Game Resolution

1920x1080

### Server

OP-FW Test Server (c2s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This has now been done!
