### ISSUE TITLE
Bug report - Battering Ram Instance Issue

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2848]
### Assurance

I have read the `README.md`

### Reporter

Arteria

### Summary

Bug Portion

When using the battering ram, you will be stuck in the apartment/house's instance when you leave again. This seems to only affect anyone who is in the vicinity and changes. The person who uses it may have to F8 some times, others who don't use it may have to. Varies each time. The only way to fix this is by F8 quitting and relogging. 

This seems to happen a lot but there has been times where it works as intended. Out of the last 3 raids Ive been apart of, 2/3 of them messed up.

### Steps to Reproduce

Using Battering Ram on a Property

### Expected Behavior

Walk out in the "real" instance of the server

### Actual Results

Stay in the same instance as the house, but now outside.

### Screenshots/Videos

Unfortunately don't have a recording of this happening. 

### Game Resolution

1920x1080

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
I've rewritten the battering ram functionality. It should now work and give anyone within 3 meters of the person using it access level 3 (max) to the property for 20 minutes. I've also removed the cooldown.
