### ISSUE TITLE
Suggestion - Battering Ram Message Change

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2849]
### Assurance

I have read the `README.md`

### Summary

Small request to change the Alert for battering ram to indicate something else. 

Such as "Alert - Police Breach at *property*" 
or something along those lines.

Just noticed that some people mistake the current one for an actual house robbery some how :/ 
Also maybe a sound would be cool. 

### Reason

So people don't accidentally avoid RP :kekw:

**Comment by DaxterPancake** [comment]
I might be misunderstanding what you're trying to say here, but if an alarm is set off, you wouldn't know WHY unless you have cameras (which we don't have for houses) so therefore if they are not coming due to thinking it's not a big deal, is that not on them?

**Comment by ImArteria** [comment]
Yea you right
