### ISSUE TITLE
Vans - Bodies in Trunk

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#285]
**Name:**
Scrubject#1646

**Summary:**
As if now, unless very recently changed it is impossible to carry people into the back of a van like you can with a trunk.

**Reason:**
I think it's drastically more realistic that you could put a body or injured person in the back of a van, opposed to the engine of a sports car for example.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
