### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by rishabmishra0341** [InZidiuZ/op-framework-issue-tracker#2850]
### Assurance

I have read the `README.md`

### Summary

we want some changes in the mirror park repair shop because the interior of the shop is too dark

### Reason

In legacy India mirror park repair shop is one of the best mechanic shop compared to other shops because we guys give 24 hours service but the main problem or suggestions we are getting from our customer that is there are no lines by which customers can get to know which is the repair bay and where they have to place there cars for repair and the second thing is its interior it seems to be too much dark and there are very less lighting inside it and some suggestion which we want to provide that is there is no proper logo of the shop there is one but that is too much blurry and there are total 6 work bench but only 4 bay are there for repair 3 in front and 1 at back so if you guys can increase the repair bay or add some washing stuff instead of the work bench it will look good i have a mlo video of this shop which looks fantastic i will share with you guys if possible you guys can add that because the interior lighting, the exterior everything looks amazing of this mlo.  Thank You

https://youtu.be/zZgusF89vbw

[](https://youtu.be/zZgusF89vbw)

**Comment by coalaura** [comment]
this would be an asset suggestion: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
