### ISSUE TITLE
Suggestion - Group funds app / joint accounts on tablet

### ISSUE THREAD

**Issue by BigPimpinBaby** [InZidiuZ/op-framework-issue-tracker#2852]
### Assurance

I have read the `README.md`

### Summary

Basically just a similar system to your /company tablet, but you can give access to a joint acount with a cid. This would allow people to gather group funds without needing everyone to be in the city at once. Ideally it could even be categorized into separate groups, like "rent" "illegal activities" "event funds" etc. Would also be very helpful to have timestamps with names and dates included to keep things clear, and to prevent stealing. Group funds could be used with  just /company, the tablet itself, or maybe even locked to doing it inside of a bank. 

### Reason

Sometimes it's just very difficult gathering funds for things as a group. I understand you want the RP of actually meeting up, but sometimes it's not possible or just takes a long time to get money from multiple people. It would be incredibly useful for the multiple examples I listed, as well as other things I haven't considered like business implications. It could also add to cop/fib RP if that information is accessible for a raid. Kind of adds a risk to the convenience. W

**Comment by CloudTheWolf** [comment]
+1 for this
It's a pain maintaining "Personal account" and "Gang account" since paying rent comes from the same balance

**Comment by txxlrrsCoding** [comment]
+1 for this

**Comment by ayushpatel1007** [comment]
/savings account is introduced. We can close this issue now.
