### ISSUE TITLE
Suggestion - Scratch Serial Numbers off Guns

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2853]
### Assurance

I have read the `README.md`

### Summary

It would be cool to have the ability to remove the serial numbers from a gun, allowing groups to take personal guns and remove the serial numbers

### Reason

Currently I think many people get a personal gun and end up just scrapping them, making any guns you get from z pills worthless. It could also become a business for a group to hand your guns over and pay to remove them

**Comment by coalaura** [comment]
I feel like this would be abused as people would buy weapon license guns and remove the serial number and sell them

**Comment by AaronSmithCoding** [comment]
Yes I agree that could be a concern but with the price of the guns its cheaper to buy from jim or others in city etc? I was thinking more for the ones you find in z pills etc
