### ISSUE TITLE
Suggestion - New Hacking Ideas 

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2854]
### Assurance

I have read the `README.md`

### Summary

These are a couple potentially cool ideas to add to the raspberry pi:

1. Ability to hack a car registration - the result would be the owners name
2. Ability to hack a radio frequency - the result could be  as minimal as returning the number of people connected to that frequency
3. Ability to hack Jims locations - something random like this would be cool to help with finding him and could allow him to be placed anywhere not just in the current common places
4. Ability to temporarily disable a close vehicle - cop chases would be pretty funny if you could disable them for a few seconds to give a little headstart

### Reason

I think a lot of people try to ask cops about car reg numbers and sometimes get a name back from them. This would allow people to do this more often very similar to the phone number hack

The radio frequency one is cool because say your doing daily/weekly security checks on your group and there are 10 of you but doing the hack returns 12 people connected. You know then that you have intruders and need to switch frequency etc

**Comment by coalaura** [comment]
1. Ability to hack a car registration
Believe you can already do this with a raspberry?

2. Ability to hack a radio frequency
You can already do something like this (find out in rp)

3. Ability to hack Jims locations
You can already do something like this (find out in rp)

4. Ability to temporarily disable a close vehicle
You can already do something like this (find out in rp)

**Comment by AaronSmithCoding** [comment]
1. Hey so I checked a raspberry and there wasn’t any command in listhacks for car reg lookup unless they are there but like hidden/secret etc?

**Comment by KaiEagle** [comment]
There is actually but it's hidden.

**Comment by AaronSmithCoding** [comment]
Ok say no more :)
