### ISSUE TITLE
Suggestion - Import/Export Changes

### ISSUE THREAD

**Issue by AaronSmithCoding** [InZidiuZ/op-framework-issue-tracker#2855]
### Assurance

I have read the `README.md`

### Summary

I have been using this import/export on cayo and had some ideas that might help make it more usable

1, Allow people to put items in multiple times before submitting/confirming 
2. If I choose company A to take my stuff then I should be allowed to still use company B and C 

### Reason

1. - This would be good as we have a 500lb limit but unless your lucky to be overweight then its only ever 250 max at most so you could do 2 runs to the computer and deposit a full 500lb
2. - If the above isnt possible then allowing us to deposit 250lb into all 3 companies at once would be great :)

**Comment by coalaura** [comment]
> Allow people to put items in multiple times before submitting/confirming

This would lead to people abusing it as storage, i intended for the items to be not retrievable once put in

> If I choose company A to take my stuff then I should be allowed to still use company B and C

I dont quite get this? You pick one company to ship your stuff not multiple, how would multiple companies ship the same items???

**Comment by AaronSmithCoding** [comment]
I agree there is a design question with the holding as storage, but you could do similar to the jackpot but it could take 50% every 5 mins if left in (given a 15 min period to allow to fill a second time from garage etc)

The second part was more to do with say I take 250 and use Company A submit confirm and thats gone off on its way...then I go to car and get another 250's worth and then choose to export that with CompanyB...so basically in LSIA I could import from all three companies at once and ship 750 worth of materials between the 3 companies
