### ISSUE TITLE
Suggestion - New Food Suggestion, with new Restaurant 

### ISSUE THREAD

**Issue by Arther0007** [InZidiuZ/op-framework-issue-tracker#2856]
### Assurance

I have read the `README.md`

### Summary

Hi I am a GTA V role player in legacy server in INDIA and Bangladesh Server. As we already know we have 3 active food center in our server. Burger Shot, Bean machine and Susi Restaurant. Where in burger shot we getting some burgers it use to like snacks and Bean machine is a cafe. We need a restaurant in this servers who serve proper Lunch or dinner items. Some items like Biriyani, Fish thali, Chicken thali, Beef ribs or pork menu. It will be great if you introduce these new foods to the server with a new resturent, might be in CAT restaurant.   

### Reason

It will make a huge changes to attract people in these servers. Also as there will be a new restaurant it will Hype the server. New RP will be performed.

**Comment by coalaura** [comment]
I like it but also, burger shot IS a restaurant. A full on burger is not a snack, thats a meal

**Comment by coalaura** [comment]
this would need roleplay and an MLO first
