### ISSUE TITLE
Fine proximity

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#2857]
### Assurance

I have read the `README.md`

### Summary

Can we have proximity in fine too just like jail?

### Reason

Because recently many cheaters and people who were supporting were banned so their friends started coming to the server and started fining everybody on the server if there is a proximity just like jail this could be prevented not entirely but at least won't be able to fine everyone :(

**Comment by coalaura** [comment]
there is already a check for distance
