### ISSUE TITLE
Suggestion - New Food at Burger Shot 

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2858]
### Assurance

I have read the `README.md`

### Summary

Hello! I would love to request the actual advertised foods to be put into Burger Shot. Having them would greatly help enhance the RP  & bring some excitement back to Burger Shot. 

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/7355d85a-4e62-43d5-b6fd-16bccc5ff8b5)

I believe that having these items being in the restaurant would be more beneficial and special to bring people into the establishment. 

Currently you can go get food from 24/7's, fruit stands, and Cayo. Having something "exclusive" at burger shot [like bean machine has their cupcakes and lemonade and whatever else], would enhance RP. Oh hey, its a hot summer day lets go get ice cream from Burger Shot! etc. 
![chickenbacon](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/5a11ff80-ba68-402e-b22f-20e802378384)
![burger2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/0b653480-a2f0-4ba8-990d-b17d0b93a79f)
![chickentaco](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/085f3f55-382c-4dfd-b775-957c13834b8a)
![heartstopper](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/dbfaf040-25e6-4cd4-95cf-a467b34b5291)
![burger1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/8762b91a-cdec-45c2-a8b9-69fa08416215)
![chickensand](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/9cede89f-fccf-4865-8769-049f733108ec)
![doublebur](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/5eb034ba-2145-49fd-aa03-d06170c2a3bf)
![Meteorite](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/b844f4ef-9920-4ba0-b70c-c03a5eea84dd)
![orangeO](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/ee8d2e4e-566a-4646-9a9f-874bd01a318a)
![chicken](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/c7375f69-61e6-48a6-b7c1-63e3136cc1d0)
![beefwrap](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/9b07d510-d813-4ddb-9ce0-89a1e060231c)
![soda](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/bab6139e-2e4e-4498-9326-4f00ab27b046)
![fries](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/90532434/4a85a820-c1e4-46b6-815d-0414a2a1864f)
 

### Reason

It would be a good change to increase and enhance RP and bring some new excitement to Burger Shot!

**Comment by seamarob** [comment]
I think having more exclusive food would be of benefit, especially with new people that haven't RP'd before. With this addition the activity for Burger Shot should see an increase with people and employees.

**Comment by coalaura** [comment]
This is the same suggestion as this #2681? Closing duplicate
