### ISSUE TITLE
/Clothes Commands

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#286]
**Name:**
Scrubject#1646

**Summary:**
Definitely a minor, quality of life improvement,  but i think it would be nice to have commands similar to /hat, /glasses, etc for each if not most types of apparel.

**Reason:**
It'd be nice to be able to take off my shirt without going to a clothing store. For swimming etc.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
