### ISSUE TITLE
Suggestion - Phone app to display mechanics that are open

### ISSUE THREAD

**Issue by BigPimpinBaby** [InZidiuZ/op-framework-issue-tracker#2861]
### Assurance

I have read the `README.md`

### Summary

Basically just a simple phone app where mechanics could check in, and it turns a little red circle to green next to the name of the shop. Or empty boxes and you can put a checkmark etc. 

### Reason

Would pretty much entirely remove the need to post ads on twitter. Simple way to see how many mechanics are available at once. W

**Comment by BigPimpinBaby** [comment]
Or tablet. Possibly have some sort of proximity setup, so if you leave the shop it will automatically clock you out in 5 minutes if you forget to do it manually.

**Comment by AaronSmithCoding** [comment]
Yeah I think for anything like this it can’t rely on people to manually check in and out etc people forget as it is already lol

**Comment by Brundoggy** [comment]
Yellow pages would be amazing

**Comment by CloudTheWolf** [comment]
Yeah, atm using twitter makes things messy, but probs could get a "Yellow Pages" or "Business Feed" that players can use to advertise shops are open, events happening etc

**Comment by gadjinee** [comment]
Could we have maybe an app like just an app on the phones that would display number of mechanics on duty, kinda same as ems. But for example in that app you have all the shops listed and in front of it has a number of mechanics clocked in

Don't know if that's the idea for yellow pages

**Comment by CloudTheWolf** [comment]
> Could we have maybe an app like just an app on the phones that would display number of mechanics on duty, kinda same as ems. But for example in that app you have all the shops listed and in front of it has a number of mechanics clocked in
> 
> Don't know if that's the idea for yellow pages

Mechanics don't go on/off duty the same way as PD/EMS and just seeing a number showing mechanics on duty would take away from the RP. (Also how would you know which mechanics are open when is says "1 Mechanic Available")

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/E8TVBS2L19.webp)
