### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/op-framework-issue-tracker#2862]
### Assurance

I have read the `README.md`

### Summary

 I would like to propose the addition of two rescue baskets and the acquisition of new helicopters to our fleet. These enhancements have the potential to significantly enhance our search and rescue operations and ensure the safety and well-being of our community.

### Reason

Rescue Basket:
A rescue basket is a versatile and indispensable tool that allows for the safe and efficient extrication of individuals in distress. Here are some key reasons to consider its implementation:

The rescue basket has two different versions which are both useful. Both provide a secure and stable platform for safely lifting and evacuating victims from hazardous or hard-to-reach locations, such as high-rise buildings, steep terrains, or confined spaces. 

Additionally, The basket provides an added layer of safety for our rescue personnel, minimizing the risk of injuries during extrication and transportation.

Last but not least the RP from this would be intense and something completely new to the server.

These are the rescue baskets and we are willing to pay for them:
https://store.londonstudios.net/category/resources
https://www.youtube.com/watch?v=1KchlnDtQi4
https://www.youtube.com/watch?v=dPHkLRmANRs

New Helicopters:
Upgrading our helicopter fleet is another crucial step towards enhancing our search and rescue capabilities. The following advantages highlight the importance of acquiring new helicopters:

Currently, we have the Maverick which says ambulance on the side of it originally we wanted to change this however we found out that it's pretty much impossible so we would like to ask for the SWAT little bird to possibly be added to the BCFD spawner at the station. Obviously, it would need our logo and not SWATS.

Additionally, we are unable to access the rescue helicopter that has floats on the bottom as it's all the way down at Mt. Zona so moving that to the BCFD spawner would be amazing.

**Comment by kaycorriher** [comment]
I personally would love this addition because I can't wait to have epic rescue missions for the Fire Department to handle

**Comment by craig9333** [comment]
I wanna see this as well because there will be more rp for the BCFD and plus we can defo help more people with in the city with doing this and when it's a fire we can help them more as well

**Comment by mastersamii** [comment]
Realized that this was posted in the wrong github 😢 
Closing it so I can move it to the other one. <3
