### ISSUE TITLE
Crafting Ideas 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#2863]
### Assurance

I have read the `README.md`

### Summary

It would be cool to have some more crafting in the city.

Breakdown items into rubber - We can break others down Alum,Steel,Scrap, Glass but not rubber
Craft Acid - It is a viable way for people who already have a WL job save having to purchase from or rely on others
Craft some spy gear - Listening devices, short range cameras
Gun Skins - Can never have enough gun skins 🙂
Grenades - Would be fun to have some smoke grenades, gas grenades and explosives....looking in arena there are pipe bombs/C4 etc
Convert Coke bricks into crack - A fun extra to cocaine which could sell for smaller bags around the city southside
Convert Medkits into IFAKS - A nice extra for shootouts 😄
Breakdown cleaning kits for Ammonia or any other chemical
Crafting Fake License Plates - Steel, Paint, Rubber etc etc

### Reason

I think each one on their own would be a great addition to the city. Many people prefer the exploring/crafting side of the city rather than chases and shootouts so these types of crafts would be great for those people. 
Each one I dont believe is deemed powerful or takes away from any other process/gang in the city

**Comment by Mugdha57** [comment]
& To be honest gas mask should be in crafting/Jim not directly in gun store.

**Comment by AaronSmithCoding** [comment]
ohhh I love these ideas :D

yeah the gas mask made with rubber,poly resin etc would be a cool one :D 
I like the idea of crafting/breaking down more of the items from tool shop/ammunition as there are some cool items in there that could be used

**Comment by coalaura** [comment]
> Breakdown items into rubber

I will add something for this

> Gun Skins

Already a thing

> Grenades 

Already a thing

> Convert Coke bricks into crack

You can already break down coke bricks into bags

> Breakdown cleaning kits

There is other things already that expand the usage of cleaning kits

> Crafting Fake License Plates

I don't think they need to be craftable, i quite like the way you get them currently its pretty balanced

> Convert Medkits into IFAKS

Don't really think this is needed since there is oxy which is 1 to 1 exactly the same

> Craft Acid

Purchasing from others encourages RP, you would be suggesting to remove RP by having people not need to interact with others

**Comment by gadjinee** [comment]
Craft Acid
My reply to this is I feel it would benefit RP because another group could hold the process of crafting it in larger batches and sell it to other groups etc. There are so many groups in the city it would be nice for them to hold another process

Grenades
I would ask, "if any more clarification is possible? Are we saying there is a way to create pipe bombs or frag grenades in the city?"

**Comment by coalaura** [comment]
Crafting acid i don't see a need for. I don't want another process that is held down by groups.

Crafting grenades, no you cannot and will never be able to craft explosives in their current state. They are not fit for RP. However you can craft gas grenades

**Comment by gadjinee** [comment]
> Crafting acid i don't see a need for. I don't want another process that is held down by groups.
> 
> Crafting grenades, no you cannot and will never be able to craft explosives in their current state. They are not fit for RP. However you can craft gas grenades

Fair enough, would be cool to be able to craft Smoke Grenades beside Tear Gas
