### ISSUE TITLE
Bug report - Helicopter Scuffs

### ISSUE THREAD

**Issue by kaycorriher** [InZidiuZ/op-framework-issue-tracker#2864]
### Assurance

I have read the `README.md`

### Reporter

kay.32

### Summary

Various Reports of Helicopters scuffing at various helipads so I went around and pulled all the Standard Helicopters the people can get at all helipads. 

Helipad Analysis: https://docs.google.com/document/d/1Hw6ykq0-tKbs07a5Cj62Eu2jli6ZRSvy2HUBP8sFtOQ/edit?usp=sharing
(Additionally, in this document I have added two different helicopters with broken propellers. Nothing user critical just if we want to clean them up)

In Summary: 
Both Commercial Helicopters "Bounce" at Maze Bank Tower 
https://medal.tv/games/gta-v/clips/1huebnhuzarmW2/d1337hqHwaeB?invite=cr-MSxpdUksOTQ2Njg5NDUs

Sea Sparrow and Sparrow kind of like flip around when spawning and could not reproduce the helicopter blowing up
https://medal.tv/games/gta-v/clips/1huebnhuzarmW2/d1337hqHwaeB?invite=cr-MSxpdUksOTQ2Njg5NDUs
https://medal.tv/games/gta-v/clips/1huiy0a-NktmV5/d1337T9Z6ZDj?invite=cr-MSxNVWgsOTQ2Njg5NDUs

### Steps to Reproduce

Pull Helicopters out at various helipads

### Expected Behavior

Helicopter on Helipad

### Actual Results

See Summary

### Screenshots/Videos

See Summary

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Fixed
