### ISSUE TITLE
Suggestion - alternative hairstyles

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/op-framework-issue-tracker#2865]
### Assurance

I have read the `README.md`

### Summary

Since we have two available hairstyles most of the time, it would be really nice to be able to customize both rather than just have one nice hair and one bad one

### Reason

It would make the changing hairstyles option more usable.

**Comment by DaxterPancake** [comment]
That's not the point of having it, the point is that you can put your hair up and down into a ponytail and also have the ability to have a hairstyle you can wear with hats if you like using addon hair.

**Comment by coalaura** [comment]
like daxter said
