### ISSUE TITLE
Bug report - Moonshining is scuffed

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#2866]
### Assurance

I have read the `README.md`

### Reporter

hellofthedevil

### Summary

so after a report of moonshining being scuffed i tested it in the test server and it is indeed scuffed, you can put the ingredients into the distillery, wait for the fermentation, but as soon as you try and remove the moonshine you don't get anything and you can't walk around anymore, even after you /e c or hit x.

eventually you end up timing out from the server and do not have the moonshine or the ingredients anymore.

### Steps to Reproduce

1. Go to the moonshine spot
2. Insert the ingredients into the distillery
3. wait for fermentation to complete
4. Attempt to remove the moonshine from the distillery (this is where it scuffs)

### Expected Behavior

it should provide you with moonshine

### Actual Results

it stops you from moving then eventually times you out

### Game Resolution

1920x1080

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
already fixed
