### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by balli24** [InZidiuZ/op-framework-issue-tracker#2867]
### Assurance

I have read the `README.md`

### Reporter

balli

### Summary

after getting killed while mining i died andnow i cant respawn to the hospital and just loading with a black screen is running.  this thing is only happening with my main id and another user is working perfectly

### Steps to Reproduce

want some solution

### Expected Behavior

solution of this issue or transfer the data equipmnts and money to my seperate user or new id later i will delete it

### Actual Results

![Screenshot (347)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/138998718/fbb645ee-2303-465e-b495-bfa46cce38a1)

### Server

OP-FW Test Server (c2s1.op-framework.com), India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
this is fixed
