### ISSUE TITLE
Suggestion - Small thing but so usefull

### ISSUE THREAD

**Issue by callmeeJeff** [InZidiuZ/op-framework-issue-tracker#2868]
### Assurance

I have read the `README.md`

### Summary

Added 3 dots above head when typing in in-game chat.

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/93746728/ad13aa95-d52f-4ae7-bdec-bef8c5889df2

### Reason

Adding this small option will ensure that players won't be competing with each other in /me commands and everyone will be able to calmly respond to narrative commands in the right order. In addition, it helps in non-verbal communication between players. Of course, it would have to be done so that administrators using commands when spectating people would not have a problem with the fact that 3 dots would be displayed above their heads. I think it's a very small thing and very helpful.

It is important that these dots are displayed using the chat and not only with narrative commands, because for example it can also be used for communication using /looc between players.

**Comment by Gr00byss** [comment]
So good suggestion

**Comment by scufflord** [comment]
As this has moved trackers I'm just adding my comment back on here: 

This just feels super immersion breaking.

**Comment by coalaura** [comment]
yeah like arteria said
