### ISSUE TITLE
Vests as Undershirts

### ISSUE THREAD

**Issue by Scrubject** [InZidiuZ/op-framework-issue-tracker#287]
**Name:**
Scrubject#1646

**Summary:**
I've been told you plan on redesigning the clothing system, But i'd like to suggest that vests are duplicated into the undershirt category if that's possible. 

**Reason:**
It would be really nice to be able to wear my cut over the various shirts in the shirts category. Currently our options are T-shirt, or no-shirt.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not happen.

**InZidiuZ**
*OP-FW Developer*
