### ISSUE TITLE
Milk - More love for minecraft 

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2871]
### Assurance

I have read the `README.md`

### Summary

Players should be able to take a bucket and fill it with milk from a cow. 

> Milk Bucket - 15lb

Once an empty bucket is used on a cow. Fill one bucket and prevent usage on same cow for a duration of time.

Cool ideas

- Milk Bucket + Fruit + blender = Flavored Milk Bottles eg. (Strawberry Milk)
- Milk Bucket + Glass = Milk bottles
- Milk bucket + Coca Beans + Blender = Chocolate Milk

### Reason

- Interesting Idea
- vErY uNiQuE

**Comment by coalaura** [comment]
You can now milk cows

![yes](https://i.shrt.day/qebEGUra01.png)

and create milk-shakes using the blender

![epic](https://i.shrt.day/fIHUMemE16.png)

**Comment by vol5** [comment]
POG
