### ISSUE TITLE
Suggestion - Nightshade Block

### ISSUE THREAD

**Issue by KingOTL** [InZidiuZ/op-framework-issue-tracker#2874]
### Assurance

I have read the `README.md`

### Summary

Nightshade are moving blocks and we've looked around the city and only place we found and kept coming back to this place we know its a big ask to get it done but we thought it was worth asking 

https://cdn.discordapp.com/attachments/1125121486814969987/1125536377057071264/image.png
https://cdn.discordapp.com/attachments/1125121486814969987/1125537728080130189/image.png
https://cdn.discordapp.com/attachments/1125121486814969987/1125537458436714568/image.png
https://cdn.discordapp.com/attachments/1125121486814969987/1125537286197612644/image.png

### Reason

Our old block was owned by the old leader and nobody in the gang liked the block, we will mainly use this as a community house, the hotel is a great location for all of us to chill hang out and host events with how big the hotel is. We would only need 1 house inside preferably a high-end apartment but if there was multiple houses on the block then the beach house interior would probably work best.

**Comment by coalaura** [comment]
I don't see how this is a dev issue???
