### ISSUE TITLE
Suggestion - Videogeddon Private Garage

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2875]
### Assurance

I have read the `README.md`

### Summary

Garage under Arcade:

Most businesses have garages, albeit, they are open to the public with the exception of Luxury Autos. Since there's a public garage near Mirror Park, it wouldn't make sense to put another public garage next to the Arcade.

A Private garage could go here:
![ARCADE GARAGE](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/35842572-5840-4aa5-9547-328423150c8d)

### Reason

To assist with our efforts in keeping the Arcade open as much as possible, we have more people spending a lot of time there. Some people even clock in and work behind the counter for hours at a time. This can lead to TWO issues:

1) Employees take up what little space is available for customer parking out front.
2) Employees park under the Arcade and when their shift is over, they go down to discover the car has been claimed by the void.

To avoid having employees stranded after their shift and in an effort to preserve what little space we have out front, it's imperative to have a garage added to the business.

**Comment by coalaura** [comment]
not needed
