### ISSUE TITLE
Hayes repair Shop parking

### ISSUE THREAD

**Issue by therubinpotato** [InZidiuZ/op-framework-issue-tracker#2876]
### Assurance

I have read the `README.md`

### Summary

it would be so easy if there is a private garage for Hayes mechanic to spawn their tow truck

### Reason

the closest parking is in burger shot which is very far
sometimes it gets so busy you need to go find a vehicle just to spawn a tow truck
mosley and mirror park has their public garage so near they can just run and get their tow truck

**Comment by coalaura** [comment]
Mirror park came AFTER the garage, just wanna not that. Also no, no garage needed
