### ISSUE TITLE
Suggestion - Vineyard turned Orchard 

### ISSUE THREAD

**Issue by seamarob** [InZidiuZ/op-framework-issue-tracker#2877]
### Assurance

I have read the `README.md`

### Summary

I was curious if fruits could be gathered via the vineyard essentially making it more of an orchard. This could open the vineyard to being another side job similar to hunting and mining. With the vineyard being a player owned business as well the licensing could be handled via the vineyard owner similar to how the state handles the other licenses. Employees of the vineyard could get a delivery job that lets them restock fruit stands as well. This truck could be an interesting addition: 

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/79816775/9af9257a-cb7e-4b2f-bd7e-e9150f2221e1)

### Reason

This could provide more civilian / business RP while adding another source of income that is a bit different location wise. In the future adding a way that vineyard employees could also make wine from the fruits and sell it to the bars and clubs.

**Comment by vol5** [comment]
#2088 🙏🏿 Here are some extra ideas from forever ago, there may be a few cool ones inside worth peeping.

**Comment by seamarob** [comment]
I appreciate the responses! I feel like a 💩 for not thinking to look for any previous suggestions. I just read through Bill’s previous post and it takes the cake! Outlines pretty much the thoughts I had. I believe with the correct RP this could be a scalable resource.

**Comment by coalaura** [comment]
Closing this in favor of #2088
