### ISSUE TITLE
Suggestion - FIB city building  

### ISSUE THREAD

**Issue by Angadsharmaa** [InZidiuZ/op-framework-issue-tracker#2878]
### Assurance

I have read the `README.md`

### Summary

i suggest to add the personal garage and spawn to only used in fib agents like mrpd & garage . add this garage in the basement of the city IAA/fib building to reduce the challenges of the undercover agent . when fib agent go under cover they need a personal vehicle to track the suspect and maintaining surveillance on suspect its really help full for batter roleplay. because sometime when we  using a unmarked cars would inform public of their existence and MRPD is highly crowed area so sometime when we come out from mrpd in normal civilian outfits and if any officer or a person see this they becoming alert and do less crime     so its damage to the roleplay its a minor change for fib add a spawn point and personal garage inside the basement its only visible for fib  
reason why you shoud add this 
1) why we cant use  public garage after spawn near train or bus station because taking spawn near public site its fear to becoming a hostage or its waste of time 1st we take a spawn near train station after than we run on the road and going to the garage c xd its hard  
2) why we cant use fib head office umm its located out side the city its good for secrete mission or a planing but not good for the maintained a  surveillance because its go far from the city and time wasting and also there is no spawn point or if i surveillance on a person and i got a tip he is  near the mosley  i sudley go under cover and track him is ez 
rest of its depend on you and you are more experience than me i just share my idea with you   

### Reason

as you know when we come out from mrpd and any office see us they just send a msg on there discord group and tell be alert undercover pd is wearing a red shit make a hostage him or maybe just don't come near the home with class 3.  people doing meta gaming haha   its a small suggestion for legacy

**Comment by ImArteria** [comment]
As FIB from international I don’t see the point. The whole point of the FIB facility out of the city is for the secrecy for undercover work. Wouldn’t people just see you guys outside the FIB building in the city just as easy as MRPD since they’re right near each other? 

Maybe just something I don’t understand but as someone in FIB myself, we’ve never had an issue tracking suspects because we would have an FIB agent on patrol communicating to us while we were at the other building getting changed.
