### ISSUE TITLE
Suggestion -  Change the Real Estate System

### ISSUE THREAD

**Issue by RiZiH** [InZidiuZ/op-framework-issue-tracker#2879]
### Assurance

I have read the `README.md`

### Summary

So currently now, only owners has the ability to give house to the player and only owner can access the company tablet. This makes the whole business rp to a single person depended and other members of the company has nothing to contribute, I request you add a feature where the co-owners and other members can also give houses for rent and access the company tablet rather than just having the ability to enter the houses. 

### Reason

Because the ability to give houses on rent is given only to the owner it becomes a problem when the owner is not available in the server or has taken a break from RP due to personal reasons and also there is almost no rp for the co owners and other members of the company

**Comment by xplrerin** [comment]
I feel like I’ve been waiting years for something like this and honestly it is still something I feel is needed!! We can already hire people and give them a paycheck through the /comp, and they can show a property but them just having that extra feature to sell the property will create so much roleplay. This also means current real estate companies across servers can higher people and that also opens a whole new civ rp.

**Comment by coalaura** [comment]
#2357 duplicate
