### ISSUE TITLE
Suggestion - Hayes Garage and Parking

### ISSUE THREAD

**Issue by RetroCharles** [InZidiuZ/op-framework-issue-tracker#2880]
### Assurance

I have read the `README.md`

### Summary

The suggestions below are for Hayes Auto Body customers and employees. These requests are to better the experience for both customer and worker when coming into the shop. The main priority of this request is having an area to accommodate larger vehicles such as semi trucks to get a repair.

### Repair Bays for Larger Vehicles/Semi trucks

**Suggestion 1:** If possible, to extend the bay entrance higher by deleting/editing the boxed areas so that trucks are able to pull into the shop without us having to use a Tow truck to place trucks inside. This process is a hit-or-miss. Trucks are damaged when not towed properly into the shop. 
![image](https://user-images.githubusercontent.com/91626825/216422330-8a4d36ee-4919-4bfb-9075-c81c1c99dd76.png)

**Suggestion 2:** Removing the two trees on the left of Hayes, and placing an outdoor bay on the side walk.
![image](https://user-images.githubusercontent.com/91626825/216422674-bff623f0-79c9-4e38-b1a5-36bc7c3b6f14.png)

**Suggestion 3:** Placing an outdoor bay behind the Hayes shop. We can deal with running to the back to repair trucks. As per [[old request](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/616)] it seems to be more work to implement a door/garage to access the back from inside the shop, if its do-able then by all means it would be even better to have a quick access to the backside, but if its too much we can cope with just walking around the back. 
![image](https://user-images.githubusercontent.com/91626825/216423181-e59402d0-e3d0-4fb1-8e33-d5aaeecd2fc8.png)

### Parking lot near Hayes

Having a parking lot near Hayes can help clear the cluster of mechanic's and visitor's cars being parked on the sidewalks in front of the shop. It would be beneficial for the mechanics/tow drivers to have their tow trucks/rumpos parked close by as well. 

**Suggestion 1:** Parking structure behind Hayes
![image](https://user-images.githubusercontent.com/91626825/216429123-9fe53552-83b1-4dd2-a399-f1f3b23ff6d8.png)

**Suggestion 2:** Parking lot behind Hayes
![image](https://user-images.githubusercontent.com/91626825/216429260-cd1c9484-e537-4604-b088-bf8c4f88c20a.png)

### Hayes Auto Repair body will be able to service all types of vehicles
- Hayes is the only shop that can not service larger vehicles 
- Eliminates the need for the shop to refuse service to bigger vehicles and sending them to a different shop.
- Eliminates the need to use a tow truck to drop the semi into the shop for a repair. 98% of the time doing so will cause additional damage to the vehicle causing the total price of the repair to be larger than the original amount

### Hayes Auto Repair body will be able to park tow trucks and personal cars in a garage near Hayes
- Eliminates having cars parked on the sidewalks
- Mechanics parking across the street or driving to the nearest parking garage (Del perro) to retrieve their tow trucks.
- Quick access for customers to park their car and return to the shop if a repair did not fully "stick" etc windows, doors.

**Comment by gadjinee** [comment]
The shop is getting quite busy lately and having that parking space for employees/ customers cars would make a huge difference in our quality of life 

Tow trucks, material vans and private vehicles ether cause space issue or lag when driving close by

**Comment by KaiEagle** [comment]
I think every Mechanic shop should have a garage nearby.

**Comment by coalaura** [comment]
no parking, it already has a garage not too far away

**Comment by gadjinee** [comment]
Not too far ? It’s not even close , can’t we not move it to closer to yhe shop? 
How come Mosleys and Harmony have shop right next to it and we can’t ?

**Comment by Kay32** [comment]
Will say this if the parking were to be rethinked. I could also add to DOJ also using their office as the elevator is right there.

**Comment by coalaura** [comment]
i just try to avoid having a billion garages everywhere as much as i can

**Comment by gadjinee** [comment]
Having garage where the elevator is at DOJ building it’s a great option as it can be used for both DOJ and Hayes 
Plus it’s already a garage

**Comment by gadjinee** [comment]
We are in desperate need of a garage near by, yesterday for example we had around 5 employees cars outside (tow and material vans) as the locker wasn't enough due to high demand. Over 100 repairs done in couple of hours time, garage nearby will drastically improve quality of life of Hayes customers as well as employees.

**Comment by gadjinee** [comment]
To avoid number of garages around the city could it be role specific ? Like for example pilots have garages at airfield, DOC has one at Prison and PD at station, so for example if you are in city how red as mechanic you could have access to a garage like that at shop

Just thinking about the previous coment of avoiding the unnecessary garages all over

**Comment by RetroCharles** [comment]
I can understand not having a garage everywhere, if that's the case is there a way to see how frequently an garage space is used, and see which garage is the LEAST used in terms of activity and cars stored? IF the garage in DOJ is too close to the one near Del Perro pier, perhaps remove that and replace with the Hayes/DOJ garage.

Some of the mechanics at Hayes put in their own money weekly to have a parking lot for their tow trucks and additional cars with materials as close as they can for Hayes. (which other shops don't have to do since they have a garage on the lot or relatively close by. Having the garage is not only for Hayes, DOJ can also benefit with this. Which is a plus in my opinion. 

The parking lot in del perro, I can only assume is probably just mechanics storing their tow trucks. The houses on near del perro have their own personal garage so i dont see them using that parking lot, and there isnt much civ/crim activites near that lot to have people use that as their main parking lot. Of course this is just my assumption.

**Comment by gadjinee** [comment]
sorry for been a pain but is there any updates on this? please and thank you

**Comment by coalaura** [comment]
I've moved garage G to be below the DOJ office (which is right behind hayes), that should be close enough while still looking like a public parking spot/garage.

![ye](https://i.shrt.day/wuhAPavO67.png)

To compensate for the garage now being further east, i also added a new garage to kinda fill the void of garages in the west.

![epic](https://i.shrt.day/YAJIpaNE17.png)

The outside/big repair spot needing map changes would be something for the asset github: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by gadjinee** [comment]
legend! thank you so much
