### ISSUE TITLE
Suggestion - Change the Helicopter camera location lock keybind

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2881]
### Assurance

I have read the `README.md`

### Summary

Change the helicopter camera lock keybind from left shift to something else, a majority of people who use keyboard to fly have altered their keybind to make shift their lift, but now whenever you use the camera and try to fly at the same time you constantly lock and and unlock the camera for the location lock.  

Or if not change the keybind at least give us a command to disable it.

### Reason

I wanna be able to fly like I used to be able to. Flying through the camera is horrendous now.

**Comment by coalaura** [comment]
what keybind would you like instead

**Comment by ImArteria** [comment]
> what keybind would you like instead

It seems my client is unavailable but space would be ideal.

**Comment by coalaura** [comment]
space it is
