### ISSUE TITLE
Suggestion - Having the /bill come out of bank if out of cash on hand.

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#2882]
### Assurance

I have read the `README.md`

### Summary

Allow this to be a thing so that it allows businesses to charge their customers as the same as the gas stations do.

### Reason

I believe this would be a good reason for more then just businesses such as Burger Shot and other player ran stores. I believe this would allow for people who play things such as attorneys to bill the people they are representing in the cells rather than having to  do work for free. Additionally, I think this would be a QoL improvement for people who are running shops such as Burgershot, because instead of giving cash to the cashier, they could potentially have this go into an account, kind of the same concept as PDM and Midnight, to my knowledge.

**Comment by coalaura** [comment]
already said no to this previously
