### ISSUE TITLE
Motion Lotion - Car wax for Mechanics

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#2883]
### Assurance

I have read the `README.md`

### Summary

People love having a clean car and showing it off. The obsession of buying EDM cars would ensure a positive look on a new item like this. 

[Car wax](https://gta.fandom.com/wiki/U_Lube_It) once [applied](https://cdn.discordapp.com/attachments/876565140902924298/1130591352418209802/image.png) could be as follows:

> massively lowers the rate at which dirtmaps progress on cars.
> Soft repair the cars visible scratches

Crafting (Mechanics only):
[Possible Ingredients](https://cdn.discordapp.com/attachments/876565140902924298/1130589973607890944/image.png)

### Reason

- This has been an item mentioned via the community 
- Mechanics gain an interesting item to sell
- Benefits mechanic RP

**Comment by navonody1** [comment]
Good idea, but doesn't this fall under a car detailing category? This product should be more widely available, just the same as a cleaning kit. Mechanics and car detailers are completely different things.

**Comment by TacticalTyl3r** [comment]
Maybe get rid of cleaning kits that people can buy and convert them to "Wax Kits" that only mechanic's can buy and just leave the current car washes are. This way normal people can only pull their car up to it and wash it or Mechanic's can either craft wax kits or buy them from the computer/car wash.

**Comment by ThisIsNotDex** [comment]
I'd love to see this addition in the server, but accessible to everyone, just at a cheaper price for mechanics.

**Comment by vol5** [comment]
Scratch remover was a similar idea that has been introduced.
