### ISSUE TITLE
Bug report - Arena Pills give 100% fullness AND hydration

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2884]
### Assurance

I have read the `README.md`

### Reporter

navonody

### Summary

Arena Pills currently fail to revert the player's hunger & thirst back to what it was before you entered the arena. Once you enter the arena, you can instantly leave and have your hunger & thirst completely filled in seconds. This eliminates the need for food or drink all in one pill. This is devastating to the food market in Legacy and not only hurts the Arcade, but also other food businesses.

### Steps to Reproduce

Take an arena pill.

### Expected Behavior

You'll instantly get your hunger & thirst bars full when taking an arena pill. Generally, you don't have to spend anymore time in the arena then it takes to access the menu to exit.

### Actual Results

On rare occasions, you'll have to die first for the hunger & thirst bars to be filled on exiting the arena, but 9/10 times they will be filled as soon as you go in. Also, when exiting the arena, you'll sometimes get full health & armor bars as well, although this isn't something as easily replicated as the hunger & thirst bug.

### Game Resolution

2560x1440

### Player Data

![arcade bug](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/d0d164f5-ae60-4aa1-93ec-50244e8f83c4)

### Server

International (c3s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This behavior has now been changed so that hunger & thirst no longer resets on respawn.
