### ISSUE TITLE
Suggestion - Add bars to the Yacht's for events

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#2885]
### Assurance

I have read the `README.md`

### Summary

I am looking for a small QOL improvement to the yacht's for when people hold events on them.  I am looking to see if we are able to add a "Bar" to both the Pacific Ocean Yacht and Paleto Bay Yacht. 

Pacific Ocean Yacht: (-2094.41, -1014.84, 8.98, 232.35)
https://i.imgur.com/N0FBCLz.png

Paleto Bay Yacht: (-1440.39, 6759.23, 8.98, 248.43)
https://i.imgur.com/F0TyVeX.png

### Reason

I believe this will be a nice QOL update for citizens is to add bar functionality onto both Yachts either be locked behind the Bar job or either open like on Cayo.  It will be better so bartenders don't have to bring the supplies out on a boat or swim with them.

**Comment by vol5** [comment]
This is an awesome idea that promotes more usage. Might be worth adding a heli spawner to enhance the value as well. People would love to be flown in on yacht trips.

**Comment by coalaura** [comment]
Hmmm, idk if this would really be needed. If i were to add it it would be a lot more expensive than regular bars to avoid taking RP away from them

**Comment by TacticalTyl3r** [comment]
That is why I would say keep it locked behind the bartender job or have it open like Cayo. I personally would rather have it locked behind the bartender job since this way a business would have to supply the alcohol for the events and it would make no sense for people to go to a yacht for an open bar.

**Comment by coalaura** [comment]
done
