### ISSUE TITLE
Suggestion - PD Spike Launcher

### ISSUE THREAD

**Issue by SirPiff** [InZidiuZ/op-framework-issue-tracker#2888]
### Assurance

I have read the `README.md`

### Summary

A "Spike Launcher" for PD.

Currently spike strips require you to have multiple in your inventory, I feel as though not only it could help with inventory clutter, but also make them a little more widely used and much easier to deploy.

With the "launcher" itself being the only thing you'd have to pick back up, maybe have a range of a lane's worth of spikes come out.

Example:
https://www.youtube.com/watch?v=b_PAEqXdUPs

Something like this but in an item instead of trunk, and most likely half-ish the length.

### Reason

I believe this could make spikes much more usable than in it's current state, and possibly give the "Parallel" role in chases a bit more to do, if spikes are authorized, they could be rewarded for anticipating criminals movements and setting up a spike instead of just blocking with their car, which usually doesn't do much unless it's an alleyway.

**Comment by Mugdha57** [comment]
Current spikes are kindda small and not much useful.

**Comment by KaiEagle** [comment]
Spikes are currently really useless and need a rework to make them deploy in vertical lines from you and also increase the length of it.

**Comment by MetaHatter** [comment]
Not sure about a launcher, but I agree that spikes should be placed from the end of the model and outward (i.e. rotate the prop 90 degrees) rather than requiring an officer to stand in the middle of the street.

**Comment by coalaura** [comment]
I wont be adding a whole launcher but the new large spike strips i added basically solve this
