### ISSUE TITLE
Suggestion - Custom Clothing for a gang named Fallen Angels

### ISSUE THREAD

**Issue by Rocky1290** [InZidiuZ/op-framework-issue-tracker#2889]
### Assurance

I have read the `README.md`

### Summary

Hey, this is to keep you posted that in the Indian Subdivision me and my friends are progressing as a gang named Fallen Angels and we've progressed a lot and after the last restart the fallen clothings are getting removed as I got an update from Daxter that it is getting removed as the NA/EU gang named Fallen Angels left and they got disbanded. So I would request you to kindly add those clothings back and also a few more clothings with the name fallen angels such as shirts or hoodies.

### Reason

The main reason for bringing this up is because that in the Indian Subdivision the Fallen Angels gang has progressed a lot and it's also going to get WL soon with all the other gangs. So requesting not to remove the clothings as this will put an end to the RP that we have progressed for almost 5-6 months.

**Comment by namnanaman** [comment]
This is much need as we have progressed a lot with fallen angels and removing our clothes would break our RP.

**Comment by rishh-02** [comment]
This is must needed as we have progressed a lot with fallen angels and removing our clothes would break our RP

**Comment by DaxterPancake** [comment]
This is the wrong subdivision, you need to recreate this [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
