### ISSUE TITLE
finance app?

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-issue-tracker#289]
**Name:**
tankfury
**Summary:**
Ability to check and track existing finances on your phone

**Reason:**
The finance system can be confusing and hard to keep track of,
would be a great addition to be able to see a list of your current cars and remaining payments,
and maybe have a app notification that prompts you when its due.

**Comment by InZidiuZ** [comment]
Hey,

If you check the "Projects" tab, you'll be able to see all the planned features for the new phone, including a planned finance app.

https://github.com/InZidiuZ/op-framework-issue-tracker/projects/1#card-24206957

**InZidiuZ**
*OP-FW Developer*
