### ISSUE TITLE
Bug report - Unable to add vodka cider moonshine or whisky to blender 

### ISSUE THREAD

**Issue by anand10102000** [InZidiuZ/op-framework-issue-tracker#2893]
### Assurance

I have read the `README.md`

### Reporter

Anand#3665

### Summary

While using blender we are unable to add vodka whisky cider or any drinks in it.
Also why there is option for sandwich to add in blender..? seriously?

Also unable to use grill whenever we try to use grill inside or outside house then it is showing some bugs like when we use grill and add meat and charcole to it and wait till 3 slots of meat got cooked once it is cooked we are unable to drag cooked meat from grill to pocket 

### Steps to Reproduce

Allow cider vodka whisky moonshine to add in blender
Allow cooked meat in grill to drag in our pocket

### Expected Behavior

We are expecting to allow cider vodka whisky moonshine beer to add in blender as we can do it few days back
we are expecting to allow us to drag cooked meat from grill to pocket

### Actual Results

we are unable to add vodka cider beer whisky moonshine into blender

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
> While using blender we are unable to add vodka whisky cider or any drinks in it.

Fixed

>  Also why there is option for sandwich to add in blender..? seriously?

Why not? xD
