### ISSUE TITLE
Purchasable speed units - Quality of life

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2894]
### Assurance

I have read the `README.md`

### Summary

Making it so the Corvette, Mustang, and Hellcat can be purchased inside of MRPD and be added to the personal vehicle roster of 6 PD has. 

### Reason

PD uses the speed units on a daily basis having divisional colors and these vehicles have multiple extras plus some customization. 
A lot of people inside of PD wouldn't own these as there is a rank requirement but this would be beneficial and just a quality of life change. These cars are sometimes used for undercover and just avoid having to go to Bennys each time to customize the vehicles as well.

**Comment by coalaura** [comment]
No, only actual patrol cars are purchased
