### ISSUE TITLE
Suggestion - Salieris Bar parking and crafting

### ISSUE THREAD

**Issue by Jordan7rider** [InZidiuZ/op-framework-issue-tracker#2895]
### Assurance

I have read the `README.md`

### Summary

 add parking at Salieri’s bar and also crafting food at salieri’s bar because this bar have a kitchen like burger shot and also for the staff if there is no customer they can deliver food for npc.

### Reason

Because there are so many things we can do in this bar but it is limited from our server side so.

**Comment by coalaura** [comment]
parking no, crafting maybe
