### ISSUE TITLE
Suggestion - New Burger Shot MLO

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#2898]
### Assurance

I have read the `README.md`

### Summary

Can we get new MLO for Burger shot something like https://www.gta5-mods.com/maps/mlo-burgershot-2023-add-on-sp-fivem this one .

### Reason

We've Vanilla MLO i think from start . whereas Bean Machine's MLO look good like with all those sitting arrangements and other things there , if we get renovation for Burger shot may be we can get new things in it .

**Comment by MetaHatter** [comment]
We are also not using a Vanilla BurgerShot MLO atm... So this is unlikely.

**Comment by Vikky98** [comment]
> We are also not using a Vanilla BurgerShot MLO atm... So this is unlikely.

oh , sorry my bad . from start i was in PD and EMS only . trying this for first time . we got renovation for almost every Dept. building so me and my team want this if possible.

**Comment by coalaura** [comment]
like arteria said, wrong github
