### ISSUE TITLE
Suggestion - About leather and meat price

### ISSUE THREAD

**Issue by viskysingh** [InZidiuZ/op-framework-issue-tracker#2899]
### Assurance

I have read the `README.md`

### Summary

For leather and meat price increase request.

### Reason

I am seeing lately that many people left hunting and started doing different work . People's left they said the leather and meat price are lower in compare to money/price ratio i think can we increase the leather and meat price.

**Comment by MetaHatter** [comment]
IMHO Leather and meat are a side activity that you get some reward for, not a replacement for a job.

**Comment by KaiEagle** [comment]
> 

FYI this github is about leather and meat prices 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/29286961/462213fe-2f21-45cb-81eb-2392d387e579)
Also, you can now /bill so I don't know why you need an ATM.

**Comment by Chinku2004** [comment]
Sir we didn’t approached first here but when we noticed that if 50 customer are coming and 30 are not carrying watches with them don’t know for what reason but this is fact so I request you if you can do it for us . 🙏

**Comment by coalaura** [comment]
leather and meat prices are at a good place imo

**Comment by Chinku2004** [comment]
Dear Sir ,
Sir we didn’t approached first here but when we noticed that if 50 customer are coming and 30 are not carrying watches with them don’t know for what reason but this is fact so I request you if you can do it for us . 🙏

Your sincerely
Chinku pandey
Bean machine
(Owner)
