### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ErrlBDabawax** [InZidiuZ/op-framework-issue-tracker#290]
**Reporter:**
Character: Errl B Dabawax. discord- ErrlBDabawax#1018

**Summary:**
Inaccessible dumpsters / trashcans. There are multiple inaccessible trashcans around the city including ones located on grove street (green territory not purple), mission row PD, the intersection near the chicken delivery place from the old city and near bahama mammas. 

**Steps to Reproduce:**
RNG while doing trash jobs
**Expected Results:**
being able to obtain a trash bag to continue the job

**Actual Results:**
not being able to get to the dumpster. right clicking to skip and either losing money based on skipping the bag or just RNG obtaining the same dumpster

## Additional Information

**Screenshots:**
will obtain next time i run into the issue. Shelbs can confirm. 

**Game Resolution:**
1920x1080 and 1900x600

**Player Data:**
will be in the next report. 

**Notes:**
i have been doing /reports of each time that i've run into the issue. Shelbs TP'd to me tonight to discuss everything and directed me here as i am not in the discord at this time. my goal here is not to get any type of compensation or take away from anyone's time to recode something, but about half of the time when i skip that particular dumpster it gives me either the same exact one or one right next to it. and then i can't skip that one and have to completely shut down fivem to fix the issue. with the longer queue times of the city's high population these days im sure you can see how this can be a larger issue than just "some asshole that can't get to a dumpster" 

at least 2 of the bags are behind locked doors inside of mission row PD that a civilian would not have any reason to ever enter. others are in the back gate locked area. some are behind indestructible fences on grove street and near bahama mammas, and these are only ones that i've seen in the last few days since returning to the city. i admittedly understand that i'm probably doing more trash runs than most other players but hopefully that can give me the opportunity to lend a hand with these reports. i definitely understand that there are bigger issues that need to be addressed first and dont expect any type of immediate response or action so in the interim i will continue to report bugs here and through the in game /report system. 

thanks for your time. loving the work i've seen you put into this city and can't wait to see it grow even more than it has! congrats on an awesome product man. seriously. 
- Kyle AKA Errl B Dabawax

**Comment by InZidiuZ** [comment]
Hey,

The garbage script finds a bin from game memory, and I don't choose where they are spawned. Only way to fix this would be to add exceptions for the inaccessible locations, but there's most likely thousands, so won't be spending time on that.

If you get assigned one which you can't reach, press "Backspace" to skip it.

**InZidiuZ**
*OP-FW Developer*

**Comment by ErrlBDabawax** [comment]
so when you press backspace to skip the bin, it sometimes gives you the exact same bin, or just one right next to it. then there is either a cooldown until you can skip the next one or it just gets stuck and you have to completely log to fix it. (train nap does not work)

**Comment by InZidiuZ** [comment]
It won't give you the *exact* same one, it stores the object ids in memory and makes sure not to choose that one again. It most likely is just a nearby one it's choosing. And there shouldn't be any cooldown on it, you just have to be a certain distance from it.
