### ISSUE TITLE
Suggestion - Midnight Employee Roles

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#2900]
### Assurance

I have read the `README.md`

### Summary

Hi. I'm the owner of Midnight and I would like to help improve the roleplay of my employees by providing more progression within the business. I want to suggest the addition of an Assistant Manager role and Supervisor roles. 

### Reason

Right now there are only 3 roles; Boss (1 slot), Manager (3 slots) & Tuner (15 slots). Whereas places like PDM and mechanic shops have a lot more roles allowing employees to progress in their career to earn more money.  I personally don't care about increasing my own paycheck as I earn enough through car sales however I have looked in the paycheck information and PDM employees earn a heck of a lot more than my employees hourly plus they get a lot of commission. The only income my staff make is on EMS 5 and car sales. Car sales are very rare nowadays and EMS 5 we only typically get on rotation days. I would like to add an Assistant Manager (2 slot) and a Supervisor (2/3 slot) role to increase the roleplay of this shop and give some staff members who deserve a promotion but are limited because of slots. The supervisor role will also give employees more to do than just sit around and wait for the 'any midnight' tweet. I believe I earn 56/52 p/h. Managers earn 42 p/h and Tuners earn 35 so there is plenty of wiggle room in between those numbers to add 2 roles. Like I said, I don't personally care about bumping my wage however it would be nice to match PDM or at least have more ways of progression as we are also a car dealership and my staff deserve a pay rise. If needs be, you could even raise my paycheck and reduce the % commission I earn through car sales. Orenj has suggested the following: Boss 70, Manager 62, Ass. Man 54 Supervisor 45 Tuner 35. We have suggested this as right now a few of my employees have left to go work for mechanics as the paychecks are relatively similar and that job role is a lot more productive and has more means for progression.

**Comment by ImArteria** [comment]
Personally I wouldnt match the same because there should be some incentive to work at PDM as opposed to Midnight. Either way neither of the cars will sell often because EDM > all of them but PDM is very dead compared to Midnight.

**Comment by CloudCait** [comment]
> Personally I wouldnt match the same because there should be some incentive to work at PDM as opposed to Midnight. Either way neither of the cars will sell often because EDM > all of them but PDM is very dead compared to Midnight. Just my thoughts on the idea. Would be cool to have more positions though

I mean the wages we suggested don't match the PDM wages at all considering the owner earns 100+ p/h. I just think it doesn't make sense for midnight wages to be around the same as mechanic shop wages. I just want to open up more opportunities for my staff and give them an incentive to work here instead of just going to a mech shop

**Comment by CloudCait** [comment]
just wondering if there was an update on this as since posting my hiring advert i've had multiple people message me asking how the pay compares to a mech shop and if it's even worth working at midnight when they can earn much more at a mech shop (which its not, tuners only earn 35 an hour)

**Comment by coalaura** [comment]
i was on vacation

![yes](https://i.shrt.day/QOwEPelA01.png)

PS: i love the "Ass man" role
