### ISSUE TITLE
Suggestion - O’Malley’s

### ISSUE THREAD

**Issue by Mustyclam** [InZidiuZ/op-framework-issue-tracker#2901]
### Assurance

I have read the `README.md`

### Summary

I am the owner of O’Malley’s and was hoping to get a changing room inside of the back employee room as well as make the sidewalks private property to provide parking for patrons.

### Reason

The main reason for the locker is just to make things easier on employees since we have a dress code at O’Malley’s. With all the unused room in the back I think a “locker” or changing room where we can put our uniforms on would be extremely helpful instead of having to go to one of the clothing stores every time before a shift.

As for the sidewalks being private property, we have been having issues with people being towed, but we also have no parking lot or space to park other than behind the bar, which is extremely limited. Parking on the side of the road is dangerous as we are on such a busy street. But I have noticed that when parking on the sidewalk no one gets hit and it helps prevent any accidents from drivers traveling at high speeds. But patrons and employees being towed recently have affected business recently.

Thank you for you consideration!

**Comment by DaxterPancake** [comment]
Making something 'private property' is completely RP based and therefore developers cannot do anything about that. Maybe speak to someone in the city you play on (such as state) to work something out with them. O'Malleys is also very close to three different parking lots so therefore I don't see any reason why any map changes regarding parking would need to me made (casino parking, taxi parking and a small parking lot near the park).

**Comment by Mustyclam** [comment]
Ok no worries on parking I’ll discuss that further with someone in the city. Is the locker/closet for changing a possibility?

**Comment by coalaura** [comment]
locker i don't really see a need for tbh but changing spot i can add

**Comment by coalaura** [comment]
done
