### ISSUE TITLE
Adding Hotlines for business 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#2903]
### Assurance

I have read the `README.md`

### Summary

Why only to have burgershot and bean machine hotline on phone? Why not all other business have their hotline?

### Reason

There are other business like arcade , bahamas , Sol-cafe , sushi , etc. This business also sell food items like burgershot and bean machine then why only to have only their hotline on phone.

Maybe we can add app where we can have all hotlines (removing hotline from phone favourites) and there will be all business hotline that are sold and will not have hotline of business that are unsold until they are sold.

We can’t just contact business employees through twitter all the time. People chat on twitter to ask if “XYZ” shop is open or not. We can have a different app for that so we can have  more clean twitter also.

**Comment by seamarob** [comment]
#2842 This is already being spoken about in this suggestion

**Comment by coalaura** [comment]
closing as duplicate
