### ISSUE TITLE
Suggestion - Governor SUV to an accessible garage to State

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#2906]
### Assurance

I have read the `README.md`

### Summary

Access for State to pull out "Governor Suburban" 

### Reason

Right now, if State would like to pull out the Governor Suburban, we have to request it from PD and have to have the right ranking officials around to get the vehicle which is helpful in high tense RP scenarios. 

While it may be a menial task, it would improve State RP and also not make us reliant on PD higher ups.

Maybe not all State Officials could pull this out but maybe State Manager/Vice Governor/Governor

**Comment by Raz5665** [comment]
hm. it would be helpful for state members.

**Comment by souravind** [comment]
It will be really helpful

**Comment by coalaura** [comment]
done
