### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by craig9333** [InZidiuZ/op-framework-issue-tracker#2907]
### Assurance

I have read the `README.md`

### Summary

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/40130845/4ecf2ad8-cc4d-4c83-9226-20a306acc104)

### Reason

it will help the bcfd out and it will have lights and woop woops on it as well

**Comment by enutpeanut** [comment]
This would be better suited for the other github!
https://github.com/InZidiuZ/legacy-assets-issue-tracker

**Comment by DaxterPancake** [comment]
> This would be better suited for the other github! https://github.com/InZidiuZ/legacy-assets-issue-tracker

This github is correct, since it would be adding the vehicle through scripting. Asset github is for car changes, map changes or clothing changes.. In this instance they don't want the car changed but instead added to a garage.

**Comment by enutpeanut** [comment]
Oh my bad, thank you Daxter!

**Comment by coalaura** [comment]
done
