### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Rayysho88** [InZidiuZ/op-framework-issue-tracker#2908]
### Assurance

I have read the `README.md`

### Summary

911 and 311 calls should be done by T muscle not by phone..  this will much better improve ems rp as no one can call ems after he is down.. I am talking about the person like me who play alone in server... If I am down i have no one for back and when i respawn in hospital .. most of my stuff is looted .. plus if no ems is on duty , pd can respond to situation ( if not in any situation) and can save characters life

### Reason

I have played my character so many times when due to some glitch or something my character just dies and when i respawn in hospital some of my expensive stuff is gone from pockets. This 911 and 311 emergency calls will stop that.

**Comment by DaxterPancake** [comment]
The fact you can't use your phone while downed is intentional. There is already a system in place that has locals call EMS for you if they see you.

The idea to potentially inform PD when people are downed is an interesting one but that idea would have to be thought out a lot more.
