### ISSUE TITLE
Mining Drills breakdown 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#2909]
### Assurance

I have read the `README.md`

### Summary

Suggestion for broken drills when mining. Currently when mining and blow up drills just automatically gone from your inventory.

suggesting it stay in the inventory but as broken, so won’t be able to be used for mining but maybe to break down for materials. Kinda like broke pistols/rifles/shotguns/smg’s

### Reason

Would give an opportunity to deconstruct/ break down the item for materials (scrap, alum, steel)

**Comment by ImArteria** [comment]
Feel like this would indirectly buff mining to make it pay out more from materials. I dont think it's a good idea

**Comment by gadjinee** [comment]
> Feel like this would indirectly buff mining to make it pay out more from materials. I dont think it's a good idea

Yeha I get it, just feel like it's a waste of drills, in terms of when you blow up they just gone

**Comment by vol5** [comment]
It would make sense if it was the same mechanic as when you use a repair kit and it breaks.

For repair kits its aluminum if I remember right.

For drills it would be cool if they have a chance to give 1 scrap when they break.
