### ISSUE TITLE
Marina or boat shop

### ISSUE THREAD

**Issue by WennbergTV** [InZidiuZ/op-framework-issue-tracker#291]
**Name:**
Fred Jones -  wENNBERG#4556

**Summary:**
Implomenting a way for players to achive boats and other watercrafts through an all RP based shop or a manual "menu" based showroom.

**Reason:**
Implomenting boats adds a whole new aspect to the game. It unlocks the ocean, which is a big part of the GTA V island. Once a player has purchased a watercraft they can spawn it at the marina (heli dock place). 

For criminals, having a boat could be a great fun way to do something new. Take your hostages out in the ocean and play around with them, for businessmen/women who want to show their friends and family how much money they have and also if you're just a casual member of society and want to have a nice fishing trip with a friend.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
