### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by Nicck03** [InZidiuZ/op-framework-issue-tracker#2911]
### Assurance

I have read the `README.md`

### Reporter

Nick

### Summary

I own a Sultan Rs Super which has issue when riding it the parts of the car starts making noise as if am riding some broken car the sound I get from car is very annoying please look into it 

### Steps to Reproduce

Idk what you guys can do It is what the issue i am facing I have tired to do upper the suspension till am getting noise

### Expected Behavior

Sultan Rs Super is a very well car but in this server.Its the wrost in handling and breaking also.I have driven it in other servers also there is some issue in this server only

### Actual Results

Idk

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
This is the wrong github. Also, the sultan RS is a native GTA vehicle so there is nothing we can do since we cant change the model without streaming it
