### ISSUE TITLE
Suggestion - Jailed API Call

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2913]
### Assurance

I have read the `README.md`

### Summary

Create an API call similar to the PD impound that would show all people currently jailed

### Reason

Add some pretty data to the new MDT and would be beneficial to see what inmates are there, as well as aid DOC in knowing as well.

**Comment by InZidiuZ** [comment]
Jailed players that are actively on the server and on their character, or even if they're offline? If you mean offline as well, then this would be a route for a database wrap.

**Comment by teddythedev** [comment]
Whichever is easier probably lol.

**Comment by coalaura** [comment]
i'll add it to the readonly api

**Comment by coalaura** [comment]
you can now filter by jail ![yes](https://i.shrt.day/DaYiQije02.png) (its a timestamp when they are released)
