### ISSUE TITLE
Suggestion - Being able to see items on the ground

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#2914]
### Assurance

I have read the `README.md`

### Summary

Make a way where we can see items dropped on the ground like Arena and BR.  If this is not able to be done due to the amount of items make it so only weapons and/or drugs are able to be viewed on the ground.  The only issue I can see is I am not sure how much strain it would have on the server with lagging.

### Reason

I believe this will increase PD/FIB RP with them being able to use the plain view doctrine when conducting their investigations.  As of now if someone would be handing off a gun or weapons to another person it goes into a ground inventory with a white arrow. Where if we were able to see the guns/drugs on the ground they are able to get a photo of it to help build their case and increase their RP.

**Comment by InZidiuZ** [comment]
You mean physical objects for per dropped item?

**Comment by coalaura** [comment]
I feel like with all the trash people throw out expired or not this would mean quite a lot of objects being spawned and despawned all the time

**Comment by TacticalTyl3r** [comment]
Yes physical items.

> I feel like with all the trash people throw out expired or not this would mean quite a lot of objects being spawned and despawned all the time

With this I would say keep it only the illegal items (Guns and drugs) But if they are broken they they don't show up just like how you can't see them on your back now.   This was just an idea and not sure how feasible it would be.

**Comment by Skai97** [comment]
Even adding to this whenever people are carrying x amount of drugs they will appear on their person. Like if a person is carrying 8 bags of cocaine. A small clear bag will be attached to their hip. So much weed maybe a weed plant hanging. Could create some interesting roleplay and people wouldn't carry a lot of drugs around with them on their person. Its also just another thing to identify. 

If someone takes 8+ bags to Vinewood to sell, a clear bag would be visible on their person

**Comment by coalaura** [comment]
> If someone takes 8+ bags to Vinewood to sell, a clear bag would be visible on their person

When i buy weed from my dealer he usually doesn't show it in the open
