### ISSUE TITLE
Suggestion - PDM cars need a buff

### ISSUE THREAD

**Issue by Kropex6000** [InZidiuZ/op-framework-issue-tracker#2916]
### Assurance

I have read the `README.md`

### Summary

PDM cars are really shit compared to EDM cars. I have a PDM sports car fully maxed out with EMS 5, turbo, race suspension and transmission, etc and yet a van from EDM with only EMS 4 on it is faster than it.

### Reason

I understand that EDM cars cost real money and should be better than PDM cars overall, but PDM cars should be buffed a little bit just to seem more realistic. Or the other way round by nerfing EDM cars.

**Comment by InZidiuZ** [comment]
Suggestions to assets should be posted [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).
