### ISSUE TITLE
Bug report - OXY ISSUE

### ISSUE THREAD

**Issue by nischay876** [InZidiuZ/op-framework-issue-tracker#2917]
### Assurance

I have read the `README.md`

### Reporter

oggy0237

### Summary

I arrived at the Oxy end location with 5 minutes remaining. However, when I pressed 'E,' it indicated that all locations not done, even though I had already completed all of them.

### Steps to Reproduce

nil

### Expected Behavior

i should get my money and end the oxy

### Actual Results

didn't get the money

### Screenshots/Videos

https://img.bio/2bng97.mp4

### Server

India (c8s1.op-framework.com)

**Comment by InZidiuZ** [comment]
Is this a consistent issue? Has it happened more than once? Do you have video of the entire run from start to finish? Can you also post your log file from that session. Did anything out of the normal happen through the run?

**Comment by InZidiuZ** [comment]
Closing due to no response

**Comment by nischay876** [comment]
https://img.bio/AOWpCo.mp4 not entire video but here is a video of just ending as my instant replay is max 2 min
