### ISSUE TITLE
Suggestion - Skins / Paint 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#2918]
### Assurance

I have read the `README.md`

### Summary

So currently pain can be applied to majority of the guns however the skins can only be applied to MK2 weapons, i was thinking if its possible to maybe be able to apply skins for legal guns? like glock or revolver? 

### Reason

just feel like it would be more inclusive for all the legal people as well been able to have a skin on gun if they want to

**Comment by coalaura** [comment]
The reason you can only apply them to mk2 weapons is because skins are a native GTA thing. GTA only added skins to mk2 weapons so its sadly not really doable.

**Comment by gadjinee** [comment]
yeah get that, would be good tho. i thought if lets say glock is internally same as mk2 pistol and revolver is same as revolver mk2 just with diferent visual you could apply the skin. Could maybe Glock and Revolver be replaced with registered Pistol MK2 and Heavy Revolver MK2? 

Probably dumb but just though would be cool for everyone to be able to use the skins

**Comment by gadjinee** [comment]
Yeah make sense. Thanks anyway
