### ISSUE TITLE
Suggestion - To change the location of 2 garbage cans.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#2919]
### Assurance

I have read the `README.md`

### Summary

While trying to enter my house "Covenant Avenue 7" through the front gate, these 2 garbage cans come in between which makes it hard/uncomfortable to go through. It would be helpful if u can change the location of those towards the right side from the gate.

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/d21c436b-551b-4b37-9b72-3563f6b3e031

### Reason

It would be much more easier to enter the house, instead of jumping through the gate to enter we can just walk by.

**Comment by coalaura** [comment]
This would require streaming that entire block, so no

**Comment by Nozimmm** [comment]
can you just remove that gate then? or change the way it opens like from the right side.

**Comment by coalaura** [comment]
same deal
