### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by WoooMonsta** [InZidiuZ/op-framework-issue-tracker#292]
**Reporter:**
- WoooMonsta⭐#0001
https://steamcommunity.com/id/WoooMonsta/

**Summary:**
Bought a Audi RS3 from imports and the neon kit does not show. I spend 3800 on it as i though i did not put the kit on it and it bought again to double check. Changed the color twice and then tried it again the third time but no change.

**Steps to Reproduce:**
Just buy a Audi from the imports garage and equip a neon kit on it and it wouldnt work.

**Expected Results:**
The neon kit i bought for 3000$ (3times) and changed colors by spending 800$ (2 times) to be refunded and the neon kit to be fixed for the car.

**Actual Results:**
The car should show the neon glow underneath the car.

## Additional Information

**Screenshots:**
![Untitled2](https://user-images.githubusercontent.com/52989835/61995644-b473e800-b0a8-11e9-8e33-7f3323998b56.png)
![Untitled1](https://user-images.githubusercontent.com/52989835/61995645-b473e800-b0a8-11e9-8d77-235194ce99d6.png)
![Untitled](https://user-images.githubusercontent.com/52989835/61995646-b50c7e80-b0a8-11e9-8b0d-12dea25e616d.png)

**Game Resolution:**
1920X1080

**Player Data:**
Character ID - 555

**Notes:**
Thanks for the server and again i appreciate the hard work you put into the server for the community :)

**Comment by InZidiuZ** [comment]
Hey,

Please use the [asset-related GitHub](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for this.

**InZidiuZ**
*OP-FW Developer*
