### ISSUE TITLE
Suggestion - Requesting my garage to be changed to a diff location in my yard space

### ISSUE THREAD

**Issue by iDaxr** [InZidiuZ/op-framework-issue-tracker#2920]
### Assurance

I have read the `README.md`

### Summary

I would like to request that my garage be moved from where it is to somewhere more convenient

### Reason

I would like my garage to be moved to a closer position to the house and also in or in front of the actual garage that comes with the house. I think it would be more convenient for me and also more realistic in my opinion. :)
![garage now](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/143039199/585961c0-8eb5-41b7-9e88-8fbf74b9245d)
![Car garage transfer request](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/143039199/36561afe-3227-4365-8762-ccfce9e1bfd3)

**Comment by vol5** [comment]
This goes here if yo didn't know > https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues that is the spot for all asset related stuff.

**Comment by DaxterPancake** [comment]
> This goes here if yo didn't know > https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues that is the spot for all asset related stuff.

In this instance he is wanting the garage moved (script related) not a map change, car change or clothing change, therefore this is the correct github to post it in.

**Comment by DaxterPancake** [comment]
> ### Assurance
> I have read the `README.md`
> 
> ### Summary
> I would like to request that my garage be moved from where it is to somewhere more convenient
> 
> ### Reason
> I would like my garage to be moved to a closer position to the house and also in or in front of the actual garage that comes with the house. I think it would be more convenient for me and also more realistic in my opinion. :) ![garage now](https://user-images.githubusercontent.com/143039199/262806895-585961c0-8eb5-41b7-9e88-8fbf74b9245d.png) ![Car garage transfer request](https://user-images.githubusercontent.com/143039199/262806911-36561afe-3227-4365-8762-ccfce9e1bfd3.png)

It would be helpful for you to prive the address of your house/map location so we can potentially make the change.

**Comment by coalaura** [comment]
> This goes here if yo didn't know > https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues that is the spot for all asset related stuff.

Its s script issue

**Comment by coalaura** [comment]
and like daxter said @iDaxr i need the address

**Comment by vol5** [comment]
/locate Mad Wayne Thunder Drive 4 @coalaura

**Comment by coalaura** [comment]
moved it

![ye](https://i.shrt.day/sIVacAyO09.png)

**Comment by iDaxr** [comment]
Its still the same place for me :(

**Comment by DaxterPancake** [comment]
It won't be moved until a server restart happens.

**Comment by iDaxr** [comment]
> moved it
> 
> ![ye](https://camo.githubusercontent.com/1128b1be32adb475937e3733174075742d2ac3814b7f306991fd0744c2b9e38f/68747470733a2f2f692e736872742e6461792f734956616341794f30392e706e67)

Currently in city and the garage hasn't been moved, not sure what happened @coalaura

**Comment by iDaxr** [comment]
> It won't be moved until a server restart/update happens.

ok noted. Tysm
