### ISSUE TITLE
Suggestion - For hayes Repair Shop

### ISSUE THREAD

**Issue by 07ashishdas** [InZidiuZ/op-framework-issue-tracker#2921]
1. 

[ ] ### [Assurance]

I have read the `README.md`

### Summary

would you Place a garage near Hayes repair Shop Because is there no garage near This repair shop or you can replace the lift  side highway garage here.

### Reason

Because this repair shop is in city center and to much public are there just put there near the shop time pop here that why i these suggestion 

How i say i give link :   https://drive.google.com/file/d/1XIGR_VoTO2g-qlvx-yyCDgrJltIynC_B/view?usp=sharing

from Legacy India

**Comment by 07ashishdas** [comment]
would you Place a garage near Hayes repair Shop Because is there no garage near This repair shop or just left side highway garage here.

**Comment by gadjinee** [comment]
There's a request for the garage already 

https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2880


That is a pretty cool location tho for the garage to be moved, we didn't actually thought of it in original request

 ![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/60bb9880-26b3-4f84-b053-9215f6b0891a)
