### ISSUE TITLE
Suggestion - Decrease Mechanic repair time for Emergency vehicles

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2923]
### Assurance

I have read the `README.md`

### Summary

Dramatically reduce the time it takes for a player mechanic to repair an emergency vehicle.  Ideally notably faster than /repair.  

### Reason

PD often cannot take the time required to get a mechanic repair due to constant calls & situations.  Reducing the time to repair will make it more competitive with /repair and increase, albeit slightly, the likelihood of an officer going to a mech shop. Obviously this leads to more RP opportunities.

**Comment by coalaura** [comment]
seems weird for repairs to be magically faster for certain types of cars.... I will however slightly up the /repair time to be more on-par with mechanic repair times

**Comment by coalaura** [comment]
/repair will now take basically the same amount of time it would take a mechanic to repair the car. The more damaged the longer ofc. I matched it with the crafting and repair times of the mechanic job
