### ISSUE TITLE
Suggestion - Car Trader App

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2924]
### Assurance

I have read the `README.md`

### Summary

Create a Car Trader app for the tablet that does the following:

- Provides a UI for the transfer of a vehicle from one person to another.
- Shows the Vehicle to be sold along with all the upgrades that it contains
- Allows for a Sale price to be entered (with a server configurable cap as multiple of original car value)
- Collects the cash and transfers the car on completion
- Allows the transaction to be taxed according to the servers configured tax rate
- Allow for printing of receipt

Proposed process to execute sale: 

1. Seller opens tablet, and selects car trader app
2. Seller enters vehicle identifier or plate number
3. Seller enters sell amount (under server-specified limit)
4. Seller enters buyer PayPal ID (proximity checked)
5. Seller sends offer
6. Buyer receives "bill" with information on the car/price/options/tax/etc.
7. Buyer agrees to sale
8. Money and car are transferred simultaneously
9. Seller tablet app is updated with option to print receipt

### Reason

This will address several issues.:
- Dramatically decrease the manual effort of a sale
- Increase the security of a sale by ensuring the vehicle is owned and the cash is there to transfer (i.e. escrow the sale)
- Allow the buyer to verify the upgrades are, as advertised
- Allow server managers to set a maximum cap on vehicle sales to manage their economies
- Receipt can provide a paper trail of ownership for RP

**Comment by coalaura** [comment]
why not use /bill?

**Comment by MetaHatter** [comment]
Bill has functionality for payment collection but not to the level that a car deal "Bill of Sale" would benefit from.  Specifically showing the upgrades the car has, how much damage it has, etc.  There is also currently no mechanic for server admins to collect sales tax or cap car sale prices that this would address.

It also could be built architecturally in a way to create the foundation for a car advertisements app and replace the need for the discord channel long term.

**Comment by COWBOI28** [comment]
Yea this would be a Great addition

**Comment by ayushpatel1007** [comment]
Maybe making individual car trader app, there is already suggestion #3128 where we are taking about /trade and car trade can be part of /trade and not an individual comand or function

**Comment by coalaura** [comment]
Closing in favor of #3128
