### ISSUE TITLE
Sons of Legacy Auto repair Bike Shop and Bar

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#2925]
### Assurance

I have read the `README.md`

### Summary

If you could add it so Staff and Owners of Sons of Legacy, can set up and use both the bar side and Bike shop side of the shop it would add more rp

### Reason

It would add more rp to the sons of legacy shop and Paleto in general

i would also like to see maybe some NPCs browsing the shop and bar area to make it feel more live and not so dead, as an RPer in the north part, feels lonely and dead

**Comment by coalaura** [comment]
what

**Comment by coalaura** [comment]
I don't think i quite follow what exactly you want done

**Comment by SluggsV2** [comment]
> I don't think i quite follow what exactly you want done

More or lesss a spot to sell vehicles inside the bike shop area, we would be losing money if we had to buy from pdm and tried to sell up at our bike shop, maybe you could remove bikes from pdm and move it solo to Sons of Legacy, as far as the Bar side, behind the counter you could add, a storage Locker for drinks and supplies and then above add a mixing station for drinks, and a shop where we can buy vodka, tequila and all the hard alcohol we could need

**Comment by DaxterPancake** [comment]
I'm not really sure if I am a fan of making a gang clubhouse also be three buisnesses. You can already sell bikes at your shop using RP and do not need scripts in order to do that. You are a mechanic shop. You have a stage/seating area that you can RP with people and hire bartenders from other buisnesses to sell booze if needed.

**Comment by SluggsV2** [comment]
> I'm not really sure if I am a fan of making a gang clubhouse also be three buisnesses. You can already sell bikes at your shop using RP and do not need scripts in order to do that. You are a mechanic shop. You have a stage/seating area that you can RP with people and hire bartenders from other buisnesses to sell booze if needed. 

Ah I see ur vision side of it, 

I forgot other cities use Sons of Legacy as a gang MC, when purchasing the shop me and my partner were intrested due to the fact it had a bike shop and mechanic shop on the side, 

We have no intention to join criminal activity and want to bring more rp up north! 

For bike selling our only concern is, why would they come to Paleto if they can get it for the same price and in city from pdm, 

We would be losing money if we bought and sold them for less up there. 

I get the bar side totally fine with me, just wanted to create more rp and interactions all over the map, more or less move people from the city

**Comment by DaxterPancake** [comment]
Even without the clubhouse part, in the past other places have been shut down to be multi-buisnesses due to the fact it isn't fair that one place can do everything.

I'd speak to the used car salesman in RP and see how he does it. You wouldn't be buying from PDM. You would need to snatch them up cheap and sell them at a higher price but still lower than PDM.

**Comment by SluggsV2** [comment]
> Even without the clubhouse part, in the past other places have been shut down to be multi-buisnesses due to the fact it isn't fair that one place can do everything.
> 
> 
> 
> I'd speak to the used car salesman in RP and see how he does it. You wouldn't be buying from PDM. You would need to snatch them up cheap and sell them at a higher price but still lower than PDM.

Can we atleast get our vending machines and an outfit changer at sons of legacy

**Comment by coalaura** [comment]
Yeah... Basically what Daxter said...
Vending machines would be something for the asset github (https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) and the clothing spot i'Ve added
