### ISSUE TITLE
Suggestion - more /bill options to tip

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/op-framework-issue-tracker#2926]
### Assurance

I have read the `README.md`

### Summary

Since a lot more people are utilizing /bill right now, while talking to some people I was wondering if it could be possible to have more % tip options like 75% and 100%.
Or alternatively the option to type in how much % you want to tip.

Separately to that, if there could be a fillable text space to manually type in how many $ you want to tip.

For example:
The Bill is $500, I tip 50% and it adds 250 on top. In which case the 50% sound like a lot, but are really not that much.
So instead you could set it at tipping 100% or adding $500-1000 yourself.

Could look something like this:
![Bill](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107942951/8a728f53-2030-404c-ad0e-b1a0d4e90005)

### Reason

In my personal experience I usually like to tip a good amount when visiting businesses, so I automatically go for the 50% option. Though sometimes the bill is just small, so my tip ends up being a small amount too. Resulting in me going to an ATM, taking money out and giving it out anyways, wasting the effort of the /bill.

Being able to set it to a higher percentage could allow a higher quick tip, or when wanted give a manual tip of an entered amount when you specifically want to tip something like $1000 or so.

**Comment by coalaura** [comment]
done

![ye](https://i.shrt.day/hOGUxefo93.png)
