### ISSUE TITLE
Bug report - Convenience store UI glitch

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2927]
### Assurance

I have read the `README.md`

### Reporter

stargroot

### Summary

After buying something from the convenience store and then opening your phone the Store UI appears on your screen. /clear_uis works to get rid of it but it still should be looked at fixing.

![image](https://ur.retarded.wtf/fCv77H.png)

### Steps to Reproduce

- open the convenience store ui
- exit the ui
- open your phone
- and the store ui will appear on your screen

### Expected Behavior

- open the convenience store ui
- exit the ui
- open your phone
- store ui doesnt appear

### Actual Results

store ui appears after opening the phone
![image](https://ur.retarded.wtf/vA314p.jpg)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
I am unable to reproduce this

**Comment by coalaura** [comment]
i THINK i've fixed this now
