### ISSUE TITLE
Suggestion - Car pushing

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2928]
### Assurance

I have read the `README.md`

### Summary

Its annoying whenever someone leaves their car out in front of a garage so you can't pull out your own vehicle. To have a option other then calling a tow truck or stealing a local car to ram it out the way It would be nice if you can enter the vehicle and enter a command like /toggle_neutral_gear. After that you can get out the car and walk to the trunk/front bumper and then press e and w or just w (whatever keycombination you think works better) to then be able to push the car out of the parking spot. 
![example](https://ur.retarded.wtf/KrRxSZ.jpg)

### Reason

- Quality of life
- option for legal people to move a car when no tows are available

**Comment by TheOneLizard** [comment]
or maybe similarly to /trunk, a command /push_car that also indicates where to stand for the animation and the script to trigger. 

I really like the idea, but I'd suggest that the pushing speed is really low, so in most cases calling a tow truck will still be faster than pushing a car to a mech shop.

**Comment by coalaura** [comment]
If its a local car it should get deleted if you try to withdraw your car (unless you get in it). This seems like an overly complicated "fix" for a very small bug
