### ISSUE TITLE
Suggestion - Car engine start

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2929]
### Assurance

I have read the `README.md`

### Summary

Currently when getting into a vehicle you have to press "W" to turn the engine on. It would be nice if you could press both W and S to turn on the engine. This would make it easier to start the car and reverse out of your parking spot.

### Reason

- Makes it easier to reverse out of parking spots
- Pressing the gas pedal is required to turn on the car and since both W and S work for acceleration S should also start the engine
- Quality of life

**Comment by coalaura** [comment]
pressing W to turn on the engine is a GTA V thing. You can also use /engine, i don't see a need for this
