### ISSUE TITLE
Oxy Run Vehicle

### ISSUE THREAD

**Issue by RecklessWillie** [InZidiuZ/op-framework-issue-tracker#293]
**Name:**
Markie King (Reckless Willie#7885)

**Summary:**
Write a short summary of what your suggestion is about.
Require that the vehicle spawned be used to do oxy runs, also add a few different vehicles to the pool so that the same primo model doesn't spawn. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
Requiring that the vehicle spawned must be used to complete the oxy run will clean up the streets in that area of abandoned vehicles. Make the location a lot less obvious, currently at times you can see anywhere from 1-4 primos parked in front or across the street from the oxy place.

**Comment by DooZolz** [comment]
He made the oxy script on stream with like 40-50 people watching. At least a couple people must have meta gamed and they probably told there friends about it.

**Comment by RecklessWillie** [comment]
Regardless if they meta’d or not.. what Im saying is the vehicle that spawns should be required to be used... or if the devs want people to be able to use their own vehicle maybe add an option.. maybe it cost a couple hundred less to use your own vehicle or something like that... my issue is the number of vehicles piling up in the street and area surrounding the oxy dealer

**Comment by DooZolz** [comment]
I'm sure he will make changes to the oxy script in the future but I'm pretty sure that's not his priority right now and OOC my character Tyrone doesn't know about the oxy place yet so idk what ur experiencing.

**Comment by HybridSquirrels** [comment]
I would just like it so at least the vehicle despawns when abandoned alot quicker, to often my character turns up there to find the vehicle left in the parking bay and it will not allow another to be spawned........super annoying

**Comment by InZidiuZ** [comment]
Hey,

If there's a vehicle in the way, it is now automatically deleted. (I think)

**InZidiuZ**
*OP-FW Developer*
