### ISSUE TITLE
Suggestion - Change the /check_ammo command

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2930]
### Assurance

I have read the `README.md`

### Summary

Currently, when using the /check_ammo command it shows you how much ammo you have for the gun you are holding.
Since the redesign of the ammo count, it is kind of useless since it already shows your ammo on the screen. 
I would therefore suggest changing the /check_ammo command to show the amount of ammo for every gun
 (pistol, tazer, smg, shotguns, sniper, and rifle).
That would give the command a use again and help people check if they need ammo for a gun without having to equip it first.
![image](https://ur.retarded.wtf/tib2Rq.png)

Instead of it showing up in the blue box on the top right like it does currently it could be listed in the chat box on the left just like when pd checks for active robberies
![image](https://ur.retarded.wtf/UpqJkz.png)

### Reason

- The current /check_ammo command is useless with the new UI already showing you the total amount of ammo
- Easier to check ammo for every gun variant

**Comment by coalaura** [comment]
done

![ye](https://i.shrt.day/VomEBEli32.png)
