### ISSUE TITLE
Suggestion - Some businesses have TV panels that don't work with a remote

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2935]
### Assurance

I have read the `README.md`

### Summary

Not all businesses have TVs, so this isn't a request to add non existing TV panels in spaces where they aren't. This is a request to add WORKING TVs to businesses that already have existing panels that DO NOT work with remotes.

Whitelisted Businesses that have TV panels that DO NOT work:

- Videogeddon Arcade
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/a88f653c-174c-4ded-95cd-6c32da5ac7e6)
![image (1)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/4ed638c2-fc24-4caa-989e-da238c574ff1)
- Burger Shot
Could replace one of these panels with a working screen for commercials/proper menu/etc.
![image (2)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/92f48c24-1338-40d2-a281-6ade44630662)
- Vanilla Unicorn
Manager's Office
![VU managers](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/294ca1ed-2e15-4b29-889d-81a6ccda35b7)
Premium Lounge
![VU Premium](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/e5eb4c3f-6433-4b59-82cf-8186d421677a)

Whitelisted Businesses that have TV panels that DO work:

- Mirror Park Auto - 1 Laptop screen works
- Marlowe Vineyard - 1 monitor works in office upstairs
- Kissaki Sushi
- Bean Machine
- Premium Deluxe Motorsport
- Lost MC Repair Shop
- Bahama Mamas
- Luxury Autos
- Green Wonderland
- SplitSides Comedy Club
- Paleto Bay Repair Shop - Has 2 old CRT panels in the back
- Paleto Bay Steak House

Whitelisted Businesses that have NO TV panels:

- Salieri's Bar
- YellowJack Bar
- Mosley's Auto Repair Shop
- Casa Blanca
- Midnight Club Tuner Shop
- O'Malley's Irish Bar
- Harmony Repair Shop

### Reason

I found it strange that only a few of the businesses with panels are missing out on this great feature. Implementing these changes will promote future content creation by way of displaying commercials, menus that display proper pricing and other potential entertainment value.

**Comment by LusciousLuna** [comment]
I agree, having working TVs in the businesses would help to encourage creativity and also make processing purchases a little smoother. Some business use notepads to post the menu and only one person can look at a time. But if a tv for example works we can have a digital menu up for all to see at the same time.
