### ISSUE TITLE
Fishing!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#2936]
### Assurance

I have read the `README.md`

### Summary

Fishing would add a whole nother level to non criminal characters, we have hunting, why not add fishing 

### Reason

Loot pool can be, 

meat, jewelry, metals, junk, rotten food, anchors, gold, ext

these would all have chances to get like jobs, it would be done the same way as hunting tho,

**Comment by InZidiuZ** [comment]
This is already an internal todo & has been suggested multiple times before here in this issue tracker.
