### ISSUE TITLE
Respawning and increased down timer

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2937]
### Assurance

I have read the `README.md`

### Summary

At any point whenever you are down there is a chance you could crash. Can sometimes be a little buggy and you might lose shit you don't want to. 

Suggesting that even after a crash or game close, you do not automatically respawn. You will be put back to your last location and be down as previously. 

Adding to this also increasing the down timer to 10-15 minutes. 

### Reason

Increasing the timer would hopefully benefit EMS when responding to some calls. 5 minutes is not a long time and most new people just go to the hospital assuming no EMS is around to help them.

With the not respawning, you could only respawn if you decided to hold your enter button as it is now or be automatically taken to the hospital after laying there for X amount of time. It stops people from losing their items from random head pops.

**Comment by stardome101** [comment]
The game has been crashing _alot_ recently and we all know that Nancy is a pickpocket. I feel like there should be some form of  leeway when spawning back in after a crash. You automatically spawn at the place you were downed and remain downed until an EMS picks you up or you are taken to the hospital OR you respawn manually. 

In regards to the timing of being downed, it could be possible to increase the timer when an EMS worker is on duty. For example, if no EMS are working then you may have a 5 minute respawn timer but if they **ARE** available then it gets upped to about 10-15 minutes.

There could also be an option to send a distress call... have you noticed that locals have been disappearing off the streets these past few days?
