### ISSUE TITLE
Suggestion - Price change on TM-02 Khanjali in Arena

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2939]
### Assurance

I have read the `README.md`

### Summary

Currently, this vehicle unlocks around level 20 if I remember correctly and only costs $1,000. This tank is indestructible and usually results in some kind of asset spam to try to make everyone headpop out of arena. To avoid any further rage across the community, is it possible to either make the TM-02 Khanjali a higher level requirement (level 130+) OR make it cost $100k? It's fine that it exists, but the low cost and level requirement to get an indestructible machine that makes everyone's screen shake is upsetting to say the least.

*Edit: 
The assets that people will spawn in to attempt to headpop everyone are: USS Iowa, Jet, Blimp, Star Destroyer, just to name a few. Basically props that aren't drivable that just get in the way and cause massive headaches.

### Reason

If this change is implemented, it will make Arena playable again. Only those who have earned it will be able to use the TM-02 Khanjali.

**Comment by ristwell** [comment]
Yeah its cringe asf CHANGE IT

**Comment by vol5** [comment]
There are massive assets people spawn rapidly to troll and cause issues. These are ones that cause headpops etc.

- Star Destroyer
- Jet
- Blimp
- RMS Titanic
- Death Star
- etc.

**Comment by Kay32** [comment]
These features most of the time make the arena unplayable for the people that it draws aka the shooters. And honestly as much as I hate the arena pills in general as I dont think they belong in RP but thats my opinion. It does the people just in the server to shoot around and not ruining RP with other groups/PD and the listed assets of the tank often make this unplayable to where whenever you spawn in you are meet with a boom and you just leave

**Comment by scufflord** [comment]
I would like to add after speaking to a few members of our community that these tanks also pose a threat to their actual health due to the shaking that happens when they get spam fired in arena. Your entire camera POV shakes uncontrollably and for people prone to seizures this can and has caused issues so far. I'd say remove these entirely or if possible disable the shaking from the cannons being fired at a minimum.

**Comment by InZidiuZ** [comment]
The entire arena vehicle list has been gone over and all unusable, abused, completely bulletproof and overly large vehicles have been removed. All vehicles have been given new prices too instead of just a hard $1,000. There are new level for when they unlock as well.
