### ISSUE TITLE
Mercedes CLS AMG

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#294]
**Reporter:**
Lars. #9309
https://steamcommunity.com/id/y0Razz/

**Summary:**
I bought the Mercedes CLS AMG, stock topspeed was around 160mph.
I upgraded it with level 4 engine, turbo and race transmission, spending about 11k.
The topspeed is now lower then before  (around 150 going downhill ), and i dont really feel like the acceleration improved aswell.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
Higher top speed and acceleration.

**Actual Results:**
Topspeed is lower and i dont think it gains any speed quicker.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080 144hz

**Player Data:**
https://i.imgur.com/wqHCQDR.png

**Notes:**
Could Kartrenko ( SORRY IF I MISPELLED THE NAME ) take a look into it maybe?
Thanks

**Comment by y0Razz** [comment]
I think the car only is this slow while you have 1 or more passengers in the car.

**Comment by InZidiuZ** [comment]
Hey,

Please use the [asset-related GitHub](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for this.

**InZidiuZ**
*OP-FW Developer*
