### ISSUE TITLE
Suggestion - TV placement 

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#2940]
### Assurance

I have read the `README.md`

### Summary

i was wondering if its possible to replace the old car photos above the casting sofa with a TV, i have attached the photo 
![hayes](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/90c657cb-c592-4acd-8fc9-ce106ea3407b)

### Reason

the reason is we would like to have some Promotional videos been displayed as well as some future giveaways that would be great, maybe even making a montage of team photos and have it there. One of the ideas would be maybe having a employee of the month and we could esseantually have a photo of the person there with some information

**Comment by coalaura** [comment]
this would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by gadjinee** [comment]
my bad, i'll change it
