### ISSUE TITLE
Suggestion - PD Undercover Calls

### ISSUE THREAD

**Issue by ThisIsNotDex** [InZidiuZ/op-framework-issue-tracker#2943]
### Assurance

I have read the `README.md`

### Summary

While on /undercover tracker mode on a PD character, send all calls through the phones 911 texts and all dispatch calls in chat through to cops on /undercover. 

### Reason

Most of the time when on undercover tracker it's really helpful to have 911 calls and information to be able to head to certain areas to check things out.

**Comment by ThisIsNotDex** [comment]
And possibly a /undercover 1/2 command, where /undercover 1 would have sidearms drawn from the waistband, while /undercover 2 would draw a sidearm from a holster

**Comment by coalaura** [comment]
Wouldn't that basically make it like being on duty just your time is tracked differently?

**Comment by coalaura** [comment]
@ThisIsNotDex
