### ISSUE TITLE
Suggestion - Salieris food

### ISSUE THREAD

**Issue by Jordan7rider** [InZidiuZ/op-framework-issue-tracker#2944]
### Assurance

I have read the `README.md`

### Summary

I had company name SALIERI’S bar but there is nothing do or craft food. The item menu which is found there is so similar to others public bar. The other bar or restaurant owners also can see our bar menu so if you can make it only SALIERI’S owner and staff can see the menu. And add some items in our bar’s menu too to sell or craft some food item for sell to civilian.

### Reason

This might help me alot to give rp from SALIERI’S bar. I always try to give my best to that bar like live music, 24 hour open for hard drinks etc. And also compare to other companies owner they get pretty good pay off but our company(SALIERI’S Bar) only pays 25$ - per hour   i hope this will be also increase like 70$.

**Comment by xplrerin** [comment]
I don’t use Salieris or anything but I want to just add whilst this is here that some items aka the Cokes in the Salieris store is $25.. Which is more expensive than a regular store and the likes of Burger Shot. Think the bar stores should have a revamp with pricing.

**Comment by MetaHatter** [comment]
Don't you already have a suggestion open for this? Duplicates aren't needed and actually slow down the process. #2895
