### ISSUE TITLE
Suggestion - Sniper and Shotgun Ammo for Legal Citizens

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#2945]
### Assurance

I have read the `README.md`

### Summary

With the new change, it is more difficult for legal citizens that hold the appropriate licenses to get the ammo for their guns. You must be legal to get the licenses that would allow you to have the hunting rifle and weapons license shotgun. 

Therefore, maybe the ability to buy that ammo is locked behind that license. 

### Reason

Most of these people are business owning/business managers and they do not have the ability to get the appropriate job or neither should they be committing crime to get the ammo.

As Governor, I also usually waste a couple days at the beginning of the month to go thru the active licenses and remove any that would be breaking the laws therefore the licenses are usually correct for the appropriate people to get the appropriate ammo for their guns to do their legal hunting.

**Comment by coalaura** [comment]
I did not mean to remove shotgun ammo, that is a bug. Sniper ammo can be found in the hunting store
