### ISSUE TITLE
CONCERN - Commenting on Roleplay Balance

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#2946]
### Assurance

I have read the `README.md`

### Summary

This will outline the main concerns I and other business owners share regarding the balance of legal citizens and business owners roleplay alike, versus police and criminal roleplay.

### Reason

Firstly I would like to start off by saying running Green Wonderland is absolute chaos and it's no secret or surprise to anyone in this community. I feel as if my business is one of the hardest, if not THE hardest business to maintain when it comes to keeping employees safe, which has direct correlation to the business being open and the willingness of myself, and employees to run the business effectively. Average cop response time to the business is not favored, even when called by myself/employees. I completely understand the police are thin in some timezones or simply just not available due to the amount of other crimes taking place that may take precedence or have a higher priority. So that leaves it up to us to protect ourselves and eachother, which leads me to number issue number two: 

It has come to my attention that shotgun ammo, as well as sniper ammo is no longer purchasable from ammu-nation. So let me get this straight, I've just paid 5 thousand dollars for a weapons license, another 8.5 thousand for a shotgun. Only to realize I have no legitimate way of purchasing ammunition for my legally purchased weapon. **HUH?** My shop does not make enough revenue to afford security or the time invested to hunt down boxes of shotgun ammo so my employees can legally and safely defend themselves on my property, not to mention whether or not it would be legal for us to obtain ammo from non-official sources(?)

From my perspective, this outlines one of the few core issues I believe that affect the balance of the roleplay in the server. A criminal can easily go build a pager, get a sub machine gun and lay waste to whomever they felt like. It's even easier for a police officer to buy guns from their armory which I'm sure does not have a restriction on the ammo available for purchase. Kay outlines a good suggestion to combat this change (https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2945) but I feel like this maybe wasn't thought of before implementation. Resulting in a larger headache than benefit across the community with the proposed changes.

Among these issues considered, leaves me asking myself what can I do to make sure not only that Green Wonderland stays open, how do I protect my employees, keep them engaged at the shop amidst the chaos of new player influxes or gang activity wreaking havoc on other customers or employees? What is the point in spending all of this money for legal avenues of protection when they're actively being stripped or becoming harder to obtain either via cost or availability, or at worst, robbed off of you from a pocket wipe? Why should I bother continue being a legal entity when it seems that I could just give up GW and go back to robbing banks and taking people hostage/participating in gang activity/drug selling because it clearly seems more viable and profitable. Not to mention the possible protection aspects from having well known gangs in your clique? Or most importantly, going back to having fun while I'm in the server.

I would also like to briefly talk about streaming and player reporting as a whole. It is becoming a task to have to stop my roleplay to either deal with a rule breaker either trying to kill me or an employee, clipping that and making a report. Every. Time. Something. Happens. **there is always something happening at green wonderland.** It is also worth mentioning that some people don't even have the capability or technical inclination to record or stream their interactions to begin making a report. I do not need to explain why this is already an issue. An issue that has led to employees of my shop being outright banned on the spot for something that was so clearly taken out of context that they were unbanned when they showed their side of the story, multiple times.

I have asked some of my employees and managers to comment below expressing their concerns as well as other business owners willing to share their concerns regarding the roleplay balance of the server.

**Comment by coalaura** [comment]
> It has come to my attention that shotgun ammo, as well as sniper ammo is no longer purchasable from ammu-nation.

I did not mean to remove shotgun ammo and it will be back with the next update. Sniper ammo can be found in the hunting store since its used mainly for hunting purposes
