### ISSUE TITLE
Bug report - Boosting not working

### ISSUE THREAD

**Issue by LethalJod** [InZidiuZ/op-framework-issue-tracker#2948]
### Assurance

I have read the `README.md`

### Reporter

Milind7x#2607

### Summary

i have some issue in boosting when i m going to spot there is no car. i tried 2 contracts and have same issue

### Steps to Reproduce

dk

### Expected Behavior

dk

### Actual Results

dk

### Screenshots/Videos

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/144170312/36619dfb-1843-4b1b-a5d4-9ad9afdd693d)

### Game Resolution

1920x1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/144170312/103aba53-a7c3-46d1-b537-bbfba0166b57)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
Is this still an issue?

**Comment by coalaura** [comment]
closed due to inactivity
