### ISSUE TITLE
Suggestion - More Food Variety at Tequilala

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/op-framework-issue-tracker#2951]
### Assurance

I have read the `README.md`

### Summary

It would be nice if there were more food options at the bar like wings or pizza like you can get at liberty bars. Alternatively, it would be cool to have a special drink that you can only get at Tequilala like how you can only get an Irish coffee at Omalleys. 

### Reason

Sometimes the bar is the only place that is open food wise, and a lot of people come in asking for food, but the prices for the food we have are more expensive than gas station food so most people figure it is more worth it to find a gas station for food.

**Comment by Kay32** [comment]
Its been a while since we've gotten new food. It would just be fun to maybe see all bars get some sort of "appetizer" thats better than peanuts available to all bars as most are now at least owned in the international server.

**Comment by coalaura** [comment]
So, bars wont get real food cause they are bars not restaurants. I did however add another new appetizer for bars
