### ISSUE TITLE
Suggestion - Change the storage in houses

### ISSUE THREAD

**Issue by Goob0** [InZidiuZ/op-framework-issue-tracker#2953]
### Assurance

I have read the `README.md`

### Summary

I think that if you’re gonna spend $17k a week for a house it should have the same storage as a house that you pay $10k a week for i think michaels interior should be 7500, then franklin 8500 and high end 10000 or something along those lines 

### Reason

It would be good because if i’m paying all that money i shouldn’t run out if storage

**Comment by coalaura** [comment]
The max storage size ALREADY varies per shell type. I have upped them a slight bit more tho
