### ISSUE TITLE
Bug report - Elevator At Mt. Zonah Medical Center

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#2954]
### Assurance

I have read the `README.md`

### Reporter

vik_ky 

### Summary

Seems Like Elevator at Mt. Zonah is bugged from some time . when we try to go to Surgery Floor it TPed character to road outside the hospital . tried to access surgery floor from ground floor , second floor and roof also . same result all the time.

### Steps to Reproduce

1 ) in Mt. Zonah enter elevator
2 ) select Surgery Floor 
3 ) wait till animation to be complete

### Expected Behavior

character to be TPed to Surgery Floor in Mt. Zonah medical center.

### Actual Results

instead of Surgery Floor , character got TPed to Road on outside of Mt. Zonah.

### Screenshots/Videos

https://youtu.be/SIVcytQvqps

### Game Resolution

1920*1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/64215926/c83b1567-894f-46db-a9af-04126b842833)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
should be fixed next update

**Comment by Vikky98** [comment]
> should be fixed next update

Thank you 🤌🏻
