### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2955]
### Assurance

I have read the `README.md`

### Reporter

botjordan0000

### Summary

Sultan RS PDM car inside of the super section costs about 150k in-game, and makes this horrible bumping sound the entire time you are driving it. It practically doesn't turn. 

### Steps to Reproduce

My car is fully upgraded with lowered suspension. I don't have any off set on the wheels and it continues to do it. 

### Expected Behavior

Very loud, obnoxious bumping sound whenever driving it

### Actual Results

Listed above

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1u9LWc0Bl1IGws/d1337EPcQ6rg?invite=cr-MSxCMDksNjIzMTM5NDks

### Game Resolution

1920-1080

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
This would be an asset issue (https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
