### ISSUE TITLE
Suggestion - Different Colored Blip for Cadets

### ISSUE THREAD

**Issue by teddythedev** [InZidiuZ/op-framework-issue-tracker#2956]
### Assurance

I have read the `README.md`

### Summary

Create a different colored blip for cadets, maybe a light green or like blue/green to match the PD vibe.

### Reason

We are trying to crack down on numbers at situations and hold command accountable for counting. However, we struggle around cadet waves because cadets we count as a half since they won't have any large weapons and usually are untrained so stay back at the vehicle.

It's a lot easier to count blip circles on the map then having to go through each individual and make sure they aren't a cadet.

**Comment by coalaura** [comment]
This was talked about already and was decided against
