### ISSUE TITLE
Bug report - Teleport Rotation Incorrect

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#2957]
### Assurance

I have read the `README.md`

### Reporter

CloudTheWolf

### Summary

When entering the Casino Parking / Casino Warehouse in a vehicle, the vehicle is not facing the direction of the entrance.
Not an issue on smaller vehicles, but is an issue with larger vehicles 

### Steps to Reproduce

- Enter the Casino Carpark in a vehicle.
- Notice that you are facing sideways instead of straight ahead

### Expected Behavior

Vehicle should be facing the direction of expected travel

### Actual Results

Vehicle as facing the site of the room. I assume the rotation is just not being updated on the Teleport

### Screenshots/Videos

Can't fly in atm to get, but will try and get one and append to ticket if needed 

### Game Resolution

1920x1080

### Player Data

N/A

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
