### ISSUE TITLE
Suggestion - Smart watch addition (Zombies Slain)

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2958]
### Assurance

I have read the `README.md`

### Summary

We currently have a locals murdered counter on the smart watch, but I think it'd be cool to have a zombies slain/killed counter as well. 

It could go right next to the locals murdered counter:
![image (3)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/c4f3dbbc-4ce0-4c45-a29b-98654ef74026)

### Reason

It's just good fun to rack up stats. Could generate new talking points when visiting the Arcade or just in general conversation. This could also be useful in setting up event ideas around the already popular Zombie Pills.

**Comment by coalaura** [comment]
I don't really wanna add so much more to that UI. I feel like it starting to get quite cluttered
