### ISSUE TITLE
/Race finish line icon

### ISSUE THREAD

**Issue by tankfurious** [InZidiuZ/op-framework-issue-tracker#296]
**Name:**
Tankfurious

**Summary:**
During a /race the finish line icon is too big please could this be moved or made smaller/more transparent

**Reason:**
The icon often blocks ped traffic and bends/turns in the road often leading to frustrating crashes and race losses.

**Comment by InZidiuZ** [comment]
Hey,

Not exactly sure how you mean the icon is too big? 🤔 It's *very* tiny, and wouldn't block any of your view. So no, this will not be changed.

**InZidiuZ**
*OP-FW Developer*
