### ISSUE TITLE
Tequilala issues and concerns

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#2960]
### Assurance

I have read the `README.md`

### Summary

No Locker, ingame Music mixes with custom Music, pay issue

### Reason

Locker - self explanatory

ingame music messing custom music - I have had people try and play / perform and the inside game music messes with  their performance and plays

pay - manger role pays 40$ every 15 mins I was making more as a senior mech, I think there should be a new role “owner” role for the bar and that should pay roughly a bit more then a mechanic syop

**Comment by coalaura** [comment]
> Locker - self explanatory

Why? Whats the need for a locker

> ingame music messing custom music 

Use a boombox

> pay - manger role pays 40$ every 15 mins I was making more as a senior mech, I think there should be a new role “owner” role for the bar and that should pay roughly a bit more then a mechanic syop

All bar and club businesses make the same, paycheck wont change

**Comment by SluggsV2** [comment]
Locker would be used to keep alcohol and snacks in, also a clothing change, work attire to non work attire

Music - even with a boombox the original gta v music still messes with it

**Comment by coalaura** [comment]
> Locker would be used to keep alcohol and snacks in

There is a store in tequilala why would you store extra alcohol in lockers

> Music - even with a boombox the original gta v music still messes with it

In your settings you can turn off Music

> also a clothing change, work attire to non work attire

Done, added
