### ISSUE TITLE
Tow for everyone 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#2963]
### Assurance

I have read the `README.md`

### Summary

Allow the / tow command for everyone, but only allow Tow truck purchasing with the tow truck role from life invader

### Reason

This allows other whitelidfed jobs to have another side hustle to do when the “bar or food shop” is closed 

also allow them to drop off the cars at impound with out roles

**Comment by ImArteria** [comment]
Honestly I was always on the wave of just making the tow driver role unwhitelisted but all mechanic jobs WL obviously

**Comment by SluggsV2** [comment]
Maybe we can have Tow trucks only able to tow and impound not do any mechanic work or have access to mechanics door,

**Comment by TacticalTyl3r** [comment]
It is not whitelisted and is just a server config that can be placed into LI by the Manager of the server.

**Comment by coalaura** [comment]
what tyler said
