### ISSUE TITLE
Suggestion - Smell People

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2964]
### Assurance

I have read the `README.md`

### Summary

If within 1m of a person with an odor, a "description-like" status will show up to tell you how they smell if it's not "clean".  

**Potential Statuses**
--------------------------
**Cleanable statuses - use a sink, shower or swim to remove.**
- Oily - People that don't within 1 in-city day.
- Smelly - People that don't within 2 in-city days.
- Crusty - People that don't within 5 in-city days.
- Dank - If they have smoked weed within the last 30 IRL minutes. (can wash off)
- Smokey - If they had a cigarette within the last 30 minutes. (can wash off)

Sweet/Flowery/Minty/etc - Could be tied to a cologne/perfume/essential oil item that will cover/replace up the above odors

**Timed Statuses - Cannot be removed**
- Boozed - If they have had a drink within the last 30 IRL minutes.  Possibly scale with amount drunk.

Possibly add a chewing gum or mint item that will reduce the radius of detection.

### Reason

To add to immersion and RP possibilities as well as create an entirely new market for items in the city.

- Fragrance vendors could be a thing. People could fancy up for events with rare/expensive perfumes/colognes and essential oils can cover the "cheap" option.
- PD RP i.e. breathalyzer use could be more common
- Gross people could come across as gross on sight

This can obviously be expanded further, but I feel that the 1m radius for detection could provide value without ruining immersion for people that are just passing by.

**Comment by joevapes3** [comment]
this would be dope

**Comment by DaxterPancake** [comment]
I like this idea a lot, but in-city days go by pretty fast so maybe we extend that out a little.

**Comment by ImArteria** [comment]
I wanna be moist

**Comment by coalaura** [comment]
i like the idea of making it so you can smell weed or alcohol but i dont like the idea of "smelling" in general with you having to wash every now and then

**Comment by coalaura** [comment]
added something like this
