### ISSUE TITLE
Suggestion - Fire Department Improvements

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/op-framework-issue-tracker#2966]
### Assurance

I have read the `README.md`

### Summary

I wanted to suggest some improvements for our Fire Station, particularly in the Personal Garage area. Additionally, I have some ideas for updates to our job roles and pay rates. These changes aim to make our Fire Department experience more enjoyable and realistic.

### Reason

Parking Space for FD Personal Vehicles: 
We'd like to request the addition of a designated parking space in front of our FD station exclusively for personal vehicles of our firefighters. This dedicated space will help organize our station and make it more efficient for our team members to access their vehicles when necessary.

https://cdn.discordapp.com/attachments/907360570968268800/1156747422169575524/image.png?ex=6516187c&is=6514c6fc&hm=06b2078b85a7a7db001ee549cf0a9b85e032db5cf043fd7e3d1e406fcc8d199d&

Logout Point in the Bunk Room: 
To enhance convenience and realism, we suggest the implementation of a logout point within the bunk room. This will allow firefighters to log out directly from their sleeping quarters, replicating the process of getting rest after a shift.

https://cdn.discordapp.com/attachments/907360570968268800/1156747514817544222/image.png?ex=65161892&is=6514c712&hm=a6248d5948eb6c00357225ee268ae65c5c3ac14687c5ca820464949f7768fb1e&

Job Updates and Pay Rates:
To maintain the standard for pd/ems/doc and ensure our firefighters are adequately compensated for their commitment and hard work, we propose updates to job roles and their corresponding pay rates. Below are the recommended adjustments: 

(Our jobs haven't been updated since we split from EMS so fixing these will help us better match the pay scale that EMS/PD/DOC have)

Fire Chief: $152
Assistant Chief: $146
Captain: $138
Lieutenant: $124
Senior Firefighter: $114
Firefighter: $104
Probationary Firefighter: $94
Recruit: $84
Explorer: $74 (This rank doesn't exist however it does within our department if it could be added that would be awesome!)

**Comment by coalaura** [comment]
Fire Chief: $150
Assistant Chief: $144
Fire Captain -> Captain: $134
Fire Lieutenant -> Lieutenant: $124
Senior Firefighter: $110
Firefighter: $102
Probationary Firefighter: $94
Recruit: $82
Explorer: $70

*jobs & pay increase done*

**Comment by coalaura** [comment]
all done

**Comment by mastersamii** [comment]
thanks so much we appreciate you!!! <3
