### ISSUE TITLE
Suggestion - Bill payment confirmation in chat log

### ISSUE THREAD

**Issue by BaronVonSnergerberger** [InZidiuZ/op-framework-issue-tracker#2967]
### Assurance

I have read the `README.md`

### Summary

Would appreciate a confirmation in the chat log for a bill being successfully paid with the name and payment received in the same place as it currently shows that we are sending a bill to someone.

### Reason

As a mechanic I've missed many times whether or not someone has sent me a payment, or if they failed to pay because they don't have a smart-watch, or cash on them, etc. The pop up confirmation can be missed, especially during peak hours with heavy traffic into shops on even a normal calm day. Add in the chaotic moments, shenanigans, being the only mechanic on duty sometimes, with a line out the door of people waiting for repairs or rushing, needing to teach newer people to the city how to pay, bill for mats, smart-watch tech, where the ATM is, etc...it can be overwhelming and we can miss out on whether or not we've actually been paid.

I genuinely believe if we could simply relocate the confirmation of payment received to a chat-oriented format similar to when we send the bill to someone it'd remedy this situation, so there is less confusion.

**Comment by coalaura** [comment]
done

**Comment by BaronVonSnergerberger** [comment]
Love the change to show that we were successfully paid, however it shows our name (the person billing's name) as being the one who successfully paid the bill. Kind of a minor issue, but if it could be changed to the person receiving the bill it'd be perfect.
