### ISSUE TITLE
Suggestion - Improve canceling dumpster dive

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#2968]
### Assurance

I have read the `README.md`

### Summary

Add the ability to use the X key to cancel a dumpster dive.
Stop the dumpster dive animation on cancel.

### Reason

Currently you get animation locked, often by mistake, and the only way to cancel is with escape (which leaves you in the dumpster search animation).

X is a more consistent key for canceling actions and the animation seems like a big fix more than a suggestion but here since related.

**Comment by coalaura** [comment]
> the only way to cancel is with escape (which leaves you in the dumpster search animation)

It doesn't leave you in the animation though, it cancels the search and the animation
https://medal.tv/games/gta-v/clips/1wtustlvk4n12T/d1337DWskE0b

I've added "X" as an additional button to cancel searching a dumpster

**Comment by MetaHatter** [comment]
Odd... I got stuck in it the one test I did... might have been a fluke... Thanks
