### ISSUE TITLE
Suggestion - Add a spawn point at Cayo Perico for Police and EMS.

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2969]
### Assurance

I have read the `README.md`

### Summary

We cant spawn at Cayo perico, would be easier if there was an option to do so.

### Reason

There is a police station at cayo but no spawn point.

**Comment by coalaura** [comment]
done

**Comment by sakar5157** [comment]
> done

Thank you sir, would be better if there was a logout point too.

**Comment by coalaura** [comment]
not a sir and i don't think a logout spot is needed

**Comment by sakar5157** [comment]
> not a sir and i don't think a logout spot is needed

alright, no worries.
