### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by walwin90** [InZidiuZ/op-framework-issue-tracker#297]
**Name:** 
Who is suggesting this? Please include discord name.
Christoffer ( WaLwiN#9550 @ discord)

**Summary:** 
Write a short summary of what your suggestion is about.
:Mcs to exclusive car dealern. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
Becuse players dont only wants cars,they want some cool mcs to. I know atleast 5 friends that want the same. And i think it will lead to some more supporters to the server,and thats good? Not all players are car drivers,some like mcs more. And that mabye will start some new cool mcs gangs? ANd that can give alot more RP.

**Comment by InZidiuZ** [comment]
Hey,

This is the wrong place to post this. Post it at the asset-related GitHub page.

**InZidiuZ**
*OP-FW Developer*
