### ISSUE TITLE
Suggestion - Spawn Upgraded delivery van for Burgershot

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2972]
### Assurance

I have read the `README.md`

### Summary

The burgershot delivery van has very low armor and gets wrecked even on a minor crash. 

### Reason

Delivery jobs are too difficult using the burgershot van.

**Comment by coalaura** [comment]
1. Don't crash
2. This would be something for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
