### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by TheGaddu** [InZidiuZ/op-framework-issue-tracker#2974]
### Assurance

I have read the `README.md`

### Reporter

goddevil_

### Summary

i am getting banned agin and again while trying to spawn 

### Steps to Reproduce

when you go to sea around military ship and log out their and join after quite a time then this problem is taking place

### Expected Behavior

i should normally be spawned in ocean swimming

### Actual Results

i am getting banned and showing that i am trying to fly in server

### Screenshots/Videos

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147269137/b4c5a818-30b9-4229-b1ba-f551817427ed

### Game Resolution

1920 x1080p

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
What is the ban message???

**Comment by TheGaddu** [comment]
flying is not enabled on server

**Comment by coalaura** [comment]
i am unable to reproduce this
