### ISSUE TITLE
Bug report - Weird behavior when vaulting fences, etc.

### ISSUE THREAD

**Issue by lavanya1995123** [InZidiuZ/op-framework-issue-tracker#2975]
### Assurance

I have read the `README.md`

### Reporter

Texter#6639

### Summary

every time i open the door of my house i spwan some where else and fall from the sky and die.

### Steps to Reproduce

don't know

### Expected Behavior

spwan outside my door.

### Actual Results

spwaning somewhere else and falling from sky and dying.

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
What house?  
Do you have a clip/recording?

**Comment by King2704** [comment]
https://discord.com/channels/618449264271687682/777722318159347712/1160164320131424299 

here's a clip of it happening to me after spawning in a different house

**Comment by coalaura** [comment]
Believe this is probably a bug in the game itself

**Comment by coalaura** [comment]
yeah i really have no clue
