### ISSUE TITLE
Finance Request to friends 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#2976]
### Assurance

I have read the `README.md`

### Summary

Finance Request can be game changer and can be best option for friends borrowing money from each other. 

Currently people just give money on their trust and expect that his/her friend will return him. So times if his/her friend gets banned than lol he just lost lacs of dollars that he just gave to his friend.

Request Finance maybe not the correct term here but you guys will suggest me one, I know that.

How will it work?? 

It’s simple thing and it is already aviable at pdm. We just need to make some changes to pdm finance code maybe then we will good to go (maybe you need to rewrite whole code)

Whenever someone want to borrow money from friend , they can request finance from friend and it will work like same as pdm, they can return pay finance using /comp or /companies.

The guy giving money can set terms and conditions like Max time to pay that is total weeks to pay finance. Total amount and each week amount etc.

this is made more better if we can added players assets in exchange of finance.

For example A guy borrowed money from B and the amount was for example $210,000.00
Then B guy can add some item of A that is worth $210,000.00 or maybe A  himself add item worth same amount and if A didn’t pay finance in given time then all the items that were kept as security will be transferred to B guy.

This can be always made better by suggestions of you all guess.

### Reason

This will increase Rp of borrowing money. Also we don’t have Bank to get loans and not everywhere is finance options aviable like pdm.

At LA or Tuner , we have to pay full amount to buy a vehicle and giving money to someone , is harder to trust. 

This “Request finance” can be great addition with right design, idea and permissions.

**Comment by coalaura** [comment]
Having the option to repay someone through a menu makes no difference tho. If like you said the person gets banned or decides to break your trust you still don't get your money. I don't see a real need for this...
