### ISSUE TITLE
Suggestion - PD impound

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2979]
### Assurance

I have read the `README.md`

### Summary

Would be better if PD can PD impound cars from anywhere instead of having to travel entire map in order to get to MRPD.
or at least one PD impound spot on all the PD around the maps, including Cayo.
or any kind of PD tow vehicle would be appreciated.

### Reason

Its difficult to PD impound cars if the vehicle is disabled or they are further away from the spot.
In less populated servers, its hard to find mechanic at the time of need.

**Comment by TacticalTyl3r** [comment]
I will agree that it would be nice for PD impounds to be in more locations. Maybe not every PD but atlease 1 in the city. 1 in Sandy and 1 in Paleto like there is for normal impound.

As for PD tow I dont see that happening. In international we usually always have an advanced repair kit and then hotwire the vehicle if there is no tow available.

**Comment by coalaura** [comment]
I like it just being in one spot. Its like a PD Impound Lot
