### ISSUE TITLE
Selling found weapons at ammunation

### ISSUE THREAD

**Issue by OfficerKiloTV** [InZidiuZ/op-framework-issue-tracker#298]
OfficerKilo#3243

Being able to sell guns found thru garbage collection. And other means

I have like 8 pistols and cant do anything with them besides saving them up. Getting like a portion of what they're worth from Ammunation would give a reason to them. Also Gun stores buy used guns all the time

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

I'd recommend selling them to other players. In the future, the idea would be to give players the ability to open stores, where their stock is self-created, meaning they'd have to find ways to purchase items for their stock, possibly from people like you.

Also guessing at some point a melting location would also be added, allowing you to melt various items back to base materials.

**InZidiuZ**
*OP-FW Developer*
