### ISSUE TITLE
Bug report - Mic Bug Bug

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#2982]
### Assurance

I have read the `README.md`

### Reporter

Arteria and Masik

### Summary

Mic bug won't let us place it =( 

### Steps to Reproduce

Buy Mic BUG
Place it down
Error, wont let you place

### Expected Behavior

It'll let you place it 

### Actual Results

https://cdn.discordapp.com/attachments/1016713049673060393/1152396087160741898/image.png?ex=653316fd&is=6520a1fd&hm=0a65f7825c0a6a8d587d0a4520726395d5bcad4e2dc6542db73223c539d0d7f5&

### Screenshots/Videos

See above

### Game Resolution

1920x1080

### Player Data

https://i.imgur.com/BCQTxK1.png

### Server

International (c3s1.op-framework.com)

**Comment by ImArteria** [comment]
This also happens with the vehicle tracker as well as I just been informed. 
https://cdn.discordapp.com/attachments/734923516394209332/1162189638878888066/image.png?ex=653b0872&is=65289372&hm=b6f9e37738ec82127128dd44b233227e05e75b5e9cc726e901991a39391a9f4f&

**Comment by InZidiuZ** [comment]
This should now be resolved.
![LBOMdt](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/22295402/f2bc0eba-f777-4cc5-a948-4da294bfa156)
