### ISSUE TITLE
Suggestion - Phone Suggestions

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#2983]
### Assurance

I have read the `README.md`

### Summary

# Phone Suggestions #
**Messages**
Change `Erase the call` to `Erase entire conversation`
Change `Erase Entire Conversation` to `Erase all conversations`
**Contacts**
When Deleting a contact `delete the 3 unneeded cancel buttons` and than change `Supprimer` to `Delete Contact`
**Calling**
add a dash in it so you don't need to make a contact so you can call someone

### Reason

Make the phone make more sense

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/rUpAMIWI33.png)
