### ISSUE TITLE
Suggestion - Random rotation for the god tier import

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#2985]
### Assurance

I have read the `README.md`

### Summary

The god tier import randomly rotates instead of on Saturday every 2 weeks.

### Reason

People sit and wait for the rotation to happen and the 5 cars on the inside almost sell immediately. Some keep but most of the time they try to be flipped for profit. Just gives more people a chance to be able to purchase these cars.

**Comment by coalaura** [comment]
No, the rotation works the same as EDM. These cars are intended to be super rare
