### ISSUE TITLE
Suggestion - Speeding Up Avocado Smoothie Making Process.

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#2986]
### Assurance

I have read the `README.md`

### Summary

Currently the Speed of Avocado Smoothie making is bit slow as compared to other things like burger and fries . so can we speed that up lil bit so the BS Employees can make meals lil bit quickly in rush hours .

### Reason

same as mentioned above , current speed to slow as compares to other process at burgershot and due to that sometime queue gets increasing and customers start quarrel . if that process can be speed up a lil , it'll be helpful for everyone.,

**Comment by scufflord** [comment]
It's roughly 15 seconds I believe to make it right now. Definitely takes a while if people come in and ask for multiple meals with shakes instead of cokes. for each meal that's 1 full minute to make the shakes, plus the time it takes to cook the burgers and assemble them.

**Comment by coalaura** [comment]
done
