### ISSUE TITLE
Car Wash

### ISSUE THREAD

**Issue by meeksbtw** [InZidiuZ/op-framework-issue-tracker#299]
**Name:**
Meeks#5150

**Summary:**
Implementing one or two car washes up in Sandy/Paleto 

**Reason:**
I always love my cars clean, and I hate when i'm up in Paleto/Sandy and have to drive half way across the map just to clean my car.

**Comment by InZidiuZ** [comment]
Hey,

I've added another 3 car washes, one in Sandy Shores, one in Grapeseed and one in Paleto.

**InZidiuZ**
*OP-FW Devleoper*
