### ISSUE TITLE
Suggestion -  Please add some new Indian clothes like pagdi , kurta pajama etc.

### ISSUE THREAD

**Issue by SkullCrusherOP** [InZidiuZ/op-framework-issue-tracker#2990]
### Assurance

I have read the `README.md`

### Summary

n/a

### Reason

suggestion

**Comment by DaxterPancake** [comment]
This is the wrong tracker, clothing requests are to be made [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

Also, when you post it there, please post links and/or pictures. You will have a better chance if you provide pre-made clothing.
