### ISSUE TITLE
Suggestion - Cheaper Gas/Extra Store items in Paleto

### ISSUE THREAD

**Issue by oceandabs** [InZidiuZ/op-framework-issue-tracker#2991]
### Assurance

I have read the `README.md`

### Summary

In Paleto the gas station needs menthol cigarettes, chewing tobacco, cheaper gas, maybe a crack pipe for sale even.

### Reason

This will bring much better roleplay for people who explore the reaches of their city. Also bringing more customers north for Paleto Repair.

**Comment by HollaYalla** [comment]
make stuff like gas and some other things cheaper in more empty areas and in more populated areas it cost more

**Comment by TacticalTyl3r** [comment]
I wish gas prices changed with what car type you are driving or having fluctuating gas prices since demand goes up and down from day to day.

**Comment by coalaura** [comment]
> This will bring much better roleplay for people who explore the reaches of their city. Also bringing more customers north for Paleto Repair.

There is already a lot of things that only exist up north......

I've changed the grocery store in paleto to have a bunch of unique and rare items
