### ISSUE TITLE
Suggestion - BCFD Rockford or Davis Station

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#2992]
### Assurance

I have read the `README.md`

### Summary

Could we get a BCFD station at Rockford next to Mount Z or a Davis Station near Mosleys it would help with our response time since right now it takes like 4 minutes to get from BCFD station to the mid city but if we had a station there it would improve our response time and also improve rp since we could have certain people stationed at different places if enough BCFD r on

### Reason

It would allow us to expand the BCFD

**Comment by TacticalTyl3r** [comment]
If you are looking for an MLO you want to use this github tracker https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

I know the station by Davis you can walk into the tuck bay which you can stage your engine there for quicker response times in the time being. Basically just drive your truck there and wait for a call. If its a script issue then this would be the place for it.

**Comment by CloudTheWolf** [comment]
Yeah, I would say atm there's not really enough RP to warrant more MLO'.

The station By Davis and by St F are both Open interiors so you could RP Stationing there

**Comment by coalaura** [comment]
Like cloud said at this time i dont think there is a need for the ***Blaine County*** Fire Department to have a station in the city.
