### ISSUE TITLE
Suggestion - Body Repairing

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#2993]
### Assurance

I have read the `README.md`

### Summary

Maybe change the body repairing from the mechanic2 to the welding emote and keep the repairing engine the same
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/40c5efab-0699-4fbd-b892-b2ff885d910a)
to
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/18d5db39-f956-42ac-9cb9-eba521af13d3)

### Reason

Would add some variation from engine repair and body repair and make it look better in my opinion

**Comment by coalaura** [comment]
That animation doesn't work for a lot of cars
