### ISSUE TITLE
Suggestion - Ability for Animal Peds to Jump on Small Obstacles .

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#2994]
### Assurance

I have read the `README.md`

### Summary

We got animal peds back, but they've got very few abilities that can be performed. apart from emotes, can we get small ability to jump, like the small high ground in parking lot of burgershot , Mt. Zonah, etc.?

### Reason

if animal peds can jump it'll be interesting like then animal can jump over lil high ground and sit there peacefully and much more .

**Comment by coalaura** [comment]
Thats a limitation of the game itself, we are not preventing animals from jumping they just cant
