### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by ighomm** [InZidiuZ/op-framework-issue-tracker#2995]
### Assurance

I have read the `README.md`

### Reporter

omm#6634

### Summary

so there is a bug  it seems to occasionally lead to temporary immobilization upon death or sudden falls

### Steps to Reproduce

step1-you should have the bnt mp5 with you.
step2-you have to die while shooting./ you have to fall from a high place 

### Expected Behavior

your character should not get stuck when you die or when you fall 

### Actual Results

your character is getting stuck when you are dieing of fall from some where 

### Screenshots/Videos

https://youtu.be/9uCHwoyH1PQ

### Game Resolution

1920x1080

### Player Data

https://cdn.discordapp.com/attachments/970661442036596766/1166166642787627048/image.png?ex=65498051&is=65370b51&hm=6d29dd1167ffe34a277099dc3fd641924b72d3a89dbd95b7dff8d534a7036525&

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
This should be fixed
