### ISSUE TITLE
Suggestion - Bollard Installation at Videogeddon

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#2996]
### Assurance

I have read the `README.md`

### Summary

Currently, vehicles are used to block the door. If possible, can we add permanent parking bollards around the door to stop this?

Up to your judgement, but it COULD look like this:
![poles for front door](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/9ecda30b-cf1a-45df-877b-b5dc41269d20)

### Reason

People have been blocking the door to the Arcade making it so no one can enter or exit. This has been an issue in the past, but recently it appears to be a bigger problem. It's a huge disruption that needs to be remedied.

**Comment by ristwell** [comment]
This would be very nice imho

**Comment by MetaHatter** [comment]
This is not the right github for this type of request.  You want to make map/clothing/vehicle suggestions here: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=Suggestion+-+

I'll take a look but please post the suggestion there so it doesn't get lost.

**Comment by MetaHatter** [comment]
@navonody1 I have pushed a change to address this.  In the future, be sure to use the proper github.

**Comment by navonody1** [comment]
> @navonody1 I have pushed a change to address this. In the future, be sure to use the proper github.

appreciate that, and will do...apologies.
