### ISSUE TITLE
Suggestion - open bank accounts

### ISSUE THREAD

**Issue by Saggyrims** [InZidiuZ/op-framework-issue-tracker#2997]
### Assurance

I have read the `README.md`

### Summary

So itd be like housing in a way (anything in brackets is how it links to housing) 
Add people to the bank account with different levels of access so they can put money in their and not take it out or can put it in and take it out(this would be like giving someone lvl1 access to your house so they can just come in and then lvl3 access so they can use the storage hope that makes sense)

### Reason

So then if your not in the server and say you own a company or are doing a raffle or own a gang n then gang fund can be put in there then that money can be put in a account for the owner or  event holder or leader of the gang to access

**Comment by coalaura** [comment]
duplicate #2959
