### ISSUE TITLE
Suggestion - Tequilala locker for workers

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/op-framework-issue-tracker#2998]
### Assurance

I have read the `README.md`

### Summary

I am the owner of Tequilala and it would be super appreciated if we could get a locker down in the staff room so I could give my employees supplies and menus that they could keep on site for their shifts rather than having to keep everything on them whenever they are going to work.

### Reason

Most work places have locker rooms or areas in the staff room to put down your stuff, and most places that I have worked have had places where you put your stuff that you work with, you don’t take it home with you.

It would also be a QoL thing because I frequently show up ready to open then realize I don’t have a boombox or enough tazer ammo or handcuffs or something that I need for the shift.

I keep getting flip flopped between the two GitHub’s by developers telling me it’s the wrong one, can someone please figure that out?

**Comment by Alyshiva** [comment]
> where in Tequilala 

My thought was downstairs in the staff room if that's possible

**Comment by coalaura** [comment]
@Alyshiva could you send a screenshot of where you think?
