### ISSUE TITLE
Garage Vespucci Boulevard 2

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#2999]
### Assurance

I have read the `README.md`

### Summary

Was wondering if it’s possible to add garage to Vespucci Boulevard 2

I have added some screenshots of maybe potential spots, right on back of the house at Main Street 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/71a910e4-3bf6-4b81-8b63-785fbb3547a2)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/bb073809-c94e-4d94-8fbf-90408fde27a6)

### Reason

Been able to store the cars

**Comment by CloudCait** [comment]
Is that two apartment buildings across the street? Just wondering because I own Vespucci Boulevard and properties 3 and 4 don't exist for me I just always thought it was because they're the two homes under construction next to 1 & 2.

**Comment by coalaura** [comment]
> Is that two apartment buildings across the street? Just wondering because I own Vespucci Boulevard and properties 3 and 4 don't exist for me I just always thought it was because they're the two homes under construction next to 1 & 2.

its apartment complex a and b
