### ISSUE TITLE
Harsher bleed out

### ISSUE THREAD

**Issue by Muliki** [InZidiuZ/op-framework-issue-tracker#300]
**Name:**
Muliki

**Summary:**
A longer respawn timer, and possibly a longer time you have to sit in the bed when you check in. It would make more sense to have you sitting in the hospital bed for much longer than you do if you are wounded and need to be treated. The respawn timer should also be extended and lose all items.

**Reason:**
A lot of people don't value their lives considering how easy it is to be taken to the hospital, or just respawning after 5 minutes and only having a chance of losing a few items. I believe the penalties of bleeding out or respawning should be much harsher.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not happen.

**InZidiuZ**
*OP-FW Developer*
