### ISSUE TITLE
Suggestion - More garages for the fire department

### ISSUE THREAD

**Issue by mastersamii** [InZidiuZ/op-framework-issue-tracker#3000]
### Assurance

I have read the `README.md`

### Summary

I recommend the addition of three garage points at strategic locations to enhance operational efficiency and realism:

**Fire Station Just Outside of St. F:**
This garage point would provide a convenient transition between the city and Blaine County.
https://cdn.discordapp.com/attachments/995517556209221732/1167195558285414410/station2.png?ex=654d3e92&is=653ac992&hm=685548055fc19e2f3920f2ab513ab713af4917c3eb1394600ceddde9b7cf416b&

**Fire Station Just Outside of Mt. Z:**
Another crucial point for seamless vehicle changes between city and county operations.
Ensures smoother response times and operational realism.
https://cdn.discordapp.com/attachments/995517138292969482/1154243692614389780/image.png?ex=6539cfb5&is=65275ab5&hm=26459915f47ca8c8571e2e6c8317e90b2097de6012e0164dd0f416b29bfb8485&
https://cdn.discordapp.com/attachments/995517138292969482/1154243257199501353/Screenshot_2023-09-20_215523.png?ex=654c444d&is=6539cf4d&hm=01b0125c04d9d0f09cd731496305633901ad0b69cde5934fb1cb0a910ea1fb6c&

**Fire Station Just Outside of Paleto Hospital:**
This location would serve as a valuable addition, improving response coordination in the northern region.
https://cdn.discordapp.com/attachments/995517556209221732/1167196313033658468/latest.png?ex=654d3f46&is=653aca46&hm=a384e68348c688056076c58276b0c094658b6a823a9962c5cb0c349b900ce750&

Additionally, if possible, the inclusion of helicopter spots at these points would further enhance our capabilities. However, we are open to settling for garage points if helicopter spots pose technical challenges.

You might argue that we have access to EMS buildings, it's important to note that we've established roleplay protocols preventing either department from using each other's facilities. This includes limitations on accessing doors and garages. This roleplay setup is designed to maintain realism, as realistically, we wouldn't have keys to a hospital, and EMS wouldn't have keys to a fire station.

### Reason

The reason for this proposed addition is to improve response efficiency and enhance the realism of our operations. Currently, the transition between Los Santos and Blaine County takes approximately four minutes, which can impact our ability to respond promptly to emergencies in both areas. By implementing designated vehicle change points, we aim to minimize this transition time, allowing us to provide quicker and more realistic support to incidents within and beyond city limits.

**Comment by mastersamii** [comment]
Just want to make it further clear that we do not want any more interiors just garage points if possible. <3

**Comment by coalaura** [comment]
I added one at st fiacre and in paleto but mount z already has a garage so there is no need to add a second one. You can just share it with EMS if needed
