### ISSUE TITLE
Suggestion - Drastically reduce vehicle health

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#3002]
### Assurance

I have read the `README.md`

### Summary

Currently every vehicle is designed to be quite tanky to allow for a more of an arcade style driving experience.  This has allowed for a number of negative side effects to occur.  First being full sending cars off any sort of incline because they know it's not going to disable their car and a majority of vehicles simply do not stay on their roof.  Second this arena slam mentality of car fighting or assisting in escapes where people are intentionally ramming at max speeds to knock cars off chases or slam them into walls to be able to jump out and shoot them easier.  The vehicle durability script may need to be tweaked in general with the impending global slowdown of all cars anyways since the top speeds will be a bit lower than they currently are.  

### Reason

People might have to actually RP in a RP server rather than using their cars as weapons.

**Comment by coalaura** [comment]
This would be something for the asset github. But since joe JUST pushed a big slowdown for all cars, i would wait to see how that affects things before making the issue
