### ISSUE TITLE
Suggestion - Change Repair Kit Upgrade Process

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3003]
### Assurance

I have read the `README.md`

### Summary

Currently the ability to Upgrade Basic Repair Kits to Advanced Repair Kits is publicly available to anyone, even though this is something that can only be done in Mechanic Shops.

My Suggestion is to either:

1) Lock this to the mechanic job
2) Remove this from Mechanic Shops to another location, Eg the 2 LS Customs in the city (Non-Benny's aka the 2nd gear interior) or somewhere up north (Sandy Recycle Centre or Paleto Construction would be potentially good spots)

### Reason

With the current location being inside mechanic shops, there should either be RP to upgrade the repair kits, rather than going in, not interacting with the business and just upgrading your own stuff and leaving. 
Or it should not be locked behind business doors, and instead be somewhere anyone can access.

**Comment by TacticalTyl3r** [comment]
I mean I like the idea of it being in a mechanic shop.  A public person can ask the owner/manager if they can use their work bench for a fee and then they can upgrade their repair kits.  That increases RP where if it gets moved to other locations there is just a random bench without anyone there and no interactions.  Also there is a spot you can do it that is not locked behind a business door already.

**Comment by coalaura** [comment]
I'll lock it to the mech job

**Comment by King2704** [comment]
Wasn't the whole point of crafting them that people could make Advanced repair kits when there is no mechanics around?

**Comment by scufflord** [comment]
Locking this to a job is the wrong call. PD has the ability to repair their cars if no mechanics are around, and this allowed crims to at least get to 70/70 on a car in the same situation. Now if there’s no mechanics around people are just entirely locked out of being able to even get a car repaired enough to drive. Having the one spot that was publicly available wasn’t a bad thing, and if anything maybe the spots in shops could be locked to the job to keep people from running in and making their own and avoiding the RP… but for balancing sake having a public spot is the only thing that makes sense without screwing over the population during non-peak times

**Comment by coalaura** [comment]
Honestly, i made it open for all so mechanics could let people in to do it and stuff, so ngl i think im keeping it like it is
