### ISSUE TITLE
Suggestion - Business Card Printer Paper

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3004]
### Assurance

I have read the `README.md`

### Summary

Add Paper that mimics the size and ratio of a business card to the printer store.  Works identically to the existing photo paper.

### Reason

To allow people to still have business cards but require them to create them and actually hand them out instead of leveraging the "weird" /me and /description functions.

It would also actually be faster to pass contact information than spamming /me until a number is recorded in a phone.

Will allow for the following: 
- custom designs
- collections
- evidence
- A new way to interact

**Comment by coalaura** [comment]
i like this idea

**Comment by goldenfvce** [comment]
As a business card lover, PLEASE let us have this. I would love to be able to *actually* make business cards for people. I think it would be a really cool way to show off who you are. It could be similar to how the trading cards or IDs pop up maybe?

**Comment by HollaYalla** [comment]
Yes, this would be a very good way to expand new or even old businesses and you could also go around to people and advertise a lot better, also at like a Job Fair you can just have a stack of like 20 of them and just have people take 1 but also I would probably have it as a special paper like Card Stock

**Comment by rakibulhasan456** [comment]
I also wanted to post a similar idea.

To me, one of the easiest way to build and show custom Business Card would be adding a **Show to Everyone** button in the inventory for Picture item.

The button would be below the **Use** button. When we drag a Picture to the button, it will show the picture to everyone around. (Just like ID card)

As people can print their custom design in Picture, the possibility is limitless. People can use it as Business Card, Invitation Card, Evidence, Showing picture to other without handing it over, and many more.

**Comment by MetaHatter** [comment]
> I also wanted to post a similar idea.
> 
> To me, one of the easiest way to build and show custom Business Card would be adding a **Show to Everyone** button in the inventory for Picture item.
> 
> The button would be below the **Use** button. When we drag a Picture to the button, it will show the picture to everyone around. (Just like ID card)
> 
> As people can print their custom design in Picture, the possibility is limitless. People can use it as Business Card, Invitation Card, Evidence, Showing picture to other without handing it over, and many more.

I would worry about this as it would be VERY easy for someone to "share" inappropriate pictures.  Printing a copy and handing it accomplishes the share while limiting the risk.

**Comment by coalaura** [comment]
They will not be like ids and they will only be visible to the person looking at them. There is no need for everyone in an area to constantly see business cards

**Comment by coalaura** [comment]
done
