### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Jordan7rider** [InZidiuZ/op-framework-issue-tracker#3005]
### Assurance

I have read the `README.md`

### Summary

I would love if this engine sound mod is added to our Japanese illegal beauty “Nissan Gtr r34”.
 
 
Link 

https://www.gta5-mods.com/vehicles/custom-gt-r-sound-mod-addon-for-fivem-server-side

### Reason

People will like it more and prefer Nissan Gtr r34

**Comment by coalaura** [comment]
this would be something for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
