### ISSUE TITLE
Suggestion - Rare items for diving

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3006]
### Assurance

I have read the `README.md`

### Summary

Had an idea for some super rare diving items that we could get from doing the activity itself that may add a little bit of extra quality of life when found. Two items specifically - first, an emergency air tank item that could be found from diving that if a player keeps it in their inventory while diving and accidentally presses X and loses their tank (like I just did and why I'm writing this github) or if they forget to watch the clock and end up going over on time then the item could automatically apply to them and give them 45-60 seconds of air to re-surface with. 

The other could be found in either dumpsters or at diving: old flippers. When used they give the user a 1.5x speed buff while swimming for X amount of time/until they end that tank. This would have to have not only a super low drop chance but also spawn as a severely deteriorated item that will only last for a very short duration, so nobody can hoard them and use a bunch of them to grind with. Maybe 6-12 hours at most. Once it breaks, you could then take that somewhere and disassemble it into rubber too. 

### Reason

Adds a little bit of new flavor to an activity that has been pretty much the same for a long time.

**Comment by coalaura** [comment]
I changed it now so if you are actively swimming X will not take off your scuba gear

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/ZAxUzElI46.png)
