### ISSUE TITLE
Suggestion - Real Estate Employees can send Leases

### ISSUE THREAD

**Issue by M4TT3R1** [InZidiuZ/op-framework-issue-tracker#3008]
### Assurance

I have read the `README.md`

### Summary

Currently only the actual owner of the real estate company can send a lease through the company tab. This makes it difficult to employ realtors who can actually RP their job. They can show listings, but then its up to whenever the owner of the company is around to send the lease. I am suggesting adding a /sendlease command for realtors to use without giving them access to the company funds. Only people listed as realtors under the specific Realty company will be able to send leases on the vacant properties owned by said company. They would do /sendlease (CID) (Address) similar to how citizens accept leases. This would allow for a smoother RP experience for both sides instead of potentially waiting hours for the owner to be around to send a lease.

### Reason

smoother RP, allows for more interactions within Real Estate

**Comment by coalaura** [comment]
Duplicate #2357
