### ISSUE TITLE
Obey 10F Bugged / suggestion

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3009]
### Assurance

I have read the `README.md`

### Summary

I have recently purchased the 10F, 

The widebody version from (bennys) is not buyable at pdm, and midnight can’t add it, could we please add the option for midnight to add, 

also the speed is terrible compared to other cars of same value and class, EMS 4, with turbo, max speed is 141 down hill, awful Imo for an r8 

### Reason

Posted above

**Comment by coalaura** [comment]
The 10f widebody is its own seperate car, there is no widebody kit for the normal 10f. I've added the 10f widebody to PDM now
