### ISSUE TITLE
Tequilala Locker for Employees

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/op-framework-issue-tracker#3010]
### Assurance

I have read the `README.md`

### Summary

I am the owner of Tequilala and it would be super appreciated if we could get a locker down in the staff room so I could give my employees supplies and menus that they could keep on site for their shifts rather than having to keep everything on them whenever they are going to work.

### Reason

Most work places have locker rooms or areas in the staff room to put down your stuff, and most places that I have worked have had places where you put your stuff that you work with, you don’t take it home with you.

It would also be a QoL thing because I frequently show up ready to open then realize I don’t have a boombox or enough tazer ammo or handcuffs or something that I need for the shift.

I was thinking around here somewhere.
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/138440128/f9fffe2c-4ac6-4158-b5af-2d34563ecbfc)

**Comment by coalaura** [comment]
That basement is not really a staff area though... It wouldn't really make sense to put lockers there

**Comment by Alyshiva** [comment]
It is the staff room, maybe that's not what it was built to be, but as long as I have worked there it has been staff only.

**Comment by coalaura** [comment]
done
