### ISSUE TITLE
Suggestion - Able to skin damaged carcasses to get rid of the corpse

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3011]
### Assurance

I have read the `README.md`

### Summary

Pretty simple suggestion, allows for people to hide the bodies from poaching if they mess up and hurt one, and also can help keep animals from spawning due to corpses being too close. Just have it delete the corpse and give us nothing, but at least we have the option. 

Instead of this message displaying, have it be a pop up in a blue box at the top right saying "You failed to skin this carcass as it was too badly damaged." 

### Reason

I'm tired of my deer stubbing their tow on a rock as I'm shooting them and this happeing LMAO

**Comment by coalaura** [comment]
sure thing
