### ISSUE TITLE
Adding Garage at Vespucci Boulevard House

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3012]
### Assurance

I have read the `README.md`

### Summary

Block Name: Vespucci Boulevard
Block ID : 48 (As per legacy India server)
Total Slots/house: 15

I recently bought above block and got to know that many of the houses of this block dont have garage. Not having garage in few house make that particular houses worthless for people and no one ever want to buy house without garage. I also reduced rent for that house but still people dont want to buy house without garage

I would like to see dev's adding garage at below house. (There is space in front side of house where we can add garage)

House that dont have garage:
Vespucci Boulevard 12
Vespucci Boulevard 13 / Apt1
Vespucci Boulevard 13 / Apt2
Vespucci Boulevard 14

Image : https://i.imgur.com/y85S1un.png

### Reason

People get house in exchange of rent they are paying and not having garage make the house useless. And also not having garage in few house make that particular houses worthless for people and no one ever want to buy house without garage. All of my customers/Tenant think that there should be garage for every house.
It would be great for all the rp players and real estate owners if you add garage.
Looking for your positive response as soon as possible.

**Comment by coalaura** [comment]
Combined all 3 into one garage

![done](https://i.shrt.day/DUHIfexe82.png)
