### ISSUE TITLE
Adding back Door at mansion

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3013]
### Assurance

I have read the `README.md`

### Summary

Block: Normandy Drive
House Number: Normandy Drive 9
Block Id: 60
Mansion type: franklin mansion

This mansion dont have second door at back side to go outside. If you can add then it would be great.

back Area 
https://imgur.com/XUmx6B9

Mansion Front Side
https://imgur.com/VJoxIaq

### Reason

All other mansion have then why not this.

**Comment by coalaura** [comment]
done

**Comment by devamop69** [comment]
Thanks
