### ISSUE TITLE
Update house Rent / Transfer Ownership of house (Real Estate)

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3016]
### Assurance

I have read the `README.md`

### Summary

what if we are able to change the owner of the house without comepleting removing it. Currently if we have to change rent amount or change the owner of the house , owner have to completelly empty their house and then buy house from company again. In this process , if they did bought any furniture , it will be get reseted.

What if we can have edit buttom in company owner tablet and send a new offer for same house with new owner or updated rent. i will be great if few friends are staying togther and one friend is leaving forever. They can just change the owner and continue living in same house

### Reason

Many people want to change owners of their house. Because at time of buying , 2-3 friends come toghther and then they want to leave. been able to change owner willl be great addition.

Also changing the rent amount while still they are staying in same house would be great. Depand for house change is city time to time and so do rent. We cant remove someone telling rent is increased and you have to reprocessed the whole buying a house thing. Just sending them new offer to /accept with updated price will be great

**Comment by coalaura** [comment]
I see this potentially getting abused to kick people out of houses. Although my idea would be that the realtor does /transfer and then the old owner and the new owner both have to confirm

**Comment by ayushpatel1007** [comment]
Yes, That would be great.  I am facing issue that my friend is owner of house but he is not coming in city regular. If I have to give or add/remove access of people , I can’t because my friend is owner and he is not coming. Maybe we can just change owner and continue living in same house with all the furniture we did. He can some come for like 2 minutes and accept the owner change offer and leave

**Comment by xplrerin** [comment]
> I see this potentially getting abused to kick people out of houses. My idea to prevent that would be that the realtor does /transfer and then the old owner and the new owner both have to confirm

This would be such a help but I still think the offers are way too complex for people to accept. Is there any plans to change the way people accept offers?

**Comment by ayushpatel1007** [comment]
Maybe We can use Ui/Ux of bills. company Owner send offer and they can see that what offer is like house address , Weekly rent etc and they can just Click Accept or Cancel (Same we have for bill, they see reason of bill, amount and Pay/Cancel Option)

**Comment by xplrerin** [comment]
> Maybe We can use Ui/Ux of bills. company Owner send offer and they can see that what offer is like house address , Weekly rent etc and they can just Click Accept or Cancel (Same we have for bill, they see reason of bill, amount and Pay/Cancel Option)

100% I did put a GitHub in similar to this in the past before the bill system. It would be perfect for real estate

**Comment by coalaura** [comment]
Done

![yes](https://i.shrt.day/DUJekIbu58.png)

**Comment by ayushpatel1007** [comment]
@coalaura Please add option for rent amount change also (if not).
