### ISSUE TITLE
Suggestion - Log out location DOC

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3017]
### Assurance

I have read the `README.md`

### Summary

Was wondering if its possible to add log out location to a break room in DOC

### Reason

the reason is when we switch a character and as DOC you would wake up in middle of yard it can be quite dangerous as if there's any prisiners that can attack you imidietly, having a diferent location within the prison , as mentioned maybe in break room where the evidence locker is would make it safer for DOC officers to come and leave the city

**Comment by coalaura** [comment]
Fine, i'll add one and add one for DOJ too while im at it

**Comment by gadjinee** [comment]
Thank you so much
