### ISSUE TITLE
Suggestion - Update Bill Payer's name

### ISSUE THREAD

**Issue by BaronVonSnergerberger** [InZidiuZ/op-framework-issue-tracker#3018]
### Assurance

I have read the `README.md`

### Summary

Had suggested a while ago to make it so the bill system would show in the chat who was paying it so we could keep track and see if we were actually being paid, or if it didn't go through etc. It's been awesome since that change, however the issue where we see the payer as ourselves (the bill issuer) has remained. Had originally commented on the original suggestion but since it was closed I don't think it was seen. Figured I'd put in an official suggestion request to update the name of the payer to the actual person receiving the bill, rather than the bill issuer. 

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/144145704/d7f1602c-e3a1-4b8e-adae-315f91d13de2)

### Reason

It would be a fix/correction to make things clearer and work as it was intended.

**Comment by coalaura** [comment]
whoops, you'Re correct it should be the person who paid it. All fixed
