### ISSUE TITLE
Suggestion - add boat spawner for boat licenses to cayo

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3019]
### Assurance

I have read the `README.md`

### Summary

ay bruh im stuck out here w/ no boat pls give boat 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/39427774/3ea89ef8-2153-44f9-a30f-8aca977f3a7c)

### Reason

because i wanna like use a boat to get home sometimes

**Comment by coalaura** [comment]
done

![yes](https://i.shrt.day/DazEBAlE83.png)
