### ISSUE TITLE
Crashing - GTA5+147E569

### ISSUE THREAD

**Issue by Handmaiid** [InZidiuZ/op-framework-issue-tracker#302]
**Reporter:**
**Who is reporting this?**
Kate Denson | _Steam - https://steamcommunity.com/id/Busty-Bitch/_ | Discord: Handmaid#0666

**Summary:**
**Write a short summary of what you're experiencing.**
Constant crashing after 5 minutes of being in the server. 

**Steps to Reproduce:**
**Include what steps that are needed in order to reproduce the issue.**
This happens when riding around, changing clothing, going anywhere near Vinewood which has caused me to believe that this issue isn't caused by anything in particular. 

**Expected Results:**
**What are the expected results?**
To not crash.

**Actual Results:**
**What are the actual results?**
Continuous crashing. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
> ![image](https://user-images.githubusercontent.com/53245564/62027855-c6d74a00-b1ac-11e9-94ae-b535aca43c18.png)

> ![image](https://user-images.githubusercontent.com/53245564/62027997-29c8e100-b1ad-11e9-908e-099f5d56303b.png)

> ![image](https://user-images.githubusercontent.com/53245564/62027975-1c135b80-b1ad-11e9-95cb-60f71bb6fd0c.png)

**Game Resolution:**
**What is your game's resolution?**
1920x1080

**Player Data:**
**Write /info whilst ingame and provide the information you're given.**
Character ID: 1024- Job Data: Government, Waste Collector, Employee
Timestamp: 2019-07:59:05

**Notes:**
**For anything else noteworthy.**
Here is the CitizenFX.log: http://pasted.co/97321e8d
I can also send you the DMP file over discord if needed.

**Comment by InZidiuZ** [comment]
Hey,

Try clearing your cache, verifying GTA files, and possible reinstalling FiveM. This issue is most likely not related to the server though, as no one else have reported to be experiencing the same, so if the issue persists, please reach out to the FiveM support for further assistance.

**InZidiuZ**
*OP-FW Developer*
