### ISSUE TITLE
/Transfer Command not showing #3016 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3020]
### Assurance

I have read the `README.md`

### Summary

/Transfer is not showing in commads.

Image:
https://imgur.com/oO7pT2E

refrence issue:
#3016 

I am Owner of company.

### Reason

Dont know. Server Also restarted just like hour before till cant see this command.

**Comment by coalaura** [comment]
Cause there has not been an update yet
