### ISSUE TITLE
Suggestion - Vespucci Boulevard 5 Garage

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3021]
### Assurance

I have read the `README.md`

### Summary

Vespucci Boulevard 5 and 6 are conjoined mansions however number 5 doesn't have a garage. Please could we get the 6 garage to be shared with number 5? 

### Reason

Garages help with QOL and people are not wanting this house due to the garage issue. I know you've had a few requests for garages along this block but I didn't see a request for number 5.

**Comment by coalaura** [comment]
I didn't add one there cause there is no nice spot for it. Also the public burgershot garage is not even a hundred meters away so i don't think its a big issue

**Comment by ayushpatel1007** [comment]
I don’t agree with coalaura, People are paying rent so why don’t they have garage. Everyone Else have also. Those people who are living in that house can understand that what problems they face without garage. Many other houses have public garage near by that doesn’t mean you don’t provide personal garage for that house. And as per my knowledge all the house in city have garage now then why not this. In everyday use, using burgershot garage is so so inconvenient. We have to literally Run to public garage and take vehicle and come back home running after storing it. Why would someone will buy even that house. 

I respected everyone point of view and perspective but you can’t just tell that there is public garage nearby so run to that garage and use it.


You can just make use house 6 garage for house 5 also. You can make common garage for both of house. Same you did in house 1 and 2.

I am just telling what problems people are facing. You are developer , it’s your call at last. But please remember we are here to give suggestion for things that are problems for people doing rp. 


I am great full that you added garage in house 1 and 2. It’s better than not having garage. But still that garages are also so inconvenient. If you can move them at side of house on road then it would be great.

**Comment by CloudCait** [comment]
It tanks the property value; it makes no sense for me to charge the same amount for the same mansion that’s attached to it as it doesn’t have a garage. It’s also pretty inconvenient, for example, when transferring storage into the house from your car when you leave the car outside and come back in 9 times out of 10 your car has poofed. Or if you desperately need to fly out but can’t just store your car run into your house and fly out within a matter of seconds. I don’t personally understand why this house should be the only one forced to use burger shots garage.
