### ISSUE TITLE
Suggestion - Add a new mask of TLMC

### ISSUE THREAD

**Issue by ShajadulGH** [InZidiuZ/op-framework-issue-tracker#3023]
### Assurance

I have read the `README.md`

### Summary

We run TLMC at Legacy Roleplay Bangladesh. We designed a Mask for TLMC and we are requesting you guys to add this mask so that we can use this for our TLMC Club. Thank You
Mask ZIP : https://gofile.io/d/Aw7EuA
![Screenshot_874](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/44522491/fd763378-bf9e-4efa-80ca-444315a65720)

### Reason

That would be a good change because all TLMC Club will have a new mask to use and show off. Thank You

**Comment by coalaura** [comment]
this would be for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by ShajadulGH** [comment]
> this would be for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

Didn't understand what are you saying, can you please clear me out what to do ?

**Comment by TacticalTyl3r** [comment]
> > this would be for the asset github https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
> 
> Didn't understand what are you saying, can you please clear me out what to do ?

This GitHub is for the framework (Scrips) where the Asset GitHub that Laura posted is for assets (Clothing, Cars, Maps, etc)
