### ISSUE TITLE
Suggestion - Flashlights see thrown guns

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#3024]
### Assurance

I have read the `README.md`

### Summary

With the addition of the ability to throw your weapons has created an unrealistic burnden for finding said weapons once thrown as they almost always lay in a way that is impossible to find once done. And sometimes these distances that need to be searched are over several city blocks. With that I think that we should be able to spot them easier with our PD flashlights, as it would help balance out that abilty. 

### Reason

Given the fact that we already can with clothing, and casings, I don't see tossed guns as any different, and when normal items are dropped on the ground a white indicator arrow sit's on top of it, weapons included. When tossed though nothing, and makes finding them narrowly impossible. At least with a flashlight indicator it would still require a bit of searching but not make it an impossible task which it is now. I firmly belive this will bring balance to the ability.

**Comment by joevapes3** [comment]
onlychans69 aka harty shlong had this great idea, he's a crim main, so must be valid, just saying.

**Comment by coalaura** [comment]
> he's a crim main, so must be valid

lmaoooooo, i usually go by "is this good for the whole community" not "is this beneficial for crims". (all done btw)

figured blue would be easier to spot than white potentially
![ye](https://i.shrt.day/Vazagoro93.png)
