### ISSUE TITLE
Suggestion - EDM Vehicles sold in PDM

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#3025]
### Assurance

I have read the `README.md`

### Summary

Remove EDM and add the vehicles to PDM. Perhaps add a separate section within the PDM menu or give the menu a refresh similarly to the clothing menu to accomodate this. Provide PDM workers the ability to facilitate the sales of these vehicles to incentivise more activity in PDM and improve pay for said workers as PDM is currently drastically unpopular compared to EDM and EDM itself does not promote any roleplay or interaction. The vehicles would still of course require paid priority to be purchased but merely just allow PDM to sell these vehicles so that there is roleplay to be had and help PDM workers make more money considering the already low money being made from the job.

Can potentially adjust the commission from EDM vehicles separately to make sure the amount of money made from it is balanced compared to the average income of other jobs of similar level.

### Reason

This would be positive for multiple reasons.

- EDM already involves waiting. Be it through making the money to buy the vehicle or due to people nowadays mostly buying vehicles from other players instead of EDM. The likelihood of waiting is pretty low with this change as the income would be good enough to incentivise PDM to be exceptionally active.

- Roleplay. Instead of going to EDM and holding E to buy a vehicle, you can go to PDM and speak to a salesman to buy the vehicle. This would also allow players to take test drives of cars from EDM.

- Increases activity of employees in one of the most important business in the server. PDM vehicles just don't sell like EDM vehicles do, not even close. PDM employees have very little incentive to be at PDM due to very little interaction occurring AND the inconsistent pay. Allowing sales of EDM vehicles through PDM would surely fix that.

**Comment by coalaura** [comment]
There would be no additional roleplay in moving the EDM display to PDM. The same cars would be on display. It would have the same rotation, same prices and work the exact same way. That being said, **generally** i dislike this idea. EDM is responsible for a good part of the income __that keeps the servers running__.
