### ISSUE TITLE
Suggestion - Midnight getting a contact like Police, Mechs/Tows etc..

### ISSUE THREAD

**Issue by KarterJHunt** [InZidiuZ/op-framework-issue-tracker#3026]
### Assurance

I have read the `README.md`

### Summary

With the recent City Changes coming to Midnight for car mods lights etc. It seems IMO that there isn't enough employee's at Midnight or there is but no one is reading/checking twitter for anyone waiting for them.

If Midnight could get a contact I think it'd help alot!

### Reason

It would bring down wait time for someone to arrive and help out.

**Comment by CloudCait** [comment]
Idk where the whole idea that there's not enough midnight staff comes from, the roster is full and I only ever see tweets not being responded to during non-busy hours of the server like when NA are sleeping and EU are at work/school. Unfortunately not every business in the server can be open 24/7. 

Also I suggested this a bit ago in the comments of another midnight related request so this might be a duplicate https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2987#issuecomment-1766092210
