### ISSUE TITLE
Suggestion - PDM Full Upgrade Test Drives

### ISSUE THREAD

**Issue by Robin-CZ** [InZidiuZ/op-framework-issue-tracker#3027]
### Assurance

I have read the `README.md`

### Summary

The ability to send people out on PDM test-drives in fully upgraded versions of vehicles. Maybe implement a 5 minute timer on the test drive so that they aren't abused.

### Reason

As it stands, people can only test drive vehicles when they are stock, which doesn't really give a full picture of how it will actually handle as there are many vehicles that don't handle as well until they are fully upgraded. Allowing people to test drive a vehicle fully upgraded for a very short duration can at least give them a rough idea of how the car will feel when or if they buy it and could potentially drive up sales for PDM as PDM workers can convince potential buyers to test drive a car on full upgrades and make a more educated decision on their purchase.

**Comment by coalaura** [comment]
duplicate #2546
