### ISSUE TITLE
Changing Location of Garage of Vespucci Boulevard 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3029]
### Assurance

I have read the `README.md`

### Summary

Recently you added common garage for house 1 and 2. But still they are not convenient.

Below are pics of place where we can add garage. 

House 1:
(https://i.imgur.com/29rSYdf.png)

House 2: 
(https://i.imgur.com/MJmFsT0.png)

### Reason

It’s same for us to run to house garage and burgershot garage. Doesn’t make sense of having garage at that far that is almost same as burgershot garage.

if we can move garage towards house side then it would be more funstional.

**Comment by coalaura** [comment]
I only add garages to spots that fit, those areas are super random, it makes no sense for a garage to be there
