### ISSUE TITLE
Tuner and bank chips should enter the game through RP

### ISSUE THREAD

**Issue by Serpentamer** [InZidiuZ/op-framework-issue-tracker#303]
**Name:**
Who is suggesting this? Please include discord name.
I play a character named Jimmie Dean, my Discord is: James Dean#3814
**Summary:**
Write a short summary of what your suggestion is about.
Tuner and bank chips should enter the game through RP instead of everyone just walking around looking for backpacks. They would come from different people involved in different underworlds, or from one person, maybe a black hat hacker that codes the chips himself? For example maybe the person who has access to the Tuner chips only gives them to people who can beat them in a race, or something similar to that. This would have to be a whitelisted position as of course it could be abused but in the right hands I think that it would be good for everyone. The bank chip would maybe be a gang leader that only sells to people that do bank jobs with him and succeed.  Just some ideas!
**Reason:**
Why would your suggestion be a good addition to Legacy?
Makes more sense for them to enter the city in this manner, rather than just saying they are hidden in backpacks around the city. Would build RP as well as the economy, because they will be more available they will become a supply/demand chain that will create a market of resellers and such.

**Comment by InZidiuZ** [comment]
Hey,

Not really what you're suggesting, but chips/tuner chips can now be obtained through various in-game jobs, so closing this.

**InZidiuZ**
*OP-FW Developer*
