### ISSUE TITLE
Suggestion - Anonymous Billing

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3030]
### Assurance

I have read the `README.md`

### Summary

Add an option / command for anonymous billing.
Like, when your name comes up for the person who billed you... Instead of
"Tyler Watson payed your bill with a $50 tip"
"Anonymous payed your bill with a $50 tip"

### Reason

For the people in gangs who are anonymous.
For example, one of AOD members doesn't share their position in AOD publicly. If he was to go to a shipment, and he had the club funds at the time, his name would be revealed.
It allows for more anonymity and better roleplay for gangs who have inside members / hidden informants.

**Comment by King2704** [comment]
how about you bring cash to illegal deals?

**Comment by ayushpatel1007** [comment]
I don't think this will help in rp in any form of way. 


A person can just directly 
/give_cash if they want to be anonymous and not using /bill

Adding one more way to pay/recive payments will create confusions.

New people who recently joined rp and particularly legacy server didn't even know that they can pay using /give_cash.

Adding more ways will just create confusions and questions
