### ISSUE TITLE
Suggestion - Darkmode for X (formerly known as Twitter)

### ISSUE THREAD

**Issue by RadicalBrosif** [InZidiuZ/op-framework-issue-tracker#3031]
### Assurance

I have read the `README.md`

### Summary

I just think it would be handy to add a "Dark Mode" feature to X (formally known as Twitter) so people who enjoy dark mode can stop getting flashbanged every time they open their phone. 

### Reason

For those of us who tend to be on when the sun is down, having our eyes blasted by a light mode X (formerly known as twitter) is extremely uncomfortable. I don't think it would affect anything in terms of RP but would make time in the city _that_ much more enjoyable.

**Comment by scufflord** [comment]
I'm on #TeamNightModeEverything and think a night mode for everything on the phone would be amazing, but I know how bad gcphone is so I'd understand if it isn't possible.

**Comment by coalaura** [comment]
lmao ur asking for a lot with that old ass phone

**Comment by HollaYalla** [comment]
Why not make a custom phone for Legacy that had the same style of gcphone but is more customizable for the servers needs

**Comment by coalaura** [comment]
> Why not make a custom phone for Legacy that had the same style of gcphone but is more customizable for the servers needs

Of course, let me just quickly code an entire phone, no biggie :)))))))))

**Comment by HollaYalla** [comment]
> > Why not make a custom phone for Legacy that had the same style of gcphone but is more customizable for the servers needs
> 
> Of course, let me just quickly code an entire phone, no biggie :)))))))))

Should take like 5 minutes max lol nah but in the future ya know

**Comment by coalaura** [comment]
> in the future

This one is waiting already xD #2447

**Comment by coalaura** [comment]
It was a massive pain to implement, but there is a dark-mode for the entire phone now, togglable in your settings.

![dark](https://i.shrt.day/ROhiqAJU27.png)
