### ISSUE TITLE
Suggestion - Acceptance of passed items

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3032]
### Assurance

I have read the `README.md`

### Summary

Create a pop up for accept or decline for transferred items.

### Reason

Right now anything and everything can be shoved in pockets without the person acknowledgement which could hinder RP and if nobodys paying attention could also be powergaming in situations

**Comment by coalaura** [comment]
I kinda like that exact point tho. You can secretly put something into someones pockets without them knowing

**Comment by Dibbey** [comment]
I feel like it could also be very dangerous, not just powergaming. Like, if I make an enemy on a legal character, someone could very easily just slip me something illegal and call police, completely ending any legal RP for me I've had going on. Without me even knowing. While yes, that makes sense and it sounds cool from one POV, also kinda seems strong from another and for me could just result in constantly checking my pockets when people walk by me.

Suggestion:
- Giving items in a trade I feel should have some sort of Agreement, making it an obvious transfer
- "Secretly giving" could maybe be a "big risk" of trying to slip something unnoticed, and it could be random if it does go unnoticed or if the other person has some sort of notification that your pockets feel heavier or something. But shouldn't be too easy to do. While it does not say who did it, it could still alert the person of something having happened IF you pay enough attention to the notification (kinda like the blue thingies in the top right where it tells you your injuries or something). 

That way it's a risk for the person trying to give something secretly and they won't go just casually giving out stuff into other people's pockets. Would also suggest that this attempt of not pick-pocketing but secret pocket-putting (?) is timed, so like you can make an attempt, then you have to wait at least 5 minutes or so to do it again. So you can't spam pocket-put stuff to others and give away various drugs and guns or whatever super fast.

**Comment by coalaura** [comment]
I mean you already get a big popup saying "Received 123x Something"

**Comment by Kay32** [comment]
Maybe not accepting having to accept them, but maybe drugs and weapons cant be put in peoples pockets? +
Personally Ive already had a shotgun thrown on my back and drugs put in my pockets, which isnt something I would just accept on the street as thats not anything my character would encounter or would set up a deal on. 

I guess its more just frustrating that something I worked 2 years on could be taken away because someone could just walk by and throw something in my hand while im like on another tab doing document work and be screwed, Id just have to RP with it. 

Just something that could spark a discussion.

**Comment by coalaura** [comment]
I definitely get your point, the issue i am having is that:
- Implementing a whole trading UI would be a much bigger project than this simple version
- Restricting what items can be given feels weird and restrictive (it doesn't make sense that i wouldn't be able to give someone a tiny bag of cocaine but im able to give them a big idk shovel for example)

**Comment by coalaura** [comment]
One possible solution i could add is adding a chat message whenever you receive an item. That way you wouldn't miss the notification

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/kAbuSuza72.png)

**Comment by sleighwhite** [comment]
Could you connect accepting/giving items to a shared emote? I know when I do a shared "hug" emote for example, it asks me to accept with "y" or something like that. Just a thought as this is also a concern for me. 

I know it's not great rp, but if I go afk in mixed company for any amount of time, someone could put coke on me and I'd have no idea. Much like Dibbey mentioned earlier.

**Comment by coalaura** [comment]
> Could you connect accepting/giving items to a shared emote? I know when I do a shared "hug" emote for example, it asks me to accept with "y" or something like that. Just a thought as this is also a concern for me. 
> 
> 
> 
> I know it's not great rp, but if I go afk in mixed company for any amount of time, someone could put coke on me and I'd have no idea. Much like Dibbey mentioned earlier.

You would know now tho, cause of the chat message. Also no, i cannot connect it to a shared emote

**Comment by Kay32** [comment]
> ![yes](https://camo.githubusercontent.com/960247e1948c192ccbdbd139a50f65683bd35e8d9e204407092db79a08a5fe60/68747470733a2f2f692e736872742e6461792f6b41627553757a6137322e706e67)

This is so much better thank you!
