### ISSUE TITLE
Suggestion - Avoid inventory getting overweight by passed items

### ISSUE THREAD

**Issue by rooks00** [InZidiuZ/op-framework-issue-tracker#3033]
### Assurance

I have read the `README.md`

### Summary

When items are passed, inventory limits of the receiving person is ignored.

### Reason

Transferring items to the next person ignores the inventory weight limit. This allows forceful transfer of items in order to make the other person fall down.
Or, this can be abused to sell 80 leather in one trip (if you go with a friend)

**Comment by coalaura** [comment]
will fix that
