### ISSUE TITLE
Bug report -  Have hunting license but cant buy rifle

### ISSUE THREAD

**Issue by VansJOD** [InZidiuZ/op-framework-issue-tracker#3034]
### Assurance

I have read the `README.md`

### Reporter

vansjod

### Summary

i have the hunting licese but when i se at hunting store i cant buy rifle and i got my hunting rife 2 weeks ago 

### Steps to Reproduce

NA

### Expected Behavior

NA

### Actual Results

NA

### Screenshots/Videos

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/151403527/022c6408-fa39-4e31-ba9d-aaba4f4cc366

### Game Resolution

Very High All

### Player Data

![Screenshot 2023-11-19 021707](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/151403527/db83c228-9c07-45be-9d25-442345a3248c)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
You dont have the hunting license

![yes](https://i.shrt.day/noZaQoBi84.png)

**Comment by VansJOD** [comment]
> You dont have the hunting license
> 
> ![yes](https://camo.githubusercontent.com/1eb23823dd7b8eea6f933e7752a1dc86071647e3ea07f8088ebadd11679f87d6/68747470733a2f2f692e736872742e6461792f6e6f5a61516f426938342e706e67)

bro i have i got it 2 weeks ago

**Comment by VansJOD** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/151403527/a956bc3e-b73b-4971-95c5-75c7eaf2f445)

**Comment by coalaura** [comment]
> > You dont have the hunting license
> > ![yes](https://camo.githubusercontent.com/1eb23823dd7b8eea6f933e7752a1dc86071647e3ea07f8088ebadd11679f87d6/68747470733a2f2f692e736872742e6461792f6e6f5a61516f426938342e706e67)
> 
> bro i have i got it 2 weeks ago

My friend, i checked the admin panel of your character on the india subdivision. Your character does not yet have the hunting license, there is not much more i can really say to you here. Open a ticket in their discord and ask
