### ISSUE TITLE
Diving spot on the left side of the map! 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3035]
### Assurance

I have read the `README.md`

### Summary

There should be a diving spot added on the left side of the map by T or S 

### Reason

There’s not much to do on that side of the map and I am trying to get rp going around all of the city!

**Comment by coalaura** [comment]
Where

**Comment by MetaHatter** [comment]
Personally, I would do around here: -2821.83, -547.898132, -73.8649139 

(Even consider actually moving the current diving location completely to here.)

Reasons: 
- Vanilla location so nothing needs to be streamed
- Closer to population centers to allow for more potential interactions
- Closer to PD for investigating possible vehicle theft attempts
- Make Chumash a more desirable place to live/spend time
- Closer to a garage for storage of materials found
- Still far from the sell locations so the transportation lift isn't significantly reduced

![2023-11-19 13_42_07](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/84351858/51e7736c-7732-403d-90b0-c458af99fe01)
![2023-11-19 13_43_29](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/84351858/590b7424-a2ac-45d0-9455-a0174dc939e4)

**Comment by coalaura** [comment]
done
