### ISSUE TITLE
Strokemasters Garage

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3036]
### Assurance

I have read the `README.md`

### Summary

It is a garage near the beach, not for repairs or anything, simply tuning cars, engine swaps, and car kits

### Reason

It would kinda be like midnight, but something different, this could do rare kits for cars, install Nos for customers, and tune cars, I feel like we need more in the city for cars, and customizations.

**Comment by coalaura** [comment]
Thats what the midnight tunershop is for
