### ISSUE TITLE
Bug report - hud alignment always partially off-screen 

### ISSUE THREAD

**Issue by rohansaikia517** [InZidiuZ/op-framework-issue-tracker#3037]
### Assurance

I have read the `README.md`

### Reporter

@.jantu

### Summary

Pressing escape and returning back to game shows the "HUD Alignment" message. I tried changing the "Safezone Size" as instructed but that doesn't seem to change anything.

### Steps to Reproduce

1. Switch the resolution to 1366x768 (Full screen exclusive) [Not really sure if this is the issue]
2. Try changing the safezone size.

### Expected Behavior

Safezone Size changes successfully and the HUD alignment message goes away.

### Actual Results

No changes in SafeZone Size.

### Screenshots/Videos

https://i.imgur.com/SRRvvm4.jpeg (hud alignment msg)
https://i.imgur.com/cgQsSPd.png (safezone size set to high value)
https://i.imgur.com/UID5RB5.png (safezone size set to low value)

### Game Resolution

1366x768 (Full Screen Exclusive)

### Player Data

https://i.imgur.com/5XASOqE.png (/info)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
If you look in your 2 screenshots showing you setting the safezone size, you can see in the background the safezone is not changing, its the same.

**Comment by coalaura** [comment]
ok i reduced it serverside a bit more, should be fixed next update
