### ISSUE TITLE
Suggestion - Deployable PA system/Megaphone

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3038]
### Assurance

I have read the `README.md`

### Summary

An item that is only purchasable by state, ems, or PD characters (that way nobody can get it just to troll) but it could allow things like large gatherings for a funeral, government election or even for PD to easier communicate things during hold-outs etc. When the player uses the item they could hold up a megaphone or set up a mic and amplifier that will project their voice in 2-3x the radius of normal yelling, without a volume boost. 

### Reason

It will just make it easier to address large crowds.

**Comment by coalaura** [comment]
done

![yes](https://i.shrt.day/ziQaBuro88.png)

![no](https://i.shrt.day/FEbexiVE77.png)
![with](https://i.shrt.day/taXOnujo10.png)

**Comment by CloudCait** [comment]
Could we make this accessible for business owners? Or maybe something the governor can purchase and give to people hosting events? This would be really handy 🙏🏻 Great addition ♥️
