### ISSUE TITLE
[job/trucking] Transporter cargo health

### ISSUE THREAD

**Issue by Warpwnge** [InZidiuZ/op-framework-issue-tracker#304]
**Name:**
Warpwnge

**Summary:**
If possible, adding "cargo health" to the transporter deliveries would be neat.
1. The more things you hit (Or get hit with) would damage the cargo little by little, or alot if it's a heavy hit.
2. The more it's damaged, the less you get paid at the end.
3. This may change the way prices are displayed when looking for a job to accept. Maybe "up to $300".
4. When having taken too much damage, the trailer can either still be "alive" and sellable for .. like $1, it could de-spawn, or just become dead weight.
5. For health display, it could be like the progress bar, but backwards and a little out of the way on the HUD, like the bars in the bottom left. Could be positioned on the bottom right, or bottom middle?
6. Maaayyybbbbeeee speeding can affect the health??? 80-85 MPH could be the threshold (for highway speed) before the bar could tick down a bit, say from the shaking of the trailer or hitting speed bumps or holes.

**Reason:**
I think this would be a good addition for:
1. Realism. Sure, they can already take damage and be destroyed (Had that personal experience before I could transport it), but let's say you're taking glass bottles somewhere. When you get there after hitting a car or two, some bottles would be broken, and so you get paid a little less.
2. Roleplay. Some players can (And have to me before) slammed repeatedly into the trailer. As the driver, you have a perfectly viable reason to yell at them and call the cops for vandalism or something. Having a value to the cargo can add more emphasis on trying to make RP instead of shrugging off the bumping.

- That's about all I have for the moment. Thanks for reading it over.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
