### ISSUE TITLE
Suggestion - Deceased Home Owners

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3043]
### Assurance

I have read the `README.md`

### Summary

Houses automatically drop when someone deletes (permas) their character

### Reason

Not sure if this is possible to be implemented. But when someone decides to perma their character they can't obviously be around to 'transfer' ownership of their houses to people in their wills. Realtors have to wait for the houses to drop off which takes around 1-2 weeks (can't remember the exact time). I currently have someone who owns like 12 ish homes with me as they were the owner of their gangs block and they recently permad but now I'll have to wait for the houses to drop to sell them to his gang members/friends who want these homes. If the house automatically drops when the character is deleted this will make it easier for lawyers to access belongings in their wills as well as being able to instantly give the people in their wills these homes or just instantly sell them. 

Again not sure if this is possible but just thought I'd suggest it.

**Comment by coalaura** [comment]
If a character is deleted you now have an extra button called "evict" when you enable manage properties. Once pressed the deceased owner will basically be kicked out and the house will be available for sale again

![yes](https://i.shrt.day/nAHEmOZA88.png)
![yes](https://i.shrt.day/xULOsiCe04.png)
