### ISSUE TITLE
Suggestion - Allow ounces of weed to be broken down into quarters

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3045]
### Assurance

I have read the `README.md`

### Summary

Had this idea earlier when I didn't have enough rolling papers left and Green Wonderland was closed. It would be kinda cool if you could take the 1 oz item in your pocket and drag it to the center to turn it back into 4 1q items. that way if you have 3 papers left and 1oz you can still roll 3 joints if you need them

### Reason

cause if i got a baggy of weed in my pocket and wanna roll 1 joint and save the rest for later, that's what i do

**Comment by coalaura** [comment]
bruh

**Comment by coalaura** [comment]
ayo but dont be mad if you dont always get exactly 4q back, sometimes a little may slip through your fingers while you break it back apart

![ye](https://i.shrt.day/VuPAnexi94.png)

**Comment by coalaura** [comment]
this has in fact happened to me before 😢
