### ISSUE TITLE
Bug in entry of mansion.

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3047]
### Assurance

I have read the `README.md`

### Summary

Block: North Sheldon Avenue
House: North Sheldon Avenue 11
House Type:  Franklin Mansion

BLock: Normandy Drive
House: Normandy Drive 8
House Type: Michale 

Front Door:
When we enter from front door of house, we went in below floor house. 
When we exit , we come outside at front

back Door:
When we enter from back door , same we enter on below floor of mansion.
When We exit , we come outside at back side.

What it should be:
When we use front door , we should go on upper floor and not below floor

### Reason

I dont know. Recently MAny problems are seen in blocks. Including garages , doors etc

**Comment by coalaura** [comment]
## North Sheldon Avenue 11
When i enter through the front door everything works fine, when i exit its fine too, same for the back door.

![front](https://i.shrt.day/fiGeqiji49.png)  
![allgood](https://i.shrt.day/vExovoVA70.png)

## Normandy Drive 8
Also works perfectly fine, same for the back door.

![front](https://i.shrt.day/foqAceMu70.png)
![allgood](https://i.shrt.day/VOyodOBe29.png)

**Comment by coalaura** [comment]
> Recently MAny problems are seen in blocks. Including garages , doors etc

If there are many problems, why are people not reporting them by opening bug reports here or posting about it in #reckless-reporting in the opfw discord???

**Comment by ayushpatel1007** [comment]
This problem i reported was notice by me today itself. I don't know if it was same for others or me only.
