### ISSUE TITLE
Suggestion - Remove mechanic icon, job related locks, and all repair spots/benches from Lost Compound

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3048]
### Assurance

I have read the `README.md`

### Summary

With the recent move within the framework away from gang named businesses like the Lost MC shop and the closure of said shop on the International server in favor of Mirror Park Autos it has left the compound completely closed off for most roleplay that the club would like to do. We are forced to take mechanic jobs elsewhere in order to open the gate and doors, and then have to deal with the confusion from newer players showing up expecting repairs because they see that it's a shop due to the map icon. 

We don't want to lose the actual interiors, just have all mechanic job related things stripped off of it and the doors unlocked for good.

### Reason

Allows people to carry on roleplay within the compound without needing to be mechanics to access it, and keeps new players from being confused about shops.

**Comment by coalaura** [comment]
this is a server config type beat
