### ISSUE TITLE
[jobs/police] Private PD garages

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#305]
**Name:**
Pancho#0001

**Summary:**
Give PD the ability to buy purchase vehicles (for cheap cause we are all broke af) and store them at the PD garage (which would repair them when putting away and taken out) just like the old city

**Reason:**
It Would allow cops to properly identify who owns what cruiser when they are found, additionally it would ensure PD vehicles are on par with crim vehicles and give officers a reason to spend money on something meaningful to them.

**Comment by Spitfire2k6** [comment]
#1826 Are these too similar? Can we close this one?

**Comment by InZidiuZ** [comment]
Closing in favor of #2072.
