### ISSUE TITLE
2nd dispo

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3050]
### Assurance

I have read the `README.md`

### Summary

2nd dispo 

MLO: https://youtu.be/jOloVORVRTM?si=F51-p3g9CcYhrKZa

### Reason

A second dispo, is always needed, this location would bring legal roasted potatoes to that area of the map, and if the one store owners not on a second open can be available for customers! 

Personally I am in my city a lot and dispo is a high need

**Comment by CloudTheWolf** [comment]
1 - This is technically an asset request.
2 - This map is Escrow'd so defiantly no.
3 - There are other ways to get these items through RP, so no real need for a second location.

**Comment by coalaura** [comment]
What cloud said plus the fact that GW already struggles, adding a second one would kill both
