### ISSUE TITLE
Bug report - 

### ISSUE THREAD

**Issue by enutpeanut** [InZidiuZ/op-framework-issue-tracker#3051]
### Assurance

I have read the `README.md`

### Reporter

enutpeanut

### Summary

When pulling out a (civ) boat, sometimes it says 'the area is not clear', even when it is. Your money is taken and no boat is spawned.
Only happened with the Toro at Paleto so far, but if I find more I'll update.

### Steps to Reproduce

Go to a dock
Pull out a boat

### Expected Behavior

Boat spawns and money is taken. When parking the boat, money is returned.

### Actual Results

Money is taken, no boat spawned.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1FoV0un7qA5wJm/d1337nRKbAZo?invite=cr-MSxwOUssMjUzNzIxNjcs

### Game Resolution

1920×1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116962577/6bb76673-c24f-4eda-afba-bb97969ae8ed)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Fixed, it will now not take your money if it cant spawn the boat
