### ISSUE TITLE
Suggestion - Add Alerts for police from DOC

### ISSUE THREAD

**Issue by KingLKingston** [InZidiuZ/op-framework-issue-tracker#3054]
### Assurance

I have read the `README.md`

### Summary

How this could work is when police try to send a prisoner to jail if DOC are on it would say something like Are you sure you would like to send this person (ID) to jail since there is DOC on-duty type yes or no something like this because even with the new phone update when I was talking to police they made it clear that they do not check their phone and from me since the phone thing has been added we have been getting a couple more a week but there are still 5-6 a day getting jailed when I am on 

### Reason

This will be good because the phone thing only works if police check their phone everytime this is something that doesn't happen alot and it also makes it where even I don't want to go on duty because there is no point if you looking at walls all the time

**Comment by TacticalTyl3r** [comment]
This was suggested already and DOC was added to the phone to show when they are on duty. #2707

**Comment by coalaura** [comment]
Duplicate #2707
