### ISSUE TITLE
Suggestion - Changing area inside of Green Wonderland

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3055]
### Assurance

I have read the `README.md`

### Summary

Hi I am the owner of Green Wonderland and I would like the suggest a area to change cloths inside of the shop for employees. We do have certain cloths that we were when we work and we would like to be able to change at the shop instead of going to a clothing store.

### Reason

Employees always have to go to a clothing store to change into or out of work cloths and I would like to make it easier for all the employees that work at Green Wonderland.

**Comment by coalaura** [comment]
done
