### ISSUE TITLE
Suggestion - removal of lightning time cycle from z pills

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3056]
### Assurance

I have read the `README.md`

### Summary

I was wondering if it would be possible for the time cycle in z pills to be altered slightly to remove the flashing lightning that happens sometimes. Due to some players having photosensitivity issues that can cause seizures or other health related issues they aren't able to do z pills when that timecycle happens to be applied. 

### Reason

User accessibility and health is POG.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/1V60ZZYB3X.png)
