### ISSUE TITLE
Suggestion - Move vehicle spawn farther up on Steele Way 1

### ISSUE THREAD

**Issue by laurealis** [InZidiuZ/op-framework-issue-tracker#3057]
### Assurance

I have read the `README.md`

### Summary

The vehicle spawn is too close to the garage wall of the house on Steele Way 1, making it so that I have to start the car and move it before I am able to access the trunk of the car. This makes it tedious and difficult accessing items that I store in multiple cars. 

### Reason

It is an issue unique to this house, as all houses and apartments that I have owned in the past do not have this problem. Albeit a small issue, it would really improve quality of gameplay, as I often store things in different cars of mine.

**Comment by coalaura** [comment]
done
