### ISSUE TITLE
Suggestion - Update Business Card Prop

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3058]
### Assurance

I have read the `README.md`

### Summary

Change prop from notepad to ID card

example using the cell phone animation and prop "p_ld_id_card_01"
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/84351858/0c6cd409-444d-418e-9063-465b6c7f406a)

### Reason

Looks better than looking at a notepad when looking at a business card

**Comment by coalaura** [comment]
![yes]}(https://i.shrt.day/8CMRJ9FLAD.png)
