### ISSUE TITLE
Local OOC

### ISSUE THREAD

**Issue by Adorbz** [InZidiuZ/op-framework-issue-tracker#306]
**Name:**
Tag#4848
**Summary:**
I think it would be a good idea to implement local ooc (as in only people in a certain radius around you can see it) Also make it a different color than normal ooc chat so you know if someone is talking in /looc or /ooc
**Reason:**
There are a lot of people using ooc and filling up the chat. It really distracts you from RP. Sure, admins could say "/ooc Clear ooc", but that still adds to the text wall. If you have /looc (stands for Local OOC) the people who need to say "brb" (or something that everyone would need to know ooc in the area) wouldn't make everyone in the server distracted by the ooc text, This also would help EMS or Police see what they need to see "/looc Hey my mic isnt working give me one sec" or "/looc Are you DOA?"

**Comment by SteezyRen** [comment]
/oocoff was implemented for this reason. If you don't like OOC then just turn it off in game. There really isnt a reason for you to want it on unless you are staff and moderating it or for general questions that the server might be able to help you with that wouldn't be considered meta gaming.

**Comment by Adorbz** [comment]
Yes but under certain circumstances when you're EMS or Police you have to see ooc to know certain things during rp, without breaking rp.

**Comment by SATIN187** [comment]
What certain things do you need to know from ooc as EMS or police?

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
