### ISSUE TITLE
Updating Garage in banham Canyon (181)

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3060]
### Assurance

I have read the `README.md`

### Summary

Block : Banham canyon
Block Id: 181

This blocks was reently made aviable for companies to buy. I was having look on it and when i saw garage locations , i thought they can be at better location

Below are images of all the house with current garage location and proposed new location marked with blue marker

House 1 & 2
https://i.imgur.com/HeJCAKO.png

House 3
https://i.imgur.com/AtLhLAT.png

House 4
https://i.imgur.com/i2wNEyx.png

House 5
https://i.imgur.com/TeGAy63.png

House 6 
https://i.imgur.com/gpObJ14.png

### Reason

There are place for garage and it is 100% better than what it is now.

**Comment by coalaura** [comment]
I **intentionally** placed the garages there due to the step driveway making it hard to properly spawn the vehicles on the ground

**Comment by ayushpatel1007** [comment]
If you have change than it would be great. This typee of garage make people not buy property. And this is not case for only this block. there are many garage that are functional but not convenient.

**Comment by coalaura** [comment]
> People are facing issue while getting their vehicles out because local from road crash in their car. Atleast if you can move it little than it would be great.

Here is a very big vehicle (flatbed) withdrawn from every garage on Banham Canyon. None of them are being hit by locals or blocking the road in any ways.

![yes](https://i.shrt.day/LH2JNHMKIR.png)
