### ISSUE TITLE
Suggestion - Let us toggle christmas music

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3061]
### Assurance

I have read the `README.md`

### Summary

Give us an option to toggle christmas music on the trees and stuff. christmas is great but jingle bells on loop for hours is actually traumatising me.

### Reason

ITS CAUSING MENTAL PAIN

**Comment by coalaura** [comment]
Don't worry, i felt the same pain and i've replaced the model globally with one that doesn't play the music

**Comment by txxlrrsCoding** [comment]
thank god
