### ISSUE TITLE
Suggestion - Ability to craft multiple food items for any food joint employee

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#3062]
### Assurance

I have read the `README.md`

### Summary

Having the ability to craft multiple food items using other ingredients while completing bulk orders will be a great asset in the food business.

### Reason

As of now, we can craft only one food item at a time using ingredients. which is okay when it comes to a single order or a few orders within the range of 5–10 orders. but when it comes to bulk orders, like around 100 or more meals, in which one needs to craft many items, it becomes a lengthy process. If we get this ability to craft multiple items, like looping one process, we'll have enough ingredients for those food items. It'll be good from an RP perspective, so we can complete orders on time and quickly.

**Comment by coalaura** [comment]
You can craft multiple at a time for the longer processes. If you have another one that you would like to have this added to could you list which one in specific?

**Comment by Vikky98** [comment]
> You can craft multiple at a time for the longer processes. If you have another one that you would like to have this added to could you list which one in specific ?
I would like to see this for following items
i. Burgers
ii. Avocado  smoothie

( BS is only food joint running in Indian subdivision till now so i suggest only for that . Don't know how other businesses work. )

**Comment by coalaura** [comment]
done

**Comment by Vikky98** [comment]
> done

Thank you very much laura.....
