### ISSUE TITLE
Black Jack and casino

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3066]
### Assurance

I have read the `README.md`

### Summary

fix black jack and add more games 

### Reason

Blackjack even if you get 21 in first try if dealer pulls 21 on 3+ cards you tie, also no bonus pay for blackjack, and no doubles or splits! 

Maybe add roulette or 3 card poker aswell!!!

**Comment by coalaura** [comment]
> fix black jack
Its not broken

> No doubles or splits
Cause blackjack is designed as a money sink.

> Blackjack even if you get 21 in first try if dealer pulls 21 on 3+ cards you tie
We generate 4 decks of cards on the server, shuffle them and pick cards from the top of the stack. You can't really get a more realistic blackjack experience when it comes to rng.

> add more games
There are already more games on the todo list, however we are just 2 script developers working in their free time, so as you can see from the list of issues in this repository it may take a while.
