### ISSUE TITLE
Suggestion - Tweak to /radio_volume

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3067]
### Assurance

I have read the `README.md`

### Summary

Increase the ratio volume input parameter to be 10x the actual value.

Change Examples
============
From /radio_volume 0.1 to /radio_volume 1 
From /radio_volume 0.25 to /radio_volume 2.5 
From /radio_volume 0.5 to /radio_volume 5 (still default)
From /radio_volume 1 to /radio_volume 10

Essentially set the radio volume to 1/10 of the new parameter.

Also potentially add an /rvol or /rv alias

### Reason

Removing the need to type the decimal and adding the alias would make typing the volume change command significantly faster and less prone to typos.  

This would be more beneficial than most shortcuts since the command tends to be required mid-RP more often than not.

**Comment by coalaura** [comment]
/rv is /replace_vehicle but i can ad /volume maybe. Also i like the idea of changing it to bigger values however i feel like 1 to 100 makes more sense intuitively (1 to 100% kinda)
