### ISSUE TITLE
Suggestion - Actual Broken Bones

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3068]
### Assurance

I have read the `README.md`

### Summary

The RP between doctors and civilians is there but isn't as good as it could be just due to the fact of the small amount of doctors that we have in Legacy International and so we should add the ability to break bones or fracture bones or dislocate them.

The way to do this is simple

To break a bone fall off a high building - This can cause your leg or arm to break in one or more places and even have a few fractures as well, If you break your right arm lets say than you can't shoot any gun until it is healed by a hospital through surgery (new command like /heal) or you can buy something like a brace from the Pharmacy also driving would be a pain if you had a broken bone or a brace on it like if you had a broken bone the car would turn slower or even just turn partially.

To Fracture a bone you could get hit by a car - This will cause a bone to be fractured and can be used still but if shooting a gun then after a few shots you may drop it a brace will fix it.

A dislocated bone - You can be punched or hit by a slower moving car and then if it get dislocated you could walk up to a wall or something and do a command like (/relocate) or a prompt will show up saying to slam your shoulder lets say against the wall to pop it back in place this will work most of the time but sometimes it wont and also you will take damage from relocating it, doesn't matter if it was successful or not maybe more damage if it is unsuccessful

Of course it would take a lot of thinking to get it to function correctly but it seems like a neat feature to have.

### Reason

Give more RP mainly to EMS and doctors

**Comment by coalaura** [comment]
How would you get healed if there is no EMS on duty

**Comment by HollaYalla** [comment]
Splints and/or Braces that you get from the pharmacy

**Comment by Dinomasen** [comment]
People would just buy the splints or braces from the pharmacy and avoid EMS RP even if EMS was on duty

**Comment by ImArteria** [comment]
I feel like people get hit by a car or things to "break bones" a lot and this would require an extremely active EMS and overall put more stress on a few people as opposed to increasing the RP. I think it's a cool idea in theory but I would just start out with the dislocated bones thing as a feature maybe. People could RP out a broken bone or whatnot if they wanted.

**Comment by Skai97** [comment]
Nerfing oxy and ifaks would be a good start tbh, the only injury these don't fix is head injuries. Leg brace, arm sling. A bandage that automatically stops bleeding but doesn't heal you. 

Medical bag similar to the wallet that could store x amount of braces, slings and splints. These cost a lot more in the shop but are cheaper if bought directly from ems. Medical supplies in general just cheaper from ems workers. You have an arm Injury? Apply a sling, leg injury use a leg brace. Just some extra depth to the Medical system in general would be nice to see. 

Ems relies heavily on people role-playing with them but this might add a little more?

**Comment by coalaura** [comment]
I mainly have the same concerns @ImArteria mentioned. We cant add these injuries if they can ONLY be treated by EMS. We do not have EMS around 24/7 and some subdivisions have them around even rarer since they don't have many players. There would HAVE to be a way to get it treated without EMS around.

**Comment by ImArteria** [comment]
Besides a splint and whatnot, I would say maybe Grandmas is good? Than again my thought process on this is we already have an issue of people trying to RP with EMS. If we give people an option to not RP with EMS for a faster experience they'll always do that. With this suggestion, it's a big gameplay impact so you'll ALWAYS need an option that isn't EMS.

**Comment by coalaura** [comment]
Grandmas wont work for legal people tho

**Comment by coalaura** [comment]
> Painkillers maybe you take 5% less damage from certain sources? Or if your leg is injured a pain killer gets rid of the injured walk temporarily

Painkillers actually have an effect but i just noticed a bug causing them to not work, should be fixed next update

Other than that, eventhough i think this is a cool idea i sont think it would work out in practice due to the reasons talked about above
