### ISSUE TITLE
Suggestion - Riding Animals

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3069]
### Assurance

I have read the `README.md`

### Summary

Purchase a saddle from somewhere like the hunting store, or pet store? And allow us to ride certain animals like Horses, Boars, Cows etc etc.

### Reason

We already have a leash, and it would be super cool to ride these animals aswell. This would be my favourite thing ever if it got added lmao.

**Comment by txxlrrsCoding** [comment]
And also if possible have to tame them before. For example, whistling at deer to lure them closer and then pet them before you can leash / saddle it.

**Comment by coalaura** [comment]
GTA was not really made for riding animals. Eventhough this is a cool idea it always ends up looking super scuffed like this for example

![yea](https://forum.cfx.re/uploads/default/original/3X/d/e/de0762df0d95ac6075faa959213f06044543df7c.jpeg)

**Comment by ImArteria** [comment]
> GTA was not really made for riding animals. Eventhough this is a cool idea it always ends up looking super scuffed like this for example
> 
> ![yea](https://camo.githubusercontent.com/d17b4628f9abed0438c5b77e8a0491dc30c2c4e67996c517d76ee2dad6043b91/68747470733a2f2f666f72756d2e6366782e72652f75706c6f6164732f64656661756c742f6f726967696e616c2f33582f642f652f646530373632646630643935616336303735666161393539323133663036303434353433646637632e6a706567)

This is better than I thought it would come out ngl.

**Comment by txxlrrsCoding** [comment]
This is perfect!

**Comment by coalaura** [comment]
thats just a random screenshot i found online, what i am trying to say is the opposite. I think it looks very goofy and when you start moving around with it, it looks super scuffed the way you move
