### ISSUE TITLE
Suggestion - Paleto Tool Store

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3070]
### Assurance

I have read the `README.md`

### Summary

Hey it's ya boy Scufflord back again with another "Paleto is really far away and could use QoL additions" Github at midnight after I've smoked too much.

We could use a tool store here at Willie's across from the clothing store. Gives access to things for folks that live up north without a far drive down to Sandy. 

https://cdn.discordapp.com/attachments/845947698628001862/1183286631436926986/image.png

### Reason

Make Paleto Great Again

**Comment by coalaura** [comment]
Done #makepaletogreatagain #toomuchweed #dontdodrugskids
