### ISSUE TITLE
Suggestion - Weapon Scratching

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3071]
### Assurance

I have read the `README.md`

### Summary

Add a way to scratch names and serials off of registered guns... But leave it on pistols so the ammo is still traceable to the person.

### Reason

Better RP

**Comment by coalaura** [comment]
No, cause that will lead to people buying guns from ammunation for crimes which defeats the point. Or legal people buying glocks, scratching off the serial number and selling them
