### ISSUE TITLE
Suggestion - No backdoor on Sam Austin Drive 3

### ISSUE THREAD

**Issue by laurealis** [InZidiuZ/op-framework-issue-tracker#3072]
### Assurance

I have read the `README.md`

### Summary

My house on Sam Austin Drive 3 doesn't have a backdoor to the backyard, and it would be nice addition to have.

### Reason

I'm pretty sure that all other mansions have a backdoor to the backyard, and it would make it much more convenient for the residents of this house.

**Comment by coalaura** [comment]
done
