### ISSUE TITLE
Suggestion - Add a lockout for paleto bank that is different than Fleeca banks

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3073]
### Assurance

I have read the `README.md`

### Summary

To keep every bank that is done being a Paleto as it currently seems to be the majority of the time, have that bank be a seperate thing from Fleeca banks when it comes to being closed or not. So instead of it being 24/7, bank, j store for /active_robberies it would have a 4th line for paleto

### Reason

cause cops are going through it rn frfr and im a crim main so you know im not biased

**Comment by coalaura** [comment]
I mean i get that but its just a bank, i don't really see a need for an extra lock considering you only make about like 6k more on average. I very recently redid the loot drops too

**Comment by coalaura** [comment]
I've made the cooldown be a few minutes longer but i dont want to separate it into its own thing
