### ISSUE TITLE
Suggestion - Videogeddon NEEDS Garage Access

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3074]
### Assurance

I have read the `README.md`

### Summary

Months ago this was a request (see suggestion #2875), but has now become a requirement. On the International server, the Arcade is open more than ever before. With this recent consistency, the business has gotten a lot of attention that has been both a blessing and a curse. The malicious activity done around the Arcade has become a MAJOR issue. A prime example of this was when we had to appeal to the asset team to put in parking bollards to prevent people from blocking the door with vehicles, effectively trapping people inside. This has since been resolved, but there are several other issues that only a garage could solve at this point.

If adding another public garage is unnecessary, a private one can go here:
![garage](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/73ce34db-799e-4f77-8130-8c81bd9d683c)

### Reason

To assist with our efforts in keeping the Arcade open as much as possible, we have more people spending a lot of time there. State has deemed Videogeddon an essential business that is required to be open to the public as much as possible.

1) Issue 1: Employees park in front or on the side of the business, sometimes for hours. With the business having no windows, there's no way of telling what's happening outside to prevent vehicle tampering. Very often, an employee will get an order on the Arcade hotline, then go to their car to complete the delivery only to find out that their car has had the tires slashed, has been blown up, has been stolen, or has been towed (when legally parked). 

2) Issue 2: If the car is parked under the business to avoid Issue 1, the car is poofed from existence. This happens so frequently that it's not worth parking down there. Combined with Issue 1, there are 5 different ways that Arcade employees can be left stranded/inconvenienced and customers unsatisfied with unfulfilled orders.

3) Issue 3: Any public garages are too far to park and walk to the Arcade, with the nearest one being the Mirror Park garage. 

As it stands, there's no amount of RP that can resolve these issues. To reiterate, this is affecting everyone on the International server that works at the Arcade. If the business is to continue to function properly, we need to be placed in an environment to succeed. The resolution to these issues is a garage mechanic. If this requirement is deemed unnecessary, please comment before closing.

**Comment by coalaura** [comment]
I'll look into potentially adding a garage that is locked to the job there

**Comment by navonody1** [comment]
> I'll look into potentially adding a garage that is locked to the job there

That would be much appreciated.

**Comment by LusciousLuna** [comment]
Yes thank you so very much

**Comment by ristwell** [comment]
Thank you very much, end my suffering

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/1ZU1W2MBYT.png)
