### ISSUE TITLE
Suggestion - About Document Printing and Document combiner 

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#3076]
### Assurance

I have read the `README.md`

### Summary

As we have printer and photo printer rn to make a small document or if you wana issue a NOC or mostly all document thing happens on Notepad or ooc on Google docs We can add one A4 Size Paper in same shop or Document paper or something where you can Print that Specfic document and it should say it got printed by whom and there should be Like combiner or 
![folder-icon-file-quality-shape-design-free-png](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/49905280/da57b90c-9be6-4a06-8580-2ae905d25b08)
Something like that So we can combine all Images and make like Court documents or something

### Reason

It will make Little bit ez in rp to access documents or most of the things and create more rp

**Comment by coalaura** [comment]
I'm down to make an A4 format paper but i don't think the whole combine thing is needed and its a lot of work for such a small use case

**Comment by HollaYalla** [comment]
Couldn’t you just use the Wallets code and stuff but change what it can hold from cards to paper plus this would be handy for business cards and receipts and other documents

**Comment by coalaura** [comment]
> Couldn’t you just use the Wallets code and stuff but change what it can hold from cards to paper plus this would be handy for business cards and receipts and other documents

wallets ALREADY hold paper

**Comment by HollaYalla** [comment]
> > Couldn’t you just use the Wallets code and stuff but change what it can hold from cards to paper plus this would be handy for business cards and receipts and other documents
> 
> wallets ALREADY hold paper

Oh I haven’t used them so I didn’t know lol
