### ISSUE TITLE
Suggestion - Inventory drop on cargo

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#3077]
### Assurance

I have read the `README.md`

### Summary

As per the new update, when you die at Cargo, your entire inventory drops on the ground except for the smartwatch. Phones and radios should not drop either.

### Reason

Because I believe it's not something that others would want to loot, and after respawning or being treated, you're completely wiped without phones or a radio.

**Comment by InZidiuZ** [comment]
The items that you are allowed to keep are only the essentials, and it follows the 'unmuggable items' list that is used on death. We've decided to not expand the list with phones and radios at this time, so this idea is being rejected.
