### ISSUE TITLE
Suggestion - Addition of new emote for roleplaying with lean

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3078]
### Assurance

I have read the `README.md`

### Summary

So normally you don't just like straight up chug lean once it's poured, so it would be kinda cool if there was like a "/e siplean" emote that is a copy of something like /e whiskey or /e coffee but with the prop used when someone drinks lean

### Reason

let me roleplay my addiction to codeine cough syrup frfr rip juice wrld

**Comment by coalaura** [comment]
sure thing, shouldn't be too hard to do (i think)
