### ISSUE TITLE
Mug shot's Channel in discord For police

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#308]
**Name:**
Randy James#4851

**Summary:**
A mug Shots channel for the police.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a good suggestion because anyone can carry around a fake id and use it in criminal activity so if we mug shot every criminal and put their real name next to every mug shot. We could catch people carrying false identification and we can get their real name by taking them to the court. So were reporting and arresting the right person.

**Comment by InZidiuZ** [comment]
Hey,

This is not a framework related suggestion at all, so closing. Please discuss this with the PD higher-ups.

**InZidiuZ**
*OP-FW Developer*
