### ISSUE TITLE
Suggestion - Log of GW storage 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3080]
### Assurance

I have read the `README.md`

### Summary

Hi I'm Ryan the owner of Green Wonderland I understand this is a longshot and I understand if you can not grant this but as theft is starting to become a issue at Green Wonderland by employees I was wondering if there would be a way that I could get a log of what people put into and take out of our storage and who took it out and put it in. 

### Reason

Theft is becoming a big issue and it needs to be handled and there is simply no other way to find out who the thieves are and have evidence of who it is.

**Comment by coalaura** [comment]
there is logs but those are staff side. I'm not going to add in character logs, no. You will have to deal with the theft a different way
