### ISSUE TITLE
Suggestion - serial numbers on guns

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#3081]
### Assurance

I have read the `README.md`

### Summary

I believe that to enhance role play from all aspects, removing 'serial numbers' from 'illegally imported guns' is something that should be considered.

### Reason

Something that makes a gun illegal, is the fact that it does not have a serial number.

I believe that removing this aspect, would enhance the low quality RP that has been happening surrounding these sorts of guns.

Walking up to a person, asking for the serial number on their rather large gun- would never happen realistically. People with illegal weapons should be 'feared', neither would someone probably hand over a gun of such for anyone to inspect realistically.

I feel like it is important to note that having these serial numbers on these guns, also can hinder the RP of the person possessing the gun.. removes the possibility of having a 'scratched off serial number' scenario, if someone were to obtain the weapon & look for the number.

**Comment by DaxterPancake** [comment]
I don't believe that removing serial numbers from all illegally imported guns is fair. A lot of police RP surrounds collecting evidence and then linking crimes. 

The ability to spend time, money, resources to remove a serial number instead of ALL being gone would be a better alternative, in my opinion. 

Instead the people who aren't fearing for their lives when faced with large weaponry should be handled by staff of the respective server you play.

**Comment by RhysLando** [comment]
+1

**Comment by selliee** [comment]
I just feel like criminals really have no use for serial numbers, so maybe just implement a function where it does not take away from cops, where they have access to it only, so things stay the same for them.

**Comment by coalaura** [comment]
It would take away massive amounts of FIB roleplay. Making it so only cops can see serial numbers feels weird too since serial numbers are on the gun so it'd make no sense for you to not be able to read it. I don't think this would solve any low quality roleplay

**Comment by coalaura** [comment]
That being said, i am going to add a way to file/scratch off a serial number. However this would be up to the person using the gun to do, all guns will still come with serial numbers. Once filed/scratched off, you wont be able to see the serial number anymore by inspecting (pd cant see it either), but PD would have the ability to ballistics test the gun to get the serial number back.
