### ISSUE TITLE
Suggestion - Serial numbers on guns  being a cop only mechanic.

### ISSUE THREAD

**Issue by ItzBrittanyBitxh** [InZidiuZ/op-framework-issue-tracker#3082]
### Assurance

I have read the `README.md`

### Summary

Make the "inspect" option on guns which shows the serial number, a police-only server mechanic. 

### Reason

The server mechanic if being able to"check" a serial number on a gun, should be limited to cops only. This function is intended (we assume) to be used by cops, as it was added at the time that gun degradation started, so serial numbers could still be checked and people charged with broken guns.

Most guns in the server show as Serial Number: unknown when checking the item itself which makes sense, as these are illegal guns. It makes no sense for a criminal to be able to see the serial number on a weapon that was imported illegally. This makes sense for cops mechanic-wise to see casings ect. A civ walking up to someone and saying "lemme see your serial number" makes no sense.

An alternate option is adding an item that allows you to scratch off serial numbers on non-registered guns, so it's only viewable to cops but removes the civ ability to do it or "see" it.

**Comment by coalaura** [comment]
Serial numbers are etched onto the weapon, it makes no sense and feels very weird and restrictive to limit this to only cops. Like i said in #3081, no i don't think this is a good idea. If i were to add a feature to "scratch" the serial number off, then it would also no longer be visible to cops.

![yes](https://www.pennlago.com/wp-content/uploads/serialnumber.jpg)

**Comment by coalaura** [comment]
That being said, i am going to add a way to file/scratch off a serial number. However this would be up to the person using the gun to do, all guns will still come with serial numbers. Once filed/scratched off, you wont be able to see the serial number anymore by inspecting (pd cant see it either), but PD would have the ability to ballistics test the gun to get the serial number back.

**Comment by coalaura** [comment]
Like so (you will need to craft a file first ofc).

![yes](https://i.shrt.day/JUTRI2QNBB.png)
![yes](https://i.shrt.day/VXJWRU738B.png)
![yes](https://i.shrt.day/VFLEW66V5U.png)
