### ISSUE TITLE
Bug report - (Oxy) JC doesn't like old bottles?

### ISSUE THREAD

**Issue by Firingzod** [InZidiuZ/op-framework-issue-tracker#3083]
### Assurance

I have read the `README.md`

### Reporter

Firingzod #2462

### Summary

I was doing an oxy run. I collected the prescription and redeemed it all.After finishing the run i went to collect the money from JC. He was saying you still have to collect oxy.So I opened the map and searched if I have missed anything but there was nothing which I had missed. I searched my inventory and I had 9 oxy 1 extra from earlier runs. eventually I lost $4k

### Steps to Reproduce

i am unaware

### Expected Behavior

Expected results are that I would get the money for collecting all the oxy in the given time

### Actual Results

I did not recieved the money and he was asking me to collect more oxy while there was no more prescriptions left

### Screenshots/Videos

"C:\Users\bhowm\Videos\Captures\FiveM® by Cfx.re - Legacy Roleplay India _ Custom Framework _ Serious RP & Economy _ Active PD, EMS, Gangs & Staff _ Custom Cars _ discord.gg_legacyindia 2023-12-19 12-27-40.mp4"

### Game Resolution

1920 X 1080

### Player Data

![FiveM® by Cfx re - Legacy Roleplay India _ Custom Framework _ Serious RP   Economy _ Active PD, EMS, Gangs   Staff _ Custom Cars _ discord gg_legacyindia 19-12-2023 16_25_16](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/108629696/bc794c4c-9816-437f-93af-4b4bfc516b17)

### Server

India (c8s1.op-framework.com)

**Comment by scufflord** [comment]
You most likely had two oxy on you from an earlier run and used one of them during your run. Due to the way the item stacking works, it made you use a new bottle from your current run instead of one of the old bottles, and thus JC didn't wanna accept it because you didn't have the brand new fresh 8 bottles he was expecting.

**Comment by InZidiuZ** [comment]
> You most likely had two oxy on you from an earlier run and used one of them during your run. Due to the way the item stacking works, it made you use a new bottle from your current run instead of one of the old bottles, and thus JC didn't wanna accept it because you didn't have the brand new fresh 8 bottles he was expecting.

Is this plausible, @Firingzod?

**Comment by coalaura** [comment]
this was fixed
