### ISSUE TITLE
Suggestion - recipe book and copier idea

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3084]
### Assurance

I have read the `README.md`

### Summary

Add a recipe book item that you can carry on you. Once you have the item on you, any items that you craft while carrying that item will have the ping to the location written down plus what items you used to make it. The owner of the book can then using a printer/copier item bought from the printing store by Tequila-la to make a copy of their book if they want to share it around.

### Reason

This moves recipe gathering and sharing into the world of roleplay and out of a google sheets document. Players could be greedy and never share all their recipes around, and others could try to steal that recipe book from them through roleplay by taking the book from them. Also adds the option for PD to better investigate things instead of having to catch someone in the act or convince someone to snitch. If they get a loaded recipe book off of a criminal then boom they have the unlock on a bunch of stuff. Since things like extended magazines and suppressors are illegal on the international server you could simply add on to the penal code that any documents detailing the crafting or production of said items is subject to seizure at arrest.

**Comment by coalaura** [comment]
I don't like this, it removes the fun of having to find them. People will just collect all and make one book to "meta-unlock" every new person, instead of people having to collect and find the places themselves piece by piece
