### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Kunal01s** [InZidiuZ/op-framework-issue-tracker#3085]
### Assurance

I have read the `README.md`

### Summary

my suggestion is for garage near repair shop 2 at diamond casino for the emplyes of repair shop 

### Reason

This will help the employes of repair shop and the person near casino because every repair shop have a garage near it because repair shop 2 is the only repair shop who don't have a garage

**Comment by coalaura** [comment]
i do not think a garage at the lost MC is needed
