### ISSUE TITLE
Suggestion - move VU garage to parking lot on roof of the ammunation by pdm

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3086]
### Assurance

I have read the `README.md`

### Summary

Simple request, moves it to an open public parking lot that makes more sense for people to be using, and also provides a fast and easy way for players to store a car, go to PDM, and purchase a new one instead of having to run far away. This location also keeps it close to VU, while detaching it from the business itself.

### Reason

Because less cars at pdm to steal = less trolls showing up trying to steal cars, vdm people, and rdm people. Also, detaches the garage from the business and moves it to a public lot like the ones near bean machine and burger shot were recently moved.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/RVRFSG97JX.png)
