### ISSUE TITLE
Suggestion - Make Daxter's Life Easier

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#3088]
### Assurance

I have read the `README.md`

### Summary

When using /debug in the clothing menu, it displays what the clothing/file name is so its easier to find when people give her a number on a clothing piece

### Reason

Make daxter's life easier

**Comment by DaxterPancake** [comment]
+1

I usually spend a good amount of time searching for clothing when people request it. I have gotten better with time knowing generally what DLC clothing is but having the file name would cut down the time it takes searching for it.

It would then make clothing requests more straight forward and easier for the community.

**Comment by MetaHatter** [comment]
From what I understand there's no real way to map between the indexes of clothing and the files they get pulled from.  But I last heard that over a year ago so something may have changed.

**Comment by coalaura** [comment]
yeah its been discussed many times that if we had the ability to do this we absolutely would lmao @ImArteria smh
