### ISSUE TITLE
Suggestion - contacts search funtion

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3089]
### Assurance

I have read the `README.md`

### Summary

Addition of a search function to the contacts page on gcphone. I know gcphone can be a headache to work with but hopefully there's a way to add this.

### Reason

Some of us have hundreds of contacts and it would be helpful to not have to scroll manually to call someone at the bottom.

**Comment by selliee** [comment]
yes

**Comment by coalaura** [comment]
![pain](https://media.tenor.com/4GUSLU8YpbgAAAAM/pepe-kid-cry.gif)

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/WQ2FWB6UZ9.png)
![yes](https://i.shrt.day/7RD3J259LZ.png)
