### ISSUE TITLE
When escorting you cant sprint if it bugs.

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#309]
**Reporter:**
Randy James#4851

**Summary:**
when I escort a criminal it sometimes it won't let go of the criminal unless i carry him and let him go but after that, I'm scuffed because I can't sprint at all.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
When escorting its just simple escort and when you do escort again its let him go simple.
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Closing, missing repro.

> Steps to Reproduce:
Include what steps that are needed in order to reproduce the issue.

**InZidiuZ**
*OP-FW Developer*
