### ISSUE TITLE
Suggestion - Visibility of Photograph

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#3091]
### Assurance

I have read the `README.md`

### Summary

with the ability to print documents and photos with the help of a printer inside the server. Most OOC stuff, like providing NOCs, rental agreements, and much more, is possible. But the scene with the photograph is that it's only visible to ourselves when used. So it would be nice if other players around us could also see the photograph, just like ID's.

### Reason

I suggest this because if someone wants to do RP as a photographer or something, he can showcase his talent with those photos. but as currently others can't see the photos, he needs to either pass those photos in others pockets or drop them on the ground. and also a binding book or something like that where one can stack all of his photos in one place if possible.

**Comment by coalaura** [comment]
No, the whole point of photographs and printed items is that its not constantly blasted in everyones faces
