### ISSUE TITLE
Bug report - Boombox sometimes causes ping spikes

### ISSUE THREAD

**Issue by Manmohan-zanwar** [InZidiuZ/op-framework-issue-tracker#3092]
### Assurance

I have read the `README.md`

### Reporter

RexDev#5702

### Summary

I work at arcade bar and until i didn't have customers, i used my boombox as a sort of timepass so when i used it today, i faced the same problem multiple times of ping-dash from 60 70 to 1500+

### Steps to Reproduce

Resolve Ping Issue that strikes after the boombox is used

### Expected Behavior

It should work as normal as it used to be

### Actual Results

right now its a lot glitchy.

### Game Resolution

1920x1080 144hz

### Player Data

![Screenshot 2023-12-22 130432](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/136070718/d04bfe41-63f7-46a6-b4f9-88315cf1fe93)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
Is this still an issue?

**Comment by Manmohan-zanwar** [comment]
Nope!!
