### ISSUE TITLE
Suggestion - Quicker Weapon Switching

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3093]
### Assurance

I have read the `README.md`

### Summary

Make it quicker to switch between weapons. (Like holstering, or a quicker animation.
OR, instead of a new animation.. Make it so you only have to play it once to pull out a different weapon.
For example, if you have an assault rifle out, and your sniper is on your second inv slot, if you press 2 then it will put the rifle away and get the sniper out in the same animation.

### Reason

For example, if you're a sniper on a roof, and someone sneaks behind you, 99% chance you wont be able to quickscope them so you're literally just dead.
Or, for example, you need to quickly unequip your assault rifle for a knife because of someone who ran right up to you. It's extremely slow to switch, and it makes you a very easy target for anyone who comes up close.

**Comment by coalaura** [comment]
This is not a shooter but a roleplay server

**Comment by txxlrrsCoding** [comment]
I am aware,  but even within rp it doesnt make sense that you have to play the animation twice. It's extremely slow.

**Comment by coalaura** [comment]
there is a reason our weapons switching takes the time it takes
