### ISSUE TITLE
Suggestion - Tweaks to Poles and Meters

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3094]
### Assurance

I have read the `README.md`

### Summary

- Make parking meters break based on speed (similar to poles now, but a lower speed requirement)
- Make light poles never break

### Reason

Parking meters being completely invulnerable is a bit odd.  Since they have less of an impact to a race or a chase when desync than light poles, they would benefit from the speed-based breaking mechanic currently on the poles.

Conversely, making Light poles unbreakable fits with reality and eliminates the horrible ghost poles that are desynced across clients.  Rewarding skilled driving and fixing an issue with the default mechanics that ruins races/chases.

**Comment by coalaura** [comment]
I dont like making the light poles fully indestructible but i've made the parking meters breakable now
