### ISSUE TITLE
Suggestion - Switchblade animation

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3095]
### Assurance

I have read the `README.md`

### Summary

Putting the animation for the switchblade back to vanilla where it is quickly pulled out instead of slowly from the back. 

### Reason

Switchblade is meant to be like the sneaky-quick pull knife with its flick animation and small size. 

Switchblade used for stabbing, other knifes have the function of hunting etc.

A lot entertaining moments missed out on when someone could quickly pull a switchblade and stick someone.

**Comment by coalaura** [comment]
#3094

**Comment by Skai97** [comment]
Most definitely not the same thing, weapon holster speed is fine. This is 1 item ands whole purpose is to be a quick pull out. 0 uniqueness between the like 6 knifes

**Comment by scufflord** [comment]
i definitely miss the animation with the switchblade

**Comment by coalaura** [comment]
> Most definitely not the same thing, weapon holster speed is fine. This is 1 item ands whole purpose is to be a quick pull out. 0 uniqueness between the like 6 knifes

Thats not really what i was on about, i was more referencing my reply to the issue: "there is a reason our weapons switching takes the time it takes" i dont really think knifes need shorter withdraw times, i can take a look at some animations tho
