### ISSUE TITLE
Suggestion - Notes for Savings Account

### ISSUE THREAD

**Issue by antonettedorado98** [InZidiuZ/op-framework-issue-tracker#3097]
### Assurance

I have read the `README.md`

### Summary

The new savings account lists previous transactions, itd be nice to add a feature that prompts players to add a note for the transaction made.

### Reason

People share savings accounts, itd be cool to know why money was taken or given.

**Comment by coalaura** [comment]
i can add an optional "note" field

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/LER5Q9L6EY.png)
