### ISSUE TITLE
Adding garage for Vespucci Boulevard 5

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3099]
### Assurance

I have read the `README.md`

### Summary

I asked before also to add garage but you told us to use public garage that was at burgershot. But recently the public garage of burgershot is shifted to another place and now it is diffucult for owner of Vespucci Boulevard 5 house to use their vehicles.

If you can just combine garage of Vespucci Boulevard 5 AND Vespucci Boulevard 6 than it would be great.

### Reason

Why not garage ?.

**Comment by coalaura** [comment]
still no, like i previously said

**Comment by ayushpatel1007** [comment]
What? Really coalaura ? What is issue adding garage ? We are not asking you to add something new to server that is never added before, it’s just a garage and you did combined few houses garage together then what’s the issue here adding one? 

Only people who use that house can understand the pain of not having garage. 

I request you to add one please. Just combine garage of house 5 and 6
