### ISSUE TITLE
Illegal tuner shop

### ISSUE THREAD

**Issue by MarioGigante** [InZidiuZ/op-framework-issue-tracker#310]
**Name:**
Who is suggesting this? Please include discord name.

Mario Gigante ( dnk | Mario Gigante#0874)

**Summary:**

Write a short summary of what your suggestion is about.
Tuner Shop where u could add some illegals on your car and much more

**Reason:**

Why would your suggestion be a good addition to Legacy?

Would add more options for the Rp scenarios and i feel people would love it

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new, more detailed issue.

**InZIdiuZ**
*OP-FW Developer*
