### ISSUE TITLE
Car Add-ons

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3100]
### Assurance

I have read the `README.md`

### Reporter

SluggsV2

### Summary

For the turismo classic, when customization, it allows you to buy HSW upgrades for 500$ when paid nothing happens then there’s a bodykit tab with HSW body kits and nothing happens also the livery’s are broken nothing show! 

### Steps to Reproduce

Check code make sure it works inside midnight 

### Expected Behavior

Add widebody kit and liveries 

### Actual Results

Just takes money and doesn’t add parts

### Server

OP-FW Test Server (c2s1.op-framework.com)

**Comment by coalaura** [comment]
This is a native GTA vehicle, we cannot change them

**Comment by SluggsV2** [comment]
But it already shows it in the customization screen at midnight? It's just visuals need fixing?

**Comment by COWBOI28** [comment]
Idk think HSW upgrades are native to the PC version of GTA so they can't add/fix it tho im not 100% sure
