### ISSUE TITLE
Suggestion - Add search bar for phone calls

### ISSUE THREAD

**Issue by laurealis** [InZidiuZ/op-framework-issue-tracker#3102]
### Assurance

I have read the `README.md`

### Summary

The search bar that was added for contacts/texts app has been very useful. However, the phone call app lacks a search bar. I think adding a search bar to phone call app would provide the same benefits that it has for texting.

### Reason

Just like texting someone has become so much easier with a search bar, make calling someone just as easy.

**Comment by coalaura** [comment]
you can call someone from the contacts tho, thats why there is a search bar there
