### ISSUE TITLE
Suggestion - Remove thermal Goggles

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3104]
### Assurance

I have read the `README.md`

### Summary

The thermal goggles practically have not been used by crims since added to the server. I've personally only seen them used to look through 6 walls of concrete (which is why all of the helicopter thermals got nerfed) or used to find people in incidents like this below. Only examples i could find. How is this server mechanic fair? There is 0 effort on the police side. 

### Reason

https://clips.twitch.tv/ViscousSplendidShingleKappaRoss-aoHgX1iqdKmEzIMQ
https://clips.twitch.tv/PiercingTardyAntOpieOP-4iVJbKXl4uLZfyCm

Not to be clipping directly from Johnsons stream, I have no affilation with the people involved but this is just one example of the many times they have been used.

**Comment by scufflord** [comment]
Hard agree on this. They just aren't useful from a criminal perspective, and are extremely overpowered and broken from the cop side.
