### ISSUE TITLE
Suggestion - More break downs and crafting

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3105]
### Assurance

I have read the `README.md`

### Summary

Breaking down desc keys
crafting ssd 
crafting chip 

### Reason

Desc keys are craftable and have a decay time. The ability to break down broken keys every 3 = 1 craftable 

Crafting SSD used for pagers, limited resource and can often be hard to find (expensive recipe) 

Crafting CHIP, Chip is used for a lot of illegal activity boosting, robberies, gun PC. They are in high demand and house robberies alone give a very low yeild of chips.

**Comment by coalaura** [comment]
> The ability to break down broken keys

sure thing

> Crafting SSD used for pagers

I'm quite happy with how rare they are right now

> Crafting CHIP

I don't like the idea of being able to craft a chip but i can look into adding more ways to get them
