### ISSUE TITLE
Suggestion - Car Tracker 

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3106]
### Assurance

I have read the `README.md`

### Summary

Car Tracker app or upgrade inside of bennys (Car tracker)

### Reason

We can no longer use the garage to track vehicles even if you buy the full alarm system full your vehicle once it is stolen, good luck finding it unless it has been towed or randomly come across it

**Comment by coalaura** [comment]
> We can no longer use the garage to track vehicles

I intentionally removed this, to encourage people to pay more attention to where they leave their cars
