### ISSUE TITLE
Bug report - Battering Ram Instance Issue

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#3108]
### Assurance

I have read the `README.md`

### Reporter

Arteria

### Summary

When leaving a house using the battering ram, it will place you in a different instance (maybe the same as the house?) than the "real instance"

### Steps to Reproduce

Use battering ram
Enter House
Leave House
Wrong Instance

### Expected Behavior

Should be in the correct Instance

### Actual Results

In the incorrect instance. Doesnt seem to be everytime though. Might not be a battering ram scuff but maybe a property scuff since battering ram was recently rewritten

### Screenshots/Videos

n/a

### Game Resolution

1920x1080

### Player Data

n/a

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
believe this is no longer an issue (correct me if wrong)

**Comment by scufflord** [comment]
> believe this is no longer an issue (correct me if wrong)

it's still pretty bad. have to close and re-open fivem after you leave the house, so if you have to do multiple in and outs its multiple times having to unload and load back in

**Comment by coalaura** [comment]
@scufflord hmmm, i've played around with the instances and i believe this may just be a FiveM bug at this point

**Comment by ImArteria** [comment]
Yo mfers this joint closed chill
