### ISSUE TITLE
Suggestion - tuner chip rebalancing

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3109]
### Assurance

I have read the `README.md`

### Summary

With the abuse of tuner chips back in the day when you could change a car from AWD to RWD or FWD to what it is now where tuner chips can only change slight things about a car, it has kind of brought the allure of getting a tuner chip down. It would be nice if the effect of a tuner chip could be doubled possibly, if not slightly more just to make it have a bit more of a difference on tuned vs untuned. 

With this, I think adding PD tuner chips could be a good thing. In roleplay, pd could limit this to only be used by certain ranks/only in speed units. northbayjoe for example uses a tuner chip on the speed units and the 18 charger for certain cars to give it just a little bit more to make it so they're more evenly matched. With crim cars and cop cars being at a very close point now after the speed reduction happened, this could be a way to widen the gap a bit more between them. Say there's nobody on duty with access to a tuner chip and a crim has a tuned cracked car? or say someone shows up in an untuned car for a bank, only to look outside and see Ryan Walker screaming about Tesco's meal deals and messing around with the tune on his Demon.

With this, I think some balancing needs to happen to drop rate of tuner chips, as well as adding them to additional loot pools such as house robberies, or even potentially a crafting option. The current market of tuner chips is basically what people happen to either find in a house they rent, or a realtor sells it to someone when they find it in a house. I'm sure there's some that still drop from chop for a few lucky people, but the number is insanely low

### Reason

Car go brrr. If car go more brrr... then car more pog. It brings a fun added dynamic to both chases and racing without requiring Joe to go in and re-tune every single car AGAIN.

**Comment by joevapes3** [comment]
yah the tuning chip works currently well, however what it gives is a bit underwhelming, I think it doesn't need much more, but maybe slightly increase it's current values and see how that does. Rather go a little and see how it feels vs alot and regret it.

**Comment by Skai97** [comment]
This has been a bug in the server for a long time. If you tune a vehicle and go into bennys, change any modification. The car will be faster. 

A very large majority of the good drivers in the server haven't touched tuner chips since they got nerfed into the ground over a year ago

**Comment by sbz3** [comment]
Adding a tuner chip to PD wouldn't be very smart as of right now with PD cars already overpowering civ cars. Most situations that come down to driving depends on the driver. But as it stands now Tuner Chips do not get used nowhere near as much as the old Tuner Chip.

**Comment by coalaura** [comment]
i've buffed all values by a little now, if it turns out to still be too little i can buff them further.
