### ISSUE TITLE
Suggestion - rock paper scissors command

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3111]
### Assurance

I have read the `README.md`

### Summary

add a command to give people a way to play rock paper scissors. could be used for gamba or to settle a disagreement on who is gonna win something/do something

### Reason

it sounds fun

**Comment by coalaura** [comment]
lmao, me likey

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/FAQQYFLN2G.png)
![yes](https://i.shrt.day/M1QFA62M77.png)
