### ISSUE TITLE
Suggestion - Tie Smartwatch to CID

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3112]
### Assurance

I have read the `README.md`

### Summary

Smart watches tied to individuals CID opposed to the watch for consistent tracking and loss of info

### Reason

There have been times when smart watches have been stolen or lost, and steps/murders/downs then go away with the watch. Linking Smartwatch Data to CID would be helpful for making this item less of a punch to lose. Steps are a fun thing to track along with other stats, just like your Phone doesn't lose contacts if lost/stolen, smart watch shouldn't either if it is "cloud sync" like phones.

**Comment by coalaura** [comment]
no, the whole point is that anyone can improve your steps for you and people can work together

**Comment by MADxxVIKING** [comment]
Great outlook! Thanks for reviewing Laura 😄
