### ISSUE TITLE
Car fix - 2018 Toyota GT86

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3113]
### Assurance

I have read the `README.md`

### Summary

Car has many issues it messes up the front of the car whenever doing any customisation, the interior looks like 90s TV static. It's costs 135k and drives very poorly. Car's main perk is in customisation but the wheel stance on most body kits is completely mesed up

### Reason

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/52269307/169d0f73-af97-497e-b145-d7f8c8e64378)

**Comment by Skai97** [comment]
Wrong place

**Comment by coalaura** [comment]
yes, wrong place https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
