### ISSUE TITLE
Text Notifactions and Phone Calls

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3114]
### Assurance

I have read the `README.md`

### Summary

Either same spot as Twitter notifications or it should bring the phone up and show the alert on it 

### Reason

Easier to see if your needed urgently or it can wait, pretty common practice for a phone, and I think it would improve the city

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/BV0LBCGXUR.png)
![yes](https://i.shrt.day/K32Q9H4HSM.png)
