### ISSUE TITLE
Neighbourhood update!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3116]
### Assurance

I have read the `README.md`

### Summary

Nikola Place Mirror Park Gated Community + removing the For Sale Sign Boards on front lawns 

### Reason

Can we make the Mirror Park Mansions Nikola Place Gated makes them feel upper class and safer just on at the end of the street nothing crazy and please could we take away the for sale sign boards!

**Comment by InZidiuZ** [comment]
This is the wrong issue tracker for this, use the [assets issue tracker](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) for map-related changes.
