### ISSUE TITLE
Exclusive Dealership - Ability to Finance cars.

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#312]
**Name:**
Hunter Zurxey, discord is Zurxey#2607.

**Summary:**
This suggestion will be about a quality of life improvement for those who choose to support the server every month. 
Basically, I am suggesting that we add a PDM like feature to the Exclusive Dealership, meaning that supporters will be able to finance those exclusive cars as well, now, i'm only suggesting this as I believe that if you truly want to help the server with $20+ per month, you should be able to do exactly what PDM Does. I'm not wanting cheaper prices, or anything of that sorts. You can make the dealership prices exclusive, and they can be done by the highest of PDM if possible as well.

**Reason:**
I believe this would be a good addition as it's got potential to make many people in the community happy, as i'm sure. 
I just believe that having an option to finance, for an extended price (it can be raised, doesn't need to be directly like PDM I guess.) it could bring some new supporters, and happy existing supporters, it also could bring in some new roleplay, bringing the fact that the PDM higherups would be in charge of it.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Devleoper*
