### ISSUE TITLE
Suggestion - make garfield area in mines a safezone from sickness 

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3121]
### Assurance

I have read the `README.md`

### Summary

praise garf. bask in his glow. allow him to protect you from the sickness for a short time. 

### Reason

garf is love, garf is life.

**Comment by coalaura** [comment]
eventhough im high as fuck and this is pretty funny im gonna say no

**Comment by tiigerrlily** [comment]
Praise lord Garf
