### ISSUE TITLE
Early Leave the house 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3122]
### Assurance

I have read the `README.md`

### Summary

So the idea is, a person can leave the house before there rents runs out.

Sometimes, many people pay advance rent for like month or so and after week, they change their mind and now they want to leave this house and buy new house somwwhere else. So what currently happens that, that person just forget that he paid rent and just buy new house and let the old house go away till rent runs out.

what if a person can just ask for upcoming week and leave the house forever. 

how this will work?
We can add option of maybe "RENT OUT" or maybe "CHeck Out " , any term that relate to this think and if company owner approve it then they get refund of upcoming weeks and house gets empty. 
only upcoming week rent can be refunded and not of the week running. 

For example:
A person bought house on 1/01/24 and paid rent for 3 weeks.
Now if he want to leave house early then he is apply for early leaving of house and get refund of next weeks ut not of 1st week that is running ( from 1/01/24 to 7/01/24)

### Reason

As mentioned above , people change their mind after buying the house. sometimes even after a day or two , people tell that i want to shift to another place, i dont like this house now.

**Comment by zyronex** [comment]
If I'm someone who changes their mind easily, I simply wouldn't pay rent this far in advance, however, if I like the peace of mind of not having to pay rent every week, then I'd pay several months in advance. I don't think it would be fair to take money away from a realtor simply because I can't make up my mind. I think this is one of those situations where you have to live with your choice.

**Comment by King2704** [comment]
I like the basic Idea of the suggestion which would be allowing people to leave their houses early but I don't think people should get the money back that they paid in advance. This could be done through roleplay if people want to ask the realtor to get the remaining weeks back but with the current system, it would take the money out of the realtor's company account which I don't think is a good idea.

**Comment by coalaura** [comment]
yeah just dontg pay rent, i dont think we need a whole new system just so one person can change their mind
