### ISSUE TITLE
Suggestion - Change how /bill works

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3123]
### Assurance

I have read the `README.md`

### Summary

Due to the increase lately from people metagaming who blacked out individuals are/people with voice changers by /bill showing their steam name, I think it should be changed to just show the paypal. This will also reduce the amount of people being like "am i supposed to bill scufflord or coaluara"

I know player names were kept from being on there due to metagaming concerns, so I think these need to be scrubbed too.

### Reason

Because the majority of OP-FW servers are public and we can't trust the public not to metagame. With how hard metagaming is to prove most of the time, doing everything we can to prevent it out the gate is the best option.

**Comment by tiigerrlily** [comment]
agreed, have had a very uncomfortable few conversations before where they've asked "is it Lily" etc etc

**Comment by DaxterPancake** [comment]
I hate when people ask if they bill 'Daxter' it is super immersion breaking.

**Comment by HollaYalla** [comment]
Make it show their CID or even their characters Name

**Comment by DaxterPancake** [comment]
> Make it show their CID or even their characters Name

That wouldn't combat the metagaming portion of this idea.

**Comment by xplrerin** [comment]
Yea it needs to be changed, i changed my fivem name to “Maeve” to make billing more immersive but now i have asked people a question and they’ve straight up ignored me and just did /bill in my face and went “OH MAEVE!” It’s weird as hell
