### ISSUE TITLE
Suggestion - Buff Evidence Collecting 

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#3124]
### Assurance

I have read the `README.md`

### Summary

Make it a bigger range where you can collect casings. Makes it so the inventory isn't as flooding. 

Also can we re-add having the casing number at the bottom so duplicate casings can be filtered out easier? Used to be where you picked it up, you could see the number labeled on the bag before being processed. It still needs to be processed to be used in court but makes it 10x easier for organization sake. 

### Reason

Pressing E and waiting 30 minutes isn't fun and we also don't have the inventory space for 200su of PD equipment, up to 12 possible GSR printouts (for suspects down) and than 30+ casing bags sometimes when a good chunk of them are duplicates.

**Comment by coalaura** [comment]
> Make it a bigger range where you can collect casings

Range is already VERY big

> Also can we re-add having the casing number at the bottom so duplicate casings can be filtered out easier

No i intentionally removed them, cause it slightly defeated the point of processing if you know the serial number beforehand
