### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by XxErro404xX** [InZidiuZ/op-framework-issue-tracker#3127]
### Assurance

I have read the `README.md`

### Summary

You guys can change the job giving system that we are using right now ,that will help us all.
You guys can make a system that will allow all business ( reapir shop ,beanmachine ,Gw etc ) owners to give job to the new unemployed employees by using commands or anything. 

### Reason

Right now we just have to wait until the Admin gives the job from the Admin pannel. And it Takes usually 24 hours in the server I am playing( Legacy Roleplay Bangladesh ). And I just faced this problem massively..I applied for reapir shop job 2 days before,,The owner also created job giving request. But its going to be 3 days but no one has got their jobs/keys. I contact the support team, they told me one of their admin usually does the job giving work and he is in LOA that's why we are not getting the job/keys. And we have to wait until his LOA ends.. You say, is this a proper system?? 
so I am hoping that you brilliant guys will make new scripts that will make our RP experience better as you guys did before...<3

**Comment by coalaura** [comment]
that sounds more of a staff issue not a dev issue, this will not be changed
