### ISSUE TITLE
Bug report - All Text Showing Scripting Language

### ISSUE THREAD

**Issue by Punit4646** [InZidiuZ/op-framework-issue-tracker#3129]
### Assurance

I have read the `README.md`

### Reporter

LUCIFER(LUCIFER#5850)

### Summary

![Screenshot (49)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/f8b2d8fb-d91a-412c-8774-52738875579f)
![Screenshot (50)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/ba072649-9cca-44b5-bb63-48964f9057bb)
![Screenshot (51)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/bd4d77b7-3fe0-4ca2-87bd-c75f127cf754)
![Screenshot (52)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/d680312e-bee1-402b-999d-36054ff16449)

### Steps to Reproduce

![Screenshot (53)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/5db1e5c9-ea4e-432d-b3e0-15e2dda80f5a)

![Screenshot (54)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/6a4c735a-ec4a-4389-8895-0d2225101a5b)
![Screenshot (55)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/1c94f067-1563-4438-806d-0fe7f96975a5)

### Expected Behavior

![Screenshot (56)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/12e6eb70-c56f-406a-a57b-1208edb66e56)

### Actual Results

![Screenshot (46)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/7b9553c5-d2ac-46e4-9b38-26c1f55b4866)

### Screenshots/Videos

![Screenshot (43)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/b068c026-6911-4c42-b932-5c1518cdce4b)
![Screenshot (56)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/9b26aa42-dfe6-4ced-a2b3-fb7f9977a26a)
![Screenshot (43)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/4e0ee939-d787-4b2d-8d9b-bc92f78cb0eb)
![Screenshot (43)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/b02e14ab-b671-4bcf-b11e-7f3fe21177d6)
![Screenshot (44)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/1430b47e-203f-441c-b69e-fbb797d58842)
![Screenshot (44)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/8cd6f798-8fe0-40b7-bc21-97e8a8689f0d)
![Screenshot (44)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/778deea7-3169-42ee-9ded-9f2d09804994)
![Screenshot (45)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/9de08499-e52c-46c0-9f42-1ecc5f21f09f)
![Screenshot (45)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/07633a00-7b8c-4567-9ce5-ba3bdc722063)
![Screenshot (45)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/99940578/b0ffbbcf-7e70-4cc0-b8d3-c0a8d40a899c)

### Player Data

IN GAME NAME IS:- itsDjtime

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
this is cause the locale is not updated

**Comment by coalaura** [comment]
change to english (US)
