### ISSUE TITLE
Bug with airplane 

### ISSUE THREAD

**Issue by WennbergTV** [InZidiuZ/op-framework-issue-tracker#313]
**Reporter:**
wANKBERG#4556
https://steamcommunity.com/id/WennbergLucas

**Summary:**
Did the mission where you rent a plane to pick up a delivery in the ocean. I payed for the plane but upon arriving at the scene didn't recieve my delivered item nor did the game let me get back in to my plane.

**Steps to Reproduce:**
Just rent the plane, head to the location given and try to get back in the plane...

**Expected Results:**
To fly over there, jump out, pick up the package, get back in the plane and fly back.

**Actual Results:**
I flew there fine, but upon arriving I did not recieve anything from the crate nor could I get back in the plane. It wouldnt let me unlock it.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1200

**Player Data:**
Character ID: 6386

**Notes:**
I lost quite alot of stuff, but I am hoping that these pictures will help with solving these issues!

**Comment by WennbergTV** [comment]
https://i.imgur.com/QuStKsj.png

https://i.imgur.com/uOE8faI.png

**Comment by capsure** [comment]
Why did you get out of the plane?

**Comment by WennbergTV** [comment]
> Why did you get out of the plane?

I thought you had to get out of the plane to pick up the crate?

**Comment by iGreatWhite** [comment]
You can grab the package from the plane as getting out makes it very difficult to get back into the plane. For future runs try to find a way to grab the package from the driver seat of the plane.

**Comment by InZidiuZ** [comment]
Hey,

Not sure what the issue is, possibly a GTA one. Just don't get out though, you're not supposed to.

**InZidiuZ**
*OP-FW Developer*
