### ISSUE TITLE
Suggestion - parking brake

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3130]
### Assurance

I have read the `README.md`

### Summary

through a combo keybind of perhaps ALT + Space allow the user to pull their parking brake, locking the car in place when at a stop and the engine is off. This will allow people to park in areas that when they're in the car stationary, the car doesn't move, but once they get out it will start rolling

### Reason

I'm tired of getting run over by my own car while picking mushrooms or doing treasure maps on the side of a mountain

**Comment by coalaura** [comment]
thats what happens if you just hold the handbrake for a moment
