### ISSUE TITLE
SIlent the Phone Mode

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3131]
### Assurance

I have read the `README.md`

### Summary

So Idea is adding a slient mode in for phone. 

Generally we toggle power off the phone when we are doing meeting in rp and doont want get disturbed but it completelly power off phone and we cant use other apps..

Adding silent mode will the silent the ringtone of incoming phone calls and maybe also mute notifications sounds while having access to phone. 

The silent mode can turn off when we rejoin server as sometimes people may forget that they have muted their phone

### Reason

Making phone more functional

**Comment by coalaura** [comment]
done

![yes](https://i.shrt.day/LCII4VTNJ9.png)
