### ISSUE TITLE
Suggestion - Saving a vehicle tune

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#3133]
### Assurance

I have read the `README.md`

### Summary

With the new Tuner chip, it would be cool if you could save a tune and give it a name so that the next time you want to tune the car you can select that tune from a drop-down menu and easily apply it.

To not make it too convenient it could be limited to only 3-5 saved tunes max
Could also make it take longer to apply so you can't just hop in a car and apply it in seconds
![tunerchip](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/93887575/cc29d4f0-35dc-4294-9c81-b82054e8b21a)

### Reason

- It would save the taking screenshots and looking for the tunes in discord
- With the tuner chip just getting an overhaul this feature would be a good addition

**Comment by coalaura** [comment]
![ugh](https://cdn.discordapp.com/emojis/1158051354095390780.webp?size=128&quality=lossless)

**Comment by coalaura** [comment]
You can now save, load and delete tunes with a custom alphanumeric name. It also stores and shows the model name of the car that you saved the tune for.
