### ISSUE TITLE
Suggestion - Make jobs require the player to do something more than "Press E"

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3134]
### Assurance

I have read the `README.md`

### Summary

With the exception of Trash, Trucking and Postal. A lot of jobs (Mainly speaking for mechanic experience) is just stand in a spot, press a button or type something and wait.

My suggestion is to make the player have to do something to actually do the job.

Examples:

**For the tow job**:

Rather than just "/tow" make the player have to:
 1. Get the tow hook
 2. Attach to the car 
 3. Start the winch to get the car on the back of the truck
 4. Strap the wheels in place

**For Burger Shot**
Since I'm not 100% sure if they have to do more than press E in a few places to cook things this is just what I think would be cool.

For Burgers:
Similar to cooking meat after hunting where they can flip the burger.
Additionally allow for building custom burgers do allow for more RP around this.

**For Mechanics**

Rather than "Press G to repair engine" maybe have it so you have to check highlighted areas of an engine to fix them, with the higher damage having more things to check.

Similar things could be done for Crafting and breaking down of items, Tuner shop tuning / customisation etc.

### Reason

Having jobs be more than "Press Button and wait" would make people more interested in the jobs and could lead to improved RP.
Eg Burger shot could have more that 2 kinds of burgers, etc...

**Comment by coalaura** [comment]
People already complained when cooking burgers was 10 seconds instead of 5 seconds, then they complained it was still taking too long, so now you can cook 6 patties at a time.

Although i think the idea is cool, not only would this take a lot of work to rework the interactions for like 7+ jobs, but i also think currently this would not work
