### ISSUE TITLE
Housing contracts

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3136]
### Assurance

I have read the `README.md`

### Summary

24 rental agreements - 24 hours to accept or deny

### Reason

It would be done the same way except you can set it to last up to 24 hours, can help and improve the reality job,

**Comment by SluggsV2** [comment]
There could be a section under the purchases tab called “pending” and you could go there to accept or deny

**Comment by ayushpatel1007** [comment]
Housing contracts are more of rp between Realtors and DOJ/State. Can’t we just don’t have agreements/contracts. Anyways realtors are already paying maintance.

And if still want to keep it , then we have have 2 week contracts with option for single week contracts also. We can directly pay from /comp from anyplace and anywhere

**Comment by SluggsV2** [comment]
I was thinking of also, 

adding in the new “pending” category under the Purchases tab, realtors can send their renters, Weekly Rent changes, 24 hours to accept or deny price change, (more or less to make it cheaper for the renter) I came up with an idea of changing rent for good and long term renters down the road, say lowering their rent by 1000 monthly or so
