### ISSUE TITLE
Suggestion - Bullet hit sound of hitting someone through car is same as that of hitting the car

### ISSUE THREAD

**Issue by namnanaman** [InZidiuZ/op-framework-issue-tracker#3138]
### Assurance

I have read the `README.md`

### Summary

I think hit mark sound of hitting the car and hitting someone in the car should be different. 
I dont know if it is core GTA thing or done by RP devs , 
If we look at other games like COD and battlefield , and far cry for example the sound is different although they are different genre game.

### Reason

I think this change will add more clarity if you hit someone in the car or its just you hitting the car,
I can be wrong here , but after playing many fps games where vehicle is involved like warzone n others where the sound is different I think adding this to RP will enhance the quality of fights and people will grind their aim in a different.

**Comment by coalaura** [comment]
thats base gta
