### ISSUE TITLE
Suggestion - 5th seat hop out (cop nerf oh my god how could I do this) 

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3139]
### Assurance

I have read the `README.md`

### Summary

With a lot of vehicles in the framework having additional seats added by northbayjoe, the problem has popped up where people are using those seats on both cop side and criminal side as a way to instantly hop out of the car and start shooting/tasing people. I believe that if we were to add either a short 1.5s freeze of a character ped if they exit the vehicle that way (roughly how long i think it takes to normally exit a vehicle). That way if you have a bunch of people in say a suburban sitting in seats 5, 6, 7, and 8, they can't just instantly hop out with two handers and start spraying faster than someone would normally be able to do that.

### Reason

Stops people from abusing this for PVP reasons and levels the playing field.

**Comment by Skai97** [comment]
As much as I dislike the seat 5 insta hop outs. It created a meta even during wars that people had to use cars with seat 5. 

If a freeze was added to people exiting the vehicles in a lot of scenarios basically just asking to be shot. Most people won't respect the "freeze" time to kill is so high that person would be just dead 9\10 times in a shoot out scenario. 

Same kinda issue when people watch elevators and shoot before loading screens are even completed

**Comment by scufflord** [comment]
It's not so much something that they need to "respect" as shooting during the freeze would be no different than getting shot while still in the animation of getting out of your car, which happens a lot as well. That's why I was wanting to time it to be roughly the same length as however long that animation is.

**Comment by ImArteria** [comment]
Why do a freeze when you could just put a timer on that seat? Also cop nerf is an L I thought you knew better

**Comment by coalaura** [comment]
![ye](https://i.shrt.day/3RIQW4GE5K.png)
