### ISSUE TITLE
Houses

### ISSUE THREAD

**Issue by iHexa** [InZidiuZ/op-framework-issue-tracker#314]
**Name:**
Kyle. aka Hexa#7168

**Summary:**
My suggestion is about buying a house! A house would be great instead of paying the motel every week.

**Reason:**
Well, we all know that we are in need of a house system in the server. Where we can change our clothes, store our stuff or feel safe. Maybe we can invite in our friends and drink some stuff. (some functionality would be good inside the house. Like drinking or watching tv. Taking a nap which takes the stress off you). There should be high-end houses as well as some shitty houses that go for some low amount of money.

**Comment by InZidiuZ** [comment]
Hey,

Please check the [Trello](https://trello.com/b/PuHkmQx3/op-framework-development), this is already planned.

**InZidiuZ**
*OP-FW Devleoper*
