### ISSUE TITLE
Scratch tickets! 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3140]
### Assurance

I have read the `README.md`

### Summary

Scratch tickets, an addition to lottery, jackpot and casino

### Reason

There would be say 5 level of them 
100$, 250$, 500$, 1000$, 5000$

there would be a max prize on each working much like todays world! Could be fun!

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/55801UXU15.png)

![yes](https://i.shrt.day/19SO7J67JO.png)
