### ISSUE TITLE
Suggestion - Green Wonderland Parking

### ISSUE THREAD

**Issue by npxfoulgming** [InZidiuZ/op-framework-issue-tracker#3141]
### Assurance

I have read the `README.md`

### Summary

we all know there is no any parking near Green Wonderland that why the worker of wonderland facing little bit problem of storing their car. Please add the parking just like burgershot , arcadebar and the bean machine.

### Reason

As the worker of wonderland need parking to secure their vehicle and to provide home delivery if the customer order due the far parking it's not possible to do that why we need parking which can access by wonderland worker only.

**Comment by coalaura** [comment]
done

![yes](https://i.shrt.day/8T398XXO5N.png)
