### ISSUE TITLE
Suggestion - Ability to opt out of daily activities (such as illegal ones)

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3142]
### Assurance

I have read the `README.md`

### Summary

I would be nice to have the option to opt out of specific daily activities such as "Arena Based Activities", "Treasure Map Activities", "Zombie Pill Activities", "Time Trial Activities", "Diving Actives"  etc for players who do not want to do this and don't want to spend on potentially multiple re-rolls.

Additionally a generic "Illegal activates" opt out would be beneficial for legal players 

Additionally, players could opt back in if they wished too. 

To Prevent abuse, this would only apply the next time your activities are generate (Either by waiting until the following day, or manually re-rolling)

### Reason

It would make daily activities more personal to the player rather than seeing them and deciding not to do one because they don't want to keep spending 1k per re-roll to get away from activities they don't like, which may end up costing more than the reward for something they end up doing

**Comment by King2704** [comment]
The reroll feature was added to give the player the ability to opt out of doing those tasks, people would just opt out of everything other then visit "certain place" and then speedrun them in 5min to get max profit.

**Comment by MetaHatter** [comment]
Opting out of Illegal activities I agree with (should also remove the chance of getting an illegal item as a reward)

All others can use reroll imho...

**Comment by coalaura** [comment]
defeats the point if i can just opt out of the difficult ones and just do the easy ones

**Comment by ThatSinisterGuy** [comment]
I agree with the sentiment that it makes little sense to ask civ/emergency characters to perform illegal tasks for the daily. It would be nice, as suggested by MetaHatter, to be able to opt out of illegal activities. Maybe make this on option that can only be changed every 7 days to avoid abuse of it? I know there's the reroll, but that's basically saying if you're not crim then you have to accept your dailies are going to be more expensive, which seems a little unfair.

**Comment by BaronVonSnergerberger** [comment]
Maybe you could tie the 'opt-out' function into the daily streak? Since right now the only point to even continue after 30 is the car, for those of us with exceptionally bad luck like myself at 193 day streak....maybe having the ability to opt out of 1 type of daily (ie not getting arena kills anymore as an option every 50/100 days+) would give another bonus to keeping it going?
