### ISSUE TITLE
Suggestion - Vape Flavors/Brands

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3144]
### Assurance

I have read the `README.md`

### Summary

I love how we have our vapes but I feel that we need different flavors and different brands to spice things up, so I thought we could add 6 flavors and they all either have side effects or relieve more stress

Banana
Strawberry
Menthol
Vanilla
Burgershot
BeanMachine

With these Flavors it adds the ability to refill your own vapes and you could get a small bottle (single use) or a big bottle (4 uses) all sold at GW but just allows you to not have multiple vapes just one vape with different juices for refilling.

Maybe add brands such as
DrFrog (knockoff MrFog)
Elfy (Elfbar)
The one we have now

Maybe different models aswell
A Box Mod gives a bigger radius smoke but goes quicker as it needs more juice

One we have now (doesn't change)

Vape Pen (Almost No Smoke and only reduces your stress)

### Reason

More Vape Flavors and adds the ability to refill them yourself

**Comment by coalaura** [comment]
I don't think we need this many different variants of vapes that all do the same thing. However i do like the idea of different flavors.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/0INDZ9F7GB.png)

![yes](https://i.shrt.day/HDHE47LL9I.png)

**Comment by coalaura** [comment]
If it would be possible i would change the color of the smoke but thats sadly a limitation within gta
