### ISSUE TITLE
Suggestion - state employee job garage

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3146]
### Assurance

I have read the `README.md`

### Summary

Add a garage outside of the governor's office at Maze Bank that all state employees including security are able to park their personal vehicles in when at the office doing their work.

### Reason

Due to the influx of tow drivers due to the international server adding towing to Life Invader we have had an increase of employees vehicles being towed for no reason while they're attempting to do state work.

**Comment by ThatSinisterGuy** [comment]
Personally I feel that making tow a public job was a big mistake. Tow is an easily abusable job, and we're seeing exactly this, at the expense of players. It makes sense to have it a public job on whitelisted servers, as there's already a vetting process, but on an open server like Legacy I believe we need the vetting of the mechanic shop owners. I get that opening tow was trying to solve a problem of no tows being available, but I think this was not the best way to approach it. Now people are left chasing for solutions to problems that didn't need to be there.

**Comment by TacticalTyl3r** [comment]
> Add a garage outside of the governor's office at Maze Bank that all state employees including security are able to park their personal vehicles in when at the office doing their work.

I would say put it down below in one of the side places since it makes sense for a garage to be there instead of right outside. 

@ThatSinisterGuy that is a Server Config that is placed by the server manager. You would have to talk with that server/staff. It can be enabled/disabled per each server under the framework.

**Comment by coalaura** [comment]
It does say no parking

![yes](https://i.shrt.day/E0AFAO1S7D.png)

**Comment by coalaura** [comment]
here you go (until i find a nicer spot for it)

![yes](https://i.shrt.day/KQNNPO0DYC.png)
