### ISSUE TITLE
Suggestion - Locals performance issues

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3147]
### Assurance

I have read the `README.md`

### Summary

Turn the local population back down to whatever it was before or just reduce it

### Reason

We've had a global slowdown and recently the local population has been turned up. The server issues have been terrible. Ground randomly disappearing more than ever. 

Random invisible objects appear that have collision 
floating locals
ghost locals are the worst I've ever seen
Locals are coded to turn into you as base gta but legacy has these random locals that become solid walls when you hit them which have gotten worse. 

More locals to bubble. Chases on both PD and Crim side right now feel like luck hoping that locals take PD out or you dont get taken out yourself.

**Comment by joevapes3** [comment]
yah it's been terrible since the increase

**Comment by InZidiuZ** [comment]
There hasn't been any increase. The thing that most likely caused this, was an attempt to force the game to fill population more consistently. The issue of there not being peds at Vinewood sometimes, and other times it being SUPER full was one of the reasons this was done. Also, roads sometimes being completely empty too.

It is often a bad idea to try to go against the game in this way though, so it was only experimental. I just checked out the live server as well, and the problem it meant to resolve seems to be still happening, so I will undo it.
