### ISSUE TITLE
Suggestion - Burger Shot Toys

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3148]
### Assurance

I have read the `README.md`

### Summary

Would love to introduce a collectable meal to Burger Shot to just add spice to the RP there. 

The meal would work like this: 
Meal Price: $1,200
Breakdown:
Toy: $750
Food: 4 Burgers, 2 Fries, 4 Coke/Pepsi, 2 Shakes

Toys would work similarly to how the 945 Studios Card Packs work. 
Toys would come boxed and each toy would have a different gambling percentage to come out. 

Sample Probability / Toy Choices

Lowest Probability (Chance of Winning: 1/64) Toy: https://forge.plebmasters.de/objects/ch_prop_princess_robo_plush_07a
Middle Probability (Chance of Winning: 12/64) Toy: https://forge.plebmasters.de/objects/ch_prop_arcade_claw_plush_04a or https://forge.plebmasters.de/objects/ch_prop_arcade_claw_plush_01a
Highest Probability (Chance of Winning: 51/64) Toy: https://forge.plebmasters.de/objects/sum_prop_sum_arcade_plush_06a or https://forge.plebmasters.de/objects/ch_prop_arcade_claw_plush_03a

### Reason

Improve the RP inside the restaurant itself by offering something that they can only pick up in the store. 
Would keep people coming back with the gambling factor of trying to get the "best" toy. 
Just in general something that would get people talking.

**Comment by antihero6713** [comment]
I kinda like this

**Comment by MADxxVIKING** [comment]
Great idea!!

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/YM7R6OAUBS.webp)
