### ISSUE TITLE
Suggestion - Move Bigger Electronics to Digital Dens

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3149]
### Assurance

I have read the `README.md`

### Summary

Move the larger electronics to a electronic based shop

Items: 
Smart Watch
Tablet
GPS
Self Driving Chip
Boombox
Microphone Stand
Photo Camera
TV Stand
TV Remote

Location Options:
Mirror Park: 
https://cdn.discordapp.com/attachments/987550018154156092/1196601303351181445/image.png?ex=65b838ce&is=65a5c3ce&hm=3e465b11d4d8e5aed4b42e46c0dd688716e1ec990ad5f0aa2661bfb8c152b082&
vector4(1144.99, -475.05, 65.97, 80.69)

Little Seoul #1: 
https://cdn.discordapp.com/attachments/987550018154156092/1196603338016444596/image.png?ex=65b83ab3&is=65a5c5b3&hm=c0d2e46d5568186c00277167e4f7f0fe15b25ab9ce2f4f8d0f3222843286bdb8&
vector4(-594.27, -1138.15, 21.76, 94.18)

Little Seoul #2
https://cdn.discordapp.com/attachments/987550018154156092/1196603669966233741/image.png?ex=65b83b02&is=65a5c602&hm=44ff8c8103af324a73679bf3247e610443219f8ec23db235cf9d3234c8e1a644&
vector4(-647.86, -858.66, 24.08, 175.36)

### Reason

Just overall it makes no sense in RP to get some of these larger items from a gas station and well move one to a more fitting shop might as well move the rest.

**Comment by scufflord** [comment]
I would go so far as to say all electronics. Cell phones, radios etc.

**Comment by MADxxVIKING** [comment]
I'd second Scuffs comment. Moving all electronics to the Digital Dens. However this idea in general is great.

**Comment by Kay32** [comment]
I thought about those as well. But also thought about telling new people about them not being everywhere.

**Comment by coalaura** [comment]
done

**Comment by coalaura** [comment]
i left phones and radios since those are more essential items everyone should have easy access to
