### ISSUE TITLE
Robbery suggestion

### ISSUE THREAD

**Issue by iHexa** [InZidiuZ/op-framework-issue-tracker#315]
**Name:**
Kyle. Hexa#7168

**Summary:**
Buffing the robbery pay/amount of cops you need to rob.

**Reason:**
Basically, we get around 20k - 25k for bank robberies. Cmon, legion bank and there are 5 cops responding to it. The bank should give at least 40-50k with the current economy. Or at least reduce the minimum amount of cops needing to rob the bank. Because you got to rob it with at least 4 people or let's say 3. And when you get 20 k, it's only 6k each and if it's a well-planned robbery you already spend 5k on the stuff you need. Body armors and stuff. Rping a robbery is actually good when both criminals and cops are doing it properly. But at this time it is not worth robbing it or actually having a good plane on it.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be adjusted. Most likely in the future, but I want more places to spend the money first, like housing, materials, etc.

**InZidiuZ**
*OP-FW Devleoper*
