### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by kal3blol** [InZidiuZ/op-framework-issue-tracker#3150]
### Assurance

I have read the `README.md`

### Summary

I'd like to do a enhancement to the drive-by experience on the OP-FW. The addition of a custom drive-by script could add depth and engagement to the gameplay. 

| There should be a drive by script, while someone is driving the passengers could sit on the windows and shoot out while sitting out of the vehicle. But it should be where the passengers can't shoot out with any gun, it should be any kind of pistol and the smg's you could already shoot out the vehicles. 

| Here is a example: https://www.youtube.com/watch?v=NTQeM6AauYo

### Reason

 I feel like this would add a difference from every other FiveM city and add immersion to the RP experience.

**Comment by HollaYalla** [comment]
I am going to put this out here most likely not as we can shoot now with pistols but we removed SMGS and ars from being able to be shot inside a vehicle for mainly the pds sake so robbers can’t have 4 people shooting full auto at solo driving cops also this could cause a lot of RDM then claimed as a “drive by” with no rp interaction beforehand so it would be a huge gray area

**Comment by coalaura** [comment]
Yeah i dont think this would bring good RP
