### ISSUE TITLE
Suggestion - PD/EMS Vehicle Megaphone

### ISSUE THREAD

**Issue by SharkyBarkyyy** [InZidiuZ/op-framework-issue-tracker#3151]
### Assurance

I have read the `README.md`

### Summary

Suggestion: Add A Loudspeaker / Intercom / Megaphone / PA System To First Response Vehicles 

Example: https://youtu.be/L-b4pVMu8QI?si=WEaDD7OrCWWL8Gfo&t=22

### Reason

Adding a loudspeaker or PA system to the first response vehicle could open a whole new type of RP, let alone heavily assist in PD, BCFD, EMS etc.'s response to calls and traffic stops.

When a local call for EMS comes and we cannot find the patient, we may use the PA system to locate them.

PD can use their PA system to interact with people without exiting their car, conduct traffic stops, etc.

BCFD can have long-range contact with victims involved in fires via their PA system.

The list goes on, and I feel this would help with RP and the general quality of life for first responders in the city.

**Comment by coalaura** [comment]
Emergency vehicles now have a built-in PA system. While in an emergency vehicle and in the driver or passenger seat you will have a new "PA" indicator next to the OIL and BELT indicator. You use your normal push to talk but if you also hold down shift while talking it will enable the PA system

**Comment by SharkyBarkyyy** [comment]
> Emergency vehicles now have a built-in PA system. While in an emergency vehicle and in the driver or passenger seat you will have a new "PA" indicator next to the OIL and BELT indicator. You use your normal push to talk but if you also hold down shift while talking it will enable the PA system

I appreciate you and thank you for accepting this suggestion have a fantastic day and a beloved time <3
