### ISSUE TITLE
Mansions with sliding gates 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3152]
### Assurance

I have read the `README.md`

### Summary

Some mansions located in the hills or by Micheal’s, have sliding gates protecting their entrance, could we allow home owners to lock those gates, 

### Reason

For example I’m trying to throw a party, would be cool if I could toss a lock the gate so no cars get towed or anything,

**Comment by coalaura** [comment]
No i dont think that is needed. It would require a good bit of work to extend the door system just so a few people can lock their gate once in a blue moon
