### ISSUE TITLE
Bug report - CAD showing vin is not Registered of Owned Vehicles

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#3153]
### Assurance

I have read the `README.md`

### Reporter

ravicant

### Summary

If You will try to look vin of any owned vhicles from cop and then search that specfic Vin number it shows vin is not registered.

### Steps to Reproduce

1. From your cop character takout any owned car ( owned by anyone )
2. do /vin
3. then copy vin and do /vin_lookup with the copied vin number
4. it will show the result

### Expected Behavior

its should say Vin number is registered for owned vehicle and not registered for Vin-scrached vehicles

### Actual Results

it always says vin is not registered for any vehicles 

### Player Data

Character-ID: 2
Job Data: Law Enforcement / SASP / Chief
Licenses: hunting

Timestamp - 2024-01-16 14:51:01

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
