### ISSUE TITLE
Suggestion - change loot table for trash a bit

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3154]
### Assurance

I have read the `README.md`

### Summary

Been doing some trash runs today and kept getting a bunch of vintages, pistol 45's and SNS pistols. Like, way too many. After thinking about it, it's a bit strange to be finding perfectly brand new pistols in the trash so here's my idea: replace the current ammunation guns in the trash runs loot table with some of the very low tier crim guns like the sig sauer p226, endurance, d&p9 etc that are decayed to between 40-60% left on them. This would provide a logical step for criminal people to move to guns that you can't just get at ammunation, and allows for additional roleplay with legal characters being able to turn these over to PD. 

### Reason

Because as much as I like the dopamine hit from getting an item pop up on my screen, I think adding this as a cool roleplay element would be dope compared to what we have now.

**Comment by coalaura** [comment]
done something like that, however i dont like changing it too much since the idea is that you do multiple jobs not just garbage
