### ISSUE TITLE
Suggestion - Yelp Reviews

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3155]
### Assurance

I have read the `README.md`

### Summary

Add an app, probably Yelp, where people can review businesses.
They can leave fake reviews, real ones, and each place will get a rating.
Allow people to add comments, their rating out of 5, and an agree or disagree button so others can react to it.

### Reason

Instead of people just doing it on twitter, a specific place for each business to have it's own reviews.
This will help the management team deal with any customer service issues, or if some staff are working really hard. It will be like a feedback place, but a lot more open to everyone and easier accessible.
Management team will have to have meetings based on how to improve their rating, to improve the feedback

**Comment by coalaura** [comment]
I don't think this is needed, yellowpages i can get behind but i've never seen someone actually review a business

**Comment by txxlrrsCoding** [comment]
Not as often, but it does happen. And it would be cool to see it start happening

**Comment by MetaHatter** [comment]
This would likely degenerate into who can 1 star and review bomb the people/businesses they don't like the fastest.
