### ISSUE TITLE
Bug report - using a repair kit bugs the character

### ISSUE THREAD

**Issue by 1M6host** [InZidiuZ/op-framework-issue-tracker#3156]
### Assurance

I have read the `README.md`

### Reporter

1M6host

### Summary

using a advanced repair kit on accident while driving bugs the character's ability to use any other item 

### Steps to Reproduce

1. put your repair kit on one of your fingertips,
2. Get into a vehicle and press that fingertip,
3. now try to draw a weapon, use a lockpick or use a food item
4. you can also verify this by trying to fuel your vehicle at a gas station as it says" you are already busy doing something else"

### Expected Behavior

nothing should happen

### Actual Results

it bugged the character's ability to use any item

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
fixed

**Comment by 1M6host** [comment]
not yet fixed on the Indian servers
