### ISSUE TITLE
Suggestion - access to sub-10 radio frequencies for state employees, managers, governor, and security

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3157]
### Assurance

I have read the `README.md`

### Summary

Due to recent roleplay that we've had with SWAT our state security team on the international server is moving towards having a more comprehensive model for our SOPs. As part of this, access to sub-10 frequencies to be able to work hand-offs with SWAT as necessary. Given that these are trusted positions and not handed out willy-nilly there would be no risk of it being abused

### Reason

For the roleplay

**Comment by ImArteria** [comment]
Nah fuck dat you havent seen the corrupt state in the FIB discord lmao

**Comment by scufflord** [comment]
> Nah fuck dat you havent seen the corrupt state in the FIB discord lmao

Excuse me sir I'm a good FIB informant, I tell Killbourne everything

**Comment by ImArteria** [comment]
> > Nah fuck dat you havent seen the corrupt state in the FIB discord lmao
> 
> Excuse me sir I'm a good FIB informant, I tell Killbourne everything

No document = not real.

On a real I dont think its a good idea to give all channels though. Maybe like 9-10 would be okay but imo it doesn't really make sense for state to be listening in on PD coms/EMS coms or whatnot.

**Comment by scufflord** [comment]
We're essentially trying to get it to a point where if a situation arises where we need to do a hand-off or seek police assistance for a code black type of situation it could be a click over to 1, or pd clicks over to our frequency to handle the situation. This is actually something that's being requested in roleplay from the PD side so they can easier assist us.

**Comment by MADxxVIKING** [comment]
Yes, this isn't without RP reason - SWAT has mentioned to "State Security" that if State could get funding for new radios to be able to access a channel of their own in sub-10, and access PD's for code black situations, this would be great. State has to change radios already when letting go of people, its also a very private and important job regardless. State Security being the "Secret Service" of State and of Legacy would ideally have access to a protected radio channel regardless. Lots of RP ongoing where higher ranking members of SWAT, FIB, and State Security are working together to build better relationships, do cross-trainings, and set up State Security to be its own small state agency.

**Comment by coalaura** [comment]
Yeah they are not getting the pd or EMS radio, however i am down to give access to channel 10 and maybe 9 so there is some overlap that can be used by both

**Comment by scufflord** [comment]
I believe 9 is currently in use on the international server as a training channel for either PD or EMS

**Comment by Dinomasen** [comment]
6 might be the best as its not used by any on international

**Comment by coalaura** [comment]
They can use a different frequency, i'll make 9 the overlap and leave 10 since that doesn't seem to be encrypted rn anyways

**Comment by scufflord** [comment]
Perfect. 9 would work because then we can just ping the PD line with CODE BLACK and then they can swap over

**Comment by MADxxVIKING** [comment]
> Perfect. 9 would work because then we can just ping the PD line with CODE BLACK and then they can swap over

Exactly. I think that's great actually.

**Comment by coalaura** [comment]
okay Government/State/* now has access to frequency 9.00 - 9.99, you can use the channel for day to day use too so you dont have to switch radios when letting people go like you mentioned

**Comment by CloudCait** [comment]
give ruby a panic button lmaooo
