### ISSUE TITLE
Bug report - Boombox not working 

### ISSUE THREAD

**Issue by Shubham-426** [InZidiuZ/op-framework-issue-tracker#3158]
### Assurance

I have read the `README.md`

### Reporter

Shubham-426

### Summary

Music is not playing in Boombox not a single music is playing

### Steps to Reproduce

Please fix it 

### Expected Behavior

The boombox to fixed all songs must be played 

### Actual Results

Boombox not working right now it should work 

### Screenshots/Videos

No

### Game Resolution

1920*1080

### Player Data

CID-8682

### Server

India (c8s1.op-framework.com)

**Comment by InZidiuZ** [comment]
This issue has since been resolved.
