### ISSUE TITLE
Bug report - Random NPC spawning with player's car

### ISSUE THREAD

**Issue by 1M6host** [InZidiuZ/op-framework-issue-tracker#3159]
### Assurance

I have read the `README.md`

### Reporter

1M6host

### Summary

 it's been a very long and persistent issue present in the game. In Paleto, NPC likes to steal and take your vehicle for a ride. wastes time.

### Steps to Reproduce

just buy a house on Paleto Block, and let a car stay in your garage for about 3-4 days, when you take your vehicle out of it a random NPC drives it and is never to be found 

### Expected Behavior

nothing should happen

### Actual Results

NPC spawns with the car

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
should be fixed now i think

**Comment by 1M6host** [comment]
how long it generally takes to be merged with the prod code. if possible, could I have the ref commit id for the fix.

**Comment by coalaura** [comment]
> how long it generally takes to be merged with the prod code. if possible, could I have the ref commit id for the fix.

loook in the #build-updates channel in the opfw discord
