### ISSUE TITLE
Black market/Automatic weapons

### ISSUE THREAD

**Issue by iHexa** [InZidiuZ/op-framework-issue-tracker#316]
**Name:**
Kyle. Hexa#7168

**Summary:**
Adding a black market in the server where we can buy automatic weapons or weapons without requiring license would be hella good.

**Reason:**
Automatic weapon deals going around and illegal weapons around the city would be something awesome! As the people in the server, we are currently in need of automatic weapons. Because cops are always pulling out their ars no matters what. With the new weapons on back system would cause people carrying them on their cars or either not carrying them in the vehicle too. And that would scare people off carrying them everywhere..

**Comment by iGreatWhite** [comment]
There will be a crafting system implemented in the future that is on the Trello. Gun smithing is a part of this system, so he probably will not be adding a black market for automatic guns. I also really don’t see a huge need to have an automatic gun.

**Comment by InZidiuZ** [comment]
Hey,

Please check the [Trello](https://trello.com/b/PuHkmQx3/op-framework-development), this is already planned.

**InZidiuZ**
*OP-FW Devleoper*
