### ISSUE TITLE
Suggestion - add tablet games to queue screen

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3160]
### Assurance

I have read the `README.md`

### Summary

Could be something fun to kill the time while "stuck on the train" if you could just toggle the same script via a button to play some games while you wait.

### Reason

Gives people something to do besides screenshotting and staring at a queue.

**Comment by coalaura** [comment]
i mean you can play all those games online and making them work in the queue would require copying them and stuff, generally dont think its worth all the effort
