### ISSUE TITLE
Suggestion - Banham Canyon 2 fixes

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3161]
### Assurance

I have read the `README.md`

### Summary

Currently the front door position is backwards so when you exit the house you are facing the door. There is not a backdoor on this property despite external ones being present, and the garage is awkwardly positioned inside of a bush and spawns cars backwards. We were hoping to get the front door fixed, have one of the doors on the back of the property turned into a working back door for the Michael's interior, and to move the garage spawner to the other side of the garage door, closer to the stairs, so that the cars will spawn with the front facing the road.

Location on map:
https://cdn.discordapp.com/attachments/1057850240553717830/1197770154596114482/image.png

Current garage location, would like it moved to where the man in the white shirt is standing if possible and have cars spawn facing the road:

https://cdn.discordapp.com/attachments/1057850240553717830/1197770155153948702/image.png

Front shot showing how far of a run it currently is from the garage, up the stairs, and to the front door: 

https://cdn.discordapp.com/attachments/1057850240553717830/1197770156038955149/image.png

Potential Back Door locations, not that this place has a nice back yard lol

https://cdn.discordapp.com/attachments/1057850240553717830/1197770156429017220/image.png

### Reason

On the international server this house was recently picked up by the state team as a residence for a few state workers. Adding these QOL fixes and changes would be beneficial to this house and our ability to use it as an off-site office/home.

**Comment by coalaura** [comment]
Fixed the incorrect headings. I've already previously said no to moving the garages. Banham canyon 2 intentionally has no back door, the one you mentioned is the back door for Banham Canyon 1

**Comment by scufflord** [comment]
Oh I wasn't aware we lived in a duplex... Time to re-negotiate rent for having neighbors I guess LMFAO

**Comment by coalaura** [comment]
banham canyon 1 is the lower door and 2 is the upper door
