### ISSUE TITLE
Suggestion - Mountable / Placeable cameras for 3rd person recording

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3162]
### Assurance

I have read the `README.md`

### Summary

Add a camera which can be placed on the ground (with a tripod or something), that allows us to record / take pictures from a distance. 

### Reason

This will be good for the ones who don't have a good enough PC to stream & get access to freecam, and it will also be good for certain things like photographers, police interrogations, group selfies. It will be good to RP with. Similar to the mic stand.

**Comment by coalaura** [comment]
There is something like that already but its limited to PD, the reason freecam is not available for everyone is since it can be abused quite easily, same goes for this

**Comment by txxlrrsCoding** [comment]
> There is something like that already but its limited to PD, the reason freecam is not available for everyone is since it can be abused quite easily, same goes for this

I see how freecam can be easily abused, but not so much with this. Simply just place it down, and then have a small remote / device that you can either press record or picture. Give it a 5s countdown before it starts to do anything. (This will already reduce how easily it can be abused)
And, to make it less *abuseable*, make it have very fine adjustments so people can't use it for anything or powergamey.65
