### ISSUE TITLE
Suggestion - prospecting license

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3164]
### Assurance

I have read the `README.md`

### Summary

Add a prospecting license option to go hand-in-hand with the mining license as an advanced course for State to be able to offer about prospecting gems before mining to analyze them and try to stablize them. When the player has this license, and thus the IC knowledge, and a magnifying glass in their inventory they are able to analyze the rock for a "better method of drilling" and it will bump that rock down one risk level.

Something else that could be tied into this license, and thus increase the possibility of people getting it, would be perhaps faster gem refining/ability to do 2 gems at once. 

### Reason

Adds additional roleplay for State to do, as well as some cool functionality and changes to mining, a system which has been basically the same since release.

**Comment by coalaura** [comment]
Mining already makes a shit load of money compared to other jobs, i don't really wanna make it easier. If i was to add this i would have to nerf mining a good bit. Generally not a big fan
