### ISSUE TITLE
Suggestion - State Employee Identification Badge

### ISSUE THREAD

**Issue by tiigerrlily** [InZidiuZ/op-framework-issue-tracker#3165]
### Assurance

I have read the `README.md`

### Summary

I would like to propose a badge for State Employees, I currently have no way through RP means to verify that I am a State Employee when being asked.

### Reason

I think it would enhance my RP to be able to show a badge / ID that states that I'm a State Employee when asked. I know that State Security have them but it could be good for other people within the State team like myself and the Governor.

**Comment by coalaura** [comment]
another badge

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/Z58HCYEYVJ.png)
