### ISSUE TITLE
Suggestion - add a public information version of /mdt for state employees

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3168]
### Assurance

I have read the `README.md`

### Summary

give all state employees including security (as we're able to do licensing as well once trained) access to /mdt so it works in city for us, as the browser version is struggling lately. We don't need access to make arrests or anything, just the public information tabs.

### Reason

make states lives easier

**Comment by coalaura** [comment]
the ingame version is the browser version just loaded in a small frame, i'm down to make the command available for state security

**Comment by coalaura** [comment]
So, the mdt the international server has is a custom one, we cant really make the built in mdt available to state since its structured in a completely different way.
