### ISSUE TITLE
Suggestion - sales tax on /bill

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3169]
### Assurance

I have read the `README.md`

### Summary

With the large amount of transactions in the city by businesses being done via use of /bill I think it's time that there starts being tax added on top of this. Cash transactions would still exist for those criminals that would prefer to evade taxes, and could open up additional DOJ RP as well if people are caught tax evading. Businesses that move vehicles for instance are doing so with no tax being placed upon a deal for hundreds of thousands of dollars potentially. Would also act as a cash sink mechanic. 

### Reason

Potholes on Supply Street are really bad and we need the tax revenue.

**Comment by coalaura** [comment]
eventhough i would love this the community would hate it

**Comment by scufflord** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/39427774/6e6073d1-ac84-4eda-a038-f1f83c102420)
