### ISSUE TITLE
Suggestion: Bus driver legal job.

### ISSUE THREAD

**Issue by AiDNDevelopment** [InZidiuZ/op-framework-issue-tracker#317]
**Name:**
AiDN#1809

**Summary:**
In short the job im suggesting would be a bus driver job.

The job would ideally start at the bus station opposite the lower entrance to pillbox (The one that players can currently use to spawn in down there.) and would provide players with a bus and they would then instruct them to follow their route. 

The route would consist of a number of stops that vary in location and distance, with an idicator marker, After approcahing the marker they player would be instructed to wait for the passengers to get on (Unsure if you could get NPC's to actually walk on the bus or even if its just a short timer). 

After completing their route the player would then be instructed to head back to the bus station to store the bus, the player would be paid here. (the pay would be a flat fee + a distance bonus similar to the garbage collection job)

**Reason:**
I believe that another legal job is always a plus, on another note it would enable players to RP a new story as a bus driver.

**Comment by allenle4** [comment]
+1

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Devleoper*
