### ISSUE TITLE
Suggestion - add a modifier for engine damage to oil script

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3170]
### Assurance

I have read the `README.md`

### Summary

Make it so that if you're driving around with a damaged engine that it increases the wear and tear on your car, and thus means you go through the lifetime of your oil change faster until the car gets repaired.

### Reason

Added realism + benefit of driving a repaired car vs a broken car

**Comment by coalaura** [comment]
hmmm, this would be a pain to implement with oil, dont think its really worth the benefits
