### ISSUE TITLE
Suggestion - fill water bottle at sinks

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3171]
### Assurance

I have read the `README.md`

### Summary

Make it so I can fill my waterbottle up at any sink that you could use to wash gsr off your hands or whatever.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/39427774/4523144a-0ef5-42d5-90bb-31be656b7c79)

### Reason

Cause it's a sink.

**Comment by coalaura** [comment]
how would you do it tho, how do you differentiate between wanting to wash your hands and filling up a bottle
