### ISSUE TITLE
Vehicle tuner update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3172]
### Assurance

I have read the `README.md`

### Summary

A summary of top speed and a graph

2 lines on graph, when you put a tune and save you can see top mph 

### Reason

To make a tuner chip more informational and effective

**Comment by MetaHatter** [comment]
Half the fun of tuning is assuming you have found the best one... or that you need to find a better one...

**Comment by coalaura** [comment]
Yeah not only is this basically impossible since the top speed is dependant on more than just 6 values with a slider, but also is it a lot more fun NOT knowing which slider affects what
