### ISSUE TITLE
Suggestion - Add a table at GW to drain vapes

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3173]
### Assurance

I have read the `README.md`

### Summary

Add another table / sink in the back of GW (where we fill vapes) so that we can drain them too.
If we buy a vape from the blue arrow in the back, we gotta stand there smoking it until it's empty if the person orders a flavoured one.
If we could simply drain them, it would make our lives so much easier.

### Reason

If we could simply drain them (fully remove all the vape juice), it would make our lives so much easier.

**Comment by coalaura** [comment]
You can now refill vapes even when they are full
