### ISSUE TITLE
Suggestion - Changes to Jim's Taco Truck

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3176]
### Assurance

I have read the `README.md`

### Summary

Jim was a great addition to the server to solve the access issue for good pistols for everyone. However, I feel like as time has gone on this has essentially killed off a lot more roleplay than it is worth. As I wouldn't want to come in here and suggest fully disabling a feature with that much time into it, I do think that some large changes need to be made to Jim to balance out the gun marketplace a bit and make it more dynamic.

1. Set a 72 hour or more timer on when Jim will sell you guns. Once you go up and talk to Jim and buy stuff from him a timer should start that counts down from the second he closes shop until a few days later when he will sell to you again. Jim's moving a lot of illegal weapons, and police have caught on and know all about it in roleplay already, so the heat is on him for sure. He's gotta start cutting back on how much product he moves.

2. Limit purchases to 1-2 weapons not including 2 handers on special offer. It's too easy for a group to fly into the city, go hunt for an hour as a collective, and be able to fully kit everyone out with a stockpile of pistols from Jim. People don't go to others for guns anymore unless it's two-handers. We need to bring roleplay into this market. Limiting how many you can purchase inherently makes those guns more valuable and rare, as there won't be so many flooding the market. 

3. Decrease the stock on weapons in Jim. Too many times I've pulled up and seen almost everything in stock with 3-4 guns each. Absolutely insane quantities of guns are available because of this.

### Reason

Because there's no roleplay in buying pistols anymore, and such easy access to weapons has caused the middle tier guns (ceramic, endurance, combat etc) to become just pieces of shit to go scrap for mats. This gives some use to them as every day carry type of guns, and brings back that feeling of "i better save the heavy pistol for when i really need it and just carry this combat while i do my dailies"

**Comment by coalaura** [comment]
I disagree with points 1 and 2 but i like 3. I'm gonna decrease the stock on weapons in Jim
