### ISSUE TITLE
Suggestion - reduce shotgun damage fall-off

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3179]
### Assurance

I have read the `README.md`

### Summary

With shotguns now having a knock-down mechanic I feel like the damage fall-off over distance needs to be adjusted a lot to make it make sense. Currently, if you're not in someone's face with a shotgun it's pretty underwhelming, but the knock back effect will kick in even if you're a block away tickling them with birdshot. I think the damage reduction needs adjusted so that at distances the rounds are still packing more of a punch. This would also in turn make shotguns even more useful compared to where they're at now.

### Reason

Balancing

**Comment by coalaura** [comment]
ok done something in the lines of this
