### ISSUE TITLE
Can't take the Ferrari 488 out of Garage D

### ISSUE THREAD

**Issue by PhizioN** [InZidiuZ/op-framework-issue-tracker#318]
**Reporter:**
PhizioN#4462

**Summary:**
I bought the Ferrari 488 from the exclusive dealership, fully upgraded it, and stored it in Garage D. After I tried to take it out, I noticed that nothing happened. It says that it's there, but is just unresponsive upon selection.

**Steps to Reproduce:**
Buy a Ferrari 488 from the exclusive dealership, upgrade it fully from LS customs, then take it directly to Garage D and store it. Then try to take it back out.

**Expected Results:**
That you will not be able to take it out.

**Actual Results:**
Nothing happens when I select my car and try to take it out, even though it says that its in.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 223

**Notes:**
For anything else noteworthy.

**Comment by PhizioN** [comment]
Also wanted to comment - the garage seems to work fine, it's probably something with the car because I watched someone store their tow truck and take it back out of the same garage.

**Comment by SATIN187** [comment]
This is the wrong github for this. You wanna post this in the assets github
