### ISSUE TITLE
Suggestion - paint protectant

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3180]
### Assurance

I have read the `README.md`

### Summary

Add a purchasable item from the mechanic computer for $50 that mechanics can sell as a service for $350 (using arena pill pricing just for example) that when used on a car by the mechanic will slow dirt buildup by 50-75% for the next hour or two. Some cars build dirt up really quick, and some colors show dirt really badly, so this would be a cool option to solve the issue in roleplay instead of having to go bother Joe to adjust how fast a car gets dirty every time. 

### Reason

QoL

**Comment by coalaura** [comment]
Duplicate #2883
