### ISSUE TITLE
Suggestion - Craftable beef jerky

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3181]
### Assurance

I have read the `README.md`

### Summary

So we've got beef jerky in trash cans and at paleto gas station right? Well hear me out... At the hunting store add a bottle of "liquid smoke" that you can use in your pocket (drag to center like making kimchi or crushing gems) with some meat from a deer to make a piece of "Raw Brined Meat" that when cooked in the bbq produces a piece of venison jerky. Due to the time required to make it, have it be pretty good like kimchi is and since it's preserved jerky, have it last a while too. 

### Reason

Gives a bit of fun flair to hunting, while also being something beneficial that could create rp (people buying and selling raw meat, or hunting and making jerky to sell)

**Comment by coalaura** [comment]
oooooh i like this

**Comment by coalaura** [comment]
done
