### ISSUE TITLE
Suggestion - Add ability to check when pawnshop sales reset

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3182]
### Assurance

I have read the `README.md`

### Summary

Add a location at the bazaar or an app on the tablet that will let you track when your "deer tags" reset for your daily limit, and when the gem stores will be able to afford more of your massive stockpile of gems.

### Reason

Quality of life. I am too old and too stoned to try to remember what time I sold leather

**Comment by ImArteria** [comment]
min max 😎

**Comment by coalaura** [comment]
yeah no
