### ISSUE TITLE
Bug report - TLMC repair shop cant buy materials

### ISSUE THREAD

**Issue by Shubham-426** [InZidiuZ/op-framework-issue-tracker#3183]
### Assurance

I have read the `README.md`

### Reporter

shubham6414

### Summary

no place to buy materials to repair cars there is no option right now to purchase materials

### Steps to Reproduce

please make a right place to buy materials for repair shop 2

### Expected Behavior

please make a good location where mechanics can easily purchase materials

### Actual Results

please make a good location where mechanics can easily purchase materials so that it would be easy for mechanics to purchase materials

### Game Resolution

192081080

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
was already fixed
