### ISSUE TITLE
Bug report - GW Refilling

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3184]
### Assurance

I have read the `README.md`

### Reporter

tyyy1022

### Summary

If you have more than 1 vape in your inventory, and you try to refill them, it will continually refill the same vape.
Due to it being able to refill vapes that are full, it will just keep cycling the same one.

A fix for this would be to revert the refilling table back to as it was, and then use the other red table as a place to drain the vapes.
Instead of refilling full ones, just empty and then refill. This will also make it slightly more realistic.

### Steps to Reproduce

Try to refill 2 diff vapes.

### Expected Behavior

Should refill them seperately

### Actual Results

It refills the same one over and over again.

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
Fixed, it will now only refill vapes that are not completely full
