### ISSUE TITLE
Suggestion - Paid parking at the casino?

### ISSUE THREAD

**Issue by xDAxDANTEx** [InZidiuZ/op-framework-issue-tracker#3185]
### Assurance

I have read the `README.md`

### Summary

works kind of like rent so more like a membership fee that could be paid through comp. It would give access to an actual garage somewhere at the casino for people to store their car while inside. It could be a paid weekly or monthly thing whatever would work the best. 

### Reason

To give people an alternative parking location at the casino that wouldn't scuff and make their car poof and also the random people who slash tires out front for no reason.

**Comment by coalaura** [comment]
There is already a garage you can get into with your car via a teleporter and use an elevator to go to the casino, people are just lazy and park up front

**Comment by coalaura** [comment]
here

![yes](https://i.shrt.day/DYFEDT3L1D.png)

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/TQKTWJ4OLS.png)
