### ISSUE TITLE
Suggestion - Clickable phone numbers on X

### ISSUE THREAD

**Issue by zyronex** [InZidiuZ/op-framework-issue-tracker#3186]
### Assurance

I have read the `README.md`

### Summary

Would it be possible to make phone numbers (anything in this format 000-0000) on X clickable and then open a prompt to either text or call that number? If not a prompt to call or text, perhaps just a message window (like emergency services) so that someone can quickly text, and the person can then text or call them.

### Reason

People use X to advertise, and sometimes include their number, but it can be a hassle to get in touch with that person. You have to memorize the number, write it down, or add them as a contact to call them. This would remove friction and allow someone to contact that person faster.

**Comment by coalaura** [comment]
done
