### ISSUE TITLE
Discount on Property Rent - Token of appreciation 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3188]
### Assurance

I have read the `README.md`

### Summary

So idea is that realtors can give discount of rent on already sold out.

this can be token of appreciation for those tenants who are loyal to company.

realtors can send them new discounted rent and if tenant accept the offer then his/her rent amount will be decreased according to discount given

### Reason

It can great thing that can enhance relationship of tenants with realtors

**Comment by enutpeanut** [comment]
not a realtor, but they can choose how much to charge if I'm not mistaken? I was paying $1500 and the owner changed and, for the same property, started paying $1000.

**Comment by xplrerin** [comment]
> not a realtor, but they can choose how much to charge if I'm not mistaken? I was paying $1500 and the owner changed and, for the same property, started paying $1000.

Yea he means after it’s been sold

**Comment by xplrerin** [comment]
I do think that amending the pricing would be beneficial in circumstances where it’s been transferred - but I believe this was already a discussion and tbh I have set pricing so I don’t know why there’s a need to amend it afterwards.

**Comment by ayushpatel1007** [comment]
So what I noticed is that, some people dont like to change house and live in same house like for months. And I am saying months then it’s Irl months. 

Now rent amount actually vary company to company in same server. Some owner take 5k for x house then other company take maybe 4K for same house. 

Now this can’t be controlled, the rent amount.
As there is no fix rent for all house decided by state or server admins. Company owner take rent amount accordingly their own thinking. 

Now some guys are telling why change rent ? 
so I say, why not? Here we are talking about decreasing rent option only and not option to increase rent.

Decreasing rent amount can’t be misused in anyway by company owner because why would owner decrease his profit. But sometimes when competition increase in server with other real estate company, owners do change rent amount and decrease the rent amount so that other company or new company in market don’t take over the whole city. 

Anyways, company owner and tenants are decreasing rent but currently they have to leta go house till it’s overdue and tenant is evicted and then same tenant buy house again with less rent. 


so anyway this is happening then why not make it easier because decreasing rent for already sold out house will not thing that will be used frequently but it make things easier. This feature is like “ownership transfer feature”. Ownerships don’t usually used to transfer but when it is needed to do so , it make work easier 


I think we need this feature. Because anyways it is happening. This will make things easier

**Comment by enutpeanut** [comment]
> Now some guys are telling why change rent ? so I say, why not? Here we are talking about decreasing rent option only and not option to increase rent.

I actually like this idea a lot. Honestly would be cool to be able to increase rent as well as decrease it, maybe give State some RP in being able to enact "rent control" orders if people complain about their rent being increased. Think it would be cool.

**Comment by coalaura** [comment]
I don't think this is needed or would even really be used... I don't think we need to add a complicated feature like this for it to be used like 2 times ever
