### ISSUE TITLE
Financing has re-occurred on a paid bike. 

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#319]
**Reporter:**
Amok#3856
https://steamcommunity.com/id/amokbsn/
**Summary:**
I had paid off my bike (Nightblade) very early on when Financing and PDM opened, over time I had made large payments to the bike and paid it off (to my knowledge) and sent at least or I'm certain 16k (2k over 8 weeks) to outright own. 

Recently it is now displaying that I need to pay another 2k p/w to the bike which would seem like I'm repaying the whole financing options. 

**Steps to Reproduce:**
I would only presume to check that bikes and financing are working as intended. 

**Expected Results:**
No duplicate financing of bikes or other vehicles 

**Actual Results:**
Not applicable

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![20190731175812_1](https://user-images.githubusercontent.com/52701837/62231902-dfb64a00-b3bc-11e9-995e-039dc45bc7b7.jpg)

**Game Resolution:**
1980x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
![20190731180156_1](https://user-images.githubusercontent.com/52701837/62232084-505d6680-b3bd-11e9-9ee3-d2e94652bead.jpg)

**Notes:**
I'm not sure if a compensation scheme would exist as I've taken out a second car and don't want to lose or be unable to pay my lovely GTX Dominator, if I am incorrect in this instance please let me know through DM's as you have my account details.

**Comment by InZidiuZ** [comment]
Hey,

I find this to be very unlikely, as the logic behind the financing system is extremely simplistic, and as there hasn't been any reported issues similar to this before, I'm doubtful.

Took another quick look at the source code for it, and can't see anything that would cause this to happen. When you pay the final week, the database entry is completely deleted, so for it to reset back to the start, doesn't make a lot of sense. The weeks paid are also updated by incrementing your weeks, which makes me even more confused as to how this would happen.

For sure, there could be some flawed logic, but without any solid repro/other reports, not sure what the issue would be. Do you have any screenshot of the initial finance? Do the finance IDs match up?

**InZidiuZ**
*OP-FW Developer*
