### ISSUE TITLE
Suggestion - add a chat alias for F5 car menu

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3190]
### Assurance

I have read the `README.md`

### Summary

Add a /command that will pop up the menu that pops up when you hit F5 in a car

### Reason

Streamdeck usage of it is the main reason, plus not everybody has F-row on their keyboard so they could still make use of the menu. Being able to call this up from a single streamdeck button vs having to try and re-make that menu basically on the stream deck is a bit of a headache.

**Comment by coalaura** [comment]
what menu again?

**Comment by coalaura** [comment]
/vehcontrol
and you can already rebind it in your settings
