### ISSUE TITLE
Suggestion - Metal detectors at government buildings

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3191]
### Assurance

I have read the `README.md`

### Summary

Add metal detectors to the front doors of these buildings that will trigger 10-32 calls for police if anyone gets too close with a two hander. These are government facilities, and people running around with two handers on their back like it's no big deal near these buildings is nowhere near realistic. The governor's office is like the #1 spot for criminals to go to to get helicopters for cargo, with LSIA being the other active one.

### Reason

Cause it makes sense

**Comment by scufflord** [comment]
realized the first part didn't paste but specifically maze bank tower, doj offices, and court house

**Comment by coalaura** [comment]
after thinking about it for longer i dont think we need this
