### ISSUE TITLE
Suggestion - 

### ISSUE THREAD

**Issue by Thales1732** [InZidiuZ/op-framework-issue-tracker#3192]
### Assurance

I have read the `README.md`

### Summary

Is there any way to change the garage door to a fixed fully closed door instead of the partial open one that is there currently.

the property address is Ineseno Road 21, also have attached a picture of the way it currently is.
![guwk6htg](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/108765393/63a53f57-3c2c-46ac-a47b-15080da4ba6a)

### Reason

More room to be able to park a car out front of the driveway and it just looks bad being partially opened.

**Comment by coalaura** [comment]
No this would mean we would have to stream the entire block just to change one garage
