### ISSUE TITLE
Bug report - Game crashing when going into properties

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#3193]
### Assurance

I have read the `README.md`

### Reporter

selliee

### Summary

My game keeps crashing whenever I go in and out of different properties in the game, sometimes its random- since my character is a realtor whenever going in a house/apt my game crashes [not always], however one property in particular Forum Drive 6 / Apt1 I crash 9/10 times entering the home. 

### Steps to Reproduce

Going into the house causes the crash

### Expected Behavior

no crash

### Actual Results

crash

### Screenshots/Videos

https://cdn.discordapp.com/attachments/916814025386516500/1203759451556028456/image.png?ex=65d2435a&is=65bfce5a&hm=1cbe1f448106c1db13121c97eb1026af2ce9ebfcc32f982d644cc8e194facfc5&

### Player Data

https://cdn.discordapp.com/attachments/962396305722851379/1203761184675991703/image.png?ex=65d244f7&is=65bfcff7&hm=c5d99165a54f6d22f69014bd10f1316cf37452d417144a42ab85d005c250220a&

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
no clue

**Comment by coalaura** [comment]
is this still happening?

**Comment by selliee** [comment]
yes the answer is yes LOL. ive crashed twice tonight
