### ISSUE TITLE
Suggestion - Removing 10-14 Alert when UC

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3194]
### Assurance

I have read the `README.md`

### Summary

Either disable the 10-14 noise for people on undercover tracker or just completely remove the ability to receive 10-14 calls whilst undercover. 

Or alternatively, the panic button sound should only come from the downed individual, if I'm nowhere near the 14 I don't really see why people are able to hear the sound when they're near me. 

### Reason

The new 10-14/panic button noise can be heard by people around you which is a good addition however when you're undercover it can blow your cover.

**Comment by coalaura** [comment]
fixed
