### ISSUE TITLE
Suggestion - increase stress multiplier

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3197]
### Assurance

I have read the `README.md`

### Summary

Honestly, we don't get stressed enough from shooting, driving fast and hitting things, crime, etc. Increasing this by 2-3x would also create roleplay benefits for not only green wonderland due to increased need for stress relief, but also bean machine, and private weed growth and illegal sales between crims.

### Reason

I'm too damn calm doing 150 shooting locals in the head and bumping their car out of the way.

**Comment by ThatSinisterGuy** [comment]
I actually quite like the idea of going above certain speeds causing stress, to represent the adrenalin of going fast and risk of cops catching you.

**Comment by coalaura** [comment]
true

**Comment by coalaura** [comment]
i upped it, keep in mind state security and sasp get less stress when shooting
