### ISSUE TITLE
/transfer command update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3199]
### Assurance

I have read the `README.md`

### Summary

Add the ability to change the price on the transfer contract 

### Reason

I am currently selling a house to myself for the same price I rent it for but am now trying to transfer to a client and make a little dough on top yah heard

**Comment by coalaura** [comment]
no, as previously discussed /transfer is purely for transferring properties not for re-selling. You'll have to let it drop and then resell it
