### ISSUE TITLE
Pillbox store/gift shop

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#320]
**Name:**
Amok#3856
https://steamcommunity.com/id/amokbsn/
**Summary:**
Pillbox currently has space for a gift shop and/or store to be implemented to potentially increase sales helping the medical centre stay open, medical bills can keep this place open on its own! 

This store would only sell basic amenities such as food/water and potentially bandages (flowers if they can get added eventually for bedside recoveries) 

**Reason:**
Patients can access the gift shop/store after recovery to stock up on needed supplies if they require, this means that we can have more connections in Pillbox through use of the store and also so we don't have to log out of duty to re-supply on our own food and water when it gets busy at Pillbox. 

![20190724171226_1](https://user-images.githubusercontent.com/52701837/62234938-aaf9c100-b3c3-11e9-8ae5-4d369611dd6d.jpg)

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
