### ISSUE TITLE
Suggestion - governor's elevator

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3200]
### Assurance

I have read the `README.md`

### Summary

Add an elevator teleporter that is locked to government only jobs (state sec, governor, employees, vice gov, assistants etc etc) that allows for access from the governor's office down to the parking garage.

From here:
https://cdn.discordapp.com/attachments/1057850240553717830/1204491245599195207/image.png

To here: 
https://media.discordapp.net/attachments/1057850240553717830/1204493285628968960/image.png

### Reason

QoL

**Comment by coalaura** [comment]
I'Ve added the grorvrernror elevator
