### ISSUE TITLE
Suggestion - Cinema Improvements

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3201]
### Assurance

I have read the `README.md`

### Summary

Food Upgrades - 
Food already in server: Nachos, Hot Dogs
Not in server: Popcorn - Potential photo for Icon https://cdn.discordapp.com/attachments/987550018154156092/1204967367835127808/Random_Photos_5.png?ex=65d6a84f&is=65c4334f&hm=b9be1d9d007ce2d2a2487df6db5dfdc399ecb177c45f4e34aff1d63e39a28051&

Storage for Employees - 
Storage for prizes and other food items if they have to be brought in. 

Location: 
https://cdn.discordapp.com/attachments/987550018154156092/1204968048830717973/image.png?ex=65d6a8f2&is=65c433f2&hm=934bfa99d865fee84b3a1158147a627e151092affc27395aadba10041273b957&
https://cdn.discordapp.com/attachments/987550018154156092/1204967993507844136/image.png?ex=65d6a8e4&is=65c433e4&hm=908b2990f313ea91e04c6be382255415f80335226989e1c31212b2040d815fd5&

### Reason

Improve the RP and community sense around the cinema. What is the movies without finger food. But most notably popcorn. 

Popcorn is a stable to a movie going experience. 

New owner asked for storage so I was already writing a Food Request. May as well make the request too.

**Comment by antihero6713** [comment]
I have the assets and animations for popcorn. Just need to get that pushed in.

**Comment by coalaura** [comment]
done
