### ISSUE TITLE
Suggestion - Allow bicycles to be transported in trunks

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3203]
### Assurance

I have read the `README.md`

### Summary

Add the ability to "tow" bicycles, motorcycles, and the small ATV's like the blazer, verus, etc into the bed of pick up trucks like the sand king, raptor, bison, titan etc for transport. This will allow people to legally transport dirtbikes without having to worry about not having a plate, enhances the roleplay of going out for a rip on your bike or going to your hunting cabin up north with the boys, and adds to the realism of what it's like to be a truck owner. Trucks are made to carry shit, so lemme carry some shit lol

It is possible to do things like [this](https://i.imgur.com/GQY5YQm.png) with bicycles currently but with vehicles that have more mass like motorcycles or quads it would just turn into a scuffed mess that would just damage both vehicles. But if you could load them into the back of the truck and have them be in a similar state to /tow where they have no mass and are able to be walked through etc then it would allow transport easily

### Reason

Quality of life type of thing, plus it just makes sense. A BMX bike would fit in most cars trunks even.

**Comment by coalaura** [comment]
motorcycles idk, i'd be down to make bicycles transportable

**Comment by coalaura** [comment]
> What about 4 Wheelers?

4 wheelers are not bicycles

**Comment by scufflord** [comment]
bicycles would be nice but dirt bikes and 4 wheelers were my main inspiration for this. would just give people a nice easy way to transport them that makes sense and adds to the roleplay

**Comment by TacticalTyl3r** [comment]
I am not sure how possible it is. But what about getting a "trailer" that can be purchased. Then maybe that would allow the safe transport of 4 wheelers, dirt bikes, and eventually boats that we could own and transport to a mechanic if needed.

**Comment by coalaura** [comment]
> I am not sure how possible it is. But what about getting a "trailer" that can be purchased. Then maybe that would allow the safe transport of 4 wheelers, dirt bikes, and eventually boats that we could own and transport to a mechanic if needed.

Don't think there is a native trailer that is made for motorcycles/4 wheelers and im certainly not making one since thats above my 3d modeling skills

**Comment by TacticalTyl3r** [comment]
> > I am not sure how possible it is. But what about getting a "trailer" that can be purchased. Then maybe that would allow the safe transport of 4 wheelers, dirt bikes, and eventually boats that we could own and transport to a mechanic if needed.
> 
> Don't think there is a native trailer that is made for motorcycles/4 wheelers and im certainly not making one since thats above my 3d modeling skills

That is totally fine. I suggested it because I was not sure.

**Comment by scufflord** [comment]
There's actually a bunch of different trailer models available out there already. Seen them used on a bunch of servers for exactly this. 

https://www.gta5-mods.com/vehicles/brute-car-trailer

**Comment by HollaYalla** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/1dfc36b8-1fcc-4ded-8185-9a02ee18fa2c)
Yes!
