### ISSUE TITLE
Suggestion - newspaper

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3204]
### Assurance

I have read the `README.md`

### Summary

Re-work how the newpaper box props work to have them display a screen showing times and dates of any upcoming public events from the discord, as well as the name and sentence of the last 10 arrests. Could even get data from the legacy doj website to show any upcoming court cases for the week.

### Reason

Brings information into the city from Discord and websites, makes it easier for people to find that info since there's newspaper boxes literally everywhere, and it can help provide increased interaction due to the information being out there.

**Comment by MADxxVIKING** [comment]
W idea.

**Comment by coalaura** [comment]
no

**Comment by coalaura** [comment]
Would be a huge feature including very subdivision specific things and i dont see it being used
