### ISSUE TITLE
Suggestion - Replacing Graffiti at Bay City Avenue 1/2

### ISSUE THREAD

**Issue by Jvyxh** [InZidiuZ/op-framework-issue-tracker#3206]
### Assurance

I have read the `README.md`

### Summary

At the moment there is a graffiti sprayed logo of a previous gang that held this block a couple of months ago, tang gang. For the past 4/5 months the location has been held down by a new up and coming gang "The Irish". We are looking to remove the current logo and replace it with our own. Apologies in advance if this is wrong place to make this request.

I would be happy to provide logo files if this request is approved. Thank you

![The-Irish---Eire-Logo-two-colour2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/159549169/2a7fbb9d-5f39-4b07-991d-723408856b3b)

### Reason

I believe tang gang are no longer an active gang in our city

**Comment by Jvyxh** [comment]
![location](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/159549169/57427a4f-f490-4824-a739-65ad8f1c89b9)
![baycity](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/159549169/e02b26e5-a74f-4699-865e-1dcb4427e46d)

**Comment by Jvyxh** [comment]
Also just wondering if it would be possible to remove these trash bins from outside. People tend to hang out here and sit along the wall and chat. We've found when trying to check your pockets, your character instead searches the bin from meters away, again not even sure if this is possible but would be great to get these moved

![bins](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/159549169/4d1d93ec-e813-4019-ab46-7db9bc3b186a)

**Comment by coalaura** [comment]
This would be something for the [asset github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=Suggestion+-+)
