### ISSUE TITLE
Bug report - Blackjack 3 - 2 Payout

### ISSUE THREAD

**Issue by GodyFromDiscord** [InZidiuZ/op-framework-issue-tracker#3207]
### Assurance

I have read the `README.md`

### Reporter

_gody

### Summary

The blackjack 3-2 payout does not work as intended if the player hits a blackjack.

### Steps to Reproduce

Play Blackjack till you get a Blackjack, Ace + High Card/10

### Expected Behavior

If I bet $100 I should get paid 250 on a payout, being the bet and a half

### Actual Results

You just get the standard 1-1 payout doubling your bet/buy in

### Screenshots/Videos

https://i.imgur.com/dAPdYyQ.png

States on the table it pays 3-2 but it does not

### Game Resolution

1920x1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/60844168/d1a60e34-82bd-4968-9b3c-60669dd5008a)

### Server

OP-FW Test Server (c2s1.op-framework.com), International (c3s1.op-framework.com), Latin America (c4s1.op-framework.com), Italy (c5s1.op-framework.com), Poland (c6s1.op-framework.com), India (c8s1.op-framework.com), Bangladesh (c10s1.op-framework.com), Nepal (c13s1.op-framework.com), South Korea (c15s1.op-framework.com), Estonia (c16s1.op-framework.com)

**Comment by coalaura** [comment]
there is no 3-2 payout

**Comment by coalaura** [comment]
the table props are part of the basegame, our version of blackjack does not and will not have 3-2 payout
