### ISSUE TITLE
Suggestion - Add support to Twitter / Printer for the new discord embed URLs 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3208]
### Assurance

I have read the `README.md`

### Summary

Using the below regex, can we add support to both Twitter and the Printer in the city for the new discord cdn url requirements:

Example URL:
`https://cdn.discordapp.com/attachments/777722318159347712/1205318529595871362/image.png?ex=65d7ef5b&is=65c57a5b&hm=12dbc0a2759f02b0d1cfb3aabf96422e78b8bb804443b9cd5049393d0a5caabe&`
Regex to check for valid image (Change supported extensions as required): 
`/^(https?:\/\/)([\w\-]+(\.[\w\-]+)+)(\/[\w\-.,@?^=%&:\/~+#]*\/)?[\w\-.,@?^=%&:\/~+#]*\.(jpg|jpeg|png|gif|bmp|webp|tiff)(\?.*)?$/`

### Reason

Discord has changed how they support attachment embedding, and as such `https://cdn.discordapp.com/attachments/777722318159347712/1205318529595871362/image.png?` would no longer work and you _must_ have the full URL.

_Image link provided is just an example_

**Comment by coalaura** [comment]
Thats intentional. Discord links now expire, optimally images should not expire on twitter, which is why we force regular image links. There are plenty of ways to get such a link be it imgur or a private sharex backend whatever you want

**Comment by coalaura** [comment]
admin panel has the same problem
