### ISSUE TITLE
Suggestion - Background Colour of "X" in phone.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#3210]
### Assurance

I have read the `README.md`

### Summary

change the colour of the background in "X" from blue to black so that it matches.
![Screenshot 2024-02-13 095548](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/7d597097-fbed-4a7b-aa2a-5e5b00542598)

### Reason

since the logo/name changed from "twitter"to "X", the colour can be black to match the logo.

**Comment by HollaYalla** [comment]
Maybe add a swappable color option? Like a little toggle that is blue themed and one is dark themed
