### ISSUE TITLE
Suggestion - Weed Strains

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3212]
### Assurance

I have read the `README.md`

### Summary

With the reintroduction of the Weed Field on Legacy International maybe we could add different strains of weed that could have different effects or sell for different prices.

* Purple Kush - This will be your daily weed like used at Green Wonderland and has no effects

* Skunk - This will relieve a more stress than normal but will also blind the smoker (use the same effect as getting pepper sprayed for like 5 minutes)

* Sour Diesel - This you will gain a lot more when harvesting and can only be found at the field but only can be made into joints (Unsellable). Smoking this strain will give you a small amount of stress relieved (Mainly used as movie props or harvested for high quantities)

* God - The **GOD** Strain of weed will be the best selling one but is the most rare one could sell from 500-900 but has like a 1 in 1,000 chance of getting it from the Weed Field and has 1 in 10,000 chance of giving you a weed seed which will have a 1 in 500 chance of getting another seed from the weed you plant. Also smoking this will give you Speed just like cocaine does but it will have a longer lasting effect.

* OG Kush - This is the original strain of weed that we have now just renamed just with a little selling price buff but it is also only obtainable from the current seeds in circulation and possibly events (makes it more rare)

### Reason

Add different kinds of weed into the city.

**Comment by coalaura** [comment]
I like keeping GW as the main business regarding anything related to weed

**Comment by HollaYalla** [comment]
It will stay the main weed location but this would be only for the weed field and those God Seeds that’s it otherwise you can only grow Purple Kush

**Comment by coalaura** [comment]
There is already suggestions like these:
#2351
#2965
which are very similar but not as easy
