### ISSUE TITLE
Suggestion - New GW Products

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3213]
### Assurance

I have read the `README.md`

### Summary

1 - Storage Containers
> Add small containers (hold like 10su) which will preserve the weed for longer and keep it fresh, (use for joints & weed)

2 - CBD Oil
> For pain relief & Stress Relief

3 - THC Oil
> For stress relief, and psychoactive effects (similar to acid but a lot weaker)

4 - Bongs
> Use the bong for the same effects of a vape but a lot more powerful. It will also get you "Stoned", will take 1 water bottle and 1 oz of weed

### Reason

These additions can enrich the role-playing experience by providing players with more options for simulating realistic interactions with cannabis and related products, leading to more diverse role-playing scenarios and character development. It can also provide a more immersive and detailed environment for players to explore and interact with, thereby enhancing the overall depth and richness of the gameplay experience.

**Comment by txxlrrsCoding** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147753100/ac116471-f339-403f-987d-a88a637bb521)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147753100/47285eb9-f273-475c-a770-97a8d5884a08)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147753100/bb55048d-da8f-4f8e-b240-d3e77b22f4f0)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147753100/9773cecf-b859-4b99-ad68-c101100f5413)

**Comment by coalaura** [comment]
i have that bong!!! lmaoo

**Comment by txxlrrsCoding** [comment]
This will also help GW sales because joints sales will drop by the next tsunami.

**Comment by HollaYalla** [comment]
Maybe also Weed Gummies

Take a Gummy Mold
Weed q’s
Gummy Base
Microwave it and boom a bag of gummies

**Comment by VernierHawk** [comment]
Bhaang (Authentic Indian Refreshing Cold Energy Drinks)
made with 1 q's
Bhang also plays a role in Ayurvedic medicine and is promoted as a remedy to various ailments, including nausea, vomiting, and physical pain.
https://www.healthline.com/nutrition/bhang

**Comment by coalaura** [comment]
I dont think we need the oil n stuff considering we already have vapes that do the stress relief part. I've added a "weed" option with the flavors tho (it applies the weed effect to everyone around). I've also added the weed gummies

**Comment by txxlrrsCoding** [comment]
> I dont think we need the oil n stuff considering we already have vapes that do the stress relief part. I've added a "weed" option with the flavors tho (it applies the weed effect to everyone around). I've also added the weed gummies

what about my bong and weed containers :(( those were the main part

**Comment by coalaura** [comment]
thats what i meant, vapes are going to be pretty strong due to the THC effect. Adding a bong would be a lot of work for something that basically already exists (i wouldn't want to bump the effect strength up higher than vapes already are). The weed containers would be very difficult to integrate with our current durability system

**Comment by coalaura** [comment]
> ...providing players with more options for simulating realistic interactions with cannabis and related products, leading to more diverse role-playing scenarios and character development...

I was more looking at this and was thinking of the products as ideas/suggestions for "Add more weed things for GW"

**Comment by HollaYalla** [comment]
For the Bong you would just need to make the Item and have it work pretty much like a Vape but use like 1q of weed and then maybe Make there be a WL Weed q version thing and when u use your bong it uses the weed and damages the bong and just use /e bong

**Comment by HollaYalla** [comment]
The Strength I personally wouldn't care if it was changed or if it stays the same, I just would like an actual bong it seems more fun than a Vape

**Comment by HollaYalla** [comment]
And maybe once the Bong breaks you get a bottle of water that is Called Bong Water and it gets you high and Hydrates you but you loose Food because it is nasty and you throw it up

**Comment by txxlrrsCoding** [comment]
but... but... bong? :(

**Comment by coalaura** [comment]
> For the Bong you would just need to make the Item and have it work pretty much like a Vape but use like 1q of weed and then maybe Make there be a WL Weed q version thing and when u use your bong it uses the weed and damages the bong and just use /e bong

its not as simple as copy pasting things
