### ISSUE TITLE
Suggestion - More Craftable Food

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3214]
### Assurance

I have read the `README.md`

### Summary

With the amount of new players that I have seen attempting to do a food truck or food stand but they don't get really any sales because everyone offers the same food for roughly the same price.

So I feel that the ability to make more food would benefit those Legal Food Workers and give so much more RP

Pickles
Cucumbers would be found in Cayo Perico because they grow best in Hotter Environments
1x Bucket
6x Cucumbers
2x Dill (Found in the mountains at rivers)
1x Salt (Either processed at the chicken factory with water to get salt or bought from a new Food Distribution Center UNMARKED)
= 6x Pickles (Dehydrates you a bit because of the salt but gives a lot of food)

French Fries
This would require a few new items including Potatoes and a Placeable Deep Fryer
2x Potatoes (Found in Paleto Bay and can be cut in your inventory like Kimchi is crafted if u have a knife)
1x Oil (Bought from a new Food Distribution Center UNMARKED)
1x Deep Fryer (Bought from a new Food Distribution Center UNMARKED)
= 1x Fries

Chips
This will be very similar to French Fries
6x Potatoes
1x Oil
1x Deep Fryer
= 1 x Bag of Chips

Flavored/Seasoned Chips
1x Bag of Chips
1x Seasoning (BBQ, Salt & Vinegar, Pizza)
= 1x Bag of Chips - Seasoned with the name

Pulled Pork Sandwiches
2x Pork (Head to an area with pigs and after killing them you can skin the pig and get Pork and Bacon)
1x Bun - (Bought from a new Food Distribution Center UNMARKED)
1x BBQ Sauce - (Bought from a new Food Distribution Center UNMARKED)
= 1x Pulled Pork Sandwich

Seasoning (For Chips)
BBQ Seasoning - (Buy BBQ Sauce and use a new Food Dehydrator Item Bought at a New Food Distribution Center and then place down the Food Dehydrator and dehydrate the BBQ Sauce to get Dehydrated BBQ Sauce and then in your pockets like the kimchi craft Grind it up to get the BBQ Seasoning)
Salt & Vinegar - (Get Salt and Buy Vinegar from the food distribution center and use the Food Dehydrator and dehydrate them to get the dehydrated Salt & Vinegar which then you grind up to get the seasoning)
Pizza - (You take 1x Pizza Dehydrate it and grind it up for the seasoning)

Grilled Chicken Sandwiches
1x Chicken Breast (Head to the chicken factory in Paleto to get 1x Raw Chicken breast then use a Grill to Cook the Chicken)
1x Bun
1x Lettuce (Picked in Grapeseed)
= Grilled Chicken Sandwich

Fried Chicken Sandwich
1x Fried Chicken (1x Chicken Breast RAW then use Milk and bread crumbs (Gotten from Dehydrating Bread and Grinding it up) Then Combine it in your pockets to get Breaded Chicken Breast (Gets u sick if eaten) Then deep fry it)
1x Bun
1x Lettuce
= Fried Chicken Sandwich

Chocolate Bars
4x Coca Powder
2x Milk
= 1x Chocolate Bar

Ice Cream Cone
4x Cone (Bought from Food Distribution Center)
1x Ice Cream Tube (Taking 12x COW Milk and crafting it into ice cream but once you hit CRAFT you need to spam **E** to Shake it up to get ice cream)
= 4x Ice Cream Cone

Salads
4x Lettuce
2x Cabbage
= 1x Salad

### Reason

More stuff for food trucks to sell

**Comment by coalaura** [comment]
> Pickles

Love the idea, i wont do the dill part tho

> french fries

Those are already made exactly as you described by burgershot

> Seasoned Chips/Chips

Those already exist and are sold by different businesses

> Pulled Pork Sandwiches

To make it a bit easier to use: 1x grilled meat, 1x bread, 1x BBQ sauce = 1 meat sandwich

> Grilled Chicken Sandwiches & Fried Chicken Sandwich

I'll keep it to the meat sandwich for now

> Chocolate Bars

cool idea, love it

> Ice Cream Cone & Salads

With all the other stuff, maybe a bit too much
