### ISSUE TITLE
Storage Lot addition for Realtors

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3215]
### Assurance

I have read the `README.md`

### Summary

Instead of buying houses all the time if people need extra storage they can buy storage lot, it will be considered a new block in /blocks and will work the same way houses do, except instead of going up it will just be a garage door you click “E”

### Reason

Why rent a full house when you only need storage, let’s say 10k storage a crate, weekly rent 

https://gta.fandom.com/wiki/Vinewood_Self_Storage This place already exist and won’t take to much for setting up, land mark is from Orgnial GtA

**Comment by coalaura** [comment]
this would go into this #2172, gonna link it to this issue whenever it gets done
