### ISSUE TITLE
Renovating house and change house type 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3216]
### Assurance

I have read the `README.md`

### Summary

So idea is simple, allowing to renovate house which allow to change the house type.

so we need limits so that companies just don’t keeping renovating their house every week

 Limits:
So only mansion can be renovate to another mansions. Example of you have Michale mansion then you can renovate it to maybe Franklin or high end. If they renovate it then they have to pay the charges accordingly. Also if they renovate then maintance will be Changed accordingly.

What can we renovate:

Michale x franklin x high end apartment 

Trevor beach house x Mid end apartment x Franklin house 

Lester house x low end apartment x janitor apartment 

trevor trailers can’t be renovated. 

Limits:

once in 2 week with charge for renovation. 

### Reason

People live different kind of houses and house type. If they liked location but they didn’t like house type then they can just ask to renovate the house. If tenant himself ask for renovation they they need to pay the charges accordingly. Also some type of house are least loved so we can just renovate it.

**Comment by coalaura** [comment]
No, this was already declined a while back
