### ISSUE TITLE
Suggestion - Money From Handoffs

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3217]
### Assurance

I have read the `README.md`

### Summary

I was thinking that maybe we should start getting like Checks "Similar to Savings Bonds" that are physical when we do handoffs it would make it so we could stash money places and also give it to our friends easier like you could IRL. also would save us money.

### Reason

Its easier to hide money and give it to someone

**Comment by coalaura** [comment]
I dont think this is needed
