### ISSUE TITLE
Suggestion - State Security changes for more pogs per second roleplay

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3219]
### Assurance

I have read the `README.md`

### Summary

On the international server we have within our SOP guidelines for scenarios where shotguns may be needed, and are working with DOJ currently to get clearance to be able to freely carry them on duty as needed, outside of any restrictions from the penal code due to us being more than just regular civilians. We also put each agent through a full pistol training course, educating them on various types of drills and how to become a better shot while maintaining firearm safety standards to the highest level. Furthermore, once those agents have spent time within the department and the Head of SASS deems it appropriate, we allow them to be certified for that shotgun to be carried as well.

Due to these things, I'm requesting that 10-32 calls for state security employees be disabled, as well as faster weapon drawing for pistols/tazers. Given the fact that we not only wear holsters with 99% of our uniforms, we also have more advanced firearm training than normal citizens receive. It only makes sense for us to be able to draw faster as well.

Edit: Also wanted to throw in that while we don't need access to /sc or /hc, uncuff would be very nice in the event that we have an asset get kidnapped perhaps and we need to remove their cuffs once we find them.

Double Edit because I forgot Chris asked me about this. Can the tahoes be swapped from white to black please? :D 

### Reason

Allows us to better protect state employees given the ever increasing number of threats and attacks we have been facing since the department has started growing.

**Comment by coalaura** [comment]
I'll swap the tahoes color but i already told you no for the 32 calls
