### ISSUE TITLE
Craftable chip & tuner-chip

### ISSUE THREAD

**Issue by EVILKTM** [InZidiuZ/op-framework-issue-tracker#322]
KTM#0661
my name is seth 

Summary:
Well my suggestion is going to be about 2 things my first thing that i want to suggest is to some how craft or buy the tuner chips and hacking chips so say like in the garbage job you can get like a really rare materials and you good go some place secret and you can craft the tuner chip or the hacking chip because that tuner chip makes your car a little faster and it gives you the handling that you want and i think that is just not fair for other players that dont get to have it or just dont have the chance. Because i was at work when the tuner chips and the hacking chips came out so i didnt even have a chance. Ok well thats the first one my seconded one is to add fake plates so you can use your  own car in bank robberys and your car can be how you like it so you can have a lot more fun and a way better chase.

Reason:
My reason for the tuner chips and hacking chips i think it would be a great idea because i would give everyone a chance to get the chips and like the hacking chip thats a little mini game for everyone that wants to do a bank robbery. and the tuner chip if everyone has it the /races would be lot more fun and if anyone wanted to do like say a difting event or somthing like that that would make the tuner chip and the hacking chips a good reason for you to add some way of getting them for everyone even if it takes like 2 or 3 weeks to get even just one. The fake plates would be a good reason to be in legacy because robberys are a big thing in GTA / RP and when you have your own car that you know how to drive you can have a way better chase with YOUR OWN CAR. well that my suggestions for the chips and fake plates thanks for reading this and have a great idea

**Comment by SATIN187** [comment]
Honestly tuner chips are poop right now, they don’t change your car much, and the bank chip, what do you mean mini game. As far as I know it just makes it so you use 1 less thermite

**Comment by Sleezybeezy** [comment]
ya tuner chips are basically non existent unless they do miracle upgrades on the imports. so unless another buff comes around i wouldn't even worry about tuner chip. and like SATIN said, hack chip only buys you like a 2 minute headstart from having to use the first thermite. thats it.

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new issue.

**InZIdiuZ**
*OP-FW Developer*
