### ISSUE TITLE
Light the way

### ISSUE THREAD

**Issue by vol5** [InZidiuZ/op-framework-issue-tracker#3220]
### Assurance

I have read the `README.md`

### Summary

Often times I've heard the quote "It would be cool if we could light this area up for x". If we could, Steve would be proud. 

A real prop that works just like a Minecraft torch would be HUGE!

Torch:
- 1su

Crafting:
LMAO

### Reason

- No more surprise Creepers
- Players can finally mine without getting hit with an arrow
- Light to see

**Comment by coalaura** [comment]
the torch be burnin

![yes](https://i.shrt.day/T4TP9ZVUFZ.webp)

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/Z6LUJH6D2A.webp)

made a custom prop for it with fire and everything. Might make it so you can carry it around in the future but this for now

**Comment by vol5** [comment]
HELL YEAH! THAT SHIT FIRE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
