### ISSUE TITLE
Suggestion - Boombox improvement

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3221]
### Assurance

I have read the `README.md`

### Summary

Seen a lot of requests from people wanting to have a way to listen to their boombox in vehicles that don't have typical trunks (things like phantoms etc) So I was thinking that it could be solved one of two ways: 

1) when in a vehicle add a command that a user can type that will pull up a "radio" display and allow them to play things just like the boombox does

or 2) allow boomboxes to be places into seats

### Reason

QoL

**Comment by coalaura** [comment]
incorporated into the summary
