### ISSUE TITLE
Pdm update 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3223]
### Assurance

I have read the `README.md`

### Summary

More cars 

### Reason

As I’ve been in my current city for months now, I have been st point of just buying cars from PDM to expand my fleet, would love an update that releases new cars in all classes,

**Comment by MetaHatter** [comment]
Vanilla cars have to be tested, hand balanced and priced before being added to the framework. EDM/casino cars are constantly being worked on and added as often as possible. 

There are hundreds of cars currently available.  Many of which are sleepers. Might be worth fully exploring what the framework already has to offer while you wait.

**Comment by coalaura** [comment]
yeah PDM sells all vanilla cars that are currently in the game (and balanced in roleplay). We have to wait to switch to a higher gta version before we can add more and even then we can only add the ones rockstar added in that version
