### ISSUE TITLE
Suggestion - Refining Times

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3224]
### Assurance

I have read the `README.md`

### Summary

Instead of every gem being 40s refining, make the less valuable ones be quicker to refine as they would require less delicacy.
For example -

Emerald: 25s
Sapphire: 30s
Ruby: 35s
Morganite: 45s
Diamond - 50s

### Reason

qol

**Comment by coalaura** [comment]
done
