### ISSUE TITLE
Suggestion - Vehicles Destroying Weed Plants

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3227]
### Assurance

I have read the `README.md`

### Summary

If you drive over a weed plant it should make it non-foragable as realistically driving over any plant would destroy it

### Reason

Lots of people driving through the weed field looking for the plants to pick. Seems very powergamy and min-maxy. I literally spoke to someone earlier and jokingly said 'stopp you're running over the product' and he said no it doesn't run them over it makes finding the plants quicker and easier... 

This could be hard to implement; potentially similar to how props would disappear/destroy when you ran into them with a vehicle

**Comment by coalaura** [comment]
done
