### ISSUE TITLE
Suggestion - Vehicle Sabotage

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3229]
### Assurance

I have read the `README.md`

### Summary

I was thinking of a way that a person can mess someone else up or just PD by cutting their breaks

**Step 1:** 
Get a Multi Tool and a Basic Repair Kit

**Step 2:** 
Walk to the front of a vehicle

**Step 3:**
Use your Multi Tool and you will go under the car like /e Mechanic or changing oil

**Step 4:**
Then you will be searching for the break lines

**Step 5:**
Once Found you will spam A & D or hit E to cancel I have a gif that I found of a example of this.

https://cdn.discordapp.com/attachments/833279066689241108/1020050955477192735/ezgif.com-gif-maker_25.gif

Once this has been completed it will use the Basic Repair kit

Or if you don't want to use the stuff that is in the server as of now you can make a new item

# Items Used (New) #
Break Kit (Can be used to Cut Break lines and repair them) (Breaks can also be repaired from (storing your vehicle or using a advanced repair kit) You also could have mechanics repair them if they are found to be broken when repairing)
Wire Cutters (Used to cut the wires and bought at Hardware store)

# Items Used (Current) #
Basic Repair Kit (Just used to Cut the break lines)
Multi Tool (Used to cut the wires)

### Reason

More fun and makes people pay attention to their vehicles

**Comment by coalaura** [comment]
This would get abused HEAVY

**Comment by txxlrrsCoding** [comment]
> This would get abused HEAVY

You could make it like a 1/20 chance of working, and if it fails then set off the alarm and call the police
