### ISSUE TITLE
Oxy Run Bug Report

### ISSUE THREAD

**Issue by LowlyGentAC** [InZidiuZ/op-framework-issue-tracker#323]
**Reporter:**
LowlyGent#1148
https://steamcommunity.com/id/big__aj/

**Summary:**
I paid $2000 to do the oxy run and when I get to the spot to sell it to the person that has been marked on the map for me, there is no-one for me to sell it to and its just stuck on that one person. 

**Steps to Reproduce:**
Go to the place where you get the oxy from, pay, and start doing it.

**Expected Results:**
A person is there at the spot where the GPS marked.

**Actual Results:**
There is no-one at the spot in which is marked on the map.

## Additional Information

**Screenshots:**

**Game Resolution:**
1920x1200

**Player Data:**
Character ID: 5997

**Notes:**

**Comment by LowlyGentAC** [comment]
![18100997170600607744_screenshots_20190731211652_1](https://user-images.githubusercontent.com/53545531/62258699-64af5c80-b3d9-11e9-987c-e3ab58dcfad2.jpg)
![18100997170600607744_screenshots_20190731211658_1](https://user-images.githubusercontent.com/53545531/62258700-66792000-b3d9-11e9-8318-c3ebc3bf0ff5.jpg)


![18100997170600607744_screenshots_20190731211645_1](https://user-images.githubusercontent.com/53545531/62258694-611bd580-b3d9-11e9-9b07-50af2b27e4f4.jpg)
![18100997170600607744_screenshots_20190731211538_1](https://user-images.githubusercontent.com/53545531/62258679-59f4c780-b3d9-11e9-8075-41ac1d901400.jpg)

**Comment by iGreatWhite** [comment]
The guy may have ran away because someone shot or startled them somehow. I got this bug before but couldn’t reproduce it.

**Comment by InZidiuZ** [comment]
Hey,

If the oxy ped is now alerted by something (gunshots, for instance) you'll receive a notification saying that the "buyer was spooked" and give you a new buyer, which hopefully solves this issue.

**InZidiuZ**
*OP-FW Developer*
