### ISSUE TITLE
Suggestion - Add parking garage at boat rental spots

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#3231]
### Assurance

I have read the `README.md`

### Summary

I know the first thing going through your mind is "No more garages we have so many". But I am requesting 4 garages to be placed around the city.  I went around and only picked the 4 spots that makes sense to have a "garage" or parking spot.  All of these would be tied to the Boating license just like the aviation garages. (Laura please don't smite me for another garage suggestion)

La Puerta Boat/Heli (Possibly attach it to the Aviation garage as well)
vector4(-682.37, -1423.65, 5.0, 262.78)

Paleto Boat
vector4(-1581.76, 5171.55, 19.57, 28.33)

Catfish View
vector4(3805.0, 4448.44, 4.04, 163.28)

Elysian Island
vector4(-333.62, -2774.91, 5.0, 237.56)

### Reason

As of right now there are not any close garages to any of the boat spawn places.  I picked 4 areas that have parking/garage spots where someone could theoretically park their car to rent a boat. I only suggest this is so someone can rent a boat and come back to their car and it will still be there. This is one of the main reasons I don't boat as much as my car usually despawns by the time I get back to it.

**Comment by coalaura** [comment]
Like you correctly assumed i am against adding these garages. paleto boat and catfish view don't even make sense for a garage.
