### ISSUE TITLE
Tuner Chil Update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3232]
### Assurance

I have read the `README.md`

### Summary

Either when your in the tuner chip, have its own unique action, (ie, E laptop2) something to show your tuning not just in /comp or /savings, also say if their is a tune applied maybe there could be a prop that gets added (ie. laptop on the passenger seat)

### Reason

To show a car is tuned and enhance the racing / drifting / tuning scene, also can show cops (some cities, servers made tuned chips illegal) so would help those cities out as well

**Comment by coalaura** [comment]
I dont see a need for this
