### ISSUE TITLE
Suggestion - TUNER SHOPS

### ISSUE THREAD

**Issue by nahkahnah** [InZidiuZ/op-framework-issue-tracker#3234]
### Assurance

I have read the `README.md`

### Summary

add REAL tuner shops where u can get deep into the car and customize it to your liking. same concept as a tuner chip except an actual shop and with how rare tuner chips are, make the cost of tuning equivalent as if you were buying a tuner chip off someone or base it off of rarity

### Reason

i think this would be great for the framework because there are plentifuls of people who are car heads such as myself and it would be a great way for the community to share their builds with each other, experiment different tunes and whatnot , and it could even be a learning experience for ppl who aren’t as familiar with cars as others.

**Comment by coalaura** [comment]
i dont think this would work out and also dont think its needed. The tuner chip is rare for a reason
