### ISSUE TITLE
Suggestion - throw away phones

### ISSUE THREAD

**Issue by eatAnus** [InZidiuZ/op-framework-issue-tracker#3236]
### Assurance

I have read the `README.md`

### Summary

burner phones with a random number and limited functionality that has x amount of uses

the information could appear here with a number, fake name and amount of uses
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/46156400/dff2ba08-6f10-4a99-810f-8dbf15add151)

(only has the phone app + could also be broken down? + shows completely random name in raspberry) 

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/46156400/5f14f210-be86-4a39-8489-599a5979612c)

### Reason

for the paranoid criminal rp enjoyers that'll allow for them to be truly anonymous; more unique rp

(side note: when anonymously calling with the regular feature in the phone it doesn't work properly and the person you're calling will see either your number or name)

**Comment by coalaura** [comment]
duplicate #2551
