### ISSUE TITLE
PD /fine Amount cap increase

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#3237]
### Assurance

I have read the `README.md`

### Summary

I am suggesting increasing the cap of the /fine command for PD given that your average fine is normally above 5k for most robbery & drug arrests which is the more common arrests. Maybe even make it a config for server managers to set, but my suggestion would be to raise internationals cap to 10k. Could possibly add a confirmation to it but not neccisary though imo. Having to split it into two fines while a minor inconvence becomes a pain over time. Previously your average fines were well below 5k but with the econemy shift, but that's defenitely changed. I agree a cap needs to be in place to prevent egregious accidental fines but 10k is a safe cap that will cover most fines.

### Reason

To help improve PD processing experience, and adjust to the current econemy/rp crime penalties.

**Comment by coalaura** [comment]
upped it to 8k for now
