### ISSUE TITLE
Suggestion - Bus Driver Job Improvements 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3238]
### Assurance

I have read the `README.md`

### Summary

After trying the Bus job I have some feedback for your consideration :)

- Instead of just stopping the engine, require the driver to open the door(s)
- Similar to other jobs, add a penalty for damaging the vehicle to encourage safer driving
- Add a "Schedule" where you have to reach the final stop in a specific time limit 
- Add some routes to Sandy / Grapeseed / Paleto that start and finish at the Dashhound Bus Center 

### Reason

More RP :o

**Comment by coalaura** [comment]
I've added some improvements with these ideas in mind and I've also added some more routes including paleto and grapeseed going through the dashhound bus center
