### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by meeksbtw** [InZidiuZ/op-framework-issue-tracker#324]
**Reporter:**
Meeks#5150

**Summary:**
While I was robbing a bank, I got through the first main vault door then, the second door but, when I stepped over the grey circle on the ground there was no UI telling me to use the thermite, I tried to "use" the thermite anyways, nothing happened, so I dropped the thermite to my friend that was in the bank, it worked for him for the first 2 then, the last thermite turned into a piece of steel allowing us only to get 2 of the 3 "vaults" This is the second time this issue has happened to me, so I would say 2 out of 16 bank robberies this has happened to me personally. (This was on server 2, no One-Sync) 

**Steps to Reproduce:**
Break through the first 2 doors and step over the grey circles on the ground and see if the UI pops up.

**Expected Results:**
The imagine of thermite popping up in the bottom center UI 

**Actual Results:**
No UI 

**Game Resolution:**
1920 x 1080

**Player Data:**
1673

**Comment by Masik52** [comment]
We had a similar issue yesterday at two different banks. Used the thermite to pop the vault door.  Once that opened everything inside was unlocked already so we could not actually gain anything from the robbery.  Here is a link to the clip of it happening.  https://youtu.be/uuGWGmTj690

**Comment by henryvolk** [comment]
same thing happened to me can i get paid for my lost thermite and time? I have a clip aswel

**Comment by InZidiuZ** [comment]
>through the first main vault door

Did you get through using a chip, or thermite?

**Comment by InZidiuZ** [comment]
Are you able to confirm whether this is still an issue after 1.3.10?

**Comment by Masik52** [comment]
The scenario I posted happened to us again last night. Thermite used to pop legion bank vault everything inside was unlocked already

**Comment by InZidiuZ** [comment]
Hey,

"last night" would've been before 1.3.10, so closing this for now as no more updates have come. If it's still happening, please create another bug-report.

**InZidiuZ**
*OP-FW Devleoper*
