### ISSUE TITLE
Suggestion - Aracade Bar Counter.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#3240]
### Assurance

I have read the `README.md`

### Summary

To move the Arcade Bar Store in the right and add an Arcade Bar Counter as shown in the screenshot below.

![arc1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/89df453c-0015-4f0b-8ad7-cf7f06267133)

### Reason

Its pretty annoying to jump over the counter and give items to customer after every sale

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/d432bc40-e251-4bc6-b3c5-3d96032d2991

**Comment by coalaura** [comment]
2 counters and moved the store

![yes](https://i.shrt.day/6TZXG2S095.webp)
