### ISSUE TITLE
Bug report - lottery 

### ISSUE THREAD

**Issue by Rachit280** [InZidiuZ/op-framework-issue-tracker#3242]
### Assurance

I have read the `README.md`

### Reporter

BornEvil

### Summary

Me and my friend together put 400k in lottery and we went before we invested the pot was at 10k and more people were also investing as they daily do but after investing 400k ourselves in lottery i only won 360k how can i win less than i betted

### Steps to Reproduce

Fix the lottery system and return the money we lost

### Expected Behavior

Fixed lottery system 

### Actual Results

Fixed lottery system

### Screenshots/Videos

I did to the legacy staffs

### Server

India (c8s1.op-framework.com)

**Comment by HollaYalla** [comment]
This is a intentional feature I believe as it functions as a Lottery Tax so you cant bet 400k like you did to win every lottery

**Comment by MetaHatter** [comment]
This is correct and working as intended. It's a tax. State needs money to run the lottery after all.

**Comment by coalaura** [comment]
breaking news: the lottery actually makes money
