### ISSUE TITLE
Suggestion - Add sound proofing to judges chambers in courthouse

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3243]
### Assurance

I have read the `README.md`

### Summary

Currently you can be heard out on the floor in the court unless you whisper. I think it needs some audio occlusion added for privacy if the judge is speaking back there.

### Reason

quality of life

**Comment by coalaura** [comment]
its a massive pain in the ass to soundproof a room through script

**Comment by scufflord** [comment]
> its a massive pain in the ass to soundproof a room through script

oh my bad i thought it was done that way. should i throw this in the asset github then?

**Comment by coalaura** [comment]
i can look into it

**Comment by coalaura** [comment]
done

![yes](https://i.shrt.day/7KCH7X2PY1.webp)
