### ISSUE TITLE
Suggestion - Outfit Item / Clothing Bags

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3245]
### Assurance

I have read the `README.md`

### Summary

In the clothing store, allow us to take an outfit out with us that is stored in our inventory.

Simply just press a button to "Fold Clothes".
It will give you an item called "Outfit: (saved outfit name)" and it will weigh 20su. Will look something like the image below. Once used, you will change outfit and that outfit will be gone from your inventory. (This will "throw away" / disgard your old outfit the same what that the clothing bag works now.)

With the addition of this, so that it doesnt make clothing bags useless, make the clothing bags multi-use. Allow them to pack 2-3 outfits, and once you change into one of those outfits, store your old one back into the bag. If you are changing outfit, you don't just throw away your old clothes.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/147753100/ce8640ab-74cb-4fcc-84ef-e8c652126742)

### Reason

Outfit Item - 
> Good for crime.
> PD can use "Dropped" clothing as evidence
> QOL

Clothing Bag -
> Also good for crime
> Useful for different activities through the day, like if you want to go hunting just put on your hunting outfit. Saves a trip to clothing store constantly.
> Makes it more useful than only being used once then having to go back to the clothing store anyway.

**Comment by King2704** [comment]
There's already an item like that ingame

**Comment by txxlrrsCoding** [comment]
> There's already an item like that ingame

Yeah, the clothing bag. Im suggesting to change that clothing bag to make it more useful and add a new item? Did you not read the whole thing?

**Comment by coalaura** [comment]
No, the clothing bag is one use only so its not too powerful
