### ISSUE TITLE
Suggestion - Realtor Co-Owners

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3246]
### Assurance

I have read the `README.md`

### Summary

Allow for multiple owners of the same real estate business aka co-owners

Many suggestions have come in asking for realtors to be able to give out keys but I understand that would be difficult due to scripting e.t.c. My suggestion is allowing for 1 or 2 co-owners to basically have the exact same access as owners with approval from the governor. This will help sell houses to people who aren't around at the same time as the owner as well as someone being there to manage the account, evictions, sales e.t.c when the owner can't be around (i.e when going on vacation).

### Reason

As we all know it's very difficult for real estate owners to maximise their sales as they aren't able to be in the server 24/7. This will help to bring more rp to real estate companies as well as spread the responsibility out. 

Roleplay that it could bring:

- Partnership/co-owner contracts (doj and state)
- State rp (background checking the co-owner, keeping tabs on them etc)
- More houses being sold
- More legal/civ rp
- Financial rp 
- Home security for tenants (i.e ensuring they don't lose their homes due to the company going bankrupt)

Over the past week I've been on vacation and lots of people have been wanting homes whilst I'm away however are unable to get these as I'm the only one who can hand out keys. It also came to my attention that my account went overdue whilst I was away. Having a co-owner would really help in these situations. It would be someone that the owner would trust to handle the money and evictions, just like a real co-owner. Their comp account would look exactly the same as the regular owner. 

Would also help in rp say for example the main owner dies, gets arrested, retires, goes missing e.t.c, the co owner would then take over. Also in situations where the owner doesn't have enough money and the account is overdue, the co-owner can directly help by putting money in the account if they please. This would also help to take away some stress from the governor in situations where the business just falls off and the governor has resell all the homes back to people.

**Comment by coalaura** [comment]
Went ahead and solved a few requests in one go. You now have an extra field when hiring/promoting employees. It defines their permission level (what they have access to and what they can do).

### Employee
*Can see all company infos but not actually do anything except use /enter and /storage. (Basically like previous employees and therefore the default)*

### Realtor
*Like the Employee level but the realtor can also sell, evict and transfer properties on their own.*

### Owner / Manager
*Has permissions to do anything, except promote/hire/fire other managers. (Can hire realtors and employees tho ofc)*

![yes](https://i.shrt.day/JP79UB5CY2.webp)
