### ISSUE TITLE
Suggestion - More FIB Items

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3247]
### Assurance

I have read the `README.md`

### Summary

Addition of burner phones or fake numbers and fake smart watches that match our fake ids

### Reason

Burner phones: When you make connections/friends with people whilst undercover but giving out your phone number might expose your identity. Also would be good for sting ops

Fake smart watches: Carrying your cop smart watch is risky in case you get kidnapped and they loot you, it will expose your identity. Not having a smart watch looks sus + it's nice to be able to have a gps whilst you're walking around. Having a smart watch that matches our fake ids will solidify our aliases

(lmk if i've put this in the wrong github, unsure if its an asset or a scripting suggestion)

**Comment by coalaura** [comment]
Duplicate #2551 (I've noted the smart watch thing)
