### ISSUE TITLE
Suggestion - Weed Processing in GW

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3248]
### Assurance

I have read the `README.md`

### Summary

Allow us to process weed in the back of GW. We already have weighing scales, and the environment is set up for it. We just need the option.

### Reason

Better RP, allows for us to "Quality control" the weed if its processed in store and not some dodgy shack in sandy. (which, by the way, is completely out of our way and means our staff have to transport large amounts of weed to sandy and back)

**Comment by scufflord** [comment]
processing weed is supposed to be done to sell to locals. why are you having to package and process legal weed?

**Comment by txxlrrsCoding** [comment]
We are permitted to harvest from the weed field. So we gotta process the buds into ounces somewhere.

**Comment by TacticalTyl3r** [comment]
> We are permitted to harvest from the weed field. So we gotta process the buds into ounces somewhere.

You don't have to process into ounces. You can use your rolling papers to make joints to sell. IMO should not have the ability to package into ounces to be able to sell there.

**Comment by txxlrrsCoding** [comment]
If this is the case, then you guys need to fix the brownies recipe. Brownies wont take the Bud, it only takes ounces

**Comment by coalaura** [comment]
No, it's intentional that you have to process the weed coming from a random field. I've added a processing spot inside GW (in the back).

**Comment by coalaura** [comment]
![yes](382.624, -817.193, 29.213)
