### ISSUE TITLE
Change weed selling location. 

### ISSUE THREAD

**Issue by Skai97** [InZidiuZ/op-framework-issue-tracker#3249]
### Assurance

I have read the `README.md`

### Summary

With the weed field coming back and people having something "new" to do. A lot of people are grinding it out and selling a lot of weed.

The pier is not a good selling spot. 90% of people are jumping into the water almost instantly whenever there is any cop presence. Often someone looking out.

Maybe move it to south side or just leave it around the trash area and maybe extend it up to fudge Lane etc. 

Police can investigate and lurk in the area but unless they are getting tackled and tazed instantly most are going for a swim. Poor interaction because of location

### Reason

Shit roleplay, avoiding police interaction or the possibility of even slightly getting caught. Most officers don't wanna chase someone diving straight to the bottom with tanks on.

Some officers aren't a high enough rank to use thermals on the helicopter to even find them. 

As a role-playing cop if you were to tackle or tase them instantly you're gonna deal with shit interaction "you're so cringe bla bla bla"

**Comment by coalaura** [comment]
This has already been done
