### ISSUE TITLE
Suggestion : Add clothes for other models other than Freemode_m while creating a new character.

### ISSUE THREAD

**Issue by WoooMonsta** [InZidiuZ/op-framework-issue-tracker#325]
**Name:**
- WoooMonsta⭐#0001

**Summary:**
There are a lot of good and distinct characters in the new character creations menu, which can make people look different and recognization. Due to the huge influx of new players everyone almost looks the same and i tried making a character from the preset models available in the game but i couldnt change their clothes / shoes etc. 

**Reason:**
It would let everyone make distinct characters which can be helpful in identifying everyone individually. Everyone runs around in a sleek sharp look with tattoos (to copy a few popular people) in the city. Would appreciate if we could have the clothing option available for all the characters in the character creation screen.

**Comment by InZidiuZ** [comment]
Hey,

This isn't up to me, all clothing is made by GTA, and those models simply don't have a lot of customization added due to them *not really* being meant to be used.

**InZidiuZ**
*OP-FW Developer*
