### ISSUE TITLE
Suggestion - Videogeddon Arcade Delivery

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3251]
### Assurance

I have read the `README.md`

### Summary

With the Arcade being added to the favorites in the phone, the demand for deliveries has slowly grown (bars). Since the Arcade is one of the businesses viewed by State as essential, it would make sense to incorporate a delivery system.  If the Arcade is on the same level as Burger Shot and Bean Machine in terms of providing essential services, it should be brought up to speed. It doesn't have to be an overhaul, but rather a copy/paste of what Burger Shot and Bean Machine have. 

The idea would be to have a spawn location to bring out a delivery vehicle to perform deliveries with. The perfect vehicle for this, that already has the Videogeddon logo on it, is the Go Go Monkey Blista. This addition would help alleviate costs associated with using personal vehicles for deliveries, which is expensive in repairs, refueling and oil changes overtime.

Potential Vehicle Spawn Locations:

 1.
![Vehicle Spawn 1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/74fdadf5-bd41-4974-a08b-c56944e2dc81)
2.
![Vehicle Spawn 2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/040ef612-6489-4305-9416-43e2eebb147a)
3.
![Vehicle Spawn 3](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/96219411/171ed531-35c3-4c96-85c4-c076d6112eb9)

I'd even take it a step further and request that the "local" delivery system be put in place as well, since that script already exists. This would diversify the income of those willing to put in time and work, without punishing them for not having anyone come into the business willing to purchase goods.

### Reason

It creates another way to interact with Arcade employees, as well put them in a position to succeed. Without this addition, there is no incentive to perform deliveries.  If there wasn't already a plan to add this, I think it would be a great addition.

**Comment by scufflord** [comment]
It's already hard enough to find arcade workers as is 90% of the time, I don't think sending them out on local deliveries would help that at all. Plus the profit from arena pills and z pills makes up for the time spent waiting, just like with midnight and ems 5

**Comment by navonody1** [comment]
> It's already hard enough to find arcade workers as is 90% of the time, I don't think sending them out on local deliveries would help that at all. Plus the profit from arena pills and z pills makes up for the time spent waiting, just like with midnight and ems 5

The idea is that if people are doing jobs for the business, they have to return to get another delivery. More traffic in and out of the Arcade is better IMO, when comparing to the state it's in now. The profit from no sales is $0, which is why no one wants to keep the business open, case and point.

**Comment by LusciousLuna** [comment]
Normally I would agree about the arena pills and Z pills, however as I have worked at Arcade since October I can say that the number of Z pills we sell are no where what you think they are. I have worked on avg 8 hour days inside the Arcade and not made anything before on multiple occasions. I have found that anymore people tend to either reroll their zombie pill daily or they go and buy z pills from other people for cheaper because they don't want to spend 1.5k per pill. As far as arena pills go since those do not degrade people will buy them in bulk and them sometimes go weeks or months without having to buy more. So Yes we can make decent money on them. But its all based on when people need them. We have recently had multiple people quit Arcade because they were not making money to live off of. I myself have to go hunting and mining jus to make money so I can pay rent.

**Comment by ristwell** [comment]
> It's already hard enough to find arcade workers as is 90% of the time, I don't think sending them out on local deliveries would help that at all. Plus the profit from arena pills and z pills makes up for the time spent waiting, just like with midnight and ems 5

If its as dead as you say (it isn't) people coming and going consistently literally alleviates that issue.

**Comment by coalaura** [comment]
I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".

**Comment by navonody1** [comment]
> I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".

Understandable. Is it possible to remove the business from the Favorites in the phones?

**Comment by coalaura** [comment]
> > I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".
> 
> Understandable. Is it possible to remove the business from the Favorites in the phones?

why would you want to remove it from the favorite list???

**Comment by navonody1** [comment]
> > > I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".
> > 
> > 
> > Understandable. Is it possible to remove the business from the Favorites in the phones?
> 
> why would you want to remove it from the favorite list???

Well, if it's not seen as essential, it's hard to justify having a hotline. It seems to have created an expectation that the Arcade won't be able to meet. I understand it's use was most likely an attempt to clear up Twitter messages of "any arcade?", but at the same time no other bars are listed in the favorites. Maybe I just don't see the vision you have for it.

**Comment by Thales1732** [comment]
I was just going to say there's probably been more times where I've reached out to the line and gotten someone to be there then has been me posting on twitter and getting someone...

**Comment by ThatSinisterGuy** [comment]
It would be nice if we could see which food places were open, like we can see the response services and mechanics. I get that would create a lot of clutter though.

**Comment by navonody1** [comment]
> It would be nice if we could see which food places were open, like we can see the response services and mechanics. I get that would create a lot of clutter though.

I think those services show up because they operate on a clock-in system, which bars and restaurants do not. Would be cool though, I agree.

**Comment by Thales1732** [comment]
They operate on an employee being close to the location if I'm not mistaken from what I've heard from mechanics if they're in the general area of any shop it shows the shop open. That's why sometimes you'll see it says a place is open but it's not.

**Comment by navonody1** [comment]
> They operate on an employee being close to the location if I'm not mistaken from what I've heard from mechanics if they're in the general area of any shop it shows the shop open. That's why sometimes you'll see it says a place is open but it's not.

Oh that's cool actually; I really like that addition.

**Comment by ristwell** [comment]
> I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential". 

I'd like to hear as to why you don't think it needs delivery. From the comment it sounds like you don't think it needs it not in regards to anything in the submission other than other businesses will want it, which to me means you think people will want this. so if people want it why do you think it's not needed.

**Comment by coalaura** [comment]
> > I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".
> 
> I'd like to hear as to why you don't think it needs delivery. From the comment it sounds like you don't think it needs it not in regards to anything in the submission other than other businesses will want it, which to me means you think people will want this. so if people want it why do you think it's not needed.

You are free to deliver to people, the reason why BS and bean have custom vehicles is for their local deliveries which is what i will not add to the arcade. Thats why i don't think custom arcade delivery vehicles are needed. You can deliver like all other businesses that are not BS or bean

**Comment by coalaura** [comment]
> It would be nice if we could see which food places were open, like we can see the response services and mechanics. I get that would create a lot of clutter though.

I didn't add it due to the sheer amount of other businesses. Also not all businesses are used in each subdivision and some businesses in other subdivisions may not even have a job, etc.

**Comment by ristwell** [comment]
> > > I don't think the arcade needs delivery. If it was added all other businesses are gonna want the same thing. The arcade already has a bunch of unique items only available there. I don't think the arcade is "essential".
> > 
> > 
> > I'd like to hear as to why you don't think it needs delivery. From the comment it sounds like you don't think it needs it not in regards to anything in the submission other than other businesses will want it, which to me means you think people will want this. so if people want it why do you think it's not needed.
> 
> You are free to deliver to people, the reason why BS and bean have custom vehicles is for their local deliveries which is what i will not add to the arcade. Thats why i don't think custom arcade delivery vehicles are needed. You can deliver like all other businesses that are not BS or bean

employees are discouraged from participating in that RP so much so that its not happening. this would alleviate that. custom vehicle for RP delivery does not have to be intrinsically tied to local delivery.
