### ISSUE TITLE
Suggestion - Changing area inside of Luxury Autos 

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3252]
### Assurance

I have read the `README.md`

### Summary

Hi I am Senior Salesman of Luxury Autos and I would like the suggest a area to change cloths inside of the shop for employees. We do have certain cloths that we were when we work and we would like to be able to change at the shop instead of going to a clothing store.

### Reason

Employees always have to go to a clothing store to change into or out of work cloths and I would like to make it easier for all the employees that work at Luxury Autos

**Comment by coalaura** [comment]
done

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/6UKTKV72VL.webp)

**Comment by darkness511** [comment]
![218_20240307003838_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/d70f82e9-466f-41c8-9abd-f501d5f46309)

Can you change location to this, as above one is office area.
(imagine in a meeting an employee comes to change dress)

**Comment by darkness511** [comment]
> ![yes](https://camo.githubusercontent.com/2f5a35bd695e4558448cfc750f49f89f62cc547bbce57dcff8acad8b4a272a9a/68747470733a2f2f692e736872742e6461792f36554b544b563732564c2e77656270)

can you change like above? would make more sense as we mostly do meetings in office.
