### ISSUE TITLE
Suggestion - Add one Aviation office for operating.

### ISSUE THREAD

**Issue by Cenazz** [InZidiuZ/op-framework-issue-tracker#3255]
### Assurance

I have read the `README.md`

### Summary

Add one Aviation office for the pilots those who will work for the department for thise who want to come atleast know where to apply and also pilots will get a outfit change location and storage for essential things for flying.

### Reason

I have already opened this business in legacy server and there are many other people i hired to teach others how to fly and we are facing problems like people don't know where to come for applying licences and pilots don't know where to store flying gears like parachutes and headphones and all therefore it's getting puzzled.

**Comment by coalaura** [comment]
There is no need for an office for pilots. International server has had an aviation company without an office for over 3 years now without a problem or there ever being any need for it

**Comment by Cenazz** [comment]
Yea may be but if nothing is changing and going on a constant way then i think there may be a need of change and in real life too there is some place where we go for licence and ask them for the forms right it's not a selling business that agents will move around and sell "you will get licence for 100 come to me come to me" this doesn't make sense right and if no office then if someone is planning for a new kind of rp it's not possible i think and if we still follow the old way then why don't you use type writers and work with pen and paper instead of using amy kind of gadgets XD XD
