### ISSUE TITLE
Suggestion - Make restaurant trash cans into shredders

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3256]
### Assurance

I have read the `README.md`

### Summary

Make trash cans like these and the ones in burger shot be shredders that only accept food items, and paper bags. I've worked at both Bean Machine and Burger Shot and a lot of my day is running around collecting food and bags people just drop on the ground and hiding it somewhere else, or re-using the bags. 

https://i.ibb.co/BK068Nq/Crosshair-X-Ms-GYAy2-K5-Y.png

### Reason

Quality of life thing

**Comment by coalaura** [comment]
just put them in the trash can, i dont see a reason to make them shredders, they are big enough to put a bunch of shit into and wipe with the server restart

**Comment by scufflord** [comment]
well they also don't work as a trash can lol

**Comment by MetaHatter** [comment]
When I worked in fast food they had dumpsters outside that we took the trash out to.

**Comment by scufflord** [comment]
which would be great, if there was also a trash can inside for it to go in first so customers stop leaving it all over the floor
