### ISSUE TITLE
Suggestion - Garage block fix in Luxury Autos

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3257]
### Assurance

I have read the `README.md`

### Summary

Hi I am Senior Salesman of Luxury Autos.
I would like the suggest to reduce range or area/ of our garage. We do have _**certain bay which is not usable**_, and we would like to be able to change that as customers who want to hold/sell instead of waiting at bay has to go inside where already other cars are parked for sell making it hectic and crowded.

![garageblock](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/1cbe5a96-0883-4c31-aecd-f9d6166e8204)

### Reason

We use the first bay for garage and _want second bay_ (which we cant use as garage gets blocked) for having interaction with customer cars and holding/buying cars with them.. As you can see in above described picture its too far, still we cant' spawn vechile or use garage as its blocked.
We can make good use of it, rather than going inside where all cars are already parked and full.

Since Luxury Autos is already filled with cars when open, and there are 2 bays one for garage and second one is un-usable as garage gets blocked due to the range... 
It will be great initiating hold/sell interaction with customer on the bays. Improving better RP for customer to us
![la_open](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/3b6c802d-f358-4db3-a919-dbf54801c1fb)

**Comment by coalaura** [comment]
fixed

**Comment by coalaura** [comment]
there has not been an update that's why

**Comment by ayushpatel1007** [comment]
maybe u have to create new issue because this issue is closed

**Comment by coalaura** [comment]
i will look into it
