### ISSUE TITLE
Changes in Real estate 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3259]
### Assurance

I have read the `README.md`

### Summary

#3246 So recently introduced that realtors can give keys of houses and having another role of employee that can see all company info but can’t do anything.

I think , there is no need for employee to see all house and company balance and company income etc. as before , employees can just enter houses and same as before , do access storage etc 

### Reason

I think, real estate companies have already done everything to let employees see what houses are available. Showing them all the company info from A to Z is I think not needed

**Comment by ayushpatel1007** [comment]
![Uploading IMG_1775.jpeg…]()

**Comment by CloudCait** [comment]
I agree also that employees shouldn't be able to see these details, only realtor+ should. However it's not that big of a deal I just make sure I only give people the employee role who I trust and ensure that leaking addresses/using them for personal benefit would be breaking data protection and therefore would result in their removal. Realistically any estate agent would be able to see this info.

**Comment by scufflord** [comment]
sounds like something that could be solved with some fun legal rp with a lawyer to have your employees sign non-disclosure agreements that would hold them liable in court if breached.

**Comment by coalaura** [comment]
I don't think its a big deal for them to see it but sure

**Comment by ayushpatel1007** [comment]
@coalaura So you are hiding it for employess?
