### ISSUE TITLE
Suggestion - Inventory storage in Paleto's Hen House

### ISSUE THREAD

**Issue by Breezy368** [InZidiuZ/op-framework-issue-tracker#3261]
### Assurance

I have read the `README.md`

### Summary

Discord: cryptic1776

Other bars have storage lockers and its difficult not having it trying to sell extra fun things that are going around in the city like bbq sandwiches.

### Reason

This allows for much easier use of extra ways to make money in the bar, instead of the cheap and RP food players would actually get filling meals or other products that can be sold there!

**Comment by coalaura** [comment]
Do you mean a locker for employees? Or a shared storage

**Comment by Breezy368** [comment]
Locker for employees

**Comment by coalaura** [comment]
i didn't really know where to put the lockers but i put em in the staff office here

![yes](https://i.shrt.day/5DOFWUD305.webp)

**Comment by Breezy368** [comment]
Awesome! Thank you!
