### ISSUE TITLE
Suggestion - Beans added to the city

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#3262]
### Assurance

I have read the `README.md`

### Summary

I am suggesting that beans be added to city in the stores or somwhere to be purchased. The prop exists for it already and people like Officer Dred eat them all the time, and it would be cool if they were an actual food item for others to enjoy. When eating the beans food item it should play the beans prop emote continuously unti the player stops it as it would be silly to watch players contiunously eat beans when consuming them. I feel adding this would really enhance the roleplay of others that already pretend to eat beans and could lead to some interesting rp stories with giving people flatulence. I further suggest it becomes a trash food item as well and call it "Moldy Beans" as it would really enhance Johnsons Farting to the greatest of heights. Please see the attached gif of dred currently using the prop emote of eating beans for the example:

![OWN3D_Desktop_Overlay_QE0s2DNZuN](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/44896032/c925ff96-db65-4264-9dd8-48db56531fe2)

one for the store:

![beans](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/44896032/69f5a110-4123-4f1d-841c-6ce7e4753c8c)

and one for trash beans lol:  

![trash beans](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/44896032/9b22fda9-560a-4984-a175-0918b8d05ff4)

### Reason

To give us amazing roleplay with the simplistic item like beans beans the musical fruit, the more you eat the more you toot.

**Comment by coalaura** [comment]
lmaooooooo yesss

**Comment by scufflord** [comment]
YES MATE GIMME SOME BEANS ON TOAST TOO LMFAOOO
