### ISSUE TITLE
Suggestion - Add contraband drops into prison

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#3263]
### Assurance

I have read the `README.md`

### Summary

Add more drops to prison jobs and/or prison trash bins. 

- Lockpicks (1 in 10 odds)
- Broken Bottle (1 in 25 odds)
- Shank (GTA Native Weapon)  (1 in 25 odds)
- Rocks (Would be a new weapon that replicates snowballs but hits harder)  (1 in 20 odds)
- Joints (1 in 7 odds)

(Note: i kinda guessed odds based on how many jobs you do whilst on a stretch in prison, however i do feel they could do with some work)

### Reason

This would allow better RP for prisoners, HUT, 51-50's and DOC as it opens up more opportunity for prisoners to be able to counter other prisoner attacks as well as give DOC a reason to search prisoners along with actually be fearful for their life in prison rather than just being worried about getting punched.

- Lockpicks would allow prisoners to break cuffs (and possibly allow them to pick certain locks within the prison in the future)
- Broken Bottles, Shanks and Rocks would be part of the offensive tools, allowing prisoners to use semi-lethal weapons against eachother, and DOC if they so choose. However attacking DOC will be heavily sanctioned.
- Joints allow a bit of stress relief as well as allow the possibility for prisoners to turn it into a "prison currency" within the prison grounds.

**Comment by coalaura** [comment]
> Rocks (Would be a new weapon that replicates snowballs but hits harder)

idk how to make weapons lmao

**Comment by coalaura** [comment]
The dumpsters already have a chance to drop lockpicks i believe, i've made them better than similar dumpsters of that size

**Comment by coalaura** [comment]
I can look into potentially having some rare drops in the prison missions themselves, kinda like "you found 1x xyz on the ground"

**Comment by coalaura** [comment]
> Shank (GTA Native Weapon)

Which weapon do you mean with this?

**Comment by gadjinee** [comment]
> > Shank (GTA Native Weapon)
> 
> 
> 
> Which weapon do you mean with this?

Probably switchblade, I believe you can find those already

**Comment by hell-of-the-devil** [comment]
My apologies @coalaura, i'm stupid, the shank scene is a DLC scenario as far as i can tell.

**Comment by hell-of-the-devil** [comment]
i'm fine with the odd switch blade getting into prison tbh, as long as you're okay with it!

**Comment by coalaura** [comment]
I've added the drops. Made them pretty rare for now, if it turns out to be too rare let me know and i'll bump them up
