### ISSUE TITLE
Suggestion - Reduce Pigeon Milk cost at Videogeddon

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3264]
### Assurance

I have read the `README.md`

### Summary

It appears that the behind the counter cost of pigeon milk at the Arcade bar is x2 more than any of the other shops that are available to the public or even other businesses.

### Reason

Currently an item that is never sold by Videogeddon because the prices can't compete.

**Comment by coalaura** [comment]
not sure why it was set so high, i've reduced it
