### ISSUE TITLE
Suggestion - Social Activities at the bar / Other money makers for bar employees

### ISSUE THREAD

**Issue by Breezy368** [InZidiuZ/op-framework-issue-tracker#3266]
### Assurance

I have read the `README.md`

### Summary

Edit: To clarify I didnt know how to ask if any of these ideas were okay, and instead of bombarding yo uwith a bunch of separate tickets I figured we could brain storm (because I was having a conversation about this in a discord, they also wanted to put in some input as well) in one ticket and then make more as your team can go through our ideas and help us figure out whats realistic and whats a pipe dream. If you can just put any of the ideas in here that could be deemed "possible" Ill make a ticket for each one.

Currently drugs are sold by going to a local and handing them something. What if there was a legal way to sell to locals around all the bar locations beers from the tap? I think it would pay something like 100 bucks per beer (approximately) and so theyd make maybe 90 dollars in profit? And also it would be completely legal just selling to locals on the street? The other thing is this would show the people employees are nearby because maybe they're carrying a crate of beers to local businesses or something? Like make 50 dollars for walking this case of beer from the bar to the tech shop in paleto, then it would give another close local business?

This is my starting point to try and make owning a business and being an employee of a bar a bit more enjoyable. Right now I find myself sitting around for many hours at a time with nothing to do, just wanting to fly out. This is why bars are never open in the city.

If there was something, anything to do in the bar that was unique, playing darts, pool, poker, anything really I feel like it could 1. give the employees something to do while they wait for customers besides listen to music / watch videos  and 2. give more attractions and uniqueness to bars.

I'm definitely open to discussing in this thread any and all ideas if that's okay? I just want there to be more social things to do.

### Reason

Right now bars aren't open for two main reasons, its like a catch 22... no one thinks they stay open so no habit formed. And theres nothing to do for employees when no one shows up. Having some intermediary thing to do inbetween would make it worth while having the business and also keep it moving and fun.

**Comment by CloudCait** [comment]
Unsure if this is still a thing but also could be an idea to remove vodka drops from chop runs so that people have to go to bars to get vodka for crafting (thought i’d drop this here instead of opening an entire new github for it)

**Comment by scufflord** [comment]
Also not sure why the arcade sells alcohol to be honest. That place is super overpowered by having food, alcohol, and their specialty unique item there. Honestly should get taken out so more bar rp can happen for the actual bars in the city.

**Comment by Breezy368** [comment]
add dailies/recipes that require liquor

**Comment by navonody1** [comment]
> Also not sure why the arcade sells alcohol to be honest. That place is super overpowered by having food, alcohol, and their specialty unique item there. Honestly should get taken out so more bar rp can happen for the actual bars in the city.

I've actually suggested that alcohol be replaced with fruit so we can make smoothies instead, but that wouldn't make sense for the current MLO with all the alcohol signs and bottles everywhere. Also, you made a presupposition that ANY bar RP even happens there...it doesn't. People come for VR and sometimes food, but that's it. I've even went out of my way to coordinate with other bars and use their stores for events and things in the past. Arcade even sells alcohol at a higher cost to encourage people to go buy alcohol elsewhere, because I agree 100% that bars suck in this city.

**Comment by MetaHatter** [comment]
I say Arcade should be beer only and make sure beer kinda sucks...

**Comment by navonody1** [comment]
@Breezy368 Definitely feel your pain on this. I've been around long enough to see worker's fatigue first hand. I've been sitting on an idea for awhile that kind of relates to this suggestion; maybe this can help #3269.

**Comment by Breezy368** [comment]
> @Breezy368 Definitely feel your pain on this. I've been around long enough to see worker's fatigue first hand. I've been sitting on an idea for awhile that kind of relates to this suggestion; maybe this can help #3269.

Great add, I upvoted will read into it later, learning lua atm :)

**Comment by coalaura** [comment]
I don't mind adding a prompt to buy a local a beer but i don't think a whole system for selling alcohol to locals is needed nor makes sense (Also not quite sure how "legal" that would be theoretically). Playing darts was actually just suggested here #3267, but at the moment we are 2 script developers who do this in our free time so it will very likely be quite some time until that has reached the top of the to-do list.


> Unsure if this is still a thing but also could be an idea to remove vodka drops from chop runs so that people have to go to bars to get vodka for crafting (thought i’d drop this here instead of opening an entire new github for it)
@CloudCait I don't mind removing vodka (or other spirits) from chop and other places (or at least making them a lot rarer)

> Add zombie pills to bars?
@Breezy368 that wont happen

> I've actually suggested that alcohol be replaced with fruit so we can make smoothies instead
@navonody1 wherever you proposed said change it must have gone past me. Usually github it a for-sure way to make sure something is looked at by a dev. I'd totally be down to replace most alcohol with fruits, could even make them a bit cheaper than the fruit stands?
