### ISSUE TITLE
Suggestion - Add ability to name printed items

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3268]
### Assurance

I have read the `README.md`

### Summary

Using the Printer and when it prints out? There should be an option to name the photo or document you printed. Simply an extra box or something, also maybe adding in a file folder for us lawyers! 

### Reason

Naming Documents and photo - when stuff get printed it says “Printed Card” there is no way to tel which card it is other then opening each one, would be helpful to see which cards ur grabbing before hand

File folders - just like a wallet a spot to store some documents, maybe 12 Spots per folder, and buyable at the printer store or Walmart! This could be a great use for lawyers so we can keep all our written document separated and organized!

**Comment by MetaHatter** [comment]
Another extension to this might be adding the ability to print a stack of the same cards.  

- Before printing enter a name and quantity. 
- Card prints all the cards in it can based on defined qty and available blanks.
- When progress bar is done, stacks the cards and names the stack/cards accordingly.

**Comment by scufflord** [comment]
Stacks of cards could work like a cigarette pack as well. say you have a stack of 20 cards and want to give one out. you use the stack, it gives you an individual card, then you hand that card over. once the stack is used up instead of becoming a "decayed" stack of cards, it just turns into a single card

**Comment by coalaura** [comment]
Dont need a complicated card stack, just make the items stackable. Much simpler

![yes](https://i.shrt.day/EFW4024KCN.webp)

Also added a title field and changed the printer to not reset the fields after printing. So once you've printed one, as long as you have enough paper you can just hit print again with the same settings. As long as you dont fully exit out of the menu

![yes](https://i.shrt.day/AN1WFOVHO8.webp)
