### ISSUE TITLE
[Phone Suggestion] Contacts Online

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#327]
**Name:**
Who is suggesting this? iGreatWhite#3018

**Summary:**
Making it so that we can see which contacts are in the city would help to see which people I can text or call in certain situations or trying to sell stuff to. Its hard to meet up with proper when you text them and don’t get an answer back because they are not in the city.

**Reason:**
Why would your suggestion be a good addition to Legacy? So that it makes it a lot easier to see who is around at the time and who is not.

**Comment by Anderzenn** [comment]
Hey,

This is a planned feature for the new phone that we're working on.

**Anderzenn**
*OP-FW UI Developer*
