### ISSUE TITLE
Suggestion - Make Paychecks Great Again 

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3270]
### Assurance

I have read the `README.md`

### Summary

Revert the change that was made back in the days before the auto-afk unload feature was added so that when off duty PD and EMS will receive their full paycheck.

### Reason

Encourage more people to actually go out and roleplay and do things off duty instead of feeling like all they can do is wake up and go do their job. For example I'm a cadet right now and while off duty I'm not even making as much as my criminal characters paycheck at Bean Machine as a waiter.

**Comment by coalaura** [comment]
Cadets make $64 an hour on-duty, off-duty is the normal paycheck * 0.4, which is $25.6 rounded down $25. How about this, i'll make it 50% ($32 as a cadet)

**Comment by TacticalTyl3r** [comment]
> > Cadets make $64 an hour on-duty, off-duty is the normal paycheck * 0.4, which is $25.6 rounded down $25. How about this, i'll make it 50% ($32 as a cadet)
> 
> I mean it wasn't so much of like a specific cadet issue, just more so trying to get people to actually have lives for their characters beyond their job while still making a fair wage. State workers and state security make $78 and $80 per hour all the time because of what they do, so why shouldn't cops, doctors, firefighters etc?

I remember when I first started out we got full paychecks on/off duty. Then when this was first implemented we got 10% so an EMT off duty used to get $5 a hour until it was increased to what it is now.

**Comment by coalaura** [comment]
i think 40% -> 50% is a good start, no?

**Comment by scufflord** [comment]
I just don't understand why it's even still a thing just for these two job types but not for any of the other high paying jobs.
