### ISSUE TITLE
Suggestion - Videogeddon Arcade Alcohol Replacement

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3272]
### Assurance

I have read the `README.md`

### Summary

This is a request to replace the alcohol in the Arcade store with fruits. If possible, keep the cider and beer, but replace/remove the other "hard liquor" items. Also, if a permanent blender is able to be set up somewhere on the counter, that would be great; no big deal if not.

### Reason

Arcade very RARELY sells alcohol. The business doesn't really operate in the same way other bars do, so there's no need for the hard liquor options. Those should only be available at the other bars in my opinion.

**Comment by scufflord** [comment]
Some video game inspired flavor combo smoothies would be dope to see, either with a permanent blender or with people having to use their own. This is a W idea.

**Comment by coalaura** [comment]
all done, for the permanent blender you'll have to go ask the [asset guys](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues), but any `prop_blender` object should work as a blender now

**Comment by MetaHatter** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/84351858/1ff97e44-4a62-441e-8ec0-ef28b689fd8c)

**Comment by navonody1** [comment]
@coalaura thank you kindly.
@MetaHatter I was just about to put in the request on the asset Github...very much appreciated!
