### ISSUE TITLE
Suggestion - Luxury Autos have TV panels that don't work with a remote

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3274]
### Assurance

I have read the `README.md`

### Summary

Not all businesses have TVs, so this isn't a request to add non existing TV panels in spaces where they aren't. This is a request to add WORKING TVs to Luxury Autos that already have existing panels that DO NOT work with remotes.

### Reason

![la_tvoff](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/d2f97e60-e452-47d5-b3c3-d4e28f6f08cf)

 Implementing these changes will promote future content creation by way of displaying commercials, menus that display proper pricing and other potential value.

having working TVs in the businesses would help to encourage creativity and also make processing purchases a little smoother. 
But if a tv for example works we can have a digital menu up for all to see at the same time.

**Comment by InZidiuZ** [comment]
This has now been fixed. They should be usable on next update.
