### ISSUE TITLE
Suggestion - Bleach Boom

### ISSUE THREAD

**Issue by andrwe777** [InZidiuZ/op-framework-issue-tracker#3275]
### Assurance

I have read the `README.md`

### Summary

Now that the pd can id a person just by them being in the car when they get out of the car. I suggest that the crims get something to counter this, aka a bleach boom would be great in this situation because it would wipe out any traces of the DNA in the car. That would allow the crims a chance to fight the DNA swabs because at this minute, there is a very high possibly that if they get your DNA at a crime scene they will put a warrant out for you.

### Reason

To try and get a way to erase any DNA for getting collected by pd.

**Comment by JennyLynn001** [comment]
I think adding this would be a great idea.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/3Q31ZF8YU3.webp)
