### ISSUE TITLE
Suggestion - Advanced Auto Pilot

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3276]
### Assurance

I have read the `README.md`

### Summary

This is for a more advanced auto pilot/cruise control for Planes and Helicopters

First there there will be a new items similar to the Self Driving Chip but a Self Flying Chip now this won't fly the plane on its own like taking turns but what it does do is it will allow you to swap seats and will continue flying straight (PLANE ONLY)

For Helicopter when you activate it the helicopter will hover even if your not in the driver seat for 5 minutes (MAX) before the engine shuts off and it falls to an explosion but a counter to this is if a Radio Jammer is near the chip is useless and shuts off and has a cool down so if you are in a heli/plane and fly by a jammer the chip will become useless for 10 minutes

### Reason

Better Auto Pilot

**Comment by ayushpatel1007** [comment]
Why pilot will start auto pilot and sit in another seat? I mean this is nothing new he can do on another seat and just sit.

**Comment by HollaYalla** [comment]
Like go to the "bathroom" or something idk it would just be fun to have, yes people would probably commit terrorism with it but I mean it adds something new

**Comment by coalaura** [comment]
If you switch the seat your plane will crash. The autopilot is already very advanced. You can increase/decrease the speed altitude with up and down arrows (+ shift). You can turn using arrow keys left and right.

I really don't think a hugely complicated system is needed just so you can switch a seat while flying

**Comment by coalaura** [comment]
besides, most planes can fly from the bottom of the map to the top in less than 5 minutes, just fly the plane
