### ISSUE TITLE
Medium Size Trailer Update / improvements

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3277]
### Assurance

I have read the `README.md`

### Summary

Being able to tow / untow a car well hooked up or detatched, 

### Reason

Right now if you try and tow a car well the truck is attached it starts untowing and merks everything up, instead change the /Tow for trailers to /Trailer that way those 2 don’t interfere

Also! 

Make it a bit longer up the price and call it a large trailer, 2 cars. You would use it the following way; 

/Trailer 1 will connect it to the most north spot of the trailer
/trailer 2 will connect it to the most southern spot of the trailer

**Comment by coalaura** [comment]
im not quite sure what you mean, do you have a clip of it happening?

**Comment by SluggsV2** [comment]
> im not quite sure what you mean, do you have a clip of it happening?

Seems to be working a bit better and depending on the damage of ur truck, can I suggest adding us to tow medium sized SUVs in trying to tow my track hawk and can't :(

**Comment by coalaura** [comment]
the trailer is meant for small things, if you wanna tow big vehicles you should get a tow truck

**Comment by SluggsV2** [comment]
> the trailer is meant for small things, if you wanna tow big vehicles you should get a tow truck

It's a medium size car trailer! SUV's should be no issue, 

There is tons of rp behind these trailers, and haven't heard anything but good things about them since our city discovered them 2 days ago! 

I would become a tow driver but simply don't want to loose my lawyer job, I like to off road and rip it through the mud on weekends off and bring beautiful built cars to car shows! 

It may not seem like big roasted potatoes but trust me they get used!! 

For example, I can put a Lifted Bronco on it but not a TrackHawk, 

Trucks, Utility, and larger sized vehicles I agree shouldn't but a family sized SUV should!!

**Comment by coalaura** [comment]
You dont have to be a tow driver to use a tow truck, the /tow command is available for anyone even on tow trucks. The medium size trailer supports all vehicles up to a certain length. Basically all vehicles that fit on it comfortably. If the vehicle cant be towed on it then either call a tow driver or buy a tow truck. The trailer is designed to carry most small vehicles including motorcycles. Its not meant for towing cars
