### ISSUE TITLE
changing main door of mansion

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3278]
### Assurance

I have read the `README.md`

### Summary

Change main entry door..

Block: Kimble Hill drive 
House : kimble hill 6

Curret entry 
![Screenshot (443)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/7e99866d-a719-40b1-baff-ea49710162f5)

New Suggest Entry
![Screenshot (444)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/22e528af-a3fa-404c-8e22-634eec435920)

### Reason

it is more functional and near to garage. With current door, we have to jump to stairs and then enter

**Comment by coalaura** [comment]
the main entrance is by the stairs, it makes sense
