### ISSUE TITLE
Suggestion - Invention Court move main entrances

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3279]
### Assurance

I have read the `README.md`

### Summary

So currently every house of invention court that have 2 doors are little less functional. 

Taking example of invention court 10,

"Garage with back door"
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/f6a4bc8c-572a-43a0-af7d-96c908f27317)

"House Main door"
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/e8dfac7a-dfd1-46d8-88d4-07c9b23da7c8)

So we cant knock of back door, so maybe to make doors of this block more functional , we can swap back door with main/front  door
or We can allow /knock of back door.  
whatever take less work for you.  

### Reason

this usggestion is More functional then current setup

**Comment by coalaura** [comment]
you should now be able to knock on back doors
