### ISSUE TITLE
[game/identification] Old IDs should be flagged stolen

### ISSUE THREAD

**Issue by MaxFunoff** [InZidiuZ/op-framework-issue-tracker#328]
**Name:**
psyCOSMO#0476

**Summary:**
When ever someone takes a new ID out from the courthouse the old one should be flagged stolen.

**Reason:**
Too many people wondering around with stolen IDs, and like in real life the old one should be flagged.

**Comment by SATIN187** [comment]
How would that be possible. In real life your is number is the same how would they flag your I’d as stolen?

**Comment by psyCOSMO** [comment]
> How would that be possible. In real life your is number is the same how would they flag your I’d as stolen?

You have a card number on that ID, not only the ID number.

**Comment by twooot** [comment]
Yeah i dont think this is very realistic
