### ISSUE TITLE
Suggestion - Move Invention Court 22 main entrance

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3280]
### Assurance

I have read the `README.md`

### Summary

This is invention court 22 house in block "INvention Court"
Currently we have to jump on either side of door to reach main door of house

House Front VIew
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/3587b40b-c275-46b7-bd48-fa43e71bae4e)

How currently we enter house (Back door)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/b702d160-468b-4741-a706-27f99a7a7b9b)

House Main Entrance which is back side of house
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/9715d937-f371-4ab7-babb-0a94c7da02ea)

What we can do is , we can use below door to enter house. Obiously it is not pratical the that door goes no where but also jumping to enter house is also not pratical and also because we cant make this door openable/movable.
![Screenshot (466)](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/5ff887b2-37d5-44f3-b433-cbcc1426d7cb)
 

### Reason

I mean i take survery of people asking them that will they buy a house where they have to jump doors to reach to main door of house to enter house, i belive 99% people will not buy. Also there is no question that this is not functional at all.

**Comment by coalaura** [comment]
#3279
