### ISSUE TITLE
Changes in Real Estate (Only for Employee Post / Not for Realtors post)

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3281]
### Assurance

I have read the `README.md`

### Summary

Reference #3259 : So in #3259 this suggestion , i told that agents doesnt need to see what we see in /comp. 
U did hide the company balance and income but what i was exaclty teliing was to hide everything which is not meant to see by agents.

generally if we even talk about IRL, companies just share details of house which are for sale and not every house company own and rent. Also #3259 , i was suggest to hire trusted people and make some aggrement with agents so that they dont leak information, but there is no use of that because we cant stop anyone sharing screnshot from /comp tablet .. if they even do, we will never know...

what i was telling was that agnets dont see anything in /comp or 

Image 1: Only show company name , ceo and year.. Showing Employess is okay but not their salary/permission.. Dont show share's info
![1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/5d4a01c5-d036-48bf-9eb9-3a61d80abecd)

Image 2: Blocks : Seeing Block is no need for agent. He just need to see what house is empty so that he can sell it. In block info , there is no imformation agent need to see.
![2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/4397cde1-e981-4708-bc87-f92b4522ce19)

Image 3: Commpany Property.
This is thing that agent can see... Where he can see what house are Empty.. He should not see houses that are sold.. Once the house is sold and is not empty ..there is no need for agent to see info for sold out house. 
![3](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/5fba8d36-98d4-4bf3-95da-ec858b88e449)

### Reason

Things that are currently agents are able to see is great issue as per my personal opinion.  I dont feel safe sharing companies private info like who much it cost company house and stuff...

**Comment by scufflord** [comment]
im gonna be honest my guy... sounds like you need to either hire more trustworthy employees or make them sign NDA's. every other realtor loves the new changes that happened.

**Comment by ayushpatel1007** [comment]
NDA is just piece of paper in rp that will i think will useless.. Talking about hiring trusted person.. So we are talking here about ompany and company dont run always on hiring trusted people.. We always compare rp with IRL then think about what you said about hiring trusted people.

**Comment by King2704** [comment]
The profit for your realtor company is also just some pixels on your screen. Not like someone is gonna think about robbing you irl because he saw how much your realtor company in the server makes

**Comment by ayushpatel1007** [comment]
> The profit for your realtor company is also just some pixels on your screen. Not like someone is gonna think about robbing you irl because he saw how much your realtor company in the server makes

 i never talked about getting robbed but thank u for this wonderfull opinion of yours

**Comment by King2704** [comment]
what are you talking about then? what makes your company information so secret that you dont want anybody to see?

**Comment by ayushpatel1007** [comment]
> what are you talking about then? what makes your company information so secret that you dont want anybody to see?
 you mean you are comfortable to let your tuner shop employess see all the things as employee that u see as owner?

**Comment by King2704** [comment]
yeh since publicly listed companies have to publish a sheet with all their profits and stuff anyways. and if people sell houses for you then they will be able to see all the blocks you own just by selling houses from those

**Comment by ayushpatel1007** [comment]
> yeh since publicly listed companies have to publish a sheet with all their profits and stuff anyways. and if people sell houses for you then they will be able to see all the blocks you own just by selling houses from those

Who told u that we have to publish a sheet with all profit ?

**Comment by King2704** [comment]
Its called a company register. (each country usually has one accessible to the public)

**Comment by ayushpatel1007** [comment]
> Its called a company register. (each country usually has one accessible to the public)

we dont in rp bro

**Comment by ayushpatel1007** [comment]
> yeh since publicly listed companies have to publish a sheet with all their profits and stuff anyways. and if people sell houses for you then they will be able to see all the blocks you own just by selling houses from those

So i didnt knew about IRL thing about public company but as per google , its meaning is as below
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/115968667/5bf9cc8f-3080-4923-90b2-c98d3d5add86)

**Comment by MetaHatter** [comment]
This isn't a place to argue it's a place for feedback. DM if you want to 1v1.

**Comment by coalaura** [comment]
I agree with what scuff said. Employees should be able to see the blocks and properties so they know what properties there are in the first place. I hid everything else that isn't needed by an employee
