### ISSUE TITLE
Suggestion - Allow PD to collect evidence if off duty

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3282]
### Assurance

I have read the `README.md`

### Summary

Change evidence gathering vs destroying to something that is tied to undercover like drawing a weapon is.

### Reason

quality of life in case something happens while an officer is clocked out and needs to collect evidence of it. had a situation happen at MRPD after i clocked out the other day and i went to grab the casing for the report i was gonna clock back on and write and realized that i accidentally destroyed it

**Comment by coalaura** [comment]
idk what exactly you did but you can already pick up casings when off-duty (if you have an evidence bag ofc)

![yes](https://i.shrt.day/0U2S5LC5VH.webp)
*off-duty in this picture*

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/85T0UAM7YV.webp)
![yes](https://i.shrt.day/3R299Q2H4N.webp)
![yes](https://i.shrt.day/KZ3PE4Z0VJ.webp)

**Comment by scufflord** [comment]
thats so weird LMFAO yeah nah i destroyed it somehow instead. ill test it again later
