### ISSUE TITLE
Suggestion - Vehicle spawn point block inside Luxury Autos

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3283]
### Assurance

I have read the `README.md`

### Summary

I would like the suggest to reduce range or area/ of our garage. 
We have a bay which is not usable, as whenever there is a car there, the garage spawn points blocks

### Reason

 and there are 2 bays one for garage and second one is un-usable as garage gets blocked due to the range...
It will be great initiating hold/sell interaction with customer on the bays. Improving better RP for customer to us
![spawn_block](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/fef79544-1ab1-4d3f-ad58-2518f229c7f7)

**Comment by coalaura** [comment]
fixed
