### ISSUE TITLE
Suggestion - Adjust SASS Vehicle Windows/Plate

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3284]
### Assurance

I have read the `README.md`

### Summary

Would like to suggest changing the windows to "Darksmoke" and license plate to "SA Exempt" (opt Blue On White 3)

### Reason

Changing these two features would make sense as..

1.) As SASS, we are essentially RPing as "Secret Service", the darker window tint on our new CTS + Gov Suburban provides us more cover as to who is in the vehicle while escorting state assets/the Gov around (less probability of someone identifying them and attempting to pull guns on an already under armed "agency", also blacked out windows is part of many luxury vehicles and government vehicles IRL)

2.) Swapping the current normal plate to SA Exempt (or opt Blue On White 3 under plates) as these vehicles are "Government Fleet" and we have the same on our gov suburban, as well as our previous Tahoes. PD also carries these plates, I believe it is just a smaller detail for gov vehicles that is fun.

(ps. love the SASS vehicle swap from Tahoe)
![Screenshot 2024-03-18 141122](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/139399473/45f064fd-1445-455a-b42d-113285ccfbbf)
![Screenshot 2024-03-18 141201](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/139399473/dfb0e15b-4d0a-4191-9de2-41267e92c5f4)

**Comment by coalaura** [comment]
light smoke and the SA Exempt plate, dark smoke is the same as blacked out and way too dark
