### ISSUE TITLE
Suggestion - Ability to add Cocoa Beans to blender as ingredient

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3285]
### Assurance

I have read the `README.md`

### Summary

Cocoa Beans as an ingredient in the blender effectively adds depth to the different milkshake and smoothie combinations.

### Reason

We all want chocolate milkshakes!

**Comment by HollaYalla** [comment]
+1 this

**Comment by coalaura** [comment]
sure thing

**Comment by coalaura** [comment]
go bonkers

![yes](https://i.shrt.day/VNXFAIFW6J.webp)

**Comment by navonody1** [comment]
> go bonkers
> 
> ![yes](https://camo.githubusercontent.com/c8536140202a2f2dc750fb0d52e7aa55a327df49ffa5ed71b8732bf52f0cec43/68747470733a2f2f692e736872742e6461792f564e584641494657364a2e77656270)

Yes cocoa powder does actually make sense for the blender. Very much appreciated :)

**Comment by navonody1** [comment]
> Blend once to get Cocoa Powder blend another time with Milk to get Chocolate then blend it with anything???

Probably just 'crush' the cocoa beans in your inventory to make powder...just guessing.

**Comment by HollaYalla** [comment]
Facts I completely forgot about the inventory craft thing

**Comment by coalaura** [comment]
that was the original use for the beans
cocoa beans -> cocoa powder -> hot chocolate
