### ISSUE TITLE
Suggestion - Add chance to find Ancient Coins from shaking coconut trees

### ISSUE THREAD

**Issue by navonody1** [InZidiuZ/op-framework-issue-tracker#3286]
### Assurance

I have read the `README.md`

### Summary

Pirates thought it would be smart to hide treasure in trees, but didn't expect people to shake them for cocoa beans.

### Reason

Creates incentive for people to shake trees at Cayo. This incentive could potentially cause an influx of cocoa beans. More cocoa beans has the potential to create commerce RP as they can be sold to businesses that use them as an ingredient.

**Comment by coalaura** [comment]
ancient coins are worth a good bit, i dont want people to go grind shaking trees. the trees have a good reason since they are the only way to make. if i add it it'll be super rare

**Comment by navonody1** [comment]
> ancient coins are worth a good bit, i dont want people to go grind shaking trees. the trees have a good reason since they are the only way to get the beans. if i add it it'll be super rare

Not a problem. Thought it would be a fun lore kinda thing, but I agree it would need to be super-ultra-mega rare (four leaf clover or rarer).
