### ISSUE TITLE
Suggestion - Evidence quality of life changes

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3289]
### Assurance

I have read the `README.md`

### Summary

Just a few things: 

change device printouts to weigh 0 su like evidence bags so we can put them into inventories like trunks that may be full on weight but not slots

add more shredders to more pds. places like sandy shores you can process evidence, but then have to travel to MRPD to shred the evidence after if you don't need to keep it.

if you gather casings from the ground and they match a bag in your pocket that has the same casing number and casing, have them go into the bag you already have instead of adding another. saves us from over collecting and having to shred a bunch of stuff we didn't necessarily even need to pick up.

### Reason

quality of life

**Comment by coalaura** [comment]
> change device printouts to weigh 0 su like evidence bags

Done

> add more shredders to more pds

Could you note where in the PDs would make most sense?

> if you gather casings from the ground and they match a bag in your pocket that has the same casing number and casing, have them go into the bag

No, complicated and not really needed

**Comment by scufflord** [comment]
So for Sandy PD apparently there is one but it's all the way downstairs by the cells, while processing is upstairs. If a second shredder could maybe get added to this trash can upstairs for situations where we're just bulk processing like casings or whatever.

https://i.ibb.co/QX27ywk/Five-M-b2699-GTAProcess-Mu7-PR4srrz.jpg

Paleto maybe at these things? 

https://i.ibb.co/fqFGPr3/Five-M-b2699-GTAProcess-CS8-MFYGHMm.jpg

Davis PD just doesn't seem to have a decent spot but maybe that trash can? It's along the route from the door to the cells so it would make sense, given processing is back by the cells here.

https://i.ibb.co/9cyNgks/Five-M-b2699-GTAProcess-HZFoux-Sr5e.jpg

Del Perro is also strange cause processing is upstairs, but there isn't much room in the building for much of anything else. 

Maybe this trash can:

https://i.ibb.co/dPdKPdk/Five-M-b2699-GTAProcess-Svk-Am-F1if-S.jpg

**Comment by coalaura** [comment]
paleto has one here

![yes](https://i.shrt.day/XB42Q3I2KR.webp)

**Comment by coalaura** [comment]
new one in davis pd
![yes](https://i.shrt.day/OQCJLFL5U7.webp)

another one in del perro
![yes](https://i.shrt.day/AO7M8WAWVP.webp)

one in cayo pd
![yes](https://i.shrt.day/J7LLIGCFNY.webp)

and one in highway pd
![yes](https://i.shrt.day/LRGMLF5HQJ.webp)
