### ISSUE TITLE
[Suggestion] Pillbox Doors

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/op-framework-issue-tracker#329]
**Name:**
Anderzenn#0069 - Brandon Whittle, 1st. Assistant Director.

**Summary:**
Do so that cops can't lock the doors at pillbox, only unlock them.

**Reason:**
I think this would be a good thing to do because currently we have had situations where cops have used the hospital as an interview room or that they have accidentally locked the doors when leaving the hospital, as well as there is no reason for the cops to be able to lock the doors. They should only be able to unlock them incase we forget to unlock them.

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed, either they can do both, or none.

**InZidiuZ**
*OP-FW Developer*
