### ISSUE TITLE
Suggestion - Tequi-La-La QoL additions

### ISSUE THREAD

**Issue by SooDurty** [InZidiuZ/op-framework-issue-tracker#3290]
### Assurance

I have read the `README.md`

### Summary

I'm the new owner of Tequi-La-La and have some ideas that will make the business have better operation. I have attached 5 images with detailed suggestions.

![2024-03-21 10_59_42-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/014c785d-d549-4180-8e78-11fe513b6320)
![2024-03-21 11_06_19-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/52d88a25-9354-498c-8d01-85facd6f49f3)
![2024-03-21 11_08_50-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/0a2845e3-2a36-4243-98e2-c27a15222267)
![2024-03-21 11_09_58-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/a0c71686-ec37-440e-98a1-47516579f7fc)
![2024-03-21 11_12_52-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/93fbbe73-cc47-4e02-b5d6-c31d763f9301)
![2024-03-21 10_50_19-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/b5a6066e-6dd6-4b47-b387-36ff0c331493)
![2024-03-21 10_46_27-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/0e472abe-c769-4418-a4de-2b71112f71e1)
![2024-03-21 11_55_57-FiveM® by Cfx re - Legacy Roleplay _ Custom Framework _ Serious RP   Economy _ A](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/753d86a0-dd33-4834-b30b-fb6740360902)

### Reason

Of the suggests listed in the images:

1.) The parking situation will make events, as well as every day business operation problematic for customers to comfortably come and go. The suggested parking change would also benefit 2 other businesses (Bean Machine and The Comedy Club).

2.) The inability to access the locker makes having the ability to make mixed drinks problematic since some require fruit which can be quite heavy to just hold on person. I have also chosen a better locker location that's not behind a locked door and closer to the bar.

3.) The previous owner said there is a changing room the business, but I do not see one. In one of the attached images I detail a perfect location behind the locked door down stairs.

4.) I have detailed some issues with the bar. (a) There is no counter space pass items to customers (like at Burgershot). (b) If counter space were to be added, the trashcan behind the bar should be removed so it's not accidently accessed. (c) To make more room for the counter space, the bar store should be moved a little close to the bar entrance. (d) Another addition that would be great to have behind the bar is access to all the Fruit Vendor items (I think this would be great for all bars since we make mixed drinks). (e) Last but not least, I think the TequiLaLa bar should have tacos instead of sandwiches. Would also love for them to be called Tequi-La-Taco and be more filling than a normal taco.

5.) The business constantly has locals spawning inside on all floors. Would love to have this not be a thing.

**Comment by coalaura** [comment]
1: I'll move the main garage but not adding an employee garage with the public one being right next door

2: I'll move the locker

3: I'll add an outfit spot

4: I'll add some counter inventories and make sure you can access them easily. Removing/moving the garbage can would be something for the [asset github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)

5: I'll make the area not spawn locals

**Comment by SooDurty** [comment]
Thank you so much for your fast response Laura! I look forward to seeing the changes.

**Comment by SooDurty** [comment]
@coalaura we still don't have a changing area in the bar and it would be super helpful if we did. Also, I did noticed that locals still spawn downstairs by the pool table but they seem to be taken care of everywhere else in the bar. Thanks for everything you've done at Tequi-La-La!

**Comment by coalaura** [comment]
should be fixed now
