### ISSUE TITLE
Post-a-parcel | Postal

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3291]
### Assurance

I have read the `README.md`

### Summary

Idea is that a person can send items in postal to someone address and when delivered, owner can collect the parcel at his house letter box. This can have charges according to SU (storage units) of items send by the sender. This is kind of import / export but by parcels within city houses.

Also we can add more rp here by letting people do job at postal and they deliver parcels.

Van for job:
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_-PtFRZV-eGdsQUG4I8Y06qU0p6IRLSh4UPfwbGZ54Y9VSzdaecQHMZol&s=10

### Reason

Can be great for sending items to someone house. Can be unknown sender also for gang situation, i dontt know.

**Comment by coalaura** [comment]
This would be a pretty big feature and i don't think anyone except a small handful of people would actually use it. Letterboxes already work so you can go and deliver things to people but if you wanna send items i'd rather people meet up in person
