### ISSUE TITLE
Suggestion - Shredder, Fingerprint Station and Medbay for Prison

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#3292]
### Assurance

I have read the `README.md`

### Summary

**Fingerprint Station and Shredder**
These functions are required for our job in DOC, our evidence locker is an absolute joke and is never emptied, and our ability to fingerprint lies in sandy PD. For this I propose the following changes

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/4959366/362ee052-8186-4ade-8546-b04da5f8289d)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/4959366/a5896871-d815-448a-8647-f12e618bf856)

Note: This does require the evidence locker to be moved slightly, however this will allow us to facilitate the needed functions all in one room.

**Medbay**
Unfortunately we have issues where DOC and inmates are left for long periods of time blacking out, DOC can leave the prison however inmates are not able to under any circumstances, even for medical. With this i believe we should have a med bay that is dedicated to inmates.

I believe the best way for this to work is have it the exact same as every other hospital, except if someone who is jailed nancies, they will end up in the prison hospital. meaning there is no need for any coordinate bounds to check what region a player who nancies is in.

(Note: if this doesn't make sense, reach out to me on discord because that last paragraph looks like absolute dog water to me)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/4959366/a105379c-40bd-49c8-98b3-f2e7fe90d4b3)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/4959366/5e42d728-402b-4d54-bd23-9257eb157efe)

### Reason

This is a QOL update for prison that assists both DOC and inmates as well as squashes some common issues we have in prison.

**Comment by coalaura** [comment]
i had already given you guys fingerprint spot a while ago when someone asked for it

![yes](https://i.shrt.day/ZXTWS90TDT.webp)

**Comment by coalaura** [comment]
i've moved it here now to hopefully make it more accessible?

![yes](https://i.shrt.day/OAFV7GE0KT.webp)

**Comment by coalaura** [comment]
moved the evidence locker, added the shredder, moved the fingerprint station as described, made the hospital functional and if you airlift while jailed you will airlift to the prison hospital.

The prison hospital does not charge patients and always fills up hunger & thirst (that's what u pay tax for).

![yes](https://i.shrt.day/BLLPOU3U9S.webp)
