### ISSUE TITLE
Suggestion - Remove the use of emotes and using radio during drug sales

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3293]
### Assurance

I have read the `README.md`

### Summary

Stop people being able to emote and use their radio to hide drug hand offs

Also apparently when you're handing off drugs you can press x to restart/stop the animation so this should be removed. 

There should be a stunlock when you're handing off drugs to stop you from running away or stopping the animation.

Also I think the atms on vinewood should get removed

### Reason

Similar to using emotes when shooting etc it's powergaming in my opinion and should be prevented

**Comment by coalaura** [comment]
people keep finding ways ffs... done
