### ISSUE TITLE
Bug report - Emote menu off-screen

### ISSUE THREAD

**Issue by Juderick20** [InZidiuZ/op-framework-issue-tracker#3294]
### Assurance

I have read the `README.md`

### Reporter

maybejuderick

### Summary

i have one problem about emote menu that when i press f3 for emote menu its goes out of my screen 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164602955/893189ed-bd32-42fc-92db-9d4d1621cd39)

### Steps to Reproduce

can u plz tell me how can i solve it

### Expected Behavior

I m expecting that that problem should be solved 

### Actual Results

so i have checked all settings restarted my pc and everything but that problem is not solved 

### Screenshots/Videos

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164602955/3c23cbad-6d79-4126-83a2-9823382bd002)

### Game Resolution

1600x900

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164602955/bdb13ff2-43b8-4d1b-98ca-b3b5f47e8ccb)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164602955/9a852796-4afe-4780-b2c0-c700dae0fe2e)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
Are other people having the same issue or is it just you?

**Comment by Thales1732** [comment]
I’m having the same issue, pulling out my phone then pressing Esc. Fixes it for me

**Comment by HollaYalla** [comment]
What’s y’all’s Aspect Ratio at or do you use an UI scaler (idk if that’s a thing for FiveM I know it is for other games)

**Comment by coalaura** [comment]
I've redone the emote menu in the new framework. There should no longer be issues with it now

**Comment by Juderick20** [comment]
> Are other people having the same issue or is it just you?

i m having this issue it is not solved

**Comment by Thales1732** [comment]
She said she fixed it but you gotta remember the update isn't live yet, could be next restart or next time they push out a server update.

**Comment by Juderick20** [comment]
okk so after update it will be fixed ?
