### ISSUE TITLE
Suggestion - Update Weed Field UI

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3295]
### Assurance

I have read the `README.md`

### Summary

With all the UI's in the city being the thing that looks like the /me maybe its time to change the Weed Fields UI as well so maybe change it to this instead of the current one

**CURRENT**
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/6ec71d2e-83bd-47fa-a56f-4d839c1ac9e7)

**New One**
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/6d77017a-99a8-42b8-b5d6-d5b10576eafa)

I just feel that it will make the UI's in the framework more consistent

### Reason

More Consistency

**Comment by coalaura** [comment]
we use the help text a lot in the framework and its how the old field used to work
