### ISSUE TITLE
Realtor HQ

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3296]
### Assurance

I have read the `README.md`

### Summary

Realtor HQ - Could be anywhere in city, most likely a high rise in the center of city? 

### Reason

Would be a spot to do paper work a buy realtor related items, (all realtors use same office) 

Realtor Drone - in a sense to grab photo of above and around the units to get good quality images of each house or unit. 

Realtor Basket - a Basket a realtor can put gifts in as a home warming gift / congratz on ur big purchase

Allow realtors to show the clients the inside of the home some how, so far I’ve been having to use other f clients homes to show ( :( ) 

Inside the HQ could be a printer, paper, desk

**Comment by xplrerin** [comment]
You can already show the inside of homes if you have them and yourself employeed on the /comp you can /enter your empty properties.

A basket to put things in is a good idea but more for everyone than just realtors imo.

**Comment by coalaura** [comment]
yeah i dont think realtors need a whole HQ
