### ISSUE TITLE
Green wonderland Seal 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3297]
### Assurance

I have read the `README.md`

### Summary

A seal or crate or bag that green wonderland can bag up goodies in

### Reason

Depending on your city and the legal limits on what you can carry it can show that you just purchased it and if the seal gets broken then well your screwed, only Green wonderland can do it in the back and it will kinda work like a trading card pack

**Comment by coalaura** [comment]
i'd say not trading card pack but simply paper bag filling station with a custom GW themed bag

**Comment by SluggsV2** [comment]
Yes, perfect! Would work perfectly

**Comment by coalaura** [comment]
Do you have a certain logo you'd like otherwise i'll just go for a weed leaf or smth like that

**Comment by HollaYalla** [comment]
![GW-Logo](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/25059d55-7f09-4754-ab5d-d80b5b69ad45)


Can you use the logo on either side of the text? I would pull it off it but I’m only on my phone

**Comment by HollaYalla** [comment]
The right one would probably be the better one to use

**Comment by HollaYalla** [comment]
Ok still looks good
