### ISSUE TITLE
Suggestion - Improvements or Changes in Ranch De Caniche

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3298]
### Assurance

I have read the `README.md`

### Summary

I've seen an overhaul to the Ranch De Caniche, previously known as the La Fuente Blanca. There are many possibilities in this property and with good implementation it can be a great resource.

In the past, the property name was occupied by the Madrazo Cartel and all the activities here were associated with them. I'm not aware of the RP in this area in International or other, but in my subdivision this property is lying for a long time and not being utilized to the fullest.

The main reason lies with the _Job Names_. Therefore, I suggest changing the job to a neutral name, so it can be maintained and utilized by various types of people.

Here is my suggestion with the new job name and position.

**1. Job Name & Positions:**

- Madrazo Cartel -> Ranch De Caniche

   - Capo -> Ranch Owner

   - Capitán -> Ranch Manager

   - Teniente -> Event Coordinator

   - Sicario -> Security

   - Halcón -> Ranch Hand

**2. Addition of Public Helicopter Spawner:**

It already has a helipad within the property. The addition of a helicopter spawner here will be fantastic.

![Ranch_De_Caniche_helipad](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/74db43ff-18a3-41dd-b44a-0bf6e4a32e95)

**3. Door Locks:**

As far as I remember, La Fuente Blanca had door locks. There are many doors in the new addition. But including locks at least the main floor doors will do just fine.

### Reason

Giving a _neutral job name_ will remove the restrictions in this property and help utilizing this area for various purpose. The naming will not only allow the current owner of this property (if any) of a subdivision to continue their activities, but also make a way to acquire this place legally.

Moreover, the name changes will justify more to the name Ranch De Caniche than the current job.

In addition, including a helipad and door locks will improve the facility and security of the ranch.

**Comment by coalaura** [comment]
> Giving a neutral job name will remove the restrictions in this property

What is stopping you currently? The name of a job is irrelevant, only you see it anyways

**Comment by rakibulhasan456** [comment]
@coalaura 

There are many people who subconsciously think the place is only allocated for a specific group of people. I've seen there are misconceptions around it that, without being the Madrazo Cartel you can't take this place.

Even though there is no one acquiring the places currently, it is hindering to take the place legally.

Also, I think the police department can see what job you have through MDT or other ways. When a good person has the name "Cartel" in his designation, it won't look appropriate.

Changing the names will irradicate all these problems. And this way both parties will be able to carry out their activities without issue and open up new possibilities in this place.

**Comment by coalaura** [comment]
There are lockers, etc. in the ranch too. I'm not changing the job name. You can remove the keys through the server config if you wish to do so.

Helipad has been added

**Comment by coalaura** [comment]
> without being the Madrazo Cartel you can't take this place

You can, nothing is stopping you. If your subdivision managers are saying this talk to them instead
