### ISSUE TITLE
Suggestion - Gift Wrapping Box

### ISSUE THREAD

**Issue by tiigerrlily** [InZidiuZ/op-framework-issue-tracker#3299]
### Assurance

I have read the `README.md`

### Summary

Gift giving by having a location where people can purchase and "gift wrap" something like a present by putting it in a gift box / gift wrapping it. It could hold like 1 or 2 items but not show the items in the description of the gift box. 
Item wise it could look like this: 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/53797982/c79d4397-61c9-44c1-903a-dc60c34dbbde)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/53797982/7134d5d3-4ea4-4731-b2c7-a641aa8eb031)

### Reason

I think this could be a really cute change for RP, it could be similar to a paper bag from Bean Machine and Burger Shot. It could require purchasing the separate box then taking it somewhere and putting stuff in it and then when they open the box it could destroy the box / item and puts the stuff in your pockets, again similar to the food bags from food places.
It's only small, but it creates the element of surprise and gift giving for people, it could potentially provide RP for people who have surprise proposals, or birthday parties.

**Comment by antihero6713** [comment]
I could whip up a quick prop for this if needed

**Comment by CloudCait** [comment]
Imma add something to this how cute would it be if you could buy or even pick different types of flowers and make bouquets instead of just roses

**Comment by coalaura** [comment]
this has now been done
