### ISSUE TITLE
Bug report on evo 9 exclusive car

### ISSUE THREAD

**Issue by henryvolk** [InZidiuZ/op-framework-issue-tracker#330]
**Reporter:**
Henry 

**Summary:**
I bought a $20 patreon just for the evo 9 and it is so slow, it caps out at 135 mph even when i spent $25k in upgradges
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Closing, wrong GitHub. Use the asset-related one.

**InZidiuZ**
*OP-FW Developer*
