### ISSUE TITLE
Suggestion - Add a second option for camera

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3302]
### Assurance

I have read the `README.md`

### Summary

v_ret_ta_camera is a smaller more portable camera option vs the big bulky one we currently use. The current one will stick through the windshield of a car and for any kind of undercover work can make it very clear to people what you're doing. Swapping to this type of camera as an option would keep that from being an issue. 

https://forge.plebmasters.de/objects/v_ret_ta_camera?search=camera

### Reason

PD tingz

**Comment by coalaura** [comment]
why not use the perfectly small camera you are already carrying around with you? (your phone)

![es](https://i.shrt.day/BGMSFGIPPF.webp)

**Comment by scufflord** [comment]
Doesn't zoom in nearly as far as the regular camera does

**Comment by coalaura** [comment]
makes sense tho, camera with huge lense has far zoom but is big, phone doesn't have far zoom but is small. I feel like thats a nice balance
