### ISSUE TITLE
Sand sifting and searching ground rework

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3304]
### Assurance

I have read the `README.md`

### Summary

Reward and Emote rework

### Reason

As far as the emote goes it’s just him kneeling to the ground, maybe could try and dig around in the ground make some dust appear or something. Small shovel may work

as far reward goes so far they all sell for the same, the amount of time required to find these compared to finding rings coins or bars well diving is significantly lower, the price on those items from ground searching should be more imo

**Comment by coalaura** [comment]
> As far as the emote goes it’s just him kneeling to the ground, maybe could try and dig around in the ground make some dust appear or something. Small shovel may work

I am not smart enough to make custom emotes so we will have to work with what we got.

> as far reward goes so far they all sell for the same, the amount of time required to find these compared to finding rings coins or bars well diving is significantly lower, the price on those items from ground searching should be more imo

How much do you think they should be?

**Comment by SluggsV2** [comment]
Maybe somewhere in between those and trading cards to keep a balance 17.5k?

**Comment by SluggsV2** [comment]
Top trading card is 25k I believe

**Comment by coalaura** [comment]
i've upped the price and increased the chance of finding the items
