### ISSUE TITLE
Suggestion - Cayo Perico Improvements

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3305]
### Assurance

I have read the `README.md`

### Summary

I Recently have noticed more and more that there is 1-2 things that people come to Cayo Perico for are the Weed Field and getting Cocoa Beans and after being in the city daily I have started to get a bit bored of the standard things on Los Santos so I think we should kinda do a overhaul of Cayo Perico by adding various different activities.

Cayo Perico Jobs
 * Adding a Job Centre on Cayo Perico could very easily bring more people to the island and these will be the jobs that are on Cayo
 * Tour Guide Job - Similar to how the Bus Job works you will head to the more livable part of Cayo Perico and start your Job where you then will be supplied with a Tour Bus similar to the Vinewood one it will then have you go to different parts of the Island such as the lighthouse and the weed field just driving around the island and people will think this is a quick way to make money but it will have like 20-30 different points you need to go to so it compensates for the short distance but it will pay like 5k per trip BUT it can only be done once every 30 minutes or so to balance it a bit more
 
 * Farmer - You will be given a task to farm x amount of Cocoa beans where it will mark a big area for you to shake the cocoa beans then once you farm enough it will make you Crush them and take it to a different place on the island and then trade it in but it works like the Oxy Runs and only takes a certain amount of the cocoa powder it then will redirect you to go back to the job site and claim your cash which will be like 2-3k with a 15 minute cool down
 
 * Fishing - I know this has been in the works for a while now but this would be different you will head to the docks and start your job it will then add a marker to a section of water that you need to go to and then you will get onto the deck of your boat and use a Fishing pole item that you need to buy from the Cayo Perico Hardware store and it costs $500 for a basic wooden one, $1,500 for an metal one (which one you have gives you a higher or lower chance of catching a fish) and as you are on the deck and use it your character will crouch down like the Ground searching animation is and you have a chance to catch fish but after 15 casts it will give you a new spot but you cant stay on the water for more than 30 minutes otherwise you will get sea sick and start throwing up, you then will head back to the job spot and then turn your fish into cash and that is determined on how much fish you catch and you will need to sell it to fish vendors around the Island like Gems but the starting and stopping of the job is just to get the fishing points and the boat supplied

These are very very rough ideas and would need a bit of polishing but they are the start of somethings that could be very very good

**Change Coke Location**
So this is a extension onto how coke will be ran so someone will need to head to Cayo Perico to get the Coke Plane and start the mission where they then will need to fly to Grapeseed to get the location of the Coke Drop and a road vehicle if the spot isnt in the water so if it is in the water it will mark the spot and also have a chance to call the police but if it is on the land it will still have the chance to call the cops but give you an vehicle to get there once you drive/fly back you will need to walk up to the desk and put the vehicle away and get the OK to head back to cayo to turn your plane in and get a brick of cocaine.

### Reason

Add more stuff to Cayo

**Comment by coalaura** [comment]
I do not think we need full on jobs on cayo. The island is tiny and would just become grinder heaven. Coke was already on cayo once, it didn't work out and was moved back so we aint repeating that.

Fishing #2716  
More cayo things already planned #2775 #3288
