### ISSUE TITLE
Bank and Store Updates

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3306]
### Assurance

I have read the `README.md`

### Summary

Rework on how often it can be done

### Reason

Make it character bound, there should be a character limit so you can’t just chain rob, make it so there’s HQ and it makes a group you can rob with, 

Crime HQ - an app you can create a Group on for say 100k or 50k, this can help character lock banks and crime rates to help stop chain robberies. 

Also could be a new House item called; 

Crime PC - could be the base for the crime HQ instead of the phone, you could place this and access it, could opens Tablet screen (like the boosting tablet, or /comp) this could bring in some new contract features too, maybe a little beach store robbery, trucking heist (over take a transport truck)

There could also be a leaderboard say for not getting arrested when ur group robs a bank or store. 

1 point for Bank Truck 
2 point for Store
3 point for Bank

maybe add another step or 2 also to unlock the bank robbing to kinda like “plan the heist” 

could be anything from hitting a electric panel outside the bank, hack cameras from outside, Make A “teller” open an extra door

Just an Idea 💡 and could be reworked a ton for sure.

**Comment by coalaura** [comment]
> Make it character bound, there should be a character limit so you can’t just chain rob

only 1 person has to actually interact with things in robberies. So if you are a group of 4 you can still chain rob by simply cycling through who actually does the interaction. And once you have run out you just get 3 new people to do the robberies with. Generally wont work, thats why we have the timeouts (which you can even configure on a per-server basis).

I generally don't think current robberies (jewelry, bank & store) need to be more difficult. Thats why they don't give gigantic payouts. The higher the risk, the higher the reward. There are plans to add bigger robberies that have more steps involved (and therefore result in a higher reward) like #3040
