### ISSUE TITLE
FaceTime!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3307]
### Assurance

I have read the `README.md`

### Summary

A facetime

### Reason

A cool feature, could just show your character shoulders to head, and you can also flip the camera to show the outside. Just a little neat feature that could bring in some cool RP

**Comment by coalaura** [comment]
> a little neat feature

If this is little i wouldn't wanna know what big is... This would be a very complicated feature to implement. Currently there is only one way to record the game and said way is VERY resource heavy, tanking FPS on most PCs. It also doesn't work at all with various common anti-virus softwares. As of right now, this is not possible in a way that works on most machines.
