### ISSUE TITLE
Suggestion - Make driving great again

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3308]
### Assurance

I have read the `README.md`

### Summary

stop stress levels when driving, honestly it makes no sense why would people get stress levels up when just driving. i get if someone crashes / has accident the stress level goes up but when you just driving normally it shouldnt be a thing, or reduce the ammount of stress that is gained. 

Stress levels can be added to bank robberies, for example when someone is robbing a bank the person at the back whos porring the thermite would get stress levels every time they open the deposit boxes 

### Reason

massive quality of life impact, as mentioned before this should be adition for when someone has an accident / crashes the vehicle but not when driving on straight line

**Comment by Imaghost1337** [comment]
There is absolutely 0 need for this to be IC in the first place.
I'd understand if crashing or near misses with other vehicles caused stress, but magically becoming stressed pass 100 mp/h makes absolutely no sense.
I've seen an argument that apparently not people will utilise Green Wonderland more, however the place is never open anyway.
Anyway, poopoo and unnecessary change that did nothing but piss off 90% of the community.

**Comment by ThatSinisterGuy** [comment]
I like the stress from driving at high speed mechanic, and it does actually make sense. If you ever travel at 120mph (especially weaving through traffic as most players here are doing) you will notice an elevated heart rate, which is your adrenaline kicking in. Adrenaline is your body's response to stress. The faster you go, the more adrenaline will kick in as you become more stressed.

I will say though, having done a Legion to Paleto run for dailies, I think it could be toned back a little bit.

**Comment by Moneeb-ux** [comment]
There's really no necessity to incorporate this aspect into the game. Requiring characters to smoke joints, vapes, or cigarettes every single time they exit their vehicle seems excessive. It could be more realistic or acceptable in certain scenarios, like after a crash or when narrowly avoiding collisions with other cars.

**Comment by Pizzzaa** [comment]
Yeah the whole idea of getting stressed cause driving fast is just weird and not needed at all.

**Comment by HollaYalla** [comment]
Stress from driving at high speeds has always been a thing but VERY VERY VERY little and a SUPER high speed but now that it has been increased and the speed has been lowered people are complaining as it adds a bit more of a challenge when chases happen and high speed driving occurs other than just the cops and it gives GW a bit more business as their main buyers wont just be shooters it will be everyday people who have taken the risk of driving at such a high speed they gain stress just drive the speed limit and you wont gain the stress is the fix to it

**Comment by coalaura** [comment]
Okay guys, I know you are all addicts and you can't go 20 minutes without FiveM. Stress while driving was literally added with the last restart. As always, **EVERYTHING** goes through multiple iterations until it's right. You only get stress while above 100mph consistently, and I've **ALREADY** reduced the amount you get.

When you drive normally you don't get stress, you get stress while driving very fast...

**Comment by Pizzzaa** [comment]
as always nice and respectful response

**Comment by coalaura** [comment]
> as always nice and respectful response

not sure what ur expecting considering the impatience and complaining. Also i don't work a corporate job where i have to be extra nice to everyone, i do this in my free time and i can respond however i please...

**Comment by coalaura** [comment]
Its common knowledge that all the brand new things that get added go through multiple iterations of balancing till they are done. Opening a github issue complaining about a feature that was introduced barely 9 hours before and just complaining is not the way

**Comment by Pizzzaa** [comment]
Ye my bad, you the best. Thanks for responding.
