### ISSUE TITLE
Suggestion - GW Deliveries

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3309]
### Assurance

I have read the `README.md`

### Summary

Since Bean Machine and Burgershot both have deliveries and a bagging system and with GW now getting that bagging system I think it could benefit us greatly if we got a Delivery system where the deliveries where down in the south side or up north kinda the stereotypical weed consumer spots and this would also give GW workers a thing to do to make money when its dead at night or its dead at the store like Bean and BS and for the vehicle it could just be the Smoke on the Water van until we could get a custom one later down the road but that is un needed

### Reason

More stuff for GW

**Comment by coalaura** [comment]
no
