### ISSUE TITLE
Chop Shop sabregt

### ISSUE THREAD

**Issue by capsure** [InZidiuZ/op-framework-issue-tracker#331]
**Reporter:**
capsure#0737

**Summary:**
When chopping the sabregt it gave a door location in the middle of the car. When trying to chop that door it gave an error saving invalid door id.

**Steps to Reproduce:**
Chop a sabregt

**Expected Results:**
probably only 2 doors a hood and trunk not the mystery 5th door.

**Actual Results:**
There was a mystery 5th door

## Additional Information

**Screenshots:**
The \ was after about the 3rd time trying nothing actually showed up right away when trying. Tried probably 4 more times. By the time I took the SS the other lines appeared.

![image](https://user-images.githubusercontent.com/52392678/62348540-97814f80-b4c2-11e9-8667-a58c141eb4b7.png)

![image](https://user-images.githubusercontent.com/52392678/62348558-9f40f400-b4c2-11e9-9bbf-f52b02430588.png)

**Game Resolution:**
1920x1080

**Player Data:**
![image](https://user-images.githubusercontent.com/52392678/62348683-0eb6e380-b4c3-11e9-8136-1034a2211742.png)

**Notes:**

I know I've done sabregt's before but not this one with the modified hood. Its possible that's what got messed up.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
