### ISSUE TITLE
Suggestion - Stress Reduction Zones

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3310]
### Assurance

I have read the `README.md`

### Summary

For bars and the VU enable it so that if you're within the interior of the building your stress will slowly go down over time. People go out to bars all the time IRL to relieve stress so this could be a good thing for those businesses as well. 

Additionally for PD and EMS have it tied to their job that when in a hospital or police department their stress slowly goes down. Back at the office doing paperwork after an arrest and you're relaxing for a little bit, you'd naturally calm down there.

### Reason

Cool idea/quality of life thing/im high

**Comment by coalaura** [comment]
i like the restaurant/bar idea but i don't wanna encourage PD to stand inside MRPD (even if its paperwork)
