### ISSUE TITLE
Suggestion - Transparent windows at Luxury Autos

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3311]
### Assurance

I have read the `README.md`

### Summary

![curtains_removal1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/c86aa74f-ba48-4a24-b7da-1339fe748cdc)
especially this one, It will give good exposure to our cars, as anyone passing from that side have no view and I want curtains to be removed and glasses as transparent like this below mentioned, old snap of Luxury Autos
![OLD_LA](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/4453b73c-caa8-4488-a0a0-723417b4d2ba)

![curtains_removal2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/702baa9d-9418-413b-af76-a49a69744b6a)
So do these curtains, 

### Reason

It will give good exposure to our cars, as anyone passing from front left and  side have no view and removing the curtains will do the work and glasses as transparent like it was before, old snap of Luxury Autos mentioned above.
We're running this business perfectly, if these changes are made it will eventually boost our work and excites us and the citizens of los santos.

**Comment by HollaYalla** [comment]
Im throwing this out here so you can make one before Laura says it 

You need to put this in the Asset Tracker as this is the Scripting Tracker

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by coalaura** [comment]
yes, like hollayolla said that would be an asset suggestion
