### ISSUE TITLE
Suggestion - Ability to push vehicles

### ISSUE THREAD

**Issue by hell-of-the-devil** [InZidiuZ/op-framework-issue-tracker#3312]
### Assurance

I have read the `README.md`

### Summary

Allow players to push vehicles from behind or infront!

### Reason

Would allow you to actually be able to do something with a broken down vehicle when there are no mechanics about. I find myself just leaving vehicles standed in places for them to eventually get robbed of their things, Atleast this way i could push it to a garage!

**Comment by ayushpatel1007** [comment]
We also have alternative like repair kits , so we can repair it up to extend that vehicle starts and works .. so this new feature can also be not much needed. Don’t know ,what are others opinions

**Comment by BaronVonSnergerberger** [comment]
Few things, one...repair kits already exist to repair vehicles. The only thing a repair kit will not fix is a waterlogged or exploded vehicle, which both require storage in a garage first. Any other vehicle an advanced is more than enough to get it working, while sometimes needing fuel as well. 

For vehicles that have been blown up, waterlogged, or if you're just unprepared and too stubborn to have spare advanced repair kits in case of emergencies like this...There already exists a trailer from PDM for smaller vehicles, and people are able to buy tow trucks for their own vehicles. If you are not actually a tow driver, you can still use the tow truck as a personal vehicle to take cars to the garage, you simply cannot profit off impounding vehicles.

Therefore this feature is pretty much unnecessary

**Comment by coalaura** [comment]
I feel like this would be too OP. There are many of ways to get your broken down car moved around that require player interaction. This would just encourage people to not call a tow and do it themselves. I get the point that there are sometimes no mechanics around but still i feel like being able to push cars around will only lead to abuse

**Comment by txxlrrsCoding** [comment]
Similar to /struggle, make the person get "exhausted" after like 10s making it so it's only really useable to push the car off of the middle of the highway while you wait for a tow. It's very annoying when your car is damaged and then locals slam into it at 70mph which then makes it explode.
