### ISSUE TITLE
Marlowe Drive Rehab Center

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3314]
### Assurance

I have read the `README.md`

### Summary

Little cafe / food spot

### Reason

I’m thinking there could be a spot inside or out, that you can buy items, such as cookies, ice cream, lollipops, hot dogs, chips, pop, water 

some things that would be consider snacks or BBQ lunch vibes, something that can fill a lot of people but cheap! 

I was pre thinking a combo could be,

Combo 1 - Hot dog + pop + chips 
Combo 2 - Hot Dog + Pop + Ice cream
Combo 3 - Pop + ice cream + chips

**Comment by coalaura** [comment]
The Rehab Center on Marlowe Drive is a therapy/rehab center not really a restaurant/cafe...
