### ISSUE TITLE
Suggestion - Delivery Job and Garbage Job updates

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3315]
### Assurance

I have read the `README.md`

### Summary

Delivery job - Routes 

garbage - co op

### Reason

Delivery Job - Is there a way to fix it so on a route we don’t go from house 1 to 9 back to 3 up to 7 it’s all random, can we get it in order? On the routes I’ve done in head, it’s in order
More or less, jump out to a bunch of deliveries on foot and go back to the truck, each delivery you would still have to go back to the truck and grab the next item 

Garbage Job - Make it Duo, many players are more interested in creating RP by doing some of the jobs in groups or with friends! This can apply to all jobs at life invader that would make sense to have 2 people working! 
(Suggested by Civs, just didn’t know where to put it)

**Comment by coalaura** [comment]
Okay so there is only so much i can do when it comes to "fix" the delivery routes without manually coming up with a whole bunch of them. I've changed it now to try to organize the randomly picked delivery locations to have the shortest path (using nearest-neighbor), that's really the best i'm able to do without doing it completely manual.

Garbage job i will look at soon.

**Comment by coalaura** [comment]
#2454
