### ISSUE TITLE
Bug report - Unable to fix doors on some cars (mechanic)

### ISSUE THREAD

**Issue by ShroudxSuju** [InZidiuZ/op-framework-issue-tracker#3316]
### Assurance

I have read the `README.md`

### Reporter

Sujil Kumar (@shroud8879)

### Summary

![Screenshot_69](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/166200028/3cbe866f-0088-4eb8-8e28-b886124c95fd)
we are unable to repair certain cars unable to fix bonets of cars please fix this bug.

### Steps to Reproduce

fix door bug in tlmc repair shop

### Expected Behavior

fix door bugs in tlmc repair shop 2

### Actual Results

-

### Screenshots/Videos

![Screenshot_69](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/166200028/07af4719-d3cd-47dc-a0e8-02e0e71a4235)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
on which cars did it happen

**Comment by rainymcjay** [comment]
> on which cars did it happen

Not op but from recent repairs at Harmony the only vehicles where I still have issues with hoods are the MTL Towtruck Custom and the Flatbed.
