### ISSUE TITLE
Suggestion - Adding Flares to PD, EMS and BCFD stores

### ISSUE THREAD

**Issue by TacticalTyl3r** [InZidiuZ/op-framework-issue-tracker#3318]
### Assurance

I have read the `README.md`

### Summary

something simple with adding Flares to PD, EMS and BCFD stores

### Reason

I think this would be a nice addition for public safety employees are able to mark off emergency scenes, warn drivers of closed roads, accidents, areas to stay out of. I believe they can be used to increase RP with different departments.

**Comment by coalaura** [comment]
yeah why not
