### ISSUE TITLE
Suggestion - Add Driver's License

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3319]
### Assurance

I have read the `README.md`

### Summary

Right now you are not able to remove driver's license from people. When you do /license_list there isn't one for drivers license. And when their license is taken away they shouldn't be able to buy a new one until their suspension is over.

edited:
Since drivers license is attached to the citizenship card I'm proposing that it should be separated.

### Reason

 I feel like Goverment and PD should be able to remove drivers license for those with suspended license. This will add an extra challenge for criminals.

**Comment by CloudTheWolf** [comment]
A drivers licence isn't really a thing, it's just tied to your citizenship card.
Having a separate Drivers Licence, with each licence having a unique ID would also be good as you could suspend all licences for a citizen and prevent them buying a new one, as well as flag a stolen licence as well Could also be a black market for fake drivers licences and a new thing crims to do where they print a licence with a character picture but a different name

**Comment by Discordop** [comment]
> A drivers licence isn't really a thing, it's just tied to your citizenship card. Having a separate Drivers Licence, with each licence having a unique ID would also be good as you could suspend all licences for a citizen and prevent them buying a new one, as well as flag a stolen licence as well Could also be a black market for fake drivers licences and a new thing crims to do where they print a licence with a character picture but a different name

Good catch, I forgot that the driver's license is tied to the citizenship card. I guess this ill rename this to add a seperate id for driver's license.

**Comment by coalaura** [comment]
I'll add it but its up to each subdivision to decide if they wanna make use of it or keep using the citizen card as a drivers license
