### ISSUE TITLE
/fix for police when near a station

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#332]
**Name:**
Lars. #9309
**Summary:**
 Distress signal to let EMS / other officers know when a officer goes down.
/fix command to fix a police car while being close to a PD.

**Reason:**
The distress signal would be good to inform fellow officers when an officer goes down. It would show a 10 code and a location so that dispatch can respond to that. At the moment this subject is kinda a grey area cause you are not allowed to use radio comms while down but that is the only way to inform dispatch if you go down while being alone.

The fix command would prevent that officers need to switch cars 10 times on a long shift to get their vehicle repaired.

**Comment by InZidiuZ** [comment]
Hey,

/repair* has now been added.

**InZidiuZ**
*OP-FW Developer*
