### ISSUE TITLE
Suggestion - Server Config For Starting Items

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3320]
### Assurance

I have read the `README.md`

### Summary

A config for changing what new people flying in the city gets.

### Reason

With the addition of the driver's license new players don't get driver's license but they are prompted to get in a car and drive to the danny clothing store. Since it is up to subdivisions to use it (the drivers license) I feel like this config should be there so we can automatically give them licenses.

Alternatively:
Prompt them to call a taxi instead of driving. This will bring more riders towards the taxi job.

**Comment by coalaura** [comment]
Using the drivers license is up to each subdivision. You need to have the actual license to be able to get the drivers license item ![yes](https://i.shrt.day/CMY3QOOG9L.webp)
