### ISSUE TITLE
Parson's Therapy Network additions

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#3321]
### Assurance

I have read the `README.md`

### Summary

Hello, I know someone recently opened a github for additions to Parson's but this is nothing in that regards. We have a very up and running department for Therapy in the international server and recently the building has been used a lot more.
It'd be nice to be able to clock in and out at the Marlowe Drive centre and be able to store our ambulances/explorers. (We have access to the houses but can't store our EMS vehicles of-course).
Another addition that might help with roleplay is the capability to buy yoga mats at the centre. Therapists are limited on ways to treat patients in a roleplay scenario and yoga is one of our biggest treatments. Even if it's only the EMS that can purchase them to give to patients during sessions.

### Reason

A lot of therapists would appreciate being able to wake up at Parson's and complete a session without having to travel to a hospital in order to get on duty. The building has a office within it that can be perfect for the on/off duty addition.
And like I said about the Yoga mats, we're limited on treatment items to give as a therapist and since marlowe drive has yoga mats to use, It'd be nice to have those be purchasable for patients too.
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/77466954/6042a986-96de-4039-b1fd-1dd45b9187f3)

**Comment by coalaura** [comment]
bet! I will just add yoga mats to the EMS store and then add an EMS store location to the therapy center so you can access other things too. clock-in/out and garage also no problem
