### ISSUE TITLE
Suggestion - Change Weed 1oz icon to match prop

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3323]
### Assurance

I have read the `README.md`

### Summary

Title basically. Currently the quarters and ounces use the same icon and it can get a bit confusing. Since we're now selling ounces with a prop to npcs I was thinking it might be easier to look at to update the icon to be of the prop, since in theory it's "packaged weed" for sale

### Reason

quality of life/nitpick/its 4am and you know why I'm here

**Comment by coalaura** [comment]
sure
