### ISSUE TITLE
Suggestion - Few ideas to add in the game

### ISSUE THREAD

**Issue by wahoovisuals** [InZidiuZ/op-framework-issue-tracker#3325]
### Assurance

I have read the `README.md`

### Summary

Add fishing
Add a stock market? on buisnesses maybe or maybe like normal gta stock market
Add a dog or cat as an actual pet to love and feed and go for adventures

### Reason

itll be fun to add these because it gives more depth and fun activities to the game

**Comment by coalaura** [comment]
> Add fishing

#2716

> Add a stock market

I don't really see a need for a stock market ngl. We already have something in that direction (/stocks) it just doesn't work right now as its a very difficult thing to balance right without just giving out free money.

> Add a dog or cat as an actual pet to love and feed and go for adventures

Most definitely not. We already removed animal peds from the creation menu.
