### ISSUE TITLE
Suggestion - EMS shop additions- Band aid boxes and lollipop boxes

### ISSUE THREAD

**Issue by bossace** [InZidiuZ/op-framework-issue-tracker#3326]
### Assurance

I have read the `README.md`

### Summary

The colorful fun band aids are only given out when you airlift to the hospital. If possible we would love the ability to buy band aid boxes in our EMS shop that when we open them up give us a random few of them for us to give out to patients.

Lollipops bags added to our ems shop that open and give a random few flavors of lollipop we could give out to our patients as well

### Reason

We in EMS are always looking for ways to add fun interactions with the people we treat and do calls for. We know it isn't always fun to be down and wait on the ground. We thought adding little treats we could give out to people would form more positive interactions with EMS. People also seem to really like the bandage designs as well. Lollipops would also be a good treat for good patients and a nice surprise.

**Comment by coalaura** [comment]
> The colorful fun band aids are only given out when you airlift to the hospital. If possible we would love the ability to buy band aid boxes in our EMS shop that when we open them up give us a random few of them for us to give out to patients.

The bandaids are a special airlift only thing you get

> Lollipops bags added to our ems shop that open and give a random few flavors of lollipop we could give out to our patients as well

Yeah i can add lollipops, i think thats a funny idea

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/9C4PPOXB1B.webp)
