### ISSUE TITLE
Suggestion - Aviation Office

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3327]
### Assurance

I have read the `README.md`

### Summary

Currently, there's no dedicated office for the Aviation Department. I've seen in a post/ comment that, there is no intention of making an interior for the aviation dept.

But with some small addition to the existing content, it's possible to make a dedicated office for the aviation.

In GTA Online, there are four CEO Offices and three of them are present in Legacy. Two of them are occupied by the State office and DOJ office. The third office is unoccupied. It's at the LOMBANK, situated near Hayes, DOJ office, and Bahamas.

![2024-04-13_232818](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/2238e38d-2679-4770-89c9-099f024c705a)

It has the necessary interior, underground parking, helipad. Only couple of access can make it ideal for the aviation. Therefore, I would request to add some facilities in here and make a dedicated office for the LSA.

**1. Helicopter Spawner**

There's already a helipad on the roof, but doesn't have a spawner. Adding a spawner will be very helpful.

![20240413225846_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/a15dfed6-167f-4268-9e34-5af4917b8d60)

**2. Door Locks**

The doors are open for everyone and there's no lock system. Adding locks to it just like the state/DOJ office will be great.

All the pilots are license holder (at least in subdivision), So, keeping the door access bound to the _Aviation License_ will be the most useful (if possible).

![20240413225945_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/21b77141-4d60-4af8-a6f9-8b333657e9ee)

**3. Building Lift**

Currently, the only way to enter the office is from the garage. Adding a lift/teleporter at the LOMBANK gate like the state office will be fantastic.

![20240413230047_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/84d0c23b-825b-452b-b31b-dad125636713)

**4. Personal Garage**

If it's possible to add a personal garage that is associated with the aviation license will be a good addition to the office. It will work like the garage at the LSIA.

![20240413230021_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/175df735-302f-412a-861c-4dffbe21f0d1)

### Reason

The Los Santos Aviation is the largest department in our subdivision. At the international and other subdivision, the size should also be considerably big, I guess.

We've been running the department all these years without a proper office. So, it will be a fantastic addition for the aviation to get a proper place for their meeting/lessons/and other tasks.

As it's very big to ask for a new interior for the LSA, as there are many things to consider, I hope utilizing the existing interior will be the easiest way to make an office for the aviation.

**Comment by coalaura** [comment]
#3255 i already declined this previously. There is no need for an office. If you need an office you use the mayors office which is accessible by all state employees.

**Comment by coalaura** [comment]
I did however add the elevator you mentioned since the building and its office space is supposed to be freely available to people who need an office space, so you are free to use it dont get me wrong im just not adding locks and etc.
