### ISSUE TITLE
Suggestion - ZYN/Chew

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3328]
### Assurance

I have read the `README.md`

### Summary

I think something like ZYN or chew being sold in gas station/convenient stores for stress relief would be a great way to relive stress. They should relieve about the same amount of stress as a typical cigarettes.

### Reason

These would be a great way to relive stress instead of something like cigarettes or vapes.

**Comment by HollaYalla** [comment]
Then could you make it relieve a small amount of stress so like one whole pack is equal to 2 cigarettes

**Comment by coalaura** [comment]
then zyn would be pointless
