### ISSUE TITLE
Bug report - /repair text bug.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#3329]
### Assurance

I have read the `README.md`

### Reporter

nozimmm

### Summary

While using /repair in PD, "Repairing Body" shows up twice. I believe its supposed to be "Repairing Engine" first and then "Repairing Body".

### Steps to Reproduce

Change the text of "Repairing Body" to "Repairing Engine".

### Expected Behavior

Show "Repairing Engine" first and then "Repairing Body".

### Actual Results

Shows "Repairing Body" 2 times.

### Screenshots/Videos

https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/7e21adfc-7fdc-479e-bb31-8c81114deb6d

### Game Resolution

1920x1080

### Player Data

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/126329392/de917e38-88f6-4dc5-af4d-9bdf8209c1e9)

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
This crucial game breaking bug has been fixed now

**Comment by Nozimmm** [comment]
it was like it from soo long and was soooooooooooo annoying to see both the texts twice xD
