### ISSUE TITLE
Addition of 911 commands

### ISSUE THREAD

**Issue by jaymssmith** [InZidiuZ/op-framework-issue-tracker#333]
**Name:**
Badwolf#3160

**Summary:**
An addition of a 911 or 997 command which down people can use to alert the police or ems Instead of using their phones which give the characters have a weird animation like they are half bent.
Also the addition of more /sit commands to assist sit on different kind and chairs and even beds
**Reason:**
I think it will be more realistic to make it look like a ped sent the emergency

**Comment by psyCOSMO** [comment]
/311 can be also used for non emergency police call

**Comment by ZurxeyH** [comment]
This wouldn’t really be valuable. Sure it’s a neat idea, but it’s not needed, as there’s already multiple systems in place.

**Comment by InZidiuZ** [comment]
/911 and /311 is most likely going to be implemented alongside with the new phone, and we most likely won't have "Police", "EMS", etc., in the phone.

**Comment by InZidiuZ** [comment]
>/911 and /311 is most likely going to be implemented alongside with the new phone, and we most likely won't have "Police", "EMS", etc., in the phone.

Yes. This will be the case.
