### ISSUE TITLE
Suggestion - New PD Impound spot & ATM

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3330]
### Assurance

I have read the `README.md`

### Summary

Right now I afaik there's only one PD impound spot in the city. Our PD would like to make Davis PD our main PD but there is no PD impound in that location. 

There's also no ATM inside the PD if possible can we add one there too?

Maybe add a location over here in the Davis PD parking lot:
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/9fdcc82c-99a2-4a9d-920d-254189fab850)

And add a vehicle shop over here:
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/6d1c11d5-9e20-47c0-bc72-083430678e11)

### Reason

It adds more PD that we can impound vehicles in.

**Comment by Nozimmm** [comment]
impound spot outside city [sandy/paleto] will be goated aswell, sometimes after a long chase we gotta bring the vehicle from paleto to MRPD and thats pretty boring.

**Comment by coalaura** [comment]
I can add a PD impound spot to sandy and paleto but MRPD is the main PD for the city and has always been. Everything important is there and not elsewhere. You are free to use it of course but since MRPD is the main city PD their impound spot will be the only one for the city.

**Comment by coalaura** [comment]
atm would be for the [asset github](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues)
