### ISSUE TITLE
Suggestion - Shared Garage Idea

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3332]
### Assurance

I have read the `README.md`

### Summary

Allow people to set one/a few people as a trusted person to have access to their garage and be able to pull vehicles out. Similar to access levels for houses and savings accounts. 1 lets you pull the vehicle out to retrieve items from the storage, level 2 lets you pull the car out and receive keys to be able to drive it.

### Reason

Quality of life thing to make it easier to share cars with a spouse, for example. Currently the only way is to fly in, physically transfer the car over, and then when done transfer it back.

**Comment by coalaura** [comment]
done (/manage_garage)

**Comment by coalaura** [comment]
i already said no to that, its either all cars or none. You are giving access to the garage not the car

**Comment by PurpleHzea** [comment]
What about having another tab open up when you click on Vehicle List, where you can either choose Your own garage or another persons garage. Instead of having them all mixed?

**Comment by HollaYalla** [comment]
Like it says Personal Vehicles and then Shared Vehicles?? Or like

John’s Vehicles
Mary’s Vehicles
Lynette’s Vehicles
Etc

**Comment by PurpleHzea** [comment]
The second one 
You'd click on vehicle list then you'd see

My Vehicles 
Jerry's Vehicles
etc

**Comment by coalaura** [comment]
this is meant for people who want to share cars like couples, etc. If this is in regards to luxury autos wanting a shared garage i remind you that i already said its still on the todo list

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/G3WP70LHRE.webp)
