### ISSUE TITLE
Bug report - Useable item / Inf ammo

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3334]
### Assurance

I have read the `README.md`

### Reporter

tyyy1022

### Summary

If you use any useable item (like a medkit) and cancel it whilst reladoing, it will fully cancel the reload and give you full ammo again.

### Steps to Reproduce

Idk start reloading, use a medkit, cancel it with esc, full ammo!

### Expected Behavior

It shouldn't happen?

### Actual Results

It happens?

### Screenshots/Videos

no 

### Game Resolution

normal

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
#3333
