### ISSUE TITLE
Suggestion - Changes in Photo Camera

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3337]
### Assurance

I have read the `README.md`

### Summary

The photo-camera should hide the overlay of Time & Location with a mode or when we turn on Cinematic mode, as thats what cinematic do.
![sample1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/40e8233b-9be0-4290-b71d-61c2c7be2cb6)
![sample2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/e1bc2f08-a01b-41c9-bdb8-4afede27c158)

### Reason

I mean izz a photo camera, I dont' use phone camera, reason: Zoom & Bokeh effect
for photographers it makes it worth using it..
Cropping photo iz hectic and looses resolution too

**Comment by coalaura** [comment]
fixed, cinematic should now hide the overlay
