### ISSUE TITLE
Suggestion - New Robbery Minigame(s)

### ISSUE THREAD

**Issue by Karl-Taken** [InZidiuZ/op-framework-issue-tracker#3338]
### Assurance

I have read the `README.md`

### Summary

Rn, I feel like the hack minigame in city for Bank Robbery, Jewelry Store Robbery, & Gun Run gets repetitive. 

I feel like the first hack for the J store should be changed to something like this:
https://www.youtube.com/watch?v=LgTMKqg4d8w&t=421s

The minigame on this video is from this repo and it's standalone & opensource:
https://github.com/boiidevelopment/boii_minigames

Then the first minigame hack for bank should be this:
https://www.youtube.com/watch?v=LgTMKqg4d8w&t=3m20s

### Reason

This would add more difficulty into hitting the J store and Banks. Since right now the hack is easy and this would also mean everyone now have to learn something new.

**Comment by coalaura** [comment]
people are very quick to learn these things

**Comment by Discordop** [comment]
It would add a variety of things to do though. Since rn the hack is the same for Bank, J store, & Gun Run.

**Comment by PurpleHzea** [comment]
People would be quick to learn but if it was difficult enough while still doable people would seek out "hackers" for jobs. Would also be more interesting than the current tumble hack used for everything. Harder hacks for harder jobs etc

**Comment by coalaura** [comment]
this has been done basically
