### ISSUE TITLE
Suggestion - Changes/Addition in Photo Paper.

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3339]
### Assurance

I have read the `README.md`

### Summary

1. Addition, there should be rectangular version of photo-paper as most photos are rectangular like ex: square one cant fit a group photo
2. The white borders come in photo-papers, it should be borderless.

![218_20240422053431_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/1d271246-1fbe-44a0-b792-c02e2c3512a9)

![218_20240422053222_1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/107997024/9820226f-a889-45f3-91dd-4859ce14b5fd)

### Reason

why? looks cool and ease for the eyes. makes ease for photographer & giving customers their photo in dealership or when someone's bday or smthng party you can gift them with something likee a memory old photo which should be full rectangular, or square with caption but borderless.

**Comment by coalaura** [comment]
done
