### ISSUE TITLE
Suggestion "/attempt"

### ISSUE THREAD

**Issue by FabulousHotdog** [InZidiuZ/op-framework-issue-tracker#334]
**Name:**
Shaggy#9752

**Summary:**
/attempt is a command used in various known sa-mp RP servers including RCRP. It is fairly self explanatory.

 EXAMPLE: "/me picks up the basketball and sets a shooting position"
"/attempt shoot the ball into the basket"

To you programmers reading this the /attempt should look something like this.

"[Player Name] has attempted to [shoot the ball into the basket] and has [FAILED.]"
OR
"[Player Name] has attempted to [shoot the ball into the basket] and has [SUCCEEDED.]"

50/50 chance for either "FAILED." or "SUCCEEDED." 

The best part is I am confident you programmers can implement this feature in under a day, if you wanted.

**Reason:**
This creates a whole new way to RP adding thousands of little games "creative" people can think up. The point of /attempt is for the little things whereas no player could decide if they were successful or not, less arguments.

I had 300 HOURS in one server and because another server added /attempt I switched and never looked back.

Here's a fun true story, say my friend is sleeping with his shoes on. 

/attempt carefully tie a knot with john's shoes

"[Shaggy] has attempted to [carefully tie a knot with john's shoes] and has [SUCCEEDED.]"

Of course I have added the square brackets but it's just to be clear, it is up to you guys to decide how you want to code it.

This command creates ROLEPLAY, this gives us less crime and more creativity.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added, and will go live after next patch.

**InZidiuZ**
*OP-FW Developer*
