### ISSUE TITLE
Suggestion - Remove all items from inventory when jailed

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3340]
### Assurance

I have read the `README.md`

### Summary

Title basically. Keeps people from going to jail with things like radios or phones on them that they realistically shouldn't have access to at all in prison. Have it automatically take your items from you and add a spot that you can get them back from the front desk. Would require removing/disabling the lock on the very front door to the lobby of the prison so people can get in there to get there stuff, and then a change of the teleport location for leaving the prison from out front to inside the lobby

### Reason

Realism, keeps people from just going to prison and popping an arena pill that they brought with them or having contact with the outside world during their prison sentence. Also adds to the roleplay for DOC to potentially be corrupt and smuggle things in, or people finding other ways to sneak things in through visits for HUT characters etc

**Comment by gadjinee** [comment]
I think this should be DOC job, every officer on duty knows what items are allowed and not allowed within the prison. Those items are removed and returned at later date to the prisoners.
In Multiple occasions PD does not confiscate the contraband, that's something that needs to be looked in to as we do have the ability to place the item as returnable during the evidence log. More of RP thing

**Comment by xplrerin** [comment]
Sending people to jail without phones or radios when they have a long sentencing is dumb as hell, that’s basically pushing for them to switch characters or Log off. Don’t play crim but no for a fact that going in there when there’s no doc and you expect them to stick around? Hell naw

**Comment by scufflord** [comment]
Perhaps to help offset it a bit the time per spot cleaned on the floor could be bumped to 5 minutes since longer sentences are becoming more and more common (at least on c3)

**Comment by xplrerin** [comment]
Yea if that was the case then fair enough but I still think being completely shut off when there’s nobody to interact with is shit, everyone runs around talking to friends on their radios or on the phone otherwise it’s mind numbing

**Comment by coalaura** [comment]
I agree that this is more DOC's job if they wish to go down that RP's route. DOC also have the ability to reduce sentences
