### ISSUE TITLE
Suggestion - Increase house storage capacities

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3341]
### Assurance

I have read the `README.md`

### Summary

I've been playing on OP-FW servers since 2021 and since then storages have overall stayed the same except for in Mansions where they were all bumped to 9000 each. During that time however, there has been a MASSIVE increase in the number of items that someone may have in their house, and with that the limited storage weights become an issue that causes people to either go the cheap way and just buy a few rumpos to store stuff in, or have to rent out multiple houses just to store shit. I have an entire house just for materials at this point, and even that gets to a point of overflowing sometimes due to attachment crafting parts, stuff to make pagers etc. 

### Reason

Realism and quality of life.

**Comment by gadjinee** [comment]
Agree with that, increasing storage might stop people from getting 10 houses in same area because they wanna have the storage. Makes more houses available to other people, from realtor perspective

**Comment by xplrerin** [comment]
Most storages were increased, mid-ends, trevors and mansions. Only ones I’d say maybe increase on to incline people to buy them more is Trailers, Janitors and Low-Ends but not even by much because they’re suppose to be “””lower end”””

**Comment by coalaura** [comment]
I already increased the storage sizes of the bigger properties about 7 months ago.

Mid-End Apartment 4500 -> 5000  
Trevor's Beach House 5000 -> 6000  
Michael's Mansion 7500 -> 9000  
Franklin's Mansion 7500 -> 9000  
High-End Apartment 7500 -> 9000

**Comment by CloudCait** [comment]
I personally think High Ends should have the most storage since they’re such big apartments & it would add more value to them. At the moment the only reason people buy high ends is because of the appearance however if you’ve got a high end with a shit exterior it’s harder to sell

**Comment by ayushpatel1007** [comment]
> I personally think High Ends should have the most storage since they’re such big apartments & it would add more value to them. At the moment the only reason people buy high ends is because of the appearance however if you’ve got a high end with a shit exterior it’s harder to sell

high end allow 5 access. Dont know if it is thing for other servers but legacy india have access limits according to house sizes

**Comment by coalaura** [comment]
idm increasing the high end ones from 9k to 10k but i dont wanna go much bigger than that

**Comment by ayushpatel1007** [comment]
> idm increasing the high end ones from 9k to 10k but i dont wanna go much bigger than that

yes i think the current storage setup is sufficient and i think there is another github suggestions where we are talking about storage warhouses , right?.

and if we talk about house shortage, it is not case. there are 5 real estate compnies here having 15+ blocks each. there are lots of house in city

**Comment by coalaura** [comment]
#3271
