### ISSUE TITLE
Suggestion - Physical Vehicle Parts

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3344]
### Assurance

I have read the `README.md`

### Summary

I think our current Upgrade System is fine but it could be improved heavily with the parts being a Physical Item so you could buy something like EMS 5 and take it off one vehicle and swap it between vehicles or maybe allow PD to take parts off your vehicle if it is used in too many crime the only way to get these Physical Items would be at Midnight for Double or Triple the price for having them to have the ability to swap parts around

### Reason

More fun

**Comment by gadjinee** [comment]
It's a cool idea but I'm pretty sure that the whole scrip for upgrade has to be re written

**Comment by HollaYalla** [comment]
I don’t believe it would be because it would just be an add on it wouldn’t replace the non physical upgrades it would just add another option

**Comment by coalaura** [comment]
I don't see a need for this tbh. LS Customs is intentionally designed to make people spend money and switching out parts would mean you wouldn't have to re-purchase the parts. I am planning to eventually make mechanic repair parts items like wheels or doors to allow on the road repairs but i don't think making ls customs like that is a good idea

**Comment by HollaYalla** [comment]
They would cost a crazy amount and always have the risk of them breaking when you pull them off or being stolen and it would be another thing you could add to Midnight and would give them more business and LS customs would stay the same it would just be something that adds risk and rp

**Comment by King2704** [comment]
If they are crazy expensive and theres a risk of them breaking and pd is able to remove them aswell why would anyone want to buy them?

**Comment by HollaYalla** [comment]
I was just throwing ideas out there

**Comment by HollaYalla** [comment]
And the option to have PD take them or the ability to have them on would be upto the server
