### ISSUE TITLE
Suggestion - Flash granade

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3345]
### Assurance

I have read the `README.md`

### Summary

Ability to purchase / craft flash granade

### Reason

I think this could be a great asset for PD, flash granade in situation where push is needed and tear gas is not enough
can be purchased in PD store
Effect of flashing the screen for 5 seconds, doesn’t have to be fully white but just with some effect that makes the player slow or with lower ability to see and aim 

this item can be also craftable in similar way as tear gas  

multiple locations around humain labs that can be utilised, for example we could use the same ingredients to craft the pin and shell but use different components to mix it up and get the flash granade

Ideas for components 
- Alum powder
- Iron Oxide 
- Metalic Fuel ( can be extracted from Scratch remover in tool shop )

**Comment by coalaura** [comment]
what about...epilepsy?

**Comment by gadjinee** [comment]
well doesnt have to be flash flash, can be something like weed / acid effect, something like an effect to disorientate the individual shooting. or even slowing down the movement for 5 seconds, that would not affect any epilepsy

**Comment by coalaura** [comment]
i'm not a fan of flash/stun grenades ngl. I don't think we really need them in rp
