### ISSUE TITLE
Suggestion - Stop spam selling of drugs

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3346]
### Assurance

I have read the `README.md`

### Summary

As of late on the international server there has become an issue of people just spam selling drugs over and over again in an area, and when PD show up they'll flee for 30 seconds to get away then come right back and start selling again. My idea is to introduce the concept of "heat" in an area. So say I'm selling drugs at Vespucci Beach and pd respond to the 66 calls. As long as pd get within a certain distance of that 66 call all of the locals in that area won't want to buy from you because you brought too much police attention to the area because they're nervous about it for say 15 minutes. This encourages people to then go around the city to all of the other places they can sell drugs at to try and move their product while also diverting attention away from other areas for PD side. 

Ideally this should be an individual cool down. If I get a cop to respond to my weed sales, it should trip a flag for locals within x distance of that call to not want to buy from me, but others can still sell.

### Reason

Quality of life

**Comment by scufflord** [comment]
Additionally, add a 5 minute timer after people leave their house before they can sell drugs to keep people from going in and out of a house to sell drugs

**Comment by coalaura** [comment]
i feel like this is very convoluted and PD can just stay in an area to make it hard to sell drugs. This is also only an issue on the international server (the one where people struggle to understand what roleplay is)
