### ISSUE TITLE
Suggestion - New Block

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3347]
### Assurance

I have read the `README.md`

### Summary

Empty property that can be used for multiple houses 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/99a18b56-381a-4cd0-aea7-b5dfa6c28e6a)

### Reason

There’s an abandoned building at Hawick avenue that can be used as a block for at least 3 houses, I think this would be a great location for some mid end apartments or even one of them can be a Michael’s mansion 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/1dffbcdf-7ca6-472e-8846-1a336b6e469a)
Michal mansion ^ 

the garage can be situated there as well as its main entry 

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/a1324c97-f0bc-409a-9b57-4e3829537056)
Mid end apartment n1

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/6f6bcea2-e958-4f00-ac24-014bf633f5a0)
Mid end apartment n2

it’s a great building that can be open

**Comment by coalaura** [comment]
I'd love to make this a block but it looks more like a hotel than an apartment building. The doors are entrances to the lobby not into apartments so it'd be weird to have houses in there that make no sense from the outside (and the other floors are not accessible at all)

**Comment by gadjinee** [comment]
Yeah fair, would be good to be able to have multiple apartments in one house tho, like you would only see your house if you go to the door. But let's say it had 4/5 apartments in it
