### ISSUE TITLE
Suggestion - Bank and Store Robbery Rework

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3348]
### Assurance

I have read the `README.md`

### Summary

The banks that we have right now are way to quick and the stores are way too long so I propose that we change the stuff needed for a bank to this

1 Chip (REQUIRED)
5-6 Thermite (REQUIRED)
3-4 Advanced Lockpicks (REQUIRED they get used)

What will happen is you will have to Chip the front door then thermite the second door then on each safe box you need to thermite each box then do the minigame that is in the stores right now

For the Stores it will be changed to the Registers take 1 advanced lockpick and it has a 50/50 chance of breaking and it will just be like the car hotwire thing were its a loading time but it takes like 2 minutes so PD have time to get there and the back will require 1 thermite and then the Lockpick Minigame

### Reason

Better Robberies

**Comment by gadjinee** [comment]
It would be cool to have something like this to the big bank at vinewood

**Comment by coalaura** [comment]
> It would be cool to have something like this to the big bank at vinewood

#3040

I don't mind making stores a bit easier and banks a bit harder. Not exactly like you said but i got an idea
