### ISSUE TITLE
Garage @ MRPD

### ISSUE THREAD

**Issue by KPNutz** [InZidiuZ/op-framework-issue-tracker#335]
**Name:**
Kieran#6701

**Summary:**
Create a garage at PD which can be used by officers to store off-duty vehicles when going on-duty. 

**Reason:**
Realistically officers would drive to work, park in staff parking, then go on duty. However, I’ve tried to do this multiple times only to return to find my car smashed up, stolen or towed. This addition would make for much better RP for officers who choose to continue their character’s story off-duty.

**Comment by ZurxeyH** [comment]
I completely agree with this. Also, motels that have garages around the area. (The one on great ocean highway would be such a beautiful area for a garage in the big parking lot)

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
