### ISSUE TITLE
Suggestion - Counter & Storage for DOC

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3350]
### Assurance

I have read the `README.md`

### Summary

There should be a counter at the front inside the building where prisoners gets teleported to when they are released. It just makes sense that returning stuff is done in the DOC.

In This Building:
![Screenshot_21](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/50b2882e-0a72-4f22-a26e-ff7ea83a8472)

Counter Here:
![Screenshot_22](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/d814f341-83c2-471e-a7a9-555730e79f56)

Storage Here:
![Screenshot_23](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/227c99cc-4aa4-4c82-aec6-64397af914f6)

### Reason

QOL

**Comment by coalaura** [comment]
all done
