### ISSUE TITLE
Suggestion - Being able to take selfies inside a car

### ISSUE THREAD

**Issue by Imaghost1337** [InZidiuZ/op-framework-issue-tracker#3351]
### Assurance

I have read the `README.md`

### Summary

It's common knowledge that you can take selfies (using the middle click button) with your phone when you're outside a vehicle, however inside a vehicle you can only take pictures with the back facing camera. It would be very cool to be able to take selfies when inside a car.

### Reason

It would give more opportunities for unique pictures being memorised. For example 'new car' or 'getting chased by cops rn' type posts. It would just give 1 extra thing for people to be able to do.
It's a non invasive addition that everyone in the city can benefit from.

**Comment by gadjinee** [comment]
That would be really cool

**Comment by coalaura** [comment]
after playing around with it gta itself seems to disable the front camera in vehicles. sadly that means we cant achieve the same selfie style front camera in vehicles
