### ISSUE TITLE
Tweak to cars

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3353]
### Assurance

I have read the `README.md`

### Summary

Can drive car if keys are left in it

### Reason

Make it so cars follow the same rules as bikes, 

as long as it’s left running your good to snatch it. Right now when you jump in a car left running, it asks for keys

**Comment by coalaura** [comment]
No, its intentionally only bikes that can be driven without hotwire when the engine is left on
