### ISSUE TITLE
Suggestion - Allow Seat Belt dinger bypass

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3354]
### Assurance

I have read the `README.md`

### Summary

Two options

- Allow midnight employees to remove the seatbelt dingaling thing and have the modification show up in /check_vehicle_upgrades 
- Add functionality to the tuner chip. PD can then review it as an illegal mod if they want that RP.

### Reason

The dinging makes people crazy and we could always use more chances for fun ejecto-seato moments (if people opt-in to it).

**Comment by scufflord** [comment]
please god yes. sometimes you gotta get in and out of your car over and over but you ain't going far or fast enough for it to be dangerous (picking shrooms is a good example, or mining even) and this would be a godsend for that

For the inevitable "realism" argument I can say for a fact that Ford has a way to bypass this on their trucks for this exact reason. Farmers, construction workers, mining environments etc

**Comment by PurpleHzea** [comment]
Or just put your seatbelt on

**Comment by scufflord** [comment]
Yeah but funny rp moments of getting ejected are worth it

**Comment by MetaHatter** [comment]
Much of the best RP comes from giving people the most opportunities to make TERRIBLE life choices...
