### ISSUE TITLE
Suggestion - Toggle option for chop radio noise

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3355]
### Assurance

I have read the `README.md`

### Summary

Allow the ability to type a command to stop the annoying radio static noise from happening until you take the radio out of your inventory. 

### Reason

quality of life. would be nice to keep a radio on you throughout the day and if you happen to notice  the car and want to grab it you can, and without having to hear the KSSSHKSSHHH headass noise lmfao

**Comment by HollaYalla** [comment]
I would love to have this but make it like a command like /chopshop so you can see if its off before you even grab it

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/YKBLOQQO97.webp)
