### ISSUE TITLE
Suggestion - Make Chop Relevant Again

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3356]
### Assurance

I have read the `README.md`

### Summary

Chop isn't really done that much anymore compared to in the past - at least on the international server - but I've been doing a lot of solo chop for fun lately and had some ideas to spice it up a bit and potentially get more people doing it again:

**- Addition of the shotguns that were previous in the dailies loot pool**
Since there is a daily for you to go do chop this would still provide an avenue for criminals doing dailies to potentially get these shotguns. Additionally, perhaps the addition of some type of SMG (maybe the gusenberg?) could be cool, but that may be a stretch. 

**- Addition of items you typically see players leaving in their cars**
We're all humans at the end of the day, so it would make sense for the locals to be doing similar things to us and carrying similar things. Some ideas I had were pagers (to allow chop to be a good stepping stone into the world of crime, like it used to be), advanced repair kits (helpful for mechanics as well as for keeping your car going if you're chopping as a group, random gems, drills, ammo etc 

**- Increase the drop chance of tuner chips**
As is these things seem to VERY VERY rarely drop which leaves the market relatively dry for them. Increasing this drop chance slightly so people end up getting them more often may create a market for them again, and thus more roleplay opportunities

**- Change fake plates to be stackable and 1su**
The majority of the player base doesn't use fake plates because of how much space they take up and the fact you can't stack them. At the end of the day it's a thin piece of sheet metal - I'd be surprised if a real license plate weighed more than 2 pound. Additionally, it's a thin piece of sheet metal so it makes SENSE to stack them

**- Add in cool flavor items like diving and scuba have received that players can sell at a pawn shop or break down for materials to make stuff**
Things like aftermarket stereos, laptops, gps systems, even speakers/subwoofers. Typical stuff that someone would acquire out of a car when they steal it and strip it. Then they can either break the tech stuff down into parts for things like pagers, scopes, etc etc 

**-Add glass drops**
Car windows bruh. Lemme get some glass.

**Final Remarks**

Overall I think the material drop rate for chop is spot on where it needs to be. I would say perhaps removing motorcycles from the rotation could be a good idea - most people typically just stop doing chop if a bike pops up because they're almost impossible to find. If it's possible also, perhaps skew it so it prefers to pick cars that aren't being driven around so you don't end up with situations like going to the called out area and the car just isn't anywhere near it.

### Reason

Chop is dead, but we have the tools to rebuild him.

**Comment by scufflord** [comment]
Had another idea: since some local cars come with upgrades now maybe the people that run chop shop will pay you a bonus for any upgrades the car has on it

**Comment by coalaura** [comment]
something like this
