### ISSUE TITLE
Bug report - Flying when jumping from stairs 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3359]
### Assurance

I have read the `README.md`

### Reporter

gujju_businessman

### Summary

BLock: Invention Court
House Number: Invention Court 18

So this house, have 2 doors from which back door is on the stairs. So a guy when coming out of house jumps through stairs, he gets thrown on house oppsite the road as shown in below image.

This won't happens if u haven't entered house and then jump from the stairs.

### Steps to Reproduce

-

### Expected Behavior

Jumping should land us near stairs

### Actual Results

Jumping From stairs should not throw us on onther side of road

### Screenshots/Videos

Door where this is happening
https://imgur.com/J3oWvtt

Place were we get throwed 
https://imgur.com/9ll5EQ2

House Exterior Facade
https://imgur.com/undefined

### Game Resolution

Medium

### Player Data

Happens with everyone

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
This is a known issue, sadly we don't know the cause
