### ISSUE TITLE
Suggestion - Converting Cash to Casino Chip

### ISSUE THREAD

**Issue by Karl-Taken** [InZidiuZ/op-framework-issue-tracker#3360]
### Assurance

I have read the `README.md`

### Summary

I feel like there should be a way for cash to be converted to casino chips. Maybe casino owner can convert cash to chips at the counter?

Then when playing blackjack you should have actual casino chips instead of cash because that's just how it is.

### Reason

It would be cool if we could get casino chips to run like illegal gambling room. This way there's a physical thing PD could confiscate during a bust. It's also just more realistic this way.

**Comment by coalaura** [comment]
yeah like mentioned i feel like this would get abused. idk if there is more planned for the casino chips but for now, no
