### ISSUE TITLE
Suggestion - Command for Gun Run

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3361]
### Assurance

I have read the `README.md`

### Summary

If possible there should be a command to turn gun computer on and off. Similar to how gun trader can be turned on and off with a command.

### Reason

This way we wont have to restart the server every time we want to turn gun comp on/off. We would also not have to change config a lot.

**Comment by coalaura** [comment]
No, gun running is not meant to be constantly toggled on and off. Either you want to use it or you don't and thats what the server config is for

**Comment by coalaura** [comment]
there is also no command to disable the gun trader

**Comment by Discordop** [comment]
I thought there was 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/67985497/bcdfd9a1-8cdc-40ec-9e16-6962a081fe82)

**Comment by HollaYalla** [comment]
That is just telling you what to put into the config to enable/disable it as it would probably look like this

CONFIG

disable_gun_computer: false # By Default this is set to false so the computer is enabled
disable_gun_trader: false # By Default this is set to false so the trader is enabled

**Comment by HollaYalla** [comment]
The only 2 actual commands are the Debug and the instant unlock for testing

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/47928bfe-0d2b-4e7b-9fff-6cdbc66d3a61)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/52ace86c-81d0-42a7-8fe9-c7925cb6ab5b)

**Comment by Discordop** [comment]
ohh I thought I was on the commands page thats my bad
