### ISSUE TITLE
Suggestion - Evidence Paper Bag

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3362]
### Assurance

I have read the `README.md`

### Summary

When arresting someone and getting all their belongings like phones, smartwatch etc. I feel like there should be a spot in front of the mugshot room at MRPD to place their belonging in a bag like in bean machine. 

### Reason

This will help organize evidence room more so that items are not too cluttered.

**Comment by Discordop** [comment]
How would they leave the city? the bag will be in PD's custody until their release. Its just so that the items are bundled up in a bag instead of scattered throughout 1 row of the locker.

**Comment by Discordop** [comment]
Sorry, I don't understand. My suggestion is just asking to add paper bags where PD can put items that needs to be returned to player back to organize the evidence-locker. Once the sentence is up PD will give the paper bag back to the person. This is just to organize the locker much better.

**Comment by coalaura** [comment]
There is a reason paper bags are restricted in what you can put in them. This **WILL** get abused not a single doubt about it. DOC has a huge shared storage for this exact reason.

**Comment by SluggsV2** [comment]
adding onto this, i think there should be an item to help clean up the locker. make a New Pd Clear bin or something that has no restrictions that only PD can buy and Use. Case after Case, arrest after arrest, its starts to get cluttered and theres no denying it. i fully agree with making PD lockers more orgainized!

**Comment by coalaura** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/32370325/1c9cd4cc-e67c-454a-b683-5901fe74ecaa)
