### ISSUE TITLE
Suggestion - Roll 5 joints at once 

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3363]
### Assurance

I have read the `README.md`

### Summary

Add the ability with 5q's in your pocket and 1 green roll to just roll 5 joints at once instead of manually having to do each one

### Reason

Quality of life, i had to roll like 40 joints for customers the other day and realized its super slow lmao

**Comment by coalaura** [comment]
i don't really like the idea of rolling a bunch of joints at once in your pockets but i'll speed it up a little

**Comment by HollaYalla** [comment]
> you can already roll 4 at once by using an ounce instead of a quarter

You can’t get strained ounces

**Comment by scufflord** [comment]
yeah the strains are super popular now that people have figured out what they do, and having to roll 1 at a time is painful lmfao
