### ISSUE TITLE
Suggestion - Command for mouse mode swap

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3364]
### Assurance

I have read the `README.md`

### Summary

Would be nice to be able to quickly swap from mouse mode to keyboard mode for the phone so say you're driving and wanna check a ping you can just bind a command, swap to keyboard mode, and check it. Then swap back to mouse mode when you want to as well.

### Reason

I keep hitting things at mach 7 trying to check my texts

**Comment by coalaura** [comment]
don't text and drive. jk, but fr i don't think we need a whole command for this
