### ISSUE TITLE
Suggestion - Ping latest dispatch command/bind

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3365]
### Assurance

I have read the `README.md`

### Summary

Add the ability to press a button or type a command to have a gps marker added automatically to the latest call that comes over pd dispatch, chop shop, ems stuff if they work the same way, etc

### Reason

quality of life, plenty of other frameworks feature something similar

**Comment by coalaura** [comment]
You can now use (and bind) `/mark_last_phone_gps`

**Comment by scufflord** [comment]
> You can now use (and bind) `/mark_last_phone_gps`

phone gps, does that mean this is for like 911 calls, or would this work if like 10-71 calls came in or 10-66 etc

**Comment by coalaura** [comment]
the last GPS coordinate ping, so if someone texts 911 and then someone sends you a GPS ping directly the second one counts

**Comment by coalaura** [comment]
ooh that way around is what you meant

**Comment by coalaura** [comment]
i will change the command to be /mark_last_dispatch

**Comment by scufflord** [comment]
W LAURA MOMENT IN THE CHAT LETS GOOOO
