### ISSUE TITLE
Suggestion - Add sweets to burgershot

### ISSUE THREAD

**Issue by Cypher45** [InZidiuZ/op-framework-issue-tracker#3366]
### Assurance

I have read the `README.md`

### Summary

Addition of sweets like donuts, ice cream, milk shakes would be great and there is already a stand with donuts but with no donuts 🥲.

### Reason

Because burger shot would be kind of mc donalds and there are already no sweets like things available like ice cream, donut etc.

**Comment by coalaura** [comment]
thats more bean machines job
