### ISSUE TITLE
Suggestion - Tracker Destroying

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3367]
### Assurance

I have read the `README.md`

### Summary

Recently a lot of cops have been getting kidnapped and the criminals just do /me breaks tracker so we were thinking of a new way for criminals to break trackers it would be a command /break_tracker for the cop to do and it would send a ping such as a officer down saying “Officer Tracker Broken” and it will show the exact location of this and maybe leave evidence on the ground that if processed it comes back to which officers tracker it was and then when the situation was back to normal they just do /tracker_new or /enable_tracker and it re-enables your tracker as if you got a new one

### Reason

Better RP

**Comment by coalaura** [comment]
You already have a command for "destroying" your tracker, this command would chang nothing but just add the callout. I don't know if the calloud is needed or should be added, would make it VERY hard to even try to kidnap a cop, the 10-14 button only works while down for a reason

**Comment by HollaYalla** [comment]
Most of the time when you kidnap a cop you handcuff them then destroy their tracker the instantly leave atleast in my experience but this would add that little bit of help mainly so the cops can start searching areas for a kidnapped officer it makes sense in my opinion and kidnapping a cop should always be a hundred times harder to do than a Criminal as we have more equipment and more advanced stuff

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/HSOABNMSP7.webp)

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/UT114IYUCH.webp)
