### ISSUE TITLE
Suggestion - Add options to /no_copyright

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3368]
### Assurance

I have read the `README.md`

### Summary

Add the ability to restrict boomboxes and not TV screens, or at least mute the audio from tv's but still show the image. I wanna be able to see menus in businesses but I also don't care about the dude driving around the southside blasting Da Baby lmao. 

### Reason

QoL

**Comment by coalaura** [comment]
I've added a /mute_boomboxes command instead which will toggle boomboxes. It is saved between sessions similarly to /no_copyright
