### ISSUE TITLE
Suggestion - Parking Meter Robbing

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3369]
### Assurance

I have read the `README.md`

### Summary

A new small criminal way to make money would be allowing the robbing of Parking Meters and to do this you would get a Multi-Tool (so you need some sort of preparations) and you would walk up to a Parking Meter than use the Multi-Tool then you would need to do 1 of the Stores Dial Spinning or it is a loading bar type thing and you can get 50-200 dollars from them and it has a 20% chance to call the cops to stop people from chain robbing them without total consequence but it still is easier as it is a petty crime and is meant to be done quickly for a quick buck but the Parking Meters take 1 Hour to refill with money to stop the mass robbing of them.

### Reason

More Petty Robberies

**Comment by coalaura** [comment]
I don't think parking meters should be robbable since that would be very easily abusable (which is why you cant find very valuable things in dumpsters) there is also a lot of parking meters and either nobody would do it (cause it gives too little) or everyone would grind the shit out of it
