### ISSUE TITLE
Suggestion - Ability to put bicycles in trunks

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3370]
### Assurance

I have read the `README.md`

### Summary

Ability to Put BMX in Van or Truck bed

### Reason

Kind of like putting a player inside of the trunk think /bmx and it will pick up the bmx bike, it can then be placed into a truck bed or Van trunk, 

It will not work in cars or suvs! 

A small feature that can go a long way

**Comment by coalaura** [comment]
#3203

**Comment by coalaura** [comment]
For now i've added the ability to carry bicycles using /pickup_bicycle or /pb. I'll add the ability to then put them in a trunk soon too.

![yes](https://i.shrt.day/YPGDMTN5OA.webp)

The default hotkey for dropping the bike is "X" but can be configured in the keybind settings.

![yes](https://i.shrt.day/JHYWHGX3WU.webp)

**Comment by coalaura** [comment]
this has been completed now
