### ISSUE TITLE
Suggestion - Rename Admin Fix command

### ISSUE THREAD

**Issue by Discordop** [InZidiuZ/op-framework-issue-tracker#3372]
### Assurance

I have read the `README.md`

### Summary

The /fix command for admin and /repair command for pd/ems is so similar. I think renaming /fix to /admin_fix or /admin_repair will be a better fit for it.

### Reason

QoL

**Comment by coalaura** [comment]
considering how little people have access to the /fix command and how alphabetically different they are i don't think this is needed
