### ISSUE TITLE
Suggestion - Ownable Penthouse

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3373]
### Assurance

I have read the `README.md`

### Location

We have several open interior public penthouse inside the city. Each building contain one to three penthouses each. The available lists are:

**4 Integrity Way** - 3 Penthouse
**3 Alta St** - 1 Penthouse
**Del Perro Heights** - 2 Penthouse
**Weazel Plaza** - 2 Penthouse
**Tinsel Towers** - 1 Penthouse

Apart from these building there are two more apartment in GTA Online, but there is no teleporter in Legacy. They are:

**Eclipse Towers
Richards Majestic**

### Penthouse Selling

The penthouse selling will work similarly to the license. The cost will entirely depend on the state through RP. You can sell or remove the penthouse using commands.

**/sell_penthouse [character cid] [penhouse id/address]** - The owner of a penthouse will be a single person. The state will sell it to the renter. The address can be for example: _Del Perro Heights Penthouse1_ or _3 Alta St Penthouse1_

**/remove_penthouse [character cid] [penhouse id/address]** - It will remove the access of the penthouse from the owner and all residents.

### Manage Penthouse Access

It will work similarly to the _garage access_. You can include a **/manage_penthouse** command and the UI will be similar like below.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/9279e013-1b5c-4764-9e74-d8e70b7e113c)

The owner can include people and they will have full access to the locks, storage, and garage.

### Locks

After using the entrance, there's a main gate in every penthouse. Currently, there are no locks in it. Add a locks only to the main gate and it should be sufficient.

### Storage

_Public locker_ will be the best for penthouse. Every person who has access to that penthouse will be able to access it. The storage capacity can be 10,000.

However, if a public locker isn't possible to implement, you can add a private locker with reduced capacity. In that case, restrict keeping drugs and weapon to make the storage balanced.

### Personal Garage

Those who are owner or have access to the penthouse will have a private garage at the building.

### Spawner

The spawner will work similarly to the PD. If you have the access, you will spawn at (x, y, z) coordinates. In this case, it should be in front of the main door.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/7f56985d-37f2-42a3-b1cf-c72dc2acc188)

### Interior

There's nothing to change with the interior. It's perfect and beautiful.

### Reason

Besides _four CEO office, and three two storey office_, there are nine penthouse in Legacy Roleplay. If you add two of the appartment buildings from GTA Online, the total number will be more than 11.

Some building has multiple penthouse. And making all of them public isn't necessary for RP. Also, all the penthouse are not utilized at the same time.

So, I suggest making **half of the penthouse** ownable. It will keep a balance to the ownable and public penthouse,. It will benefit more to the city and increase the efficiency of these property.

Most importantly, the transparent view from the window is not replicable in our blocks house. For which many people want to have these types of house to their collection.

It will be a great addition to real estate and people will go crazy for having one of these penthouses.

**Comment by Faisalhasan7** [comment]
Excellent plan, I hope devs will implement this. It will bring more realism to the server. State can ask for a huge chunk of money for it. It'll be great for the millionaires. This penthouse idea will be great addition.

**Comment by Valoci-Raptor** [comment]
That's cool idea, state property rp will increase & others can do more realistic rp at their own space.

**Comment by SluggsV2** [comment]
This is a sweet idea, I think a cool feature maybe you could have a private garage that you can show off 6 - 10 cars, can use a base interior from GTA online, or if they had their own EDM garage, (not sell point but interior wise) that could be a little much tho!

**Comment by coalaura** [comment]
I kinda like them being open for everyone to use as they wish... They would very quickly sell out making it so nobody else can use them. Eclipse Towers is intentional, that apartment is in use.

I will add an elevator for Richards Majestic but i want the penthouses to stay open for public use not private.
