### ISSUE TITLE
Suggestion - Multiple logged in twitter accounts

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3375]
### Assurance

I have read the `README.md`

### Summary

SO currently we can log in in single account at a time and then if we want to switch accounts, we have to log out of one account and then login in to another account. and veriversa.

what if we can keep 2 account logged in at same time and just switch between them. 

Also we cant only switch between  2 accounts max so that people dont make like tons of account 

### Reason

it would be fun having 2 account as people anyways use mutliple account on twitter to sell illegal stuffs. And while doing white stuff they use their own name account. It will help players to easilly switch.

**Comment by coalaura** [comment]
You can now switch between 2 accounts (per character). The Switch account button will basically just swap your currently logged in user with the saved "secondary" account. Kinda like having 2 seperate tabs you switch back and forth

![yes](https://i.shrt.day/UCYYBUO06V.webp)
