### ISSUE TITLE
Adding garage to cayo perico airport block

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3376]
### Assurance

I have read the `README.md`

### Summary

So this block was recently added but none of the houses here have garage. People travel all the way to cayo and relax at theiir new bought house at cayo and they see they have no garage.

we have space where we can added garage so please add it. 
there are 3 house in this block and none of them have garage.

https://imgur.com/a/nt2iHfv

### Reason

every other house have garaage then why not this ones

**Comment by scufflord** [comment]
my brother in christ there is a public garage 10 feet away from the door...

**Comment by HollaYalla** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/8b98e931-b909-40ac-a268-8867246ca145)
Found your Garage

**Comment by HollaYalla** [comment]
Its that Blue One

**Comment by ayushpatel1007** [comment]
> my brother in christ there is a public garage 10 feet away from the door...

i am not owner of house, it was request from the house owner. but even if i was owner, i would love to have my personal garage rather than using public garage no matter how far or near it is

**Comment by coalaura** [comment]
> > my brother in christ there is a public garage 10 feet away from the door...
> 
> i am not owner of house, it was request from the house owner. but even if i was owner, i would love to have my personal garage rather than using public garage no matter how far or near it is

This is stupid, there is 0 difference between a public and private garage, they are the exact same
