### ISSUE TITLE
/savings update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3377]
### Assurance

I have read the `README.md`

### Summary

a quick glance maybe a second page inside each savings account for total amount put in and taken out by each person that has access

### Reason

This would help with business owners and gang leaders to get a quick and easy glance at how much each has taken out or put in, this would help insanely especially once there's 100s of transactions, i find it hard to keep track once i have to step outta city for a day or 2!

**Comment by coalaura** [comment]
It would be only the last 90 days tho

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/VIYQGM232R.webp)
