### ISSUE TITLE
Suggestion - Refunding furniture items when you delete them

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3378]
### Assurance

I have read the `README.md`

### Summary

When you delete a furniture item you should be able to get the money back

Maybe have it as a timer, like if you place a furniture item you have a certain amount of time to delete and get it refunded

### Reason

A lot of money can get wasted when items turn into toilets lol, for example I placed like 10 table 3 to make the floor black marble, i left the house came back and they were all toilets (unless i'm being stupid and theres a solution to have the toilets revert back to their original state)

Many furniture items can turn into toilets, or you just decide the item doesn't look right with the rest of the decor but it was expensive like those $700 tv sets, you should be able to get a refund on these. 

This would be particularly beneficial to the decorators in the server who make a living out of decorating houses

**Comment by coalaura** [comment]
Props that turn into toilets only TEMPORARILY turn into toilets. They turn into toilets when the game takes too long to load the model. I don't think you should get the original price back but maybe like a percantage

**Comment by coalaura** [comment]
ATM and weed plants will not be refunded tho
