### ISSUE TITLE
Suggestion - Leaving a Savings Account

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3379]
### Assurance

I have read the `README.md`

### Summary

Right now, if you do not want to be a part of a savings account you have to ask the savings account owner to remove you. But what happens if the savings account owner no longer flies in and you are just stuck on that savings account for ever with a list of people that you don't know who can access that account. 

This puts money at a liability and depending on how well you choose your friends, you could also hit the max amount of savings accounts pretty easily if you cant manually leave them.

### Reason

Financial Responsibility

You can only be apart of 6 accounts so you have to be in them responsibly and you should be able to leave an account you do not want to be apart of anymore.

**Comment by coalaura** [comment]
I'll add a "leave" button or smth like that

**Comment by ayushpatel1007** [comment]
What if a guy withdraw all money and leave savings?? Because many companies also use /savings

**Comment by coalaura** [comment]
> What if a guy withdraw all money and leave savings?? Because many companies also use /savings

What is stopping them from doing it rn? Leaving the savings account wont delete logs

**Comment by Kay32** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/85036959/692e79d7-8cf6-4a31-ad38-2dd32fdd49df)

Right now, theres both sequential logs and summarized logs
You'd still be able to track who took what money
