### ISSUE TITLE
More exclusive dealership cars

### ISSUE THREAD

**Issue by Camdaddy34** [InZidiuZ/op-framework-issue-tracker#338]
Camdaddy#6835
Who is suggesting this? Please include discord name.

Just throwing this out into the world, as I know this isn't probably wouldn't take a huge priority on list of things to do, but I've been hearing a lot of in-game talk about how there are wishes of more cars within the exclusive dealership. Personally, I'd love a Dodge Hellcat or a Demon in the market, if we're keeping favorites in mind. Could also potentially introduce some Libertywalk style liveries or even LS Custom options for the vehicles to really let people get creative with their cars. 
Write a short summary of what your suggestion is about.

I believe it would add tremendous variety to the car scene. I've seen a lot of rx7's, supra's, etc running around the city in every shape and form, and I know there are characters out there that prefer the muscle cars. Very small suggestion, but just something I've been thinking about. Great job on the server, I absolutely love it! 
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Hey,

 Post this in the asset-related GitHub issue tracker.

**InZidiuZ**
*OP-FW Developer*
