### ISSUE TITLE
Bug report - Hospital elevator to Surgery takes you in the middle of the road.

### ISSUE THREAD

**Issue by uolla** [InZidiuZ/op-framework-issue-tracker#3380]
### Assurance

I have read the `README.md`

### Reporter

GambloTwitch

### Summary

When you use the elevator for the Hospital 1 trying to go to Surgery, you get tp'd in the middle of the road.

### Steps to Reproduce

Go to the Los Santos Medical Center. Get into the Elevator and try to reach the Surgery room.

### Expected Behavior

You should be able to reach the Surgery room.

### Actual Results

You will be teleported in the middle of the road.

### Screenshots/Videos

https://i.imgur.com/BPQcfKw.mp4

### Server

Italy (c5s1.op-framework.com)

**Comment by coalaura** [comment]
ok i'll close this issue for now then. If it does happen again, i've added a bunch of logs to teleporting that should give me a better idea of what exactly is not working. Those logs should be in your F8 console right after teleporting (in any form like evelators, teleporters, /tp, etc.)
