### ISSUE TITLE
Suggestion - add default kill flash option to custom crosshair menu

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3381]
### Assurance

I have read the `README.md`

### Summary

So I like having a green dot for my crosshair personally, but I like the red X animation that plays with the default one. It would be nice if we could have that same kill effect happen while using a customized crosshair.

### Reason

quality of life

**Comment by HollaYalla** [comment]
Tbh this would probably only give people an advantage and allow people to use external software to get an advantage if it was a thing please make it able to be turned on and off on each server because I do know on the international server that stuff is against the rules

**Comment by scufflord** [comment]
> Tbh this would probably only give people an advantage and allow people to use external software to get an advantage if it was a thing please make it able to be turned on and off on each server because I do know on the international server that stuff is against the rules

it's not against the rules it's literally built into default GTA and into the custom crosshair settings for OP-FW

https://i.ibb.co/hd2x0vD/tvl-PNOEk-Gq.png

**Comment by DaxterPancake** [comment]
It has been a few years but I believe this in general was turned off coz it's more realistic to not have a confirmation when you kill someone for RP purposes

**Comment by scufflord** [comment]
> It has been a few years but I believe this in general was turned off coz it's more realistic to not have a confirmation when you kill someone for RP purposes

it's never been turned off in the 3 years ive been playing on Legacy International, it's always been a thing

**Comment by DaxterPancake** [comment]
> > It has been a few years but I believe this in general was turned off coz it's more realistic to not have a confirmation when you kill someone for RP purposes
> 
> it's never been turned off in the 3 years ive been playing on Legacy International, it's always been a thing

That's wild since I remember testing it & also having the death flash thing turned off aswell. Who knows tho I have been around too long every memory has turned to putty in my brain (send help)

**Comment by coalaura** [comment]
i cant really mix and match native and custom

**Comment by scufflord** [comment]
would it perhaps be possible to make it so that either the "Main" or "Outer" could just have an option to only appear with the kill flash if people want? could accomplish the same thing
