### ISSUE TITLE
Bug report - Can't access storage of Own House 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3382]
### Assurance

I have read the `README.md`

### Reporter

gujju_businessman

### Summary

So i dont how many people are facing this issue but i got complain from 2-3 people that they can’t access storage of their own house also they are unable to plant weed in house.

House in below images:
Normandy Drive 8
Michale Mansion

Also i have noticed that when we plant weed plant , it got planted but it didnt use seed in my inventory and also i didnt have bucket in my inventory. Also after it get planted , i cant water it or use fertilizer on it. 

Below are images 

### Steps to Reproduce

?

### Expected Behavior

We should able to access the storage.

We should able to water and fertilize the weed plant.
Also 1x seed should be deduted from our inventory while planting

### Actual Results

?

### Screenshots/Videos

CANT ACCESS STORAGE:

STORAGE 1
https://i.imgur.com/Ky2PkVX.jpeg
https://i.imgur.com/cd4eQdI.jpeg

STORAGE 2
https://i.imgur.com/EMfQrhl.jpeg
https://i.imgur.com/wEF7n76.jpeg

STORAGE 3
https://i.imgur.com/PL4rJ1S.jpeg
https://i.imgur.com/kc6elw6.jpeg

CANT WATER OR FERTILIZE WEED PLANT
https://i.imgur.com/YgwXzZh.jpeg

### Game Resolution

Medium

### Player Data

https://i.imgur.com/4gnHqF7.png

### Server

India (c8s1.op-framework.com)

**Comment by scufflord** [comment]
this should be fixed with the next update.
