### ISSUE TITLE
Suggestion - Third eyes?

### ISSUE THREAD

**Issue by itzCali00** [InZidiuZ/op-framework-issue-tracker#3383]
### Assurance

I have read the `README.md`

### Summary

Title/Topic: Third Eyes

Objective/Purpose: To make the framework even faster without wasting time typing commands for any purpose, especially since there are too many commands in the framework, newcomers struggle to understand how to manage the situation without having to open the command guide every time.

### Reason

Am asking this update because of some point of view.
like i said before to make the thing even more easier and also because in Legacy Italy our players cant remember all commands and they are not going at all in our server because of this, so if there's any small change to get even a beta of this third eye of few integration like /give_cash or /give_key and so on to make just small start thing just a bit easier will be super nice and so helpful and step by step with time updating this script to have it full updated with all scripts.

Thanks and we hope u might consider our request a huge hug from the staff :)

**Comment by coalaura** [comment]
what do you mean with "third eye"

**Comment by HollaYalla** [comment]
EWWWW NO

It’s like what ESX and QB Core have to interact with stuff, Third Eye is so stupid and breaks RP so much

**Comment by coalaura** [comment]
wtf is third eye lmaooo i've never played on an esx/qbcore server

**Comment by HollaYalla** [comment]
![](https://i.ytimg.com/vi/L6TNqELdngY/sddefault.jpg)

**Comment by HollaYalla** [comment]
That

**Comment by itzCali00** [comment]
yes, like will be so easier and fast for command and other staff, u will have more interaction and ppl can interact with everything

**Comment by itzCali00** [comment]
and also this was also a selfish request, because in our community we are loosing player for this reason, cuz they dont know command and they get sick typing command

**Comment by HollaYalla** [comment]
OPFWs goal is to be different then other servers Third Eye is on nearly every other server and personally I would quit any OPFW server if we had that and I know a lot of people probably would aswell because you can’t hide crafting spots like you can now because people would just run around holding ALT and finding all the locations plus just set up a hotkey or get a stream deck

**Comment by HollaYalla** [comment]
You would get a lot more people who don’t want to put any effort into rp than there already is

**Comment by itzCali00** [comment]
> OPFWs goal is to be different then other servers Third Eye is on nearly every other server and personally I would quit any OPFW server if we had that and I know a lot of people probably would aswell because you can’t hide crafting spots like you can now because people would just run around holding ALT and finding all the locations plus just set up a hotkey or get a stream deck

am completely agree with u with this

**Comment by itzCali00** [comment]
but Ben can make this as Config like make it false or true if u want to enable or not

**Comment by itzCali00** [comment]
i mean if its possible, so in international one they will not have the third eye and who wants it maybe they can enable it for make this easier

**Comment by coalaura** [comment]
I feel like this can quite easily be accomplished with keybinds. Keybinds also allow people to customize them to their needs. It would be a somewhat big endeavor to get all the different commands and who can use them into one usable menu...
