### ISSUE TITLE
Suggestion - Split radio keybind away from special ability keybind

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3385]
### Assurance

I have read the `README.md`

### Summary

Currently the default radio bind is tied to the "special ability" option in the gta settings, meaning that in order to pedal fast on a bicycle you basically need to hold your radio open the whole time you're riding. Since we've started to get more and more user configurable keybind options with more recent updates to the framework I was wondering if this could be split apart so I could theoretically pedal fast on my bike by pressing a different button and not have to be breathing into the radio for my entire gang to hear like a creepy stalker from an 80's horror movie.

### Reason

quality of life

**Comment by coalaura** [comment]
You can only add keybinds for commands in fivem. We have to have it set to a fixed key sadly since we need to know when you start pressing it and when you stop to know when to transmit and when not to, which wont work with a command keybind.
