### ISSUE TITLE
Suggestion -  Ability to send live location to someone using phone 

### ISSUE THREAD

**Issue by RDXMANI** [InZidiuZ/op-framework-issue-tracker#3386]
### Assurance

I have read the `README.md`

### Summary

Be able to send/see a person's live location, So they can keep track of our location.

### Reason

It helps in improving RP and helps players and police while their squad is chasing after criminal.

**Comment by SluggsV2** [comment]
You can already ping friends via phone, i

**Comment by coalaura** [comment]
No, i don't want trackers for civillians
