### ISSUE TITLE
Bug report - meth sales bug

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3387]
### Assurance

I have read the `README.md`

### Reporter

scufflord

### Summary

Currently even if you get declined for a sale of meth to a ped you can keep spamming E over and over again until they accept the bag. They'll freeze up and try to call the cops on you a bunch, and pay you for the meth. On the PD side of this, it ends up meaning that every time somebody tries to sell a bag we get spammed with back to back to back calls within seconds of each other until the sales go through. It's super annoying and also super gimmicky when it comes to selling it.

### Steps to Reproduce

Spam E while trying to sell meth

### Expected Behavior

if they say no, call cops or just walk away without calling cops. if say yes, they buy drugs.

### Actual Results

EVERYBODY BUY DRUGS BECAUSE I OFFER IT A LOT OF TIMES

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
