### ISSUE TITLE
Suggestion - Add a garage for Mount Chilliad Wilderness 7

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3388]
### Assurance

I have read the `README.md`

### Summary

Hey laura remember that really cool motel interior you put in up at the nudist camp? It doesn't have a garage, and basically every time I go inside my car poofs and then i have to walk to paleto. pls add garage prayge

### Reason

quality of life

**Comment by coalaura** [comment]
done
