### ISSUE TITLE
Suggestion - Change acid icon and buff sale price

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3389]
### Assurance

I have read the `README.md`

### Summary

Currently most people just throw acid on the ground or mix it into smoothies or whatever because the sell price is so low. Think it would be good to bump the prices up a bit to try and get it to be more actively done. 

Additionally, for some reason the icon is like pills but that ain't how acid works lol. it comes on sheets of paper like this that you put on your tongue

https://i.ibb.co/sQ31dyy/l4cvudwh-I0.png

### Reason

balancing i guess

**Comment by coalaura** [comment]
done
