### ISSUE TITLE
/glasses for female

### ISSUE THREAD

**Issue by Adorbz** [InZidiuZ/op-framework-issue-tracker#339]
**Name:**
Tag#4848

**Summary:**
Option for females to take off glasses

**Reason:**
When you do /glasses for female, they're not taken off. 
I suggest when someone does /glasses the script needs to find if the ped is male or female. Like
If [female] > use [glasses 5] 
I think the 4th or the 5th glasses is the no glasses for female.

**Comment by InZidiuZ** [comment]
Hey,

This was an issue which has since been resolved.

**InZidiuZ**
*OP-FW Developer*
