### ISSUE TITLE
Suggestion - Press tab to preview chat message history

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3390]
### Assurance

I have read the `README.md`

### Summary

Similar to how you can currently press tab to have your hot bar items pop up at the bottom of your screen make it so the chat up in the top right corner also appears for the same duration. Useful for cops or people that use /ped_messages to be able to see /me's, phone numbers, drivers licenses etc

### Reason

quality of life

**Comment by coalaura** [comment]
You can press T followed by escape for the same effect
