### ISSUE TITLE
Suggestion - Ways to earn a little Money in Prison

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3391]
### Assurance

I have read the `README.md`

### Summary

While a Character is in Prison as a Normal Inmate, HUT, or Life I think they should still be able to make money by doing certain things such as cleaning the floor and the stuff you find you can go and sell in the Prison for a little bit of Money or Going and Washing Clothes or Cooking Food all things that normally would be done in a Prison to let inmates Make a little bit of extra money.

### Reason

More Fun times in Prison

**Comment by MADxxVIKING** [comment]
In theory could be cool -- but I think it needs to be a very very low money maker if any (I'm talking $10-$20 every 3-5mins, as prison job notoriously pay pennys on the dollar). The money shouldn't matter, more so for waiting out your time for the RP with DOC, could be something like "breaking rocks".. like the old cartoons where they're mining away at big boulders etc. 

Could be an emote + action that pays very little.

**Comment by HollaYalla** [comment]
Yea thats what I mean plus like HUT or LIFE Prisoners some done wanna fly in as their criminal because they just do nothing so this gives them a grind

**Comment by coalaura** [comment]
I definitely agree that there needs to be more things to do in prison, however i don't think people in prison should be earning any significant amount of money, since that would defeat the point of the prison being a "punishment".

**Comment by coalaura** [comment]
An idea would be to add more tasks like you mentioned "Cleaning Dishes", "Cooking Food", etc. that will be chosen at random with the other regular tasks and upon completion result in a small payment of like $12-24.
