### ISSUE TITLE
New Activity! 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3392]
### Assurance

I have read the `README.md`

### Summary

Street Performer! 

### Reason

Description: Become a street artist or musician, entertaining pedestrians in popular areas.

Activities: Perform acts like playing instruments, singing, dancing, or doing magic tricks. Use creative emotes and props to enhance your performance.

Interactions: Engage with the audience, earn tips, and participate in talent shows or busking competitions. Handle interactions with police or city officials regarding permits.

For the interaction part maybe it can kinda be like guitar band or something c where random Letters pop up over random time intervals and you have to click within a few 
Seconds

to start this job you would go to any location and use any dance emote from the menu or /e 

Rewards for the event, mainly lower - medium amounts of cash, lost penny, lollipop, 

maybe some new items just from this! 

Also rewards can be bad,

Maybe the locals don’t like the performance!

**Comment by SluggsV2** [comment]
No job would be needed, anyone could run this as a side gig!

**Comment by coalaura** [comment]
You can already to this.........

**Comment by coalaura** [comment]
Just do a performance it in an area where there is people or announce it on twitter or let people know by word of mouth or distribute printed flyers, etc... And if people like the show they can tip you or you can ask for an entry fee. I don't think just standing in a location doing nothing or random emotes and getting paid by locals is a good idea, people gonna macro it and/or grind the ever living shit out of it

**Comment by SluggsV2** [comment]
Would be a random key/button everytime, would be no way to Macro it, also it would be like a drug sale, not everyone would work. After so many successful hits, the locals will no longer be interested and then you will have to pack up and move!

**Comment by coalaura** [comment]
It wouldn't be like a drug sale. Drugs require **WAY** more effort to get and to sell without being caught. This would literally be "press button to get money"

**Comment by SluggsV2** [comment]
I'm talking in terms of how locals act, 


But, maybe make a shop, for instruments and items along those lines (guitar, drums, flute, bass, could add the microphone here instead of the tech shop)
