### ISSUE TITLE
Suggestion - Additional Criminal Activity (ATMs)

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3394]
### Assurance

I have read the `README.md`

### Adding an additional criminal activity - Robbing ATMs

In this activity, you would use one of the following devices to initiate..

You would walk up to an ATM, using either a USB or Laptop device to temporarily disable the security system for 30 seconds with a complicated "hack". You could either buy a Laptop from the electronic store for $5,000 - $8,000 (make the buy in high) -- or find _one time use_ USB for $1500 - $2500 in Jim's selection of items to buy.

After hacking, you would then "use" either..

1). a Grinder (already in tool store)
OR
2). a Big Drill (whatever you'd like to name it so not confused with current drills). 

Once using either your drill or grinder, you begin working through the locks on the ATM through an interface (something similar to the hacks) before your initial "30 second hack disable" expires. The minimum to break into the ATM would be 45 seconds to actually drill through (allowing a risk regardless of how good you are at it for PD to be in the area and arrive), with a maximum timeframe of 1 minute before your drill or grinder breaks (they will **_always_** "break" or "be used" regardless of failure or success of the activity to make this an actual task/challenge opposed to an infinite use tool you can farm with). As far as the drilling interface, I believe this could be something like "tapping a specific key, or series of keys" idea. With roughly 4-6 tiers or "locks" to break through.

ATMs would also have "timers" but not need to be closed by PD. Timer would be per ATM, same rules with chain robbing ATMs as Banks, possibly a little lower (one an hour/two hours).

**Rewards:**

ATM rewards would not be massive. Thought is payout of $2000 - $4000. If you consider the tools you would have to purchase eating into the profit, you would be looking at $1000 - $1500 profit (ideally). 

### Reason

**Summary:** 

Small gig, small reward, but a new activity as a criminal to gather resources, hit something new that is challenging with a two tier "hack puzzle", and something PD could answer calls to. Obviously all timers and rewards are just numbers being tossed out for example -- however the ideal of a smaller end payout is ideal to deter people farming, but not also take away from J Store and Bank payouts as an ATM doesn't hold more money than those.

**Comment by coalaura** [comment]
#2584 and if the payout is relatively little nobody will do it or people will constantly grind ATM robberies

**Comment by coalaura** [comment]
#2485
