### ISSUE TITLE
Suggestion - Illegal cargo in trucking 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3395]
### Assurance

I have read the `README.md`

### Summary

An illegal form of trucking it would pay more than regular trucking and work similar to boosting. There could be a tablet or something for it. If police pull over any trucker they would be able to search the trailer to see if the trucker is transporting anything illegal like guns drugs etc. 

### Reason

More for both police and criminals

**Comment by coalaura** [comment]
Police would barely have a chance to catch people doing this tho, no? There is so many trucking spots across the map and they already pay decently well. The extra pay wouldn't be much higher

**Comment by baconnator1** [comment]
> Police would barely have a chance to catch people doing this tho, no? There is so many trucking spots across the map and they already pay decently well. The extra pay wouldn't be much higher

Instead of a pay raise there could be a chance for the trucker to get something better than what regular trucking give. And you do make a good point about it being hard to catch the I can't think of much of a work around for that.

**Comment by SluggsV2** [comment]
I think this idea could work, 

base it off the boosting tablet like stated, making it have their own spawn locations and drop off points, this would bring in a good use for spike strips as for pd side, and for rewards it could be either a new sort of currency, that can be spent to upgrade your hauler and buy different haulers, as well as a drop chance at legal and non legal items!

**Comment by coalaura** [comment]
Making it its own thing would most likely move it down on my todo list as i don't often get around to working on bigger features although i try my best. I quite like the idea of just having it in regular trucking and like suggested by @baconnator1 just have it give you different, maybe illegal rewards. Could then add a command or way for PD to check any trailers contents :)

**Comment by baconnator1** [comment]
> Making it its own thing would most likely move it down on my todo list as i don't often get around to working on bigger features although i try my best. I quite like the idea of just having it in regular trucking and like suggested by @baconnator1 just have it give you different, maybe illegal rewards. Could then add a command or way for PD to check any trailers contents :)

Yeah that's what I was thinking with a command and I think if police know truckers might have something illegal they will stop them more often

**Comment by coalaura** [comment]
I've added illegal cargo to trucking now. I've also slightly overhauled the UI.

![yes](https://i.shrt.day/AQKD3F00MJ.webp)
![yes](https://i.shrt.day/1DY5JPUW32.webp)
