### ISSUE TITLE
Suggestion - An option to chose between Cash or Bank while paying

### ISSUE THREAD

**Issue by Manannn924** [InZidiuZ/op-framework-issue-tracker#3396]
### Assurance

I have read the `README.md`

### Summary

While paying a bill or doing a transaction at vending machine , there should be a option for both cash or bank(if we have smartwatch).

### Reason

This will help in some better RP scenarios , in some situation the cash needs to be saved for later and is more convenient in some RP scenarios.

**Comment by coalaura** [comment]
No, the vending machines want cash
