### ISSUE TITLE
Suggestion - Meat not expiring so fast.

### ISSUE THREAD

**Issue by Goofierhi** [InZidiuZ/op-framework-issue-tracker#3397]
### Assurance

I have read the `README.md`

### Summary

The meat when cooked VERY quickly shoots down in durability to half health where it then slows down. This looks very bad for any businesses trying to sell things like BBQ sandwiches (Like myself.) All im asking is for the cooked meat not to expire so fast along with BBQ sandwiches.

### Reason

This would make it better for smaller businesses to open up and sell meat without worrying about people getting mad that your foods already half expired (Like they did with me) its a really big issue for small food companies.

**Comment by coalaura** [comment]
Its classified as "durable food", it has a degradation time of 4 whole days. I think for a cooked piece of meat thats a decent durability. Idm upping it to like 5 days but not more

**Comment by Goofierhi** [comment]
that’s not necessarily what i meant, it degrades down to half way instantly
then slows down to a halt, people were complanning i was selling half
duration BBQ sandwiches even though i had JUST made them.

**Comment by coalaura** [comment]
The durability does not change the "quality" of the food or how much it fills you up. All degradation also works the same way (its one system doing it all). All degradation is linear, meaning it will degrade at a constant rare, not speeding up or slowing down. Might just be people seeing things that aren't actually true (placebo). The extra day should help in keeping the durability high

**Comment by coalaura** [comment]
hmmm, thats weird. the way the degradation system is built this shouldn't happen. We just store a time at which the item will be fully degraded, which never changes

**Comment by Goofierhi** [comment]
i got a buddy to go hunting, and picked up the meat exactly as he was done
(meat was at 100%) and took it to mosleys where i began cooking and making
it into sandwiches, it was still at 100% i then put 4 in the Food truck
Trunk, someone ordered 1 so i gave it to him, i stored 5 more when he
returned claiming “it smelt funny” and gave it back, the durability was at
half, then i checked the rest of mine and they were all at half aswell.
that’s all i know, im not asking for it to be 5 days until it expires, 4 is
plenty, i just want it to stay close to full durability for the first few
hours.

**Comment by Goofierhi** [comment]
yea, but the problem is it’s durability being at half “in the morning” when
you first started eating. I can make it work if i really have to, but it’s
really hard to not get people trying to be shitters and going “oh i’m gonna
call food services on you!” and causing others to not want to buy. i was
just hoping i could get it to last a little bit, just a few hours at 80% or
higher.
