### ISSUE TITLE
Suggestion - LA Employee Roles

### ISSUE THREAD

**Issue by laalaalaee** [InZidiuZ/op-framework-issue-tracker#3398]
### Assurance

I have read the `README.md`

### Summary

On Behalf of Luxury Autos and I would like to help improve the roleplay of our employees by providing more progression within the business. I want to suggest the addition of an Assistant Manager role and Supervisor roles.

### Reason

Right now there are only 3 roles; Boss,  Manager (3 slot )& Employee. 
Whereas places like PDM and mechanic shops have a lot more roles allowing employees to progress in their career.
I would like to add an Assistant Manager (2 slot) and a Supervisor (3/3 slot) role to increase the roleplay of this showroom as we have people but they call themself as management and having a role give some staff members progression who deserve a promotion. thanks !

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/L9BWMS1O8G.webp)

**Comment by coalaura** [comment]
Yes! Can do, however i will lower the regular employees paychecks to allow for a pay increase in each position

**Comment by coalaura** [comment]
like so :)

![yes](https://i.shrt.day/KT9QX9SEKM.webp)

**Comment by coalaura** [comment]
Keep in mind, all players who currently have the "Employee" position will need to have a staff member give them the new job position of "Salesman"

**Comment by coalaura** [comment]
its alright, tunershop also has a Supervisor :)
