### ISSUE TITLE
Suggestion - Ability to smoke meth (with a meth pipe)

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3399]
### Assurance

I have read the `README.md`

### Summary

Add a meth pipe that when used in combination with 1 bag of meth in your inventory turns you into a methed out juggernaut for 30 seconds. During this time period you run extremely fast, double if not triple normal speed, and take no damage and can't be tasered. However, any damage dealt during that 30 seconds INSTANTLY gets applied when the timer runs out. Basically like real life where methheads will just take 30+ rounds of 9mm to their body and just keep going for a long time after.

### Reason

funny

**Comment by enutpeanut** [comment]
this would be insane, imagine during a shootout you just get one guy to smoke meth and sacrifice him to the gods
maybe just disable using weapons during this phase and it would be cool as hell

**Comment by scufflord** [comment]
disable guns, leave melee weapons and fists usable and just smoke some meth and go ham with a hatchet until the effects wear off LMFAO

**Comment by coalaura** [comment]
I think it'd be funny af to disable ALL weapons except fists, but make the player have very strong health regeneration xD

**Comment by coalaura** [comment]
You can now craft a meth pipe and use it to smoke meth.

![yes](https://i.shrt.day/S0S3MOVPV5.webp)
