### ISSUE TITLE
Suggestion - Add staffpm_area and staffpm_multi commands

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3401]
### Assurance

I have read the `README.md`

### Summary

Add command that can be used to send all users within a definable distance the same Staff PM. Additionally, if you need to warn multiple sides of a situation add a command that allows you to either send your last staffpm automatically to another user or a way to list out IDs for them to be sent to.

### Reason

quality of life

**Comment by coalaura** [comment]
I really don't think this is needed since we kinda have /looc for that...
