### ISSUE TITLE
Suggestion - Add another tunershop down at the docks

### ISSUE THREAD

**Issue by itzCali00** [InZidiuZ/op-framework-issue-tracker#3402]
### Assurance

I have read the `README.md`

### Summary

Title: Tuner MLO Scripted Street Racer

### Reason

Since its been added an mlo as mechanic with any script with it, theres any possibile to make a copy of the midnight tuner shop and implement with the new mlo to have 2 job to make competition?

**Comment by itzCali00** [comment]
> competition should be there

how? i mean in the server there's only one tuner shop. and they can also sell car

**Comment by coalaura** [comment]
No, tunershop already barely survives. PDM and EDM also don't have a second one
