### ISSUE TITLE
Suggestion - Blimp

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3403]
### Assurance

I have read the `README.md`

### Summary

With the Blimp being a base game vehicle I think we should add it to a brand new License just named **Blimp License** the only spawn point for it would be on top of Maze Bank Tower and would cost 500 to pull out mainly the low cost is because it blows up so easily

### Reason

Dinner in the Sky :)

**Comment by coalaura** [comment]
no, blimps are usually pretty scuffy. We got rid of them from even spawning locally a long long time ago
