### ISSUE TITLE
Suggestion - Spray Paint

### ISSUE THREAD

**Issue by Goofierhi** [InZidiuZ/op-framework-issue-tracker#3404]
### Assurance

I have read the `README.md`

### Summary

Im requesting that Spray paint cans be added. It can be added and work just like a boombox where you input a link of an image, and it places onto the wall like an item such as a table. And using "/mp" you could "wipe it off." I dont understand coding, but I dont think it would be too hard if the boombox coding and object pick up coding were used to help build off of it!

### Reason

This would be very useful for new and old gangs marking territory, or add for smaller encounters of vandilism and petty crimes for cops to go after! It would be a very cool addition to the city, and im sure many others would agree!

**Comment by coalaura** [comment]
There is already an issue for this here #2402 although i don't know if this is even possible to do in the first place

**Comment by Goofierhi** [comment]
oh, i apologize i didn’t see it! May i ask why not?

**Comment by coalaura** [comment]
> oh, i apologize i didn’t see it! May i ask why not?

Cause FiveM is a modification framework ONTOP of gta v, its not a separate game. We cant add/change core game features and not every feature is physically possible to be implemented

**Comment by Goofierhi** [comment]
their isn’t any way to implement it like a boombox?

**Comment by coalaura** [comment]
Playing music and drawing an image to a wall ingame are 2 very different things

**Comment by Goofierhi** [comment]
bad wording on my part, more like a TV. you can use a link to a TV and it
will put up either the video or the image. what if yall made it so it only
does images, and places down the Tv thing that goes over the TV. but it
places onto a wall instead of a Tv

**Comment by HollaYalla** [comment]
Even if this was possible the amount of props around the map would cause so much lag and he nearly unplayable especially with a good majority of the population across OPFW not having super pcs

**Comment by Goofierhi** [comment]
Ahh, yea that would make sense, i could see why that would be a problem
their
