### ISSUE TITLE
Suggestion - Addition of Album Paper

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3405]
### Assurance

I have read the `README.md`

### Summary

Add an Album Paper at the printer shop. It will contain 12 pages, 1 cover page, 10 normal pages, and 1 back cover page. The Printer and Album Paper will work as below.

![A1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/a025796b-bc43-4b16-9674-d02412951df9)

1. When you select the Album Paper in Printer, you will see a drop-down menu beside the link tab.
2. Pressing the drop-down button will expand the link pasting tab.

![A2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/883ffe8f-4565-4847-884b-2731c0cca4fa)

3. There will be total 12 tabs for link. First one is cover photo, next ten is normal pages, and last one is back cover.
4. Pressing the drop up button will shrink the tab.

![A3](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/8776a0e8-1246-42a0-8df7-a7390c2aac30)

5. You will see 12 photo preview at the bottom. If you don't paste a link in one tab, it will be blank/white page.
6. Typing an album name and printing it will give you a custom album.

The album will open similarly to the Weazel News Magazine. I would suggest not to add any border around the pages. So, if someone wants to use two pages for a landscape photo, it will look good.

### Reason

An album can serve a wide range of purpose. You can use it as a photo album, documents, manual, guide book, comic, limited edition magazine, and many more.

The possibilities with the album are limitless. It will open a massive amount of roleplay content.

It will create a way to open publications and various other sectors or business. This addition has a great potential that can benefit a wide range of people.

**Comment by coalaura** [comment]
I feel like this is incredibly clunky and weird to use. Don't think it is a good idea

**Comment by coalaura** [comment]
However this could help

![yes](https://i.shrt.day/0OZXB0XR9U.webp)
