### ISSUE TITLE
Suggestion - Add an option for PD oil changes

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3406]
### Assurance

I have read the `README.md`

### Summary

Currently if there's no mechanic shops open and we're needing oil changes on vehicles we're just kinda screwed over and have to swap cars. Sometimes - at lower ranks especially - this puts us at a direct disadvantage. So I was wondering if it was possible that one of two things happen:

option 1: add a command that checks to see if any mechanic shops are open based off the same way the phones detect it, and if there are none then /repair will also do an oil change

option 2: add oil to the pd store and let us do our own oil changes if needed.

### Reason

Quality of life

**Comment by coalaura** [comment]
but it takes so long before you need one, i feel like if you just pay attention to it you have quite a lot of time before it actually goes bad, plenty of time for there to be a mechanic around

**Comment by scufflord** [comment]
i mean as soon as it goes yellow it starts effecting the vehicle so at that point the vehicle basically becomes useless for patrol.

**Comment by coalaura** [comment]
It turns yellow under 12%, orange under 8% and red under 5%. It only starts affecting the vehicle if its at 0%

**Comment by coalaura** [comment]
i feel like there is plenty of time to go get it changed before it gets bad. I've added a command that allows you to check the oil level precisely.

![yes](https://i.shrt.day/NT707WMMA8.webp)  
![yes](https://i.shrt.day/MTJKTDV7NB.webp)
