### ISSUE TITLE
Suggestion - New Ideas for Album Paper

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3407]
### Assurance

I have read the `README.md`

### Summary

I agree with what you said in #3405. Printing album with Printer looks weird and not the best suitable.

An album should work like an album, right? Therefore, I've reworked the ideas and it requires no Printer. It's much straightforward to understand and hope you will like it.

![Album1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/8800a740-769f-40b9-af82-19ce635d4276)

1. After purchasing the Album item, you will see an **Edit Album** option when dragging. (first picture)

![Album2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/54036e5f-182d-48c1-86b4-1e18b47569b9)

2. Editing the Album item will give you an interface like above. It will have _link paste and add_ option in each page. Adding the image will fill the page, and keeping it blank will stay white. (second picture)
3. You can add your cool album name and _Finish_ it.

The finished Album item can't be edited again. But if you wish to make it work just like an album and re-use it, you can keep the method.

The album will open similarly to the Weazel News Magazine. I would suggest not to add any border around the pages. So, if someone wants to use two pages for a landscape photo, it will look good.

### Reason

An album can serve a wide range of purpose. You can use it as a photo album, documents, manual, guide book, comic, limited edition magazine, and many more.

The possibilities with the album are limitless. It will open a massive amount of roleplay content.

It will create a way to open publications and various other sectors or business. This addition has a great potential that can benefit a wide range of people.

**Comment by Faisalhasan7** [comment]
Me making limited edition magazine with this for sure

**Comment by coalaura** [comment]
i already added folders for this basically
