### ISSUE TITLE
Suggestion - Add /clockout command for mechanics

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3408]
### Assurance

I have read the `README.md`

### Summary

Having a repeat issue that mechanics will not be working but will stop by a mechanic shop to drop off materials or do their own personal repair, and then the shop opens up on the phone and it confuses everyone. So maybe add a command to actually disable that feature on a per person basis for the current session so if people don't want a shop to appear open they can toggle it.

### Reason

quality of life

**Comment by coalaura** [comment]
Then you'd need another clockin command
