### ISSUE TITLE
Doing Ctrl M for /radar menu wont come up

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#341]
**Reporter:**
Randy James#4851
**Summary:**
I do /Radar and it works brings up the radar then doing Ctrl M and nothing comes up. I have tryed changing binds 

**Game Resolution:**
1920 x 1080
**Player Data:**
4232 Law Enforcement, Trooper

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. I also added front and rear lock vehicle plates to allow for more easy identification of vehicles.

**InZidiuZ**
*OP-FW Developer*
