### ISSUE TITLE
Suggestion - /Dispatch while in a car or on training tracker

### ISSUE THREAD

**Issue by scufflord** [InZidiuZ/op-framework-issue-tracker#3410]
### Assurance

I have read the `README.md`

### Summary

Dispatch is used a lot to announce when people go on duty or are doing a traffic stop if there's active comms going on, or for cadets to ask for a FTO. Makes it annoying having to get out of a car in order to use it since it's roleplayed out as just being a radio comm but in text format.

### Reason

quality of life

**Comment by coalaura** [comment]
you can now use it in vehicles, training tracker no tho

**Comment by scufflord** [comment]
> you can now use it in vehicles, training tracker no tho

why not on training tracker? if a cadet goes on duty they have to sit on training tracker until a fto is available, and if pd numbers are low they risk the possibility of a bank or j store possibly popping off in that time frame that a cadet has to type out a message and then go back on training tracker

**Comment by coalaura** [comment]
cause they can go on radio 1 and just ask, if there is a lot going on there wont be an fto available anyways, if there is not a lot going on a quick "any fto available" works
