### ISSUE TITLE
Suggestion - Group Chat on Phone

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3411]
### Assurance

I have read the `README.md`

### Summary

We use messages a lot for chatting , sharing locations etc. 
Chatting with frends in group can be great things.

doing mining or huting? share your location to your group of friends easilly in group chat.

### Reason

It can be great thing for rp players to have group chat. its fun

**Comment by coalaura** [comment]
This is currently not possible to implement with our phone. However as an alternative you are already able to use darkchat which is basically a group chat if you just share the room name with your friends.

#2447

**Comment by ayushpatel1007** [comment]
Yes we do have darkchat but it is least used. phone is much easier andd used in daily basics. hope we will have group chat on phone soon
