### ISSUE TITLE
Suggestion - Fudge Lane 1 & 2 Garages

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3412]
### Assurance

I have read the `README.md`

### Summary

I was wondering if its possible to move the location of the garages for Fudge Lane 1 and Fudge Lane 2 closer to the houses, currently the garages for those houses are all the way down and away from the actual propery 

Current Garage Location
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/7c112ca3-66f8-49e1-9888-3d2de6865bfb) 

Fudge Lane 1
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/4f188b96-c7c6-4931-a814-5ecb6f654f6d)

Fudge Lane 2
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/87e37980-8874-420b-b777-e314897a264f)

### Reason

This would be extremly helpful and would improve the quality of life for the people who purchase those properties.

**Comment by coalaura** [comment]
where, there is no spot

**Comment by coalaura** [comment]
Those garages belong to the property, i think the garage location is fine

**Comment by gadjinee** [comment]
Well it's not really fine, since that's why we asking to see if they can be moved. 

All the other houses at that block have the garages at the exit of the houses. So the vehicle spawn on the road, that's pretty much what we looking instead of going all the way down. 

Both houses Fudge 1 and 2 can have garage with vehicle spawn on the road, and the garage marker next to stairs

**Comment by gadjinee** [comment]
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/6acbd981-58c1-4ec5-a6f4-dcf04b202ebf)

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/06ac5e3b-50a2-4bd5-bab7-f769c9690260)

Just an idea of what I meant with garage on the road, same as the other ones on that street without driveway
