### ISSUE TITLE
Suggestion - Auto Pay Rent (House)

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3413]
### Assurance

I have read the `README.md`

### Summary

So currently real estate have setup where a person forget to pay rent and his rent is over. We have this security week where owner have access of house for 1 more week and if they pay rent in that week. everything is good. But if they still dont pay rent then after that week , they will still have access as company owner has to manually evict the house owner to revok his access.

I dont know why but there are lots of people complaining that company should remind them to pay rent or they say alteast inform owners that their rent is over and house will get evicted.

I think that it is not companies job to remind them even aftter they are getting extra week after their rent get overdue. 

most of time they say we were out of town , or we forget or we were banned etc etc.

what if we have option to pay rent automatically which can be toggled ON and OFF by their own preferences. So whenever they want they can toggle this auto pay button and their house rent will be paid automatically from their /companies account

We as company also have already autopay for block maintance then why not the house owners.

or we can have always onn autopay rent and when a person what to leave that house , they can have option to " Leave the house" then the autopay rent will stop and their house will be evicted by company once rent is fully over

### Reason

The is big problem which is observed by players themself. I think this can help both company and tenants in many cases where they lost their house and their stuff inside as they forget to pay rent or were unable to pay rent due to some reasons.

**Comment by gadjinee** [comment]
There's already a lot of people who barely play the server or just join the server to pay rent and gate keep the houses, this pretty much will stop people from coming around just to pay their rent as they can just set it all automatic 

Gate keeping on properties is already becoming an issue, there's barely any blocks to sell, barely any houses. 

It theory this is a cool idea but in practice this will just benefit non active gate keepers

**Comment by ayushpatel1007** [comment]
> There's already a lot of people who barely play the server or just join the server to pay rent and gate keep the houses, this pretty much will stop people from coming around just to pay their rent as they can just set it all automatic
> 
> Gate keeping on properties is already becoming an issue, there's barely any blocks to sell, barely any houses.
> 
> It theory this is a cool idea but in practice this will just benefit non active gate keepers

I dont know in what server u r playing but trust me in legacy india where i am playing, we have tons of tons of house to sell

Also if you are saying about gate keeping on properties, and they just come pay rent, they cant be rich to pay rent forever without earning anything or not coming in server except to pay rent.

**Comment by xplrerin** [comment]
Doesn’t work for international, the economy means they do have enough money to pay rent forever unfortunately. Might work for other subdivisions but international it won’t. People can already pay their rent off so why don’t you advise people to pay it off monthly? Thats what most people do.

**Comment by ayushpatel1007** [comment]
> Doesn’t work for international, the economy means they do have enough money to pay rent forever unfortunately. Might work for other subdivisions but international it won’t. People can already pay their rent off so why don’t you advise people to pay it off monthly? Thats what most people do.

maybe that is case in international server. not here

**Comment by scufflord** [comment]
> > Doesn’t work for international, the economy means they do have enough money to pay rent forever unfortunately. Might work for other subdivisions but international it won’t. People can already pay their rent off so why don’t you advise people to pay it off monthly? Thats what most people do.
> 
> maybe that is case in international server. not here

right, and OP-FW is a FRAMEWORK that is used on a multitude of servers, thus any changes on THIS github would also change for EVERY SINGLE ONE of those servers

**Comment by ayushpatel1007** [comment]
> > > Doesn’t work for international, the economy means they do have enough money to pay rent forever unfortunately. Might work for other subdivisions but international it won’t. People can already pay their rent off so why don’t you advise people to pay it off monthly? Thats what most people do.
> > 
> > 
> > maybe that is case in international server. not here
> 
> right, and OP-FW is a FRAMEWORK that is used on a multitude of servers, thus any changes on THIS github would also change for EVERY SINGLE ONE of those servers

i am not technical guy so i didnt knew that. but still having autopay option with toggle on and off can be great thing to have

**Comment by coalaura** [comment]
I think its on you to remember to pay rent for your houses. This allows houses owned by people who don't fly in a lot to drop eventually rather than being auto-paid forever
