### ISSUE TITLE
Suggestion - Yellowjack & Vineyard Alcohol "Store/Spawner"

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3414]
### Assurance

I have read the `README.md`

### Summary

Both Yellowjack, and Vineyards are actively sold "bars" by the State. 
Neither have access for bartenders to purchase drinks, essentially just making them buildings to be owned, and having to purchase alcohol from different areas. 

For Roleplay sake, I believe both should have the correct spawners added to the bar area for proper RP to be functioning businesses. 

### Reason

QOL update for these businesses which do not have available to them the same "store/spawner" they can purchase drinks from as other bars can - Overall a hindrance to RP

**Comment by coalaura** [comment]
The Vineyard is not a bar, however i've added a bar item store to yellowjack

**Comment by MADxxVIKING** [comment]
Thank you @coalaura!! Appreciate all the work you do
