### ISSUE TITLE
Suggestion - Nicotine addiction 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3415]
### Assurance

I have read the `README.md`

### Summary

Our character get addicted to nicotine the more they use it. For example if you use a vape or smoke a cigarette you get addicted and if you go so long without nicotine your screen begins to shake and you get other withdrawal symptoms. 

### Reason

More realistic RP when it comes to nicotine products.

**Comment by HollaYalla** [comment]
So pretty much make people dependent on GW to live got it

**Comment by coalaura** [comment]
the overwhelming majority does not seem to like this idea and i too think it could get very annoying very quick

![yes](https://i.shrt.day/BE2RRV0F98.webp)
