### ISSUE TITLE
Suggestion - chetgpt phone ap

### ISSUE THREAD

**Issue by bananajoe4000** [InZidiuZ/op-framework-issue-tracker#3416]
### Assurance

I have read the `README.md`

### Summary

should have chetgpt pone app call like choper or somethin so wen i forget 2 rp i can ask chetgpt how 2 rp and wut to say n stuf

### Reason

scefflard said it good ide

**Comment by scufflord** [comment]
great idea from bananajoe. 11/10 must be implemented immediately

**Comment by coalaura** [comment]
lmaoo
