### ISSUE TITLE
Suggestion - Midnight Tunershop garage

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3417]
### Assurance

I have read the `README.md`

### Summary

Employee Garage Inside the shop, i believe the garage bay beside the office would work awesome! or even behind the work shop where you refill nos! More Clothing!

### Reason

Garage will be a nice addition for employees so when we have tons of employees we are crowing the sales floor and or banging into eachother.

**Comment by coalaura** [comment]
done
