### ISSUE TITLE
DMV or addition to courthouse

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3419]
### Assurance

I have read the `README.md`

### Summary

Licnece Plate Checks, Casino & EDM Car Tracker

### Reason

License Plate Checks - Allows locals to check if a plate is taken and or search a plate if they know the exact plate,

Casino & EDM Car Tracker - This would be a board similar to the dailies activity board and show a catalog like PDMs, It would simply have 2 tabs Casino & EDM this would show all the cars available and how many in city! You could also expand the current EDM Catalog to include this feature! 

Would be cool to add in custom license plates through state as well, in game currency maybe 25k or something

**Comment by coalaura** [comment]
> License Plate Checks - Allows locals to check if a plate is taken and or search a plate if they know the exact plate

What do you mean by this? Locals are NPCs, if you mean players you can already do /plate_available to see if a plate is taken

> Casino & EDM Car Tracker - This would be a board similar to the dailies activity board and show a catalog like PDMs, It would simply have 2 tabs Casino & EDM this would show all the cars available and how many in city! You could also expand the current EDM Catalog to include this feature!

The EDM catalog already has a page for special imports
![yes](https://i.shrt.day/0WK67Y7B85.webp)
