### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Cyberjunk1e** [InZidiuZ/op-framework-issue-tracker#342]
**Name:**
Who is suggesting this? Please include discord name.
Cyberjunk1e
**Summary:**
Write a short summary of what your suggestion is about.
Taser/Pistol on the hotbar
**Reason:**
Why would your suggestion be a good addition to Legacy?
one reason PD members switch to the SMG as quickly as they do, is because of the time it takes to stop, tab, switch to pistol, tab, take out weapon. Its simply not efficient. I suggest moving the Taser to the Melee category for PD. or make taser its own category.

**Comment by stormin88** [comment]
I agree with this

**Comment by InZidiuZ** [comment]
Hey,

The taser is now recognized as "Others" by the action bar, but won't put it into melee as it isn't classified as that.

**InZidiuZ**
*OP-FW Developer*
