### ISSUE TITLE
Suggestion - Leave the House Button 

### ISSUE THREAD

**Issue by ayushpatel1007** [InZidiuZ/op-framework-issue-tracker#3421]
### Assurance

I have read the `README.md`

### Summary

Want to leave the house you are staying in? 
Click on "Leave" and you are done.

So this is nothing but a button than will inform company owner than this person will leave the house once the rent is over. Obiouslly they will able to pay rent even after using that button. If they pay rent after using "Leave" button than company owner will not see the leave button.

Company Owner will see that house in maybe "Yellow" or "Blue" that will indicate it that owner want to leave. Not red because we have that for evict. or maybe we can see "Leave" aside of house name.

### Reason

many times people forget to pay rent and company owners things that they want to leave. This will help understnad owner that owner actually want to leave the house and doesnt want to stay there anymore.

Also if rent is over and they didnt used leave button then company owner will know that they forget to pay rent and they can wait and remind the owner

**Comment by coalaura** [comment]
just talk to people, there is no need for a button. If you want to not have your house anymore you simply talk to your realtor

**Comment by ayushpatel1007** [comment]
> just talk to people, there is no need for a button. If you want to not have your house anymore you simply talk to your realtor

i myself am owner of real estate company and people dont contact company to leave house because they dont need to. Which is making things hard for company. As we have rule in our server to inform house owners before evicting them @coalaura
