### ISSUE TITLE
Suggestion - Adjusting the Gun Comp + Removing or lowering shotgun drops

### ISSUE THREAD

**Issue by tiigerrlily** [InZidiuZ/op-framework-issue-tracker#3424]
### Assurance

I have read the `README.md`

### Summary

So, I don't run the gun comp, but have had multiple instances as a GM, and as a crim, of being told that Shotguns have a high drop rate vs AR's and SMGs in the gun comp.
In turn this means shipments from the gun computer take an extreme amount of time, delaying RP.

I think Shotguns should be lowered, if not removed from the Gun Computer.

### Reason

There isn't a market for people who want shotguns, unless it's bikers or newer players. 

The issue I'm seeing a lot of is people will run the gun computer and get like 6 x shotguns, 4 x SMG's and 1 x AR. Which, while that's fine maybe every **few** runs, it shouldn't be every single one. This means 1 single shipment of 200k = 20 AR's will take upwards of 20 runs, just to get viable and decent guns. That's so much time spent running that the people who actually use the gun computer don't really get to RP much.

With Chop now having a better drop rate for shotguns after shotguns were removed from dailies, and people having backlogged orders with the gun comp being run over and over and people only getting **mostly** shotguns over SMG's and ARs.

An idea could be implenting shotgun crafting as an alternative but removing them from the gun comp entirely and increasing the rates of the other two guns could mean that people are actually getting their time + money's worth of effort.

**Comment by coalaura** [comment]
we did it at the same time :DD if the new balancing is still too likely to drop let me know
