### ISSUE TITLE
Suggestion - Bagging Station, Bar Store Changes, Counters, Employee Garage

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3425]
### Assurance

I have read the `README.md`

### Summary

With the recent changes to Kissaki there is a few more that has came up in conversations that would be good

Moving the Bagging Station to the Espresso Machine here

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/bd0d1f6f-9d57-415c-97a6-116733bdea3b)

Aswell as adding the Counters like the Arcade and Most Bars have at the circles in the picture below

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/aab5c0c3-ddd9-48e0-abcd-def949063e17)

Move the Bar Store here so the counters work better

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/008ef4bc-2d43-4d97-b1a5-819372855cbf)

Aswell as adding Alcohol mainly Wines, Tequilas, and beer as it is in the building as a prop and would be nice to have mainly since Kissaki is good for events and stuff and its meant to be a dine in restaurant and those usually have a few types of alcohol to serve 

Potentially adding a new Beer type that is the same as normal beer but uses the prop that is on the counter as it is a Japanese Beer the prop name is "prop_beer_am"

A Employee Garage maybe here

White item is where the marker thing is

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/e874792a-f5a8-4d59-b3d0-a00ce6abb578)

### Reason

More things for Kissaki

**Comment by coalaura** [comment]
pls no edit, rather comment cause it gets confusing

**Comment by HollaYalla** [comment]
Ok the only thing I added was the Employee Garage part in the future ill just add a comment

**Comment by coalaura** [comment]
Its easier to see an added comment than someone edit the original issue, i almost closed it being done with it before i noticed

**Comment by coalaura** [comment]
Put the garage at the back where there is an actual garage door

![yes](https://i.shrt.day/B4XJ694LX5.webp)
