### ISSUE TITLE
Suggestion - Bank Cards

### ISSUE THREAD

**Issue by gadjinee** [InZidiuZ/op-framework-issue-tracker#3426]
### Assurance

I have read the `README.md`

### Summary

So we already have an animation when using the ATM of inserting a Bank card and irl we do need to have a bank card when using any ATM's, why dont we get one in server. Essentually in the same way as you can pay /bill only if you have your watch on you this way you could only use any ATM if you have your physical card on you. Card can also be customisable or maybe some unique ones 

i have attached some examples 

![fleecabank](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/e1c0461b-6df8-4882-839a-6eb862f55f96)
![mazebank](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/124582929/8dc2901f-69c1-4b82-aa87-a5c03172b5a3)

### Reason

I gues its just more realistic way to use the ATM's

**Comment by coalaura** [comment]
why tho, whats the point? This would just make everything way more annoying to use and you'd have to carry another item with you at all times

**Comment by gadjinee** [comment]
but its the same as all other licenses and stuff, thats why we have the wallet

**Comment by coalaura** [comment]
Licenses give you access to spawners, this would reduce peoples freedom forcing them to have it on them at all times. Also, we have a smartwatch, don't see the point of having a bank card if all it does is restrict when you can use an atm. Also what if its stolen from you, are they then able to access your money with the card? This would be a cool idea if we didn't have the smartwatch already
