### ISSUE TITLE
Suggestion - Rest API - Add additional fields to the "character_vehicles" endpoint 

### ISSUE THREAD

**Issue by CloudTheWolf** [InZidiuZ/op-framework-issue-tracker#3428]
### Assurance

I have read the `README.md`

### Summary

The `character_vehicles` endpoint is missing some useful/key information that makes it hard to use.

|Field Name|Type|Justification |
|------------|------|--------------|
| vin_scratched | Bool | Currently there is no way to identify and filter out VIN Scratched vehicles which causes ownership confliction between this and the `/check_plate` command`  |
| financed | Bool | A flag to show the vehicle is financed (Set to false when fully paid) |
| finance_ next_due_date | Timestamp | Timestamp of next due date |

### Reason

Using the `character_vehicles` endpoint there is currently no way to exclude Illegally obtained vehicles and identify is a vehicle has been "Repossessed"

**Comment by coalaura** [comment]
The rest API is not officially a part of the op-framework so suggestions for it you can just come to my DMs instead. I've added the `was_boosted` flag to the character_vehicles endpoint. I've also added a new endpoint for active vehicle finances.
