### ISSUE TITLE
Suggestion - Addition of New Twitter Verification Badge

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3429]
### Assurance

I have read the `README.md`

### Summary

Introduce two new verification badges for Twitter, **Grey** and **Golden**.

**1.** The Grey checkmark represents the Government and people associated with the Government.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/300ea1e5-d2fb-499e-b8fc-101974c4ae9f)

**2.** The Golden checkmark is used by a verified business or organization.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/ef0bec4a-87d9-4812-be86-70f826448739)

The Grey Badge can represent the account of the State, DOJ, Mayor, Deputy Mayor and other people in the management.

Similarly, the Golden Badge can represent verified business like PDM, Tuner, BurgerShot, Repair Shop, etc.

### Verification Method

The verification will be done from the Sub-division side using the Admin panel. As far as I know, there's already a process of adding Blue checkmark. The Grey and Golden badge will be added in the same process.

### Reason

The Grey badge will help users identify official government entities and officials, ensuring that information coming from these accounts is credible and authentic. It will work as official sources of information, enhancing trust in public information and various events.

The Golden badge will help users identify official accounts of companies and business entities. It will build trust and recognition by confirming that the account is genuinely associated with the business.

The overall addition will improve credibility, and authenticity, tackling misinformation, impersonations, or unofficial sources in the Role-play scenario, creating a more enhanced Twitter experience.

**Comment by coalaura** [comment]
already exists
