### ISSUE TITLE
Can't customize livery on Nissan Titan.

### ISSUE THREAD

**Issue by TheRealRoty** [InZidiuZ/op-framework-issue-tracker#343]
**Reporter:**
Roty#8992 
https://steamcommunity.com/id/TheRealRoty/

People should get an option to customize the livery on the truck, maybe at Los Santos Customs or using the /livery command.

Like I got stuck with the truck with a Monster Logo on it. I'd like to have the camo print on it.
The only way as off now to do it is to go to the Exclusive Dealership and just toggle in and out until it gives you the truck with the livery you desire to have, and then buy it.

**Player Data:**

351 - Job Data : Mechanic, Los Santos Customs, Tow Driver.
Timestamp : 2019-08-05 10:25:05

**Screenshot:**

https://i.imgur.com/A4J6C6G.png

**Comment by InZidiuZ** [comment]
Hey,

It's not a bug, create a suggestion about adding livery changing to ls customs. ;)

**InZidiuZ**
*OP-FW Developer*
