### ISSUE TITLE
Suggestion - Pizza This Script

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3430]
### Assurance

I have read the `README.md`

### Summary

Pizza this has been in the server as a MLO for a while now and I think its about time to make it functional and its own restaurant so we can have it player owned and this is what it would need.

Its Own Job (Same Pay Grade as BS and Kissaki)

A Store with some new items
* Dough
* Shredded Cheese
* Pepperonis
* Pizza Sauce
* Coke
* Pepsi

Store Location
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/b48e159b-3bdf-4e84-a374-dd358cb7f00f)

Roll the Dough out into Either Bread Dough or Pizza Dough
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/38e49d81-d505-4a29-aae0-aa4f01118993)

Cook the Bread Dough into Bread Sticks or Cook the Pizza Dough with the following ingredients to make pizza
1x Pizza Dough
1x Pizza Sauce
2x Shredded Cheese
4x Pepperonis
= 8x Pepperoni Pizza Slices

1x Pizza Dough
1x Pizza Sauce
2x Shredded Cheese
= 8x Cheese Pizza Slices

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/c2577f9a-35ba-4a52-b8fd-ce65dd866101)

Add a Counter Here
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/34a16a74-1a80-4930-9b59-03033da25662)

Employee Garage Here
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/a1416383-8625-4422-9595-452173dafba7)

Add Door locks to all the Doors

Employee Locker Here
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/d370f042-228a-4879-bf91-946fc68cbd01)

Changing Spot Here
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/fb2bcfdc-5613-4162-b90f-50f3c1e608c4)

Instead of a Bagging Area make a Pizza Boxing Area where you get the Pizza boxes from the store and then box them here and it functions just like a bag just the Icon and name is a box
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/1ad0f64d-dd5c-40d8-ad81-15fd1fc125e0)

### Reason

Make Pizza This functional

**Comment by HollaYalla** [comment]
Can you also add the Blip

here is a good one

Sprite: 267
Color: 25
Coords: vector4(91.42, -229.57, 58.98, 160.11)

**Comment by coalaura** [comment]
this is all already done, did you not see the github commits and stuff????????

**Comment by coalaura** [comment]
its already live even

**Comment by HollaYalla** [comment]
There aint a Blip for it

**Comment by coalaura** [comment]
yeah but ur issue is for the whole thing
