### ISSUE TITLE
Suggestion - Keys for Law School

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3433]
### Assurance

I have read the `README.md`

### Summary

The school at the university [not the haunted high school, the one across from it] should have locks similar to the court house that is locked to DOJ / State

### Reason

This building gets abused for shootouts and drug sales way too often and should be lockable for use for law school and other community activities

**Comment by antihero6713** [comment]
I am working on making that be less desired location for it.

**Comment by coalaura** [comment]
idk about locks, like anti said he did a bunch of shootout related changes to discourage it from being used for that. I think leaving it open could open the doors for more RP than locking it

**Comment by Kay32** [comment]
EMS also have been using the building for trainings and lessons

**Comment by antihero6713** [comment]
the changes have been pushed. We will see how it goes
