### ISSUE TITLE
Suggestion - Adding Job For Boat Association

### ISSUE THREAD

**Issue by Manannn924** [InZidiuZ/op-framework-issue-tracker#3434]
### Assurance

I have read the `README.md`

### Summary

In our Subdivision there's a RP going on by people who have started a company 'Boat Association' which provides Boat licenses . The company's motive as similar as Aviation . It would be helpful if we have in-game roles for the same , so we can continue our RP smoothly.

The Roles Can be :
1. Owner
2. Co-Owner/Manager
3. Instructor

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/122094350/38e1c329-b394-4028-9f47-dfc84d96f410)

### Reason

To enhance RP situations as a company and something new for providing boat licenses.

**Comment by antihero6713** [comment]
If you are patient I have a place called SeaDM that is to be a place to sell boats its a WIP though

**Comment by coalaura** [comment]
Eventually there will be a boat sale spot like antihero mentioned, however eventhough you opened 2 tickets and one issue on github, the answer for now is no, this job is not needed
