### ISSUE TITLE
Suggestion - Shredder at Del Perro Pier PD.

### ISSUE THREAD

**Issue by Nozimmm** [InZidiuZ/op-framework-issue-tracker#3435]
### Assurance

I have read the `README.md`

### Summary

To add a shredder at Del Perro Pier PD beside the Evidence Locker in the room inside.

### Reason

Its pretty annoying to carry illegal items all the way to another PD to shred them after processing a suspect.

**Comment by HollaYalla** [comment]
#3289 there is a shredder at Del Perro Pier PD
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/72ff6539-9b24-43a1-bef3-6331f966fb5d)

**Comment by Nozimmm** [comment]
ooh im dumb then xD
