### ISSUE TITLE
Suggestion - Hayes Female Shirts

### ISSUE THREAD

**Issue by SooDurty** [InZidiuZ/op-framework-issue-tracker#3437]
### Assurance

I have read the `README.md`

### Summary

We are looking to get a couple new shirts for the ladies at Hayes. Attached are a couple examples/ideas. 
![hayesshirt](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/c54c23e3-27bf-4dda-9cc6-2ec2f96b9c68)
![hayesshirt2](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/be733128-70e6-4b11-a757-8c999d31fb00)

### Reason

A bunch of the female mechanics have reached out to management regarding new shirts. The one shirt they currently have is a cropped undershirt that has a knot tied in the front. Attached are some of the feedback I've gotten from the ladies on the Hayes team. 
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/bf7532e7-3804-4f71-a2f9-c346125b4f8f)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/76dc51ec-ac1c-4260-93df-ae99b87aa4e8)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/3788316e-08a4-4b10-a328-4ba3f4346c85)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/ab131e8a-a11f-4ac4-aeb5-afc029bbb619)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/164375395/b939de59-4e89-4003-aab6-094a62fc90b8)

**Comment by Alyshiva** [comment]
Absolutely agree, we need some new styles especially coming into summer since the crop top is both scuffed and too feminine for some employees, and the only other options are long sleeved sweaters/coats. It would also be nice to have another kind of sweater for those looking for some variety in the colder months.

**Comment by emeraldenraged** [comment]
I 100% agree that we need new clothing for women. I don't like being reduced to either fully covering up in a sweater and being hot, or having to wear some sort of "crop" top. I think it would definitely benefit not only current employees, but future employees looking for something more casual of a mech shop, without losing the comfortability of something like a jersey or tshirt. The hoodie is nice but summer time calls for something cooler. Additionally, I don't think it would hurt for us to have a sweater/hoodie that is different than what men have.

**Comment by DaxterPancake** [comment]
Sure, I can work on that fairly easily. You've provided a few photos but specifics are actually better for me, so if you have photos of the actual clothing you'd like a texture for I can look into it easier. The crop top is very very very old added back when I was't even a dev so it's super outdated. I am team tom boy energy so I feel that pain.

**Comment by DaxterPancake** [comment]
Though I do hate to be that person, this is the wrong github. Please remake this issue + the photos of specifics to [THIS](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) github.

**Comment by SooDurty** [comment]
@DaxterPancake Sorry for the mix up. Thanks for pointing me in the right direction.

**Comment by Alyshiva** [comment]
Absolutely agree, we need some new styles especially coming into summer since the crop top is both scuffed and too feminine for some employees, and the only other options are long sleeved sweaters/coats. It would also be nice to have another kind of sweater for those looking for some variety in the colder months.
