### ISSUE TITLE
Suggestion - More Kissaki Additions

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3439]
### Assurance

I have read the `README.md`

### Summary

With Kissaki now being owned on the International server I think its ok to ask for these now

1. A Hotline
The Addition of a Kissaki hotline would be good for it being open and stuff and heres an icon that can be used aswell
![Untidwtled](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/b41d65ce-efec-4968-ad56-e8d92983ee73)

2. Deliveries
With Kissaki being new it will get a lot of traction but it is also a food place and it will probably die after about a month and it would be a good way to make some extra money for our employees in the dead hours

### Reason

Make Kissaki Good

**Comment by coalaura** [comment]
deliveries no, hotline i've just done
