### ISSUE TITLE
Suggestion - Regarding Hayes 

### ISSUE THREAD

**Issue by 07ashishdas** [InZidiuZ/op-framework-issue-tracker#3440]
### Assurance

I have read the `README.md`

### Summary

Make a repair Point Backside the Hayes Even there any car repair Easily 
![1](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/133572519/13364a15-2439-4e08-b5e8-c4e7011e0ad8)

[Updated _Point](https://i.ibb.co/Q8Pptbz/Discord-ZBIKYo-U8v-A.png

### Reason

It seems like you're expressing difficulty with accessing Hayes due to size constraints, particularly with our tow truck and Big truck Not Repair Inside the Hayes. It's challenging to enter Hayes because of these size limitations, which doesn't seem logical.

**Comment by gadjinee** [comment]
Big trucks can fit through the main doors, they were altered some time ago. any car can fit through

**Comment by 07ashishdas** [comment]
> Big trucks can fit through the main doors, they were altered some time ago. any car can fit through

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/133572519/b918f59c-5f6c-4056-927c-58c836e7d45a)
 What about this truck

**Comment by gadjinee** [comment]
yeah, anything will fit throught the main doors

**Comment by Alyshiva** [comment]
> > Big trucks can fit through the main doors, they were altered some time ago. any car can fit through
> 
> ![image](https://private-user-images.githubusercontent.com/133572519/342059192-b918f59c-5f6c-4056-927c-58c836e7d45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDA1MjQsIm5iZiI6MTcxOTE0MDIyNCwicGF0aCI6Ii8xMzM1NzI1MTkvMzQyMDU5MTkyLWI5MThmNTljLTVmNmMtNDA1Ni05MjdjLTU4YzgzNmU3ZDQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxMDU3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2EwMzNjY2RlMTcwYmI2NzVjYjc0YWJjODMyY2YxZWFhYWE1MDVjZGViMDI2NTFjMTQ5ZGZlN2U5N2JhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9tnCFaAgHZAaMwg0P0VMWJAd3PL1mzC05t1oBY9N9wg) What about this truck

yes, those fit into the bays, we haven't had any issues with that

**Comment by coalaura** [comment]
closing this then if its been solved already
