### ISSUE TITLE
Suggestion - Gov Wallet for the State

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3441]
### Assurance

I have read the `README.md`

### Summary

Add a **Gov Wallet** item at the store in State Office, similarly to the EMS and PD wallet.

### Reason

When we keep the Gov ID in a normal wallet, people can take the wallet and keep it in their pocket. Therefore, add a Gov Wallet in the State Store just like PD and EMS to prevent this from happening.

**Comment by coalaura** [comment]
i really dont see the need for that
