### ISSUE TITLE
Suggestion - Real Estate Eviction Change

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#3442]
### Assurance

I have read the `README.md`

### Summary

I think that being able to 'evict' someone after ~14 days of unpaid rent is an OK option, however I think there should be an option similar to /transfer, where when someone wants to move and lets the realtor know that they do not want that home anymore- there should be a way to take the property back immediately so it saves the realtor $ from unpaid rent. 

I could see it working either as making it so in the comp, we have free reign to always evict someone [of course only using it in this instance or hey sometimes ive accidentally sold the person the wrong house so would be cool to just cancel out that house all together]

or, very much like /transfer where both the realtor who initiates the eviction, and the tenant both have to agree to said property removal. 

### Reason

This would save each realtor money for when people decide to either buy a different property or are just not wanting a house anymore- they can utilize this function so their company does not have to wait two weeks or so to evict and ultimately negative money.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/SL2LY8ICKU.webp)
![yes](https://i.shrt.day/3WOO6Y8PEF.webp)
![yes](https://i.shrt.day/93RKLIY5LI.webp)
![yes](https://i.shrt.day/3KV7EZLEXN.webp)
