### ISSUE TITLE
Suggestion - More Stuff for Kissaki

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3443]
### Assurance

I have read the `README.md`

### Summary

After Opening Kissaki to the public I have some ideas that will help the business run better

1. Sound Proof the Upstairs Dining Area because it gets very very loud and you cant hear anyone if theres a lot of people above you and right infront of you.

2. More Food, The addition of having more food will expand the potential and price scale of Kissaki and bring a lot more people as we only have 4 things which 1 has been in the server for a long time and no one really buys which is Kimchi
I propose that we get some of the following Items

Bento Boxes (Cooked Rice, Fish Filets, Cabbage) - This would give you a tiny bit of health
Spicey Ramen (Cooked Noodles, Spring Onions, Fish Filets, Chile Peppers) - This would give you a tiny amount of Armor and Health
Ramen (Cooked Noodles, Spring Onions, Fish Filets) - This would give you a tiny amount of Armor

FOOD CHANGES
Miso Soup - Relieves Stress

3. Add another Rice Cooking spot because just having the 1 makes it very hard for multiple people to cook at once and with food taking a hot minute to make it is a struggle

Here is a picture of what the Stoves will look like after this new update is pushed so maybe move the current one and add another one to the other pot

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/116779146/a85e00c2-741d-4525-b1f3-c537afa09bc7)

I know we have been asking a lot for Kissaki Recently but with getting the feedback of the people who eat there we think these changes will bring a lot to the restaurant

### Reason

Better Kissaki

**Comment by HollaYalla** [comment]
Also the Addition of Green Tea would be good so its another drink only Kissaki has

**Comment by coalaura** [comment]
will do whenever the new stove is added

**Comment by HollaYalla** [comment]
Just waiting on Anti then

**Comment by coalaura** [comment]
> Sound Proof the Upstairs Dining Area

This is a massive pain to do manually through script. I'm only doing it that way when its urgently necessary, if its possible to do it via asset things feel free to.

> More Food

What food

> Miso Soup - Relieves Stress

No, as miso soup current is the most filling food already.

> Add another Rice Cooking spot

Done

**Comment by HollaYalla** [comment]
>> This is a massive pain to do manually through script. I'm only doing it that way when its urgently necessary, if its possible to do it via asset things feel free to.
> 
> Makes Sense
> 
>> What food
> Bento Boxes (Cooked Rice, Fish Filets, Cabbage) - This would give you a tiny bit of health
Spicey Ramen (Cooked Noodles, Spring Onions, Fish Filets, Chile Peppers) - This would give you a tiny amount of Armor and Health
Ramen (Cooked Noodles, Spring Onions, Fish Filets) - This would give you a tiny amount of Armor
> 
>> No, as miso soup current is the most filling food already.
> Makes sense
> 
>> Done
> Thanks

**Comment by coalaura** [comment]
oh oops, i skipped over the food while reading nvm me

**Comment by HollaYalla** [comment]
All good ill make some props for the food if they get added if you arent using basegame props for any of them

**Comment by rakibulhasan456** [comment]
A bento box uses a combination of Rice/Noodles, Meat/Fish/Egg, and Vegetable.

The store has Egg and there's already a Fried Egg item. Maybe we can use the stove to cook the eggs? It can be an easy and quick addition to the shop.

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/88003289/2c4a1bab-5393-44bd-bd06-fc580ec3438b)

**Comment by coalaura** [comment]
done now
