### ISSUE TITLE
Suggestion - Add Press Passes

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3445]
### Assurance

I have read the `README.md`

### Summary

Add a state issued "license" called a "Press Pass" for Press that state deems worthy of special access.

### Reason

Currently Weazel News is a LI job but there are notable instances where the Press should be afforded access to interviews, sensitive areas, crime scenes, persons, etc if they are vetted.

Adding the press pass (state issued license) would allow for background checking the reporter as a "security check" as well as providing a mechanic to check credentials before allowing access to sensitive areas.

This should allow for more flexibility and avenues to those putting effort behind journalism RP.

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/XLHGEU4MF1.webp)
