### ISSUE TITLE
Suggestion - Skateboard balancing 

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#3446]
### Assurance

I have read the `README.md`

### Summary

Make running speed reduced by 25% when carrying a skateboard on your back. 

### Reason

As it sits right now there is no disadvantage to carrying a skateboard on your back at all times, and it's basically having a bicycle in your pocket ready to roll at a moments notice. The skateboard should be used for skateboarding rp and the fun that comes with it, not as a pocket getaway tool. Between it's deploy speed being insanely fast, hitting speeds of a bicycle, and its ability to hop walls makes it extremely op to be carried at all times. So I think this helps balance that out a bit by creating a downside to having it at all times. 25% is my suggested reduction but that can be adjusted up or down depending on how well it balances things out. Anyone not escaping PD on foot with them will have no downside to this as they'll be riding the skateboard and the slow down won't necessarily affect them. I get IRL you wouldn't be slowed down by carrying one, but this suggestion isn't necessarily being made to mimic IRL but create balance as the title suggests.

**Comment by coalaura** [comment]
i dont like the slow down, i like skateboards being a thing you can just carry around with you at all times and when your car breaks down you dont have to run on foot everywhere just skate. I do see how it needs a bit of a nerf tho, however i dont want slowdown while carrying

**Comment by MetaHatter** [comment]
If they were relatively easy to fall off of if you hit something it might offset it a bit.  hitting a wall or pole on a real one would ragdoll you IRL.

**Comment by joevapes3** [comment]
I mean it's a bike that people can just shit out their pockets at anytime and escape on, there is legit no balance, and or downside to using them currently and there should at least be something. Legit every criminal is carrying them on them and using them to escape, and there isn't any downside to packing them. If you ran slightly slower it would at least make it so you had the trade off to carrying it on you while you do crime, and it doesn't hurt the legal people using it as they're actually riding the skateboard. 25% is just the suggestion but it can be lower than that, just needs some type of trade off. Deploy times should be slower too but that's a whole other issue in itself.

**Comment by coalaura** [comment]
rn they are about 10mph slower than top speed with a bmx but you can probably push that when going downhill. I'll try to make it so being hit by a car will knock you off

![yes](https://i.shrt.day/UCSPG2FM8U.webp)
![yes](https://i.shrt.day/OP45FGJGO5.webp)

**Comment by coalaura** [comment]
> I mean it's a scooter that people can just shit out their pockets at anytime and escape on, there is legit no balance, and or downside to using them currently and there should at least be something. Legit every criminal is carrying them on them and using them to escape, and there isn't any downside to packing them. If you ran slightly slower it would at least make it so you had the trade off to carrying it on you while you do crime, and it doesn't hurt the legal people using it as they're actually riding the skateboard. 25% is just the suggestion but it can be lower than that, just needs some type of trade off. Deploy times should be slower too but that's a whole other issue in itself.

all good man, i'm not saying they are staying the way they are. I said i do see that they need a nerf however i just don't like the slower walking speed approach. I am more than down to look into other tradeoff ideas tho, like meta said for example making them easier to fall off of.

**Comment by coalaura** [comment]
I've also added an extra animation step to the deploying of the skateboard making the whole process slower

**Comment by joevapes3** [comment]
The extra step is great, that will add some more balance too it. Question though; Do they use a handling meta to make them operate? Cause if they do check the mass on the xml cause they currently knock cars out of the way when hit and that usually indicates a high mass, but could just be scuff with them too. Figured I'd ask. But yah they need some type of trade off, cause you've never had the ability to just poop a scooter out and it's super OP as it sits now. I think they're cool asf, but need to find a balance to them with consideration to crime. I hate that we have think that way but you know how people are, they take any and all advantages that they can get.

**Comment by coalaura** [comment]
its not a vehicle, beneath the hood its an NPC riding a bmx bike with the skateboard and the skateboarder being attached to the bmx. Them kicking cars out the way is simply a limitation of gtas physics

**Comment by coalaura** [comment]
personally i'd wanna leave them be with these changes and the ones i already did which will be in next update. If there is certain things that arise that are actually serious issues making it unbalanced we can work on finding a solution for those scenarios. I'll close this for now, but i will keep it on my todo list to check back in in a week or 2 to see if any issues arise

**Comment by joevapes3** [comment]
I just look at it this way, coke, makes you faster, it has a trade off, you get hurt when you use it. Skateboards? no trade off, you can just rip when you use them without any downsides. Needs a downside.

**Comment by coalaura** [comment]
I don't think everything needs a downside. IF something turns out to be too OP in certain scenarios, THEN we can add a trade-off specific for the scenarios where its too OP

**Comment by scufflord** [comment]
Not everything needs a downside. I had a super fun chase with two cops yesterday on a skateboard and it was by far the most fun pd interaction I've had. Respectfully, PD needs to stop locking a lot of their tools that may be able to help with these scenarios behind every high rank and test that they can. This is only an issue with the international server, none of the other servers seem to be having that issue, and the framework is used across multiple servers not just legacy international. 

People need to remember we're not roleplaying real life - we're roleplaying grand theft auto characters. Not everything is gonna make sense or be balanced.
