### ISSUE TITLE
Bug report - Cayo Hospital Checkin

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#3448]
### Assurance

I have read the `README.md`

### Reporter

.vikky_.

### Summary

So before some time, Cayo Hospital had some glitch, not sure, due to which downed players from the cargo ship went into an infinite black screen after taking respawn. That issue has been fixed, but now if someone is grinding in Cayo and wants to check in at the hospital in Cayo,. we get pop-ups always saying, **All beds are occupied.**

### Steps to Reproduce

go to cayo hospital .
Press **E** to check in into hospital for treatment 

### Expected Behavior

After Pressing **E** player must be teleported onto 1 of the bed for treament as of other hospital .

### Actual Results

instead of that we get pop up that **All Beds are Occupied** when no one is on the bed .

### Screenshots/Videos

https://media.discordapp.net/attachments/777722318159347712/1256662949465034913/image.png?ex=66839052&is=66823ed2&hm=f4cdf2194d93f8bea8892b858d567e27b22a5f76ca3c17b851df9bce62100742&=&format=webp&quality=lossless&width=1194&height=671

### Game Resolution

1920*1080

### Player Data

https://i.ibb.co/qFVXBWm/Five-M-b3095-GTAProcess-t-N6n-Xwy-Jmq.png

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
is this still an issue?

**Comment by Vikky98** [comment]
> is this still an issue?

it's fixed now; we had wipe on c8 yesterday . I just checked, and checkin is working perfectly.
