### ISSUE TITLE
Suggestion - State issued License for Part-Time Lawyer

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3451]
### Assurance

I have read the `README.md`

### Summary

It will work similarly to the **Press Pass**. The license name will be **Lawyer**. The heading in the ID card will also be Lawyer and be available at the Courthouse.

### Reason

In our subdivision, we have many people who have other full-time job and do the lawyer as a part-time service. I am sure other subdivision also have people like this.

The problem is, they don't have any access to the DOJ office or can't withdraw any Lawyer ID card. They can't show any identification card when required.

So a State issued ID card only for those lawyer will do a great job for the people involved as a part-time lawyer.

**Comment by coalaura** [comment]
There is already a DOJ ID. You can just give them the job temporarily and they can grab an id. I don't think a whole separate item is needed for this edge case.

![yes](https://i.shrt.day/OCH2C9A4VP.webp)

**Comment by rakibulhasan456** [comment]
@coalaura 

It can be done. But the ID card might have **DOJ** label and I think you won't be able to use it or move in or out of your inventory.

If it's possible to show this ID card without the job and you can move from your inventory, that will do the work.
