### ISSUE TITLE
Rework to 945 Studios

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3452]
### Assurance

I have read the `README.md`

### Summary

Changing it to a local store instead of player owned!

### Reason

With how it’s set up atm, the only one who can edit and or add / delete reading card packs are ones with the database (the owners of each city) I think making the store let’s say up on vinewood at the toy store or something along those lines, but it could add more interaction with trading cards this way! 

For right now it’s pretty much pointless to own / work at 945 studios if you aren’t the owner, for example I have packs made but can the use because I mainly focus PD!

**Comment by coalaura** [comment]
no, its designed to be a player owned store
