### ISSUE TITLE
Flag Swap Rework

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3454]
### Assurance

I have read the `README.md`

### Summary

A little more visual appearing

### Reason

Let’s say we make a little custom prop, a smaller flag and then for holding it, we could use maybe a vest, 

1+ Flag - Blue Vest
5+ Flag - Red Vest
10+ Flag - Pink Vest
25+ Flag - yellow Vest
50+ Flag - green Vest
100+ Flag - white Vest

with the current flag, it’s just big and janky for some not wanting to participate in the event!

**Comment by coalaura** [comment]
i think the flags are cool

**Comment by coalaura** [comment]
also feel like it would kinda defeat the point of **FLAG** swap

**Comment by InZidiuZ** [comment]
This will not be done at this time.
