### ISSUE TITLE
Traction control

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3455]
### Assurance

I have read the `README.md`

### Summary

Similar to cruise control or speed limiter

### Reason

Making another muscle Traction Control

turning the tires from regular to drift,

**Comment by Alyshiva** [comment]
> I think we have traction tires in LS Customs..

We do but you can’t toggle them

**Comment by coalaura** [comment]
no, i dont like them being togglable at all times, you have to go and get your tires changed at ls customs
