### ISSUE TITLE
PD Radar Gun

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3456]
### Assurance

I have read the `README.md`

### Summary

Much like the speed tracker in car

### Reason

There should be a gun, that you can point and capture the speed of. Certain cars ur aimed at! 

This would bring in some good rp for cops, maybe it can print out a piece of paper with the plate number and speeds, I’m thinking some more things for highway patrol!

**Comment by coalaura** [comment]
Wouldn't it be smarter to sit in your car in a bush with the radar open? By the time i've read my radar gun and gotten back into my vehicle and started the engine the speeding vehicle is long gone

**Comment by SluggsV2** [comment]
Yes and no, I think the radar gun either way will be a good addition and something that will be used,

**Comment by HollaYalla** [comment]
A passenger can use it or the driver can sit in a spot and aim it at a specific direction but still have their vehicle angled to be ready to take off

**Comment by coalaura** [comment]
could instead just make the radar accessible when in the passenger seat too

**Comment by coalaura** [comment]
i just really don't think anyone is gonna use a radar gun that does the exact same thing as their already existing radar, just with more effort

**Comment by MetaHatter** [comment]
> could instead just make the radar accessible when in the passenger seat too

This would actually be a very nice change.  Kind of silly that a passenger can't check a plate or anything since thy can't "see" the device on the dashboard.

**Comment by TacticalTyl3r** [comment]
The only thing I can see is a car up the street standing outside his car running radar with other vehicles down the street ready to intercept them.

**Comment by SluggsV2** [comment]
yeppers, how highway patrol does it most of the time in head, or hell the driver even uses it, i think there will be more use then you think with this. like i mentioned in the first thread, i think if it had a little print out that you "clocked (Trigger a button)" and on that print out will be, Plate, Top Speed well clocked, this can be used for court RP as well as its another physical evidence
 we can bring fourth!

**Comment by coalaura** [comment]
the radar is now accessible when in the passenger seat too, like i said i really dont think this would get used for the amount of effort needed to make it work nice. Being able to control the radar from the passenger seat should alleviate the same issues tho
