### ISSUE TITLE
Suggestion - MP Autos workbench addition/relocation

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#3457]
### Assurance

I have read the `README.md`

### Summary

Hey! Just a quick one to ask if it would be possible to have a workbench on the wall at the clothing spot side of MP Autos. (Images attached)
If that's not doable and you want to keep it to two workbenches, the one on the office side at the windows doesn't get used as often.

### Reason

Sometimes if it's really busy it can be a faf for mechanics having to run past not only cars but people, and having the addition of a second workbench in a useful spot would be beneficial for mechanics
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/77466954/ec87e9a9-8063-453f-aa54-0a50be86e33f)
![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/77466954/61dd75d7-bdd1-43c2-b8da-d4326085c4d2)

**Comment by antihero6713** [comment]
I pushed the workbench there

**Comment by coalaura** [comment]
i'll move the workbench spot to match the new location

**Comment by coalaura** [comment]
done
