### ISSUE TITLE
Emotes Update / rework 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3458]
### Assurance

I have read the `README.md`

### Summary

Placement of emotes like props 

### Reason

With the “recent” addition of improved prop placement / advanced Prop placement, I think this could be a huge case for emotes, from sitting, to dances to job emotes, (all in the emote menu) could add some huge benefits, 

When turned on like prop placement, 

You will select a emote, and then an outline of your person doing that emote will pop up as a preview then you will accept when you want it set, 

you can also cancel. With X or /e c just like normal,

**Comment by coalaura** [comment]
I've seen this in other servers and it tends to look a bit wonky. Adding to this, i know for a fact this **WILL** be abused on public servers
