### ISSUE TITLE
Suggestion - Add "Locker" to Mayor's Office

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3459]
### Assurance

I have read the `README.md`

### Summary

Requesting a "Locker" similar to PD, EMS, Mechanics, and Fast Food establishments be added to the Mayor's Office inside of Maze Bank Tower

https://files.catbox.moe/wklksm.png

https://files.catbox.moe/46yuub.png

### Reason

As currently there is no location, office, or building dedicated for State Security, and our vehicles are not owned as PDs are where they can store things in their cars or locker - I believe both State Security (in addition to state employees) could benefit from a locker location in the attached photos above. 

Clothing may need to move a tad to the right in front of the actual clothing prop, then locker could be in front of the doors (or wherever seen fit, this is just a suggestion) - but this would allow SASS and State Employees to store job related items they are required to carry according to SOP that they might not necessarily carry all the time when they are not actively working (advanced repair kits, baton, cuffs, taser, Gov ID, med kits - printers, paper, printed documents, items for events etc) 

This would be a great solution for swapping out inventories when "going on duty" 

 In addition, a request for them to be able to store **_Government issued_** ammunition and firearms would be a great addition (I believe PD can as well).
 
 I am looking to make small but impactful QOL updates for State RP that makes it more fun, this is small but useful.

**Comment by Thales1732** [comment]
Agreed a locker would be nice, I tend to use my personal vehicles more often than state issued vehicles just due to the fact I can store stuff in them. This would help me be able to clean up my pockets a bit before going on detail and actually be able to equip things required in SOP.

As mentioned PD is able to store stuff in their cars we can't but this would go along way for both Security and State officials.

**Comment by coalaura** [comment]
done

**Comment by Thales1732** [comment]
W's Laura ❤️

**Comment by MADxxVIKING** [comment]
Another common W for Laura ❤️
