### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#346]
**Reporter:**
Tria.

**Summary:**
Vehicle cruise control can be enabled by passengers and driver which leads to a visual and speed meter desync.

**Steps to Reproduce:**
Have 2+ people in a car and activate it.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
