### ISSUE TITLE
Suggestion - Yellow Jack QOL Additions

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3460]
### Assurance

I have read the `README.md`

### Summary

Adding three additional spots to help with Yellow Jack functionality and RP -

1. New "Counter" space location where there is an inventory to exchange drinks/food with the patron (also seen at other restaurants, and Teqilala bar, etc
Picture for Location Request - https://files.catbox.moe/hilqhh.png

2. A Blender. This establishment frequently makes blended drinks & smoothies. Seeing a perm blender will 
Picture for Location Request - https://files.catbox.moe/lpxyxn.png

3. Locker to store items (currently additional food items not provided in the bar store)
Picture for Location Request - https://files.catbox.moe/mo1h1x.png

4. Water Cooler (Opt A, B, or C)
Pictures for Location Request - 
https://files.catbox.moe/gmalvn.png
https://files.catbox.moe/dd846y.png
https://files.catbox.moe/w01ju9.png

5. Yellow Jack Private Garage - Location anywhere, behind the business could be nice.

### Reason

Requesting for the following reasoning -

1 - **New Counter Space:** Counter Space to exchange drinks & food has become the new standard for bars and restaurants - Yellow Jack bar is so thick that you have to come around the bar in order to hand things, its hard to position yourself to access and inventory from the other side, also unrealistic. 

2 - **A Blender:** Due to a number of "mixed drinks" that have been produced on the menu, many things get mixed. This has become a standard practice at most Legacy bars, commonly seen at Tequilala. Adding a blender would help easily creating these drinks for RP in addition to some of their smoothie offerings from local fruit stands etc.

3- **Storage Locker:** Currently for Legacy International, the owners of Yellow Jack have had a a decent turn out due to two key things - 1. Cheap drinks (they don't bill for profit margins, just to drive people to be patrons of the bar for RP) and 2. they make BBQ sandwiches, jerky, and a few other items there on site at Yellow Jack. They currently have to travel a far distance to bring 2-3 vans holding food items to the site. They still plan on bringing a grill as we believe it may be unrealistic to request a grill inside Yellow Jack since it is a bar not a restaurant (unless you see fit to add one, there is a "blackstone" style grill on the counter top already, or one could be added outside), however being able to store meat they buy off of people to make BBQ sandwiches, also storing the ingredients in which to make those and other combos they create by gathering items for when they open, could greatly benefit the RP of having a "run down kitchen making bar food".

4 - **Water Cooler** It would just be nice to have a water cooler in the establishment. You're in the middle of nowhere, could be cool to have one included at this site as I don't believe there is another local. 

5 - Employee Parking would help not clog up parking spots and add to any potential headaches in the area. Also helps from cars poofing -- nearest garage is quite the jog away.

I would consider all of these QOL for the location seeing as an MLO won't be added for Yellow Jack to make it into a biker bar/clubhouse - it already has a biker bar aesthetic though, and in the future I could see these additional resources beneficial for the business as a whole and making it more desirable to own location opposed to it going months without an owner, and when it does get an owner, it dies out within a month tops due to lack of resources.

**Comment by MADxxVIKING** [comment]
* for request #2 - Also wanted to include a second blender on the opposing side of the counter would also be nice, but not absolutely required. One would still be a huge W

**Comment by coalaura** [comment]
blender and water cooler would be an asset issue, i'll add the counter, locker and parking

**Comment by coalaura** [comment]
all the script related changes are implemented

**Comment by Dibbey** [comment]
I hope this is okay if I re-open this as my title would've just ended up being the same. We just got the Blender and Water Cooler from this github: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/916#issue-2484103277

And I was wondering if it would be possible to get something worked out with a Grill via this suggestion of the same github (https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/916#issuecomment-2307998642)

> Additionally, if possible (and I hope this is the correct github, if not I will post it on the script one), it would be really nice if the grill in the Yellow Jack Bar that is on the counter, next to the suggested position of the Blender, could become usable for cooking.
> 
> The most balanced slots to cook meat, eggs and pancakes better would be really neat, as we are currently utilizing the 4-slot grills to slowly cook up everything. So anything would be really nice, such as replacing the counter grill with the 4-slot grill to be permanently usable by Yellowjack Employees and such, or a similar grill of the cheaper variaton.

I'm mainly bringing it up, so employees can efficiently operate from inside the building and don't have to rely on either keeping track of their own placed grill that blocks up ground space or repeatedly buy more grills if lost. As Meat, Eggs and Pancakes are cooked up for like every opening (Since it's an Inn, but also to give off more of a BBQ kinda vibe with the Bar). Not really asking for an electric grill, even if that would be cool too, but just one that can be used to cook up the stuff for the menu reliably ♥
