### ISSUE TITLE
Working stripper pole at lostmc shop

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3462]
### Assurance

I have read the `README.md`

### Summary

Stripper Pole working

![Screenshot 2024-07-12 153417](https://github.com/user-attachments/assets/f63e1779-ee3b-4cc1-a5bd-700c0456dd83)

### Reason

We can use it in the house why not use it at the business!

**Comment by coalaura** [comment]
done
