### ISSUE TITLE
New Buildings

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3463]
### Assurance

I have read the `README.md`

### Summary

A few more shops for existing and non existing shops! (Pets, Icecream, SeaFood)

### Reason

Pet Store adding one to the city (by the beach), the same one from the paleto 

![Screenshot 2024-07-12 153940](https://github.com/user-attachments/assets/740dcb55-ad0f-4b3a-82f8-abc0d9795b70)
![Screenshot 2024-07-12 153927](https://github.com/user-attachments/assets/8751a003-8b41-4d61-9245-4025b979ffdf)

Pot-Heads SeaFood, Already got a place in city, Can be a new restaurant owned by a player,
Menu;
Lobster (From Fishing)
Crab (Make a Crab Net from fishing store)
Fish (Cooked Fish Opposite of Sushi) 
Seafood Hash (Its on the side of the building)
THC Butter (Its a *Weed* name store) also i need butter for my lobster (Milk + weed 1oz)
Fries 
Biscuits (All Sea-food have Biscuits) 

![Screenshot 2024-07-12 154701](https://github.com/user-attachments/assets/659b992a-0050-44c9-8e6f-e18395c34928)
![Screenshot 2024-07-12 154626](https://github.com/user-attachments/assets/8ae19864-b1c4-421e-aa94-134f2b2b7f1d)
![Screenshot 2024-07-12 155502](https://github.com/user-attachments/assets/251349ed-c9c7-47d4-a243-9c0187c431de)

Ice Cream - Also a player owned business, by the beach!
Menu;
Ice Cream Cone, (Mint, Vanilla, Chocolate, rocky road, really endless)
Milk Shake (Mint, Vanilla, Chocolate, rocky road, really endless)
Slushies (Blueberry, Grape, Orange, Raspberry, Also tons of flavours)
Ice Cream Sandwich
Freezes (Blueberry, Grape, Orange, Raspberry, Also tons of flavours)

![Screenshot 2024-07-12 155147](https://github.com/user-attachments/assets/61289734-bd46-499e-992f-a741ac3ae420)
![Screenshot 2024-07-12 155137](https://github.com/user-attachments/assets/066144c9-8553-43ed-b499-666b8254b133)

**Comment by coalaura** [comment]
> Animal store in the city

Maybe, i'll take a look

> 2 brand new restaurants

No, we have a lot of restaurants in the city which are underused, before any big new businesses are gonna be added, they not only have to rp their business existing in the first place and second the other restaurants should be used and there should be an actual need for new restaurants
