### ISSUE TITLE
/race_info (race name)

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3465]
### Assurance

I have read the `README.md`

### Summary

It would give you basic info like

### Reason

Race Checkpoints, 
Fastest Time and by who
Or 
/race_leaderboard
And it pulls up a tablet of all races in city then when you click a race it tells you the top 5 fastest lap times and by who

**Comment by coalaura** [comment]
races are per person, also not everyone may want all times to be publicly visible
