### ISSUE TITLE
Suggestion - PD Tow Truck 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3466]
### Assurance

I have read the `README.md`

### Summary

A tow truck that officers can pull out kinda like motorcycles. 

### Reason

We need this when there are no tow truck drivers available and we need to PD impound a car that is disabled.

**Comment by SluggsV2** [comment]
I back this 100% also having a long winch or something to grab cars that crimals ocean dump, maybe a 30-50ft. Cable we could use! But great idea in general!

**Comment by coalaura** [comment]
Since you are asking for a new vehicle, this would be an asset issue: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=Suggestion+-+I+want+tow+truck+plsss
