### ISSUE TITLE
Ocean Side bank

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#347]
**Reporter:**
Who is reporting this? Cricketx818

**Summary:**

So Ive had some people in my group hit Ocean side bank, every time they go to the vault and use the thermite, The vault door never opens

**Comment by InZidiuZ** [comment]
Are you able to confirm whether this is still an issue after 1.3.10?

**Comment by InZidiuZ** [comment]
Closing, no further activity.
