### ISSUE TITLE
Suggestion - Bahama Mama Changes

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3471]
### Assurance

I have read the `README.md`

### Summary

Bahama Mamas is a bit outdated so here is some changes that would help make it better for the employees to run it
![image](https://github.com/user-attachments/assets/9419dafa-06c3-4c72-a1e4-9141eaff2519)
A Bagging station and Bahama Mama Bags
![image](https://github.com/user-attachments/assets/7aae63c3-84ae-4b58-ac9d-bf148ff8a950)
2 Counters placed in those 2 spots
![image](https://github.com/user-attachments/assets/babb4855-04c3-42eb-a4cc-a20b676c056f)
A Counter and a Store Upstairs so using that room is faster

### Reason

Make Bahama Mamas Better

**Comment by HollaYalla** [comment]
![image](https://github.com/user-attachments/assets/17b0a155-6f0b-477c-b1dd-f5d03bf9caae)
Also can we get this to be a No Ped Population Area please because locals love to spawn inside Bahama Mamas sometimes and it can get annoying fast

**Comment by coalaura** [comment]
> A Bagging station and Bahama Mama Bags

Its a bar not a restaurant, no

>  A Counter and a Store Upstairs so using that room is faster

Sure
