### ISSUE TITLE
Suggestion - More MDT's

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3472]
### Assurance

I have read the `README.md`

### Summary

So in Legacy International more and more businesses have their own type of "MDT" so I was thinking maybe allowing /mdt be accessible by each job but it will lead to a different link each time so if an Kissaki Employee did /mdt it would bring their MDT up and if their job didnt have a specific MDT in the chat it would just say "You do not have access to this command" it just makes sense to have it In Character instead of going to a web browser

### Reason

It just makes sense

**Comment by coalaura** [comment]
PD are the only one that need an MDT to do their job thats kinda the only reason they have the command. I don't think it should be added for all jobs, i'd rather keep those where they are rn
