### ISSUE TITLE
Garbage Cans

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3475]
### Assurance

I have read the `README.md`

### Summary

Place Players in garbage cans, and making them smell bad

### Reason

This would only work if they were handcuffed, and then maybe like a minute timer until they can come out or "tip over the garbage can" mini game to get out,  this would also trigger a /smell "Musty" in order to put them in the garbage can, you must handcuff then /carry them and just like putting them in the car maybe /door will open the lid of the dumpster and then flex ur "f" muscle to put them in and thats when it starts a timer or mini game to get out

**Comment by coalaura** [comment]
No, i dont think you should be able to do this. Even the ability to hide in a dumpster would be hella abused...
