### ISSUE TITLE
Suggestion - City Power Blackouts 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3478]
### Assurance

I have read the `README.md`

### Summary

Every once in a while the power in the city will go out for a while so maybe if there's a storm the power goes out for 10-15 minutes. Or if there's a large amount of people ic the power has a small chance of going out for 10-15 minutes. 

### Reason

Not necessary reason other than it would be cool and could create fun RP.

**Comment by HollaYalla** [comment]
Make it so that all ATMS are unusable during these times and /bill doesn’t work either would be fun

**Comment by baconnator1** [comment]
Well then anyone that is working at a business would have to close.

**Comment by SluggsV2** [comment]
This would be sick, we recently had 4 days over a 3 week stretch where we had terrible and I mean terrible ran, cause us to black out, and have to close my mechanic shop. Sent all my workers home and took the day as it went. Very possible in head and I think would be a great addition to rp. Now to balance it I think it should only happen on those bad rain or wind storms

**Comment by TacticalTyl3r** [comment]
If someone can "tamper" with the substations or small electrical boxes around the city it could also give the PD a call for them to check it out as well.

**Comment by coalaura** [comment]
I don't think making everything stop for a whole 10-15 minutes is a good idea. However i have added a small chance for a blackout to be triggered during thunder weather. I've also updated the blackout script to disable all ATMs while a blackout is active (/bill will still work however).
