### ISSUE TITLE
Suggestion - More Food Options+ Changes at Pizza This!

### ISSUE THREAD

**Issue by spitslave** [InZidiuZ/op-framework-issue-tracker#3479]
### Assurance

I have read the `README.md`

### Summary

**Slight Food Buff**
Make it so a slice grants a little more fullness

**More Toppings**
Pepperoni Pizza
Veggie (Just various vegetables, ex. jalapenos and olives)
Meatlovers (Various meat Salami, Pepperoni, and Ham)

**Appetizers**
Garlic Bread w/ Cheese or No Cheese option (For people that are lactose)
Bread Sticks
Than put the reasoning in the reasoning

### Reason

The reasoning for wanting the slices to be more filling is because; other food in the city do fill up players more and I feel like Pizza This is less wanted because people prefer things beneficial to them. 

I feel like having more options in food would give us more RP as well, people do come to the Pizza shop and ask for Pepperoni Pizza all the time and I thought having a meat lovers that will require the same ingredients that already exist as well as a veggie pizza would be good to also have so that we have more of a selection. 

Reason for appetizers is because most Pizzeria's do have appetizers and I want to incorporate making coupons that people can get with each meal where they will be able to get a deal for 2 orders of Mozzarella sticks, pizza, and drinks etc. Although its a game I want to make the experience as realistic as possible. 

I know Pizza This is a new added feature but I do think these things will be great to have if you will grant us with it.

**Comment by coalaura** [comment]
>  Make it so a slice grants a little more fullness

Maybe, but only a little. They don't do AS much cause you get 4 slices from 1 pizza. Different pizza flavors will also fill you up different amounts.

**Comment by coalaura** [comment]
I've added the pepperoni pizza, vegetarian pizza and breadsticks.
