### ISSUE TITLE
Helicopters and Planes

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3480]
### Assurance

I have read the `README.md`

### Summary

Making the switch from license style to PDM style its needed and will add alot more RP

### Reason

To Give a quick summary it can add anything from new laws in city to jobs to new ways to flex your money. 

For the jobs, 

Luxury Helicopter Salesmen - Sames as PDM, maybe maybes a little less % wise since sale price is generally higher 
Helicopter and Plane Custom Shop, There can be one at LSIA, a hanger there can be turned into a custom shop for planes and helicopters
Players can also rent out their helicopters and planes for a fee, kinda like Turo, or something close. 

This will add a stance of RP in the fact that they can be tied back to the owner which will make the more reason to keep things legal with them, right now you can poof them in and poof them out aslong as they are still running, say it can be used in a chase and they get away it can get put away with no tracking back, with owner ship it can bring in investigation rp. which brings into the next point customization and flexing.

with the prices of planes and helicopters being most likely 500k ish starting maybe even 750k thats not a purchase just anyone can do, as of right now the owner thing you can really spend money on is cars, lets step it up and lets spend big boy money! 

Please give this a thought i believe this will add a whole nother step to RP and think the community could benefit!

**Comment by coalaura** [comment]
I am not a fan of a PDM style dealership for aircraft & helicopters. I like them being relatively difficult to obtain. I believe it offers more RP to keep it license based and rentable than to have a PDM for planes and heli's. However i do want to add a more reliable way for criminals to obtain aircraft and helis too.
