### ISSUE TITLE
Homeless Tents Lootable

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3481]
### Assurance

I have read the `README.md`

### Summary

Just like Garbage cans, make homeless tents lootable

### Reason

Theres a few spots around the map where homeless tents / homeless camps are setup. Make then lootable like garbage cans and have the loot table similar but not exact: This would help Homeless RP, by adding a new way for us to obtain items.

Im thinking items such as almost expired drugs, almost broken shanks and knives, and then the items like nearly expired food and drinks, maybe even like broken game systems and random broken items that can be either fixed or sold to a new store in town! like a pawn shop maybe

**Comment by enutpeanut** [comment]
that's fucked up?? stealing from homeless people 😭

**Comment by SluggsV2** [comment]
well more or less you really wouldnt do it unless you were a homeless character youself, Homeless on homeless crime is allowed xD items that would be given, wouldnt last long, and or wouldnt be worth a ton, just gives a reason to actaully want to RP as homeless, im currently starting a character my self,!

**Comment by coalaura** [comment]
hmmmm, not sure if i like this idea

**Comment by SluggsV2** [comment]
Can we get some sort of enhancement for homeless rp?

**Comment by coalaura** [comment]
done now
