### ISSUE TITLE
Lemonade 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3483]
### Assurance

I have read the `README.md`

### Summary

New drink, lemonade! 

### Reason

As much of a popular drink it is, I believe we should have lemonade and link lemonade!!

**Comment by SluggsV2** [comment]
Maybe doesn’t have to be a store item, but lemon tree that you can harvest lemons, and then a juice press, could even turn this into, orange trees, apple trees, and make juices out of them aswell! But main one would be lemonade!!!!

**Comment by coalaura** [comment]
there is lemonade already, its sold by bean machine
