### ISSUE TITLE
Bug report - Speed Limiter Not Limiting

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3484]
### Assurance

I have read the `README.md`

### Reporter

MetaHatter

### Summary

The Speed Limiter does not work if your speed goes above the set limit. It will return to functional if the speed is reduced to below the limit. (at least until you hit a bump or go downhill)

### Steps to Reproduce

set speed limiter to 50mph and drive down the hills in vinewood. You will exceed the limiter speed and continue to accelerate

### Expected Behavior

As it used to work.  If you exceed the limit it will hold that as max speed, preventing you from accelerating further, until you drop back to or below the set limit.

### Actual Results

If you exceed the set limit with speed limiter enabled and hit a bump, or otherwise exceed the limit, the accelerator will behave as if no limit is set until you lower speed to below the set limit again.

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
wait nvm i missread this, will fix

**Comment by coalaura** [comment]
fixed
