### ISSUE TITLE
BCFD/EMS Training 

### ISSUE THREAD

**Issue by SammySandbags** [InZidiuZ/op-framework-issue-tracker#3485]
### Assurance

I have read the `README.md`

### Summary

Currently when BCFD switches Training tracker on it says EMS Training this can be confusing for PD, as they are not familiar with whos who. And can cause PD to switch to Freq 2 to ask BCFD for assistance when no EMS is on Duty. This can cause frustration between PD and EMS as they think EMS is ignoring them when actually they are asking on the wrong Frequency.

Please can you change the BCFD Training tracker from EMS training to BCFD Training. 

Many thanks 

### Reason

Change the BCFD training tracker to say BCFD Training. 

This will help PD switch to the correct frequency and speed up any medical assistance they require.

**Comment by coalaura** [comment]
fixed
