### ISSUE TITLE
Birthday Cake

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3487]
### Assurance

I have read the `README.md`

### Summary

Birthday cake! And gift boxes! 

### Reason

Birthdays are major yearly events that happen to everyone and anyone! Having a cake in game, would create a party type event food we could enjoy, even if it was made in our house! 

There can be other items, such as wrapping paper that turns what ever items you want into a “mystery item” limited to non lethal (weapons) or balloons! 

*we have a bday in our city in 2 days (the 30th) and it would be huge to just have a cake* ofc no rush! But thank you in advanced if this does get accepted!

**Comment by coalaura** [comment]
Yeah i like the idea of being able to cook a cake. I would probably make it a more generic cake so you can use it for all kinds of festivities instead of being limited to a birthday cake.

> There can be other items, such as wrapping paper that turns what ever items you want into a “mystery item” limited to non lethal (weapons) or balloons!

We already have gift boxes for this exact thing

> we have a bday in our city in 2 days (the 30th) and it would be huge to just have a cake ofc no rush! But thank you in advanced if this does get accepted!

probably wont be done in time

**Comment by coalaura** [comment]
Bean machine now has the ability to bake cakes in their oven

![yes](https://i.shrt.day/IEMTH4VL1Y.webp)

using the materials in their fridge

![yes](https://i.shrt.day/IZQS7F3FRM.webp)

to make one of 3 cakes

![yes](https://i.shrt.day/HU6LYB9IGM.webp)

which you can then slice by using them in your inventory, like pizza from pizza this

![yes](https://i.shrt.day/L1EEPW8DGF.webp)

**Comment by HollaYalla** [comment]
Finally Bean Machine isnt just a Buy and Bag place
