### ISSUE TITLE
Rocks

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3488]
### Assurance

I have read the `README.md`

### Summary

We can go 2 ways with rocks, simple or In depth

### Reason

Simple - Adding Rocks via Magnfine glass, let’s say on dirt trails, or gravel pits

In depth - People like rocks and typically like finding weird shapes or oddly looking rocks, 🪨 we could add a new type of activity, kinda like gem finding, but for new rocks, once obtaining the rocks you could either, “wash them”, sell them, or keep them, which brings me into the next part, Painting Rocks, let say they use

a paint + rock + paint brush, and there’s, preset paintings on the rocks, happy face, clouds, flower, ect, now this will be a lot more code, I generally think the simple route is all we would need!

**Comment by coalaura** [comment]
Simple is something else. There is no builtin feature to paint on rocks in gta that i can just use. I dont mind adding more items you can find with the magnifying glass but rocks i dont think are a good addition
