### ISSUE TITLE
Bug report - Drowning in Canals after taking Z-Pill

### ISSUE THREAD

**Issue by AileenHeather** [InZidiuZ/op-framework-issue-tracker#3489]
### Assurance

I have read the `README.md`

### Reporter

AileenHeather

### Summary

The deeper canals are drowning you when you are placed in them at the start of a z-pill. 

### Steps to Reproduce

Take a z-pill. 

### Expected Behavior

If you land in the canal it carries you down the canal underwater. Drowning you unless you can manage to get to the surface. 

### Actual Results

Drowning? Loss of Z-pill time due to injury or drowning. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/im9nw7nD5fjptvS1R/d1337QkMuqPY?invite=cr-MSxrWlQsNjQ3NDEyNzMs

### Game Resolution

NA

### Player Data

Ayla Maree-Nemex - This isnt applicable as it is not just me that would encounter this issue. Sorry Im not much help, I was told to bring this issue here, but I feel like it may be more server specific because of the suddenly deeper canals. 

### Server

International (c3s1.op-framework.com)

**Comment by antihero6713** [comment]
Sorry

**Comment by coalaura** [comment]
there is not really much i can do about this. The canals were filled by people in the asset team so you'd need to speak to them to have them drained. I would just recommend not taking a z pill while near the canals to avoid spawning there
