### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by stormin88** [InZidiuZ/op-framework-issue-tracker#349]
Stormin#5314

Not allowing shooting from inside vehicles over X mph. Also add the old style of driver not being able to pull a weapon inside vehicle.

This would allow for much better chases between police v crim or crim v crim. Less shooting more driver skill. More people in 1 vehicle instead of 1 person per vehicle.

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not happen.

**InZidiuZ**
*OP-FW Developer*
