### ISSUE TITLE
Suggestion - ability to load people into big rig / semi truck seats

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#3490]
### Assurance

I have read the `README.md`

### Summary

big rigs / semi trucks for some reason do not allow you to place people in the seats of them, no matter if the door is open or not. This creates an issue when truckers find people downed and there is no ems around cause you have to steal a car to help them or go and get one of your own. Would be nice to be able to set them into the seats but it doesn't seem to work. I think every big rig we've tried doesn't allow it. I'll list some of the models below.

### Reason

Would provide the ability for truckers to help people who are downed and not have to steal a car or leave to get one at another location when they already have an open seat available in their vehicle. Would keep the naturalness of the scenario moving vs the awkwardness of it not. That and not having to explain that it doesn't work to the people trying. 

These are some of the models where you are not able to carry and load players into the seats of the truck:
phantomday
phantomoldschool
phantomflattop
phantom
hauler
mule
packer

**Comment by coalaura** [comment]
Its cause the seat is so far up, obv gonna be difficult to lift a dead body up 6 feet into the air to place them in an elevated seat. I'll look into it

**Comment by coalaura** [comment]
fixed
