### ISSUE TITLE
Suggestion - Better Trailers

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3491]
### Assurance

I have read the `README.md`

### Summary

With all the bugs and issues with the normal trailers but the Semi ones having nearly no issues let us just own Semi Trailers.

One that can replace our current trailer is the **Flat Trailer** it can tow 1 Large Vehicle and has a storage of 500 or 750

A New Trailer that is mainly for storage which is the container trailer has a storage of 1000 or 1250 (or even 750 so its not OP) this would allow people to actually use their Semi's even if they don't truck.

Also for actual truckers maybe a change to the script would be good and if they had the Box trailer on and they went to a specific Trailer Depo you would go upto the door and select the cargo and this would give you more money maybe starting be the same price as the illegal cargo and the illegal cargo for this would be like 1500ish, and you would backup to the spot and click **E** and it would take a hot minute for the cargo to get loaded up and show a progress bar of **Loading Trailer** and when it is done it will give you a normal trucking route, and maybe add a new blip for these new locations just called **Supplies Depot** and these require for you to own the trailer and if you dont it will give u the 1 minute penalty and give a notification saying "You do not own this trailer" or something like that

### Reason

Better Trailer Use

**Comment by coalaura** [comment]
Storage no, thats why we have storage containers. I don't want to give people the ability to store even more item in their cars. Vehicle trailer maybe, but you'd need an actual semi for it. The current trailers only have so many issues cause GTA is pretty ass when it comes to them.

**Comment by coalaura** [comment]
Although i believe you will encouter the exact same bugs with the flat trailer, but idm adding it

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/P40A2YOYKK.webp)

**Comment by SluggsV2** [comment]
Can we reopen this? what is the point of adding this, if can only tow one vehicle, there should be a tow 1 and tow 2 for 2 spots on the big flat bed, even if Tow 1 and Tow 2 are locked to the Trucker Job.

**Comment by coalaura** [comment]
> Can we reopen this? what is the point of adding this, if can only tow one vehicle, there should be a tow 1 and tow 2 for 2 spots on the big flat bed, even if Tow 1 and Tow 2 are locked to the Trucker Job. 

No, the point of adding it is that this one has no size restrictions compared to the regular trailer which can only move small vehicles
