### ISSUE TITLE
Suggestion -  Add Griddy Emote from Fortnite

### ISSUE THREAD

**Issue by cutep0ison** [InZidiuZ/op-framework-issue-tracker#3492]
### Assurance

I have read the `README.md`

### Summary

I propose adding a new emote called **griddy** from Fortnite. The community will probably welcome this well-liked emote and think it would be a fantastic addition to the server. It would be a useful addition to the emote collection and offer a lively and entertaining interaction between players.
[Reference-1](https://www.youtube.com/shorts/gkSTgJO8TJc) [Reference-2](https://www.youtube.com/watch?v=DgBcKPiKQ2o)

### Reason

Adding it to the emote library would be a great idea because it would allow for more dynamic and fun player-on-player communication.

**Comment by HollaYalla** [comment]
Yes I want to Griddy on cops after I down them all and maybe a L dance emote aswell???

**Comment by coalaura** [comment]
I aint smart enough to make custom animations so you would have to actually find the animation as a downloadable mod to suggest for us to add. This would then also be an [asset issue](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) most likely
