### ISSUE TITLE
Suggestion - command for picture takers! 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3493]
### Assurance

I have read the `README.md`

### Summary

we need a command for civs to take photos like in freecam! but not freecam! 

### Reason

i love taking photos from like 5 feet out and so do other civs that ive talked to, it makes the depth of the photos, just so much better and the quality just stands out, so a command like /pic or /snap maybe lets the user have a zoomed out angle, to take that great photo!

**Comment by coalaura** [comment]
Thats what /freecam is for which can be enabled for specific players

**Comment by SluggsV2** [comment]
Through command tho? Like will I have to /freecam (server id) everytime someone wants to take a photo?
