### ISSUE TITLE
Suggestion - Yellow Jack TV Menu / Garage Placement

### ISSUE THREAD

**Issue by MissPianist43** [InZidiuZ/op-framework-issue-tracker#3494]
### Assurance

I have read the `README.md`

### Summary

I know Yellow Jack is a landmine for no construction. BUT is there any possible way, we can put a tv in one of these four places to get a menu available? We currently have to put our menu on the ground, and with long lines, only one person can look at the notepad, and it takes so much time to get people served in a timely manner. Most bars and restuarants in our city has a TV menu. Our menu is placed near the front of the fridge (locker), and anywhere there would be ideal, but over the windows will work too. I was thinking the TV can be placed in front of the shelves or the previous menu to avoid doing any construction to the establishment. Please see provided photos. 

Also, we do need our garage moved from the current spot. Bikes and cars are always parked out front, which makes it near impossible to get our vehicles out when needed while people are blocking the spot.  Can we please have this moved to the side of the establishment or behind? This would make things so much easier on Yellow Jack employees!

Please contact me if you have any questions, or if I can be of more assistance. We always appreciate everything you do!

- Stella Jones, YJ Manager

### Reason

We currently have to put our menu on the ground, and with long lines, only one person can look at the notepad, and it takes so much time to get people served in a timely manner. Most bars and restuarants in our city has a TV menu. 

Also, we do need our garage moved from the current spot. Bikes and cars are always parked out front, which makes it near impossible to get our vehicles out when needed while people are blocking the spot.

**Comment by MissPianist43** [comment]
![TV ideas 2 (1)](https://github.com/user-attachments/assets/8ae97fe2-0276-4672-9ab9-32b9f6131888)
![TV ideas 2](https://github.com/user-attachments/assets/5466d432-5145-454d-baa8-5f0163daa234)
Forgot photos :)

**Comment by MissPianist43** [comment]
Photos of preferred Garage Placement! 
![Uploading Best Parking Spot (1).png…]()

**Comment by MissPianist43** [comment]
![Best Parking Spot](https://github.com/user-attachments/assets/bbe00d52-e844-428d-8a26-18554c63c485)
![Best Parking Spot (1)](https://github.com/user-attachments/assets/a925d307-83a3-4e71-ab52-365e14570b58)
Photos of preferred garage placement!

**Comment by DaxterPancake** [comment]
The trailer out back is a property that can be sold to someone in your gang that has a garage associated with it. Not sure if you guys knew.

**Comment by MissPianist43** [comment]
> The trailer out back is a property that can be sold to someone in your gang that has a garage associated with it. Not sure if you guys knew.

It is owned by a non - YJ employee/Non-Dreaded and he is not interested in selling or allowing us access.

**Comment by MADxxVIKING** [comment]
> The trailer out back is a property that can be sold to someone in your gang that has a garage associated with it. Not sure if you guys knew.

There is already a garage for Yellow - this is a request to relocate it. Owner has already RPed attempting to get the house before having the garage added previously. Location just gets blocked a lot. Nobody parks in the back so seems like a better option.

**Comment by DaxterPancake** [comment]
> > The trailer out back is a property that can be sold to someone in your gang that has a garage associated with it. Not sure if you guys knew.
> 
> There is already a garage for Yellow - this is a request to relocate it. Owner has already RPed attempting to get the house before having the garage added previously. Location just gets blocked a lot. Nobody parks in the back so seems like a better option.

I know what the request is about, I was just offering an alternative solution :)

**Comment by coalaura** [comment]
i will move the garage, however the TV is an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by MissPianist43** [comment]
> i will move the garage, however the TV is an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

Can I ask how when every other bar or food place in the city has one, and not us? We are already placing down a TV in front of the shelves, but want it to be permanent.

**Comment by coalaura** [comment]
cause it hasn't been suggested yet? idk i cant read minds really, like i said you have to suggest it in the asset repo @MissPianist43

**Comment by MissPianist43** [comment]
I just want to be sure, its my first time making business suggestions, and the link took me to a lot of threads so I was confused. Thank you!
