### ISSUE TITLE
Water not seen by Driver in any BCFD Vehicles. 

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/op-framework-issue-tracker#3495]
### Assurance

I have read the `README.md`

### Reporter

Astrozombiecat

### Summary

Drivers of BCFD vehicles with a water hose are unable to see water being sprayed which makes it difficult to put out fires.  The water spray can be seen by anyone and everyone outside of the driver seat but the driver can not see where they are aiming to put out a fire which is a hazard to anyone nearby. 

### Steps to Reproduce

Get fire truck , be in driver seat and activate hose.   You will not see anything or hear anything. the 

### Expected Behavior

While in the driver's seat of any hose-equipped fire vehicle, we should be able to see the water spraying from the hose to put out a fire. 

### Actual Results

No water can be seen by the driver, 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/inNEEDt1hrS_k-u1R/d1337eMouVZ1?invite=cr-MSwzaWMsMjUzMDkwNTE3LA

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
this would be an asset issue https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues
