### ISSUE TITLE
CPR alike command for PD

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3497]
### Assurance

I have read the `README.md`

### Summary

CPR alike command for PD /arrest

### Reason

Kinda Like CPR for EMS and Cops have Now, We were discussing maybe a /arrest command, could use it on locals maybe ones that just bought drugs off people selling, it take's the same amount of time if not a little longer to finish the command, maybe a pat down, question and arrest animation all tied into one, then you would be reward the item sold from player and 20-30$ the same as CPR Could add some great rp, makes us get items sold back, and could add another level, maybe one cop has to stay back well the other chases the suspect it could be really cool!

**Comment by coalaura** [comment]
no, dont think we need to arrest locals lol
