### ISSUE TITLE
Suggestion - Spanish Avenue Complex O Missing Garage

### ISSUE THREAD

**Issue by xplrerin** [InZidiuZ/op-framework-issue-tracker#3498]
### Assurance

I have read the `README.md`

### Summary

Hey! Discovered after buying the two apartment block Spanish Avenue Complex O that there was no garage with the block. This is incredibly annoying for tenants and there is no garage close to the properties either. The addition would be great for them.
![image](https://github.com/user-attachments/assets/6ca4313a-9228-478d-854c-7815f64bec46)
![image](https://github.com/user-attachments/assets/5bc0c0ce-fb15-4a95-9339-b831b0a9d10b)

### Reason

Every block has a private garage for that block, or specific houses. This is no different. As shown on the GPS it is quite the distance from the garage near Go Postal. This isn't ideal and when someone is paying rent for a property they should have the garage perk.

**Comment by coalaura** [comment]
is there a spot that would work as a garage? i don't want to just put a garage in the street or on the sidewalk

**Comment by xplrerin** [comment]
> is there a spot that would work as a garage? i don't want to just put a garage in the street or on the sidewalk

I've attached a couple options. I know this block isn't the best for parking because it is right onto the street but hopefully one of these spots helps!
![image](https://github.com/user-attachments/assets/ed21fdd6-3fad-436f-a085-2bb9464a34ca)
![image](https://github.com/user-attachments/assets/a1de5359-8efb-4b3b-b51e-3b9cda667e52)
