### ISSUE TITLE
Pay phones and Burner phones

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3501]
### Assurance

I have read the `README.md`

### Summary

Would add a good amount of RP I think

### Reason

Pay phones - 30 seconds per call (maybe a 5 or so min cool down after every call) , (free to use) can be used to call any phone number memorized or written down. Will help for when Nancy robs your phone, instead of running years or stealing a local call, I can get on the near pay phone and call my boy!  It would use say a random number assigned to each pay phone that way if PD has an investigation to do, they can track calls back. 

Burner Phone - Can be bought at electronic store, lets say 1 week break time, only used for calls and texts. Also can be tracked by FBI some how would be cool.

**Comment by coalaura** [comment]
#2551
#2286
