### ISSUE TITLE
Suggestion - Remove Thermite Crafting

### ISSUE THREAD

**Issue by Eyriiz** [InZidiuZ/op-framework-issue-tracker#3503]
### Assurance

I have read the `README.md`

### Summary

The ability to craft thermite should be removed because of its negative effect on what could be active roleplay. Before thermite crafting was a thing there was an active economy constructed through the trash job. This economy was ended along with any roleplay around it once its main commodity of thermite was able to be crafted.

### Reason

The removal of this feature would incentivize players to work more civilian jobs other than just trucking. Before thermite crafting was a thing a large hotspot for meeting people within the server was the Trash HQ. Here people actually interacted with other players constructing the trash economy for items solely obtained through trash. This was amazing for new players to meet people and progress their characters within the server. The trash job used to be many new players' first activity within the server because of its easy entry and its ability to take these items obtained through trash to work towards something bigger. With the ability introduced a couple years ago to craft thermite we’ve taken away trash running’s main item used for bargaining and selling to other players. With thermite crafting removed you would likely see more influx to people running trash as well as people collaborating together to create interactions previously seen at Trash HQ prior.

**Comment by ImArteria** [comment]
Only agree because I think it'll slow down the economy a bit. I.e less banks/stuff robbed due to no crafting and having to buy things.

**Comment by gadjinee** [comment]
But nothing stops you to craft it and sell it. It doesn't really slow down the economy, trash is becoming less and less popular, people prefer to do trucking job since it gives you more items as well as better payout 

All you see nowadays is people trucking

**Comment by coalaura** [comment]
Yeah, I don't think the crafting should be removed. It still takes a good bit of time and materials and the knowledge of where to go to craft it. I will buff the drop rates in other places a bit but i wont be removing its crafting at this time
