### ISSUE TITLE
Bug report - Oxy peds not appearing

### ISSUE THREAD

**Issue by Rohanx04** [InZidiuZ/op-framework-issue-tracker#3505]
### Assurance

I have read the `README.md`

### Reporter

rohanx4

### Summary

NPC of the prescription giver at sandy most of the times does not spawn the NPC after knocking and also did not give the prescription.

### Steps to Reproduce

Maybe Reconstruct the code at the sandy houses, this happened at 2 to 3 locations at sandy for various other people too

### Expected Behavior

Give prescriptions when interacted to know the door for prescription while collecting them before delivering.

### Actual Results

it should be giving prescription every time when we interact for the collection.

### Screenshots/Videos

https://i.imgur.com/FqWqCkm.png

### Game Resolution

resolution for completion of oxy

### Player Data

https://i.imgur.com/63ICbFE.png

### Server

India (c8s1.op-framework.com)

**Comment by MetaHatter** [comment]
@InZidiuZ updated this script recently.  May not be a bug.

**Comment by InZidiuZ** [comment]
It's not bugged, I tested it on prod servers as well, it's just different now. You have to wait for the peds to come out of the house & they may not come out at all if they call the cops.
