### ISSUE TITLE
Car tent prop

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3507]
### Assurance

I have read the `README.md`

### Summary

We have tents, but we don’t have car tents

### Reason

Can be used for pop up business or car tents, picture attached! And also prop that’s closest attached! 

Prop names already In game similar, 

cs1_11_tentcloth01c
cs1_11_tentcloth03c

![IMG_6978](https://github.com/user-attachments/assets/2c5d523e-a645-45e3-aff1-4ccc51b11247)

Would be awesome to have in city to rp with!!!

**Comment by coalaura** [comment]
This would require a custom prop for something i see not really a real use for. The props you mentioned cant be spawned ingame and also are not full tents ![yes](https://i.shrt.day/LZA1FECAZ7.webp)
