### ISSUE TITLE
Radio Update 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3508]
### Assurance

I have read the `README.md`

### Summary

Range effects how far you can talk to someone, break it into 5 sections or 4 and allow it break up between. could add alot of aspect into RP and would cause a change that everyone would have to get use to xD 

### Reason

Cooool RP!

**Comment by coalaura** [comment]
I don't think we need to limit radio reach. You can use things like radio jammers if you wish to restrict peoples ability to use the radio
