### ISSUE TITLE
Food with new Grill addition!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3509]
### Assurance

I have read the `README.md`

### Summary

New new food items that we could definitely use in different ways! 

### Reason

Just some food items that could be cool! 

Hot Dogs, Chicken Wings, Kebabs, pork chops, loaded baked potatoes, fish (when fishing comes)

**Comment by coalaura** [comment]
There is already a lot of things you can cook on a grill, i dont think we need to forcibly add more items just for the adding sake, if something comes up i will consider it

**Comment by SluggsV2** [comment]
I know this is closed, but can I please ask for Corn, corn seeds, into corn you gotta harvest into corn on the grill! Cmon everyone loves their corn!
