### ISSUE TITLE
Ford Raptor, Exclusive Car slow

### ISSUE THREAD

**Issue by Shifty123** [InZidiuZ/op-framework-issue-tracker#351]
**Reporter:**
Shifty#4167, Shifty

**Summary:**
I bought the Ford F150 Raptor in the Heroic imports for 50K and it seems to go much slower than it should. The Nissan Titan goes aroudn 170 and is an 8 seater when my truck is a 2 door and goes around 115-120 ish. I feel like this should go faster.

**Steps to Reproduce:**
Drive the F150

**Expected Results:**
The car goes fast

**Actual Results:**
It is very slow

**Comment by SATIN187** [comment]
That’s a Ford for ya

**Comment by Shifty123** [comment]
The raptor is fast af irl

**Comment by InZidiuZ** [comment]
Hey,

Wrong GitHub page. Use [this one](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

**InZidiuZ**
*OP-FW Devleoper*
