### ISSUE TITLE
Prop request, if possible!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3510]
### Assurance

I have read the `README.md`

### Summary

Some signs!

### Reason

No Trespassing Signs - Can be used on your property, for the home owners that don’t want people one their property! 

Some sort of pillow to place outside - With recent grill Update back yards will be used more some new type of furniture would be awesome! 

( https://www.ebay.ca/itm/185752619840 ) kinda like this! 

Inside the house furniture, 

 Trading Card Holder - Some where to show off your trading cards,
you would place it 1 for 1, each 1 gets 1 card, friends or family can walk up press E and inspect the trading card! Shows the card and what type and pack it’s from!

**Comment by coalaura** [comment]
> Some sort of pillow to place outside

there is a sleeping bag, a yoga mat, a towel and multiple differnt types of chairs. plenty of things to sit on :)

> No trespassing sign

these would have to constantly be re-placed with each server restart. Also most properties dont have the space for such a sign and the ones that do are usually already protected by a fence or similar
