### ISSUE TITLE
Suggestion - Smokable Cigars

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3511]
### Assurance

I have read the `README.md`

### Summary

Cool 2 new smokables, maybe at green wonderland or a new store!

### Reason

Some Civs brought up the idea? And thought it was an amazing idea aswell! Backwoods as papers too!

**Comment by coalaura** [comment]
we have bongs, vapes, edibles and joints to consume weed, don't think a blunt that does the exact same as all the other things is needed. I'd be down to maybe add cigars tho

**Comment by MADxxVIKING** [comment]
Blunt would be essentially same thing as a joint. 

Cigar on the other hand... Could be a cool addition to select gas stations? Maybe some effect like "lowers stress more than cigarettes, but also lowers small percentage of armor?" - just spit ballin here

**Comment by coalaura** [comment]
this has been done now
