### ISSUE TITLE
Some EMS Ideas

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3512]
### Assurance

I have read the `README.md`

### Summary

Just a few ideas regarding EMS and patients

### Reason

For starters, I believe there should be a cool down when you come out the hospital for switching back to another run / walk style, making your player remain “injuried” and not up to full recovery asap! 

Also cast, if your bones break or something maybe a cast goes on for a time frame, and then the player would have to go back at the end to get it “cut off”

I will add more when I think about it but those 2 dor startes would be fire 🔥

**Comment by TacticalTyl3r** [comment]
Honestly I dont like the first reason. If im just checking into the hospital for a checkup without going down and was walking fine going in. I shouldn't have to be forced to walk injured if I never was downed to begin with.

**Comment by SluggsV2** [comment]
Different circumstances would be different, checking in for just a little health maybe 30 seconds, checking in for nearly dead longer,

**Comment by Pixel-Nomad** [comment]
I have more ideas for EMS

**Eating Expired Items:**

- Players can consume expired food or drinks to reduce hunger or thirst.
- Consuming expired items can lead to illnesses with gradual effects.

**Illness Effects:**

- **Diarrhea:** Causes abnormal thirst level reduction.
- **Fever:** Results in health loss over time.
- **Headaches:** Increases stress level slightly (e.g., by 0.1).

**Role-Playing with EMS:**

- Players experiencing abnormal thirst, stress, or health issues can RP with EMS to get treatment.
- Vomit emote: Players can vomit after consuming expired items, reducing hunger level.

**Medical Interactions:**

- **Checkups:** EMS can perform checkups using a thermometer for fever and other medical conditions.
- **Blurred Vision:** A rare effect (1 in 100) where players experience blurred vision, leading to potential RP scenarios for eye surgery.

**Vision Correction:**

- Introduce an item like glasses with different power levels to correct vision.
- If the glasses are not in the player's possession, they experience blurred vision, prompting them to seek RP with EMS for corrective measures.

**Comment by SluggsV2** [comment]
the glasses idea is sickk. maybe over time eyes get worse in general and depedning on job it speeds or declines the progess

**Comment by Pixel-Nomad** [comment]
that was i meant cause dust can harm eyes garbage has dust mining has dust and a lot things has dust

**Comment by Dibbey** [comment]
Forcing people into the injured walk for any set duration **will** result in people complaining about it a lot. When I was still in EMS and the injured walk was introduced to the check-in, many newer players came up to us and asked us how to stop the "stupid" walk and many other names. Forcing it onto players for any duration will also disable any storytelling they want to do, such as what Tyler said, if I got shot in the shoulder why am I limping and forced to do so?

Entirely the same idea for casts, each player decides on their own if they broke their bones or not. This also already gets dealt with in-rp whenever EMS puts on RP-casts on characters and they come back to get it taken off.

I do like the idea of being able to eat and drink expired food and drinks, then having certain risks attached to them that CAN be treated better by EMS but overall fall off after some time, in cases when EMS and BCFD is not around.

The eyes idea also sounds interesting, but again I would not force it onto anyone, each player themself should be able to choose if they need glasses or not, and while I do think it could be a fun mechanic to play around with, I'm not sure how it would be feasible with the Outfits and Clothing side of it, as you'd have to wear the glasses and can't wear other glasses ontop of it.

**Comment by Pixel-Nomad** [comment]
we can convert glasses by lens you just only need have them on pocket or to avoid those get the surgery done by ems and as i said early about eating expired stuff and get ill you will get ill day by day not eventually you won't even notice but you still notice it out in some days

and for those who don't want to get treated we can introduce an rp for every job person to have medical checkup for every employee in 2 weeks if they are unfit they can suspend them from job...

i say there are so many rp's that will gonna get unlocked you will gonna have hard time to get medical certificate do the medicine first and get well then come again for certificates

**Comment by coalaura** [comment]
> For starters, I believe there should be a cool down when you come out the hospital for switching back to another run / walk style, making your player remain “injuried” and not up to full recovery asap!

No

> Also cast, if your bones break or something maybe a cast goes on for a time frame, and then the player would have to go back at the end to get it “cut off”

I am fairly sure there is a cast somewhere in clothing items allowing people to roleplay this way already if they want to.

> Eating Expired Items

I like the idea, would maybe give the antibiotics and painkillers some more use and could maybe add more pills and medications. I've made a new issue with that comment since the main points of this one wont be done or are already ingame
