### ISSUE TITLE
Suggestion - Ability for EMS to remove other players masks, glasses, etc.

### ISSUE THREAD

**Issue by Krish-021** [InZidiuZ/op-framework-issue-tracker#3513]
### Assurance

I have read the `README.md`

### Summary

 - Can we get some command or a way to use remove mask/clothes of a downed patient. I know i could be miss used so it could be done like this command only works when a player is downed rather than any time when someone use it for fun .
 - Also i would like to suggest to get some other emote like /e mechanic3 for /inspect  search which dont seems good as we are seeing for injuries in air while patient is down on the ground 
 something like this = https://litter.catbox.moe/60anl1.jpg

### Reason

 it wouldn’t be logical if we say “sir we are treating your friends face and applying Cream and basic first aid for injuries ” while he has his mask on and same with clothes like we say we are doing basic first aid while he have his shirt on .

**Comment by coalaura** [comment]
I've redone the /remove_glasses, etc. commands PD had and made one /remove_clothing command which takes "mask", "glasses", "hat" or "gloves" as the type for both PD and EMS
