### ISSUE TITLE
Suggestion - Add "Clear Path" option to garages

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3515]
### Assurance

I have read the `README.md`

### Summary

Add a menu option to public, job and private garages to clear the spawn point of blocking local vehicles.   

Ideally have a confirmation or require holding a key for a period of time to do it to prevent accidental removal.

### Reason

Currently local cars in the way are cleared when spawning in a vehicle but there is no way to clear one out of the way in order to store one.

- Removing the spots via map editing would necessitate streaming an excessive number of files.  
- Doing it regionally via script may remove cars unnecessarily and require a loop. 
- The menu option would give players the option of calling a tow if one is available.

**Comment by coalaura** [comment]
When pulling out vehicles it will already despawn any NPC vehicles (as long as they have not been used by a player)

**Comment by MetaHatter** [comment]
This was to address the inability to park a vehicle when a local is in the spawn spot when you arrive.

**Comment by antihero6713** [comment]
Some local cars have paths to park in drive ways as well

**Comment by coalaura** [comment]
I've solved this issue now. When selecting store vehicle it will now only consider owned vehicles and completely ignore any other vehicles that may be in the way
