### ISSUE TITLE
Suggestion - Group based jobs.

### ISSUE THREAD

**Issue by stutsy** [InZidiuZ/op-framework-issue-tracker#3516]
### Assurance

I have read the `README.md`

### Summary

I had an idea for group based jobs, for example. Jobs that require multiple people and you can do with your friends, and the more you do it with, the more money you get. 

### Reason

I feel like this would make it fun for more people who like to grind, and also itll bring other people together for do these jobs. I feel like itll be a good change

**Comment by MADxxVIKING** [comment]
I'm going to add some to this as I don't think it's a bad idea, but doesn't have an ideal for execution -

Group Jobs would be a Phone App - something where someone "starts group job", and other can "join group jobs" (this could be something like a randomly generated ID # those who want to join someone's job must enter) - Max amount of people on one job should be 4

Once 1-3 people have joined the "hosts" group job, the job would begin and have a time limit or objective to meet.

Group Jobs could be - 

**Trash** 
(2 people max - trash job extends to Sandy & Paleto or city based) Extended trash job unlike current trash work. Will be longer routes with more stops, and multiple areas. So 5-10 pick ups in city, then another 5-10 pickups in Sandy or Paleto. 

**Mining** 
(4 people max)
There would be a dedicated area above the query on the winding roads where you locate "ore veins" or "coal veins" only accessible during the job where you mine 30 ore (a lengthy time consuming task, let's say 30seconds per item obtained) then you turn into a NPC (site foreman) down by the entrance to the query. Tools required - a pickaxe which deteriorates upon use (same as weapons)

**Food Delivery** 
(2 people max)
This would be for food establishments that are not open (such as Cluckin Bell) where you walk up to the drive-thru, obtain an order, then deliver to a variety of locations all over the city. Distance varies payout. 

**Cayo Based Job**
(Ideal 4 People)
Some kind of harvesting job. Could be coconuts or chocolate from trees. 

Could also be some kind of "fix up" job where you go to different locations with buildings and "repair" the building bringing a hammer and saw, all it does is perform emotes on the given area - you visit 4-5 different locations to "fix things up" and each visit has 5-8 actions to perform that last 20-30 seconds each. 

Also could look into a "digging for treasure" thing where you dig up items, the items must be turned into the person requesting them (without turning in the items have no value). 


These are just ideas to maybe help give the idea some more vision.

**Comment by coalaura** [comment]
has already been suggested #2454

**Comment by stutsy** [comment]
yeah i like this a lot, me personally would do this a lot with people, adds to meeting new people and having more content and RP with different people everyday.Sent from my iPhoneOn 17 Aug 2024, at 1:03 AM, MADxxVIKING ***@***.***> wrote:﻿
I'm going to add some to this as I don't think it's a bad idea, but doesn't have an ideal for execution -
Group Jobs would be a Phone App - something where someone "starts group job", and other can "join group jobs" (this could be something like a randomly generated ID # those who want to join someone's job must enter) - Max amount of people on one job should be 4
Once 1-3 people have joined the "hosts" group job, the job would begin and have a time limit or objective to meet.
Group Jobs could be -
Trash
(2 people max - trash job extends to Sandy & Paleto or city based) Extended trash job unlike current trash work. Will be longer routes with more stops, and multiple areas. So 5-10 pick ups in city, then another 5-10 pickups in Sandy or Paleto.
Mining
(4 people max)
There would be a dedicated area above the query on the winding roads where you locate "ore veins" or "coal veins" only accessible during the job where you mine 30 ore (a lengthy time consuming task, let's say 30seconds per item obtained) then you turn into a NPC (site foreman) down by the entrance to the query. Tools required - a pickaxe which deteriorates upon use (same as weapons)
Food Delivery
(2 people max)
This would be for food establishments that are not open (such as Cluckin Bell) where you walk up to the drive-thru, obtain an order, then deliver to a variety of locations all over the city. Distance varies payout.
Cayo Based Job
(Ideal 4 People)
Some kind of harvesting job. Could be coconuts or chocolate from trees.
Could also be some kind of "fix up" job where you go to different locations with buildings and "repair" the building bringing a hammer and saw, all it does is perform emotes on the given area - you visit 4-5 different locations to "fix things up" and each visit has 5-8 actions to perform that last 20-30 seconds each.
Also could look into a "digging for treasure" thing where you dig up items, the items must be turned into the person requesting them (without turning in the items have no value).
These are just ideas to maybe help give the idea some more vision.
