### ISSUE TITLE
Suggestion - Extra low suspension

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3517]
### Assurance

I have read the `README.md`

### Summary

Slammed cars! 

### Reason

Is there a way to get suspension a tier or 2 lower for the people who love their slammed cars? Maybe only a few of the tuners / ricer cars, doesn’t have to be for everything like trucks or suvs

would be awesome to see!

**Comment by coalaura** [comment]
Some cars if you get the max suspension, they basically already touch the ground while other cars seem to be less affected by suspension upgrades. This would be very weird for a bunch of cars which would clip into the ground and stuff.
