### ISSUE TITLE
Suggestion - Ability for BCFD to remove vehicle doors

### ISSUE THREAD

**Issue by SammySandbags** [InZidiuZ/op-framework-issue-tracker#3519]
### Assurance

I have read the `README.md`

### Summary

Add a new command for members of the Fire Department, which will help and enable more Roleplay for them and help both EMS and PD for when people are stuck inside of cars.  

/Removedoor

### Reason

The command could be used to enable a door to be removed from a car, enabling the victims/Suspects inside the car to escape from the vehicle in a situation where they are stuck. 

A timer of 15-30 seconds while the Fire Fighter removes the door with a Sawzall or Jaws of life or a drill. An Animation would be great for this where they either use a Saw or a Drill to remove the Hinges from the car, If that is to much to code then Just a simple animation like the /inspect command from EMS would do. 

This should give BCFD a lot more Roleplay and interactions as currently if EMS is on duty they are lacking with the opportunity to get evolved on most medical scenes. when a person however is locked/stuck inside a car EMS currently Suspect out them though closed doors as there is no other way to deal with this.  

Removal of the doors from BCFD would be a great chance for them to be heavily evolved on most medical scenes.

**Comment by AlaricBenning** [comment]
i work for BCFD and i believe this will help with more RP in assisting EMS on calls and PD on calls

**Comment by coalaura** [comment]
I dont like having commands for everything. I think a better idea could be to maybe have it that if you use a drill or smth next to a car door you would go into a drill animation for a moment and then it would remove the door

**Comment by SammySandbags** [comment]
Honestly Laura that would work super well. and would assist with the RP. TY

**Comment by coalaura** [comment]
added the power saw to the ems and pd store, you can now remove vehicle doors when using it (only EMS (includes BCFD) and pd)

**Comment by AlaricBenning** [comment]
Thank you Laura for this
