### ISSUE TITLE
Owned vehicles behaving oddly

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-issue-tracker#352]
**Reporter:**
SkippingBaboon

**Summary:**
I have, and upon speaking to, numerous others, have been having problems since the recent reset, the one which happened a few hours after the reset that added the additional tuner chips, with our cars not behaving properly once moving out of render.

First noticed this when arriving back from using the plane for the supply drop. But happens in any situation, at random, if you move away from your vehicle.

You can still get in the vehicle, but when you start driving it has little acceleration compared to before, and the brakes also do not work. Its not even a slight performance drop, its very noticeable, the non braking function also is very noticeable as one would imagine. The handbrake still works though. If you come to a complete stop, the car then does not work at all, the engine revs but no movement.

The car that it happened personally with is a Mitsubishi Evolution X, but I have come across people with cars of all descriptions and the only common theme other than the above bug is that the cars are personally owned, not stolen.

**Steps to Reproduce:**
Taking car from garage, moving away from car, returning and attempting to use. Doesn't seem to happen every time, but has done on numerous occasions.

**Expected Results:**
Not sure what this means.

**Actual Results:**
Not sure what this means.

## Additional Information

**Screenshots:**

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 6923

**Notes:**
I believe all has been covered above.

**Comment by ZurxeyH** [comment]
This has been happening.

**Comment by InZidiuZ** [comment]
Hey,

Unable to replicate locally. Guessing a secondary client would be required. Not completely sure as to what would be causing this though, could *possibly* (most likely not) be a FiveM issue. Please do let me know if it's still happening though (as of the last 1-2 day(s)), but will close for now as I don't have a working repro, no video, nor any certainty as to whether this is still an issue or not.

I do have an idea as to what might be happening, but, I don't believe (as far as I can remember) I made any changes that would cause this to happen on the most recent updates.

**InZidiuZ**
*OP-FW Developer*

**Comment by Masik52** [comment]
This seemed to show up after the last update with vehicle damage changes. It happened last night to my C7 Corvette. It only seems to happen to custom vehicles.

**Comment by SkippingBaboon** [comment]
This is still happening with all of my Vehicles. It still seems to happen to most people I run into especially around the air strip. Yesterday I got back from doing a run with the plane, my bike was scuffed, so I reversed it from air strip 2 miles to nearest garage at 4mph -.- after taking motorcycle back out from garage, I then drove to the processing plant in Peletto, to come out of the facility with a non working motorcycle :/
