### ISSUE TITLE
Suggestion - Add Pet food to EMS store

### ISSUE THREAD

**Issue by battlea** [InZidiuZ/op-framework-issue-tracker#3521]
### Assurance

I have read the `README.md`

### Summary

I would like to be able to purchase the dog food, dog treats, cat food, and cat treats at the EMS store. Currently only available up at the Paleto pet store. I would like to have pet food more easily available for Veterinarians to give us something else to create interactions with animals and the fire departments dogs

### Reason

The Veterinary department has been getting a steady flow of appointments and it would be convenient to be able to give animals proper food when we do appointments. I also am trying to get the fire dept to bring in their dogs for check ups and teach them proper nutrition for their dogs. For vet appointments we typically use St. F and ocassionally Mt. Z. We dont have the proper equipment needed at Paleto hospital for Veterinary appointments. Next to Paleto Hospital is the pet store which is the only place I know of that sells pet food. If we could help supply pet food in the city it would give us another chance to have interactions with pet owners and hopefully supply the fire dept dogs with pet food.

**Comment by coalaura** [comment]
sure :)

**Comment by SammySandbags** [comment]
Hey Laura, 

The Food is not working for animal PEDs I think it might be missing the Animal PED Flag attached to the item. they just cant use it at all.
