### ISSUE TITLE
BCFD Panic Alarms 

### ISSUE THREAD

**Issue by SammySandbags** [InZidiuZ/op-framework-issue-tracker#3522]
### Assurance

I have read the `README.md`

### Summary

Can BCFD Panic alarms read "Firefighter Down" Not "Paramedic Down"

### Reason

When BCFD pull their Panic Alarms it states "PARAMEDIC DOWN". This can make confusion with PD. As they think its an EMS worker that has been downed, they will switch to the EMS Freq and ask us what happened and EMS wont know, we then have to explain its a Firefighter and then both EMS and PD will be on the BCFD Freq asking about the Panic alarm slowing down reaction times to help and assist with the downed firefighter. 

Thank you.

**Comment by coalaura** [comment]
sure :)

**Comment by SammySandbags** [comment]
TY
