### ISSUE TITLE
Suggestion - Yellow Jack Owner has no access under Business > Yellow Jack

### ISSUE THREAD

**Issue by MissPianist43** [InZidiuZ/op-framework-issue-tracker#3524]
### Assurance

I have read the `README.md`

### Summary

Our Owner, Heinrich, has no access to our employee garage and locker all of a sudden once our Roster and Business type was updated to Business > Yellow Jack > Bartender (as opposed to Bar & Club Bartender). Can we get an Owner (role) under the Business > Yellow Jack? I had entered a ticket in Discord to see about this, which I was directed here. They did update the entire roster for Yellow Jack in the previous Discord ticket mentioned, except for the Owner role. Thank you! 

### Reason

He had a LOT of vehicles in this garage, to which are essentially gone now. Is there a way we can get this updated or a workaround so he can get his vehicles back at the very least? Thank you!!!

**Comment by coalaura** [comment]
There is no way to make a workaround just for this. It was requested to change the job which will result in things like this changing. The garage should still be accessible, just under the new job. The "manager" position is supposed to be given to the owner.
