### ISSUE TITLE
Suggestion - Make the Wheelchair pickup-able

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3525]
### Assurance

I have read the `README.md`

### Summary

Add the ability for wheelchairs to be picked up and put in trunks like bicycles. 

### Reason

Increase EMS RP and also, it’s a bitch to roll up a hill

**Comment by PurpleHzea** [comment]
Would be cool if wheelchairs were physical items that can be placed into a players inventory

**Comment by coalaura** [comment]
would't make them items because of their sheer size but picking up like bicycles and even maybe let them be attached to the back of cars too idm

**Comment by coalaura** [comment]
lmaoooo

![yes](https://i.shrt.day/BI1IWVN94A.webp)
