### ISSUE TITLE
Suggestion - New scratch cards designs and a lottery store

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3526]
### Assurance

I have read the `README.md`

### Summary

Some new designs for em scratch cards! Maybe a car themed, sports theme, movie theme! And maybe a few stores (vine wood, sandy, paleto and Chumash) I could even maybe help with The design on the cards! 

### Reason

Lotto stores - just a simple lotto store, can hold the lotto tickets and scratch tickets, saying that it wouldn’t remove them from the variety store just a new store and maybe bring some extra Roasted Potatoes to those spots!

**Comment by coalaura** [comment]
I got the designs for the scratch card off some lottery site, didn't make them myself. If you want to make some sure, but my photoshop skillz aint good enough for that.

> Lotto stores

Do you have a specific place in mind?

Also, the "reason" field is fore the reason not for the idea, the idea would go into "Summary", reason would be WHY you think it should be added

**Comment by SluggsV2** [comment]
i can get some mock ups of new cards done, and send em over ill see what you think. and no real place in mind ill start looking around!

**Comment by coalaura** [comment]
I haven't really found a good spot to move them to, as i also want them to stay easily accessible. @ImArteria has already done an amazing job adding 2 new designs and i believe he is working on more :)
