### ISSUE TITLE
Wings!!

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3528]
### Assurance

I have read the `README.md`

### Summary

Chicken Wings! Please please please let us have wings!!! Citizens can buy chicken wings from bars and or cook them theirselves, finding a chicken, walking up to the chicken pressing “e” Will snap the neck, citizens can then pick up the chicken, players can then use a knife to cut the chicken, resulting in chicken breast, 2 legs 2 wings? 

### Reason

I have never met a person who doesn’t like wings, it would be awesome to see the new RP. Could even have the citizens drop off the chicken to different bars making it the only way they can sevre them!

**Comment by coalaura** [comment]
You can get chicken nuggets from burgershot. Idk if we need another chicken food for now
