### ISSUE TITLE
Bug report - Unable to open Inventory & then crash

### ISSUE THREAD

**Issue by Manmohan-zanwar** [InZidiuZ/op-framework-issue-tracker#3531]
### Assurance

I have read the `README.md`

### Reporter

.rexdev & aadarsh0001

### Summary

So yesterday, i.e., 28/08/2024, I was playing in Legacy Roleplay India. I was facing this issue again and again.As soon as I tried to open my inventory, my game used to crash without any internet or PL issue.
![FiveM_b3095_GTAProcess_xbE5p70AtZ](https://github.com/user-attachments/assets/22a52de2-08cd-4075-8b24-ee59e4a995fa)

### Steps to Reproduce

This issue need to to be resolved as soon as possible as i am unaware about the current amount of player facing this issue.

### Expected Behavior

Expected behavior should be responsiveness of the Inventory and game shouldn't crash.

### Actual Results

![FiveM_b3095_GTAProcess_xbE5p70AtZ](https://github.com/user-attachments/assets/016791b3-efc4-4ee7-87ac-49e70eda0898)

### Game Resolution

1920*1080

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
You seem to be the only one facing this issue. From the logs in the screenshot it seems like things are timing out so considering you are the only one with this issue atm, i'd believe it may be something with your internet or ISP
