### ISSUE TITLE
Suggestion - Risk to milking cows

### ISSUE THREAD

**Issue by emeraldenraged** [InZidiuZ/op-framework-issue-tracker#3533]
### Assurance

I have read the `README.md`

### Summary

This is just a small & silly idea so no sweat if this is the dumbest thing you've read & have no interest in:

There should be a risk to milking a cow. Let me explain my thought process here:

We can now punch sharks & there are more sharks in general in the water to affect people doing diving or other water based activities. 
Statistically, cows kill more people than sharks. 
By milking a cow, you run a risk of getting kicked. To avoid being kicked, there's a specific approach to milking the cow. Don't run up on it, or try to milk it from behind. In the event those things aren't followed, there's a however many percent chance the cow will "kick you" and possibly down you. Obviously if that's too complicated to implement, just in general a however many percent chance of it happening. 
This doesn't necessarily need an animation as well. Perhaps just the cow moos really weird or something. I don't know how putting these things into motion work. 

### Reason

My thoughts behind this are that it would encourage pairs of people to go milk cows, it could also add a risk to stealing a cow if wanted, and hell, you could make punching a cow/milking a cow a daily even. While it is annoying to try to get the dang cows to stop walking so you can milk them, it's overall easy and risk free. I think adding some sort of risk could also make it a *little* fun, and considering cows are relatively based in Blaine County area, could potentially provide more things "in district" for BCFD.

**Comment by emeraldenraged** [comment]
I meant to say milking a cow a daily, not punching a cow but like... either works lol

**Comment by AlaricBenning** [comment]
i would also think this is a great idea to add into the server.

**Comment by emeraldenraged** [comment]
Adding this as a comment vs editing message here: 
There could be a pop up message of "the cow was displeased" "you have angered the cow".
Or when the cow walks away middle of being milked, "Warning! Do not upset the cow!" Or any number of ways of wording to let them know why they went down. I'm trying to think of ways to help give reason why they got knocked in regards to no animation available. I'll think over it some more with some friends, maybe, but I wanted to put the idea out there.

**Comment by coalaura** [comment]
> There should be a risk to milking a cow

I really don't think there has to be, people already barely do it so this would just make people want to do it even less. There is already a slight risk that the cow will walk off and you have to start over again but i don't see a need to make it more difficult or risky
