### ISSUE TITLE
Suggestion - Cap/lower shouting volume in cars

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3534]
### Assurance

I have read the `README.md`

### Summary

Now that the emergency PAs are a thing (and radios/phones always have been), yelling at full range from cars seems odd. There would be some type of occlusion.

Propose adjustments to cap speaking range while in a vehicle:
Shouting = Normal Speaking Range
Normal = Normal Range
Whisper = Whisper Range

### Reason

Just makes sense for RP and might incentivize people to get out of their car to socialize/interact. 

Would also prevent people from overhearing plans from a car going 100mph 3 car lengths in front of them just because someone forgot to hit Y.

**Comment by coalaura** [comment]
i like the ability to shout in cars and you CAN change your volume to whisper and only the people in the car will hear. Think of it as having your window down, yelling out of it.
