### ISSUE TITLE
Suggestion - Pizza This and That

### ISSUE THREAD

**Issue by Z3KE337** [InZidiuZ/op-framework-issue-tracker#3535]
### Assurance

I have read the `README.md`

### Summary

To improve the experience at Pizza This, I suggest adding an employee-only garage to streamline staff operations and reduce crafting time, as making a pizza currently takes too long, causing frustration among customers who prefer takeout. Additionally, it would be beneficial to add a food item or modify an existing one to reduce stress, as customers are moving toward other establishments like Bean Machine and Burger Shot for this reason, leading to a decline in restaurant RP for Pizza This. I've also seen a great idea on Discord about replacing NPC delivery with a cleaning task for employees to earn extra cash, which I hope to see implemented soon. Overall, these changes would significantly enhance the gameplay and make Pizza This a more attractive destination for players.

### Reason

It can significantly enhance the user experience and overall engagement. By adding an employee-only garage, we can streamline staff operations and make it easier for employees to manage their tasks. These changes would make Pizza This a more dynamic and appealing part of the framework, benefiting both players and the community as a whole.

**Comment by coalaura** [comment]
> employee-only garage
> reduce crafting time
> modify an existing one to reduce stress

All done

> replacing NPC delivery with a cleaning task for employees to earn extra cash
similar to #3065

**Comment by Z3KE337** [comment]
Another suggestion: Is it possible to make the trash bins within the Pizza This restaurant usable? Since they are not usable at the moment, people tend to throw garbage randomly everywhere.

![trash 2](https://github.com/user-attachments/assets/d5a6c93f-407f-4546-b010-1dcabd7d1f8a)
![trash](https://github.com/user-attachments/assets/973b8659-b0c2-4043-bbac-9a4e63102fa0)

**Comment by MEOWkasan** [comment]
its high time pizza this gets a task system. its getting very boring while other business gets to do Local delivery. Other co workers are also complaining.
