### ISSUE TITLE
Suggestion - See Transaction History on /comp

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3536]
### Assurance

I have read the `README.md`

### Summary

Be able to see who is withdrawing / depositing money in realtor comp accounts; similar to how it works in savings accounts

### Reason

A small QOL adjustment since co-owners can also manage the funds in this account as well as owners

**Comment by coalaura** [comment]
hmmmmm, is this really needed?

**Comment by CloudCait** [comment]
What if one day a co-owner decides to take money without the owner's permission and you have no way of knowing because you'd just assume the missing money is from a block payment; idk just thought it would be a good way for realtors to track their money in the comp account

**Comment by coalaura** [comment]
thats a fair point

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/9JAAW8IH0E.webp)

**Comment by CloudCait** [comment]
Another common Laura W, thank youuu!
