### ISSUE TITLE
Suggestion - Move the Paleto EMS Heli Spawn

### ISSUE THREAD

**Issue by SammySandbags** [InZidiuZ/op-framework-issue-tracker#3537]
### Assurance

I have read the `README.md`

### Summary

Can you move the EMS Heli Spawn from the back of the hospital onto the Helipad next to the hospital please. 

Also can the Sea rescue Helicopter for EMS be added to this spawn point. 

### Reason

When pulling out the Airbus helicopter at the Paleto Bay EMS Heli Spawn you are not able to use it as the blades are so big that they are inside the hospital. 

PSB Link to a video with the problem. 

https://medal.tv/games/gta-v/clips/iBUXH68Ji0eehwllX/d1337JAyIoXE?invite=cr-MSw4MUYsMjA0Mzc2MDEzLA

Although it looks like the blades are clipping though the wall if I was to try and take off they would hit the building making it a very very dangerous take off. 

Many thanks

**Comment by coalaura** [comment]
done

**Comment by SammySandbags** [comment]
TYVM
