### ISSUE TITLE
Suggestion - Mini Game Alterations

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3539]
### Assurance

I have read the `README.md`

### Summary

House Lockpicking: I feel like this should only be for expensive houses such as mansions as these would typically have more advanced security systems

Car Lockpicking: This should be for civ cars and/or expensive local cars not just all cars as a whole

Also I feel like the colour blind community *coughs* eyrii *coughs* might struggle with the minigame that is on the house lockpick 

### Reason

Having these mini games for local cars and cheaper houses seem very anti-new player as cleaning houses and stealing local cars is something we see newer players do a lot as they're just starting out and they're typically easy tasks to make money/get places. OPFW is very good for new roleplayers as its beginner friendly and I feel like adding these minigames for easy tasks for players who are just starting out will make them struggle / deter them. 

Having the car lockpicking minigame for civ cars and making it a bit more difficult can also deter the issue we see where lots of new players will just steal people's cars for no reason other than ooo shiny car i want.

**Comment by coalaura** [comment]
> House Lockpicking

I like the variety of not just "use lockpick to enter" but having a small minigame. The difficulty of the minigame is incredibly easy in this scenario (even i managed with plenty of time left to do it and i suck at these).

> Car lockpicking

Again, i don't like just pressing a button and waiting, the occasional minigame makes it a lot more interesting and engaging. Here the minigame is also again, VERY easy to do and gets easier the better your tools are. I increased the difficulty for player owned cars now to make it not aaas simple to do, however thats what the alert system is for.

> colour blind community might struggle

I believe the colors are far enough apart from each other to be distinguishable by color blind people. If however someone who is color blind can tell me different i'd be happy to work on a solution :)
