### ISSUE TITLE
Car Spawns

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-issue-tracker#354]
**Reporter:**
SkippingBaboon

**Summary:**
There are still areas where local controlled cars spawn out the floor.
Most of these locations seem to be within the city. What with how costly repairs are getting, and hospital bills if you are on a motorcycle, I feel more could maybe be done to prevent these spawns, as they were not a problem before the big reset.

The incident that caused me to bug report occurred when I took my vehicle from my garage at 100% body, 100% engine, drove out the car park at 15mph, moment I touched the road, local car spawned underneath me, had to replace all windows but one, and engine was black smoke. Cost me 3 scrap 2 steel for engine. 2 scrap for body. 5 glass for window, bringing it to a total of $700 all from simply driving my car out the car park onto the road, below speed limit.

**Steps to Reproduce:**
Drive around the city for 10 minutes will probably happen at least once.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920 x 1080

**Player Data:**
ID: 6923

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This is a FiveM problem, not a OP-FW one.

**InZidiuZ**
*OP-FW Devleoper*
