### ISSUE TITLE
Bait Cars 

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3540]
### Assurance

I have read the `README.md`

### Summary

Concept: The /baitcar command lets officers turn any vehicle into a bait car, designed to catch car thieves in the act.

How It Works:
Setup: An officer selects a vehicle and types /baitcar, making it appear normal but with hidden tracking.
Trigger: When someone hotwires the car, the PD gets a silent alert with the car’s location via a tracker.
3-Minute Timer: The thief can drive away, but after 3 minutes, the car shuts off and locks the doors, trapping the thief.
Roleplay: This system allows for strategic sting operations and adds tension to car theft scenarios.

Additional Features: Officers can manually shut off the car early if needed, and the bait car could emit a warning just before it shuts down.

This system enhances police roleplay and adds a new dynamic to car theft in OPFW.

### Reason

It will add another type of RP for Cops and Criminals! introducing Bait Cars i was thinking of having them EDM cars that only can be pulled out so often!

**Comment by coalaura** [comment]
There are vehicle trackers in the FIB store that allow you to do this basically.
