### ISSUE TITLE
Hunting shotgun

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3541]
### Assurance

I have read the `README.md`

### Summary

A hunting shot gun (just like the hunting rifle, deals no real damage to players and only animals) this would be used for birds and bunnies, making hunting less repetitive and more animals to hunt! 

You could even go one step further making the rabbits eatable and cookable on the grill! 

### Reason

Minor change to hunting!

**Comment by coalaura** [comment]
You can already get yourself a registered shotgun by acquiring a weapons license. It does damage to players too but i see no reason why you cant use it to hunt
