### ISSUE TITLE
Bug report - /sit does not work 

### ISSUE THREAD

**Issue by Z3KE337** [InZidiuZ/op-framework-issue-tracker#3542]
### Reporter

zekesenpai

### Summary

The /sit command stops working after a player uses it once on the same chair, and even after reconnecting, the issue repeats, allowing the command to be used only once before it fails again. The trash cans inside the Pizza This restaurant are currently unusable, leading players to throw garbage randomly around the restaurant.

(file is to long that's why giving a link) video link: https://youtu.be/9fA_bDgTgJw

### Screenshots/Videos

![Desktop Screenshot 2024 09 06 - 14 46 46 39](https://github.com/user-attachments/assets/fdc11a44-281f-4ef9-b3dd-fdce6587f25a)
![Desktop Screenshot 2024 09 06 - 14 46 46 39](https://github.com/user-attachments/assets/0fcbff78-9de1-4b99-9500-d8ec036dea9f)

### Note

These issues are affecting the restaurant's cleanliness and functionality and addressing them would significantly improve the user experience.

**Comment by coalaura** [comment]
fixed
