### ISSUE TITLE
Suggestion - Add BCFD Logout spot in rockford hq

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/op-framework-issue-tracker#3543]
### Name

Astrozombiecat

### Summary

With the move from Sandy Fire Station to Rockford Station as the main HQ for BCFD, we want to encourage members to use the quarters area when they are finished with their shift and to promote more RP within the station while not on duty. We are requesting the logout point be moved from Sandy to Rockford.  

### Reason

Logout Point in the Bunk Room:
To enhance convenience and realism, we suggest the implementation of a logout point within the sleeping quarters. This will allow firefighters to log out directly from their sleeping quarters, replicating the process of getting rest after a shift.

We understand as we were told that only one logout point is needed for BCFD, so we are requesting that the Logout Point be moved from Sandy station and moved to the Rockford HQ, possibly somewhere around the area of the photo attached. 

![Medal_deY85Uo5Zx](https://github.com/user-attachments/assets/865737e5-7471-43f6-b772-031250572b41)

**Comment by coalaura** [comment]
added a logout spot in the last bed on the right and also a spawn spot at the chair at the end so you can fly into rockford fd directly
