### ISSUE TITLE
Suggestion - Boosting Hack Changes

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3545]
### Assurance

I have read the `README.md`

### Summary

Can we increase the time for the boosting hack or add letters more spread out on the keyboard? 

### Reason

There's not enough time to do this hack for your average joe and all the letters being on the left hand side of the keyboard is super difficult. I understand that there have been 'skill checks' implemented to certain activities but I think this hack just needs a couple tweaks.

This isn't just a me skill issue, my group love doing boosting and are usually really good with hacks but only one of them can actually do this hack. Really puts us off wanting to do a boost that requires hacking now.

**Comment by PurpleHzea** [comment]
Hacking should not be for everyone, and should be difficult IMO. Every hack there is now takes a few tries to learn, but ultimately  pretty easy to get the hang of. Plus if someone cant do the the hacks it forces them to outsource for help.

**Comment by CloudCait** [comment]
I’m not saying make them extremely easy and people should get them first try. I’m giving feedback as part of a group who regularly boosts but can’t anymore because the hack is too difficult. This hack does not get easier the more you get the hang of it. Either you can move your fingers quickly or you can’t, that’s nothing to do with skill.

**Comment by InZidiuZ** [comment]
I've made it a little easier now. Though it's still somewhat difficult as it should be. The time limit has been increased from 7 seconds to 9 seconds.
