### ISSUE TITLE
New Phone App - Yellow Pages

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3547]
### Assurance

I have read the `README.md`

### Summary

Creation of new Phone App - Yellow Pages.

**Function:**
Serves as a place where ANY Buying/Selling Ads should be posted. In addition for businesses to post "Open/Closed" Ads. We could limit posts to 1hr cooldown. In Yellow Pages, OP can delete their own "Ad".

This also could also technically be the new home of the Mechanic Shop listings where you can tell if they are open - In addition, if it was possible and seen as a generally good idea, we could add Food Establishments to the function where if they are on property, it lights up automatically without an ad needing to be spammed. This also could include things like PDM, GW, Midnight..

Also would be used for Realtor Ads, and other creative businesses people may have come up with without an actual whitelisted business.

**Use Examples:**

- "Buying Mats at Hayes - Contact Number"
- "Selling PDM Rumpo - Call me @ 111-1111"
- "Taco Truck at Bazaar for next hour!"
- "BurgerShot Delivery for Next 2hrs - Call our line!"

**ADs:**

We could still have ads, however like Spam Texts, these could be random on Myspace and pre-created by a dev. 5-10 that randomly post throughout the day. Could even be used for small hints at new features (like the skateboards when they dropped, LSIA renovation, Mt. Z ad, etc). This would feel more like an actual social media platforms natural ads. Almost "ambient ads".

### Reason

Suggestion #2192  has a Yellow Pages suggestion, however I wanted to go more in depth -

Myspace App (Formerly X/Twitter) is a place for communication of all sorts currently. However I believe this app could be used for more meaningful RP than the spam of "Buying/Selling Car", "This Place Open" followed by 6 tweets if its opened.. Refocusing on actual posts of thoughts, pictures, and general RP social media stuff like Invites to a wedding, event, or getting a group together to go bar hopping would help make Myspace more fun.

If we separated the Ads from Social Media RP, it would be beneficial for those focused on buying/selling something to have a dedicated place people go to. And for those who want to have the casual social media rp to be on MySpace.

Yellow Pages has been long requested, and I believe as more things are flowing into the city, this would be an amazing new feature/QOL the community is looking for. I do understand this a big ask due to coding and the way the current phone system is set up (at least mentioned in 2022), but would be a wonderful thing to move towards.

**Comment by Dibbey** [comment]
I agree that this is strongly needed for the current state that the "social media RP" is in. It's repetitive "Selling XYZ car" tweets multiple times in a row, followed by "Business open?" / "mechs?" / "Any food?", then the occasional actual useful ad of a business being open or closing. But all of them clog up the timeline next to when people rant, argue, post pictures etc., making it harder to actually see when businesses open or find what you are looking for.

Having a separate app JUST for those ads where they don't disappear after a certain amount of them being posted, but rather being able to see them all and they can either be deleted by the poster themselves or after a set time of 2-3 hours or so, would massively free up MySpace to be used like a social media platform and further tweets could just be directed to the yellow pages.

**Comment by coalaura** [comment]
#2192 #2658
