### ISSUE TITLE
Suggestion - Custom Panic Buttons For PD/EMS

### ISSUE THREAD

**Issue by TROWER-MF** [InZidiuZ/op-framework-issue-tracker#3548]
### Assurance

I have read the `README.md`

### Summary

With the panic button make it so you can change it like the Radio, This would be nice to have some customisation, 

### Reason

This would be nice for the user, This would obs have the same pros and cons as having the custom radio clicks

**Comment by coalaura** [comment]
why do you need custom panic button sounds

**Comment by coalaura** [comment]
the panic button plays for everyone around you too, so custom sounds wont really work for it
