### ISSUE TITLE
Suggestion - [New Baton] for PD 

### ISSUE THREAD

**Issue by Mugdha57** [InZidiuZ/op-framework-issue-tracker#3549]
### Assurance

I have read the `README.md`

### Summary

I would like to suggest the addition of a new PD baton for law enforcement officers in the server [Especially for our Legacy Bangladesh Subdivision]. This item would serve as a non-lethal alternative for controlling suspects during police encounters, improving roleplay dynamics in non-lethal situations.

Baton - https://www.youtube.com/watch?v=KruDQpHuro4 | https://www.gta5-mods.com/weapons/asp-baton

Baton Features
1. Non-lethal weapon: Deals minimal damage and is designed to subdue suspects without using lethal force.
2. Knockdown Mechanic: When a player is hit with the baton, they are knocked down for a few seconds, allowing officers to cuff 
them.
3. Cuffing Interaction: Officers can cuff suspects during the knockdown period, adding a tactical element to gameplay.
4. Self-Recovery: After a few seconds (e.g., 5–10 seconds), the knocked-down suspect can stand up if they are not cuffed.
5. Cooldown: There will be a short cooldown between baton strikes to prevent abuse.
6. Sound Effects and Animations: Include unique baton strike animations and sounds for enhanced realism.

Baton Benefits
1. Non-lethal control: Encourages officers to use non-lethal means in arrest situations, reducing the need for more aggressive force.
2. Enhanced roleplay: Improves realism and adds tactical depth, requiring officers to use timing and coordination to successfully subdue and arrest suspects.
3. Balanced encounters: Gives suspects a chance to escape or resist if not quickly cuffed, keeping the RP engaging for all players.
4. Realistic police procedures: Reflects actual police procedures where officers use non-lethal force and restraint tools like batons and handcuffs.

### Reason

The current PD Nightstick is too OP, 1 shot fully down. 

The main goal of this suggestion is to add a new baton or nerf the current PD nightstick so that when used, players get knocked out rather than fully down. Example - https://files.catbox.moe/8wpzbj.png

**Comment by coalaura** [comment]
done now
