### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by WiredWifi** [InZidiuZ/op-framework-issue-tracker#355]
**Reporter:**
Who is reporting this?  WiredWifi #8614, WirelessEthernet

**Summary:**
Write a short summary of what you're experiencing.
Only one of my characters are saving when I relog. I go to create a new character and all is fine until I leave the game and rejoin and the character slot says empty. Have the same problem for 3/4 of the slots.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
There is no fix that I know of so hopefully you can resolve this issue.

**Expected Results:**
What are the expected results?
When I go onto Legacy my characters will still be there so I can have multiple to RP as.

**Actual Results:**
What are the actual results?
Currently when I go on Legacy only one of my characters are there and the rest haven't saved.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![image](https://user-images.githubusercontent.com/53901532/62699429-68457380-b9d7-11e9-8b84-c8199016cea0.png)
![image](https://user-images.githubusercontent.com/53901532/62699400-582d9400-b9d7-11e9-9227-9e0b8e74dfb2.png)

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
ID: 5682
**Notes:**
For anything else noteworthy.
Nothing else worthy.

**Comment by InZidiuZ** [comment]
Hey,

I've resolved the issue for you. Your user should be all good now. I believe the bug causing this was fixed a while back, but if your user had already been bugged it'd remain like that until I fixed it.

**InZidiuZ**
*OP-FW Devleoper*
