### ISSUE TITLE
Suggestion - Restaurant Balance

### ISSUE THREAD

**Issue by MEOWkasan** [InZidiuZ/op-framework-issue-tracker#3551]
### Assurance

I have read the `README.md`

### Summary

Currently, restaurants like Burger Shot and Bean Machine have local delivery systems, while other businesses do not. This creates an imbalance where employees tend to leave other restaurant jobs after a while to grind money from these establishments through NPC deliveries. This system also causes employees to be less active during peak times, making it difficult for customers to buy food. To address this, I suggest removing the local delivery system entirely from all restaurants and introducing a task-based system similar to EMS, with a normal payout during low payer count and High during server Peak time. This would encourage more active participation during peak times and create a fairer, more engaging environment for all businesses.

### Reason

I think this suggestion would create a more balanced and fair economy across all restaurants, ensuring that employees remain active during peak times and enhancing player-to-player interaction. By removing the local delivery system and replacing it with a task-based system, it would encourage more engagement and improve the overall gameplay experience for everyone involved.

**Comment by coalaura** [comment]
So, i want to get away from local deliveries as they encourage staff to not be at the business which is the opposite of what we want. I've been working and testing a new tasks system that randomly creates things to do inside the business and give a small reward to the player for doing the task. I'm planning on removing local deliveries from BS and BM and add these tasks to restaurants and bars to encourage staff to stay in their businesses so customers can interact with them

**Comment by coalaura** [comment]
EMS is basically me testing it for a while to see what needs changing/balancing and then i will create a bunch of tasks for all other restaurant businesses and bars :)

**Comment by CloudCait** [comment]
> So, i want to get away from local deliveries as they encourage staff to not be at the business which is the opposite of what we want. I've been working and testing a new tasks system that randomly creates things to do inside the business and give a small reward to the player for doing the task. I'm planning on removing local deliveries from BS and BM and add these tasks to restaurants and bars to encourage staff to stay in their businesses so customers can interact with them

I know this is a github for restaurants but if possible could we include this for other businesses like midnight and pdm? Since most employees will only be at the business when they get a tweet requesting them to be there

**Comment by coalaura** [comment]
yeah its planned for all businesses that require their staff to be in the business

**Comment by SammySandbags** [comment]
> EMS is basically me testing it for a while to see what needs changing/balancing and then i will create a bunch of tasks for all other restaurant businesses and bars :)

Its working well in Mount Z, I have done a few but currently Super busy so not had chance to full grind the hell out of it while on duty. I think you have fixed the broken tasks that were there, its now to see if its OP or not. :)

**Comment by Z3KE337** [comment]
As 

> > EMS is basically me testing it for a while to see what needs changing/balancing and then i will create a bunch of tasks for all other restaurant businesses and bars :)
> 
> Its working well in Mount Z, I have done a few but currently Super busy so not had chance to full grind the hell out of it while on duty. I think you have fixed the broken tasks that were there, its now to see if its OP or not. :)

I have Been Testing it and It works Perfectly fine. The only issue I see is The task gives Items that are mainly Food which takes up a lot of  Inventory space. Most of the people either throw those Iteams or Give it away.  Making a balance between Giving Iteams and Cash PROLLY needs to be fixed.
