### ISSUE TITLE
Suggestion - Licenses at City Hall

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/op-framework-issue-tracker#3552]
### Assurance

I have read the `README.md`

### Summary

Now that the new City Hall has been around for a while and has working locks etc., I would like to suggest the moving of the License "shop" that is currently positioned at the old Courthouse to the City Hall reception desk in the main hall.

### Reason

Here are some reasons as to why I think the moving would be a good idea:
- State would be able to meet up with people and utilize the offices for more in-depth interviews and conversations regarding the licenses then direct them to the reception counter for the licenses all in the same building. With the current courthouse, we stand outside because there are no offices or much space.
- People who lose licenses from airlifting or whatever can run over to the City Hall from Mount Zonah and acquire a new printed ID without having to drive or run to the old courthouse.
- The same goes for physical IDs for individuals at Rockford PD or so.

**Comment by coalaura** [comment]
They are mainly there because its central and easy to find for new players

**Comment by MetaHatter** [comment]
I like the idea of the State approved licenses being available at the state building but agree with Laura that the new players REALLY should go to where they are?

Can't they be sold in both places?  IRL there's multiple offices to get state documents.

**Comment by coalaura** [comment]
yeah idm adding a second location to the store, do you have a specific spot in the new courthouse in mind?

**Comment by MetaHatter** [comment]
I would think the desk in the lobby makes the most sense to me.

**Comment by Dibbey** [comment]
I didn't even think of asking for a 2nd location, but that works too. I just thought utilizing the City Hall and its offices makes sense for the licenses allowing us to actually do some proper paperwork RP and bring people into offices to discuss the licenses etc. rather than standing on the steps of the old courthouse building by the bazaar.
But yea, the main desk when you walk into the lobby would be perfect for another license shop.
