### ISSUE TITLE
Suggestion - Addition of new Secondary Job system

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3555]
### Assurance

I have read the `README.md`

### Summary

Add a new system called Secondary Job which contains some selected jobs.

### Command
The command can be **/secondary_job** which will work the same as the Job UI.

### Permissions
The person will get access to door locks, store, private locker, private garage, commands (if any), and outfit change option.

### Paycheck
For the secondary job, there will be no payout. The person will only recieve the paycheck from the primary job.

### List of jobs
**1. Primary Job**
- All jobs

**2. Secondary Job**
- Bar and Club (Optional)
- Comedy Club
- Bahama Mamas
- Tequi-la-la
- Vanilla Unicorn
- Yellow Jack Inn
- Madrazo Cartel
- Peaky Blinders
- Vintner
- Cinema
- LSUV
- Los Santos Aviation
- Law (Optional)

I have included the jobs as secondary which are dependent on roleplay. Any job that has good income and not suitable as a side job are considered as Primary Jobs.

### About Optional Secondary Job
- **Bar and Club:** The only reason to add this job is because of Paleto Hen House. It has the same store like other bar but doesn't have a specific key (ex: Bahama Mamas, Tequi-la-la)

- **Law:** Many people do the lawyer as a part-time job. Adding this as secondary job will allow them to access the office when needed.

- **LSUV:** The main server has a large number of player base and they haven't got a wipe in years. So, they have a very good number of used vehicles to sell. As for the sub-division, the numbers are very small. So, adding the LSUV will benefit the small subdivisions.

### Reason

Most of the people aren't interested in these secondary jobs because of the low earning. For them, it's more beneficial to do the Life Invader jobs instead of these.

For this reason, these business goes vacant throughout the whole year in sub-division. I am not sure about the current condition in the main server, but I once looked at the public roaster and most of them were vacant.

Occasionally, people take these business for specific reason and some days later they become inactive. Even if someone takes these jobs, they use a second character which is mostly inactive and people don't find them when needed.

As a citizen, people would want the services available most of the time. And it's very normal in real life to do a part-time job like bar and restaurant beside the main job.

In addition, it is very logical for a businessman to own a bar/club. For example, the PDM boss might want to own a bar. But in our server you need to switch the job to have the access.

If you add the secondary job option, I am sure many people will be interested in all the sub-division to own a bar/business as it will allow them to keep their primary job. Also, many people will join the job with their main character which will eradicate the inactivity problem.

This addition will bring opportunity in these businesses and make them more lively,

I hope I was able to demonstrate the idea, and wish people will get the benefit from this addition.

**Comment by coalaura** [comment]
This would not work with our current job system and is not how the job system is intended to work. Businesses being vacant is a problem that should be dealt with by the managers/owners of those businesses. In addition, there will soon also be tasks for people to do in businesses, encouraging them to stay there
