### ISSUE TITLE
Suggestion - Addon in Doj Building 

### ISSUE THREAD

**Issue by 07ashishdas** [InZidiuZ/op-framework-issue-tracker#3556]
### Assurance

I have read the `README.md`

### Summary

To ensure a consistent supply of paper in our buildings, it would be beneficial to implement a system similar to the one at Bean Machine. Specifically, we should introduce a comprehensive paper supply management system for the DOJ, PD, and EMS buildings. This system would help avoid the inconvenience of frequently needing to purchase paper on an ad-hoc basis. 

By setting up a dedicated supply process or inventory system for these locations, we can streamline paper management and reduce disruptions.

If possible add all paper categories in doj building.

### Reason

When we are out of paper we are going again again to buy near bean Machine is better to add the same thing only for DOJ, PD and EMS in their
buildings.

**Comment by coalaura** [comment]
this was already done, you made 2 discord posts about it aswell
