### ISSUE TITLE
Suggestion - Add Speed detection camera at junctions and Add Mobile speed cam

### ISSUE THREAD

**Issue by ekhowan12** [InZidiuZ/op-framework-issue-tracker#3558]
### Name

alcoholic9999

### Summary

Speed Detection Cameras at Junctions
Installing speed detection cameras at junctions will greatly assist highway patrol and local police in monitoring traffic and enforcing speed limits. These cameras will automatically detect any vehicle exceeding the speed limit and issue a fine without the need for officers to be present. The cameras will be linked to a system that uses police department (PD) number plate detection technology, ensuring that fines are issued accurately and efficiently. The police will also have access to the camera footage and system data to review violations, with fines being automatically deducted from the offenders.

Mobile Speed Cameras
In addition to fixed cameras, mobile speed cameras will give the police department more flexibility. Officers can place these cameras in any location as needed, allowing them to monitor areas where speeding is a concern temporarily. These mobile cameras will also use PD number plate detection to issue fines automatically, just like the fixed cameras. This system will help reduce speeding in various locations and improve road safety.

### Reason

Introducing speed detection and mobile cameras in Legacy will create more dynamic and immersive roleplay opportunities for both police and citizens. These systems will encourage people to obey speed limits because of the consequences, such as automatic fines or even the possibility of having their license revoked. This will make players think twice before speeding, leading to more realistic driving behavior and traffic enforcement roleplay.

Additionally, with the increased fines, there will be greater deterrence, ensuring that people take traffic laws seriously. The ability for police to use mobile cameras will also give them more control over traffic management, allowing them to address speeding in different areas as needed, enhancing both the realism and depth of police roleplay.

**Comment by Psycho1952** [comment]
Nah this is way to op and stupid imo. I have seen servers having this and its annoying af like makes 0 sense to me... but it would be nice to have a camera or something so when we do speed traps etc to pull them out then. They are rarely done but still its cool

**Comment by ekhowan12** [comment]
atlist u can add something that will say excess speeding that will come as radio chatter with number plate
