### ISSUE TITLE
Suggestion - Ammunation x Firearms licenses

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3559]
### Assurance

I have read the `README.md`

### Summary

Allow PD to get more involved on giving licenses to people in regards to buying guns from ammunition, removing licenses, etc. 

Once new players fly in for the first time they will not be able to purchase a firearm from ammunition. This would be for basic pistols. Players would then need to go to someone from state or reach out to a PD trained officer who has the ability to do a test for someone to obtain their license. This would be known as a "basic firearms license". Would work similar to getting a boat license where you do a quiz or something and then meet with someone for the test and get the license. The same would work for other firearms from ammunition, but would be known as a "advanced firearms license". This is where they would be able to buy all the other firearms from ammunition. These specific trained officers, and state would have the ability to give, remove, suspend, and whatever else with the licenses. 

Criminals who obtain a certain amount of feloines will not be able to purchase anything from ammunition and would have to get their record expunged in order to apply for any firearms license(s). They would need to rely on Jim to get their firearms.  

PD would communicate with state in regards to how they would like this to work. But essentially certain officers in the city would be trained on how to work with these licenses and document everything correctly.

### Reason

The whole idea of this is supposed to implement a new way to interact with players and the police. Additionally, criminals can very easily walk into ammunition buy a "throw away pistol" for a bank or J-store and not have any value or worry over losing that pistol. Not to mention that someone who is a felon with 10+ felonies can just walk into a ammunition and get a firearm like its nothing. 

There should be more value behind something as simple as these guns.

**Comment by coalaura** [comment]
There is already a weapons license and a way for server managers to override which weapons can be purchased at ammunation and which require a weapons license
