### ISSUE TITLE
Suggestion - PD Evidence Bags Having Serial Numbers Show up in Chat

### ISSUE THREAD

**Issue by ImArteria** [InZidiuZ/op-framework-issue-tracker#3560]
### Assurance

I have read the `README.md`

### Summary

Add back the Serial Numbers in the chat message for a evidence bag after it's processed

Current Message:
Bullet Casings: X Casing(s) were shot by a (Weapon Name) (Picked up at X near Location)

Adjusted:
Bullet Casings: X Casing(s) were shot by a (Weapon Name) with the serial number XYZ (Picked up at X near Location)

I think it was done because SN scratching was brought in, but the gun is scratched not de bullets do not. 

### Reason

Is a tad iffy to screenshot/submit a description when using it for RP. Plz for me plz

**Comment by coalaura** [comment]
fixed, didn't mean to get rid of them
