### ISSUE TITLE
Suggestion - Monitor multiple radio frequencies

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#3561]
### Assurance

I have read the `README.md`

### Summary

Essentially, be able to listen in the multiple radio frequencies for PD/EMS, or just in general

### Reason

This would allow for easier communications for PD/EMS.

**Comment by coalaura** [comment]
how would this work, how would you talk on multiple channels or switch to multiple ones?

**Comment by Brundoggy** [comment]
Have a primary push to talk and a secondary push to talk. 

To have a primary channel, perhaps the command primary-freq then second-freq.

**Comment by MADxxVIKING** [comment]
Couldn't you just key bind two different radio frequencies and bounce between them? 
Idk how you'd have two channels coming in at once, but then know which one to reply to?

**Comment by coalaura** [comment]
honestly i've been thinking about this and i dont think we should add the ability to be on multiple frequencies at a time. I feel like this can be solved other ways and would be a bit too OP
