### ISSUE TITLE
Suggestion - Move State Security Assets to City Hall

### ISSUE THREAD

**Issue by MADxxVIKING** [InZidiuZ/op-framework-issue-tracker#3562]
### Assurance

I have read the `README.md`

### Summary

Moving State Security Vehicle Spawner and Item Shop to City Hall - Along with State Employee IDs

### Reason

As we begin utilizing the new City Hall, some items have been moved such as licenses, however some of our State Employee/Security items such as lockers and State Store are still remaining at  Maze Bank Tower. It would be beneficial to relocate the State Suburban + State Cars here either in the PD garage, between PD/City Hall, or the street between City Hall and Mt. Z.

In addition, placing State Security/Employee shop in the fishbowl office up top in City Hall, or in the reception area where the other shop with paper/folders/etc are placed, possibly opposite side of the room.

This would help locate everything in one location, unless there is something else from devs they are planning that should keep State Security's items in another location

**Comment by coalaura** [comment]
rip old office

**Comment by MADxxVIKING** [comment]
Unless old office interior turns into a State Security interior 🤔

**Comment by coalaura** [comment]
I'll move everything over but keep the old office clothing spot and locks
