### ISSUE TITLE
Suggestion - Additions to Airport Shops

### ISSUE THREAD

**Issue by rakibulhasan456** [InZidiuZ/op-framework-issue-tracker#3563]
### Assurance

I have read the `README.md`

### Summary

Now that we have a facility at the airport, It might be better to move or add some items that are necessary for the flight.

### Flight Radar

There's a DigitalDen at the airport which contains the electronic items. Move the Flight Radar from the Legion Square to here, so it will be easier for the pilots to purchase/access.

![image](https://github.com/user-attachments/assets/51af9fa8-e4d5-4b57-bb5b-578cf83fb578)

If you don't want to include the Flight Radar item in the electronic store, then maybe add another store option in here.

![image](https://github.com/user-attachments/assets/deee7019-ca3a-4992-a05a-b5ecc561e35c)

### Parachute

Parachute is a necessary item for pilots and required for passengers during skydiving. We often need to go at the tool store to bring the item.

There's a BAGstars shop at the airport that can be a good spot for selling the parachute item.

![image](https://github.com/user-attachments/assets/f415a510-33b0-45fb-858d-5cc35dbb4ba2)

### Reason

These additions at the airport will make it easier for pilots and passenger to get the necessary items without going at the tool store or legion square.

**Comment by coalaura** [comment]
flight radar yes, parachutes i don't want to really add there
