### ISSUE TITLE
Suggestion - Adding personal stash/locker to LSUV

### ISSUE THREAD

**Issue by Manmohan-zanwar** [InZidiuZ/op-framework-issue-tracker#3564]
### Assurance

I have read the `README.md`

### Summary

![FiveM_b3095_GTAProcess_XQXNGPI2k0](https://github.com/user-attachments/assets/bbfc0b53-1722-4f7f-9557-d1cbbaadfe75)
Adding a locker to the new LSUV will let the employees keep their personal stuff that cannot or should not be carried or used at LSUV.

### Reason

The reason for this is that usually employees forget to keep their LSUV or personal use stuff with them, which is necessary to be carried on duty, like hold receipts, etc. This addition will help them to manage their work material more efficiently.

**Comment by coalaura** [comment]
Why do you need a locker, you don't really need to store anything

**Comment by Manmohan-zanwar** [comment]
Why do you need a locker, You don't really need to store anything

as mentioned rather than keeping work stuff like hold receipts and other documents or any thing at home which someone can forget would be more efficient if kept at workspace it self 

We can just add a basic or small storage respective to the locker is smaller too.

**Comment by coalaura** [comment]
I generally do not see a real need for a locker for LSUV. Same reason why i declined one for PDM
