### ISSUE TITLE
Suggestion - Moonshine as fuel

### ISSUE THREAD

**Issue by MetaHatter** [InZidiuZ/op-framework-issue-tracker#3567]
### Assurance

I have read the `README.md`

### Summary

Add the ability to use Moonshine as fuel.

- Only partially fills tank
- Causes minor damage to the car and/or makes an oil change necessary sooner

### Reason

Add value to Moonshine as an item.
Funny.
Realistic ( https://www.youtube.com/watch?v=uaoqgKZtaaA ).

**Comment by coalaura** [comment]
done
