### ISSUE TITLE
Suggestion - More PD Impound Locations

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3568]
### Assurance

I have read the `README.md`

### Summary

Please add more PD impound locations than just MRPD. I know a lot of people wanna try get more use out of Rockford PD too. But in Sandy would also be useful too.

Maverick also asks if they could be marked on GPS too.

### Reason

More practical to have more than ONLY one.

**Comment by coalaura** [comment]
there are already 3 at the moment, seems like they are scuffed tho. fixed them now

**MRPD**  
![yes](https://i.shrt.day/RQ7ZV3H17M.webp)

**Sandy**  
![yes](https://i.shrt.day/L635OJAE3N.webp)

**Paleto**  
![yes](https://i.shrt.day/WWCARIIOWV.webp)

I also added one to rockford pd now.

![yes](https://i.shrt.day/AW4XD1CQ9M.webp)
