### ISSUE TITLE
Suggestion - Add info about tow hitches on PDM website

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3570]
### Assurance

I have read the `README.md`

### Summary

Please can we add in the description of a vehicle if it has the ability to hitch a trailer because the number of customers who come in and ask & then end up wasting their money on a vehicle that doesn't have the hitch and then they get annoyed at the employee for not knowing is becoming more and more frequent

### Reason

It would just make life 10x easier for both pdm employees and customers

**Comment by coalaura** [comment]
do you have a list of vehicles that support the hitch?

**Comment by coalaura** [comment]
This would also not be a framework issue as the pdm catalog is a side-project i built a while ago not part of the framework. If you have a list of vehicles that support the hitch i can look into adding it to the catalog, otherwise no
