### ISSUE TITLE
Suggestion - Additions to DOJ

### ISSUE THREAD

**Issue by Lunabelle666** [InZidiuZ/op-framework-issue-tracker#3571]
### Assurance

I have read the `README.md`

### Summary

I have two suggestions that I believe could really improve the RP of the DOJ.

1. A physical bar license, similar to the current physical weapons license. 
2. Keys to the front doors of MRPD for Judges. 

### Reason

Suggestion 1 would be a good change for the DOJ as many members of the DOJ are employed elsewhere whilst they are bar certified and so they have no physical way of showing that they are bar certified when trying to represent someone or talk with PD. This would allow for PD to be able to look them up in the MDT as well and also if they lose their license it allows additional RP when removing the license.

Suggestion 2 would be a good change for DOJ as currently Judges are unable to access the front doors of any PD and so Judges will often be left outside alone and be vulnerable to attacks from the general public and criminals. This happens very often unfortunately and there is not always PD available to let them in to work or meet with other PD members. It also works the other way in which Judges can get locked inside after dealing with DOJ work in PD and then PD shoot off to a chase and leave the Judges locked inside with no way to leave, sometimes for very extended periods of time. I think this would improve DOJ RP greatly.

Thank you for listening.

**Comment by coalaura** [comment]
> A physical bar license, similar to the current physical weapons license.

Will add :)

> Keys to the front doors of MRPD for Judges.

Don't see any reason why judges should be entering MRPD without there also being an officer with them. PD can unlock the doors for Judges if they are needed. If you are meeting up with an officer then that officer should let you in.
