### ISSUE TITLE
Suggestion - Allow licensed weapons in lockers

### ISSUE THREAD

**Issue by justjordyn** [InZidiuZ/op-framework-issue-tracker#3572]
### Assurance

I have read the `README.md`

### Summary

It would be exceptionally helpful for citizens to be able to put licensed weapons only in lockers. 

### Reason

Situations where this would be useful: 
**EMS**: EMS is not allowed to carry guns on duty and they are not allowed to use their licensed taser while off duty. Currently neither can be stored in the locker, so they have both on them at all times. 
**DOJ**: DOJ has lockers at the new courthouse, and to comply with the "no weapons in the courtroom" rule, it would be amazing for them to be able to store licensed weapons only in their locker at the new office. 
**Civs**: Some civs are legal citizens and would like to be able to store their legally registered weapons in a locker. For myself, when I am working at Burger Shot, it would be amazing to put my gun in my locker as the burger making supplies are heavy and working with empty pockets is preferred. That way a gun is not just sitting on the floor in the restaurant kitchen.

**Comment by coalaura** [comment]
done
