### ISSUE TITLE
Scratch Ticket Update

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3573]
### Assurance

I have read the `README.md`

### Summary

Winners and Losers, once you win a ticket with any value you will have to cash it at a convenice store, if you loose you gotta toss it in the trash, just adds a bit more RP to the whole scratch ticket one. would be cool if the larger ones (14k+) took a day or 2 or instead of cash at the conveintent stores on the bigger wins you get savings bonds that you must turn into the bank

another way to get those!

### Reason

Bringing for RP into the tickets!

**Comment by coalaura** [comment]
No, this would make people not want to use them at all due to the extra effort of having to go somewhere to cash them in and the delay. They are meant to be easy so people throw money on them to remove it from the economy
