### ISSUE TITLE
Registration Papers for local Cars

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3574]
### Assurance

I have read the `README.md`

### Summary

I think when we take a local car, there should be a Chance to find “registration papers” in the glove box, it would include plate number and local owners name. 

could be fun for boosting vehicles. imagine having a registration in the glovebox of the boosting car.

Instead of chase might motivate the players to RP their way out of traffic stop

### Reason

Better for traffic stops
It’ll evolve the story / rp relationship I believe

**Comment by coalaura** [comment]
This would be an insane pain to have to carry around with you and make sure you dont loose it. I'd rather not have these things be fully physical
