### ISSUE TITLE
Suggestion - Door Lock Needed At Rockford Station BCFD

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/op-framework-issue-tracker#3576]
### Assurance

I have read the `README.md`

### Summary

The Rockford BCFD station has two vehicle garage stations a north end ( 3 bays) and the West garage ( 4 Bays). When the Rockford Station was constructed, locks in a middle inner garage door were missed and a lock was not installed.  We would like to know if it was possible to get a lock put on the middle door

![Medal_Rezm19FQ6J](https://github.com/user-attachments/assets/331b9edd-d8bf-4366-bc45-3606710dbe74)

### Reason

The reason for this suggestion is so that BCFD can utilize this side of the new station, as it stands we can not use this side of the building due to this unsecured door.  If the garage doors are left unlocked ( due to the timing of them locking, they don't always lock as we drive out)  we normally have people running up inside the station.  If one of the inner doors is not secured, we then have to chase them out of the station's main core area, which seems to be often.   We would like to use this side of the building  while on duty so that we can have service vehicles at the ready as to having to keep telling people to move their vehicles to get them out of the garage.

**Comment by coalaura** [comment]
Found and added the missing door :)

**Comment by Astrozombiecat** [comment]
Thanks Laura you are the best!!
