### ISSUE TITLE
PowerBall

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3577]
### Assurance

I have read the `README.md`

### Summary

 **Powerball System Mechanics**:

1. **Ticket Purchase**: Players can buy a Powerball ticket at designated locations, like convenience stores, banks, or through their phone. Each ticket lets them pick 5 numbers from a set range (e.g., 1-99). The ticket could be priced anywhere from $100 to $1,000 in-game currency, depending on the economy of the server.

2. **Regular Draws**: A Powerball draw happens at regular intervals, say every week or every in-game day, depending on the server's time scale. The winning numbers are drawn automatically by the system.

3. **Progressive Jackpot**: If no player hits all 5 numbers, the jackpot rolls over to the next draw and grows over time. Each new round adds a percentage of the ticket sales to the jackpot, building anticipation. The jackpot could have a visual tracker displayed on billboards or on a special lottery website that players can access.

4. **Matching Numbers**:
   - **5 Numbers**: Hits the jackpot (massive payout).
   - **4 Numbers**: Smaller payout, like 10% of the jackpot.
   - **3 Numbers**: Even smaller payout, maybe a flat amount (e.g., $5,000).
   - **2 Numbers**: Consolation prize, like a free ticket for the next draw.

5. **Payouts**: When a player wins, the server could announce it through global notifications. The payout would be deposited into their bank account, or for RP flair, players could claim their winnings at a specific location like a lottery office.

6. **RP Tie-ins**: 
   - **Scams**: Criminal players could try to sell fake lottery tickets or steal winning tickets.
   - **Group Pools**: Civilians or groups could form "lottery pools" to increase their chances, creating interesting social dynamics.

### Reason

New Powerball Situation!!!! COULD BE FIREEEEEEE

**Comment by coalaura** [comment]
This is basically the lottery already tho, no? or this #3476

**Comment by coalaura** [comment]
I feel like this would just be a copy paste mostly of the already existing lottery
