### ISSUE TITLE
Suggestion - New Phone Abilities

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3578]
### Assurance

I have read the `README.md`

### Summary

All phones should have unique ID's. For example, once I purchase a phone it will be "registered" to me. So when someone checks the phone information it will say the "phones name" is whoever purchased the phone from the store, or when they first fly in.

 Checking phones will work the same as checking a serial number of a gun. But once the phone information is checked it will appear in chat with relative information. 
![54052864463_049854dc7f_o](https://github.com/user-attachments/assets/aee465b3-7362-4eea-bfbd-5c0994b27ceb)
![54051748777_500eca4464_o](https://github.com/user-attachments/assets/72c38f7a-bad1-4125-a64e-306624a3b4a9)

### Reason

Allows people and/or police to check peoples phone during crimes. For example they are checking if a phone prank called the 911 line. Or if someone is tryna check someones phone for a certain piece of information. 

Obviously this can allow room for other ideas like this to develop. But just a concept idea. 
![54052867798_36b3869221_o](https://github.com/user-attachments/assets/56f935b4-2dcf-4e2f-a582-8f7a4dba5848)

**Comment by coalaura** [comment]
i like it

**Comment by kieran179** [comment]
Yeah for cops it would be easy. Crims just takes for them to rob them and do it

Could maybe implement some kind of way to check messages and other things maybe, as every phone would be different

**Comment by coalaura** [comment]
I will close this for now as it has no use case and it is not doable ingame as it requires people to buy a new phone (their old one wont be registered) and would take a long time before it becomes even usable.
