### ISSUE TITLE
Suggestion - Ability to pick up local(s) firearms

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3579]
### Assurance

I have read the `README.md`

### Summary

When locals die they tend to drop guns, if you see them you should be able to pick them up but they will be VERY broken. These can be used to break down for mats etc
![54053126520_053816e3b8_o](https://github.com/user-attachments/assets/cd579987-a68b-499d-82a7-560542118249)

### Reason

Just a cool feature that will help people getting mats etc

**Comment by coalaura** [comment]
This is pretty unreliable and very easily abusable. You'd be able to get a shit load of materials just by driving down grove once.
