### ISSUE TITLE
Throwing people out of cars

### ISSUE THREAD

**Issue by Blackhawkchris** [InZidiuZ/op-framework-issue-tracker#358]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Players sitting in the passenger and back two seats are able to do "/carry" which will then throw the driver out of the vehicle and instantly kill them.

**Steps to Reproduce:**
Took car, filled with driver and passenger, drove on highway, /carry , driver was thrown out of car and died.

Then repeated the above steps in each of the two back seats and same result happened.

**Expected Results:**
Driver to be flung out of car and suffer injuries.

**Actual Results:**
Driver had died instantly.

## Additional Information

**Screenshots:**
N/A as this was taken a while ago. Video of this happening - https://clips.twitch.tv/QuaintPreciousPeppermintRickroll

**Game Resolution:**
1920 x 1080

**Player Data:**
600 | Ellie Holmes | Garbage Collector 

**Notes:**
N/A

**Comment by psyCOSMO** [comment]
That's a bit powergamy, just like carrying someone without any /me

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
