### ISSUE TITLE
Suggestion - Vehicle Clamp Update

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3584]
### Assurance

I have read the `README.md`

### Summary

Allow broken-down vehicles to be clamped. As it currently stands you cannot clamp broken-down vehicles. It just comes up saying something like "you cannot clamp a broken vehicle".

### Reason

People should have to go and get an advanced repair kit tor repair it.

**Comment by joevapes3** [comment]
I think mainly it's cause people return to the car we'd normally clamp with a repair kit and drive off, when we'd with a non damaged car clamp it so they'd at least have to get a tow truck to move the vehicle. Being able to clamp with the car damaged would require them to still complete that step to move it.

**Comment by coalaura** [comment]
done
