### ISSUE TITLE
Suggestion - Increase Bag Capacity for Restaurants

### ISSUE THREAD

**Issue by justjordyn** [InZidiuZ/op-framework-issue-tracker#3588]
### Assurance

I have read the `README.md`

### Summary

The bags currently hold 10 items it seems for food at restaurants. It would be awesome if that could increase to 12. 

### Reason

A good example is Bean Machine. Our meals are 5 food items and 5 drinks. When we do that we can't fit the kinder egg in the bag. Just a small increase in the bag size would be phenomenal! Thanks for reading this and I appreciate you all!

**Comment by coalaura** [comment]
done
