### ISSUE TITLE
Suggestion - GW Candy Bars 

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3589]
### Assurance

I have read the `README.md`

### Summary

GW would be able to sell candy bars 

### Reason

This would be good as we are a dispensary and a chocolate bar with joints would go well. Most dispensary's do sell candy bars in IRL. Also people commonly ask if we sell any snacks like candy bars.

**Comment by baconnator1** [comment]
> > Also people commonly ask if we sell any snacks like candy bars.
> 
> You do have snacks tho, brownies and the gummies, no?

That is true however we would still like to have a regular snack with no weed in it. And these would be obtainable from our store in the shop

**Comment by coalaura** [comment]
ooh without weed, i get now what you mean

**Comment by coalaura** [comment]
done
