### ISSUE TITLE
CarList Suggestion 

### ISSUE THREAD

**Issue by MarioGigante** [InZidiuZ/op-framework-issue-tracker#359]
**Name:**
Who is suggesting this? Please include discord name.
dnk | Mario Gigante#0874
**Summary:**

Write a short summary of what your suggestion is about.

I would like to suggest a couple of car's who could be on the Exclusive Cardealership.
https://www.gta5-mods.com/vehicles/6str-vapid-drift-ellie-custom-add-on-tuning ( 6STR Vapid Drift Ellie Custom )
https://www.gta5-mods.com/vehicles/6str-declasse-drift-yosemite-add-on-tuning ( 6STR Declasse Drift Yosemite )
https://www.gta5-mods.com/vehicles/6str-bravado-gauntlet-custom-add-on-tuning ( 6STR Bravado Gauntlet Custom )
https://www.gta5-mods.com/vehicles/6str-ubermacht-sentinel-classic-custom-add-on-tuning ( 6STR Ubermacht Sentinel Classic Custom )
https://www.gta5-mods.com/vehicles/maibatsu-revolution-sg-rx-tuners-and-outlaws ( Maibatsu Revolution SG-RX )
https://www.gta5-mods.com/vehicles/bf-ladybird-add-on-tuning ( BF Ladybird )
https://www.gta5-mods.com/vehicles/6str-imponte-ruiner-450-custom-add-on-tuning ( 6STR Imponte Ruiner 450 Custom)

**Reason:**

Why would your suggestion be a good addition to Legacy?
This would be a good addition to legacy because i feel the people are waiting for these type of car's to buy a car from Exclusive CarDealership. I would love to see the Tuner Shop where you now buy the Exclusive Car's but the owner of the TunerShop was the one who was selling this type of car's !

**Comment by InZidiuZ** [comment]
Hey,

Pleas post this in the asset-related GitHub issue tracker.

InZidiuZ
OP-FW Developer
