### ISSUE TITLE
Suggestion - Map Marker for Marlowe Vineyards

### ISSUE THREAD

**Issue by Gh0stlius** [InZidiuZ/op-framework-issue-tracker#3592]
### Assurance

I have read the `README.md`

### Summary

Just recently got ownership of the vineyard (Wayne Adams) and people are having an issue finding the place because it's not marked on the map. Maybe a green 'V' or similar could mark the location for gps.

### Reason

People can find the business easier so I can sell wine and book events without having to constantly provide the coordinates via text.

**Comment by coalaura** [comment]
You can use [this tool](https://blip.opfw.net/#0/0) to pick a marker and color. Just post the url of the one you selected here and i'll add it

**Comment by PremKarira** [comment]
https://blip.opfw.net/#411/50/3
Colour can be better but i like this blip.
OR a capital V blip : https://blip.opfw.net/#871/50/3

**Comment by Gh0stlius** [comment]
https://blip.opfw.net/#871/1/3 should work since it's already green up
there.

**Comment by Gh0stlius** [comment]
On second thought, it'd be better if it was this:
https://blip.opfw.net/#871/28/3 since there already a lot of red letters in
city

**Comment by coalaura** [comment]
i'll go for the purple V

**Comment by Gh0stlius** [comment]
Sounds good!
