### ISSUE TITLE
Suggestion - why should sharks get all the Kills?

### ISSUE THREAD

**Issue by Z3KE337** [InZidiuZ/op-framework-issue-tracker#3593]
### Assurance

I have read the `README.md`

### Summary

There should be a feature to allow players to free themselves from a shark bite. If a player is attacked by a shark and has a melee weapon, like a knife, they can rapidly press a button to escape from the shark’s grip. Without a weapon, freeing themselves would be more challenging, but still possible, adding a realistic and interactive way to deal with underwater dangers.can

### Reason

I think The Kill to Death ratio of sharks is waaayy higher than humans. Let us live

**Comment by coalaura** [comment]
This is not really doable nor realistic imo. Not doable since shark attacks are a core part of the game and not something that we added which we have control over
