### ISSUE TITLE
Suggestion - Starting construction for Marlowe Vineyards

### ISSUE THREAD

**Issue by Gh0stlius** [InZidiuZ/op-framework-issue-tracker#3594]
### Assurance

I have read the `README.md`

### Summary

https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2088 hoping to have something for the business owner dinner later next month and to be able to do in-house cooking/catering

### Reason

Makes Marlowe Vineyards more functional and have more variety of things to have on hand for events.

**Comment by coalaura** [comment]
Please don't open issues for things that already have an issue open. Will not have them be done faster

**Comment by Gh0stlius** [comment]
Sorry about that.
