### ISSUE TITLE
Suggestion - LSUV podium displays 

### ISSUE THREAD

**Issue by Beetkrunkles** [InZidiuZ/op-framework-issue-tracker#3595]
### Assurance

I have read the `README.md`

### Summary

The next step in the success of LSUV would be to add some sort of “computer” or something similar to the way that Pdm works
This will allow the managers and owner to place a vehicle from the stored garage on display in one of the bays at a price we set and let customers buy them from the floor

### Reason

the reason this is needed would be to make the buying a used car experience better for the customers as most are newer to the city and wish to grind and get a nice new car to get from A-B or just to show off the hard work they have put in
The current issue is we can show and let them test drive the cars but then have to wait x amount of time (could be hours or days) for the owner to be available to fly in at random times and sell a car which kind of halts rp for both party's involved 
 
This change will be a great addition to streamline the experience and push the success of the business for all city’s that use this feature

**Comment by coalaura** [comment]
I really don't think you need a whole computer. The whole idea of LSUV is you are buying used cars from a second hand dealership. All employees can pull out and store cars in the shared garage, the manager just has to fly in once and move them from their personal garage to the shared garage. You have plenty of showcase spaces in the LSUV building where you can put the cars for showcase. If you wish you can even drop a notepad in front of the car with more information about it and/or a price. Once someone wants to purchase a car you can sell it to them using /givecar and /bill.

**Comment by Beetkrunkles** [comment]
The current issue is we can show and let them test drive the cars but then have to wait x amount of time (could be hours or days) for the owner to be available to fly in at random times and sell a car which kind of halts rp for both party's involved
