### ISSUE TITLE
Suggestion - Revised Construction Plan for Marlowe Vineyard

### ISSUE THREAD

**Issue by Gh0stlius** [InZidiuZ/op-framework-issue-tracker#3596]
### Assurance

I have read the `README.md`

### Summary

This suggestion is to simplify something that was previously brought to me about what the vineyard would have. As the new vineyard owner (Wayne Adams), I'd like to simplify some things to make the vineyard both functional and sensible to the business.

-**Remove the proposed winery job, have only three types of grapes available**

-I believe that wineries would try to sensibly specialize in the grapes they cultivate. In this case, the only ones needed would probably be Red Grapes (for Red Wine), Green Grapes (for White Wine), and Purple Grapes (For Table Wine). _These can be named Marlowe Red, Marlowe White, and Marlowe Table Wine respectively. Ingredients would only require water, glass (for bottles), and the appropriate grapes required to make each wine._

-Use the wine cellar that's already in the building to store these wines, as well as other places sensible for water (like a water cooler) and glass (currently, the private lockers). The fridge in the kitchen/catering area would be a decent place to put the grapes.

-Only allow the grapes to be picked by employees of the Vineyard, as well as the crafting station for making the wine. This can be time gated, and the amount of time at engineer's discretion.

-Place locations for fire extinguishers within the building, as well as a fire hydrant outside of the building to stay compliant to fire inspections.

-Allow the kitchen/catering area stoves to function as grills.

### Reason

   The previously provided summary will cut down on a lot of the older building suggestions and streamline the functionality of the vineyard. It will also provide utilities not only to employees, but to businesses that might want to use these things for catering so it cuts down on having to have previously made food items that might go to waste due to little or no demand for them. It will also give the Vineyard a specialty outside of being a host for events and gatherings in the form of the red, white, and table wine.

I have included all of what I've observed from ownership thus far to prevent having to make multiple suggestions over time to cut down on requests. I am aware and understand that these things take time and will be patient if these are being worked on or implemented.

Thank you for your time and I hope you will consider this suggestion. I hope that this will save some time and make things a bit easier.

**Comment by coalaura** [comment]
> Remove the proposed winery job

I'd rather have it be an actual job allowing you to harvest grapes and produce wine properly.

All the rest is basically the same as the winery job: #2088

**Comment by Gh0stlius** [comment]
The water cooler and the fire compliance is still needed for the building,
though.

**Comment by coalaura** [comment]
> The water cooler and the fire compliance is still needed for the building, though.

Yes, for those you'd have to make an asset issue :) https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by Gh0stlius** [comment]
So this simplification I did of things got shut down because the older one
is being worked on or what? The job would still be there but with less
moving parts.

**Comment by coalaura** [comment]
> So this simplification I did of things got shut down because the older one
is being worked on or what? The job would still be there but with less
moving parts.

It was closed as its a duplicate of an existing issue. Simplifying it is not a solution, i rather have a fully working job with all its parts than do something just half way. Its on the todo list, however we are 2 devs, not 20 and there is over 90 other github issues plus a truck load of suggestions in the opfw discord that want to be implemented too. I put a comment on the original issue, which i linked, explaining how i currently plan on implementing the job once i get to it.

**Comment by coalaura** [comment]
That being said, the watercooler and fire extinguisher you mentioned are easy and quick things to be done. Since they require mapping work tho, you'll have to create an issue for them in the asset issue tracker [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new?assignees=&labels=suggestion&projects=&template=suggestion.yml&title=Suggestion+-+).
