### ISSUE TITLE
Suggestion - Permissions Update Please :)

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3598]
### Assurance

I have read the `README.md`

### Summary

Please can there be a way for regular CFI's to add/remove license's. Not everyone who is a CFI works for State who are the only people who can add/remove licenses for aviation. 

Please make it so people who do not work for State but are a CFI can give ONLY the aviation licenses. 

### Reason

Saves non-state worker CFI's chasing people up all the time just to give a license. 

Hopefully, this is something that can be done, thank you :)

**Comment by coalaura** [comment]
With aviation licenses the potential for abuse it quite high and in the end licenses irl are not given out by the instructor but by the state. I think it should stay that way and state should be the ones managing licenses (also makes keeping track of it easier)
