### ISSUE TITLE
Kill logs Bug report

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#360]
**Reporter:**
Pancho#0001
**Summary:**
No logs for who u kill in the logs

**Steps to Reproduce:**
look at logs after killing someone, nada

## Additional Information
easy to find, this is kinda important for staff issues, aka combat loggin primarily
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://cdn.discordapp.com/attachments/408001370554105856/609903184634183681/unknown.png

killed someone 3 different ways 3 times to test as staff then had them kill me nothin shows there

**Comment by InZidiuZ** [comment]
Hey,

This is not a bug... I did, however, change the logging to log "Killed Player" too, but this can be manipulated maliciously, so take it with a grain of salt in sketchy scenarios. The same goes for "Player Killed" logs.

**InZidiuZ**
*OP-FW Developer*
