### ISSUE TITLE
Suggestion - Panic Button Command

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3601]
### Assurance

I have read the `README.md`

### Summary

A legit panic button that is behind a command would be useful to pd that you can press while you are still alive, I know we have our downed panic button and our broken tracker button but those are only used in specific situations but a command that u can bind to a hotkey and it will send the message to all official personnel 
**Panic Button - Officer has pressed their panic button at XYZ**
This would be most useful if you are taking fire and there’s too much radio chatter and your voice gets annoyed you can hit your button after screaming 10-99 and then it will notify everyone your location and maybe it can track your character for like 5-10 seconds so if its a mobile shootout people have a physical tracker to go to

### Reason

it’ll help officers and I especially think of cadets on solo who this will help out

**Comment by coalaura** [comment]
No, this would have big potential for abuse and is also a bit OP. Panic button should only happen once when dying
