### ISSUE TITLE
Suggestion - New Script Idea 

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3602]
### Assurance

I have read the `README.md`

### Summary

This would be cool for people to use for tons of things like businesses, events, investigation scenes. Thats just to name a couple. This is similar to /description but for putting them on the wall, floor, wherever else. 

https://www.youtube.com/watch?v=9MnwVHepLOg

### Reason

Cool feature that has the potential to have a lot of purpose

**Comment by HollaYalla** [comment]
a /scene command would be nice to have for RP but a limit would need to be made or allow everyone to delete them as I could see dannys spamming them to cause lag to peoples games

**Comment by kieran179** [comment]
Pretty sure when placing them there is a maximum time they can be up for before they expire anyway

**Comment by coalaura** [comment]
duplicate #2648
