### ISSUE TITLE
Suggestion - Store Bought Food Decay Increase

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3603]
### Assurance

I have read the `README.md`

### Summary

Most people as much as I have seen just go and buy food from the Store instead of going to a already open restaurant ran by players but if you make the food bought in the store decay fully in like a couple hours or even a day but keep the player made food decay in like a couple days so it has a longer shelf life could bring more people to the restaurants since the food lasts longer and could increase prices of donuts and tacos or just reduce the amount of food that they give to make them not as worth it.

### Reason

Bring more People to player owned restaurants

**Comment by coalaura** [comment]
I think people mainly go to grocery stores WHEN they are hungry so this wouldn't really affect them. People mainly don't go to reataurants cause they are open so rarely (which i hope to adress with the tasks system). grocery store food is already insanely overpriced and barely fills you up, i don't think this change is needed
