### ISSUE TITLE
Suggestion - Purchasable Abandoned Wearhouse  

### ISSUE THREAD

**Issue by Ollie0976** [InZidiuZ/op-framework-issue-tracker#3605]
### Assurance

I have read the `README.md`

### Summary

Adding The ability to purchase abandon warehouses , Customise the interior similar to a house , Have  similar storage amounts as shipping containers  but have 2 Tiers small (20k storage) Large (40k Storage) However also make them purchasable as an option so you can either play a weekly fee or buy one outright. 

### Reason

The reason this should be implemented
- Due too the gun computer returning shipping containers have now become less of viable option  based on the activities at the docs
- An option for Solos and Groups too use their abundance of cash  to purchase something bigger than an house
- For someone like myself give people outlets to get together and plan heist and prepare better (A run down warehouse can help with the immersion and roleplay
- Could open up more options for different and unique events and situations even the possibility of new businesses Legal or Illegal

**Comment by coalaura** [comment]
hmmm, i dont see how the gun computer makes the containers less viable. If you really dont want to use containers at the docks, there is plenty more locations where you can rent containers in different places on the map

**Comment by Ollie0976** [comment]
The large majority revolve a round the gun comp, All of midnight ones are full and all of southside ones etc are no longer purchasable

**Comment by coalaura** [comment]
I'll go around and add some more purchasable ones

**Comment by Ollie0976** [comment]
And add a cool 500k Wearhouse I can buy >:)
