### ISSUE TITLE
Suggestion - Sell Disposable Vapes at Convinient Stores

### ISSUE THREAD

**Issue by kieran179** [InZidiuZ/op-framework-issue-tracker#3606]
### Assurance

I have read the `README.md`

### Summary

Green Wonderland literally never opens anymore. Doesn't matter what anyone says it's impossible to catch them ever at this point. I feel like there needs to be another alternative instead to getting a vape, or even having somewhere else to refill them. 

### Reason

Green Wonderland never opens. I will make an effort to contact state IC and see if they can do anything too

**Comment by HollaYalla** [comment]
This most likely won’t happen as it will run GW out of business there’s already cigarettes and ZYNs at convenience stores as the GW never being open is a IC problem

**Comment by coalaura** [comment]
Yeah, there is PLENTY of alternative ways to reduce stress or get high. GW not being open is a in server roleplay problem.
