### ISSUE TITLE
EMS Suggestion

### ISSUE THREAD

**Issue by CapTurtle00** [InZidiuZ/op-framework-issue-tracker#361]
**Name:**
Who is suggesting this? Please include discord name.
CapTurtle#2531

**Summary:**
Write a short summary of what your suggestion is about.
Getting rid of the /carry command either entirely or make it to where EMS and police just have it.
Also Respawn suggestion 

**Reason:**
Why would your suggestion be a good addition to Legacy?
I as high command of EMS feel that the /carry command is bring down EMS roleplay. I have have multiple people tell me that they feel that people overuse the /carry command to bring people their friends into the hospital. I agree, I feel that people are over using it, I also feel that police officers over use the command to bring in suspects I feel that us as EMS, we are paramedics first and doctors second. I have someone come to be and said they would rather focus on Paramedic roleplay then being forced into doctor roleplay. But use the /carry command forces into doctor roleplay instead of paramedic roleplay, We dont really have a choice. It has come to the point to where alot of EMS dont roleplay because of the doctor roleplay they would rather do Paramedic roleplay. and I feel that getting rid of the /carry command would be the best option. I also feel that if we do get rid of the /carry command. We should also add that if you respawn you should lose some of your stuff. It would make sure people stop killing each other randomly and make it to where they value their life more. I feel that at the moment people just stand outside of pillbox and fight and demand to be helped after they just came in. its getting kind of ridiculous. I just feel like these suggestions would help in general. 
-Captain Alex Rae of the EMS deparment

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed. Not a framework issue.

**InZidiuZ**
*OP-FW Developer*
