### ISSUE TITLE
Suggestion - More food items for Kissaki 

### ISSUE THREAD

**Issue by HollaYalla** [InZidiuZ/op-framework-issue-tracker#3610]
### Assurance

I have read the `README.md`

### Summary

I feel like I only care about Kissaki lol but here is more stuff I think should be added to kissaki

**Mochi**
Mochi is a very good Japanese Dessert and it is a Rice Cake usually with powdered sugar and filled with a type of ice cream and I think adding it would be a good idea to give kissaki a actual dessert item this could be crafted with some Milk and Rice and some Sugar which all but Milk are already in the Kissaki Shop

![image](https://github.com/user-attachments/assets/72c84efb-ad3f-46a0-91a9-e9a5ffa23353)

**Dorayaki (Japanese Red Bean Pancake**
Dorayaki is a basic Pancake filled with a red bean filling it is a very common dessert in Japan as far as I have seen and it would make a great fit into the Japanese Restaurant it could utilize the Pancake mix that is already in the game and a can of beans and both can be added to the Kissaki Store and maybe some milk to actually make the Pancake Batter than you mix them both at the Pot and cook them into a Pancake.
![image](https://github.com/user-attachments/assets/3d7b8016-2901-41b3-8f14-1c36b0f7d2a6)

**Ramune**
Ramune is a Japanese Styled Soda which would add some diversity to the soda market and it can only be gotten from Kissaki this could be bought like any other soda and a reskin of the beer bottle could be a good prop for it (I am happy to make it for you)
![image](https://github.com/user-attachments/assets/06c1acbb-17f8-44f1-ba7f-0ba77eea1c74)

**Kissaki Bag Icon Reskin**
This is just kind of a weird ask but the current kissaki bag doesnt have the actual kissaki logo at all so maybe switching it from this 
![image](https://github.com/user-attachments/assets/4a81b31e-c283-4794-90c3-df04c25b3570)
To this logo 
![Untidwtled](https://github.com/user-attachments/assets/6fbc6178-08ec-4e84-b34f-4a770a62c2c0)
Or using this
![white_new](https://github.com/user-attachments/assets/d23938e5-40fb-43d8-9b1c-7e7ff2faa570)
or a dark version 
![image](https://github.com/user-attachments/assets/25329a29-27a6-47cc-b515-a57c40ede049)

theres a lot of options for the bag

### Reason

The food items can add a better menu for Kissaki and also make it a lot more different than a normal restaurant and add more special foods like Burgershot has Avocado Smoothies and Bean has Espresso and while Kissaki has Asahi Beer a non-alcoholic alternative would be great and some dessert items would be nice as Kissaki is styled more as a Dine In Restaurant

**Comment by spitslave** [comment]
I feel like Kissaki out of all the restaurants already has a lot of food, I'd like to give the options for more restaurants to have more items as well.

**Comment by Manmohan-zanwar** [comment]
i would personally agree that it has a lot of food items already on the list and businesses like pizza This has only pizza's and a breadstick, where as we can add some items like Garlic bread, fries for pizza this too, and more

**Comment by coalaura** [comment]
I've changed the paper bag icon. I've also added 4 flavors of mochi and green tea

![yes](https://i.shrt.day/DW7Q98WBWR.webp)
![yes](https://i.shrt.day/4D1A62LDK0.webp)
