### ISSUE TITLE
Suggestion - Panic Button for Businesses

### ISSUE THREAD

**Issue by Vikky98** [InZidiuZ/op-framework-issue-tracker#3613]
### Assurance

I have read the `README.md`

### Summary

a type of emergency alarm or panic button for businesses all over the city by using which they can contact law enforcement quickly when something wrong is happening in their building.

### Reason

Currently, we don't have any feature like this, and in case of any crimes, we may need to message the PD's hotline, which might get ignored or something due to being busy in some other situation or something. and if businesses have a panic button or emergency trigger that can be used in unwanted circumstances so that PD gets a message or popup like robberies or drug sales or something like that. Free units can directly respond there, or units can be assigned to check over there. PD response will be quick imo.

**Comment by Cypher45** [comment]
Yep, that's would be a great idea.
Employees will be able to contact law enforcement faster, rather then opening whole phone to type the message in front of the criminals and then getting ignored.

**Comment by spitslave** [comment]
I think this would be abused easily, and people should go through the RP of trying to call the cops

**Comment by AliAsger007** [comment]
Yes it would be great if a stress button will be add for business only
