### ISSUE TITLE
Suggestion - PD garage & repair spot at zancudo

### ISSUE THREAD

**Issue by Vexi1221** [InZidiuZ/op-framework-issue-tracker#3614]
### Assurance

I have read the `README.md`

### Summary

having a repair station or a place to pull out vehicles in the hanger primarily used for police academies.

### Reason

 i feel would be nice to have as most of the time academies can go in very unexpecting ways leading to cars being destroyed leaving trainers/cadets without vehicles, and with how long we are normally at the hanger we get very low on fuel having trainers needing to leave and go buy jerry cans taking even longer for us to finish the academy

**Comment by coalaura** [comment]
all done

![ye](https://i.shrt.day/R82GKJI47M.webp)

**Comment by coalaura** [comment]
the repair spot is right across in front of the small indent

![yes](https://i.shrt.day/JHOSD0H6I1.webp)
