### ISSUE TITLE
Suggestion - Destroying PD Spikes

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3616]
### Assurance

I have read the `README.md`

### Summary

I think non-pd should be able to destroy/break down spike strips to remove them. This could be via a mini game or by using a sawzall or some other tool. 

### Reason

In scenarios where pd are careless and don't watch their spikes or just leave them in places they shouldn't be or in scenarios where you see a cop lining up to spike your friend in a chase, criminals should be able to counter that but can't since only pd can touch spikes

This could add some extra rp to chases or pd interactions in general. E.g holding up a cop whilst your friend destroys the spikes so your other friend doesn't drive over them. Or when pd *coughs* spike the coke hangar.

**Comment by coalaura** [comment]
you can now do so with the sawzall
