### ISSUE TITLE
Suggestion - Destroying Tire Walls

### ISSUE THREAD

**Issue by CloudCait** [InZidiuZ/op-framework-issue-tracker#3619]
### Assurance

I have read the `README.md`

### Summary

Tire walls should be able to be destroyed via shooting them

### Reason

Crims like to block entrance ways in shootouts with tirewalls and the only way to counter is to have a meat shield go and take it down

**Comment by ImArteria** [comment]
or just remove them

**Comment by coalaura** [comment]
This was discussed at a previous time and determined not to be possible due to the way they work
