### ISSUE TITLE
Suggestion - Coin Purse

### ISSUE THREAD

**Issue by Kay32** [InZidiuZ/op-framework-issue-tracker#3622]
### Assurance

I have read the `README.md`

### Summary

A coin purse that can hold the coins instead of having a 5 different coins holding inventory space

### Reason

I love the new coins and I want to use them as a "rainy day fund" but 5 different spaces consumed by penny, nickel, dime, quarter, half dollar is cluttering my pockets

**Comment by coalaura** [comment]
![yes](https://i.shrt.day/JWU2AEEXJY.webp)
