### ISSUE TITLE
Suggestion - Access for staff to add temporary counters.

### ISSUE THREAD

**Issue by Git-Rexdev** [InZidiuZ/op-framework-issue-tracker#3624]
### Assurance

I have read the `README.md`

### Summary

Recently we got access to add temporary garages and we already have access to commands like `add_notice`
So for short work or some community events, it would be really awesome for anyone to add counters and keep food or stuff in them, which can be efficient and decrease the work of food/material distribution when we have open for all or big community events.

### Reason

The reason is that it takes a lot of time to distribute things to people, and we can't give time to things. Also, it can be inappropriate a lot of times, which causes uneven distribution, so we can get access to temporary counters, which can be used to manage things efficiently.

**Comment by coalaura** [comment]
ground inventories exist, they work basically exactly the same as a temporary counter would. I see no need for this
