### ISSUE TITLE
Suggestion - Adding new items to paper bags

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#3626]
### Assurance

I have read the `README.md`

### Summary

Make it so the following items can be placed into paper bags for Green Wonderland workers:
- Penjamins
- Bongs
- Redwood Card Packs

### Reason

Green Wonderland would like to make more effective use of paper bags and for quality of life enhancements. This would allow us to put penjamins, bongs and redwood card packs, which are currently items that are unable to be placed into a paper bag. This would also aid in being able to package weed and bongs together in a clearly identifiable package, this would also allow for me to propose penal code changes that would allow us to sell this combination of product legally. For clarification, the card packs are going to be packaged in bags for GW related events.

**Comment by coalaura** [comment]
penjamins and card packs yes, bong is too big for a paper bag
