### ISSUE TITLE
Suggestion - Unregistered firearms having a legal selling option

### ISSUE THREAD

**Issue by SuperDupper45** [InZidiuZ/op-framework-issue-tracker#3627]
### Assurance

I have read the `README.md`

### Summary

Currently unregistered firearms are considered prizes in events such as dailys and zombie pills and also when you go diving in cayo. im asking for a legal way to sell these weapons similar to how you offer a way to sale device scanners and gem scanners at the bazar in the silver camper. im suggesting there be a option to sell items like illegal pump shot guns and pistols so that people who are legal are provided something for the time spent doing things like dailys and diving.
cuurently only option is for the legal members to destroy or surrender these items to police for zero gain. so having it as a prize is equal to receiving nothing this suggestion would be to add guns to the silver camper in the bazar with the other items such as cell phones device scanners and gem stone scanners adding the weapons would be a great and easy fix so these items can no longer be equal to nothing.

### Reason

As with any city there are legal and illegal sides to all components this suggestion would provide a major benefit to the legal members of your city as where currently receiving a unregistered firearm is only benefiting the illegal side this suggestion would offer a balance to this prize to offer a monetary gain for selling thereby making this prize worth more then zero.

**Comment by coalaura** [comment]
You can break them down, to get the materials which you can sell, no?

**Comment by SuperDupper45** [comment]
Agreed but that is in my mind illegal I'm selling gun making parts to gangs, also that doesn't apply to all firearms only pistols

**Comment by coalaura** [comment]
You don't get gun making parts tho. You get materials most commonly used by mechanics

**Comment by SuperDupper45** [comment]
Oh I've only ever known that you can use the parts to make guns I've never broke one down because of it. Does it allow you to break down the gold revolver and stuff too? And pump shot gun?

**Comment by SuperDupper45** [comment]
I'll break a pistol down tonight and see what I get

**Comment by SuperDupper45** [comment]
Sorry just got in city so I checked your correct I can break down everything pistol related but not rifle it shot gun related or is that something available that also needs to be roleplayed out?

**Comment by coalaura** [comment]
you are able to break down almost every gun including shotguns and rifles, however they are in different locations which you have to find through rp

**Comment by SuperDupper45** [comment]
Thank you for your time
