### ISSUE TITLE
Suggestion - Boosts to Strained Weed Growth

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#3628]
### Assurance

I have read the `README.md`

### Summary

Slightly decrease the growtime of strained plants or increase the harvest yield if possible.

### Reason

As it stands, there are seven different strains of weed available to us at Green Wonderland, we feel that either an increase of harvest yield or a slightly decreased grow time would help us be able to maintain a more active supply of product. Since we were used to dealing with three strains, I had devised a routine with my employees to regularly pick the strained product, however we found ourselves running out quickly, we feel that this issue will be further exacerbated due to the new additions.

**Comment by coalaura** [comment]
They are supposed to be rare. You are supposed to try to keep the ones in stock that are requested and they shouldn't always be available due to their special effects
