### ISSUE TITLE
Bug report - Issue with AK-47 Weed Strain

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#3629]
### Assurance

I have read the `README.md`

### Reporter

darkness

### Summary

Smoking AK-47 weed joints produces an error message that can be logged to OP-FW.

### Steps to Reproduce

Roll AK-47, smoke AK-47

### Expected Behavior

Not sure, but you shouldn't receive an error box.

### Actual Results

An error box is produced on your screen and the joint has no effect

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/0e154599-4f7a-4bf7-8b66-254411ec2a13)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
