### ISSUE TITLE
Report: Public access to WN Helicopters

### ISSUE THREAD

**Issue by Git-Rexdev** [InZidiuZ/op-framework-issue-tracker#3630]
### Assurance

I have read the `README.md`

### Reporter

.rexdev

### Summary

I have been talking about this for a long time now, but seeing these things abused recently made me open this issue.
Everyone who has a normal heli license has access to the Weazel News helipad as well as Weazel News's business helicopters like the WN Maverick & WN Supervolito. I request you to remove them from the license, either by giving another license to be issued or by making it directly role-bound like PD & EMS.

### Steps to Reproduce

Go to WN HQ helipad and try to take out any helicopter. 
![FiveM_b3258_GTAProcess_OEiy0Q4TLO](https://github.com/user-attachments/assets/d2451039-9242-4d87-ba66-95ccb081cacb)

### Expected Behavior

Expected to show only 2 unauthorized helicopters, i.e. Supervolito & Maverick WN Livery and Perks.

### Actual Results

People get access to PD calls like 10-71, 10-90s and other stuff.
![FiveM_b3258_GTAProcess_smoQxpd1fs](https://github.com/user-attachments/assets/571ba3e3-2dfa-4e09-ad63-998dbd6a893c)

### Screenshots/Videos

![FiveM_b3258_GTAProcess_smoQxpd1fs](https://github.com/user-attachments/assets/c9747de8-8a1b-43d6-bc74-9577ab78171f)
![FiveM_b3258_GTAProcess_OEiy0Q4TLO](https://github.com/user-attachments/assets/7c88fce0-3389-49a7-952e-86b19fa0d6cb)

### Game Resolution

1920*1080

### Player Data

Character-ID: 1267
Job Data: Business / Los Santos Aviation / Manager: $62 (Without multipliers)
Licenses: heli, passenger, weapon, hunting

Timestamp: 2024-12-20 07:17:53

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment]
I've changed it to the "press" license now
