### ISSUE TITLE
Bug report - No Turbo option at Midnight Tuner Shop or Los Santos Customs/Benny's.

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-issue-tracker#3631]
### Assurance

I have read the `README.md`

### Reporter

Baboon ヒヒ / skippingbaboon / 389169991028703232

### Summary

I was working at Midnight Tuner Shop, I had a number of people ask for "Full Performance Upgrade" in quick succession. Whilst undertaking each "Full Performance Upgrade" (Every performance mod option including armor) I noticed there wasn't an option to install a turbo.

Once the customers had left, I tested myself using both a PDM and EDM vehicle, and as predicted, neither of my vehicles I tested had an option to install a turbo. This was also replicated at Los Santos Customs.

### Steps to Reproduce

Go to either Midnight, Los Santos Customs, Benny's, try to install a turbo.

### Expected Behavior

To have an option to install turbo.

### Actual Results

No option to install turbo.

### Screenshots/Videos

No Turbo option at Los Santos Customs Lesus LFA - 
https://drive.google.com/file/d/1EY-vLWmz5yALE87OWtvQtdDe5C8Nw851/view?usp=sharing

No Turbo option at Midnight  Lexus LFA -
https://drive.google.com/file/d/1V4I7uZzg32ksmNGuApYD6ZEVobpaifYo/view?usp=sharing

No Turbo option at Midnight Declasse Tahoma Coupe -
https://drive.google.com/file/d/1NXsxw0yw00SMuuhbpK4yguBzgLEke09a/view?usp=sharing

### Game Resolution

1920x1080p

### Player Data

Character-ID: 134404
Job Data: Business / Midnight Tunershop / Tuner - $35
Licenses: hunting, boat

Timestamp - 2024-12-20 20:43:09

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
