### ISSUE TITLE
Bug report - Gorilla Glue Bug

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#3632]
### Assurance

I have read the `README.md`

### Reporter

darkness

### Summary

smoking gorilla glue produces an error

### Steps to Reproduce

smoke gorilla glue

### Expected Behavior

no error message, the ability to surf on vehicles should be expected.

### Actual Results

an error box is produced to be submitted to OP-FW servers.

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/27fa2c5a-e07a-46c4-9311-56de3679a7ca)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
fixed
