### ISSUE TITLE
Bug report - Trucking Job Issues 

### ISSUE THREAD

**Issue by Astrozombiecat** [InZidiuZ/op-framework-issue-tracker#3633]
### Assurance

I have read the `README.md`

### Reporter

Astrozombiecat

### Summary

I received a ticket report 28392 in the Legacy international server.  The ticket states when accepting a job and completing the job it says "error: you are not in a job", and does not pay the player. 

I went into the city to test this myself and got the same results.  

### Steps to Reproduce

Get Semi Truck. 
Accept the Job at any of the pickup points
Get trailer
Make Delivery. 
Turn in Job

### Expected Behavior

The expected results is to get paid for making the delivery. result

### Actual Results

You get an error message in the upper right hand side of the screen that reads
"error: you are not in a job"  ( when you are on a job) right-hand

### Screenshots/Videos

![Medal_BgXDkWIRvk](https://github.com/user-attachments/assets/7aea677b-387b-4d01-b997-132d805b06fa)

https://medal.tv/games/gta-v/clips/jl23GItA0tive4rcI?invite=cr-MSw0STQsMTg0MTU2NzEyLA

https://medal.tv/games/gta-v/clips/jl2bZ3CULpqb__yhF?invite=cr-MSxTUFYsMTg0MTU2NzEyLA

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment]
i've looked into it and i'm unable to reproduce it. It may be a FiveM issue

**Comment by coalaura** [comment]
@Astrozombiecat let me know if this is still an issue with the update that was pushed today

**Comment by Astrozombiecat** [comment]
it seems like its ok now.  Ive not heard any  complaints from it and watched Joes stream while he's trucking and it seems to be ok now.   Thanks Laura you're the best.
