### ISSUE TITLE
Suggestion - Personal lockers in GW

### ISSUE THREAD

**Issue by baconnator1** [InZidiuZ/op-framework-issue-tracker#3634]
### Assurance

I have read the `README.md`

### Summary

Personal lockers in GW for employees like every other business has. However we would need them so employees can't put weed in them and steal as we can't search their lockers. 

### Reason

Every other business has one and it would be nice for employees to be able to put things away before they start working especially vapes as they often mix with customers. 
![Screenshot 2024-12-26 141501](https://github.com/user-attachments/assets/1590e16b-6272-4c05-a1b7-1eedd3c0fd6d)

The lockers can go here

**Comment by coalaura** [comment]
> like every other business has

Not every business has lockers. Lockers are added if they are urgently needed and usually only restaurants and repairs shops. GW does not need lockers, they have the shared storage and everything else is the employees discretion
