### ISSUE TITLE
Suggestion - Make strained plants unharvestable unless you work at GW

### ISSUE THREAD

**Issue by tcphdr** [InZidiuZ/op-framework-issue-tracker#3635]
### Assurance

I have read the `README.md`

### Summary

People have been left and right abusing an issue with their games to bypass my doors in the building. Leaving nothing in the way to stop them from just walking through the building straight into the back and harvesting the plants.

### Reason

It would stop them from being able to harvest while ensuring that we also aren't having to stop what we're doing to deal with people that are abusing game issues.

**Comment by baconnator1** [comment]
I agree with this as people often walk through our walls and steal our product which could get GW in trouble if they get caught by the police

**Comment by coalaura** [comment]
This is just powergaming and can be handled by staff very easily. I don't like the idea that you cant harvest a plant thats right in front of you. You can lock the doors, if people abuse glitches then well thats powergaming and is a staff issue

**Comment by tcphdr** [comment]
So basically I have to drop my roleplay every 20 minutes to deal with powergaming?

Nice.
