### ISSUE TITLE
Suggestion - Adding craftables 

### ISSUE THREAD

**Issue by Git-Rexdev** [InZidiuZ/op-framework-issue-tracker#3636]
### Assurance

I have read the `README.md`

### Summary

Recently, I have seen a good amount of additions to the crafting scripts in our FW, and I would really like to see more additions in the future. But, currently, I have some suggestions that can be thought of being added.

### Reason

Adding craftables like Armors and Cuffs and some more paints from base GTA (We dont have some like the christmas special paint,
and the golden paints.

**Comment by coalaura** [comment]
Armor and cuffs shouldn't be craftable imo. We already include all paints from the basegame with the exception of very special paints (which don't exist for all weapons). The golden (luxury) paints have already been suggested in the discord
