### ISSUE TITLE
Clipped into sunken ship

### ISSUE THREAD

**Issue by Killibrew** [InZidiuZ/op-framework-issue-tracker#364]
**Reporter:**
Titan#3369
https://steamcommunity.com/profiles/76561198407843626/

**Summary:**
I clipped into the sunken ship and died. I hear it's a known issue so I wanted to get a report in on it. 

**Steps to Reproduce:**
Swimming around the sunken ship I clipped into the front end of the ship. 

**Expected Results:**
You clip into the front end of the ship and can't get out.

**Actual Results:**
Clipping into the front of the ship. 

## Additional Information

**Screenshots:**
Here is a youtube link of the spot. I wasn't recording when I actually clipped into the spot though. 
https://www.youtube.com/watch?v=q5TPFFb9qSo&t=212s

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 5490

**Notes:**
I would like to get the materials I lost back if that's possible. It's not much but I'm a poor cadet in game so that was what I was going to do to get some cash.
1x Phone
8x Steel
7x Scrap Metal
3x Rubber
2x Aluminum
4x Glass
1x Plastic.

**Comment by InZidiuZ** [comment]
Hey,

I managed to replicate this at two locations, both of which I placed a "[E] Stuck 'teleporter'" as a workaround for this. Don't want to start messing with GTA maps, so this will do for now.

There are no compensations currently, though, so I'm unable to refund the lost items.

**InZidiuZ**
*OP-FW Developer*
