### ISSUE TITLE
Nissan Titan Can't change delivery

### ISSUE THREAD

**Issue by Verbzz** [InZidiuZ/op-framework-issue-tracker#365]
Reporter:
Verbzz#1558 | https://steamcommunity.com/id/vLostSoul/

Summary:
Nissan Titan cant change livery.

Steps to Reproduce:
Just a little fix in the coding

Expected Results:
Nothing much just so i can change the livery on the car.

Actual Results:
Fixed livery issue

Screenshots:
Game: https://gyazo.com/237961ac536a08d263625e613f4071ac | F8: https://gyazo.com/284638c5acede7246b80a13b936d1f1f

Game Resolution:
1920x1080

Player Data:
https://gyazo.com/e69bb25746cb6274209892e52cddf5e7

**Comment by InZidiuZ** [comment]
Hey,

This is not a bug report.

**InZidiuZ**
*OP-FW Developer*
