### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#366]
**Reporter:**
Who is reporting this? nilmar#3552 https://steamcommunity.com/id/legend_nilmar/ Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing. i rebought the engine 4 upgrade twice 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue. buy the upgrade again when already bought

**Expected Results:**
What are the expected results? not beeing able to buy the upgrade when already bought

**Actual Results:**
What are the actual results? u buy it again

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution? highest

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Closing as you failed to fill in the template *and* I won't be making any changes to the ls customs for the time being as it's set to be rewritten at some point in the future, and it's a mess currently.

**InZidiuZ**
*OP-FW Developer*
