### ISSUE TITLE
Rule suggestion

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#367]
**Name:**
DegenTheo#2209

**Summary:**
Greenzones at garages. Greenzone would not be "active" if the rp is started outside of the greenzone. This would mean if you are being chased and you run in to a greenzone it work protect you.

**Reason:**
Right now some people camp garages for people to pull out storage cars and then they try to rob you. It is very bad rp and just ruins for people.

**Comment by InZidiuZ** [comment]
Hey,

This is for framework-related/development suggestions, not rules.

**InZidiuZ**
*OP-FW Developer*
