### ISSUE TITLE
PDM

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#368]
**Name:**
Cricketx818

**Summary:**
Hey, So I Know It's probably getting really annoying on me asking about PDM stuff to get fixed, but the reason why I Am asking is because people keep leaving PDM from the way the payout works.

This is what I really recommend For PDM to have So here are a couple options.

So right now the Commision rate is %15 Max you can put, Witch is perfectly normal so nobody gets scammed.
1)I personally Think If a Salesman/Apprentice/Senior Salesman Sells a car, I think they should be getting at least %95 of the commision they put on the car.
So my Suggestion is, Make all Employees get %95 of the %15 commision they put, & have the Boss get the other %5 of Every sale that gets sold **with** Commision.

2) Or Have PDM have its open Bank account & have the owner have access to it, to give Everybody Bonuses or Raises if Needed.

Also PDM workers should have a better paycheck.

Apprentice Should get $35
SalesMan should get $40
Senior Salesman Should get $50
Assistant manager should get $65
Boss should get $75+

Paychecks Matter on which way you choose to change up PDM.

**Reason:**
The reason why I want it to be changed like this is because, I have noticed a lot of people get very very exited for working for PDM and then they find out how BAD the payout is, and they just wanna quit because they are not allowed to do any other jobs such as banks and stuff.

I think this will be a GREAT change if it is made, & PDM will have a HUGE plus if it was changed to this.

Please let me know Thank you :)

**Comment by ZurxeyH** [comment]
I agree with this. This job goes hand and hand with SASP.

It's such a great feature into the servers, and yet it feels it's been very neglected.

**Comment by InZidiuZ** [comment]
Hey,

Balancing changes to PDM has since been made.

**InZidiuZ**
*OP-FW Developer*
