### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by skyy-reginald** [InZidiuZ/op-framework-issue-tracker#370]
**Name:**
Skye

Discord: Skyy#1536

**Summary:**
Trying to enhance rp on legacy by making it not all about robbing people. 

**Reason:**
I think if it is possible to make it where you can only rob people if x amount of cops are online. It will make people rp more and not be so on edge about being robbed all the time. You could do this different ways such as having an indicator that shows a way to show how many cops are on. example have a SASP text in yellow if 1 cop is on and have SASP text green if 2 or more are online that way people still don't know how many cops are on. That way it can still be "costly" to rob people because you would still need to buy handcuffs, but they can't be used until the 2 cops are online. I think this will let people not be so on edge about being robbed and can help with rp more. You won't see people having their gun out constantly (hopefully).

**Comment by dreamviz** [comment]
Please consider this. This will force people to RP. I'd like to be able to walk up to anyone and not have to worry about what I have on me incase all they want to do is rob instead of RP.

**Comment by Aesfy** [comment]
+1 Please consider this! It would be so great to rp with people and not worry about being robbed. I have had to where people have ran away from me because they think im gonna rob them when all im tryna do is talk to them and have a conversation.

**Comment by Kurtuno** [comment]
+1 I have to give this the thumbs up! 

I've personally experienced this in another roleplay server and that was truly one of the better parts of the server. 

It allows more interactions without the thought of being robbed. Leads to better roleplaying, more roleplaying and less staff cases. All round I don't see an issue with this and I think it'll only benefit the community!

**Comment by HybridSquirrels** [comment]
+1 to this also! RP needs to improve in Legacy right now and the main way to do that will be to reduce opportunities for easy money crim activities....eg make people think how to do something, so by putting things in small 'fencing' restrictions it can only make that better

**Comment by iGreatWhite** [comment]
+1 I would also like to walk up to people without thinking twice what I have on me and micro managing 24/7. Also with this robbing at places like weed farm/process/sale | coke pickup/sale should be robbable no matter the case being drug locations.

**Comment by InZidiuZ** [comment]
Hey,

This is more of a community problem, more than a framework one. Adding this also seem like a very unnecessary, overly complicated & lazy solution to this issue.

**InZidiuZ**
*OP-FW Developer*
