### ISSUE TITLE
[Phone Suggestion] DOJ APP

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/op-framework-issue-tracker#372]
**Name:**
Who is suggesting this? Please include discord name.
th3finalgamer

**Summary:**
Write a short summary of what your suggestion is about.
DOJ app that allows people to see the penal code, might be helpful for new people into the city 
might be good if we could get it to be a link to a website like in story mode but don't know how hard that would be 

**Reason:**
Why would your suggestion be a good addition to Legacy?
So police officer don't get accused for making things up like no open carry, if its clearly stated somewhere for the public to be then maybe it will stop rambos running around with shotguns

**Comment by InZidiuZ** [comment]
Hey,

This most likely wouldn't be placed on the phone, but on a separate UI, together with the "CAD"/public records.

**InZidiuZ**
*OP-FW Developer*
