### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#375]
**Reporter:**
Cyberskunk#5173 - https://steamcommunity.com/id/lankovich/

**Summary:**
Keep falling through the map when ever I get inside one of the entrances to MRPD.

**Steps to Reproduce:**
So you fall through the ground when ever you go in on the front side or the back side, you "respawn" somewhere close 9/10 times and just walk in again through the entrance and you'd fall again.

**Expected Results:**
To walk like a normal man on the floor heh.

**Actual Results:**
Falling through the ground/floor into the "nowhere".

## Additional Information

**Screenshots:**
It's hard to screenshot it in a good perspective.

**Game Resolution:**
1920x1080 60Hz

**Player Data:**
1942 - Job Data: Law Enforcement, SASP, Trooper.

**Notes:**
Seems to work after you'd made a hardnap ones or twice.

**Comment by InZidiuZ** [comment]
Hey,

I'm unable to replicate this locally, guessing it's cache-related issues, so try clearing your cache and see if that does anything.

**InZidiuZ**
*OP-FW Developer*

**Comment by Lankovich** [comment]
> Hey,
> 
> I'm unable to replicate this locally, guessing it's cache-related issues, so try clearing your cache and see if that does anything.
> 
> **InZidiuZ**
> _OP-FW Developer_

Okey, I'll check it out. 

OBS. There was a suspect in the exact same time also having this issue. But I will check it out, and thanks for a fast reply, InZ!
