### ISSUE TITLE
Luxart Vehicle Control

### ISSUE THREAD

**Issue by Doughnut2001** [InZidiuZ/op-framework-issue-tracker#376]
**Name:**
Doughnut#1718

**Summary:**
More siren control for emergency services

**Reason:**

https://forum.fivem.net/t/release-luxart-vehicle-control/17304

I feel like this would be a great addition to emergency services city-wide because the codes have changed, now making us sound our bullhorn every time we go trough an intersection, wich is almost impossible because of how vanilla GTA sirens work, now we have to hold down the horn key (E by default) wich most of the time turns off the whole lights and siren system forcing us to drop code 2 and go without lights at all, i feel like this would be amazing to avoid crashing into locals and others, it would also avoid a strike from pd for jumping red lights without going code 2, it would be great for the sake of realism, convenience and overall fun that people in the city will have while using this, a lot of people that i know on pd and i would love to see this implemented and it's very easy to install into the server too, drag and drop to server resources, add a copy paste line onto the server.cfg, and change the keys in the plugin cfg file if needed, (the instructions are on the link, it's pretty much the same) i really love this community and it would be amazing to see this, thanks in advance! 

P.D. 
I suggested this in the past but got a response saying; not now, maybe later. 
Perhaps now is the time? 
Thanks.

**Comment by Lankovich** [comment]
I totally agree on this one! I've checked the sound and all that on it as well and it sounds even better then any of the soundmods I've heard of so far! This would make it a lot easier for everyone of us in the EMS/PD.

+1

**Comment by InZidiuZ** [comment]
Hey,

We've now added 'Luxart Vehicle Control', so this issue is hopefully resolved now.

**InZidiuZ**
*OP-FW Developer*
