### ISSUE TITLE
Identification for Attorneys

### ISSUE THREAD

**Issue by Kurtuno** [InZidiuZ/op-framework-issue-tracker#377]
**Name:**
KurtUno#0007

**Summary:**
Currently attorneys have no real way of identifying themselves to the Police Department, realistically the only way the Police Department can verify the legitimacy of the Attorney is to check Discord, which in some sense is taking out of game knowledge into an in-game scenario. 

I propose that we offer Attorney ID Cards OR edit the current ID cards and introduce an Attorney Title. (In the same area shown as Unemployed, Government etc.  

**Reason:**
We currently have no way to know if someone is an attorney or not, and increasingly this becomes a security risk to allow non-government officials to represent people or into confidential areas such as the Cells. 

Alternatively, we could bring the Attorney Whitelist role back, as it genuinely makes for some entertaining role-play. Whether or not this is the plan further down the line, I do think at-least adding an identity card would be beneficial in the present moment.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added. Once a proper law/legal system is implemented this most likely won't be an issue.

**InZidiuZ**
*OP-FW Developer*
