### ISSUE TITLE
Suggestion PD Armory

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/op-framework-issue-tracker#379]
**Name:**
Who is suggesting this? Please include discord name.
Sercan#0001

**Summary:**
Adding shotgun to the armory.

**Reason:**
Let the officer to choose between a shotgun and SMG. Give swat a different weapons to make them different as they are called Special Weapon And Tactics.

**Comment by Vexzarkov** [comment]
This would be needed and carbine rifle as well.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
