### ISSUE TITLE
Life Invader Job Selection

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#381]
**Name:**
Who is suggesting this? iGreatWhite#3018

**Summary:**
 Be able to have a selection of jobs including whitelisted positions if allowed. Such as being accepted to PDM would allow you to do other jobs besides PDM in off-time as a second job. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
This way people who are PDM and other whitelisted jobs have another line of roleplay they can do besides being restricted to always being PDM and never another job unless they resign.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added.

**InZidiuZ**
*OP-FW Developer*
