### ISSUE TITLE
CAR CHANGED AFTER SAVING IN  GARAGE

### ISSUE THREAD

**Issue by TricksterClown** [InZidiuZ/op-framework-issue-tracker#382]
**Reporter:**
HELLO SIR I'M PRIYANSH JHARWAL MY DISCORD ID IS TRICKSTER#0337 AND STEAM ID IS PROVIDED IN THE SCREENSHOT BELOW IN APPROPRIATE ORDER.

**Summary:**
I BOUGHT A CAR FROM PDM ABOUT 2 WEEKS AGO AND MODIFIED CHANGED ITS COLOUR AND HAD A CAR WASH TO IT, THA CAR WAS ON FINANCE 100K IT WAS A NERO SPORTS VERSION AND AFTER ALL THE MODS AND STUFF I SAVED IT INTO THE GARAGE C WHERE I STORE ALL MY VEHICLES SO AFTER I STORED IT I AGAIN CAME AND WANTED TO GET MY CAR OUT BUT AFTER OPENING VEHICLE LIST IT SHOWED ME VAPID DOMINATIOR SO NOW
THE VAPID DOMINATOR HAS THE SAME COLOR AND ENGINE MODS WHICH I APPLIED TO MY NERO BUT MY CAR GOT CHANGED AND NOW IM STUCK WITH NO SOLUTION I INFORMED THE RESPECTED AUTHORITIES OF LEGACY ROLEPLAY INDIA Mr.RaviCant and HE TOLD ME TO SUBMIT THIS REPORT SO IM REPOTING MY ISSUE HERE DEV.
**Steps to Reproduce:**
SIR WHAT EVER ACCORDING TO DEV IS FINE TO ME.

**Expected Results:**
SIR EITHER I GET MY CAR BACK IN MY GARAGE WITH COLOUR AND MODS I GOT IT WITH OR EITHER IF DEVs CAN COMPENSATE ME THE MONEY I INVESTED IN MY CAR WHICH INCLUDED 40K CHARGES AND THE FINANCE OF 100K AND MODS , I PAID 40K TO THE PDM DEALER SIR APART SIDE AND THE PDM DEALER WAS MR. RAVICANT ONLY SIR HE ONLY INFORMED ME THAT HE BY HIMSELF SOLD ME THE CAR SO YOU CAN ALSO CROSS CHECK SOME STUFF FROM HIM DEV.  

**Actual Results:**
CURRENTLY CAR IS SITTING IN MY GARAGE RECKED xD  SO IM ALWAYS ACTIVE WITH PROBLEM IN RP SO IM EXPECTING SOMETHING GOOD NEWS FROM DEVs.

## Additional Information
SIR I BOUGHT THE CAR AND THE MONEY DID GOT DEDUCTED I WAS HAVING APPROX 250K APPROX INGAME CASH AND AFTER BUYING I HAD ONLY 110K CUZ I PAID 40K TO PDM AND 100K FOR CAR THATS IM SURE ABOUT 
**Screenshots:**
screenshots are included sir while before going into the support of legacy 
![Screenshot (94)](https://user-images.githubusercontent.com/54229815/63418591-fcc0c480-c420-11e9-8651-9109a23d8760.png)
![Screenshot (95)](https://user-images.githubusercontent.com/54229815/63418595-ffbbb500-c420-11e9-818a-2db808629819.png)
![Screenshot (96)](https://user-images.githubusercontent.com/54229815/63418599-00ece200-c421-11e9-95d3-7deb40b7c6e1.png)
![Screenshot (97)](https://user-images.githubusercontent.com/54229815/63418601-021e0f00-c421-11e9-8d20-99539987363f.png)
sir all the screen shots are here  one is with the car in my garage list and the car itself which got exchanged or changed idk and my steam id and my f8 key console ss sir 

**Game Resolution:**
2560X1440p

**Player Data:**
no info just car sits in garage as if i bought the same one but i bought the nero and it changed into vapid dominator 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

PLEASE DO NOT USE CAPS LOCK WHEN CREATING A BUG-REPORT. THANKS!

**InZidiuZ**
*OP-FW Devleoper*
