### ISSUE TITLE
Cooldown on changing your job

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#383]
**Name:**
Who is suggesting this? Please include discord name.
@KaiEagle#2469

**Summary:**
Write a short summary of what your suggestion is about.
 If you take or change your Job you should have 24 hours (1day) or 1-week cooldown.. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
This would help mechanics to do their jobs...

**Comment by InZidiuZ** [comment]
Hey,

This won't be added for the time being.

**InZidiuZ**
*OP-FW Developer*
