### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ritaxe** [InZidiuZ/op-framework-issue-tracker#384]
**Name:**
REINCARNATE#2388 

**Summary:**
Nothing to be able to do basically in server if there's no PD. 
**Idea**:- Make Streamer Meetup with Proper security and stuff so that feels as if there's like Hollywood actors and stuff in the game/ optionally Mayor's Press Meet and Stuff as well and the other in game players can try to get to  Mayor and PD protects him. 

And for PD just give them Working Shift in real Life per 6 hours. Like 8-10 guys in this server from 12Pm to 6pm IST and stuff. Just get the Police department more organized. 

And rules to not randomly shoot bullets if there's no reason otherwise people will be arrested. 

**Reason:**
It saves us from Boredoom

**Comment by iGreatWhite** [comment]
There is alot to do besides do stuff with PD man. Just gotta create the roleplay for yourself

**Comment by InZidiuZ** [comment]
Hey,

This is not really a framework suggestion. I can't see it being, at least.

**InZidiuZ**
*OP-FW Developer*
