### ISSUE TITLE
Nerf Punching and Kicking

### ISSUE THREAD

**Issue by SkippingBaboon** [InZidiuZ/op-framework-issue-tracker#385]
**Name:**
SkippingBaboon

**Summary:**
Make punching and kicking against locals, other players, and vehicles less powerful.

**Reason:**
Most fist fights consist of 1 or 2 punches landed, unless wearing body armour, and feels very much like RNG as to the damage caused.  Using the SPACE bar to dodge punches isn't strong enough as a function, you could land 2 punches, dodge 2, then get hit with one and its game over. This function would still be hugely beneficial to use over the course of a fight, especially as there is no way to block a punch, as the fights would last longer, there would still be a higher probability that the person that managed to evade being hit as much would come out as the winner of the fight. 

I feel with less powerful punching and kicking, it would create cool RP scenarios. Fist fights would appear more realistic. Fight Club ideas would become better as fights would last out. Less people will be "accidentally" knocked out/killed by people that "accidentally" punch or kick someone, which can be a common occurrence in the City.

I will also add that I also feel the damage that can be caused to vehicles using bare hands is far too extreme, could also be reduced.

Overall, I cannot see how these changes could cause a negative effect.

**Comment by InZidiuZ** [comment]
This has already been suggested in #197.
