### ISSUE TITLE
Character issues

### ISSUE THREAD

**Issue by alekslucius** [InZidiuZ/op-framework-issue-tracker#386]
**Reporter:**
Aleks#4118
https://steamcommunity.com/profiles/76561198119676871/

**Summary:**
I continuously have to delete one of my character slots, because it continues to pop back up despite me removing it, I can only delete, but can't play as that character.

**Steps to Reproduce:**
create a character, and attempt to delete it.

**Expected Results:**
The character slot does not remove the character;.

**Actual Results:**
The character does, not delete, and continuously appears.

**Comment by InZidiuZ** [comment]
Hey,

Can you confirm whether you're still having issues with this or not?

**InZidiuZ**
*OP-FW Developer*
