### ISSUE TITLE
About PDM

### ISSUE THREAD

**Issue by nikgoud-del** [InZidiuZ/op-framework-issue-tracker#387]
**Name:**
nik_goud#2294

**Summary:**
As i can see there are 2 places to buy cars one is bugged mostly and other needs a pdm to choose different cars . In indian legacy servers they appointed 10-12 pdm but hardly i can see 2-3 online playing other games . and always when i reach the pdm to buy a car i can see 8 slots with random costly cars whithout changing while im in whole servers making people difficult to buy them and forcing all to do GTA stuff by stealing cars for mobility. ive been playing in all servers and im unable to buy a vehicle till now . i suggest either make pdm user interface easy so that every individual can browse all vehicles and buy  at his price or make it legal to steal cars because even after earning some money and unable to get a vehicle because of these pdm people unavailable and keeping costly cars we are not intrested to walk through whole city or use taxi 24/7 spending all money. 

**Reason:**
either removing pdm staff or replacing with regular online staff or removing that job and making it available to all helps every one using their own vehicle to do their small jobs and mobilty in city instead of stealing cars and getting caugh by police and having fines and sending to jail . this thing will be in a cycle process if you guys dont take any action in indian servers . i hope you understand and make this easy for people

**Comment by iGreatWhite** [comment]
The PDM boss of the Indian server needs to make sure his staff is active if you feel this is a continuing problem contact your staff team it’s not entirely a GitHub issue

**Comment by InZidiuZ** [comment]
Hey,

This is not a suggestion for the framework.

**InZidiuZ**
*OP-FW Developer*
