### ISSUE TITLE
Add Jester Classic to PDM Dealership

### ISSUE THREAD

**Issue by ryz0o** [InZidiuZ/op-framework-issue-tracker#389]
**Name:**
ryz0o#3471

**Summary:**
The Jester Classic is the GTAV variant of the Supra, it's a balanced car and is very customizable and beautiful.

**Reason:**
It's a needed car, for those that like having tuner-like vehicles. I'm sick of seeing only Elegy Customs around the cities, it's time for another addition for the custom cars.

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

**InZidiuZ**
*OP-FW Developer*
