### ISSUE TITLE
Fix offset on GTR for cosmetic upgrades.

### ISSUE THREAD

**Issue by meeksbtw** [InZidiuZ/op-framework-issue-tracker#390]
**Name:**
#Meeks5150

**Summary:**
Fixing the wheel offset of the import GTR with cosmetic upgrades such as, Liberty Walk, Rocket Bunny, etc Liveries / upgrades that puts a wide body kit on the car but, the wheels do not match up. The GTR that Karpenko imported has all of the liveries but he had to disable them due to this reason. I requested this topic on the other git-hub about a week or so ago, I've been talking with Karpenko and he says there is no way for him to fix it and told me to contact Ben so, now I am here. I would assume this would be a quick fix but what do I know :P 

https://www.gta5-mods.com/vehicles/2015-nissan-gtr-nismo-yca-y97y

**Reason:**
The cosmetic upgrades of any import car is really needed and the liberty walk kit is one of the best looking kits.

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

InZidiuZ
OP-FW Developer
