### ISSUE TITLE
We need more emotes

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#391]
**Name:**
Randy James #4851

**Summary:**
Can we get more emotes/more dances. Emotes is such a good way to immerse into a conversation. Its just adds a good experience.

**Comment by InZidiuZ** [comment]
Hey,

Emotes are constantly being added as we go, some by Cricket are to be added soon. If you have more specific suggestions, feel free to create another issue, but closing this as it's fairly vague, and more emotes has since been added.

**InZidiuZ**
*OP-FW Developer*
