### ISSUE TITLE
[jobs/police] Police impounding

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-issue-tracker#392]
**Name:**
Who is suggesting this? Please include discord name.
SATIN187#0187

**Summary:**
Write a short summary of what your suggestion is about.
I think that police should have the ability to impound cars for a certain length of time anywhere from a day to months or extreme cases be able to take the car away from a person permanently 

**Reason:**
Why would your suggestion be a good addition to Legacy?
I think this could add in some good roleplay by making people think twice about using their own car to rob banks cause they could potentially lose their car. This I believe could help balance cop chases after robbing a bank due to people using the lambo and cops have nothing that can keep up

**Comment by iGreatWhite** [comment]
The permanent impound should have to be approved before happening. I don’t agree on that fact the rest is just fine. +1

**Comment by SATIN187** [comment]
Yeah I’m not saying a cop can just do it but like it would go through chain of command to higher ups to be approved and only they would be allowed to do it type of stuff

**Comment by twooot** [comment]
Uhm we have an impound feature now, (3 years later kekw)
