### ISSUE TITLE
"Custom Tires" don't save properly

### ISSUE THREAD

**Issue by Wrothgar** [InZidiuZ/op-framework-issue-tracker#394]
**Reporter:**
Wrothgar#1293
Wrothgar

**Summary:**
“Custom tires” option under wheel accessories does not stay, it reverts back to stock tires after the car is stored.

**Steps to Reproduce:**
Purchase the custom tires option and store vehicle.

**Expected Results:**
Custom tires should stay

**Actual Results:**
Reverted back to stock tires 

## Additional Information

**Game Resolution**
1920x1080

**Player Data:**
Character ID: 463 - Job Data: mechanic, los Santos customs, tow driver

**Comment by KoreeXD** [comment]
I agree this should stay

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved.

**InZidiuZ**
*OP-FW Developer*
