### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Foster1810** [InZidiuZ/op-framework-issue-tracker#395]
**Name:**
Who is suggesting this? Please include discord name.
Foster
**Summary:**
Write a short summary of what your suggestion is about.
Add a club like building where people can hangout.
**Reason:**
Why would your suggestion be a good addition to Legacy?
If you can add a club like building where people can hangout  then it will be helpful for people who want to meet other people (Those who want to make new friends or for interaction with people ). The hospital will also be clear as the hospital is being used as a meeting point.

**Comment by SATIN187** [comment]
There’s already a strip club in game people can go to

**Comment by InZidiuZ** [comment]
Hey,

There already are tons of locations you can "hangout"...? 🤔 

**InZidiuZ**
*OP-FW Developer*
