### ISSUE TITLE
Bug (24xCoke Bag got replaced by 24xKeys of same vehicle)

### ISSUE THREAD

**Issue by BlurryGiri** [InZidiuZ/op-framework-issue-tracker#397]
I processed my 3xCoke Brick into 24xCoke bag , and returned to city to store it in my van , but when i reached, and opened my inventory it was changed into 24xKeys of same vehicle.

My Steam ID - https://steamcommunity.com/id/56iri97/

![20190826102108_1](https://user-images.githubusercontent.com/54522750/63666393-f483d300-c7ec-11e9-8ea9-234310583be4.jpg)

**Comment by SATIN187** [comment]
Unstack the keys and leave your inventory and go back in they should come back as the coke

**Comment by InZidiuZ** [comment]
Hey,

Missing template.

**InZidiuZ**
*OP-FW Developer*
