### ISSUE TITLE
Repair shop at The Lost MC

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/op-framework-issue-tracker#398]
**Name:**
Who is suggesting this? Please include discord name.
th3finalgamer

**Summary:**
Write a short summary of what your suggestion is about.
I know you have added the lost mc garage, wondering if we could get repairs over the ls custom.

**Reason:**
Why would your suggestion be a good addition to Legacy?
lost mc is mechanics repairing things would make more sense for them over body shop :)

**Comment by ZurxeyH** [comment]
There are a lot of places that need repair shops, if Ben continues to add them the map will be flooded.
