### ISSUE TITLE
Livery resets

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/op-framework-issue-tracker#399]
**Reporter:**
Kiwi#6887 https://steamcommunity.com/id/KiwiUK/

**Summary:**
I am financing an Elegy Retro (a none-import car). I decided to put a livery on it about a week ago. Recently I had some issue with the police IC, so decided to change it up. I tried to change or take the livery off but after doing so and repair the car, the livery would come back.

**Steps to Reproduce:**
So far I know of two ways, the first would to repair your car after taking it off and the second would be to put the car in your garage, then take it back out.

**Expected Results:**
I expect the car to be without the livery after taking it off.

**Actual Results:**
The car still has the livery on after taking it off.

## Additional Information

**Screenshots:**
![gg](https://user-images.githubusercontent.com/54548483/63708130-772b8300-c82b-11e9-9642-13ff0b4110ea.PNG)

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 8084-Job Data: Mechanic, Los Santos Customs, Tow Driver

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
