### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Willgallagher22** [InZidiuZ/op-framework-issue-tracker#400]
**Name:**Will Gallagher (WACCOON)
Who is suggesting this? Please include discord name.

**Summary:**
(1) I want to seen more rarity with the exclusive cars, i feel like everyone and there grandmother 
     has a super car whats not realistic at all, I honestly think if anyone complains that this is 
     stupid is not here for Role play at all. The high tier cars should be available to buy but by a 
     certain high command staff members but only a certain amount of Lambos, Nissan GTR's, 
     Ferrari.

(2) Moving on to Pricing there needs to be an increase in these cars to an actual hard to get 
     amount so its hard to get to keep the cars rare and exclusive.
 
(3) Maybe auctions to sell these cars off and PATREON gives access to the car auctions.

!!! Im sorry if i come across a bit harsh but if people complain they need to go to GTA online and stop crying when they only care about buying cars, IT NEEDS TO BE RARE!!!!!

**Reason:**
When im roleplaying i want to see less rare and exlusive cars so im suprised. Nearly everyday i see 10+ just from one city, its not realistic at all.

**Comment by InZidiuZ** [comment]
Hey,

Guessing there'll be more rotation in the future, to not have everyone use the same cars constantly. But, the two options you suggested aren't very feasible. Increasing the price isn't really going to get us far, it'll only cause more farming & worsen the feel of the economy. Auctions would also constantly require someone to do them, which will be hard to constantly organize both on our main server, as well as the subdivisions.

**InZidiuZ**
*OP-FW Developer*
