### ISSUE TITLE
Bag O' Money

### ISSUE THREAD

**Issue by 7uurbo** [InZidiuZ/op-framework-issue-tracker#402]
**Name:**
@7urbo #0007

**Summary:**
I suggest for bank robberies, the guy that is stealing the valuables and money in the bag, comes out with a duffel bag around his character, or have a duffel bag a purchasable item at the mega mall and they have to bring that with as well to robberies.

**Reason:**
I believe it would be a good addition to Legacy because it'll add a sort of immersive-ness to the robberies. People right now just walk out with $20k in cash should be put in a bag. It would add a little bit more risk into robberies and getting away.

-Expanded Notes-
 -With the duffel being purchasable, it could be coded to where they fill the duffel with money and then it'll put a duffel on the guy with the money and appear as a full bag of money in the players inventory. It could allow players to keep money in their apartments in full duffel bags, to sit on money or save it. To get the money out of the bag, they could "use" the item, then the cash would then be in their pockets.

**Comment by y0Razz** [comment]
Would be cool to get items aswell instead of only money.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added.

**InZidiuZ**
*OP-FW Developer*
