### ISSUE TITLE
The Ubermacht Sentinel Classic

### ISSUE THREAD

**Issue by Pizzzaa** [InZidiuZ/op-framework-issue-tracker#403]
**Name:**
Luis Siul "in-game" ... Pizza #2928

**Summary:**
I uprageded it fully engine/turbo... and that car hits only 130mph. Went around the same before upgrades.

**Reason:**
Every second car goes faster when you buy it without upgrades than mine.

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

InZidiuZ
OP-FW Developer
