### ISSUE TITLE
Have AFK players be automatically kicked

### ISSUE THREAD

**Issue by ZaczrG** [InZidiuZ/op-framework-issue-tracker#405]
**Name:**
ZaczrG#0702

**Summary:**
Its about kicking the players that go Away From Keyboard (AFK) for more than 2 minutes.

**Reason:**
It would be a great addition, as you know a lot of players wait like an hour just to get in 1 server. I have noticed some players just standing around and me going to them and talking but they wouldn't respond and would be AFK. So it would be a nice idea to implement this in the server so other players could join once a player goes AFK for more than 2 minutes? You can keep the minutes by yourself whether it would be 1, 2 or 5... That's it easy and simple.

**Comment by Cironite** [comment]
+1 Maybe not 2 mins, but a little higher like 5 or 4 but this would be a nice addition to stop people from AFK'ing.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. After 10 minutes of standing still & not talking, you'll receive a message saying you've been detected as 'AFK', and will then have another 5 minutes to move.

**InZidiuZ**
*OP-FW Developer*
