### ISSUE TITLE
Gtr nismo kit

### ISSUE THREAD

**Issue by kreg423** [InZidiuZ/op-framework-issue-tracker#406]
Melvin East

I would like for the GTR to have the nismo kit enabled as it is currently disabled. I spoke to karp about it, he thought it was already available but it wasn't. I know the mod file has the nismo kit and would be nice we can have the option to customize it to the nismo package.

It would give people the option to customize their gtr how they want, so everyone isn't driving the generic standard version of it.

**Comment by SATIN187** [comment]
You’re gonna wanna our that in he assets GitHub 

https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**Comment by iGreatWhite** [comment]
I moved his issue over to the Assests Tracker. Melvin you can comment anything I missed on the post in the assets tracker

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

InZidiuZ
OP-FW Developer
