### ISSUE TITLE
Bug report- Vehicle not moving forward after completing cocaine mission( it was parked beside hangar the whole time)

### ISSUE THREAD

**Issue by JamesBond2003073** [InZidiuZ/op-framework-issue-tracker#407]
**Reporter:**
Discord-James Bond#1160
Steam - James Bond

**Summary:**
Whenever I park my vehicle outside the hangar at cocaine airfield,lock it, and then go and complete the mission and then try to drive the vehicle , the vehicle doesn't move forward or backward it gets stuck but if it's a bike it moves only backwards (something to do with the engine maybe). This happens everytime. I have checked the engine is on and fuel is there.

**Steps to Reproduce:**
Take any vehicle to the cocaine airfield and park and lock it beside the hangar. Complete the cocaine mission and try to drive the vehicle. It will not move forwards and only move backwards. 

**Expected Results:**
The vehicle should move in all directions and don't get stuck after completing cocaine mission.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920*1080

**Player Data:**
Character ID:11249
Job Data: Government,Waste collector,employee.
Timestamp: 2019-08-29 02:58:33

**Notes:**
IN CASE OF BIKE IT MOVES BACKWARDS BUT NOT FORWARD. So this most probably has something to do with engine. Even when the engine is on its not working.

**Comment by iGreatWhite** [comment]
This used to be a bug for me. But not anymore it works flawlessly.
This was also reported before but inzidiuz said he could not replicate it locally so it has to do with multiple clients more than likely.

**Comment by JamesBond2003073** [comment]
@iGreatWhite can you explain how to fix this bug?

**Comment by InZidiuZ** [comment]
Hey,

Guessing it's related to the tuner-chip, as I haven't had anyone report this since they were disabled. Will look into it again once the tuner-chips are re-enabled with the next update, which will let me confirm whether that's the cause or not.

**InZidiuZ**
*OP-FW Developer*
