### ISSUE TITLE
Impound system Improvements.

### ISSUE THREAD

**Issue by Vexzarkov** [InZidiuZ/op-framework-issue-tracker#408]
**Name:**
VexZarkov#0359

**Summary:**
Id like to see the impound system have a 
/ImpoundCivil for every day impounds ect  and a 
/ImpoundCriminal  for cars involved in major crimes IE bank jobs

**Reason:**
Too many people go around with personal cars to grind banks with it and it adds a unfair level of RP mechanics. this would make criminals think twice of takeing that new lambo ect as a getaway car as the risks will be higher, a larger Fee for a criminal impound option will make the risks higher for taking your own car to a bank job one idea on how to do this is a large impound fee  or the owner will need to pay 1/3 of the cars total sticker price from when they bought it at PDM

**Comment by y0Razz** [comment]
+1

**Comment by HybridSquirrels** [comment]
+1

**Comment by TwoplePop** [comment]
this is absolutely needed

**Comment by InZidiuZ** [comment]
Hey,

At this time, this will not be added.

**InZidiuZ**
*OP-FW Developer*
