### ISSUE TITLE
New Job - Post/Parcel Delivery Man

### ISSUE THREAD

**Issue by HybridSquirrels** [InZidiuZ/op-framework-issue-tracker#410]
**Name:**
HybridSquirrels #2899

**Summary:**
In the interest of getting more fun non crim RP and adding to job centre some more, I would like to have a UPS type courier/postman job made 

**Reason:**
To give variation in the amount of legal jobs people can do if they choose to, it can work almost exactly like garbage job but you get paid per letter dropped maybe. The building already exists for spawning on Hawick. Legacy needs to continue to create more non-crim focused jobs and this is a nice easy one to do.

**Comment by InZidiuZ** [comment]
Hey,

This was added a couple of updates ago.

**InZidiuZ**
*OP-FW Developer*
