### ISSUE TITLE
Able to access inventory while dead with the help of a dropped bag

### ISSUE THREAD

**Issue by DrHenny** [InZidiuZ/op-framework-issue-tracker#411]
**Reporter:**
https://steamcommunity.com/id/HennessyBae

**Summary:**
Well.. when you're dead if theirs a bag near your body (inventory (7 key)) you can pass your friends items (can be abused when dead while arrested, being robbed and so on)

**Steps to Reproduce:**
Just some kind of check where if you're dead you can't press key 7 to access the bag?

**Expected Results:**
Fix or remove inventory handling while dead.

**Actual Results:**
Umm? 

## Additional Information

**Screenshots:**
N/A

**Game Resolution:**
Default

**Player Data:**
https://gyazo.com/e5398b3d64a86943103da56f5d7ed9e1

**Notes:**
Nothing :)

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
