### ISSUE TITLE
Skill Levels for activities

### ISSUE THREAD

**Issue by DrHenny** [InZidiuZ/op-framework-issue-tracker#412]
**Name:**
DrHenny#0001

**Summary:**
Implementation of "skill levels" for miscellaneous activities 

Activity list (more can be added):
- Mechanic Job (Towing & Repairing)
- Picking Weed
- Collecting Cocaine
- Processing Drugs

How it would work:

Brief Summary:
The more you do the activity the more XP you gain. The more XP you gain the higher the level you receive. (Capped at Level 5 or 10) The higher level you are the faster you can do the activity (the time it takes to repair, pick or process).

(**Mechanic Job**):
Every time you repair a part of your car (can scale depending on the part) you gain X amount of XP. 
(**Picking Weed**):
Every time you pick 1x Weed you gain XP
(**Processing Drugs**):
Every time you process a brick or turn 4x 1oz you gain XP.
(**Collecting Cocaine**):
Every run you do, you gain XP.

**Reason:**
Why would your suggestion be a good addition to Legacy?

It wouldn't necessarily be for RP. It would be based on realism. A skill you can call it. We all know the more you do something 
(Example):
 Shuffling cards. When you first start out you're slow, the more you do it the faster you become and the less headache it is.

**Other notes:**
If you need more information on this or want to see a design of XP/Levels feel free to reply or directly message me on discord.

**Comment by Aspratic** [comment]
I like the idea but i think there needs to be more depth to this. I feel like there can be more to this than just doing it faster but i like the premise

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
