### ISSUE TITLE
Oxygen bar expands *a lot*

### ISSUE THREAD

**Issue by DrHenny** [InZidiuZ/op-framework-issue-tracker#413]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Just a visual bug I assume? the bar at the bottom for oxygen is bugged when you do this action

**Steps to Reproduce:**
Drive a jetski, go to the X, while you're on the jetski and have your belt on put on a tank and it should work

**Expected Results:**
Should be able to recreate the bug

**Actual Results:**
umm

## Additional Information

**Screenshots:**
https://gyazo.com/9578c1bd0771ce83fc2028c1aa1f20d6

**Game Resolution:**
Default

**Player Data:**
https://gyazo.com/19f2a218e325728659a93e7104318787

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
