### ISSUE TITLE
Vehicles Despawning upon fix in the Repair shop.

### ISSUE THREAD

**Issue by whateversosa** [InZidiuZ/op-framework-issue-tracker#416]
**Reporter:**
Who is reporting this? whateversosa#5984 steam: whateversosa

**Summary:**
When you repair your vehicle at the repair shops it completely despawns your vehicle and forces you to retrieve it for the x amount of money required which is $250 not to sure what is causing this bug.
**Steps to Reproduce:**
Just fix the car

**Expected Results:**
Expected results are for the vehicle to fix and stay in the current realm where you currently are.

**Actual Results:**
The actual results are when you fix your car it is almost as if it like becomes instanced and despawns infront of your eyes and you must retrieve it for money.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
2019-08-31 22:08:01
**Notes:**
For anything else noteworthy.

**Comment by iGreatWhite** [comment]
This is a one sync issue. Just don’t repair your car on the onesync server for the time being. Which is server 3. It was mainly upped to 55 to use for an event happening.

**Comment by InZidiuZ** [comment]
Hey,

This will not be resolved for the time being.

**InZidiuZ**
*OP-FW Developer*
