### ISSUE TITLE
[jobs/*] Please bring back Butcher/Miner Job

### ISSUE THREAD

**Issue by daf4ever** [InZidiuZ/op-framework-issue-tracker#417]
**Name:**
DAF4ever

**Summary:**
Please bring back Butcher/Miner job! 
I've spoken to alof of people and many seem to agree that they all would like to have a job that has all of the following:
1. - Drive from A to B and back (or to C to D to E...), Basically drive a long distance.
2. - Use your own car
3. - A job that both players earn money at the same time
4. - Legal

**Reason:**
[Intro]
There are players that love the driving aspect of the game. Players who used to do the Butcher or the Miner Job on the old server. Currently you are very limited on the server. Since Day 1 the server has started I've been waiting for a job like Butcher/Miner.

1. Drive from point A to B. People love to drive. I love to drive. With the a driving job you are able to roleplay random races with new players you meet. With driving fast you crash more and therefore need to call the Mechanics more.

2. - Use your own car. Right now I own 3 cars that are most of the time stored in the Garage. I tried taxi driver for 6 hours and I got 1 phone call. Hardly no roleplay at all. There isnt any legal job where you can drive your own car except Taxi. There's no reason right now buying a fast car since for most jobs you drive a slow "truck-ish" vehicle anyways. I am forced to play a criminal character to pick up weed if I want to roleplay and at the same time getting money for a car and paying the apartment. It is missing on the server, a legel job where you can show off your car.

3. - A job that both players earn money at the same time. Again here I am forced to play a criminal. Options are (kinda?) Weed runs or Bank Robber. You can play with your friend and both get money, even though you mostly split yourself with your friend while selling weed. I would like to get my friends that don't play GTA on the server. While explaing the new server they both told me that there isn't a real job you can do together where both get payed out. They both want to do something with me but we cant. I mean you can both be mechanic but then you always need to split what you make. In real life when 2 mechanics go onsite, they both get payed their full wage from their garage. Same with Truck driver, you are forced to split the cash.

4. - Legal. Many characters on the server don't like to rob other players. They don't like to rob banks because it doesnt fit their character or they don't want to spend one hour sitting behind jails or doing jail roleplaying. But they do like to get pulled over by cops and have a role play scenario. 

[End statement]
Many friends and my oppinion is, that on the last Server there were 2 Driving Jobs and now you have none. We love to roleplay and grind at the same time, unfortunately the new server is only grinding. Back as butcher, there were many RP scenarios such as "Jason was camping Butcher Job and scaring people" "Two groups of players thats were enemies with each other, so you always had to be super carefull doing the job" "Cops waiting at Chicken Dropp off to catch the racers" "When I was playing with a close Friend doing the Run together" "The endless races with random players when you walked into each other". And now I am being stuck alone doing boring Garbage runs because it pays even more then doing illigal jobs like picking Weed. Please bring back a job or multiple similar to Butcher. It is definately missing on the server.

[Personal notes: Comparing Butcher vs Miner]
Butcher job was better because you stood longer in one spot and therefore you ran into more people, generating more roleplay. Both had really nice tracks. Butcher was overpayed compared to the Miner job. Once I started doing Butcher I did 90% of my job as Butcher, 10% as Miner.
For me the server turned out more grindier then the last one, because now its a pain to make money. 

[To the critics]
This is personal positive constructed feedback. 
- I know there are jobs similar (Truck driver, etc) to what I listed, but they don't come close to the Butcher/Miner job. There's no job with all the 4 requirements listed above. 
- Some people like to grind and roleplay at the same time. (Yes people like that exist)
- Yes I am aware I could rob banks but there are characters that don't want to be hardcore criminals. Again, I am talking about a job that has all 4 requirements.
- There are jobs that where 2 players drive in 1 car to the client to repair something at the clients place. Yes, where you can drive your personal car. I've had a job like that before.
- There are many new roleplay scenario's if you are a good roleplayer. Defenately more fun then doing solo Garbage runs where you lonley walk from garbage bin to garbage bin.

**Comment by JaspeSniff** [comment]
Agreed

**Comment by JaspeSniff** [comment]
Yeah I agree - a job like that is definately missing on the server

**Comment by WilsonPlays** [comment]
One of the main issues of this job which was constant was the amount of times people was being robbed whilst doing the job.  It was causing more hassle than we would like to have dealt with

**Comment by daf4ever** [comment]
@WilsonPlays Agreeable, there were many robbings going on there. But the Weed Field was more dangerous then the Butcher stop, because you spent more time there. I died way more on the fields. In the other hand, with longer stops you create more roleplay scenarios and not all of them were bad. The Miner job had short stops therefore you hardly got robbed there. Maybe somehow implement it with a shorter stop time if people are too concerned getting robbed nonstop? Or make it a safe zone? Last server had 2 jobs and now we have 0 jobs like it.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
