### ISSUE TITLE
PROMOTION TO ALL THE JOBS IN THE CITY .

### ISSUE THREAD

**Issue by BRM7** [InZidiuZ/op-framework-issue-tracker#419]
**Name:** B_R_M
Who is suggesting this? Please include discord name.
B_R_M#8732

**Summary:**
So basically all are working hard on their respective jobs in the city ,but I have noticed that only police have promotions on the basis of their hard work .Similarly all the citizens in the city do their job honestly and sincerely so why not give them promotions, so they work even more hard then they usually do. It gives more realistic feeling to the RolePlay. If there is no such promotions then what is the difference between the person who is working very very hard for more than 10+ days and The person who is new to the city ,both have same job same amount of payments.Try to add something new concept so the experienced people in the city gets opportunity to teach the respective jobs to the new people. Try keeping interviews in game so it becomes even more realistic.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding promotion in jobs means Hard work from people and the passion towards the job will inscrease. Thus RolePlay will be even more fun. If you find this Interesting please feel free to DM me. I have already planned all the promotion roles to all the jobs in the city so it will be easy to impliment later on.

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
