### ISSUE TITLE
Suggestion and a topic that needs consideration!

### ISSUE THREAD

**Issue by BlurryGiri** [InZidiuZ/op-framework-issue-tracker#421]
**Reporter:**
Blurry(56iri97#0005)

**Summary:**
Purpose Of Fake Citizen Card. IF there's no purpose of fake citizen ID then there's no purpose of keeping even real citizen ID.

**Steps to Reproduce:**
Like, if we get pulled over by officer for any speeding or not following traffic lights, and show them the fake ID. Basically, the fine or charges should be registered on the fake ID, because there's no proof that I am using wrong ID. But Officers open steam ID(#paypal number) and tell us that we are using fake ID and tell us our own name. Then the question is, if they can see through everything , know our ID and name , then whats the purpose of keeping Citizen ID. whenever we get pulled over by officer, we will say, Sir why are you asking me when you can see by yourself! 

so there are few questions that arises because of this:
1)Purpose of Citizen Card?
2)Is there any use of Fake Citizen Card?
3)If its roleplay, then how the officers suddenly know our real name even if we show them fake ID and didn't tell them our real citizenship name?

**Expected Results:**
While using citizen card, we also show our citizen number. Every Fine, charges, even while buying the vehicle should happen using that number instead of pressing key U and seeing the paypal ID or so. It will allow a whole different and interesting way to play roleplay. It will disable the power of police to just see through fake ID and know their real name(because if it doesn't remove there's no role of keeping Citizen ID with yourself).

**Actual Results:**
For every Identification and stuff. Police just see through our fake ID. So, there's no role of keeping fake ID and no actual purpose of keeping our own ID with us.

**Notes:**
Citizen number should be used as transaction and identification of a person. Police should not claim Fake ID as Fake if there's no complaint registered of lost Citizenship card.

**Comment by y0Razz** [comment]
I feel like this is a grey area.
Me personally never use the info i gather when i bill someone, i just believe that they show me their own ID. Would be kinda powergaming cause IRL you wouldn't get a pop up saying '' you billed * person * Only when PD uses the fingerprintscanner they should be able to use that info.

That being sad, if you drive in a car with a fake ID, the chances that the car won't come back to that ID is like 99% so you would be fucked anyway lol. But i get what you are saying.

**Comment by AmokBSN** [comment]
Problem is that PD don't have a CAD system at the moment to identify people they are billing, I'd say they need to take you directly to the courthouse to get an ID if they're going to arrest you and don't come clean rather than bill.

**Comment by InZidiuZ** [comment]
Hey,

This is not a bug-report.

**InZidiuZ**
*OP-FW Developer*
