### ISSUE TITLE
The ubermacht sentinel classic

### ISSUE THREAD

**Issue by Pizzzaa** [InZidiuZ/op-framework-issue-tracker#423]
**Reporter:**
Luis Siul
Pizza #2928

**Summary:**
So i think this car goes 130mph stock (not sure) but after i fully upgraded his turbo/engine it started going around 130-140mph. I think the stock speed is fine i guess but after all upgrades its should be going at least 170-180 mph (i got told it goes that fast).

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

**InZidiuZ**
*OP-FW Developer*
