### ISSUE TITLE
Nissan Skyline R34

### ISSUE THREAD

**Issue by Rookinton** [InZidiuZ/op-framework-issue-tracker#424]
**Reporter:**
Rook
Rook#6895

**Summary:**
My Nissan Skyline was stock for a while, I had finally earned the cash to buy all the upgrades expect armor 100%. Before my Nissan would reach up to 165m/ph easily on the highway. After buying all upgrades for about 20k, it still only hits about 165m/ph and everything else feels the same as before too.

**Steps to Reproduce:**
Bought the car, few days later, went to Los Santos Customs and bought all upgrades, put it in the garage and pulled it out again to make sure things had "saved".

**Player Data:**
Character ID: 9207 - Job Data: Goverment, Waste Collector, Employee. Timestamp: 2019-09-06 20:40:53

**Notes:**
I'm not sure if this only happens for the R34 or if it's for all cars.

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

**InZidiuZ**
*OP-FW Developer*
