### ISSUE TITLE
Suggestion: add /cycle for a free or PAID cycle spawn.

### ISSUE THREAD

**Issue by shouvikpc** [InZidiuZ/op-framework-issue-tracker#425]
**Name:
**Shouvik** Paul Chowdhury 
**Discord** : Xgamster#5956

**Summary:** add a free/paid vehicle spawn i
**Reason:**
**Why** would your suggestion be a good addition to Legacy?**aa

**if** a car flipped inside a tunnel or desert even when spawned in airport /train station you GTA or hotwire and a **police is camping and stuff ... speciallly in the indian servers**.
i would add a SC of a situation that happened after which i decided to come here i really dont knw anything about github thanks to both of your mods @M-11 and A-6 

![]( https://cdn.discordapp.com/attachments/471788803254648842/620101482552754181/unknown.png ) Its like very **irritating** when youre **glitched dead** under PILLBOX  **here** and your friends car flipped inside tunnel so he walked up to you in order to save you and starved to **death by walking miles** inside tunnel and getting mugged after all this ,

**i** dont know if youll see this or not if you did **please reply your view** on this matter because you are an admin you can do anything and everything so **it may not be helpful to you** but i bet this WOULD **HELP EVERYONE ELSE IN LEGACY** make a poll and see the results what other people think and **hope  this idea makes a sense** if not free you can code like it can deduct money in order to get rid of spawn spammers or you can do like delete last vehicle ?

**Comment by InZidiuZ** [comment]
Hey,

This will not be added.

**InZidiuZ**
*OP-FW Developer*
