### ISSUE TITLE
Raising PD fines

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#427]
**Name:**
Lars.
#9309
**Summary:**
My suggestion is to raise the fines which we have in the city.

**Reason:**
It would add more realism cause i don't think a $50 dollar fine seems right for fleeing/evading.
It would also make the economy a bit tougher compared to how it is at the moment.

**Comment by InZidiuZ** [comment]
Hey,

This is currently not a framework-related suggestion, so closing.

**InZidiuZ**
*OP-FW Developer*
