### ISSUE TITLE
PD Fines RAISE

### ISSUE THREAD

**Issue by pxyeb** [InZidiuZ/op-framework-issue-tracker#429]
**Name:**
pxyeb.#8125

**Summary:**
With the recent economy / people grinding / criminial roleplay going down we as High Command think that raising the fines will make the roleplay way better. Currently we are blocked to giving 5k maximum fine when combined and we think thats a limit that should be taken off. Accordingly to that we need to raise fines A LOT more so criminals will start fearing of getting fined by the cops. We can discuss what fines would be fine for the current economy.

**Reason:**
I think this would be a great change/addition to legacy because it could balance the economy at least to a better point than it is now. Would also help crims being less disrespectful towards the cops.

**Comment by y0Razz** [comment]
I made a same suggestion last night, but apparently this isn't the right place.
