### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by munindra15** [InZidiuZ/op-framework-issue-tracker#430]
**Reporter:**
@ConvictXX#9626
https://steamcommunity.com/profiles/76561198209801515/

**Summary:**
Basically i term it as Graphic Glitch. So what happens is that many a time when I'm driving on road suddenly the graphics disappears and i fell into the infinity. I mean I'm the admin so i think i dont get any ban for noclip but most of the players who face this same problem are being banned. And it has also happened with some big Streamers. At first i thought it was due to my low end system. But later on when i had a chat with on of our streamer he also faced this same problem btw he has very good system so i see no point that its a Glitch happening with low spec pc's only. 

**Steps to Reproduce:**
I don't know what or how this thing happens. It's totally random. 

**Expected Results:**
I expect you to give a good amount of time if possible into this issue as this is the most common one faced right now in the Indian servers.

**Comment by InZidiuZ** [comment]
Hey,

This is a GTA issue, related to PC issues. If your PC is bad, upgrade. If your PC is good, close unnecessary applications which may be taking up memory/performance.

**InZidiuZ**
*OP-FW Developer*
