### ISSUE TITLE
Suggestion - Drug changes

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#431]
**Name:**
Who is suggesting this? Please include discord name.
Aspratic#3121 

**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about adding another coke sell spot into the city.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding another coke spot to sell would be a good addition to the server because with the current amount of cops which varies from 4-10 on average now, makes selling coke nearly impossible. The strip of which you sell coke is such a concentrated area and makes catching criminals very easy. Adding another spot gives criminals a chance to make money by selling coke, I have talked to both cops and players and the consensus that we came to is that this is the best option and brings the server more RP opportunities.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*

**Comment by frohsti** [comment]
really hoping this gets a review, atleast one more spot is needed maybe atleast at certain times of day, this is a death trap.
