### ISSUE TITLE
Suggestion:Different reconnect priority queue for priority holders.

### ISSUE THREAD

**Issue by pcgamer1** [InZidiuZ/op-framework-issue-tracker#432]
**Name:**
Who is suggesting this? Please include discord name.
Sarthak#1731
**Summary:**
Write a short summary of what your suggestion is about.
While trying to join the Indian WL server, we usually have to wait in a queue for *more than 2 hrs.*
After getting in and playing for sometime, in-case I get disconnected, when I enter the queue again, its the same queue as before. I do not get any benefit of the reconnect priority. If there was a *different reconnect priority for the priority holders* which would place us before all the other priority holders, it would help a lot and *reconnect queue would become useful* for the priority holders.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would help the priority holders to reconnect easily after a network error or a crash.

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
