### ISSUE TITLE
[player/health] Introduce heart attacks, which may occur with high stress levels

### ISSUE THREAD

**Issue by RobinWell** [InZidiuZ/op-framework-issue-tracker#433]
**Name:**
Who is suggesting this? Please include discord name.
RobinWell#6084

**Summary:**
Write a short summary of what your suggestion is about.
When your stress rises to a certain level, you have a risk of having a heart attack.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would give some roleplay to EMS as people would have to RP that they are having a heart attack. The EMS would also have to find out why someone is having a heart attack, and how they can resolve the issue.

**Comment by Cironite** [comment]
+1 I think this would be a nice addition, which can also lead to people taking better care of their health :)

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
