### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Godzy69** [InZidiuZ/op-framework-issue-tracker#437]
**Reporter: Godzy, Godzy#6387, https://steamcommunity.com/profiles/76561198346198330/**

**Summary: It is a OP Bug Found In Pill Box**

**Expected Results: BUG Fixing**

## Additional Information

**Screenshots: https://drive.google.com/file/d/1PER_-B_Rlbr5ebAGg4mwbxjfdeUM989m/view?usp=sharing **

**Game Resolution:1920*1080 **

**Player Data: ID 11531**

**Comment by InZidiuZ** [comment]
Hey,

I'm unable to fix this, I didn't create this interior.

**InZidiuZ**
*OP-FW Developer*
