### ISSUE TITLE
Bring Back The Ruiner 

### ISSUE THREAD

**Issue by WeKnowTheTruth** [InZidiuZ/op-framework-issue-tracker#438]
Lonely
#7496
I purchased the ruiner as my first car and went full out upgrading it fully and the car wasn't half bad it topped out at 70 and had a decent handling line but my favorite part the wheelies but you take the wheelies away which is one thing ok I get that rp wise yea not that realistic but to then go and also make the car go 135 140 max now idk it seems really slow when a 1200 dollar bike can go 115 stock idk maybe its just me but a fully upgraded ruiner should be able to go over 140 in my eyes with 15k in just a turbo plus max engine and transmission upgrades I just wish to see the ruiner brought back to its former glory maybe not to what it once was but right now it doesn't feel real at all it so slow compared to other cars of its class even though before was right with them 

**Reason:**
Realism to me every other car in its class is out performing it in the game and upgraded it doesn't change all that much top speed wise maybe acceleration other cars didn't seem that effected either idk why the ruiner was nerfed so hard a few month ago I don't have that much time to spend on a game and to have it wasted on this car stinks

**Comment by iGreatWhite** [comment]
This is the incorrect spot for a car to be added to the server. Please use the assets GitHub Tracker which you can find in the discord server under #bugs-and-ideas.

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

**InZidiuZ**
*OP-FW Developer*
