### ISSUE TITLE
Mechanic Vehicles

### ISSUE THREAD

**Issue by HazzerEFC** [InZidiuZ/op-framework-issue-tracker#439]
**Name:**
Who is suggesting this? Please include discord name.
Harry. Q - hazzerefc#4679
**Summary:**
Write a short summary of what your suggestion is about.
This is an additional for mechanics as the vehicle is currently buggy with the /tow unless luck is on your side

https://www.gta5-mods.com/vehicles/non-els-fivem-ready-kenworth-t440-heavy-wrecker

**Reason:**
Why would your suggestion be a good addition to Legacy?
This is something different. Also adds the edition for a better mechanic service/role

**Comment by TwoplePop** [comment]
It looks a little excessive. Maybe something like the tow truck with the actual hook thats in gta 5 already would work a lot better but i heard desync sucks with that vehicle.

**Comment by SATIN187** [comment]
Yeah I would agree with something like a smaller tow truck with a hook so we can get into parking garages

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related GitHub issue tracker, not in the framework one.

Highly unlikely, though.

**InZidiuZ**
*OP-FW Developer*
