### ISSUE TITLE
Canceling lockpicking

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-issue-tracker#440]
**Name:**
Who is suggesting this? Please include discord name.
SATIN187#0666
**Summary:**
Write a short summary of what your suggestion is about.
Possibly adding in the option to cancel lockpicking
**Reason:**
Why would your suggestion be a good addition to Legacy?
As of right now if youre trying to lock pick somebodys car to either steal iteam in it or to steal the car you, if somebody comes up to you, you arent able to cancel to either stop and defend yourself or to run away

**Comment by InZidiuZ** [comment]
You already are for lock-picking inside, no?

**Comment by triatomic** [comment]
you still lockpick the lock outside a vehicle.

**Comment by SATIN187** [comment]
no mainly for lock-picking outside the vehicle to get in it

**Comment by InZidiuZ** [comment]
Hey,

You can now cancel lockpicking from outside.

**InZidiuZ**
*OP-FW Developer*
