### ISSUE TITLE
Gun Recoil 

### ISSUE THREAD

**Issue by TrabThaKidd** [InZidiuZ/op-framework-issue-tracker#442]
**Name:**
Knight_Rider28#9358

**Summary:**
The Gun Recoil I just feel like it's a little too much and it's excessive and it shakes so much.  

**Reason:**
It will help improve gunfights and just make it a bit realistic!

**Comment by psyCOSMO** [comment]
It's because of your stress level, start decreasing it and shooting less often,
It's a punishment system for people that just shoot a lot, and totally against removing that.

**Comment by InZidiuZ** [comment]
Hey,

Like @psyCOSMO said, keep your stress level low. Also, having injuries will also increase it. The recoil is high to encourage longer "shootouts" allowing players to get more immersed in the scenarios.

**InZidiuZ**
*OP-FW Developer*
