### ISSUE TITLE
Stress and how to get it down

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/op-framework-issue-tracker#443]
**Name:**
Blanket#0404

**Summary:**
Currently the only viable option for removing stress is smoking weed. I don't agree with this as I like to stay within the legal limits of life. Smoking weed is negative to the human body as it distorts functionality and causes people to feel increased heart rate. As someone with hypertension I'm constantly afraid of suffering from heart attacks or even raising my blood pressure even more by the usage of marijuana. I understand that drinking fine quality H2O will also decrease stress but it's such a low amount that it's not even worth it. It literally takes like 20 bottles of water to completely de-stress someone, I'd like to tack on that it is theoretically not safe to drink anymore than 33 ounces of water per hour and considering each standard bottle of Nestle Pure Life water has 16.9 ounces of water you'd have to drink over almost 10 times the safe amount of water to be completely safe of stress. Let's move on, food. We got burgers and sandwiches, right? Wrong, they're the same as water and I won't even go into consumption amounts with food aside from saying that you'd need to eat over 20 burgers in one sitting to be completely rid of stress. Keep in mind that the world record for most burgers eaten in one sitting is held by Ricardo 'Rix-Terabite' Francisco with a total of 5 107-gram burgers which equals out to 545 grams. The standard McDonalds Big Mac weights roughly 240 grams, which means the world record is roughly 2 and a half big macs. Which means eating 20 burgers in one sitting is incredibly impossible. Moving on, Cigarettes. Don't get me started on Cigarettes, They're extremely unhealthy, they cause cancer, and they hurt the body in more ways than they help. I shouldn't need to rush through two packs of cigarettes one-after-another just to get 1/4th of my stress bar down. It's a bad habit and I won't start it. That's about it, my main suggestion is that I'd like food/water to remove a bit more stress so that they become viable options for de-stressing, right now they're completely pointless.

**Reason:**
I don't want to be a criminal or get lung cancer just to remove my stress.

**Extra Information**

Screenshots of before and after I ate one of these behemoths.
![image](https://user-images.githubusercontent.com/49964391/65198662-f9395100-da51-11e9-949c-c9736961c838.png)

Before:
![image](https://user-images.githubusercontent.com/49964391/65198671-035b4f80-da52-11e9-95b2-3c92d9190d87.png)

After:
![image](https://user-images.githubusercontent.com/49964391/65198691-14a45c00-da52-11e9-865e-fa86714b1d29.png)

LITERALLY DOESN'T MOVE

**Comment by psyCOSMO** [comment]
I think that going to sleep/yoga/ ems therapist should reduce your stress

**Comment by BlankeyBoi** [comment]
Another experiment!

Before:
![image](https://user-images.githubusercontent.com/49964391/65257354-17916200-dacf-11e9-8f1f-96b3294eef77.png)

What I will be drinking:
![image](https://user-images.githubusercontent.com/49964391/65257639-840c6100-dacf-11e9-8e9f-16ed7deb1be9.png)

After:
![image](https://user-images.githubusercontent.com/49964391/65257985-22002b80-dad0-11e9-94ba-653f685c0388.png)


It took 28 water bottles to completely remove ~25% of the stress meter.
I should be dead.

**Comment by BlankeyBoi** [comment]
A third experiment!

Before:
![image](https://user-images.githubusercontent.com/49964391/65343610-63154000-dba3-11e9-8659-93388073baa2.png)

What I will be drinking:
![image](https://user-images.githubusercontent.com/49964391/65343632-6f999880-dba3-11e9-9c12-447555e6b0c1.png)

After:
![image](https://user-images.githubusercontent.com/49964391/65344054-9ad0b780-dba4-11e9-9501-b04cc2cca42a.png)

I'm a true scientist, so I'll keep drinking until it's gone.
Another 40:
![image](https://user-images.githubusercontent.com/49964391/65344122-d2d7fa80-dba4-11e9-993b-df59fe477205.png)

After:
![image](https://user-images.githubusercontent.com/49964391/65344401-9f49a000-dba5-11e9-9af4-de9343924af0.png)

It takes 100 water bottles to remove full stress.

AKA: ~4 Nestle Pure Life 24 pack packaged water.

That's ridonkulous.

**Comment by InZidiuZ** [comment]
Yoga has been added. Are you happy? >(
