### ISSUE TITLE
Enhanced HUD

### ISSUE THREAD

**Issue by krishus96** [InZidiuZ/op-framework-issue-tracker#444]
https://forum.fivem.net/t/release-enhanced-hud/634217

https://github.com/Naikzer/HUD-GTAVRP

I love Playing in your Indian LegacyRolePlay servers but only compalin is the HUD is not so good. So it ill be nice if you introduce Nice looking and easy to use HUD's.

:)

**Comment by Anderzenn** [comment]
Hi :)
For future reference please follow the templates. (It's required)
Our huds are custom made. If you wish to suggest any changes to the UIs feel free to post a suggestion (using the template)

**Anderzenn**
*OP-FW UI Developer*
