### ISSUE TITLE
Megaphone in Cruisers/Air-One

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#445]
**Name:**
CyberSkunk#5173

**Summary:**
So I'd like to see a megaphone future in the police vehicles and perhaps even the EMS vehicles. You can basically use it to speak out to the public when ever a certain area is dangerous and needs to be evacuated or when to stop a suspicious vehicle at a trafficstop and so on.

Here's also a link for a good example, even if you might wanna change the actual voice or messages coming from that addon. Also this particular addon is not really a megaphone, it's basically GTA voices from the LSPD NPCs, 
Me personally would rather suggest a actual megaphone to make your OWN voice heard.

https://forum.fivem.net/t/release-polspeak-police-vehicle-megaphone/257835

**Reason:**
I do believe it would be a cool and great future to have in-game to provide a more realistic roleplay in chases/bankrobberys/trafficstops etc.

**Comment by psyCOSMO** [comment]
Certainly can be cool but seeing as it available for you to switch to the "shout" voip mode and using external program to change your voice via a button, I don't think it should be a priority.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being. If you wish to have a "megaphone" effect, I'd suggest using a voice changer together with the shout option, like @psyCOSMO said.

**InZidiuZ**
*OP-FW Developer*
