### ISSUE TITLE
MAKE GRAPHICS LIKE REDLINE-RP

### ISSUE THREAD

**Issue by James-Aditya** [InZidiuZ/op-framework-issue-tracker#446]
RolePlay is a another life of ours so to make to more realistic we want the graphics of this city to be like REDLINE- RP because it makes people to play more seriously.

**Comment by Anderzenn** [comment]
Hi :)

Implementing a default graphics mod would not make people rp more seriously.
The only thing it would do is make the game look prettier, most people on Legacy already use graphics mods that they have chosen themselves anyways (me included) and this would just cause interference and errors with the graphics mods some people already have installed.
Most people do not have a PC that is able to run GTA V with a graphics mod anyways.

And for future reference, **FOLLOW THE TEMPLATE**. It's there for a reason.

**Anderzenn**
*OP-FW UI Developer*
