### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by L1MO** [InZidiuZ/op-framework-issue-tracker#448]
**Name:**
@L1MO#6332
**Summary:**
Suggestion for opening a new bank.
The Pacific standard bank on Vinewood Boulevard can be open as a large bank with large loot and as it has more enterances it can be more difficult for players to escape creating a quality RP.

**Reason:**
Because it will add content and make more options for quality RP

**Comment by InZidiuZ** [comment]
Hey,

Closing, as this suggestion doesn't really make a whole lot of sense.

**InZidiuZ**
*OP-FW Developer*
