### ISSUE TITLE
Should have option to get down if someone is carrying uncuffed/undead person.

### ISSUE THREAD

**Issue by nirmal743** [InZidiuZ/op-framework-issue-tracker#449]
**Name:**
Nirmal#1113

**Summary:**
If person gets carried by another person. S/He should get an option to get down if s/he is not dead or cuffed. 

**Reason:**
So many times, I was carried by someone without having any single conversation. He just carried me and walking around. If I'm alive and not cuffed. I should be able to get down from shoulder on my own. 
OR atleast Add option like "try to get down". So that may take many tries.

**Comment by psyCOSMO** [comment]
Totally

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
