### ISSUE TITLE
Add Indicators/Side lights while driving a vehicle! 

### ISSUE THREAD

**Issue by paulbettany** [InZidiuZ/op-framework-issue-tracker#450]
Name: RGauravB#5358

Summary:
Please assign a key so that players can use the side lights while taking turn or changing lanes!

Reason:
Since this is the best server for GTA V RP to play, I expect the developer to add a small feature in vehicle, i.e. to add a side lights in the vehicles for the players so that they use it while taking turns and the players coming from back don't have to collide with each other seeing the indicators players will be aware and it will be a very good RP. And also while in chase the players can flash the indicators to one direction and turn on another side to loose the cops.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. Use left & right arrow key to use them.

**InZidiuZ**
*OP-FW Developer*

**Comment by SATIN187** [comment]
are these client or server side
