### ISSUE TITLE
Addition of "item cards"

### ISSUE THREAD

**Issue by qaisahmed1** [InZidiuZ/op-framework-issue-tracker#451]
**Name:Qais#2007**
Who is suggesting this? Please include discord name.

**Summary: In-game cards that can be placed on victims. For example Cartel Cards, If gang members come up with card logo ideas for there gang, these could be implemented into physical items that we could leave on victimised bodies (in there pockets)., this would create a whole new wave of Roleplay for gangs as cops could use these cards to gain evidence.**
Write a short summary of what your suggestion is about.

**Reason: This would greatly benefit gang roleplay and will give cops more to work with when bringing down large organisations.
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
