### ISSUE TITLE
Suggestion to Remove Deposite options in ATM

### ISSUE THREAD

**Issue by pabloptk** [InZidiuZ/op-framework-issue-tracker#452]
Name: 

Summary:
Since in GTA V legacy is the best server to play on, I love the interactions between the owner/developers/admins and all. But i would like to take attentions of the developer to remove deposit from the ATM menus.

Reason:
Role Play is a virtual world where the players have to perform the tasks as if it was supposed to be in real life. Ok, so here is the main reason to remove the deposit menu from the servers ATM. People mainly use ATM to with drawl money or transfer money to the players, which is fine. But most of the players after escaping from cops they go to ATM (by the side of roads, shops etc) and they deposit the money so that even if the cops found them they could not take money, if it is so then is bank available in games only to rob. Compel users to deposit the money only when they visit bank.

**Comment by ExpDev07** [comment]
Hey and thanks bruh the feedback! However, I really don’t think we’ll ever remove ATMs from the game. You’re right about the IRL-part, but players need to feel some kind of safety regarding their money. It’s not realistic to carry around 3 million in cash either.

We have rules to make sure that people don’t abuse the deposit feature, for example, if they’re being mugged. 

Marius

**Comment by InZidiuZ** [comment]
Hey,

With @ExpDev07 reasoning, this will be closed.

**InZidiuZ**
*OP-FW Developer*
