### ISSUE TITLE
ATM can be accessed through wall

### ISSUE THREAD

**Issue by pabloptk** [InZidiuZ/op-framework-issue-tracker#453]
Reporter:
Who is reporting this? Please include discord name and your steam profile.

Summary:
Yesterday while robbing a bank I found that i can access the ATM outside of bank from inside. But i didn't use it because i thought that it may be a bug. so please fix this bug

Steps to Reproduce:

Expected Results:
If this bug is fixed people who are not streaming cannot put the robbed money inside their account and will be fined accordingly

Actual Results:

Additional Information

Screenshots:
Sorry , I was not recording at the particular time

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
