### ISSUE TITLE
Missing livery

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/op-framework-issue-tracker#454]
**Reporter:**
Discord: Kiwi#6887 Steam: https://steamcommunity.com/id/KiwiUK/

**Summary:**
I am not able to change the livery on my Nissan Titan

**Steps to Reproduce:**
There isn't exactly any steps to reproduce this bug, there is simply just no livery options on the Nissan Titan when taken in to Benny's or Los Santos Customs. 

**Expected Results:**
I expect to be able to drive into a customisation shop and be able change my livery or remove it. 

**Actual Results:**
Whilst in the customisation shop, there is no options to change or remove liveries.

## Additional Information

**Screenshots:**
![titanlv](https://user-images.githubusercontent.com/54548483/65817920-8fb10380-e204-11e9-9708-c5be8f162d3a.PNG)
![f8lv](https://user-images.githubusercontent.com/54548483/65817925-98093e80-e204-11e9-9ef7-309b49623ba7.PNG)

**Game Resolution:**
1920x1080

**Player Data:**
Chacter ID: 8084 - Job Data: Mechanic, Los Santos Customs, Tow Driver.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This is due to some issues with the LS customs, and will not be fixed as of this moment. In the future, I plan to rewrite the LS customs, also fixing the issues we have with the current one.

**InZidiuZ**
*OP-FW Developer*
