### ISSUE TITLE
PROGEN T20 WINDOWS

### ISSUE THREAD

**Issue by HARSH292001** [InZidiuZ/op-framework-issue-tracker#455]
**steam**
@HARSH#1087 AND steam ID = https://steamcommunity.com/id/always29/

**Summary:**
WINDOWS OF PROGEN T20 GETS BROKEN AGAIN AND AGAIN TRIED EVERY POSSIBLE WAY , I HAVE REPAIRED THEM FOR LIKE 40X TIMES  ,I SPENT ALL MY MONEY IN THAT CAR , PLEASE HELP US OUT

**Game Resolution:**
11920x1080 75hz 

**Player Data:**
IN GAME NAME : ALWAYS4U YT

**Notes:**
PLEASE HELP US OUT

**Comment by InZidiuZ** [comment]
Hey,

Post this in the asset-related issue tracker, found [here](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues).

**InZidiuZ**
*OP-FW Developer*
