### ISSUE TITLE
Condoms for the virgins

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#456]
**Name:**
DooZolz#4014

**Summary:**
Since we are all about being realistic, I think that we should add condoms to the game, you don't even need to add large or extra large cause let's be real everyone here is an extra small.

**Reason:**
Well It's more realistic and just a funny part of having it on you is good, let's say the police search you or something and they find extra small condoms maybe it'll give them a little laugh, and where have you seen condoms as an item on other servers?

**Comment by KPNutz** [comment]
And I thought I’d heard it all

**Comment by psyCOSMO** [comment]
I'm gonna be regretting for asking that, for what use will they be for in rp perspective.

**Comment by SATIN187** [comment]
Honestly not a good idea considering erp is not accepted very much do to people streaming and a lot of it is against twitch tos

**Comment by DooZolz** [comment]
Then don’t ERP. It’s just meant to be a joke when you see someone has it on
them you know

**Comment by ExpDev07** [comment]
As clearly stated in the rules, we're an adult community but respect that younger people also play here. Swearing etc is generally fine, however, we try to stay away from sexually explicit content unless it's in direct relation with The Unicorn. This is also to create a safe enviroment for streamers, as @SATIN187 mentioned.

Marius

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. It's obtainable, but doesn't have any use yet. Not sure what it'll be used for, but we'll figure that out later... NOT FECKINGS ERP THOUGH PLEASE NO GOD NO

**InZidiuZ**
*OP-FW Developer*
