### ISSUE TITLE
[player/health] "/checkstatus" command. 

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#457]
Name:
Ori#4385

Summary:
A new command that allows cops, or everyone, to observe the status of other players during interactions, by doing /checkstatus, or something along those lines, when in a certain radius from a player. 
To obtain RP information such as certain indications, depending on usage of narcotics, alcohol etc. 
For example, if a player has recently smoked a joint, or carries a above a certain amount of weed, the command would return : Strong/Faint smell of marijuana.

In addition, players could perhaps be able to view their own character status, this would work the same as our current injury system like "upper spine injury". To then roleplay according to their assigned indication from the database below. For example, if a player has been drinking, they would be able to see their own characters status. So if the status indicates "Slow response to questions or comments" (random database example). They can verbally roleplay this with other individuals, regardless to whether or not other people check their status.  **(This would highly improve RP)**

Database of /checkstatus information: 

**Appearance**
1. Bloodshot, glassy, or watery eyes
2. Flushed face
3. Droopy eyelids
4. Blank stare or dazed look
5. Twitching or body tremors
6. Disheveled clothing 

**Speech**
1. Thick, slurred speech
2 Loud, noisy speech
3 Speaking loudly, then quietly
4. Rambling train of thought
5. Unusually fast or slow talking
6. Slow response to questions or
comments
7. Repetitive statements
8. Bravado, boasting
9. Making irrational statements 

**Behavior**
1. Swaying, staggering, or stumbling
2. Unable to sit straight 
3. Disoriented 
4. Overly animated or entertaining
5. Crude, inappropriate speech or
gestures
6. Drowsiness or falling asleep
7. Lack of focus and eye contact
8. Difficulty standing up
9. Unusual walk 

**Other**
1. Odor of alcohol, marijuana or
chemicals
2. Excessive perspiration 

**Reason:**
1. Improve Police-Civilian and Civilian-Civilians interactions and Roleplay. 
2. Create more paths for "probable cause" for law enforcement (by adding indications for possession & usage). Instead of the current situation which only allows police the pursue drugs when they are sold. 
3. Build a whole new avenue of roleplay for all parties in the server.
4. Make drugs as a whole more interesting and dangerous.

**Comment by Cironite** [comment]
+1

**Comment by iGreatWhite** [comment]
+1

**Comment by Cironite** [comment]
I forgot to add this, I also dont want players knowing im spectating them, some cops just happen to see my marker cus they are driving and im spectating.

**Comment by KoreeXD** [comment]
+1

**Comment by iGreatWhite** [comment]
Rather than this being a command, I’m thinking if this was just something that is automatically ran when the status could change such as smoking weed would change your status to smell of weed

**Comment by zonaG** [comment]
I think Vedders post is a prime and perfect example of what were looking to get added into the city for a improved experience. In my opinion having alcohol effect people would greatly improve the experience in the city for all the reasons listed above but as a bar owner i think it would also improve the economy of the city. As a bar owner it would make people buying drinks actually worth the money people are spending in the club allowing for club owners to profit from the selling. It also allows civilians to profit from the bottles they find doing garbage, it would allow for bar owners to purchase those bottles and resell them allowing for a RP experience of purchasing bottles from one another. It adds the additional RP of a police officer stopping or pulling over someone for driving under the influence. It also allows EMS to RP different situations like someone falling and hitting there head from being to drunk to walk. It would allow for therapists to RP someone who is a alcoholic and rehab them back into functionality. That in turn allows a civilian to RP a alcoholic creating a storyline on its own.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
