### ISSUE TITLE
Crime Data App

### ISSUE THREAD

**Issue by Trasaraj** [InZidiuZ/op-framework-issue-tracker#460]
# Legacy Phone Suggestion
**Name:**
taoteique #6402
**Summary:**
City crime data app, where you need to log in with the user id and the citizen can check other citizens crime record.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This will allow the citizens to know the crimes other citizens charged with.

**Comment by Anderzenn** [comment]
Hi :)

Maybe.

**Anderzenn**
*OP-FW UI Developer*

**Comment by ExpDev07** [comment]
Could be cool yeah!

**Comment by 1THC** [comment]
Pretty sure they've already got this planned on the trello

**Comment by Anderzenn** [comment]
> Pretty sure they've already got this planned on the trello

Hi :)

It is not.

**Anderzenn**
*OP-FW UI Developer*

**Comment by psyCOSMO** [comment]
Don't think citizens should see other citizens crime record, as well as not legal IRL to check those or ask in job interviews.

**Comment by Trasaraj** [comment]
Why not, Citizens have the right to know crime records of other citizens. Crimes which are charged by police are never secret in the real world too. It also makes a criminal think twice before committing any crimes.

**Comment by Trasaraj** [comment]
Why should I employ any citizens in my company whose criminal recordis bad? The trust laid down by my shareholders/investors cannot be broken because an employee was corrupt or fraudulent.

**Comment by SATIN187** [comment]
Actually it is legal to see people’s crimes and what they were charged with... that’s all public records and jobs also have the right to see somebody’s past if it’s criminal that’s why they do background checks

**Comment by psyCOSMO** [comment]
Well I got mixed up it is indeed legal and free to lookup a criminal record in California, which is what we based on, tho you need to request it with a form and some more additional stuff...

**Comment by 1THC** [comment]
In my state you can google "<blank> county jail records" and see all of the current inmates in that jail. So +1 for me as it would help a lot of companies.

**Comment by Anderzenn** [comment]
> make sure you go under the post and give the plus 1 other so itll move it up and ben will see it has a lot of plus 1

Hi :)
Ben is not the person who does the Phone, that is me :)

I am going to be locking this issue so that no further comments can be made on it.

**Anderzenn**
*OP-FW UI Developer*

**Comment by InZidiuZ** [comment]
This is essentially suggesting the planned CAD/DOJ. Whether we make it accessible through the phone is uncertain, but will close this.
