### ISSUE TITLE
Whitelist gangs incorporation

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#461]
**Name:**
Who is suggesting this? Please include discord name.
Aspratic#3121
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about giving certain whitelistable things in game to different gangs. For example Guns, Attachments, Drugs, Tuner shops, these are all examples of things that different gangs around the city should control.
For a new drug a gang would have to go to somewhere such as a yacht call in a drop, which is sent out to police and then it is a race to secure the drop, either the gang loses the money they spent to call in the drop or the police clean up the streets and secure the drop. Possibly picking up the secure drop at the big boat on the docks. It could/should take a certain amount of time to secure and should have a good amount of risk. These drops should be expensive and risky, with a cool down limit of when you can call them in. Maybe once an hour or every two hours. The drop could have a certain drug like Opium. Once the gang secures the drop they sell the opium to other people around the city (the gang themselves cannot sell the drug to npcs). The people that buy the opium off of the gang can then go and process the drug into heroin which then they can find a new or existing (depending on how you would want it) area to sell the drugs too. 

Variation of Cocaine. Coke plane would be removed. Two gangs control coke, they have to go to a location such as the yacht (each gang would have a different yacht they use) go on a computer (or just press "e" in the beginning of this update) call the cocaine in, then the drop spawns in 1 of however many locations. This drop should have lots of coke bricks inside it, which would induce multiple trips, big trucks to transport and calls for heavy protection from other gangs and police. A siren or colored smoke could be in the area of the drop so other people on the server can find it. The people that called in the drop will get the exact location to secure it. (Another variation could be that people around the city can use the bank chip, go to lester's house and insert the chip into his huge computer database that can locate the drop so the person can intercept it. This gives more use to the hacker chip and increases its value because it is currently underused). The cocaine would then be sold to people around the city. Note: Not everyone in a gang will be whitelisted only certain members, people that are whitelisted cannot sell coke bags to npcs, only the bricks they get from the drops to other players.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This would be a great suggestion to legacy because it creates a lot of Roleplay, incorporating everyone in the city. It includes the Police, the certain Gang, and the people of the city. It gives a risk vs reward to the people of the gang as the drugs should be expensive to call in the drop. The police have roleplay through fighting to keep the opium from ever hitting the streets and battling to arrest the street dealers selling bulk or selling to NPCs. The people of the city have to try and figure out who has the drugs and that could take hours and days of roleplaying with people to find the right connect to buy from. It also forces people to be friendly with people and causing a negative consequence for messing/killing people all around the city and makes them think twice before pulling the trigger. If two different drug whitelists were given to 2 different gangs then it could create a battle on the streets and a rivalry or the gangs would have to have meetings to keep the peace. Either way this encourages roleplay for the entire city and would help make Legacy stand out even more than it already does from other places. 
I know this may seem like a lot of work but I can assure you it is not as grueling coding as it may sound. I would be able to work with Inzidius or any dev who would try to implement this as I believe this could be a huge game changer for the city for the better. Please contact me if this sounds like a good idea at all, not everything I listed has to be the exact way I said it, as I should not be making the final call. But I have amazing ideas and I can give very good input of how to make this happen.

**Comment by SATIN187** [comment]
Why does it have to be gangs?

**Comment by Aspratic** [comment]
Because it should be a whole organization, they put in the work to become whitelisted, and gangs are some of the most active people on the server. In real life gangs run huge amounts of drugs it just makes sense, if a gang isn't being active then take it away and give it to another gang

**Comment by SATIN187** [comment]
But there are whitelisted groups that aren’t considered a gang

**Comment by Aspratic** [comment]
When I say whitelist gangs I mean any whitelist group that is fitting for it. Usually gangs run drugs, Bikers run guns, Mobs don't usually run drugs as that kind of goes against their beliefs (godfather films and others) but as I said Inzidius should make the final call. Any group that is Roleplaying good and has gotten recognition for the good RP should have the opportunity to get it

**Comment by EarlRodrick** [comment]
+1

**Comment by Trasaraj** [comment]
I like this Idea +1

**Comment by 1THC** [comment]
+1 Would add a lot better RP for sure

**Comment by TAshton99** [comment]
+1 adds a shit ton of rp and things to do.

**Comment by Aspratic** [comment]
I am going to edit the first part of this suggestion now, adding improvement, more detailed and make it easier to read/follow

**Comment by HazzerEFC** [comment]
+1 Rate this a lot, this idea only sees benefits and i cant think of any negatives as this improves gang rp and police rp massively

**Comment by Lilgrizz818** [comment]
+1 i feel as us Whitelisted crews have been getting bored and doing the same thing over and over not much for us to expand into just stuck in the same thing also this being added makes us feel like being whitelisted actually comes with perks and fun to increase RP

**Comment by FilipQeh** [comment]
+1 Definitely agree with Lilgrizz ^

**Comment by BlankeyBoi** [comment]
+1, As of right now I feel like whitelisted gangs are pointless and as a group manager I feel like an idiot for handing out strikes to whitelisted gangs when they serve no purpose. Many gangs don't really care about receiving strikes for their gang because they know that it won't change much aside from a simple Discord tag. Giving gangs access to more features in-game would allow for strikes to be a more severe punishment and would make it so that those with quality gang/group RP are rewarded.

**Comment by Aspratic** [comment]
^ I fully agree with what blanket said, strikes can be handed out to gangs with no actual negatives involved except for not having a discord tag, they will still be around in the city and everything will be the same. Rewarding gangs that have good roleplay sets an example for other gangs and will give other gangs a reason to sharpen up their roleplay. And work toward achieving something such as a whitelist

**Comment by selb97** [comment]
What's got my thought is what decides who gets what? Wouldn't it be kinda pointless if a gang was "given" a thing and all they have to do is that?

Lets say that one coded turfs which they have to fight for. And then depending on the turf they own, they will be given control over a certain thing. (then this would be done every week and has to be fought for to be kept in their possession). This is just an example out of many options. But hardscripting it so that a certain gang only controls guns doesn't make sense.

**Comment by Aspratic** [comment]
well for guns i don't know or think there will be a gang (that is rumors of course) and you are describing these gangs like they will make it boring. If the gang doesn't do cool shit when selling and find exciting ways to make rp out of the whitelist then they simply won't be given the whitelist. I don't like the turf stuff as that will automatically go along with drugs and guns etc. I don't think there should be a coded turf they have to control. it enables shit rdm style gunfights. when there can be similar RP and better RP when the gang doesn't have to worry about if they lose the gunfight they lose money and turf etc.

**Comment by iGreatWhite** [comment]
I think more RP needs to go into stuff like territory just make it very well known that it’s your turf a lot like the ‘The Families’ were doing. They are showing a prominence that Forum Drive is theirs. I personally in RP am kind of scared to go there sometimes not knowing if it’s gonna end bad or not. I don’t agree that just because I’m a biker gang that we automatically get guns. I should have to show my knowledge and that I know what I’m doing and getting into with them. Knowing what attachments are best for you. Or if I was a drug dealer. I agree with bringing in systems in which people can bring it into the city and only certain people have that knowledge for say.

**Comment by BlankeyBoi** [comment]
Could always just designate the group managers to decide who gets what. Heehee ;)

**Comment by BlankeyBoi** [comment]
Or randomize it.

**Comment by Aspratic** [comment]
I think admins/group managers should decide who gets what. They know the groups better than everyone and what the groups are all about. They are not biased and can decide what is fitting for what gang

**Comment by selb97** [comment]
I'm not saying that gangs will do their business in a boring way. But scripting it so that _only_ one gang can deal coke, and another one _has_ to do something else because they have no real way to take control over that territory because it's part of coding, there won't really be any competition.

We provide RP. People have to RP and actions will lead to other actions. Hard coding it will basically remove the RP point of actually controlling it. Yes they have to conduct their business in a professional manner, but there won't really be any competition in between gangs themselves.

We also have to remember that it's still a game. Yes we roleplay and try to be as realistic as possible. But taking the fun away from the gangs being able to actually grind for something, work together for an objective and trying to actually control something (with high quality RP of course) is where the fun's at. Pre-planning who gets what isn't fun at all.

**Comment by selb97** [comment]
And then when they finally control it, they can profit off of it.

**Comment by Aspratic** [comment]
Well idk what gangs u are thinking of but i know a few for sure that would be very competitive without any need of a turf coding

**Comment by Aspratic** [comment]
if you re read what i wrote up above you can see that i tried to make it clear there is a huge risk when calling in these shipments and that many people including cops and rival gangs or even stick up crews would be competing for the drugs. There won't be grinding as the shipments would be big and the cooldown would be long. it would have to be planned strategically on both sides of it. I think you are limiting yourself with the possibilities just because you saw that I think the gangs should be handpicked. If gangs were chosen it's not like it's set and stone forever also, it can be taken away just as easily as it was given to the gang

**Comment by selb97** [comment]
I mean. If you specifically code it so that only one gang can do shipments of some sort of drug there won't really be any rival gangs to compete for it?

I just think that a certain gang is the only gang that can do a specific thing is the wrong way to go by doing it.

**Comment by SATIN187** [comment]
This is good but I also think that the players in said gangs should also be reviewed to see if they’ve had strikes in the past and for what and how long ago and how long apart they were and also see if they’ve had previous bans as this would call for high level rp with also being within the rules set upon us

**Comment by AdeptCL** [comment]
+1 to all of the points here.

I've always said if all "leaders" of the shortlisted* whitelisted organisations went into some form of OOC chat with higher-ups of the server to chat about how they can make this fair, accessible, but also very enjoyable for RP for the lowers in an organisation.

* Shortlisted whitelisted organisations = after a couple of weeks/even months of higher-ups reviewing the whitelisted groups with how they're, quality of RP, support issues, etc and picking a group of selected to discuss routes with.

**Comment by Mike8862** [comment]
+1 this seems like an amazing idea!! i like the point of a event that happens that all gangs fight for!!

**Comment by allenle4** [comment]
+1 This brings in more RP for everyone.

**Comment by Aspratic** [comment]
If you guys could leave a reaction of +1 it is a better way for inzidiuz to

**Comment by Aspratic** [comment]
Well I just closed this by accident and I am not sure how to re-open it

**Comment by Lankovich** [comment]
Been into other cities before where my old gang dealt with all Heroin deals, it was shit tbh... i dont dislike the idea of a gang ruling a drug, but there must be a proper way to get this implemented with a way to make great RP with. Wheb I did it, we were so dependent on our customers, if we didnt get customers who want to make a cool RP drugdeal, then it was all only for the money

**Comment by InZidiuZ** [comment]
Hey,

Will close this as it doesn't comply with the framework's standards for FFA RP features. The ability for certain players being able to have access to more advanced 'import options', for example, isn't impossible, though. These abilities should however be gained through the game, and not an OOC role given from staff members. One solution could be reputation levels that are built up after time, for instance.

If you want to rework this suggestion, feel free to do so & post another issue. It's also important you go in-depth with exactly what you are suggesting, from beginning to end.

**InZidiuZ**
*OP-FW Developer*
