### ISSUE TITLE
PD extra command 

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#463]
**Name:**
Lars.
#9309

**Summary:**
I think it would be nice to have a command to turn on / off all the extra's on PD cars.

**Reason:**
Some PD cars have up to 15 or 20 extra's, that's a lot of typing when you spawn in your car and you want to add all the extra's. So a command like '/extra all on'  would be nice i think. Same for turning them off. '/extra all off'

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. Do '/extra all on' to use.

**InZidiuZ**
*OP-FW Developer*
