### ISSUE TITLE
Police Owned Personal Vehicles

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#465]
**Name:**
Beezy#6584

**Summary:**
With all the new lovely changing in the works, and finally new PD cars, which i may add, i like just about every one of them. With all their extras to take off or put on, I was thinking on the suggestion of being able to purchase our own personal cop cars, that we could upgrade in shops or customize to an extent and use on everyday patrol. Making each cop a little more unique and giving us something to spend our money on other than the new houses and companies. Probably comes as a kind of basic suggestion but i think others would like the idea as well. Obviously still have requirements we have to follow but being able to have suspension upgrades or engine upgrades other than everyone wanting to use the "speed unit"

**Reason:**
I just like the idea of people that play strictly as cops, would be able to spend their money on a car they use on the job. Sounds very minimal but just a suggestion for a slightly personalized car.

**Comment by FossiiLs** [comment]
Would be nice if you could take your cop car home after your shift. Not sure about all the upgrading, that was a pain in the old framework.

**Comment by Sleezybeezy** [comment]
@FossiiLs i dont think it would be too difficult, just have a form of purchasing police vehicles in one of the garages just like you pull them out. maybe the back 2 garages that are used to park cars rarely. and have a check to where you can't pull them out of your garage if not clocked on. so cops couldnt abuse them off duty. i'm on duty 24/7 if i'm in the city. so was just a suggestion. to get cops to interact more with mechanics. they were actually shocked last night when i went to them to repair my cruiser. They said they hardly see cops for repairs because they just pull out another one instead of repairing and costing money. Like i stated probably a silly suggestion, but i feel like if each cop had a more personalized car, it would push for more re-occuring bonds between police and the public.

**Comment by InZidiuZ** [comment]
This has already been suggested in #335.
