### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Karpenkooo** [InZidiuZ/op-framework-issue-tracker#466]
**Name:**
Karpenko#3362

**Summary:**
From what i have seen there is no helicopter spawner in Paleto PD. There is a heli-pad there though. Would be really nice for PD! 

**Reason:**
I think it would be a great addition because it would help the server spread out into Blain County. I also don't think it would be too hard to do as there already is one in the main PD. If needed i could also get Co-ordinates for you.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
