### ISSUE TITLE
Respawning when in water keeps you dead.

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#467]
**Reporter:**
Duroode#2178
https://steamcommunity.com/id/Duroode

**Summary:**
when people get excuted and they throw the body in the ocean they wake up and die again

**Steps to Reproduce:**
To Reproduce this, Die in the Ocean and Air lift to hospital. You will respawn dead.

**Expected Results:**
When respawning, Regardless if its in the ocean or not you should be alive in pillbox

**Actual Results:**
You Respawn Dead in pillbox.

## Additional Information

**Notes:**
This Report came from Multiple Support cases, and Advice from other staff to Report.

**Comment by InZidiuZ** [comment]
Hey,

Unable to reproduce it. Are you on a *very slow* PC, perhaps?

**InZidiuZ**
*OP-FW Developer*

**Comment by iGreatWhite** [comment]
This is actually a very common issue InZidiuz. I do not know how you can’t replicate it. Basically if you kill someone then carry them into a body of water so they can drown. Then respawn after like a minute or two. It should do the presented result

**Comment by Duroode** [comment]
> Hey,
> 
> Unable to reproduce it. Are you on a _very slow_ PC, perhaps?
> 
> **InZidiuZ**
> _OP-FW Developer_

So in the last week we've had multiple people come to discord for support in which they have died after respawning to pillbox, then needing us to go in game and revive them. I personally have not had this issue. But i was advised by other staff and players to report this as a bug.

**Comment by InZidiuZ** [comment]
If anyone has video, info or a repro on this, please post it here.

**Comment by Aspratic** [comment]
Anytime u are thrown into water and respawn u wake up dead in the hospital and u have to /report an admin to get revived

**Comment by InZidiuZ** [comment]
Hey,

Still not able to reproduce, but might be solved as you're now kept invincible from the point you hit "Enter" till you leave the hospital bed.

**InZidiuZ**
*OP-FW Developer*

**Comment by Duroode** [comment]
Bug Still Exist's i've gotten a clip of it from ZainX's stream
https://clips.twitch.tv/FantasticBloodyOstrichCurseLit
