### ISSUE TITLE
EMS able to turn off trackers

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#468]
**Name:**
Ciros#2048

**Summary:**
I dont know if this was intentional or not, but Im going to list it as a suggestion to enable ems to use /tracker off

**Reason:**
It would be nice to be able to turn it off when we engage with other criminals, such as Kidnap roleplay and hostage rp, some of them might take away our trackers for the scenario to progress, Again idk if its a bug or its intentional, Nonetheless i think its an option we should have

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
