### ISSUE TITLE
SWAT Vest

### ISSUE THREAD

**Issue by ShelbsShelbs** [InZidiuZ/op-framework-issue-tracker#469]
**Name:**
Shelbs#9300

**Summary:**
Cruxer (Staff &PD member) reskinned a few of the unused styles of the vest for SWAT to use. The vest that is used for main PD patrol does not fit females wearing the SWAT polo so we looked into re-skinning vest with SWAT on it. He has done so and tested.

[SWAT_GEAR.zip](https://github.com/InZidiuZ/op-framework-issue-tracker/files/3693568/SWAT_GEAR.zip)

**Reason:**
Replaces unused vest skins (PIA which is a department we would never have, basically is immigration or something skin) to skins that would be used every day. Allows female SWAT members (currently just me), to wear a suitable vest while on duty, as well as the men in SWAT to also have SWAT vest. 
<3 <3 <3

**Comment by InZidiuZ** [comment]
Hey,

This has been added.

**InZidiuZ**
*OP-FW Developer*
