### ISSUE TITLE
PD shop

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#470]
**Name:**
Lars.
#9309

**Summary:**
Add a shop somewhere in the New MRPD where officers would need to buy ammo, bulletproof vests, attachments etc.

**Reason:**
jUsT LiKe On nO PiXeL.

**Comment by InZidiuZ** [comment]
Hey,

No. You get free ammo, bulleltproof vests and attachment when going on-duty.

**InZidiuZ**
*OP-FW Developer*
