### ISSUE TITLE
PD Distress Signal

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#471]
**Name:**
Lars.
#9309

**Summary:**
A distress signal when an officer goes down. It would notify the cops on duty with a 10-14 Dispatch Call.
**Reason:**
Because it's kinda a grey area at the moment cause you are not to supposed to speak on radio if you are down but yet that's the only way  to inform your fellow officers that you are down.

**Comment by InZidiuZ** [comment]
Hey,

It has come to my attention, that people don't want this. Nor do I want to make it, lol.

**InZidiuZ**
*OP-FW Devleoper*
