### ISSUE TITLE
Pre furnishes

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#472]
- To pre furnish a house its says $10,000 but when you actually purchase its only $1,000 
- make it 10,000 i guess
10,000
1000

**Comment by iGreatWhite** [comment]
Make sure to fill out a bug report using the template provided

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. The correct pre-furnish prices are now shown for the different house-types.

**InZidiuZ**
*OP-FW Developer*
