### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#473]
**Reporter:**
DooZolz#4014 - https://steamcommunity.com/profiles/76561198185121513/

**Summary:**
Well, I was driving a boat on the water the other day just for some chill moments and I decided to dive in the water, I got curious and wondered if you could smoke a cigarette under water and surely enough you could, I didn't try smoking a joint though cause I didn't have one on me but I'm guessing its the same with a joint as well (it also removed my stress)
**Steps to Reproduce:**
make it so you can't smoke things in water and reduce stress, idk how you guys would do it but that's the idea

**Expected Results:**
To not be able to smoke a cig underwater.

**Actual Results:**
When smoking a cig underwater it reduces your stress.

## Additional Information
I blame InZidiuZ
**Screenshots:**
No screenshots

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. You're now no longer able to use items while in water.

**InZidiuZ**
*OP-FW Developer*
