### ISSUE TITLE
Advertisements

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#474]
**Name:**
Who is suggesting this? Please include discord name.
#Ciros2048
**Summary:**
Write a short summary of what your suggestion is about.
Option for companies to advertise
**Reason:**
Why would your suggestion be a good addition to Legacy?
Instead of what has happened today, Companies using Mechanic/EMS/SASP hotlines to advertise their businesses, What if we add an Ad space either it be On a phone or actual thing on the stocks UI, Having their own space to put their advertisements could help their business grow but of course not for free, they have to pay for it.

**Comment by InZidiuZ** [comment]
A "yellow pages" app for the new phone is planned.
