### ISSUE TITLE
Stocks

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#475]
**Reporter:**
 Cricketx818

**Summary:**
I noticed everybody went bankrupt the first day that the stock system came out, my company was -$50,000 So i deposited $80,000, Then after a couple hours It went negative again -$29,000 So i deposited another $50,000 and lost it again, then decided to put another 80k into the company and now its at $40,000.

**Steps to Reproduce:**
I have no clue to be honest

**Expected Results:**
Hopefully get my money back?

**Actual Results:**
It might be a bug issue

**Player Data:**

327

**Comment by InZidiuZ** [comment]
Hey,

Changes have been made to the stocks since the previous restart. See if this continues to happen now. DM me on discord with more information if it continues.

**InZidiuZ**
*OP-FW Developer*
