### ISSUE TITLE
[companies/stocks] Company workers improvement

### ISSUE THREAD

**Issue by TAshton99** [InZidiuZ/op-framework-issue-tracker#476]
Name: 
Who is suggesting this? Please include discord name.
#Serge2349
**Summary:**
Write a short summary of what your suggestion is about.
pretty much currently only the owner of the company can access it.meaning jobs like real estate agency and stuff like that are impossible because only the owner can physically sell a house(and access the company).My suggestion is make it so if that the owner of said company wants a worker(vice president,agent etc...) to be able to access the company's data(houses etc..). He should be able to do so.
**Reason:**
Why would your suggestion be a good addition to Legacy?
it would add alot of RP. more interactions.More job possibilities(real estate agent for example.)

**Comment by FossiiLs** [comment]
+1 I pray thee Inzidiuz adds this!

**Comment by Aspratic** [comment]
People other than the owner should be allowed to sell

**Comment by allenle4** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
