### ISSUE TITLE
Third 'access level' for owned properties

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#478]
**Name:**
Who is suggesting this? Please include discord name.
iGreatWhite

**Summary:**
Write a short summary of what your suggestion is about:

The house owner (person who was given the house by the CEO of the company they are renting from) should be able to give people a 3rd level of access and be limited to 2 or 3 people personally. The definition for the 3rd level of access will be described as below.

3rd Level of Access:
- Access Storage
- Ability to Furnish
- Ability to spawn there
- Ability to store vehicles at the house

**Reason:**
Why would your suggestion be a good addition to Legacy?

I firmly believe this could only benefit legacy as it would allow people to come together and buy a property and all be able to function the same as if they owned it. The reason why I want to suggest this that if someone is helping pay the rent they should be able to access the things the owner can besides the ability to add people to the property and give them keys. This would relieve some restrictions that people may have like going to grab someone from the train station even though they live with you.

**Comment by iGreatWhite** [comment]
Just to leave a comment on this as it will be pulled to the top and be visible to people so they don’t create duplicate suggestions. I really would like people to comment on this with 100% thought into what I am trying to propose.

**Comment by Trasaraj** [comment]
-1
Ability to spawn there
Ability to store vehicles at the house

Companies will lose business, not a good economic plan. Houses are so cheap, I think everyone can afford to rent one.

**Comment by AdeptCL** [comment]
+1
Ability to spawn there
Ability to store vehicles at the house

If someone has level 3 access, it's almost like someone you live with. They should also be able to wake up there and store vehicles. It makes sense to and doesn't really cause any problems. 

However, it should be limited.

Okay some houses are cheap. But as a company, you wouldn't care as long as the rent is paid.

**Comment by SATIN187** [comment]
I’m down for this it’ll make companies think about their prices and it could help some people out who don’t do much crime afford a place

**Comment by iGreatWhite** [comment]
@trasaraj Let’s put some numbers into perspective. A person who doesn’t do crime can do other jobs with their spare time that aren’t illegal such as Garbage and Delivery. I haven’t done delivery yet so I do not know the numbers on that. For garbage though, you make around 300-450 a run depending on the distance if I remember correctly. Let’s use the number of 400. Average rent of an apartment that I have seen as right now is around 6.5k - 9k. So 400x10 is 4K. That doesn’t even cover the cost of the apartment and that’s 10 garbage runs which can cost you up to 2 hours of your time driving back and forth and doing all the runs. Multiply that by 2 again and your at 8k. Costing 4 hours of your time for just a week of your apartment. People also own cars they have to pay on. They pay for food, water, medical bills if they go the hospital. There is a lot more to money than just the cost of the apartment. The constant drain of that money every week and having to repeatedly do the same activity to keep up is draining for some.

**Comment by Trasaraj** [comment]
@i give apartment with 500$ profit. why cannot you friend or gang member buy an apartment in the same block? I would have agreed if the government gives individual houses for the companies but they don't companies need to purchase the whole block and also pay advance for the week. your rent starts of an apartment from the day you rent but we pay for the whole block from the day we book. If whole block is rented or not we pay rent towards the government.
If you guys start staying in one apartment, then what i will do with the remaining apartments in the block?

**Comment by iGreatWhite** [comment]
That’s for marketing man. You have to find people that want to buy them. We had to change our price just to bring people in. And we are happy with the results. I think it’s just a bit selfish to say this will be cutting into your profits.

**Comment by Trasaraj** [comment]
Most of the blocks i hold are low end and mid-end, people can afford them. the rent is 1500 - 3500$
about the profits, what do you mean, i get 500 per week from each apartment

**Comment by iGreatWhite** [comment]
“Companies will lose business, not a good economic plan.” Referring to your profits? No?

**Comment by Trasaraj** [comment]
yes, i am right on that. when the city has hundreds of apartments then why to fill everyone in 1 or 2

**Comment by iGreatWhite** [comment]
Ah yes I’ll tell my significant other that they need to buy their own house/apartment I am totally wrong in that one sorry boss.

**Comment by Trasaraj** [comment]
I am sorry if i was rude, but we have lost lot of investors money on shares plus we are also losing on week grace period after the rent due.

**Comment by InZidiuZ** [comment]
Hey,

People are now able to spawn at shared properties, although no access to the garage will be given.

**InZIdiuZ**
*OP-FW Developer*
