### ISSUE TITLE
Falling through the floor in houses when atempting a burglary.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#479]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Cyberskunk#5173

**Summary:**
A few times I have been crawling and tried to crouch from that position and while doing that you fall through the floor and get busted right away. This happens every time I repeat the same action.

**Steps to Reproduce:**
Crawl on the floor, hit CTRL to crouch.

**Expected Results:**
Gets up from floor to start crouching instead of crawling.

**Actual Results:**
Falls through the floor and gets busted right away.

**Notes:**
I know you're not supposed to use CTRL to cancel the Crawl animation, but still you shouldn't fall through the floor I believe.

**Comment by InZidiuZ** [comment]
Hey,

I managed to reproduce this issue a couple times, and made some changes to the animation script. I believe I solved it, but it was difficult reproducing it to begin with, so maybe I'm wrong. I'll close for now, if it's still an issue after next patch, though, feel free to reopen this issue.

**InZidiuZ**
*OP-FW Developer*
