### ISSUE TITLE
Eclipse Blvd property should have a accessible garage.

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#480]
**Name:**
Allen - Allen#8921

**Summary:**
I bought the Eclipse Boulevard block. I rented out the house and stuff, rented people houses and rooms. The one thing we all request is that the Garage there is should be accessible for us to use. 

**Reason:**
It'd be a good thing to add to Legacy so the people who have a Eclipse Boulevard room/house doesn't have to run to like Garage D or something just to get their vehicle. Making the garage accessible would benefit everyone that lives on Eclipse Boulevard.

![image](https://user-images.githubusercontent.com/52551909/66279801-887f9a80-e881-11e9-89ca-1489dfa57091.png)

**Comment by pxyeb** [comment]
That is a place for the garage but when I was testing it there was a problem with some cars hitting the gate when spawning. Might make a garage closer to Eclipse Boulevard and suggest it to InZidiuZ so he adds it.

**pxyeb**
OP-FW Helper

**Comment by InZidiuZ** [comment]
Hey,

With 1.5, the changes was pushed to the live server.

**InZidiuZ**
*OP-FW Developer*
