### ISSUE TITLE
Lost MC 'Shop'

### ISSUE THREAD

**Issue by W1lsonCodes** [InZidiuZ/op-framework-issue-tracker#481]
**Name:**
WilsonPlays'6969

**Summary:**
Since the Lost MC have a repair shop now, they don't have a computer so adding a computer would benefit them

**Reason:**
This will improve the rp what i have seen already from them. Allowing them to not leave the site because they have no Mats.
![Screenshot_63](https://user-images.githubusercontent.com/48604034/66294058-f2c72800-e8df-11e9-98cb-e2740cc18e89.png)

**Comment by HybridSquirrels** [comment]
I agree we were having alot of business up there in just my few hours tonight in city, so materials purchase would be massively helpful to save a long trip down to grove

**Comment by ZurxeyH** [comment]
This adds more of a working Roleplay to their part, should stay this way

**Comment by 1THC** [comment]
+1 The other day we were extremely busy and someone was out towing cars while I was doing repairs for the people at the shop and ran out of materials. Would be much easier to be able to buy materials instead of driving down to grove street in the middle of a repair which removes a lot of interaction with the customer...

**Comment by InZidiuZ** [comment]
>adding a computer

😕 wat

Do you mean a 'material purchase menu'?

**Comment by W1lsonCodes** [comment]
Yes (:

**Comment by 1THC** [comment]
> > adding a computer
> 
> 😕 wat
> 
> Do you mean a 'material purchase menu'?
The material purchase menu that's already in the Grove Street repair shop.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
