### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HarshpreetS1** [InZidiuZ/op-framework-issue-tracker#482]
Harshpreet Singh
SUPRESSOR#4362 https://steamcommunity.com/profiles/76561198811530009/

Summary
While Playing I get 70 to 80 fps but after the update it gives 70 80 fps but after 15 minutes it lags too much like only 7 to 8 fps I also tried lowering the settings
Steps to Reproduce
Don't know.

Expected Results
don't know

Actual Results:
What are the actual results?
laging
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1080p
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

After the lag begins, press F8 and type `resmon 1` in the console. Expand the info-box that appeared. (might need to use right-alt) Take a screenshot/gif of everything inside it, and post it here.

**Comment by HarshpreetS1** [comment]
Sir is this what you mean?

**Comment by InZidiuZ** [comment]
wat
