### ISSUE TITLE
Bug report: Owned property sometimes doesn't show as spawn button.

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#483]
**Reporter:**
tria #6025

**Summary:**
I and other people have ran into this issue where the house you own doesn't show up on spawn screen and you are not able to access its garage.

**Steps to Reproduce:**
(random chance)

**Expected Results:**
To have your house as spawn and be able to access garage

**Actual Results:**
Your house doesn't act as a spawn point
Cant access the garage
You can enter it manually and /locate command works

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Made some changes to the way your active properties are received on login. If it's still an issue after next update, feel free to reopen.

**InZidiuZ**
*OP-FW Developer*
