### ISSUE TITLE
Bug report: House robbery

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#484]
**Reporter:**
Discord: HS#6627
Steam ID: https://steamcommunity.com/id/hridayhs

**Summary:**
You get busted when the "Alert bar?" is at like 80%.

**Steps to Reproduce:**
Do house robbery and casually move around and notice your alert bar going 0-80% and then get instantly busted.

**Expected Results:**
The alert bar should reach 100% before getting busted?

**Actual Results:**
Bar goes to 0-80% and then instantly busted.

## Additional Information
Sometime it even happens when you're standing still, it should go down I guess? But instead you get busted.

**Game Resolution:**
1600x900

**Player Data:**
Character ID: 23570

**Video Proof:**
https://streamable.com/qr3wp

**Comment by InZidiuZ** [comment]
Hey,

There's a chance of busting when it's near 100%, so this is not a bug, it's intentional. You goal should be to keep it below 50-60%.

**InZidiuZ**
*OP-FW Developer*
