### ISSUE TITLE
Bug report: Cocaine selling

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#485]
**Reporter:**
Discord: HS#6627
Steam ID: https://steamcommunity.com/id/hridayhs

**Summary:**
When you press E to sell the coke bag and if you do not sell it, the message "Sell coke bag" stays on your screen forever + that person who's buying it.

**Steps to Reproduce:**
Have cocaine bag in your inventory, go to cocaine selling location, Press E to sell coke bag and do not sell it. Roam around city.

**Expected Results:**
I guess it should cancel itself if we don't sell it on time or go away from selling location, so that we don't get "Sell coke bag" message everywhere we go. And what about the person standing there? (He needs some rest, he shouldn't stay there forever for me)

**Actual Results:**
Buying person will stand there forever until we go to him and press E to sell or kill that person.

**Screenshots:**
https://i.imgur.com/KfZiy3o.png

**Game Resolution:**
1600x900

**Player Data:**
Character ID: 23570

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
