### ISSUE TITLE
Bug report: OneSync and Garage Storage

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#486]
**Reporter:**
tria #6025

**Summary:**
Storing the car in garage impounds them

**Steps to Reproduce:**
Store the car in one sync server and it will get impounded

**Expected Results:**
Just get stored

**Actual Results:**
Gets impounded

## Additional Information

**Game Resolution:**
1920x1080

**Comment by InZidiuZ** [comment]
🤔 got a plate number?

**Comment by triatomic** [comment]
all the vehicles are doing that.

**Comment by InZidiuZ** [comment]
They weren't actually getting impounded, should just've been a typo in a check. And they also disappeared due to me pushing live changes. See if you can take out vehicles now.

**Comment by triatomic** [comment]
Seems to be resolved. (i already retrieved them and lost 1.2k)
