### ISSUE TITLE
Vehicle gets impounded after storing in garage I(Sandy Shore)

### ISSUE THREAD

**Issue by nirmal743** [InZidiuZ/op-framework-issue-tracker#487]
**Reporter:**
Nirmal#1113 :: https://steamcommunity.com/id/nirmal743

**Summary:**
I'm Storing my News Van at the garage I in sandy shore. It shows 2 notification.
1. Vehicle is stored.
2. Vehicle is impounded.
In vehicle list, It has "out" status. I don't know if it happens with any other vehicle. I only have news van yet.

**Steps to Reproduce:**
Go to the garage I at sandy shore. Store your vehicle there.

**Expected Results:**
Vehicle should not be impounded.

**Actual Results:**
Vehicle gets impounded immediately after storing in garage. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Fixed already.
