### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by naaazz** [InZidiuZ/op-framework-issue-tracker#488]
**Reporter:**
Naaazz#0545 

**Summary:**
so when I am at the reception to rent a motel and click E I cannot (renew) rent it again. normally I get a message in the upper right corner that I have to come later. yesterday my friend lost his motel with all his stuff in it. I've tried all the cities ( 1 - 2 - 3 )

**Steps to Reproduce:**
you tell me :D :D :D :D 

## Additional Information

**Screenshots:**
Here is a youtube clip https://www.youtube.com/watch?v=kLEwfsInPJU

**Game Resolution:**
1920 x 1080

**Notes:**
have a wonderful day :)

**Comment by DooZolz** [comment]
Same thing happened to me the other day, notification didn't pop up and the F8 console had some error I was just too lazy to take a screenshot and post it as a bug

**Comment by Sleezybeezy** [comment]
@naaazz is that the same motel you live at? also use F8 and get that in the video as well. it might help with a code error not going through and the reason its not showing. everything you do generates a line of code that F8 shows. i'd get that and update another video with F8 doing that again at your motel you live at.

**Comment by InZidiuZ** [comment]
Hey,

This has been resolved already.

**InZidiuZ**
*OP-FW Developer*
