### ISSUE TITLE
3rd access level for properties

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/op-framework-issue-tracker#490]
**Name:**
Kiwi#6887

**Summary:**
Add a 3rd access level which allows other people with this level to store vehicles in the house's garage and spawn there when coming into the city.

**Reason:**
I feel as if this would be more realistic as the person with the access is most likely paying rent as well as the owner so they should have the same features if the owner gives them the access.

**Comment by ZurxeyH** [comment]
This would be an excellent addition, but limit it to a few uses per home owner to keep from over saturating garages.

**Comment by KiwiUK** [comment]
Maybe like a maximum of 3-5 aloud

**Comment by Trasaraj** [comment]
-1. No, Companies will lose the business of apartments.

**Comment by xShaww** [comment]
This should definitely be added imo, I’d say a max of 3 keys would be sufficient as it’s totally unfair in the current state with only 1 person allowed to wake up there and use the garage. Especially if people are sharing rent.

**Comment by InZidiuZ** [comment]
Already suggested in #478.
