### ISSUE TITLE
[jobs/police] Evidence locker logs. 

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#492]
**Name:**
Pancho#0001

**Summary:**
Logs for the evidence locker in PD

**Reason:**
stop pd evidence from being abused. pretty important 

-

**Comment by FossiiLs** [comment]
+1 I believe this is critical

**Comment by TheBillyZee** [comment]
+1

**Comment by InZidiuZ** [comment]
Somewhat unlikely due to the amount of logs that would be created. Would say start off by getting rid of your shitty cops. This will also go under 'powergaming', so you can involve a staff member if you find out anyone is doing it, and they'll be banned.

**Comment by InZidiuZ** [comment]
This has now been added. All items that are transferred from one inventory to another is now logged. Each log includes information on the amount that was moved, the slot it was moved from, the slot it was moved to and both inventory names.
