### ISSUE TITLE
Impound unpaid finance cars

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#493]
**Name:**
Who is suggesting this? Cricketx818

**Summary:**
Boss of PDM is allowed to get the car back into PDM if the finances are not paid, so if somebody is behind on payments Boss has to get in touch with PD to run plates to get impounded for good (Removed from being owned by Civ). /Repo

Bug: Once somebody finances a car, they are automatically one week behind on payments.

**Reason:**
People just buy supercars and paid only one down payment for 50k and they are driving a 300k car and never care to pay another payment.

**Comment by InZidiuZ** [comment]
Hey,

This is already added.

**InZidiuZ**
*OP-FW Developer*
