### ISSUE TITLE
Allow state employees to enter unowned properties

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#494]
**Name:**
Who is suggesting this? Please include discord name.
KaiEagle#2469
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion for Legacy is Employee & Mayor should able to enter empty houses without even purchasing it & can allow other people to look it from inside too so that they can get an idea about how is the house from inside. If someone owns it then they should not able too & one more thing Employee & Mayor should be able to see if there is a garage in-home or not.
**Reason:**
Why would your suggestion be a good addition to Legacy?
So that everyone can buy their dream house & get some idea what inside looks like, Of course, everyone wanna see their homes from inside too.

**Comment by InZidiuZ** [comment]
Hey,

This is now a thing.

**InZidiuZ**
*OP-FW Developer*
