### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sallugt5rp** [InZidiuZ/op-framework-issue-tracker#496]
**Reporter:**
hello this is wilson. my discord and steam name is knightflyerminja

**Summary:**
My issue is that my thermites are randomly somehow disappeared from my taxi storage and I talk with many people and they also have same issue that there stuffs are disappearing from there storages

**Expected Results:**
I want you to solve this problem as soon as possible because people are facing problems. And will be waiting for your reply.

**Comment by InZidiuZ** [comment]
Hey,

Closing as you're not following the template properly. Include more information, like CID, plate, timestamps, video/screenshots, and so on.

**InZidiuZ**
*OP-FW Developer*
