### ISSUE TITLE
Let us sell rubber

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#497]
**Name:**
HS#6627

**Summary:**
Let us sell rubber in warehouse.

**Reason:**
I've been doing house robberies and I've collected around 30+ rubber and there's really not much use of it. It's just stacking up and taking inventory space, let us sell it in warehouse.

**Comment by AdeptCL** [comment]
+1 to this. Even if it's a simple $25-50 p/piece.
I have over 200 pieces over my time as a mechanic/doing dives. It's just useless until the rare occasion someone has a popped tyre.

**Comment by ZurxeyH** [comment]
I’d have to say -1 currently, as this material will be used in the future I’m sure. It sucks to have such a stockpile, but yet it’s 0.01 worth of storage space. It’s basically a ghost object you are able to store, and can be used in the future for many applications..

**Comment by AdeptCL** [comment]
Same as saying metals are usable right now, but they can still be sold.
It should be an option whether someone sells it in the warehouse or keeps/sells to another person.

**Comment by psyCOSMO** [comment]
I definitely think there should be like a pawn shop that you can sell your items to

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
