### ISSUE TITLE
Suggestion: Phones For New Characters

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#498]
**Name:**
tria #6025

**Summary:**
Have new characters spawn with a phone in their inventory.

**Reason:**
New players should be able to RP as civs when they start the game and call for taxis or their friends.

**Comment by Cironite** [comment]
Pretty sure this got added in the recent update

**Comment by triatomic** [comment]
> Pretty sure this got added in the recent update

I just made a new character a while ago and didn't get a phone. (it was a new 2nd character)

**Comment by Cironite** [comment]
Then its a bug report not suggestion
