### ISSUE TITLE
More Character slots 

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#499]
**Name:**
DooZolz#4014

**Summary:**
I think we should have more than 4 character slots, 4 characters is good but I would love to have 6-8 slots to possibly create more RP instead of having to delete a character and the best part is, NoPixel has 8 character slots mine as well do it kappa

**Reason:**
It would be a good addition because people would have the chance to get creative and make more than 4 characters, creating more RP opportunities for others!

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
