### ISSUE TITLE
Weird lightning effects inside courthouse

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#500]
**Reporter:**
Discord: HS#6627
Steam ID: https://steamcommunity.com/id/hridayhs

**Summary:**
There are weird lightning effects inside courthouse. I don't know about lawyers office but I believe it's happening there as well.

**Steps to Reproduce:**
I don't know exactly, I think it happens at night time I believe.

**Expected Results:**
To have normal lightning inside courthouse.

**Actual Results:**
Weird lightning effects.

## Additional Information
Need a fix like we have during house robberies I guess.

**Game Resolution:**
1600x900

**Player Data:**
Character ID: 23570

**Notes:**
I can provide a video if needed.

**Comment by InZidiuZ** [comment]
Hey,

Guessing it is due to it not being an MLO. Not much I can do.

**InZidiuZ**
*OP-FW Developer*
