### ISSUE TITLE
Occupation Avenue Apartment A | Local car block garage

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#501]
**Reporter:**
Allen#8921
**Summary:**
So, I have an apartment at Occupation Avenue Apartment A, and I try to take my vehicle from the garage, but there's always a local vehicle blocking it so I can't get in to the option to take my vehicle out etc.

**Steps to Reproduce:**
Make local vehicles not enter the "garage" spot

**Expected Results:**
0 local vehicles should be blocking the "garage" spot so we can take out our vehicles

**Actual Results:**
A local vehicle is blocking the "garage" spot, and I can't take out my vehicles.

## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/52551909/66529144-52842580-ead0-11e9-9132-b02ed52c550b.png)

**Game Resolution:**
1920x1080

**Player Data:**
136 | Mechanic | Tow Driver

**Notes:**
Negative

**Comment by pxyeb** [comment]
Hey,
I have changed the location of this garage to be more up front so the local cars that are parked there don't block spawning a car anymore. You only need to wait for InZidiuZ to push it.

**pxyeb**
OP-FW Helper

**Comment by InZidiuZ** [comment]
Hey,

I can't "Make local vehicles not enter the 'garage' spot".

**InZidiuZ**
*OP-FW Developer*
