### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Cyniah** [InZidiuZ/op-framework-issue-tracker#502]
**Reporter:**
#jenny1862 STEAM_0:1:98388930

**Summary:**
The HUD for the /furniture menu does not fit my screen resolution. I have sat here trying each one in my settings and I cannot get it to fit properly or work for me. Whenever I click on "new object" I cannot click on the very last item on the list or it closes my menu. I can click the one above it but only on the top edge part allows me to view the specific furniture. This is very difficult for me because I have a home decorating business and I cannot access these items, therefore, I am not able to give my all when designing clients homes.

**Steps to Reproduce:**
Possibly raising up the menu for furniture a tad bit if possible.

**Expected Results:**
Being able to decorate houses and continue with my business.

**Actual Results:**
Successfully being able to decorate houses.

## Additional Information

**Screenshots:**
https://gyazo.com/a2956c861c2da68a942123aea70cd6e5

**Game Resolution:**
1600x900 (I've tried all and none helped...)

**Player Data:**
Character ID: 3026 

**Notes:**
For anything else noteworthy.

**Comment by Anderzenn** [comment]
Hello :)

When I made this UI I was honestly not expecting people with resolutions smaller than 1920x1080 to use it because a lot of people nowadays use that or bigger, however! I will work on a fix that will hopefully do so that you can continue your business as soon as possible!

**Anderzenn**
*OP-FW UI Developer*

**Comment by Cyniah** [comment]
Hello Anderzenn,

Thank you so much I honestly appreciate it. Yeah, my monitor is a bit aged but still does the job.

**Comment by Anderzenn** [comment]
Hi :)

I have now fixed this and uploaded it to the repository for Inzidiuz to put into the framework.
Thank you for the patience!

**Anderzenn**
*OP-FW UI Developer*
