### ISSUE TITLE
Unable to get a vehicle on flatbed

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#503]
**Reporter:**
Masik52#5834 
https://steamcommunity.com/profiles/76561198397274352

**Summary:**
As of today while trying to work as a mechanic towing vehicles and using the flatbed to transport hot vehicles for car chopping I've not been able to get any car to go on the flatbed.  I've tried changing the distance between the flatbed and target vehicle.  Sat in the target vehicle then attemped to /tow. Nudged/Hit target vehicle before trying to /tow it

**Steps to Reproduce:**
Locate a vehicle to tow back flat bed close to it and /tow.

**Expected Results:**
target vehicle goes on flatbed

**Actual Results:**
target vehicle sits there and doesn't go on  flatbed

## Additional Information

**Screenshots:**

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 516 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Notes:**
I use my flatbed daily and as of the latest Tsunami I've started to have issues and not been able to get any vehicles to go on the flatbed.  I'm not sure if something changed recently with the updates but multiple mechanic's attempted and it wouldn't work for them either.

**Comment by InZidiuZ** [comment]
Hey,

Store your flatbed and take it out again. That should fix it.

**InZidiuZ**
*OP-FW Developer*
