### ISSUE TITLE
Bug report ( Things vanishing from car's trunk )

### ISSUE THREAD

**Issue by humayunraza1** [InZidiuZ/op-framework-issue-tracker#504]
**Reporter:**
Who is reporting this? Discord: Azzy#6584 Steam: steamcommunity.com/id/azzy5
**Summary:**
I did the chop chop work and then went to garage to keep the things in the trunk. I spawned my vehicle and typed /trunk near it, the inventory opened but it didnt show car's trunk slots so i closed it and typed /trunk again and that's where all it began, my car's trunk was empty even the weight showed 0/400

I had exactly 73 Cocain Bags 
4x Thermites which i just bought
1 x scrap metal 
1x binoculars 
1x Advanced Lock pick 
1x Basic Lock pick

## Additional Information

**Screenshots:**
I cannot show what i had but i can show you what i have now 
these things are what i got after my first chop chop delivery 
https://i.imgur.com/LDJ1NXE.png

**Game Resolution:**
What is your game's resolution?
1752x956

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 29808 - Job Data : Mechanic , Los Santos Customs , Tow Driver

**Notes:**
Those items were worth almost around 30k$ to 35k$ please do something 

I dont have proof since i didnt know that something like this would happen, i mean tbf no one would ever know the exact time that this would happen so that they keep proof of things beforehand.

Suspect: Radio/chop chop work as it vanished only after i delivered my very first vehicle, also i met a guy who told me that his friend also faced the same problem and he does the radio work to however the guy didnt face anything like this since he has never done the radio work.... Anyhow kindly help me and others

**Comment by humayunraza1** [comment]
I didn't know what to do all i did was go to support channel and tell an admin abt it he said he would look into it and told me to submit a report here, I tried driving the vehicle and then checking but it didnt work l

**Comment by humayunraza1** [comment]
Yes m8 im damn sure i didnt coz i dont use my personal car for normal use all i do is store things in it's trunk and store it back in garage, also just few minutes ago before the bug i bought 4x thermites from a guy named John Wick and kept them in the trunk and stored the car then i went to do the radio work and after that you know what happened

**Comment by humayunraza1** [comment]
Note: I play in legacy indian server (thought i should mention this)

**Comment by InZidiuZ** [comment]
Hey,

This has been resolved now.

**InZidiuZ**
*OP-FW Developer*
