### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by shreyanksaksena** [InZidiuZ/op-framework-issue-tracker#506]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

My name Is Shreyank Discord Tag :- @Shawn Frost#6969  
https://steamcommunity.com/profiles/76561198909850957/ 
My Stream Profile 

**Summary:**
Write a short summary of what you're experiencing.

The Thing is If You are kept in the car Trunk Dead And then You are thrown Into the water If you Respawn You will respawn in The same water ( Be it Ocean be it swimming pool ) into the trunk where you were lying dead and there would be options to come out of the trunk after we respawn . and i do not come to the hospital ultimately Thus we respawn 2 times wasting money and time .thus the bug is if we die in water we have to respawn two times

If we Die In Swimming Pool And then we respawn We come to hospital and then i have a vigorous movement on my hospital bed And i die again THus dying 2 times 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

Die And Keep Yourself in a Car Trunk 
Wait for 5 minutes 
Then respawn 
You Would be respawned in THe Ocean 
Press F TO climb Out 

Die In a swimming pool
Wait for 5 minutes 
then respawn 
Vigorous movement on the bed 
You Die again 

**Expected Results:**
What are the expected results?

I should Not Die After i am being Respawned in the case Of swimming pool 

I should Teleported to the Hospital After i Am respawned in the case of trunk car

**Actual Results:**
What are the actual results?

I die 2 Times in the swimming pool case 

I respawn in the car trunk itself instead of hospital 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
I do not have any 
**Game Resolution:**
What is your game's resolution?
1920x 1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

Shawn Frost 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
