### ISSUE TITLE
Suggestion- Room mates get house benefits too

### ISSUE THREAD

**Issue by HuhCjay** [InZidiuZ/op-framework-issue-tracker#507]
**Name:**
Who is suggesting this? Please include discord name. 
Me- HuhCjay#2888

**Summary:**
Write a short summary of what your suggestion is about.
I'm sure a few people have already made complaints about it, not sure if they actually put it here tho so here I am. When I say "house benefits" I mean the able to wake up there and put their cars in the garage too. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would add to realism as irl you can obviously share garages and obviously you should be able to wake up in the bed that you slept in.

**Comment by iGreatWhite** [comment]
Already suggested man check out, #478.
