### ISSUE TITLE
Livery command for EMS

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#508]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
/livery command for the ford explorer "QRV"
**Reason:**
Why would your suggestion be a good addition to Legacy?
The Explorer already has many liveries, It would seem fit for each department in EMS to use the correct Livery, eg: LSFD using the LSFD Livery, Doctors/Supervisors using the Black supervisor livery, and finally you got the default one used by the First Responders

**Comment by InZidiuZ** [comment]
Hey,

This has now been added, together with an /extra command.

**InZidiuZ**
*OP-FW Developer*
