### ISSUE TITLE
Bug report Items are missing from my GTA 5 RP taxi trunk 5 pistols 20 bags of weed  1 thermite  ,tuner chip  these are the only Items I remember of  in my trunk. My discord name is :- Fuk_Fuk_Fukrey#9763, Steam ID is:- https://steamcommunity.com/id/Fuk_Fuk_Fukery/

### ISSUE THREAD

**Issue by DeviLPunisheR** [InZidiuZ/op-framework-issue-tracker#509]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Excellent use of the template!
