### ISSUE TITLE
Radar autodetects stolen vehicles by their plates.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#510]
**Name:**
Who is suggesting this? Please include discord name.
CyberSkunk#5173

**Summary:**
Write a short summary of what your suggestion is about.
Would be a good feature to have the radar alerting you when ever there's a stolen vehicle infront/behind you or atleast sometimes (lets say the radar aint 100%). 

**Reason:**
Why would your suggestion be a good addition to Legacy?
Would be both a helpful and realistic feature to have ingame as we do have lots of criminal activites, especially regarding to vehicles.

**Comment by SATIN187** [comment]
I’m sorry but this is a horrible idea... the whole point is to catch the criminal if he’s abiding by the laws even in a stolen vehicle he shouldn’t just get pulled over cause some system auto detects it... takes the fun away from stealing cars and trying not to get caught

**Comment by 1THC** [comment]
-1 from me as cops would just be able to powergame and automatically know the car is stolen without actually having a reason to pull them over in the first place. This would piss a lot of people off and ruin RP.

**Comment by psyCOSMO** [comment]
As far as IRL it is understandable, but less enjoyable, I would like a command that you can checkplate with the plate that your radar focused on but non of those auto bs.

**Comment by Lankovich** [comment]
Ye, I suppose you're right. PsyCOSMO, that idea aint bad tbh

**Comment by InZidiuZ** [comment]
This is sort of an automated version of #415. Think that one might be a better implementation than this one, though.

**Comment by InZidiuZ** [comment]
Hey,

After further review, this will not be added due to balancing concerns.

**InZidiuZ**
*OP-FW Developer*
