### ISSUE TITLE
Delivery job improvements

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#511]
**Name:**
HS#6627

**Summary:**
1. Can we have Red markers instead of White markers? Or anything else which is brighter than this.
2. Can we have minimap shown all the time during delivery job mission (just like garbage job).
3. Also can you increase the distance for getting the option "Pick up a box in the back of the truck".

**Reason:**
1. https://i.imgur.com/hsIARsO.png <- Just look at the marker man... Barely even visible.

2. Most of the time it's really hard to to find the house door without minimap. It would be good if we can have minimap shown to us just like we have in garbage job when picking up Garbage bags.

3. https://i.imgur.com/UGZCJUN.png <- I am not that far from the delivery location and it still won't let me pick up boxes, I have to go really near to the location. There are some places where it's hard to fit truck in and my truck got stuck just because so I could get the option to pick up boxes.

**Comment by AdeptCL** [comment]
I spent like 5 mins trying to find one door and it was in front of all along.

**Comment by humayunraza1** [comment]
totally agree with this i sometimes had to press esc in order to see the exact location

**Comment by InZidiuZ** [comment]
Hey,

This has now been changed.

**InZidiuZ**
*OP-FW Developer*
