### ISSUE TITLE
Rifles for cops

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#512]
**Name:**
Pancho#0001

**Summary:**
 Cops getting rifles

**Reason:**
with the introduction of criminal full-auto SMG's the cops need some sort of weapon to stay competitive, The smg we have right now is trash, damn near impossible to fire accurately first person and the range on it is essentially nonexistent. Additionally, it cannot be fired out of a car (making the micro smg much more useful). crims have mobility and unpredictability, something that compliments the micro smg quite well. The cops (should you choose to implement this,) would be outfitted with a weapon to fit them quite well. A rifle that compliments the play style of the police: planning, predictability, and reliability. Right now, we are armed with a weapon that fits none of those needs the police have. it's too inaccurate to shoot and be confident that you will hit your shots, its recoil is absurd, its damage is equivocal to a pistol and it can not, by any means, stack up to what a rifle could do. we had the rifles before when crims had SMG's. the smg's are back and I think it would be a wonderful opportunity to give cops a fighting chance. I sincerely hope you consider this, mag dumps happen when you need to fire that many bullets to kill what your shooting at, rifles would cut down on this a lot. Firing wildly hoping you hit something cinematic is great for crims and its hella fun, not so much for cops.

**Comment by Lankovich** [comment]
Totally agree on this! +1

**Comment by ZurxeyH** [comment]
I can agree with this. The PD SMG is absolute garbage, and I would love to see a rifle introduced.
Make us PD Members able to use them as DUTY WEAPONS only.

**Comment by Djmeowzle** [comment]
just give PD a grip for their gun, make the recoil not as bad, giving them AR's would turn everything into what happened last city, cops roll up to a traffic stop, AND PULL AN AR, it would be too unbalanced, just work out the kinks with the SMG, making them maybe reload faster and have less muzzle climb, then it will be fine, we all know shotguns > smg's anyways :^)

**Comment by triatomic** [comment]
do you want tanks too ?

**Comment by Cricketx818** [comment]
-1 there are only like 10 class 2's in the city, Not 100

**Comment by Vedder742** [comment]
I guarantee you that constantly having better weapons than a cop would not make your RP more fun, crims might as well go kill the NPC cops in GTA V story mode.

@Djmeowzle 
At this point of time, the point of this suggestion is at the very least to allow for balance between the clashing sides, which might require entirely changing our SMG as you suggested.
I can tell you that people will be better trained this time around, and assure you that if a cop theoretically pulls out a bigger gun there is a reason for it. Either way, don't think about things from a powergaming perspective on either side and think about the realistic roleplay, cops should be equipped and ready to deal with every situation and have the option to be a step ahead, or at the very least the same step. That is how things work in real life, rifles get pulled out in felony stops etc, it would be stupid not to utilize the tools that cops realistically should have to keep themselves safe and everyone around them. **In every modern city, the police equips themselves according to demand to always stay one step above everyone else, especially when it comes to weapons.** Take a look at the use of force model http://prntscr.com/pijzhm

**Comment by PanchoGarcia** [comment]
@Cricketx818 Perhaps not at the moment but that is how many you are aware of. More will come, many more. i would agree if it were a set amount or something along those lines, but the number keeps growing everyday, and it aint gonna stop anytime soon.

**Comment by DrHenny** [comment]
-1 aslong as what you're suggesting isn't "police issued" i have a crim and a cop and i dislike this suggestion. Micro SMGs are 'Rare' I think it's fair currently.

**Comment by iGreatWhite** [comment]
-1 as of now, this just seems to be another factor that PD has a gun they aren’t afraid to lose because they can’t have it taken from them. I would say this would be an okay suggestion if they are rank limited/supervisor approval from Lt.+ or Cpt.+ and as well use them in certain circumstances. If people were able to rob them off cops with valid RP reason to possess one of these ARs, good enough reason to rob the cop you took it from either personal reason or general PD reason. Also the fact that if caught it’s a huge penalty as it is a PD AR which could be the name of the gun PD Assault Rifle.

**Comment by Aspratic** [comment]
-1 PD has unlimited smgs compared to the very rare mini uzi. People are rarely bringing them out anyway. Once another 1 or 2 automatics are around the city like an AP pistol and tec 9 or unless there's another way to get uzis, then the police should need rifles.

**Comment by Max-House** [comment]
+1 Currently we have no weaponry that is able to respond to the threats PD is facing. Limiting when to use them and who are authorized to use them will address most of the concerns people are having in this thread.

**Comment by Aspratic** [comment]
Make the recoil more controllable for smg... but ARs??

**Comment by iGreatWhite** [comment]
Well if every trooper was able to grab an AR and they were rob able then you have problems with crims having loads of ARs. My suggestion was based around if they are rob able. Also I really don’t think the SMG is that bad.

**Comment by selb97** [comment]
And for me it kind of says something when i'd rather pull out a heavy pistol instead of the SMG in almost every gunfight i end up in.

**Comment by ZurxeyH** [comment]
I'm just really annoyed with having pea shooters for weapons.

**Comment by KPNutz** [comment]
If these weapons are only available to high ranking officers then any argument that they would be ‘abused’ is pretty much nullified. 

There is a fair argument for cops needing to use the SMG more effectively, however this can only go so far. If you’re truly trying to “balance” the server, then you should implement a rifle for high ranking troopers - that way crime with automatic weapons is met by appropriate force (and by a competent high ranked office) but the everyday civilian doesn’t experience it and so it won’t influence role-play unnecessarily. Win-win, no?

**Comment by InZidiuZ** [comment]
Hey,

Closed in favor of #587.

**InZidiuZ**
*OP-FW Developer*
