### ISSUE TITLE
[UI Bug] Multiple people opening bag at once 

### ISSUE THREAD

**Issue by 1THC** [InZidiuZ/op-framework-issue-tracker#516]
# Legacy UI Bug Report
**Reporter:** (Example: Anderzenn#0069 | https://steamcommunity.com/id/anderzenn)
Who is reporting this? Please include discord name and your steam profile. 
1THC#4847

**Summary:**
Write a short summary of what you're experiencing.
I've just experienced a bug where when multiple people try to open a backpack at the same time the actual inventory UI disappears and the inventory cursor is the only thing on our screens allowing no input causing us to all have to relog. This just happened to 3 people at the same time when one person dropped a key and we all opened the bag.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Have one person drop an item and three people open it at the same time.

**Expected Results:**
What are the expected results?
A message should come up saying busy inventory and not let them open the bag.

**Actual Results:**
What are the actual results?
All 3 people who open the bag get no inventory screen and the cursor is the only thing showing which allows no input besides being able to hit f8 and type quit. 

## Additional Information

**Screenshots:**
If possible, please include screenshots of the issues you're having.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Notes:**
For anything else noteworthy.
I believe being able to type inventory in the console to open the inventory would be a possible fix to this.

**Comment by SATIN187** [comment]
I’ve found if that happens to hit F8 and type phone to bring phone up and then exit phone is how I’ve fixed it

**Comment by 1THC** [comment]
Yeah , I've got the cursor disabled on the phone so thats probably why it wouldn't work for me.

**Comment by InZidiuZ** [comment]
Hey,

Tried replicating it with 2 & 3 people, but nothing. When someone else was already in it, it just takes you to your own inventory.

**InZidiuZ**
*OP-FW Developer*
