### ISSUE TITLE
Repo Thinking cars paid off

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#517]
**Reporter:**
Cricketx818

**Summary:**
I am trying to repo a guys car, and it will not allow me to.

**Steps to Reproduce:**
I have no clue

**Expected Results:**
Car suppose to get deleted

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
https://plays.tv/video/5da2c5c7ad2f9572a8/repo

https://cdn.discordapp.com/attachments/591055233078263840/632828386607235074/cricket.JPG

**Notes:**
I think the licence plate of that car matches with a diffrent car that is paid off, and the other car is paid off that is why it is not allowing me to repo that car

**Comment by InZidiuZ** [comment]
Maybe include the license plate if you think it's matching with another car...? 🤔

**Comment by Cricketx818** [comment]
This is Happing to every car with any license plate

**Comment by InZidiuZ** [comment]
Hey,

This issue has since been resolved.

**InZidiuZ**
*OP-FW Developer*
