### ISSUE TITLE
Bug report Stuff gone from box with evidence

### ISSUE THREAD

**Issue by ZroonX** [InZidiuZ/op-framework-issue-tracker#518]
**Reporter:**
ZroonX#5281
https://steamcommunity.com/profiles/76561198058001316/

**Summary:**
I put a mk-2 pistol and a pair of cuffs in my box and next time i look in box its gone, the video tells everything

**Steps to Reproduce:**
Stuff staying in box

**Expected Results:**
stuff staying in box

**Actual Results:**
stuff gone from box

## Additional Information

**Screenshots:**
https://youtu.be/VOnU6ohQc9w
dont have screen of f8 menu
**Game Resolution:**
1980x1080
**Player Data:**
4532

**Notes:**
Noone else was in the box between i put it in and came back so it cant be someone stealing it cuz the other guy in the video was standing in the hallway and hes a really good friend and he wouldnt do that

**Comment by InZidiuZ** [comment]
Hey,

Unable to investigate, closing.

Could it have been someone on another server, perhaps? Don't have DB logs for opened house inventories, so not able to check myself.

**InZidiuZ**
*OP-FW Developer*
