### ISSUE TITLE
Grandma's / Grandpa's house

### ISSUE THREAD

**Issue by Shifty123** [InZidiuZ/op-framework-issue-tracker#519]
**Name:**
Shifty#4167
**Summary:**
I suggest having a place up north  (Sandy/Grapeseed/Paleto) Where us criminals can pay money for our friends to get revived there.

**Reason:**
This would avoid a lot of weird situations at the hospital where we have a shootout with cops and then we bring all our boys to the hospital. It will encourage Crims to grab their friends and get out of there in order the get them revived elsewhere rather than the public hospital. Would definitely encourage gang's to RP accordingly and rushing to get treated by an underground doctor.

**Comment by ZroonX** [comment]
+1

**Comment by allenle4** [comment]
+1

**Comment by Kristoffermyr** [comment]
+1

**Comment by Cricketx818** [comment]
+1

**Comment by InZidiuZ** [comment]
y'all are doing this +1 incorrectly, you're meant to use the reaction feature... this will still be at the bottom when I sort using the reactions 🤷‍♂

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
