### ISSUE TITLE
EMS should be able to do /tracker off/on

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#521]
**Name:**
Allen#8921

**Summary:**
EMS on the server should be able to do /tracker on/off and it will turn off their tracker on the map/gps

**Reason:**
Just incase EMS gets kidnapped or such, they can turn it off once the kidnappers breaks their tracker. It's just like how the PD has the command, so I don't see why the EMS shouldn't have it.

**Comment by InZidiuZ** [comment]
This has already been suggested in #468.
