### ISSUE TITLE
Cannot "/suspect out" on the new police mustang.

### ISSUE THREAD

**Issue by TheBillyZee** [InZidiuZ/op-framework-issue-tracker#523]
**Reporter:** BillyZee#1111
Who is reporting this? Please include discord name and your steam profile.

**Summary:** Unable to perform "/suspect out" on someone in the new police mustang. I and many other have tried the command while in the vehicle and outside from multiple angles but no luck. The only way is to "/carry" them out. 

**Steps to Reproduce:** The police mustang is the only vehicle I've encountered this issue with so maybe look into the vehicles coding, see if something is blocking us from performing "/suspect out". "/suspect in" works just fine.

**Expected Results:** For the suspect to pop out once you do "/suspect out".

**Actual Results:**" Nothing happens when you perform "/suspect out" on someone that is in the mustang via "/suspect in".

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
