### ISSUE TITLE
Whenever I am going to the weed farm while going there There is bugged road where i fall down and many time die

### ISSUE THREAD

**Issue by AGboi** [InZidiuZ/op-framework-issue-tracker#525]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by AdeptCL** [comment]
It's not a bug. Your PC can't handle the world loading and you fall trhough.
It happens to me sometimes.

**Comment by InZidiuZ** [comment]
As @AdeptCL said, most likely PC issues. Also, make proper use of the template next time...

**Comment by AGboi** [comment]
i have i7 8700k 1050ti and 16 gb ram so how cannot it handle it?

**Comment by AdeptCL** [comment]
It doesn't happen to me many times until my PC is struggling.
Never happens to anyone I know OOC/IC.

**Comment by InZidiuZ** [comment]
Do you have GTA installed on an SSD or HDD, @AGboi?
