### ISSUE TITLE
Bug report - police radio

### ISSUE THREAD

**Issue by basemas** [InZidiuZ/op-framework-issue-tracker#527]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Parodax#6371

**Summary:**
Write a short summary of what you're experiencing.
When you go in cover with Q, and use your radio after releasing the radio button the character will go out of cover.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
go in cover ( behind a car or w/e ) use your police radio to transmit something and release the radio button.

**Expected Results:**
What are the expected results?
Staying in cover

**Actual Results:**
What are the actual results?
Character stands up like all animations are reset or something.

**Comment by psyCOSMO** [comment]
I think it's not a bug,
Probably the script didn't get coded for remembering which animation you were in (sitting/proning) and when you do the animation for the radio it puts you back in the generic animation.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
