### ISSUE TITLE
[companies/stocks] 48 hrs or last 50 Transactions Log for Company Register

### ISSUE THREAD

**Issue by Trasaraj** [InZidiuZ/op-framework-issue-tracker#528]
Who is suggesting this? Please include discord name.
taoteique#6402

Write a short summary of what your suggestion is about.
Companies should have a 48hrs log or last 50 Transactions of who bought the shares, who sold them. Now we can check the last 5 transactions if it's possible it should be last 48 hrs or last 50 Transactions. A scroll down feature can be used at the same place.

Why would your suggestion be a good addition to Legacy?
I owe a company, its very difficult to make a strategy for the company without knowing who is buying or who is selling. most of the people play with stocks, they think its state treasury money so they withdraw when shares go up, no loyalty towards the company or the shareholders. If I can see the last 48hrs list or last 50 transations I can know which people should not be employed in my company. Will able to grow my company without fear of some backstabber.

**Comment by humayunraza1** [comment]
+1

**Comment by DoctorVespucci** [comment]
+1

**Comment by Sam601** [comment]
+1

**Comment by sayamjainn** [comment]
+1

**Comment by 1THC** [comment]
+1

**Comment by BlurryGiri** [comment]
+1

**Comment by InZidiuZ** [comment]
If this is still relevant, please create another issue.
