### ISSUE TITLE
Armor Issue - Zurxey

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#529]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Zurxey#2607 https://www.steamcommunity.com/id/Zurxey
**Summary:**
Write a short summary of what you're experiencing.
So, basically, this issue will be regarding the Police Department Armor vs. Civilian Armor. Showing the fact of how both are completely messed up. 

- PD Armor takes 2 shots to get rid of, and then another shot to kill.
- Civ Armor takes 3 or so SMG Mags to even break. You don't take damage anywhere above belt and 
under neck.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Purchase gun store armor, equip, go clock into PD, get armor, and shoot each other.
**Expected Results:**
Civ Armor and PD Armor should be the same, or differentiate in minor ways.

**Actual Results:**
What are the actual results?
PD Armor is way less than Civ armor. Also, a $1500 price tag for PD members every shootout isn't too great. 

## Additional Information
It has been like this for months now, and is causing so many battles to be lost by PD, as we need lucky headshots to even remotely damage a person. (With our weaponry recoil, this isn't easy)
Officers are losing 8v2 gunfights, and getting downed almost instantly after shooting civs multiple times.

**Screenshots:**
https://clips.twitch.tv/GoldenSpotlessBeef4Head (Clip from BowchkaHonkHonk)

https://www.twitch.tv/videos/495083961 (Body cam with testing)

https://clips.twitch.tv/IcyAmusedVelociraptorHotPokket (Clip from I_Deadeye_I POV.)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 1399 - Job Data: Law Enforcement, SASP, Senior Trooper

**Notes:**
For anything else noteworthy.
The video(s) provided one is from Ivana Vin, other is body cam from Hunter Zurxey.

**Comment by InZidiuZ** [comment]
Hey,

This issue has since been resolved.

**InZidiuZ**
*OP-FW Developer*
