### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SULTAN6666** [InZidiuZ/op-framework-issue-tracker#530]
**Name:**
SULTAN

**Summary:**
i would ike to suggest that everytime we file a report for a player, a notification should be generated regarding the status of the report. i mean we should know what action was taken. plus i am quite sure that only reports with proofs are being taken care of and the in game reports are being completely ignored.

**Reason:**
if you implement this then it would ensure the law in the city and would gain faith with the citizens that the government is actually working and is strict against any unlawful acticites

**Comment by InZidiuZ** [comment]
Hey,

If you want to open a proper case, do it on the forum. /report is just for 'quick-reports' which may be disregarded at times.

**InZidiuZ**
*OP-FW Developer*

**Comment by SULTAN6666** [comment]
Thats what i meant as quick reports get disregarded sometimes and the culprit gets away free. Its a suggestion coz everyone can not afford to do bodycam with gta5 as you know its quite a burden on resources on PC. Rest i leave to your fine jurisdiction. Peace!!

**Comment by InZidiuZ** [comment]
Would recommend either [Plays.tv ](https://plays.tv/) or [ShadowPlay](https://www.nvidia.com/nb-no/geforce/geforce-experience/shadowplay/) as those are known to not make a huge impact on performance.
