### ISSUE TITLE
[companies/businesses] Pawn Shop / Resell Location

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#531]
**Name:**
IC: Chris Leigh.
Discord: AdeptCL#0402.

**Summary:**
A Pawn Shop location which allows you to sell melee weapons, misc items (drills/lock picks/etc), and rubber/glass/battery/etc (as there is no current location).

**Reason:**
It's not a negative, but it is very easy to find melee weapons. You can find them in garbage jobs, chopping jobs, diving, and house robberies now. It would be good if there was a location in the city, in which we can sell these melee weapons, even at a cheap price (like $10-50 per melee weapon).

Another feature I think would help with the above is being able to sell rubber/glass. These are the most collected from my experience with certain jobs/diving. I think being able to sell these on when no-one else is buying them would be a good option. Just like it is for metals at the warehouse.

**Comment by FilipQeh** [comment]
+1.

Like the idea, no mechanic buys rubber or glass since it is so easy to get. This just makes it that everyone ends up with either a stack of 400 rubber or they end up throwing it away. Definitely would love to see a pawnshop!

**Comment by Aspratic** [comment]
I like this idea, but it is not nearly in depth enough. There needs to be bigger changes for a pawnshop like new items etc

**Comment by DaxterPancake** [comment]
Alternatively, we could create a system where you can sell back to the stores that sell you items for an extremely reduced price. For example, you find a knife while robbing houses, you can take that knife to a gun store and drag and drop it back into the shop keepers inventory to recieve some money.

**Comment by rajbastakoti** [comment]
like the idea it makes resources/items players obtain from any kind of (garbage ,or house robbery , scuba ) jobs a more managed and useful thing , instead of just stacking up in inventories

**Comment by AdeptCL** [comment]
I'd like to bring this back up from 2019 and 2020, into 2021.
Now if anything is a very good time period to introduce something like this. Throughout many activities, miscellaneous items are easily obtainable. A spot in which these items can be sold would be perfect.

Things that can be sold to this: drills, lock picks (adv/basic), repair kits, etc.

**Comment by claymstehling** [comment]
I would like to bump this back in. I think this would be a great addition to the city. 


There are many things that could be sold here and things that could be added to sold here as well.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
