### ISSUE TITLE
[companies/stocks] Powers to rent house to customers for all CEO's of the company. For eg : A level 3 access.

### ISSUE THREAD

**Issue by JatinBhatia10** [InZidiuZ/op-framework-issue-tracker#532]
Hey! I'm JB10 from India. I'm a CEO of a company in legacy and I have a suggestion to make. I'll add the summary below. You can find me on discord : JB10#7350

Summary : So after facing a lot of difficulty for all the company owner, On behalf of everyone I would like to give an idea. So my idea is to add a power from the company dashboard to the company's board members/CEO/top staff, so that they can also have the powers to put it up for rent to customers. It is very difficult for a single guy to be in city all the time and meet the sales. So we Request you to have a look on our request. This feature will be really helpful and make all the renting procedure much easier for companies.

Reason : The reason for suggesting this idea is because, it has been very difficult for a single guy ( company's owner) to be available in city every time and put the house for rent. Without the owner, it's has been very difficult to sell property without his presence. Adding this new feature will make the whole process much easier and faster.

**Comment by MICWIK4U** [comment]
+1 Same Issue As I am Co-founder Of A company In Legacy India like Our Customer always Have to wait for CEO to arrive and Alot them There Rooms.

**Comment by Trasaraj** [comment]
+1

**Comment by iMStokes** [comment]
+1

As someone who spends a bit of time on the server after the owner of the company is asleep, this would help resolve some issues with people not mixing with time zones - and allow us to get more properties out to people in search of properties in that moment.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
