### ISSUE TITLE
Bug report glasses

### ISSUE THREAD

**Issue by Miliax** [InZidiuZ/op-framework-issue-tracker#533]
**Reporter:** 
Miliax#2530 
https://steamcommunity.com/id/miliax

**Summary:**
I made a new character, and I chose some glasses that I liked. After a while I wanted to take off the glasses by typing /glasses. Then she put on some ugly ass glasses instead of taking the first one off. So I had 2 glasses. I tried to make new outfits and save without glasses etc but when I typed /glasses she still put the ugly ones on. 
After that I tried to make a male free model and typed /glasses he didn’t have any, only the female model has and u can’t take them away.

**Steps to Reproduce:**
Make a female free model choose no glasses or any glasses you want, then type /glasses.

**Expected Results:**
To have the glasses you actually want.

**Actual Results:**
When I choose to take off my glasses she puts on a different pair of glasses.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Typing this on my phone so can’t see right now.
**Notes:**
For anything else noteworthy.

**Comment by Miliax** [comment]
I just realized that my main character has that same problem with the glasses

**Comment by AdeptCL** [comment]
Have you tried leaving the city and rejoining?
You could also go to a clothing store, remove glasses, add the ones you want and then you can save the outfit.

**Comment by Miliax** [comment]
I’ve tried leaving city, I’ve tried removing glasses and saved that outfit but when I type /glasses they still come in. And when I choose a pair of glasses I want, and I wanna take them off she puts on another one like in the video.

**Comment by AdeptCL** [comment]
The only thing I can potentially suggest is when you're in the city next, ask for a reskin in /report and basically redo your character (without actually restarting everything).

**Comment by Miliax** [comment]
well i made a new character, and it still happens. so that's not it.

**Comment by iGreatWhite** [comment]
Did you put the glasses on in your first initial creation?

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*

**Comment by Miliax** [comment]
It's still happening :(
