### ISSUE TITLE
TOYOTA SUPRA ALL THE MODIFICATION ARE MISSING NOW AFTER UPDATE.

### ISSUE THREAD

**Issue by SHIKARI-007** [InZidiuZ/op-framework-issue-tracker#535]
**Reporter:**
Discord ID SHIKARI#7226 Steam Link https://steamcommunity.com/profiles/76561198980369176/

**Summary:**
My Toyota Supra bought from executive dealership in heroic tire had all the MODIFICATION in LOS SANTOS CUSTOMS but now all the modification like spoiler,skirt, front bumper back bumper, hood and roof are all gone only stock available.  

**Steps to Reproduce:**
This happen after the last update it was all there before.

**Expected Results:**
Have all the modification back in los Santos customs for the TOYOTA SUPRA.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920X1080 144Hz

**Player Data:**
Character ID: 21098 Job Data Mechanic, Los santos customs, tow driver.

**Notes:**
For anything else noteworthy.
![Screenshot (15)](https://user-images.githubusercontent.com/56630831/66982800-9aa8d680-f0d4-11e9-96ed-bebef7f85e72.png)
![Screenshot (16)](https://user-images.githubusercontent.com/56630831/66982801-9aa8d680-f0d4-11e9-92fc-3652a717cbac.png)
![Screenshot (17)](https://user-images.githubusercontent.com/56630831/66982802-9b416d00-f0d4-11e9-9440-2b7514bb2952.png)
![Screenshot (18)](https://user-images.githubusercontent.com/56630831/66982803-9bda0380-f0d4-11e9-9bde-52f8acdbcb8b.png)
![Screenshot (19)](https://user-images.githubusercontent.com/56630831/66982804-9bda0380-f0d4-11e9-9dd2-69ece2d7b948.png)
![Screenshot (20)](https://user-images.githubusercontent.com/56630831/66982805-9bda0380-f0d4-11e9-8ab3-ee055dd1b74b.png)
![Screenshot (21)](https://user-images.githubusercontent.com/56630831/66982806-9bda0380-f0d4-11e9-80bc-ce4a7b734365.png)
![Screenshot (22)](https://user-images.githubusercontent.com/56630831/66982807-9c729a00-f0d4-11e9-9b65-c679f6ab1551.png)

**Comment by Lankovich** [comment]
I think this applies to all the exclusive cars atm, I might be wrong tho.

**Comment by InZidiuZ** [comment]
Hey,

No repro, nothing I can do to try & investigate it, closing.

**InZidiuZ**
*OP-FW Developer*

**Comment by SHIKARI-007** [comment]
I guess i ran out of luck on this one o well Thanks For your help appreciate it.
