### ISSUE TITLE
Buff mansion-robberies

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#537]
**Name:**
BowchkaHonkHonk#5146

**Summary:**
House Robberys in the 2 story houses are not high in value compared to one story. The 2 story houses (primarily in vinewood) have way to much space between objects to rob and similar pay out to ones in grove street. I feel as an incentive to rob these houses make certain things higher chances to get. Like possibly coke bags or if you get money its no less then 100$ due to it being a higher wage class.  

**Reason:**
Why would your suggestion be a good addition to Legacy?
When robbing houses theres really only 2 places people primarily rob. Grove and Mirror Park. This would then spread it out more and make vine wood more appealing to rob if these changes were implemented

**Comment by InZidiuZ** [comment]
Hey,

This has now been changed, and mansions have been buffed.

**InZidiuZ**
*OP-FW Developer*
