### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by donny1323** [InZidiuZ/op-framework-issue-tracker#538]
**Reporter:**
shrut#8123
**Summary:**
i had 40 thermite and it got converted into 35

**Steps to Reproduce:**
give my thermites back bro pls

**Expected Results:**
i need my hard earned thermite

**Actual Results:**
40 ke 35 thermite hogaye

## Additional Information

**Screenshots:**
https://drive.google.com/file/d/1leDSWpZ9poEVuqamZVf7bVV4FrS39AKB/view

**Game Resolution:**
1920 x 1080

**Player Data:**
33006

**Notes:**
For anything else noteworthy.

**Comment by TwoplePop** [comment]
that looks hard to test with no information

**Comment by iGreatWhite** [comment]
These steps don’t work can you provide ones that do?

**Comment by AdeptCL** [comment]
They're my thermites now. ( ͡° ͜ʖ ͡°)

**Comment by donny1323** [comment]
sir they were 40 and now 35 sir pls you guys are god of game pls give me i had already lost my 2 tuner chip from taxi and now this, that time i did not had video evidence of tuner chip so did not reported but and i have and u r not helping pls sir

**Comment by AdeptCL** [comment]
I am god of game but unfortunately this is something that can't be fixed (I don't think).
I have never had this issue with thing sin my vehicles, so it could be a taxi storage issue.

**Comment by donny1323** [comment]
no bro it got vanished you can see that i was having 40 thermites and then it was converted into 35

**Comment by donny1323** [comment]
@AdeptCL bro pls help me i did garbage for 1 week for daily 10-12 hrs and finally wanted to sell but my 40 thermite got into 35

**Comment by AdeptCL** [comment]
What do you think I can do? Magic some thermite out of thing air for you.
It's just a game. Stop taking it so seriously.

**Comment by InZidiuZ** [comment]
Hey,

lol.

**InZidiuZ**
*OP-FW Developer*

**Comment by donny1323** [comment]
pls bro spawn 5 thermites u saw that they vanished and i had proved it

**Comment by SATIN187** [comment]
It’s not gonna happen just take it and leave it things happen it’s a video game get over it
