### ISSUE TITLE
Apartment & Blocks Renewal 

### ISSUE THREAD

**Issue by Trasaraj** [InZidiuZ/op-framework-issue-tracker#539]
**Reporter:**
taoteique #6402

**Summary:**
I hold a company in Legacy India, my apartment holders are not renewing the apartment and they still hold the key of the room. I too not renewed one block and I still hold the key. can you please check this Bug. Thank You.

**Steps to Reproduce:**
Please fix this and allow me to rent the room to some other citizen, Company is losing revenue.
  
**Expected Results:**
Companies should have powers to remove any apartment holders if they don't pay rent.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by Trasaraj** [comment]
![0_20191018002747_1](https://user-images.githubusercontent.com/56026311/67040148-7d115680-f140-11e9-8b35-fc05109979b5.png)

**Comment by AdeptCL** [comment]
The auto renew does not exist. You need to manually pay the rent/maintenance costs. I believe there is a week threshold after the date due for someone who cannot pay immediately.

**Comment by iMStokes** [comment]
This is something I've questioned tonight as well.   

To my understanding the "week long" grace period is supposed to be for companies who end up being bankrupt to get back into the positives.  

However I have tenants who are moving and their rent is overdue - and we cannot remove them to get new tenants in who want to live there.   Ultimately, companies are losing out on money if people are not being automatically or forcefully removed for non payment.  If motels boot you the day of or after for non-payment - then houses should follow the same rule.

**Comment by Trasaraj** [comment]
How will I renew my Blocks if people don't renew And if they leave after grace period then the company has to face the loss of one week.

**Comment by AdeptCL** [comment]
Then you gotta send round the Bailiffs! Pog

**Comment by SATIN187** [comment]
bailiffs are court room officers lol unless youre british

**Comment by Trasaraj** [comment]
Real-world I will Put a big lock outside the door. lol

**Comment by InZidiuZ** [comment]
Hey,

The purchased properties will stay in an "overdue" state for a week before the tenant loses permanent access, and the property is given back to the company.

**InZidiuZ**
*OP-FW Developer*

**Comment by selb97** [comment]
There should be some way to see who has and has not paid rent tho. I do belive that there should also be a way to edit the rent on agreement of both parts.

There should also be a way of kicking someone out of the apartment.
