### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by 9dgamer** [InZidiuZ/op-framework-issue-tracker#540]
9DGAMER AKA SAMOSA

i have 2 suggesion please add spawn and garage store for level 2 access and please add gear change speed for tuner chip

reason
1st suggestion reason is when 2 peoples purchase one villa like me it was regestered on my account but i gave higher access to my friend casue he pay half of the rent with me so please add spawn and garage access for level 2 access

2nd suggestion reason is if you add fast gearbox sytem then we properly enter the city race cause gear change is more imp because when the gear change is faster then the acceleration of the car is also faster

**Comment by InZidiuZ** [comment]
Please only include one suggestion for each issue. This has also already been suggested in #478.
