### ISSUE TITLE
[new][game/blackjack] Blackjack

### ISSUE THREAD

**Issue by thefinalgamer** [InZidiuZ/op-framework-issue-tracker#542]
**Name:**
Who is suggesting this? Please include discord name.
th3finalgamer
**Summary:**
Write a short summary of what your suggestion is about.
can we have blackjack?
**Reason:**
Why would your suggestion be a good addition to Legacy?
just thinking it would be fun to have more things I can lose my money on thanks

**Comment by InZidiuZ** [comment]
If this is still relevant, please create another issue.
