### ISSUE TITLE
Paintball

### ISSUE THREAD

**Issue by Miliax** [InZidiuZ/op-framework-issue-tracker#543]
**Name:**
Miliax#2530

**Summary:**
I’ve been thinking. There is nothing much to do with your friends in the city. Besides if someone make an event of course. But why not have like activities in the city? Such as paintball etc. How, I don’t know. Maybe make a fast travel, maximum 6 people etc. last one standing wins. Those who gets hit gets kicked from the fast travel and have to wait outside on the friends.

**Reason:**
Cause it would bring joy and people get to interact with each other on a fun way.

**Comment by psyCOSMO** [comment]
I would definitely like more legal activities with or without groups

**Comment by 1THC** [comment]
Paintball would be dope as shit. There's already a paintball gun mod that exists (https://www.gta5-mods.com/weapons/paintball-gun) and maybe add betting to the system. For example: 500$ entry and winning team gets all the money placed in.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added to the actual framework. Alternatively, it could be a separate server at some point. But closing as I won't be doing anything with this anytime soon.

**InZidiuZ**
*OP-FW Developer*
