### ISSUE TITLE
[new][game/roadflares] Roadflares

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#544]
**Name:**
CyberSkunk#5173

**Summary:**
So I've been in a lot of different situations now where I felt like I really needed roadflares to make my work easier as a Police Officer. For example traffic accidents, blocking roads, re-directing traffic and even bankrobberies at evenings/nights, where I can put them down to make the "line" way more visible for civilians.

**Reason:**
I believe this would improve the RP for the police and the surrounding civilians as it looks realistic and is very useful. This mod example I linked even makes the npc stop(?).

Here's a link for what I mean or that perhaps could be to any use.
https://forum.fivem.net/t/release-road-flare-realistic-slows-down-ai-cars-nearby/249503

**Comment by superiorchicken007** [comment]
With flares being added into the city it would be nice to see them in the PD shop and also in the trunks of PD cars.  It can be used on traffic accidents like noted above or when conducting checkpoints on roads.

**Comment by InZidiuZ** [comment]
Closing in favor of #2395.
