### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JackToes** [InZidiuZ/op-framework-issue-tracker#545]
**Reporter:**
🤡Jack🤡#7009 
**Summary:**i dont get my keys when i get my car out of the garage 

**Steps to Reproduce:**
![2019-10-19_20-14-27-475](https://user-images.githubusercontent.com/56508250/67149623-a1d70c80-f2ad-11e9-80e8-00e1631d9ec1.jpg)

**Expected Results:**
get my car back to work

**Actual Results:**
get my car back to work

## Additional Information
i got no keys

**Game Resolution:**
idk
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Include a video of it happening as well as the license plate to the car.

**Comment by InZidiuZ** [comment]
Also write /info whilst in-game & provide a screenshot of the given information.

**Comment by InZidiuZ** [comment]
Closing due to no response.
