### ISSUE TITLE
LSFD Content.

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#546]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
I have a few suggestions to add some content for Los Santos Fire Department, Here are some:
1. Possible Arson script, People can start fires, And get LSFD Notified so they can go out there and stop it.
2. Maybe have Thermite fire go out of control and start a fire which results in cancelling the robbery and notifying LSFD to stop it, (Only if a Fireman is sign on, similar to Doctors in Pillbox)
3. A Fire Department Fire Truck in Spawn menu or an Actual Fire Department Building.
**Reason:**
Why would your suggestion be a good addition to Legacy?
For now, LSFD is just a roleplay job, They go around and it help people stuck in places, Maybe a stop a fire or two IF people notify us, It would be nice just giving them a little bit more content, Make the job more enjoyable.

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new, more detailed issue.

**InZIdiuZ**
*OP-FW Developer*
