### ISSUE TITLE
EMS Improvements

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#547]
**Name:**
Duroode#2178 & LegacyRP EMS

**Summary:**
Possible Idea's for the EMS of Legeacy Roleplay.

**Reason:**
I got togeather a few Suggestions from other EMS and put them in a long post and got the Entire EMS team to vote on it. Seen [Here](https://gyazo.com/4241a74d720ecfd2e547aa75da451ebe) the Majority of the jobs seem to be under 2 and 3. 3 Being the one something server side would need to be done for it to work, With number 2 it would require the EMS job in-game to have access to the Doors in PD.

**Comment by Duroode** [comment]
Also Forgot to Add, EMS Need access to the /tracker Command, We're currently Unable to turn our trakcers on or off.

**Comment by InZidiuZ** [comment]
Hey,

For the still relevant suggestions, please create individual issues.

**InZIdiuZ**
*OP-FW Developer*
