### ISSUE TITLE
[UI Bug] GARAGE UI LIST CUT OFF

### ISSUE THREAD

**Issue by joevapes3** [InZidiuZ/op-framework-issue-tracker#549]
# Legacy UI Bug Report
**Reporter:** https://steamcommunity.com/id/northbayjoe
Who is reporting this? DISCORD: northbayjoe
#5571 

**Summary:**
Cant see all my cars in the garage list after owning more than 25 of any cars, bicycles, and dirt bikes. The list exceeds the length of the screen on 1920x1080 resolution

**Steps to Reproduce:**
Go to any garage or home garage and look at your garage list after owning more than 25 of any cars, bicycles, and dirt bikes. 

**Expected Results:**
To be able to see all the cars, bicycles, and dirt bikes on the list in your garage.

**Actual Results:**
You cannot see all the cars, bicycles, and dirt bikes on the list in your garage after the 25th purchase. 

## Additional Information

**Screenshots:**
https://ibb.co/D71LJrB
**Game Resolution:**
1920x1080

**Notes:**
No rush, but just wanted to point this out. Would be cool if you were able to split the list into multiple Columns or how ever you wanna do it. Thanks for all the work you do.

**Comment by InZidiuZ** [comment]
Hey,

lol

**InZidiuZ**
*OP-FW Developer*
