### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Vexedgaming** [InZidiuZ/op-framework-issue-tracker#550]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
@VeXeD GaMinG#1036      https://steamcommunity.com/id/V3XX3DG4MlNG/
**Summary:**
Write a short summary of what you're experiencing.
My plane got stuck at the cocaine air strip
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
we should get a proper key so that we can lock and unlock the plane easily
**Expected Results:**
What are the expected results?
we should get a proper key so that we can lock and unlock the plane easily
**Actual Results:**
What are the actual results?
Results can help people
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
http://prntscr.com/plppih
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

You already get a key for the plane in your inventory... try clearing your cache if the issue persists.

**InZidiuZ**
*OP-FW Developer*
