### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by hamzah7865** [InZidiuZ/op-framework-issue-tracker#551]
**Reporter:**
myself Hamzah.
discord id: Hamzah#8692
steam id: J_O_K_E_R

**Summary:**
when pressing the microphone key the sound does not produce and sometimes the microphone button does not respond. I have changed the button also but still does not respond. 

**Expected Results:**
while pressing the microphone key it should work accordingly.

**Actual Results:**
the microphone button does not work. 

## Additional Information

**Game Resolution:**
1920*1080

**Comment by Miliax** [comment]
I agree, the microphone is cutting off and I have to like make a sound for it to react then I have to talk really loud hah. I’ve been trying to change key binding as well.

**Comment by InZidiuZ** [comment]
Hey,

This is a GTA issue, Change your voice/activation settings.

**InZidiuZ**
*OP-FW Developer*
