### ISSUE TITLE
Proper Class 2 Reimbursement

### ISSUE THREAD

**Issue by Skhurt** [InZidiuZ/op-framework-issue-tracker#552]
**Name:**
Skhurt#8910

**Summary:**
Re-implementing class 2 weapons for people that purchased them second hand, or full refunds for people that were foolish enough to trust in the RP of higher quality weaponry. Example: You introduced regular AK's post-wipe for RP, so spare the people who invoked that same experience as now the benefit of the doubt with the same thing as the people who paid real money. We shouldn't leave anyone high and dry, especially when there's RP involved. I don't care whose mistake it was in the long run, but to disregard our community effort into PROPERLY distributing them and actually roleplaying was booty cheeks.

I'm not asking you to spawn money, or more items; maybe just distribute what's being used for silly decryption messages that are being google translated/worse, and then focus on your gun heist stuff accordingly.

**Reason:**
Trusting in the RP, and then realizing that was a bad choice after my inventory was manually overwritten with no personal word, or reconciliation outside of "ask the players for a refund". I understand everyone's busy, but you're not too busy to compensate me or other players for an internal affairs mistake.

**Comment by InZidiuZ** [comment]
Hey,

Not a framework suggestion, closing.

**InZidiuZ**
*OP-FW Developer*
