### ISSUE TITLE
Unable to see evidence as a criminal

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#553]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Aspratic#3121 https://steamcommunity.com/id/aspratics/
**Summary:**
Write a short summary of what you're experiencing.
Unable to destroy/see evidence as a criminal.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Pulls out a flashlight and cannot see bullet casings or anything of that nature to destroy or even look at
**Expected Results:**
What are the expected results?
To be able to see and destroy evidence
**Actual Results:**
What are the actual results?
No evidence to destroy or look at as a criminal
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

I had forgotten to start the evidence, lol. Should be active now.

**InZidiuZ**
*OP-FW Developer*
