### ISSUE TITLE
Storage Inventory not Showing Up

### ISSUE THREAD

**Issue by JFEAndrews** [InZidiuZ/op-framework-issue-tracker#554]
Dynasty#7062
https://steamcommunity.com/profiles/76561198180541363/

So the issue I am having is that one of my three storage locations in my house isn't actually showing me what's inside the storage unit.  So when I hit E to access it it only shows what's in my inventory and it doesn't show what's in the storage.  It was fine for the past week or so but it just wont show up now.  I have tried multiple times deleting the storage container and adding a new one to see if that would fix the issue and it has not yet costing me $6000 in game.  Attached are going to be a screenshot of me showing that the Access actually shows up and what happens when I actually try to Access my storage.  Also included will be everything that was in my storage just in case it completely wiped my entire inventory!

Player Data
Character ID 9691
Job Data - Mechanic, Los Santos Customs, Tow Driver

https://gyazo.com/307a2f1e9e8c77ff51187a15306749f2 - Showing that is says Access for Storage
https://gyazo.com/292921d8dc84c85e5156caf7866afa41 - When I try to Access Storage

Screenshots of what I had in storage prior to this happening
https://gyazo.com/8c4d171d1ac1746052db7003b7393f71
https://gyazo.com/d5cecd2327f226a4560d84fd05a4c44b
https://gyazo.com/c58273937bca69500562be642ba9596d
https://gyazo.com/5349c299364233a0a79a302e0689592a
https://gyazo.com/69bf9c11d61f883abe14fd0ba1756e1b
https://gyazo.com/dd5acdc8437621f065f7d9f7bf45c295

**Comment by JFEAndrews** [comment]
So I did try swapping cities and was able to see the inventory in city 2 and then when I swapped back to city 3 it wasn't showing up....but for the other cities it is fine....idk if that's just a little bug but thought it was worth sharing!

**Comment by InZidiuZ** [comment]
Any update on this after the server restarted? Is it still an issue, or was it perhaps some inexpiable anomaly? 😕

**Comment by JFEAndrews** [comment]
Honestly I haven't checked on city 3 today but I will let you know...I know it was fine on city 1 and city 2 but it just wouldn't show up on 3....I'll have a look though....could've been an anomaly

**Comment by JFEAndrews** [comment]
Yeah so now on city 3 my inventory in my stash is showing up....hey I mean maybe it wasn't a bug and just a inexpiable anomaly!
