### ISSUE TITLE
Possible weapon issue

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#555]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
I don't know this is a bug or a glitch but when we take SMG from storage and then put in out inventory and then fire one bullet and put it back and then on vehicle still we can use the SMG.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
I don't know after putting back SMG in the storage still we can use.
**Actual Results:**
What are the actual results?
I don't know after putting back SMG in the storage still we can use.
## Additional Information

**Video**
https://plays.tv/video/5dad2414ed50b7b1d8/-

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920×1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID - 7247 
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
