### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Terry-Crews** [InZidiuZ/op-framework-issue-tracker#556]
**Reporter:**
Xwezio#5716

**Summary:**
Status/Percentage goes and no option to fertilise or water more after first planting.

**Steps to Reproduce:**
Plant the pot and water and fertilise the first time exit the building come back in and the percentage should be gone 

**Expected Results:**
Come back into the house and see the status/percentage.

**Actual Results:**
percentage/status disappears 

**Screenshots:**
https://plays.tv/video/5dad943a11e8c84b81/status-percentage-goes-no-option-fertilize-or-water-more-after-first-planting-

**Game Resolution:**
1920x1080

**Player Data:**
Character ID:8083 - Job Data: Mechanic,Los Santos Customs, Tow Driver
Timestamp: 2019-10-21 12:23:51

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
