### ISSUE TITLE
Storage at house shows weight but no items

### ISSUE THREAD

**Issue by Seferti** [InZidiuZ/op-framework-issue-tracker#557]
**Reporter:**
https://steamcommunity.com/id/Seferti/ seferti#4952
**Summary:**
So my house storage has been bugged, i have multiple storage places and the one i have "hidden" under my bed has weight for the items but all the items are not there, i have tried clearing cache, moving the storage etc, still nothing

**Steps to Reproduce:**
I have no idea TBH

**Expected Results:**
My items to be in my sotrage

**Actual Results:**
No items in the storage

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080
![20191021103707_1](https://user-images.githubusercontent.com/54122557/67215287-38f7ad80-f3ef-11e9-9bc9-0f005e544d7a.jpg)

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by TwoplePop** [comment]
probably because someone other than you was furnishing your house and it screwed the items up?

**Comment by Seferti** [comment]
Just did that, it literally didnt fix it, but it added tow items in the 2000 inventory storage box and thats it

**Comment by Seferti** [comment]
nevermind, working now
