### ISSUE TITLE
Issue with Bridge Street 13 Garage

### ISSUE THREAD

**Issue by RandomKilled** [InZidiuZ/op-framework-issue-tracker#560]
**Reporter:**
RandomKilled#0300
https://steamcommunity.com/id/RandomKilled/

**Summary:**
There is an issue with a certain garage for a house for Bridge Street 13. I stored my vehicle at the garage. When I tried to get it out it said vehicle is in 'Garage Bridge Street 13' Which is the garage to the house I own.

**Steps to Reproduce:**
Storing a vehicle in Bridge Street 13 Garage

**Expected Results:**
To be able to pull out a vehicle stored in the garage.

**Actual Results:**
It says it is in that garage but not actually be able to retrieve the vehicle

## Additional Information

**Screenshots:**
https://gyazo.com/60f2e7da850f36c87f587b1b224684b4
https://gyazo.com/25794bc878d665fbc44e26863bf0c1be
https://gyazo.com/33cac72a90fdc7fbaa384b75eee008f8

**Game Resolution:**
1920x1080

**Player Data:**
https://gyazo.com/01a762a4366e27e1133063367c0d1a13

**Notes:**
None

**Comment by babablacksheep4771** [comment]
Same problem i face

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
