### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by lildobbeh** [InZidiuZ/op-framework-issue-tracker#561]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
lildobby steam name
lildobbeh Discord name
**Summary:**
Write a short summary of what you're experiencing.
Everytime i get dced from the server the items in my car when its out disappears,
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Get Dced while car is out of garage.

**Expected Results:**
What are the expected results?
Lose everything in the vehicle

**Actual Results:**
What are the actual results?
Lose everything in my car.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920 x 1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 12413 - Job Data: Mechanic, Los Santos Customs, Tow Driver 
Timestamp: 2019-10-22 22:17:37
**Notes:**
For anything else noteworthy.

**Comment by lildobbeh** [comment]
Couldnt find the screenshots

**Comment by iGreatWhite** [comment]
Put the car away and take it back out all your items are in there.

**Comment by InZidiuZ** [comment]
This is intentional.
