### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#563]
**Reporter:**
Who is reporting this? iGreatWhite

**Summary:**
When you get disconnected from the server, instanced and have to disconnect to come back, or just leave the server with your car out. When you come back ,everything in the trunk of the car not sure about the glovebox, will disappear and the only way to get them to reappear is to put the car away and take it back out.

**Steps to Reproduce:**
1. Pull out a car with stuff in the trunk
2. Disconnect from the server
3. Look in the trunk. It should be empty.
4. Put the car away.
5. Take it back out and look in the trunk. Everything should have reappeared.

**Expected Results:**
What are the expected results?
For the cars inventory to not disappear on disconnect until it is put away again.

**Actual Results:**
What are the actual results?
Inventory seems to disappear until car is pulled back out.

## Additional Information
This is just a minor bug. Please get to it when you have time but don’t sweat over it :)

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

I can include the F8 next time I am at a PC right now I cannot.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
Can’t provide this as of now on my phone.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
This is intentional. The inventory unloads when you disconnect & won't let random players load it back due to security concerns.
