### ISSUE TITLE
Different Types of Contracts

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#565]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
customizable/preset contract/Payment Renewal time
For instance, The property owner can have it so payments occur every 2 weeks or every 3 weeks or even each month.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Some people get busy with life, And they have to let go of RP for a good week or 2, they dont want to lose their progress, Some of them cant keep up with the money and payments if they are gone for a week or 2.

**Comment by SATIN187** [comment]
You can pay in advanced, that’s what I did for my block and my house

**Comment by Aspratic** [comment]
I like this because evicting someone is hard sometimes, and people do get busy

**Comment by AdeptCL** [comment]
It takes two weeks from initial payment for someone to be evicted.
That's two weeks of maintenance payments, plus any extra due to finding a new tenant.

There should be an alert like the motels, and it be reduced to 3/4 days after rent due date to stop people just not paying.

**Comment by InZidiuZ** [comment]
Hey,

There's #586 suggesting the ability to change the current contract. And as stated by @SATIN187, you're able to pay in advance for as long as you wish, so closing.

**InZidiuZ**
*OP-FW Developer*
