### ISSUE TITLE
Hotkeys for Inventory

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#566]
**Name:**
Who is suggesting this? iGreatWhite

**Summary:**
Hotkeys at the top of your inventory versus having 1-5 be only for weapons.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This would be easier to use items without having to go into your inventory.

![unknown](https://user-images.githubusercontent.com/30253522/67437612-1956b580-f5a6-11e9-958a-7ad4c6b353c0.png)

**Comment by Aspratic** [comment]
this is going to be added when the new inventory gui is complete (pretty sure)

**Comment by ZurxeyH** [comment]
this would hopefully be a priority with new inventory, we’ll have to see.

**Comment by InZidiuZ** [comment]
@Anderzenn 👀

**Comment by Anderzenn** [comment]
It's being added in the new Inventory. I'm going to go ahead and close this since it's already planned!
