### ISSUE TITLE
[illegal/weed] Weed Adjustment

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#567]
**Name:**
Who is suggesting this? Please include discord name.
Aspratic#3121
**Summary:**
Write a short summary of what your suggestion is about.
When growing weed it is simply not profitable or even costs more money then you make. Getting 2-3 4oz bags is not nearly enough with the current rates at which weed sells for. The average price locals will buy weed from you is around $200-250 per 4 oz bag. Spending $500 on fertilizer barley allows you to break even, and buckets cost $50 plus water which is another $25. Growing weed for 2 days and making POSSIBLY $100 profit is insanity considering the time it takes to actually farm the seeds, grow the plants, and find locals that wont kill you when you try to sell to them, on top of getting $250 per 4 oz bag (more when primetime but that is a 5 minute period out of a 2 hour day and night cycle). Weed must be increased for this to be remotely worth it. I watched your stream and saw you estimated money made but that is simply very far off from what anyone in the city is making. My suggestion is to increase the amount of weed from 1-2 1oz, 2-3 4oz to 4-7 4oz and 1-3 1oz bags.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would be a good suggestion simply because it encourages people to grow the weed, while as right now many people in the city are simply saving their seeds because it is not worth it when you can lose money on growing weed. 
Growing weed takes time and OUR own money, whereas the other option is to go to the weed field  and pick the weed which will give anywhere from 3-6 4oz bags and costs us nothing, also it only takes about 10 mins to pick the weed and 15 mins after you finish picking the weed for more to grow. Which is outrageously OP compared to growing your own.
Thank you in advance for reading this suggestion.

**Comment by MICWIK4U** [comment]
Plus you can Add A Sun Lamp in Furniture section To Increase The Rate Of growth Of Weeds As Inside House there is No Sun Rays

**Comment by AdeptCL** [comment]
If you're selling at $200-250 per 4oz bag. You're not timing it right. You can get a good rate of $350-450 per 4oz bag.

**Comment by Aspratic** [comment]
Replying to adept, there is a very limited window to sell weed at 350-450. And the weed you sell in the 5-10 minute period is probably the weed you collected from the weed field to try and get the seeds to grow the plants in the first place. Lets say you get 2 seeds every weed run, a higher end average for the amount of 4oz bags is 5. So you do 10 runs which = 50 4 oz bags and 20 weed seeds. the amount of time it takes to sell those 50 weed bags at 7am (the 350-450 window) is insane. selling 1 bag per minute within the 7am-9am timeslot is 10 bags. You can do that every 2 hours. so it takes 10 hours irl just to sell the bags that you harvested for FREE. 
When businesses setup baseline profit margins they don't calculate by the 1 day per week that they are profitable and all the other days that they are barely making money or losing money dont matter. They calculate by the average profit per day.

**Comment by joevapes3** [comment]
Reply to Adept,  you only get 350-450 for the first 3-6 bags sold. After that it drops into the 200's.

**Comment by InZidiuZ** [comment]
Prices for buckets and fertilizers have now been lowered.
