### ISSUE TITLE
Seatbelt

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#568]
**Name:**
Lars.
#9309

**Summary:**
Disable the seatbelt above a certain speed so you would fly out when you crash with 100MPH for example.

**Reason:**
Would encourage people to drive more carefull and should create some nice scenario's.
Would also be good for some more realism.

**Comment by InZidiuZ** [comment]
Hey,

This is now the case.

**InZidiuZ**
*OP-FW Developer*
