### ISSUE TITLE
Multiple people getting access to garage and spawn in houses

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#569]
**Name:**
BowchkaHonkHonk#5146
**Summary:**
I own a large house with 3 rooms in it so I am renting it to room mates as well but i am the only one who can spawn vehicles and spawn at the house. Im thinking adding a Level 3 for people to spawn vehicles and spawn at the house would be nice! If it needs to be limited then a max of 3 people at one house would be nice!

**Reason:**
3 reasons to own a house besides for RP are, Storage, Garage, and Spawn point. If i rent out a room to a friend or co-worker then they should have access to the same luxury of the person who owns the house!

**Comment by ZurxeyH** [comment]
I believe this has been suggested before, ticket #478

**Comment by Cricketx818** [comment]
I don't think people should be able to wake up at the house. Buy the garage could be cool, Reason why people should not wake up is because "People wont buy homes anymore and they will just live with there friend"

**Comment by iGreatWhite** [comment]
then dont give access if they are not paying their fair share? i feel like this is more of a duh type thing. im not gonna give someone a key and bed in my house if they are living for free... they gotta help out.

**Comment by Bowchikahonhonk** [comment]
I can see where cricket is coming from but thats why there might be a limit on the amount of people per house

**Comment by Lunar929292** [comment]
> I don't think people should be able to wake up at the house. Buy the garage could be cool, Reason why people should not wake up is because "People wont buy homes anymore and they will just live with there friend"

OK so the way I am looking at it.. Level 1 & 2 access stay same. Level 3 Access could grant access for garage & spawning at the house GIVEN they are paying the rent in the Finance tab inside the tablet (/comp) cause I don't think anyones gonna let someone bum free and if they did not that long before they start requiring some $$$.. ya know? so adding a 3rd lvl of access to spawn, get garage access & pay rent isn't a bad idea imo.

**Comment by ZurxeyH** [comment]
I disagree, if people are allowed to share a Home, let them pay for rent, maybe even the landlords could up it a bit “a person on person fee” or whatever. There’s no way in hell someone will have keys to my home, and garage with no payments. Also, realistically if I’m letting someone live with me, they have access to garage, and waking up in their bed xd

**Comment by InZidiuZ** [comment]
Already suggested in #478.
