### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kr1zzzz** [InZidiuZ/op-framework-issue-tracker#570]
**Name:**
Who is suggesting this? Please include discord name.
Kristoffer#9080
**Summary:**
Write a short summary of what your suggestion is about.
Puling out the mini smg as you do with the pistol instead of having it on your back
**Reason:**
Why would your suggestion be a good addition to Legacy?
people wouldn't be scared to go around with a mini smg because if you walk around with it now you have it on your back so you re getting robbed by the first person that sees you, which creates bad rp

**Comment by TwoplePop** [comment]
definitely +1

**Comment by InZidiuZ** [comment]
Hey,

This has now been done.

**InZidiuZ**
*OP-FW Developer*
