### ISSUE TITLE
Police Suggestion

### ISSUE THREAD

**Issue by TheBillyZee** [InZidiuZ/op-framework-issue-tracker#571]
**Name:** BillyZee#1111

**Summary:** As of now you cannot "/suspect in" more than 1 person in a vehicle. If you attempt to do it on a 2nd person nothing happens and the escort gets let off. We (the police) usually are in situations where we have 6 people in hardcuffs and we need to transport them to prison. It becomes a whole ruckus of us first uncuffing them then softcuffing them and asking them to get in the prison bus. Allowing us to "/suspect in" multiple hardcuffed people in at least the prison bus would make it very easy for us.

**Reason:** Because it would allow for a better flow of roleplay as the whole ruckus would get removed.

**Comment by DeadManGamingYT** [comment]
I thing previous one is better... for proper RP.

**Comment by CZenStar-alt** [comment]
Consider Real Life Situations. Multiple suspect In should be there. It's needed to save time for more incoming RP situations.

**Comment by InZidiuZ** [comment]
This is already meant to be a thing. File it as a bug-report.
