### ISSUE TITLE
House has a space at the end, So the garage is not locating the home address 

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#572]
**Reporter:**
Cricketx818

**Summary:**
So a guy is trying to pull his car out the garage, But its not letting him because the garage is assuming the car is at a different house.

https://cdn.discordapp.com/attachments/616075936340901891/637134336642121761/help2.PNG

https://cdn.discordapp.com/attachments/616075936340901891/637134359228317706/help1.PNG

https://plays.tv/video/5db270ec3c632eb245/bug

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
