### ISSUE TITLE
Repo System

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#573]
**Reporter:**
Cricketx818

**Summary:**
So I have been trying to repo a car but Nothing happens when I /repo 

Here is a vid of me checking the plate and it saying the car has unpaid finances, & me trying to repo it.

Licence Plate # Is 30ECM740

https://cdn.discordapp.com/attachments/616075936340901891/637138047875678218/help3.PNG

https://plays.tv/video/5db272cc10ed274d74/repo

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved *and* tested.

**InZidiuZ**
*OP-FW Developer*
