### ISSUE TITLE
Regarding Mass plantation of weed plants in a room.

### ISSUE THREAD

**Issue by NeLLyBrownmen** [InZidiuZ/op-framework-issue-tracker#574]
**Reporter:**
Discord : neL._.Ly#4627
Steam : https://steamcommunity.com/id/cheetosenpai99/

**Summary:**
I planted 101 weed plants in my middle sized apartment which is at paleto bay ( cascabel Avenue apartment complex a 171 ) so I undoubtedly leave enough space to walk around every plant, it was working smooth before the 40% growth of plants but when it reached to 40 and I came back to my apt to water and furtilize the plants, some invisible things started blocking my way. These invisible things does not vanish even after modifying those plants or re-entering the server. I am attaching 2 attachments to make my above stated statements more convincible.

**Steps to Reproduce:**
1. Plant more than 100 plants in your room.
2. Nurture them until it's growth reaches 40%
3. Some invisible things starts to block your way when you returns to your room to nurture it.

**Expected Results:**
I don't know what's causing this but it's ruining the RP as I cannot cultivates it smoothly with my gang or show it to our friends. Removal of this invisible thing bug is important as mass producing weed provides quality rp of a gang doing an operation together.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1600x900

**Player Data:**
Character ID : 6091, Job Data : Government, waste collector, Employee
![weed plantation](https://user-images.githubusercontent.com/57019192/67605794-04904280-f79d-11e9-92ba-440a59947e0f.PNG)
![weed](https://user-images.githubusercontent.com/57019192/67605795-0528d900-f79d-11e9-977c-ab4528009bfd.PNG)

**Notes:**
For anything else noteworthy.

**Comment by ZurxeyH** [comment]
this guy is a fuckin madlad

**Comment by InZidiuZ** [comment]
Hey,

Are you on the public or white-listed Indian server? Also, do you have the address for this house?

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
