### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#575]
**Reporter:**
Who is reporting this? Please include the discord name and your steam profile.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what you're experiencing.
Wrong block payment info. The last payment of block Eclipse Boulevard was done on 26th Oct 2k19 but it's showing 2nd October.
**Steps to Reproduce:**
Include what steps are needed in order to reproduce the issue.
Fix it plox.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
http://prntscr.com/pod8fk
https://cdn.discordapp.com/attachments/619973123478913044/637591170834235413/20191026144320_1.jpg

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
