### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#576]
**Name:**
Who is suggesting this? Please include the discord name.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what your suggestion is about.
Priority - Person with the same Tier can /givecar each other.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would make people happy xD.

**Comment by InZidiuZ** [comment]
Already suggested in #357
