### ISSUE TITLE
PDM Bank Account

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#577]
**Name:**
Cricketx818

**Summary:**
I think PDM should have its own bank account based off the commission that employees add on cars. 
Example: If a sales man sells a car with %15 and he gets %50 of that commission, The other %50 should go to the PDM bank account, That bank account can be used for  bonus's & buy backs for cars for used car dealership that is going to be added hopefully soon, in noPixle, the owner of PDM has his own bank account and that is how the system works, I Dont think this will break the Economy because if the sales man sell cars with commission that money should go to an account to provide the city with buy back cars. I have been investing my own money to buy people's cars because I am the "Boss of PDM".

**Reason:**
PDM will buy back cars for a reasonable price, and it brings more RP towards the employees & having them put in more work, + I can give them weekly Bonus's if they enough sales.

**Comment by AdeptCL** [comment]
Not a member of PDM, but this would make sense.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
