### ISSUE TITLE
Plane Bug

### ISSUE THREAD

**Issue by EvilGhost5** [InZidiuZ/op-framework-issue-tracker#578]
I was in the coke field. I hired the plane and started to flew it..i just passed a little and suddenly i found myself in the landing site and after a sec it showed mission failed. I didnt got the money back too. Please fix the issue. It is very heart breaking. Here is my video proof.

Here is the link:- https://streamable.com/kpcfv

Okay, here is the 2nd type

Link:-https://streamable.com/uk0cl

**Comment by iGreatWhite** [comment]
Might want to use the template.

**Comment by AdeptCL** [comment]
"it is very heart breaking"

????

**Comment by InZidiuZ** [comment]
Use the template. Clear your cache & see if that resolves the issue.
