### ISSUE TITLE
Cocaine Field Fatso Scamming People

### ISSUE THREAD

**Issue by pr4thikkum4r** [InZidiuZ/op-framework-issue-tracker#579]
**Reporter:**
TheMadJoker#1854    / https://steamcommunity.com/id/themadjoker007/

**Summary:**
I was on the cocaine field waiting for the plane, but when i purchased the plane money got deducted and  plane didnt't show up. My internet is fine.  i restarted the game. Then  it happened second time as well. i have attached the video proof as well

**Steps to Reproduce:**
Step are easy go and buy the plane on cocaine field. i don't know if its happening with everyone or not.

**Expected Results:**
Need plane after money gets deducted not a scam

**Actual Results:**
You will produce i guess

##  give all above

**Screenshots:**

![123 mp4_000030166](https://user-images.githubusercontent.com/57058516/67631847-cfc9db80-f8c1-11e9-8a95-46b2adec888f.png)
![123 mp4_000030366](https://user-images.githubusercontent.com/57058516/67631848-cfc9db80-f8c1-11e9-99ee-e796bba4b357.png)
![Uploading 123.mp4_000030500.png…]()

**Game Resolution:**
1080p

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by humayunraza1** [comment]
Happened with me in the beginning, happens rarely ig anyhow this should get fixed

**Comment by AdeptCL** [comment]
Never had this happen to me, but it's definitely a bug that would need fixing.

**Comment by InZidiuZ** [comment]
No response from OP. Follow the template properly. Clear your cache & see if that resolves the issue.
