### ISSUE TITLE
[jobs/police] Easy way for fingerprinting.

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#580]
**Name:**
Randy James#4851

**Summary:**
So basically find any computer in the pd we could use the one in the room way you do mugshots. Basciallt whenever you go near it you do /fingerprint [then the ID] It will say there name top right and there citizen id number.

**Reason:**
Fining someone $1 to fingerprint aint a good way of doing it. This is just an easy way to make it abit more realistic. ;D

**Comment by DaxterPancake** [comment]
This has recently been added with a simple command. 

Thank you for the suggestion, I will be closing this.

Daxter.
**Project Manager.**
