### ISSUE TITLE
Flickering Furniture In Block 101

### ISSUE THREAD

**Issue by MICWIK4U** [InZidiuZ/op-framework-issue-tracker#581]
**Reporter:**
Steam- https://steamcommunity.com/id/micwik
Discord- MICWIK/Shivam Bajaj#2111 

**Summary:**
Furniture Blinks Inside The Room Of "Power street Apt. Complex B (101)

**Steps to Reproduce:**
You Know as This issues Has been Previous Founded In some Blocks.

**Expected Results:**
Furniture Should Be solid And Must Not Blinks Plus my Character Also Blinks Inside The Room. 

**Actual Results:**
Furniture Flickers Plus My Character Also Flicker. 

## Additional Information
This Blocks Has 4 rooms have same issue in all 4 rooms

**Screenshots:**
![20191028134537_1](https://user-images.githubusercontent.com/47519389/67663321-3a931980-f98b-11e9-95b8-bf8c5f2cbdc6.jpg)
![20191028123832_1](https://user-images.githubusercontent.com/47519389/67663345-48489f00-f98b-11e9-9e1e-952c36ad6cf0.jpg)
![20191028123841_1](https://user-images.githubusercontent.com/47519389/67663356-50a0da00-f98b-11e9-9869-d2856b0becf8.jpg)
![20191028123859_1](https://user-images.githubusercontent.com/47519389/67663368-58f91500-f98b-11e9-93e2-1e45d99d2f90.jpg)

Video - https://streamable.com/70zs9

**Game Resolution:**
1350x729

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
My Customers Are Leaving My Rooms As they Says My Rooms Are Haunted xD

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved.

**InZidiuZ**
*OP-FW Developer*
