### ISSUE TITLE
Missing Garage Storage option In "Bay City Avenue (82)"

### ISSUE THREAD

**Issue by MICWIK4U** [InZidiuZ/op-framework-issue-tracker#582]
**Name:**
Steam- https://steamcommunity.com/id/micwik
Discord- MICWIK/Shivam Bajaj#2111 

**Summary:**
My Company Has Rented a Block "Bay City Avenue (82)" Maintenance Cost Is 5000$/Week  But It Has No Garage Storage Available So If you Can add The Garage Parking Facility That would Be Awesome. Attaching Some Screenshots . 

**Reason:**
My customers says Paying 5000+$/week And not Getting garage parking Feels not Good.
![20191028124208_1](https://user-images.githubusercontent.com/47519389/67665008-d2decd80-f98e-11e9-9baa-8d864f4acff0.jpg)
![20191028124234_1](https://user-images.githubusercontent.com/47519389/67665033-deca8f80-f98e-11e9-9c1c-6d68d45450de.jpg)
![20191028124301_1](https://user-images.githubusercontent.com/47519389/67665035-deca8f80-f98e-11e9-9c1d-1d9752ad3524.jpg)

**Comment by ZurxeyH** [comment]
Has the customer even looked around?

**Comment by MICWIK4U** [comment]
Yes i have personally Confirmed from Both of my customers @ZurxeyH

**Comment by pxyeb** [comment]
Hey,
I have added garages for both properties accessible from this point: https://gyazo.com/e1fad369961450c95af416e3e8ee3813 
They should be live within the next update.

**pxyeb**
OP-FW Helper

**Comment by MICWIK4U** [comment]
@pxyeb  Thanks <3
