### ISSUE TITLE
[animations/emotes] Looking at map emote

### ISSUE THREAD

**Issue by triatomic** [InZidiuZ/op-framework-issue-tracker#583]
**Name:**
tria

**Summary:**
Looking at map emote

**Reason:**
this can add alot of RP situation with new players and old alike.

how it looks like:
https://i.imgur.com/NdZPC8Q.png

**Comment by InZidiuZ** [comment]
Is that an NPC in the picture?

**Comment by triatomic** [comment]
Yes the NPC was in vinewood (near the tattoo shop).

**Comment by DaxterPancake** [comment]
This animation has been available for awhile now by using /e map.

If this is not what you were talking about, please remake this suggestion.

Thanks!
Daxter.
**Project Manager.**
