### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#584]
**Name:**
Who is suggesting this? Please include discord name.
RaviCan'T#0001
**Summary:**
Write a short summary of what your suggestion is about.
Lot of people suggesting me to add a cool down in life invader so that if some one pick mechanic job and he need to change his job he will need to wait for 1 week or some days.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Bcz right now in legacy Indian server mechanic RP is totally gone.

**Comment by AdeptCL** [comment]
-1.
I understand why this is likely to be added.

However, there has been times where for example - mechanics - are not on the server, or are not working as per the job role should. So being able to swap over to a mechanic job - given RP reasoning like ex-mechanic - is appreciated by the community.

**Comment by InZidiuZ** [comment]
This has been both proposed & declined already, see #383
