### ISSUE TITLE
Adding Train Missions

### ISSUE THREAD

**Issue by LOxPanda007** [InZidiuZ/op-framework-issue-tracker#585]
**Name:**
 debabratapanda_0710#5425

**Summary:**
Adding Trains Mission In RP Will Be Great

**Reason:**
Yes, I Think This Will Make Our Legacy Roleplay More Exited To Do Train Missions

**Comment by AdeptCL** [comment]
This is one of the worst suggestions I've seen.

The reason for this is horrendous. No effort put into this. -1.

**Comment by InZidiuZ** [comment]
What in the world is this even meant to mean...?

If you're going to suggest something, take some time to properly explain the suggestion, at least...
