### ISSUE TITLE
[companies/stocks] Rent changes suggestion

### ISSUE THREAD

**Issue by Miliax** [InZidiuZ/op-framework-issue-tracker#586]
**Name:**
Miliax#2530

**Summary:**
So i've been thinking of real estate companies etc. I think you should change the way of paying rents. If you rent a house, let's say today. The rent is gonna pay it self after 7 days, 5th november. 
And if you don't have any money, you are gonna get kicked from the house/apartment after 1-2 weeks. Cause of people don't paying the rents, Real estates get bankrupt.  I don't know, maybe anyone else have a better suggestion for this to work.

**Reason:**
Cause other people that maybe pay their rents gets suffering for other that's not paying the rents and the real estate get's bankrupt and the houses gets removed and we loose all off our stuff..

**Comment by SATIN187** [comment]
Welcome to the real world... where it could take months and a court order to get somebody out of your house

**Comment by selb97** [comment]
There's just a lot that feels unfinished with the way companies are set up. You can't see who has paid or not paid their rent, you can't see who has paid weeks in advance and you can't literally do anything but sell the houses and just... guess that things are going good.

Until the person just leaves the server, and house suddenly goes poop and then companies lose money. Or that they just forgot to pay rent, and the company lose money.

At the same time, there's no way of working together with anyone in real estate. Nobody that works for you can sell houses. Also, lets say that you sell the house for X and make a deal that the rent will change in a bit, you can't... unless the person just stops paying rent and loses his house -> then you re-sell.

**Comment by Aspratic** [comment]
> Welcome to the real world... where it could take months and a court order to get somebody out of your house

The thing is this isnt the real world and people are renewing houses 1 day before the house will be taken. SO they are getting 2 weeks for free living and people that own the block have no way of kicking them out of it.
Housing needs to be the same as motels and if your late by 1 day you lose the house. Of course there should be a 3-4 day warning that rent is due.
If this isnt enough time then add a bi-weekly payment. There is nothing companies can do and we are getting fucked from a system we are double beat at.

**Comment by MICWIK4U** [comment]
True As Many Customer Purchase 5000$ plots and get extra benefits of 5000$ in overdue period and rest the company have to bear the loss of 1 Week of 5000$ frons it's company balance.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
