### ISSUE TITLE
Motel Suggestion.

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#588]
**Name:**
Who is suggesting this? Please include the discord name.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about removing motels so that people can actually buy houses from the company.
**Reason:**
Why would your suggestion be a good addition to Legacy?
That means more profit for companies :)

**Comment by 1THC** [comment]
That doesn't seem like a very good reason to remove motels...There are plenty of empty blocks and apartment buildings for companies to own and make profit off of.

**Comment by selb97** [comment]
We're here to RP. When you first are looking for somewhere to live, i think RPing your way towards a house is better rather than just running up to a motel. At least someone should own that motel if they should exist.

**Comment by SATIN187** [comment]
Some people don’t play on the server everyday and some of the motels are cheap and maybe that’s all they can afford for the short tome they’re playing in the server

**Comment by selb97** [comment]
Nobody said motels have to be expensive?

**Comment by InZidiuZ** [comment]
Hey,

This won't happen. Motels are there for people just starting out. Properties offer far more options & benefits than motels, so eventually moving out of a motel makes sense.

**InZidiuZ**
*OP-FW Developer*
