### ISSUE TITLE
Grandmas house

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#589]
**Reporter:**
Randy James#4851

**Summary:**
So just did a bank robbery some of the guys went down. Instead of rolling up to pillbox we headed to grandmas because it was a bank robbery and we just killed cops so we go there. 2500 to revive is stupidly too much. Spent 5000. So they were getting revived and they said they cant see anything but a black screen and couldnt move. They relogged and went to pillbox and got items taken away from them.

**Steps to Reproduce:**
Put the $ to 1000 because 2500 is too much. Otherwise, no one is going to use grandmas.
**Expected Results:**
Once revived you can just get up and head on out without seeing a black screen.

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Horrible bug.
