### ISSUE TITLE
Can't use Assault SMG

### ISSUE THREAD

**Issue by TheRealRoty** [InZidiuZ/op-framework-issue-tracker#590]
**Reporter:**
TheRealRoty#5555

**Summary:**
I found an Assault SMG from a crate, and now I have it in my inventory, but I can't pull it out.

**Steps to Reproduce:**
Have an "Assault SMG" in your inventory and try and pull it out in your hands.

**Expected Results:**
The Assault SMG should come out in your hands like other weapons, and you should be able to use it.

**Actual Results:**
The Assault SMG sits in your inventory but you can't pull it out.

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/608803536741990402/639070702309474305/asssmg.png

**Game Resolution:**
1920x1080

**Player Data:**
https://cdn.discordapp.com/attachments/608803536741990402/639071071059836938/info.png

**Notes:**
PlxFixTy. <3

**Comment by AdeptCL** [comment]
Might be a dumb suggestion, have you tried putting into one of your storages and then taking it out again to see if it registers it?

**Comment by TheRealRoty** [comment]
Yes. I did everything I could. I also slept for 12 hours and tried again before reporting it, you know. Just in case lol.

**Comment by AdeptCL** [comment]
Damn that really sucks.

**Comment by TheRealRoty** [comment]
I mean, it's gonna be fixed anyways so who cares lol.

/me sleeps in bed with an AK I found earlier today.

**Comment by TwoplePop** [comment]
drag the gun to use

**Comment by TheRealRoty** [comment]
Did all that already bro.

**Comment by Aspratic** [comment]
Probably due to the code with police where the smg can't be taken from them

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*

**Comment by TheRealRoty** [comment]
Noice! ^^
