### ISSUE TITLE
Check-In Sound Notification for EMS.

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#591]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
Get a Sound Notification when someone checks into the hospital IF an EMT is signed on as a doctor, Like a beep or a sound, as long as it alerts them.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Due to people not "Dying" most of the time EMT's like to sit in their head especially those in the hierarchy who like to spend their time writing up documents, A Sound Notification would help them get back on track, just like when the beeper goes off for a call.

**Comment by AdeptCL** [comment]
If they're in their heads, they're most likely not tabbed into the game. I know I don't hear sounds when I'm tabbed out, so how would a sound notification help with this?

**Comment by AdeptCL** [comment]
I did not know this...

Which setting is it?

**Comment by InZidiuZ** [comment]
The "custom" sound effects are played through HTML, and will play even if you're tabbed out of the game.

**Comment by InZidiuZ** [comment]
Hey,

This was added. Not a "custom" sound effect though, so this probably won't play when alt-tabbed & the game is muted.

**InZidiuZ**
*OP-FW Developer*
