### ISSUE TITLE
Gun heist key scam

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#592]
**Reporter:**
DegenTheo#2209

**Summary:**
GUn running stealing my keys even when i put them i nthe correct order

**Steps to Reproduce:**
I think someone has to do a gun run before you or at the same time and you will sometimes get scammed of your keys if you do it to fast after someone. It might also be cuz you are too quick to put in the keys. It said Correct key for the first. NOTHING for the second. and correct for the third

**Expected Results:**
You get the location to a crate with the hack

**Actual Results:**
You get scammed of your keys and you dont get the second hack

## Additional Information

**Screenshots:**
I dont have any sorry (might update if it happens again)

**Game Resolution:**
What is your game's resolution?

**Comment by TwoplePop** [comment]
I heard that you have to wait 15 minutes after the previous heist but it could just be a bug

**Comment by DegenTheo** [comment]
Weird, did 2 yesterday with a 5 min space without getting scammed

**Comment by TwoplePop** [comment]
oh that's probably a bug then

**Comment by Aspratic** [comment]
Yeah ive seen a few people saying this. Inzidiuz should make a cooldown to prevent this from happening. Something like "Lester is not looking for keys currently" or some type of message along those lines

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZIdiuZ**
*OP-FW Developer*
