### ISSUE TITLE
Mansions not rewarding enough

### ISSUE THREAD

**Issue by kahzey** [InZidiuZ/op-framework-issue-tracker#594]
**Name:**
Who is suggesting this? Please include discord name. 
Kahzey#7620

**Summary:**
Write a short summary of what your suggestion is about.
Robbing mansions feels like a huge waste of time for how long it takes and what you get out of it. I feel like if you are robbing a house you should ALWAYS find something when searching through the stuff. If I'm robbing a mansion or any kind of house for that matter, I know irl i would definitely come out with more than a battery and some rubber no matter what so why is it that you can spend 10 min inside some of the wealthiest houses and still come out with practically nothing?

**Reason:**
Why would your suggestion be a good addition to Legacy?
I'm sure most can agree robbing a mansion feels like a huge waste of time for what you get and how  long it takes. I've spent 10+ sneaking around a mansion only to find a useless condom, $21, and some rubber? I just wanna feel rewarded for risking jail time.

**Comment by Aspratic** [comment]
mansions got buffed like a day ago

**Comment by InZidiuZ** [comment]
Yea, they did. Are you talking about before or after they 1.6? 🤔

**Comment by HridayHS** [comment]
Maybe you could also make it so that we can get 2-3 items at once but at very low chance.

**Comment by InZidiuZ** [comment]
Probably not, @HridayHS. Also, since OP hasn't responded yet, I'm gonna guess he's talking about pre-1.6 times, so closing.
