### ISSUE TITLE
Pillbox Beds Suggestion

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#595]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
Have hospital beds automatically regenerate health for patients instead of having EMS /cpr them or make it have a specific animation other than /cpr
**Reason:**
Why would your suggestion be a good addition to Legacy?
/cpr animation makes look like im sucking off the patient in the bed and it is inappropriate, We do get a lot of sexual comments about it, but this is not a major issue, We just feel like there is better animations that could replace it or have it as an interaction option just like treating wounds or have the patient regenerate health as long as they are in the bed.

**Comment by InZidiuZ** [comment]
You're not meant to do /cpr on patients. When they check in they're revived automatically.

**Comment by Cironite** [comment]
> You're not meant to do /cpr on patients. When they check in they're revived automatically.

We do /cpr on them to set them to Full HP since it does not do it automatically

**Comment by InZidiuZ** [comment]
It should. If it doesn't, file a bug-report. :)

**Comment by Cironite** [comment]
> It should. If it doesn't, file a bug-report. :)

10-4 rubber ducky

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
