### ISSUE TITLE
Fake Plates Too Rare?

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/op-framework-issue-tracker#596]
Dean Hunt(TwoplePop#7989)

I was watching Ben's stream and was very excited for the new fake plates. As soon as the update released, I was very ecstatic to chop some cars and get some fake plates. I then realized that they were very rare since I chopped about 12 cars collectively that day and didn't get 1 single fake plate. 

My suggestion would be good for legacy since people wouldn't have to chop cars the entire day to get 1 fake plate. I understand that getting a fake plate every single car would just mean people would use fake plates every single time they pull their car out. I don't know if I just have ultra bad luck but I don't think it should be that rare.

**Comment by Kr1zzzz** [comment]
I dont think people would use fake plate everytime they take out their car tho because if you get pulled over the car is not going to come back to your name. I think the reason why they are so rare are because people are going to use it for bank robberys etc and dont want people robbing banks wirh their personal veichles all the time without a fake plate

**Comment by Aspratic** [comment]
nothing wrong with them being a little rare imo, more rare then expected but

**Comment by InZidiuZ** [comment]
There's a 10% drop-chance on every chopped vehicle.

**Comment by TwoplePop** [comment]
with the amount of cars that are classified as "ghost cars" that don't spawn in as a chop vehicle and the amount of people doing chop shop, I just thinks it's a little low. obviously there has to be rarity, I understand that but those are just my thoughts.

**Comment by InZidiuZ** [comment]
Hey,

The drop-chance has now been doubled, and you now have a 20% chance of obtaining one when chopping a vehicle.

**InZidiuZ**
*OP-FW Developer*
