### ISSUE TITLE
People not regenerating health when they check in with a Doctor On Duty

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#597]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Ciros#2048 https://steamcommunity.com/id/Ciiros/
**Summary:**
Write a short summary of what you're experiencing.
When there is a Doctor Sign on Duty and people check in, They do not get full health/regenerate health when they are in the bed.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Sign on duty as a doctor, Have someone with low HP check in,
**Expected Results:**
What are the expected results?
Patients get Full Health/Regenerate Health when they check in with a Doctor On Duty
**Actual Results:**
What are the actual results?
They don't Regenerate/Get full health when they check in.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://i.gyazo.com/thumb/1200/65501d40ed79efa1cb8b7b6405c3ab1c-jpg.jpg
https://cdn.discordapp.com/attachments/571107902081728524/639466382731509780/unknown.png
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://cdn.discordapp.com/attachments/571107902081728524/639467351347167273/unknown.png
**Notes:**
For anything else noteworthy.
For now people use /cpr to counter this issue, but the CPR animation is weird and it looks like as if im sucking someone off.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
