### ISSUE TITLE
[animations/library] /badge command for cops 

### ISSUE THREAD

**Issue by HuhCjay** [InZidiuZ/op-framework-issue-tracker#598]
**Name:**
Who is suggesting this? Please include discord name.
HuhCjay#2888

**Summary:**
Write a short summary of what your suggestion is about.

Just giving a command to flash your badge to any person who may want your name/ badge number and to further prove you are indeed a police officer
if it was possible it could be a item that you drag over to "use" which would further the need for a command of /makebadge {name, badgenumber} that only promoting chiefs can do. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would definitely add more immersion when cops speak to civilians and I would personally really like to see this be done when conducting traffic stops on civilians to keep a professional tone when doing so.

**Comment by InZidiuZ** [comment]
@cricket pls find anim)

**Comment by DaxterPancake** [comment]
Found an animation that could work for this command.

Prop: `prop_fib_badge`
Dictionary: `paper_1_rcm_alt1-9`
Animation: `player_one_dual-9`

Example of animation seen [here](https://streamable.com/941f36).

**Comment by Brundoggy** [comment]
Yes this would be awesome

**Comment by panpawn** [comment]
I agree this would be a very nice addition - it's awkward when someone asks to see your badge and you have nothing to show them.

**Comment by DaxterPancake** [comment]
Here is a script which does what we are looking for, the only addition we would need is something put into the chat that says the players badge number and name.

Script can be found [here](https://forum.cfx.re/t/standalone-release-flash-badge-script/2977049).

**Comment by twooot** [comment]
Something like this has been done. Maybe in the future we can add custom badges for departments as well.
