### ISSUE TITLE
Bug report house garage

### ISSUE THREAD

**Issue by ZroonX** [InZidiuZ/op-framework-issue-tracker#599]
**Reporter:**
ZroonX#5281 https://steamcommunity.com/profiles/76561198058001316/

**Summary:**
Okey so my friend had a house and he put all his expensive cars in there that he have grinded for and he lost that house so those cars are stuck in that garage and he cant get the house back because i payed rent for a few months would be really good if this could be fixed some how.

Tell me if you need any more info about this cuz i would really apreciate if that could be solved soon.

**Comment by InZidiuZ** [comment]
Follow the template. Give more information on what house it happened on, when it was lost, etc. This issue would already have been fixed with 1.6.
