### ISSUE TITLE
Pillbox Morgue

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#600]
**Name:**
Who is suggesting this? Please include discord name.
Ciros#2048
**Summary:**
Write a short summary of what your suggestion is about.
Have it so only Medical Staff have access to Pillbox Morgue, I have seen numerous people abusing it by doing criminal activity then going to the locker there to change outfits so they are not recognized. E.g: Rob a bank, check in get treated, walk to morgue and change outfit, It should be like the Old Pillbox Rooftop where if they wanted to go up or down, they must be escorted by Medical personnel  
**Reason:**
Why would your suggestion be a good addition to Legacy?
Just put an end to people abusing it while still keeping its rp potential.

**Comment by InZidiuZ** [comment]
I probably won't remove people's access. What I could do though is limit the outfit-area to EMS only, to prevent abuse. Same goes for the one found in PD.

**Comment by Cironite** [comment]
> I probably won't remove people's access. What I could do though is limit the outfit-area to EMS only, to prevent abuse. Same goes for the one found in PD.

Sounds good

**Comment by Cironite** [comment]
> > I probably won't remove people's access. What I could do though is limit the outfit-area to EMS only, to prevent abuse. Same goes for the one found in PD.
> 
> Sounds good
Nvm they can break a window and get in anyway

**Comment by InZidiuZ** [comment]
Limit the actual "circle location" to EMS, not just the doors. The radius is pretty high on /outfits too, so I think you'd even be able to use it outside of that little room.

**Comment by Duroode** [comment]
> Limit the actual "circle location" to EMS, not just the doors. The radius is pretty high on /outfits too, so I think you'd even be able to use it outside of that little room.

Does this mean only EMS can use the Changing room there? Because those windows Aren't player proof. 
https://youtu.be/kfq7m1cdAIU

**Comment by Cironite** [comment]
> > Limit the actual "circle location" to EMS, not just the doors. The radius is pretty high on /outfits too, so I think you'd even be able to use it outside of that little room.
> 
> Does this mean only EMS can use the Changing room there? Because those windows Aren't player proof.
> https://youtu.be/kfq7m1cdAIU

Yes i think that is what he means, Only EMS will be able to see the circle, for example GoPostal job see the circle where they can start the mission but if you have other jobs than GoPostal you dont see it, same with garbage.

**Comment by InZidiuZ** [comment]
Hey,

This is no longer an issue. Only EMS can open the doors to the outfit area, and it's also only usable by EMS.

**InZidiuZ**
*OP-FW Developer*
