### ISSUE TITLE
[player/injuries] More Injury Details for EMS

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#601]
**Name:**
Duroode#2178

**Summary:**
More Injury Details for EMS to treat people at the Hospital. When people airlift they say they don't remember What happened to them and it puts us EMS in a Tough spot, How do we know what to treat RP wise? What if they got Shot in the arm and we end up treating their Foot for a Stab wound. 

**Reason:**
I think it would be a good Addition because it gives us EMS more to focus on, and Provides us with more RP when we are treating patients, We are treating people for the Wrong issues and it makes us look stupid to the People we are treating, Because really they know how they ended up there, But we don't. Like i said we're treating GSW's as stab wounds etc...

**Comment by Cironite** [comment]
+1

**Comment by OrionSparkles** [comment]
Big +1

**Comment by twooot** [comment]
The whole remembering part is only IC. Once they airlift they can tell you /looc what their wounds are without remembering things ic?

**Comment by Duroode** [comment]
We, my friend are from a different time. A really different time.
