### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#602]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#00011
**Summary:**
Write a short summary of what you're experiencing.
When we use bandage whole using termite it skip the process time of termite pouring and looting Bank Money.  
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
1. we need some bandages and we use bandage first and pour termite and it take few second to rob one bank 
**Expected Results:**
What are the expected results?
results we get easy money which does not good for rp 
**Actual Results:**
What are the actual results?
we get easy money which does not good for rp 
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://youtu.be/5XSQN9oUmyY

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by ZurxeyH** [comment]
This isn’t a bug, it’s a mechanic. 
Using a bandage then using a thermite while in the animation stops the way it should.

**Comment by InZidiuZ** [comment]
Hey,

This *feature* has now been resolved.

**InZidiuZ**
*OP-FW Developer*
