### ISSUE TITLE
House Robbery Cooldown

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-issue-tracker#603]
**Name:**
Nate

**Summary:**
Because house robberies are easy to do and rarely prevented, a cool-down would slow down the grinding and allow police to investigate and do their job in catching robbers. I believe the cool-down should be per-player, but would prevent the chain robbing that happens now.

**Reason:**
As staff on the server, it is part of my role to spectate players to make sure they aren't AFK or doing things they should not be doing. Whilst doing these checks, 9/10 players are robbing houses. While I understand that it is a lucrative action, it severely limits the roleplay of the server when everyone is just robbing houses all day. When I go through an hour later for another round of spectating, all the same players are still robbing houses. For this reason, I believe that robberies need a cool-down so that players can't just spend all day robbing and have to go out and meet people, make friends, make enemies, hustle, etc. The current situation does not offer much value to roleplay, and that isn't taking into account the flood of rare items in the market as people grind for them.

**Comment by InZidiuZ** [comment]
Hey,

This won't be added for the time being. When spectating, are you really sure they're not just inside their houses? 🤔 There would also be an increase of house-robberies right now as the gun-heist system was recently added, which requires "decryption keys" which can be obtained from the robberies. There also already are house-specific cooldowns.

**InZidiuZ**
*OP-FW Developer*

**Comment by Cironite** [comment]
> Hey,
> 
> This won't be added for the time being. When spectating, are you really sure they're not just inside their houses? 🤔 There would also be an increase of house-robberies right now as the gun-heist system was recently added, which requires "decryption keys" which can be obtained from the robberies. There also already are house-specific cooldowns.
> 
> **InZidiuZ**
> _OP-FW Developer_

To tell if they are in their house or robbing one, you would see them move a few steps then stop, usually this indicates them stopping to drop the Busted Indicator, and 80% of players in a server are doing just that.

**Comment by Aspratic** [comment]
Well a new update just came out, but I think a better solution is taking advanced lockpicks out of the shop (along with other items like the .50 and body armor etc) and make a shop where u have to use and item like 1 gold bar plus the price of the item. I would like the .50 removed completely for now bc it 1 shots but for the advanced lockpicks they shouldn't just be lying around so easily
