### ISSUE TITLE
Suggestion: Robbing players

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#604]
**Name:**
Who is suggesting this? iGreatWhite#8870

**Summary:**
What I am proposing is that when players are dead, they will be able to be robbed without the use of handcuffs. 
The other suggestion that I am also proposing along side this is that when a player is robbed dead or alive their money is taken off them.

**Reason:**
Why would your suggestion be a good addition to Legacy?
I believe this would be a good fit for legacy because the first suggestion would just make more sense as if a person was dead you don’t need to restrain them to grab things from them.
The second suggestion would be very helpful for the people that just carry around thousands of dollars in their pocket without caring.

**Comment by InZidiuZ** [comment]
Hey,

We had the ability to do /search on cuffed players when it launched, but it was quite the shit-show, so it was removed again. Can't imagine it's much better now, especially with the 6-man rule instead of 4, so this will not be reverted for the time being.

**InZidiuZ**
*OP-FW Developer*

**Comment by HridayHS** [comment]
You can still rob cuffed players with /steal command.
Why did your comment felt like you don't know about /steal command? @InZidiuZ

**Comment by iGreatWhite** [comment]
I was talking specifically only about dead players. Not even alive players

**Comment by triatomic** [comment]
People literally grab a dead body put them in a trunk, and go to a hardware store just to rob them.
i kinda prefer not seeing that..

**Comment by InZidiuZ** [comment]
Ops* I meant to say you used to be able to /search people while they had their hands up, which was what resulted in total mayhem.

Also, @triatomic, people doing that can most likely receive an easy ban if reported.

**Comment by triatomic** [comment]
@InZidiuZ majority of people do that behavior tho. Maybe make it as a rule ?
