### ISSUE TITLE
Enable rifle ammo

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#605]
**Name:**
Red#8978

**Summary:**
Enable rifle ammo. (Assuming it is already isn't enabled now)

**Reason:**
Because we can obtain rifles now.

**Comment by iGreatWhite** [comment]
It was removed on purpose.

**Comment by HridayHS** [comment]
I know, even Sub(SMG) ammo was removed but it's actually not now. Assuming we have SMG in-game he enabled SMG ammo? If that's the case we should have rifle ammo as well.

**Comment by iGreatWhite** [comment]
Sub ammo was always there. He only removed rifle and sniper ammo.

**Comment by InZidiuZ** [comment]
Might remove sub ammo instead of re-adding the rifle ammo, as it'll act as a simple restriction to the guns, which we still don't know how will *truly* effect the server as time goes by.

**Comment by HridayHS** [comment]
That's only honestly fine if you remove sub ammo as well. I just thought if we have sub ammo in stores we should have rifle ammo as well.

**Comment by joevapes3** [comment]
Yah I don't think we need to be able to purchase anything but pistol ammo from ammunation, and I am for removing sub ammo as well. The ammo is still obtainable in game, but it makes it more rare. Therefore people would be more selective when wasting ammo or using it in unnecessary situations.

**Comment by HridayHS** [comment]
Nope^ -1 on that and I think sub ammo shouldn't be removed because police has SMG and police not being able to buy ammo for their SMG in stores doesn't make sense. Obviously police does not buy ammo because they can get it for free but if they wanted to they can buy it from stores and use it.

**Comment by iGreatWhite** [comment]
I think the cops being able to get their ammo for free from the armory is good enough to be fair. They have 280 bullets on them from start.

**Comment by SATIN187** [comment]
From my understanding cops just have to clock in and they get their ammo filled so there’s no reason for them to spend their own money on it I’m with only having pistol ammo purchasable in store... all ammo is pretty easy to get

**Comment by HridayHS** [comment]
Well if you all are with pistol only then +1 for that from my side as well, what I can do alone here :p

**Comment by InZidiuZ** [comment]
Hey,

Sub-machine ammo has now been removed.

**InZidiuZ**
*OP-FW Developer*
