### ISSUE TITLE
Tow Command

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#606]
**Name:**
Who is suggesting this? iGreatWhite#8870

**Summary:**
For some people that have a whitelisted job it is hard to do chop shop on the side with only being able to lockpick a vehicle. I feel as if you have a tow truck you should be able to use the /tow command.

**Reason:**
Why would your suggestion be a good addition to Legacy? People who have a job like PDM are kind of hindered when it comes to doing chop shop as our only option is to Hotwire and risk the cops showing up.

**Comment by Aspratic** [comment]
I tried chopshop for the first time today and actually went fast asf without the towtruck bc i am pdm. BUT I think having a towtruck option would be good +1

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being due to networking concerns.

**InZidiuZ**
*OP-FW Developer*
