### ISSUE TITLE
[animations/emotes] Emotes

### ISSUE THREAD

**Issue by Aesfy** [InZidiuZ/op-framework-issue-tracker#607]
**Name:**
Randy James#4851

**Summary:**
3 emotes that are really useful. Welcome Emote, Fine Emote and Damn emote

**Reason:**
They add alot to conversations to spark it up abit. There's alot of emotes out there.

**Comment by InZidiuZ** [comment]
Way more emotes have been added since the addition of dpemotes. If there are still some more emotes you'd like added, feel free to create a new issue.
