### ISSUE TITLE
House grown weed balance/suggestion

### ISSUE THREAD

**Issue by Vishy7** [InZidiuZ/op-framework-issue-tracker#608]
**Name:**
Vishy#0510

**Summary:**
My suggestion is to balance the house-grown weed in some of the ways possible. One which I found is by either letting the bucket unaffected after you've harvested since it makes sense and re-placing the bucket to the location in furniture is a hassle specially when you are harvesting large no of plants (5 or more). Also the house-grown weed isn't really profitable when you add the numbers vs the amount of time you put in it. I think the weed plant should stay same but reset to 0% growth on harvesting there we would fertilize and water it. The current quantity is very less (around 12 1oz or 3x4oz). I also suggest to buff up the final quantity. Yes, I've already seen the balance suggestion.

**Reason:**
The current system isn't profitable vs the amount of time you put it in, no one would would put in so much time for peanuts. Also refilling the whole place with buckets again and again doesn't make any sense.

**Comment by InZidiuZ** [comment]
See #567. If an issue regarding the same topic is already open, comment on that one instead...
