### ISSUE TITLE
Phantom sirens Bug report

### ISSUE THREAD

**Issue by PanchoGarcia** [InZidiuZ/op-framework-issue-tracker#609]
**Reporter:**
Pancho#0001 Panchito!n

**Summary:**
When in a certain range, you hear the siren of cop cars even without any lights on or if they have lights and no sirens
**Steps to Reproduce:**
Have someone drive a cop car, drive down the street and you ought to hear it, it sounds like sirens in the distance.

**Expected Results:**
sirens should only make noise when activated

**Actual Results:*
You will hear the sirens, this is kinda like an issue you may know of that used to happen with tow trucks before, the vehicle seems to be acting like its got gta sound mechanics tied to it.

## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/51061905/68077215-4c632b00-fd96-11e9-9f38-3346510b3aff.png)

**Game Resolution:**
1920x1080

**Player Data:**
character id 88 (though this happens for every cop who plays)

**Notes:**
This makes it almost impossible to make a stealthy approach as a cop. people hear you coming from blocks away

**Comment by Bowchikahonhonk** [comment]
This is a big problem when we are going for house robberies and drug calls as they know we are in the area even if we dont have sirens on

**Comment by InZidiuZ** [comment]
Hey,

We've now added 'Luxart Vehicle Control', so this issue is hopefully resolved now.

**InZidiuZ**
*OP-FW Developer*
