### ISSUE TITLE
Error when using repair command in non police character

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#610]
**Reporter:**
Discord: Red#8978
Steam ID: https://steamcommunity.com/id/hridayhs

**Summary:**
Error in console when using /repair command in non-police character.

**Steps to Reproduce:**
Use command /repair in non-police character.

**Expected Results:**
To pop a notification saying it's only for Police and EMS.

**Actual Results:**
Error...

## Additional Information

**Screenshots:**
https://i.imgur.com/d2CPsdH.png

**Game Resolution:**
1600x900

**Player Data:**
Character ID: 23570

**Comment by HridayHS** [comment]
Check Imgur link for error.

**Comment by Cironite** [comment]
I think its meant to be for EMS and Police only.

**Comment by HridayHS** [comment]
Yeah it is but it is supposed to give a notification saying this is strictly for Police and EMS only if someone who is not Police or EMS tries to use it.
I saw Inziduz implementing this part in his stream. Well it gives error right now.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
