### ISSUE TITLE
Lester's Comp not working on Indian servers

### ISSUE THREAD

**Issue by Trasaraj** [InZidiuZ/op-framework-issue-tracker#611]
**Reporter:**
Rasaraj#6402

**Summary:**
We cannot use Bank Chip on Lester's comp. Is this a Bug or Gun's heist not activated for Indian Servers?
**Steps to Reproduce:**
Please fix this problem if it is.
**Expected Results:**
Comp should accept the chip.

**Actual Results:**
What are the actual results?
Nothing happens, when I use the chip.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Forgot to enable, it's enabled now.

**Comment by Trasaraj** [comment]
Thank You
