### ISSUE TITLE
Delivery job improvement #2

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#612]
**Name:**
Red#8978

**Summary:**
When you complete the mission you get money in your bank, make it so that we get it as cash. Just like other jobs.

**Reason:**
It makes sense to have it as cash and it's better to have it as cash.

**Comment by SATIN187** [comment]
No I actually prefer it to go into the bank and wish all the jobs put it into the bank directly. As somebody who tries to mainly play as a civ this option I great so people don’t always try and rob you

**Comment by HridayHS** [comment]
People cannot rob money off you^

**Comment by HridayHS** [comment]
In other jobs as well we get our payment as cash and I think we are all satisfied with that. Plus it will be nice to have same payment method in all jobs.
All I want is to have common payment in all jobs doesn't matter if it's in bank or cash.
But I would definitely do +1 for cash payment.

**Comment by InZidiuZ** [comment]
Hey,

It makes more sense to receive a bank payment on this specific job, and it doesn't seem many more are eager to have this changed, so will close this issue.

**InZidiuZ**
*OP-FW Developer*
