### ISSUE TITLE
[vehicles/fuel] Gas station improvement

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#613]
**Name:**
Red#8978

**Summary:**
Let us use the bank as well if we don't have enough money to re-fuel or purchase jerry can.

**Reason:**
I mean why not and also it will be like real life?

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
