### ISSUE TITLE
Amarillo Vista 8 Garage 

### ISSUE THREAD

**Issue by Wrothgar** [InZidiuZ/op-framework-issue-tracker#614]
**Name:**
Wrothgar#1293

**Summary:**
The garage at Amarillo Vista 8 is scuffed because 2 cars spawn on top of where you spawn your own vehicle, which means you need to ram these 2 cars just to spawn in your own vehicle.
![20191103133657_1](https://user-images.githubusercontent.com/52108942/68091420-0fa23d00-fe45-11e9-8977-02a22d66ecda.jpg)
You could possibly add a driveway here and allow to spawn the cars here.

**Reason:**
Having to ram these 2 cars just to spawn my own car every session is annoying.

**Comment by pxyeb** [comment]
Hey,
Could you provide me a short video of what happens exactly when you take out your car?

**pxyeb**
*OP-FW Helper*

**Comment by InZidiuZ** [comment]
No response from OP, closing.
