### ISSUE TITLE
[properties/properties] Amarillo Vista 10 should have a garage.

### ISSUE THREAD

**Issue by allenle4** [InZidiuZ/op-framework-issue-tracker#615]
**Name:**
Allen#8921

**Summary:**
There's 9 houses on Amarillo Vista, and 8 of the houses on Amarillo Vista has a garage, so I don't see why this house doesn't have a garage. The "garage" spot (in the picture) is where you should be able to take our & store your vehicle for Amarillo Vista 10 house.

**Reason:**
8 out of 9 houses has a garage, and I don't understand why this one doesn't. It will benefit the person who owns the house so they can store and take out their vehicle when they spawn here. It's a lot better so they don't have to go to a garage just to get their vehicle. It's a lot more convenient to have a garage for this house than them walking to a public garage. 
![image](https://user-images.githubusercontent.com/52551909/68092994-058d3800-fe5f-11e9-9d61-6ca0cdde75a4.png)

**Comment by InZidiuZ** [comment]
@pxyeb mr

**Comment by Trasaraj** [comment]
+1 I too Rent this Block but have not rented out the 10th House, hope this solves as it will be a prob to convince the customers to buy the house without the garage.

**Comment by pxyeb** [comment]
Garage for Amarillo Vista 10 has now been added. It will be accessible within the newest update.

**Pxyeb**
*OP-FW Helper*
