### ISSUE TITLE
Yoga improvement

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#616]
**Name:**
Red#8978

**Summary:**
Change the button to **F** instead of **E** to stop doing yoga.

**Reason:**
https://streamable.com/xhfq2 - Not able to stop it.

**Comment by InZidiuZ** [comment]
Are you holding it? 🤔 This would be a bug, though. Will look into it soon.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been fixed. Also fixed stress not being removed.

**InZidiuZ**
*OP-FW Developer*
