### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Titansdengaming** [InZidiuZ/op-framework-issue-tracker#617]
**Name:**
Who is suggesting this? Please include discord name.
JustSayTitan
**Summary:**
Write a short summary of what your suggestion is about.
At a Twitch team: Legacy Rp
**Reason:**
Why would your suggestion be a good addition to Legacy?
Because we are starting to have a good amount of streamers around 16 that I know, it might be more. That's already half of a server. I believe that the legacy streamers can benefit from a community. If we create a community, streamers can help each other out so we can grow our streams together and maybe attract more likeminded people that prioritize Roleplay over grinding to the servers. Let me know what you think, and thanks for taking the time :)

**Comment by AdeptCL** [comment]
Don't think this is going to stay open as it isn't a Framework issue/suggestion.

**Comment by Titansdengaming** [comment]
> Don't think this is going to stay open as it isn't a Framework issue/suggestion.

Okay, could you point me the direction where I should post this?

**Comment by InZidiuZ** [comment]
You can suggest it to staff members. Closing.
