### ISSUE TITLE
[Phone Suggestion] Wrong time on phone inside house.

### ISSUE THREAD

**Issue by adityaef** [InZidiuZ/op-framework-issue-tracker#618]
# Legacy Phone Suggestion
**Name:**
harshef#4473

**Summary:**
The phone clock always shows 22:00 inside the apartment/house.

**Reason:**
We need to go outside the house to check the correct time. During house robberies, we can't see how much time is left until the morning.

**Comment by Anderzenn** [comment]
Hi :)
This is a bug with GC Phone and not our own phone.

This will not be a problem with our future phone, so I am closing this issue.

**Anderzenn**
*OP-FW UI Developer*

**Comment by HridayHS** [comment]
This is actually not a bug rather intentional to stop "weird lightning effects".
I remember InZiduZ telling that this is intentional.

**Comment by Anderzenn** [comment]
Still a bug with how GC Phone tells you what time it is

**Comment by Anderzenn** [comment]
Scratch what I said earlier, this is done intentionally.
