### ISSUE TITLE
Distress Signals for PD and EMS

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#621]
**Name:**
Duroode#2178

**Summary:**
Distress Signals for when EMS and PD are Downed.

**Reason:**
After Discussing this more with the Higher-ups in EMS and PD we have come to the decision that it would be a thing both departments would like to have For the Departments only. If a Cop or an EMS were to go down Both Departments would be Alerted Via Dispatch (in-game chat) that there is a person down and/or in Distress. Both departments would most likely put rules in place to prevent this from being Abused.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
