### ISSUE TITLE
Radar number plate scans not visible on smaller resolutions

### ISSUE THREAD

**Issue by OrionSparkles** [InZidiuZ/op-framework-issue-tracker#622]
# Legacy UI Bug Report
**Reporter:** Orion Sparkles#6053 | https://steamcommunity.com/id/osparkles/

**Summary:**
The police radar doesn't show the vehicle plate of the person infront/behind you. This might be because I'm using my secondary monitor (Old dell model 720p). This limits my abilities when I'm on duty.

**Steps to Reproduce:**
-Use the /radar command.

**Expected Results:**
It shows the vehicles locked number plate.
![image](https://user-images.githubusercontent.com/54718744/67840176-401f6980-fb1b-11e9-9aae-248e888e18d0.png)

**Actual Results:**
The number plate lock doesn't show, just the radar does. Like this
![image](https://user-images.githubusercontent.com/54718744/68142925-5f245e00-ff56-11e9-9331-b6b0ca743b1f.png)

## Additional Information

**Screenshots:**
Provided above.

**Game Resolution:**
1366x768

**Comment by joevapes3** [comment]
also the radar does not lock in the plate when someone triggers the radar's fast limit. I think it should lock the plate in until they reset the radar. Currently it just changes as soon as another car gets scanned even though the fast limit was tripped.

**Comment by InZidiuZ** [comment]
Looked into it, it's the UI not resizing to fit the resolution. Will need to change the way the widths/heights are obtained.

**Comment by OrionSparkles** [comment]
Yes, I can see it for a brief moment when I use the /radar command and the radar actually dosent come up (if you know what I mean) I can see the vehicle lock prompts and it seems to be located behind the radar

**Comment by InZidiuZ** [comment]
Hey,

A [successor](https://forum.cfx.re/t/preview-wraith-ars-2x-the-successor-to-wraithrs/933627) for the radar is currently being created by its developer, which should resolve the mentioned issue. It hasn't been released yet, although he's claiming it's close, so it most likely will be a part of the beta version.

**InZidiuZ**
*OP-FW Developer*
