### ISSUE TITLE
/repair command improvement

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#623]
**Name:**
Red#8978

**Summary:**
Make it so that it takes some time to repair the car. Probably with a progress bar like "Repairing vehicle".

**Reason:**
I think having your vehicle fixed instantly is a little bit bad for RP.

**Comment by OrionSparkles** [comment]
Totally agree, Any cop who is chasing someone either near pillbox or PD with a semi disable vehicle can do something just as simple as typing /repair and they are instantly good to go with a full tank of fuel.

**Comment by InZidiuZ** [comment]
Hey,

This has been done.

**InZidiuZ**
*OP-FW Developers*
