### ISSUE TITLE
Issue when you open a bag

### ISSUE THREAD

**Issue by SaRsHYT** [InZidiuZ/op-framework-issue-tracker#625]
Whenever someone drops anything in a bag and when I open it my cursor appears on the screen and I'm not able to perform any task after that... I have to disconnect and rejoin the server which takes more than 10 mins Please fix this bug.. A humblr request 🙏

**Comment by Lilgrizz818** [comment]
Click F8 type in Stocks 
and your problem will be fixed

**Comment by InZidiuZ** [comment]
Use the template. See #516.
