### ISSUE TITLE
PDM vehicle system.

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#626]
**Name:**
Who is suggesting this? Please include the discord name.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what your suggestion is about.
My suggest is about changing the PDM vehicle Finance or at least the Buy key or you can add a confirmation screen while buying the vehicle.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would help a lot of people who are accidentally buying vehicles by pressing F (Some people press F to sit in the car to check out the Interior).
![giphy](https://user-images.githubusercontent.com/29286961/68213221-255c6180-0001-11ea-93aa-be988a135483.gif)

**Comment by hemanLRP** [comment]
+1

**Comment by InZidiuZ** [comment]
See #632.
