### ISSUE TITLE
Everything Gone in Alta Street 9 / APT2

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#627]
**Reporter:**
BowchkaHonkHonk#5146
**Summary:**
Everything in my apt is gone and no one has lvl 2 access to it

**Steps to Reproduce:**
no idea

**Expected Results:**
to have everything in my apt say

**Actual Results:**
Everything is gone

## Additional Information

**Screenshots:**
https://clips.twitch.tv/SincereTriangularKoalaUWot

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by TwoplePop** [comment]
I believe someone can access your storage with level 1. level 2 gives furniture permissions. correct me if I'm wrong cause I'm not 100% sure

**Comment by AdeptCL** [comment]
Level 1 does. I had access to someone's house at Level 1.

**Comment by sugarc-cub** [comment]
Someone who has a key was able to get into your storage. That someone may have been me. This isn't a bug :D

**Comment by OrionSparkles** [comment]
LMFAO IM DONE

**Comment by AdeptCL** [comment]
Wooooooooooooooow.

**Comment by Bowchikahonhonk** [comment]
then thats really  fucking dumb. Level 1 shouldnt have access to storage

**Comment by Bowchikahonhonk** [comment]
Looks like Bonnie Morrello is getting a bullet on her head then xD

**Comment by sugarc-cub** [comment]
Prove it was her first ;)

**Comment by Bowchikahonhonk** [comment]
only one who has access to my apt? It was her lol

**Comment by AdeptCL** [comment]
Kinda swinging on the side that this is meta... you don't really know IC that it was her... maybe house robbery? :O Could be something very good to develop into a story line rather than going "IT WAS YOU! KILLING INBOUND!".

The quality of RP in this server is only as good as you make it.

~ In relation to your tweet also.
