### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Kr1zzzz** [InZidiuZ/op-framework-issue-tracker#628]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Kristoffer#9080
**Summary:**
Write a short summary of what you're experiencing.
Facial hair on my character doesn't save even tho I save it with an outfit 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
i go to artber shop and get eyebrows or smthing like that save it on a outfit and i lose it when i either soft log or change outfit back to back
**Expected Results:**
What are the expected results?
The facial hair doesn't get removed every time i hard log or soft log 
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
[![Screenshot from Gyazo](https://gyazo.com/bc168c4e910b0ac71e26c8ac68e8e57a/raw)](https://gyazo.com/bc168c4e910b0ac71e26c8ac68e8e57a)
Screenshot from when i am at the barbershop 
[![Screenshot from Gyazo](https://gyazo.com/0572ce51fbedd5108ee616539dbf0fb8/raw)](https://gyazo.com/0572ce51fbedd5108ee616539dbf0fb8)
Screenshot where i change to an outfit where I had facial hair saved 
**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This will be resolved with the new, planned clothing system. So won't bother with this now.

**InZidiuZ**
*OP-FW Developer*
