### ISSUE TITLE
Losing all Car upgrades

### ISSUE THREAD

**Issue by SATIN187** [InZidiuZ/op-framework-issue-tracker#629]
**Reporter:**
SATIN187#0666

**Summary:**
Drove my fully upgraded Supra to the exclusive dealership. went inside to look at cars. came back out my car was gone, went back in and came back out and my car was where i parked it but lost all of the upgrades. put it in my garage and pulled it back out still stock. even waited for restart and its still all stock

**Steps to Reproduce:**
Take s fully upgraded car to exclusive dealership go in look at cars and come back out

**Expected Results:**
For your car to stay will all your upgrades

**Actual Results:**
Go in dealership to look at cars and come out to a stock car

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by HridayHS** [comment]
I think you need to store your vehicle first in garage after upgrading it in order to save upgrades.

**Comment by SATIN187** [comment]
ive had this car upgraded since the supra first came out

**Comment by InZidiuZ** [comment]
Hey,

The way upgrades are stored in the server, is really, really bad. This won't be an issue with beta. That 'repro' also isn't really a repro...

**InZidiuZ**
*OP-FW Developer*

**Comment by SATIN187** [comment]
So just gotta deal with losing the upgrades and wait till the beta is out with the new car system?
