### ISSUE TITLE
[vehicles/garages] Personal garage at Pillbox

### ISSUE THREAD

**Issue by bluedevil69** [InZidiuZ/op-framework-issue-tracker#630]
**Name:**
@BluE_DeViL#9539

**Summary:**
We need a personal garage and a locker in PillBox. (ONLY FOR EMS) 

**Reason:**
This may very helpfull to ems staff. beacause some of guyz messaged for help then they just kidnapped and we have many things which cost more so we need a personal locker soplzz think about it

**Comment by AdeptCL** [comment]
Rent a house, and when you're at work (doing EMS stuff), don't carry it on you so store it in your home?

This literally makes no sense. What do you have on you which is so expensive that you need a locker?

**Comment by Cironite** [comment]
Thats a Big -1, Its completely useless, I am assuming you are from one of the Legacy Subdivisions, I would say an Alternative to this is make a rule change suggestion and prohibit people from calling EMS/SASP with the intention to rob them as its completely Unrealistic, If EMS were to be robbed IRL the person robbing them would be traced eventually either from the phone they called EMS with or EMS calling it out to police forces, and its just Bad roleplay in general.

**Comment by KaiEagle** [comment]
> Thats a Big -1, Its completely useless, I am assuming you are from one of the Legacy Subdivisions, I would say an Alternative to this is make a rule change suggestion and prohibit people from calling EMS/SASP with the intention to rob them as its completely Unrealistic, If EMS were to be robbed IRL the person robbing them would be traced eventually either from the phone they called EMS with or EMS calling it out to police forces, and its just Bad roleplay in general.

Eventually, we already got that rule 👍

**Comment by SATIN187** [comment]
There’s a rule on that... you can’t call somebody like a mechanic police or ems or even taxi through your phone to just rob or kidnap them

**Comment by Cironite** [comment]
> There’s a rule on that... you can’t call somebody like a mechanic police or ems or even taxi through your phone to just rob or kidnap them

Rules in other subdivisions are not the same

**Comment by SATIN187** [comment]
Looks like you need to talk to admins in the subdivision you play on cause that was an original legacy rule

**Comment by twooot** [comment]
This is done
