### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vibhavnirmal** [InZidiuZ/op-framework-issue-tracker#631]
**Reporter:**
ViN#6077

**Summary:**
BUG: The phone rings even while it is not in inventory.

**Steps to Reproduce:**
If there is no cellphone in inventory and someone calls, it would ring (without phone).

**Expected Results:**
To have no notifications while the phone is not in inventory. And when we have a phone back, it would show messages and missed calls.

**Actual Results:**
The phone rings even while it is not in inventory.

**Comment by InZidiuZ** [comment]
Hey,

This won't be an issue with the new phone. Check the 'Projects' tab.

**InZidiuZ**
*OP-FW Developer*
