### ISSUE TITLE
Outright Buying in PDM

### ISSUE THREAD

**Issue by JFEAndrews** [InZidiuZ/op-framework-issue-tracker#632]
Dynasty#7062

I had a recommendation on the outright buying of a vehicle at PDM....when you outright buy all you have to do is press G (and tackling someone is also set to G)....so is there any way for a confirmation once you hit that G muscle because me personally I just accidentally bought a motorcycle for 26k that I didn't want.....so just a suggestion maybe a confirmation after you flex that G muscle to outright buy a PDM vehicle

**Reason:**
Because it would prevent people from accidentally buying a vehicle that they did not want unless they confirm it!

**Comment by Seferti** [comment]
Just don't tackle anyone in PDM. I don't know why you would be doing that anyway.

**Comment by JFEAndrews** [comment]
I mean usually when you get tackled you tackle back...

**Comment by SATIN187** [comment]
so you just normally go around assaulting people in public?

**Comment by InZidiuZ** [comment]
Hey,

You now have to press '8' and '9' to buy/finance a car.

**InZidiuZ**
*OP-FW Developers*
