### ISSUE TITLE
ALL THE MODIFICATION ARE MISSING NOW IN LOS SANTOS CUSTOMS FOR ALL THE EXCLUSIVE CARS

### ISSUE THREAD

**Issue by SHIKARI-007** [InZidiuZ/op-framework-issue-tracker#633]
**Reporter:**
Discord ID SHIKARI#7226 Steam Link https://steamcommunity.com/profiles/76561198980369176/

**Summary:**
 All the MODIFICATION in LOS SANTOS CUSTOMS like spoiler,skirt, front bumper back bumper, hood and roof are all gone for all the exclusive cars only stock available please help on this major issue buying propriety to get these cars from exclusive dealership and not be able to upgrade them like it was available before is a major draw back and demotivating please look into this.

**Steps to Reproduce:**
Bring all the upgrades for exclusive cars spoiler,skirt, front bumper, back bumper, hood and roof in LOS SANTOS CUSTOMS.

**Expected Results:**
Have all the modification back in los Santos customs 

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
![66982800-9aa8d680-f0d4-11e9-96ed-bebef7f85e72](https://user-images.githubusercontent.com/56630831/68376067-f7e0f680-016d-11ea-9695-65b10ddbbe3b.png)
![66982801-9aa8d680-f0d4-11e9-92fc-3652a717cbac](https://user-images.githubusercontent.com/56630831/68376068-f8798d00-016d-11ea-9691-4ab7b82025fc.png)
![66982802-9b416d00-f0d4-11e9-9440-2b7514bb2952](https://user-images.githubusercontent.com/56630831/68376069-f8798d00-016d-11ea-8d48-f10ebb1df494.png)
![66982803-9bda0380-f0d4-11e9-9bde-52f8acdbcb8b](https://user-images.githubusercontent.com/56630831/68376070-f8798d00-016d-11ea-961d-7fec0ed21185.png)
![66982804-9bda0380-f0d4-11e9-9dd2-69ece2d7b948](https://user-images.githubusercontent.com/56630831/68376073-f9122380-016d-11ea-9bde-de49e39a50b5.png)
![66982805-9bda0380-f0d4-11e9-8ab3-ee055dd1b74b](https://user-images.githubusercontent.com/56630831/68376074-f9122380-016d-11ea-93b8-cc4ba77b907f.png)
![66982806-9bda0380-f0d4-11e9-80bc-ce4a7b734365](https://user-images.githubusercontent.com/56630831/68376075-f9aaba00-016d-11ea-968d-3035fa1c8f31.png)
![66982807-9c729a00-f0d4-11e9-9b65-c679f6ab1551](https://user-images.githubusercontent.com/56630831/68376076-f9aaba00-016d-11ea-957f-c6d84f7bdc8d.png)

**Game Resolution:**
1920X1080 144Hz

**Player Data:**
Character ID: 21098 Job Data Mechanic, Los santos customs, tow driver.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

The way upgrades are stored in the server, is really, really bad. This won't be an issue with beta which will include a rewrite of the vehicle system.

**InZidiuZ**
*OP-FW Developer*
