### ISSUE TITLE
Employees being able to rent out houses

### ISSUE THREAD

**Issue by FilipQeh** [InZidiuZ/op-framework-issue-tracker#634]
Name:
Who is suggesting this? Please include discord name.
FrankiE#1227

Summary:
Write a short summary of what your suggestion is about.
I would like it to be possible for people other than the CEO of the company to be able to sell houses. 
Reason:
Why would your suggestion be a good addition to Legacy?
In our RP, we are trying to become a company that sells houses. Does it make sense for a real estate agency to have only the CEO be able to sell the houses? What if the CEO isn't available to sell the house - I should lose my sale because they didn't get on? It would make sense for employees of these companies to be able to sell houses from our blocks that our CEO owns.

**Comment by AdeptCL** [comment]
I do think it makes sense that in the /companies tablet, you're able to give employees a level of access.
For example, some companies do have CEO/COO roles so there are going to be more than one person accessing the company funds also.

Creating RP for real estate agents to sell houses should already - in my opinion - been a thing when a companies/properties came out.

**Comment by InZidiuZ** [comment]
See #532.
