### ISSUE TITLE
Loan System

### ISSUE THREAD

**Issue by rachitkataria13** [InZidiuZ/op-framework-issue-tracker#635]
**Name:**
@bwat#3001

**Summary:**
A loan system for players with maximum loan amount based on the average time that they spend on the servers and each week payment will be deducted 10% of the sum amount and extra 15% will be charged as interest.
If the balance is less than the amount available in player's account then the account will be in minus amount.
Optional Feature: Select Span Of Payment (Less the time Less the Interest Rate)

**Reason:**
This can be useful to players who don't have enough money to buy cars that are expensive for them at their current wealth status or start a new business. It'll also cause players to do some jobs and grind to pay the money back. (Suggestion for Indian servers).

**Comment by AdeptCL** [comment]
> It'll also cause players to do some jobs and grind to pay the money back. (Suggestion for Indian servers).

It isn't a grinding server. It's roleplay. The idea is good for roleplay, but people need to stop this grinding mindset.

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new, more detailed issue.

**InZidiuZ**
*OP-FW Developer*
