### ISSUE TITLE
Fuel Economy

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/op-framework-issue-tracker#636]
Dean Hunt aka TwoplePop#7989

I think that fuel should last longer.

I think this would be good for legacy since people wouldn't be scared to get in an actual police chase that is long. I also feel like my Subaru shouldn't be going 10 miles while losing 80 percent of its gas. Just a little bit unrealistic how much fuel is actually in our tank.

**Comment by InZidiuZ** [comment]
Hey,

Fuel is good.

**InZidiuZ**
*OP-FW Developer*
