### ISSUE TITLE
All the upgrades disappeared in my Lamborghini 

### ISSUE THREAD

**Issue by Arcadyyy** [InZidiuZ/op-framework-issue-tracker#637]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Arcadyyy #8747 
https://steamcommunity.com/id/arcision34/
Hex Code - 11000011b445958
**Summary:**
Write a short summary of what you're experiencing.
I had fully upgraded my Lamborghini and unfortunately a accident happened that caused a blast and after retrieving the vehicle, it  was back to stock with no upgrades.
This caused around a loss of 28,000$
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
1] Upgrade the car fully
2] Blast the car / Without saving it in a garage
3] Retrieve the car and check the upgrades, it will be back to normal

**Expected Results:**
What are the expected results?
Upgrades in my car shouldn't have disappeared 
**Actual Results:**
What are the actual results?
The upgrades disappeared and the car was back to stock
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![1](https://user-images.githubusercontent.com/57530061/68479063-6f3e8500-0257-11ea-9024-eaf2ca82eff5.PNG)
![2](https://user-images.githubusercontent.com/57530061/68479069-72397580-0257-11ea-97db-e9e1bb31e753.PNG)
![3](https://user-images.githubusercontent.com/57530061/68479072-736aa280-0257-11ea-96b7-60a336c6d5c2.PNG)
![5](https://user-images.githubusercontent.com/57530061/68479078-76659300-0257-11ea-8a39-7236d9871034.PNG)

**Gam
![6](https://user-images.githubusercontent.com/57530061/68479080-7796c000-0257-11ea-8b07-a529fcc51161.PNG)

![4](https://user-images.githubusercontent.com/57530061/68479073-749bcf80-0257-11ea-85e7-d74fef69fbc8.PNG)
e Resolution:**
What is your game's resolution?
1904x1041
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID : 18870 - Job Data : Journalist,Weazel news,Reporter
**Notes:**
For anything else noteworthy.
This caused around a loss of 28,000$

**Comment by InZidiuZ** [comment]
Hey,

The way upgrades are stored in the server, is really, really bad. There also are some issues with add-on modifications/upgrades. This won't be an issue with beta which will include a rewrite of the vehicle system.

InZidiuZ
OP-FW Developer
