### ISSUE TITLE
NOT ABLE TO ACCESS THE VEHICLES FROM THE PROPERTY GARAGE

### ISSUE THREAD

**Issue by futureeeeeeee** [InZidiuZ/op-framework-issue-tracker#638]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Future#9611
https://steamcommunity.com/profiles/76561198955556085/
hex id- 11000013b52ecf5
**Summary:**
Write a short summary of what you're experiencing.
NOT ABLE TO ACCESS MY VEHICLES FROM MY HOME GARAGE IT SHOW THE GARAGE NAME OTHER THAN SHOWING 'IN' IN THE VEHICLE LIST! (THE RENT IS PAID) IM ABLE TO ACCESS MY HOUSE BUT NOT THE GARAGE WITH THE HOUSE THERES A 2 MIN SHORT CLIP EXPLAINING EVERYTHING ABOUT THE SITUATION PLEASE HAVE A LOOK INTO IT YOU WILL GET A BRIEF IDEA.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
1. GET THE 'IN' OPTION IN THE GARAGE THE VEHICLES ARE
2. GET A RETRIVE OPTION IN ANY OTHER GARAGE
**Expected Results:**
What are the expected results?
GETTING BACK THE 'IN' OPTION IN THE GARAGE OTHER THAN SHOWING THE GARGHE NAME  
**Actual Results:**
What are the actual results?
NOT ABLE TO ACCESS THE PROPERTY GARGE
## Additional Information
RENT IS PAID,PROPERTY IS ACTIVE,CAN ACCESS THE PROPERTY,NOT ABLE TO ACCESS THE VEHICLES IN THE PROPERTY GARGE 
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://drive.google.com/open?id=1SwbiQdhRS1NxRTtfDCRbeygC_cfAzQRr
**Game Resolution:**
What is your game's resolution?
1920X1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID : 42188 - Job Data : Mechanic,Los Santos Customs,Tow Driver
**Notes:**
For anything else noteworthy.
THIS CAUSED A LOSS OF MORE THAN 100K DOLLARS

**Comment by TwoplePop** [comment]
that's a lot of caps

**Comment by futureeeeeeee** [comment]
Should I Re Do It In Non Caps Form? Please Help!

**Comment by TwoplePop** [comment]
I was just looking at it sorry,

**Comment by futureeeeeeee** [comment]
Please Help Me Out With This Issue! Thanks

**Comment by InZidiuZ** [comment]
Hey,

You should be able to take your car out now. I'm guessing this was related to some mis-labeled property names, so hopefully you won't have this issue again. If you do, please comment on this issue & reopen it.

**InZidiuZ**
*OP-FW Developer*
