### ISSUE TITLE
Emote Bug

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#639]
**Reporter:**
Who is reporting this? Please include the discord name and your steam profile.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what you're experiencing.
When we jump, Tackle or anything else & while in that process if we execute emote key it will cancel that process & will trigger the emote.
**Steps to Reproduce:**
Include what steps are needed in order to reproduce the issue.
Recode it :)

## Additional Information
Video Proof:- 
https://cdn.discordapp.com/attachments/521973785218252802/642456156236939312/Desktop_2019.11.09_-_01.36.14.01.mp4
![giphy](https://user-images.githubusercontent.com/29286961/68508667-f65e1e00-0294-11ea-8748-fb5fdc30d04a.gif)

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
