### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#640]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
1. People getting More Money from the bank
2. By using hacking Cheap people can breach in another bank while another bank is getting robed.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
1.Fix the money Bug
2. Make a cool down in which before closing the bank we cant trigger another one.(for chip)
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://youtu.be/NpvVWN2ICnk

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
