### ISSUE TITLE
[animations/emotes] Hostage taking

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#642]
**Name:**
Who is suggesting this? Please include discord 
DegenTheo#2209
**Summary:**
Being able to take someone hostage and putting a gun to their head.
Something like this: https://forum.fivem.net/t/release-take-hostage/840235
**Reason:**
it would be a cool addition to the server.

**Comment by Lankovich** [comment]
I love this idea, would make a kidnapping scenario even better for both crims and cops! Cool idea

**Comment by DaxterPancake** [comment]
Closing in favour of #1661.

Thanks,
Daxter.
**Project Manager.**
