### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by iKunalmathur** [InZidiuZ/op-framework-issue-tracker#643]
**Reporter:**
Discord ID:  SOLO#8773, Steam ID:https://steamcommunity.com/id/soloind/

**Summary:**
my player die most of the time while entering or exiting to house. including my own house, friends house, NPC house. sometime my friends unable to carry me.
after pressing ENTER i loss my all the importent stuff 
this bug tends me to bear losses
**Steps to Reproduce:**
enter or exit to house

**Expected Results:**
just fix this bug ASAP and some compensation if possible

**Actual Results:**
just fix this bug 

## Additional Information
some compensation if possible

**Screenshots:**
https://imgur.com/z3beHyq
https://imgur.com/V5WR4Qh
https://imgur.com/0juxjgq
https://imgur.com/ZWKfpqJ
https://imgur.com/HwZGXbt

**Game Resolution:**
1280 x 720

**Player Data:**
Character ID: 52649

**Server:**
india

**Notes:**

**Comment by InZidiuZ** [comment]
You're not following the template correctly...

Also, most likely related to some PC *or* local game issues. If your PC is low-end, the solution might be to upgrade. If it's not, try cleaning it up, possibly with a windows reinstall. A FiveM reinstall could also be attempted.

You shouldn't run any other, unnecessary applications in the background when playing, too.
