### ISSUE TITLE
Weapon issue

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#644]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
I can shoot anyone without loosing my weapon
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take out the Gun in your hand and then open ur inventory and put the gun back in another inventory Boom Magic. 
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://youtu.be/PrMG8CwqQvU

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This should already be fixed. But you might not have the fix on the Indian servers.

**InZidiuZ**
*OP-FW Developer*
