### ISSUE TITLE
Add A lawyer white list

### ISSUE THREAD

**Issue by MinyMeep1** [InZidiuZ/op-framework-issue-tracker#645]
**MinyMeep#4702:**
Who is suggesting this? Please include discord name.

**Adding a whitelisted rank for lawyers judges, da so on so forth.:**
Write a short summary of what your suggestion is about.

**Because within the community meeting this has been requested so many times and throughout the two years of opening.:**
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Check the Trello. This is already planned.

Also, "two years" would be incorrect as we've only been on OP-FW for a couple of months & used to have a *lazy* implementation of a legal system prior to OP-FW.
