### ISSUE TITLE
Need premium company BIKES

### ISSUE THREAD

**Issue by sarnav98** [InZidiuZ/op-framework-issue-tracker#646]
**Name:**
Sarnav Dutta // A.K.A -> @L3GiON #7830

**Summary:**
Just a suggestion I wanted to make, like Premium car companies like BMW, Lamborghini.

It would be cool if premium company BIKES like Kawasaki, Yamaha can also be implemented.

**Reason:**
Because owning a premium bike that we can see in real life, gives more feel into the game.

**Comment by InZidiuZ** [comment]
Check out the 'Exclusive Dealership' marked on your map. There are a bunch of streamed IRL cars there available for server-supporters.
