### ISSUE TITLE
[illegal/principal] Pacific Standard Robbery Suggestion

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/op-framework-issue-tracker#647]
**Name:**
Lady Hope [Lady Hope#0001]

**Summary:**
Make the Pacific Standard bank up in Vinewood a robbable location. I've compiled a possible way a heist could go / the items required [here.](https://docs.google.com/presentation/d/1tlL_ztFLAbMo-6BL91Bm8qiXvwZbEsTotVRl7B6NhoE/edit?usp=sharing) It's not too different from the current robbery, so criminals can learn/improve on smaller banks, but brings that up to another level.

**Reason:**
It would be a rare small event in a way. Creates planning for criminals as they have to train and prepare for such a big venture. It also brings more to sections like SWAT who can really bring their skills to a large high-risk operation. Brings an investigation to detectives as they'll be looking into someone who is big/prepared enough to pull it off. As well as it will bring new and exciting RP that can be shared with many / all involved.

**Comment by Jaygo356** [comment]
I like the idea, but I think ben should create new items like Chains, watches etc, things like that, that are saved in safety deposit boxes and then I think people who rob the bank should get a bit of the money from the actually vault, and then most of the money would be the items, and possible since its gold smelt it down and sell it

**Comment by TwoplePop** [comment]
This idea is amazing but I dont think guns should be given since in irl, guns arent stored in banks but other than that, its amazing.

**Comment by LadyH0pe** [comment]
> This idea is amazing but I dont think guns should be given since in irl, guns arent stored in banks but other than that, its amazing.

They're more safety deposit box thus a gun would be in there, but it would need to be small hense a pistol. But I get where you're coming from :)

**Comment by y0Razz** [comment]
+1, if items like watches etc are added i would love to see that you get them from the smaller banks instead of cash only. imo that would encourage more RP to happen. Getting an amount of cash but also some materials like plastic, watches and aluminum for example :)

**Comment by InZidiuZ** [comment]
Nice document, looks good!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
