### ISSUE TITLE
In Garage C we can access the vehicle Trunk from 1st Floor also.

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#649]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
In Garage C we can access the vehicle Trunk from 1st Floor also.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Just go on first floor and type /Trunk
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/841b157413e64fbea4922dd1687a5e98

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
