### ISSUE TITLE
Granny take people eyes so that they they cant see and make whole screen Black then we need to Type /revive T-T

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#650]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
Granny take people eyes so that they they cant see and make whole screen Black then we need to Type /revive  T-T

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
No Steps
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/2a6d9eeb14cc4e696124d44d8ba1e74a
https://gyazo.com/4a4c9a71db86f4137716401b75b7d012

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
