### ISSUE TITLE
we can use /phone when we are cuffed doesn't matter we are soft or hard cuffed.

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#651]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCant'T#0001
**Summary:**
Write a short summary of what you're experiencing.
we can use /phone when we are cuffed doesn't matter we are soft or hard cuffed.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
use /phone when u get cuffed.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/12f4ee6139bcc480fa8e7ddddfc6351b

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
