### ISSUE TITLE
/e Ragdoll No Damage 

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#652]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
when u use /e ragdoll then the gun or melee Damage is ZERO 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/06efcf677e2b9470629936c5ccacab18

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue won't be resolved.

**InZidiuZ**
*OP-FW Developer*
