### ISSUE TITLE
Inventory Bandage Glitch 

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#653]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.

when we use bandage and while using bandage if we change it position in inventory then the amount of bandage will remain same.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Just change the position of all of your bandage in your inventory. 
**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/1565177814220cf7028f5df3a511850f

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue won't be resolved right now, but with Beta.

**InZidiuZ**
*OP-FW Developer*
