### ISSUE TITLE
/e ragdoll 2 time and poff Magic

### ISSUE THREAD

**Issue by ravikants542** [InZidiuZ/op-framework-issue-tracker#654]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
RaviCan'T#0001
**Summary:**
Write a short summary of what you're experiencing.
when we check in to the hospital and when we come on the bed then if we use /e ragdoll 2 times then we can escape like Harry Potter invisible cloth.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
After Check in Just use /e Ragdoll 2 times.
**Expected Results:**
What are the expected results?
People can miss use it for escaping.
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Video**
https://gyazo.com/757519ebc962fa9ae23206e395d141f5

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved.

**InZidiuZ**
*OP-FW Developer*
