### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/op-framework-issue-tracker#655]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Ciros#2048
**Summary:**
Write a short summary of what you're experiencing.
If you do the Guitar emote you dont get the AFK message and basically can afk
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
do the Guitar AFK
**Expected Results:**
What are the expected results?
Get the Automatic AFK Check message.
**Actual Results:**
What are the actual results?
You dont get the message and basically AFK all you want
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
