### ISSUE TITLE
EXCLUSIVE CAR BUG!!! 

### ISSUE THREAD

**Issue by AntiXGaming** [InZidiuZ/op-framework-issue-tracker#656]
**Reporter:**
Discord Tag - AntiX#1786 
Steam Id - bit.ly/AntixSteamID

**Summary:**
I purchased Lamborghini Super Car from Exclusive Showroom cause I have Legendary Priority,  Lamborghini was of 2,50,000$ I purchased it but it didn't spawned there then I went to garage and retrieve vechile For 250$ then my Lamborghini was showing (in)  but whenever I am cliking enter it's showing (The vechile is not in any garage) 
Now please help me either you giv me my momey 2,50,000$ so i can purchase again or you giv me the same car 
I have every proof community pls support

**Steps to Reproduce:**
I went to exclsive showroom purchased a Lamborghini for 2,50,000$ but I didn't  got it

**Expected Results:**
-

**Actual Results:**
I am not getting my car even if it gets retrieve 

## Additional Information

**Screenshots:**
Video Proof https://youtu.be/mIaCnhclNrk

**Game Resolution:**
1980 x 1080 p

**Player Data:**
IGN - MISTER FADU

**Server. ** 
India 

**Notes:**
Please provide me 2,50,000$ or please provide me that awesome car 
Cause I also purchased legendary priority for that car! 

Regards "AntiX Gaming"

**Comment by AdeptCL** [comment]
It's your own fault for purchasing the car before it loaded into your game.

**Comment by 1THC** [comment]
Retrieve it from the impound...

**Comment by InZidiuZ** [comment]
Hey,

Closing as video is gone.

**InZidiuZ**
*OP-FW Developer*
