### ISSUE TITLE
[properties/furniture] Prop Suggestions

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#657]
**Name:**
DegenTheo#2209

**Summary:**
I want to suggest a few props for houses.

List
prop_toilet_roll_01
prop_toilet_roll_02
prop_cs_keyboard_01
prop_cs_mouse_01
prop_toaster_02
v_corp_offchair
v_res_pcheadset
v_res_pcspeaker
prop_amp_01
prop_speaker_01
prop_speaker_05
v_res_mchopboard
prop_sink_06
prop_tv_cabinet_03
prop_vcr_01
prop_dj_deck_02

^ I know that some of them might not work. But would be cool to see as many of these as possible and some of them might already have been put in but im not sure.

**Comment by AdeptCL** [comment]
I'd like to see more props/furniture to the houses.

**Comment by Cricketx818** [comment]
These Items have now been added to the new furniture List, Thank you for your Suggestion, If you have more, let me know. Thank you

***SM-20 Gregory Cricket***
**OP-FW**
**Copy Paster**
