### ISSUE TITLE
Vehicle in Unaccessible Garage

### ISSUE THREAD

**Issue by KPNutz** [InZidiuZ/op-framework-issue-tracker#658]
**Reporter:**
Kieran#6701
https://steamcommunity.com/profiles/76561198093787483

**Summary:**
I previously owned 17 Mirror Park Drive and parked my two vehicles inside the garage, a 4x4 and a sports car. I then went on vacation and lost the property. Even with the highest access tier of the new owner I am unable to access the garage to get my cars. It is not possible to retrieve them or access them from any other garage.

**Steps to Reproduce:**
Store vehicles inside a house garage, lose the house, try to access the vehicles.

**Expected Results:**
You can reclaim your vehicles at a public car park.

**Actual Results:**
You have no way of accessing your vehicles.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This has not been an issue since 1.6.

**InZIdiuZ**
*OP-FW Developer

**Comment by KPNutz** [comment]
I appreciate that but currently I’ve got $250,000 worth of cars stuck in a garage that I can’t get them out of. So ermm....!?
