### ISSUE TITLE
[illegal/jewelry] Store Robbery & Jewellery Heist

### ISSUE THREAD

**Issue by Mechan1caL** [InZidiuZ/op-framework-issue-tracker#659]
**Name:**
Mechan1caL#2438

**Summary:**
Adding Store robbery & Jewellery store Heist.
1. Store robbery needs Drill to drill the vault at backside of store, it will most probably take 90 secs to drill that thing.
2. Jewellery Heist needs nothink as soon we start the heist it will trigger the alarm and you can loot the jewellery.

**Reason:**
1. Bring store robbery will help SASP cause robber's are taking 5000$ on every robbery from cops to free the hostage.
2. As the thermite's drop are low.. criminals are getting bored(OFFCOURSE NO BANK ROBBERY), So this can bring a new heist to city which will help criminals to earn money easily.
![1eb351-GTA5 2015-06-02 14-17-36-52](https://user-images.githubusercontent.com/57615196/68796724-5bd95280-0679-11ea-9d11-5253552627f3.png)
![1eb351-GTA5 2015-06-02 14-17-43-25](https://user-images.githubusercontent.com/57615196/68796725-5bd95280-0679-11ea-8f77-665a8dadefcb.png)

**Comment by InZidiuZ** [comment]
This has since been added.
