### ISSUE TITLE
[player/health] improve medical RP

### ISSUE THREAD

**Issue by Mechan1caL** [InZidiuZ/op-framework-issue-tracker#660]
**Name:**
Mechan1caL#2438
**Summary:**
This system that can help improve medical RP, It can give more info about a patient.
Any players can do /med [player ID] to check someone’s medical info like where they’ve been hit
their pulse and blood level as seen below.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This will improve the RP of EMS team, by giving patient details like it happens on real life.
![unknown](https://user-images.githubusercontent.com/57615196/68798916-4a924500-067d-11ea-8ad7-366735464ead.png)
Removing name would be best i guess.

**Comment by GIBBS260** [comment]
+1 this will help in quality rp

**Comment by MRJGAMER** [comment]
+1 Would help us treat patients with pure roleplay and with game mechanics.

**Comment by GameXport** [comment]
+1 when it's gonna come?

**Comment by TomatoPatel** [comment]
+1 this will help alot in in EMS RP.

**Comment by ArshvirSingh** [comment]
+999 this is must have thing for ems.. Please do it

**Comment by novapurple** [comment]
Feel like this might hinder in the sense if someone is trying to go into ICU or wanting to Perma , or make some good medical RP that involves intense surgery.

**Comment by ArshvirSingh** [comment]
> Feel like this might hinder in the sense if someone is trying to go into ICU or wanting to Perma , or make some good medical RP that involves intense surgery.

If they want surgery or a good rp we can do it by ignoring this but this is very good for normal 911 calls so we just don't bluff in front of patient but have actual results

**Comment by superiorchicken007** [comment]
Yes this would be nice to have.  But TBH you don't need this to RP what they have.  You can say things such as let me check their vitals and they should use /me whatever they say it is.  I believe this will hinder the "injured" person's RP by having the medics going by those stats and not on how they want to be injured or want to RP out what happened.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
