### ISSUE TITLE
[GUN HEIST BUG] Had put the correct key, Still showed Wrong key!

### ISSUE THREAD

**Issue by Arcadyyy** [InZidiuZ/op-framework-issue-tracker#661]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Arcadyyy #8747
https://steamcommunity.com/id/arcision34/
Hex Code - 11000011b445958
**Summary:**
Write a short summary of what you're experiencing.
This bug is regarding the gun heist. Even after putting the correct key combination given, it showed "Wrong key!" 
Is there any way of compensation?
Video Proof : https://youtu.be/Vtb8yyrYqys 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Steps included in video proof!
Includes the normal procedure of gun heist.
Have done a lot of gun heists before but this never happened! 

**Expected Results:**
What are the expected results?
Correct key combination shouldn't be showing any error.

**Actual Results:**
What are the actual results?
"Wrong key!" error even after putting the correct key
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

Couldn't put screenshots, have proper video proof here : https://youtu.be/Vtb8yyrYqys

**Game Resolution:**
What is your game's resolution?
1904x1041

**Player Data:**
Write /info whilst ingame and provide the information you're given.

Character ID : 18870 - Job Data : Journalist,Weazel news,Reporter

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India WL
**Notes:**
any way of compensation?

**Comment by Mechan1caL** [comment]
Yeah it hurts alot : (

**Comment by MICWIK4U** [comment]
Same Had happen ones with me So I always now wait for 4hrs in-game before doing the next then this problem don't occurs.

**Comment by InZidiuZ** [comment]
Hey,

This won't be fixed as of this moment. It'll not be an issue with beta.

**InZidiuZ**
*OP-FW Developer*
