### ISSUE TITLE
I AM NOT GETTING PROCESS COCAIN OPTIONS IN COKE LAB . I HAVE 2 BRICKS HELPPPP

### ISSUE THREAD

**Issue by SpyRipper** [InZidiuZ/op-framework-issue-tracker#662]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by iGreatWhite** [comment]
This is not the proper way to report a bug. Please utilize the template and not just the title box.

**Comment by InZidiuZ** [comment]
Hey,

No.

**InZidiuZ**
*OP-FW Developer*
