### ISSUE TITLE
Bug report(Vehicle name not in the retrieve vehicle list though it's outside.)

### ISSUE THREAD

**Issue by adityaef** [InZidiuZ/op-framework-issue-tracker#663]
**Reporter:**
harshef#4473
https://steamcommunity.com/id/bellacassa/

**Summary:**
I took my acura out in Whitelist 2 and then didn't store it and moved to whitelist 1 but I was not able to retrieve it there. I then came back in whitelist 2 but couldn't find it there also. It doesn't appear in the retrieve vehicle list and says it's not inside any garage.

**Steps to Reproduce:**
Take your acura out in whitelist city 2
Move to whitelist city 1
The acura doesn't appear in the retrieve vehicle list. (Although tried it on different cars, nothing like this happened and happened with acura for the first time also.)

**Expected Results:**
The vehicle that is not in the garage should appear in the retrieve vehicle list.

**Actual Results:**
The car doesn't appear in the retrieve vehicle list and in the vehicle list it says it's outside.

## Additional Information

**Screenshots:**
*Says the vehicle is not inside any garage* - https://prnt.sc/px6931
*Retrieve vehicle list is empty* - https://prnt.sc/px698l

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 5847

**Server:**
India Whitelist

**Notes:**
All my rent for all the apartments is paid. This happened to me for the first time. Tried retrieving on both the servers whitelist 1 and 2 but didn't work.

**Comment by SATIN187** [comment]
It’s probably impounded check there but make sure you have $500 cash on you

**Comment by adityaef** [comment]
It should be in the retrieve vehicle if it would have been impounded. Also, if one doesn't have enough cash then for him the vehicle at least show up in the retrieve vehicle and then on selecting it says not enough cash but the problem with me is that it doesn't even appear in the retrieve vehicle.

**Comment by adityaef** [comment]
Nevermind the issue got solved when I reconnected to the server after an hour.
