### ISSUE TITLE
Lost MKII Bullpup Rifle

### ISSUE THREAD

**Issue by ElijahakaDemon** [InZidiuZ/op-framework-issue-tracker#664]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

ShadGamingYT#2453
https://steamcommunity.com/id/shadakhtar1/

**Summary:**
Write a short summary of what you're experiencing.

I dropped my Bullpup MKII rifle which i loved so much, the only rifle i loved like hell.. i was so happy to have that.. i showed it to my friends by putting it into the dashboard but another friend came and asked me to show it i was in hurry so i just dropped it and the bag just disappeared.. i was so disappointed it felt like crying.. ( hurt more than a break-up) but yeah there was no dustbin or something nearby.. i don't have the gun proof as i was not recording that time (didn't thought this would happen) but i did the same with other things.. if you can check my logs and return the gun somehow it would mean so much..

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Please look through it that where did the bag went as there was no dustbin nearby..

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://youtu.be/FEHDZ-dc1eY
PS: I just saw the recording please ignore the hissing in the video it never happened before maybe my mic jack wasn't fit properly.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
8860 character ID
 
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India Whitelist - 1
**Notes:**
For anything else noteworthy.

**Comment by SATIN187** [comment]
its a video game... and you were gonna cry?

**Comment by iGreatWhite** [comment]
It is a bug that sometimes when you drop an item the bag does not show up. This is unfortunate but refrain from dropping valuable stuff.

**Comment by ElijahakaDemon** [comment]
> its a video game... and you were gonna cry?

not actually but yeah it did hurt -_-

**Comment by InZidiuZ** [comment]
Hey,

Very sad story. Nearly cried. But, this is probably related to bad inventory-logic and will probably be fixed with beta.

**InZidiuZ**
*OP-FW Developer*
