### ISSUE TITLE
Fire Hydrant knocking people out trunks

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#665]
**Reporter:**
Duroode#2178
https://steamcommunity.com/id/Duroode

**Summary:**
When running over a fire Hydrant with someone in your trunk, the person Falls out the trunk but stays in the Animation.

**Steps to Reproduce:**
Place someone in the trunk of a car and run over and destroy a fire Hydrant

**Expected Results:**
Expected Results should be that the person remains in the trunk of the car

**Actual Results:**
The water knocks the person out of the vehicle. and keeps them in the Animation as if they were still in the Vehicle

## Additional Information

**Screenshots:**
My PoV - https://youtu.be/bQkvzLqIfEY
Langstons PoV - https://clips.twitch.tv/CrispySarcasticKathyHeyGirl

**Game Resolution:**
1920x1080

**Player Data:**
https://gyazo.com/b09101a138f9a4cf97d7487b67546890

**Server:**
Legacy Roleplay # 1 Main servers

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
