### ISSUE TITLE
Limit No. Of Alive People In Trunk?

### ISSUE THREAD

**Issue by rachitkataria13** [InZidiuZ/op-framework-issue-tracker#666]
**Name:** bwat#3001

**Summary:**
Limit the no. of alive people who can be put inside the trunk as many people use it as means of transporting a lot of people in a two seater or a four seater with 3-4 in trunk. This should not be applicable to dead people as they need to be transported to a hospital and ems is not always available. (usually after a code red situation)

**Reason:**
 This is something that cannot happen in real life as maximum people you can put in a trunk are 2 (don't ask me how I know that ;) xD)
This will help eliminate the amount of kidnapping of players and fail RP situations.

**Comment by TwoplePop** [comment]
Don't think it will eliminate the kidnapping of players and I don't think it should. We should be able to escort people or put them inside the vehicle when that person is downed. It would be more realistic but I will agree that your solution will reduce fail to. I also know that some trunks are huge af so you could probably fit more in there.

**Comment by rachitkataria13** [comment]
@TwoplePop If that's possible then its well and good else a global limit for all vehicles is good too.
Kidnapping will be not that affected but, I've seen many people with 4 in car and 3-5 in trunk just to go to a place together. I still think its worth a shot to limit the no. of people alive in a trunk. Dead shouldn't be limited as they need to get to the hosp and ems isn't always available. It's up to @InZidiuZ  we're just suggesting.

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved on the beta version.

**InZidiuZ**
*OP-FW Developer*
