### ISSUE TITLE
[game/inventory] Repair Kit price reduction 

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#667]
**Name:**
Who is suggesting this? Please include discord name.
Zurxey#2607 - https://steamcommunity.com/id/Zurxey
**Summary:**
Write a short summary of what your suggestion is about.
I would like to see the repair kit prices lowered in the tool shops. 

New Prices:
- Basic Repair Kit: $250
- Advanced Repair Kit: $500-750

As many of us know, the advanced repair kit breaks too easily, sometimes first try, if not second.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Spending $2,000 on a one use repair kit is ridiculous, Many people of this community wish for it to be cheaper, as it would allow everyone to use, and embrace the mechanic the repair kits allow. It also gives chances for racers, cops, and others that crash cars to get back out there, instead of stealing local cars, etc.

**Comment by AdeptCL** [comment]
I agree with the adv. repair kits.

However, I don't think the basic repairs should be. You find them a lot in house robberies, so if that's something you don't do, buying them from other people will improve the quantity of roleplay.

**Comment by ZurxeyH** [comment]
> 
> 
> I agree with the adv. repair kits.
> 
> However, I don't think the basic repairs should be. You find them a lot in house robberies, so if that's something you don't do, buying them from other people will improve the quantity of roleplay.

It's more or less a balancing issue with Adv. Repair Kits. They're too expensive that yield too little use to even try.

**Comment by InZidiuZ** [comment]
This has since been done.
