### ISSUE TITLE
[vehicles/vehicles] Able to turn off/on neon lights

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#668]
**Name:**
Red#8978

**Summary:**
Command to turn off/on neon light
or a keybind.

**Reason:**
Because not always you want neon lights.
If you remove the lights from Los santos, you have to buy them back which sucks.

**Note:**
FiveM has a native for neon lights.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. You can toggle this using SHIFT+H.

**InZidiuZ**
*OP-FW Developer*

**Comment by Imaghost1337** [comment]
POG!

**Comment by Livius99** [comment]
Cool stuff!
