### ISSUE TITLE
"Medical Bags"

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/op-framework-issue-tracker#671]
**Name:**
Who is suggesting this? Please include discord name.
LilGrizz818#1449
**Summary:**
Write a short summary of what your suggestion is about.
I was thinking maybe some sort of PD medical pack that treats our injuries. Currently we cannot take anything on the field during shootouts and all those situations i was thinking maybe have it at the stores we would have to pay around 500-1000 for each Medical bag.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be really good addition to legacy cause it would increase the training for our PD courses and swat courses Also will increase the RP to heal up while in shootouts. Plus alot more just lazy at writing Gn

**Comment by InZidiuZ** [comment]
Oxy, my dude)

**Comment by InZidiuZ** [comment]
& bandages wut

**Comment by AdeptCL** [comment]
#MakeOxyGreatAgain

Plenty of people stockpiling it due to no-one wanting it. So if you ain't wanna do oxy-runs, find some other people who are stocking it and buy it off them.

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new issue.

**InZidiuZ**
*OP-FW Developer*
