### ISSUE TITLE
/getintrunk

### ISSUE THREAD

**Issue by Chizz3** [InZidiuZ/op-framework-issue-tracker#672]
**Name:**
Who is suggesting this? Please include discord name.
Chizz#9511
**Summary:**
Write a short summary of what your suggestion is about.
If added, people will have the ability to get into trunk themselves instead of having someone do /carry and put them in that way.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It will add so many opportunities with RP, you could force people to get in the trunk themselves instead of doing /carry because for myself getting carried is basically stripping me of my ability to do anything for a scenario which is in my eyes a bad thing. I'm not good at explaining how it will benefit I just know it will.

**Comment by InZidiuZ** [comment]
Hey,

This has been added on the beta version. You are now able to 'Press E to enter the trunk' while the trunk is open and you are behind it.

**InZidiuZ**
*OP-FW Developer*
