### ISSUE TITLE
Import Car suggestion

### ISSUE THREAD

**Issue by LordNetloc** [InZidiuZ/op-framework-issue-tracker#673]
**Name:**
Who is suggesting this? Please include discord name.
LordNetloc #1498
**Summary:**
Write a short summary of what your suggestion is about.
I have heard that most of the import cars have little to no customization. it is kinda you get what you see. i think that the cars that have body kits should have them added. Example the supra has so much you COULD change but not in this city :(
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would encourage people to support the server. it would make it more realistic because then the imports wont be so similar.

**Comment by TwoplePop** [comment]
its a bug with lsc. Developers will get to it eventually

**Comment by InZidiuZ** [comment]
After Beta, this won't be an issue. This has also previously been addressed multiple times.
