### ISSUE TITLE
[jobs/garbage] Suggestion

### ISSUE THREAD

**Issue by Omeeno** [InZidiuZ/op-framework-issue-tracker#674]
**Name**
Omeeno

**Summary:**
Garbage Dropping Area Being Rigged

**Reason:**
Can You Make A Change Where Cars Despawn At The Garbage Truck Spawning Area And Dropping Garbage Area As Many People Rig It So No One Can Do Garbage Collector Job By Parking Cars Buses And Many Vehicles

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
