### ISSUE TITLE
PD Medical Room

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#676]
**Name:**
Duroode#2178

**Summary:**
The Medical Room Bed in MRPD should be usable like the ones in pillbox

**Reason:**
I feel like this would be a good Addition for both EMS and PD Roleplay. Make it so it has a check-in system and EMS can come down to MRPD when requested by PD to treat a Suspect that is injured. This will prevent Trips constantly for both EMS, PD and the suspect going from PD > Pillbox > back to PD and the majority of the time its often multiple trips.

**Comment by InZidiuZ** [comment]
Hey,

This will be looked into once a proper asset library is created for the framework. Until then, I will close this.

**InZidiuZ**
*OP-FW Developer*
