### ISSUE TITLE
Fake Plate Issue

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#677]
**Reporter:**
Lars.
#9309

**Summary:**
When you apply a fake plate to a car the key won't work anymore since the license plate won't match the key.

**Steps to Reproduce:**
Drive a personal car, put a fake plat on it and try to start the engine.

**Expected Results:**
Drive away like normal.

**Actual Results:**
Needing to hotwire the car even tho you got the keys in your inventory.

## Additional Information

**Screenshots:**
https://imgur.com/FH3twaY

**Game Resolution:**
1920x1080 144hz

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved already, but not pushed to the live servers.

**InZidiuZ**
*OP-FW Developer*
