### ISSUE TITLE
[new][vehicles/soundeffects] Soundeffects for police cruisers.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#678]
**Name:**
CyberSkunk#5173

**Summary:**
Write a short summary of what your suggestion is about.
I'd love to see some soundeffects inside the vehicles, maybe even when you're standing close to a cruiser that is powered "on" if that makes sense. Like you could hear different *beeps* and Radio chatter going in the background.  

**Reason:**
Why would your suggestion be a good addition to Legacy?
For me as a police officer, I like it when everything regarding the police job actually feels like a real police job. I think some people would enjoy this, maybe not everyone(?). But there might be a way to fix that by setting it into the "radio" so that you could turn if off by lowering the "music" in the settings? I think it would just feel alot more realistic and fun to have this in the police vehicles.

**Comment by DaxterPancake** [comment]
If I am not mistaken, this is already in the base game. In both the cruisers and EMS Ambulances/Explorers, every now and then you'll hear small beeps and radio static. No talking, though, from what I know.

**Comment by Lankovich** [comment]
I think so, but I do believe its turned off on Legacy, there might even be any "cooler" soundeffects, otherwise we might could have that standard soundeffects going live on Legacy? :)

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being. Feel free to create another suggestion about this in the future once the servers start receiving regular updates again.

**InZidiuZ**
*OP_FW Developer*
