### ISSUE TITLE
[assn: damage control] Gun damage/Player Health

### ISSUE THREAD

**Issue by LordNetloc** [InZidiuZ/op-framework-issue-tracker#679]
**Name:**
Who is suggesting this? Please include discord name.
LordNetloc #1498
**Summary:**
Write a short summary of what your suggestion is about.
I think that gun fights right now are not fun. People go down way too quick imo.
**Reason:**
Why would your suggestion be a good addition to Legacy?
From what i have seen and heard gunfights are somewhat short and sweet which is realistic but not necessarily fun. I think that everyone would enjoy gunfights a little more with some changes to health or damage. :)

**Comment by Aspratic** [comment]
# RemoveTheDeagle

**Comment by InZidiuZ** [comment]
Damage levels for all weapons are currently being reworked. If you have additional feedback for improvements after 2.5, please create another issue.
