### ISSUE TITLE
[jobs/dealership] PDM access to mechanic /tow and purchase menus.

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#681]
**Name:**
Who is suggesting this? Please include discord name.
Zurxey#2607
**Summary:**
Write a short summary of what your suggestion is about.
I've been thinking lately, and I have thought about this for a while, and i'm finally making it.
Recently PDM has become a new force to be reckoned with in the whitelisted world, and I believe the only thing that PDM needs now for it to be the best it possibly could be is for the workers to have access to mechanic things. Such as towing, and purchasing materials. Already we can do most of the things mechanics can, but I feel as giving PDM permission to do /tow, and access buy menus it would put us even further up on the map.
**Reason:**
Why would your suggestion be a good addition to Legacy?
I feel this would be a good addition as PDM has grown substantially, and I know how boring, and how easy it is to lose motivation sitting at a car dealership all day. Some of us don't want to run drugs, or hit banks all day every day to make money. Sure, we make money from the paychecks, but even then, it takes a long time. We'd still sell cars, and do the commission, but allowing us to tow, and purchase materials to be used at mechanic shops, and allow us to accumulate a bit more cash would be amazing, and also provide more roleplay in the community.

**Comment by Aspratic** [comment]
I like this, but what I am going to add is that only certain PDM workers will have access. They will have to go through training, to get the special PDM role
