### ISSUE TITLE
Cash storage

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#682]
**Name:**
Who is suggesting this? DegenTheo#2209

**Summary**
Let us store cash in our houses, Only make this a certain amount for example 10k or something around that amount.

**Reason:**
It would be good if you go minus in the bank by getting fined. It would let you have some spare cash stored while you try to work back the money for your bank

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
