### ISSUE TITLE
[weapons/ammo] Lowered Max Ammo

### ISSUE THREAD

**Issue by Aspratic** [InZidiuZ/op-framework-issue-tracker#683]
**Name:**
Who is suggesting this? Please include discord name.
@ Aspratic#3121
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is having less ammo allowed to be shot at a time. Instead of being able to carry 250 bullets ready to shoot, it should be cut in half to 125 or 150.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would be a good suggestion because it forces players to carry spare or extra ammo on them in their inventory. Creating variables during gunfights of people having to reload and such. It makes people more cautious when in gunfights and reduces "magdump season"

**Comment by Aspratic** [comment]
ARs and SMGs currently have more. But I personally think 150 max for all guns would be the best

**Comment by InZidiuZ** [comment]
Closing in favor of #1366.
