### ISSUE TITLE
Assault Rifle MKII has only 1 weight

### ISSUE THREAD

**Issue by HridayHS** [InZidiuZ/op-framework-issue-tracker#684]
**Reporter:**
Discord: Red#8978
Steam ID: https://steamcommunity.com/id/hridayhs

**Summary:**
Title

**Steps to Reproduce:**
Have Assault Rifle MKII

**Expected Results:**
It should be heavy and not have 1 weight.

**Actual Results:**
Title

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/633997799834386463/646688562544377857/IMG_20191120_171429.jpg

**Server:**
Indian

**Comment by HridayHS** [comment]
Also Machine Pistol have 22 weight, isn't way too much considering rifles have around same weight.

**Comment by InZidiuZ** [comment]
Hey,

This won't be changed until the inventory system is rewritten.

**InZidiuZ**
*OP-FW Developer*
