### ISSUE TITLE
Bug report op base: verifying account cannot login to legacy roleplay india 

### ISSUE THREAD

**Issue by robingill05** [InZidiuZ/op-framework-issue-tracker#685]
**Reporter:**
Robin Gill #3334 https://steamcommunity.com/profiles/76561198074921319/
**Summary:**
when i login to legacy roleplay india i get error op base:verifying account and cannot login it only comes on india server i tried login in to bangladesh server and i got logged in its been 2 months no admin is able to help me 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
https://imgur.com/PDZwcTS  https://imgur.com/Cv8qAsD

**Game Resolution:**
1600*900

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
India

**Notes:**
explained everything above 
![Untitled](https://user-images.githubusercontent.com/58003681/69262696-ee35a500-0be9-11ea-9129-2b12d14852d0.jpg)
![Capture](https://user-images.githubusercontent.com/58003681/69262697-ee35a500-0be9-11ea-8fb4-894996126427.PNG)

**Comment by InZidiuZ** [comment]
Hey,

Restart steam, relog into your rockstar account. If that doesn't work, contact FiveM support maybe idk.

**InZidiuZ**
*OP-FW Developer*
