### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Lunar929292** [InZidiuZ/op-framework-issue-tracker#686]
**Name:**
Who is suggesting this? Please include discord name.
tophead#0799

**Summary:**
Write a short summary of what your suggestion is about.
I am suggesting that a functioning & lockable gate is to be added to the Lost MC repair shop. similar to the gate @ MRPD, this gate would only be lockable by members of the lost or above & required to be under the list of employees for the company. (/comps).. what I am saying is tying the locking function to the "Block". 

(Example Video without locking function)
[https://streamable.com/m7qag](url)

**Reason:**
Why would your suggestion be a good addition to Legacy?
I would like to see this be added simply for when we are not around, having a meeting, etc. Privacy is the main point.. if we have a war going on in mirror park close shop. lock the gate.. don't mess with it and don't let the people from the war inside and drag their illegal business into our place of work. we treat the lost as neutral zone with no Illegal business or intent for anyone to bring their illegal business to the lost.

**Comment by Seferti** [comment]
I don't think this is possible because i believe you would need a job to be able to lock/unlock gates and doors

**Comment by Lunar929292** [comment]
> I don't think this is possible because i believe you would need a job to be able to lock/unlock gates and doors

yes, you would need a job, but I feel it would be possible to be done through the blocks system & company. not sure yet.. we will see I guess. :)

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZidiuZ**
*OP-FW Developer*
