### ISSUE TITLE
Hacking Screen During Gun Heist Not Appearing

### ISSUE THREAD

**Issue by CreamSlush** [InZidiuZ/op-framework-issue-tracker#687]
**Reporter:**
Cream Slush#8990
https://steamcommunity.com/id/asdfsagfasdfsd/

**Summary:**
Used all Keys in the correct order 

**Steps to Reproduce:**
Not quite sure how to reproduce. It could of been from my friend messing up the hacking on his first one. Then I did mine afterwards. But from what I was told, that shouldn't matter.

**Expected Results:**
A Hacking Screen should of popped up after using the last key.

**Actual Results:**
Nothing happened after using the last key.

## Additional Information

**Screenshots:**
Video: https://www.youtube.com/watch?v=4vSURfrryv0&feature=youtu.be
(I accidentally had my screen capture at 1 minute 30 sec. So you won't see me use the blue key or the chip hacking.)

**Game Resolution:**
1920x 1080

**Player Data:**
Character ID: 13131

**Server:**
Main

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Hey,

Unable to investigate due to incomplete template. No F8 console, no timestamp.

**InZidiuZ**
*OP-FW Developer*
