### ISSUE TITLE
Garbage Collector: Sometimes runs have no trash to pickup and return to HQ with no payment

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/op-framework-issue-tracker#688]
**Reporter:**
Legacy Roleplay in-game: Johnny Flame
Discord: Johnny2s#5991
Steam: https://steamcommunity.com/id/johnny2s

**Summary:**
When starting a trash run, it directs you to drive to the general area to initiate the trash bag pickups. However, sometimes when you arrive at the destination, it immediately states to return to HQ. When returning, it accepts the garbage truck but pays out no money and you have to start another run. I've had this happen 2-3 times in a row, when driving across the city. There's no way that the city is cleaned of all trash at times!

**Steps to Reproduce:**
Do a bunch of garbage runs and you'll encounter soon enough.

**Expected Results:**
Doing a garbage run with no trash to pickup, thus returning to HQ and getting paid nothing. Sometimes happens multiple times in a row.

**Actual Results:**
Above

## Additional Information

**Screenshots:**
None

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 11187 - Job Data: Government, Waste Collector, Employee, Timestamp: 2019-11-21 18:41:07

**Server:**
EU/NA #1-2

**Notes:**
None

**Comment by InZidiuZ** [comment]
Hey,

This is related to GTA not spawning in garbage bags. It might try to compensate performance by not spawning too many objects in, so if you have low-end PC, a possible solution is to upgrade.

**InZidiuZ**
*OP-FW Developer*
