### ISSUE TITLE
[game/cad] Criminal Records In Court House!

### ISSUE THREAD

**Issue by GameXport** [InZidiuZ/op-framework-issue-tracker#690]
**Name:**
GameXport#1320

**Summary:**
It would be good if criminals can see their or others criminal records in court house. They can also see that if they have warrants or not.

**Reason:**
It would improve Criminal Roleplay and it will also improve overall RP.

**Comment by InZidiuZ** [comment]
This would be a thing whenever the CAD is created.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
