### ISSUE TITLE
[companies/state] Mayor/State Announcement In OOC Chat!

### ISSUE THREAD

**Issue by GameXport** [InZidiuZ/op-framework-issue-tracker#691]
**Name:**
GameXport#1320

**Summary:**
I don't think that there is any state announcement option in OOC chat. I have provided a screenshot (for example). 
![Screenshot_14](https://user-images.githubusercontent.com/57890579/69408129-293ff180-0d2c-11ea-872e-31ae8d82f497.png)

**Reason:**
It will improve the quality of RP in the city. It would be helpful for state employees and Mayor. If they want to announce something in the server, they don't need to type those things in OOC, they can make an State Announcement.

**Comment by InZidiuZ** [comment]
This will not be added at this time.
