### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bhagyesh2791** [InZidiuZ/op-framework-issue-tracker#692]
**Name:**
Bhagyesh#2791

**Summary:**
Before AFK kick there should be a warning displayed on whole screen 

**Reason:**
Because during situation sometime police dies and they cant respawn untill situation is over and sometime they even dont move their mouse and just sit mostly streamers do so if warning come they can move their mouse and prevent afk kick

**Comment by FossiiLs** [comment]
There is already warning telling you to type /afk or you'll be kicked.

**Comment by InZidiuZ** [comment]
Hey,

As @FossiiLs said, this is already a thing.

**InZidiuZ**
*OP-FW Developer*
