### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Eagl3Eyes** [InZidiuZ/op-framework-issue-tracker#694]
**Reporter:**
discord- Eagl3Eyes™ ◈👑#2740 
steam- https://steamcommunity.com/id/tuhin_aj/
![Screenshot_2019-11-23 VACBanned com - See the VAC status of any Steam account (Counter Strike, Left 4 Dead, Call of Duty Mo](https://user-images.githubusercontent.com/58110053/69483269-618c2080-0e4f-11ea-9995-2cb00557ed94.png)

**Summary:**
property glitch.my purchased property are not showing in the map. 

**Expected Results:**
i cant span in my house.

**Actual Results:**
this is a big problem for me. i cant access normally.

## Additional Information
my purchased  property are not showing in the map. in the house door i cant access by pressing ''E''. but if i use "/enter" command then i can access in my house. i can access my storage too. and i cant span in my house.

**Screenshots:**
![Screenshot (256)](https://user-images.githubusercontent.com/58110053/69483261-39042680-0e4f-11ea-9650-0b5b69d0c086.png)
![Screenshot (257)](https://user-images.githubusercontent.com/58110053/69483263-399cbd00-0e4f-11ea-919a-284043581128.png)

i have video clip also- https://drive.google.com/open?id=17FFcKBc-f6BH8_osuGg5J3DqGJpgXjjf

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 49665 - Job Data: Government, Waste Collector, Employee

**Server:**
Bangladesh

**Comment by InZidiuZ** [comment]
Hey,

This issue is already known, and will be fixed with beta.

**InZidiuZ**
*OP-FW Developer*
