### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kr1zzzz** [InZidiuZ/op-framework-issue-tracker#695]
**Name:**
Who is suggesting this? Please include discord name.
Kristoffer#9080
**Summary:**
Write a short summary of what your suggestion is about.
a body kit for the BMW M4
https://www.gta5-mods.com/vehicles/m4-f82-widebody
**Reason:**
Why would your suggestion be a good addition to Legacy?
i think it would have been a good addition since the BMW doesn't have a lot customizable to the car the only thing you can change is the roof and the hood

**Comment by InZidiuZ** [comment]
Hey,

Wrong issue tracker. Check this one out: https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues

**InZidiuZ**
*OP-FW Developer*
