### ISSUE TITLE
'player dropped priority level' increase

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/op-framework-issue-tracker#696]
**Name:**
Kiwi#6887

**Summary:**
Crash priority should be higher than the legendary tier and staff prio as when a person's game crashes or they have to relog, they shouldn't be met with a queue when trying to rejoin considering it isn't exactly their fault.

**Reason:**
If you're in an rp scenario and your game crashes, they might have to wait up to an hour to get back into the city where they can't exactly resume the roleplay.

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
