### ISSUE TITLE
Bug report (CHOP SHOP 2 cars with same number plate)

### ISSUE THREAD

**Issue by heisenberg512** [InZidiuZ/op-framework-issue-tracker#697]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Discord: Azzy#6584
Steam: steamcommunity.com/id/azzy5

**Summary:**
Write a short summary of what you're experiencing.
Aight, so i was doing chop shop work in Legacy India City 4, and was headed to the delivery/chop shop after getting the vehicle. I was very much near to the location when the radio chattered and said that the vehicle had been delivered and i was dumbfounded. i just went in to check and found that other car with same number plate was delivered by some other guy. Then when the next car appeared our car name was different but the number plate was same so was its location.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Perhaps a check that would delete any one of the vehicles with same number plate and send the info over the radio after its deleted

**Expected Results:**
What are the expected results?
One car with unique number plate 

**Actual Results:**
What are the actual results?
-

## Additional Information
  Later a guy wrote on ooc that there;;s another car with same plate so anyone who wanted it could come and get it ... :) 
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://i.imgur.com/tnyT7QN.png

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Name: Azzy Banks CID:29808 Job: Mechanic
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

Legacy India City #4 

**Notes:**
For anything else noteworthy.
-

**Comment by InZidiuZ** [comment]
Hey,

This is *either* a coincident (definitely possible as GTA's plate generation seems to follow a very specific pattern) but it's even more likely that the player that was before you used a mod menu to manipulate the vehicle's plate number. He also had the incorrect vehicle model, so it's likely.

You could probably get the player banned if you report the player, though.

**InZidiuZ**
*OP-FW Developer*
