### ISSUE TITLE
Suggestion [PDM confirmation msg]&[Car name being displayed above it ]

### ISSUE THREAD

**Issue by heisenberg512** [InZidiuZ/op-framework-issue-tracker#699]
**Name:**
Who is suggesting this? Please include discord name.
Discord: Azzy#6584
Steam: steamcommunity.com/id/azzy5
**Summary:**
Write a short summary of what your suggestion is about.
1.In my opinion there should be a confirmation msg that would ask us if we really want to buy/finance the requested car .
2.Vehicle's name displaying above it where the Price/Finance Price/Commission is displayed.

**Reason:**
Why would your suggestion be a good addition to Legacy?
1.After the latest update many people accidentally financed a car even though they werent willing to, all they wanted was to sit in the car and see its name (including me).

**Comment by iGreatWhite** [comment]
It was changed to keys 8 and 9? Why would you be getting in a car using key 8 or 9?

**Comment by heisenberg512** [comment]
> It was changed to keys 8 and 9? Why would you be getting in a car using key 8 or 9?

suggested this before the update got pushed so imma close it now.
