### ISSUE TITLE
Garage of the house that i used to own

### ISSUE THREAD

**Issue by markoLuis** [InZidiuZ/op-framework-issue-tracker#700]
**Reporter:**
Pizza#2928

**Summary:**
I used to own a house up at mount chiliad and cause i wasnt paying the rent that house got taken of me but i was using the garage of that house and now that the house is gone it still says theres cars in that garage wich i cant get in. Some staff member told me they should just spawn at garage or either wait till next restart and it will be fine. Cant retrive the cars either.

**Steps to Reproduce:**
/

**Expected Results:**
Iam hoping to get cars back.

**Actual Results:**
/

What are the actual results?
/
## Additional Information
/
**Screenshots:**
https://gyazo.com/f1efafc014e4afc2dcecede7129710ee

**Game Resolution:**
1920x1080

**Player Data:**
Characther ID: 1110 - Job Data: mechanic, lost santos customs, tow driver

**Server:**
Legacy server EU/NA

**Notes:**
/

**Comment by InZidiuZ** [comment]
Closing due to not following the template. This also isn't an issue. Your vehicles are automatically put back to other garages once the house is removed from you.
