### ISSUE TITLE
Many people's tuner chip is not working the people who got it earlier when it came out only that one is working

### ISSUE THREAD

**Issue by AGboi** [InZidiuZ/op-framework-issue-tracker#701]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by ZurxeyH** [comment]
Tuner Chips havent worked for a while. Even when they are fixed, they continue to bug out. It's just going to need to be worked on, but InZidiuZ has other priorities.

**Comment by InZidiuZ** [comment]
Tuner-chips have been working since the latest rewrite from what I know. If there are issues, create a proper bug-report using the template.
