### ISSUE TITLE
[vehicles/wheels] Camber Adjustment System with the tuner chip

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/op-framework-issue-tracker#702]
Who is suggesting this? Please include discord name.

Dean Hunt | TwoplePop#7989

**Summary:**
A Camber system would be like adjusting the camber on the back wheels and the front wheels on the tuner chip menu. 

**Reason:**
The wheel offset system may have been canceled but I feel like this system could revive the motive to do the wheel offset system. The reason for adding this would be variation in everyone's cars since there are a lot of the same cars going around.

**Comment by Karpenkooo** [comment]
From what i understand there are many issues with the Offsets however it would be so cool if we had it :))))

**Comment by ZurxeyH** [comment]
Offsets and Camber would be absolutely amazing. The wide-body kits that are now available with LS Customs being fixed, it would allow us car lovers to enjoy the vehicles just that much more!

**Comment by KiwiUK** [comment]
+1 Some widebody cars just don't look as appealing without the offsets and cambers.

**Comment by TwoplePop** [comment]
"cough' "cough", r35

**Comment by Karpenkooo** [comment]
Also, @ZurxeyH is sending me a pic of his car without offset every day until we get offset. Soooooo yeah :)

**Comment by Karpenkooo** [comment]
plez add <3

**Comment by InZidiuZ** [comment]
I believe I have an idea of how this *could* be implemented without it totally scuffing out. But with the tuner-chip, though? Wouldn't it be more realistic if you had to change the offsets in LSC?

**Comment by TwoplePop** [comment]
Yea, it would be more realistic in LSC

**Comment by KiwiUK** [comment]
The offsets should just come with the corresponding wide body kits when selecting them in LSC. With a tuner chip,  not everyone would have access to it and it would reset every tsunami.

**Comment by TwoplePop** [comment]
I think offsets should be done at LSC or bennys for that reason but I think that the camber should be exclusive to the tuner chip

**Comment by KiwiUK** [comment]
The question is how would LSC know if you have a tuner chip or not?

**Comment by TwoplePop** [comment]
I mean, there should be either a preset or an option to change the offset on somebody cars in LRC without a tuner chip, but the tuner chip would be used to camber solely with the tuner chip. As in offset=LSC, Camber=Tuner Chip

**Comment by ZurxeyH** [comment]
> 
> 
> I believe I have an idea of how this _could_ be implemented without it totally scuffing out. But with the tuner-chip, though? Wouldn't it be more realistic if you had to change the offsets in LSC?

If you are going to work on this, it would be greatly appreciated. As stated above, the offset should come with standard bodykits from LSC / Bennys. If it's harder to do that, we can always add offsets ourselves, but be ready for people to have cars with tires 20 inches out from the wheelcage.

**Comment by InZidiuZ** [comment]
So I've been writing an improved syncing system for beta which also allows this to be added with ease. I suppose [this](https://gyazo.com/c43329d89cb2a3b55b2319eb1737d017) is what you were looking for? It's been tested with a secondary client & works phenomenally, I just need to make it available for modification/purchase through the tuner chip as mentioned or LS customs.

Neither of those are implemented on my local test server right now though, so I'll do that later.

**Comment by InZidiuZ** [comment]
ops

**Comment by Karpenkooo** [comment]
I think LS Customs would be best

**Comment by iGreatWhite** [comment]
LS customs would be a better option because not everyone has a tuner chip.

**Comment by Livius99** [comment]
We also need more upgrades in LSC, I've seen that some car upgrades aren't included yet

**Comment by InZidiuZ** [comment]
Hey,

Closing this as functionality for it has been added. It'll most likely be available in the LS customs once that is added.

**InZidiuZ**
*OP-FW Developer*
