### ISSUE TITLE
Bought a vehicle, got another one

### ISSUE THREAD

**Issue by DeviLPunisheR** [InZidiuZ/op-framework-issue-tracker#703]
**Reporter:**
Discord :-  Fuk_Fuk_Fukrey#9763 
steam:-  https://steamcommunity.com/id/Fuk_Fuk_Fukery/

**Summary:**
I bought a Car For PDM by mistake, I saved It on in my Garage Now its changed into another Truck which I never bought can I get my original car back.

**Steps to Reproduce:**
Don't know what to type here! Sorry

**Expected Results:**
Getting my original car back and removing that truck.

**Actual Results:**
The car I bought that should be in my garage.

## Additional Information
U have Nicer server going on If I could donate I wold have donated U on while streaming enjoy your day.

**Screenshots:**
https://youtu.be/8a8s_QBh0iA , 
https://imgur.com/qj81Zir , 
https://imgur.com/DEVQAJ6
**Game Resolution:**
1920X1080 (Full screen)

**Player Data:**
  
Name:- DeviL PunisheR
Character ID:-36713
**Server:**
Legacy India

**Notes:**
U are doing nice job just few more request Please add more jobs on Life invader.

THANK YOU!!!! ;)

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new issue.

**InZidiuZ**
*OP-FW Developer*
