### ISSUE TITLE
[game/jail] Lose job when jailed

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#704]
**Name:**
DooZolz#4014

**Summary:**
It's pretty simple, let's say I'm a garbage collector and I go to jail. I basically just loose my job and if I want to get it back then I have to go back to life invader.

**Reason:**
It's just more of a cool realistic thing and could possibly stop people from grinding garbage runs all day and plus you know this server I heard NoPickle I think it is has it so mine as well copy them you know.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
