### ISSUE TITLE
Radio Animation for everyone

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#705]
**Name:**
Daxter#7158

**Summary:**
I'd like to suggest to making the Radio Animation able to be used by everybody, not just EMS and Police.

**Reason:**
I feel like it would be useful to legacy because you'd be able to tell when people are talking to their people, from afar or from up close. For example, if you're trying to hold someone up, as it currently is, they are able to hot mic and talk to their people, if they had the radio animation then you'd be able to tell when they are trying to talk to their gang or friends and put a stop to it before you have a whole gang coming to destroy you.
I understand if it was made that everyone can use it, some people would not, but for whitelisted gangs at the very least, I feel it would be a welcomed addition.

**Comment by TwoplePop** [comment]
definitely +1, just gotta trust that people will actually use the keybind

**Comment by LilMags** [comment]
100% a +1. I recommended this in the community meeting and it kinda went un-noticed. I would mainly like it for when speaking to people, other people will know that you are talking down your radio

**Comment by AdeptCL** [comment]
+1 to this.

**Comment by Duroode** [comment]
Fat +1

**Comment by AmateurProfessional** [comment]
+1

**Comment by MICWIK4U** [comment]
This Is will Be great Enough By Adding Hot Mic Radio It game it self rather than using TS/discord.

**Comment by InZidiuZ** [comment]
Hey,

I believe this is now irrelevant with the TokoVoip currently being added.

**InZidiuZ**
*OP-FW Developer*
