### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JatinSharma-007** [InZidiuZ/op-framework-issue-tracker#706]
**Reporter:**
discord - Akiller24#9433
**Summary:**
I purchased block 9 on indian server and realized that it didn't have garage to store vehicles
**Steps to Reproduce:**
N.A.
**Expected Results:**
I want you to add garages
**Actual Results:**
Add garage 
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
India
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Not a bug.
