### ISSUE TITLE
I have Property But I Can't Access

### ISSUE THREAD

**Issue by Eagl3Eyes** [InZidiuZ/op-framework-issue-tracker#707]
**Reporter:**
discord- Eagl3Eyes™ ◈👑#2740
steam- https://steamcommunity.com/id/tuhin_aj/
![Screenshot_2019-11-23 VACBanned com - See the VAC status of any Steam account (Counter Strike, Left 4 Dead, Call of Duty Mo](https://user-images.githubusercontent.com/58110053/69665585-dc09aa00-10b4-11ea-9d5a-b5770e7a8344.png)

**Summary:**
My purchased property are not showing in the map. And i can't spawn in my Property. but My properties are showing on the Company menu. 

**Actual Results:**
 I cant access/spawn in my house.

## Additional Information
My purchased property are not showing in the map. in the house door i cant access by pressing ''E''. but if i use "/enter" command then i can access in my house. i can access my storage too. and i cant span in my house.
And i can access 1 house by "/enter" command but i cant access/spawn other two Property. and My properties are showing on the Company menu. 
**CHECK MY VIDEO CLIP & Screenshots**
**Video Clip-** https://drive.google.com/open?id=17FFcKBc-f6BH8_osuGg5J3DqGJpgXjjf

**Screenshots:**
![Screenshot (286)](https://user-images.githubusercontent.com/58110053/69666083-dc567500-10b5-11ea-8679-d79f27519772.png)
![Screenshot (287)](https://user-images.githubusercontent.com/58110053/69666092-e1b3bf80-10b5-11ea-8c51-876abb1f9acb.png)

video clip- https://drive.google.com/open?id=17FFcKBc-f6BH8_osuGg5J3DqGJpgXjjf

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 49665 - Job Data: Government, Waste Collector, Employee

**Server:**
Bangladesh

**Notes:**
I cant access/spawn in my house. its big issue for me. Please fix this issue ASAP.

**Comment by LilMags** [comment]
Try going into your purchases tab, then give keys to yourself. Worked for me.

**Comment by Eagl3Eyes** [comment]
how can i find purchases tab ?

**Comment by Eagl3Eyes** [comment]
It's not working for me.
