### ISSUE TITLE
[illegal/guns] Addition of 2 more Class 2s

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#708]
**Name:**
Who is suggesting this? iGreatWhite#8870

**Summary:**
The addition of the Gusenberg and the AP pistol to gun drops. Also with a change of more common drops being one handed guns and SMGs and making ARs more rare.

**Reason:**
Why would your suggestion be a good addition to Legacy?
The gusenberg fits my organizations style of mafia roleplay. We feel it would be a very cool gun to see in the city. The AP pistol would even out the number of each class 2 type in the city. The added change to rarity of guns would make ARs a lot less common.

**Comment by InZidiuZ** [comment]
This has since been done.
