### ISSUE TITLE
Unable to access owned properties

### ISSUE THREAD

**Issue by Eagl3Eyes** [InZidiuZ/op-framework-issue-tracker#709]
**Reporter:**
discord- Eagl3Eyes™ ◈👑#2740
steam- https://steamcommunity.com/id/tuhin_aj/
![Screenshot_2019-11-23 VACBanned com - See the VAC status of any Steam account (Counter Strike, Left 4 Dead, Call of Duty Mo](https://user-images.githubusercontent.com/58110053/69696171-0be29d00-1109-11ea-88af-2d8900f71e8e.png)

**Summary:**
My purchased property are not showing in the map. And i can't spawn in my Property. but My properties are showing on the Company menu.

**Actual Results:**
I cant access/spawn in my house.

## Additional Information
My purchased property are not showing in the map. in the house door i cant access by pressing ''E''. but if i use "/enter" command then i can access in my house. i can access my storage too. and i cant span in my house.
And i can access 1 house by "/enter" command but i cant access/spawn other two Property. and My properties are showing on the Company menu.
**CHECK MY VIDEO CLIP & Screenshots**
**Video Clip**- https://drive.google.com/open?id=17FFcKBc-f6BH8_osuGg5J3DqGJpgXjjf

**Screenshots:**

![Screenshot (287)](https://user-images.githubusercontent.com/58110053/69696240-4ba98480-1109-11ea-8c36-cb0ba7f0f3ce.png)
![Screenshot (286)](https://user-images.githubusercontent.com/58110053/69696254-5237fc00-1109-11ea-8f6f-c090b789a444.png)

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 49665 - Job Data: Government, Waste Collector, Employee

**Server:**
Legacy RP Bangladesh 

**Notes:**
I cant access/spawn in my house. its big issue for me. Please fix this issue ASAP.

**Comment by Cricketx818** [comment]
This issue will be fixed once the Beta comes out, For now to fix that issue, Spawn at train station, And go back to Press [E] to exit city and the other homes will appear.


**OP-FW**
**Copy Paister**
**[SM-30][PDM]Gregory Cricket

**Comment by Eagl3Eyes** [comment]
it's not working. @Cricketx818
