### ISSUE TITLE
[properties/properties] Garages for 'Forum Drive' apartment complexes

### ISSUE THREAD

**Issue by aggaming111** [InZidiuZ/op-framework-issue-tracker#710]
**Name:**
Who is suggesting this? Please include discord name.
This is Aakash Ghodke ( AG Gaming ) discord id AG 👑#8683

**Summary:**
Write a short summary of what your suggestion is about.
please put garages on forum drive apartments groove street there is lot of space for garage there is a garage for only 2 apartments in forum drive but other 6-7 apts doen't have any garage

**Reason:**
Why would your suggestion be a good addition to Legacy?
being a company owner all customes ask for garage and also peoples says that they have garage and why dont we have a garage so please put garages in forum drive apts too

**Comment by AdeptCL** [comment]
Some apartments would have the facility. But apartments tend to not have personal garages.

**Comment by pxyeb** [comment]
All of the Forum Drive Apartment Complexes have now an accessible garage. They will be usable within the newest update.

**Pxyeb**
*OP-FW Helper*
