### ISSUE TITLE
Suggestion - Giving Impounding Option For Tow Drivers

### ISSUE THREAD

**Issue by LOxPanda007** [InZidiuZ/op-framework-issue-tracker#712]
**Name:**
Who is suggesting this? Please include discord name.
This Is Tony Vercetti And I Live In Black Legacy City? debabratapanda_0710#5425

**Summary:**
Write a short summary of what your suggestion is about.
Please, Give Impounding Options For Tow Drivers In The Legacy Cities.

**Reason:**
Why would your suggestion be a good addition to Legacy?
When Respected Officers Or Admins Are Not In City, Most Of Peoples/Citizens Block Cars In Road And Infront Of Pillbox. I'm Not Saying Giving Direct Option As Officers And Admins Impound The Vehicles. If Vehicles Are Destroyed Then Give The Option For Tow Drivers To Impound The Vehicles. If, Vehicles Are Ok. Then, The Tow Driver Can Tow The Vehicles. It's A Humble Request.
Because Of Its A Big Issue In Black Cities. Peoples/Citizens Just Destroyed Cars Un-Necessary In Cities And Doing Anything In This City.

**Comment by LilMags** [comment]
Nah, Tow Driver isn’t a whitelisted job. This feature would be 100% abused

**Comment by LOxPanda007** [comment]
I Don't Know Much Sir. But If In Future It Will Come. It Will Help To Clear Or Impound Damaged Vehicles From Roads

**Comment by MICWIK4U** [comment]
You Get already Get Impound power in tow job you Need To do Proper RP Way like bring Tow Truck Tow the Vehicle And Send it to Impound Lot.

**Comment by InZidiuZ** [comment]
Hey,

To impound a vehicle as a 'tow driver', use the impound lot.

**InZidiuZ**
*OP-FW Developer*
