### ISSUE TITLE
Trunk wiped

### ISSUE THREAD

**Issue by sallugt5rp** [InZidiuZ/op-framework-issue-tracker#713]
**Reporter:**
hello this is wilson. my discord and steam name is knightflyerminja
**Summary:**
All stuff in my van get disappeared and now my van is empty and i don't have any screenshot of my stuffs in my van.

**Expected Results:**
I want to you to solve this problem as fast as possible because am facing this problem second time.

## Additional Information
Vehical plate no - 18HAX787 (rumpo news van)

**Game Resolution:**
1440*900

**Player Data:**
CID-29815

**Server:**
Legacy rp india

**Comment by InZidiuZ** [comment]
Hey,

This issue should be resolved with the beta version of the framework.

**InZidiuZ**
*OP-FW Developer*
