### ISSUE TITLE
Attorney/Judge in-game jobs

### ISSUE THREAD

**Issue by AmateurProfessional** [InZidiuZ/op-framework-issue-tracker#714]
**Name:**
Amateur_Professional#7313 (M-37 Shazzles)

**Summary:**
Adding a job in game to allow judges and attorneys to exist. 

**Reason:**
Adding a white listed job for attorneys and judges to allow for court proceedings to take place in game. Currently anyone can claim to be an attorney and it just falls into a fake attorney arguing with a cop, which isn't how it should go. With my suggestion, predetermined judges and white listed attorneys would take over the case to argue if the suspect is in fact guilty of the charges held against them 

With the recently implemented penal code, there are now ways to prove if someone is innocent or guilty using the language as it is written. But court cases could be for civil and criminal cases. 

What the jobs should do:

I believe the attorney and judge jobs should be able to fine *and collect* payments from individuals. I believe the pay scale for judges and attorneys  should be a similar structure to EMS. If possible, giving the judges the ability to seize assets (/repo) provided enough evidence. When a judge enters the city, an announcement stating a judge has entered the city to allow for a bench trial or full trial if attorneys are also present. I believe Judges and Attorneys should have ID cards that state they are either a judge or an attorney. 

The ranking structure: 

Judge - presiding over all court cases.
Partner - Individuals leading the law firm
State Attorney Manager/Associate Attorney Manager
Senior District Attorney/ Senior Associate Attorney Manager
District Attorney/Associate Attorney
Paralegal
Intern
Applicant

Work has already begun on the back end, in hopes this gets implemented in a more official fashion.

**Comment by OrionSparkles** [comment]
+1

**Comment by Duroode** [comment]
+1

**Comment by Alabeen** [comment]
+1

**Comment by Cironite** [comment]
+69

**Comment by Brundoggy** [comment]
Plus one

**Comment by KPNutz** [comment]
+1

**Comment by AdeptCL** [comment]
Having a full Court system in place is brilliant to the server. However, it can only be done if the correct total of personnel will do it.

I think a lot of people don't realise that they could just have a standalone 2nd/3rd character dedicated to a Lawyer+. And whenever one is needed, something can be posted in a Lawyer chat for someone to hopefully join the city and do it.

Again, unfortunately it will only work if the right personnel will do it. You can't just have a standard ordinary person being Lawyer who doesn't have 0 knowledge of the Law, procedures, and arguments.

**Comment by FilipQeh** [comment]
+420

**Comment by InZidiuZ** [comment]
Hey,

If this is still relevant, please create a new issue.

**InZidiuZ**
*OP-FW Developer*
