### ISSUE TITLE
Suggestion | Idea 

### ISSUE THREAD

**Issue by RezGamingg** [InZidiuZ/op-framework-issue-tracker#715]
Name:
Who is suggesting this? Please include discord name.
I am Reece, Discord is: RezGamingg#3692

Summary:
Write a short summary of what your suggestion is about.
The 4 man rule, needs to be looked at especially in regards to the gang's. From previous experience, the rule is very restricting especially for gang members. I think, if crime is deemed upon you, for example someone initiates a shootout with you your boys should be able to come and help you and not have to just sit there and listen/watch you get taken away/shot. However, i think that the rule if people are planning a bank, or hunting people should apply. And if 4 people are already on scene of the incident, it should apply. 

Reason:
Why would your suggestion be a good addition to Legacy?
It will make roleplay the priority and not rules the priority. It is also very difficult to constantly have to make sure you're not breaking it.

**Comment by InZidiuZ** [comment]
Not a framework suggestion.
