### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#716]
**Reporter:**
Who is reporting this? iGreatWhite#8870

**Summary:**
When trying to spawn in at Lesbos Lane 2. I get a loading screen that never finishes

**Steps to Reproduce:**
IDK

**Expected Results:**
What are the expected results?
no loading screen

**Actual Results:**
What are the actual results?
stupid loading screen

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://imgur.com/qnB4PK7

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Clear your cache & verify the integrity of your GTA game files. Try reinstalling GTA/FiveM if that doesn't work. If that doesn't work either, try leaving your previous identity behind, move to a new country, get a new PC, and see if that solves the issue.
