### ISSUE TITLE
[jobs/ems] More patients in ambulances

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#721]
**Name:**
Who is suggesting this? Please include discord name.
Guardian3-1 #6969
**Summary:**
Write a short summary of what your suggestion is about.
Increase the number of patients ems can put inside an ambulance with /suspect in to atleast two.
**Reason:**
Why would your suggestion be a good addition to Legacy?
This would provide ems the opportunity to take more patients to pillbox efficiently and provide a better. In gang wars situation it would give ems a chance of getting patients more efficiently

**Comment by InZidiuZ** [comment]
This has since been done. If I'm wrong, please create another issue.
