### ISSUE TITLE
Gunfights/Oxy

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#722]
**Name:**
Cricketx818

**Summary:**
1) I think adding something such as "Headshots" to not be an instant death would be cool, I think all gunfights should last like maybe over 30 seconds since everything melts down your health. I guess reducing weapon damage would help? Not to sure.

2) Oxy should stop bleeding instantly, and give you a little health also, Maybe fix head injuries so it can be worth something out in the streets since its kinda priceless right now.

**Reason:**
Gang/Pd fights will be more of a balanced level so people just don't get melted instantly.

**Comment by KiwiUK** [comment]
PHAT +1 like if you’re shot in the head you might fall to the ground but not die.

**Comment by KPNutz** [comment]
If you get shot in the head, you should be knocked unconscious at a minimum. I’m not a fan of changing that.

**Comment by KiwiUK** [comment]
I understand it might be realistic but you also have to take into consideration that gun fights should be enjoyable not something that lasts 3 seconds. A lot of role players have come from a pvp back ground and spend most of their time role playing so it would be good to see a more detailed damage system to improve gun fights.

**Comment by InZidiuZ** [comment]
When was the last time you were in a gunfight? 🤔 Headshots haven't been an instant kill for weeks now...

**Comment by Cricketx818** [comment]
Really? I shot somebody in the head like 3 days ago and they died? Maybe they didnt have armor or something. how about he oxy :P

**Comment by InZidiuZ** [comment]
The health-loss amount when shot in the head is the same as normal body damage. Oxy won't be changed either. You said it was 'priceless', which means very expensive, guessing you meant the opposite? 🤔 It still has a good use though, so not really.
