### ISSUE TITLE
[game/players] Ability to take cash on /steal

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#723]
**Name:**
Who is suggesting this?
DegenTheo#2209

**Summary:**
When cuffing someone and robbing them with /steal, you should be able to steal the cash that they are carrying

**Reason:**
Since you need a good rp reason to rob someone now and people down get robbed as often, I think that you should be able to steal cash, There is currently not really any risk to carrying cash, since you can’t really get it stolen right now

**Comment by KPNutz** [comment]
Only issue is some transactions (ridiculously) require cash. Imagine being ambushed between legion bank and PDM.

**Comment by DegenTheo** [comment]
You are able to use your bank to buy PDM cars right? I thought they made it like that

**Comment by KPNutz** [comment]
Ahh perhaps. I’ve not bought a car in a while

**Comment by DrHenny** [comment]
Add this or make cash an actual item :)

**Comment by twooot** [comment]
I think this could get abused way to easily.
