### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LilMags** [InZidiuZ/op-framework-issue-tracker#724]
**Name:**
Who is suggesting this? Please include discord name.

Magzify #2425

**Summary:**
Write a short summary of what your suggestion is about.

Adding the option for Peds to change clothes 

**Reason:**
Why would your suggestion be a good addition to Legacy?

I and many other people play characters which are peds, now, commuting crime with these peds suck as you cannot apply a mask due to being locked to certain clothing and every time you get a warrant or a bolo. I don’t know if this is in the works already, but would be nice if peds could put masks on.

**Comment by KiwiUK** [comment]
Pedestrian models already have the option to do this, it’s whether you particular model has different clothing styles.

**Comment by InZidiuZ** [comment]
Hey,

There's a native limit on how many clothe variants the default peds have. If you wish to be able to use a mask, choose one that has that option, or alternatively use a freemode model.

**InZidiuZ**
*OP-FW Developer*
