### ISSUE TITLE
[game/inventory] Item Icon change, Joint/Lockpick

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#725]
**Name:**
DegenTheo#2209

**Summary:**
A few icon changes for weed and lockpick since i think these look a bit better

![joint](https://user-images.githubusercontent.com/45525477/70233411-c8b6a880-175e-11ea-89df-527e28dd9839.png)

![lockpick](https://user-images.githubusercontent.com/45525477/70233412-c8b6a880-175e-11ea-868f-eae08f783b02.png)

**Comment by InZidiuZ** [comment]
Do you have the original pictures?

**Comment by InZidiuZ** [comment]
Hey,

Closing due to no response.

**InZidiuZ**
*OP-FW Developer*
