### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LilMags** [InZidiuZ/op-framework-issue-tracker#727]
**Name:**
Who is suggesting this? Please include discord name.

Magzify #2425

**Summary:**
Write a short summary of what your suggestion is about.

Regarding jailing and times + fines

**Reason:**
Why would your suggestion be a good addition to Legacy?

Getting 150+ mins in prison is very boring especially seeming it’s a concrete box. Say it’s a Saturday night, that’s your night gone. TBH i think they shouldn’t be able to jail above 150 months.

**Comment by DrHenny** [comment]
I concur heavily. However, it is RP.. I would like to see him add an actual prison that you can break out of. It would balance it out.

**Comment by AdeptCL** [comment]
Not even necessarily break out of. A new prison system - which I think is already in the works - that adds to Prison RP.

**Comment by InZidiuZ** [comment]
Hey,

This issue would not be resolved by setting framework limitations, instead this could be discussed with the community and/or the actual police department itself.

**InZidiuZ**
*OP-FW Developer*
