### ISSUE TITLE
[properties/properties] Add backdoor to Lake Vinewood Estates 4

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#728]
**Reporter:**
Who is reporting this? Please include the discord name and your steam profile.
KaiEagle🦅#6969
**Summary:**
Write a short summary of what you're experiencing.
As there is no back door in Lake Vinewood Estates 4 we can't access the backside of the mansion.
**Steps to Reproduce:**
Include what steps are needed in order to reproduce the issue.
Add a back door. :)
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![FiveM_GTAProcess_7E3TPvYetd](https://user-images.githubusercontent.com/29286961/70407107-0706dd00-1a69-11ea-9b3b-d098e167c3a6.jpg)
![FiveM_GTAProcess_8dVxOfXbyb](https://user-images.githubusercontent.com/29286961/70407128-125a0880-1a69-11ea-88c9-c47778cdb0bc.jpg)

**Game Resolution:**
What is your game's resolution?
1920x1080

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India
**Notes:**
For anything else noteworthy.
![giphy](https://user-images.githubusercontent.com/29286961/70407157-2f8ed700-1a69-11ea-91b3-38da4ed9a8d7.gif)

**Comment by pxyeb** [comment]
A door in the back has been added. It will be accessible in this place: https://i.imgur.com/fi2daLs.jpg

**Pxyeb**
**OP-FW Helper*
