### ISSUE TITLE
Transporter Job No box found

### ISSUE THREAD

**Issue by gameshots1** [InZidiuZ/op-framework-issue-tracker#729]
Hey was just trying to check out transporter job, but cannot see the box when I reached the destination seems to be some bug.

**Comment by AdeptCL** [comment]
If you want this to be a bug report, at least provide some further info: screenshots, video, game info, etc.

You haven't followed the template either.

**Comment by SATIN187** [comment]
Did you open the back of the truck and walking there?

**Comment by InZidiuZ** [comment]
Hey,

Please use the available templates.

**InZidiuZ**
*OP-FW Developer*
