### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DeviLPunisheR** [InZidiuZ/op-framework-issue-tracker#730]
**Reporter:**
Discord:- Fuk_Fuk_Fukrey#9763
Steam:-  https://steamcommunity.com/id/Fuk_Fuk_Fukery/

**Summary:**
I bought a Car For PDM by mistake, I saved It on in my Garage Now its changed into another Truck which I never bought can I get my original car back.
https://youtu.be/8a8s_QBh0iA

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
My original car should be in garage 

**Actual Results:**
A truck which I didn't bought

## Additional Information

**Screenshots:**
https://imgur.com/qj81Zir ,  
https://imgur.com/DEVQAJ6 

**Game Resolution:**
1920X1080 (Full screen)

**Player Data:**
Name:- DeviL PunisheR
Citizen Id:- 36713
**Server:**
Legacy India

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
