### ISSUE TITLE
My suggestion is that the Pacific Standard Bank should be robbable and the requirements for that should be 8 thermites and 6 police officers and effect will be that there can be huge code red scene and people can get high money

### ISSUE THREAD

**Issue by AGboi** [InZidiuZ/op-framework-issue-tracker#731]
**Name:**
AGboi#4227

**Summary:**
Write a short summary of what your suggestion is about.
Bank Robberies
**Reason:**
Why would your suggestion be a good addition to Legacy?
Because of huge robbery

**Comment by DrHenny** [comment]
It's a nice suggestion, however.. If this does get implemented I believe the 'bank cooldown timers' should be increased to at least 3hours.

**Comment by AGboi** [comment]
The cooldown of 3 hours should be only for Pacific standard and rest should be normal

**Comment by InZidiuZ** [comment]
Closing in favor of #647.
