### ISSUE TITLE
[assn: assets] Open bahama mamas!

### ISSUE THREAD

**Issue by DrHenny** [InZidiuZ/op-framework-issue-tracker#732]
**Name:**
Hennyways#0281

**Summary:**
I'd love to see bahama mamas open. Currently, you can NOT enter the building because the doors are locked.

**Reason:**
I would love to start hosting one of my events at this location, it has such a beautiful interior.

**Comment by AdeptCL** [comment]
+1. The Bahama Mamas has a more nightclub interior, so you can't really host parties at Tequi-la-la as it's more of a band/club type of venue.

**Comment by DrHenny** [comment]
bump

**Comment by DrHenny** [comment]
need blimp too pls ty

**Comment by Panda-XV** [comment]
big ole +1

**Comment by SoniMatt** [comment]
Much better looking than VU and Tequi La La, I really hope it gets "opened"

**Comment by InZidiuZ** [comment]
This has been done with 2.7. Please use the assets issue tracker for future inquiries regarding assets.
