### ISSUE TITLE
[illegal/robberies] Indicators for house robberies

### ISSUE THREAD

**Issue by DrHenny** [InZidiuZ/op-framework-issue-tracker#733]
**Name:**
Hennyways#0281

**Summary:**
I'd like to see some kind of arrow indicator of the location you have to stand in order to lockpick the house. Or some kind of command or hotkey to actually start robbing in the house.

**Reason:**
It's annoying constantly searching for the right spot, it's different on every door, some houses I can never find the perfect spot and others are instant.

**Comment by SATIN187** [comment]
from my understanding its not that youre not in the right spot theres like a 15 second cool down from the time you get out of the house till you can lock pick the next

**Comment by InZidiuZ** [comment]
> from my understanding its not that youre not in the right spot theres like a 15 second cool down from the time you get out of the house till you can lock pick the next

This is most likely it in this case.

Once the burglary system is rewritten (which it is set to be), I'll most likely be taking advantage of more base-game functionality to automatically position your player where it should be when using a lockpick.
