### ISSUE TITLE
2 min break after a person leaves the city

### ISSUE THREAD

**Issue by AGboi** [InZidiuZ/op-framework-issue-tracker#734]
**Name:**
Who is suggesting this? Please include discord name.
AGboi#4227
**Summary:**
Write a short summary of what your suggestion is about.
This suggestion helps the people who got their game crash or internet problem and they have to rejoin and have to stand in long queue there should be 2 mins break after the person leaves so that the left person can join again and he/she does not have to stand in long queue
**Reason:**
Why would your suggestion be a good addition to Legacy?
This will help the people who don't have a priority

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being. If you're having issues with game crashes, try to get them resolved instead.

**InZidiuZ**
*OP-FW Developer*
