### ISSUE TITLE
Suggestion: Job outfits to start work on standard jobs (Garbage Collector)

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/op-framework-issue-tracker#735]
**Name:**
-In game: Johnny Flame
-Discord: Johnny2s#5991

**Summary:**
I believe for standard jobs (at least for Garbage Collectors), you should have to get ready for work to start hours. For Garbage Collector, I would have to get changed at my house/apt or at a clothes store or else if I tried to start up hours at garbage HQ, it would state that I need to "get changed for work". Basically you can't show up to collect garbage in a tuxedo or some other non-garbage apparel.

**Reason:**
This would increase roll roleplay all around for standard jobs because at least people will have to get ready for work and look legit, currently there's no incentive besides just farming for materials. I've only met 2 people that were actually RPing garbage collecting like myself, have seen 10+ not even engage or attempt to act like a garbage man.

**Comment by DaSkeeT** [comment]
Forgot to mention: a command like /joboutfit at the house, apartment, or clothes store to get dressed for work. There's either a set preset uniform or can choose from a few when customizing in the apparel store.

**Comment by DaSkeeT** [comment]
Attached is an example of my garbage collector uniform. I think this and maybe another 1-2 to choose from when starting the job, would suffice for adequate outfits for garbage.

![garbage-uniform](https://user-images.githubusercontent.com/58045478/70855127-087e3e00-1e8b-11ea-887e-a8b85d71765e.jpg)

**Comment by Karpenkooo** [comment]
Not gonna lie I really like this idea! However, I see that as more of a Roleplay issue with the majority of players that do garbage runs inexpensive outfits.

**Comment by DaSkeeT** [comment]
Agree. However if you show up to HQ and try to start the job when not in uniform, there will be a notice that you must "get changed for work" to clock in. That way you have to get dressed at the house/apt or a clothing store. Believe it will influence more RP within garbage as the only people that truly follow through currently, are roughly about 2-3 that I've also seen in some type of uniform. I know it's still a standard job and not police/ems/etc, but am just trying to move a bit more towards the RP role of cleaning up the city.

**Comment by Karpenkooo** [comment]
Yeah, I agree that something has to be done about it though. It does look pretty ridiculous.

**Comment by DaSkeeT** [comment]
Yeah, not a lot of RP most of the time. Hopefully something comes of this, RP would benefit heavily with at least garbage collecting.

**Comment by InZidiuZ** [comment]
Hey,

This is not doable as all the player models available in the base game are usable, most of which does not have such clothes. It also won't change anyone's mindset by simply forcing a different outfit for a player. The only possibility would be forcing this for the two available models, but until later I won't do anything with this.

**InZidiuZ**
*OP-FW Developer*
