### ISSUE TITLE
[new][illegal/heist] Smuggle with yacht

### ISSUE THREAD

**Issue by NahianMikdad** [InZidiuZ/op-framework-issue-tracker#736]
**Name:**
Nahian

**Summary:**
Well, it's like smuggle. There would be a yacht every 6 hours(IRL Time) to take the smugglers (players) to another place on ocean and the journey must be longer than 10 mins, after the journey players get illegal stuffs as smuggleitems. There must be more than an amount of police and police must chase the yacht and try to warn/kill the smugglers (players) and smugglers (players) can shoot them as well to save themselve. (ref: https://www.youtube.com/watch?v=_Z2RFe0jp8k)

**Reason:**
Well, i feel like this can bring more fun and rp stuff in the server.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
