### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Arnob106** [InZidiuZ/op-framework-issue-tracker#737]
**Reporter:**
Arnob#8600
Steam : https://steamcommunity.com/id/arnobislam/home

**Summary:**
Block maintenance charge payment option is not showing 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/473560960536150036/655087014097453066/Screenshot_5.png
![Screenshot (5)](https://user-images.githubusercontent.com/58127905/70828897-86ecc880-1e16-11ea-88a3-b7a4fd31c6bd.png)

**Game Resolution:**
1400x900 (Full Screen)

**Player Data:**
Mr. Don 
Citizen ID: 49114
**Server:**
Bangladesh Legacy 

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Please properly use the template when filing an issue. If this is still an issue, please create a new issue with the appropriate information.

**InZidiuZ**
*OP-FW Developer*
