### ISSUE TITLE
Pay Fixes for EMS

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#738]
**Name:**
Duroode#2178

**Summary:**
Theres alot of EMS Positions where you dont get paid for having them.
EMT (Paid)
EMT Advanced (Unpaid)
Paramedic (Paid)
Lead Paramedic (Unpaid)
Specialist (Unpaid)
Sergeant (Paid)
lieutenant (Paid)
Captain (Paid)
Assistant Director (Paid)
Deputy Director (Paid)
Chief Director (Paid)
There are Currently 3 Positions Within the EMS where you dont receive Pay. When you get Paramedic you dont get another pay upgrade until you get Sergeant. and have to keep your job listed as Paramedic in order to still Receive pay for doing the job.

**Reason:**
This would Allow us to Give the EMS within those positions to get the correct pay for earning their Job and place in the EMS

**Comment by ZurxeyH** [comment]
+1 Recently joining the EMS Team I have realized this is a major issue.

**Comment by InZidiuZ** [comment]
Hey,

Please recreate or reopen this issue once the servers starts receiving updates to the live server again.

**InZidiuZ**
*OP-FW Developer*
