### ISSUE TITLE
[game/inventory] Stores for items and such

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#739]
**Name:**
Who is suggesting this? iGreatWhite#0001

**Summary:**
Write a short summary of what your suggestion is about.
SASP and EMS Stores
SASP Store:
Body Armor - $750
Handcuffs - $350
Diving Tanks - $250
Etc. (Maybe Stun Guns, Batons and other pistols)
[Remove commands for cuffs and make it so police can escort soft cuffs]
Makings this so cops have to have cuffs on them to rob. Cops don't have infinite handcuffs IRL.
[Remove Heavy Pistol from stores and make it exclusive to police at this store]

EMS Store
[These Items I know for sure aren't in legacy but to give examples of things that could be sold]
Medkits [Heal all bleeding and full health]
Ibuprofen [Some type of medicine to heal injuries legitimately] 
Etc. (Fire Extinguishers, cant think of other things)

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would change the way cops do certain things and possibly give them an edge in situations. Where they can buy 3 to 4 body armors and stay in a fight longer. Medkits allowing the police and such to once again stay in a fight longer. these items can ultimately be able to rob by criminals so they can also get the same edge the other side has.

**Comment by Brundoggy** [comment]
+1 would LOVE to see something like that, so we dont have to clock in and out in order to refresh armor, plus we can carry some more while out on duty.

**Comment by AdeptCL** [comment]
From the EMS side of stuff, this would be perfect.
I do really like the Ibuprofen idea as a legitimacy to Oxy. The only thing I can think of which would cause conflict is how you balance the idea of people just constantly coming for Ibuprofen instead of also keeping the market/opportunity for people to sell/gain Oxy from the runs.

**Comment by InZidiuZ** [comment]
This has since been done.
