### ISSUE TITLE
Forum Drive Apartments - No personal garage

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#740]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Zurxey#2607
**Summary:**
Write a short summary of what you're experiencing.
Basically I purchased Forum Dr. Apt. Complex G (7) and the homes do not have personal garages. I understand that there is a garage right around the corner, but it should have it's own garage for customers. There is an entire back street off this apartment, and the others, they should all have personal garages :) 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Purchase the block, look for garage doesn't exist.
**Expected Results:**
What are the expected results?
There should be a garage icon (red triangle) showing where to park cars, and retrieve
**Actual Results:**
What are the actual results?
There is no icon showing this, neither out front nor back. 
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 6122 - Job Data: Mechanic, Los Santos Customs, Tow Driver
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**
For anything else noteworthy.

**Comment by rachitkataria13** [comment]
@ZurxeyH see  #710 Please close the issue thank you.

**Comment by ZurxeyH** [comment]
> 
> 
> @ZurxeyH see #710 Please close the issue thank you.

I think i'll keep it open for the moment, it is using the correct format.
