### ISSUE TITLE
[vehicles/damage] Suggestion

### ISSUE THREAD

**Issue by LilMags** [InZidiuZ/op-framework-issue-tracker#741]
**Name:**
Who is suggesting this? Please include discord name.

Magzify #2425

**Summary:**
Write a short summary of what your suggestion is about.

Cars dying to gun shootings

**Reason:**
Why would your suggestion be a good addition to Legacy?

When i watch N* i see them having fun shootouts, with drive-by’s and what not and their cars can withstand it. I understand it’s ‘unrealistic my but it’s more ‘fun’ and gets rid of ‘let’s just disable the car, then shoot them on foot’.

**Comment by InZidiuZ** [comment]
Hey,

This should no longer be an issue with the revamped damage system. Overall vehicles will tolerate more damage, and weapons will have different damage-multipliers to optimize the realistic capabilities of weapons.

**InZidiuZ**
*OP-FW Developer*
