### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pandaError404** [InZidiuZ/op-framework-issue-tracker#743]
My Name is Manasvi Vartak. Error 404#7916 and https://steamcommunity.com/id/manasvivartak/.

Ambulance /suspect in bug

When any ems team do /suspect in near ambulance if any vehicle present near ambulance the suspect/patient will directly went into nearest vehicle.  

result should be suspect/patient has to inside ambulance not into nearest vehicle 

results are suspect/patient going into nearest vehicle 

game resolution is 1080p
/info ID 61251
India

this is serious issue because sometimes its a suspect situation. and role play just mess up because of this bug.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
