### ISSUE TITLE
[new][illegal/yacht] Yacht with Class 2's

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-issue-tracker#745]
**Name:**
Cricketx818

**Summary:**

This suggestions came to my mind randomly, Since we currently are stacked with weapons and it takes ZERO effort on getting them, What if we changed up the way you get it.
How?
We can still keep lester's house the way it currently is, & not change anything from that, but change up the way the crate spawns, instead of spawning them at the docks, it spawns at the big Yacht, the only way to get it is going to be with 4 people.
Why 4 people?
That's the crim activity rule but have the Yacht CODE RED by AI's that have ar's and shoot to kill if you are nearby.You must kill all AI's to get accesses to the crate to drill out the weapon. I feel like it will be MORE entertainment then just going & doing it with any any cops getting alerted. So its pretty much a heist to get class 2's and they are worth something on the street since you have to use "Armor, and risk yourself not to go to jail"

**Reason:**
Create more roleplay for class 2's & value to the weapons since they are worth literally nothing currently.

**Comment by TwoplePop** [comment]
This sounds amazing so there's actually risk and that new people won't be seen with class 2s on there 2nd day. def +1

**Comment by TwoplePop** [comment]
or maybe like the oil fields workhouse could be another crate location along with yacht.

**Comment by Livius99** [comment]
that would be amazing!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
