### ISSUE TITLE
Hacking Keys Used in right order but the 2nd Hack part did not come up. [Bug report]

### ISSUE THREAD

**Issue by FearTheShadow** [InZidiuZ/op-framework-issue-tracker#746]
**Reporter:**
Discord Name- ๖ۣۜζ͜͡FearTheShadow#6579 Steam ID - https://steamcommunity.com/id/feartheshad0w/

**Summary:**
Hello Sir,
In Weapon-Heist the hacking giving wrong info i guess,like even if we are giving the right key its saying WRONG KEY, also lost 6 of my keys because the 2nd hack part did not come,i gave the keys it did not even say correct key or wrong the keys were gone. We lost 12 keys tonight,It is so hard to collect keys,its sad when it goes all gone.

**Steps to Reproduce:**
One time one failed the hack then the other one went to do the hack,whenever its saying to give the keys we give but its doesnt say right key or wrong key. But the key gets dissapear and we dont get the 2nd Hack option, it happend 2 times back to back. Then we changed server and went to do that again then we have the correct order of keys but it was saying WRONG KEY, and we lost the keys also there. But the keys were right.
**Expected Results:**
As always we give keys then it says correct keys then the 2nd hack comes up, but it did not come up but we lost the keys.

**Actual Results:**
We gave the keys ,followed the order but did not happen anything no 2nd hack part came.

## Additional Information

**Screenshots:**
I think my friend has the screenshot or the video clip i guess,but i am not sure.

**Game Resolution:**
1920*1080

**Player Data:**
52083

**Server:**
Legacy Roleplay Bangladesh

**Notes:**
I don;t know.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
