### ISSUE TITLE
Air One Lock On Bug

### ISSUE THREAD

**Issue by TwoplePop** [InZidiuZ/op-framework-issue-tracker#748]
**Reporter:**
Dean Hunt | TwoplePop#7989

**Summary:**
After a bank, Air one locked on to my voltic and it caused it to be undriveable completely. I couldn't turn or control my acceleration.

**Steps to Reproduce:**
Use Air One lock on while chasing a vehicle. I had an electric car but it could be any car. The spotlight could have also been activated but I'm not sure.

**Expected Results:**
For Air One lock on to lock on to my vehicle without my perspective going berserk.

**Actual Results:**
As air one locks on, my FOV zooms in and my car goes uncontrollable. I'm not able to steer or control acceleration.

## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
Dean Hunt 3125 ... I don't know the rest currently since my internet is cut but I'll try to update it soon.

**Server:**
Main

**Notes:**

https://drive.google.com/open?id=1uQIKJ0zrfIujsvsyUrZaxFsq9CH0AAzo

Getting locked on by air one should probably be fixed soon. The pilot claimed there wasnt lock on but after my 46 days of playtime, thats never happened to me unless air one locks on.

**Comment by TwoplePop** [comment]
I reposted to this github after posting it to the wrong one yesterday.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
