### ISSUE TITLE
[vehicles/garages] Attempt to automatically delete *NPC* vehicles if in the way.

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/op-framework-issue-tracker#749]
Reporter:
-In game name: Johnny Flame
-Discord: Johnny2s#5991

Summary:
The Roy Lowenstein Boulevard apartments garage bugs out when a local parks their vehicle next to the "garage spot". Basically have to wait until the local leaves, hopefully the "garage spot" can be made smaller so it doesn't detect a vehicle in the next parking spot.

**Steps to Reproduce:**
Have a local or player park their vehicle on the spot next to the "garage spot". It will display the message to clear the garage and won't spawn your vehicle.

## Additional Information

**Screenshots:**
![1](https://user-images.githubusercontent.com/58045478/71327199-2e2ec700-24cb-11ea-8c4f-dae82e389881.jpg)
![2](https://user-images.githubusercontent.com/58045478/71327200-2e2ec700-24cb-11ea-8124-a105edbbeace.jpg)
![3](https://user-images.githubusercontent.com/58045478/71327415-cd54be00-24cd-11ea-94f3-ad509d83e2e2.jpg)

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 11187 - Job Data: Government, Waste Collector, Employee, Timestamp: 2019-12-22 22:08:59

**Server:**
Main EU/NA 1-2

**Comment by InZidiuZ** [comment]
Hey,

This will no longer be an issue with Beta.

**InZidiuZ**
*OP-FW Developer*
