### ISSUE TITLE
[properties/properties] Shared house garages

### ISSUE THREAD

**Issue by zombiecidec02** [InZidiuZ/op-framework-issue-tracker#750]
Zeus/Josh Black
Zombiecide#6524

Sharing House Garages

So this may have been asked before but...I feel like that the level 1 keys have the right feature of people can come over to a house and use it to store items, but with the level 2 key Its all well and good having someone able to wake up at the house, but with out having there vehicles stored there, it's a pointless key to have, as then they would have to run to a nearby local garage to collect there car, why not have it so that if they have the ability to wake up at a house then have there cars stored there too, it also helps RP if you have In character relationships and family

**Comment by T-52Chris** [comment]
+ From me [T-52] Chris. Totaly agree,even if this was posted a long time ago.

**Comment by InZidiuZ** [comment]
Hey,

This became a thing with 2.4.

**InZidiuZ**
*OP-FW Developer*
