### ISSUE TITLE
Character Bug Not Able to Sell Cocaine, Inventory Bug, no materials while doing Garbage and Chopshop Job

### ISSUE THREAD

**Issue by nimai786** [InZidiuZ/op-framework-issue-tracker#751]
Discord Id; N.AWorld#6739
Steam Profile: https://steamcommunity.com/profiles/76561198826748341/

Character Bugs:
Character Name: New Knockout
1. Not able to sell cocaine and weed from a particular character.
2. Inventory Bug cocaine Bags automatically changes to weed bags & items gets vanished.
3. Getting no materials while doing Garbage Job, house robbery and Car chopshop. sometimes no cash for the garbage job.

when i do the same jobs and work from another character it works properly.
![Bugged Character](https://user-images.githubusercontent.com/594692/71338515-37c13900-2576-11ea-91be-8b3448b3299e.JPG)

**Comment by InZidiuZ** [comment]
Hey,

Please use the available templates.

**InZidiuZ**
*OP-FW Developer*
