### ISSUE TITLE
Bug report [ Exploded car in chop shop radio]

### ISSUE THREAD

**Issue by humayunraza1** [InZidiuZ/op-framework-issue-tracker#752]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Azzy#6584
https://steamcommunity.com/id/azzy5

**Summary:**
Write a short summary of what you're experiencing.
I was doing chop shop and it gave a car which was exploded. I got a tow truck and successfully towed it and took it to the chop shop but i was unable to sit in it thus failed to deliver.

**Steps to Reproduce:**
Either make it not give exploded cars or make a new command which doesnt require player to sit in the car.

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://imgur.com/gallery/nBjZq7J

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
CID: 29808
Name: Azzy Banks
Job: Mechanic
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India
**Notes:**
For anything else noteworthy.
-

**Comment by LilMags** [comment]
You’ll probably find someone just ended up not being able to tow/lockpick the vehicle and due to that, blew it up so nobody else could get it. That’s my best guess.

**Comment by humayunraza1** [comment]
> You’ll probably find someone just ended up not being able to tow/lockpick the vehicle and due to that, blew it up so nobody else could get it. That’s my best guess.

could be but this wasnt the first time tbh, got an exploded before but i was able to sit in after spamming F but in this car i wasnt ... :(

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
