### ISSUE TITLE
[properties/properties] Missing backdoor on Didilon Drive 6

### ISSUE THREAD

**Issue by balaarjun** [InZidiuZ/op-framework-issue-tracker#753]
**Reporter:**
AntiqueBaba

**Summary:**
My Mansion in didilon drive (Didilon Drive 6)) does not have back door to the swimming pool

**Screenshots:**

Video Link
https://youtu.be/Vq6nGChPIKU

**Comment by pxyeb** [comment]
Door in the back has been added. It will be accessible from the big left window-panes.

**Pxyeb**
*OP-FW Helper*
