### ISSUE TITLE
[UI Bug] SASP Radar Front Lock Bug

### ISSUE THREAD

**Issue by SaRsHYT** [InZidiuZ/op-framework-issue-tracker#754]
# Legacy UI Bug Report
SaRsH#8631 | https://steamcommunity.com/id/sarsh_07)

**Summary:**
The Front Lock of Radar in the SASP Vehicle doesn't show up, in some resolutions like 1366x768,  
I tried lowering my resolution to 1280x1024, so the screen was stretched and the Front Lock was visible to me, but the game was looking Crappy AF

**Steps to Reproduce:**
You can resize the size of the RADAR so that the Front Lock will be visible to the users with the 1366x768 resolutions

**Expected Results:**
The Radar will be adjusted and the Front Lock will be seen 

**Actual Results:**
Front Lock isn't visible, the radar hides it behind it self

## Additional Information

**Screenshots:**
1.https://cdn.discordapp.com/attachments/647263764256653342/659648558781169685/0_20191222204400_1.png
2. https://media.discordapp.net/attachments/647263764256653342/659648560828121088/0_20191222204357_1.png?width=841&height=473

**Game Resolution:**
1366*768

**Notes:**
Back Lock is also off, If you turn it on it would be an honor

**Comment by LilMags** [comment]
Not being a dick, but pretty much everyone plays on 1920

**Comment by Anderzenn** [comment]
> Not being a dick, but pretty much everyone plays on 1920

Only comment if you have anything useful to say.

**Comment by InZidiuZ** [comment]
Hey,

See #622 for further information.

**InZidiuZ**
*OP-FW Developer*
