### ISSUE TITLE
when doing to house robbery if you check time in phone it will show 22:00 and it will not go ahead when we come out of house 

### ISSUE THREAD

**Issue by CaptSpider4** [InZidiuZ/op-framework-issue-tracker#755]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by Anderzenn** [comment]
This is intentional, see #618 

**Anderzenn**
*OP-FW UI Developer*

**Comment by InZidiuZ** [comment]
*Would like to add that the server-time is still stored locally, so when the new phone comes, the time will be displayed correctly.
