### ISSUE TITLE
Suggestions and new feature which should make RP more real

### ISSUE THREAD

**Issue by demisedemon** [InZidiuZ/op-framework-issue-tracker#756]
Should add more jobs in the jobs section like fueler, Miner and remove old non-functional jobs from the roster. Jobs should only be provided only after getting a citizen ID card. Then the person has to get police clarification from the police dept. for a clean chit. After that, he or she will be able to do jobs.
More pointers - 
1. Remove storage things from the game in cars to make it more challenging.
2. There should be a min. 1 police, mechanic, doctor or PDM must present at each city. (Go recruit)
3. Taxi jobs should include getting rides from NPCs
4. Journalist jobs should be more focused on journalism and should be a two-man job with cameraman and reporter.
5. the payout of the job should be provided only after completing the job mission.
6. not everyone should be able to purchase firearms even after buying a license. need to submit and clarify the reason for one. (it will reduce the looting of cars on roads and using taxi more.)
7. If a person found having a job and not doing it, he or she should be fired and will have to face some problem in getting a new job.
8. Add property dealers also in the city and a job like PDM
9. If we can add some hobbies from the game also that will work like - arm wrestling, tennis, golf, etc. or gym maybe.
10. Can we provide skills also in-game like the original game has for driving etc?
11. Can we have more camera adjustments?

It will be awesome if some of these features get in the RP.

**Comment by InZidiuZ** [comment]
Hey,

Please create an issue for each individual suggestion.

**InZIdiuZ**
*OP-FW Developer*
