### ISSUE TITLE
[jobs/police] New cuffing suggestion 

### ISSUE THREAD

**Issue by EVILKTM** [InZidiuZ/op-framework-issue-tracker#757]
Jaxon Cole - KTM#0661
Who is suggesting this? Please include discord name.

so basically a new cuffing system would be cool and it would make things a lot easier for cops in cells. So pretty much you have to hard cuff someone to escort someone and when you put them in the cell you have to put them just the right way to uncuff them so i think it would be cool if when you uncuff people you dont do any animation and you just uncuff them. Also when you hard cuff someone instead of you going to there back they go right in front of you and when they are handcuffed you can put them in soft cuffs with out doing any animation so you can just go to hard cuff straight to soft cuff.  and when you get cuffed there should be a little thing on the top right that says Cuffed! also i would be cool if we could get hot keys for cuffing people and to escort people and to put people in cars and to take them out of cars. also for the hotkeys you could make them like the arrow keys on your key board like up arrow is hard cuff down arrow is soft cuff and left arrow is to put someone in a car and to take someone out of the car and right arrow is to escort someone!!! 
Write a short summary of what your suggestion is about.

The reason it would be good for legacy is because when you cuff someone you go to there back and when a suspect is in the cells and they don't comply then you go into the cells with them and you where on the outside of the cells. It would also be better with the uncuffing system because it would be a lot easier and it wouldn't make us go to there cells bye accident and then the suspect can punch you or do anything like that. 
Why would your suggestion be a good addition to Legacy?

so for example the cuffing system like this video.
this is hard cuffing - https://clips.twitch.tv/PiliableBelovedNewtLitFam
this is soft cuffing **Make sure you watch to 4:07 to 4:30**  - https://www.youtube.com/watch?v=jotfIf8gSc8
This is uncuffing **Make sure you start at 9:25 to 9:34** - https://www.youtube.com/watch?v=jotfIf8gSc8

**Comment by Jaygo356** [comment]
+1

**Comment by Lankovich** [comment]
I dont think this would be better RP wise, if the suspect aint complying for example, he's providing RP, he creates a situation where we have to do something in general to get him in cuffs etc.

**Comment by twooot** [comment]
yeah, i think cuffing is good where it is rn
