### ISSUE TITLE
[vehicles/damage] Suggestion

### ISSUE THREAD

**Issue by LilMags** [InZidiuZ/op-framework-issue-tracker#758]
**Name:**
Who is suggesting this? Please include discord name.

Magzify #6969

**Summary:**
Write a short summary of what your suggestion is about.

Vehicle damage system

**Reason:**
Why would your suggestion be a good addition to Legacy?

Make cop chases and overall driving more interesting and ‘risky’

As of now, if you hit a tiny pole with your car, 9 times out of 10, it gets decently damaged, say to 70-80%. Now, i feel as though hitting small things shouldn’t damage your car as much, and when the crash is heavy enough it just disables the car and you feed to repair kit it. Because i’ve realised in cop chases break checks literally do nothing at all, 0. If anything, it actually helps the cops out ramming you in the rear end.

**Comment by InZidiuZ** [comment]
Hey,

The vehicle damage system has been revamped for beta, and this should no longer be an issue.

**InZidiuZ**
*OP-FW Developer*
