### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JustSayTitan** [InZidiuZ/op-framework-issue-tracker#759]
**Reporter:**
JustSayTitan#1381 / https://steamcommunity.com/profiles/76561198950440847/

**Summary:**
I just bought a car and someone else at the same time in the other server and I got the car from that server. I bought the grotto gt and got to drive it into the garage, as soon I wanted to pull it out again the Karin came out.

**Steps to Reproduce:**
Buy a car in another server at the same time.

**Expected Results:**
You will buy the car you want, or have in front of you.

**Actual Results:**
the car duplicates or it gets switched up, that much i'm not sure.

## Additional Information

**Screenshots:**
- https://gyazo.com/c9775bb5ab310e4d61d522bb9ea4b83a
- https://cdn.discordapp.com/attachments/660984047391997963/660991199972163607/Untitled.png

**Game Resolution:**
I've restarted Fivem but it is still saved up in my garage.

**Player Data:**
I have been told to contact Cricket and talk with him but I think this is more of a system error.

**Server:**
I'm in the normal server, the server that it happened was #2 with Id : 145.239.205.202:30121

**Notes:**
For anything else noteworthy.

**Comment by JustSayTitan** [comment]
I there anything else I could do about this, or the car because I actually never use it

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
