### ISSUE TITLE
Enable Rockstar Editor Feature

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#760]
**Name:**
Vishal Bhosale (Vishal#6256)

**Summary:**
We want Rockstar Editor in our legacy server so we can edit our roleplay seen and have more fun.. or see a movie and cinematic scene of our roleplay..

**Reason:**
it will help players to do more things and enjoy the situations they did in a game and content creators can make movies out of it.

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being.

**InZIdiuZ**
*OP-FW Developer*
