### ISSUE TITLE
New MLO Hospital Interior - Pillbox Hill

### ISSUE THREAD

**Issue by LikeConnorr** [InZidiuZ/op-framework-issue-tracker#764]
**Name:**
Con#9999 | Connor | S-203 C. Steel

**Summary:**
My initial suggestion is to add a new hospital interior. Interiors and maps are generally really expensive and costly for almost any FiveM server. For example, this one here is $1,500. https://www.youtube.com/watch?v=dlJ-4uKrVdU. It contains 47 rooms and 4 floors. Since then, another has been released, which is only a $30 monthly subscription for 1 premium interior a month. If Legacy would only purchase the hospital, the subscription can be immediately cancelled. The interior is used by NP. This is the interior:

https://www.youtube.com/watch?v=4B0f0GO2MYM
The interior contains offices, lobbies, wards, examination rooms, x-ray rooms, mri rooms, diagnosis rooms & more...

**Reason:**
Everyday in the medical department we're urging to teach more advanced medical knowledge for the roleplay and everyday medical needs. We all feel that with a new hospital we can deliver the roleplay in an appropriate setting. For now, I tend to complete surgeries and scans within the morgue. This would be an exciting feature for beta, and would finally bring a suprise to the server that aren't crosshairs ;). The hospital has appropriate locations for signing on-duty, signing on doctor-duty, checking into the hospital and exciting the city when permaing. It also has appropriate clothing editing locations. 

I hope you understand why this would be an amazing feature to bring LRP to the next level.

**Comment by AdeptCL** [comment]
I have to +1 this, both as a Crim character and EMS character.

When we have patients who come in with serious injuries, but treating them like a normal patient in the main ward area just doesn't seem right. Whereas having to rush them into an operation, and let them stay in an actual ICU would be awesome.

**Comment by stardome101** [comment]
Big +1 from me. We have more and more patients who require specialist treatment in different kinds of rooms. There is only so much you can do in the morgue of a hospital. We need MRIs, surgery rooms, an actual ICU and an X-Ray room, etc. It will be highly beneficial to the EMS RP as a whole.  

-Deputy Director, EMS.

**Comment by OrionSparkles** [comment]
+69 This has to happen.

-Sergeant EMS

**Comment by InZidiuZ** [comment]
Hey,

Please post this in the asset-related issue tracker.

**InZIdiuZ**
*OP-FW Developer*
