### ISSUE TITLE
Tatto remove plastic surgery

### ISSUE THREAD

**Issue by DewanMahide** [InZidiuZ/op-framework-issue-tracker#765]
Reporter:
Who is reporting this? Please include discord name. TerminatoR2#2260

Summary:
Write a summary of what you're experiencing.
There is no option to remove the tattoo from the tattoo shop. If plastic surgery is still not working by the commissioner.

Notes:
For anything else noteworthy.
Please fix this problem thank you

**Comment by InZidiuZ** [comment]
Hey,

Please use the available templates correctly.

**InZidiuZ**
*OP-FW Developer*
