### ISSUE TITLE
[jobs/fishing] Suggestion: More legal jobs (ex: fishing)

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/op-framework-issue-tracker#766]
**Name:**
-In game name: Johnny Flame
-Discord: Johnny2s#5991

**Summary:**
1. I believe there should be more legal jobs, as in fishing for example. Not sure if it's been suggested before, but it would be fun to go fishing along with scuba diving. Or just be able to fish legally and then have a "fish store" to turn into the fish for cash that goes straight into your bank account. I think it would be cool to have 2 spots to fish (1. dock to fish off of and and store to turn in nearby) and (2. spot to rent a fishing boat to take out in the water to a general designated fishing spot, then can take all fish back and turn into another store nearby).

2. Also, maybe have a part of the fishing that can be illegal? For example, another city I played in awhile back had different kinds of bait (ex: sea turtle bait to fish for sea turtles, that can be turned in a shady turn in spot that gives dirty money/cash back per turtle). Can expand on that where you can fish turtles for sharks for a bigger payout, but obviously more rare chance to catch.
There are a good amount of options just for fishing, that I believe would be fun for both legal and illegal parts.

**Reason:**
Increase legal jobs as there aren't that many, would be fun to fish and RP with others either on the dock or fishing boat.

Sample images:
![1](https://user-images.githubusercontent.com/58045478/71837730-b9d45600-307c-11ea-83e2-b6bd77f0868c.jpg)
![2](https://user-images.githubusercontent.com/58045478/71837734-bb9e1980-307c-11ea-8500-f38d584b5685.jpg)
![3](https://user-images.githubusercontent.com/58045478/71837736-bccf4680-307c-11ea-8231-51e6214f57de.jpg)
![4](https://user-images.githubusercontent.com/58045478/71837739-be007380-307c-11ea-90fb-a89aec4e3f58.jpg)

**Comment by kucej** [comment]
I like it. Perhaps add a boat shop and fishing boats you could buy - better the boat more chances to get rare fish.

**Comment by TwoplePop** [comment]
the better the fishing rod, the better the fish. The better the boat, the more people can fit on it(for rp reasons).

**Comment by TwoplePop** [comment]
I could only imagine 1 fishing boat though which is the tugboat

**Comment by DaSkeeT** [comment]
Yeah, seems tugboat is the only one that would prob work since it's already active in game. Thinking like a fishing dock that has a boat for rent, to sail out in the ocean and fish at a designated location? Also the boat can support multiple people so friends and can go fishing together?

Like the idea of different fishing poles to catch larger fish, that can be turned in for more money?

**Comment by frohsti** [comment]
i like all of this

**Comment by claymstehling** [comment]
hello! I would love to bring this back! I think it would be awesome to have this in the framework, and with hunting being added and with the Sushi Restaurant in the city I think it would be amazing for them as well to be able to have people bring them fish to cook and sell

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
