### ISSUE TITLE
Screen Shaking Badly

### ISSUE THREAD

**Issue by TonyStarkRP** [InZidiuZ/op-framework-issue-tracker#767]
**Reporter:**
Discord: IndianBoy712#3373
Steam: http://steamcommunity.com/id/indianboy712

**Summary:**
My screen is shaking as hell as some explosions are going on continuously around me. The problem is from yesterday. I tries restarting the game but it doesn't help. I tried to go to a hospital but that doesn't seem to work as well.

**Steps to Reproduce:**
Fix the BUG.

**Expected Results:**
My In-Game screen works normally as intended

**Actual Results:**
xxx-xxxx-xxxxx-xxxxxx-xxxx

## Additional Information

**BUG Video:**
https://www.dropbox.com/s/cp7uorbcyq1wb1i/2020-01-07%2008-55-02.mkv?dl=0

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 67814

**Server:**
India

**Notes:**
Please do fix this ASAP!

**Comment by Seferti** [comment]
If you look on the bottom left of your screen you will see your hunger/thirst bars, and their will be a red bar on the far right, that is your stress level which causes your screen to shake when it's high.

**Comment by TonyStarkRP** [comment]
That red bar is in middle. Sharing the video of my problem as well now. Please do have a look at it.

https://www.dropbox.com/s/cp7uorbcyq1wb1i/2020-01-07%2008-55-02.mkv?dl=0

**Comment by Seferti** [comment]
Yes. the red bar is your stress level, you can lower it by doing yoga, which is marked on the map, also you can smoke cigarettes/joints to relieve stress.

**Comment by TonyStarkRP** [comment]
> Yes. the red bar is your stress level, you can lower it by doing yoga, which is marked on the map, also you can smoke cigarettes/joints to relieve stress.

Thank you.
