### ISSUE TITLE
Cocaine Brick disappears every time I try to package cocaine

### ISSUE THREAD

**Issue by TonyStarkRP** [InZidiuZ/op-framework-issue-tracker#768]
**Reporter:**
Discord: IndianBoy712#3373
Steam: http://steamcommunity.com/id/indianboy712

**Summary:**
Whenever literally happened to me twice and only 2 times I tried to get the cocaine business running, I run upto the factory and try to get my cocaine bar converted into Package cocaine, my brick disappears from my inventory whenever the bar is completed and I receive an error stating that you do not have a cocaine bar in your inventory.

**Steps to Reproduce:**
FIX the glitch

**Expected Results:**
I get back my packaged cocaine

**Actual Results:**

## Additional Information
I also reported this issue at the same time when it happened using /report in-game.

**Screenshots:**

**Game Resolution:**
1920*1080

**Player Data:**
Character ID: 68035

**Server:**
India

**Notes:**
This happened to me for the second time.

**Comment by Livius99** [comment]
hmmm... weird, never happened to me or to the boys that do that with me...

**Comment by Livius99** [comment]
maybe you were instanced, idk.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue. Also please use the template correctly.

**InZidiuZ**
*OP-FW Developer*
