### ISSUE TITLE
WL DOJ jobs not giving paychecks - Bug report

### ISSUE THREAD

**Issue by AmateurProfessional** [InZidiuZ/op-framework-issue-tracker#769]
**Reporter:**
Amateur_Professional#7313
https://steamcommunity.com/id/Amateur_Professional/

**Summary:**
The jobs Attorney, District Attorney, and Judge are not paying out like they are supposed to. 

**Steps to Reproduce:**
/setjob [id] Government
/setdepartment [id] Law
/setposition [id] (Attorney/District Attorney/Judge)

**Expected Results:**
Expected to have the role when you /info, and receive paychecks regularly. 

**Actual Results:**
No paychecks are received, and ID cards to not display occupation. 

## Additional Information

**Screenshots:**
N/A

**Game Resolution:**
1920x1080

**Player Data:**
Server was skuffed during this bug report, unavailable. 

**Server:**
NA/EU Whitelist

**Notes:**
Tried this on multiple people including my own character, with no success in getting paid.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
