### ISSUE TITLE
Bugged arm while using radio, females.

### ISSUE THREAD

**Issue by Miliax** [InZidiuZ/op-framework-issue-tracker#770]
**Reporter:**
miliax#2530 
www.steamcommunity.com/id/miliax

**Summary:**
When i'm using the radio my arm looks weird, it's like my underarm goes through the upper part of my arm?.

**Steps to Reproduce:**
Make a female character, use your radio and you see that your arm is looking weird.

**Expected Results:**
To have a normal arm when using the radio.

**Actual Results:**
The results looks weird, it's like the underarm goes through the upper part of the arm a little bit. It's hard to explain, i have picture to show it.

## Additional Information

**Screenshots:**
https://cdn.discordapp.com/attachments/467778021974212609/665973672254767136/20200112183352_1.jpg

https://cdn.discordapp.com/attachments/467778021974212609/665973671042613248/20200112183343_1.jpg

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 18 - Sasp, Trooper First Class.

**Server:**
Main WL.

**Notes:**
Nope =)

![20200112183352_1](https://user-images.githubusercontent.com/51051445/72223064-80fc1b80-356b-11ea-8076-f079337394b6.jpg)
![20200112183343_1](https://user-images.githubusercontent.com/51051445/72223065-835e7580-356b-11ea-9802-5c85b8a010f8.jpg)

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
