### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/op-framework-issue-tracker#771]
**Reporter:**
Nemmesys#1235
https://steamcommunity.com/id/Nemmesys/
**Summary:**
I went at the warehouse to sell some materials and when I came out the key for my truck was totally different.

**Steps to Reproduce:**
Get into the warehouse with the key for the car in the inventory, sell the materials you have (scrap, alluminium etc) and when you get out (idk if it happens to everyone , happened the first time and only to me ) your key for the car has a whole different plate number so it cannot be used with the car.
**Expected Results:**
I was expecting to have my key in the inventory and to leave with the flatbed.

**Actual Results:**
The key had a whole different number.

## Additional Information

**Screenshots:**
https://imgur.com/a/XL28o5O

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 171- Job Data: Mechanic,Los Santos Customs,Tow Driver
Timestamp:2020-01-12 20:37:26

**Server:**
WL main
**Notes:**
nothing

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
