### ISSUE TITLE
Vehicle Glovebox and Trunk inventory disappearing after server restart

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#772]
Reporter:
Masik52#5834
https://steamcommunity.com/profiles/76561198397274352/home
Summary:
I had items stored in my flatbed's glovebox and trunk last night when I logged off and when I got back in the city today my vehicle inventory is empty.  The vehicle was stored so there is no way someone could have stolen the items from it. 

Steps to Reproduce:
Obtain items put in trunk of vehicle or glovebox store vehicle and wait for server restart.  Items went bye bye after restart. 

Expected Results:
I was expecting the items to be in my vehicle

Actual Results:
items were gone

Additional Information
Screenshots:

Game Resolution:
1920x1080

Player Data:
Character ID: 56 - Job Data: Mechanic, Los  Santos Customs, Tow Driver
Timestamp: 2020-01-12 21:32:35

Server:
WL main
Notes:
nothing

**Comment by Masik52** [comment]
I just logged  back into the city and the previous items I had in the glove box and trunk are back and what items I had in there at the time of opening this ticket are now gone.  I have no clue what is happening w/ the inventory.

**Comment by Livius99** [comment]
if you have your car out and log off / crash the items disappear to avoid getting them stolen while you're gone. you have to put the car in the garage and take it out again to see the items back

**Comment by InZidiuZ** [comment]
Hey,

Please use the available templates properly.

**InZidiuZ**
*OP-FW Developer*
