### ISSUE TITLE
[animations/emotes] Using radio while in Handcuffs

### ISSUE THREAD

**Issue by Seferti** [InZidiuZ/op-framework-issue-tracker#773]
**Name:**
seferti#6666

**Summary:**
Some people told me that you are able to use your radio in handcuffs, I feel as if this should be restricted and not be able to be done.

**Reason:**
It would prevent a lot of "powergaming" and "FailRP" that would happen with this, I am also pretty sure it does not do the radio animation in-game so no one would know you're doing it.

**Comment by TwoplePop** [comment]
Yep, can confirm. radio still on in a jail cell while cuffed. I was able to hear people but i tested and was also able to talk. this should be considered as powergaming and should be fixed soon

**Comment by TwoplePop** [comment]
radio should also be a physical item so pd are able to take it off you

**Comment by Livius99** [comment]
+1

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
