### ISSUE TITLE
Bug report: Vehicle keeps disappearing when exiting buildings (warehouse/motel/etc)

### ISSUE THREAD

**Issue by DaSkeeT** [InZidiuZ/op-framework-issue-tracker#774]
**Reporter:**
-Discord: Johnny2s#5991
-Steam: https://steamcommunity.com/id/johnny2s

**Summary:**
Whenever entering a building (warehouse/motel/etc) and leaving the building, almost every time my vehicle is gone. This never happened on the old pub servers so am wondering if it's something with the server side or my side. Once it happened outside the warehouse, however I could still see the vehicle. Upon trying to enter, my character's animation would freeze after opening the door. Someone near my asked if I was trying to get in my car, because he couldn't see it with his eyes. This happens almost always and have a good computer so don't believe it's that (graphics turned up/etc). It seems to only not happen when someone else stays outside by the vehicle.

**Steps to Reproduce:**
Drive up and park outside of the warehouse or motel, then enter. Upon leaving to go back outside, the vehicle is almost always missing.

**Expected Results:**
Vehicle remains in the same spot upon parking it.

**Actual Results:**
Vehicle disappears and have to retrieve from a garage.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
-Character ID: 76
-Job data: Government, Waste Collector, Employee
-Timestamp: 2020-01-13 18:36:57

**Server:**
EU/NA Whitelist

**Notes:**
This rarely happened when the server was public (32 slot).

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
