### ISSUE TITLE
Lost MC Repairs are appearing from time to time on the Roof of the clubhouse

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#775]
**Reporter:**
Bob Hess  - Nohbob#1028 - https://steamcommunity.com/id/nohbob/

**Summary:**
When repairing at the Lost MC Mechanics, sometimes the repaired car spawns on the Roof. 

**Steps to Reproduce:**
1. Take Damaged Car to Garage 4 
2. Repair
3. From time to time, will respawn on Roof instead of floor. 
When repairing at the Lost MC Mechanics, sometimes the repaired car spawns on the Roof. 

**Expected Results:**
Does not spawn on roof, respawns in Garage

**Actual Results:**
Sometimes spawns on Roof. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
