### ISSUE TITLE
Chop - Sometimes cars don't spawn near or at locations

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#776]
**Reporter:**
Bob Hess - Nohbob#1028 - https://steamcommunity.com/id/nohbob/

**Summary:**
There are a number of locations that do not appear to spawn the correct car for the shop.

**Steps to Reproduce:**
1.  Own Radio
2.  Listen Annoucement
3.  Try to locate car.  For instance Strawberry at Olympic Freeway can never seem to be found.
4. See if Car exists.

**Expected Results:**
Car spawns properly and can be located. 

**Actual Results:**
Some locations don't appear to spawn a choppable car. 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by Masik52** [comment]
This is also happening, call outs that are impossible to locate as they aren't feasible.  Some of the vehicles aren't able to be found due so many vehicles being stolen at the moment.

![Chop Issues](https://user-images.githubusercontent.com/52395441/72657789-b55e4600-3976-11ea-81fd-8b14b11d2603.PNG)

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
