### ISSUE TITLE
New bank, Whitewashing money

### ISSUE THREAD

**Issue by BobbyStonyy** [InZidiuZ/op-framework-issue-tracker#777]
I Feel like it would be a good idea to make the big bank on vinewood robbable, It would need to be a bigger payout but it would also be really hard, Lockpicking minigame/ thermite minigame. There should be a higher amount cops in the city to do a bank robbery, For the standard bank i believe its 4 i recommend putting the minimum at 6 or so.

I also have a second idea for whitewashing money, I Feel like if you illegaly made money, Selling drugs/Robbing a bank you would need to whitewash it, I Think it would be a good idea to only let some people be able to do it as a regular person would not be able to whitewash their money. It should be done by an expert/Maffia/Gang. 

I know all of the devs are working really hard and such but i feel like this would improve the server alot

**Comment by y0Razz** [comment]
That would mean that civilians would buy drugs with illegal money, doesn't seem realistic imo. Making the vinewood bank robbable is a big +1 but i'm pretty sure this is already on the planning.

**Comment by BobbyStonyy** [comment]
No if civilians sell drugs they would have illegal money, that money would have to be whitewashed by a certain person

**Comment by y0Razz** [comment]
I get that, but if i would buy drugs IRL i would pay the dealer with '' normal legal '' money.

**Comment by BobbyStonyy** [comment]
I'm talking about selling drugs to NPCs not players

**Comment by y0Razz** [comment]
Yeah i get that aswell, but why would NPC's be walking around with illegal money on them?

**Comment by InZidiuZ** [comment]
Hey,

Closing in favor of #647.

**InZidiuZ**
*OP-FW Developer*
