### ISSUE TITLE
New Cuts Inzidiuz <3 

### ISSUE THREAD

**Issue by Jester1994** [InZidiuZ/op-framework-issue-tracker#778]
**Name:**
Who is suggesting this? Please include discord name.
𝕵𝖊𝖘𝖙𝖊𝖗
#9731

**Summary:**
Write a short summary of what your suggestion is about.
Pirados MC CUTS
**Reason:**
Why would your suggestion be a good addition to Legacy?
We're an MC for the server and I was wondering if you could add these for us Ben
https://cdn.discordapp.com/attachments/622407707969716244/666565485424410644/image0.png

Please contact me for the file....

**Comment by 1THC** [comment]
You guys should have to make a name for yourself and earn it. Pirados MC isn't even a whitelisted gang yet.

**Comment by Jester1994** [comment]
your not ben
𝕵𝖊𝖘𝖙𝖊𝖗Last Wednesday at 9:31 PM
ignore that, i got it, ermm ben can i ask a favour ish....
if i create an mc on legacy can i get these cuts in 

 
InZidiuZLast Thursday at 8:50 AM
Yea sure, probably can


Want more proof bud??

**Comment by TwoplePop** [comment]
Chill, all he's doing is giving a recommendation. You're giving a suggestion. Anyways, having a good backstory/rp towards your goal is probably better imo.

**Comment by Jester1994** [comment]
> Chill, all he's doing is giving a recommendation. You're giving a suggestion. Anyways, having a good backstory/rp towards your goal is probably better imo.

Chapter 1 (Ryan Williams)
It all started back when Ryan was a kid, he always got in trouble in some sort of way. He dropped out from school.
He got stuck in the dark side of drugs for 2 years when dark things started to happen, lucky he got out of that.
One day when Tony was walking past a clubhouse down the main road in Liberty City, he saw a bunch of men flewing past him on motorcycles with the same patches 
on their backs. He got so blown away by that, that he told himself that one day he's gonna own a club of his own.
 
 
 
Chapter 2 (Start of the club)
Some years went past, he got his shit back together. got himself a license and a bike.
He got so in love with riding his bike that he one day in the year of 2010 started the club
 "Pirados MC"
McCarter had one vision to form a group of like minded individuals working together to achieve one goal and that goal was (Brotherhood). 
To get what he wanted, he had to put in his blood, sweat and tears. He got some members to join him that he has met from riding his bike all over the city.
They didn't knew that being part of a club was so much more than just being friends and riding bikes with a cool patch on the back.
After a while, things started to get heated with the other MC club in the town. things started to go south. They got in some fights with them and even getting shot at some times.
One day when it was a big fight with fists and even guns were pulled at one point. Ryans best friend got shot in the chest 3 times.
His best friend passed away a few days later in the hospital. After that Ryan was planning to move the club to a new city.
 
 
 
Chapter 3 (The new beginning)
Few months passed by, most of the members was going to stay behind in Liberty City where they all had family and friends.
Now Ryan are here starting his club once more back from scratch. This time even more prepared.

**Comment by InZidiuZ** [comment]
Hey,

This has since been added.

**InZidiuZ**
*OP-FW Developer*
