### ISSUE TITLE
[properties/properties] Addition of a property garage

### ISSUE THREAD

**Issue by ZroonX1998** [InZidiuZ/op-framework-issue-tracker#779]
**Name:**
ZroonX#2499 / https://steamcommunity.com/profiles/76561198058001316/

**Summary:**
I own a block and it doesnt have a garage i would like if itys possible if you can add one it clearly have a spot for garage 

**Reason:**
It would be good for Legacy because the owner of the apartment is upset about not having a garage and thats gonna look bad on me for telling him that a garage should be available because there is a a lot of space for it 

Here is a screenshot of the location please help me out with this much love for the new whitelisted city its awesome so far.
http://prntscr.com/qnpdl5
If you have any questions please contact me on my dicord above.

**Comment by pxyeb** [comment]
Garage has been added, it will be accessible from the front of the Apartment Complex.

**Pxyeb**
*OP-FW Helper*
