### ISSUE TITLE
[properties/properties] Ability for PD to Raid Houses

### ISSUE THREAD

**Issue by FossiiLs** [InZidiuZ/op-framework-issue-tracker#780]
**Name:**
FossiiLs_#4043

**Summary:**
Add the ability for PD to raid peoples houses and search their belongings. Detectives would gather evidence which they would go to a Judge and get a warrant signed off on. Once done, they would contact SWAT and schedule a time to do a raid and search for guns and drugs. Also adding either ARs to PD or at least the pump shotgun to the armory would balance out the gun fights between criminals and PD.

**Reason:**
This would add a whole new level of RP. It would actually allow PD to do their jobs and get these drugs, guns, etc off the streets of Los Santos. It would require criminal organizations to be smarter with how they do their business. If not they may get raided.

**Comment by Livius99** [comment]
Would be cool but let's make it an "online raid" like this gangs or criminal organizations can fight back in case cops try to raid. idk if you want to be offline raided and make it like on rust tho xd

**Comment by Livius99** [comment]
Also about the ARs, I'd say that only shat should have them, cops already have smgs and pistols, shotguns would be nice in their loadout as well imo

**Comment by skyy-reginald** [comment]
I like this idea as long as the criminal needs to be in the city, that way if they find out about it they have a chance of fighting back or moving their shit out before police get to it

**Comment by DaxterPancake** [comment]
This is extremely needed. Having to tell criminals that they need to give us keys so we can raid them always ends bad. :)

**Comment by Nuziatella** [comment]
This is something that I've discussed as well. While the opportunity for abuse could be high. The ability for it to be abused can be circumvented by only allowing those with the highest ranking jobs (chiefs of pd or judges for example) the ability to /raid a house and see inventories. The addition of inventories being able to be tracked also adds another layer of security against possible abuse.

**Comment by DaxterPancake** [comment]
I am completely fine with only higher ranks in PD having access to said command. I understand it could be abused but not having it is allowing the people being raided to abuse knowing it is coming. If it is found to be abused, we'd punish who is involved.

**Comment by novapurple** [comment]
If this was to be abused, I imagine there would be a HUGE consequences for doing so.

**Comment by JepsonHepson** [comment]
A way to go about this could be copy pasting the existing job structure for PD, but changing the department name from SASP to for example: "raid". Then only giving the ability to enter houses for people in that department, this would allow for staff members to reset jobs and remove the ability to raid, also this would allow it to be more controlled requiring a staff member present might sound tedious, but there is most definitely, always someone around.

**Comment by AdeptCL** [comment]
I agree with Jepson's addition.
When doing a raid, you're more than likely to use 2-4 individuals to actually make entry into the house. Therefore allocating one of those individuals who is already a staff member would regulate and make sure it isn't abused. After every raid is complete, the staff member can then change the individual's job back to the SASP/Trooper as an example.

I'm not sure if you have already thought about it @JepsonHepson, but would it be a 2 FIB and 2 SWAT making entry if using a 4 person entry?

**Comment by b-hess** [comment]
Currently, the challenge with setting up a raid, is that we need to meet beforehand with the house owners, and get a set of keys to later execute a raid.  It doesn't allow for the situation to develop naturally.

**Comment by Nuziatella** [comment]
If anything, at minimal my recommendation is that staff be able to use a command that would allow them to enter and allow others to enter similar to real estate owners

**Comment by DCS281** [comment]
Allowing for PD to raid makes it not weird for crims who know OOC that they are getting raided... it allows for the situation to develop naturally and it allows for people to actually find out about a raid in-character instead of having to meet and give keys. Since we have to meet, being able to raid would give FIB and SWAT a chance to do a lot more of these raids, which are fun and gives a lot of fun RP for everyone that they may not be able to experience a lot.

**Comment by Nuziatella** [comment]
Agreed. Relying on OOC methods for roleplay is immersion breaking and can lead to the ruining of story lines and/or roleplay scenarios.

**Comment by twooot** [comment]
We now have the battering ram
