### ISSUE TITLE
Give PDM a business fund

### ISSUE THREAD

**Issue by Funkallnight** [InZidiuZ/op-framework-issue-tracker#781]
It would be cool if they had a business fund for like liability/ insurance purchases. Take a certain percentage paid on each car and put in fund. for example an employee can scam a customer or something and you can sue PDM. the money would come from the fund and not the personal employee or PDM owner. i say this cause im currently in an ongoing RP situation like this and seems like the only reason it might not continue further is cause there is no PDM fund.

**Comment by ZurxeyH** [comment]
We have one.

**Comment by ZurxeyH** [comment]
> hmm RPd about it with cricket in game and he said the PDM owner and seller get 50/50 of the commission money and the rest disappears so they have no fund to refund me for my situation. Im suggesting that the rest go to a fund nobody can touch but is used for lawsuits and stuff etc... If its not like that already i guess

Working directly at PDM, and for Cricket I can guarantee you there is a PDM fund. If you go in game, do /pdm you will see the commands available only to him. Now this was added a few months ago, not sure the last time you RP’d with him.

**Comment by InZidiuZ** [comment]
Hey,

Please use the template.

**InZidiuZ**
*OP-FW Developer*
