### ISSUE TITLE
New Interiors for Pillbox Medical Hill Center

### ISSUE THREAD

**Issue by shobhitkdutta** [InZidiuZ/op-framework-issue-tracker#783]
**Name:**
Shobhit Dutta Dutta#8933

**Summary:**
Need New Interior for Pillbox with the option of locking/unlocking door and dispensary kind of thing from where people can buy bandages.

**Reason:**

- The reason I think that new interiors should be added within pillbox because it can take RP to next level and make EMS job a little bit more challenging and interesting compared currently

- Option of Locking/Unlocking the door can be helpful in treating in a patient peacefully and professionally.
 

. Addin
_Attaching some screenshot for reference_
![Screenshot_3](https://user-images.githubusercontent.com/32891115/72529758-f03b7d80-3893-11ea-8bb4-53c0bf9d9283.png)
![Screenshot_4](https://user-images.githubusercontent.com/32891115/72529759-f03b7d80-3893-11ea-9915-510cb9fb060d.png)
![Screenshot_5](https://user-images.githubusercontent.com/32891115/72529760-f03b7d80-3893-11ea-9e77-d78a349217cd.png)
![Screenshot_6](https://user-images.githubusercontent.com/32891115/72529762-f03b7d80-3893-11ea-9872-754f3d5eb2e5.png)

**Comment by AdeptCL** [comment]
Already a suggestion. #764

Please close and add on your reason to #764

**Comment by shobhitkdutta** [comment]
It's already been posted #764
