### ISSUE TITLE
Vehicle disappearing while gassing up

### ISSUE THREAD

**Issue by Funkallnight** [InZidiuZ/op-framework-issue-tracker#784]
**Reporter:**
SNAQS#8360      //// https://steamcommunity.com/profiles/76561198844082227/

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
The car that it has happened to twice in a row is the Sabre turbo custom. First time it was at the gas station closest to the Vanilla Unicorn. While i was gassing it up, it disappeared. The Second time was at the store on Grove st and i actually finished gassing it up but before i could get in the car it disappeared. 

**Expected Results:**
not disappear 

**Actual Results:**
Car will vanish during or right after fueling

## Additional Information

**Screenshots:**

**Game Resolution:**
What is your game's resolution?
not sure at the time but its never happened before

**Player Data:**
Write /info whilst ingame and provide the information you're given.
quit out of FiveM before i reported it 

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
On the Whitelist server

**Notes:**
For anything else noteworthy.
Have a good day :)

**Comment by InZidiuZ** [comment]
Hey,

If you encounter this issue in future versions of the framework, please create another issue.

**InZidiuZ**
*OP-FW Developer*
