### ISSUE TITLE
[vehicles/sirens] Bug report - "phantom Sirens"

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#785]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
https://steamcommunity.com/id/lankovich/

**Summary:**
Write a short summary of what you're experiencing.
So in the previous city we had problems with the sirens being heard all of the city from time to time when there actually was no sirens on at all. This problem has come up again and is very annyoing since it destroys the purpose of going with lights and no sirens, when they still can hear us coming.  

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Drive around like normal in a Police Cruiser and the problem will occur eventually.

**Expected Results:**
What are the expected results?
Not hearing any sirens when sirens are off.

**Actual Results:**
What are the actual results?
Sirens being heard from distance, but when the cruiser/mc comes closer it turns down to eventually being turned off completely.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Please create another issue if this is still a problem once the live servers starts to receive regular updates again.

**InZidiuZ**
*OP-FW Developer*
