### ISSUE TITLE
[jobs/winery] Winery Job - Suggestion

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#787]
**Name:**
DooZolz#4014

**Summary:**
I think it would be very interesting to have a winery job. Basically the owner of the vineyard/winery can hire people by typing a command (ex: /wineryhire [id] [salary]) and when you are then able to the 3D Text or a Marker spawning a van or something and you basically can pick grapes to make into wine and then once that's done you deliver the wine to a random selected amount of houses or maybe a company or something which gives you a small but good amount of money.

**Reason:**
Well, I see a lot of people wanting more legal jobs and I really think that this would be an interesting job to make and it would be interesting to see people actually doing some legal for once. The winery owner can also put out advertisements saying that the winery is hiring and you can do IC (In Character) job interviews. It's just a suggestion but I think it would be a really cool and fun job to do.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
