### ISSUE TITLE
[illegal/weed] Weed Changes

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#790]
**Name:**
Who is suggesting this? iGreatWhite#0001

**Summary:**
Changing Weed Ratios to make more sense.
Using Weed Q would make 2-2g joints.
Weed 1oz = Weed Q - Quarters
Weed 4ox = Weed 1oz

Because 2-2gram joints is 4grams. 4grams is a quarter of an ounce. 4 quarters is an ounce.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Makes more sense than what we have now as when people go to farm for weed they come out with 1lb+ of weed.

**Comment by Livius99** [comment]
Big +1 from me, plus location changes wouldn't be bad

**Comment by CranioDad** [comment]
agreed and big +1

**Comment by InZidiuZ** [comment]
This has now been done.
