### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LordNetloc** [InZidiuZ/op-framework-issue-tracker#791]
**Name:**
Who is suggesting this? Please include discord name.
LordNetloc 1498
**Summary:**
Write a short summary of what your suggestion is about.
i think a cop limit of 20 is way too many cops. Even if crims were still allowed to be in groups of 6 i still think 20 cops is a lot. think reducing this to maybe like 12 plus 4 cadets in training to make a max of 16 would be ok or maybe even less.
**Reason:**
Why would your suggestion be a good addition to Legacy?
i understand there is a lot of crime and a lot of criminals but with the WL becoming a thing i would expect more original RP and more social RP. Not everyone is a criminal type thing. gives a cops vs robbers vibe. i think 20 cops is too many. i understand the realism aspect that irl there would be a lot of cops but this is RP. there is supposed to be a fun aspect as well and as ive heard from some criminals it is just not too enjoyable to be swarmed by a million cops in anything and everything you do.

**Comment by y0Razz** [comment]
There is a max amount of cops that respond to a call, so nothing changed compared to before we went WL. And i'm pretty sure we only had 20 cops on duty once since the launch of WL.

**Comment by iGreatWhite** [comment]
how many cops per call is it?

**Comment by AdeptCL** [comment]
Depending on the level of crime, should depend on how many units respond:
- For traffic stops, there should be max 2 units on scene. If needed, 1 further unit not on scene, maybe around the corner out of sight. It feels even from an outside POV, that the situation feels like Officers are trying to win it.
- For drug sales and/or home robberies, there should be max of 3 units on scene. I would have said 2 again, but for the reason of a chase happening/guns being involved, 3 seems very reasonable.
- For bank robberies, there should be 4 units on scene. This will allow 1 unit to remain on scene while the other 3 units begin the chase.
- For large quantity of gunshots, it's a free for all so go all out.

**Comment by AdeptCL** [comment]
I only say the above because I've seen and heard direct from Officers that they cannot go to other scenarios because every on-duty officer seems to want to go to the very same bank robbery or vehicle chase.

Allocate/spread on-duty resources to maintain a level of authority in the city.

**Comment by y0Razz** [comment]
At the moment it's 8 units for a bank, but this was also the case when we were 32 slots.
Imo it should be lowered to max 4 or 5 units. 4 units to chase maximum.

**Comment by AdeptCL** [comment]
It just feels like when there is a bank robbery happening, then everyone has to hold their roleplay scenarios if there is cops involved because EVERY unit "HAS" to respond to it.

When you could have 4 on scene, and if they crash throughout the chase then a new unit can enter the race.

**Comment by y0Razz** [comment]
Agreed, but there isn't anything on paper regarding a max amount of units responding to a call sadly.

**Comment by Lankovich** [comment]
I don't see the point taking the Police RP away from bankrobberies. Usually all police in the jurisdiction respond and why would you prevent all officers from responding. I like to respond and RP it out like a real bankrobbery, setting up perimeters, searching the areas, SWAT etc etc. When the chase begins I agree only 4 units should be in the chase. But at the very scene I dont get why you would prevent troopers from being there to RP a bankrobbery?

**Comment by iGreatWhite** [comment]
because not every bank robbery ends in a chase. at the end of the day, this is a game and people have to realize that rules and features should be balanced around the fact that everyone should be having fun. so limiting cops per robbery would make sense to a degree.

**Comment by y0Razz** [comment]
We both know that if we have 8 units on scene of a bank robbery, all units will join the chase except swat / the trooper staying with the hostage. I think we need to get some rules about units per chase / call on paper asap so it stays enjoyable for everyone.

**Comment by Camdaddy34** [comment]
The initial response shouldn’t be limited tbh. All troopers on scene, whether it interrupts external RP or not, is something that would happen organically. The chase afterwards is where it should be limited however. 4 units could make for a good chase, or if there is no change to implement a 4 unit max, maybe the other units could spread out around the city instead of following in tow just a giant ass Congo line.

**Comment by Lankovich** [comment]
I agree with the chase and all that. If there is 8 units in the chase, commanding officer or the other units did something wrong. I always tell the line to stay as 4 units, rest of them shall break off and return to their patrol while on stand-by

**Comment by y0Razz** [comment]
Don't get me wrong, we can all agree but if the higher ups don't make a rule for this in the SOP nothing will change.

**Comment by InZidiuZ** [comment]
Hey,

Closing as this is not framework related.

**InZidiuZ**
*OP-FW Developer*
