### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Hanssonjao** [InZidiuZ/op-framework-issue-tracker#793]
**Name:**
Who is suggesting this? Please include discord name.
Ryan Williams 
Hansson#8418

**Summary:**
Write a short summary of what your suggestion is about.
Beards for the male characters.
https://sv.gta5-mods.com/player/beards-for-male-mp

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would make some characters look more natural. And they look nice as well.

**Comment by Livius99** [comment]
+1 I also wanna have long hair, bikers would look sick with beards and long hair bro 🤘🏻

**Comment by InZidiuZ** [comment]
Hey,

Please post this in the asset-related issue tracker.

**InZidiuZ**
*OP-FW Developer*
