### ISSUE TITLE
Losing money from bugs, reimbursment suggestion.

### ISSUE THREAD

**Issue by Ciiber** [InZidiuZ/op-framework-issue-tracker#794]
**Name:**
Who is suggesting this? Please include discord name.
Finn 7319, FinnRP on forums

**Summary:**
Write a short summary of what your suggestion is about.
After losing money due to bugs in game on two separate occasions I think it would be a good idea to have a system in place to reimburse funds to those that lose money to bugs in game.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Because nothing ruins your motivation to play more than losing everything you work for.

**Comment by InZidiuZ** [comment]
Hey,

This is not a framework-related suggestion, rather a community one.

**InZidiuZ**
*OP-FW Developer*
