### ISSUE TITLE
Robbing

### ISSUE THREAD

**Issue by y0Razz** [InZidiuZ/op-framework-issue-tracker#795]
**Name:**
Lars #5487

**Summary:**
With us going Whitelisted i thought it would be cool to add robbing back again without cuffs, like it used to be.

**Reason:**
It got removed because it got abused on the public servers, but now we are fully whitelisted so that shouldn't be an issue anymore :)

**Comment by Imaghost1337** [comment]
Well. Yes, and no. Considering the RP is _slightly_ better, in my opinion it's still a bad idea. 
What do you want to achieve by robbing people? Drive to one of he drug locations, point a gun at them and instruct them to do as you say? Or maybe go to Legion and camp on 1 wealthy person?
There's so little point in robbing people unless you're actually beefing with them in a RP scenario, and if you are, you should carry cuffs to rob them. It will still get abused, as one of my friends went afk in one of the popular locations, and got shot while afk (?) Talk about WL servers..and better RP

**Comment by y0Razz** [comment]
Well if we are going to talk like that, might aswell remove all the mechanics in the city because they can be abused. I mean people chainrobbed banks and we didn't remove them right? 

If we as a community put effort in we can be one of the best servers, there will always people who will ruin it by abusing certain things. Just report them so they can get unwhitelisted.

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
