### ISSUE TITLE
Vagner

### ISSUE THREAD

**Issue by RandleCaster** [InZidiuZ/op-framework-issue-tracker#797]
The Vagner is a 340,000$ super car that only goes 145-150 stock on flat and has rather poor acceleration.  I feel that it could use some tweaking

**Comment by iGreatWhite** [comment]
1. Proper format.
2 Asking for car changes won’t get much here. That’s for the assets tracker.
3. Maybe ask for the price to be adjusted as most of those cars are rediculous.

**Comment by RandleCaster** [comment]
Name:
Who is suggesting this? Please include discord name.
@ST-407 | Randle Caster 

Summary:
Write a short summary of what your suggestion is about.
 I feel that the Vagner could use some tweaking

Reason:
Why would your suggestion be a good addition to Legacy?
The Vagner is a 340,000$ super car that only goes 145-150 stock on flat and has rather poor acceleration.

**Comment by Livius99** [comment]
If cars can't be improved then prices need to drop on all cars... That would fuck up the market imo
