### ISSUE TITLE
Garbage job: Unable to pick up from PD

### ISSUE THREAD

**Issue by Lucifer1011** [InZidiuZ/op-framework-issue-tracker#799]
While collecting garbage near PD, there are few garbage which spawns inside PD and those are inaccessible because few doors are locked. There is another place near forum drive where the garbage are not accessible. Please look forward into the problem, as we have no other option than skipping which is a loss of finding something maybe a thermite or a gold bar.
![garbage inside PD2](https://user-images.githubusercontent.com/60744739/73945617-979f5380-491a-11ea-997d-6f8dbb39e97a.png)
![Uploading garbage inside PD1.png…]()

**Comment by iGreatWhite** [comment]
There’s really nothing that can be done that’s why the skip option is there. If I am correct skipping doesn’t act as a delivery so it won’t count toward the total bags.

**Comment by TwoplePop** [comment]
So basically what i see here is that you're refraining from calling a cop over to rp getting a trash can and you can also get the ones in grove by being smart with parkour tactics so not really sure what this is for.

**Comment by XBTech** [comment]
I don't see an issue here. I see an RP opportunity missed!

**Comment by LOxPanda007** [comment]
Same Think, Unable To Pick Garbage From Police Department. Also, If Officers Are There Most Of The time They Say We Are Busy Come Back Later We Are In Situation. They Have To Think We Are Also Doing RP. It Happens With Me

**Comment by TwoplePop** [comment]
It seems you forget they have rp too.

**Comment by LOxPanda007** [comment]
Not A Problem. They Are Cops They Have To Work For More To Clean The City From Crime

**Comment by InZidiuZ** [comment]
Hey,

Please use the available templates.

**InZidiuZ**
*OP-FW Developer*
