### ISSUE TITLE
[properties/shells] Buyable Warehouses

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#800]
**Name:**
Daxter#7158

**Summary:**
I'd like to suggest the addition of Warehouses to blocks to be able to be bought by companies and then sold.

**Reason:**
I think that it would nice to be able to purchase a warehouse which would include a large storage amount (Way bigger than the houses currently have) and they would have large interiors (Weed Lab, Coke Lab, Etc). 
Gangs would be able to house their weapons, weed, coke. They'd be able to set up a large weed farm and perhaps in the future other operations.
There are many locations on the map that could be the entrance to these warehouses and would be happy to provide these locations for you if requested.
A lot of the interiors may already be ready to use depending on which IPL we are currently using.
It would also be amazing roleplay for SWAT to have to find and clear these warehouses.

![image](https://user-images.githubusercontent.com/50828532/73987332-1ab0c000-4994-11ea-8b85-de491279c7bf.png)
![image](https://user-images.githubusercontent.com/50828532/73987391-5481c680-4994-11ea-916d-41e69d9ca1e3.png)
![image](https://user-images.githubusercontent.com/50828532/73987425-7aa76680-4994-11ea-88d5-a7e0c23795a9.png)

**Comment by Imaghost1337** [comment]
Huuuuge +1 from me!

**Comment by CranioDad** [comment]
Want to add a big ole +1 on this as well

**Comment by Livius99** [comment]
Big +1 from me too

**Comment by DaxterPancake** [comment]
I found this:

https://forum.cfx.re/t/release-esx-warehouse-gta-online-like-smuggling-job/922715

Food for thought?

**Comment by LeBewm** [comment]
Do we have an Idea of when this will  be implemented?

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
