### ISSUE TITLE
[jobs/trucking] Transport Job Buff

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#801]
**Name:**
BowchkaHonkHonk#0001

**Summary:**
So i feel like the delivery pays good when you deliver the product. You can get up to 500 for one delivery if you go from the airport to Paleto but something that was not transferred to OP-FW was when you do a certain amount of deliveries your check increases. right now it is 16$ flat and i feel as tho increasing it (maxing it at 4 increases) would be great. It is what i liked about it way back when and increasing it to like 28, then 40, then 65 as an example, would make it a more viable job. 

**Reason:**
Right now the only viable jobs for civs are mechanic and garbage so buffing the check amount would make this viable for a different reason. Mechanic is viable for repairing your own car while garbage you can get items.

**Comment by CranioDad** [comment]
+1

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
