### ISSUE TITLE
[weapons/ammo] Infinite Ammo

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#802]
**Reporter:**
BowchkaHonkHonk#0001

**Summary:**
When you unbox Ammo it shows there is a cap but the cap does not actually exist. You can keep unboxing and unboxing and if you reach past the cap then your ammo amount does not change. So the max ammount of ammo shown for an smg is 260 i believe and if you unbox over 260 it does not actually change when you reload.
**Steps to Reproduce:**
Just keep unboxing ammo as it will stack

**Expected Results:**
It to say you are full on ammo and can not unbox anymore

**Actual Results:**
It keeps unboxing and adding to your ammo

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
I don't believe there's an limit in place right now. Will look into getting this added once I rewrite the ammo system, though.

**Comment by InZidiuZ** [comment]
Closing in favor of #1366.
