### ISSUE TITLE
[jobs/garbage] Waste Collector Job

### ISSUE THREAD

**Issue by BlackSEXY007** [InZidiuZ/op-framework-issue-tracker#803]
**Name:**
I'm Tony Vercetti And My Discord ID Is debabratapanda_0710#5425

**Summary:**
In Garbage Job There Should Be Picking Garbage From The Whole City.

**Reason:**
I'm A Waste Collecter. The Garbage Pickup Location Is Same. Sometimes It Feels Bored While Doing The Job. If Possible Change The Location Randomly In The Whole City. It Will Be Better For Those Who Do Garbage Collecting Work In The City. Thank You For Your Precious Time.

**Comment by twooot** [comment]
I think this may be an idea when we get around to rewriting the garbage job completely. For now i dont think this will be done
