### ISSUE TITLE
[game/radio] larger bandwidth selection on the radio Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#804]
**Name:**
Who is suggesting this? Please include discord name.
CranioDad#0619

**Summary:**
Write a short summary of what your suggestion is about.
Look into a larger range than 100 frequencies for the radios. i.e. NP has 1000+ with a 999 base + decimals.

**Reason:**
Why would your suggestion be a good addition to Legacy?

We are rapidly growing and this is causing many people finding their way onto other channels. We (the Lost MC) have had to change frequencies 5 times in two days.  100 frequencies may seem like a lot, but it takes seconds to scroll through them all, reducing security and ability to RP. Expanding would allow much more security, and less frustration due to needed to change because someone else "has been using this freq for ever....".

This will also add in the aspect of "looks at radio" to be more effective and usable by cops (or just detectives) when working a scene. longevity of frequencies means people will be more comfortable on coms, making the act of investigating even more fruitful.

**Comment by DaxterPancake** [comment]
+1 This needs to happen.

**Comment by Livius99** [comment]
+1

**Comment by DopePixel** [comment]
+1

**Comment by RaleMaximus** [comment]
+1

**Comment by InZidiuZ** [comment]
With the next update, all radio frequencies will have two decimals.
