### ISSUE TITLE
[properties/properties] Reposition garage

### ISSUE THREAD

**Issue by DopePixel** [InZidiuZ/op-framework-issue-tracker#805]
DopePixel#9481

Summary:
The garage of the block of Spanish Avenue Apt. Complex M (122) The garage is very terribly placed. When you go to get a vehicle such as a tow truck out of the garage it will spawn on top of you and while putting vehicles in the garage it is very easy to get stuck on the stairs.  It should be moved down the stairs to the larger plot down the stairs.

**Steps to Reproduce:**
Go to the Garage and pull out a tow truck and it will spawn on top of you.

**Expected Results:**
Expected results would be the garage would be moved to the parking garage where there would be more room and the vehicle wouldn't spawn of top of you.

**Actual Results:**
The Vehicles spawn of top of you and could possible give you injuries causing a useless trip to pillbox.

## Additional Information

Screenshots:

The Block :![image](https://user-images.githubusercontent.com/57329053/74107933-eaf3ea80-4b42-11ea-81d5-16a91263d1e4.png)

New Garage Location:
https://youtu.be/phMnPBBHIcc

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 863-Job Data:Mechanic,Los Santos Customs,Tow Driver
**Server:**
EU/US

**Notes:**
For anything else noteworthy.
I feel as if this would help as it is more realistic and will stop the car spawning on top.

**Comment by Miliax** [comment]
Yea. its so annoying. doesn't make any sense why it should be there.. its should be at the parking lot down the stairs.

**Comment by pxyeb** [comment]
I'm sorry my ultimate developer skills did not allow me to make all the 200+ garages perfect, I shall fix this issue within the next update.

**Pxyeb**
*OP-FW Helper*
