### ISSUE TITLE
[game/doors] Yellow Jack features.

### ISSUE THREAD

**Issue by Lankovich** [InZidiuZ/op-framework-issue-tracker#806]
**Name:**
Jack Tyler - CyberSkunk#5173

**Summary:**
So, I just got approved by the state to be a Approved Business Owner. I'm about to take Yellow Jack Inn, in Sandy shores under my wings. It is mainly for Bikers and bypassers on Route 68 to rest or have a good time in. I will basically contribute to various different stuffs. As this will be a owned place, I would like to lock or unlock it while it's not been used. Another thing would be to add maybe a storage for us to use (Owner/Employee), as a fridge.

**Reason:**
As I stated above, I want to contribute with some RP for various bikers and Biker Clubs around the city, as well as for the people coming by for other reasons. We will hold different events and people/clubs will be able to hire the place for private nights/events/meetings. This would fit good to all of us bikers in town.

Thanks in advance.

**Comment by InZidiuZ** [comment]
Doors are being added to Yellow Jack in the next update, though the other features requested will not be added at this time.
