### ISSUE TITLE
[jobs/police] Giving crime/calls for police a much needed boost

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#807]
**Name:**
Joe Vedder - Ori#4385

**Summary:**
The absence of "petty" crime aside from full-blown gangster RP and bank robberies has been felt strongly ever since the launch of OP-FW and particularly WL. This has created a boring atmosphere in the city in which the activity of the police has been mostly ranging from either responding to bank robberies involving serious criminal RP, to doing nothing at all. **People are currently relying on themselves to stay away from boredom, especially in the police, because the server (not to the fault of any of the civilians) has been giving little to none to us.**
While you can push features to create interesting illegal opportunities and make them more worthwhile. The biggest flaw is currently in the call system. It is always going to depend on our ability to engage with people. Some of the new calls are better, for example with vehicle-related crimes involving a somewhat accurate description of the vehicle.
But this is needed in many other types of calls.

Police calls and crimes require more information to be reported, and in less time.
Some things are realistically delayed, yet some are also delayed too much. In addition, the absence of information in most calls is so far from reality, and some might think this is to create an even playground but the fact is. It is reducing interactions and preventing a lot of RP from taking place, and those who don't feel that simply don't know better just yet. The city is currently missing out on so many opportunities to engage.
If this doesn't change, most people who do police RP will slowly give up on responding to more and more calls, as we feel that there is no point to respond when the system is currently so flawed. We know that nothing will happen and we are not given a very fair chance to interact with anyone.
To stress this and pinpoint just one example out of many, the chance of actually running into a person on a house burglary call is about once every ten or more times. And that is when the person is unsafe enough to be chain robbing houses right next to each other, because you bet that they would be long gone otherwise, and we would have no description on them or their vehicle to make up for the delay either. Apparently people also have a "scare bar", because playing a mini-game of holding still until the bar drops is more realistic than having to be careful and dreading the chance of unknowingly getting called the police on when you aren't safe enough.

The drug world is the biggest example to be given, the economy and risk factors for harvesting, processing, transporting and dealing drugs in legacy is unrealistically easy and risk-free. This not only creates an unstable economy, but also makes the drug world boring. The only time calls are sometimes made in this entire process is when drugs are being dealt, which most people get away with because they RP with the police or simply get away. 
I am hearing more and more criminals say they wish we could interact more, engage more, people want to be more scared doing certain things. And we as the police sadly cannot provide that.

**Reason:**
With enough tweaking, it will keep the server healthy and alive.

**Comment by TwoplePop** [comment]
+1

**Comment by AdeptCL** [comment]
Big +1.

There is no fear being played through criminals right now. People even walk through Pillbox admitting to getting Oxy or Cocaine so openly.

**Comment by Pyrotimegamer** [comment]
Huge +1 , Playing as a cop and crim I personally feel like im to safe as a crim I can do however mutch illegal activity that i want without ever being caught even gathering stuff is to easy. id like to see more added for pd to be able to arrest me or the other way arround.

**Comment by nyjetsfanmike** [comment]
+1

**Comment by Jamerson1793** [comment]
Psss don’t put just +1 add the reaction thumbs up to the original post

**Comment by Jamerson1793** [comment]
+1 tho

**Comment by JamieG681** [comment]
+1

**Comment by InZidiuZ** [comment]
Wrong '+1' y'all 😡 

There's a reaction feature available, which even allows for sorting on the main page, use that instead...

**Comment by skyy-reginald** [comment]
honestly i think this is a great idea. hopefully we can see this in the future. it will generate so much more rp.

**Comment by AdeptCL** [comment]
Just going back to this topic. 

Oxy calls - failed oxy drops giving PD a call. Could create some true RP for PD in the Blaine County.

**Comment by lildiavolo** [comment]
we still need them house robberies to be reworked

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
