### ISSUE TITLE
[vehicles/wheels] Ability to slash tires

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#808]
**Name:**
Daxter#7158

**Summary:**
I am suggesting that we add the ability to slash someones tires when we have any sharp weapon equip.

**Reason:**
The reason why I am suggesting this is because I personally feel like it would add some more roleplay for mostly the criminals but also for the cops. If you're about to do a bank robbery or start some type of criminal RP that would involve people chasing after you, you can pre-plan and sneak up to their vehicle and slash the tires. It gives you a slight advantage especially if you're trying to get away from a speed unit. Other uses could be that you've found a car belonging to a gang you're currently in a war with and want to mess with them. It would also mean that rubber would be used a lot more and wouldn't be thrown on the ground as junk as much.

Here is a link to a mod that does what I am talking about, if you'd like a clearer idea:
https://forum.cfx.re/t/release-slash-tires/155838

**Comment by TwoplePop** [comment]
just crouch and hit it with a knife a lot of times?

**Comment by TwoplePop** [comment]
it works for me

**Comment by DaxterPancake** [comment]
I was thinking more along the lines of a button press to slash the tires to eliminate accidently stabbing someone. Plus slashing tires should literally just be knife goes in tire and then bam it's done and not make a lot of noise to be noticed.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. [Here](https://gyazo.com/6debc36e7f69e0a9141d6d960c98ad9b) is a preview of the script.

**InZidiuZ**
*OP-FW Developer*
