### ISSUE TITLE
[jobs/police] /frisk

### ISSUE THREAD

**Issue by Jamerson1793** [InZidiuZ/op-framework-issue-tracker#809]
**Name:**
Who is suggesting this? Please include discord name. Jamerson#0001

**Summary:**
Write a short summary of what your suggestion is about. I believe we should have a /frisk command as police. When we go up to an person we could use /frisk and if they had a weapon on their person it would say, “Slight Bulge In back of Waistband.”

**Reason:**
Why would your suggestion be a good addition to Legacy?
This would allow for a higher quality roleplay for Police, let’s say we did not have probable cause to perform a full search on then individual but we could perform a Terry stop and frisk the outer part of their body. Instead of using /search all the time and seeing everything in their pockets instantly.

**Comment by AdeptCL** [comment]
It would be interesting. However, there are a lot of current Officers who would power game this to being "I know you have a weapon". As long as there was a guideline for Officers to not instantly assume this is a weapon or something, it would definitely bring more entertaining interactions.

**Comment by Jamerson1793** [comment]
@AdeptCL the only reason /frisk would be used is if the individual is acting suspicious let’s say around a bank and has a mask on, realistically you would be able to terry stop them and frisk from with reasonable suspicion, questioning them and then frisking them and once seeing a budge I would consider from experience and suspicion that it’s some sort of weapon. I understand your point though, thank you for the +1

**Comment by Brundoggy** [comment]
I feel it would be good for more law stuff so that we can have more "4th amendment" violations

**Comment by Vedder742** [comment]
I like this idea but don't think the command is needed, Police may legally frisk people under the same relevant situations (such as a traffic stop) Naturally this would be used under the exact same circumstances. To frisk and simply pat down an individual for weapons, you may already do so by simply searching a person and only paying attention to any weapons they might have on them. In RP, this translates to the fact that **you are only feeling for weapons on the individual**, so if you know how to RP and don't metagame anything else they have on them, you're good to go. Of course you must also understand the difference between a pat down for weapons and a full search and when you may do either of them legally.
On that note, I would also like to suggest that some of you start to roleplay failing to find some things on an individual, take into account that a bag of cocaine can be hidden in a shoe and many places that you may not bother roleplay checking. In that case, only remove some of the illegal substances, or cash off people, and give them something to smile about and make them appreciate your realistic RP.

**Comment by twooot** [comment]
This has been done
