### ISSUE TITLE
[properties/properties] Garage Location For Forum Dr. Apt. Complex F (6)

### ISSUE THREAD

**Issue by StegoSau** [InZidiuZ/op-framework-issue-tracker#811]
**Name:**
Theodore Tolerance: Devongaimz #7644

**Summary:**
A garage spot for this Appartement complex. It has 10 appartments but no Garage area.

**Reason:**
It's reasonable for every Complex to have a garage. No one wants to live here if they have to walk a mile to a city garage.
The links I attached show a location ready for a garage spot.

![20200215213247_1](https://user-images.githubusercontent.com/50210875/74594960-6e7a7380-503c-11ea-9a8c-d892dae0b61e.jpg)

![20200215214231_1](https://user-images.githubusercontent.com/50210875/74594965-71756400-503c-11ea-9cad-53a7f63071cc.jpg)

![20200215214241_1](https://user-images.githubusercontent.com/50210875/74594968-73d7be00-503c-11ea-957e-8b6e9a0ed54f.jpg)

**Comment by InZidiuZ** [comment]
This has already been done, see #710.
