### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ArshvirSingh** [InZidiuZ/op-framework-issue-tracker#812]
**Name:**
My name is Arshvir singh. My dicord name is Skullbuster #9111

**Summary:**
This suggestion is about long waiting time for cocaine plane in the new 64 player server

**Reason:**
As the player limit is upgraded from 32 to 64 and most of the things are same as in the previous servers like flying plane and waiting 15 to 20 mins for another plane. So all the players are grinding now and there is no bank robbery for some time and also there are not many well paid jobs to do in the city. The cocaine plane is the only good paying option for players and if 20 out of 64 players want to fly plane they all have to wait on an avg 17 mins for plane which is  20*17=340 and 10 mins for plane travel time which adds another 200 mins so total is 540 mins on an avg which is way too much and this is not just theoretical i have been trying to get a plane since yesterday morning but i am unable to get one because there is huge line always.. Somebody is always there waiting like always it never free. So please understand this problem and decrease the waiting time to 5 mins or less. And try to add few more interesting things to do in the city

**Comment by Livius99** [comment]
I think that will increase the " grinding", plus the time right now it's ok imo

**Comment by ArshvirSingh** [comment]
> I think that will increase the " grinding", plus the time right now it's ok imo

I know  it will increase grinding but also the player limit is doubled and 20 mins is way too much when there are so many players 10 mins will be fine i guess

**Comment by InZidiuZ** [comment]
Hey,

This will not be changed for the time being.

**InZidiuZ**
*OP-FW Developer*
