### ISSUE TITLE
[vehicles/vehicles] New Feature / Command: Flipping vehicles

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#813]
**Name:**
Who is suggesting this?
iGreatWhite#0001

**Summary:**
Instead of having to steal a new vehicle in order to flip our cars, would it be possible to make like a little easier and add a command for us to flip our vehicles when outside of them. The just simply serves as a small quality of life change to the server.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Would not need to attract police for unnecessary calls for stolen vehicles. Could also possibly allow for better RP in some and certain scenarios.

**Comment by InZidiuZ** [comment]
Hey,

This has now been added. [Here's](https://gyazo.com/1d15369eb78d7dc5af7ff135bfc07379) a preview.

**InZidiuZ**
*OP-FW Developer*

**Comment by Livius99** [comment]
Wait... Is this in the actual city?

**Comment by Masik52** [comment]
Or you know you could just call a mechanic to come help you with that. Who am I kidding that would require RP rather than everyone having super human strength.

**Comment by InZidiuZ** [comment]
You still can & should unless under certain circumstances @Masik52 ;)
