### ISSUE TITLE
Bug report: Garbage Run by the police station.

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#814]
**Reporter:**
DooZolz#4014
https://steamcommunity.com/profiles/76561198185121513/

**Summary:**
So when I was doing garbage runs my GPS was set near the MRPD. When I got there I noticed that I couldn't get to any of the trash cans because all of them are behind the locked doors inside the MRPD. Meaning I needed to skip every single trash can. Not too sure if anyone has reported this yet but I basically can't get to my trash cans that are inside the PD.

**Steps to Reproduce:**
Possibly removing the garbage run near the PD.

**Expected Results:**
Is that next time I don't have to experience this. This was truly a tragic event. This was my 37th garbage run of the day and I only made 80 dollars from it. Truly disgusted and disappointed kappa. On a serious note. The excepted results are that when doing garbage runs you are able to get every single trash bag without having any issues. (ex: trash can being behind a locked door) 

**Actual Results:**
The actual results are that I can't get to my trashcans and get my money which means I can't feed myself or my children. ;(

## Additional Information
None
**Screenshots:**
No errors in the F8 console, this doesn't really seem like a bug it's just being unlucky but mine as well report it anyway.

**Game Resolution:**
1970x1080

**Player Data:**
ummmmmmm idk im not home atm

**Server:**
Main

**Notes:**
no, srry about the player data thing I'm currently in a library not reading cuz im kool lollll.

**Comment by InZidiuZ** [comment]
Hey,

If this is still an issue once the live servers start receiving regular updates, feel free to reopen or recreate this.

Also see #799.

**InZidiuZ**
*OP-FW Developer*
