### ISSUE TITLE
[jobs/diving] Remove collision on oxygen tank

### ISSUE THREAD

**Issue by Bowchikahonhonk** [InZidiuZ/op-framework-issue-tracker#817]
**Reporter:**

BowchkaHonkHonk#0001
**Summary:**
The oxygen tank is completely bullet proof and you take no damage when you have it on from the face mask to the body

**Steps to Reproduce:**
Put on the oxygen tank after buying it from the tool shop

**Expected Results:**
To take damage when shot in the head or body

**Actual Results:**
No damage is taken when you are shot

## Additional Information

**Screenshots:**
https://clips.twitch.tv/SuaveJoyousDragonflyAliens

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main WL
**Notes:**
For anything else noteworthy.

**Comment by Karpenkooo** [comment]
This a job for Karpenko?? :)

**Comment by InZidiuZ** [comment]
This has since been done.
