### ISSUE TITLE
I am Vedant Tiwari here for a Bug report. @Vedant Tiwari#1000 OneSync is causing many PedAI and traffic AI issues our vehicle's trunk empty's at any time and the items get lost. The garage near Pillbox is also bugged where the Trunk issue and sudden vehicle explosions happen. The new OneSync sucks.

### ISSUE THREAD

**Issue by Vedant42** [InZidiuZ/op-framework-issue-tracker#818]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by AdeptCL** [comment]
Close this and redo it. 
You did not follow the template below it.

**Comment by AdeptCL** [comment]
Again, you haven't followed the template literally provided to you in the main box below the title.
Again, please close this and redo it for it to be seen properly.

**Comment by InZidiuZ** [comment]
bruh... 😴

**Comment by Vedant42** [comment]
Lol, actually I am not using my computer right now, if you can then please
remove the issue I will submit another tomorrow because it’s night time in
India right now.
