### ISSUE TITLE
[clothing] Suggestion

### ISSUE THREAD

**Issue by TrialByCombxt** [InZidiuZ/op-framework-issue-tracker#819]
**Name:**
𝒯𝓇𝒾𝒶𝓁𝐵𝓎𝒞𝑜𝓂𝒷𝒶𝓉#1365 (Sylvester Salvetti)
**Summary:**
I believe we show have clothing/masks to help assist our RP with injuries. This could include things as such as eyepatches and bandages.
**Reason:**
I believe this would be a good addition because it would take away a partial use of /me and it would allow people to see visually you have an injury. The reason why I am asking for this is because the other day my character got his eye cut out and I would like to visually show this by having an eyepatch.

**Comment by InZidiuZ** [comment]
Hey,

Either this is already in the base game, or this is asset related & you should use the other issue tracker with appropriate links.

**InZidiuZ**
*OP-FW Developer*
