### ISSUE TITLE
Suggestion Crazy_you yt#0598 should add some more jobs to indian legacy server because we can do many other thing and people will also find interested in doing new job

### ISSUE THREAD

**Issue by Crazyyouyt** [InZidiuZ/op-framework-issue-tracker#820]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by InZidiuZ** [comment]
Hey,

Use the template.

**InZidiuZ**
*OP-FW Developer*
