### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jamerson1793** [InZidiuZ/op-framework-issue-tracker#821]
**Name:**
Jamerson#0001

**Summary:**
Enable Bags and Parachutes in the Clothing Menu.

**Reason**
My Suggestion would be good for Legacy Roleplay because when that section is enabled cops will look way better and will actually be able to put on badges. RN our police outfit does not even identify that we are police on any part of the normal clothing. The only thing that identifies us is our vest.

**Comment by InZidiuZ** [comment]
Hey,

This is already a thing on beta.

**InZidiuZ**
*OP-FW Developer*
