### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jamerson1793** [InZidiuZ/op-framework-issue-tracker#822]
**Name**
Jamerson#0001

**Summary:**
Add decimals to the radio for example 81.89 and also add Radio’s as an Item

**Reason:**
I think this suggestion would benefit Legacy Roleplay in multiple ways, having the radio be an item makes it so people can’t use a radio after comms have been taken off of that person. Decimals in the radio would benefit Roleplay and Legacy so that people would not fight over channels and also people can’t just go through the radio 1 - 100 and listen to everyone. ADD IT IN BEFORE BETAAAAAAAA.

**Comment by InZidiuZ** [comment]
Hey,

The radio is not yet a part of beta, but when it will be, this will be done. Plan is also to not use TokoVoip for beta.

**InZidiuZ**
*OP-FW Developer*
