### ISSUE TITLE
Weird Car Issue - Linked?

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#823]
**Reporter:**
CranioDad#0619

**Summary:**
Was repairing my motorcycle at the Lost MC shop. After repairing the engine, another player from Lost MC (Nohbob) appeared on my bike. Radioed and he was no where near the shop, in his own car. He drove to the shop and got out of his car. When he did, the character got off my bike, and he appeared in the lot. He could not see my bike in the shop, I could not see his truck in the lot. We did this MANY times. From the time that he 'appeared' on my bike, it was running and I could not do anything with it besides lock and unlock. When I sat on my bike, I would appear, to him, as in his truck. 

After many rounds of testing, he took his truck and parked it in a garage. When he did this, my bike vanished.  This happened around 1pm est on 2/25/2020 on the NA Whitelist server.

**Steps to Reproduce:**
Unsure if this was a momentary glitch or an issue tied to the shop. Perhaps he was parked where the bike would have moved itself too if it had vanished?

**Expected Results:**
For this not to happen

**Actual Results:**
unsure

## Additional Information

**Screenshots:**
![2](https://user-images.githubusercontent.com/60828050/75274678-4542ab80-57d1-11ea-98fe-cf48a68e163f.PNG)

Did not know that f8 was needed. Can also supply video of issue taking place

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 410- Job Data: Mechanic, Los Santos Customs, Tow Driver Timestamp 2020-02-24 19:19:39

**Server:**
NA Whitelist

**Notes:**
Can supply video of issue taking place.

**Comment by InZidiuZ** [comment]
Hey,

Not quite sure why that's happening. It's definitely an issue related to FiveM/OneSync, so not much I can do about it from what I know, unfortunately.

**InZidiuZ**
*OP-FW Developer*
