### ISSUE TITLE
[jobs/mechanic] Add Tow Truck :)

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#824]
**Name:**
Who is suggesting this? Please include discord name.
KaiEagle🦅#6969

**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is about adding the mini Tow Truck to the Mechanic Job.

**Reason:**
Why would your suggestion be a good addition to Legacy?
It's because sometimes the tow truck can't fit in the compact areas where only a mini car can go through.
![Tow truck](https://user-images.githubusercontent.com/29286961/75309084-f7cc4a00-5875-11ea-9f4b-6e79fab28d37.png)

**Comment by twooot** [comment]
This tow truck is very scuffy with the chain, which is why i'll not be adding it to the list of purchasable vehicles.
