### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#825]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
KaiEagle🦅#6969

**Summary:**
Write a short summary of what you're experiencing.
The Lost MC Club repair shop is bugged like the vehicles get teleported out of the repair shop to anywhere inside the Lost MC compound.

## Additional Information

**Video:**
https://www.youtube.com/watch?v=SjxJ9erBzw0
This is not the first time it happened...

**Game Resolution:**
What is your game's resolution?
1920 x 1080

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India WL

**Comment by InZidiuZ** [comment]
Hey,

This is most likely a FiveM/OneSync related issue, therefor there's not much I can do about it.

**InZidiuZ**
*OP-FW Developer*
