### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KaiEagle** [InZidiuZ/op-framework-issue-tracker#826]
**Name:**
Who is suggesting this? Please include the discord name.
KaiEagle🦅#6969

**Summary:**
Write a short summary of what your suggestion is about.
If we can have a emote of a mechanic toolbox that would be great like we have of a briefcase.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding the mechanic toolbox emote will look good that's all xD

Example of Toolbox :)
![FiveM_GTAProcess_VhrCJiV1l6](https://user-images.githubusercontent.com/29286961/75452568-8c2ecd80-5998-11ea-9eaf-5028809d561d.png)

**Comment by InZidiuZ** [comment]
Hey,

This will not be added for the time being. The briefcases are natively supported to be an 'equipped weapon', meanwhile the repair kit is not.

**InZidiuZ**
*OP-FW Developer*
