### ISSUE TITLE
[game/miscellaneous] /card just like /dice

### ISSUE THREAD

**Issue by psyCOSMO** [InZidiuZ/op-framework-issue-tracker#827]
**Name:**
**psyCOSMO#0476**

**Summary:**
/card just like /dice will give out a random card with its type,
For example /card will result in a **me** that looks like this:
[CARD] Got ♥ J
[CARD] Got ♦ 5
[CARD] Got ♣ Q

**Reason:**
Just like gambling with dices I think it could add some black jack possibilities or even quick poker flop, can be enhanced in the future to allow a proper holdem, etc :)

```
 var aCards = ['♥ 2', '♦ 2', '♣ 2', '♠ 2', '♥ 3', '♦ 3', '♣ 3', '♠ 3', '♥ 4', '♦ 4', '♣ 4', '♠ 4', '♥ 5', '♦ 5', '♣ 5', '♠ 5', '♥ 6', '♦ 6', '♣ 6', '♠ 6', '♥ 7', '♦ 7', '♣ 7', '♠ 7', '♥ 8', '♦ 8', '♣ 8', '♠ 8', '♥ 9', '♦ 9', '♣ 9', '♠ 9', '♥ 10', '♦ 10', '♣ 10', '♠ 10', '♥ J', '♦ J', '♣ J', '♠ J', '♥ Q', '♦ Q', '♣ Q', '♠ Q', '♥ K', '♦ K', '♣ K', '♠ K', '♥ A', '♦ A', '♣ A', '♠ A',
]

function randomCard() {
    var index = Math.floor(Math.random() * aCards.length)
    return aCards[index]
}
```

a code that can be done in 2 min :D, maybe additional line to show it in /me

**Comment by AdeptCL** [comment]
This would be beneficial to all sorts of roleplay. Both business and entertainment routes.

**Comment by KiwiUK** [comment]
Would love to see this feature!

**Comment by InZidiuZ** [comment]
A variant of this has now been added. I had to drop the icons of the different card types as they didn't display very well in-game. [This](https://gyazo.com/4402131b724cfce2f919b0cd771ece06) is what it looks like for now.

The animations is also the same as the /dice command. I tried finding a better one, but couldn't find any that would work here. If you, or anybody else finds one we could use, please post it here or DM me on discord! 😄

**Comment by InZidiuZ** [comment]
*I quickly changed the animation to [this one](https://gyazo.com/fc5aae8bbe5b75633e59998f8116cc87) instead, so there's some difference between the dice commands.
