### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BluEDeViL9929** [InZidiuZ/op-framework-issue-tracker#829]
**Name:**
Who is suggesting this? Please include discord name.
@BluE_DeViL#4042
**Summary:**
Write a short summary of what your suggestion is about.
I want to suggest Some thing for ems:
Add QRVs back in EMS Gradges
Add ems personal garadge
Add a EMS personal locker 

**Reason:**
Why would your suggestion be a good addition to Legacy?
1. Beacuse for now we have only 1 one fast car that is tahoe so thats why if you add QRVs it may help EMS to be good
2. Personal garadge may help like if you go offduty so we want to run to gradges or take lift so it may help 
3. Adding a personal Locker is important beacuse we have very costly thing linkamu bandages, burgers, water, tanks and overall so we want to save them

**Comment by InZidiuZ** [comment]
Hey,

Use the asset-related issue tracker for the vehicle-related issue. Also, create one issue per suggestion, and each suggestion should be thoroughly explained in an understandable fashion. It's also important to keep suggestions realistic while benefiting something.

**InZidiuZ**
*OP-FW Developer*
