### ISSUE TITLE
[game/hospitalization] Adding an /bed command to allow people to lay down on hospital beds.

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#830]
**Name:**
Daxter#7158

**Summary:**
Add the ability to use a command (ex: /bed) next to a hospital bed and the surgical beds in the Morgue and have the player lay down and stop moving.

**Reason:**
I'd like this to be added because having people use the /e sunbathe1 or /e sunbathe2 which has them moving their arms and legs around, it personally takes away from the surgical/treatment roleplay that I do. I also think that people would enjoy not having to move around to find the perfect spot on the bed to them do the command. It'd place you perfectly in the center of the bed without any movement.

**Comment by InZidiuZ** [comment]
This has since been done.
