### ISSUE TITLE
[game/hospitalization] Hearse for use during funerals

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#831]
**Name:**
CranioDad#0619

**Summary:**
Access for a state employee, even cops, to 'rent' a hearse, with keys, for use during funerals. Removes needing to acquire one, and adds to the realism.

**Reason:**
It makes absolutely no sense to have people have to hunt down, find, and lock-pick a hearse for use during funerals. Having one that someone could get keys to, sign out, even leave a deposit on, makes far more sense. These person could be any state employee, even cops would make sense. As of late, the planning around these events are done well in advance, so coordination should be seamless, easy, and the people responsible for the hearse would know of the event. Heck, add punishment if it is also used in a crime. Just a way to help the sad end of the RP along and allow all to focus on what is at hand.

**Comment by InZidiuZ** [comment]
Hearses have now been added to EMS spawners.
