### ISSUE TITLE
[game/ambience] Stop combat walk animation

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#832]
**Name:**
Igna#6192

**Summary:**
Simple, stop combat walk animation when you shoot.

**Reason:**
Because the combat walk is a bit annoying after you shoot.
[code.zip](https://github.com/InZidiuZ/op-framework-issue-tracker/files/4279644/code.zip)

**Comment by psyCOSMO** [comment]
Yup, it is useless

**Comment by InZidiuZ** [comment]
Hey,

This has now been added.

**InZidiuZ**
*OP-FW Developer*
