### ISSUE TITLE
[Illegal/cocaine]no process option appear in cokelab

### ISSUE THREAD

**Issue by anirudhsureka02** [InZidiuZ/op-framework-issue-tracker#833]
Name:
RaZoR#8942
https://steamcommunity.com/id/anirudhsj/

Summary:
I m not getting a option to process my cocaine bricks. This issue is coming from 2-3 days i have tried to exit city then enter but it didnt work.

**Comment by InZidiuZ** [comment]
Hey,

Create a *proper* report again once the server starts to receive regular updates again, if this is still an issue then.

**InZidiuZ**
*OP-FW Developer*
