### ISSUE TITLE
New Pill Box Hospital 

### ISSUE THREAD

**Issue by Mechan1caL** [InZidiuZ/op-framework-issue-tracker#835]
**Name:**
Mechan1caL#4751

**Summary:**
This have new interior's and unlock more room. This will allow EMS to do more RP like Therapist will ge there own Cabin, Doc's will get there own Cabin, Xray room, Operation Room. I guess this will improve and boost the EMS RP. The Interior and color, Lighting, the sliding door also looks look.

**Reason:**
Why would your suggestion be a good addition to Legacy?
This update will help improve EMS RP (Docs and therapist's).
![92600610_pillbox png 004d8a6bcffb6d9140f254d56082b5b6](https://user-images.githubusercontent.com/57615196/75809525-eb347e00-5dae-11ea-9aa8-3df9668c9648.png)

**Comment by AmokBSN** [comment]
This has already been suggested a number of times

**Comment by GameXport** [comment]
+1 Nice Idea. I think it should be implemented soon as this Pillbox is very old now :(

**Comment by InZidiuZ** [comment]
Hey,

Use the issue tracker... this is an asset.

**InZidiuZ**
*OP-FW Developer*
