### ISSUE TITLE
Garbage Job - Bug Report

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#836]
**Reporter:**
DooZolz#4014
https://steamcommunity.com/profiles/76561198185121513/

**Summary:**
So when I was doing a garbage run it told me to go to this place up in Rockford Hills (you can see the screenshots of the location below) and as soon as I arrived at the blip it immediately told me to go back to HQ. I didn't even step out of the garbage truck or do anything. Once I arrived it told me to go to back to HQ... and the mini map was disabled even though I was in my vehicle. So I went back to the HQ, and dropped off the garbage and it gave me 0 dollars for the run (cause I wasn't able to collect any trash). 

**Steps to Reproduce:**
Remove this garbage run?

**Expected Results:**
To make this garbage run work like the other ones and not just tell you to go back to HQ without collecting any trash...

**Actual Results:**
Well... I got 0 dollars from this run and collected no garbage.

## Additional Information

**Screenshots:**
F8 Console: https://gyazo.com/fbf33af061536eb4d05d0e9934e22d74
Location: https://gyazo.com/470243f9a0685e124bc2699e7271d4e9
Location In Game: https://gyazo.com/c66cd05c5d44fe52d7623a8f96c0d93a

**Game Resolution:**
1960x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://gyazo.com/e324b37eef2f1cffeef1fd9f2a25762a

**Server:**
Main

**Notes:**

**Comment by InZidiuZ** [comment]
Hey,

There were no available garbage bags at the location. This might be related to low-end specs. Proper validation for the location to ensure bags are present would only be implemented with a rewrite, so closing for now.

**InZidiuZ**
*OP-FW Developer*
