### ISSUE TITLE
More illegal activities - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#837]
**Name:**
CranioDad#0619

**Summary:**
I know that this has been talked about. But I could not find the suggestion. Bring in store robberies, vault, bank trucks, jewelry store heist, hot cargo runs, shop robbery (like B&E for houses),etc.

**Reason:**
This (IMO) will not turn this into a grind server. If anything, it will bring massive amounts of content. As crims, we are creating RP for lack of things to do. As LEO, having more than one situation to respond to, multiple situations at the same time, and degrees of situations, would allow the force to be more fluid in the community. 
SOOOO much RP can be created in those scenarios. It is not about the money, it is about the creativity that we (on both sides of the table) will be able to produce. This would up overall interaction, create interesting moments, and bring more into and to the city. I see little to no reason to 'wait for beta' for SOME of these things.

**Comment by InZidiuZ** [comment]
Hey,

Please be more specific about your suggestions. They should also be individual, and include tons of information as to how the suggested system should work, from start to end.

**InZidiuZ**
*OP-FW Developer*
