### ISSUE TITLE
Unable to remove Oxygen Tank once attached

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#838]
**Reporter:**
AdeptCL#0402
https://steamcommunity.com/id/AdeptCL/

**Summary:**
Once the oxygen tank has been used and is on you, due to the new /e feature, you cannot remove the oxygen tank as it doesn't recognise it as an emote.

**Steps to Reproduce:**
Attach oxygen tank and try to remove.

**Expected Results:**
To take off the oxygen tank.

**Actual Results:**
"No emote to cancel" message.

## Additional Information

**Screenshots:**
https://gyazo.com/8f6d4d5efb23142bd435b8586c97a28e

**Game Resolution:**
N/A.

**Player Data:**
N/A.

**Server:**
Legacy Main.

**Notes:**
N/A.

**Comment by InZidiuZ** [comment]
Hey,

This should no longer be an issue.

**InZidiuZ**
*OP-FW Developer*
