### ISSUE TITLE
[external/dpemotes] Improvements

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#839]
**Name:**
Who is suggesting this? Please include discord name. Masik52

**Summary:**
Write a short summary of what your suggestion is about.

With the addition of the new emotes and numpad keybinds we used to be able to hit the keybind again to cancel the emote is there a way to get that back rather than using /e c. Also would it be possible to get B back as the old pointing emote with the current emotes the point is just a like a quick spasm. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
Would be more user friendly to be able to hit the keybind again to cancel the emote and the old point is better than the new.

**Comment by twooot** [comment]
I think this is fixed
