### ISSUE TITLE
[game/miscellaneous] /roll with more dice - replace /dice - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#841]
**Name:**
CranioDad#0619

**Summary:**
Introduce more dice types into the city. Not just a d6

**Reason:**
There have already been multiple times that have dice OTHER than 1d6 would have promoted better RP. By implementing the /roll #[DICE TYPE] there would be other ways to roll for things. Dice to include are: d6 , d10, d12, d20, and d100. The command would work something like this:
/roll 1d20
result: 18

**Comment by CranioDad** [comment]
Further, a command could be to /roll 3d6 where the result is the total number from each d6

**Comment by InZidiuZ** [comment]
This has now been added. [Here's](https://gyazo.com/148a4d0a89e8b07fe68dc27014193718) a gif of what it looks like in-game.
