### ISSUE TITLE
[game/items] Advanced Repair Kits - Enhancement

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#842]
**Name:**
Zurxey#2607

**Summary:**
Basically an enhancement to gameplay. Advanced repair kits are so under utilized because of their pricing, and odds of breaking. I believe that these kits should cost roughly $500, and basics $250 each. Keep the same odds for Advanced, but allow it to be cheaper so we're not spending $2100 on one use of the repair kit. 
If not this, allow it to be sold for cheaper from certain companies *cough cough* allowing to bring more Roleplay into purchasing simplistic things that should be allowed around the server. 

**Reason:**
I believe this would be a good addition as it would allow for racers, and other drivers who inevitably crash, regardless of the mass amount of ghost locals, or just plain shit driving. Allowing these prices to not be outrageous would allow for them to be more utilized, along with removing them from the shop, and allowing say a racing company to sell them out to civilians creating more sustainable RP. Too many times have I purchased an Advanced, and had it break first try. I'd like to see the pricing change, and keep the same odds.

**Comment by InZidiuZ** [comment]
This has since been adjusted.
