### ISSUE TITLE
[game/afk] Suggestion

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#843]
**Name:**
Who is suggesting this? Please include discord name. 

Masik52

**Summary:**
Write a short summary of what your suggestion is about.

I’m not sure if it’s possible since we use tokovoip but the afk timer. It currently doesn’t take into account that you are in the city and speaking.  There have been several situations while being the passenger in air1 that I’ve not noticed the afk message pop up and then poof kicked for afk but I was there. Is it possible to extend the afk timer out more or possibly have it take into consideration that if you’re speaking that you aren’t afk. 

**Reason:**
Why would your suggestion be a good addition to Legacy?

It’s annoying if you don’t notice the pop up since it’s the same color as PD calls and all of a sudden poof you’re kicked.

**Comment by InZidiuZ** [comment]
The AFK system is being removed all together, so closing this.
