### ISSUE TITLE
[jobs/mechanic] Mechanic/Lost Santos Customs Suggestion

### ISSUE THREAD

**Issue by z-Lunar** [InZidiuZ/op-framework-issue-tracker#844]
**Name:**
Who is suggesting this? Lunar#3391

**Summary:**
Write a short summary of what your suggestion is about.
Mechanic Job & Los Santos Customs Rework.

**Reason:**
Why would your suggestion be a good addition to Legacy?
I think the mechanic job needs to be reconsidered, maybe restrict this job to whitelisted groups such as the Lost Mechanics & Jackal Racing(?..I forget if this group runs grove idk..). summary, Whitelist mechanics to Whitelisted Groups, Whitelisted Mechanics will be able to fix advanced repairs such as, Fuel Tank, Tires, Breaks, Oil(?) Etc, these are the core parts of the car that will kill the car in the long run, with the new LS Customs [https://forum.cfx.re/t/esx-ls-custom-bennys/51037](url) you will still be able to repair your car on your own, basic engine, windows body & tires..but overtime the deep engine parts will degrade and the car will shut down/stall or even die completely on you requiring a mechanic to fix it for you..adding depth to the mechanic job & forcing interaction rather than people repairing their own cars, this will also add a use for items such as batteries, plastic, copper & other placeholders we currently have.. - If I forgot anything I will update it here. 

**edit** Example: [https://forum.cfx.re/t/release-realistic-vehicle-failure/57801](url)

**Comment by Imaghost1337** [comment]
Would be complicated with the wave of new players which choose the mechanic as their first job, but the concept seems great. +1 from me :)

**Comment by Lunar929292** [comment]
> Would be complicated with the wave of new players which choose the mechanic as their first job, but the concept seems great. +1 from me :)

I almost always suggest new players to run garbage, these new players can sell their parts such as copper to us & make good cash.

**Comment by CranioDad** [comment]
BIG +1

**Comment by Livius99** [comment]
+1 from me too

**Comment by ZurxeyH** [comment]
BIG +1. 
This was suggested before, and could possibly be in planning for Beta. It's good to see other community members suggesting this! <3

**Comment by twooot** [comment]
I dont think this issue is really relevant anymore
