### ISSUE TITLE
[game/hospitalization] Bug report - Moving the Doctor Sign-On and /Outfit location in Pillbox

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#845]
**Name:**
AdeptCL#0402

**Summary:**
Changing the location of where people get changed to the new locker room, which is accessed via behind the desk.
Changing the location of the doctor sign-on to the break room, which is accessed via behind the desk.

**Link:**
There are no links available. But I will provide some screenshots to assist in the reason.

**Reason:**
Currently, the outfit change location is still in the Morgue area which I feel is now out-dated. I recommend this being moved to the new locker area in the staff room next to the new reception desk.

> https://gyazo.com/65469be8dc2c65de5297fbc94df438ea
Essentially where the current "Doctor sign-on" trigger is.

In addition to this movement, I would also recommend moving the "doctor sign-on" trigger to the room before it - the break room.

> https://gyazo.com/17410d5595bf1b033e5eee353ebc9563

The move would hopefully stop them overlapping when triggering one of them.

**Comment by InZidiuZ** [comment]
If this is still relevant, please create a new issue.
