### ISSUE TITLE
[properties/properties] Bug Report - Bike stuck on a garage I no longer own

### ISSUE THREAD

**Issue by Rondsonn** [InZidiuZ/op-framework-issue-tracker#846]
**Name:** 
Rondson#7557

**Summary:**
One of my bike is stuck in a garage I no longer own

**Link:**
https://prnt.sc/reblu0
https://prnt.sc/rebm9u
https://prnt.sc/rebnb4

**Reason:**
I used to own a house in Forum Drive in the garage of that property I stored a bike 2 days before I stopped owning it, due to this I no longer can pull out my bike.

**Comment by InZidiuZ** [comment]
Hey,

In 2.4 you will be able to retrieve vehicles inside other garages, so this will not be an issue then.

**InZidiuZ**
*OP-FW Developer*
