### ISSUE TITLE
[game/items] Issued with oxygen tanks

### ISSUE THREAD

**Issue by vojdan31** [InZidiuZ/op-framework-issue-tracker#847]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Sasha Soprano 
https://steamcommunity.com/id/Yappy1
YAPPY#7700
**Summary:**
Write a short summary of what you're experiencing.
I went diving at the boat crash and I had 2 scuba tanks on me, I used up one, then went up to an island. Changed it up and went for another dive, halfway though I anonymously dead. Keep in mind 
I had half a tank left, more than half full water and food and no sharks around.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
I have no idea how to reproduce the issue due to this happening to me only once in the many times I've went diving.
**Expected Results:**
What are the expected results?
For this issue to be fixed and for there to be no longer cases of the same issue.
**Actual Results:**
What are the actual results?
The results are the person drowning, losing his scuba suit and getting mugged at PillBox.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
I do not have any screenshot of when the issue accrued.
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
I am from EU/NA server.
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
See #846

**Comment by InZidiuZ** [comment]
Has this happened since the last update?

**Comment by vojdan31** [comment]
I'm banned from LegacyRP

**Comment by InZidiuZ** [comment]
Guessing this was a one-time thing as I haven't seen any other reports on this. Closing this issue. If there is an issue with the diving system, I suspect it'll be resolved once this system is rewritten.
