### ISSUE TITLE
[animations/emotes] Proposed Handcuff Changes

### ISSUE THREAD

**Issue by DaxterPancake** [InZidiuZ/op-framework-issue-tracker#848]
**Name:**
Daxter#7158

**Summary:**
I'd like to propose some changes to the way handcuffs work, as I feel like at the moment they are a little too OP in the server. I would propose maybe a timer once you are cuffed (5-10min) that once that time has been reached, a mythic_notify appears telling you that you have broken out of the cuffs (you are then uncuffed). Alternatively you could have a prompt appear once that timer has been reached to ATTEMPT to break your cuffs.

**Reason:**
As it stands right now, if you get cuffed and are able to escape from the police, the only way you can get them off is by checking into pillbox (which could be classed as powergaming, not to mention cops will camp there to see if you visit) or trying to find someone in the city who will help you (which could end in you getting robbed or kidnapped). You're unable to jump fences or drive cars. You can't use your phone and it is power gaming to talk on your radio. You are forced to run for a potentially long time before you're able to get any help at all.

**Comment by iGreatWhite** [comment]
Bolt Cutters are a thing in the city you know right?

**Comment by DaxterPancake** [comment]
Ofcourse I know that Bolt Cutters are in the city.

In order to have Bolt Cutters used on you, you need to find someone that has them. Which then loops back around to my argument that you can't contact anyone to get help due to being unable to use your phone and your radio, you'd have to run for a long time, to hopefully find someone that will help you. Keeping in mind that they could steal from you or kidnap you.

**Comment by InZidiuZ** [comment]
Closing in favor of #1730
