### ISSUE TITLE
Police Vehicles Bug

### ISSUE THREAD

**Issue by IamAvneetSK** [InZidiuZ/op-framework-issue-tracker#849]
Whenever the livery or extra is turned on/off like rooftop, the fuel automatically goes to 100 rather than being what it originally was. This gives police an edge in chase.
@InZidiuZ 
[Clip](https://drive.google.com/file/d/17ohTGuoJuljAF26m8cevHoIUV7yO6ZoB/view?usp=drivesdk)

**Comment by InZidiuZ** [comment]
Hey,

Use the template.

**InZidiuZ**
*OP-FW Developer*
