### ISSUE TITLE
[game/citizens] Gun RP realism update, SER# database, better overall RP, evidence & investigations improvement

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#850]
As they are in real life, guns should be registered in "the system" using their serial numbers, and contain the buyer's information. A feature to run these serial numbers should be added for the Police, so that they can obtain the owner's information that is listed based on the Serial numbers. (Full name, Social security number, date of purchase etc)
Realistically you cannot buy a gun without this basic information or even a background check, it is weird the police currently do not have the ability to properly tie gun evidence together (using processed evidence and casings for example), link it to possible owners, or simply be able to run a serial number for the sake of checking if a gun is stolen.

Stolen gun charges are quite common in real life, and should definitely be a part of the city's RP.
**Perhaps with this addition, mindless shootings in the city will no longer go unpunished, casings found will now give a lead, probable cause, more RP, and the start of consequences, rather than none at all.**

Overall a small yet important possible feature, out of many, to add some complexity to the city's current flatline limited and repetitive police RP.

**Comment by skyy-reginald** [comment]
This is also a great feature to have in the city.

**Comment by twooot** [comment]
This was done a while ago
