### ISSUE TITLE
[game/cad] Database of all registered phone numbers for police

### ISSUE THREAD

**Issue by Vedder742** [InZidiuZ/op-framework-issue-tracker#851]
Ori#4385

Proposing a way for police to be able to find the phone numbers of civilians by having their full name and information, or the ability to check who the number is registered to by having only the number itself.

Big RP and interaction Improvements overall, allowing the police to contact civilians for any reason or find them as you would in real life. Lots of ways this can be used in RP, and It's an important step towards the overall feel of a higher quality & realistic city.

**Comment by skyy-reginald** [comment]
this will improve police finding stolen cars and giving back to citizens or calling people down to PD who they may suspect for questions, or even help return items that were confiscated.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
