### ISSUE TITLE
Bug report | "command is not available" but still works

### ISSUE THREAD

**Issue by SoniMatt** [InZidiuZ/op-framework-issue-tracker#852]
**Reporter:**
Soni#2000 | https://steamcommunity.com/id/OniSoni/
**Summary:**
I will do a command in game, and it would work as intended. But still says "Command not available" which is obviously wrong
Also /ooc_off doesn't work
**Steps to Reproduce:**
Do a command, i've noticed it does it mostly with PD related commands
**Expected Results:**
A command will work as intended but the system will say it was not available

**Actual Results:**
Same as Expected Results

## Additional Information

**Screenshots:**
https://gyazo.com/519a2a95e7c5add5602246d5ca6bac7d
https://gyazo.com/4c4807b156a43050dd193365f5d21867

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 9 - Job Data: Law Enforcement, SASP, Sergeant First Class

**Comment by SoniMatt** [comment]
Also /ooc_off doesn't work

**Comment by Livius99** [comment]
Wasn't it /oocoff?

**Comment by SoniMatt** [comment]
@Livius99 Yes but its changed now, only shows /ooc_off  or /ooc_on as an option

**Comment by InZidiuZ** [comment]
Hey,

This is related to the framework's alpha-to-beta migration and will not fixed be for the time being. Once the deprecated commands-related code from alpha is fully removed, this will no longer occur.

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
p.s. /ooc_* has been resolved
