### ISSUE TITLE
[jobs/mechanic] Mosley's Auto Repair / Servicing - Whitelisted Job / Server MLO Interior.

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#853]
**Name:**
Zurxey#2607 / Zurxey

**Summary:**
Basically, I found a useful MLO Interior that really allows for multiple new aspects of Grove Repair to be done. This would include locks for the doors, and mechanic shop beginnings. Just like Vanilla Unicorn, and Tequi-La-La, and PDM, I wanna have a whitelisted job, and actually create the RP that goes along with it. 
Also down below I have set a new grouping for Mosley Autos, a whitelisted mechanic job. 

https://www.gta5-mods.com/maps/mosley-s-auto-shop-interior-sp-fivem

Addon:
*If this is brought about into the servers, we can have a much longer talk, and discuss.* As stated in Suggestion #844, Whitelisted Mechanics should be able to fully fix a vehicle, it should deteriorate over time, using Benny's as a fix mechanic that will repair a vehicle to say, 75% health. After that, if you'd like it to be 100% and a LOT CHEAPER than Benny's, you will come to a Private Mechanic shop, such as Lost MC, or Jackal Racing. Basically trying to revitalize how the vehicle repair methods, and roleplay scenarios work. I'd love to have an abudance of employees, and a company infrastructure that creates that Roleplay, and allows the server to grow, not only in new mechanics, but also in solid Roleplay that could help the most necessary part of Legacy, CARS.  

**Reason:**
This would be a good addition to legacy because it will provide a brand new experience, and allow for many future events to happen. It can also help bring back the old days whitelist mechanic job, and it would be led by myself. It's been my straight passion for 6 months, trying for that old whitelist job, and a new interior / repair shop. I mean, even with the repair shop i'd be happy, doesn't need to include showroom, etc. 

**Job Information/Structure:**

Ranking Structure: 
Owner - $75 
Manager - $70
Tuner - $60
Senior Mechanic - $50
Mechanic - $40 
Roadside - $35 

Owner - In charge of business side, hires and promotes employees, takes care of finances, and watches over, will create application, Stand Operating Procedures, any other governmental responsibilities needed.
Manager - Responsible for anyone below Management, will watch over employees, and bring deserving individuals up to the Owner. 
Tuner - Will have permissions to the Los Santos Customs inside the shop, this will allow us to upgrade, and apply Engine, Turbo, Tires, Colour, etc for a cheaper price than Benny's because of the interaction. Tuner/Manager/Owner will have access to this.
Senior Mechanic - Senior Mechanic will have body work options, and the ability to repair, tune, and clean vehicles. They will also be trusted individuals who have access to the stocks of materials.
Mechanic - Mechanic is a newbie at repairing, they will be mainly focused on Tows/Repairs, working for people like the SASP, contracting publicly, and privately.
Roadside - Roadside workers will simply do things like AAA does. Tire Repairs, Gas Fillup, Small bump damage/repair, and towing vehicles when needed. They will be given personal trucks, and funded. 

Materials:
As its known, there is a need for materials, simply asking to have a storage locker within the shop that can allow us to stock pile materials, sort of like PD Evidence Locker, but instead it doesn't disappear. This could hold Scrap, Steel, Aluminum, Glass, Rubber, Plastic, and any future materials. 
This will allow for us to have an in-house material station for mechanics to pull out, and use for repairs. The company will pay for all materials, and the materials used, our employees will keep a large percentage, and a small percentage will go to the company. 

Structure: 
There will be a strict structure made for this job, you will be required to have training, and be established within the city. I will make sure they know how to Roleplay properly, and are actually active / interested in this type of RP. It will also provide a more interesting experience than just going inside of Grove Repair / other repair shops, fixing ur vehicle, and leaving. We'll have space for people to park, and space for people to hang out, chill, and enjoy themselves. 

Extras:
As stated in issue 

Now, this does not need to set aside regular mechanics, this team would be for the most experienced and the most interested. It will be a better paycheck, more interaction/scenarios, and a family to be apart of. Not to mention some great cars, women, and other things to come! 

Any questions, comments, concerns, DM me: Zurxey#2607

**Comment by Imaghost1337** [comment]
I've seen this being used on different servers, and I do agree it looks great.

**Comment by LostAI** [comment]
Giant +1, I think this would bring a bunch of RP to a part of the server that you don't see much of.  Right now, you just drive in as a mechanic, buy the stuff you need and leave. No interaction at all and this could really improve that.

**Comment by iGreatWhite** [comment]
This in turn can be a leeway to possibly have a dealership for exclusive vehicles that could also be run seeing there is a dealership built into this MLO interior. Would love to see a job dedicated to selling imports and having limited number of them around the city. Seeing cool like 1/1 vehicles and stuff.

**Comment by DaxterPancake** [comment]
After speaking to InZiduiz more about this issue, we have decided that something like this may be available in the FAR future through the use of the company system, but as it stands right now, it won't be added.

Cheers,
Daxter.
Project Manager.
