### ISSUE TITLE
/repair not working for emergency vehicles

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#854]
**Reporter:**
Jepson, T-56 & X-100

**Summary:**
Damaged emergency vehicles are not able to be repaired at a "repair area" such as MRPD.

**Steps to Reproduce:**
Withdraw a emergency vehicle from MRPD, damage it and then use the command "/repair"

**Expected Results:**
The car gets repaired, engine stops smoking, windows gets replaced.

**Actual Results:**
Nothing happens

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Main server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved. Let me know if fuel still saves though after using this, as it might not.

**InZidiuZ**
*OP-FW Developer*
