### ISSUE TITLE
Coke Plane Breaking Down Mid Run

### ISSUE THREAD

**Issue by DopePixel** [InZidiuZ/op-framework-issue-tracker#855]
**Reporter:**
DopePixel#9481
https://steamcommunity.com/id/DopePixel/

I signed the coke plane out made the journey to the box get to the box pick up the goods get out of the water and the place starts smoking then the engine turns off so I landed the plane on the side of a hill.

**Steps to Reproduce:**
Sign the plane out fly to the box collect the good fly back and the plane will start smoking and engine will shut off.

**Expected Results:**
No breaking down and no smoke.

**Actual Results:**
The plane breaks down and you have to land.

## Additional Information
I believe this is because of the new fire script along with the new vehicle damage

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Character ID:863- Job Data: Government, Waste Collector, Employee

**Server:**
Main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
solution found: become a better pilot and don't crash)

additionally, I've excluded planes (and certain other vehicle classes) from the damage system, giving them 'more' health
