### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by vojdan31** [InZidiuZ/op-framework-issue-tracker#856]
Reporter:
Who is reporting this? Please include discord name.
YAPPY#7700
Summary:
Write a summary of what you're experiencing.
People are not able to see my vehicle in-game.

Additional Information
Ever since I lost my apartment due to not paying rent and having my car in its garage other players couldn't see my car. The car in question is the Plister Comet SR, sports. The situation has happened 3 times to date and the only way I know of fixing it is leaving it out before tsunami, but even if I do that, it bugs out and no one can see it after I put the car back in the garage after I have gotten it after the tsunami.
Screenshots:
If suitable, include some screenshots.

Notes:
For anything else noteworthy.
FrankiE, $ini and Vitaly helped me with discovering the temporary fix for it aka putting the car in the garage before the tsunami.

**Comment by InZidiuZ** [comment]
See #846
