### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by VOiDVato** [InZidiuZ/op-framework-issue-tracker#857]
**Reporter:**
Steam Name: VOiD_Vato Discord Name: VOiD_Vato #9666

**Summary:**
I recently purchased a elergy retro and I spent the rest of my money on upgrades for the car at Benny's including interior and exterior modifications. After I added the modifications I proceeded to drive it back to my garage at my apartment on Forum Drive. I stored the vehicle and then pulled it out and everything was fine. Now fast forward to a couple hours later I have stored the vehicle another handful of times and no problem. I take a flight out and then take a flight back into the city and proceed to pull out my car and some of the modifications that I had already purchased have disappeared forcing me to have to pay for it again. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
I went to Benny's purchased the most expensive dash board, roll cage, trim, and license plate modification. 
After purchasing the modification I stored the vehicle in garage at my Forum Drive apartment. 
Within the next couple hours of storing and pulling it out I had no problems until I took a flight out and then back in and pulled the vehicle out a couple times. 

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![20200318025213_1](https://user-images.githubusercontent.com/62326878/76937939-bc94c800-68c3-11ea-8e59-28a3abedd4b2.jpg)
![20200318025238_1](https://user-images.githubusercontent.com/62326878/76937948-c0284f00-68c3-11ea-9615-658e7476adf9.jpg)
![20200318025310_1](https://user-images.githubusercontent.com/62326878/76937953-c3bbd600-68c3-11ea-9c65-b012574fdf8a.jpg)
![20200318025207_1](https://user-images.githubusercontent.com/62326878/76937986-d59d7900-68c3-11ea-860f-88d632dcf2b7.jpg)

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 1413 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Server:**
I am from the main EU/NA Legacy server.

**Comment by InZidiuZ** [comment]
Hey,

This is caused by unknown reasons. It is also assisted by an extremely bad method of saving vehicle modifications. In the future, this will not be an issue, once a new modification system is completed. (roughly 60% done already, but development on it was paused)

**InZidiuZ**
*OP-FW Developer*
