### ISSUE TITLE
[game/radar] Bug report

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#858]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile. nilmar#3552 https://steamcommunity.com/id/legend_nilmar/

**Summary:**
Write a short summary of what you're experiencing. pd radar not working on the pd bike

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue. f5 and try and activate overlays

**Expected Results:**
What are the expected results? for the radar overlays to show up and work

**Actual Results:**
What are the actual results? overlays dont show up and cursor gets stuck on screen so u have to f8 comp

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution? 1080-720

**Player Data:**
Write /info whilst ingame and provide the information you're given. id 43 sasp corporal

**Server:**
What server/community are you from? Main, India, Bangladesh, etc. main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Is this still an issue?

**Comment by InZidiuZ** [comment]
Hey,

I've updated the wk_wrs resource and it seems that resolved the issue.

**InZidiuZ**
*OP-FW Developer*
