### ISSUE TITLE
[base/queue] Suggestion

### ISSUE THREAD

**Issue by KiwiUK** [InZidiuZ/op-framework-issue-tracker#860]
**Name:**
Kiwi#6887
**Summary:**
Make crash queue prio the highest tier.
**Reason:**
Crash prio should be the highest because if I am mid scenario and my game crashes, I should be able to get back into the server as fast as possible to resume the scenario. At the end of the day, it is a roleplay server and I believe resuming rp scenarios is more important than a $40 donation or being a staff member. I understand that some people are dedicated to the server and feel like donating is necessary but for those who can't donate, they shouldn't have to be held back because of a game crash. Same with staff, if the server is full there is most likely staff in the server and therefore should not have better priority than someone who has crashed.

**Comment by InZidiuZ** [comment]
Hey,

Before creating an issue, use GitHub's search function to make sure there isn't already an issue created around the same topic. #432, #696 (this is even yours...?) & #734.

If your game is having issues, you should work on resolving that instead. Our servers are very stable for both the server's side as well as the client's, and unless there is an issue on *your side*, crashes should not occur.

**InZidiuZ**
*OP-FW Developer*
