### ISSUE TITLE
[game/miscellaneous] More /commands more things to collect

### ISSUE THREAD

**Issue by chromewick** [InZidiuZ/op-framework-issue-tracker#861]
**Name:**
Who is suggesting this? Please include discord name.
Kintsukuroi Vector (zonta)#7951
**Summary:**
Write a short summary of what your suggestion is about.
more /commands like /darts simulate dart scores. /pool game you get a message to accept.  you hit the 3 ~r~ red ~w~ in the right pocket or you sunk the other player ~b~ blue ~w~ striped 10 balls. so on and so forth. /basketball game and you play with others to spell out horse. something I would want but I don't see happing is a /bug hunt and you get indicators. you go to those spots and get a pop up to search area. you either fail or succeed. if you do succeed you get a butterfly, beetle or spider. the species is unknown. ya gonna take it to an entomologist or "bug guy" to identify it. then you can keep it and have it as a collection or sell it to a collector. /gofish. just more games or things to do or something like that. /scavenger hunt more things to collect and give as gifts. more things to find such as seashells, crystals, books, jewelry, puzzle pieces, dolls. /cups and the other person get a pop up to press 1-2-3 to guess which cups has the ball. and a /murdergame or something like that. you get a random message pop up that you are the killer or the bystander. but that one can be for events.
**Reason:**
Why would your suggestion be a good addition to Legacy?
because most of the things we do have in the city are geared to crime. I've noticed many times that people will have birthdays or weddings other things and there are no gifts to give. just guns and food. as far as the mini-games. I think they would be welcomed. mini-games would create more RP, more contest, more things to do.

**Comment by InZidiuZ** [comment]
A lot of these suggestions, such as the darts, pool games and basketball requires *a lot* of work to get working properly with syncing, UIs, and such. I'm doubtful basketball would even be possible without months of research and work, same goes for the pool game.

Some of the other suggestions are doable, but wouldn't be a priority right now as there's so much other work to be done.

Will close this for now though as nothing will be done with this at this time. Though if this is still relevant, please create another issue with more details for the different ideas, and limit every issue to one suggestion only.
