### ISSUE TITLE
[base/queue] Add Priority to White Listed Members over non in queue - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#863]
**Name:**
CranioDad#0619

**Summary:**
Push white-listed players up a notch in priority over non-white-listed 

**Reason:**
Benefit those that put in the time, and effort, with the promise to bring good RP to the server. Many nights, the queue time is HOURS. Members from the White-list are sitting watching their number never really increase in line, with known new players ahead of them. This would ensure that the members of the city, that are white list approved, should get in before any non-white-listed player (even those with prio). I believe that this can be done by altering the "deferral" setting in the playerConnecting call to set. It is painful to watch people that have been providing quality content and RP for MONTHS sit on the train for hours, sometimes debating on ever coming back. Something like this would go a long way in giving some notice to those that are white-listed.

**Comment by Lunar929292** [comment]
Yes

**Comment by Imaghost1337** [comment]
+1

**Comment by InZidiuZ** [comment]
Hey,

This will not be done at this time.

**InZidiuZ**
*OP-FW Developer*
