### ISSUE TITLE
High Risk Issue with O2 Tank - Bug report

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#864]
**Reporter:**
CranioDad#0619

**Summary:**
Since we can no longer remove the O2 tanks with /e c we need to hover below the surface to wait for them to run out. HOWEVER, there is a chance that one of three things will happen. 1. It goes away as intended, you have 10-15 seconds of air to surface, you live and all is well. 2. It goes away as intended, you INSTANTLY start taking damage, you have 3 seconds to make it to the surface, you likely die. OR 3. It does not go away as intended, you start taking damage, with your mask and tank still on, and you have 3 seconds to figure that out before you die. 

**Steps to Reproduce:**
It is a mixed result that I have experienced, as well as many others, completely at random. Just take some tanks, get in the water, and see what results you get. Seems to be a higher chance of option 2 over 1 or 3 from above. 

**Expected Results:**
Since we cannot remove them with /e c (which would be optimal and more realistic) IF we have to wait for the tank to resolve, then we should have 10-15 seconds of air... every time. This is mostly to ensure that those that want the tank to be removed without exiting the session, have a guarantee that they will have time. 

**Actual Results:**
It is mixed, with a tendency to be that the tank resolves and you instantly start taking damage, over the other two scenarios listed above. 

## Additional Information

**Screenshots:**
None to provide

**Game Resolution:**
Happens to multiple people regardless of resolution

**Player Data:**
Happens to multiple people, even witnessed all three on a group dive last night. 

**Server:**
Main

**Notes:**
This is not a singular person issue. I have talked to MANY and realized that there was not a ticket for this yet. Wanted to get this out there, in front of somebody as even on group dives, trips to pillbox with experienced divers is now commonplace.

**Comment by MPar22** [comment]
You just have to do an emote and the tank goes away.

**Comment by InZidiuZ** [comment]
See #847. The system will most likely be rewritten in the near future.
