### ISSUE TITLE
[game/crafting] Craft-able Thermite - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#865]
**Name:**
CranioDad#0619

**Summary:**
Using a little science, technology, and luck, a way to craft thermite with items already in game.

Aluminum Powder + Iron Oxide + Magnesium = Thermite.

So, if we take scrap to the furnace, a lot of it, and attempt to use it, it could result in Iron Oxide.
If we take Aluminum to a mill, or a shop, and grind it on the work bench, it could result in Aluminum powder.

For Magnesium, ez.  Take the recyclable materials, and a fair amount of copper, to the furnace, super heat it to refine materials. From that you may get plastic, perhaps gold bars, maybe even some magnesium strips.

Take the above items to a workbench, say at the forge, and craft "homemade thermite" on a 40-60% success rate (you get one item called "homemade thermite"). Since it is not as refined as the real stuff, perhaps there is an 80% chance of success (it works as intended). But, mixing these things in the forge could be dangerous. Perhaps a 5% chance of the materials igniting, causing you damage. 

**Reason:**
This would utilize some of the existing trash items that people just dump, add a bit of risk, and create a way to obtain more thermite without overpopulating the system with it.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
