### ISSUE TITLE
[game/radio] A way to change the volume on the radio - Suggestion

### ISSUE THREAD

**Issue by CranioDad** [InZidiuZ/op-framework-issue-tracker#866]
**Name:**
CranioDad#0619

**Summary:**
Change the radio to be the one that includes volume management on the radio. Think like NP.

**Reason:**
The radio currently has two settings, on and blaring in your ear. Or off and no communication. There are times that it would be nice to be able to talk to people standing in front of me without having them drown out by radio chatter. It has a tendency to make conversation impossible at times. We know that this can be done, it would be a game changer for RP in and around the city.

**Comment by InZidiuZ** [comment]
With the next update, you'll have to options to control radio sounds.
* `/radio_sounds [volume level (0-1)]` to lower the sound effects.
* `/radio_volume [volume level (0-1)]` to lower the volume of the players talking on the radio.
