### ISSUE TITLE
My games crashes as it get started like my games get loaded completely and after i select my character i click on spawn but it doesn't get spawned and my games crashes and it shows gta5+ something crashed plz help me to fix this crash. 

### ISSUE THREAD

**Issue by itsyphantom** [InZidiuZ/op-framework-issue-tracker#867]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Follow the template.

**InZidiuZ**
*OP-FW Developer*
