### ISSUE TITLE
[jobs/garbage] Garbage collection bug area

### ISSUE THREAD

**Issue by diptej2012** [InZidiuZ/op-framework-issue-tracker#868]
There is one place when reached there with the garbage truck it says return back to HQ without showing any garbage to pick up. It happened 4-5 times with me with that same location. The location is "North Bound | Portola Dr | Spanish Ave | Rockford Hills
![g](https://user-images.githubusercontent.com/17718375/77270780-ae5ff680-6c8b-11ea-8f81-cb72f8ded19b.jpeg)
 "

**Comment by mjankush** [comment]
I also faced this issue, and there are a couple of more such areas where same thing happens, it was working fine till last week, but after last week's maintenance it again started behaving this way.

**Comment by InZidiuZ** [comment]
Use the template. This issue has also already been addressed multiple times. Use the search function to find the responses to it.
