### ISSUE TITLE
[game/sound] Replacing music in PDM

### ISSUE THREAD

**Issue by Imaghost1337** [InZidiuZ/op-framework-issue-tracker#869]
**Name:**
gHo$T#0188

**Summary:**
Change the music in PDM

**Reason:**
As a guy, that spends 2-5 hours a day at PDM, I'm so tired of hearing 2 same songs all the time...yes *2*. I think that putting a radio station instead of having 2 songs on repeat would boost PDM workers productivity by 69%.

**Comment by Livius99** [comment]
Big thumb up for this suggestion.

**Comment by InZidiuZ** [comment]
Any idea as to how? 🤔

**Comment by Imaghost1337** [comment]
I saw a thread that it's possible to replace ambient sounds. The music playing in the building isn't playing from speakers, and has the same volume across all of PDM, excluding the offices. 
I'm not a dev, but what I think can be done, is finding the audio file that plays at PDM, and replacing it in gtav > x64 > audio. 
At least that's how it works with all sounds including anything from sirens, horns to lightning sounds.

**Comment by InZidiuZ** [comment]
This will not be done at this time.
