### ISSUE TITLE
[illegal/chopshop] Change how Chop Shop functions

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/op-framework-issue-tracker#870]
Right now, with Chop Shop being very 50/50 on the rate of vehicles being able to be found, especially if the server is at the full population, I have a suggestion on how to improve Chop Shop. 

**Reasons**
- People aren't fighting over vehicles, 
- People can explore the whole map for the vehicle
- There's no specific plate so less risk of the vehicle not appearing and bugging
- Those who control the chop shop get a consistent set of customers as well as it makes it more prolific for the PD to investigate if the area has a high rate of traffic 
- It adds consistency and less frustration with the whole process

**How it would work**
- Make a timed list that lasts 30-45 minutes at a time. This list contains around 10 vehicles, cars and bikes instead of a specific plate, with the model listed. 
- You use the radio item, found at the hardware store, to deliver the list.  To get the list the radio sends in would be a / command like /chop etc, but the command could only be used if they had purchased the radio. 
- Each time a vehicle is delivered, the list would remove the 1 delivered and people could see the updated list via the /command. 
- Same drops etc from the vehicles delivered, up to those controlling to ensure the economy.

**Comment by Imaghost1337** [comment]
Thumbs up from me

**Comment by CranioDad** [comment]
This could not only make this work, but add a ton of RP and creativeness to the task. Big +1

**Comment by maguhd** [comment]
+1

**Comment by DooZolz** [comment]
As a Lost MC member myself, I can indeed say that this chop shop system needs a bit of a change.

**Comment by twooot** [comment]
The way chop shop works was changed so i'm gonna close this
