### ISSUE TITLE
[vehicles/tunerchip] Rework tuner chip

### ISSUE THREAD

**Issue by Imaghost1337** [InZidiuZ/op-framework-issue-tracker#873]
Name:
gHo$T#0188

Summary:
Tuner chip rework

Reason:
Recently I came into owning a tuner chip, and quickly noticed it doesn't do anything, or VERY, VERY LITTLE.
I think a rework to the tuner chip is essential as many people will want to do something tuner chip related in the future and will be disappointed like me after realizing I've spent money on something that doesn't work on my personal vehicle.

**Comment by Nuziatella** [comment]
After testing on a few vehicles as well as imports this issue can be reproduced handily on any vehicle. There doesn't seem to be any difference outside the notion of a perceived change.

**Comment by Nuziatella** [comment]
This is what the UI looks like. It appears as if the sliders are meant to be centered below the text or the text is to far spaced out. This is at 2560x1440 resolution. 

![tunerchip](https://user-images.githubusercontent.com/67765305/87677060-5328a700-c747-11ea-990d-6da5fb839a62.png)

**Comment by InZidiuZ** [comment]
This has since been fixed.
