### ISSUE TITLE
Bug report - Money has gone from my bank

### ISSUE THREAD

**Issue by Wilsain** [InZidiuZ/op-framework-issue-tracker#875]
**Reporter:**
Wilsain

**Summary:**
I had over 19,000 in my bank before the restart, but when I went back in, I only had 4000

**Steps to Reproduce:**
Logging in?

**Expected Results:**
To keep my money

**Actual Results:**
My money is gone

**Comment by InZidiuZ** [comment]
Thank you for the detailed report I will change the config to resolve this issue.

**Comment by InZidiuZ** [comment]
I've set [this ](https://gyazo.com/395e791038f89035e8d1b9d2addb511f) to false now, it should no longer happen. 25 million $ will be delivered to your account for compensation.

**Comment by Wilsain** [comment]
Thanks for replying so quickly, and I appreciate that.
Do you know how long would that take by any chance?
I've just logged back on to the game and don't see it.

Thanks


________________________________
