### ISSUE TITLE
Bug report - Money gone missing from Bank - Not Resolved.

### ISSUE THREAD

**Issue by Wilsain** [InZidiuZ/op-framework-issue-tracker#876]
**Reporter:**
Wilsain

**Summary:**
I had money missing from my bank and you replied with the solution and resolution recently and then "Closed" the case. But I did not receive my money back nor the compensation I was promised

**Comment by iGreatWhite** [comment]
Compensation is not a thing done around here.

**Comment by Wilsain** [comment]
But I was already promised by InZidiuZ. I just can't seem to get in contact with him.

**Comment by iGreatWhite** [comment]
You should DM him if you feel you need comp.

**Comment by AdeptCL** [comment]
My guy, he was playing with you. There is no compensation methods in place, it cannot be done. The way he responded to your case was because it was a stupid thing to request for.

You ain’t getting a dollar back. The server is in a Alpha-Beta mode. Bugs can happen.

**Comment by AdeptCL** [comment]
Plus, he never promised a single thing.
