### ISSUE TITLE
[illegal/cocaine] Tweak fee-system

### ISSUE THREAD

**Issue by NovaPurplee** [InZidiuZ/op-framework-issue-tracker#877]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is to change the way the plane for coke runs work, instead of having a 1000$ returnable deposit, make it so it is a 1000$ fee for using the plane.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Currently whoever has the ability to run coke and use the plane makes 100% profit from coke
with a drug that is that hardcore and can make stupid amounts of money if done correctly. the main reason why I'm suggesting this change is so it will better help the economy even more than it is and if you are going to be running a hardcore drug there should be fees to doing such things not making 100% profit from these drugs. this can also include other drugs " Oxy " for example could be changed to where you don't double your money but to where you make back $1500 instead of on the $2000 just so people aren't doubling their money or making 100% profit on these things

**Comment by InZidiuZ** [comment]
Closing in favor of #2068 which suggests a total rework of the system.
