### ISSUE TITLE
[game/objects] ATM at Tequi-la-la

### ISSUE THREAD

**Issue by NovaPurplee** [InZidiuZ/op-framework-issue-tracker#878]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
We need an atm in the Tequi la la 
**Reason:**
Why would your suggestion be a good addition to Legacy?
the closest atm is near the exclusive dealership and if people have to buy drinks its silly for them to have to drive away from the RP of being at a bar to drive to an ATM to buy beer etc.

**Comment by z-Lunar** [comment]
This has been resolved. 😄 ty for the suggestion, for the future post in https://github.com/InZidiuZ/legacy-assets/issues -Lunar Assets Team
