### ISSUE TITLE
[jobs/dealership] More vehicles

### ISSUE THREAD

**Issue by mavroses** [InZidiuZ/op-framework-issue-tracker#879]
**Name:**
Mav Roses aka MAVROSES#0402

**Summary:**
I would like to suggest adding limousines and other transport vehicles to the cities to create new business and increase the ways that people can make money and interact with people.

**Reason:**
There are a ton of weddings and VIP+ events happening all the time all around the cities and I would personally love to start a VIP transport service and drive people around in luxurious limousine like vehicles to their set destinations (whether that is a wedding, honeymoon, party etc).

I think this would add a very cool new route for people to make money and also interact with other citizens and also add more competition for different companies.

I already have my future limo/transport company planned out and would love for this to be added!

**Comment by InZidiuZ** [comment]
Could you be a bit more precise as to what vehicles you'd like to see, besides just limousines and 'transport' vehicles?

**Comment by mavroses** [comment]
These would be fantastic:

https://gta.fandom.com/wiki/Patriot_Stretch
https://gta.fandom.com/wiki/Cognoscenti
https://gta.fandom.com/wiki/Stretch

**Comment by iGreatWhite** [comment]
Two of these would be difficult to fit in PDM without an additional slot for long vehicles.

**Comment by mavroses** [comment]
That's what I was thinking too but they'd be great to implement somehow, maybe into exclusive or something

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
