### ISSUE TITLE
Plane didn't arrive [Bug report]

### ISSUE THREAD

**Issue by gmacdev** [InZidiuZ/op-framework-issue-tracker#880]
**Reporter:**
GMAXGO YT#2328 & https://steamcommunity.com/id/GMAXGO/

**Summary:**
I booked the plane but the plane never came and the timer was running 

**Steps to Reproduce:**
Book the plane

**Expected Results:**
The plane arrives

**Actual Results:**
The plane didn't arrive

## Additional Information

**Screenshots:**
https://media.discordapp.net/attachments/693128637909696512/693965752721473566/unknown.png?width=788&height=443
https://media.discordapp.net/attachments/693128637909696512/693967777668792390/unknown.png?width=788&height=443
https://media.discordapp.net/attachments/693128637909696512/693971005093183508/unknown.png

**Game Resolution:**
1920 x 1080 144hz

**Player Data:**
Char id: 5747 But this is after I dc and reconnected

**Server:**
Server India, City 3

**Comment by InZidiuZ** [comment]
Hey,

Clear your cache. If it happens again take a screenshot of your F8 console & create a new report.

**InZidiuZ**
*OP-FW Developer*
