### ISSUE TITLE
[dependency/dpEmotes] DpEmotes keybinds

### ISSUE THREAD

**Issue by Igna28** [InZidiuZ/op-framework-issue-tracker#881]
**Reporter:**
Igna#6192
steam:1100001156ca896

**Summary:**
When you keybind a emote you can't remove it and when you bind any emote and it plays randomly without press any keybind keys.

**Steps to Reproduce:**
Keybind any emote and randomly it start to play solo, sometimes it doesn't happen.

**Expected Results:**
Keybind a emote and when you press it the emote plays immediately and it doesn't play randomly. And have a way to remove the keybind.

**Actual Results:**
When you keybind any emote and it plays randomly wihout press any keybind keys.

## Additional Information

**Screenshots:**
https://streamable.com/76ekh

**Game Resolution:**
1920x1080

**Player Data:**
CID: 719

**Server:**
Latin America

**Notes:**
The only why to fix this I think is delete the keybind row from database. Thanks In Advance.

**Comment by iGreatWhite** [comment]
The key bonds are attached to the aircraft controls in your settings. If you have changed these it will change the way you do your emotes as well.

**Comment by InZidiuZ** [comment]
Hey,

As a temporary fix for this issue, I've added /removebinds which resets all your bindings.

**InZidiuZ**
*OP-FW Developer*
