### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NovaPurplee** [InZidiuZ/op-framework-issue-tracker#883]
**Name:**
Who is suggesting this? Please include discord name.
NovaPurple#0185
**Summary:**
Write a short summary of what your suggestion is about.
a buff to the Mustang GT, as a person that drives this car on a daily basis as a first choice
**Reason:**
Why would your suggestion be a good addition to Legacy?
at semi moderate speeds the car tends to spin out more than any other car I have ever driven, 
Car taps out around 215 (fully tuned) IMO fully tuned this car should prop go a little bit faster than it usually does, acceleration is pretty slow so if that could also be looked at. the mustang gt500 in the city goes faster than this one which Imom shouldn't be a thing lol.

**Comment by InZidiuZ** [comment]
Hey,

Use the asset-related issue tracker.

**InZidiuZ**
*OP-FW Developer*
