### ISSUE TITLE
Suggestion - Whitelisted Mechanic Job

### ISSUE THREAD

**Issue by bhosalevishu** [InZidiuZ/op-framework-issue-tracker#885]
As of now, In Indian legacy server, mechanic job is white listed, so we all mechanics request you to add mechanic roles and their salary also and option to go on duty and off duty in repair shops and place to change clothes, and only mechanic should review vehicles and when he is on duty only.
 can you do this please..?

**Comment by Cricketx818** [comment]
Mechanic jobs will not be white-listed, As inzidiuz said previously many times. So I dont think its going to change

**Comment by bhosalevishu** [comment]
but it is whitelisted in INDIA WHITELISTED

**Comment by iGreatWhite** [comment]
That’s going to have to be something you guys control yourselves if you want to do it that way.
