### ISSUE TITLE
[game/teleporters] FIB Building Elevator Point

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#886]
**Name:**
Duroode#2178

**Summary:**
With the Introdution of the FIB, And the lack of room in PD to Question people, I would like to suggest a possible Elevator point for the FIB building, there is already an Interior on the upper floors Which i have attached below.

**Reason:**
I feel this would be a good edition to help create RP for Detectives/FIB as a whole, having a building where they can conduct their work would make everything feel more professional as a whole.
![fib1](https://user-images.githubusercontent.com/53537974/78264852-9c881a00-74fb-11ea-8e8d-57fc58b2d1af.jpg)
![fib2](https://user-images.githubusercontent.com/53537974/78264857-9db94700-74fb-11ea-863b-d54a162fcfe9.jpg)
![fib3](https://user-images.githubusercontent.com/53537974/78264861-9e51dd80-74fb-11ea-9d09-767bdb338030.jpg)
![fib4](https://user-images.githubusercontent.com/53537974/78264865-9e51dd80-74fb-11ea-94ea-974452901821.jpg)
![fib5](https://user-images.githubusercontent.com/53537974/78264868-9eea7400-74fb-11ea-9c70-0c0c306337d8.jpg)

**Comment by Imaghost1337** [comment]
+1

**Comment by LikeConnorr** [comment]
I'm certainly a +1 for this, but I believe there is a door that would need to be permanently locked due to it giving access to a burnt area.

Correct me if I'm wrong, it should be located towards a staircase.

**Comment by Panda-XV** [comment]
big ole +1 for my FIB friends :D

**Comment by InZidiuZ** [comment]
This has now been done.

**Comment by Duroode** [comment]
Thanks Beautiful, Ill be sure to check it out sometime.
