### ISSUE TITLE
[vehicles/garages]Car is in Garage but when spawning it spawns random cars of the same type but not the one I own

### ISSUE THREAD

**Issue by AmokBSN** [InZidiuZ/op-framework-issue-tracker#887]
**Reporter:**
AmokBSN#3856

**Summary:**
After attempting to get my car fixed at the Lost MC garage, it ended up going onto the roof however the car on the roof wasn't mines? After going to a garage and paying to retrieve, I was now able to spawn random of the same type car but not the one I owned.

No keys were received. 

**Steps to Reproduce:**
I have attached a video showing the reproduced results. 

**Expected Results:**
To have my car

**Actual Results:**
NA

## Additional Information

**Screenshots:**
Video link provided - https://drive.google.com/open?id=1TZTgKkArYLuYHhajC3rYuDDOpm4-ymNY

**Game Resolution:**
1920x1280

**Player Data:**
Marc Goodtouch ID: 116

**Server:**
Legacy EU/NA

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

If this is still an issue with 2.4.2, please create another issue. A screenshot of your F8 console (as asked for) as well as a timestamp would be of good help, might not be able to find the issue if not.

**InZidiuZ**
*OP-FW Developer*
