### ISSUE TITLE
[game/inventory] PD Private Lockers

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#888]
**Name:**
Who is suggesting this? Please include discord name. nilmar#3552

**Summary:**
Write a short summary of what your suggestion is about.
lockers for pd now we have to buy our items 

**Reason:**
Why would your suggestion be a good addition to Legacy?

so we dont lose items after going off duty and more rp than signing in and out we can actually use the locker room to get our items
maybe like multiple areas in locker room so its not crowded in 1 spot

**Comment by InZidiuZ** [comment]
Hey,

This has now been added for both PD and EMS.

**InZidiuZ**
*OP-FW Developer*
