### ISSUE TITLE
Mechanic Repair location not working 

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#889]
**Reporter:**
Nohbob#1028

**Summary:**
Mechanic Repair location not working 

**Steps to Reproduce:**
Go to the Lost MC Repair Garage
Get Materials
Hit R and bring up information for Repairs needed
Hit appropriate key (E for Engine)
Nothing Happens.

**Expected Results:**
Car is Repaired

**Actual Results:**
Nothing happens and vehicle menu no longer appears. 

## Additional Information

**Screenshots:**
https://streamable.com/054uzu

**Game Resolution:**
2560 x 1440

**Player Data:**
Character ID - 11 - Job Data: Mechainc, Los Santos Customs, Tow Driver

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Notes:**
Following the new server, this is an error.

**Comment by Girdeux2k** [comment]
The garage from the docks is functioning the same way.

**Comment by Seferti** [comment]
Actually, none of the repair shops are working. I tried all of them last night.

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved.

**InZidiuZ**
*OP-FW Developer*
