### ISSUE TITLE
Inventory - Weight - Players may not be able to be overweight

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#890]
**Reporter:**
Nohbob#1028, https://steamcommunity.com/id/nohbob/

**Summary:**
I had too many pounds of objects in my inventory and was not effected in any way. 

**Steps to Reproduce:**
Put alot of stuff in your inventory. Nearly 250 weight.
Do an activity that gives items directly to your inventory (Chop, Swimming)
Notice that you can be put overweight without any side effects
[EDIT]Unsure, but I chopped and got some additional items that put me over 250. 

**Expected Results:**
I fallover and get over weight messages

**Actual Results:**
You continue gain items and will go over weight.  

## Additional Information

**Screenshots:**
https://imgur.com/Hb4kpqF

**Game Resolution:**
2560 x 1440

**Player Data:**
Character ID - 11 - Job Data: Mechainc, Los Santos Customs, Tow Driver

**Server:**
Main

**Notes:**
This may only happen with given items in the case of Diving and/Chop.  If I took an item from the ground afterward, it didn't allow me to add more items.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
