### ISSUE TITLE
Unable to use PD items after being downed

### ISSUE THREAD

**Issue by Duroode** [InZidiuZ/op-framework-issue-tracker#891]
**Reporter:**
Duroode#2178

**Summary:**
After going down you are unable to use PD items such as Armour, food and First aid kits.

**Steps to Reproduce:**
Have the items on you, Go down, get back up and attempt to use the items

**Expected Results:**
You should be able to use the items as normal

**Actual Results:**
Items wont be Used.

## Additional Information

**Screenshots:**
https://gyazo.com/8912d1ceac3e89680b9309ad49a108ca

**Game Resolution:**
1920x1080

**Player Data:**
https://i.gyazo.com/c7e727e8aff861faee91495259673643.png

**Server:**
Main Severs

**Comment by Duroode** [comment]
Update: Cant use any items, Not even Normal First aid kits.

**Comment by InZidiuZ** [comment]
Hey,

Not reproducible. Might've been solved when some other issues related to item-uses were fixed. If not, please create another report once a repro is found.

**InZidiuZ**
*OP-FW Developer*
