### ISSUE TITLE
New UI - Food/Water under Monitor's Bezel

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#892]
**Reporter:**
Zurxey#2607 : https://steamcommunity.com/id/Zurxey

**Summary:**
Basically the new UI system isn't fitting to my screen correctly. My food/water is under my bezel for my monitor.

**Steps to Reproduce:**
Just login 4head

**Expected Results:**
The UI should be leveled with the resolution.

**Actual Results:**
UI under monitor bezel

## Additional Information

**Screenshots:**
https://i.imgur.com/ZP1cRV5.jpg
https://i.imgur.com/xwQUAyw.jpg
https://i.imgur.com/EVqRRMx.jpg
**Game Resolution:**
1920 x 1080 - Windowed Borderless

**Player Data:**
Character ID: 132 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**
ily Inzid <3

**Comment by InZidiuZ** [comment]
You have to move your radar in your game settings. The HUD is placed based on its position.

**Comment by ZurxeyH** [comment]
> 
> 
> You have to move your radar in your game settings. The HUD is placed based on its position.

So how would I do this then?

**Comment by InZidiuZ** [comment]
Settings -> Display -> Safezone Size

**Comment by ZurxeyH** [comment]
> 
> 
> Settings -> Display -> Safezone Size

It moves the GTA Default stff, but not Legacy's Custom UI.

**Comment by InZidiuZ** [comment]
Move it then restart your game

**Comment by ZurxeyH** [comment]
> 
> 
> Move it then restart your game

thanks so much beautiful human
