### ISSUE TITLE
Pistol MK2 unable to put away

### ISSUE THREAD

**Issue by Louie656** [InZidiuZ/op-framework-issue-tracker#893]
**Reporter:**
Louie#4475

**Summary:**
I found a pistol MK2 and i put it in the hotkey slot 2 and pulled it out, when i had it out it would not let me put it away or use any other items in my inventory/hotbar. I re-logged, pulled out the same pistol MK2 to see if it would work now and the issue repeated it self. 

**Steps to Reproduce:**
Pull the pistol MK2 out. 

**Expected Results:**
Be able to put it away and use other items in my inventory,
**Actual Results:**
Unable to put the pistol MK2 away and unable to use other items in my inventory.
## Additional Information

**Screenshots:**
![image](https://user-images.githubusercontent.com/63130749/78412662-17405a80-760c-11ea-8e82-5ac3b86468ea.png)

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 488 - Job Data: mechanic, los santos customs, tow driver

**Server:**
Main
**Notes:**

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
