### ISSUE TITLE
Warehouse not working

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#894]
**Reporter:**
@Jepson#1379
https://steamcommunity.com/id/Di-Deli/

**Summary:**
When selling items you don't receive money.

**Steps to Reproduce:**
Have one of the items that you can sell at the warehouse and attempt to sell it.

**Expected Results:**
Item gets removed from your inventory and you get cash added to your balance.

**Actual Results:**
Item gets removed.

**Comment by InZidiuZ** [comment]
Hey,

This has now been resolved.

**InZidiuZ**
*OP-FW Developer*
