### ISSUE TITLE
I didn't receive my weapon from the gun crate

### ISSUE THREAD

**Issue by Jaygo356** [InZidiuZ/op-framework-issue-tracker#895]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Discord - Jaygo#7566
Steam - https://steamcommunity.com/id/ESKETIT456/
**Summary:**
Write a short summary of what you're experiencing.
So I did the hacking for my gun run and I didn't experience any type of issues I then went down to the docks to open my crate to get my weapon and when I opened it, it said I received a Machine Pistol and I checked my pockets and it wasn't there

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
I don't know how to essentially reproduce the issue but I'd assume doing the gun run and then going to the crate and checking if the weapon is in your pockets

**Expected Results:**
What are the expected results?
I was expecting to have a Tec-9 in my pockets that I could move to my hotkeys

**Actual Results:**
What are the actual results?
I didn't receive any item but it told me that I received a Tec-9[Machine Pistol]
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://gyazo.com/1262b66be760e374b0ec2ec7257ce313
Video - https://drive.google.com/file/d/1Q0Ki0i6o2bcXCVlD4ZOeIlV5mFIzZDUL/view?usp=sharing

**Game Resolution:**
What is your game's resolution?
2560X1440

**Player Data:**
Write /info whilst ingame and provide the information you're given.
254
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
From the main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
