### ISSUE TITLE
Tow Trucks - Currently can not spawn in Garage

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#896]
**Reporter:**
Nohbob#1028, https://steamcommunity.com/id/nohbob/

**Summary:**
At this time,  Tow Trucks are unable to spawn from Garages, and show as Unknown Vehicle in Garages. 

**Steps to Reproduce:**
Go to Apartment Garage.
Attempt to Remove Tow Truck
See that's it's listed as CARNOTFOUND

**Expected Results:**
Be able to remove and drive a tow truck

**Actual Results:**
Nothing Spawns when selected in the APT Garage. 

## Additional Information

**Screenshots:**
https://imgur.com/5xlWvkz

**Game Resolution:**
2560 x 1440

Player Data:
Character ID - 11 - Job Data: Mechainc, Los Santos Customs, Tow Driver

Server:
Main

Notes:
Unsure of any additional info, it does bar the Tow Job completely

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
