### ISSUE TITLE
[external/clothes] Dog models

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#897]
**Name:**
Who is suggesting this? Please include discord name. nilmar#3552

**Summary:**
Write a short summary of what your suggestion is about. i believe that dog models shouldnt be open to the public, you should have good reason to play as a dog aka k9, security dog , guard dog for wl gang then u can be reskinned for a dog model

like myself i have been wanting this update for a while i have been roleplaying as a 'dog' aka a human dressed in k9 vest dog looking gloves and a pug mask 

**Reason:**
Why would your suggestion be a good addition to Legacy? stop every person running around as a dog and possibly abusing it

**Comment by KiwiUK** [comment]
+1

**Comment by XBTech** [comment]
> +1

There is an option to like the post use it instead of doing +1

**Comment by InZidiuZ** [comment]
This has since been added-
