### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by riddlevongrump** [InZidiuZ/op-framework-issue-tracker#898]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

RiddleVonGrump#9380
**Summary:**
Write a short summary of what you're experiencing.
PD "Search" command Does not open targets inventory

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

With target in front of you, type /search (cuffed/hardcuffed/uncuffed.

**Expected Results:**
What are the expected results?

Target inventory and one executing commands inventory to open revealing items.

**Actual Results:**
What are the actual results?

Only things that displays is target's cash on hand, inventory screen doesnt open.  

## Additional Information
This was tested last night in a both soft cuff, and a hard cuff situation.  Was also tested by using /search command and then pressing "K" to see if that would do anything.  Only shows your inventory, and ground inventory.  

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
