### ISSUE TITLE
PD Search no working

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#900]
**Reporter:**
Beezy#6584 

**Summary:**
The option of searching and/or stealing isn't working. Currently if a civilian /steal or a cop /search a detained suspect, only their money on hand appears but no inventory shows up. Therefore we can't take anything in anyone's pockets. I'm not sure if this has been reported as i'm not seeing this bug posted.

**Steps to Reproduce:**
/steal and /search doesn't work at all under any circumstance. the command doesn't open up the new inventory due to possible coding error/problems

**Expected Results:**
When /search or /steal their cash on hand is displayed as it is now but also their inventory opens up as well (pockets) to be searched.

**Actual Results:**
Currently when /steal or /search the only thing that appears is cash on hand. Inventory/pockets don't show up at all or flash even for a second.

## Additional Information
N/A

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 4266- Job Data: Law Enforcement, SASP, Cadet 
Timestamp: 2020-04-04 18:03:52

**Server:**
NA server #1

**Notes:**
Hail Hydra

**Comment by InZidiuZ** [comment]
See #898
