### ISSUE TITLE
[game/inventory] First Aid Kits

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/op-framework-issue-tracker#902]
**Name:**
Who is suggesting this? Please include discord name.
LilGrizz818
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is changing the price and weight of First aid kits.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a good addition cause it opens up some room in our inventory cause currently 10 first aid kits weigh in at 50 pounds kinda hard to keep important stuff and also first aid kits

**Comment by iGreatWhite** [comment]
Sometimes I have to use 3 to 4 first aid kits in a fight being at 10 and that being 1/5 of my pocket weights is brutal. Especially as a cop, Pistol Taser Night Stick Flashlight and SMG is already 50 pounds. Food is like 15-20 pounds. Phone is 10 pounds. This is already like 1/2 my pockets.

**Comment by Lilgrizz818** [comment]
hi Sar i am just giving this a little bump <3 cause my pockets are so dam heavy rn

**Comment by InZidiuZ** [comment]
This has now been done.
