### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by shadabrdx2** [InZidiuZ/op-framework-issue-tracker#903]
Reporter:
Who is reporting this? RDX https://steamcommunity.com/profiles/76561198980004007/

Summary:
car livery is not showing in los sentos customes but car in livery

Steps to Reproduce:
need to fix livery issues with my cars

Expected Results:
i can change my car livery

Actual Results:
i can change my car livery my car is windsor with livery

Game Resolution:
1920x1080

Player Data:
legacy india backlist /info- 1035

Server:
legacy india backlist

Notes:

For anything else noteworthy.
https://youtu.be/Tq-fSFtY3gA this is the issue

**Comment by InZidiuZ** [comment]
Hey,

Wait till 2.4.2 and see if it's still an issue then.

**InZidiuZ**
*OP-FW Developer*
