### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by restlesslist35** [InZidiuZ/op-framework-issue-tracker#904]
**Reporter**

MagicGnome#9484

**Summary:**
Taxi cab is unable to spawn. Shows unknown vehicle in garage.

**Steps to Reproduce:**
Go to garage and take vehicle out. 

**Expected Results:**
Select vehicle to remove. Then it spawns

**Actual Results:**
Nothing spawns when I select the vehicle

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This has been resolved already.

**InZidiuZ**
*OP-FW Developer*
