### ISSUE TITLE
[game/tattooshops] Bug report | Tattoos reset / remove on log-out 

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/op-framework-issue-tracker#905]
**Reporter:**
Lady Hope#0723 / https://steamcommunity.com/id/Lady_Hope

**Summary:**
Tattoos are able to be purchased but on relog, they disappear. 

**Steps to Reproduce:**
Purchase tattoos, log out the server then back in

**Expected Results:**
Tattoos should be there and maintained 

**Actual Results:**
Tattoos are erased and your body is blank again

## Additional Information
**Screenshots:**
N/A

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 224 - Job Data: Mechanic, Los Santos Customs, Tow Driver
Character ID: 233 - Job Data: Law Enforcement, SASP, Lieutenant 

**Server:**
EU/NA

**Notes:**
N/A

**Comment by InZidiuZ** [comment]
Does this happen on every load? Was it the same before 2.4?

**Comment by LadyH0pe** [comment]
> Does this happen on every load? Was it the same before 2.4?

It was never an issue before 2.4, it only began after. And yes it happens on every load and it isn't just to myself.

**Comment by InZidiuZ** [comment]
Have you met anyone that it did correctly load for?

**Comment by LadyH0pe** [comment]
> Have you met anyone that it did correctly load for?

I haven't, the entire Lost that I've communicated with haven't retained their tattoos.

**Comment by InZidiuZ** [comment]
Will look into it soon

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
