### ISSUE TITLE
[UI Bug] Livery option Los Santos Customs

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#906]
# Legacy UI Bug Report
**Reporter:** (Example: Anderzenn#0069 | https://steamcommunity.com/id/anderzenn)
Who is reporting this? Please include discord name and your steam profile. 
Cruxer#4806 | https://steamcommunity.com/id/FearingMANiac/
**Summary:**
Write a short summary of what you're experiencing.
When entering the Los Santos Customs with an exclusive vehicle there isn't an option to chose livery in the ui. I know for a fact however that there is a livery on that car as I got Karpenko to add it.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
1) Obtain a Dodger Charger 1969 without a livery
2) drive inside Los Santos Customs and you will find no livery option when there should be
**Expected Results:**
What are the expected results?
A livery option in the Los Santos Customs
**Actual Results:**
What are the actual results?
No livery option in the Los Santos Customs

## Additional information
**Game Resolution:**
What is your game's resolution?
1920*1080
**Notes:**
Not sure if this goes in ui bug report but here we go.

**Comment by InZidiuZ** [comment]
Hey,

In no way is this UI-related. The LS customs is currently being redone. If it's still an issue once it's released, create another issue.

**InZidiuZ**
*OP-FW Developer*
