### ISSUE TITLE
R32 constantly going over bumps.

### ISSUE THREAD

**Issue by MPar22** [InZidiuZ/op-framework-issue-tracker#907]
**Reporter:**
Par#0396

**Summary:**
While driving the R32, the car sounds like it is constantly going over bumps. From time to time, the car has trouble handling and will also randomly flip in the air because of the bumps, causing the car to easily be totaled. I'm not sure if the car is off-balanced causing the constant bumps, but something is throwing the car off. Thanks for taking a look at this issue!

**Player Data:**
Character ID: 1810

**Server:**
Main

**Comment by InZidiuZ** [comment]
Hey,

Use the asset-related issue tracker.

**InZidiuZ**
*OP-FW Developer*
