### ISSUE TITLE
Bug report | Evidence Locker won't open

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/op-framework-issue-tracker#908]
**Reporter:**
Lady Hope#0723 / https://steamcommunity.com/id/Lady_Hope

**Summary:**
Evidence locker will not open. When I go to open it the inventory flashes and closes itself.

**Steps to Reproduce:**
Sign On Duty - Go to the Evidence Locker - Press E to open

**Expected Results:**
The locker should open and be able to add items to its inventory

**Actual Results:**
Locker just flashes as if it will open but closes immediately. 

## Additional Information
**Screenshots:**
https://gyazo.com/ff15010b7f3e5c97d789d6c02c8e37f9

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 233 - Job Data: Law Enforcement, SASP, Lieutenant

**Server:**
EU/NA

**Notes:**
Isn't just happening to me, it's anyone who tries to open the locker. I tried pressing K to open my pockets to see if it would then allow me to access the locker but it just offers to drop an item on the ground.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved. Fix will be live next restart.

**InZidiuZ**
*OP-FW Developer*
