### ISSUE TITLE
[game/health] Addiction system

### ISSUE THREAD

**Issue by kucej** [InZidiuZ/op-framework-issue-tracker#909]
**Name:**
dugzy#9752

Summary:
Well, I was thinking - How to make weed, oxy and coke more usable character-wise, instead of just the "Sell to NPC" option. Right now, you can use weed to get your stress level down, which is fine I guess. My idea was, add more "legal" ways to get the stress level down. The legal ways should not lower it as much as weed (AND coke). Buff the weed to get stress level down even more. BUT add an addiction level bar which would increase, and the more you use weed and coke, the more addictied you get and the more drugs you need to use. If you dont use it , get withdrawal symptoms (Heatlh decline, headaches, nausea?). Add the "Rehab" to pillbox in order to be rehabilitated from addiction? More RP for the EMS there too... Countless possibilities here.

****Reason:**
Why would your suggestion be a good addition to Legacy?**
This would make drugs more usable, instead of just to sell to NPCs, people might start buying off of each other.

**Comment by kucej** [comment]
The legal ways to get the sress level down can maybe be: Watching a movie at a theatre, watching a race at the race track, swimming?, "enjoy the view" option at the top og mount chilliad, ice cream? , bicycling ... idk, just thinking.

**Comment by DaxterPancake** [comment]
I like the idea, but I don't think weed is an 'addictive' drug. I'd suggest the addicition bar be more for 'hard' drugs. Coke and any other mixed drugs we add in the future.

**Comment by Livius99** [comment]
@DaxterPancake you always come around with the best ideas ever!

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
