### ISSUE TITLE
[vehicles/garages] Issue with bike deposit

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#910]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Masik52#5834 

**Summary:**
Write a short summary of what you're experiencing.
tried to store my motorcycle at my house and it says I've stored the vehicle but the vehicle is still out and able to be used.  When I look at my vehicle list it says the vehicle is in the garage but it is still out for me to use.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

Drive to house, go to your garage, attempt to store  vehicle.

**Expected Results:**
What are the expected results?

Vehicle is stored and disappears.

**Actual Results:**
What are the actual results?

Vehicle is still out and able to be used 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![image](https://user-images.githubusercontent.com/52395441/78463649-6ab6b500-76ad-11ea-87ff-c549aa696e7c.png)
![image](https://user-images.githubusercontent.com/52395441/78463652-71452c80-76ad-11ea-8e9d-088fee813228.png)

**Game Resolution:**
What is your game's resolution?
1920 x 1080 
**Player Data:**
Write /info whilst ingame and provide the information you're given.
CID 56 - job data mechanic, los santos customs, tow driver

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
main
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Which bike is it?

**Comment by Masik52** [comment]
Innovation

**Comment by InZidiuZ** [comment]
Are you able to retrieve the vehicle, withdraw it, spawn it, and deposit it with success?

**Comment by InZidiuZ** [comment]
Bump @Masik52

**Comment by Masik52** [comment]
Yes it seems to be working fine now

**Comment by InZidiuZ** [comment]
Great! Think it was related to another solved (maybe not fully yet) issue. Closing for now, if you encounter it after 2.4.4, feel free to reopen the issue.
