### ISSUE TITLE
Items in property storage disappearing.

### ISSUE THREAD

**Issue by MPar22** [InZidiuZ/op-framework-issue-tracker#911]
**Reporter:**
Discord: Par#0396
Steam: Par

**Summary:**
I currently have 155 4oz bags and 151 1oz bags of weed in my storage in my property. When I go to take some of the weed out, it disappears from both my inventory and my property's storage. When I exit out of the inventory screen and go back into my property's storage, all of the weed is back in its spot. The first time I noticed it happen was when I took all of the 151 1oz bags out to go process, and it said I had no weed in my inventory when I began processing. Basically, the weed disappears from my inventory when I move it from place holder to place holder a couple times, then it appears back in my property's storage when I open it up. This will be shown in the screen shots below. If a video is needed, let me know where to send it and I will provide you with one.

**Steps to Reproduce:**
I am not sure how this issue occurred since all I did was transport my weed from one property to the other.

**Expected Results:**
I thought I would be able to access my weed from the storage, but that is not the case.

**Actual Results:**
The weed is unable to be used.

**Screenshots:**
![image](https://user-images.githubusercontent.com/62226246/78466250-17ecf580-76cd-11ea-9255-cc9bb9ccd051.png)
![image](https://user-images.githubusercontent.com/62226246/78466257-220ef400-76cd-11ea-8a2e-409f484aed11.png)
![image](https://user-images.githubusercontent.com/62226246/78466260-2804d500-76cd-11ea-85ee-126f21412401.png)
![image](https://user-images.githubusercontent.com/62226246/78466263-2f2be300-76cd-11ea-9f98-f72248beb5d1.png)
![image](https://user-images.githubusercontent.com/62226246/78466269-38b54b00-76cd-11ea-8d0c-bee207153b58.png)

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 1810 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Server:**
EU/NA

**Comment by MPar22** [comment]
Note: This occurs with every item in my storage crate; I just confirmed.

**Comment by InZidiuZ** [comment]
Same questions as I had for #915.

Did you try restarting your game, and if so, was it the same? Do you also know if it is still an issue after the restart?

**Comment by InZidiuZ** [comment]
Closing in favor of #915. Please respond there once you're able to get back to me.
