### ISSUE TITLE
Able to access trunk inventory while car is locked

### ISSUE THREAD

**Issue by Masik52** [InZidiuZ/op-framework-issue-tracker#912]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Masik52#5834
**Summary:**
Write a short summary of what you're experiencing.
Vehicle is locked yet people are  still able to access the trunk inventory without the vehicle being unlocked
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
lock car, go to the back use /trunk command access inventory
**Expected Results:**
What are the expected results?
trunk is locked and inaccessible
**Actual Results:**
What are the actual results?
trunk inventory is accessible but you can't get into the vehicle without unlocking it
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.
CID 56 job data mechanic, los santos customs, tow driver
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
main
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
