### ISSUE TITLE
Cars - Lock functionality not currently locking trunks of cars 

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#913]
**Reporter:**
Nohbob#1028, https://steamcommunity.com/id/nohbob/
**Summary:**
After locking a car, the trunk is still accessible for anyone to take items from. 

**Steps to Reproduce:**
Get a car
Put items in trunk
Lock Car
Have someone else go into trunk
Can take items from the locked car.

**Expected Results:**
You cannot open the trunk or take items from it

**Actual Results:**
You can open the trunk or take items from it

## Additional Information

**Screenshots:**
Will get shortly. 

Game Resolution:
2560 x 1440

Player Data:
Character ID - 11 - Job Data: Mechainc, Los Santos Customs, Tow Driver

Server:
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Comment by InZidiuZ** [comment]
See #912
