### ISSUE TITLE
[vehicles/garages] Issue with storing vehicles after repairing them. 

### ISSUE THREAD

**Issue by VOiDVato** [InZidiuZ/op-framework-issue-tracker#914]
**Reporter:**
VOiD_Vato 

https://steamcommunity.com/profiles/76561198833447336/

**Summary:**
I pulled out multiple vehicles from my garage to fix them at the Grove Street Mechanic shop. After I finished fixing them in the mechanic shop, I then proceeded to head back to my apartment and store my vehicle. Immediately after storing them I would try and pull them out again and it appears in my garage that they are out of my garage causing me to have to retrieve them. 

**Steps to Reproduce:**
I would begin by pulling a vehicle out of a garage and then repairing that same vehicle. After you complete the repairs head back to an apartment, store the vehicle, and then try retrieving it again. 

**Expected Results:**
You should  be able to see that the vehicle you just stored is in your garage ready to be pulled out at anytime. 

**Actual Results:**
It shows the vehicle is not stored in your garage and is somewhere else. 

**Screenshots:**
https://i.imgur.com/bVOuiH6.jpg.
https://i.imgur.com/vbI7L0H.png
https://i.imgur.com/KhevBfP.png
https://streamable.com/8tm9nv

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 1413 - Job Data: Mechanic, Los Santos Customs, Tow Driver

**Server:**
Main Legacy NA/EU Server

**Additional Information**
This happened to two exclusive vehicles that I own. It was the RX7 and the Subaru WRX. I don't know if that has anything to do with it but they both disappeared after storing them.

**Comment by Masik52** [comment]
This is happening at city garages as well and with normal vehicles not just exclusives.

**Comment by InZidiuZ** [comment]
Hey,

This issue should now be resolved.

**InZidiuZ**
*OP-FW Developer*
