### ISSUE TITLE
[vehicles/garages] Spawn issues

### ISSUE THREAD

**Issue by Livius99** [InZidiuZ/op-framework-issue-tracker#916]
**Reporter:**
Nemmesys#1235
https://steamcommunity.com/id/Nemmesys/

**Summary:**
I'm having issues with my exclusive car , when I get it out of my garage it spawns a stock one with a different plate number , which is not mine

**Steps to Reproduce:**
retrieve it and spawn it out of the garage

**Expected Results:**
I would expect to see my car , who already got partially tuned 

**Actual Results:**
a stock vehicle spawns  with a different color and different plate number every time , I'm unable to store it as well because "it's not mine"

## Additional Information

**Screenshots:**
https://imgur.com/a/yqE9BUG

**Game Resolution:**
1920x1080

**Player Data:**
CID: 239 - Job data : Vehicle Dealership, Premium Deluxe Motorsport, Senior Salesman
Timestamp 2020-04-05 10:55:09

**Server:**
Main server

**Notes:**
I've noticed that all the vehicles have issues with the headlights as well...

**Comment by InZidiuZ** [comment]
Does this happen 100% of the time?

**Comment by Livius99** [comment]
nope , it  actually happened 6 times in a row before the restart and after the restart everything started working correctly

**Comment by InZidiuZ** [comment]
Hmm that's odd. Closing for now. Feel free to reopen or create a new issue if the issue returns
