### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#920]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile. nilmar#3552

**Summary:**
Write a short summary of what you're experiencing. when going down your health bar goes to full green again

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
die and lay there
**Expected Results:**
What are the expected results? for the health bar to be empty to show your down and not think its a bug

**Actual Results:**
What are the actual results? when u go down your health bar goes back to full

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution? 1080-720

**Player Data:**
Write /info whilst ingame and provide the information you're given. 43 cid corporal 

**Server:**
What server/community are you from? Main, India, Bangladesh, etc. main

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
This is not a bug. In order to continue to lay there without respawning, you have to be 'revived' but are stuck into an animation being 'dead'. The health bar is reflecting that your health is full, because it is.
