### ISSUE TITLE
[vehicles/garages] MRPD garage

### ISSUE THREAD

**Issue by iGreatWhite** [InZidiuZ/op-framework-issue-tracker#921]
**Name:**
Who is suggesting this? Please include discord name.
iGreatWhite

**Summary:**
Write a short summary of what your suggestion is about.
Garage at MRPD. Store on duty weapons and other personal belongings at MRPD so we don’t use the evidence locker.
**Reason:**
Why would your suggestion be a good addition to Legacy?
So that the evidence locker doesn’t clog up with random junk that we can be putting in vehicles.

**Comment by twooot** [comment]
I think this is done
