### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#923]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
DegenTheo#2209
**Summary:**
Write a short summary of what you're experiencing.
not being able to spawn or retrive my car
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
not sure

https://gyazo.com/474e808f5fd8c1a751a1009eb43170a8

**Comment by InZidiuZ** [comment]
I'm for real going to ban you

**Comment by DegenTheo** [comment]
why? i am having a fucking bug and im reporting it

**Comment by InZidiuZ** [comment]
IF YOU CAN'T FUCKING READ AND FILL OUT A TEMPLATE, DON'T BOTHER PLAYING HERE

**Comment by InZidiuZ** [comment]
It doesn't take a lot of brain cells to fill out a simple template
