### ISSUE TITLE
[game/commands] Command still works but "This command is not available!" message appears.

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#924]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
DegenTheo#2209
**Summary:**
Write a short summary of what you're experiencing.
When you type a command it tells you its no available but it is
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
type any commands, for example /comp
**Expected Results:**
What are the expected results?
comp should open without any chat message
**Actual Results:**
What are the actual results?
comp opens and it says the command isnt available
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://gyazo.com/7655857426b272b300de88ce9ce5ce22
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
http://prntscr.com/ruuv0d
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Comment by InZidiuZ** [comment]
See #852.
