### ISSUE TITLE
[vehicle/garage]  Unable to retrieve car due to 'not enough money' bug 1

### ISSUE THREAD

**Issue by DegenTheo** [InZidiuZ/op-framework-issue-tracker#925]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
DegenTheo#2209
**Summary:**
Write a short summary of what you're experiencing.
I am trying to spawn my car at garage C and it doesnt let me. It says its in garage C. I cant retrieve it because it says i dont have enough money but i do.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Not sure exactly. It seems i am the only one with this proble?
**Expected Results:**
What are the expected results?
YOur car spawns and you have no problem
**Actual Results:**
What are the actual results?
my car doesnt spawn and i cant retrieve it
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://gyazo.com/b2dc4b2692a3e20b9af68ba32095773f
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
http://prntscr.com/ruuwrb
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main
**Notes:**

**Comment by DaxterPancake** [comment]
Hey!

Can you please clear your cache and then let me know if you are still experiencing this issue?

Thanks!

**Comment by InZidiuZ** [comment]
Hey,

Doesn't seem like this is an issue any more. Might've been caused by me pushing changes while the server was live, or I already resolved it & forgot I did so. Tested both locally and on the live server.

**InZidiuZ**
*OP-FW Developer*
