### ISSUE TITLE
[vehicle/garage]  Unable to retrieve car due to 'not enough money' bug 2

### ISSUE THREAD

**Issue by TCruxer** [InZidiuZ/op-framework-issue-tracker#926]
**Reporter:**
Cruxer#4806 | https://steamcommunity.com/id/FearingMANiac/

**Summary:**

When I try to retrieve a car it states "You do not have enough account balance in either of your accounts.." when I actually do.

**Steps to Reproduce:**
1) I bought a car from the exclusive dealership and instead of putting me in the car it left me inside of the dealership and didn't spawn the car.
2) I went to the closest garage to retrieve it but when when I went to do so it stated not enough account balance. I tried multiple garages

**Expected Results:**

Takes 250$ out of my cash and retrieves the car

**Actual Results:**

Nothing except the message prompted as shown in the screenshots.

## Additional Information

**Screenshots:**
https://imgur.com/a/esyDxsy

**Game Resolution:**
1920 - 1080

**Player Data:**

https://imgur.com/a/esyDxsy

**Server:**
Main server

**Comment by DaxterPancake** [comment]
Hey!

Can you please clear your cache and then let me know if you're still experiencing this issue?

Thanks!

**Comment by InZidiuZ** [comment]
Hey,

Doesn't seem like this is an issue any more. Might've been caused by me pushing changes while the server was live, or I already resolved it & forgot I did so. Tested both locally and on the live server.

**InZidiuZ**
*OP-FW Developer*
