### ISSUE TITLE
[game/login] More character slots

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/op-framework-issue-tracker#928]
**Name:**
Who is suggesting this? Please include discord name.
LilGrizz818
**Summary:**
Write a short summary of what your suggestion is about.
Adding more character slots. 
I have 4 characters already and there all important so i could never make another char for fun and to try new things. Im sure alot of people are on the same boat cause ATM i have ems char, PD char , State and Crim so id love to be able to have maybe around like 6 characters ? just to let us have a chance to expand.
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a really good addition cause it would Increase the RP and let people cry out more new things More characters more fun more stories basically.

**Comment by Panda-XV** [comment]
I mean, what would you do on those other 2 characters, you already have all the big things covered.

**Comment by DaxterPancake** [comment]
Some people would like more slots so they can roleplay more characters, not just the same 4 they play all the time.. I don't understand telling someone they've got all their big things covered when it's roleplay and every character someone makes is vastly different and brings new roleplay to the city.
I'd love to see more slots. I'm having to delete and re-make characters when I want to play them again.

**Comment by Lilgrizz818** [comment]
Me personal would love the extras so i can maybe one day make one life chars or even a char that comes around to increase others RP and what not theres plenty of stuff i could do with the extra slots i just dont want to have to delete one of my main chars for all that stuff @Panda-XV

**Comment by InZidiuZ** [comment]
Hey,

With the login UI and entire core being rewritten, supporters (most likely) will be able to take advantage of additional slots. The default would remain 4.

**InZidiuZ**
*OP-FW Developer*
