### ISSUE TITLE
[illegal/banks] Change bank cooldown to 1 hour

### ISSUE THREAD

**Issue by Brundoggy** [InZidiuZ/op-framework-issue-tracker#929]
**Name:**
Who is suggesting this? Please include discord name.
Brundoggy
**Summary:** Banks having a 1 hour cool down rather than 30 minutes.

**Reason:**
Why would your suggestion be a good addition to Legacy?

Cops deal with bank jobs a lot and feel the RP with it is rushed. Such as this; bank is closed almost immediately after the criminals leave. They have a chase which can take a while if they are good about it,  there is about 30 minutes with 2/3s of the police force being used, not to mention that they have to do reports and collect any potential evidence as well, forcing the RP to be rushed as the next bank pops off. So I feel that banks should be pushed to an hour to allow actual RP to happen rather than having a half-@$$ed response to the banks.

Also would like to see store/jewelry robberies as well :)

**Comment by Vedder742** [comment]
I can't stress this enough, by the time we finish a bank scenario **properly** the cooldown ends and we GET ANOTHER ONE, WHILE STILL PROCESSING THE SUSPECTS FROM THE LAST

**Comment by Phunkadelia** [comment]
The amount of bank robberies we respond to is insane. It seems as if it's the only thing we do when there are 4+ cops on duty. A global one hour cooldown will allow us to respond to other scenarios without having to ditch them half way through to respond to a 10-90. Groundhog day with these bank heists. This change needs to be pushed through by senior command. This is an issue that WILL and HAS caused officers to leave or decrease their playtime, thus negatively impacting the servers health and overall roleplay quality.

For the love of half decent roleplay please **implement a one hour global cooldown**!

**Comment by joevapes3** [comment]
I really wish this, and the cop amount requirement for banks to hit-able increased came into fruition. Currently we have severe burnout happening in PD where people are feeling completely defeated with the amount of back to back robberies. If it only happened every now, and then it wouldn't be a huge deal for us to get changed. However people are literally queuing inside banks waiting for cops to get online. Then when they hit the first bank, they continue queuing at the 30 minuet mark on the dot. As of right now criminals know they have a 50/50% chance to hit a bank without any cops showing up at all, cause they're either down from getting shot up on the previous robbery, still in the chase, or transporting downed PD members or suspects to the hospital then MRPD. This is causing people to sit on the corners near every bank robbery watching the status of the current robbery to min/max weather they need a hostage for the next one.

**Comment by iamlapi** [comment]
+ Infinity sign this one

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
