### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by adityadevharkar** [InZidiuZ/op-framework-issue-tracker#930]
**Name:**
Who is suggesting this? Please include discord name.

**Summary:**
Write a short summary of what your suggestion is about.

**Reason:**
Why would your suggestion be a good addition to Legacy?

**Comment by DaxterPancake** [comment]
Hey! 

I'm not sure if you noticed but you havn't written anything here! I'll give you a few hours to correct this, if not then I will be closing this.

Thanks!

**Comment by DaxterPancake** [comment]
Closing due to incorrectly filling out forum.

Feel free to make a new one if this was a mistake.
