### ISSUE TITLE
[game/inventory] Lockpicks

### ISSUE THREAD

**Issue by maguhd** [InZidiuZ/op-framework-issue-tracker#931]
**Reporter:**
MaguHD#8534
https://steamcommunity.com/id/maguhd/

**Summary:**
Bought this lockpick when update 2.4 hit, and I still have it. It broke like 10 times, never dissapeared from my inventory. I dont know if it happens with normal lockpicks thou cuz i never used one.

## Additional Information

**Screenshots:**
https://prnt.sc/rvm4rp
https://prnt.sc/rvm4ym
https://prnt.sc/rvmbmt
https://prnt.sc/rvmpr6

**Game Resolution:**
1920*1080

**Player Data:**
https://prnt.sc/rtbzut

**Server:**
Main

**Comment by InZidiuZ** [comment]
Hey,

This issue should now be resolved.

**InZidiuZ**
*OP-FW Developer*
