### ISSUE TITLE
[game/inventory] Apartment storage flickering/unable to open

### ISSUE THREAD

**Issue by Terry-Crews** [InZidiuZ/op-framework-issue-tracker#932]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Xwezio#5716     https://steamcommunity.com/id/Xwezio/

**Summary:**
Write a short summary of what you're experiencing.
Unable to access the storage box inside my apartment the UI flickers then disappears

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Just let the storage box mature

**Expected Results:**
to be able to use and access my box 

**Actual Results:**
Ui flickers and no access to the inventory in the box

## Additional Information
https://clips.twitch.tv/SucculentTemperedDelicataOSkomodo
**Screenshots:**

![image](https://user-images.githubusercontent.com/55332094/78980274-7d017a80-7b15-11ea-9abd-8642dc4f42af.png)

**Game Resolution:**
1920x1080

**Player Data:**
Character ID: 27-Job Data: Mechanic, Los Santos Customs, Tow Driver
Timestamp : 2020-04-10 10:25:03

**Server:**
Main

**Comment by InZidiuZ** [comment]
Hey,

The cause of this issue has been pinpointed and resolved. Your container should become available again with a server restart regardless of the fix being live.

**InZidiuZ**
*OP-FW Developer*
