### ISSUE TITLE
[properties/blocks] /removeblock command

### ISSUE THREAD

**Issue by GuArDiAn-ops** [InZidiuZ/op-framework-issue-tracker#933]
**Name:**
Who is suggesting this? Please include discord name.
GUARDIAN #3000
**Summary:**
Write a short summary of what your suggestion is about.
So my suggestion of the feature is about adding a /removeblock for the state department to able to remove a block from a company as  in real life state department would usually hold power be able to remove a block from a company. It can be the command like the state department uses /sellblock we can use /removeblock to use in many situations such as if the company owner is no longer in the city or it can also kinda help state play an eviction rp of sorts. a cooldown can be added upto 7 days or before it can be transferred to a different company like we can rp it like a court or a judge has given a green light for eviction. 
**Reason:**
Why would your suggestion be a good addition to Legacy?
I think this suggestion would be a good addition to legacy because it would give state additionally rp in the variety of company being in loss due to debt or the company owner not being in city and state department can play a good rp with the court and lawyers with to go with eviction or a variety of options for rp.

**Comment by InZidiuZ** [comment]
This has now been added with version 3265.
