### ISSUE TITLE
[assn: damage control] Nerfed Weapons

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#934]
**Name:**
@Jepson#1379

**Summary:**
Gunplay needs to be more balanced:
Heavy Revolver MK2: from 1 shot to 2 shot
Heavy Revolver: from 2 shot to 3 shot
(Can still be oneshot headshot)

Musket - removed

**Reason:**
It is not healthy for a roleplay server where there is guns that can shoot you from almost out of render distances. A concealable pistol that can oneshot is not helping either. I like that there is variation, but they can't be this powerful. They blow up cars, it's crazy how much power is packed into one.

**Comment by InZidiuZ** [comment]
Damage levels for all weapons are currently being reworked. If you have additional feedback for improvements after 2.5, please create another issue.
