### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Lilgrizz818** [InZidiuZ/op-framework-issue-tracker#935]
**Name:**
Who is suggesting this? Please include discord name.
LilGrizz818
**Summary:**
Write a short summary of what your suggestion is about.
I think we should get bennys to start repairing cars again.
Of course i dont want to take away from the mechanics Roleplay but at this point people arent even really repairing cars due to the fact that literally almost every cars glitches and disappears im tired of having to wait 30 minutes trying to find ways to retrieve the car asking for rides and paying double all the time. I was thinking so we dont take away Mechanics jobs maybe we can get a system in bennys where you only get 50-75% Engine repaired and the for you to get it 100% youd have to take it to a mechanic for the further repairs.  
**Reason:**
Why would your suggestion be a good addition to Legacy?
I think it would be a great addition cause people have been experiences the same struggles and this would save alot of people from losing car upgrades forgetting to save it before a repair. Also will save alot of time and people wont have to retrieve over and over

**Comment by AdeptCL** [comment]
I agree to some extent. 
However, I think it would be better for the server to exterminate the bugs crawling in the mechanic shop so that mechanics are able to function again.

**Comment by LikeConnorr** [comment]
Although the function you're suggesting is great, simply deterring away from the fact that there is a bug isn't healthy, and instead the issues caused in the mechanic shop as mentioned above should be considered/fixed first.

**Comment by InZidiuZ** [comment]
Will close as this has already been confirmed it'll be a thing in the future.
