### ISSUE TITLE
[?] Addition of a racetrack

### ISSUE THREAD

**Issue by nilmartwitch** [InZidiuZ/op-framework-issue-tracker#936]
**Name:**
Who is suggesting this? Please include discord name. nilmar#3225

**Summary:**
Write a short summary of what your suggestion is about.
a racing area built around the airport in to the ocean

**Reason:**
Why would your suggestion be a good addition to Legacy?
it woukd be good then we could hold legal race events like laps or drag races also gives the opportunity for a race company to be around 

sorry if this isnt frame work i just know its only possible by u

**Comment by InZidiuZ** [comment]
Right now all assets are pushed to all servers (for the most part), so this won't be added at this time. In the future the plan is to set up a website/control panel for OP-FW servers allowing server managers to quickly toggle different assets. Once that happens, we'll set the asset issue tracker up to allow for more suggestions such as this one, and we'll be able to make different "asset" packs, including a pack for what's suggested here. Though you'd have to recreate this issue/suggestion once that time comes.
