### ISSUE TITLE
[game/inventory] Advanced Lockpick not working / breaking instantly

### ISSUE THREAD

**Issue by Seferti** [InZidiuZ/op-framework-issue-tracker#937]
**Reporter:**
seferti#9792  https://steamcommunity.com/id/Seferti/

**Summary:**
I don't know if I have bad luck, but every time I use an advanced lockpick, it either breaks after one use, or it just doesn't work, i can get a video of this later when i am back in the server. 

**Steps to Reproduce:**
Make it so the lockpicks work and do not break after one use

**Expected Results:**
Advanced lockpicks should work, and shouldn't break after one use. 

**Actual Results:**
Sometimes they work and every time it works for me they break after one use

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
CID- 125

**Server:**
Main

**Notes:**
For anything else noteworthy.

**Comment by Masik52** [comment]
This was happening to me last night. If I used the advanced lockpick from the hotkey to hotwire a vehicle it would do the progress bar but never actually work and I could try to lockpick it again with the hotkey and got the same result.  If I used the lockpick from inventory it would work and the lockpick would break after one use.

**Comment by Seferti** [comment]
> This was happening to me last night. If I used the advanced lockpick from the hotkey to hotwire a vehicle it would do the progress bar but never actually work and I could try to lockpick it again with the hotkey and got the same result. If I used the lockpick from inventory it would work and the lockpick would break after one use.

Good to know it's not just me having this issue with advanced lockpicks

**Comment by Masik52** [comment]
Here is a video of what's happening using the advanced lockpick on a hotkey and then just using it from inventory.  https://youtu.be/P3iAhvf3ZD0

**Comment by InZidiuZ** [comment]
This issue has now been resolved.
