### ISSUE TITLE
Dispatch Animation Doesn't Work..In Legacy BD

### ISSUE THREAD

**Issue by darkness96240** [InZidiuZ/op-framework-issue-tracker#938]
When Clicking Middle mouse button to Talk in Dispatch,Dispatch animation doesn't work..
![Screenshot (17)](https://user-images.githubusercontent.com/62806122/79084037-8a0bad00-7d53-11ea-80c6-3b12a17f7ac1.png)

**Comment by DaxterPancake** [comment]
Hi,

This is the incorrect format to issue a bug report. Please refer to [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose) and select the Bug Report. Though, this may not be an bug but instead you've selected a key that is conflicting with a different bind. 

I will be closing this. Please re-submit with the correct format and information.

Thanks,
**Daxter.
Project Manager.**
