### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Beardgryll** [InZidiuZ/op-framework-issue-tracker#939]
New Mask: Thinking to add some new masks in the masks section of some popular cartoon characters like doraemon, nobita, giyan and shinchan so that it will be more fun when people do robbery or  just chilling.

**Comment by TCruxer** [comment]
Hey, 

This is the wrong issues/suggestions tracker please use the following [GitHub](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues/new/choose) tracker for this suggestion.

**Cruxer   _Lead Assets Developer_**
