### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rajatchoudhary7829** [InZidiuZ/op-framework-issue-tracker#946]
**Reporter:**
my name is mr. Jason Rajatchoudhary#4212 https://steamcommunity.com/id/Rajatchoudhary/
**Summary:**
after this new update 
1) my health auto drain
2) i cant see other players they auto disappear sometimes i can see sometimes i can only hear them
3) i cant connect to voice chat i did every settings of voice chat

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Follow the template.
