### ISSUE TITLE
[illegal/coke] Coke Plane causing players to crash

### ISSUE THREAD

**Issue by RandomKilled** [InZidiuZ/op-framework-issue-tracker#947]
**Reporter:**
RandomKilled#0300
https://steamcommunity.com/id/RandomKilled/

**Summary:**
Recently many players have been trying to fly the plane but are unbale to as their game crashes either when they try to take off. Not all are experiencing this issue but a good amount of players are. This has been tested and only happens when using your mouse to control the plane.

**Steps to Reproduce:**
Pull out the plane at grapeseed

**Expected Results:**
To fly to the waypoint to collect the drop and fly back towards the airfield

**Actual Results:**
Game crashing right as you left click to take control of the plane with the mouse

## Additional Information

**Screenshots:**
https://images-ext-1.discordapp.net/external/59dDtNT08LP40b4-uUQEraRSoMUvU8GP5x-2vqMxoJM/https/i.gyazo.com/thumb/1200/65c15897ec154f17448b9de6912f9ba3-jpg.jpg?width=553&height=454

**Game Resolution:**
1920x1080

**Player Data:**
https://gyazo.com/39660a7508d1ada1514d7bdf6d9be2e9

**Server:**
Main Server

**Notes:**
This doesnt happen to everyone but still alot of players are experiencing the same crash and error code

**Comment by Lilgrizz818** [comment]
Yeah the second i left click my mouse it automatically crashes. This is the crash report we all get https://gyazo.com/73c47bbd702cabd66f9525455f7ee276

**Comment by Seferti** [comment]
> Yeah the second i left click my mouse it automatically crashes. This is the crash report we all get https://gyazo.com/73c47bbd702cabd66f9525455f7ee276

I searched the crash code on the FIveM forums and it's something to do with all aircraft, try it with a plane from the airport and see if it does it.

**Comment by InZidiuZ** [comment]
It's a FiveM issue. You'll have to wait for them to resolve it.
