### ISSUE TITLE
Bug report Regarding random spawn and money in meth sales.

### ISSUE THREAD

**Issue by Beardgryll** [InZidiuZ/op-framework-issue-tracker#948]
After server leaving and entering in it again is getting me spawn at random locations far from the main city and it waste time to get to the city by travelling. 

in meth sales the amount of money for we get is proportional to the number of police in the city, maximum amount earlier was 2100 for more than 5 police, now it only gives 1000 no matter how much police is there, please fix this issue so that we will make good money working in the city. nobody will be playing if they will face this issue from the most done jobs.

**Comment by AdeptCL** [comment]
1) You didn’t follow the template of the bug report. 
2) You can only access the city when you login via the train or bus stations or property if you own any. 
3) We don’t have meth in this server. Are you sure you’re on the right server?

**Comment by InZidiuZ** [comment]
^I am very certain you're mixing servers... x)
