### ISSUE TITLE
[subdivison/india] /repair on ems silverado not working

### ISSUE THREAD

**Issue by Guardian3-1** [InZidiuZ/op-framework-issue-tracker#949]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GuArDiAn#0031
**Summary:**
Write a short summary of what you're experiencing.
We tried to use /repair on ems silverado but we occured the error only emergency vehicles can be repaired
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take out ems silverado and do /repair on pillbox.
**Expected Results:**
What are the expected results?
The vehicle should be repaired
**Actual Results:**
What are the actual results?
The error comes that only emergency vehicles can be repaired
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://imgur.com/a/ExtLuDR
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://imgur.com/a/ExtLuDR
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
India WL
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

The Silverado is being removed, so this will not be fixed.

**InZidiuZ**
*OP-FW Developer*
