### ISSUE TITLE
[?] Addition of using radio emote

### ISSUE THREAD

**Issue by Yusuf0007** [InZidiuZ/op-framework-issue-tracker#950]
**Name:**
@𝕐𝕦𝕤𝕦𝕗#0007
**Summary:**
In bangladesh subdivision police can not use radio emote automatically which sometime causing poor rp quality and causing a massive confusion that police/ems are doing meta instead of doing rp. Fix it please its a humble request from the SASP Bangladesh and LSFD Bangladesh. We want to do some quality rp beside of these complain as we know you guys are working hard but please fix these as soon as possible.

**Reason:**
As the member of SASP i thing using radio emote while using dispatch is a good quality rp. And it should be automated because using /emote is sometime very hard in many situation so fixing it would add some extra fun.

**Comment by InZidiuZ** [comment]
TokoVoip automatically create an animation though...? If not, then please create a bug report using that template instead.
