### ISSUE TITLE
[subdivison/india] Not enough money to retrieve bug

### ISSUE THREAD

**Issue by FuturisticGamerYT19** [InZidiuZ/op-framework-issue-tracker#951]
**Reporter:**
Discord : Futuristic Gamer#4131 (Steam : Futeristic Gamer YT)

**Summary:**
I bought a car from PDM yesterday around 10PM. His name was Hari Kumbhar.
When i bought it, he said that the car has directly gone in the garage because of a bug.
He said got to garage and try to retrieve the vehicle. I am trying to do that but it gives me error that you don't have money available in both of your accounts. But i do have it.

**Expected Results:**
I expect that you will be able to get everything sorted.

## Additional Information

**Screenshots:**
I have attached the video clip.

**Player Data:**
Player Name : Bunty Chatriwala, DOB : 10-10-1993.

**Server:**
Legacy Roleplay India #2 .

Video Clip Link : https://photos.app.goo.gl/wXA5p2xUuHB5edAY9

![FiveM - Legacy Roleplay India #2 _ Custom Housing w_Furniture _ Custom Framework _ Active Staff_Development _ Join us @ discord gg_ehNU9xP 14-04-2020 12_47_21](https://user-images.githubusercontent.com/63635686/79198444-1e0f6e80-7e51-11ea-9876-02db7c7848d1.png)

**Comment by DaxterPancake** [comment]
Hi,

We've has past players fix this issue by clearing their cache. Please try this.
If it doesn't work, please let us know. 

Thanks, 
**Daxter.
Project Manager.**

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved in a later version not yet available in your server.

**InZidiuZ**
*OP-FW Developer*
