### ISSUE TITLE
[subdivison/india] trunk not opening

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#952]
Reported by RitikBakshi#4798

**Summary:**
When i try to open trunk of my own vehicle it just doesnt open .

**Steps to Reproduce**
Go near your vehicle’s trunk and type /trunk but it don’t do anything

**Expected Results:**
I expect you to fix this ASAP

**Actual Results:**
when typing /trunk the trunk should open

**Game Resolution:**
1080p

**Player Data:**
Character ID-4082.

**Server:**
Indian server

**Notes:**
Just fixed bugs ASAP

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved in later version not yet available in your server.

**InZidiuZ**
*OP-FW Developer*
