### ISSUE TITLE
[subdivison/bangladesh] Vehicles dissapearing after purchase

### ISSUE THREAD

**Issue by darkness96240** [InZidiuZ/op-framework-issue-tracker#953]
**Reporter:**
DaRKNeSS#6969.   https://steamcommunity.com/profiles/76561198994558226/
**Summary:**
News Van,Taxi,PDM vehicles are disappearing from purchased after purchasing them.It says vehicle not owned when you try to store it
**Steps to Reproduce:**
Buy any Vehicle  From the Jobs or PDM vehicle.

**Expected Results:**
Vehicle should't disappear from purchased and should be storeable.

**Actual Results:**
First it will tell you to hotwire it then it won't store in garrage also.

## Additional Information

**Screenshots:**
https://imgur.com/8ui45bk
https://imgur.com/4P1eOVw
https://imgur.com/V7rT3es
**Game Resolution:**
1366x768

**Player Data:**
https://imgur.com/V7rT3es

**Server:**
Bangladesh Public #1

**Notes:**
It is happening to everyone in the server.

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved in a later version not yet available in your server.

**InZidiuZ**
*OP-FW Developer*
