### ISSUE TITLE
[subdivison/india] Voice not transmitting on phone call

### ISSUE THREAD

**Issue by praveenprk25** [InZidiuZ/op-framework-issue-tracker#954]
Praveen 
@praveenprk25#9757
 While maing a call in normal server , we cant hear each other may be because of no tokovoip available in indian normal server.

**Expected Results:**
CAN HEAR EACH OTHER OVER A CALL

**Actual Results:**
NO VOICE

## Additional Information

**Game Resolution:**
High

**Server:**
Indian normal server

**Comment by ghostfreak070** [comment]
same for Legacy Bangladesh its not working

**Comment by InZidiuZ** [comment]
Hey,

Once TokoVoip was given to all the subdivisions' servers, this should be resolved.

**InZidiuZ**
*OP-FW Developer*
