### ISSUE TITLE
Car key issue when buy

### ISSUE THREAD

**Issue by 7837452956** [InZidiuZ/op-framework-issue-tracker#955]
Legacy bangladesh server face the problem of car issue when people buy a car money is desucyed but car is not owned in any harage or anywhere

**Comment by DaxterPancake** [comment]
Hi, 

Due to you not using the template provided I will be closing this issue.
Please go [HERE](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose) and select the bug report and fill in each section with as much detail as you can.

Thanks,
**Daxter.
Project Manager.**
