### ISSUE TITLE
[subdivison/bangladesh] Buying Taxi/News Van or even From PDM its not working

### ISSUE THREAD

**Issue by ghostfreak070** [InZidiuZ/op-framework-issue-tracker#956]
**Reporter:**
GhostFreak#8785 

**Summary:**
People in Legacy Bangladesh they are facing a bug which is they can not but any taxi/news van or PDM cars.After purchasing the car its showing "Hotwire Option" Even they are unable to store it on Garage.

**Expected Results:**
It should working normally like before the update.

**Actual Results:**
Currently Its broken and people are facing too much problems because of this

n

**Screenshots:**
https://media.discordapp.net/attachments/641983766285254686/699055209799745536/too.png?width=1086&height=611

**Game Resolution:**
1920*1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
Legacy Bangladesh

**Notes:**
![taxi](https://user-images.githubusercontent.com/59240289/79224697-d510e780-7e5b-11ea-91b8-098a1ba7005c.png)

**Comment by InZidiuZ** [comment]
Hey,

This issue has been resolved in later version not yet available in your server.

**InZidiuZ**
*OP-FW Developer*
