### ISSUE TITLE
[subdivision/india] coke plane doesn’t appear 

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#957]
**Reporter:**
RitikBakshi#4798.

**Summary:**
When i try to take coke plane i press E button and 1000$ cuts off but the plane just don’t spawn in the hanger  

**Steps to Reproduce:**
Just go to airstrip and press E and it will deduct 1000$ but won’t give you a plane.

**Expected Results:**
When pressing E plane should come 

**Actual Results:**
plane does not come but money gets deducted 

**Game Resolution:**
1920*1080

**Player Data**
4082

**Server:**
Indian server

**Comment by InZidiuZ** [comment]
Does this happen every time?

**Comment by InZidiuZ** [comment]
Closing due to no response.
