### ISSUE TITLE
[jobs/garbage] 'Return to HQ' at Rockford Hills

### ISSUE THREAD

**Issue by ceann1337** [InZidiuZ/op-framework-issue-tracker#958]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
ceann#6815
**Summary:**
Write a short summary of what you're experiencing.
At Rockford Hills garbage collection point it always tells me to 'Return to HQ' as soon as i get there.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Start garbage job, Go to collection point in Rockford Hills.
**Expected Results:**
What are the expected results?
Should tell you to start collecting trash and not tell you to instantly return to HQ before any trash has been collected.
**Actual Results:**
What are the actual results?
Get 'Return to HQ' message.
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
![20200414154857_1](https://user-images.githubusercontent.com/61167023/79239701-c7ae2a00-7e68-11ea-9396-c26a7469732c.jpg)
![20200414154905_1](https://user-images.githubusercontent.com/61167023/79239706-c846c080-7e68-11ea-9a41-4bf0c338cbee.jpg)
![20200414160107_1](https://user-images.githubusercontent.com/61167023/79240022-270c3a00-7e69-11ea-9885-576489f1053b.jpg)

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID: 390, Job Data: Government, Waste Collector, Employee.
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main server
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
See #688. This won't be resolved unless a full rewrite of the garbage job is done, which will probably happen at some point in the future.
