### ISSUE TITLE
[jobs/fishing] Addition of fishing

### ISSUE THREAD

**Issue by ceann1337** [InZidiuZ/op-framework-issue-tracker#959]
**Name:**
Who is suggesting this? Please include discord name.
ceann#6815
**Summary:**
Write a short summary of what your suggestion is about.
Add a fishing job into the server.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Because it would be an excuse to get out onto the sea or go wading. Could set up a bait shop with different bait, Maybe even a fishing skill level and a meat shop were you could sell your fish.

**Comment by DaxterPancake** [comment]
Closing in favour of #766 

Cheers,
Daxter
Project Manager.
