### ISSUE TITLE
Bug report | games Crashes when i try to reach Sandyshores

### ISSUE THREAD

**Issue by AliRajpoot4275** [InZidiuZ/op-framework-issue-tracker#960]
**Reporter:**
Discord : AliRajpoot#4275 
Steam : AliGamingYt

**Summary:**
Everytime when i go to sandyshores to my house or just reach the place my game just get crashed. I tried to check it several times and it happens again and again

**Server:**
Legacy Roleplay india

**Notes:**
please fix it As soon as posible

**Comment by DaxterPancake** [comment]
Hi,

This sounds like a FiveM issue or an issue on your end. I'd suggest clearing your cache and if that doesn't work then unfortunately you'll have to wait until FiveM resolves it on their end. 

Thanks,
**Daxter.
Project Manager.**
