### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DarkD1d** [InZidiuZ/op-framework-issue-tracker#962]
**Name:**
Who is suggesting this? Please include discord name.
Alfie#4022

**Summary:**
Write a short summary of what your suggestion is about.
The ability to be able to remove the roof on the buccaneer and chino lowriders.

**Reason:**
Why would your suggestion be a good addition to Legacy?
Allows people to customise vehicles more.

**Comment by DaxterPancake** [comment]
Hi,

This is not a framework issue. This is an issue for [THIS](https://github.com/InZidiuZ/legacy-assets-issue-tracker) github that handles the assets for the server. Please post your issue over there.

I will be closing this.

Thanks,
**Daxter.
Project Manager.**
