### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#963]
**Reporter:**
RitikBakshi#4798
**Summary:**
when i try to take out my vehicle from garage it says there is a vehicle blocking at the spawn point but the garage is clean no other vehicle is there

**Steps to Reproduce:**
Go to any garage and try to take out your car or bike

**Expected Results:**
Vehicle should spawn or withdraw without any issue

**Actual Results:**
it doesn’t spawn and says there is a vehicle blocking at the spawn point

**Game Resolution:**
1920*1080

**Player Data:**
4082

**Server:**
Legacy roleplay India

**Comment by DaxterPancake** [comment]
Are you still having this issue?

Unfortuantly with One Sync these issues do happen and it is out of our control.

It should have fixed itself after a restart.
