### ISSUE TITLE
[jobs/mechanic] Transforming the former "Los Santos Customs" shop in Paleto Bay, to a functional mechanic shop.

### ISSUE THREAD

**Issue by AdeptCL** [InZidiuZ/op-framework-issue-tracker#964]
**Name:**
AdeptCL#0402
Con#0053

**Summary:**
Transforming the former "Los Santos Customs" shop in Paleto Bay, to a functional mechanic shop.

**Reason:**
Paleto Bay is having more and more activity now that whitelisted groups are extending territory to outside of the main city of Los Santos. Currently, there are 4 mechanic shops. 3 of those are within the boundaries of the main city, and 1 being situated towards Sandy Shores. There is no mechanic shop past Sandy Shores.
As there are gangs now pushing up North, it would be really helpful to organisations and just the general pass-by if there was somewhere in which vehicles can be maintained.

Having this, would also enable those that have storylines being played up North rather than in the city to have an area which their vehicles can be serviced. This also brings more roleplay to be played up North, whether that be mechanical based, car show/racing based, etc.

Location of where the mechanic shop would in correspondence to Paleto Bay: https://imgur.com/a/QMdy4xC
The store front: https://imgur.com/a/w2MMa33
Video of the pre-existing interior (identical to Lost MC shop): https://www.youtube.com/watch?v=UpPyu-NEYNs

**Comment by LikeConnorr** [comment]
Huge +1, will be the entire story line of this group- am excited to see what it will bring.

**Comment by mavroses** [comment]
**Huuugeee +111**

**Comment by z-Lunar** [comment]
in turn removing Grove street? ;)

**Comment by AdeptCL** [comment]
I personally would say:
- Remove Grove Street. 
- Add Benny’s into a repair shop.
- Remove the small shop in Sandy (or add ability to buy materials).
- If removed, add the shop into another building in Sandy (I think there’s a garage somewhere).

**Comment by z-Lunar** [comment]
> I personally would say:
> 
> * Remove Grove Street.
> * Add Benny’s into a repair shop.
> * Remove the small shop in Sandy (or add ability to buy materials).
> * If removed, add the shop into another building in Sandy (I think there’s a garage somewhere).

my goal with removing a repair shop is the prevention of avoiding RP/Interaction with someone :)

**Comment by DaxterPancake** [comment]
Due to Paleto having a mechanic now, I will be closing this issue.

Thank you,
Daxter.
**Project Manager.**
