### ISSUE TITLE
[jobs/mechanic] Car Repair still teleports cars/makes them invisible.

### ISSUE THREAD

**Issue by b-hess** [InZidiuZ/op-framework-issue-tracker#965]
Reporter:
Nohbob#1028, https://steamcommunity.com/id/nohbob/

**Summary:**
When repairing cars at any of the mechanic shops, cars are still teleporting and/or disappearing. Sometimes they just no longer render for some players, sometimes they teleport to a different location (for the Lost MC it can be the roof, for other locations, the docks)

**Steps to Reproduce:**
Please note, this will not happen 100% of the time, but happens enough in gameplay that it makes using shops frustrating at best.
1. Damage a car
2. Bring it into repair location
3. Have a mechanic do a repair
4. From time to time, the vehicle when repaired will teleport into the air and land on the roof (or to a different location)

**Expected Results:**
The vehicle would not teleport to different location, or no longer render. 

**Actual Results:**
The vehicle sometime teleports and lands on the roof or teleports to a different location.

## Additional Information

**Screenshots:**
Will take additional footage from in-game. 

Game Resolution:
2560 x 1440

Player Data:
Character ID - 11 - Job Data: Mechainc, Los Santos Customs, Tow Driver

Server:
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Notes:**
For anything else noteworthy.

**Comment by LostAI** [comment]
As someone that does mechanic for a job and has repaired many vehicles, this is one of the biggest setbacks. Might be out of reach to be fixed as it is most likely a thing with OneSync but maybe something can be added to counter this?

**Comment by InZidiuZ** [comment]
Hey,

Some changes to how repairs are applied has been made in 2.4.6. See if this is still a constant issue once the update has been pushed.

**Comment by InZidiuZ** [comment]
Any feedback on whether this was improved or not?

**Comment by b-hess** [comment]
So it no longer lands on the roof.  So the teleporting problem seems to be fixed.  

There is still visibility issues (from putting on Doors), but that might be a separate issue.

**Comment by Masik52** [comment]
It seems like the repairs aren’t always syncing for everyone. So if a mechanic puts in missing windows for a customer we see the repair they do not. So we have to give them glass and rubber (the same is happening for tires as well) for them to make the window or tire and install themselves. At times once they get back in the vehicle all the glass that was just put in will magically break or the tire will pop as soon as they start driving.

**Comment by InZidiuZ** [comment]
#1012, closing this too
