### ISSUE TITLE
[drugs/oxy] Oxy Rework

### ISSUE THREAD

**Issue by mavroses** [InZidiuZ/op-framework-issue-tracker#968]
**Name:**
MAVROSES#0402 (once again)

**Summary:**
I and most of the community think that the oxy pills (which you get from doing oxy runs) are not worth it at the moment (and have basically no proper use), and we think that it would be better if oxy had some sort of regen healing effect, maybe like 25/100 health in like 10 seconds or something once used and of course the current effect of removing minor injuries.

**Reason:**
Because it's hard to make money as it is doing illegal things, atm there are only banks and drugs (+ gun runs but those can only be done by the cartel and selected gangs), also cocaine is only being done by the red mafia since they don't let anyone else do it.

So increasing the value and usability of oxy I think would bring more business up north and help the economy in the long run since there will be a hot new drug that people will be buying and selling on the streets.

This would also give the police a reason to sometimes visit the north side of the map.

**Comment by InZidiuZ** [comment]
With version 2.7, oxy has been buffed to also give +20 health and stop all bleeding.
