### ISSUE TITLE
[vehicles/belt] Able to get out of car with belt on

### ISSUE THREAD

**Issue by Guardian3-1** [InZidiuZ/op-framework-issue-tracker#969]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GuArDiAn#0031
**Summary:**
Write a short summary of what you're experiencing.
So when you wear a belt and the vehicle is stationary if you press f you exit the vehicle even when the belt in on.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
Take any vehicle put the seatbelt on make sure vehicle is stationary and press f.
**Expected Results:**
What are the expected results?
The player should not exit vehicle when the belt in on.
**Actual Results:**
What are the actual results?
player exits the vehicle
## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920x 1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://imgur.com/a/ExtLuDR
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
IndiaWL
**Notes:**
For anything else noteworthy.
https://youtu.be/gzz85Tl0Q6A

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
