### ISSUE TITLE
[vehicles/helicopters] Heavy Sniper in helicopter bug

### ISSUE THREAD

**Issue by Guardian3-1** [InZidiuZ/op-framework-issue-tracker#970]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
GuArDiAn#0031
**Summary:**
Write a short summary of what you're experiencing.
When you take any helicopter medevac or police or helicopter in airport and sit in the back and right click you get a heavy sniper as a glitch which can be used 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
 take any helicopter medevac or police or helicopter in airport and sit in the back and right click you get a heavy sniper 
**Expected Results:**
What are the expected results?
You should not get a heavy sniper in helicopter 
**Actual Results:**
What are the actual results?
You get a working heavy sniper
## Additional Information
https://imgur.com/a/u81Xgy6
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1920X1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
https://imgur.com/a/ExtLuDR
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
IndiaWL
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
