### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by aanaydixit644** [InZidiuZ/op-framework-issue-tracker#971]
No one is able to put things in trunk beacause trunk is not opening jn normal server of legacy roleplay .....

**Comment by DaxterPancake** [comment]
Hi!

Due to you not using the bug report template, I am closing this issue.

Please refer to [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose), choose bug report and fill in all sections with as much detail as you can.

Thank you,
**Daxter.
Project Manager.**
