### ISSUE TITLE
hospital bug, when i entered the hospital I fell in the underground train tracks and died. I was waiting for respawn and I had my treatment, then after the treatment i again fell in the underground train tracks and died. i was also mugged and all my things vanished from my inventory. Please do something about this issue. 

### ISSUE THREAD

**Issue by theDCgaming** [InZidiuZ/op-framework-issue-tracker#972]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Create another report using the template correctly.

**InZidiuZ**
*OP-FW Developer*
