### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Boutton** [InZidiuZ/op-framework-issue-tracker#973]
Name: Boutton#7433

Summary:I would like to recommend the new 2020 ford explorer for PD and also maybe a suburban kinda like the one in the exclusive dealership.

Reason:It would just be good to have a new model for the explorer and suburban can just be a good addition to the city.

**Comment by DaxterPancake** [comment]
Hi,

This is the wrong place for this.
Please go [HERE](https://github.com/InZidiuZ/legacy-assets-issue-tracker/issues) and post your suggestion.

Thanks,
**Daxter.
Project Manager.**
