### ISSUE TITLE
[subdivison/india] Falling through hospital

### ISSUE THREAD

**Issue by theDCgaming** [InZidiuZ/op-framework-issue-tracker#975]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Discord: DCgaming#3239, Steam: devlakshay77  
**Summary:**
Write a short summary of what you're experiencing.
i was going to the hospital and when i entered it, the hospital vanished and i fell in the underground railway tracks and died. Then i was waitind to respawn and after the treatent i again fell in the same place. Also i was mugged somehow and all my things from inventory are lost.
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
walk into the hospital
**Expected Results:**
What are the expected results?
You enter the hospital lobby
**Actual Results:**
What are the actual results?
I am falling in the underground railway tracks and dieing again and again.
## Additional Information
I am falling and dieing again and again and being charged for the treatment. I cannot move, it is like a loop going on.
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?
1080p 
**Player Data:**
Write /info whilst ingame and provide the information you're given.
Character ID - 1681 
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Legacy Roleplay India
**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

* Upgrade your potato.
* Clear your cache.
* Don't have a billion applications running in the background.
* Be on the latest drivers with windows 10.

**InZidiuZ**
*OP-FW Developer*
