### ISSUE TITLE
[game/gunstores] Free gun bug

### ISSUE THREAD

**Issue by GamingZone01** [InZidiuZ/op-framework-issue-tracker#976]
**Reporter:**
Gaming Zone#9193 and https://steamcommunity.com/id/subha0109/

**Summary:**
People can take pd guns easily without loosing money by dragging it on use. The gun gets equipped, but it doesn't comes on inventory. Everyone can buy ammo from the gun stores, they can get the gun from the pd and use it easily.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
it should not get equipped, when it gets drag from the store inventory

**Actual Results:**
it get's equipped, when it get's drag from the store inventory

## Additional Information
same problem happening with the every gun store
**Screenshots:**
https://imgur.com/780RFhn
**Game Resolution:**
1600x900
**Player Data:**
character id 199
**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Bangladesh
**Notes:**
Video Link - https://youtu.be/e1ESvLzFrss
There is no armory & private locker at Paleto bay PD & Sandy Shore PD, please add it in there.

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
