### ISSUE TITLE
Bug Report - Locals

### ISSUE THREAD

**Issue by DCS281** [InZidiuZ/op-framework-issue-tracker#978]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
DCS #9532, https://steamcommunity.com/id/dcs_281/
**Summary:**
Write a short summary of what you're experiencing.
Some of my income on one of my characters includes the use of locals, I have noticed since the server upgrading to 1024 slots, no locals are "spawning" in around Forum Dr, Grove St, (You Know What I Mean).  This is my first time doing this so I might not do the correct things on this "report"
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?
Locals constantly "spawning" just like before the upgrade to the server happened.
**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.

**Notes:**
For anything else noteworthy.

**Comment by mavroses** [comment]
A known bug already I think, same with cocaine etc.

**Comment by DCS281** [comment]
Thats what I thought, I think all around Locals are kinda messed up. I have seen local cars drive straight into buildings. Im sure they can fix it

**Comment by InZidiuZ** [comment]
Hey,

This will be a 1s infinity issue, and not something that can be resolved on our end. A temporary workaround would be to change the way selling works. Though some ideas have already been planned, I'd recommend creating a suggestion if you have any propositions.

**InZidiuZ**
*OP-FW Developer*
