### ISSUE TITLE
House Raid Function

### ISSUE THREAD

**Issue by Clorox54** [InZidiuZ/op-framework-issue-tracker#980]
**Name:**
Clorox#8063

**Summary:**
Some sort of function that allows the police to breach/raid a players house (only allow use to higher ranks in PD)

**Reason:**
As it stands right now, in order to raid a players house using a search warrant, you must first track down and arrest the player that owns the house, then force them to give the keys to you using /comp. This whole process is very difficult to do and detracts from the RP for the SWAT/FIB folks who put a lot of work into these house raids. The ability to use this breach or raid function, should be reserved for the upper ranks of PD and be logged, so that if abused the user can easily be punished.

**Comment by ABOW402** [comment]
fire suggestion

**Comment by mavroses** [comment]
very much needed.

**Comment by ZurxeyH** [comment]
great for roleplay.

**Comment by selb97** [comment]
yes.

**Comment by FossiiLs** [comment]
For the love of god BEN, implement this please!!!!!!!!!

**Comment by InZidiuZ** [comment]
Before creating an issue, use the search function to ensure what you're suggesting, isn't already suggested.

#780
