### ISSUE TITLE
[jobs/mechanic] Los Santos Customs only useable by mechanics

### ISSUE THREAD

**Issue by KingRich-TLFRP** [InZidiuZ/op-framework-issue-tracker#981]
**Name:** 
KingRich#0001

**Summary:**
Put all the los santos customs accessible only to mechanics, so players will have to go to the tuners to have their vehicles modified.

**Reason:**
This modification would be an excellent implementation, to create very intense roleplay scenes, and to give more work to the mechanics and the tuners.

**Comment by KingRich-TLFRP** [comment]
> **Name:**
> @kingrich#1
> 
> **Summary:**
> Put all the los santos customs accessible only to mechanics, so players will have to go to the tuners to have their vehicles modified.
> 
> **Reason:**
> This modification would be an excellent implementation, to create very intense roleplay scenes, and to give more work to the mechanics and the tuners.

**Comment by DexterMad** [comment]
It's really useful

**Comment by Lunar929292** [comment]
a similar thing has been suggested in the past as well as many other things like it. I don't see it happening but that's my view.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
