### ISSUE TITLE
[subdivision/india] Missing Items

### ISSUE THREAD

**Issue by vishalkumar456** [InZidiuZ/op-framework-issue-tracker#982]
**Reporter:**
discord: H¥DRA丨VISH#5237
Steam name: vishal kumar
steam url: http://steamcommunity.com/id/vishalkumar456

**Summary:**
when ever i come to any legacy server some of my items are missing one time i had no items in my ineventory

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
no items missing

**Actual Results:**
items missing 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1600x900

**Player Data:**
character id: 8295
job-data: government waste collector,employee

**Server:**
india

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

Use the template correctly. This doesn't provide a lot of information...

**InZidiuZ**
*OP-FW Developer*
