### ISSUE TITLE
Bug report - not seeing cars

### ISSUE THREAD

**Issue by AshtonNiddle** [InZidiuZ/op-framework-issue-tracker#983]
**Reporter:**
Ashton#2520          https://steamcommunity.com/profiles/76561198354688905/

**Summary:**
when i pull my willard faction custom out some people can and cant see it sometime people can see it if i pull it out next to someone 

**Steps to Reproduce:**
pull a willard custom out of garage (not sure if other cars do the same) and drive around people will drive through you like your not there.

**Expected Results:**
car will be destroyed slowly ruining your bank account

**Actual Results:**
What are the actual results?

**Game Resolution:**
1920x 1080

**Player Data:**
ID: 6114 2020/04/19 01:51:33

**Server:**
NA/EU server 1 with 256 player slots

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Hi, 

Unfortunately this is is a OneSync issue.
Until OneSync is more stable it's something everyone has to deal with.

Thanks,
**Daxter.
Project Manager.**
