### ISSUE TITLE
[jobs/police] Changes to the PD Armory

### ISSUE THREAD

**Issue by JepsonHepson** [InZidiuZ/op-framework-issue-tracker#984]
**Name:**
@Jepson#1379

**Summary:**
Combat pistol to be changed to a Pistol mk2
(and / or) The pistol model receiving a flashlight attachment.

Attachments for SMG and normal Carbine. I just want a flashlight. Flashlights are cool.

SWAT AR. The people in SWAT and SWAT **only** should have access to a specialized Carbine rifle.
I suggest a Carbine Mk2 with spicy attachments.

**Reason:**
As for the pistol we try to preach to use pistols vs pistols and with previously being able to use Heavy Pistols now we are in a even bigger disadvantage. Now with a combat pistol against a normal pistol it's a fair fight. Against a Pistol .50, a Revolver or a Heavy, it's a very unfair fight. It's not about cops having the best pistol on the market, it's about having an average and more fair pistol. It would help us deal with situations in a better way and we don't have to resort to SMG's or similar to stand a chance in a one on one pistol fight. 

As for the SWAT Rifle. With the original rifle we have strict guidelines, in total it takes a bit over an hour to become certified per person. If it's abused we deal with it with severe punishments. People know not to abuse it. And now with SWAT having access to the same rifle as the rest of PD, it doesn't make them stand out. SWAT should be an elite tactical unit that have a heavy presence at a scene. They are after the fact called "Special Weapons and Tactics" and right now they're missing their special weapon(s). If this were to be implemented there would be heavy restrictions like there is with the current rifle.

**Comment by Max-House** [comment]
+1
Like Jepson mentions, it's not about us being overpowered against crim weapons, but actually standing a chance. With the VERY limited weaponry and extremely high recoil/low damage we have on our rifles, we do currently not stand a chance against it, and we are not a threat at all to a group of criminals with revolvers/rifles with next to no recoil and extremely high damage. We just want to be able to stand a chance.

**Comment by AverageStatistic** [comment]
Just checking in, over a month later from when this thread was touched last, I just want to say, it would be awesome for there to be attachments that we could purchase in the armory and equip to our weapons. The flashlight, for pistols, and/or scopes for SMG's and Carbine Rifles.

**Comment by Doughnut2001** [comment]
yeah, everyone would like to see this in the near future, it's a shame it hasn't been looked at much 
:C

**Comment by mavroses** [comment]
This is very much needed but I have low hopes.

**Comment by devesh180** [comment]
Yes +1

**Comment by its-Frost** [comment]
fat +1

**Comment by twooot** [comment]
We have a bunch of epic addon guns now so this is considered done
