### ISSUE TITLE
[subdivison/india] Infinite loading screen entering house

### ISSUE THREAD

**Issue by NinadWalke** [InZidiuZ/op-framework-issue-tracker#989]
**Reporter:**
My Name is Ninad Walke (IGN:- Walky) from India. My steam link:- https://steamcommunity.com/profiles/76561198819646262/

**Summary:**
The issue I am getting is,  as soon as I enter any owned property, it just keeps on loading and loading and loading. It never ends. It is so annoying especially when there are queues in the server. I just enter a house owned by me and it keeps just loading forever.

**Steps to Reproduce:**
Just own a Random property. Go to a distant place. Suppose I own a property at Forum Drive. So go towards Sandy Shores and come back in a vehicle at very high speed (Suppose 120 mph.) Stop outside Forum Drive and go inside your house as quick as possible. It would just keep loading on and on without letting you in the house.

**Expected Results:**
I should get into the house and the black screen should disappear.

**Actual Results:**
I get a black screen with the loading icon on the bottom right. I never load into the house I always have to quit fivem through the console.

## Additional Information

**Screenshots:**
Due to my low-end PC, If I get a screenshot then my Fivem would crash. Sorry about that.

**Game Resolution:**
Windowed Fullscreen, 1920 X 1080

**Player Data:**
Name:- Walky Wilson
Character ID:- 625
Job- Garbage Collector.

**Server:**
India (Whitelist).

**Notes:**
For anything else noteworthy.

**Comment by DaxterPancake** [comment]
Hi,

Have you cleared your cache? I have had this happen to me quite a few times and all I had to do was clear my cache file. 
Please give it a try and if it doesn't work, let us know.

Thanks!
**Daxter,
Project Manager.**

**Comment by InZidiuZ** [comment]
Hey,

Sounds more like a you and/or cache/download issue. I'm not able to assist much here.

**InZidiuZ**
*OP-FW Developer*
