### ISSUE TITLE
[subdivision/india] Unable to access trunk sometimes

### ISSUE THREAD

**Issue by Torpedo02** [InZidiuZ/op-framework-issue-tracker#990]
**Reporter:**
"TORPEDO"
#8054
STEAM-https://steamcommunity.com/profiles/76561198840725668/
**Summary:**
i cant access my cars trunk sometimes and even if the cars spawn area is clear it still says "Vehicle blocking the spawn area"...my blue decryption key got replaced by green one....

**Steps to Reproduce:**
BUY A TAXI
SAVE IT IN THE GARAGE
ACCESS IT 2-3 times
AFTER THAT IT DOSENT WORK ANYMORE
**Expected Results:**
OPEN CARS TRUNK

**Actual Results:**
NOTHING HAPPENS STANDING THERE LIKE A FOOL 

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
What server/community are you from? LEGACY INDIA BLACKLIST

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Hey,

This issue was resolved in a later version not yet available in the Indian servers.

**InZidiuZ**
*OP-FW Developer*
