### ISSUE TITLE
[subdivision/india] Unable to lock or unlock vehicle 

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#992]
**Reporter:**
RitikBakshi#4798 https://steamcommunity.com/id/sutta69/

**Summary:**
When i try to press L and lock vehicle it just doesn’t work

**Steps to Reproduce:**
Go near vehicle you have key of then press L but nothing happens.

**Expected Results:**
By pressing L the vehicle should lock or unlock

**Actual Results:*
Nothing happens by pressing L

**Game Resolution:**
1920*1080

**Player Data:**
RitikBakshi 
Character id:-4085.

**Server**.
India

**Comment by InZidiuZ** [comment]
Hey,

Closing due to the template not being properly filled out, no repro & me not being able to do much when I don't know what the issue even is.

**InZidiuZ**
*OP-FW Developer*
