### ISSUE TITLE
[Vehicle/Garages] In garage it shows there is vehicle blocking spawn point, when there is no vehicle

### ISSUE THREAD

**Issue by hooman2101** [InZidiuZ/op-framework-issue-tracker#994]
Discord ID: hooman2101
Steam ID: https://steamcommunity.com/profiles/76561198061929037/

**Summary:**
I am not able to take out my vehicle out of garage it says vehicle spawn point i tried different garages as well still same issue is happening. I am just here to learn RP and do not have technical knowledge so cant give any mre details of the following

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
https://paste.pics/f55b7c9ee0fcd95320d71ba4ced6b4cd
![Scr 1](https://user-images.githubusercontent.com/64156406/80010515-24a08480-84e8-11ea-9435-cecfeed095f8.jpg)

**Game Resolution:**
1920*1080

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
India

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Will close this as it's missing parts of the template, and I'm also not able to do much with this. If this happens again, make sure you get a screenshot of the actual notification/message you're given. Also check if there are vehicles nearby (above as well).

**InZidiuZ**
*OP-FW Developer*
