### ISSUE TITLE
[vehicles/vehicles] Manual cars

### ISSUE THREAD

**Issue by RitikBakshi** [InZidiuZ/op-framework-issue-tracker#995]
**Name:**
RitikBakshi#4798.

**Summary:**
Adding (optional) manual transmission in vehicles.

**Reason:**
Manual transmission would be a great idea for bringing out the realistic things in the game which would make it more interesting and also it will provide great control over vehicle

**Comment by Doughnut2001** [comment]
def a +1 could help the drifting mechanic making you able to hold a shift for wheelspin

**Comment by InZidiuZ** [comment]
Could anyone further explain what "manual transmission" means? 😄

**Comment by Masik52** [comment]
Manual transmission means you’d have a muscle to shift gears.  Currently all the vehicles are an automatic transmission so the gear shifts automatically as the engine begins to get closer to red lining thus allowing you to continue to accelerate.

**Comment by InZidiuZ** [comment]
Ah! I could probably make something like that happen, probably with SHIFT & CTRL as these two are natively used to control the vehicle in-air, but as that's removed for us, we can put them to use for gears instead I suppose.

Should this also be a toggle? Or should it be required for certain vehicles? I don't want to force players to use this, so it'd be one of the two most likely. To me a toggle sounds like the easiest & best solution.

**Comment by Masik52** [comment]
If it was done I’d say a toggle but imo if someone fucks up and downshifts while going at a rate of speed beyond the threshold of the gear they are in the engine should receive some significant damage etc

**Comment by InZidiuZ** [comment]
I'll see what I can get done once I have some time 😄

**Comment by InZidiuZ** [comment]
This has now been added, though I didn't add any form for engine damage when gears are improperly set as I'm not quite sure what the best way of determining when and how much damage should be applied, @Masik52..
