### ISSUE TITLE
[illegal/burglaries] Add more to house robberies

### ISSUE THREAD

**Issue by JC-5** [InZidiuZ/op-framework-issue-tracker#996]
**Name:**
Who is suggesting this? Please include discord name.
J.C.
**Summary:**
Write a short summary of what your suggestion is about.
Adding safes and watches to house robberies.
**Reason:**
Why would your suggestion be a good addition to Legacy?
As of right now keys used to be found by doing the house robberies now that they can also be found diving, In my opinion it would be a welcomed change to add at least safes to house robberies and require them to use the normal lock pick. If the safes contained anywhere from 200-500 dollars it wouldn’t break the economy as long as the safes are somewhat rare maybe a 10 percent chance to find one and maybe only in the mansions. I think then the watches could be found either everywhere or the lower end interiors. I think the watches would be a good edition obviously for profit and hopefully it would require a pawnshop and runs to deliver the watches (I know it’s not really realistic but it adds something else to do) Gangs could also tax the pawn shop and give them something to claim as well. Mainly this isn’t to make people rich but add more stuff to do to keep people moving around the city and creating more situations.

**Comment by InZidiuZ** [comment]
Closing as outdated. If this is still relevant, please create a new issue.
