### ISSUE TITLE
[vehicles/garages]  In garage it shows there is vehicle blocking spawn point, when there is no vehicle 

### ISSUE THREAD

**Issue by hooman2101** [InZidiuZ/op-framework-issue-tracker#997]
Discord ID: hooman2101
Steam profile: https://steamcommunity.com/profiles/76561198061929037/

**Summary:**
This is in continuation to Thread no 994, i have raised request earlier of a bug, i tried taking screenshot from all the the angles to show that there are no vehicles nearby. Still it shows same message alongwith F8 Screenshot as well.

if you need anything more kindly let me know will try the same. Please do not close the request, give time to reply on same thread, so that it can be solved.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
![New Scr 1](https://user-images.githubusercontent.com/64156406/80125782-c17a2500-85af-11ea-9ac8-c6ed0edc27ef.jpg)
![New Scr 2](https://user-images.githubusercontent.com/64156406/80125784-c343e880-85af-11ea-9c24-50548a36386a.jpg)
![New Scr 3](https://user-images.githubusercontent.com/64156406/80125789-c4751580-85af-11ea-9a50-13985030e30f.jpg)
![New Scr 4](https://user-images.githubusercontent.com/64156406/80125793-c63ed900-85af-11ea-8dd3-2371cada4359.jpg)
![New Scr 5](https://user-images.githubusercontent.com/64156406/80125804-c8a13300-85af-11ea-8d82-696a91213a60.jpg)

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Server:**
India Legacy Server

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Very strange... was this after a game/server restart from the previous issue? Also, the first time you tried taking the vehicle out at a garage, did it show the same message then?

**Comment by hooman2101** [comment]
This is after the big update which had came I can take vehicle out sometimes but from last 1 2 week m not able to take out vehicle only.

Yes if I don't do any activity after coming to city and I go direct to garage c vehicle comes out and if store the vehicle I cannot take it out again. It's like I cannot once when I come so most of time if I have to store things I have quit fivem completely and start again 

Hope this helps to close this issue

**Comment by InZidiuZ** [comment]
Try clearing cache (or reinstalling your game if cache doesn't work) and verify your game files.

**Comment by hooman2101** [comment]
HI i tried both still having same problem, is it because i bought 2 rumpo vans as 1 rumpo van is parked in garage I, when i have gone there it was showing me to go to garage I when i was already in garage I .

As i was able to take out taxi in garage H, but once i tried taking out rumpo van in garage I, i was not able to take out any vehicle

**Comment by 8grey8** [comment]
i am also have same issue maybe its happening because of gta vehicle collision

**Comment by InZidiuZ** [comment]
If this is an issue in 2.5, please create another issue.
