### ISSUE TITLE
#Bugs faced in normal Indian server

### ISSUE THREAD

**Issue by praveenprk25** [InZidiuZ/op-framework-issue-tracker#998]
**Praveenprk25:**
@Praveenprk25#9757

**Summary:**
/Givekey , /trunk , siren of police vehicles , putting someone in trunk in bugged in normal server (india)

**Steps to Reproduce:**
Press /trunk and put carried person in trunk , he will be tp to EDM. /Givekey gives error. Turning on code 3 in police vehicle

**Expected Results:**
Everything should work good as it meant to be.

*Server:**
India normal server

**Comment by InZidiuZ** [comment]
Hey,

Use the template properly. Only create one issue per bug. Some of the noted issues has already been resolved in a later version not yet available in your server.

**InZidiuZ**
*OP-FW Developer*
