### ISSUE TITLE
[vehicle/garage] Garage H & I in same place

### ISSUE THREAD

**Issue by LostAI** [InZidiuZ/op-framework-issue-tracker#999]
**Reporter:**
Who is reporting this? Please include discord name and your steam profile.
Discord Name: Lost#8366
Steam Profile: https://steamcommunity.com/id/20040110/

**Summary:**
Write a short summary of what you're experiencing.
Garage H and Garage I are located in the same place. On the map and when you go to the location. If you go to Garage H you will notice sometimes you might open Garage I which is because it's at the same location.

**Steps to Reproduce:**
Include what steps are needed in order to reproduce the issue.
Open your map
Go to Garage H
Go to Garage I
Notice they are at the same location.

**Expected Results:**
What are the expected results?
Only one garage is supposed to be shown.

**Actual Results:**
What are the actual results?
Two garages are shown at the same location.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
https://prnt.sc/s5futf
https://prnt.sc/s5fuzc
Console: https://prnt.sc/s5fx6l

**Game Resolution:**
What is your game's resolution?
1080x1920

**Player Data:**
Write /info whilst ingame and provide the information you're given.
2212 | Mechanic

**Server:**
What server/community are you from? Main, India, Bangladesh, etc.
Main

**Notes:**
For anything else noteworthy.
N/A

**Comment by InZidiuZ** [comment]
Hey,

This issue has now been resolved.

**InZidiuZ**
*OP-FW Developer*
